### ISSUE TITLE
BUG: linalg: `test_decomp_update` fail

### ISSUE THREAD

**Issue by yajiedesign** [scipy/scipy#5117] opened 2015-08-06 12:45 UTC
win10 x64 python3.6.0a0 amd64  
numpy master:9cd868a00cc488478ac4f07ee0b5452a38cb3cc0  
scipy  master:89066e8b5eea5ce638b95cd6a94013102495e39a
mkl 2015 
# 

FAIL: test_decomp_update.TestQRdelete_D.test_delete_last_p_col

Traceback (most recent call last):
  File "E:\pyjq\cpython\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "E:\pyjq\cpython\lib\site-packages\scipy\linalg\tests\test_decomp_update.py", line 328, in test_delete_last_p_col
    assert_unitary(q1)
  File "E:\pyjq\cpython\lib\site-packages\scipy\linalg\tests\test_decomp_update.py", line 21, in assert_unitary
    assert_allclose(aTa, np.eye(a.shape[1]), rtol=rtol, atol=atol)
  File "E:\pyjq\cpython\lib\site-packages\numpy\testing\utils.py", line 1347, in assert_allclose
    verbose=verbose, header=header)
  File "E:\pyjq\cpython\lib\site-packages\numpy\testing\utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-13, atol=4.44089e-16

(mismatch 1.3888888888888857%)
 x: array([[  1.000000e+00 +0.000000e+00j,   3.816392e-17 +5.898060e-17j,
          4.163336e-17 +2.775558e-17j,   1.387779e-17 +2.775558e-17j,
          6.938894e-17 -6.245005e-17j,   3.469447e-17 -2.341877e-17j,...
 y: array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],...

---

**Comment by ewmoore** [comment] 2015-08-06 14:08
This looks like it is probably okay, but the test tolerance is too tight.  @yajiedesign, could you rerun the tests after changing line 328 of scipy/linalg/tests/test_decomp_update.py  to be 
```
assert_unitary(q1, rtol=1e-13, atol=1e-14)
```
If that doesn't fix things, could you please try changing the atol value too see what tolerance it would take to pass?

**Comment by yajiedesign** [comment] 2015-08-07 13:49
when i change 328 to assert_unitary(q1,1e-5,1e-6) ,it not fail

**Comment by rgommers** [comment] 2015-10-13 20:17
Hmm, not sure what to do with this one. Going from ``2 * eps`` to 1e-5 doesn't sound like a simple case of test tolerance a bit too tight. The mismatch of 1.38% means that exactly 2 values (it's an array of shape ``(12,12)``) are way off.

**Comment by rgommers** [comment] 2015-10-13 20:20
MKL 2015 probably hasn't been exercised a lot yet (and neither has Python 3.6.0a0, but that's probably less relevant).

**Comment by rgommers** [comment] 2015-10-13 20:21
Removing the 0.16.1 milestone; this is not a must-have.

**Comment by ev-br** [comment] 2024-03-10 12:03
Both this and gh-10550 seem to have a slight tolerance issue. 
https://github.com/scipy/scipy/blob/main/scipy/linalg/tests/test_decomp_update.py#L14 sets 

```
    if atol is None:
        atol = 10*np.finfo(a.dtype).eps
```

which is too tight, at least on a MacOS with some linalg backends. 

- we do not see it in our regular CI, incl MacOS
- the last time it was seen was in 2019 (gh-10550)
- the tolerance violations look minor both here and in gh-10550 (over there with float32/complex64 arrays: 3.6e-7 vs atol=2.4e-7; in here "mismatch 1.3888888888888857%", so the bump in https://github.com/scipy/scipy/issues/5117#issuecomment-128703596 is likely an overshot)

I suggest we close both this and gh-10550, possibly bumping the atol to 20 eps or some such. Thoughts?
cc @tylerjereddy who participated in the linked issue, @ilayn as the linalg regular

**Comment by mdhaber** [comment] 2024-08-22 07:30
@ev-br I agree. I wrote up a detailed history of this issue in gh-21432, which would bump the tolerance as you suggest, but I suspect we can just close it and this issue. (I closed the other duplcates tonight.) 

Before closing this one, I'd just like to confirm that @andyfaff is no longer able to reproduce the failure (he filed gh-10716), and I'd like to see if @h-vetinari can provide more information about it (reported in gh-19210).

**Comment by h-vetinari** [comment] 2024-08-22 07:57
> I'd like to see if @h-vetinari can provide more information about it (reported in [gh-19210](https://github.com/scipy/scipy/issues/19210)).

I'm unsure if this is related. The failures in #19210 are catastrophically wrong, not a simple tolerance violation. To my understanding they also only happen in emulation, not on native hardware (which makes it likely that the bug is in the emulation layer itself). However, I have no native hardware to test (and neither does conda-forge), so I've been taking that item on good faith.

**Comment by mdhaber** [comment] 2024-08-28 00:46
OK, I'll go ahead and close this. If the problems are related, then we'll conisder gh-19210 to supersede this issue; if they aren't, I agree with https://github.com/scipy/scipy/issues/5117#issuecomment-1987202802 that this doesn't appear to be a problem anymore.

**Closed by mdhaber** 2024-08-28 00:46 UTC
Labels: defect, scipy.linalg
