### ISSUE TITLE
Apparently issue on mahalanobis distance calculation while using pdist

### ISSUE THREAD

**Issue by AlexandreBouyssoux** [scipy/scipy#8801] opened 2018-05-04 13:44 UTC
I wanted to compute mahalanobis distance between two vectors, with a known distribution Variance-Covariance Matrix inverse named VI.

I have compared the results given by:
 - dist0 = scipy.spatial.distance.mahalanobis(array1, array2, VI)
 - dist1 = scipy.spatial.distance.pdist(m, metric="mahalanobis", VI=VI)
with m = [[array1], [array2]]
 - dist2 = scipy.spatial.distance.mahalanobis(m[0], m[1], VI)
 - dist3 = manual implementation of mahalanobis distance

All the 4 distances should be equal, nevertheless dist1 is the only one different from the others.

### Reproducing code example:

```
import numpy as np
import scipy.spatial.distance as scipy_distance
import pickle

def computeMahalanobisDistance(array1, array2, vi):
    x = np.copy(array1)
    y = np.copy(array2)
    # force vectors to be column
    x.shape = (len(x), 1)
    y.shape = (len(y), 1)
    m = np.concatenate((x, y), axis=1)
    m = np.transpose(m)

    scipyDist = scipy_distance.pdist(m, metric="mahalanobis", VI=vi)
    scipyDist2 = scipy_distance.mahalanobis(array1, array2, vi)
    scipyDist3 = scipy_distance.mahalanobis(m[0], m[1], vi)
    if len(x) != len(y):
        print("error, vector must have the same dimension")
    diffVec = x - y
    temp = np.matmul(np.transpose(diffVec), vi)
    dist = np.sqrt(float(np.matmul(temp, diffVec)))
   
    print("distance", dist)
    print("scipy distance", scipyDist)
    print("scipy distance 2", scipyDist2)
    print("scipy distance 3", scipyDist3)
    return dist


if __name__ == "__main__":
    array1 = pickle.load(open(r"array1.pickle", "rb"))
    array2 = pickle.load(open(r"array2.pickle", "rb"))
    v = pickle.load(open(r"trainPatientCovarianceMatrix.pickle", "rb"))
    vi = np.linalg.inv(v)
    _ = computeMahalanobisDistance(array1, array2, vi)
```

### Error message:
no error message. Output in my terminal is:

distance 11.703891989728923
scipy distance [11.66951974]
scipy distance 2 11.703891989728923
scipy distance 3 11.703891989728923

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```
scipy version: 1.0.0
numpy version: 1.14.2
sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)

[array1.log](https://github.com/scipy/scipy/files/1974609/array1.log)
[array2.log](https://github.com/scipy/scipy/files/1974610/array2.log)
[trainPatientCovarianceMatrix.log](https://github.com/scipy/scipy/files/1974611/trainPatientCovarianceMatrix.log)

**Comment by WarrenWeckesser** [comment] 2018-05-04 17:39
By the way, here's another method to compute the Mahalanobis distance that is mathematically equivalent to those in the script but it also gives a different value:

```
In [85]: delta = array1 - array2

In [86]: y = np.linalg.solve(v, delta)  # Mathematically equiv. to y = inv(v).dot(delta)

In [87]: np.sqrt(delta.dot(y))
Out[87]: 11.710250447675168
```

**Comment by WarrenWeckesser** [comment] 2018-05-05 15:16
Because the problem is in the input (a poorly conditioned covariance matrix), I'm closing this issue.

**Closed by WarrenWeckesser** 2018-05-05 15:16 UTC
Labels: scipy.spatial

**Comment by AlexandreBouyssoux** [comment] 2018-05-07 07:06
Thanks for your answer.
I suspected the problem to come from my ill-posed problem, but i could find nowhere in the documentation why to implementation of Mahalanobis distance in Scipy would give a different solution.
