### ISSUE TITLE
mode for ndimage.filters to exclude pixels outside borders?

### ISSUE THREAD

**Issue by larrybradley** [scipy/scipy#4141] opened 2014-11-12 19:03 UTC
I would like to use the `ndimage.filters` using a boundary `mode` where pixels outside the data borders are simply excluded/ignored.  In this case the filter size would need to be smaller around the borders.  For example, a `3x3` median filter would use only 6 pixels on the data edges and 4 pixels at the corners.   My current workaround is to pad the array with `np.nan` and then use `generic_filter` with functions that ignore `nan` (e.g. `np.nanmedian`).  Is there a better way to do this or is it possible to include such a mode (e.g., `mode = 'exclude'`) to the `ndimage.filters` functions?

EDIT:  A better workaround is to use `generic_filter` with `mode='constant', cval=np.nan` and using functions that ignore `nan`.

**Comment by rgommers** [comment] 2015-04-04 20:20
this is a question not a bug, and workaround is found, so closing.

**Closed by rgommers** 2015-04-04 20:20 UTC
Labels: query, scipy.ndimage
