### ISSUE TITLE
BUG: Preparing metadata (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by webadmin-psychologie** [scipy/scipy#18401] opened 2023-05-02 11:55 UTC
### Describe your issue.

I always (since about three days) get this error when install the package.

### Reproducing Code Example

```python
pip install scipy
```

### Error message

```shell
Using cached scipy-1.10.1.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      The Meson build system
      Version: 1.1.0
      Source dir: /tmp/pip-install-1_lvv1l1/scipy_49f6f8770d974237958632829d776336
      Build dir: /tmp/pip-install-1_lvv1l1/scipy_49f6f8770d974237958632829d776336/.mesonpy-i8u5z56g/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.1
      C compiler for the host machine: cc (gcc 12.2.1 "cc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924")
      C linker for the host machine: cc ld.bfd 2.39
      C++ compiler for the host machine: c++ (gcc 12.2.1 "c++ (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924")
      C++ linker for the host machine: c++ ld.bfd 2.39
      
      ../../meson.build:1:0: ERROR: Cython compiler 'cython' cannot compile programs
      
      A full log can be found at /tmp/pip-install-1_lvv1l1/scipy_49f6f8770d974237958632829d776336/.mesonpy-i8u5z56g/build/meson-logs/meson-log.txt
      + meson setup --prefix=/usr/local /tmp/pip-install-1_lvv1l1/scipy_49f6f8770d974237958632829d776336 /tmp/pip-install-1_lvv1l1/scipy_49f6f8770d974237958632829d776336/.mesonpy-i8u5z56g/build --native-file=/tmp/pip-install-1_lvv1l1/scipy_49f6f8770d974237958632829d776336/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

### SciPy/NumPy/Python version and system information

```shell
scipy-1.10.1
```

**Comment by tupui** [comment] 2023-05-02 14:58
Thank you for reporting @webadmin-psychologie. This is a duplicate of #18390 so closing this one 😃

**Closed by tupui** 2023-05-02 14:58 UTC
Labels: defect, Build issues
