### ISSUE TITLE
I get the following errors when running scipy-0.16.0.dev0+a48063d on Python2.7.6 and Ubuntu

### ISSUE THREAD

**Issue by s0r2637** [scipy/scipy#4644] opened 2015-03-18 01:42 UTC
I get the following errors when running scipy-0.16.0.dev0+a48063d on Python2.7.6 and Ubuntu.  Are these errors serious?  I am using numpy-1.10.0.dev0+c60f1c6 underneath.

======================================================================
ERROR: test_idl.TestPointerStructures.test_arrays_replicated_3d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/tests/test_idl.py", line 382, in test_arrays_replicated_3d
    s = readsav(pth, verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/idl.py", line 821, in readsav
    replace, new = _replace_heap(r['data'], heap)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/idl.py", line 607, in _replace_heap
    for ir, record in enumerate(variable):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 481, in __getitem__
    return obj.view(dtype=(self.dtype.type, obj.dtype.descr))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 540, in view
    return ndarray.view(self, dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 457, in __setattr__
    raise exctype(value)
TypeError: Cannot change data-type for object array.

======================================================================
ERROR: test_idl.TestPointerStructures.test_pointers_replicated_3d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/tests/test_idl.py", line 348, in test_pointers_replicated_3d
    s = readsav(path.join(DATA_PATH, 'struct_pointers_replicated_3d.sav'), verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/idl.py", line 821, in readsav
    replace, new = _replace_heap(r['data'], heap)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/idl.py", line 607, in _replace_heap
    for ir, record in enumerate(variable):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 481, in __getitem__
    return obj.view(dtype=(self.dtype.type, obj.dtype.descr))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 540, in view
    return ndarray.view(self, dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 457, in __setattr__
    raise exctype(value)
TypeError: Cannot change data-type for object array.

======================================================================
ERROR: test_idl.TestStructures.test_arrays_replicated_3d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/tests/test_idl.py", line 232, in test_arrays_replicated_3d
    s = readsav(path.join(DATA_PATH, 'struct_arrays_replicated_3d.sav'), verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/idl.py", line 821, in readsav
    replace, new = _replace_heap(r['data'], heap)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/idl.py", line 607, in _replace_heap
    for ir, record in enumerate(variable):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 481, in __getitem__
    return obj.view(dtype=(self.dtype.type, obj.dtype.descr))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 540, in view
    return ndarray.view(self, dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 457, in __setattr__
    raise exctype(value)
TypeError: Cannot change data-type for object array.

======================================================================
ERROR: test_idl.TestStructures.test_scalars_replicated_3d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/tests/test_idl.py", line 188, in test_scalars_replicated_3d
    s = readsav(path.join(DATA_PATH, 'struct_scalars_replicated_3d.sav'), verbose=False)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/idl.py", line 821, in readsav
    replace, new = _replace_heap(r['data'], heap)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/idl.py", line 607, in _replace_heap
    for ir, record in enumerate(variable):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 481, in __getitem__
    return obj.view(dtype=(self.dtype.type, obj.dtype.descr))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 540, in view
    return ndarray.view(self, dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/records.py", line 457, in __setattr__
    raise exctype(value)
TypeError: Cannot change data-type for object array.

======================================================================
FAIL: test_nanmedian_all_axis (test_stats.TestNanFunc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scipy/stats/tests/test_stats.py", line 218, in test_nanmedian_all_axis
    assert_equal(len(w), 4)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 334, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 1
 DESIRED: 4

----------------------------------------------------------------------
Ran 18401 tests in 245.143s

FAILED (KNOWNFAIL=128, SKIP=1022, errors=4, failures=1)

**Comment by WarrenWeckesser** [comment] 2015-03-18 05:53
The `test_idl` error was also reported here: https://github.com/scipy/scipy/issues/4589

**Comment by rgommers** [comment] 2015-10-24 18:11
The ``test_idl`` errors were due to a numpy regression (now fixed) and the ``nanmedian`` one is also fixed with scipy 0.16.0 + numpy 1.10.1 I believe.

Thanks for the report @s0r2637

**Closed by rgommers** 2015-10-24 18:11 UTC
