### ISSUE TITLE
ENH: Access to objective function value in collback method of differential_evolution algorithm

### ISSUE THREAD

**Issue by r-brivio** [scipy/scipy#15211] opened 2021-12-14 16:00 UTC
### Describe the solution you'd like.

I would like to be able to access the objective function value at each iteration of the differential_evolution algorithm provided in scipy.optimize. This is currently not available in the callback method.

### Describe alternatives you've considered.

I have considered evaluating the function given the parameters value xk (which is available in the callback method). Unfortunately, this means I need to reevaluate the objective function, which in my case is prohibitive because the objective is very expensive to evaluate.

**Comment by tupui** [comment] 2021-12-16 21:47
This is a duplicate of things we are discussing in #15046

**Closed** 2021-12-16 21:47 UTC
Labels: enhancement, scipy.optimize
