### ISSUE TITLE
DOC: `stats.multivariate_normal` has extra backticks on methods

### ISSUE THREAD

**Issue by david-cortes** [scipy/scipy#15510] opened 2022-02-02 17:36 UTC
### Describe your issue.

Docs for `scipy.stats.multivariate_normal` here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multivariate_normal.html

Render the method signatures with two backticks at the beginning and at the end, which they should not have. The docs from other distributions do not have this issue - e.g.: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html

### Reproducing Code Example

```python
-
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

1.7.1

**Comment by mdhaber** [comment] 2022-02-02 17:40
Duplicate of gh-12848, so I'll close this one. There are a lot of issues with multivariate (and even single variable) distribution documentation.

**Closed by mdhaber** 2022-02-02 17:41 UTC
Labels: defect
