### ISSUE TITLE
BUG: scipy.stats.logistic.fit cannot fitting any parameters 

### ISSUE THREAD

**Issue by HZT3434** [scipy/scipy#16204] opened 2022-05-18 06:33 UTC
### Describe your issue.

When I call for logistic.fit(), it returns error say that there is a type error, during the optimzation it occurs None type value.

### Reproducing Code Example

```python
ss.logistic.fit(x)
```

### Error message

```shell
Traceback (most recent call last):
  File "E:\Python\Python3_10\lib\site-packages\numpy\core\getlimits.py", line 459, in __new__
    dtype = numeric.dtype(dtype)
TypeError: 'NoneType' object is not callable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "E:\Python\Python3_10\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-33-05b96b2f6f8c>", line 1, in <cell line: 1>
    ss.logistic.fit(x)
  File "E:\Python\Python3_10\lib\site-packages\scipy\stats\_continuous_distns.py", line 63, in wrapper
    return fun(self, *args, **kwds)
  File "E:\Python\Python3_10\lib\site-packages\scipy\stats\_continuous_distns.py", line 5242, in fit
    return tuple(optimize.root(func, (loc, scale), args=(data,)).x)
  File "E:\Python\Python3_10\lib\site-packages\scipy\optimize\_root.py", line 234, in root
    sol = _root_hybr(fun, x0, args=args, jac=jac, **options)
  File "E:\Python\Python3_10\lib\site-packages\scipy\optimize\_minpack_py.py", line 228, in _root_hybr
    epsfcn = finfo(dtype).eps
  File "E:\Python\Python3_10\lib\site-packages\numpy\core\getlimits.py", line 462, in __new__
    dtype = numeric.dtype(type(dtype))
TypeError: 'NoneType' object is not callable
```

### SciPy/NumPy/Python version information

1.8.0 1.22.3 sys.version_info(major=3, minor=10, micro=3, releaselevel='final', serial=0)

**Comment by tupui** [comment] 2022-05-18 08:40
Hi @HZT3434, thank you for reporting. Can you list a complete reproducible example? What is `x`?

**Comment by HZT3434** [comment] 2022-05-18 09:01
Hi. The data x is a numpy array. When I run my script on python 3.9 the program did not scream for the same error. It can be the python problem. Thanks for the quick respond.




Regards,
Huang










At 2022-05-18 16:40:17, "Pamphile Roy" ***@***.***> wrote:

Hi @HZT3434, thank you for reporting. Can you list a complete reproducible example? What is x?

**Comment by tupui** [comment] 2022-05-18 09:06
I cannot reproduce the issue on Python 3.10 with the latest released version nor the development version.

```python
import scipy.stats as stats
x = stats.logistic.rvs(size=10)
stats.logistic.fit(x)
# (0.6128791075218377, 0.7050674549310291)
```

**Comment by tupui** [comment] 2022-05-18 09:08
Can you give more details about `x`? The dtype, shape, range, etc. could help.

**Comment by HZT3434** [comment] 2022-05-19 02:13
Hi. I have checked the versions and here is the setting for a successful run of my script. I have attached my program.  Dtypes of x is np.float64, range of x is [-0.095893, 0.069124], shape(x) is (749999,).
Hope the info can be useful. Thank you!







Regards,
Huang
















At 2022-05-18 17:08:32, "Pamphile Roy" ***@***.***> wrote:

Can you give more details about x? The dtype, shape, range, etc. could help.

**Comment by HZT3434** [comment] 2022-05-19 02:41
Thank you for the respond. Now I will work with the stable release for the project.


Regards,
Huang
















At 2022-05-19 10:34:29, "Robert Kern" ***@***.***> wrote:

This looks like the problem with all-but-the-latest Cython, Python 3.10, and some kind of debugger or tracer being used (c.f. numpy/numpy#21519)

**Comment by HZT3434** [comment] 2022-05-19 02:45
OK. Thanks!


Regards,
Huang
















At 2022-05-19 10:40:12, "Robert Kern" ***@***.***> wrote:

Nothing to do but wait for the release cycles of numpy (1.22.4 should have the fix) and scipy (don't see anything about it in the 1.8.1 release notes) to churn through with the latest Cython being used. In the meantime, avoid using a debugger.

**Comment by mdhaber** [comment] 2022-05-19 02:48
Does that mean we can close this? 
@HZT3434 is your problem resolved when you are not using a debugger?

**Comment by HZT3434** [comment] 2022-05-19 02:50
Yes, please close it.

Regards,
Huang



---- Replied Message ----
| From | Matt ***@***.***> |
| Date | 05/19/2022 10:48 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [scipy/scipy] BUG: scipy.stats.logistic.fit cannot fitting any parameters (Issue #16204) |

Does that mean we can close this?
@HZT3434 is your problem resolved when you are not using a debugger?

**Closed** 2022-05-19 02:54 UTC
Labels: defect, scipy.stats

**Comment by tupui** [comment] 2022-06-20 12:52
@cartisan we have several jobs in CI using latest Cython and latest (even main branch) NumPy. See https://github.com/scipy/scipy/blob/main/.github/workflows/linux.yml for instance. Can you give more details?

**Comment by cartisan** [comment] 2022-06-20 16:52
@tupui I have been able to zero in the error to the latest pandas version, which apparently is not yet built using the new Cyton.  Sorry for stirring up the old thread!

**Comment by jabowery** [comment] 2022-06-30 20:45
By disabling debugging, this has stopped development here.   Optimization of runtimes while debugging is a far lower priority than is debugging itself.  Why is it so difficult to disable cython's optimization of debugging so we can get on with development?

**Comment by tupui** [comment] 2022-06-30 21:13
@jabowery I don't think I follow what you are trying to say.
