### ISSUE TITLE
Return computation intermediate from LinearNDInterpolator / BarycentricNDInterpolator ?

### ISSUE THREAD

**Issue by Didou09** [scipy/scipy#9221] opened 2018-09-04 16:13 UTC
Hi,

LinearNDInterpolator is very useful, but what if we have a fixed set of points and a series of several sets of values defined on another, also fixed, set of points (e.g. : several thousands of time slices of M values, on the same M points, and we want to interpolate of a fixed set of N points) ?

A for loop on each time slice would require creating a new LinearNDInterpolator  every time.
But since the set of points is fixed and the routine does linear barycentric interpolation, a much more efficient strategy would be to return the ND barycentric interpolation in the form of a sparse (M,N) numpy.array containing the weights associated to each values / point.

This way the barycentric is computed only once (and re-used) instead of at every time slice.

I understand that this would be somewhat like what BarycentricInterpolator does, except in ND instead of just 1D.

Any chance to see something like that in a near future ?

Thanks

**Comment by pv** [comment] 2018-09-04 19:11
LinearNDInterpolator already supports interpolating multiple data values per point, if that it what you mean.

**Comment by Didou09** [comment] 2018-09-10 11:57
Thanks, 
You're right, LinearNDInterpolator already provides enough for me to build what I need, I had not considered it carefully enough, sorry
Best

**Comment by ev-br** [comment] 2018-09-10 17:14
Looks like the issue is resolved, closing.

**Closed by ev-br** 2018-09-10 17:14 UTC
Labels: enhancement, scipy.interpolate
