### ISSUE TITLE
BUG: Scipy stats probability greater than 1

### ISSUE THREAD

**Issue by Scriddie** [scipy/scipy#17146] opened 2022-10-04 14:11 UTC
### Describe your issue.

I am computing values of a binomial probability mass function and find that their sum exceeds 1 when passing extreme parameters to the pmf. [stackoverflow question](https://stackoverflow.com/questions/73949131/scipy-stats-probability-greater-than-1). No error is thrown, meaning the problem could easily go unnoticed.

### Reproducing Code Example

```python
from scipy.stats import binom
n = 1541096362225563.0
p = 1.0477878413173978e-18
vals = [binom.pmf(n=n, p=p, k=i) for i in range(3)]
print(vals)  # -> [0.9983865609638467, 1.0, 0.060730098812886574]
```

### Error message

```shell
.
```

### SciPy/NumPy/Python version information

1.5.3 1.18.5 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

**Comment by mdhaber** [comment] 2022-10-04 20:38
A few versions ago, we replaced the implementation of `binom.pmf` with that of Boost. Now (in 1.9.1):
```
[1.0, 0.0016121367428128667, 1.3015924788782256e-06]
```
The sum is still greater than 1, but it's better. 

It is possible to improve the accuracy of the calculation for `k=0`:
```
np.exp(binom.logpmf(n=n, p=p, k=0))  # 0.9983865609638467
```
But this strategy is poor for `k=1`.
```
np.exp(binom.logpmf(n=n, p=p, k=1)) # 734.0188489038472
```  
If someone can reproduce this problem in C++ w/ Boost, it would be better to post this issue upstream.

In the meantime, note that we cannot guarantee the results of all distributions to floating point precision for all possible inputs. When working with extreme parameters, consider using arbitrary precision arithmetic (e.g. mpmath).

**Comment by Scriddie** [comment] 2022-10-05 15:30
Thanks for the quick reply! Good to hear this is improved upon in newer versions. Interestingly, vals[0] is the one value that actually seems to be very close to accurate in the old version - I am surprised that one appears to be worse in the new one.

The new `logpmf` implementation you suggested looks like quite an improvement. I cannot tell if it would have any drawbacks for other values of `n` and `p`, but perhaps there are tests for that. 
Seems like it would be a great change overall, and might save some people from accidentally ending up with funky variance values, especially since there is no error!

I will be switching between `binom` and `poisson` for my case, thanks for the suggestion!

**Comment by WarrenWeckesser** [comment] 2022-10-07 16:52
Thanks for the report, @vincentvalton.  Unlike the OP, which seems to be a limitation of the numerical calculations when some of the parameters are extreme, the issue that you report is a pretty clear bug.  The *probability mass function* should take on nonzero values only at the integers in the support.  Could you create a new issue with this report?  It really is a different issue than the OP.

**Comment by vincentvalton** [comment] 2022-10-07 18:03
> Thanks for the report, @vincentvalton. Unlike the OP, which seems to be a limitation of the numerical calculations when some of the parameters are extreme, the issue that you report is a pretty clear bug. The _probability mass function_ should take on nonzero values only at the integers in the support. Could you create a new issue with this report? It really is a different issue than the OP.

Thanks @WarrenWeckesser, I've opened a bug report here: https://github.com/scipy/scipy/issues/17167#top

**Comment by mborland** [comment] 2022-10-16 17:45
See: https://github.com/boostorg/math/pull/847.

I used @mdhaber suggested test values, and now we have the correct values and a sum <= 1.

**Comment by mborland** [comment] 2022-10-18 00:56
Fix has been merged into Boost.Math. Let me know if you need anything else.

**Closed** 2023-02-27 22:24 UTC
Labels: scipy.stats, enhancement
