### ISSUE TITLE
test failure -- OSError: /usr/lib64/libm.so: invalid ELF header

### ISSUE THREAD

**Issue by jlec** [scipy/scipy#5425] opened 2015-10-25 18:50 UTC
```python
======================================================================
ERROR: test_improvement (test_quadpack.TestCtypesQuad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0-python3_4/build/test/lib/scipy/integrate/tests/test_quadpack.py", line 42, in setUp
    self.lib = ctypes.CDLL(file)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libm.so: invalid ELF header

======================================================================
ERROR: test_typical (test_quadpack.TestCtypesQuad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0-python3_4/build/test/lib/scipy/integrate/tests/test_quadpack.py", line 42, in setUp
    self.lib = ctypes.CDLL(file)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libm.so: invalid ELF header
```
This is with glibc-2.22 on Gentoo Linux

```
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /lib64/libm.so.6  AS_NEEDED ( /lib64/libmvec.so.1 ) )
```

**Comment by rgommers** [comment] 2015-10-25 18:53
Thanks for the report @jlec. This is a duplicate of gh-5370, and will be fixed by gh-5416.

**Closed by rgommers** 2015-10-25 18:53 UTC
Labels: duplicate
