### ISSUE TITLE
BUG: scipy.stats.shapiro gives a negative pvalue

### ISSUE THREAD

**Issue by Noe-AC** [scipy/scipy#18322] opened 2023-04-19 17:27 UTC
### Describe your issue.

p-values are supposed to be in [0,1], but I get a negative p-value using the scipy shapiro.
See the example code below.

### Reproducing Code Example

```python
from scipy.stats import shapiro
x = [0.6931471805599453, 0.0, 0.0]
res = shapiro(x)
res.pvalue # gives -6.830188112871838e-07, which is negative...
```

### Error message

```shell
# no error message, just a negative p-value
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.23.5 sys.version_info(major=3, minor=9, micro=15, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
  lapack:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 12.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 12.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.33
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 4.9.0
  pythran:
    include directory: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-x9bi86_d/overlay/lib/python3.9/site-packages/pythran
    version: 0.12.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
Python Information:
  path: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-1cu21evt/cp39-macosx_x86_64/build/venv/bin/python
  version: '3.9'
```

**Comment by mdhaber** [comment] 2023-04-19 18:51
The null distribution of the Shapiro-Wilk test is usually estimated using a Monte Carlo approach, but for $n=3$ there is an exact distribution. 
![image](https://user-images.githubusercontent.com/6570539/233172167-449fb54b-e458-4743-a948-941c2e58efa3.png)

Maybe we want to override whatever `shapiro` is doing in this case.

**Comment by tupui** [comment] 2023-04-20 11:11
That would fix the case n=3, but are we sure that negative values are only appearing for n=3? Since the underlying Fortran is more than 20 years old, I guess we would have heard by now, but who knows.

**Comment by mdhaber** [comment] 2023-04-20 13:36
Not certain, but $n=3$ is indeed treated differently from other cases (confirmed in `swilk.f`), so I'm content with fixing the reported bug to close this.

**Closed** 2023-04-21 11:42 UTC
Labels: defect, scipy.stats
