### ISSUE TITLE
BUG: Pip install scipy fails on FreeBSD

### ISSUE THREAD

**Issue by peterhil** [scipy/scipy#17875] opened 2023-01-28 15:09 UTC
### Describe your issue.

Pip install scipy fails on FreeBSD 13.1 – and probably any other OS than Linux, Mac, Android and Windows – because of an ifdef in `xsimd` library.

https://github.com/serge-sans-paille/pythran/issues/2070
https://github.com/xtensor-stack/xsimd/issues/893

* FreeBSD 13.1-RELEASE-p3
* LLVM clang version 9.0.1
* openblas-0.3.20,1
* GNU Fortran (FreeBSD Ports Collection) 12.2.0
* Python 3.9.16
* pip 22.0.4

Here is the [full build log](https://github.com/serge-sans-paille/pythran/files/10461681/scipy.log)

### Reproducing Code Example

```python
python3.9 -m venv venv/py39
. ./venv/py39/bin/activate
pip install scipy
```
```


### Error message

```shell
[825/1620] Compiling C++ object scipy/stats/_stats_pythran.cpython-39.so.p/meson-generated_..__stats_pythran.cpp.o
      FAILED: scipy/stats/_stats_pythran.cpython-39.so.p/meson-generated_..__stats_pythran.cpp.o
      c++ -Iscipy/stats/_stats_pythran.cpython-39.so.p -Iscipy/stats -I../../scipy/stats -I/tmp/pip-build-env-i5rkurrm/overlay/lib/python3.9/site-packages/pythran -I/tmp/pip-build-env-i5rkurrm/overlay/lib/python3.9/site-packages/numpy/core/include -I/usr/local/include/python3.9 -fvisibility=hidden -fvisibility-inlines-hidden -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++14 -O2 -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_NONE -Wno-cpp -Wno-deprecated-declarations -Wno-unused-but-set-variable -Wno-unused-function -Wno-unused-variable -Wno-int-in-bool-context -MD -MQ scipy/stats/_stats_pythran.cpython-39.so.p/meson-generated_..__stats_pythran.cpp.o -MF scipy/stats/_stats_pythran.cpython-39.so.p/meson-generated_..__stats_pythran.cpp.o.d -o scipy/stats/_stats_pythran.cpython-39.so.p/meson-generated_..__stats_pythran.cpp.o -c scipy/stats/_stats_pythran.cpp
      In file included from scipy/stats/_stats_pythran.cpp:34:
      In file included from /tmp/pip-build-env-i5rkurrm/overlay/lib/python3.9/site-packages/pythran/pythonic/include/numpy/ceil.hpp:8:
      In file included from /tmp/pip-build-env-i5rkurrm/overlay/lib/python3.9/site-packages/pythran/xsimd/xsimd.hpp:55:
      /tmp/pip-build-env-i5rkurrm/overlay/lib/python3.9/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp:447:16: error: no member named 'exp10f' in the global namespace; did you mean 'exp10'?
              return ::exp10f(x);
                     ^~~~~~~~
                     exp10
      /tmp/pip-build-env-i5rkurrm/overlay/lib/python3.9/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp:445:18: note: 'exp10' declared here
          inline float exp10(const float& x) noexcept
                       ^
      /tmp/pip-build-env-i5rkurrm/overlay/lib/python3.9/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp:451:16: error: no member named 'exp10' in the global namespace; did you mean simply 'exp10'?
              return ::exp10(x);
                     ^~~~~~~
                     exp10
      /tmp/pip-build-env-i5rkurrm/overlay/lib/python3.9/site-packages/pythran/xsimd/arch/xsimd_scalar.hpp:449:19: note: 'exp10' declared here
          inline double exp10(const double& x) noexcept
                        ^
      2 errors generated.
```

### SciPy/NumPy/Python version information

1.10.0 1.24.1 3.9.16 (main, Dec 17 2022, 01:13:33)

**Comment by tupui** [comment] 2023-01-28 21:12
Thank you for reporting @peterhil. It looks like the issue is going to be fixed with the next release of Pythran, thank you for the xref. Would you mind coming back and closing this once it's done?

**Comment by peterhil** [comment] 2023-01-30 01:24
Yes, will close this once there is next release of Pythran. Just checked an improved patch, and it works.

**Comment by rgommers** [comment] 2023-07-30 16:36
This was resolved a while ago, I'll close it. Thanks all!

**Closed by rgommers** 2023-07-30 16:36 UTC
Labels: defect, Build issues, upstream bug, Pythran
