### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#6422] opened 2016-07-27 20:43 UTC
See comment by lobisquit at https://aur.archlinux.org/packages/python-scipy-openblas/:
> Compiling new version of package gives me following error:
"BLAS : Program is Terminated. Because you tried to allocate too many memory regions"
This seem to happen during the testing of this file:
python-scipy-openblas/src/test/usr/lib/python3.5/site-packages/scipy/signal/filter_design.py
Any idea of a fix?
>
> EDIT: "export OPENBLAS_NUM_THREADS=1" before giving "makepkg -s" seems to fix the issue

which I can reproduce.

Arch Linux Python 3.5.2

**Comment by pv** [comment] 2016-07-27 20:53
Never seen this before, but the message --- and, potentially also the
bug --- comes from Openblas.
.
Openblas documentation indicates that it may be due to incorrect
openblas build:
https://github.com/xianyi/OpenBLAS/blob/master/USAGE.md#usage

**Comment by pv** [comment] 2016-07-27 20:55
Closing -- please reopen if it seems it's not openblas bug.

**Closed by pv** 2016-07-27 20:55 UTC

**Comment by u55** [comment] 2016-08-01 13:05
@anntzer @pv I think lobisquit identified the wrong failing scipy test. The openblas error comes from this test: `test_linsolve.TestSplu.test_threads_parallel` in the sparse.linalg module, which was added to scipy version 0.18.0 with commit 3ad3b6f. A minimal working example which reproduces the error message is the following:
```python
import scipy.sparse.linalg
scipy.sparse.linalg.test('full', verbose=10)
```
I am not sure if this is an openblas bug or a scipy bug. Someone can correct me if I am wrong, but I think the error message comes about because the scipy test tries to create 20 python threads with [this line](https://github.com/scipy/scipy/blame/0a09577fecfeaeae0806c2c27a2af6ac7865f4fa/scipy/sparse/linalg/dsolve/tests/test_linsolve.py#L473-L474),
```python
        threads = [threading.Thread(target=worker)
                   for k in range(20)]
```
where each thread calls an optimized (possibly multithreaded) matrix operation, but by default, openblas is compiled to use only as many threads as there are (possibly virtual) CPU cores, which on my machine is 8. 

Now, I have found that openblas will run this scipy test without error if openblas is compiled either with 'USE_OPENMP=0 USE_THREAD=1 NUM_THREADS=64' to increase the number of threads available to openblas, or with 'USE_OPENMP=0 USE_THREAD=0' to disable threading in openblas altogether.

This statement can be found in the openblas FAQ:
"If your application is already multi-threaded, it will conflict with OpenBLAS multi-threading. Thus, you must set OpenBLAS to use single thread ..."

Note, there are comments in the openblas section of the Numpy [site.cfg.example](https://github.com/numpy/numpy/blob/55b766d549dc7a9cd417de001a2f7ba8d445579f/site.cfg.example#L113-L122) file which suggest that the pthread build of openblas should work. So again, I am not sure if this is a problem with scipy or a problem with openblas.

**Comment by pv** [comment] 2016-08-01 13:35
To me, that seems to be a limitation/footgun in OpenBLAS. I do not 
believe it's a bug in Scipy per se. The issue appears to be only with 
the test, which spawns multiple threads, to check whether a race 
condition is hit. That the BLAS library has a feature where it crashes 
when there are too many threads calling to it at the same time, is not 
IMO a bug in our side.
.
The potential change in Scipy to be done could be to change the test to 
use a smaller number of threads if openblas is used (not completely 
trivial to check at runtime however, and I'm not sure if you can get the 
value of NUM_THREADS from it somehow).
.
Or, you can set OPENBLAS_NUM_THREADS=1 when running the test suite.
.
AFAICS, debian and ubuntu build openblas with NUM_THREADS=64.

**Comment by u55** [comment] 2016-08-01 17:47
@pv Yes, after thinking about it some more, I agree with you. Scipy should not have to make any assumptions about whether openblas is built with support for multiple threads. And in fact, since this test is failing when creating _python_ threads, and not multiprocesses, I think the statement in the openblas FAQ about multi-threaded applications is not relevant here. Openblas should be able to handle python threads, and the fact that it doesn't, seems like a bug in openblas. I suspect that setting 'NUM_THREADS=64' will still fail when calling openblas with more than 64 threads, and I think I found a related open issue here JuliaLang/julia#14857 that suggests as much.

In the meantime, maybe we should add a comment to the Numpy site.cfg.example file about compiling openblas with 'NUM_THREADS=64', especially if this is what debian and ubuntu do.

**Comment by matthew-brett** [comment] 2016-08-01 17:53
Maybe it would be good to add an issue to OpenBLAS for this?   The
maintainer has been very responsive in the past...​

**Comment by u55** [comment] 2016-08-01 18:13
@pv @matthew-brett Actually, I re-ran the scipy test using a larger number of python threads than 64 when openblas is compiled with 'NUM_THREADS=64', see my edited comment above, and the test passed without any error messages. 

As far as I can tell, openblass _needs_ to be compiled with 'USE_OPENMP=0 USE_THREAD=1 NUM_THREADS=64' or with 'USE_OPENMP=0 USE_THREAD=0'. I don't know if this is an openblas feature or a bug.

**Comment by pv** [comment] 2016-08-01 18:20
You can maybe also try a simpler testcase e.g. calling `scipy.linalg.blas.dgemm` from multiple threads.

**Comment by anntzer** [comment] 2016-08-01 19:01
FWIW, by default Arch Linux builds openblas with NUM_THREADS set to the number of cores: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openblas

**Comment by u55** [comment] 2016-08-01 19:10
@anntzer Actually, I have been using a different AUR package that, by default, does not set NUM_THREADS and does not use openmp: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openblas-lapack

**Comment by anntzer** [comment] 2016-08-01 20:35
Actually I just checked, I am also using openblas-lapack, which just sets USE_THREAD=1 with no mention of NUM_THREADS, as you indicated.

**Comment by VictorRodriguez** [comment] 2017-03-20 23:00
Hi 

I am facing the same problem despite the fact that these are my make flags in openblas : 

make TARGET=HASWELL F_COMPILER=GFORTRAN  SHARED=1 DYNAMIC_THREADS=1 USE_OPENMP=1  NUM_THREADS=128 %{?_smp_mflags} 

I am using this spec file: 
http://kojiclear.jf.intel.com/cgit/packages/openblas/tree/openblas.spec

The test that im running is: 
python scipy/interpolate/tests/test_interpnd.py
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions
Segmentation fault (core dumped)

I have try with USE_OPENMP=0 USE_THREAD=1  NUM_THREADS=128 with the same result 

Thanks a lot

**Comment by VictorRodriguez** [comment] 2017-03-20 23:13
Hi

I am facing the same problem despite the fact that these are my make flags in openblas :

make TARGET=HASWELL F_COMPILER=GFORTRAN SHARED=1 DYNAMIC_THREADS=1 USE_OPENMP=1 NUM_THREADS=128 %{?_smp_mflags}

I am using this spec file:
https://github.com/clearlinux-pkgs/openblas/blob/master/openblas.spec

The test that im running is:
python scipy/interpolate/tests/test_interpnd.py
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions
Segmentation fault (core dumped)

I have try with USE_OPENMP=0 USE_THREAD=1 NUM_THREADS=128 with the same result

Thanks a lot

**Comment by pv** [comment] 2017-03-21 11:11
@VictorRodriguez: based the above, this appears to be an Openblas issue 
not actionable from our side.
