### ISSUE TITLE
BUG: scipy.interpolate.interp2d fails to interpolate and returns with incorrect function

### ISSUE THREAD

**Issue by bsipocz** [scipy/scipy#4138] opened 2014-11-12 00:14 UTC
There seems to be a genuine bug in ``scipy.interpolate.interp2d``. In this example the input arrays are given as full coordinates (and not as a regular grid). This data here, is part of a much bigger non-regularly sampled surface, thus I can't call ``interp2d`` with x, y as column and raw coordinates on a regular grid.

```
>>>  data
array([(0.11, 1.0, 10.045999999999999), (0.13, 1.0, 9.6010000000000009),
       (0.14999999999999999, 1.0, 9.2579999999999991),
       (0.17499999999999999, 1.0, 8.9199999999999999),
       (0.20000000000000001, 1.0, 8.6479999999999997),
       (0.25, 1.0, 8.2159999999999993), (0.11, 2.0, 10.045999999999999),
       (0.13, 2.0, 9.5999999999999996),
       (0.14999999999999999, 2.0, 9.2579999999999991),
       (0.17499999999999999, 2.0, 8.9190000000000005),
       (0.20000000000000001, 2.0, 8.6460000000000008),
       (0.25, 2.0, 8.2089999999999996)], 
      dtype=[('M', '<f8'), ('age', '<f8'), ('J', '<f8')])
>>> interp_data = interp2d(data['M'], data['age'], data['J'])
Warning:     No more knots can be added because the number of B-spline coefficients
    already exceeds the number of data points m. Probably causes: either
    s or m too small. (fp>s)
        kx,ky=1,1 nx,ny=7,5 m=12 fp=0.000284 s=0.000000
```

The result definitely doesn't look right, I don't expect any interpolated value to be around 0 especially with linear interpolation.
![failed_interp2d](https://cloud.githubusercontent.com/assets/6788290/5002954/033c3ee2-69ff-11e4-9b9a-a68d3e19b2b4.png)

**Comment by rgommers** [comment] 2015-03-09 21:19
Hi @bsipocz, thanks for the report. Can you provide a self-contained example that reproduces this issue?

**Comment by andreas-h** [comment] 2015-04-06 16:41
import numpy as np
    from scipy.interpolate import interp2d
    data = np.array([(0.11, 1.0, 10.045999999999999),
                     (0.13, 1.0, 9.6010000000000009),
                     (0.14999999999999999, 1.0, 9.2579999999999991),
                     (0.17499999999999999, 1.0, 8.9199999999999999),
                     (0.20000000000000001, 1.0, 8.6479999999999997),
                     (0.25, 1.0, 8.2159999999999993),
                     (0.11, 2.0, 10.045999999999999),
                     (0.13, 2.0, 9.5999999999999996),
                     (0.14999999999999999, 2.0, 9.2579999999999991),
                     (0.17499999999999999, 2.0, 8.9190000000000005),
                     (0.20000000000000001, 2.0, 8.6460000000000008),
                     (0.25, 2.0, 8.2089999999999996)],
                    dtype=[('M', '<f8'), ('age', '<f8'), ('J', '<f8')])

Then,

    interp2d(data["M"], data["age"], data["J"], kind="linear")

triggers the warning.

However, I'm not sure if this is actually a bug.  The `interp2d` docstring says

    The interpolator is constructed by `bisplrep`, with a smoothing factor
    of 0. If more control over smoothing is needed, `bisplrep` should be
    used directly.

When I use a smoothing factor of `len(data) = 12`, `bsplrep` seems to work:

    from scipy.interpolate import fitpack
    fitpack.bisplrep(data["M"], data["age"], data["J"], kx=1, ky=1, s=12.)

returns
    
    [array([ 0.11,  0.11,  0.25,  0.25]),
     array([ 1.,  1.,  2.,  2.]),
     array([ 9.87069752,  9.87158497,  8.08217381,  8.07662335]),
     1,
     1]

**Comment by andreas-h** [comment] 2015-04-06 16:46
Actually, this seems to be a duplicate of #2167

**Comment by rgommers** [comment] 2015-04-28 21:04
Thanks @andreas-h, closing this then as a duplicate. Will link to this on gh-2167.

**Closed by rgommers** 2015-04-28 21:04 UTC
Labels: scipy.interpolate
