### ISSUE TITLE
Build issues on macOS Catalina.

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#13776] opened 2021-03-31 01:54 UTC
I've just updated my macOS operating system to Catalina, and can't build scipy any more.

- I have the Xcode command line tools installed.
- I installed gfortran 10.2 (https://github.com/fxcoudert/gfortran-for-macOS/releases)
- I have an openblas installation via brew.
- I am using Python 3.9 (miniconda env) with numpy 1.20.2, cython, pybind11, pythran installed.

The tail end of the build log is below. The full build log is [here](https://gist.github.com/andyfaff/a3c2e563d1ddf8fb55113f286342290d).

```
CCompilerOpt.cc_test_flags[999] : testing flags (-mavx5124fmaps -mavx5124vnniw -mavx512vpopcntdq)
C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64

compile options: '-c'
extra options: '-mavx5124fmaps -mavx5124vnniw -mavx512vpopcntdq'
CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -c /Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.c -o /var/folders/jm/bgyywkdd59qcn1g9m7x_1l506jdzvv/T/tmpa_4u0h6h/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o -MMD -MF /var/folders/jm/bgyywkdd59qcn1g9m7x_1l506jdzvv/T/tmpa_4u0h6h/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/test_flags.o.d -mavx5124fmaps -mavx5124vnniw -mavx512vpopcntdq) failed with exit status 1 output -> 
clang: error: unknown argument: '-mavx5124fmaps'
clang: error: unknown argument: '-mavx5124vnniw'

CCompilerOpt.cc_test_flags[1003] : testing failed
CCompilerOpt.feature_test[1444] : testing feature 'AVX512_KNM' with flags (-msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512er -mavx512pf)
C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64

compile options: '-c'
extra options: '-msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512er -mavx512pf -Werror'
CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -c /Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c -o /var/folders/jm/bgyywkdd59qcn1g9m7x_1l506jdzvv/T/tmpa_4u0h6h/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.o -MMD -MF /var/folders/jm/bgyywkdd59qcn1g9m7x_1l506jdzvv/T/tmpa_4u0h6h/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.o.d -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512er -mavx512pf -Werror) failed with exit status 1 output -> 
/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:9:9: error: implicit declaration of function '_mm512_4fmadd_ps' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    b = _mm512_4fmadd_ps(b, b, b, b, b, NULL);
        ^
/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:9:9: note: did you mean '_mm512_fmadd_ps'?
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/avx512fintrin.h:2716:1: note: '_mm512_fmadd_ps' declared here
_mm512_fmadd_ps(__m512 __A, __m512 __B, __m512 __C)
^
/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:9:7: error: assigning to '__m512' (vector of 16 'float' values) from incompatible type 'int'
    b = _mm512_4fmadd_ps(b, b, b, b, b, NULL);
      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:11:9: error: implicit declaration of function '_mm512_4dpwssd_epi32' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    a = _mm512_4dpwssd_epi32(a, a, a, a, a, NULL);
        ^
/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:11:9: note: did you mean '_mm512_dpwssd_epi32'?
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/avx512vnniintrin.h:68:1: note: '_mm512_dpwssd_epi32' declared here
_mm512_dpwssd_epi32(__m512i __S, __m512i __A, __m512i __B)
^
/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:11:7: error: assigning to '__m512i' (vector of 8 'long long' values) from incompatible type 'int'
    a = _mm512_4dpwssd_epi32(a, a, a, a, a, NULL);
      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.

CCompilerOpt.feature_test[1458] : testing failed
CCompilerOpt.__init__[1695] : skip features (SSE2 SSE SSE3) since its part of baseline
CCompilerOpt.__init__[1699] : initialize targets groups
CCompilerOpt.__init__[1701] : parse target group simd_test
CCompilerOpt._parse_target_tokens[1910] : skip targets (XOP NEON VSX VSX3 FMA4 ASIMD VSX2) not part of baseline or dispatch-able features
CCompilerOpt._parse_policy_not_keepbase[2022] : skip baseline features (SSE2)
CCompilerOpt.generate_dispatch_header[2236] : generate CPU dispatch header: (build/src.macosx-10.9-x86_64-3.9/numpy/distutils/include/npy_cpu_dispatch_config.h)
CCompilerOpt.generate_dispatch_header[2245] : dispatch header dir build/src.macosx-10.9-x86_64-3.9/numpy/distutils/include does not exist, creating it
CCompilerOpt.feature_extra_checks[1519] : Testing extra checks for feature 'AVX512F' (AVX512F_REDUCE)
C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64

compile options: '-c'
extra options: '-msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -Werror'
CCompilerOpt.feature_extra_checks[1519] : Testing extra checks for feature 'AVX512_SKX' (AVX512BW_MASK AVX512DQ_MASK)
C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64

compile options: '-c'
extra options: '-msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq -Werror'
C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64 -fPIC -O2 -isystem /Users/anz/miniconda3/envs/dev39/include -arch x86_64

compile options: '-c'
extra options: '-msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq -Werror'
Detected changes on compiler optimizations, force rebuilding
get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
customize Gnu95FCompiler
customize Gnu95FCompiler
customize Gnu95FCompiler using build_clib
building 'mach' library
using additional config_fc from setup script for fortran compiler: {'noopt': ('scipy/integrate/setup.py', 1)}
customize Gnu95FCompiler
compiling Fortran sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -arch x86_64 -fPIC
Fortran f90 compiler: /usr/local/bin/gfortran -Wall -g -fno-second-underscore -arch x86_64 -fPIC
Fortran fix compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -arch x86_64 -fPIC
creating build/temp.macosx-10.9-x86_64-3.9
creating build/temp.macosx-10.9-x86_64-3.9/scipy
creating build/temp.macosx-10.9-x86_64-3.9/scipy/integrate
creating build/temp.macosx-10.9-x86_64-3.9/scipy/integrate/mach
compile options: '-I/Users/anz/miniconda3/envs/dev39/lib/python3.9/site-packages/numpy/core/include -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/distutils/include -c'
gfortran:f77: scipy/integrate/mach/xerror.f
gfortran:f77: scipy/integrate/mach/d1mach.f
scipy/integrate/mach/xerror.f:1:37:

    1 |       SUBROUTINE XERROR(MESS,NMESS,L1,L2)
      |                                     1
Warning: Unused dummy argument ‘l1’ at (1) [-Wunused-dummy-argument]
scipy/integrate/mach/xerror.f:1:40:

    1 |       SUBROUTINE XERROR(MESS,NMESS,L1,L2)
      |                                        1
Warning: Unused dummy argument ‘l2’ at (1) [-Wunused-dummy-argument]
llvm-ar: adding 2 object files to build/temp.macosx-10.9-x86_64-3.9/libmach.a
error: Command "/opt/concourse/worker/volumes/live/ab2513ba-3c1a-4cb3-5083-7af35a6674ad/volume/python-split_1614801139224/_build_env/bin/llvm-ar rcs build/temp.macosx-10.9-x86_64-3.9/libmach.a build/temp.macosx-10.9-x86_64-3.9/scipy/integrate/mach/d1mach.o build/temp.macosx-10.9-x86_64-3.9/scipy/integrate/mach/xerror.o" failed with exit status 127
```

**Comment by andyfaff** [comment] 2021-03-31 02:57
With the same compiler setup, but on in a Python 3.8 environment the build works.

**Comment by rgommers** [comment] 2021-03-31 21:35
Not sure, but mixing conda and Homebrew packages is inherently a little fragile. Could you try http://scipy.github.io/devdocs/dev/contributor/quickerstart_conda.html#quickerstart-conda with Python 3.9?

**Comment by andyfaff** [comment] 2021-03-31 23:40
I like the way that conda-forge has created a setup that makes it easier to build everything, and for people to get started. 

However, having an overly homogenous build setup comes with its own risks, it's a good thing to be able to build in reasonably diverse ways, including the standard way for the OS.

Once the standard command line build tools are installed (xcode-select), then it's straightforward to install openblas from source (./configure; make; make install). I just use brew to grab gfortran. I only use conda here because it's my default setup for making environments; once Python is installed in an env I use pip for everything else.

**Comment by rgommers** [comment] 2021-04-01 08:55
I'm just suggesting it as a way to start eliminating things. The build command fails on `llvm-ar rcs` which I can't remember seeing before. If you mixing Homebrew, conda and pip plus a Fortran compiler from yet somewhere else, there's a lot of things that can clash.

**Comment by V0lantis** [comment] 2021-04-02 18:14
I just met te same error here, following exactly the steps from [doc](https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_mac.html#quickstart-mac)

**Comment by V0lantis** [comment] 2021-04-02 18:46
Ok it works for me just using pip (without conda)

**Comment by andyfaff** [comment] 2021-04-03 03:12
@V0lantis, is Python provided by pip or conda?

**Comment by V0lantis** [comment] 2021-04-03 07:41
I erased everything on my computer and installed Python with Brew (Python@39)

**Comment by thomasjpfan** [comment] 2021-04-24 01:39
I ran into a similar error while debugging a build of scikit-learn on osx. Using `ar` and not `llvm-ar` resolved the build error for me:

```bash
export AR=/usr/bin/ar
```

**Comment by HaoZeke** [comment] 2021-09-06 07:48
Ran into this as well. The `AR` is not the issue here (though if `llvm-ar` is being called with `gcc` that would be a different kind of error). 

From the compiler logs the naive (and working) fix is simply to add the relevant `CFLAG` to suppress the error, `-Wno-error=implicit-function-declaration`. That is:
```bash
export CFLAGS=-Wno-error=implicit-function-declaration
python runtests.py -vv -j 16 --  -n 16
# and / or
pip install .
```
This should be fixed though, it essentially means the build system is including files out of order. Perhaps the `meson` version will not have this issue.

**Comment by rgommers** [comment] 2021-09-06 09:57
> From the compiler logs the naive (and working) fix is simply to add the relevant `CFLAG` to suppress the error, `-Wno-error=implicit-function-declaration`. That is:

Suppressing a warning should not matter, right? Unless something else is adding a `-Werror` flag, which would definitely be wrong.

**Comment by HaoZeke** [comment] 2021-09-06 10:19
> > From the compiler logs the naive (and working) fix is simply to add the relevant `CFLAG` to suppress the error, `-Wno-error=implicit-function-declaration`. That is:
> 
> Suppressing a warning should not matter, right? Unless something else is adding a `-Werror` flag, which would definitely be wrong.

`-Werror` is being added by `extra_commands`, the relevant portion of the error log is:

```bash
compile options: '-c'
extra options: '-msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512er -mavx512pf -Werror'
```

**Comment by rgommers** [comment] 2021-09-06 14:51
> `-Werror` is being added by `extra_commands` (it is the last one), the relevant portion of the error log is:

Thanks. This was modified recently in gh-19642. @seiko2plus did you mean to add `-Werror` or `-Wno-error` there? Also, I think we discussed before about `-Werror` in general, but there's no code comments and I cannot find it back. It's usually a bad idea to add `-Werror` to a build script, why is it necessary for this bit of code?

**Comment by rgommers** [comment] 2021-09-16 20:21
> I just met te same error here, following exactly the steps from [doc](https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_mac.html#quickstart-mac). By the way, I am on macOS BigSur
> ...
> I erased everything on my computer and installed Python with Brew (Python@39)

I was reminded of this issue. Homebrew Python should be avoided, see https://justinmayer.com/posts/homebrew-python-is-not-for-you/.

It looks like there are multiple issues being mixed in this issue:
1. The original report, failing on `llvm-ar`. Seems somehow caused by using XCode Clang + Homebrew gfortran + Conda Python 3.9.
2. Failures caused by `-Werror` in `numpy.distutils`
3. Homebrew Python + some other dependencies from conda (this one is invalid I'd say).

For next commenters: please add enough detail on how you installed your compilers, Python and other dependencies. Ideally add the output of `pip list` or `conda list` wrapped in `<details> ... </details>`.

**Comment by seiko2plus** [comment] 2021-11-03 15:09
@rgommers, [`gh-19642`](https://github.com/numpy/numpy/pull/19642) fixes detecting the compiler support of certain intrinsics, NumPy's distutils force the compiler to treat warnings as errors only during testing the availability of SIMD/intrinsics.

However, the build fails due to the following error only and has nothing to do with `-Werror`:
```Bash
error: Command "/opt/concourse/worker/volumes/live/ab2513ba-3c1a-4cb3-5083-7af35a6674ad/volume/python-split_1614801139224/_build_env/bin/llvm-ar rcs build/temp.macosx-10.9-x86_64-3.9/libmach.a build/temp.macosx-10.9-x86_64-3.9/scipy/integrate/mach/d1mach.o build/temp.macosx-10.9-x86_64-3.9/scipy/integrate/mach/xerror.o" failed with exit status 127
```
Error number `127` returns from exec interpreter when it fails to find certain command in a path. in our case here `llvm-ar`.
IMHO, this issue should be forwarded to `miniconda`, they need to replace the path of `ar` within python/sysconfig with the path of the system or ship the toolchain they used in building NumPy.

**Comment by rgommers** [comment] 2021-11-06 16:14
> However, the build fails due to the following error only and has nothing to do with `-Werror`:

As I said above, there are two separate issues. `llvm-ar` is one of them. The other one can be fixed by disabling a `-Werror` flag, says https://github.com/scipy/scipy/issues/13776#issuecomment-913426017.

> IMHO, this issue should be forwarded to `miniconda`, they need to replace the path of `ar` within python/sysconfig with the path of the system or ship the toolchain they used in building NumPy.

That compiler toolchain does get shipped. An issue here is that the OP isn't actually using that toolchain, but is using a different compiler toolchain (C/C++ compilers from the system, and Gfortran from Homebrew). The conda devs try to make that work, but it's inherently limited and prone to breakage from time to time.

**Closed** 2021-11-12 05:51 UTC
Labels: Build issues

**Comment by rlucas7** [comment] 2021-12-27 02:30
@andyfaff I see you closed this issue. 

I'm seeing the same error on a new setup of env for scipy development. 

Were you able to resolve?

**Comment by andyfaff** [comment] 2021-12-28 00:43
I think I closed the issue because I was able to build at that point. I can't remember what I did to recover the situation.
