### ISSUE TITLE
scipy.linalg.orthogonal_procrustes

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#12019] opened 2020-05-04 12:12 UTC
Most of the linalg decomposition functions are correctly set up to work with complex matrices (like svd, qr).  However, orthogonal_procrustes is not.   It needs an extra conjugate on the matrix A to be correct for the unitary procrustes problem.   The existing function could either be modified (which would not break anything for real matrices), or a new function like this could be added.

```
def unitary_procrustes(A,B,check_finite=True):
  # Given matrices A and B of equal shape, find a unitary matrix R that most closely maps A to B (AR should be close to B)
  # This only differs from orthogonal_procrustes by np.conjugate(A) in the first line.  
  u,w,vt=np.linalg.svd(B.T.dot(np.conjugate(A)).T)
  R=u.dot(vt)
  scale=w.sum()
  return R,scale
```

**Comment by ilayn** [comment] 2020-05-04 12:37
Seems like a sensible addition though the name would be wonky a bit. I don't think this needs yet another function since it is basically an SVD call and another one-liner.

Also the code can be cleaned up for Py3. Care to send a PR?

**Comment by keithbriggs** [comment] 2020-05-04 14:21
What py3 changes are needed?

**Comment by ilayn** [comment] 2020-05-04 14:39
`@` for matmult and the future imports at the top specifically.

**Comment by WarrenWeckesser** [comment] 2020-05-04 14:50
> I don't think this needs yet another function ...

@ilayn, does that mean you are suggesting that the `conjugate` call be added to the existing function in the appropriate place rather than creating a new function?  That makes sense to me, since `conjugate` is just the identity with real matrices.  The docstring should also be updated to mention that complex inputs are handled and the result in that case is the solution to the unitary Procrustes problem.

This would be a change in behavior for anyone who currently calls the function with complex inputs, but I think we can interpret the current behavior with complex inputs as a bug, and adding `conjugate` is a bug fix.

(At the moment, I'm also assuming that this is, in fact, the correct fix.  It seems reasonable, but I've never thought about unitary Procrustes decompositions.)

**Comment by WarrenWeckesser** [comment] 2020-05-04 14:53
> ... and removing the future imports at the top specifically.

Those imports have already been removed in master: https://github.com/scipy/scipy/blob/master/scipy/linalg/_procrustes.py

**Comment by ilayn** [comment] 2020-05-04 15:18
> does that mean you are suggesting that the `conjugate` call be added to the existing function in the appropriate place rather than creating a new function? 

Yes, and I agree with your doc change. To me still the whole function looks a bit redundant but it is what it is I guess.

> (At the moment, I'm also assuming that this is, in fact, the correct fix. It seems reasonable, but I've never thought about the unitary Procrustes problem.)

Yes the definition of the problem is different but the maximizer value and hence the machinery is the same. 

> Those imports have already been removed in master:

Ah clicked the wrong link. Good catch.

**Comment by melissawm** [comment] 2021-11-11 18:16
@keithbriggs it looks like you did this on your own fork instead of submitting a PR to SciPy, are you still interested in submitting a PR?

**Comment by keithbriggs** [comment] 2021-11-11 19:35
Yes, I thought I had done that. If not could you please advise the procedure?

**Comment by melissawm** [comment] 2021-11-11 19:57
You can:
- Clone the current repo for scipy, or update your own;
- [Set up your remotes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/configuring-a-remote-for-a-fork) (usually, we use `origin` for your own fork and `upstream` for the scipy main repo)
- Create a feature branch with `git checkout -b branch_name`
- Do your changes
- Push them to your own fork by doing `git push origin branch_name`
- Either click the link that shows up in your terminal or visit your fork at `https://github.com/keithbriggs/scipy` and there will be a prompt at the top of the repo about creating a pull request for the scipy master branch.

Hope this helps! Feel free to ping otherwise :)

**Comment by keithbriggs** [comment] 2021-11-12 08:53
Thank you very much - I will try this on the weekend.

**Comment by mdhaber** [comment] 2024-08-20 06:39
Closed by gh-12071.

**Closed by mdhaber** 2024-08-20 06:39 UTC
Labels: enhancement, scipy.linalg
