### ISSUE TITLE
Bug fixes for #5400, #7237 and #8174 in linprog(method='simplex')

### ISSUE THREAD

**Issue by Kai-Striega** [scipy/scipy#9076] opened 2018-07-26 07:12 UTC
Issues  #5400, #7237, #8174 occur when the simplex method updates with a pivot value very close to the given tolerance leading to very large tableau elements. The pivot values are `2.15e-12`, `4.38e-12`, `2.74e-12` respectively. Zeroing the tableau values below the tolerance after each iteration - `T[abs(T) < tol] = 0` - should fix these issues (I’ve tested this on #5400). Personally, I do not like this approach; it will only “cover-up” the issue and make debugging similar problems harder in the future. My preferred fixed would be something like this.

First in many cases these division can be avoided entirely. E.g. in #5400 by removing redundancies or applying Bland’s rule to select a different pivot (as in #7237).  The pre-solve technique from the interior-point solver could simplify the bounds but this should be co-ordinated with the HiGHS solver #8575.  Second (similar to #6139) return a non-zero status with a message to educate the user on why this bug occurs and possible fixes; increasing the tolerance, using Bland’s rule or using a pre-solver.

@mdhaber @rgommers Do you think these are reasonable changes?

**Comment by mdhaber** [comment] 2018-07-26 14:22
I agree that zeroing small elements sounds like a hack to avoid.

If what we're dealing with is numerical problems rather than a logical bug in the simplex code, reporting the difficulties is totally fine - and certainly better than returning an erroneous result. Even better if the error message is helpful and suggests things to try, like using a different pivot strategy, etc...

So if you can 1) detect when small pivots are used, 2) check for constraint violation before returning, and 3) include a helpful status message, that sounds perfect.

Let's make that one PR. I think it would allow us to close all these issues, right? 

With the issues out if the way, we're free to improve things like you suggested before. The interior point presolve can remove redundancy and simplify bounds, so if applying it before running simplex could prevent small pivots from being encountered, great. And I suppose if you're going to apply presolve before simplex, you might as well unify the input validation, conversion to standard form, and postsolve like you suggested before : )

These could be one or a few other PRs. 

While you're at it you may notice some awkwardness with presolve. Parts of that code are good, but some parts should be improved. If i remember correctly, I'm not happy with the way I removed variables from the problem. Bounds should be converted from a list of tuples to arrays as part of input validation/standardization (and the user should be allowed to specify bounds with arrays from the outset). Also, the option to iterate the presolve routine should be added, as sometimes simplifications enable the possibility of performing additional simplifications of a certain type that has already been attempted. This could be another good PR.

Finally, I think it is reasonable to write a revised simplex code even before we have sparse rank one updates. If sparse rank one updates become possible in the future, they can be worked in. (And dense rank-one updates are already possible, if I remember correctly.) I'm brushing up on the simplex method so I can help. (I'll try to help with presolve improvements, too.)

**Comment by Kai-Striega** [comment] 2018-07-27 13:49
@mdhaber Just a few thoughts:

I've submitted a PR #9081 adding warnings if the pivot value is close to the set tolerance, it still feels a bit off so I'd appreciate if someone could have a look over it. The checks if a returned solution is feasible have been intentionally left out for now. These would benefit both the simplex and interior-point methods. I think it's worth discussing how we merge the two before adding it, so it may be applied to both methods.

Using IP's presolver seems like a solid idea. So does reusing the remaining IP’s  functionality. The simplex implementation mixes the input cleaning and tableau construction which may need to be separated/cleaned-up before the interior-point's functions are added. For a common conversion to be useful #9008 will need to be addressed, or at a minimum figure out why the tests are passing when an improper tableau or basis is given. 

This seems like a good time to improve the presolver function =). I still need to read into your work more before I will be much use here. I agree with both iteratively applying presolve and converting the bounds to arrays... both methods do this at some point anyway.

I'm also in favour of writing a revised-simplex solver, but I think there's enough to be done just managing the two we already have.

**Comment by mdhaber** [comment] 2018-07-27 20:51
@Kai-Striega IP already has checks for feasibility in `_postprocess` (see line 981 of `_linprog_ip.py`).

I'm not sure that #9008  _has_ to be addressed. It might not be worth it. Maybe the bug in #9008 is not really a bug but a novel, magical variant of the simplex method : ) Anyway, I'm not going to suggest fixing it unless it seems to be causing incorrect results.

Would you try just replacing the call to `_ip_hsd` (Line 2147) with a call to `_linprog_simplex` (from `_linprog.py`)? That is:
```
_linprog_simplex(c, A_eq=A, b_eq=b)
```
and running all the tests that simplex is supposed to pass through that? It's sort of a long shot, but I can't see why it shouldn't work. I'm pretty sure that `A`, `b`, and `c` represent a perfectly normal linear programming problem in standard form at that point, and so it shouldn't matter how it gets solved. 

The tests that require Bland's rule will fail, and if you turn display on the objective function value will be off by a constand (`c0`), but if the other tests pass I think that it should be relatively straightforward to unify the two solvers from there.

I'll take a look at your PR.

Re: revised simplex - of course - first things first.

**Comment by Kai-Striega** [comment] 2018-07-28 05:07
@mdhaber Actually, having the problem in standard form should avoid the problem anyway. It occurs when formatting negative inequality constraints with artificial variables. If there are no negative inequality constraints in the first place it should work fine =).

Another point `_linprog_simplex`'s main functionality covers cleaning inputs/outputs and managing the two-phase transitions. `_solve_simplex` drives the `"actual"` simplex method. Giving `A, b, c` in standard equality form causes much of `_linprog_simplex` to be redundant. Aligning the  simplex and IP methods to both use variable substitutions should allow only using `_solve_simplex` with `postprocess` handling the clean-up for both methods.

**Comment by mdhaber** [comment] 2018-07-28 06:21
@Kai-Striega yes, I know that there was a lot of redundancy. trimming that out was part of what I meant by "unifying the two solvers from there"

**Comment by mdhaber** [comment] 2018-07-30 21:06
I think we need to re-open this until we at least apply the postsolve check for feasibility. The warning message is not quite enough to consider these issues closed; I think there needs to be an error with an infeasible solution. The tests should be updated to check for this error; once those are passing I think we can close this issue and all three of the others.

**Comment by mdhaber** [comment] 2018-09-12 06:28
I'm checking to see whether this is addressed. #5400 should not keep this open.

**Comment by mdhaber** [comment] 2018-09-12 06:44
OK, I think #9145 finished addressing this issue, because with default options we now get status 4 and message: "The solution does not satisfy the constraints, yet no errors were raised and there is no certificate of infeasibility or unboundedness."

However, the message continues: "This is known to occur if the `presolve` option is False and the problem is infeasible. If you encounter this under different circumstances, please submit a bug report. Otherwise, please enable presolve." which is not quite right any more.

That will need to be changed, but I think this issue is closed.

**Closed by mdhaber** 2018-09-12 06:44 UTC
Labels: maintenance, needs-decision, query, scipy.optimize
