### ISSUE TITLE
refguide: scipy.optimize.dual_annealing difference

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#9732] opened 2019-01-31 01:37 UTC
I'm seeing a single difference in the ref guide output.

### Reproducing code example:

```
$ python runtests.py -g  --refguide-check
```

### Error message:
```
==============
scipy.optimize
==============

scipy.optimize.dual_annealing
-----------------------------

File "build/testenv/lib/python3.6/site-packages/scipy/optimize/_dual_annealing.py", line 584, in dual_annealing
Failed example:
    print("global minimum: xmin = {0}, f(xmin) = {1:.6f}".format(
          ret.x, ret.fun))
Expected:
    global minimum: xmin = [-4.26437714e-09 -3.91699361e-09 -1.86149218e-09 -3.97165720e-09
     -6.29151648e-09 -6.53145322e-09 -3.93616815e-09 -6.55623025e-09
    -6.05775280e-09 -5.00668935e-09], f(xmin) = 0.000000
Got:
    global minimum: xmin = [-4.97631811e-09 -3.69101793e-09 -1.88357084e-10  1.37810900e-09
      5.06402684e-10  8.30841365e-10 -4.53443041e-09 -7.49711203e-10
     -4.17790512e-09 -2.58444857e-09], f(xmin) = 0.000000


ERROR: refguide or doctests have errors
```

Apparently the global minimum occurs at x = [0, 0, ..., 0]. The (absolute) differences between `expected` and the `returned` values are small, ~1e-10, and the function evaluates to 0 at both points, so both are reasonable stopping points. 

1. Is `dual_annealing` deterministic when given a rand seed?    
1. Is this difference only visible in my environment? Or does it appear for anyone else?

### Scipy/Numpy/Python version information:
```
1.3.0.dev0+a00b057 1.14.2 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment] 2019-01-31 03:59
`refguide_check.py` passes on current master for me. And I believe `dual_annealing` should be fully deterministic when seeded (pinging @sgubianpm for confirmation).

**Comment by rgommers** [comment] 2019-01-31 04:01
That's with numpy 1.15.4 though (and Python 3.6.4 from Anaconda).

**Comment by sgubianpm** [comment] 2019-01-31 09:36
@rgommers , @pvanmulbregt 
Sorry guys, the example is already seeded. Don't know why there is this difference then. Does something changed in numpy since regarding RGN?

**Comment by rgommers** [comment] 2019-01-31 23:54
There aren't any changes in the random number generation. So not sure what's happening here. @pvanmulbregt could you check if it depends on numpy version?

**Comment by pvanmulbregt** [comment] 2019-02-01 01:07
Same result with numpy 1.16.0, also from Anaconda.

### Scipy/Numpy/Python version information:
```
1.3.0.dev0+a00b057 1.16.0 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by sgubianpm** [comment] 2019-02-01 07:58
I am using ``check_random_state`` from ``scipy._lib._util`` with the provided seed value (can be integer or a random state value). I basically mimic ``basin hopping`` on this. Then seeds are consumed by calling ``random_sample()`` on the ``rand_state`` object. Still thinking where this could come from but no idea so far...

**Comment by rgommers** [comment] 2019-02-02 23:33
Had a closer look - there is something wrong with `dual_annealing` here I think. It seems to depend on the order of execution here, `refguide_check.py` passes but running the example manually gives me
```
In [3]: %paste

    >>> from scipy.optimize import dual_annealing
    >>> func = lambda x: np.sum(x*x - 10*np.cos(2*np.pi*x)) + 10*np.size(x)
    >>> lw = [-5.12] * 10
    >>> up = [5.12] * 10
    >>> ret = dual_annealing(func, bounds=list(zip(lw, up)), seed=1234)
    >>> print("global minimum: xmin = {0}, f(xmin) = {1:.6f}".format(
    ...       ret.x, ret.fun))

## -- End pasted text --
global minimum: xmin = [-4.64347813e-09 -4.69297688e-09 -5.49006902e-09 -3.24065415e-09
 -4.68002286e-09 -6.53216304e-09 -5.95086109e-09 -1.37868575e-09
 -7.01083895e-09 -5.38069312e-09], f(xmin) = 0.000000
```

**Comment by rgommers** [comment] 2019-02-02 23:42
Okay, can reproduce with `refguide_check.py` now as well:
```
$ python tools/refguide_check.py --doctests optimize
Running checks for 1 modules:
scipy.optimize ..........................................................................................F.....................................

==============
scipy.optimize
==============

scipy.optimize.dual_annealing
-----------------------------

File "scipy/optimize/_dual_annealing.py", line 584, in dual_annealing
Failed example:
    print("global minimum: xmin = {0}, f(xmin) = {1:.6f}".format(
          ret.x, ret.fun))
Expected:
    global minimum: xmin = [-4.26437714e-09 -3.91699361e-09 -1.86149218e-09 -3.97165720e-09
     -6.29151648e-09 -6.53145322e-09 -3.93616815e-09 -6.55623025e-09
    -6.05775280e-09 -5.00668935e-09], f(xmin) = 0.000000
Got:
    global minimum: xmin = [-4.64347813e-09 -4.69297688e-09 -5.49006902e-09 -3.24065415e-09
     -4.68002286e-09 -6.53216304e-09 -5.95086109e-09 -1.37868575e-09
     -7.01083895e-09 -5.38069312e-09], f(xmin) = 0.000000


ERROR: refguide or doctests have errors
```

My answer is different from @pvanmulbregt's, but always the same. So could still be the numpy RNG as well (although that is unlikely, because we have many tests relying on its exact sequence).

**Comment by rgommers** [comment] 2019-02-02 23:48
Adding `>>> print('Number of iterations: {}'.format(ret.nit))` shows that the example runs for 1000 iterations (so till `maxiter`), which isn't really desirable probably for an example.

**Comment by sgubianpm** [comment] 2019-02-06 08:38
We do observe minor differences between 1.2.0 and the 1.3dev on ``dual_annealing``. Could this come from the SciPy ``minimize`` local search that may have changed (it is used in ``dual_annealing``). A change in the RNG is indeed unlikely.

**Comment by sgubianpm** [comment] 2019-02-06 09:24
In the meantime, maybe in the example, we should only output 8 digits so that the example will always match the different scipy/numpy versions. Thoughts?

**Comment by ilayn** [comment] 2019-02-06 09:49
Interestingly, I get 

```bash
$ python .\tools\refguide_check.py --doctests optimize
Running checks for 1 modules:
scipy.optimize ......................................................................................F.........................................

==============
scipy.optimize
==============

scipy.optimize.check_grad
-------------------------

File "..\..\..\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy-1.3.0.dev0+b955206-py3.6-win-amd64.egg\scipy\optimize\optimize.py", line 796, in check_grad
Failed example:
    check_grad(func, grad, [1.5, -1.5])
Expected:
    2.9802322387695312e-08
Got:
    4.2146848510894035e-08
```

from running `python tools/refguide_check.py --doctests optimize` command. My setup is  `1.3.0.dev0+b955206 1.17.0.dev0+e269475 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)`

**Comment by sgubianpm** [comment] 2019-02-06 10:25
This may be a reason as ``dual_annealing`` is using gradient computation in the ``minimize`` calls. But this should impact also others methods.

**Comment by andyfaff** [comment] 2019-02-28 01:17
can reproduce with miniconda Python:
`3a3361c964e0c7c0543d4c4752a1b8fa0bab27d4, 1.15.4, sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)`

**Comment by andyfaff** [comment] 2019-02-28 01:37
I checked out 9a52acf, which was just when dual_annealing was merged, with the intention of git bisecting. However `python runtests.py -g -s optimize --refguide-check` still fails (`
1.15.4, sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0`).

This might indicate that either it's numpy/Python related.

**Comment by andyfaff** [comment] 2019-02-28 03:44
I've gone to Python3.6, with pip/conda installed numpy==1.14, and run the example (at 9a52acf) manually.
Whatever I try I get the same as @pvanmulbregt:

` x: array([-4.976318e-09, -3.691018e-09, -1.883571e-10,  1.378109e-09,
        5.064027e-10,  8.308414e-10, -4.534430e-09, -7.497112e-10,
       -4.177905e-09, -2.584449e-09])`

i.e. cannot reproduce the doctest value. It's a mystery as to why it ever passes/d

**Comment by rgommers** [comment] 2019-02-28 21:31
I think it's not python/numpy reproducibility of random numbers, we'd see that in other places. The example just isn't good - there are many solutions and somehow numerical noise is just giving different `x` values that all yield `f(xmin) = 0.000000`. The number of iterations is always exactly `maxiter` as well.

@sgubianpm can you explain this bit:
```
            val = strategy_chain.run(i, temperature)
            if val is not None:
                message.append(val)
                need_to_stop = True
                break
```
It seems like `strategy_chain.run` never returns a value for this example. The only way it does is if ` if e < self.energy_state.current_energy` is True:
```
            # Calling the objective function
            e = self.func_wrapper.fun(x_visit)
            if e < self.energy_state.current_energy:
                # We have got a better energy value
                self.energy_state.update_current(e, x_visit)
                if e < self.energy_state.ebest:
                    val = self.energy_state.update_best(e, x_visit, 0)
                    if val is not None:
                        if val:
                            return val
```

I'm not understanding some logic here - if a better energy value is found, `val` is returned and the while loop in `dual_annealing` then terminates immediately. Otherwise, it keeps going until `maxiter` (which is the case here even for very large `maxiter`) and returns the final value, which is apparently not deterministic (probably because of eps-sized differences in floating-point comparison variations between machines).

**Comment by sgubianpm** [comment] 2019-03-04 10:27
@rgommers, thanks for this.
This has been introduced with the callback mechanism for having the algorithm stopping if the callback returns ``True`` (only if the callback is defined by the user).
In this bit, if a better energy value is found, it calls ``update_best`` method from ``EnergyState`` instance This may call the callback (if defined). If the user defined callback returns ``True`` for some (user defined) reason, ``val`` is not ``None``, ``val`` is ``True``, and is returned by the ``run`` method of ``StrategyChain`` instance.
The while loop in the ``dual_annealing`` function will then stop if anything other than ``None`` is returned by the chain. This includes; callback returns ``True`` reason or maximum number of objective function evaluation reached.
I think that the logic is fine here. In the example, it is using the default ``maxiter`` value which is the expected behavior.
For a given Python/Numpy, the unit test ``test_reproduce`` in test__dual_annealing.py is checking (with assert_equals) the x coordinates of 3 different runs with seeding.
Don't you think that this is similar to @ilayn comment above for ``check_grad`` (and therefore as you mentioned floating-point issue between machines)?

**Comment by rgommers** [comment] 2019-03-08 20:22
thanks for the explanation @sgubianpm 

> Don't you think that this is similar to @ilayn comment above for check_grad (and therefore as you mentioned floating-point issue between machines)?

Yes, probably. We should just try to replace the example with one that has a single global minimum and see if it becomes reproducible then.

**Comment by mdhaber** [comment] 2022-11-19 18:01
The original refguide issue seems to have been resolved by appending `# random` at the end, so I'll close this.

If we're interested in understanding why `dual_annealing` does not produce the same vector of zeros on different machines, here is a different example with a single local minimum that is also the global minimum.
```python3
import numpy as np
from scipy.optimize import dual_annealing, minimize
np.set_printoptions(precision=20)
func = lambda x: np.sum(x*x)
bounds = np.array([[-5.12, 5.12]]*10)
ret = dual_annealing(func, bounds=bounds, seed=0)
ret.x
```
I get:
```
array([-1.0095076352634180e-07,  1.7694041115623449e-07,
        3.1744814987799685e-07, -2.5936135461535059e-08,
       -1.0437972752797009e-07,  4.9412265834547497e-07,
        4.0790139266277947e-08,  7.0676412278203316e-08,
        1.6263374114089402e-07, -6.8122159913031055e-08])
```
Hopefully, this is exactly reproducible on different machines. I could be persuaded otherwise, but I wouldn't be surprised to see floating point variation between machines amplified somewhat over the course of thousands of feedback loops. I think we've seen this in local minimizers, too. Do others get the same result here?
```python3
rng = np.random.default_rng(98234569802627)
func = lambda x: np.sum(x*x - 10*np.cos(2*np.pi*x)) + 10*np.size(x)
res = minimize(func, rng.random(10)*0.1, bounds=bounds)
res.x
# array([-7.3213350131356735e-09, -4.4885716685925209e-09,
#        -5.8678572172709794e-09, -9.2573999559912831e-09,
#        -8.0632850324774111e-09, -9.5405543288649615e-09,
#        -1.6220218156180330e-09, -9.8430355344942163e-09,
#        -2.8533392299796783e-09, -1.4143671253723397e-09])
```

FWIW, I think the Rastrigin function is good for the public example because it shows that `dual_annealing` is capable of finding the global minimum of a function with many local minima. All of the minimizers reported above are in the basin of the global minimum with very small error.

**Closed** 2022-11-19 18:02 UTC
Labels: scipy.optimize, Documentation
