### ISSUE TITLE
SciPy 1.3.0 vs. 1.2.0 sparse matrix type difference when indexing  

### ISSUE THREAD

**Issue by wasade** [scipy/scipy#10553] opened 2019-07-29 21:59 UTC
While debugging biocore/biom-format#816, we noticed that the return type of `__getitem__` for a sparse matrix object changed between SciPy versions. 

We did not see anything that stood out in the changelog regarding this, but we apologize if we overlooked something. We also attempted to identify what commit may have been associated with this but have so far not been successful. We would be happy to assist on or contribute a PR if one is appropriate here. 

#### Reproducing code example:

For SciPy 1.2.0:

```python
>>> import scipy.sparse as sp
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.0 1.15.4 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
>>> print(type(sp.csr_matrix([[0, 1.0, 2], [3, 4, 5]])[0, 0]))
<class 'numpy.float64'>
```

For SciPy 1.3.0:

```python
>>> import scipy.sparse as sp
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.0 1.16.3 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
>>> print(type(sp.csr_matrix([[0, 1.0, 2], [3, 4, 5]])[0, 0]))
<class 'numpy.ndarray'>
```

Behavior as observed with a 2D `np.array`:

```python
>>> print(type(np.array([[0, 1.0, 2], [3, 4, 5]])[0, 0]))
<class 'numpy.float64'>
```

**Comment by peterbell10** [comment] 2019-07-29 23:41
Thanks @wasade. This is a duplicate of gh-10206, fixed by gh-10207 and should be sorted in the upcoming 1.3.1 release (gh-10496).

**Closed by peterbell10** 2019-07-29 23:41 UTC

**Comment by wasade** [comment] 2019-07-29 23:58
Wonderful, and thank you for the rapid response!
