### ISSUE TITLE
Documentation build with scipy-sphinx-theme

### ISSUE THREAD

**Issue by frenzymadness** [scipy/scipy#8351] opened 2018-02-01 12:34 UTC
Hello.

I am trying to build Scipy RPM package in Fedora with -doc subpackages but now I am facing a strange issue.

I've changed `python setup.py build` to `python setup.py build_sphinx` and everything seems to work but not. The documentation part of the build log contains only a few tens of lines and it seems that not Scipy documentation is built but documentation for scipy-sphinx-theme is. And the result is also evidence of this.

![with theme](https://user-images.githubusercontent.com/5688939/35678340-38c5c9e4-0753-11e8-8992-999d006a7388.png)

So I tried to remove scipy-sphinx-theme from doc directory before the build and it seems help. Now the documentation seems to be complete but without the theme.

![without-theme](https://user-images.githubusercontent.com/5688939/35678383-70b76fb0-0753-11e8-8a4d-56906998d5c2.png)

Am I missing something? Is there any way how to prevent sphinx-theme being build instead of actual documentation?

Scipy version: 1.0.0
Sphinx version: 1.6.6
Complete RPM build log with theme: https://kojipkgs.fedoraproject.org//work/tasks/4211/24614211/build.log
Complete RPM build log without theme: https://kojipkgs.fedoraproject.org//work/tasks/5435/24615435/build.log

Let me know if I can do or provide something more.

Thanks for your help and have a nice day.

**Comment by rgommers** [comment] 2018-02-04 13:04
Don't use `setup.py`, go to `doc/` and use the Makefile there. If you want to build the docs the same way as they are on docs.scipy.org, use `make dist`.

**Comment by frenzymadness** [comment] 2018-02-05 07:56
Thank you for your response. I'll try to use Makefile instead of setup.py. It might be better to mark this way as a preferred way for building documentation in `doc/README.txt` where the setup.py way is mentioned in the first place as an easy way how to do it.

**Comment by rgommers** [comment] 2018-02-05 08:21
Hmm, you're right. Thanks for pointing that out. I'll see if I can reproduce your issue as well as update the build instructions.

**Comment by frenzymadness** [comment] 2018-02-05 11:28
Another question is, how can I build docs using `make html` with a fresh build of scipy with no need to install scipy first? I tried to change PYTONPATH to the location, where the scipy is built but I got the following error:
```
$ make PYTHONPATH=${PYTHONPATH}:.. PYVER=2.7 html
mkdir -p build/html build/doctrees
LANG=C python2.7 /usr/libexec/python2-sphinx/sphinx-build -b html -d build/doctrees   source build/html 
Running Sphinx v1.6.6

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 58, in <module>
    import scipy
  File "/builddir/build/BUILD/scipy-1.0.0/scipy/__init__.py", line 106, in <module>
    raise ImportError(msg)
ImportError: Error importing scipy: you cannot import scipy while
        being in scipy source directory; please exit the scipy source
        tree first, and relaunch your python intepreter.

make: *** [Makefile:103: html] Error 1
```

**Comment by rgommers** [comment] 2018-02-05 15:54
I assume you have built scipy already with `python setup.py build_ext -i`? In that case that command shouldn't give this error. If you didn't build in-place, but did `python setup.py build`, then adding it to PYTHONPATH will result in the error you see.

Split it in two lines maybe for clarity and use the full path:

    export PYTHONPATH=/builddir/build/BUILD/scipy-1.0.0/:${PYTHONPATH}
    make PYVER=2.7 html

**Comment by rgommers** [comment] 2018-02-05 16:03
I cannot reproduce the original issue here, for me the html docs build fine and end up in `build/sphinx/html/index.html`. The build log does look quit odd, it looks like the `build_sphinx` command runs `cythonize.py` and does the compiler configuration multiple times.

**Comment by rgommers** [comment] 2021-02-06 20:15
There's now a `doc/README.md`, so closing this issue.

**Closed by rgommers** 2021-02-06 20:15 UTC
Labels: Build issues, Documentation
