### ISSUE TITLE
scipy/sparse/linalg/isolve/ is missing _iterative.py

### ISSUE THREAD

**Issue by anmol1e1** [scipy/scipy#11109] opened 2019-11-22 17:08 UTC
The folder `Python37\site-packages\scipy\sparse\linalg\isolve\` inside Scipy package in Python has the following file: `_iterative.cp37-win_amd64.pyd`.

When I run a Python file, I get the following error :- <br/>
```
File "C:\......\Python37\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 10, in <module>
    from . import _iterative
ImportError: DLL load failed: The specified module could not be found
```

Scipy should work out of the box after installation!

**Comment by ilayn** [comment] 2019-11-22 17:17
Duplicate of #11062

**Closed by ilayn** 2019-11-22 17:17 UTC
Labels: Build issues, duplicate
