### ISSUE TITLE
Improve documentation for Elliptic Integrals

### ISSUE THREAD

**Issue by Noxbru** [scipy/scipy#7141] opened 2017-03-08 18:28 UTC
This afternoon I have been writing code that relies in both elliptic integrals (`scipy.special.ellipk` and `scipy.special.ellipe`) but I was getting completely wrong values.

This has been until I realized that scipy defines the elliptic integrals in a different that wikipedia or other resources do.

For example, [wikipedia](https://en.wikipedia.org/wiki/Elliptic_integrals) and Wolfram MathWorld [First Kind](http://mathworld.wolfram.com/EllipticIntegraloftheFirstKind.html) and [Second Kind](http://mathworld.wolfram.com/EllipticIntegraloftheSecondKind.html) define the complete integral of first kind as:

K(x) = int_0^(pi/2) dy / sqrt(1 - x^2 sin^2 y)

While scipy documentation defines it as:

K(x) = int_0^(pi/2) dy / sqrt(1 - x sin^2 y)

Note the lack of a square in the x.

So, problem:
- Different definition of what an elliptic integral is from what would be expected.

Proposed fix:
- Change the implementation of the functions to match that of the more usual version.
- Improve the documentation by including a (possibly in red or some bright colour) note saying that the parameter you pass doesn't get squared, or that you are calculating the integrals of the square root of the parameter.

**Comment by WarrenWeckesser** [comment] 2017-03-08 18:41
This is a duplicate of https://github.com/scipy/scipy/issues/3618, but I'll leave it open because of the specific suggestion to improve the documentation.  It sounds like a good idea to note the different conventions in the docstring, and add a reference to the appropriate section of Abramowitz and Stegun.

**Comment by person142** [comment] 2017-03-08 18:42
But in particular, we shouldn't do

> Change the implementation of the functions to match that of the more usual version

which will break existing code for a not-good-enough reason.

**Comment by person142** [comment] 2017-03-08 18:50
And now that I think about it, there is a good reason for using `m` instead of `k^2`--it allows you to do something like

```python
>>> import scipy.special as sc
>>> sc.ellipk(-1.0)
1.3110287771460598
```

without having to resort to complex arguments.

**Comment by WarrenWeckesser** [comment] 2017-03-08 18:54
> ... and Wolfram MathWorld First Kind 

Note that the function `EllipticK(m)` in Wolfram Alpha agrees with `scipy.special.ellipk`.  For example, in Wolfram Alpha, [`EllipicticK(0.9)`](https://www.wolframalpha.com/input/?i=EllipticK(0.9)) is 2.57809..., and in scipy,

```
In [37]: from scipy.special import ellipk

In [38]: ellipk(0.9)
Out[38]: 2.5780921133481733
```

**Comment by pv** [comment] 2017-03-08 19:33
I don't really think it's correct to characterize the definition as unusual, so the only thing to add is probably a mention that there are also a second commonly used definition.

**Comment by Noxbru** [comment] 2017-03-08 19:56
@WarrenWeckesser sorry, I had only checked on open issues. Also, I don't own mathematica, so I coudn't check it.

@person142 I agree that changing the behaviour will break a lot of things, that's why the issue refers to documentation and I add a suggestion to improve it.

@pv Honestly, I don't know how many people would use A&S or Mathematica as a primary source as oposed to wikipedia.

**Comment by ewmoore** [comment] 2017-03-08 20:10
@Noxbru Look at wikipedia again.  The need to take care with notation has a small section dedicated to in your very first link.  https://en.wikipedia.org/wiki/Elliptic_integral#Notational_variants

**Comment by Noxbru** [comment] 2017-03-08 21:09
@ewmoore I see, what I did was just look in the index for the complete versions and just jumped there. Maybe we should edit wikipedia to add that scipy also uses that convention.

Anyway, I still think that at least a small 'please note that this is the convention we use' would be nice in the documentation.

**Comment by person142** [comment] 2017-03-08 21:18
> Anyway, I still think that at least a small 'please note that this is the convention we use' would be nice in the documentation.

Agreed, want to add it?

**Closed** 2017-03-09 05:46 UTC
Labels: Documentation, easy-fix
