### ISSUE TITLE
Python 3.10 manylinux wheels

### ISSUE THREAD

**Issue by hrnciar** [scipy/scipy#14567] opened 2021-08-09 08:26 UTC
Hello.

Could you please release CPython 3.10 manylinux wheels on PyPI? 

Python 3.10.0 release candidate 1 was released this week: https://www.python.org/downloads/release/python-3100rc1/

It should be quite safe to release wheels for release candidate. ABI for Python 3.10 should be frozen from now on, even for bugfixes. From release notes: 

> There will be no ABI changes from this point forward in the 3.10 series and the goal is that there will be as few code changes as possible.

Thank You.

**Comment by ilayn** [comment] 2021-08-09 08:31
We are always waiting for the official release and not for any RCs that might come out until then. This is to reduce the maintainer efforts to adapt to changes between release candidates and the official release.

**Comment by andyfaff** [comment] 2021-08-09 08:44
Scipy is being tested against 3.10 in the ci matrix. However nightly wheels, https://anaconda.org/scipy-wheels-nightly/scipy/files?page=1 aren't being built for 3.10 yet.

**Comment by andyfaff** [comment] 2021-08-09 08:45
3.10 wheels won't be available on pypi until after the official release of 3.10.

**Comment by hrnciar** [comment] 2021-08-09 09:02
I am a member of Fedora Python maintenance team and we would like to encourage upstreams of important Python packages to release manylinux wheels as soon as possible.  The reason I am asking for this is that on Fedora 35 Python 3.10 is the main Python interpreter and users might run into troubles when installing `scipy` using `pip`.

Unlike previous main Python releases, Python 3.10 is the first major release with ABI frozen when the first release candidate was released. Hence there is a minimal risk of troubles in future because ABI will remain the same for all upcoming release candidates and the official release. Would you be willing to reconsider this? Thank you.

**Comment by andyfaff** [comment] 2021-08-09 09:23
Fedora appears to have a scipy 1.7.0 RPM. What proportion of Fedora users use rpms vs pip?

**Comment by matthew-brett** [comment] 2021-08-09 09:32
In the past, we have resisted releasing wheels for release candidate Pythons because of the risk of ABI changes, so the wheels would then be broken.   In the past this has caused some chaos with each new Python release, as the wheels slowly catch up.   Freezing the ABI for the RC is a really substantial improvement in process here - and agree - I think we should release wheels for the RC as soon as possible.  I'll look into what needs doing for the wheel machinery.

**Comment by hroncok** [comment] 2021-08-09 09:35
Unfortunately, we don't have any real data for that. Only assumptions.

Some users prefer to `sudo dnf install pytohn3-scipy` and use the RPM scipy package built by the distro.
Many non-Pythonistas will install scipy like that as a dependency of various applications packaged in Fedora.

But many others, usually Python developers (incl. beginners), will install scipy via pip to various virtual environments. Since Python 3.10 will be the "main" Python version, by default, their new virtual environments will be Python 3.10.

**Comment by hroncok** [comment] 2021-08-09 09:37
Also note that wheels can have build numbers. In the unlikely event that the promise of not changing the ABI is not delivered, it is possible to build a new wheel of the same version, see e.g. https://twitter.com/uranusjr/status/1423373475788431361

**Comment by tylerjereddy** [comment] 2021-08-10 01:59
Hmm, I'll keep an eye on what the NumPy team decides to do in the matching issue you opened in their repo: https://github.com/numpy/numpy/issues/19630

Even small changes to the release process can generate a fair bit of entropy for a big project, so I'm always a bit cautious with volunteered time of course.

**Comment by tupui** [comment] 2021-08-11 14:49
Since NumPy released a wheel now, I guess we should do the same.

**Comment by rgommers** [comment] 2021-08-18 21:42
@tylerjereddy it requires a `1.7.2` release to put wheels on PyPI (because at least `python_requires` needs a bump), so I think we should aim to bunch it with support for macOS `arm64`.

**Comment by tylerjereddy** [comment] 2021-08-20 13:32
@rgommers that sounds good--I didn't really make much progress anyway

**Comment by rgommers** [comment] 2021-09-30 13:29
arm64 macOS is turning out to be a bit hairier than expected, and Python 3.10.0 release date is in 5 days - so we should probably separate the two. Will try to find some time to add 3.10 support to https://github.com/MacPython/scipy-wheels before then.

**Comment by tupui** [comment] 2021-09-30 13:31
> arm64 macOS is turning out to be a bit hairier than expected, and Python 3.10.0 release date is in 5 days - so we should probably separate the two. Will try to find some time to add 3.10 support to https://github.com/MacPython/scipy-wheels before then.

@rgommers if it's similar to what I did with the removal of 3.7, I can help if needed 😃

**Comment by rgommers** [comment] 2021-09-30 14:11
@tupui yes that would be nice. Adding 3.10 jobs analogous to the 3.9 ones for Azure, Appveyor and TravisCI.

**Comment by tupui** [comment] 2021-09-30 14:28
@tylerjereddy since you already have this open, do you take care of this task then?

**Comment by tylerjereddy** [comment] 2021-09-30 14:29
I'll close mine and try to help with your attempt? Hopefully you can just do what Ralf says (fingers crossed). For some reason I was slightly worried about manylinux version stuff which I thought we had been putting off for a bit longer than we should, but maybe we'll get away with something simple.

**Comment by tupui** [comment] 2021-09-30 14:30
Ok sure, I will do the PR soon.

**Comment by tupui** [comment] 2021-09-30 14:43
Ok done let's see how wrong this is 😅🤞

**Comment by yashk2810** [comment] 2021-10-08 02:46
Since Python 3.10 has been released, when will scipy release an official version compatible with 3.10?

**Comment by tupui** [comment] 2021-10-15 06:21
> Is it possible to make a linux release only for 3.10 just like what Numpy is doing?

It's possible, but we don't have the man-power for making n-releases a year. You can grab nightly wheels for linux if you really can't wait more https://anaconda.org/scipy-wheels-nightly/scipy/files

**Comment by rgommers** [comment] 2021-10-29 21:32
> Would it make sense to add wheels to the 1.7.1 release on PyPI, instead of waiting for a new release?

The real work here is to add 3.10 jobs to CI in this repo and the scipy-wheels repo, the rest is a few bug fix backports. So it's about as much effort to do `1.7.2` as it is to do `1.7.1`. Also, the `1.7.1` metadata says `python_requires < 3.10`, so we cannot just upload wheels.

**Comment by andyfaff** [comment] 2021-10-29 21:47
3.10 is being tested on Linux, but not macOS

**Comment by tylerjereddy** [comment] 2021-10-30 02:09
FWIW, the current attempt to backport 3.10 support to the 1.7.x series, which builds on the main branch work of many others (including generous help from the NumPy team as well), is here: https://github.com/MacPython/scipy-wheels/pull/135

The Windows 3.10 wheel tests seem to be passing, and so do the Linux 3.10 wheel tests, which is great.

MacOS is a super-confusing situation where I believe we have no choice but to ship universal 2 wheels even though we only want to provided 3.10 Intel support and are not ready to provide M1 native support yet. It feels awkward/fishy--open to better ideas here (also it fails the CI there at the moment..).

**Comment by charris** [comment] 2021-10-30 02:23
I suspect your best option in the short term is to release without 3.,10 support for Mac. The clang compile problems are probably fixable, but it would be much easier for someone who had access to it to track down. It would be worth trying universal wheels for 3.9 just to see if the problem is xcode version dependent, but I don't expect that to work either :)

**Comment by olivierlefloch** [comment] 2021-10-30 02:28
Put of curiosity are there nightly source distributions (as opposed to pre
built wheels)? That would make checking for compatibility a bit easier
while waiting for the final release. I only saw wheels on the
aforementioned nightly mirror.

**Comment by andyfaff** [comment] 2021-10-30 02:52
Willing to help build/test things, but I've only got an Intel Mac running 11.6. note that no Mac CI machines would be testing the arm64 component anyway.

**Comment by cbrnr** [comment] 2021-10-30 06:31
> I suspect your best option in the short term is to release without 3.,10 support for Mac.

Please don't do that. Just because M1 support cannot be tested at the moment (building works fine), this is no reason to preventing Intel Mac users (the majority I guess) from 3.10 support.

**Comment by tylerjereddy** [comment] 2021-10-30 21:37
In a debug branch (https://github.com/MacPython/scipy-wheels/pull/136) the Python `3.10` MacOS x86_64 wheel build stage does appear to succeed after hacking a `multibuild` branch and also forcing `export ARCHFLAGS="-arch x86_64"`. The latter change was the main thing that helped really though, so we may be able to simplify the changes that are actually needed (it looks like either XCode and/or the Python itself was insisting on injecting `-arch arm64` even if I told `multibuild` not to, and there are reports of this in other projects that also used the `ARCHFLAGS` workaround in other situations).

My main concerns now are:
- the test suite for that wheel has quite a few failures, many of them apparently related to "large" dtypes like `float128` and `complex256` for array comparisons in `sparse` tests--suggestions on the nature of the problem? need to adjust the compile flags with 3.10 a bit more or?
- some of the paths, and indeed the wheel itself, still get incorrectly labelled as universal2 despite my disabling of the `arm64` flag/fusion steps, i.e., `scipy-1.7.2.dev0+1272.5f587c6-cp310-cp310-macosx_10_9_universal2.whl`

**Comment by tylerjereddy** [comment] 2021-10-30 21:55
Chuck's comment (https://github.com/MacPython/scipy-wheels/pull/135#issuecomment-955597287) makes me wonder about stuff like the x86_64 wheel build getting packaged/combined with the wrong shared objects or something if some part of the control flow is still labeling the final product as `universal2`, but that's wild speculation.

**Comment by charris** [comment] 2021-10-30 22:37
It might be worth tracking down how the thin arm64 wheels are produced by universal2. @isuruf Thoughts?

**Comment by isuruf** [comment] 2021-10-30 22:42
That should be taken care of by https://github.com/multi-build/multibuild/blob/b89bb903e94308be79abefa4f436bf123ebb1313/osx_utils.sh#L460

**Comment by charris** [comment] 2021-10-31 03:11
@isuruf The problem with SciPy is that they want a stand alone x86_64 wheel because M1 is not yet supported. The universal2 code produces stand alone M1 wheels as well as the universal wheel, but no stand alone Intel wheels. The usual method of producing stand alone wheels does not work with Python 3.10.

**Comment by andyfaff** [comment] 2021-10-31 03:53
If it's difficult to make a wheel from the normal multibuild code we could add an extra step to the existing CI job on GH actions that would make a wheel.

**Comment by isuruf** [comment] 2021-10-31 07:04
@charris, you have to add a Py3.10 normal job instead of a universal2 job there.

**Comment by isuruf** [comment] 2021-10-31 07:07
nvm, I was looking at a wrong log

**Comment by isuruf** [comment] 2021-10-31 07:15
See https://github.com/multi-build/multibuild/pull/438

**Comment by rgommers** [comment] 2021-10-31 09:00
> If it's difficult to make a wheel from the normal multibuild code we could add an extra step to the existing CI job on GH actions that would make an Intel wheel.

That doesn't work. We need to use multibuild (now) or cibuildwheel (likely in the future). Building a wheel for use on the system you build it on is easy, but building it so it is redistributable, vendoring and name-mangling libraries, using auditwheel et al. to ensure it runs on older systems etc. is tricky.

**Comment by tylerjereddy** [comment] 2021-10-31 14:20
@isuruf Is that really going to give me different results than i.e.,: https://github.com/tylerjereddy/multibuild/commit/aad1f9b67a7b665a7759dea0b6d6389c711bf497

(i.e., I think I already hacked to get the desired code path one way or another)

**Comment by isuruf** [comment] 2021-10-31 14:25
Not really. I'll try to see what's going on.

**Comment by isuruf** [comment] 2021-10-31 14:30
@tylerjereddy, it looks like that in that branch you are testing you don't have https://github.com/MacPython/scipy-wheels/blob/880834995fa372d9ab6b51c2302a58283ce86e92/config.sh#L14

**Comment by tylerjereddy** [comment] 2021-10-31 14:36
hmm, I did delete a bunch of stuff to debug at some point; it shouldn't be hard to try your branch as well--will try that later

**Comment by isuruf** [comment] 2021-10-31 16:42
It's not the multibuild branch. You need the changes in `master` of `scipy-wheels` applied to `1.7.x` branch.

**Comment by tylerjereddy** [comment] 2021-10-31 22:40
Alright, I've opened https://github.com/MacPython/scipy-wheels/pull/137 against `master` of the wheels repo to see if we can observe a successful MacOS `3.10` x86_64 wheel build/test cycle there before I spend more time worrying about the backport. It is temporarily pointing to Isuru's `multibuild`repo & branch, and specifies `x86_64` for `PLAT`, but for now I will see if it does "ok" without `export ARCHFLAGS="-arch x86_64"` on the SciPy side.

**Comment by tylerjereddy** [comment] 2021-10-31 22:43
Hmm, something is wrong there.. the backport one gets a lot farther.. I imagine something simple to be fixed somewhere before I can see what's really going to happen.

**Comment by isuruf** [comment] 2021-10-31 22:49
@tylerjereddy, my branch was not merged with multibuild devel branch. Can you try updating again?

**Comment by tylerjereddy** [comment] 2021-10-31 22:52
done

**Comment by tylerjereddy** [comment] 2021-10-31 23:44
The MacOS Python `3.10` x86_64 test suite results are basically the same using Isuru's `multibuild` branch and `master` of the wheels repo and my various `multibuild` hacks on the wheels repo backport, so I'm not really convinced that I need to backport a ton more stuff on `config.sh` as long as x86_64 codepath is triggered one way or the other, though we probably will do that because at least the wheel has a more appropriate name and there is less random hacking of `multibuild` that way.

- Backport debugging/hacking (https://github.com/MacPython/scipy-wheels/pull/136) : `485 failed, 32060 passed, 2110 skipped, 104 xfailed, 10 xpassed, 199 warnings in 645.53s (0:10:45)`
- `master` debugging/less hacking (https://github.com/MacPython/scipy-wheels/pull/137) : `= 489 failed, 33199 passed, 2402 skipped, 106 xfailed, 10 xpassed, 202 warnings in 596.52s (0:09:56) =`

So, are we getting hamstrung by `python.org` only offering a `macOS 64-bit universal2 installer`? Do we need to build our own MacOS Python `3.10` for x86_64 to avoid the type size issues? Or is this something else?

**Comment by isuruf** [comment] 2021-11-01 01:07
> Do we need to build our own MacOS Python 3.10 for x86_64 to avoid the type size issues? 

Can you explain what the type size issues are?

**Comment by isuruf** [comment] 2021-11-01 16:23
Ah yes. `_numpyconfig.h` is wrong on universal2 wheels for x86_64. We'll have to build numpy x86_64 thin wheels for this to work.

**Comment by isuruf** [comment] 2021-11-01 16:26
Opened https://github.com/MacPython/numpy-wheels/issues/140

**Comment by tylerjereddy** [comment] 2021-11-01 16:33
oh great, that sounds like exactly what we need fixed

**Comment by tylerjereddy** [comment] 2021-11-05 03:05
Following the upstream NumPy release and multibuild improvements, I've made some updates to attempt the `3.10` backport process again in the wheels repo: https://github.com/MacPython/scipy-wheels/pull/135#issuecomment-961591589

**Comment by tylerjereddy** [comment] 2021-11-05 22:17
An attempt to build the official wheels for SciPy `1.7.2` is now underway. (MacOS will be 3.10 x86_64 thin-only for this set of wheels; other platforms that we usually support will be 64-bit only for 3.10).

**Comment by tupui** [comment] 2021-11-06 11:28
Thanks @tylerjereddy 🙏 Great to see this release!

**Comment by hroncok** [comment] 2021-11-06 11:36
Thank you!

**Comment by rgommers** [comment] 2021-11-06 12:55
https://pypi.org/project/scipy/1.7.2/#files has an almost complete set of Python 3.10 wheels, all that's left is 32-bit Windows. NumPy also doesn't have 32-bit Windows wheels for 3.10, so nothing can be done until those materialize.

> other platforms that we usually support will be 64-bit only for 3.10).

- There already are 32-bit manylinux wheels; we're just dropping those for 1.8.x and onwards.
- Maybe I'm misremembering, but isn't this a temporary situation for `win32`?

**Comment by charris** [comment] 2021-11-06 14:40
> Maybe I'm misremembering, but isn't this a temporary situation for win32

Azure doesn't support it, evidently Microsoft want to move away from 32 bits for windows starting next spring (vs2022). We could probably push to add it, or use another platform to build the wheels, but I'm happy to go along with Microsoft here. It was a considered opinion on their part and there wasn't any push back.

**Comment by rgommers** [comment] 2021-11-06 14:51
Oh okay, I am misremembering then, thanks Chuck. Then we should be all good here; support for macOS arm64 is another issue. So closing this.

**Closed by rgommers** 2021-11-06 14:51 UTC
Labels: Official binaries
