### ISSUE TITLE
ImportError: cannot import name 'Type'

### ISSUE THREAD

**Issue by josh-ashkinaze** [scipy/scipy#12021] opened 2020-05-04 12:30 UTC
Hi, 

Whenever I try to import scipy I get this error regarding 'Type'. 

I am using Python 3.5.1

```
import scipy
```

```
Traceback (most recent call last):
  File "/Users/ashkij/Downloads/asd.py", line 1, in <module>
    import scipy
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/__init__.py", line 156, in <module>
    from . import fft
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/fft/__init__.py", line 76, in <module>
    from ._basic import (
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/_lib/uarray.py", line 27, in <module>
    from ._uarray import *
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/_lib/_uarray/__init__.py", line 114, in <module>
    from ._backend import *
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/_lib/_uarray/_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'
[Finished in 0.4s with exit code 1]
[cmd: ['python3', '-u', '/Users/ashkij/Downloads/asd.py']]
[dir: /Users/ashkij/Downloads]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

**Comment by ilayn** [comment] 2020-05-04 12:41
Duplicate of #11356

**Closed by ilayn** 2020-05-04 12:41 UTC

**Comment by agrawalanshul053** [comment] 2021-06-14 19:14
Please tell the final solution for this problem

**Comment by ilayn** [comment] 2021-06-14 19:56
See the duplicate marked above please
