### ISSUE TITLE
scipy.fftpack.rfft takes forever for an array of 450001 elements

### ISSUE THREAD

**Issue by claudiodsf** [scipy/scipy#10228] opened 2019-05-28 16:42 UTC
Hi,
The following code runs without problems:

```python
import numpy as np
from scipy.fftpack import rfft
rfft(np.random.random(450000))
```

while this one takes forever:

### Reproducing code example:
```python
import numpy as np
from scipy.fftpack import rfft
rfft(np.random.random(450001))
```

### Scipy/Numpy/Python version information:

tested on macOS 10.14.5:
```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

and Debian 9.9:
```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.18.1 1.12.1 sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)
```

**Comment by peterbell10** [comment] 2019-05-28 16:51
This is a duplicate of #2629 and is being actively worked on. Once pocketfft is added (see #10175), prime sized ffts will be much faster thanks to bluestein's algorithm.

**Comment by rgommers** [comment] 2019-05-28 17:54
thanks for answering the question @peterbell10. this is a duplicate, so closing.

thanks for reporting @claudiodsf

**Closed by rgommers** 2019-05-28 17:54 UTC
