### ISSUE TITLE
scipy.stats.mstats.winsorize

### ISSUE THREAD

**Issue by smalltoe** [scipy/scipy#7656] opened 2017-07-25 22:22 UTC
Not possible to set argument inclusive=(False, False)

### Reproducing code example:
```
    a= [[2.19376284551822], [1.36477815816063], [1.35502940072563], [1.3415273880688], [1.33842516846894], [
        0.934908974768445], [0.93275704430222], [0.800210166819913]]

    aa=winsorize(a, limits=[0.05, 0.05], inclusive=(False, False))
```

### Error message:
```
Traceback (most recent call last):
  File "/home/tk3mh/pyspimp/spi-multi-premia/calculation/cwinsorize.py", line 14, in <module>
    terrerst()
  File "/home/tk3mh/pyspimp/spi-multi-premia/calculation/cwinsorize.py", line 10, in terrerst
    aa=winsorize(a, limits=[0.05, 0.05], inclusive=(False, False))
  File "/home/tk3mh/pyspimp/lib64/python3.4/site-packages/scipy/stats/mstats_basic.py", line 1848, in winsorize
    return _winsorize1D(a.ravel(), lolim, uplim, loinc, upinc).reshape(shp)
  File "/home/tk3mh/pyspimp/lib64/python3.4/site-packages/scipy/stats/mstats_basic.py", line 1817, in _winsorize1D
    a[idx[:lowidx]] = a[idx[lowidx]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Process finished with exit code 1
```

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.0 sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)

```

**Comment by rgommers** [comment] 2017-07-26 17:38
@smalltoe thanks for the bug report. 

This is caused by the change in numpy for boolean indexing/subtraction it looks like. Should be straightforward to fix.

**Comment by vbasu** [comment] 2017-07-27 22:45
I was taking a look at this, and it seems like an issue is that when either inclusive argument is false, lowidx (or updix) is the result of numpy.round, so a float. Is using numpy's astype(int) function, e.g. adding .astype(int) to https://github.com/scipy/scipy/blob/master/scipy/stats/mstats_basic.py#L1821 and the other bound an acceptable solution?

Related, scipy doesn't appear to have a test that checks winsorize's inclusive argument. Is this sort of a test excessive, or would it be helpful if I tried to write one?

**Comment by rgommers** [comment] 2017-07-28 06:28
> adding .astype(int) .. and the other bound an acceptable solution?

Converting to integer looks like the right solution. It's not clear to me immediately that ``round(.., astype(int)`` gives the  documented behavior though, but that's straightforward to verify.

> Related, scipy doesn't appear to have a test that checks winsorize's inclusive argument. Is this sort of a test excessive, or would it be helpful if I tried to write one?

Yes a test is definitely a good idea. Actually we'd require it when reviewing a fix, otherwise we won't know if the problem stays fixed:)

**Comment by aadithpm** [comment] 2018-10-07 17:11
Hey, is the issue still open? I'm looking to contribute, if that's okay :)

**Comment by AtsushiSakai** [comment] 2020-02-09 12:13
@rgommers Hi. This issue seems already to be fixed.
I run the Reproducing code example, and there is no error. So I think you can close this issue. 
Thanks.

**Closed** 2020-02-09 12:23 UTC
Labels: defect, good first issue, scipy.stats
