### ISSUE TITLE
DOC: update scipy.stats.truncnorm.rvs example

### ISSUE THREAD

**Issue by leweex95** [scipy/scipy#18316] opened 2023-04-17 16:35 UTC
### Describe your issue.

When creating a truncated normal distribution with a mean of 0.95 and two truncation points at 0.9 and 1.0, I expect that when sampling from the distribution using the `.rvs()` method, all values should be between 0.9 and 1.0, and they should concentrate around the mean of 0.95. 

Instead of this expected behavior, the below attached code shows that the smallest sampled value is around 0.995; hence only the top 5% of the (0.9, 1.0) interval is sampled. This is comfirmed by the histogram plotted in the below code.

Is this a bug, or am I overlooking something?

### Reproducing Code Example

```python
import matplotlib.pyplot as plt
import scipy.stats as stats

samples = stats.truncnorm.rvs(a=0.9, b=1.0, loc=0.95, scale=0.05, size=100000)
print(min(samples))
plt.hist(samples, bins=50)
plt.show()
```
```


### Error message

```shell
No error message.
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.24.2 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.33",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.12.1",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-v_zt9njv\\overlay\\Lib\\site-packages\\pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.18",
      "detection method": "pkgconfig",
      "include directory": "c:/opt/openblas/if_32/64/include",
      "lib directory": "c:/opt/openblas/if_32/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= PRESCOTT MAX_THREADS=4",
      "pc file directory": "c:/opt/openblas/if_32/64/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.18",
      "detection method": "pkgconfig",
      "include directory": "c:/opt/openblas/if_32/64/include",
      "lib directory": "c:/opt/openblas/if_32/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= PRESCOTT MAX_THREADS=4",
      "pc file directory": "c:/opt/openblas/if_32/64/lib/pkgconfig"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-dskf9r9k\\cp310-win_amd64\\build\\venv\\Scripts\\python.exe",
    "version": "3.10"
  }
}
```

**Comment by mdhaber** [comment] 2023-04-17 16:42
I will take a close look later, but it is probably not a bug. The `truncnorm` documentation says:
![image](https://user-images.githubusercontent.com/6570539/232553391-3eef1bda-cfb9-4484-9f50-8c0acbcaf512.png)

This is often a source of confusion around the behavior of the truncated distributions.
I suspect that it is not a coincidence that the `scale` is 0.05 and only the top 5% is being sampled.

**Comment by leweex95** [comment] 2023-04-17 16:51
Thanks for your response @mdhaber. 

I checked the documentation before posting here but it wasn't clear in solving my issue. It might very well be that I misunderstand the way this method is to be used; in such a case please let me know how I can create a truncated normal distribution with center at 0.95 and scale of 0.05, truncated at 0.9 and 1.0, if not this way:

`stats.truncnorm.rvs(a=0.9, b=1.0, loc=0.95, scale=0.05, size=100000)`

**Comment by leweex95** [comment] 2023-04-17 19:06
I agree that it would likely make the doc much more informative.

Thanks a lot; indeed I overlooked that part of the code! Now it makes sense!

**Comment by mdhaber** [comment] 2023-04-17 22:12
To close this issue, I'd suggest a PR that:

- Adds this code (with explanatory text) as an example
- Mentions the example in the notes (which discuss this issue)

**Comment by Oddball777** [comment] 2023-04-27 14:44
@mdhaber I'd like to contribute to this issue. Can someone point me to where the code examples are defined? I've looked through the documentation and have only found "%(examples)s" where they should be.

**Comment by mdhaber** [comment] 2023-04-27 16:25
Yeah, that's some sort of magic that automatically generates examples. You can see what it produces in the rendered documentation. You can add your example either above or below it, or you can replace it entirely if yours covers the same uses.

**Comment by Oddball777** [comment] 2023-04-27 18:12
And these automatically generated examples don't show up in the editor when using the function right? So ideally, should these be replaced with hardcoded examples so that we can see them everywhere, not just in the rendered documentation?

**Comment by mdhaber** [comment] 2023-04-27 18:15
There are many problems with the distribution documentation, but that is not one of them:
```
In [2]: from scipy.stats import truncnorm
help(truncnorm)
Help on truncnorm_gen in module scipy.stats._continuous_distns:
<scipy.stats._continuous_distns.truncnorm_gen object>
    A truncated normal continuous random variable.
    
    As an instance of the `rv_continuous` class, `truncnorm` object inherits from it
    a collection of generic methods (see below for the full list),
    and completes them with details specific for this particular distribution.
    
    Methods
    -------
    rvs(a, b, loc=0, scale=1, size=1, random_state=None)
        Random variates.
    pdf(x, a, b, loc=0, scale=1)
        Probability density function.
    logpdf(x, a, b, loc=0, scale=1)
        Log of the probability density function.
    cdf(x, a, b, loc=0, scale=1)
        Cumulative distribution function.
    logcdf(x, a, b, loc=0, scale=1)
        Log of the cumulative distribution function.
    sf(x, a, b, loc=0, scale=1)
        Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
    logsf(x, a, b, loc=0, scale=1)
        Log of the survival function.
    ppf(q, a, b, loc=0, scale=1)
        Percent point function (inverse of ``cdf`` --- percentiles).
    isf(q, a, b, loc=0, scale=1)
        Inverse survival function (inverse of ``sf``).
    moment(order, a, b, loc=0, scale=1)
        Non-central moment of the specified order.
    stats(a, b, loc=0, scale=1, moments='mv')
        Mean('m'), variance('v'), skew('s'), and/or kurtosis('k').
    entropy(a, b, loc=0, scale=1)
        (Differential) entropy of the RV.
    fit(data)
        Parameter estimates for generic data.
        See `scipy.stats.rv_continuous.fit <https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.fit.html#scipy.stats.rv_continuous.fit>`__ for detailed documentation of the
        keyword arguments.
    expect(func, args=(a, b), loc=0, scale=1, lb=None, ub=None, conditional=False, **kwds)
        Expected value of a function (of one argument) with respect to the distribution.
    median(a, b, loc=0, scale=1)
        Median of the distribution.
    mean(a, b, loc=0, scale=1)
        Mean of the distribution.
    var(a, b, loc=0, scale=1)
        Variance of the distribution.
    std(a, b, loc=0, scale=1)
        Standard deviation of the distribution.
    interval(confidence, a, b, loc=0, scale=1)
        Confidence interval with equal areas around the median.
    
    Notes
    -----
    This distribution is the normal distribution centered on ``loc`` (default
    0), with standard deviation ``scale`` (default 1), and clipped at ``a``,
    ``b`` standard deviations to the left, right (respectively) from ``loc``.
    If ``myclip_a`` and ``myclip_b`` are clip values in the sample space (as
    opposed to the number of standard deviations) then they can be converted
    to the required form according to::
    
        a, b = (myclip_a - loc) / scale, (myclip_b - loc) / scale
    
    Examples
    --------
    >>> import numpy as np
    >>> from scipy.stats import truncnorm
    >>> import matplotlib.pyplot as plt
    >>> fig, ax = plt.subplots(1, 1)
    
    Calculate the first four moments:
    
    >>> a, b = 0.1, 2
    >>> mean, var, skew, kurt = truncnorm.stats(a, b, moments='mvsk')
    
    Display the probability density function (``pdf``):
    
    >>> x = np.linspace(truncnorm.ppf(0.01, a, b),
    ...                 truncnorm.ppf(0.99, a, b), 100)
    >>> ax.plot(x, truncnorm.pdf(x, a, b),
    ...        'r-', lw=5, alpha=0.6, label='truncnorm pdf')
    
    Alternatively, the distribution object can be called (as a function)
    to fix the shape, location and scale parameters. This returns a "frozen"
    RV object holding the given parameters fixed.
    
    Freeze the distribution and display the frozen ``pdf``:
    
    >>> rv = truncnorm(a, b)
    >>> ax.plot(x, rv.pdf(x), 'k-', lw=2, label='frozen pdf')
    
    Check accuracy of ``cdf`` and ``ppf``:
    
    >>> vals = truncnorm.ppf([0.001, 0.5, 0.999], a, b)
    >>> np.allclose([0.001, 0.5, 0.999], truncnorm.cdf(vals, a, b))
    True
    
    Generate random numbers:
    
    >>> r = truncnorm.rvs(a, b, size=1000)
    
    And compare the histogram:
    
    >>> ax.hist(r, density=True, bins='auto', histtype='stepfilled', alpha=0.2)
    >>> ax.set_xlim([x[0], x[-1]])
    >>> ax.legend(loc='best', frameon=False)
    >>> plt.show()
```

**Comment by mdhaber** [comment] 2023-07-04 00:11
Closed by gh-18477.

**Closed by mdhaber** 2023-07-04 00:11 UTC
Labels: scipy.stats, Documentation, good first issue
