### ISSUE TITLE
BUG: windows dll install directory changed from scipy/.libs to scipy.libs

### ISSUE THREAD

**Issue by oregenfelder** [scipy/scipy#17437] opened 2022-11-17 12:10 UTC
### Describe your issue.

From scipy 1.9.1 to scipy 1.9.3 the directory used to install dlls on windows changed.
scipy-1.9.1: dlls are installed in .../site-packages/scipy/.libs
scipy-1.9.3: dlls are installed in .../site-packages/scipy.libs

This causes pyinstaller builds using scipy-1.9.3 to fail as the expected dll location changed.

If this change was intented I will file a bug report with pyinstaller to update the scipy installer hook.

### Reproducing Code Example

```python
None
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.9.3 1.23.1 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by rgommers** [comment] 2022-11-17 19:14
Hi @oregenfelder, yes this was intended. The build system changed. Actually we have two build systems now, and are going to remove the old one at some point. Also the wheel building infrastructure is different - `multibuild` vs. `cibuildwheel` - that should be the root cause here.

`package-name.libs`  is what `cibuildwheel` produces I believe. It'd be great if PyInstaller could account for that.

**Comment by andyfaff** [comment] 2022-11-17 20:16
It's not `cibuildwheel` that controls where the bundled dlls end up, it's down to the tool that repairs the wheel. For Windows this is [`delvewheel`](https://pypi.org/project/delvewheel/), for macOS it's `delocate` and on Linux it's `auditwheel`.
One can use the `-L, --lib-sdir` option to control where the vendored dlls are stored, but `package-name/.libs` is the default. I believe this is the same behaviour as `delocate` except that tool uses `package-name/.dylibs`

**Comment by adang1345** [comment] 2022-11-18 16:09
This bug has already been fixed in PyInstaller 5.6 with https://github.com/pyinstaller/pyinstaller/pull/7170.

**Comment by rgommers** [comment] 2022-11-18 21:45
Great, thanks a lot @adang1345. And thanks for reporting and digging in @oregenfelder and @andyfaff. Closing then.

**Closed by rgommers** 2022-11-18 21:45 UTC
Labels: Build issues, query

**Comment by WarrenWeckesser** [comment] 2022-11-28 17:18
Was the conclusion that putting the libs in a top-level directory `scipy.libs` was a bug, and we won't do that in the future?  Or is that the expected behavior now?

**Comment by rgommers** [comment] 2022-11-28 19:14
It's the expected behavior now.

**Comment by WarrenWeckesser** [comment] 2022-11-28 19:21
Huh, that's not what I expected.  Seems weird, but I'll trust y'all that it's the best solution at the moment.

**Comment by andyfaff** [comment] 2022-11-28 19:36
From the delvewheel doc:

> -L,--lib-sdir: subdirectory suffix to store vendored DLLs (default .libs). For example, if your wheel is named mywheel-0.0.1-cp310-cp310-win_amd64.whl, then the vendored DLLs are stored in mywheel.libs by default. If your wheel contains a top-level extension module that is not in any package, then this setting is ignored, and vendored DLLs are instead placed directly into site-packages when the wheel is installed.

I'm not sure if that option permits the older behaviour. I thought it was wise to retain the standard behaviour of the repair tool.

**Comment by rgommers** [comment] 2022-11-28 19:36
It's whatever the default of the tools doing the shared library vendoring is. I don't think we care too much either way. If I had to choose, I'd probably stay with `.libs`, but it's not a big deal.

> I thought it was wise to retain the standard behaviour of the repair tool.

Same here
