### ISSUE TITLE
BUG: Build picks up the wrong Cython

### ISSUE THREAD

**Issue by jmd-dk** [scipy/scipy#17552] opened 2022-12-07 00:30 UTC
#### Problem
I am building SciPy from source on a system with multiple Python installations, including a system-wide one. Specifically, I use
```bash
/path/to/python setup.py build
```
which triggers
```bash
/path/to/python tools/cythonize.py scipy
```
which calls the Cython executable via [the line](https://github.com/scipy/scipy/blob/v1.9.3/tools/cythonize.py#L100)
```python
r = subprocess.call(['cython'] + flags + ["-o", tofile, fromfile], cwd=cwd)
```
Here `'cython'` is left for the shell to resolve, meaning that the first `cython` found on `$PATH` is used.

This cause trouble, as we want *the* Cython installed on the currently running Python installation. In my case specifically, calling a wrong Cython causes the cythonization of `scipy/stats/_biasedurn.pyx` to fail because of different NumPy versions installed within the Python installations:
```
Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.memory cimport unique_ptr

np.import_array()

IF not NPY_OLD:
    from numpy.random cimport bitgen_t
   ^
------------------------------------------------------------

_biasedurn.pyx:13:4: 'numpy/random.pxd' not found
```
though I imagine that various different error messages could show up on different systems due to this.

#### Solution
To fix this locally, one can do
```bash
export PATH="/path/to/correct/python/bin/:${PATH}"
```
prior to installing SciPy. However, as I believe that letting the shell resolve `'cython'` is a bug and not a feature (note that e.g. the `cython_version` variable also defined in `scipy/stats/_biasedurn.pyx` always uses the correct Cython installation), this is not the correct approach.

The **correct solution** is to explicitly use *the* Cython that is installed with the currently used Python. This can be achieved by changing the above line in `tools/cythonize.py` to e.g.
```python
r = subprocess.call([sys.executable, '-m', 'cython'] + flags + ['-o', tofile, fromfile], cwd=cwd)
```
(perhaps the full path to the `cython` executable can also be obtained directly as some attribute on e.g. `Cython.Build`, though I could not find it).

### Reproducing Code Example

An easy way to see the problem in action is to just make a fake `cython` executable somewhere on `$PATH`, e.g.

```bash
mkdir fake_cython
echo '#!/usr/bin/env bash' > fake_cython/cython
echo 'echo "Fake Cython called with $@"' >> fake_cython/cython
echo 'exit 1' >> fake_cython/cython
chmod +x fake_cython/cython
export PATH="${PWD}/fake_cython:${PATH}"

...

python setup.py build
```

### Error message

```shell
Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.memory cimport unique_ptr

np.import_array()

IF not NPY_OLD:
    from numpy.random cimport bitgen_t
   ^
------------------------------------------------------------

_biasedurn.pyx:13:4: 'numpy/random.pxd' not found
```

### SciPy/NumPy/Python version information

1.8.0 1.22.3 sys.version_info(major=3, minor=9, micro=10, releaselevel='final', serial=0)

**Comment by ilayn** [comment] 2022-12-07 00:53
`setup.py` based builds are going away soon since we have switched to `meson` based builds via `dev.py`, our new CLI tool. Please have a go at it by typing `python dev.py` and then you can do many such tweaks by environment variables.

Having said that however, leaving the path finding for executables to the packages is the most fun way to break many workflows if you think about virtual environments and containers and many other places this package is builtin. Providing env vars or through `pkg-config` is our way of allowing for custom settings.

**Comment by eli-schwartz** [comment] 2022-12-07 05:30
If `/path/to/python` is in PATH such that `python` resolves to it by default, then the cython executable installed in the same directory will also be found by default. :D 

https://github.com/scipy/scipy/blob/502df0ece7eb9525de8a7f243044b3fe18ad5cca/tools/cythonize.py#L98-L114

Seems there's already code to handle this. But it's not the same code that Meson uses. :p That uses https://github.com/scipy/scipy/blob/502df0ece7eb9525de8a7f243044b3fe18ad5cca/scipy/_build_utils/cythoner.py instead which is a pretty thin wrapper around cython, and will eventually go away once cython support in Meson works a bit better. (Currently I think probably the main thing is depfile support?)

With Meson, you could set a machine file specifying both the python interpreter to build for, and the cython command to use.

**Comment by jmd-dk** [comment] 2022-12-07 07:25
So are you saying that this is in fact an intentional feature? Is there ever a case where one would want the SciPy files to be cythonized using a Cython different from the one belonging to the currently running Python interpreter (and obtained from `import Cython`)?

As a comparison, consider how `f2py` is called:
https://github.com/scipy/scipy/blob/502df0ece7eb9525de8a7f243044b3fe18ad5cca/tools/generate_f2pymod.py#L280-L283

or indeed how the `python` interpreter itself is called using `sys.executable` throughout, never just `'python'`/`'python3'`.

**Comment by eli-schwartz** [comment] 2022-12-07 12:44
> So are you saying that this is in fact an intentional feature? Is there ever a case where one would want the SciPy files to be cythonized using a Cython different from the one belonging to the currently running Python interpreter (and obtained from `import Cython`)?

In terms of Meson functionality, certainly. `find_program()` in the meson.build DSL or `mesonbuild.compilers.detect.detect_cython_compiler()` doesn't know or care that cython is implemented as a python module, and also doesn't know whether it is installed -- so it finds out by checking if the program exists (because it is a program, after all).

Furthermore, cython doesn't care what version of python it runs on, it produces the same `*.c` / `*.cpp` files either way and you can include those files in an sdist and not have a build dependency on cython at all. All that matters is what *version* of cython you have -- you can check that by running `['cython', '--version']`. As for different versions of numpy pxd files, I imagine the issue there is actually missing include paths, not the "wrong copy of cython". :) That should be fixable.

**Comment by rgommers** [comment] 2023-01-06 17:09
> `_biasedurn.pyx:13:4: 'numpy/random.pxd' not found`

This problem is gone now, after gh-17574. That was the root cause. Everything else does work as it should, the answers above are correct that the first `cython` found is used. And that should be the one in the currently active environment if it's installed there.

There's nothing left to do here, so I'll close this issue.

**Closed by rgommers** 2023-01-06 17:09 UTC
Labels: defect, Build issues
