### ISSUE TITLE
BUG: 404 of website page

### ISSUE THREAD

**Issue by DawnEve** [scipy/scipy#14766] opened 2021-09-24 02:54 UTC
### Describe your issue.

404 not found

### Reproducing Code Example

```python
Here: https://docs.scipy.org/doc/scipy/reference/tutorial/index.html#user-guide
when click `Getting started`
404: https://docs.scipy.org/doc/scipy/reference/getting_started.html
```

### Error message

```shell
Not Found
The requested URL /doc/scipy/reference/getting_started.html was not found on this server.

Apache/2.4.39 (Ubuntu) Server at docs.scipy.org Port 443
```

### SciPy/NumPy/Python version information

NULL

**Comment by ilayn** [comment] 2021-09-24 03:43
Duplicate of #14267

**Closed by ilayn** 2021-09-24 03:43 UTC
Labels: defect
