### ISSUE TITLE
LinAlgError: Schur form not found. Possibly ill-conditioned

### ISSUE THREAD

**Issue by paulagm12** [scipy/scipy#12687] opened 2020-08-09 14:59 UTC
My issue is about the error LinAlgError: Schur form not found. Possibly ill-conditioned raised when I use the following code. The problem is that it only happens in the first execution of the script, then it disappears. It also happens when I try to use `scipy.linalg.expm` and `scipy.linalg.logm` as it has to do with the Schur decomposition.

#### Reproducing code example:

```python

""" Obtains the fidelity for the QFT for n=3 for Qiskit noise model """

import numpy as np

def fidelity(a,b):
    ''' Computes the fidelity of two density matrices
    
    Args:
        a (array): density  matrix
        b (array): density matrix
    
    Returns:
        float: fidelity of a and b
        '''
    return (np.matrix.trace(scipy.linalg.sqrtm(np.matmul(scipy.linalg.sqrtm(a),np.matmul(b,scipy.linalg.sqrtm(a))))))**2

rho0=np.array([[0.23394436+0.j        , 0.11036513+0.07068888j,
        0.03302341+0.1088189j , 0.02706909+0.0881958j ,
        0.05815633-0.01072523j, 0.02037557-0.02607218j,
        0.1016744 +0.00529989j, 0.12719727+0.00524902j],
       [0.11036513-0.07068888j, 0.13571167+0.j        ,
        0.05817668+0.06459554j, 0.05001153+0.03409153j,
        0.01467896-0.03614299j, 0.02297974-0.02354262j,
        0.05975342-0.05200195j, 0.07036336-0.04786174j],
       [0.03302341-0.1088189j , 0.05817668-0.06459554j,
        0.14170668+0.j        , 0.09006076-0.00379435j,
        0.0081075 -0.02009074j, 0.00140381-0.01287842j,
        0.01685588-0.05481296j, 0.02995809-0.0568339j ],
       [0.02706909-0.0881958j , 0.05001153-0.03409153j,
        0.09006076+0.00379435j, 0.1104499 +0.j        ,
        0.0189209 -0.01251221j, 0.00768026-0.02039591j,
        0.03121948-0.0254008j , 0.03673299-0.03857761j],
       [0.05815633+0.01072523j, 0.01467896+0.03614299j,
        0.0081075 +0.02009074j, 0.0189209 +0.01251221j,
        0.0863071 +0.j        , 0.04125298+0.00418091j,
        0.01762221-0.00102403j, 0.03347778+0.00219727j],
       [0.02037557+0.02607218j, 0.02297974+0.02354262j,
        0.00140381+0.01287842j, 0.00768026+0.02039591j,
        0.04125298-0.00418091j, 0.06473456+0.j        ,
        0.0410258 +0.00813802j, 0.01971775+0.01372613j],
       [0.1016744 -0.00529989j, 0.05975342+0.05200195j,
        0.01685588+0.05481296j, 0.03121948+0.0254008j ,
        0.01762221+0.00102403j, 0.0410258 -0.00813802j,
        0.11333211+0.j        , 0.06110975+0.02015177j],
       [0.12719727-0.00524902j, 0.07036336+0.04786174j,
        0.02995809+0.0568339j , 0.03673299+0.03857761j,
        0.03347778-0.00219727j, 0.01971775-0.01372613j,
        0.06110975-0.02015177j, 0.11381361+0.j        ]])

rho=np.array([[ 0.17706638+0.j        ,  0.06659953+0.01608955j,
         0.0297682 +0.01830716j,  0.00812785+0.01222738j,
         0.00753445-0.00309584j,  0.00878906-0.01509603j,
         0.02885946-0.0179952j ,  0.04318237-0.01519775j],
       [ 0.06659953-0.01608955j,  0.13491143+0.j        ,
         0.03180949+0.01096598j,  0.01931085+0.01529609j,
         0.00876872-0.00343831j,  0.00969103-0.01005385j,
         0.01644897-0.02258301j,  0.02629598-0.01775106j],
       [ 0.0297682 -0.01830716j,  0.03180949-0.01096598j,
         0.12190416+0.j        ,  0.03262329+0.01110501j,
         0.0140686 -0.00460815j,  0.00094604-0.01165771j,
         0.00431993-0.02871026j,  0.01617432-0.02577718j],
       [ 0.00812785-0.01222738j,  0.01931085-0.01529609j,
         0.03262329-0.01110501j,  0.10249498+0.j        ,
         0.00314331-0.00964355j,  0.00564575+0.00064087j,
        -0.00264486-0.00935872j,  0.00440131-0.01796807j],
       [ 0.00753445+0.00309584j,  0.00876872+0.00343831j,
         0.0140686 +0.00460815j,  0.00314331+0.00964355j,
         0.10799493+0.j        ,  0.02676392+0.0035163j ,
         0.01410251+0.00034248j,  0.00727336+0.00429281j],
       [ 0.00878906+0.01509603j,  0.00969103+0.01005385j,
         0.00094604+0.01165771j,  0.00564575-0.00064087j,
         0.02676392-0.0035163j ,  0.10673353+0.j        ,
         0.01838175+0.00315348j,  0.02171156+0.01295641j],
       [ 0.02885946+0.0179952j ,  0.01644897+0.02258301j,
         0.00431993+0.02871026j, -0.00264486+0.00935872j,
         0.01410251-0.00034248j,  0.01838175-0.00315348j,
         0.12371487+0.j        ,  0.0449117 +0.01037259j],
       [ 0.04318237+0.01519775j,  0.02629598+0.01775106j,
         0.01617432+0.02577718j,  0.00440131+0.01796807j,
         0.00727336-0.00429281j,  0.02171156-0.01295641j,
         0.0449117 -0.01037259j,  0.12517971+0.j        ]])
fidelity=DAQC.fidelity(rho0,rho)

```

#### Error message:

```
File "C:\Users\Paula\Dropbox\Master thesis\FinalCode\ibmq_estimation\DAQC.py", line 37, in fidelity
    return (np.matrix.trace(scipy.linalg.sqrtm(np.matmul(scipy.linalg.sqrtm(a),np.matmul(b,scipy.linalg.sqrtm(a))))))**2

  File "C:\Users\Paula\Anaconda3\envs\test_env\lib\site-packages\scipy\linalg\_matfuncs_sqrtm.py", line 172, in sqrtm
    T, Z = schur(A, output='complex')

  File "C:\Users\Paula\Anaconda3\envs\test_env\lib\site-packages\scipy\linalg\decomp_schur.py", line 170, in schur
    raise LinAlgError("Schur form not found. Possibly ill-conditioned.")

LinAlgError: Schur form not found. Possibly ill-conditioned.
  ...
```

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

1.5.2 1.18.5 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment] 2020-08-09 15:19
I can't reproduce this after cleaning the code a bit

```python
import numpy as np
from scipy.linalg import sqrtm


def fidelity(a, b):
    ''' Computes the fidelity of two density matrices

    Args:
        a (array): density  matrix
        b (array): density matrix

    Returns:
        float: fidelity of a and b
        '''

    s = sqrtm(a)
    return (np.matrix.trace(sqrtm(s @ b @ s)))**2

fidelity(rho0, rho)
(0.8144429942166306-0.04514095274618541j)
```

I don't know if the result is correct though. If the error disappears probably something in `DAQC` method is overwriting something.

**Comment by paulagm12** [comment] 2020-08-09 15:25
The result is correct, can I have some kind of problem with the installation of scipy? I have already uninstalled and reinstalled it.

**Comment by paulagm12** [comment] 2020-08-09 15:28
I also get a similar error in the following example:

```
import numpy as np
import scipy.linalg

M1=np.array([[ 0.        +0.j  0.        +0.j  0.70710678+0.j  0.70710678+0.j
   0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j]
 [-0.        +0.j  0.        +0.j -0.70710678+0.j  0.70710678+0.j
  -0.        +0.j  0.        +0.j -0.        +0.j  0.        +0.j]
 [ 0.70710678+0.j  0.70710678+0.j  0.        +0.j  0.        +0.j
   0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j]
 [-0.70710678+0.j  0.70710678+0.j -0.        +0.j  0.        +0.j
  -0.        +0.j  0.        +0.j -0.        +0.j  0.        +0.j]
 [ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
   0.        +0.j  0.        +0.j  0.70710678+0.j  0.70710678+0.j]
 [-0.        +0.j  0.        +0.j -0.        +0.j  0.        +0.j
  -0.        +0.j  0.        +0.j -0.70710678+0.j  0.70710678+0.j]
 [ 0.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j
   0.70710678+0.j  0.70710678+0.j  0.        +0.j  0.        +0.j]
 [-0.        +0.j  0.        +0.j -0.        +0.j  0.        +0.j
  -0.70710678+0.j  0.70710678+0.j -0.        +0.j  0.        +0.j]])
U=scipy.linalg.expm(deltaB*scipy.linalg.logm(M1))
```

The error is

```File "C:\Users\Paula\Anaconda3\envs\test_env\lib\site-packages\scipy\linalg\matfuncs.py", line 197, in logm
    F = scipy.linalg._matfuncs_inv_ssq._logm(A)

  File "C:\Users\Paula\Anaconda3\envs\test_env\lib\site-packages\scipy\linalg\_matfuncs_inv_ssq.py", line 878, in _logm
    T, Z = schur(A, output='complex')

  File "C:\Users\Paula\Anaconda3\envs\test_env\lib\site-packages\scipy\linalg\decomp_schur.py", line 170, in schur
    raise LinAlgError("Schur form not found. Possibly ill-conditioned.")

LinAlgError: Schur form not found. Possibly ill-conditioned.
```

**Comment by ilayn** [comment] 2020-08-09 15:29
What is `deltaB` ?

**Comment by paulagm12** [comment] 2020-08-09 15:33
Sorry, I forgot to add its value, now it should be more clear.

**Comment by paulagm12** [comment] 2020-08-09 15:35
Actually what is weird is that this code on its own appears not to raise any error, but then I run it as part os a bigger code where this is a function of a module and the error appears.

**Comment by ilayn** [comment] 2020-08-09 15:43
As I said, probably something is fiddling with the data somewhere so probably it is an interaction problem in the bigger class/function.

**Comment by paulagm12** [comment] 2020-08-09 15:44
Okay, I will try to have a look at it then, thank you for your help! What I do not undestand is that it worked perfectly three weaks ago and now it raises this error when I have not change a thing in the code, the only change was to update the Windows version of my computer.

**Comment by ilayn** [comment] 2020-08-09 15:45
Hmm, that sounds fishy. We touched that part of the code recently if I remember correctly so let me check.

**Comment by charris** [comment] 2020-08-09 16:30
> the only change was to update the Windows version of my computer.

There have been other reports of problems following the latest Windows update, see https://github.com/numpy/numpy/issues/16744 .

**Comment by paulagm12** [comment] 2020-08-09 16:35
So maybe here's the problem, it seems certainly similar to my own issue. Thank you!

**Comment by paulagm12** [comment] 2020-08-09 17:47
@ilayn 

The problem is in the shur function in line 133     

```
gees, = get_lapack_funcs(('gees',), (a1,))
```

By calling the function gees  of LAPACK the error code (info variable in shur function) is 8 and, hence, the LinAlgError is raised.

**Comment by bashtage** [comment] 2020-08-11 15:44
@paulagm12 If you run

```
import numpy as np
a = np.arange(13 * 13, dtype=np.float64)
a.shape = (13, 13)
a = a % 17
va, ve = np.linalg.eig(a)
```

do you see an error?

**Comment by paulagm12** [comment] 2020-08-11 17:12
Yes, I obtain the following one: 

````
Traceback (most recent call last):

  File "<ipython-input-1-bad305f0dfc7>", line 5, in <module>
    va, ve = np.linalg.eig(a)

  File "<__array_function__ internals>", line 6, in eig

  File "C:\Users\Paula\Anaconda3\envs\test_env\lib\site-packages\numpy\linalg\linalg.py", line 1324, in eig
    w, vt = _umath_linalg.eig(a, signature=signature, extobj=extobj)

  File "C:\Users\Paula\Anaconda3\envs\test_env\lib\site-packages\numpy\linalg\linalg.py", line 94, in _raise_linalgerror_eigenvalues_nonconvergence
    raise LinAlgError("Eigenvalues did not converge")

LinAlgError: Eigenvalues did not converge

``` 
However, I have tried it in another Anaconda environment and it seems to work without problems. Maybe it is something to do with the versions of the packages.

**Comment by paulagm12** [comment] 2020-08-11 17:13
However, I have tried it in another Anaconda environment and it seems to work without problems. Maybe it is something to do with the versions of the packages.

**Comment by ilayn** [comment] 2020-10-21 10:31
Duplicate of #12747

**Closed by ilayn** 2020-10-21 10:31 UTC
Labels: scipy.linalg
