### ISSUE TITLE
TypeError: _nnls.nnls() missing required argument 'n' (pos 3)

### ISSUE THREAD

**Issue by Garve** [scipy/scipy#13550] opened 2021-02-11 14:18 UTC
Hello!

I installed scipy v1.6.0 and I noticed that the signature of the nnls function changed somehow.

Before it was scipy.optimize.nnls(A, b, maxiter=None), but if I use it like this, I get the following error:
```
TypeError: _nnls.nnls() missing required argument 'n' (pos 3)
```

Same happens when I try scikit-learns LinearRegression with the parameter positve=True since it seems to use nnls, too.. Was there a regression?

Thank you very much!

**Comment by ilayn** [comment] 2021-02-11 15:59
Hi @Garve how do you exactly use it? Are you importing from directly private `_nnls`? There is an issue about namespace clashes about optimize module which we are working on a fix so it would be nice to know how you import and use.

**Comment by tupui** [comment] 2021-02-11 17:49
@ilayn I guess it is coming from L80 of `scipy.optimize._nnls.py`: `__nnls.nnls(A, m, n, b, w, zz, index, maxiter)`

**Comment by tupui** [comment] 2021-02-11 18:05
I cannot reproduce the issue.

```python
import numpy as np
import scipy.optimize 
A = np.array([[1, 0], [1, 0], [0, 1]])
b = np.array([2, 1, 1])
scipy.optimize.nnls(A, b, maxiter=None)
# (array([1.5, 1. ]), 0.7071067811865475)
```

**Comment by tupui** [comment] 2021-02-25 14:53
@Garve could you provide more info?

**Comment by Simpsonguitar** [comment] 2021-02-26 09:35
Hello,
I noticed the exact  same issue but with variable reproducibility results.
The function works just fine on two workstations with a conda installation and the conda-forge scipy v1.6.0 module but for some reasons, on my personal computer with an other conda installation and the  scipy 1.2.1 module provided by pypi, the error occured.

Update :
Ok this i solve my issue by updating the scipy module from v1.2.1 pypi to v1.4.1 conda-forge.
@Garve is this workaround working for you ?

**Comment by tupui** [comment] 2021-02-26 09:38
Thanks @Simpsonguitar, as it seems to be fixed with newer releases, I will close the issue.

@Garve feel free to re-open it if you still have issues with the latest version.

**Closed by tupui** 2021-02-26 09:38 UTC
Labels: scipy.optimize

**Comment by Garve** [comment] 2021-02-26 12:51
Hi! Sorry for the late answer. Still present in 1.6.1, but I will wait to the next one.

```python
import numpy as np
import scipy

print(scipy.__version__)

A = np.array([[1, 0], [1, 0], [0, 1]])
b = np.array([2, 1, 1])
scipy.optimize.nnls(A, b, maxiter=None)
```

gives me 
```
1.6.1

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-c1dc6cdb5431> in <module>
      6 A = np.array([[1, 0], [1, 0], [0, 1]])
      7 b = np.array([2, 1, 1])
----> 8 scipy.optimize.nnls(A, b, maxiter=None)

TypeError: _nnls.nnls() missing required argument 'n' (pos 3)

```

**Comment by tupui** [comment] 2021-02-26 12:59
I just tried this example and I think I know what is happening. With a clean environment, calling `scipy.optimize` fails due to the way you import scipy. If this is working on your side, I would expect you have something in your PYTHONPATH that could conflict.

Fixing the import with `from scipy.optimize import nnls` or `import scipy.optimize` and it works as expected on my side:

```python
import numpy as np
import scipy.optimize

print(scipy.__version__)

A = np.array([[1, 0], [1, 0], [0, 1]])
b = np.array([2, 1, 1])
scipy.optimize.nnls(A, b, maxiter=None)

# 1.6.1
# (array([1.5, 1. ]), 0.7071067811865475)
```

**Comment by Garve** [comment] 2021-02-26 13:24
Hmm still the same for me :( but thank you! Maybe I try a clean install of everything.
