### ISSUE TITLE
BUG: optimize.test.test_milp::test_milp_timeout_16545 fail

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#18334] opened 2023-04-21 06:31 UTC
### Describe your issue.

Running the full test suite on macosx_arm64 results in a failed test for `optimize.milp` 

### Reproducing Code Example

```python
python dev.py test
```

### Error message

```shell
________________________________________________________ test_milp_timeout_16545[options0-Time limit reached. (HiGHS Status 13:] ________________________________________________________
scipy/optimize/tests/test_milp.py:323: in test_milp_timeout_16545
    assert res.message.startswith(msg)
E   AssertionError: assert False
E    +  where False = <built-in method startswith of str object at 0x42180c650>('Time limit reached. (HiGHS Status 13:')
E    +    where <built-in method startswith of str object at 0x42180c650> = 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'.startswith
E    +      where 'Optimization terminated successfully. (HiGHS Status 7: Optimal)' =         message: Optimization terminated successfully. (HiGHS Status 7: Optimal)\n        success: True\n         status...00  0.000e+00 ...  0.000e+00  0.000e+00]\n mip_node_count: 2715\n mip_dual_bound: -11.00000000000001\n        mip_gap: 0.0.message
        A          = array([[1, 2, 2, ..., 4, 0, 0],
       [4, 1, 2, ..., 0, 4, 4],
       [4, 1, 1, ..., 1, 4, 3],
       ...,
       [4, 0, 4, ..., 4, 1, 3],
       [4, 1, 3, ..., 2, 0, 2],
       [2, 2, 1, ..., 2, 1, 2]])
        b_lb       = array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf, -inf, -inf, -i...f, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf])
        b_ub       = array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, ...25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25])
        c_vector   = array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1.,...  -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1.])
        constraints = <scipy.optimize._constraints.LinearConstraint object at 0x42171ffd0>
        integrality = array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., ...1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
        msg        = 'Time limit reached. (HiGHS Status 13:'
        options    = {'time_limit': 10}
        res        =         message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status...00  0.000e+00 ...  0.000e+00  0.000e+00]
 mip_node_count: 2715
 mip_dual_bound: -11.00000000000001
        mip_gap: 0.0
        rng        = Generator(PCG64) at 0x42185C580
        variable_bounds = Bounds(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0...., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))
        variable_lb = array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., ...0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
        variable_ub = array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., ...1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
================================================================================ short test summary info ================================================================================
FAILED scipy/optimize/tests/test_milp.py::test_milp_timeout_16545[options0-Time limit reached. (HiGHS Status 13:] - AssertionError: assert False
```

### SciPy/NumPy/Python version and system information

```shell
1.24.2 sys.version_info(major=3, minor=11, micro=3, releaselevel='final', serial=0)

scipy main
```

**Comment by andyfaff** [comment] 2023-04-21 06:32
@mdhaber it looks like the solve finishes before the `milp` run can time out. Should the timeout be lowered?

**Comment by WarrenWeckesser** [comment] 2023-04-21 12:39
@andyfaff, this looks like a duplicate of https://github.com/scipy/scipy/issues/17137, so I'm closing this one.

**Closed by WarrenWeckesser** 2023-04-21 12:39 UTC
Labels: defect, scipy.optimize
