### ISSUE TITLE
Better argument preparation for distributions in stats package.

### ISSUE THREAD

**Issue by iandall** [scipy/scipy#13589] opened 2021-02-19 02:08 UTC
**Is your feature request related to a problem? Please describe.**
Before calling most member functions of the `rv_continuous` class (no doubt `rv_discrete` as well) copies of the arguments are made by `argsreduce()` with invalid items removed. A side effect of this is that scalar arguments (shape parameters, `loc`, `scale`) get expanded to arrays of the same length.

However, when member functions get called internally (such as when `_ppf()` is called by the `rv_generic._rvs()`) these arguments are scalars. So subclass distributions have to be able to handle both scalar and expanded array copies of these parameters. By the magic of broadcasting, this mostly works transparently, but not always. I have written my own distribution where I was forced to test the number of dimensions of the shape parameter and take different action depending on whether it was scalar or not.

It is also inefficient in memory and potentially computation as well. For example, I calculate `(1 - g**2)/np.sqrt(2 * np.pi)`, where `g` is a shape parameter. It is much more efficient to do this once on a scalar `g` and then rely on broadcasting, than to first expand `g` to an array and then perform the computation on each item of the array.

**Describe the solution you'd like**
 `argsreduce()` should only apply `np.extract(cond, arg)` to array arguments, or maybe more correctly, array arguments with the same size as `cond`, and leave other arguments alone.

I note that `argsreduce()` has a comment: "This should be rewritten".

**Describe alternatives you've considered**
This can't really be fixed in the subclass. 
```python
dist.cdf([3, 3], [1, 3])
```
works as expected. I am not sure if this is behavior which is expected, or a happy consequence of numpy arrays, but it means the member functions might receive a shape parameter argument which is a list of values for the shape parameter, or it might be the result of expanding a scalar, and short of testing every item for equality, there is no way to tell.

`argsreduce()` is not a member function which can be overridden in a subclass.

**Additional context (e.g. screenshots)**

**Comment by ev-br** [comment] 2021-02-19 09:22
Backwards-compatible improvements are always welcome. (That comment have been there forever (tm)).

**Comment by iandall** [comment] 2021-02-19 10:39
I'll try and come up with something.

It is hard to be absolutely sure you don't break undocumented behavior, especially of user provided distribution sub classes. One approach would be for the subclass to override an attribute to indicate the new approach should be used. Then as distributions are tested they could set that attribute. Long term it leaves this obsolete cruft through.

I guess the thing is that the signatures for the private member functions are not well documented.

**Comment by ev-br** [comment] 2021-02-19 14:42
This is indeed not documented very thoroughly. Any change this deep will need to be tested to jot break e.g. statsmodels, which is a heavy user. 

I'm guessing one reason the comment is there since forever is that this stuff is not broken enough to justify the churn.

**Comment by josef-pkt** [comment] 2021-02-19 15:20
IIUC, the main backwards compatibility problem will come with inplace operations, `+=`, `*=`, which I think are still heavily used.
Those will break if the array is supposed to expand across inplace operations.

**Comment by iandall** [comment] 2021-02-25 11:38
> IIUC, the main backwards compatibility problem will come with inplace operations, `+=`, `*=`, which I think are still heavily used.
> Those will break if the array is supposed to expand across inplace operations.

That was indeed a problem, but those ones are easily fixed.

**Comment by iandall** [comment] 2021-02-25 12:39
This [13611] PR is really a request for comment. Although there are significant performance improvements (dramatically in some cases), there are also some performance decreases which need to be addressed. One approach would be to have `argsreduce` be a method which can be overridden by sub classes, so that the classes can chose the method which works best for them.

The testsuite passes, but there is still the possibility that there are issues with use cases which aren't tested.

The new `argsreduce` returns different shape arguments in different cases, which is inelegant at least. The approach I've taken is that shape doesn't matter so long as all the arguments are broadcastable.

Q is this approach worth persevering with?

**Comment by josef-pkt** [comment] 2021-02-25 14:52
If performance improvements are large enough, then I think it's a good change.
However, I think the subclasses need to opt in with an attribute, otherwise there are too many ways to break user defined subclasses of distributions.
Maybe the old behavior can be deprecated over time. I haven't looked at cases that might be affected in statsmodels.

(In statsmodels we have a problem with, for example, weights, which, if not used, could be implemented as scalar 1, as vector of ones or as None. The actual code is a mix of the 3 cases depending on coding convenience, on performance, and on how common the None/1 case is. Any change, needs follow up changes all over the place.)

**Comment by josef-pkt** [comment] 2021-03-11 19:50
I guess #13611 broke statsmodels prerelease testing, subclassing scipy distributions

https://github.com/statsmodels/statsmodels/issues/7371

**Comment by mdhaber** [comment] 2021-03-20 23:51
@iandall I have not been involved with these, but from your comment in gh-13611:
> Addresses 13589

I assume that gh-13611 was intended to close this. The issue mentioned by @josef-pkt is documented in gh-13675, so I am closing this one. Please reopen if I missed something.

**Closed by mdhaber** 2021-03-20 23:51 UTC
Labels: scipy.stats
