### ISSUE TITLE
Warning: Desired error not necessarily achieved due to precision loss.

### ISSUE THREAD

**Issue by kash1102** [scipy/scipy#7536] opened 2017-06-27 20:35 UTC
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I am getting this error when i try to optimize using optimize.fmin_cg() , could someone explain the reason also in _line_search_wolfe12(f, myfprime, xk, pk, gfk, old_fval,old_old_fval, **c2**=0.4) what does c2 represents is it the initial step size?

Any help on this would be appreciated.
Thanks.

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by cdouglass** [comment] 2017-07-08 22:39
@kash1102 Could you include the input values you are using when you get the `Warning: Desired error not necessarily achieved due to precision loss` error? This warning occurs when line search could not find a step size meeting both Wolfe conditions *and* the Polak-Ribiere descent condition within a certain number of iterations.

The (strong) Wolfe line search method searches for a step size meeting two criteria: for some constants 0 < c1 < c2 < 1:
1) the function value must decrease from the starting point by at least c1 * step length * -(slope along search direction at starting point)
2) the absolute value of the function's slope along the search direction must decrease by a factor of at least 1/c2

**Comment by rgommers** [comment] 2017-07-15 00:59
@kash1102 without a reproducing example it's unclear that this is a scipy issue, so I'm closing for now.

**Closed by rgommers** 2017-07-15 00:59 UTC
Labels: query, scipy.optimize
