### ISSUE TITLE
scipy.cluster.hierarchy.linkage: Allow usage of different datatypes

### ISSUE THREAD

**Issue by fizzX** [scipy/scipy#12567] opened 2020-07-18 03:42 UTC
**Is your feature request related to a problem? Please describe.**
scipy.cluster.hierarchy.linkage uses double (float64) to store and do its computation for hierarchical clustering. However, I have a very large dataset (292000x292000) that I would like to perform hclust on but my computer is RAM limited. I have 252GB RAM and I think the clustering algorithm should be able to work on my dataset when all values are stored and computed using float16s instead. 

For large datasets on machines with insufficient RAM to store and compute on Arrays of float64s, it would be awesome if computation could be done on a different precision float to reduce the memory footprint.

Additionally, adding choices for datatypes could be very useful for almost all scipy functions.

**Describe the solution you'd like**
Allow for an argument to specify what datatype you'd like to use (e.g. np.float64, np.float32, np.float16)

The argument could be like dtype='np.double' by default but changable to whatever datatype is chosen.

**Comment by rgommers** [comment] 2020-07-18 14:46
Adding just a `dtype` keyword to `linkage` won't help with memory usage, because the `scipy.spatial.distance` functionality it uses is only implemented in `double`.

This is a duplicate of gh-3563.

Doing a lot of work to reduce memory uses by a constant factor 2 or 4 doesn't seem worth it. Using a different algorithm (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2718652/) for online hierarchical clustering or agglomerative clustering would make much more sense.

I don't think this is actionable (at least without a major overhaul of `spatial.distance`), so I'll close it. Feel free to keep discussing of course @fizzX.

**Closed by rgommers** 2020-07-18 14:46 UTC
Labels: enhancement, scipy.cluster
