### ISSUE TITLE
ss2tf got the wrong output

### ISSUE THREAD

**Issue by Asem-Abdelhady** [scipy/scipy#15537] opened 2022-02-06 14:23 UTC
### Describe your issue.

I tried ss2tf in one example and got the wrong output
The output from the implementation
![ss2tf](https://user-images.githubusercontent.com/40506647/152685336-3f6154f8-c9f5-4126-8780-0bc02acf2e2b.png)

The output from wolfram alpha
![wolframe-ss2tf](https://user-images.githubusercontent.com/40506647/152685356-c181cdee-7fc4-4c53-a8f1-513b16fb2872.png)

My solution
![my_solution](https://user-images.githubusercontent.com/40506647/152685364-c959bd2c-3ceb-416e-8148-95c31b7651e3.png)

as you can see that in ss2tf implementation it got the result in the numerator of 7, whereas, wolfram and my solution is 8. 

### Reproducing Code Example

```python
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```

### Error message

```shell
none
```

### SciPy/NumPy/Python version information

import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

**Comment by kilimanj4r0** [comment] 2022-02-09 20:40
# Yet another wrong output
I have another example of wrong output from the `scipy.signal.ss2tf()` function:
![wolfram](https://user-images.githubusercontent.com/43704968/153285256-e882d6ba-431f-444a-b62b-c55301d9b1a4.png)
![colab](https://user-images.githubusercontent.com/43704968/153285094-56c7855e-cd1a-49dc-a89a-394ef8cc05dc.png)

To be more precisely, the error in the second element of second array (denominator). Since the element `1.77635684e-15` is highly close to `0`, maybe there is some issue with the calculation precision in this function. 

## Reproducing Code Example
```python
A = [[0, 8], [6, 0]]
B = [[0], [1]]
C = [[1, 0]]
D = [[0]]
ss2tf(A, B, C, D)
```

**Comment by roryyorke** [comment] 2022-03-05 17:45
I can't reproduce your first example:

```
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> print(scipy.__version__)
1.7.3
>>> from scipy import signal
>>> A = [[0,8], [1,3]]
>>> B = [[0],[1]]
>>> C = [[1, 0]]
>>> D = [[0]]
>>> signal.ss2tf(A,B,C,D)
(array([[0., 0., 8.]]), array([ 1., -3., -8.]))
```
Could you please double-check if you can still get your reported result, and, if so, please let us know what version of Scipy, etc., you're using (your original report doesn't include the output of `import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)`).

I *can* reproduce your second example (continuing Python session above):
```
>>> A = [[0,8], [6,0]]
>>> B = [[0],[1]]
>>> C = [[1, 0]]
>>> D = [[0]]
>>> signal.ss2tf(A,B,C,D)
(array([[ 0.00000000e+00, -1.77635684e-15,  8.00000000e+00]]), array([ 1.00000000e+00,  1.77635684e-15, -4.80000000e+01]))
```
but I think that's fine: 1.8e-15 is round-off error.  Wolfram may be doing a symbolic transformation, and so have no round-off error.  You can try Sympy if you need this sort of exact result, though you'll need to code the ss2tf function yourself (it's not all that complicated -- though if your system is big I suggest investigating DomainMatrix; see https://github.com/sympy/sympy/issues/19920)

**Comment by rgommers** [comment] 2023-09-30 09:25
I got the same correct result as @roryyorke on current `main`, so that all looks okay. And I agree that the second example is round-off error. So I'll close this issue. If we missed something, please comment with more details and we can investigate further.

**Closed by rgommers** 2023-09-30 09:25 UTC
Labels: defect, scipy.signal
