### ISSUE TITLE
cumtrapz non-zero initial  argument test

### ISSUE THREAD

**Issue by kangwonlee** [scipy/scipy#7890] opened 2017-09-19 00:55 UTC
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

Dear all,

Could you please test non-zero `initial` argument of `scipy.integrate.cumtrapz()`?
To me it seems only meaningful if `initial=0`.

Hope this helps,

KW

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```
```
import numpy as np
import scipy.integrate as si
import matplotlib.pyplot as plt

x = np.deg2rad(np.arange(0, 360+0.05, 0.1))
y = np.sin(x)
z = si.cumtrapz(y, (x), initial=-1.0)
plt.clf()
plt.plot(x, y, label='$y(x)$')
plt.plot(x, z, label='$\int y \, dx$')
plt.legend(loc=0)
plt.show()
```
### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>

```
$\int y \, dx$ graph suddenly jumps from initial value

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>

0.18.1 1.11.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment] 2017-09-19 09:34
Thanks for the report @kangwonlee. You're right that in your case ``initial=0`` makes sense, but the description in the docstring explains that. So not really a bug. 

The reason for providing ``initial`` is to be able to return an array of the same length as the input, rather than one less (which is annoying for plotting etc.). The authors could have chosen to use the ``initial=0`` behavior as the default and leave out the keyword completely though.

**Comment by rgommers** [comment] 2017-09-19 09:34
Since not a bug and we can't change the behavior anymore due to backwards compatibility, I'm closing this issue.

**Closed by rgommers** 2017-09-19 09:34 UTC
Labels: scipy.integrate

**Comment by kangwonlee** [comment] 2017-09-20 05:30
@rgommers Thanks for your comments.  

* I could find the [docstring](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.cumtrapz.html) of the `cumtrapz()` function:
> If given, uses this value as the first value in the returned result. Typically this value should be 0. Default is None, which means no value at x[0] is returned and res has one element less than y along the axis of integration.
* Do you think the following description could be more clear or specific?
> If given, insert this value at the beginning of the returned result. Typically this value should be 0. Default is None, which means no value at x[0] is returned and res has one element less than y along the axis of integration.
* Or, do you think it would be a good idea to try to introduce another default argument such as `base` or would it just add more complexity?

Thanks again & Good day,

KW

**Comment by rgommers** [comment] 2017-09-20 07:45
I think the change to the docstring you propose looks good, and it's probably not a great idea to add another keyword.

**Comment by kangwonlee** [comment] 2017-09-22 17:58
@rgommers Hope #7913 helps.

KW

**Comment by rahulbhadani** [comment] 2021-06-04 02:01
That's kind of stupid that `initial=<insert some arbitrary value>` doesn't set the initial conditions for integration. 
Developers of scipy should really look at integrator block of Mathworks's Simulink to see how to really implement integrate function.

https://www.mathworks.com/help/simulink/slref/integrator.html

**Comment by zhihua-zheng** [comment] 2022-05-13 07:45
Agree with @rahulbhadani. This is an issue that needs improvment.
