### ISSUE TITLE
BUG: hypergeom.sf sometimes fails with multidimensional inputs

### ISSUE THREAD

**Issue by ascillitoe** [scipy/scipy#15044] opened 2021-11-15 23:20 UTC
### Describe your issue.

In older scipy versions (<1.7.0) `hypergeom` and its methods were able to be vectorized over higher dimensional arrays (e.g. 2D ndarray's). However, some of the methods (e.g. `.sf`)  do not work consistently here in version >=1.7.0. More specifically, `hypergeom.sf` and `hypergeom.logsf` sometimes fail on multdimensional arrays, but `hypergeom.cdf` (which is equivalent to `1-hypergeom.sf`) is OK.

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import hypergeom

arg1 = np.array([
    [ 8,  7],
    [ 6,  6],
    [ 6,  7],
    [ 8,  8],
    [10, 11]]
    )

arg2 = np.array([
    [1020, 1020],
    [1020, 1020],
    [1020, 1020],
    [1020, 1020],
    [1020, 1020]]
    )

arg3 = np.array([
    [508, 507],
    [506, 506],
    [506, 507],
    [508, 508],
    [510, 511]]
    )

arg4 = np.array([
    [20, 20],
    [20, 20],
    [20, 20],
    [20, 20],
    [20, 20]]
    )

# Test explict loop - this works
result_exp = np.empty_like(arg1, dtype=np.float64)
for j in range(arg1.shape[1]):
    result_exp[:,j] = hypergeom.sf(arg1[:,j], arg2[:,j], arg3[:,j], arg4[:,j])

# Test vectorised algo - works in <1.7.0, does not work in >=1.7.0
result_vec = hypergeom.sf(arg1, arg2, arg3, arg4)

# but cdf still works
hypergeom.cdf(arg1, arg2, arg3, arg4)

# Compare results
print('Results match?', np.array_equal(result_exp, result_vec))
```

### Error message

```shell
Traceback (most recent call last):
  File "test_scipy2.py", line 42, in <module>
    result_vec = hypergeom.sf(arg1, arg2, arg3, arg4)
  File "/home/ascillitoe/Software/alibi-detect/venv/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 3304, in sf
    place(output, cond, np.clip(self._sf(*goodargs), 0, 1))
  File "/home/ascillitoe/Software/alibi-detect/venv/lib/python3.8/site-packages/scipy/stats/_discrete_distns.py", line 542, in _sf
    k2 = np.arange(quant + 1, draw + 1)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### SciPy/NumPy/Python version information

1.7.2 1.19.5 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

**Comment by mdhaber** [comment] 2022-03-13 21:21
I can't reproduce this in `main`, and it doesn't look like a platform-dependent sort of thing, so closing. Please re-open if you can reproduce it in `main`.
@tirthasheshpatel would you check me? Just copy-paste and execute the example above.

**Closed by mdhaber** 2022-03-13 21:21 UTC
Labels: defect, scipy.stats

**Comment by tirthasheshpatel** [comment] 2022-03-14 02:16
Confirmed. It works for me too on main.
