### ISSUE TITLE
BUG: special: bdtr(k, n, p) returns nan for n > 2**31-1

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#9454] opened 2018-11-07 23:58 UTC
`bdtr` returns `nan` whenever `n` > 2**31 - 1.  For example,

```
In [14]: import scipy

In [15]: scipy.__version__
Out[15]: '1.2.0.dev0+dfc9a9c'

In [16]: from scipy.special import bdtr

In [17]: bdtr([0, 2**30, 2**31-1], 2**31, 0.5)
Out[17]: array([nan, nan, nan])
```
If I use `n = 2**31-1`, the values are not `nan`:
```
In [18]: bdtr([0, 2**30, 2**31-1], 2**31-1, 0.5)
Out[18]: array([0.       , 0.8891082, 1.       ])
```

This is on a 64 bit system.

This looks related to https://github.com/scipy/scipy/issues/5503, but I don't know if it is a duplicate.

`bdtr(k, n, p)` calls `incbet(n - k, k+1, 1.0-p)`, so the underlying problem is probably in `incbet`.  Note that the first two arguments of `incbet` are `double`, not integers.

This problem was reported as [a question on stackoverflow](https://stackoverflow.com/questions/53199088/scipy-stats-binom-cdf-returns-nan), where it appeared as a problem with `scipy.stats.binom.cdf`:

```
In [26]: from scipy.stats import binom

In [27]: binom.cdf([0, 2**30, 2**31-1], 2**31, 0.5)
/Users/warren/miniconda36/lib/python3.6/site-packages/scipy-1.2.0.dev0+dfc9a9c-py3.6-macosx-10.7-x86_64.egg/scipy/stats/_discrete_distns.py:60: RuntimeWarning: floating point number truncated to an integer
  vals = special.bdtr(k, n, p)
Out[27]: array([nan, nan, nan])
```

**Comment by tpudlik** [comment] 2018-11-24 20:07
> Note that the first two arguments of `incbet` are `double`, not integers.

That's true, but [bdtr](https://github.com/scipy/scipy/blob/8dba340293fe20e62e173bdf2c10ae208286692f/scipy/special/cephes/bdtr.c) casts `k` and `n` to `int` before calling `incbet`.  I even get a runtime warning about this if I explicitly make `k` a `float`:

    >>> bdtr([0, float(2**30), float(2**31-1)], 2**31, 0.5)
    __main__:1: RuntimeWarning: floating point number truncated to an integer

It looks like the problem is that `n` is too large for a C `int`.  Maybe this could be fixed just by making `n` and `k` be `int64_t` instead of `int`?  (Is C99 code OK in Scipy?)

**Comment by rgommers** [comment] 2018-11-24 23:31
> Is C99 code OK in Scipy?

Should be, now that we've dropped Python 2.7 for the next release. I'm not really sure about portability of `int64_t` on other platforms though (most C99 issues were Windows Python 2.7 related, that's the part we can stop worrying about). 

On closer inspection, should be fine given that Cython does `ctypedef npy_int64      int64_t`.

**Comment by rlucas7** [comment] 2020-01-10 03:01
We made some changes to `bdtr` functions and I wanted to see if this issue is still an issue, looks like it is: 
```
>>> from scipy.special import bdtr 
>>> bdtr([0, 2**30, 2**31-1], 2**31, 0.5)
array([nan, nan, nan])
>>> from scipy.stats import binom
>>> binom.cdf([0, 2**30, 2**31-1], 2**31, 0.5)
array([nan, nan, nan])
>>> import scipy
>>> scipy.__version__
'1.5.0.dev0+9a0ada2'
>>> 
```
I'm not sure what the solution is here but figured I'd update the issue, with #11045 merged the plan 
is to deprecate the bdtr function from accepting non-`int` `n` values, see e.g. 
https://github.com/scipy/scipy/pull/11045/files#diff-fd81e7b91e9207faab6e37c6809e382aR41

@tpudlik it looks like you may have a branch on your fork that may (or may not) address the issue, are you still interested in working on this issue?

**Comment by person142** [comment] 2020-01-10 03:36
@rlucas7 this should be fixed once the legacy deprecation expires, so I'm going to close. If someone wants to bump the signature to a long int that seems fine too.

**Closed by person142** 2020-01-10 03:36 UTC
Labels: defect, scipy.special

**Comment by rlucas7** [comment] 2020-01-10 04:53
> On Jan 9, 2020, at 10:36 PM, Josh Wilson <notifications@github.com> wrote:
> 
> ﻿
> @rlucas7 this should be fixed once the legacy deprecation expires, so I'm going to close. If someone wants to bump the signature to a long int that seems fine too.
> 
Yeah I can probably look into that signature change over the weekend. Better to do it now while the code is still (somewhat) fresh in mind.
