### ISSUE TITLE
Build error  No BLAS/LAPACK libraries found

### ISSUE THREAD

**Issue by huwei1024** [scipy/scipy#13533] opened 2021-02-08 15:12 UTC
numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found. Note: Accelerate is no longer supported.
To build Scipy from sources, BLAS & LAPACK libraries need to be installed.

How can i build source on mac m1?

**Comment by ilayn** [comment] 2021-02-08 18:13
Duplicate of #13409

**Closed by ilayn** 2021-02-08 18:13 UTC
