### ISSUE TITLE
Convergence issue of GMRES

### ISSUE THREAD

**Issue by gokberkkabacaoglu** [scipy/scipy#12748] opened 2020-08-20 07:24 UTC
My issue is about a convergence issue when using scipy.sparse.linalg.gmres routine. When using GMRES with a preconditioner, it seems that the convergence is tested by looking at the residual not the preconditioned residual. So, although the preconditioned residual is smaller than the absolute tolerance I ask, the iterations do no stop if the (not preconditioned) residual is greater than the tolerance. In order to fix this, I need to go into iterative.py and add the following lines (under the if conditional elif(ijob==3):
if presid < atol and np.linalg.norm(x) > 0:
  resid = 0.0
  break

This kind of hard coding is not something I prefer. I will appreciate if you can take a look at this issue and inform me about it.

Thanks!

#### Reproducing code example:

```
Sample code to reproduce the problem
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by rgommers** [comment] 2022-02-22 20:44
There's a GMRES rewrite in progress. This cannot be investigated as an issue without sample code to reproduce the problem. I'll leave it open for now, but maybe you can recommend an action here (close or follow up) @zhaog6?

**Comment by zhaog6** [comment] 2022-02-23 02:21
@rgommers Yes, I am rewriting the restarted GMRES. The original GMRES did use the residual instead of the preconditioned residual.

**Comment by blackwer** [comment] 2022-02-23 11:10
I've been working with @gokberkkabacaoglu on code that requires our little patch. Since you acknowledge this is an issue, is there anything you still need from us?

**Comment by rgommers** [comment] 2022-02-23 12:24
That's good to hear @blackwer. Maybe you can check PR gh-15149 and see if that already fully addresses your issue? And if not provide a test case and/or suggested algorithmic improvement there?

**Comment by zhaog6** [comment] 2022-02-24 08:28
Dear Robert @blackwer , I am glad that we are all focused on this issue. The reimplemented restarted GMRES (PR gh-15149) has been basically completed and it uses preconditioned residual norm as convergence criterion. You can copy the PR code to your local and use the implementation to test your issue.

**Comment by blackwer** [comment] 2022-03-01 17:20
@zhaog6 I was about to test this and it seems you had some issues with deleting your fork. Can you ping me when this is resolved?

**Comment by zhaog6** [comment] 2022-03-24 10:35
@blackwer Thank you for your attention. The new PR is in gh-15693

**Comment by zhaog6** [comment] 2022-03-24 12:25
> That said, your version is taking more iterations than our patch to converge (~26 vs your ~31), and also giving very slightly different results.

Dear @blackwer , you can copy the following code and make a testing.
```python
import numpy as np
from scipy.sparse import spdiags
from gmresk import *

nn = 100
data0 = 2 * np.ones(nn)
data1 = - np.ones(nn)
data = np.array([data1, data0, data1])
A = spdiags(data, [-1, 0, 1], nn, nn)
b = - data1
x, info = gmresk(A, b, restart=20, show=True)  # relative tolerance is 1.0e-5 by default
x, info = gmresk(A, b, restart=40, show=True)
x, info = gmresk(A, b, restart=100, show=True)
```
The iterative steps is 1217, 580, 50  respectively in my server. And if you are familiar with PETSc (ANL) and can master it, you'll check and find that the iterations is same and the convergence history of residual norm is almost same but the implementation is different.

**Comment by zhaog6** [comment] 2022-03-24 12:31
> Edit: I found your repo and used the fastgmres branch. The GMRES iterations are indeed much faster (though partly from improvements to numpy).

Yes, there are also some improvements of data storage way based on Python and other mathematical optimizations.

**Comment by ilayn** [comment] 2023-05-29 21:19
Now that #18488 is going to be merged for v.1.12, I'd like to mention that preconditioned tolerance level has no guarantee for the actual solution to be converged. It depends on the success of the preconditioner. However if needed the tolerance values can be altered with the presolve(b) value as a rough estimate of the relationship between `atol`, `rtol` and `pretol`. Now that it is pure python it should be much easier to hack into it.

**Closed** 2023-06-18 09:18 UTC
Labels: scipy.sparse.linalg
