### ISSUE TITLE
Difference between `lu` and `lu_factor`

### ISSUE THREAD

**Issue by Juanlu001** [scipy/scipy#4085] opened 2014-10-19 11:41 UTC
Apparently these two functions do exactly the same but there are no links between them in the documentation. Is there a reason to keep the two? If so, perhaps it's worth adding to the docs.

https://github.com/scipy/scipy/blob/master/scipy/linalg/decomp_lu.py#L17

**Comment by ilayn** [comment] 2017-11-24 00:25
The difference is as given above and the motivation is that you factor your matrix once and you reuse your factorization to solve for different RHS of the equations. It's a bit too low level for the generic audience of SciPy in my opinion. But there is also some issue with rejecting empty matrices as given in #8056 so closing this as a duplicate of that. 

I'll hopefully submit a PR that would attempt to fix this as soon as I have time.

**Closed by ilayn** 2017-11-24 00:25 UTC
Labels: defect, Documentation, scipy.linalg
