### ISSUE TITLE
BUG: grey_erosion discrepancy in different calling styles

### ISSUE THREAD

**Issue by RSKothari** [scipy/scipy#19384] opened 2023-10-13 17:59 UTC
### Describe your issue.

Output mismatch when calling `grey_erosion(im, structure=kernel)` vs `grey_erosion(im, (filt_sz, filt_sz))` when kernel is defined as flat, square array of ones. The expectations is that the values would match.

### Reproducing Code Example

```python
from scipy.ndimage import grey_erosion
import numpy as np

im = np.random.rand(50, 50)

filt_sz = 7
kernel = np.ones((filt_sz, filt_sz))

out_with_kernel = grey_erosion(im, structure=kernel)
out_with_sz = grey_erosion(im, (filt_sz, filt_sz))

assert (abs(out_with_kernel - out_with_sz) < 1e-5).all(), 'Mismatch detected'
```

### Error message

```shell
Mismatch detected.
```

### SciPy/NumPy/Python version and system information

```shell
1.9.1 1.24.3 sys.version_info(major=3, minor=8, micro=18, releaselevel='final', serial=0)
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rakshit/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rakshit/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rakshit/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rakshit/opt/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rakshit/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rakshit/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/rakshit/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/rakshit/opt/anaconda3/include']
```

**Comment by grlee77** [comment] 2024-05-26 16:50
Hi @RSKothari, sorry this issue was neglected.

This is not a bug, but just a misunderstanding of how the `grey_erosion` function works. It is admittedly not trivial to understand from the description and I double checked the underlying C implementation to verify the expected behavior is as described below:

When you called this function:
```
grey_erosion(im, (filt_sz, filt_sz))
```
That is applying a minimum filter over the values in a neighborhood of shape `(filt_sz, filt_sz)`

This would be equivalent to calling with `footprint` and NOT `structure`. The example below verifies this.
```py
from scipy.ndimage import grey_erosion
import numpy as np

im = np.random.rand(50, 50)

filt_sz = 7
kernel = np.ones((filt_sz, filt_sz))

np.testing.assert_allclose(
    grey_erosion(im, (filt_sz, filt_sz)) ,
    grey_erosion(im, footprint=kernel),
)
```

The values in `structure` result in a shift in the grayscale values used for the erosion at positions falling within the footprint. For erosion the shift is done by subtracting the values in structure, but for dilation it would be the opposite. To get an equivalent result to specifying just the `size` argument, `structure` would need to be zero everywhere.
```py
# structure that is all zeros so no grayscale shift
np.testing.assert_allclose(
    grey_erosion(im, (filt_sz, filt_sz)) ,
    grey_erosion(im, structure=np.zeros_like(kernel)),
)

# offset image by 1 is equivalent to structure shift of 1
np.testing.assert_allclose(
    grey_erosion(im - 1, (filt_sz, filt_sz)) ,
    grey_erosion(im, structure=kernel),
)
```

I think the real-world use case for structure is only for cases where the amplitude of the values is not equal over the footprint.

**Comment by grlee77** [comment] 2024-05-26 16:55
closing as not a bug, please see explanation above

**Closed by grlee77** 2024-05-26 16:55 UTC
Labels: defect, scipy.ndimage

**Comment by grlee77** [comment] 2024-05-26 17:08
opened #20799 to make the documentation clearer
