### ISSUE TITLE
BUG: special: Riccati Bessel function of the second kind lacks a minus sign

### ISSUE THREAD

**Issue by Hugokth** [scipy/scipy#17920] opened 2023-02-03 10:00 UTC
The Riccati Bessel function of the second kind: scipy.special.riccati_yn(n, x) is coded as xy_n(x) whereas it should be **-**xy_n(x) leading to errors in calculations.

Thank you for taking this into account

**Comment by ev-br** [comment] 2023-02-03 14:31
A comment from 30000 feet: these sorts of suggestions are best backed up with some more details of commonly used conventions for phases, links to classic texts or other resources. 

As written, it is full well possible that it us just a different convention for the global phase. If there are several, then the best course of action could be to document the one we use.

**Comment by Hugokth** [comment] 2023-02-03 16:13
I have never seen the Riccati Bessel function of the third kind written as xy_n(x) instead of -xy_n(x).
However it is true that this comment would be better documented.
Hence, here is some litterature showing that scipy.special.riccati_yn(n, x) should be -xy_n(x):
**Wikipedia:**
https://en.wikipedia.org/wiki/Bessel_function
**Book:**
Absorption and Scattering of Light by Small Particles - C. Bohren, D. Huffman https://onlinelibrary.wiley.com/doi/book/10.1002/9783527618156
**Research report:**
MATLAB Functions for Mie Scattering and Absorption Version 2 - C. Mätzler
**Book**:
Light Scattering by Small Particles - H. C. van de Hulst 
https://books.google.fr/books?id=777DAgAAQBAJ&hl=fr
**Article**:
On the computation of Riccati-Bessel functions - P. Malicky, M. Malicka
https://eudml.org/doc/15649

I haven't found any litterature with scipy.special.riccati_yn(n, x) = xy_n(x) but if I do i will post the references here.

**Comment by mdhaber** [comment] 2024-09-22 02:57
This is a duplicate of gh-12895. References without the negative sign are posted there. gh-21603 closes these by highlighting the sign convention used by SciPy in the docstring.

**Closed** 2024-09-22 07:27 UTC
Labels: defect, scipy.special
