### ISSUE TITLE
Accuracy of non-central chi-squared distribution implementation in scipy

### ISSUE THREAD

**Issue by pyguy3** [scipy/scipy#8712] opened 2018-04-12 07:10 UTC
The implementation of the non-central chi-squared distribution in scipy (scipy.stats.ncx2, scipy.special.chndtr) is not accurate for large values of the non-centrality parameter. E.g. consider

### Reproducing Code example:

`from scipy.stats import ncx2`

`print(ncx2.cdf(1200,2,1000))`
`print(ncx2.cdf(1500,2,1000))`
`print(ncx2.cdf(2000,2,1000))`
`print(ncx2.cdf(5000,2,1000))`

which produces

0.998604279948
0.999933004449
0.999933004449
0.999933004449

instead of converging to one.

The [implementation](https://github.com/scipy/scipy/blob/master/scipy/special/cdflib/cdfchn.f) in scipy is based on Formula 26.4.25 of Abramowitz and Stegun, Handbook of Mathematical Functions (1966).

There are faster and more accurate algorithms for implementing this function, especially for large non-centrality parameter (ncp). For example, [R](http://stat.ethz.ch/R-manual/R-devel/library/stats/html/Chisquare.html) apparently uses Ding (1992) for ncp>80. However [boost](https://www.boost.org/doc/libs/1_38_0/libs/math/doc/sf_and_dist/html/math_toolkit/dist/dist_ref/dists/nc_chi_squared_dist.html) states that Ding can take a long time to converge for large ncp, and recommends a different method. I am wondering if it is worth upgrading the implementation in scipy to work for large non-centrality?

### Scipy/Numpy/Python version information:
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.18.0 1.11.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment] 2018-04-13 23:35
@pyguy3, thanks for reporting the problem.

This is a duplicate of https://github.com/scipy/scipy/issues/8665

**Closed by WarrenWeckesser** 2018-04-13 23:35 UTC
Labels: defect, duplicate, scipy.special, scipy.stats
