### ISSUE TITLE
BUG: MemoryError Not enough memory to perform factorization.

### ISSUE THREAD

**Issue by chfhf** [scipy/scipy#18148] opened 2023-03-14 14:18 UTC
### Describe your issue.

I have a  matrix norm_adj representing a simple undirect bipartite graph, the matrix size is (29809,40764), I want to get the smaller eigenvectors of A1, A1 was a 2 x 2 block symmetric matrix composed of R and the size of A1 is (70573,70573), but this code suffers a memory error, how should I do to fix it? 

### Reproducing Code Example

```python
# the size of norm_adj is (29809,40764)
# the size of A1 is (70573,70573)

import scipy.sparse as sp
from scipy.sparse.linalg import eigsh
u2u = norm_adj @ norm_adj.T
l2l = norm_adj.T @ norm_adj
u2l = norm_adj
A1 = sp.bmat([[u2u, u2l], [u2l.T, l2l]])
A1 = sp.eye(A1.shape[0]) - A1
vals, vecs = eigsh(A1, k=10, sigma=-1, which='LM', tol=1E-3)
```

### Error message

```shell
python(45746,0x106622e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744056529682432, flags: 100) failed (error code=3)
python(45746,0x106622e00) malloc: *** set a breakpoint in malloc_error_break to debug
python(45746,0x106622e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744056529682432, flags: 100) failed (error code=3)
python(45746,0x106622e00) malloc: *** set a breakpoint in malloc_error_break to debug
python(45746,0x106622e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744065119617024, flags: 100) failed (error code=3)
python(45746,0x106622e00) malloc: *** set a breakpoint in malloc_error_break to debug
Not enough memory to perform factorization.
Traceback (most recent call last):
  File "test.py", line 132, in <module>
    vals2, vecs2 = eigsh(A1, k=10, sigma=-1, which='LM', tol=1E-3)
  File "/Users/chf/opt/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1641, in eigsh
    Minv_matvec = get_OPinv_matvec(A, M, sigma,
  File "/Users/chf/opt/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1074, in get_OPinv_matvec
    return SpLuInv(A).matvec
  File "/Users/chf/opt/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 914, in __init__
    self.M_lu = splu(M)
  File "/Users/chf/opt/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 337, in splu
    return _superlu.gstrf(N, A.nnz, A.data, A.indices, A.indptr,
MemoryError
```

### SciPy/NumPy/Python version and system information

```shell
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/chf/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/chf/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/chf/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/chf/opt/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/chf/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/chf/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/chf/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/chf/opt/anaconda3/include']
```

**Comment by tylerjereddy** [comment] 2023-03-14 22:46
Note that this code isn't really reproducing since `norm_adj` is only *described* rather than i.e., constructed programmatically.

If I do something like this on top of the example:

```python
rng = np.random.default_rng(123)
norm_adj = rng.random((29809, 40764))
```

I can see the memory climb up to > 60 % on a machine with 128 GB RAM, so it does indeed get a pretty substantial footprint.

**Comment by rgommers** [comment] 2023-03-15 10:29
This isn't really a bug, right? Factorizing a large matrix requires a lot of memory.

**Comment by ogauthe** [comment] 2023-03-16 09:17
@chfhf the simplest solution here is to use a computer with more memory. You may save a bit of memory by deleting temporary arrays before calling `eigsh`, such as `u2u`, `l2l` and `u2l`, but large arrays will always be heavy in memory:

```python
u2u = norm_adj @ norm_adj.T
l2l = norm_adj.T @ norm_adj
u2l = norm_adj
A1 = sp.bmat([[u2u, u2l], [u2l.T, l2l]])
A1 = sp.eye(A1.shape[0]) - A1
del u2u, l2l, u2l
vals, vecs = eigsh(A1, k=10, sigma=-1, which='LM', tol=1E-3)
```

Just calling `del` may not be enough to recover the memory, you may also define a specific function just to construct A1 to call the garbage collector before calling `eigsh`.

I think this can be closed as there is nothing to be done for scipy.

**Closed** 2023-03-16 16:59 UTC
Labels: scipy.sparse.linalg, query
