### ISSUE TITLE
BUG: hypergeom.cdf slower in 1.8.0 than 1.7.3

### ISSUE THREAD

**Issue by bgyori** [scipy/scipy#16079] opened 2022-04-30 14:29 UTC
### Describe your issue.

While using the `fisher_exact` test in a loop on some 2x2 tables, I noticed a significant slowdown between Scipy versions 1.7.3 and 1.8.0 (1.8.0 is about 20x slower than 1.7.3). I narrowed it down to the call to `hypergeom.cdf`, and found a specific set of arguments with which the slowdown can be reproduced (see code example below).

### Reproducing Code Example

```python
import time
import scipy
from scipy.stats import distributions

ts = time.time()
for _ in range(10000):
    distributions.hypergeom.cdf(0, 48127, 57, 35775)
te = time.time()
print(scipy.__version__, '%.2fs' % (te-ts))

# Output for version info 1.7.3 1.22.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
# 1.7.3 1.84s

# Output for version info 1.8.0 1.22.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
# 1.8.0 41.11s
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

1.8.0 1.22.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by mdhaber** [comment] 2022-04-30 15:13
We switched from a custom implementation to using Boost to improve accuracy. One path forward would be to confirm that this is an issue with Boost itself and ask for improvement upstream. Another would be to try to determine when the old implementation would give accurate results and use Boost only when necessary.

**Comment by bgyori** [comment] 2022-04-30 15:55
Thanks @mdhaber. I can confirm that on 1.8.0, my example above boils down to:
```
import numpy as np
import scipy.stats._boost as _boost
_boost._hypergeom_cdf(np.array([0]), np.array([57]), np.array([35775]), np.array([48127]))
```
and the slowdown is reproducible with this call, so the performance issue is indeed related to Boost.

I also found that the slowdown persists on two different Ubuntu 20.04 systems both running Python 3.8 but on a Mac running Python 3.9, there is a much smaller, ~1.5x slowdown between 1.7.3 and 1.8.0.

**Comment by mdhaber** [comment] 2022-06-08 11:43
@bgyori do you think this should remain open? If Boost is very slow on certain platforms, it sounds like something that could be reported upstream. In principle, we could switch between the two implementations, but this would add undesirably complexity (and performance overhead), and it's unclear whether we would be able to confidently identify a range of parameters for which the old method was suitably accurate. With that in mind, do you have suggestions for what to do here?

**Comment by bgyori** [comment] 2022-06-11 21:24
Hi @mdhaber, thanks for following up. I tried looking around but couldn't figure out what part of the Boost code `_boost._hypergeom_cdf` originates from (this bit of code is as far as I could trace things back: https://github.com/scipy/scipy/blob/e1d2f1c5db9810e36792e5599bba53cbfb1a4539/scipy/stats/_boost/meson.build#L15-L22). If I were to file an issue with Boost, do you know which function I should refer to as being slow?

**Comment by steppi** [comment] 2022-06-11 22:11
Hi Ben, small world! Boost wrappers in SciPy are auto-generated, which can make it difficult to track down the original source code for functions. Here are the [docs for Boost's hypergeometric distribution](https://www.boost.org/doc/libs/1_79_0/libs/math/doc/html/math_toolkit/dist_ref/dists/hypergeometric_dist.html). The hypergeometric cdf is implemented [here](https://github.com/boostorg/math/blob/2b9927871fd86312f753e4bcbdb82236022c5856/include/boost/math/distributions/detail/hypergeometric_cdf.hpp) and  public facing hypergeometric distribution class is [here](https://github.com/boostorg/math/blob/2b9927871fd86312f753e4bcbdb82236022c5856/include/boost/math/distributions/hypergeometric.hpp). 

SciPy ships a [lightweight headers only Boost distribution](https://github.com/scipy/boost-headers-only) which is included as a submodule of the main repo. Cython .pyx wrappers for the Boost stats distributions used in SciPy are generated [here](https://github.com/scipy/scipy/blob/main/scipy/stats/_boost/include/code_gen.py). I haven't worked on these things, but my understanding is that integrating Boost into SciPy was not an easy task and it could not be done in a straightforward way.

Hi @mdhaber!  @bgyori is my former PI. I think it's fine for you to go ahead an close this issue. I've agreed to submit an issue to the Boost developers on his behalf.

**Comment by mdhaber** [comment] 2022-06-12 07:03
Great. Thanks @steppi @bgyori!

**Comment by steppi** [comment] 2022-06-12 14:00
@mdhaber I'll try to write a reproducible example directly in C++. That should help us rule out a problem with the wrapper if it isn't the source of the slowdown.

**Comment by cthoyt** [comment] 2022-11-04 11:22
Just confirming that things seem alright in scipy 1.9:

I just ran the example on Mac OS 13 (Ventura) with python 3.10 and scipy 1.9.3:

```python
import time
import scipy
from scipy.stats import distributions
import sys

ts = time.time()
for _ in range(10000):
    distributions.hypergeom.cdf(0, 48127, 57, 35775)
te = time.time()

print(sys.version)
print("scipy:", scipy.__version__)
print("time:", '%.2fs' % (te-ts))
```

And got

```
3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
scipy: 1.9.3
time: 2.04s
```

**Comment by bgyori** [comment] 2022-11-04 11:44
@cthoyt The issue I reported above was primiarily on Ubuntu and we determined it to be Boost-related. I confirmed that updating the scipy version to 1.9.3 alone does not change it.

**Comment by steppi** [comment] 2022-11-05 14:42
> @cthoyt The issue I reported above was primiarily on Ubuntu and we determined it to be Boost-related. I confirmed that updating the scipy version to 1.9.3 alone does not change it.

I'm still planning to attempt to isolate the problem and submit an issue to the boost developers. I've been very busy but hope to get to it by the end of the year.

**Comment by mdhaber** [comment] 2022-12-01 19:18
I reopened this due to a new report in gh-17519 for the `pmf`. Personally, I would consider it closed if we can isolate the problem and report it to Boost. In the meantime, users are welcome to use the old `hypergeom` code.

```details
    
    def _pmf(k, M, n, N):
        # same as the following but numerically more precise
        # return comb(good, k) * comb(bad, N-k) / comb(tot, N)
        return exp(_logpmf(k, M, n, N))

    def _logpmf(k, M, n, N):
        tot, good = M, n
        bad = tot - good
        result = (betaln(good+1, 1) + betaln(bad+1, 1) + betaln(tot-N+1, N+1) -
                  betaln(k+1, good-k+1) - betaln(N-k+1, bad-N+k+1) -
                  betaln(tot+1, 1))
        return result
```

**Comment by naodell** [comment] 2022-12-01 20:03
I've noticed this issue as well and have addressed it by generating bindings for the much faster GSL implementation (see the discussion [here](https://stackoverflow.com/questions/42831438/how-to-efficiently-vectorise-hypergeomentric-cdf-calculation)) and using those instead.  While fairly simple, this is obviously not ideal.

I've also noticed that the implementation of the inverse cdf (ppf) calculation suffers from both the calls to the suboptimal cdf calculation _and_ using binary search.  The latter is a separate issue all together, and I suppose this is considered an acceptable fallback when the ppf can't be calculated analytically in that it will find the right answer, but you can virtually always do better perfomance-wise by using other available information about the pdf/pmf.  For example, I was able to get a substantial speedup simply picking the initial value in the search to use the value of the ppf you would get under the assumption of normality.

**Comment by mdhaber** [comment] 2022-12-02 07:27
@steppi did you have a chance to report this to Boost? I didn't find it.

**Comment by steppi** [comment] 2022-12-02 12:13
> @steppi did you have a chance to report this to Boost? I didn't find it.

No, unfortunately. Sorry about that. I ended up going through an extremely busy stretch after that and it slipped my mind.

**Comment by steppi** [comment] 2022-12-10 14:54
> @steppi did you have a chance to report this to Boost? I didn't find it.

I can do this on Tuesday evening if no one else has time before then.

**Comment by mdhaber** [comment] 2022-12-10 16:47
No problem! That would be terrific. (At some point I should really learn to run simple Boost stuff in C++...)

**Comment by mdhaber** [comment] 2023-01-05 07:56
@steppi Happy new year! I thought I'd check about this - did you have a chance to report the issue?

**Comment by steppi** [comment] 2023-01-23 04:57
I finally did some digging into this today. I don't think I'm quite ready to report an issue to Boost, but I did find that it's not a Mac vs Linux issue, but instead c++11 vs c++14 issue.

I wrote the following short c++ program ((I modified the original example to use different values to eliminate the impact of caching.)

```C++

#include <iostream>
#include <boost/math/distributions/hypergeometric.hpp>

using namespace std;
using boost::math::cdf;
using boost::math::hypergeometric;

int main(void) {
  for (int N = 48000; N < 50000; N++) {
    for (int r = 55; r < 59; r++) {
      hypergeometric hg(r, 35775, N);
      cdf(hg, 0);
    }
  }
  return 0;
}
```

Using an M1 Macbook Air I compiled the program with both c++11 and c++14 using the following two commands

`clang++ -std=c++11 -stdlib=libc++ -I ~/boost-headers-only -o hypergeom1 hypergeom.cc`
`clang++ -std=c++14 -stdlib=libc++ -I ~/boost-headers-only -o hypergeom2 hypergeom.cc`

and the results are dramatically different.

```
> time ./hypergeom1
./hypergeom1  0.78s user 0.01s system 56% cpu 1.409 total
```

```
> time ./hypergeom2
./hypergeom2  12.14s user 0.07s system 97% cpu 12.473 total
```

It seems the std flag to use is decided in [scipy/_build_utils.compiler_helper.py](https://github.com/scipy/scipy/blob/a0f9a590c51d9a1e002559e644ea13ec7c897d3f/scipy/_build_utils/compiler_helper.py#L9-L31) by testing if a dummy program will compile. I'm not sure why c++14 fails here but works fine when compiling directly with clang++.

I've found some chatter [here](https://codeforces.com/blog/entry/53675) about programs running slower when compiling with c++14 instead of c++11. The examples in that link don't even use Boost. It would be funny if this needed to be kicked even further upstream. I plan to dig a little more before submitting an issue. Hopefully later this week.

**Comment by mdhaber** [comment] 2023-01-23 06:23
Thanks @steppi! Good to know it's not SciPy.
@mckib2 @mborland thought you might be interested in this.

**Comment by mborland** [comment] 2023-01-23 16:14
When approximately were Scipy 1.7.3 and 1.8.0 released? I didn't see anything in the [release notes](https://docs.scipy.org/doc/scipy/release.1.7.3.html) that specified. Within that window we should be able to pull apart anything that would have caused this slowdown. @steppi The boost issue [is here](https://github.com/boostorg/math/issues/923) if you want to add anything else to it.

**Comment by steppi** [comment] 2023-01-23 17:12
Thanks for creating the issue @mborland!

**Comment by mdhaber** [comment] 2023-01-23 17:29
1.8.0 was released around Dec/Jan 2022. (SciPy releases a new 1.x.0 every six months, and we just released 1.10.0.)

Would you mind if we started to ping you on suspected Boost issues? So far, I've hesitated to bring an issue to your attention until we can confirm that the bug is in Boost itself, not our wrapper.

**Comment by mborland** [comment] 2023-01-23 17:44
> Would you mind if we started to ping you on suspected Boost issues? So far, I've hesitated to bring an issue to your attention until we can confirm that the bug is in Boost itself, not our wrapper.

I have no issue with that. I've been meaning to email you and the scipy team on behalf of the Boost.Math team.

**Comment by mborland** [comment] 2023-01-29 16:56
This has been fixed by https://github.com/boostorg/math/pull/930. In C++14 there was a change in memory storage duration that caused a >10,000 element table to be rebuilt numerous times during the evaluation of the cdf.

**Closed** 2023-02-27 22:24 UTC
Labels: scipy.stats, enhancement
