### ISSUE TITLE
Scipy ndimage.imageread cannot find PIL in Python3

### ISSUE THREAD

**Issue by benelot** [scipy/scipy#7347] opened 2017-04-28 10:17 UTC
I tried to import an image in python3 (through an ipython notebook) using scipy.ndimage like this:
```
from scipy import ndimage

image_file = ... # get yourself any kind of image file, the problem occurs before it gets relevant what it really is
ndimage.imread(image_file).astype(float)
```
I received an error message saying that scipy could not find pillow installed. However, I could resolve my problem by replacing the scipy call with:

```
from PIL import Image
np.array(Image.open(image_file)).astype(float)
```

which shows that in fact PIL is installed and works well.

### Error message:
/usr/local/lib/python3.4/dist-packages/scipy/ndimage/io.py in imread(fname, flatten, mode)
     23     if _have_pil:
     24         return _imread(fname, flatten, mode)
---> 25     raise ImportError("Could not import the Python Imaging Library (PIL)"
     26                       " required to load image files.  Please refer to"
     27                       " http://pillow.readthedocs.org/en/latest/installation.html"

### Scipy/Numpy/Python version information:

python3 --version
`Python 3.4.3`

pip3 list

```
appdirs (1.4.3)
backports-abc (0.5)
bleach (1.5.0)
chardet (2.2.1)
colorama (0.2.5)
command-not-found (0.3)
coverage (4.3.4)
cycler (0.10.0)
Cython (0.25.2)
decorator (4.0.11)
entrypoints (0.2.2)
enum34 (1.1.6)
futures (3.0.5)
grpcio (1.4.0.dev0)
html5lib (0.9999999)
ipykernel (4.6.1)
ipython (6.0.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
jedi (0.10.2)
Jinja2 (2.9.6)
jsonschema (2.6.0)
jupyter-client (5.0.1)
jupyter-core (4.3.0)
language-selector (0.1)
Markdown (2.2.0)
MarkupSafe (1.0)
matplotlib (2.0.0)
mistune (0.7.4)
mock (2.0.0)
nbconvert (5.1.1)
nbformat (4.3.0)
nose (1.3.1)
notebook (5.0.0)
numpy (1.12.1)
olefile (0.44)
packaging (16.8)
pandocfilters (1.4.1)
pbr (2.1.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (4.1.0)
pip (9.0.1)
prompt-toolkit (1.0.14)
protobuf (3.2.0)
ptyprocess (0.5.1)
pycurl (7.19.3)
Pygments (2.2.0)
pygobject (3.12.0)
pyparsing (2.2.0)
python-apt (0.9.3.5ubuntu2)
python-dateutil (2.6.0)
pytz (2017.2)
pyzmq (16.0.2)
requests (2.2.1)
scikit-learn (0.18.1)
scipy (0.19.0)
setuptools (35.0.2)
simplegeneric (0.8.1)
six (1.10.0)
sklearn (0.0)
tensorflow (1.1.0rc1)
terminado (0.6)
testpath (0.3)
tornado (4.5.1)
traitlets (4.3.2)
typing (3.6.1)
ufw (0.34-rc-0ubuntu2)
unattended-upgrades (0.1)
urllib3 (1.7.1)
wcwidth (0.1.7)
Werkzeug (0.12.1)
wheel (0.29.0)
widgetsnbextension (2.0.0)

```
Just tell me if you need additional information.

**Comment by pv** [comment] 2017-04-28 10:19
Works fine for me on Python 3.

**Comment by benelot** [comment] 2017-04-28 12:19
Strange...any ideas what could be the issue?

**Comment by cgohlke** [comment] 2017-05-03 22:08
Does `from scipy.misc.pilutil import imread as _imread` raise an `ImportError`?

**Comment by benelot** [comment] 2017-05-05 07:22
No. This passes fine.

**Comment by pv** [comment] 2017-05-05 08:06
Then you can try studying ift the file in question works stand-alone:
https://github.com/scipy/scipy/blob/master/scipy/ndimage/io.py
and if not, try finding out why.
.
The problem is likely not general, but looks like it's some quirk of 
your installation.

**Comment by rgommers** [comment] 2018-09-02 10:41
not a bug, and `imread` is deprecated anyway - so closing.

**Closed by rgommers** 2018-09-02 10:41 UTC
Labels: scipy.ndimage
