### ISSUE TITLE
Regression: Memory consumption when using scipy.stats.rv_continuous

### ISSUE THREAD

**Issue by cbourjau** [scipy/scipy#7253] opened 2017-04-03 19:02 UTC
Following the example given in the documentation I am using `rv_continuous` to generate a custom pdf. The following code snippet works as expected in scipy v0.18.1 but exhibits a very large (~GB) memory consumption when run with scipy v0.19.0

```python
from scipy.stats import rv_continuous
import numpy as np
import resource
import scipy
import sys

print "numpy version: {}".format(np.version.full_version)
print "Scipy version: {}".format(scipy.version.full_version)
print "Python {}".format(sys.version)

class gaussian_gen(rv_continuous):
    "Gaussian distribution"
    def _pdf(self, x):
        return np.exp(-x**2 / 2.) / np.sqrt(2.0 * np.pi)

def print_mem():
    mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    print 'Memory usage: %s (kb)' % mem

print_mem()
gaussian = gaussian_gen(name='gaussian')
print_mem()
values = gaussian.rvs(size=1000)
print_mem()
values = gaussian.rvs(size=5000)
print_mem()
```

The output of the snippet for version 0.18.1 is:

```
numpy version: 1.12.1
Scipy version: 0.18.1
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
Memory usage: 70048 (kb)
Memory usage: 70048 (kb)
Memory usage: 70048 (kb)
Memory usage: 70592 (kb)
```

while 0.19.0 looks as follows:
```
numpy version: 1.12.0
Scipy version: 0.19.0
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
Memory usage: 69672 (kb)
Memory usage: 69672 (kb)
Memory usage: 426952 (kb)
Memory usage: 2215576 (kb)
```

I just noticed that it appears to be working in master, but I figured it might be good to post this issue in any case, just so that people can find it or if it was only fixed by accident. Output when run on master:

```
numpy version: 1.12.1
Scipy version: 1.0.0.dev0+ab9eff3
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
Memory usage: 75972 (kb)
Memory usage: 75972 (kb)
Memory usage: 75972 (kb)
Memory usage: 75972 (kb)
```

Before opening this issue I asked a question about it at [stackoverflow](http://stackoverflow.com/questions/43181237/how-to-keep-memory-consumption-at-bay-when-using-scipy-stats-rv-continuous)

**Comment by pv** [comment] 2017-04-03 19:13
Possibly duplicate of gh-7214

**Comment by ev-br** [comment] 2017-04-03 19:35
If it is really a `quad` bug, it should disappear if you define `_cdf` too:

https://github.com/scipy/scipy/blob/3d5024b40e2e089251af1b4b89c5ec1c7145412c/scipy/stats/_distn_infrastructure.py#L1613

Can you add a `_cdf` implementation and check memory consumption @cbourjau ?

**Comment by cbourjau** [comment] 2017-04-06 12:28
@ev-br : Yes, I can confirm that the issue goes away if `_cdf` is defined using scipy 0.19. Thanks for your fast feedback on this issue!

**Comment by person142** [comment] 2017-04-06 12:55
Good, then this issue should be fixed in master.

**Closed by person142** 2017-04-06 12:55 UTC
