### ISSUE TITLE
`scipy.stats.qmc.LatinHypercube` cannot sample single sample at a time

### ISSUE THREAD

**Issue by kstoneriv3** [scipy/scipy#13647] opened 2021-03-05 18:23 UTC
I am playing around `scipy.stats.qmc` for hyperparameter optimization and found that `scipy.stats.qmc.LatinHypercube` cannot sample **one** sample. Though sampling one sample is an impractical case, I expect that it should not just throw an error in this case. 

@tupui I suppose you know a lot about this...

#### Reproducing code example:

```python
import scipy.stats.qmc

engine = scipy.stats.qmc.LatinHypercube(d=2)
engine.random()  # same as `engine.random(n=1)`
```

#### Error message:

```
Traceback (most recent call last):
  File "b.py", line 4, in <module>
    engine.random(n=1)
  File "/home/kstoneriv3/.local/lib/python3.8/site-packages/scipy-1.7.0.dev0+fc77ea1-py3.8-linux-x86_64.egg/scipy/stats/_qmc.py", line 956, in random
    q = self.rg_integers(low=1, high=n, size=(n, self.d))
  File "_generator.pyx", line 460, in numpy.random._generator.Generator.integers
  File "_bounded_integers.pyx", line 1254, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
```

#### Scipy/Numpy/Python version information:

1.7.0.dev0+fc77ea1 1.19.5 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

**Comment by tupui** [comment] 2021-03-05 18:39
Hi! Thanks for reporting this. I will look into it. I agree that it should not fail. Although not very useful, any single point is a valid LHS. Also note that currently there is so strategy to add samples and maintain the properties.

If you have an idea before me, feel free to do a PR 😄

**Comment by kstoneriv3** [comment] 2021-03-05 19:44
Thank you for the quick reply!

I came across this error because I was trying to sample QMC samples iteratively (e.g. calling `engine.random(5)` 2 times to sample 10 QMC samples.). This iterative sampling approach seems to work for the Sobol and the Halton but not for the LHS and OA-LHS. As far as I understood, LHS and OA-LHS sequences must be sampled in a batch. Am I correct about this? (I don't know much about QMC...)

If my understanding is correct, I would like to suggest removing `fast_forward(...)`  in LHS and OA-LHS because it makes it look as if LHS and OA-LHS support iterative sampling. (If you agree with it but are busy, I can make PR on this)

**Comment by tupui** [comment] 2021-03-05 20:27
Iterative sampling is tricky with QMC. It would only be safe with Halton (Sobol' is okay under certain conditions, basically doubling the number of samples. So if you had 64 ask for 64 to have 128. Then ask for 128 to have 256, etc.).

So asking for another sample with LHS (OLHS too), generates an independent sample. This is by design because we cannot (easily, not implemented) iterate a LHS.

Fast forward goal is to change the state of the random number generator. I case of a sequence, we skip some points, but for LHS based designs, we ask for LHS designs. The inner working is a bit different, but the logic the same. So here there is nothing to remove, but maybe the doc can be improved.

**Comment by tupui** [comment] 2021-03-05 20:40
Actually I checked and we don't change anything when fast forwarding LHS. Maybe we should call the sampling method, or change the seed to somehow have a state change.

Here it's really not clear about what would be the best to be honest. It doesn't matter for the next calls of the function.

I have no strong opinion so feel free to propose some change. But I would not delete the method as this would break the API.

**Comment by kstoneriv3** [comment] 2021-03-05 21:22
> Iterative sampling is tricky with QMC. It would only be safe with Halton (Sobol' is okay under certain conditions, basically doubling the number of samples. So if you had 64 ask for 64 to have 128. Then ask for 128 to have 256, etc.).

As far as I can see, the iterative sampling in the Sobol sequence works perfectly even if I do not increase the sample size by the power of 2... When I looked at the code of a python package `sobol_seq`, iterative sampling of the Sobol sequence seemed safe.  Are you 100% sure if the Sobol sequence can not always be sampled iteratively? If you can tell me some references on Sobol sequences, I can have check this point on my own...

**Comment by kstoneriv3** [comment] 2021-03-05 21:30
> Fast forward goal is to change the state of the random number generator. In case of a sequences, we can skip some points (hence move forward), but for LHS based designs, we ask internally for another LHS designs. The inner working is a bit different, but the logic the same. So here there is nothing to remove, but maybe the doc can be improved.
> 
> FYI, there is a tutorial coming up in #13487 where I try to explain these concepts a bit more.
>
> Actually I checked and we don't change anything when fast forwarding LHS. Maybe we should call the sampling method, or change the seed to somehow have a state change.

I see. I personally want to have these points documented so I might make a PR for documentaion.

**Comment by kstoneriv3** [comment] 2021-03-05 21:37
By the way, I think the current implementations of Latin hypercubes are mistakenly named... I read some articles on Latin hypercube to see if I can fix the original bug of this issue and noticed this.

Current  `OrthogonalLatinHypercube` is implementing standard Latin Hypercube and `LatinHypercube` does not seem to be any kind of Latin hypercube. Orthogonal Latin hypercube seems to have wide variations and looks very complicated to implement...

**Comment by kstoneriv3** [comment] 2021-03-05 21:46
I now feel the implementation of the Latin hypercube has a bug as well... I think it would be easier to discuss this over the code so I will create a PR.

**Comment by kstoneriv3** [comment] 2021-03-05 21:51
Sorry it was my mistake! 🙏 The naming seems wrong but the implementation is correct.

**Comment by tupui** [comment] 2021-03-05 21:57
> Thank you for the detailed answer! As far as I can see, the iterative sampling in the Sobol sequence works perfectly even if I do not increase the sample size by the power of 2... When I looked at the code of a python package `sobol_seq`, iterative sampling of the Sobol sequence seemed safe.  Are you 100% sure if the Sobol sequence can not always be sampled iteratively? If you can tell me some references on Sobol sequences, I can have check this point on my own...

The Sobol' sequence is a 2**n sequence. Which means its properties are only guaranteed if you respect some rules.

So you cannot do burning without care for instance. If you need 256 points. You must skip at least 256 points before. But the. You will not be able to resampling without losing the properties. For this you would need to skip 512 points to at most get 512 for instance.

In this implementation, you can see that we have some warnings at first if you try to do something you should not. But we did not want to clutter to much the API and found the current balance.

Most implementation (if not all), do not warn about this and have other flaws like the missing first point. We had lengthy discussions on the original PR (with some of best specialists) and had some emails about all these. We showed that the convergence rate is greatly affected if you just remove one point from the sequence...

So yes, you will be able to use the methods like you want, in any order. We tried to put enough warnings around to explain that it will be wrong to do so.

You can check out Art's paper which came out of these discussions: https://arxiv.org/abs/2008.08051

**Comment by tupui** [comment] 2021-03-05 22:01
> Sorry it was my mistake! 🙏 The naming seems wrong but the implementation is correct.

Mmm I am pretty sure there is no naming mistake here. Can you elaborate? You can also look at the tests to see how LHS and OLHS are verified.

**Comment by kstoneriv3** [comment] 2021-03-05 22:10
> The Sobol' sequence is a 2**n sequence. Which means its properties are only guaranteed if you respect some rules.
> ...

Thank you for detailed clarifications again! 
I know importing the QMC sampler to a hyperparameter optimization tool of machine learning models. There, being able to query parameter configurations iteratively comes in handy, so I wanted to sample a point after another there. As you said, it makes more sense to use 2^k parameter configurations but sometimes it is not easy (for example, it might be hard to estimate the runtime of training each model...). At least, I will make sure to document these properties of QMC sequences.

**Comment by kstoneriv3** [comment] 2021-03-05 22:21
> Mmm I am pretty sure there is no naming mistake here. Can you elaborate? You can also look at the tests to see how LHS and OLHS are verified.

In this article, section 1.3, page 9, the algorithm for standard (non-orthogonal) Latin hypercube is described. 
https://statweb.stanford.edu/~owen/courses/362-1011/readings/siggraph03.pdf
This is what I can find in the current `OrthogonalLatinHypercube`. 

When I google "orthogonal" Latin hypercube, I can find a lot of papers. They essentially try to more smartly the random permutations of Latin hypercube in each dimension so that the orthogonality of resulting samples will be high (there seems be several measures of orthogonality here).

**Comment by tupui** [comment] 2021-03-06 13:47
Feel free to open a PR to improve the documentation. I would be happy to review it. There are some notes about the points I just explained, but maybe we can improve.

The base LHS (as described both in Art's article and the original paper) does not say that the grid has to be of equal size. This is why the algorithmic could be difficult to get here. But if you look at other papers implementing it, they use the same technique. I believe I put the reference article for the orthogonal version in the documentation. I will check and give more ref if needed. But the only difference is that here the grid is of constant size.

**Comment by kstoneriv3** [comment] 2021-03-06 16:19
I do not think the difference between orthogonal Latin hypercube and Latin hypercube is that the former uses constant grid size. 

In the following paper, which you mentioned in the document of `OrthogoanalLatinHypercube`, you can find that the algorithm of the standard Latin hypercube uses constant grid size. It is described in equation (2.1). The algorithm for orthogonal Latin hypercube is described in section 3.
Owen, A. B. (1992). Orthogonal arrays for computer experiments, integration, and visualization. Statistica Sinica, 439-452.

If you are not convinced, can you tell me from which paper you took the algorithm for `LatinHypercube`? For me the algorithm does not seem to provide a sequence of high uniformity.

**Comment by tupui** [comment] 2021-03-06 19:48
This reference is good and if you indeed look at the equation 2.1, this is exactly what is done for `LatinHypercube`. 

```python
# this is Uij
r = self.rg_sample((n, self.d))

# this is the random permutations of integer pi
q = self.rg_integers(low=1, high=n, size=(n, self.d))

self.num_generated += n
return 1. / n * (q - r)
```

Also, here is a link to an issue where we discussed about this implementation for statsmodels (it was ment to go there initially): https://github.com/statsmodels/statsmodels/pull/4113#issuecomment-353796051

And here are some figures showing the difference between the 2. Orthogonal LHS does enforce a grid. I have to dig up more to remember what I did exactly for OLHS. But all this looks really fine to me...

LHS:
<img width="558" alt="Screenshot 2021-03-06 at 20 37 23" src="https://user-images.githubusercontent.com/23188539/110218982-d7898f00-7ebc-11eb-938f-1adfce509615.png">

Orthogonal LHS:
<img width="566" alt="Screenshot 2021-03-06 at 20 37 50" src="https://user-images.githubusercontent.com/23188539/110218983-d9ebe900-7ebc-11eb-9079-f227e3ff4c6b.png">

**Comment by kstoneriv3** [comment] 2021-03-06 20:16
Thank you for the clarification with the code!

I think the line below produces independently random integers and **not** the random permutation.
> ```python3
> # this is the random permutations of integer pi
> q = self.rg_integers(low=1, high=n, size=(n, self.d))
> ```
Thus, the current `LatinHypercube` produces random samples, not the samples from the Latin hypercube.

If the above line was properly fixed, it will be a proper Latin hypercube implementation. And if you do so, the algorithm for `LatinHypercube` and current `OrthogonalLatinHypercube` becomes identical.

**Comment by tupui** [comment] 2021-03-06 20:27
It is the same. Taking random permutations of a list of integers or random integers produce the same outcome.

**Comment by kstoneriv3** [comment] 2021-03-06 20:34
> It is the same. Taking random permutations of a list of integers or random integers produce the same outcome.

I am quite sure Latin hypercube sampling must be constructed from a permutation of [1, ..., n] when we want n samples. The current implementation just returns iid random samples.

> To convince yourself, there is currently another implementation of LHS in the differential evolution algorithm to initialize the population. It's the same algorithm.

Could you provide a pointer to the implementation? I want to check it.

**Comment by tupui** [comment] 2021-03-06 20:35
@ArtOwen, if you have time can you help here? Maybe we missed something.

**Comment by tupui** [comment] 2021-03-06 20:40
> I am quite sure Latin hypercube sampling must be constructed from a permutation of [1, ..., n] when we want n samples. The current implementation just returns iid random samples.

Yes but what is the difference if you take a list from [1,..., n] and permute it vs directly a list of random integers?

> Could you provide a pointer to the implementation? I want to check it.

It's in scipy.optimize._differential_evolution

**Comment by kstoneriv3** [comment] 2021-03-06 20:41
Each integer must appear only once in each dimension of the sample so we use permutation.

**Comment by tupui** [comment] 2021-03-06 20:48
Mmmm the random permutation are independent. But I might be wrong indeed. It's good if you found a bug here, but then it means we have an issue with our tests. I will look more.

**Comment by kstoneriv3** [comment] 2021-03-06 20:59
> Then maybe we should have used `rng.permutation` instead.
Yes, that's my point. Then, the current `OrthogonalLatinHypercube` and `LatinHypercube` become identical.

If I am correct about this, you just have to remove the old `LatinHypercube` and change the name of the `OrthogonalLatinHypercube` to `LatinHypercube`. So I assume there is no new code required.

If you want to support the Latin hypercube using an orthogonal array, we have to make a routine for creating an orthogonal array but I am not sure how much effort is needed to make such a routine. So I guess, we may just not support `OrthogonalLatinHypercube` for now.

**Comment by tupui** [comment] 2021-03-06 21:03
I am really confused now 😅. It was quite some time ago, and I really thought I had the orthogonal version correct. I have to check. In any case, thanks for raising this!

**Comment by kstoneriv3** [comment] 2021-03-06 21:06
@takashigoda
He is a professor I learned from, who has written many papers on QMC. I think he is happy to help with this.

**Comment by tupui** [comment] 2021-03-06 21:08
> @takashigoda
> He is a professor I learned from, who has written many papers on QMC. I think he is happy to help with this.

Thank you, I notified Art Owen as well (above). Let see if they can help to sort this out.

**Comment by tupui** [comment] 2021-03-06 21:22
But in the meantime, feel free to submit a PR at least about the first point and I guess you're also correct about the permutations. Let me know if you need any support. Thanks again!

**Comment by kstoneriv3** [comment] 2021-03-06 21:32
OK, I will work on it!

**Comment by tupui** [comment] 2021-03-06 21:41
I propose this:
```python
perms = [np.random.permutation(range(n)) for _ in range(self.d)]
q = np.stack(perms).T
```

**Comment by kstoneriv3** [comment] 2021-03-07 01:09
> ```python
> perms = [np.random.permutation(range(1, n + 1)) for _ in range(self.d)]
> q = np.stack(perms).T
> ```

Yes, this is what I expect from Latin hypercube.

> But I think the Orthogonal version is correct. It produces better results all the time. It really ensures one point per subspace as expected whereas here it's not the case.

 If you look at the code of the current `OrthogonalLatinHypercube` you will see that it is exactly the same algorithm.

**Comment by tupui** [comment] 2021-03-07 19:33
I got the confirmation about the LHS. So we can move forward with it! Thanks for noticing this bug! This is fairly urgent then I would say. If you don't have time, let me know so that I quickly do this.

For Orthogonal LHS, the current code is really doing something different as you can see from the output. Also here is the message I got from Art Owen:

> For the randomized orthogonal arrays, you need code to generate the underlying OA.  I very much like the Bose construction that I describe in my book.  For n = s^2 rows you can have up to s+1 columns (variables).  An OA is usually on symbols 0,1,...,s-1 so after permuting the columns you have to add 1/2 or add a uniform variable instead of subtracting.  Then you divide by s.
>
> There are a great many OAs to choose from.
>
> If you're adding a uniform variable then you might as well use the Tang method because it gives an LHS from which you get better one dimensional marginal distributions.  The centered version is nice if you want to have s points with x_1j ... x_nj equal to (k+1/2)/s. This might be nice for plotting.

I have to check closely, but the Tang method is what I wanted to have here.

**Comment by tupui** [comment] 2021-03-07 19:47
I believe the orthogonal version is correct from this description.

**Comment by kstoneriv3** [comment] 2021-03-07 23:02
No, I do not think so. From your quote, I can see that you need an orthogonal array (OA), which is not implemented in the current `OrthogonalLatinHypercube`, to support orthogonal Latin hypercube sampling (of strength >1).

**Comment by ArtOwen** [comment] 2021-03-07 23:53
Hi everybody,  I got some emails from tupui about this.  

-Art

For LHS you want each variable (each column of the resulting matrix) to have one value in the range [j/n,(j+1)/n) for all 0 <= j < n.  You can permute integers 0 to n-1 into a random order and add a U(0,1) to each of them.  Do that d times independently to get d columns and then divide the whole thing by n.  [Many texts permute 1 to n and then subtract U(0,1). Same distribution.]

Some users will want `centered' LHS that you can get by adding 0.5 instead of U(0,1).

Orthogonal LHS could mean different things to different people.  The ones by Tang are good.   It makes a big difference what OAs you use.  It makes the most sense to use OAs of strength 2.  Then you balance single and double marginal distributions.  I like the ones that have n=s^2 where s is a prime number (or any prime power if you have an implementation of Galois fields) and d <= s+1 that I call the Bose construction in my papers.  The OA book by Hedayat, Sloane and Stufken calls them something else.  There are also arrays with n = 2s^2 for d <= 2s+1, once again with s a prime or prime power.  (Warning: the modular arithmetic formulas are quite incorrect if s is not a prime.)

Using an OA of strength t=2, the Tang LHS balances first and second order margins nicely.  A scrambled QMC rule will often have better balance because the OA only balances square subregions while the QMC balances many rectangular shapes in two dimensional margins and usually also balances some higher dimensional regions.

I have a paper where I generate LHS with very small correlations among columns that could also be called orthogonal LHS.   Owen AB. Controlling correlations in Latin hypercube samples. Journal of the American Statistical Association. 1994 Dec 1;89(428):1517-22.  Those along with optimized LHS are good for exploring a function.  I'm not aware of studies on how they work for estimating integrals; they might have a subtle bias. 

Randomizing an OA and embedding it in the unit cube [0,1]^d is also useful as inputs for visualizing a function. If you do the version adding 1/2 instead of U(0,1) then you get regular grids of points in low dimensional views.  Owen AB. Orthogonal arrays for computer experiments, integration and visualization. Statistica Sinica. 1992 Jul 1:439-52.

Something that I think would be very cool for computational purposes is an implementation of randomized Hadamard matrices.  Those are n x n binary arrays.  The first column is all 1s, so discard that.  Now you have n-1 mutually orthogonal binary columns each is half 1s and half -1s.  The value of n can be almost any multiple of 4 that you like.  The first Paley construction in the Hedayat et al book is available for lots of values of n, and it can be computed for n in the millions or billions because you only need to store O(n) binary variables at a time while delivering n rows of n-1 values.  I.e., it can be flow through.  You can even access any row you like without computing prior ones.  A common strategy for fitting sparse models on n-1 variables is to take a random sample of m rows of the Hadamard matrix.  So ... Hadamard OAs are among the most important ones.

**Comment by ArtOwen** [comment] 2021-03-08 00:11
It would be useful to allow LHS with n=1.  It would also be useful to allow n=0 or even d=0.  

For instance, suppose you want to paste d LHS columns after s randomized QMC columns in a hybrid point set.  Some calling function might decide to choose d=0 at run time.  For instance they might want to run a simulation through d time steps for multiple values of d after initializing a system based on s variables.

**Comment by tupui** [comment] 2021-03-08 08:23
Thank you @ArtOwen for the explanations.

@kstoneriv3 I propose the following, we fix `LatinHypercube` and for `OrthogonalLatinHypercube` there are 2 options:

1. remove all references to `OrthogonalLatinHypercube` for now. I would not use this to replace `LatinHypercube` as the code is slower and slightly less readable and comparable to the literature than what I proposed above.
2. fix it by implementing some Orthogonal Arrays. (I would only do this if we are sure... Seemingly I am not 😅)

**Comment by kstoneriv3** [comment] 2021-03-08 08:34
I would go for option 1 as it's also hard for me to fully understand the algorithm for constructing OAs at the moment. 
Could you take a look at #13654 then? Its implementation is efficient but the readability is not quite high, I guess.

In addition, I would like to allow n=0 or even d=0 in LHS, as discussed above.

**Comment by mdhaber** [comment] 2021-03-20 23:33
@tupui @kstoneriv3 I believe this was closed by gh-13654. Please re-open if I missed something.

**Closed** 2021-03-20 23:33 UTC
Labels: defect, scipy.stats
