### ISSUE TITLE
Extending the elliptic integral functions to support complex arguments

### ISSUE THREAD

**Issue by s1291** [scipy/scipy#11220] opened 2019-12-14 13:52 UTC
**Is your feature request related to a problem? Please describe.**

Currently the incomplete elliptic integrals function in scipy.special do not support complex arguments for `phi`

**Describe the solution you'd like**
This could easily solved using the Landen Transformation. Let's take as example, the incomplete elliptic integral of the first kind `ellipkinc`

We could approximate the function as follows (note that it is expressed in terms of the parameter k instead of m where m=k²):

![k_and_phi](https://user-images.githubusercontent.com/17838489/70849434-8851db80-1e7e-11ea-9465-d360f6cd4f60.png)
![expression](https://user-images.githubusercontent.com/17838489/70849445-bcc59780-1e7e-11ea-8b31-0b103d652d21.png)

from the second expression above,, we could express `phi` at `n+1` as follows:
![phin1](https://user-images.githubusercontent.com/17838489/70849510-a835cf00-1e7f-11ea-89fd-b7db105e1e16.png)

The advantage of this last expression over using something like `scipy.optimize.fsolve` is that it could accept complex numbers.

The implementation is easy. 

For different complex arguments for `phi` the results match exactly with results in WolframAlpha 

**Reference**
>R.E. Deakin & M.N. Hunter Elliptic Integrals And Landen's Transformation: What I should've known  for Geodesy. [Link](http://www.mygeodesy.id.au/documents/Elliptic%20Integrals%20and%20Landen%27s%20Transformation.pdf)

**Comment by person142** [comment] 2020-01-18 06:47
This is a duplicate of https://github.com/scipy/scipy/issues/3979, so closing.

**Closed by person142** 2020-01-18 06:47 UTC
Labels: enhancement, scipy.special
