### ISSUE TITLE
BUG: scipy cython RegularGridInterpolator type error

### ISSUE THREAD

**Issue by kjurka** [scipy/scipy#17723] opened 2023-01-04 23:30 UTC
### Describe your issue.

Starting with scipy 1.10.0 I'm having trouble interpolating with 32bit values.  The below code crashes and previously worked with scipy 1.9.1.  It looks related to this PR https://github.com/scipy/scipy/pull/17291

### Reproducing Code Example

```python
import numpy as np
import scipy

ys = np.linspace(0, 10, 100).astype(np.float64)
xs = np.linspace(0, 10, 100).astype(np.float64)

vals = np.arange(100 * 100).reshape((100, 100)).astype(np.float32)

interp = scipy.interpolate.RegularGridInterpolator((ys, xs), vals, method='linear')

print(interp((5.1, 6.2)))
```

### Error message

```shell
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    print(interp((5.1, 6.2)))
  File "/home/docker_user/a3/lib/python3.8/site-packages/scipy/interpolate/_rgi.py", line 336, in __call__
    result = evaluate_linear_2d(self.values,
  File "_rgi_cython.pyx", line 19, in scipy.interpolate._rgi_cython.__pyx_fused_cpdef
TypeError: No matching signature found
```

### SciPy/NumPy/Python version information

1.10.0 1.21.6 sys.version_info(major=3, minor=8, micro=15, releaselevel='final', serial=0)

**Comment by tupui** [comment] 2023-01-05 00:56
Hi @kjurka thank you for reporting. This is a duplicate of #17718 hence closing this one.

**Closed** 2023-01-05 00:56 UTC
Labels: defect
