### ISSUE TITLE
vtk incompatibility with scipy.interpolate (and mvpoly.rbf)

### ISSUE THREAD

**Issue by guillermo-jimenez** [scipy/scipy#7203] opened 2017-03-20 15:15 UTC
Hi all,

When using this library with VTK this problem arises. Imagine I was to use the scipy.interpolate module or the mvpoly.rbf and the vtk library in the same project. When opening the python interpreter:

```
foo@bar:~$ python
>>> import scipy.interpolate
>>> import vtk
>>>
```

Works great. But, when importing the opposite way:

```
foo@bar:~$ python
>>> import vtk
>>> import scipy.interpolate
QH6248 qh_lib_check: Incorrect qhull library called.  Caller uses reentrant Qhull while library is non-reentrant
QH6249 qh_lib_check: Incorrect qhull library called.  Size of qhT for caller is 8184, but for library is 2896.
QH6255 qh_lib_check: Cannot continue.  Library 'qhull 7.2.0 (2015.2 2016/01/18)' uses a dynamic qhT via qh_QHpointer (e.g., qhull_p.so)
```

It also happens when importing another library, mvpoly, on its module rbf. The exact same error.

Issue also posted in the [vtk issue tracker](https://gitlab.kitware.com/vtk/vtk/issues/17004).

Thanks!

**Comment by rgommers** [comment] 2017-03-23 10:05
Could you give some more details:
- How did you install SciPy?
- What OS, and what compilers (if installed from source)?
- Do you know if this issue is new after upgrading one of the libraries involved or not?

``mvpoly.rbf`` is irrelevant right? It just imports ``scipy.interpolate``, but doesn't do anything with QHull itself.

**Comment by pv** [comment] 2017-03-23 10:09
import vtk+scipy works fine for me on Ubuntu, so probably it's some 
problem with incorrectly done build.

**Comment by guillermo-jimenez** [comment] 2017-03-28 09:18
Hi, @rgommers, @pv. Sorry for the delay in my response.

Indeed, as you said, installing python-vtk and python-scipy in a dockerized ubuntu and importing vtk+scipy.interpolate in the dockerized system did not produce any errors, so the problem must be in my specific machine. I mark this issue as closed.

As @rgommers suggests, I'll add some of my system's data for the sake of completion:
* **OS**: Ubuntu Mate 16.10
* **SciPy installation method**: `sudo apt install python-scipy`
* **VTK installation method**: I think it was `sudo apt install python-vtk6`, but I honestly don't remember
* **Upgrading**: not the problem, as far as I know. Probably something went wrong after installing some other libraries via pip install.
* **mvpoly.rbf**: yes, it was a typo. It it corrected now in the OP.

Thanks!

**Comment by rgommers** [comment] 2017-03-28 09:27
thanks @guillermo-jimenez

**Comment by thomaskeck** [comment] 2018-04-03 12:05
Just for documentation purposes:
I did encounter this bug as well in combination with matplotlib and ROOT. I do not have VTK installed.
So it is probably caused by scipy.

```
>>> import matplotlib.pyplot as plt
>>> from ROOT import Belle2
>>> from scipy import stats
QH6248 qh_lib_check: Incorrect qhull library called.  Caller uses reentrant Qhull while library is non-reentrant
QH6249 qh_lib_check: Incorrect qhull library called.  Size of qhT for caller is 8184, but for library is 2896.
QH6256 qh_lib_check: Cannot continue.  Library 'qhull 7.2.0 (2015.2 2016/01/18)' uses a static qhT (e.g., libqhull.so)
```

I was able to reproduce this on several machines with a custom build python 3.6.2 installation on Ubuntu 16.04.4 LTS.

Changing the order of the imports solved the problem, but there is clearly something wrong.

**Comment by rgommers** [comment] 2023-01-03 22:39
We just got another bug report for this, and it seems we should have reopened this issue after the last comment. There is an actual issue here: https://mail.python.org/archives/list/scipy-dev@python.org/thread/I535LGRTWUXJIP2VM7VQGF3HELHQJ4B2/

**Comment by rgommers** [comment] 2024-05-03 07:48
The mailing list thread linked above is quite detailed. I am pretty sure that this has been resolved after the move to Meson and the efforts to remove all exported symbols. `_qhull.so` now only exports a single symbol, `_PyInit__qhull`. So I'll close this.

**Closed by rgommers** 2024-05-03 07:48 UTC
Labels: defect, scipy.spatial
