### ISSUE TITLE
ENH: Add Legendre elliptic integral Pi

### ISSUE THREAD

**Issue by duetosymmetry** [scipy/scipy#15151] opened 2021-12-03 16:24 UTC
### Describe the solution you'd like.

The Cephes library is missing the Legendre Pi elliptic integral.
As of 1.8.0, `scipy.special` will contain the Carlson symmetric elliptic integrals (R_{C,D,F,G,J}). Pi [can be implemented in terms of R_J](https://dlmf.nist.gov/19.25) and one or two other integrals, depending on where the arguments are in the complex plane.

An elliptic Pi function only needs to be implemented in python, not C(++) -- it will just dispatch to the appropriate combination of Carlson functions.

One needs to study the reality conditions and efficiency of evaluating for different combinations of inputs to ensure an efficient implementation.

**Comment by person142** [comment] 2021-12-04 23:36
Note that generally you will want to implement it in (your favorite of) C/C++/Cython/Fortran _anyway_ so that it will be a ufunc.

**Comment by mdhaber** [comment] 2024-08-31 15:33
Closing as duplicate of gh-4452, which has more information.

**Closed by mdhaber** 2024-08-31 15:33 UTC
Labels: enhancement, scipy.special
