### ISSUE TITLE
Nelder-mead algorithm yields: TypeError: '>' not supported between instances of 'float' and 'NoneType'

### ISSUE THREAD

**Issue by arbolis** [scipy/scipy#8917] opened 2018-06-09 13:24 UTC
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I have an extremely complex code (I run FEniCS) to which I apply a minimization process using the nelder-mead algorithm provided by scipy.

I use the command 
```
results = minimize(some_func, initial_guesses=(the_variable), method='nelder
     -mead', options={'fatol':4e3, 'xatol':4e3})
```
After some minutes the code returns the following error message:

### Error message:
```
Traceback (most recent call last):
  File "enormously_complex_code.py", line 2030, in <module>
    results = minimize(some_func, initial_guesses=(the_variable), method='nelder
     -mead', options={'fatol':4e3, 'xatol':4e3})
  File "/usr/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 591, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/usr/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 571, in _minimize_neldermead
    if fxr < fsim[0]:
TypeError: '>' not supported between instances of 'float' and 'NoneType'

```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)

```

**Comment by ev-br** [comment] 2018-06-11 22:21
Traceback seems to point to the line `if fxr < fsim[0]`. Quickly looking at the code, both variables `fxr` and `fsim` seem to be results of some evaluations of the user-provided function, https://github.com/scipy/scipy/blob/master/scipy/optimize/optimize.py#L552 and https://github.com/scipy/scipy/blob/master/scipy/optimize/optimize.py#L568

This way, it's likely that the issue is caused by your `some_func` returning `None` in some cases. Do you have a standalone reproducer? Since it's a pure python code, the easiest way to debug the issue seems to be to patch up your local scipy install (or even your function) with an `import pdb; pdb.set_trace()` and looking why and what generates `None`s.

**Comment by WarrenWeckesser** [comment] 2018-06-11 22:24
Apparently your objective function `some_func` is returning None.  Here's a simple example that produces the same error:

```
In [16]: minimize(lambda x: None, 3, method='nelder-mead')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-fbb11c9ee653> in <module>()
----> 1 minimize(lambda x: None, 3, method='nelder-mead')

~/miniconda36b/lib/python3.6/site-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    589                       callback=callback, **options)
    590     elif meth == 'nelder-mead':
--> 591         return _minimize_neldermead(fun, x0, args, callback, **options)
    592     elif meth == 'powell':
    593         return _minimize_powell(fun, x0, args, callback, **options)

~/miniconda36b/lib/python3.6/site-packages/scipy/optimize/optimize.py in _minimize_neldermead(func, x0, args, callback, maxiter, maxfev, disp, return_all, initial_simplex, xatol, fatol, adaptive, **unknown_options)
    569         doshrink = 0
    570 
--> 571         if fxr < fsim[0]:
    572             xe = (1 + rho * chi) * xbar - rho * chi * sim[-1]
    573             fxe = func(xe)

TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

Because this is apparently a problem with your code, I'm closing the issue.  If you think I'm mistaken, please comment, and we can reopen the issue if  necessary.

P.S. @ev-br got his comment in just as I was about to click "Close and comment"!

**Closed by WarrenWeckesser** 2018-06-11 22:24 UTC

**Comment by ev-br** [comment] 2018-06-11 22:28
> P.S. @ev-br got his comment in just as I was about to click "Close and comment"!

Huh, correlation does not mean causation, as they say :-).

**Comment by arbolis** [comment] 2018-06-17 12:44
What you explained seems to make sense, because when I try another minimization algorithm, such as BFGS, I get a similar error message. I have never seen my some_func function return a "None" though, but I guess I introduced some bugs that might have caused it to return None.
