### ISSUE TITLE
wishlist: special functions wrightw and unwindk

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#2851] opened 2013-09-11 01:59 UTC
The unwinding number `unwindk(z) = ceil((z.imag - pi) / (2 * pi))` and the [Wright Omega function](http://en.wikipedia.org/wiki/Wright_Omega_function) `wrightw(z) = lambertw(exp(z), unwindk(z))` are single-valued functions of complex numbers.  They're related to complex `exp`, `log`, [`arg`](http://en.wikipedia.org/wiki/Argument_%28complex_analysis%29) (which I think is `numpy.angle`), `lambertw`, [principal values](http://en.wikipedia.org/wiki/Principal_value), and branch cuts.  The unwinding number can be evaluated naively but the Wright Omega function implementation needs more care, which I have only seen in detail in TOMS which is not available to scipy for licensing reasons.

My particular interest is that these functions could be used as efficient and accurate building blocks for more complicated functions of complex matrices (or real matrices with complex eigenvalues) that let you unwind or rescale big things intelligently instead of losing precision by downstream cancellation.

**Comment by pierslawrence** [comment] 2015-05-08 08:43
If there is still interest in integrating the code for the evaluation of the Wright Omega function, I think under the copyright transfer agreement I should be able to provide a suitable license for the ACM TOMS implementation.

Please let me know.

Dr. Piers Lawrence

**Comment by argriffing** [comment] 2015-05-08 16:49
@pierslawrence Yes that would be great!  I'm not sure about the details or logistics of making licensing agreements; I think @rkern knows more about that stuff.  Also I can't promise that I'll have time to add the code into scipy myself.

**Comment by rkern** [comment] 2015-05-08 17:18
:+1: Thanks, @pierslawrence! Once you get your situation sorted with ACM, all we need is for you to license the code under the BSD license. A simple statement to that effect is sufficient. Here is SciPy's license text (you would become one of the "SciPy Developers" referred to in the text at this point):

https://github.com/scipy/scipy/blob/master/LICENSE.txt

If you wish to make a formal release of your code with the actual BSD license attached to it, you can find the right project-neutral wording here:

http://opensource.org/licenses/BSD-3-Clause

Just stick in the year and your name in the right places.

**Comment by pierslawrence** [comment] 2015-07-07 09:51
Great, @rkern seems that I should be able to provide either license for the code. I am a little far behind on the necessary steps needed to integrate the code into python. Back when I was working on this project, I guess that I generated an f2py interface for the function, but perhaps things have moved on since then. Could you tell me what is useful for getting the function into SciPy?

**Comment by pv** [comment] 2015-07-07 10:50
The way it's done for most of them nowadays is:

- Write a small C wrapper function with signature `npy_cdouble wrightw(npy_cdouble z) { ... call the fortran routine ... }` see e.g. https://github.com/scipy/scipy/blob/master/scipy/special/specfun_wrappers.c#L73
- Add the wrapper function to this list: https://github.com/scipy/scipy/blob/master/scipy/special/generate_ufuncs.py#L84
- Add any new C/Fortran source files to `setup.py` https://github.com/scipy/scipy/blob/master/scipy/special/setup.py#L74
- Add a corresponding entry for the documentation to `add_newdocs.py` https://github.com/scipy/scipy/blob/master/scipy/special/add_newdocs.py#L22
- Run `generate_ufuncs.py`

**Comment by argriffing** [comment] 2015-07-17 20:32
> an f2py interface

Or the C code at [TOMS](http://toms.acm.org/Volumes/V38.html) could be added if licensing is resolved.

**Comment by aringh** [comment] 2016-10-04 06:50
Hi everyone. I am interested in Wright's Omega function as well, and I found this discussion when I googled it. Just wanted to check: is there any progress? :)

**Comment by pv** [comment] 2016-10-04 08:30
All progress is reported on this page.

**Comment by pierslawrence** [comment] 2016-10-04 20:04
Hi there I have been carried away on some other projects in the last year. As the author of the ACM TOMS code, I would like to license to scipy it under the BSD 3 clause license.

**Comment by person142** [comment] 2016-10-04 20:38
I will just comment that if licensing issues are settled (I defer to others on how official a statement is needed to make it okay) I will gladly hook the source code up to the SciPy ufunc machinery, add tests, and write documentation.

**Comment by pv** [comment] 2016-10-04 20:44
04.10.2016, 22:04, Piers Lawrence wrote:
> Hi there I have been carried away on some other projects in the last
> year. As the author of the ACM TOMS code, I would like to license to
> scipy it under the BSD 3 clause license.
.
Thanks for sorting out the license situation for "ACM TOMS Algorithm
917: Complex Double-Precision Evaluation of the Wright ω Function".
.
Please check that the following license information is accurate:
https://github.com/pv/scipy-work/commit/cbb787c6e38d220be8f058844534d85b06ed0a96#diff-cabc1f779ef83e612b068cf48e87e446R20
.
As I understand, it's still ACM that owns the copyright since this was
published before 2013.

**Comment by pierslawrence** [comment] 2016-10-04 21:25
Dear pv,

Sorry about the delay, I can confirm the licence information is accurate.
I checked the copyright transfer and it was a non-exclusive license issued to the ACM for the code.

**Comment by pv** [comment] 2016-10-04 21:46
Hi, thanks for the clarification --- you're the copyright holder then.
Nice to see ACM has changed its policy to be a bit less of a hassle.
.
Now that the obligatory stuff is out of the way, I think there's nothing
blocking this from proceeding.

**Comment by person142** [comment] 2016-10-04 21:59
Great. I'll probably port to C++ unless @pv reckons it's worth reevaluating whether C99 compiler support is widespread enough?

**Comment by pv** [comment] 2016-10-04 22:11
My guess is that MSVC will never support C99 complex. I guess there are no other compilers don't that we would need to care about, so the decision would be about dropping MSVC.

**Comment by person142** [comment] 2016-10-04 22:19
Seems to me it's not worth dropping it over this; porting shouldn't be hard.

**Comment by pv** [comment] 2016-10-13 18:29
gh-6653 merged, thanks everyone!
I guess we could also copy the unwindk implementation from sparse.linalg to special.

**Comment by person142** [comment] 2019-07-13 03:20
Closing this-the Wright Omega function was implemented, and the unwinding number can be computed easily.

**Closed by person142** 2019-07-13 03:20 UTC
Labels: enhancement, prio-lowest, scipy.special

**Comment by pierslawrence** [comment] 2019-07-13 13:28
I would suggest that a specialized version of Wright Omega be used on the real axis. In comparison to the other Scipy special functions the current behavior might seem unusual. What are the best options for doing this?

**Comment by person142** [comment] 2019-07-13 16:16
You add the new implementation to the repo and then add a line here:

https://github.com/scipy/scipy/blob/master/scipy/special/functions.json#L1329

pointing to it... and that’s it!

You can see an example of us doing the same thing for `loggamma` here:

https://github.com/scipy/scipy/pull/7983
