### ISSUE TITLE
RK45 produces wrong result for specific setting

### ISSUE THREAD

**Issue by Wrzlprmft** [scipy/scipy#9899] opened 2019-03-04 16:36 UTC
The following code integrates and plots the same differential equation with the different integrators of Solve IVP as well as ODE’s DoPri5 for comparison:

``` Python3
from matplotlib import pyplot as plt
from math import cos
import numpy as np
from scipy.integrate import solve_ivp, ode

# Common Parameters
T = 300
y0 = [0.2]
f = lambda t,y: y**2*cos(t+y)

# Solve IVP
for method in ["RK23","RK45","Radau","BDF"]:
	sol = solve_ivp( fun=f, t_span=(0,T), y0=y0, method=method )
	plt.plot(sol.t,sol.y.T,label=method)

# ODE for comparison
ODE = ode(f)
ODE.set_initial_value(y0)
ODE.set_integrator("dopri5",rtol=1e-3,atol=1e-6)
times = np.arange(0.5,T,0.5)
sol = np.hstack([ODE.integrate(time) for time in times])
plt.plot(times,sol,label="dopri5")

# Plotting
plt.legend()
plt.show()
```

At least for me, the result of this looks as follows:

![plot produced by above script](https://user-images.githubusercontent.com/291070/53747435-8c8aaa80-3ea3-11e9-900a-d4476eef7f2c.png)

As you can see, all integrators produce roughly the same result, except RK45 which is way out of line. As RK45 and DoPri5 use the same algorithm, this should not be a pathology for this specific algorithm. This problem vanishes when I set `rtol=1e-5`.

### Version information
* SciPy: 1.2.1
* NumPy: 1.15.0
* Python: 3.6.7

**Comment by MatthewFlamm** [comment] 2019-03-05 14:32
The default `rtol` for `solve_ivp` is 1e-3, while you set ``rtol=1e-6`` for dopri5.  You say the problem vanishes when ``rtol=1e-5`` in `solve_ivp`, so this seems like the expected behavior to me.  Can you check whether you get similar behavior when you set ``rtol=1e-3`` in dopri5?

**Comment by Wrzlprmft** [comment] 2019-03-05 15:05
> The default `rtol` for `solve_ivp` is 1e-3, while you set `rtol=1e-6` for dopri5. You say the problem vanishes when `rtol=1e-5` in `solve_ivp`, so this seems like the expected behavior to me. Can you check whether you get similar behavior when you set `rtol=1e-3` in dopri5?

Damnit. I wanted set the error tolerances for `dopri5` explicitly to match those of Solve IVP, but I swapped `rtol` and `atol`. However, when you correct this (which I now did in the initial post), this doesn’t change the outcome, i.e, `dopri5` works fine at those tolerances.

By the way, the observed outcome for `RK45` is not what I would expect at due to a too lenient error tolerance (at least on this level).

> I suppose the higher level question would be, why do we have different default tolerances for each ODE integrator interface?

I have no big issue with this. For `ode` those tolerances aren’t even properly documented, and I would consider the defaults of Solve IVP to be more reasonable.

**Comment by MatthewFlamm** [comment] 2019-03-05 15:28
It looks like you didn't update the graph after this change, does it look exactly the same?  It probably looks pretty similar.

I'm not well versed in the ODE implementation but it looks like it is integrated over many small time chunks, while in `solve_ivp` it uses the solver chosen time steps until `t_bound`.  I'm assuming that you are taking smaller steps in dopri5 which results in an effectively better solution accuracy.  What happens if you set `max_step=0.5` in `solve_ivp`?

**Comment by Wrzlprmft** [comment] 2019-03-05 15:46
> It looks like you didn't update the graph after this change, does it look exactly the same? It probably looks pretty similar.

I did not bother updating, because at least I cannot spot a difference.

> I'm not well versed in the ODE implementation but it looks like it is integrated over many small time chunks, while in `solve_ivp` it uses the solver chosen time steps until `t_bound`. I'm assuming that you are taking smaller steps in dopri5 which results in an effectively better solution accuracy. What happens if you set `max_step=0.5` in `solve_ivp`?

Good call. Indeed, the way I call `ode` imposes an upper limit to the step size, and when I restrict the maximum step in `solve_ivp` accordingly, the problem is gone. Conversely, when I increase the step size for `dopri5`, it also produces bogus results:

![Result with larger steps for dopri5](https://user-images.githubusercontent.com/291070/53817548-f23f6b00-3f65-11e9-9e45-1c707d51b20b.png)

This still leaves the question why this happens – because it really shouldn’t.

### Updated Code

``` Python3

from matplotlib import pyplot as plt
from math import cos
import numpy as np
from scipy.integrate import solve_ivp, ode

# Common Parameters
T = 300
y0 = [0.2]
f = lambda t,y: y**2*cos(t+y)
dt = 5

# Solve IVP
for method in ["RK23","RK45","Radau","BDF"]:
	sol = solve_ivp( fun=f, t_span=(0,T), y0=y0, method=method, max_step=dt )
	plt.plot(sol.t,sol.y.T,label=method)

# ODE for comparison
ODE = ode(f)
ODE.set_initial_value(y0)
ODE.set_integrator("dopri5",atol=1e-3,rtol=1e-6)
times = np.arange(dt,T,dt)
sol = np.hstack([ODE.integrate(time) for time in times])
plt.plot(times,sol,label="dopri5")

# Plotting
plt.legend()
plt.savefig("bug.png")

```

**Comment by MatthewFlamm** [comment] 2019-03-05 15:51
To me, this confirms that the two solvers give equivalent results using like for like settings.  I see no problem here, for stiff problems you require either a stiff solver, tight tolerances, or step size control.

**Comment by Wrzlprmft** [comment] 2019-03-05 17:34
> I see no problem here, for stiff problems you require either a stiff solver, tight tolerances, or step size control.

Both, `RK45` and `dopri5` have step-size control. If this problem were just stiff, they should not finish or take very long. Also, the non-stiff solver `RK23` works just fine. Thus I expect that something else is going wrong here.

**Comment by nmayorov** [comment] 2019-03-05 22:26
I think it might be related to #9822. Of course it all is not trivial.

**Comment by zechenhund** [comment] 2020-04-03 14:27
As far as I can see, this issue is not yet resolved. 

I did an extended search in parameter space to try to understand the behavior of the different algorithms on this problem, and to get a hint at the probable problem cause. 

It now seems to me rather obvious that there is a problem with step size control in RK45. Major arguments: when setting atol = 10.0 * rtol (atol = 1.0 * rtol * |values|) the problem goes away. And when setting max_step = 0.1, there is no problem with the default values for atol, rtol either. 

Hence, I conclude: fully automatic step size selection does not work on this problem.    

However, having had a look at the code, the difference between RK23 (well behaved) and RK45 (going astray) couldn't possibly be due to a coding error, given the way the code is structured such that RK23 and RK45 both use the some kernel routine RK. Having suspected that there might be an error in the coefficients, I verified them by comparison with the original Dormand-Prince paper as well as with the FORTRAN code for dopri5 (which is their RK45 implementation).     
For more details see the graphs attached. 

Of course, in general, ODE solvers might behave erratically on specific problems, don't they? However, the (not necessarily naive) casual user might rightfully expect a more intricate solver like RK45 to give better and more reliable results than a simpler one like RK23.

I would therefore humbly suggest, one of the experts might have a look at the step size control of the RK solver kernel or else at the parameters of RK45. (Could the specific choice DP made in their paper lead to instabilities in step size control, which might be cured by another choice?)  

And while the discussion in [#9822.](https://github.com/scipy/scipy/issues/9822) is more extensive and makes some certainly worthwhile proposals, I do think the mishandling of step size control in RK45 should be fixed asap.   

![solver_comparison_ATOL=1 00E-03_RTOL=1 00E-06_dt=0 1](https://user-images.githubusercontent.com/63060305/78277770-52ac2d80-7515-11ea-86a5-a1e36d63dd89.png)
![solver_comparison_ATOL=1 00E-03_RTOL=1 00E-06_dt=1 0](https://user-images.githubusercontent.com/63060305/78277793-593aa500-7515-11ea-985e-bf9cfd87a9f4.png)
![solver_comparison_ATOL=1 00E-03_RTOL=1 00E-06_dt=2 0](https://user-images.githubusercontent.com/63060305/78277797-5cce2c00-7515-11ea-85b3-17fd35ce96ec.png)
![solver_comparison_ATOL=1 00E-03_RTOL=1 00E-06_dt=5 0](https://user-images.githubusercontent.com/63060305/78277808-6192e000-7515-11ea-90db-5dea51b74f9c.png)
![solver_comparison_ATOL=1 00E-03_RTOL=1 00E-06_dt=10](https://user-images.githubusercontent.com/63060305/78277817-648dd080-7515-11ea-999c-e9db8e710241.png)
![solver_comparison_ATOL=1 00E-03_RTOL=1 00E-06_dt=auto (dopri5: 0 1)](https://user-images.githubusercontent.com/63060305/78277879-7e2f1800-7515-11ea-9c6d-6b3dfb924658.png)
![solver_comparison_ATOL=1 00E-04_RTOL=1 00E-06_dt=auto (dopri5: 1 0)](https://user-images.githubusercontent.com/63060305/78277884-7ff8db80-7515-11ea-83c8-455ece278fb1.png)
![solver_comparison_ATOL=1 00E-05_RTOL=1 00E-06_dt=auto (dopri5: 1 0)](https://user-images.githubusercontent.com/63060305/78277889-825b3580-7515-11ea-9559-dbd3d10217ef.png)
![solver_comparison_ATOL=1 00E-06_RTOL=1 00E-06_dt=auto (dopri5: 1 0)](https://user-images.githubusercontent.com/63060305/78277893-84bd8f80-7515-11ea-9a8a-27a56c1dfecc.png)
![solver_comparison_ATOL=1 00E-07_RTOL=1 00E-06_dt=auto (dopri5: 1 0)](https://user-images.githubusercontent.com/63060305/78277905-871fe980-7515-11ea-9bdf-ff6ca4af6198.png)
![solver_comparison_ATOL=1 00E-08_RTOL=1 00E-06_dt=auto (dopri5: 1 0)](https://user-images.githubusercontent.com/63060305/78277916-8ab37080-7515-11ea-9fa6-92d4b1230331.png)

Version info: 
sys.version: 3.6.5 (default, Apr 27 2018, 23:34:23) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
numpy.version: 1.18.2
scipy.version: 1.4.1

**Comment by laurent90git** [comment] 2021-02-28 17:33
#13619

**Comment by mdhaber** [comment] 2022-04-16 19:45
The conclusion here seems to be that RK45 automatic step size selection is not perfect. It's been about two years since the last post, so I don't think the step size of RK45 is going to be fixed ASAP, especially since it sounds like a pretty thorough review of the code was unable to find a problem, and what is being asked for is research to improve the suggestions of the Dormand-Prince paper. I'd suggest that we focus the effort on improving step size selection rather than trying to hunt down an elusive bug that might not really be a bug. With appropriate tolerance settings, RK45 does fine on this problem, so I think it's safe to close and wait for progress on gh-9822. Thanks for reporting, @Wrzlprmft, and please reopen if you disagree!

**Closed by mdhaber** 2022-04-16 19:45 UTC
Labels: defect, scipy.integrate
