### ISSUE TITLE
Scipy installation error when importing sklearn.preprocessing

### ISSUE THREAD

**Issue by rizvian** [scipy/scipy#12122] opened 2020-05-15 09:49 UTC
Reference: https://github.com/scikit-learn/scikit-learn/issues/17174 

Hello,
I am getting and error when importing sklearn.preprocessing. In the above referenced issue, it was found out to be a scipy installation issue. Please help in resolving. Thanks 

Python version: Python 3.5.1rc1

The notebook that I am working on is running from a virtual environment.

Here are the installed packages in that environment. [pip_list.txt](https://github.com/scipy/scipy/files/4633580/pip_list.txt)

Error Details:

from scipy.sparse import issparse
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-570e7ed10a94> in <module>
      3 from matplotlib import pyplot
      4 
----> 5 from scipy.sparse import issparse

c:\users\local_user\appdata\local\programs\python\python35\notebook\lib\site-packages\scipy\__init__.py in <module>
    154     # This makes "from scipy import fft" return scipy.fft, not np.fft
    155     del fft
--> 156     from . import fft

c:\users\local_user\appdata\local\programs\python\python35\notebook\lib\site-packages\scipy\fft\__init__.py in <module>
     74 from __future__ import division, print_function, absolute_import
     75 
---> 76 from ._basic import (
     77     fft, ifft, fft2, ifft2, fftn, ifftn,
     78     rfft, irfft, rfft2, irfft2, rfftn, irfftn,

c:\users\local_user\appdata\local\programs\python\python35\notebook\lib\site-packages\scipy\fft\_basic.py in <module>
----> 1 from scipy._lib.uarray import generate_multimethod, Dispatchable
      2 import numpy as np
      3 
      4 
      5 def _x_replacer(args, kwargs, dispatchables):

c:\users\local_user\appdata\local\programs\python\python35\notebook\lib\site-packages\scipy\_lib\uarray.py in <module>
     25     from uarray import _Function
     26 else:
---> 27     from ._uarray import *
     28     from ._uarray import _Function
     29 

c:\users\local_user\appdata\local\programs\python\python35\notebook\lib\site-packages\scipy\_lib\_uarray\__init__.py in <module>
    112 """
    113 
--> 114 from ._backend import *
    115 
    116 __version__ = '0.5.1+5.ga864a57.scipy'

c:\users\local_user\appdata\local\programs\python\python35\notebook\lib\site-packages\scipy\_lib\_uarray\_backend.py in <module>
----> 1 from typing import (
      2     Callable,
      3     Iterable,
      4     Dict,
      5     Tuple,

ImportError: cannot import name 'Type'

**Comment by pv** [comment] 2020-05-15 09:57
Duplicate of #11356

**Closed by pv** 2020-05-15 09:57 UTC
