### ISSUE TITLE
Problem with installing Scipy using PyPi on Windows

### ISSUE THREAD

**Issue by mklemarczyk** [scipy/scipy#7114] opened 2017-02-28 23:15 UTC
Problem with installing Scipy 0.18.1 using PyPi on Windows (Python 2.7.13)

Here is log:
``Collecting scipy
  Using cached scipy-0.18.1.tar.gz
Installing collected packages: scipy
  Running setup.py install for scipy: started
    Running setup.py install for scipy: finished with status 'error'
    Complete output from command D:\Web\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mklem\\appdata\\local\\temp\\pip-build-hocqsj\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\mklem\appdata\local\temp\pip-ceoa2h-record\install-record.txt --single-version-externally-managed --compile:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['D:\\Web\\Python27\\lib', 'C:\\', 'D:\\Web\\Python27\\libs']
      NOT AVAILABLE
    
    openblas_lapack_info:
      libraries openblas not found in ['D:\\Web\\Python27\\lib', 'C:\\', 'D:\\Web\\Python27\\libs']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    D:\Web\Python27\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.10.1-sse2-32\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    D:\Web\Python27\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['D:\\Web\\Python27\\lib', 'C:\\', 'D:\\Web\\Python27\\libs']
      NOT AVAILABLE
    
    D:\Web\Python27\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE
    
    D:\Web\Python27\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE
    
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mklem\appdata\local\temp\pip-build-hocqsj\scipy\setup.py", line 415, in <module>
        setup_package()
      File "c:\users\mklem\appdata\local\temp\pip-build-hocqsj\scipy\setup.py", line 411, in setup_package
        setup(**metadata)
      File "D:\Web\Python27\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "c:\users\mklem\appdata\local\temp\pip-build-hocqsj\scipy\setup.py", line 335, in configuration
        config.add_subpackage('scipy')
      File "D:\Web\Python27\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "D:\Web\Python27\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "D:\Web\Python27\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "D:\Web\Python27\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "D:\Web\Python27\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "D:\Web\Python27\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------

Command "D:\Web\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\mklem\\appdata\\local\\temp\\pip-build-hocqsj\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\mklem\appdata\local\temp\pip-ceoa2h-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\mklem\appdata\local\temp\pip-build-hocqsj\scipy\
``

**Comment by ev-br** [comment] 2017-02-28 23:26
Duplicate of https://github.com/scipy/scipy/issues/5461 (and several others). 

The short answer is that you cannot install SciPy with pip on Windows. Your best bet likely is Christoph Gohlke wheels or Anaconda.

**Closed by ev-br** 2017-02-28 23:26 UTC

**Comment by mklemarczyk** [comment] 2017-05-02 21:43
Why do you think you cannot? I think you are too lazy to make it work.

**Comment by e-q** [comment] 2017-05-02 22:05
I think you are too lazy to follow the link provided above. The issue is not lack of motivation, but licensing options of fortran compliers on windows. Before you cast aspersions on the developers, show some willingness to understand the issue yourself.

**Comment by KDharmindar** [comment] 2017-05-25 22:26
But we can always compile through the source code which should be more simple and easier through git

**Comment by mklemarczyk** [comment] 2017-10-22 22:30
@e-q Thank but I used something that works. If you can not solve that problem I wonder what will happen when harder problems appear.

**Comment by person142** [comment] 2017-10-22 22:36
This conversation appears to no longer be constructive, so locking it. Note that with the upcoming 1.0 release you will be able to install SciPy with pip on Windows.
