### ISSUE TITLE
missing code signatures on macOS 12.6/x86_64 but not macOS 12.6/arm64

### ISSUE THREAD

**Issue by khpeterson** [scipy/scipy#17343] opened 2022-11-04 17:56 UTC
For the same version of scipy on macOS (12.6), the .so files are missing code signatures in the x86_64 build but not in the arm64 build.

I saw mention of this in #16446 and that signing responsibility falls with the "installation tools", but I thought the difference was worth noting.

On macOS 12.6/arm64, as expected:
```
khp@Kevins-MacBook-Pro-M1 Temp % uname -m; sw_vers
arm64
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
khp@Kevins-MacBook-Pro-arm64 Temp % pip3 install --no-cache-dir -t . scipy                                                   
Collecting scipy
  Downloading scipy-1.9.3-cp39-cp39-macosx_12_0_arm64.whl (28.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.6/28.6 MB 16.2 MB/s eta 0:00:00
Collecting numpy<1.26.0,>=1.18.5
  Downloading numpy-1.23.4-cp39-cp39-macosx_11_0_arm64.whl (13.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 16.0 MB/s eta 0:00:00
Installing collected packages: numpy, scipy
Successfully installed numpy-1.23.4 scipy-1.9.3
khp@Kevins-MacBook-Pro-arm64 Temp % for so in `find . -name \*\.so -print`; do codesign -d $so 2>&1 | grep "not signed"; done
khp@Kevins-MacBook-Pro-arm64 Temp % 
```

On macOS 12.6/x86_64, most code signatures are missing:
```
khp@Kevins-Mac-mini-x86_64 Temp % uname -m; sw_vers
x86_64
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
khp@Kevins-Mac-mini-x86_64 Temp % pip3 install -t . --no-cache-dir scipy                                                   
Collecting scipy
  Downloading scipy-1.9.3-cp39-cp39-macosx_10_9_x86_64.whl (34.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.3/34.3 MB 19.6 MB/s eta 0:00:00
Collecting numpy<1.26.0,>=1.18.5
  Downloading numpy-1.23.4-cp39-cp39-macosx_10_9_x86_64.whl (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 20.0 MB/s eta 0:00:00
Installing collected packages: numpy, scipy
Successfully installed numpy-1.23.4 scipy-1.9.3
khp@Kevins-Mac-mini-x86_64 Temp % for so in `find . -name \*\.so -print`; do codesign -d $so 2>&1 | grep "not signed"; done
./numpy/core/_operand_flag_tests.cpython-39-darwin.so: code object is not signed at all
./numpy/core/_simd.cpython-39-darwin.so: code object is not signed at all
./numpy/core/_rational_tests.cpython-39-darwin.so: code object is not signed at all
./numpy/core/_umath_tests.cpython-39-darwin.so: code object is not signed at all
./numpy/core/_struct_ufunc_tests.cpython-39-darwin.so: code object is not signed at all
./numpy/core/_multiarray_tests.cpython-39-darwin.so: code object is not signed at all
./numpy/fft/_pocketfft_internal.cpython-39-darwin.so: code object is not signed at all
./numpy/random/bit_generator.cpython-39-darwin.so: code object is not signed at all
./numpy/random/mtrand.cpython-39-darwin.so: code object is not signed at all
./numpy/random/_generator.cpython-39-darwin.so: code object is not signed at all
./numpy/random/_pcg64.cpython-39-darwin.so: code object is not signed at all
./numpy/random/_sfc64.cpython-39-darwin.so: code object is not signed at all
./numpy/random/_mt19937.cpython-39-darwin.so: code object is not signed at all
./numpy/random/_philox.cpython-39-darwin.so: code object is not signed at all
./numpy/random/_bounded_integers.cpython-39-darwin.so: code object is not signed at all
./numpy/random/_common.cpython-39-darwin.so: code object is not signed at all
./scipy/cluster/_hierarchy.cpython-39-darwin.so: code object is not signed at all
./scipy/cluster/_optimal_leaf_ordering.cpython-39-darwin.so: code object is not signed at all
./scipy/cluster/_vq.cpython-39-darwin.so: code object is not signed at all
./scipy/ndimage/_ni_label.cpython-39-darwin.so: code object is not signed at all
./scipy/ndimage/_nd_image.cpython-39-darwin.so: code object is not signed at all
./scipy/ndimage/_ctest.cpython-39-darwin.so: code object is not signed at all
./scipy/ndimage/_cytest.cpython-39-darwin.so: code object is not signed at all
./scipy/linalg/_solve_toeplitz.cpython-39-darwin.so: code object is not signed at all
./scipy/linalg/_cythonized_array_utils.cpython-39-darwin.so: code object is not signed at all
./scipy/linalg/_matfuncs_sqrtm_triu.cpython-39-darwin.so: code object is not signed at all
./scipy/linalg/_decomp_update.cpython-39-darwin.so: code object is not signed at all
./scipy/linalg/_matfuncs_expm.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_lsap.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_zeros.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_moduleTNC.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_minpack2.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_bglu_dense.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_highs/_highs_constants.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_highs/_highs_wrapper.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_lsq/givens_elimination.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/cython_optimize/_zeros.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_minpack.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_group_columns.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_slsqp.cpython-39-darwin.so: code object is not signed at all
./scipy/optimize/_direct.cpython-39-darwin.so: code object is not signed at all
./scipy/integrate/_test_multivariate.cpython-39-darwin.so: code object is not signed at all
./scipy/io/matlab/_mio_utils.cpython-39-darwin.so: code object is not signed at all
./scipy/io/matlab/_mio5_utils.cpython-39-darwin.so: code object is not signed at all
./scipy/io/matlab/_streams.cpython-39-darwin.so: code object is not signed at all
./scipy/_lib/_uarray/_uarray.cpython-39-darwin.so: code object is not signed at all
./scipy/_lib/_test_ccallback.cpython-39-darwin.so: code object is not signed at all
./scipy/_lib/_ccallback_c.cpython-39-darwin.so: code object is not signed at all
./scipy/_lib/_test_deprecation_call.cpython-39-darwin.so: code object is not signed at all
./scipy/_lib/_fpumode.cpython-39-darwin.so: code object is not signed at all
./scipy/_lib/messagestream.cpython-39-darwin.so: code object is not signed at all
./scipy/_lib/_test_deprecation_def.cpython-39-darwin.so: code object is not signed at all
./scipy/special/_comb.cpython-39-darwin.so: code object is not signed at all
./scipy/special/_test_round.cpython-39-darwin.so: code object is not signed at all
./scipy/special/_ufuncs_cxx.cpython-39-darwin.so: code object is not signed at all
./scipy/fftpack/convolve.cpython-39-darwin.so: code object is not signed at all
./scipy/interpolate/_bspl.cpython-39-darwin.so: code object is not signed at all
./scipy/interpolate/_rbfinterp_pythran.cpython-39-darwin.so: code object is not signed at all
./scipy/interpolate/interpnd.cpython-39-darwin.so: code object is not signed at all
./scipy/interpolate/_ppoly.cpython-39-darwin.so: code object is not signed at all
./scipy/fft/_pocketfft/pypocketfft.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/_sparsetools.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/csgraph/_min_spanning_tree.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/csgraph/_traversal.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/csgraph/_tools.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/csgraph/_matching.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/csgraph/_reordering.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/csgraph/_flow.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/csgraph/_shortest_path.cpython-39-darwin.so: code object is not signed at all
./scipy/sparse/_csparsetools.cpython-39-darwin.so: code object is not signed at all
./scipy/spatial/_hausdorff.cpython-39-darwin.so: code object is not signed at all
./scipy/spatial/_ckdtree.cpython-39-darwin.so: code object is not signed at all
./scipy/spatial/_voronoi.cpython-39-darwin.so: code object is not signed at all
./scipy/spatial/_distance_pybind.cpython-39-darwin.so: code object is not signed at all
./scipy/spatial/transform/_rotation.cpython-39-darwin.so: code object is not signed at all
./scipy/spatial/_distance_wrap.cpython-39-darwin.so: code object is not signed at all
./scipy/signal/_spectral.cpython-39-darwin.so: code object is not signed at all
./scipy/signal/_sosfilt.cpython-39-darwin.so: code object is not signed at all
./scipy/signal/_peak_finding_utils.cpython-39-darwin.so: code object is not signed at all
./scipy/signal/_max_len_seq_inner.cpython-39-darwin.so: code object is not signed at all
./scipy/signal/_sigtools.cpython-39-darwin.so: code object is not signed at all
./scipy/signal/_upfirdn_apply.cpython-39-darwin.so: code object is not signed at all
./scipy/signal/_spline.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_levy_stable/levyst.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_qmc_cy.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_boost/hypergeom_ufunc.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_boost/binom_ufunc.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_boost/ncf_ufunc.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_boost/nbinom_ufunc.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_boost/beta_ufunc.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_sobol.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_biasedurn.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_statlib.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_unuran/unuran_wrapper.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_stats.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_mvn.cpython-39-darwin.so: code object is not signed at all
./scipy/stats/_hypotests_pythran.cpython-39-darwin.so: code object is not signed at all
khp@Kevins-Mac-mini-x86_64 Temp %   
```

**Comment by rgommers** [comment] 2022-11-05 10:15
@khpeterson thanks for the report. Are you actually experiencing a problem on x86-64 due to the lack of code signing, or is this more of a "I'd like to understand what is happening here"?

**Comment by andyfaff** [comment] 2022-11-05 10:54
Does the test suite pass? `python -c "import scipy; scipy.test()"`?

**Comment by khpeterson** [comment] 2022-11-05 16:02
@rgommers no hard issue for me, just thought the discrepancy was worth noting in case it's unexpected.

**Comment by khpeterson** [comment] 2022-11-05 16:36
@andyfaff The test suite finishes on arm64:
```
=================================== 37188 passed, 3336 skipped, 12061 deselected, 138 xfailed, 11 xpassed, 326 warnings in 416.61s (0:06:56) ===================================
```
And FYIY/not related to code signatures, on x86_64 pytest dies with "OSError: [Errno 24] Too many open files" after Fs in scipy/stats/tests/test_sampling.  Everything else finishes OK and when I rerun 'scipy.test(tests=['scipy/stats/tests'])' it finishes OK too.

**Comment by rgommers** [comment] 2022-11-05 18:09
> And FWIW/not related to code signatures, on x86_64 pytest dies with "OSError: [Errno 24] Too many open files" after Fs in scipy/stats/tests/test_sampling. Everything else finishes OK and when I rerun 'scipy.test(tests=['scipy/stats/tests'])' it finishes OK too.

That is bad. Probably a relatively new issue. Is it reproducible? And what do you mean by "after Fs"?

**Comment by khpeterson** [comment] 2022-11-05 18:40
Yes, seems reproducible, though I've only tried twice.  By "after Fs" I meant, the first hard failure cases reported by pytest:
```
scipy/stats/tests/test_sampling.py .......................................................................................................................................FFFF [ 97%]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.....F.....FFFFFFF.FFFFssFFFssssssssssFFsFF.....F.FF..........F.FFFFssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 97%]
ssssssssssssssssssssssssssssssssssssssFFFFFFFFFF..FFFFFFFFFFFFFFF.........FFFFFFFFF..sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 98%]
sssssssssssssssssssss.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFssFFFssssssssssFFsFFFFFFFFF..........FFFFFF...                                                                             [ 98%]
```

**Comment by rgommers** [comment] 2022-11-05 18:50
I suspect it's a newly added and highly parametrized test that is failing to close a data file, or some such thing. If you could run it with higher verbosity (e.g., `python dev.py test -s stats --verbose`) so that the test output shows on which test it's failing, then hopefully we can get that fixed.

**Comment by khpeterson** [comment] 2022-11-05 23:37
OK, I ran scipy.test(verbose=10) and have a log that shows the specific failing tests.  Would you like me to create another issue rather than conflate with this one?

**Comment by rgommers** [comment] 2022-11-06 07:13
Yes, that would be good, thanks (please Cc me on it).

**Comment by rgommers** [comment] 2023-04-24 22:51
I don't think there's anything left to do here, and nothing is actually broken. So I'll close this issue.

**Closed by rgommers** 2023-04-24 22:51 UTC
Labels: Build issues
