### ISSUE TITLE
BUG: Compile SciPy on Docker image i386/python:3.10.11-slim-bullseye not Success

### ISSUE THREAD

**Issue by pok1800** [scipy/scipy#18396] opened 2023-05-01 16:10 UTC
### Describe your issue.

Compile SciPy on Docker image i386/python:3.10.11-slim-bullseye not Success.

### Reproducing Code Example

```python
Test1
RUN pip3 install scipy==1.10.1  <-- Not work
Test2 
RUN pip3 install --no-cache-dir git+https://github.com/andyfaff/scipy <-- Not work
```

### Error message

```shell
Collecting git+https://github.com/andyfaff/scipy
  Cloning https://github.com/andyfaff/scipy to /tmp/pip-req-build-8vsmg7hl
  Running command git clone --filter=blob:none --quiet https://github.com/andyfaff/scipy /tmp/pip-req-build-8vsmg7hl
  Resolved https://github.com/andyfaff/scipy to commit 52a5ecb875588fcef5bc18dcd84b302a9ba9bd39
  Running command git submodule update --init --recursive -q
  From https://github.com/boostorg/math
   * branch                109a814e89f77ff8a3fc8f0391f6b35a12640669 -> FETCH_HEAD
  From https://github.com/scipy/highs
   * branch              4a122958a82e67e725d08153e099efe4dad099a2 -> FETCH_HEAD
  From https://github.com/scipy/unuran
   * branch            a63d39160e5ecc4402e7ed0e8417f4c3ff9634cb -> FETCH_HEAD
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      + meson setup /tmp/pip-req-build-8vsmg7hl /tmp/pip-req-build-8vsmg7hl/.mesonpy-c5n8yvav/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-req-build-8vsmg7hl/.mesonpy-c5n8yvav/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.1.0
      Source dir: /tmp/pip-req-build-8vsmg7hl
      Build dir: /tmp/pip-req-build-8vsmg7hl/.mesonpy-c5n8yvav/build
      Build type: native build
      Project name: SciPy
      Project version: 1.11.0.dev0
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2

      ../../meson.build:1:0: ERROR: Cython compiler 'cython' cannot compile programs

      A full log can be found at /tmp/pip-req-build-8vsmg7hl/.mesonpy-c5n8yvav/build/meson-logs/meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### SciPy/NumPy/Python version and system information

```shell
SciPy=1.10.1 
Python=3.10
Cython=3.0.0b2
```

**Comment by tylerjereddy** [comment] 2023-05-01 16:40
This is likely a duplicate of gh-18390, you could try pinning `gast` to version `0.5.3` or temporarily disabling Pythran.

**Comment by tupui** [comment] 2023-05-01 17:51
+1 Closing as we are discussing this already.

**Closed by tupui** 2023-05-01 17:51 UTC
Labels: defect
