### ISSUE TITLE
Possible error in docs for leastsq

### ISSUE THREAD

**Issue by HPLegion** [scipy/scipy#11850] opened 2020-04-13 09:39 UTC
Hello,

I am currently reading some of the source code touching on fitting routines in scipy because I am trying to verify that I understand the documentation correctly. I am not terribly comfortable with statistical methods.

During this work I discovered that in the [docs for leastsq](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.leastsq.html#scipy.optimize.leastsq) for the return values it says:

```
cov_xndarray

[...]
To obtain the covariance matrix of the parameters x,
cov_x must be multiplied by the variance of the residuals
 – see curve_fit.
```
However when looking at the code for ```curve_fit```, to me it looks as if the opposite is the case, i.e. cov_x is rescaled in cases where we are not interested in the absolute value of the parameter variance (because the absolute sigmas are unknown).

The respective code block https://github.com/scipy/scipy/blob/adc4f4f7bab120ccfab9383aba272954a0a12fb0/scipy/optimize/minpack.py#L760-L766
seems to return pcov/cov_x unchanged if the absolute sigmas are known. The documentation of ```curve_fit``` to me suggests that in this case pcov is the correctly scaled covariance matrix for the optimisied parameters, i.e. I can estimate the parameter uncertainties by taking the square root of the diagonal elements.

Chances are I am mixing something up here due to my personal lack of understanding, in that case I apologise for wasting your time :-P

**Comment by RobertoFranceschini** [comment] 2020-08-13 10:20
did you try this out minimizing the least squares sum for a simple dataset? I think it is the only way you can sleep well knowing the covariance from curve_fit is the one you think it is

**Comment by mdhaber** [comment] 2021-05-12 00:36
The code/documentation part of this doesn't look too bad, so it's a good first issue from that perspective. Requires some familiarity with the math, though.

**Comment by santinoacco** [comment] 2022-10-20 23:32
If no one is working on this topic I would like to help and contribute to this issue. I can try to figure out a solution and add some test to check.

**Comment by mdhaber** [comment] 2022-10-21 00:02
I think it is safe to assume that nobody else is working on it. Go for it!

**Comment by musteng** [comment] 2022-12-20 22:54
Are you working on this @santinoacco ? If not I may want to solve this.

**Comment by mdhaber** [comment] 2022-12-31 19:56
To make sure we stay in sync with the current codebase, here is section highlighted by @HPLegion.

https://github.com/scipy/scipy/blob/829b79c93a8bada44debcb0ace3265d4dd106470/scipy/optimize/_minpack_py.py#L885-L893

The [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.leastsq.html#scipy.optimize.leastsq) in question is:

![image](https://user-images.githubusercontent.com/6570539/210154241-d79aa319-a7d6-49c4-bfac-5d12e1e65459.png)

IIUC, the issue is that the documentation is suspected to be wrong:

> However, when looking at the code for curve_fit, to me it looks as if the opposite is the case...

The code that modifies `pcov` `if not absolute_sigma` is:

https://github.com/scipy/scipy/blob/829b79c93a8bada44debcb0ace3265d4dd106470/scipy/optimize/_minpack_py.py#L923-L934

Here is code that shows agreement between `pcov` returned by `curve_fit` and `cov_x` (scaled by the variance of the residuals) from `leastsq`.

<details>

```python3
import numpy as np
from scipy import optimize

rng = np.random.default_rng(8250058582555444926)
size = 100
x = np.linspace(0, 3, size)
y = 2*x + 1 + rng.normal(size=size)*0.5

def line(x, *p):
    return p[0]*x + p[1]

# with curve_fit
guess = np.array([1.0, 5.0])
popt, pcov = optimize.curve_fit(line, x, y, guess, method='lm')

# with leastsq
def residual(p):
    return line(x, *p) - y

popt, hessinv, _, _, _ = optimize.leastsq(residual, guess, full_output=True)
pcov2 = hessinv * np.var(residual(popt))

np.testing.assert_allclose(pcov, pcov2, atol=1e-3, rtol=5e-2)    
```

</details>

---

I don't see a problem with the documentation of `leastsq` in this case. The code above demonstrates that:

> To obtain the covariance matrix of the parameters `x`, `cov_x` must be multiplied by the variance of the residuals -- see curve_fit.

is true. I'm not sure where the confusion is coming from, but my guess it is actually the [curve fit documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html) - perhaps the definition of `absolute_sigma`?

![image](https://user-images.githubusercontent.com/6570539/210154409-359181e2-03d6-48c4-a304-adba4a26d451.png)

I don't think `absolute_sigma` is whether "the absolute sigmas are known" - the `sigma` parameter is used to specify known a covariance matrix of errors; `absolute_sigma` only changes how it is interpreted.

**Comment by mdhaber** [comment] 2023-01-10 07:23
I believe the issue was a misunderstanding that is resolved by the previous post.
It's been a few weeks without follow-up, so If I don't hear back in another two weeks or so, I'll go ahead and close this one.
If I misunderstood, or if there are documentation suggestions that would help us avoid a misunderstanding in the future, please let me know.

**Comment by HPLegion** [comment] 2023-01-11 08:43
Hi,

unfortunately it has been a while since I looked at this, and I really don't have time to dig deep right now.
But looking at @mdhaber 's posts I think it looks indeed as if I misunderstood the docstrings at the time when I ran into this. So this can probably be closed.

Cheers to all of you for following up on this regardless! :)

**Comment by ilayn** [comment] 2023-01-11 08:45
Thanks all for the discussion then

**Closed by ilayn** 2023-01-11 08:45 UTC
Labels: scipy.optimize, Documentation, good first issue
