### ISSUE TITLE
integrate.quad() problem

### ISSUE THREAD

**Issue by lfini** [scipy/scipy#11571] opened 2020-02-21 21:50 UTC
My issue is about a funny behavior of scipy function integrate.quad.

Integrating a gaussian function I get wrong values depending on the integration interval. See below.
in [3] I compute the integral on [-100, 0.5] and I get the expected value.

In [4] I compute the same integral on [-1000,0.5]. I expect the same value because there is no co ntribute to the integral sum extending the interval to the left. But I get a wrong value.

In [5] and [6] I show that something happens between -997 and -998

In [7] I extend further the integration interval and the returned value is still wrong (I've tried several values with the same result.

In [8] I show that the integral is correct if I integrate from -infinity

#### Reproducing code example:

```
$ ipython --pylab
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import scipy.integrate as integrate                                                                   

In [2]: from scipy.stats import norm                                                                          

In [3]: integrate.quad(lambda x:norm.pdf(x,0.64449662,0.19),-100,0.5)                                         
Out[3]: (0.22347533732644612, 3.1634786288170372e-12)

In [4]: integrate.quad(lambda x:norm.pdf(x,0.64449662,0.19),-1000,0.5)                                        
Out[4]: (4.75208186635514e-09, 9.44858985141507e-09)

In [5]: integrate.quad(lambda x:norm.pdf(x,0.64449662,0.19),-987,0.5)                                         
Out[5]: (0.22347533732644612, 1.8395174387908237e-10)

In [6]: integrate.quad(lambda x:norm.pdf(x,0.64449662,0.19),-988,0.5)                                         
Out[6]: (7.303423606392351e-09, 1.4521436311212504e-08)

In [7]: integrate.quad(lambda x:norm.pdf(x,0.64449662,0.19),-2000,0.5)                                        
Out[7]: (6.486552015239486e-32, 1.2897246147166321e-31)

In [8]: integrate.quad(lambda x:norm.pdf(x,0.64449662,0.19),-np.inf,0.5)                                      
Out[8]: (0.2234753373264382, 1.598765108016799e-09)

```

#### Error message:
No error message. Wrong result

**Comment by lfini** [comment] 2020-02-21 21:52
Here follows version info:
...
In [13]: print(scipy.__version__, numpy.__version__, sys.version_info)                                        
1.4.1 1.18.1 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
...

**Comment by ev-br** [comment] 2020-02-22 06:08
Is seems to be a duplicate of 
https://github.com/scipy/scipy/issues/10305 : the adaptive routine gets confused and fails to find a tiny peak over a huge integration interval where the function is mostly zero.

**Comment by mdhaber** [comment] 2023-01-21 07:18
I don't think this is a defect. It's just the way these algorithms work. Please let us know if you find an algorithm that is guaranteed to find all peaks in an arbitrary integration interval, though. 

gh-10305 and other similar reports have been closed for the same reason, so I'll follow suit and close this one.

**Closed by mdhaber** 2023-01-21 07:18 UTC
Labels: defect, scipy.integrate, duplicate

**Comment by ev-br** [comment] 2023-01-21 11:33
This comes up regularly, and I don't believe there is a way out for an adaptive quadrature. Maybe we could try making a doc note to this effect more visible and with its own anchor, so that we can close with a link next time(s).

**Comment by mdhaber** [comment] 2023-01-21 16:18
Ok. I'll do that. Thanks @ev-br !

**Comment by mdhaber** [comment] 2023-01-21 17:13
Hah we could link to this:
https://www.mathworks.com/matlabcentral/answers/276764-numerical-integration-gives-0#answer_216121
Presumably "User Level 9 of 10" carries some weight. I'll keep looking for an academic reference, though.
