### ISSUE TITLE
jac argument for scipy.integrate.solve_ivp() ignored

### ISSUE THREAD

**Issue by Henrik-AI** [scipy/scipy#11607] opened 2020-02-28 14:27 UTC
The jacobian argument is not used and not validated. Passing some wrong datatype, int(42) for example, errors are thrown. The callable is never called!!!

#### Reproducing code example:

```
import numpy as np
from scipy.integrate import solve_ivp

def f(t, y):
    return np.arange(42)

def jac():
    print('hello world')

if __name__ == '__main__':
    solve_ivp(f, (0, 1), np.zeros(42), method='LSODA', jac=jac)
```

#### Error message:

This should print an error or at least 'hello world'. Unfortunately it turns out, the jacobian function is never called!

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by Henrik-AI** [comment] 2020-02-28 14:29
seems to be related to #10793

**Comment by gholdman1** [comment] 2020-02-28 15:19
According to the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html), `solve_ivp` defaults to using the `RK45` method (Runge-Kutta method of order 5(4) ). This algorithm does not use a jacobian. See [this answer](https://scicomp.stackexchange.com/questions/14635/is-there-a-relatively-simple-way-to-extract-the-jacobian-from-a-runge-kutta-4-5) on stackexchange.

**Comment by MatthewFlamm** [comment] 2020-03-03 20:15
The LSODA method switches between nonstiff solver, which does not call the Jacobian, and a stiff solver, which does call the Jacobian.  It detects the stiffness of the problem and only switches to the stiff solver if necessary.  You have provided a nonstiff ODE, therefore the Jacobian is never called in LSODA method.  The LSODA method will call the Jacobian if a stiff problem is used as is shown in the linked issue, which is about banded Jacobians.

The BDF method always uses the Jacobian and you can verify that it calls it as below.

```
import numpy as np
from scipy.integrate import solve_ivp
def f(t, y):
        return np.arange(42)
        
def jac(t, y):
        print('hello world')

# following line never calls Jacobian because the problem is nonstiff        
solve_ivp(f, (0, 1), np.zeros(42), method='LSODA', jac=jac)

# following line will call Jacobian because it doesn't check stiffness
# but the Jacobian isn't specified properly so an error is raised
solve_ivp(f, (0, 1), np.zeros(42), method='BDF', jac=jac) 
```

**Comment by Henrik-AI** [comment] 2020-03-04 13:48
1. What is the decision criterion for stiffness? According to my assumption, my model is a stiff system. Experiments with explicit solvers showed that the required extremely small stepsizes reasoned by the stability, not by the accuracy, which should be a sign for a stiff problem?

2. Is it possible to enforce the solver the use the jacobian nevertheless? Runtime experiments with the other solvers and our expectation suggest a possible speedup by using an analytical jacobian instead of calculating one via finite differences. Especially for LTI Systems, where the jacobian does not change in time and just needs to be calculated ones, a speed-up is expected.

Taking the other solvers is not really an option. The runtime in all of our experiments showed way longer calculation times. Even the Speedup by getting a sparse Jacobian is not big enough to beat the LSODA.

The solver is used for Reinforcement Learning, so the runtime is really crucial!

**Comment by MatthewFlamm** [comment] 2020-03-04 14:31
For 1) you have to go to the documentation for LSODA itself.  Here is the [LSODA source code](https://github.com/scipy/scipy/blob/master/scipy/integrate/odepack/lsoda.f) within scipy from which you can get some background info from the comments and a reference to a paper written on LSODA.

For 2) If you want to enforce it to always use the stiff solver, you wouldn't use LSODA, you would use LSODE (if you are can only choose from the ODEPACK fortran integrators), which unfortunately isn't available in scipy.  But, I believe that both LSODA and LSODE use the BDF method for stiff problems, which is included in scipy with a separate implementation for solve_ivp.  This would be functionally, but not identically equivalent to the stiff solver in LSODA or LSODE.  Have you tried this as I suggested above?  If your performance isn't very good, I would suspect that you have not written your functions to use numpy vectorization.

Also, you need to probably need to adjust the default tolerances in solve_ivp.  The default tolerances are _extremely high_ and you need to reduce them for stiff problems in my experience.

**Comment by stheid** [comment] 2020-03-05 09:35
Thank you for your help, i think the issue is now solved for us.

**Comment by Patol75** [comment] 2021-09-21 02:30
@tupui @tylerjereddy Just a friendly ping to let you know that you should be able to close this issue without any trouble.

**Closed** 2021-09-21 02:54 UTC
Labels: defect, scipy.integrate
