### ISSUE TITLE
compilation of master on Ubuntu (14.04)

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#5594] opened 2015-12-08 17:50 UTC
Hi,

I've been trying to compile the latest scipy master branch on Ubuntu (14.04) for a few days and thought I'd attach my build log text file, and ask for suggestions.

[build_log.txt](https://github.com/scipy/scipy/files/55807/build_log.txt)

I've looked at the official guide for doing this kind of thing, and of course each time an error pops up you can kind of google it and squash it, but the progress seems to be a bit circular with old problems re-emerging as I fix other things in the build process.

The `build_log.txt` file comes from: `python setup.py -vvv build > & build_log.txt` 

I've tried adjusting `site.cfg` in various ways, adjusting the various environment variables that can cause issues, removing older versions of gfortran, and even looking through the scipy `travis.yml` file to check for tricks I might be missing.

I'm a bit suspicious of the multiple -L cuda paths in the final problematic gfortran compilation--are those possibly the issue here? 

The primary motivation for building scipy master / related branches is to allow me to use recent contributions that are important for my research, but may not be available in binaries for quite some time. The build process works fine on Mac OS X for the same branch.

Thanks,
Tyler

**Comment by pv** [comment] 2015-12-08 18:18
Try "unset LDFLAGS" and probably others.
(Closing -- not a bug report, but feel free to discuss.)

**Closed by pv** 2015-12-08 18:18 UTC
Labels: query
