### ISSUE TITLE
LinAlgError in lobpcg: leading minor not positive definite

### ISSUE THREAD

**Issue by cinvro** [scipy/scipy#5947] opened 2016-03-09 02:59 UTC
I am using scikit-learn to train a spectral clustering model, which calls lobpcg to find the spectral embedings:

```
lambdas, diffusion_map = lobpcg(laplacian, X, tol=1e-15,
                                largest=False, maxiter=2000)
```

and I run into following errors:

```
numpy.linalg.linalg.LinAlgError: the leading minor of order 18 of 'b' is not positive definite.      
The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.
```

The laplacian is a 100 X 100 symmetrical matrix. 
X is randomly generated, according to the code in scikit-learn.

**Comment by ev-br** [comment] 2016-03-10 22:17
Could you provide a short self-contained example which shows the problem? Ideally, it would demonstrate it with scikit-learn being out of the picture.

**Comment by lobpcg** [comment] 2018-09-14 17:36
That should now be fixed in scikit-learn, see [https://github.com/scikit-learn/scikit-learn/issues/6489#issuecomment-421422497](url) and issue can be closed

**Comment by lobpcg** [comment] 2018-09-14 17:40
> I am using scikit-learn to train a spectral clustering model, which calls lobpcg to find the spectral embedings:
> 
> ```
> lambdas, diffusion_map = lobpcg(laplacian, X, tol=1e-15,
>                                 largest=False, maxiter=2000)
> ```
> and I run into following errors:
> 
> ```
> numpy.linalg.linalg.LinAlgError: the leading minor of order 18 of 'b' is not positive definite.      
> The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.
> ```
> The laplacian is a 100 X 100 symmetrical matrix.
> X is randomly generated, according to the code in scikit-learn.

The issue is that  tol=1e-15 is way too excessive for LOBPCG and cannot be even reached, making LOBPCG to crash. Just use more reasonable tolerance and it should work fine.

**Comment by rgommers** [comment] 2019-08-10 23:21
this was fixed, closing. thanks all

**Closed by rgommers** 2019-08-10 23:21 UTC
Labels: query, scipy.sparse.linalg
