### ISSUE TITLE
scipy.optimize.least_squares fails if the return array of the `fun` callback is reused

### ISSUE THREAD

**Issue by bek0s** [scipy/scipy#11493] opened 2020-02-09 22:41 UTC
`scipy.optimize.least_squares` thinks that it has converged if the return array of the `fun` callback is reused. Due to this error I need to do one additional copy of a very big array every time I calculate my residuals. This is of course waste of memory.

#### Reproducing code example:

This is a modified version of the example found in [scipy.optimize.least_squares](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html) documentation. The `enable_bug` flag enables and disables the bug.
```
import numpy as np
from scipy.optimize import least_squares

enable_bug = True
buffer = np.empty(2)

def fun_rosenbrock(x):
    buffer[:] = np.array([10 * (x[1] - x[0] ** 2), (1 - x[0])])
    return buffer if enable_bug else np.array(buffer)

x0_rosenbrock = np.array([2, 2])
res_1 = least_squares(fun_rosenbrock, x0_rosenbrock)

print('x:', res_1.x)
print('nfev: ', res_1.nfev)
print('message: ', res_1.message)
```
#### Output (bug disabled):

This is how the output should look like (`enable_bug = False`):
```
x: [1. 1.]
nfev:  3
message:  `gtol` termination condition is satisfied.
```

#### Output (bug enabled):

This is the wrong output  (`enable_bug = True`):
```
x: [2. 2.]
nfev:  1
message:  `gtol` termination condition is satisfied.
```

#### Scipy/Numpy/Python version information:

 By running the following:
```
import sys, scipy, numpy
print(scipy.__version__, numpy.__version__, sys.version_info)
```
I get the following:
```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment] 2020-03-30 10:50
I'm not sure if this is a bug, looks like user error - inplace operations on arrays that are outputs of function calls should always be allowed. I think there'd be many other functions where you could construct such examples.

@AtsushiSakai or @bek0s, it would be good to spell out more clearly what is happening inside `least_squares` that could be considered a bug.

**Comment by AtsushiSakai** [comment] 2020-03-30 11:35
@rgommers This problem happened because the loss function return a reference of global variable, and I think some codes change the variable value in `least_squres`. So, I changed the `least_squares` to make a copy of return value of loss function and use it in main optimization routine.
I agree that you think it is not a bug. It is OK to close this issue and my PR if you want : ).

**Comment by bek0s** [comment] 2020-03-30 11:54
@rgommers To my understanding, in order to classify this as "not a bug", the documentation of the `fun` argument in `scipy.optimize.least_squares` should change from this:

`It must return a 1-d array_like of shape (m,) or a scalar.` 

To something like this:

`It must always allocate and return a new 1-d array_like of shape (m,) or a scalar.`

Unless I am misreading the documentation.

Thanks

**Comment by rgommers** [comment] 2020-03-30 12:17
> and I think some codes change the variable value in `least_squres`

indeed, I was asking if you found out which code that was. that could help deciding on the best solution

**Comment by AtsushiSakai** [comment] 2020-04-01 12:41
@rgommers I'm sorry I tried to find which code that was today, but I could not find it. I will try it later again. 
BTW. In my observation, `method` is no related to this issue, because all `method` has same result.

**Comment by nmayorov** [comment] 2020-04-02 19:12
@rgommers @AtsushiSakai 

The problem occurs when computing numerical derivative: `df = fun(x) - f0` returns zeros and the optimizer thinks that Jacobian and gradient is zero (thus the solution is optimal) right at the initial point and terminates.

We can fix it by doing copies at this place (and maybe other places), but I think it's not a right approach fundamentally - we still doing many copies and only hides this requirement from a user. 

I think adjusting documentation as suggested by @bek0s is a better solution.

@AtsushiSakai would you rework your pull request in this way?

**Comment by AtsushiSakai** [comment] 2020-04-03 11:44
@nmayorov Thank you for your analysis!!. I updated my PR #11752 . PTAL

**Closed** 2020-04-04 10:38 UTC
Labels: scipy.optimize
