### ISSUE TITLE
BUG: Inconsistent behaviour in scipy.sparse.find

### ISSUE THREAD

**Issue by JoergVanAken** [scipy/scipy#19542] opened 2023-11-16 21:17 UTC
### Describe your issue.

The `scipy.sparse.find` leads to different results in different scipy versions. 

### Reproducing Code Example

```python
Python 3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from scipy.sparse import csr_matrix, find

In [2]: A = csr_matrix([[1.0, 2.0, 0],[2.0, 3, 0], [0, 0, 4]])

In [3]: find(A)
Out[3]:
(array([0, 1, 0, 1, 2], dtype=int32),
 array([0, 0, 1, 1, 2], dtype=int32),
 array([1., 2., 2., 3., 4.]))


Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from scipy.sparse import csr_matrix, find

In [2]: A = csr_matrix([[1.0, 2.0, 0],[2.0, 3, 0], [0, 0, 4]])

In [3]: find(A)
Out[3]: (array([0, 0, 1, 1, 2]), array([0, 1, 0, 1, 2]), array([1., 2., 2., 3., 4.]))

```

### Error message

```shell
The results should be the same but they are different.
```

### SciPy/NumPy/Python version and system information

```shell
The first example uses python 3.8.16, scipy 1.6.2, numpy 1.22.4

The second uses python 3.10.13, scipy 1.11.3, numpy 1.26.0
```

**Comment by dschmitz89** [comment] 2024-04-01 22:19
Related to https://github.com/scipy/scipy/pull/20314 ? CC @perimosocordiae Looks like another accidental transpose operation to me.

**Comment by perimosocordiae** [comment] 2024-04-01 23:50
Looks similar, yes, but I'm less inclined to treat this as a bug. The "natural" index ordering for CSR format is C-order, which the new behavior matches.

As @TimButters mentioned, both results are correct, and we don't guarantee a fixed index ordering. So in this case, I'm going to say it's working as intended.

**Closed** 2024-04-01 23:51 UTC
Labels: defect, scipy.sparse
