### ISSUE TITLE
cant install scipy on my laptop

### ISSUE THREAD

**Issue by kartikeyasaxena1012** [scipy/scipy#7645] opened 2017-07-23 13:04 UTC
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Dell>pip install scipy
Collecting scipy
  Using cached scipy-0.19.1.tar.gz
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command c:\users\dell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-build-7txu6_5w\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Dell\AppData\Local\Temp\tmp1l7vwfw7pip-wheel- --python-tag cp36:
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.10.1-sse2-32\lib is invalid.
    pre_dirs = system_info.get_paths(self, section, key)
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
    libraries lapack not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
    NOT AVAILABLE

  c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  non-existing path in 'scipy\\integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Dell\AppData\Local\Temp\pip-build-7txu6_5w\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\Dell\AppData\Local\Temp\pip-build-7txu6_5w\scipy\setup.py", line 412, in setup_package
      setup(**metadata)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\Dell\AppData\Local\Temp\pip-build-7txu6_5w\scipy\setup.py", line 336, in configuration
      config.add_subpackage('scipy')
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command c:\users\dell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-build-7txu6_5w\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  Failed cleaning build dir for scipy
Failed to build scipy
Installing collected packages: scipy
  Running setup.py install for scipy ... error
    Complete output from command c:\users\dell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-build-7txu6_5w\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dell\AppData\Local\Temp\pip-hld1q3ns-record\install-record.txt --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)

    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.10.1-sse2-32\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
      NOT AVAILABLE

    c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-7txu6_5w\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-7txu6_5w\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-7txu6_5w\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "c:\users\dell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-build-7txu6_5w\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dell\AppData\Local\Temp\pip-hld1q3ns-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Dell\AppData\Local\Temp\pip-build-7txu6_5w\scipy\

C:\Users\Dell>

**Comment by ilayn** [comment] 2017-07-23 13:42
Please have a look at #5461, this is a very common question (duplicate in fact) and on Windows systems you are better off with downloading the wheels and installing them instead.

**Comment by ev-br** [comment] 2017-07-23 13:50
Closing as a duplicate of gh-5461 and others

**Closed by ev-br** 2017-07-23 13:50 UTC

**Comment by kartikeyasaxena1012** [comment] 2017-07-23 14:07
@ilayn sir I tried to install wheel and it did but still nothing happened
I still cant install scipy take a look at this


C:\Users\Dell>pip install scipy
Collecting scipy
  Using cached scipy-0.19.1.tar.gz
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command c:\users\dell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-build-kjouyblt\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Dell\AppData\Local\Temp\tmp7_p9s2q8pip-wheel- --python-tag cp36:
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_rt not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.10.1-sse2-32\lib is invalid.
    pre_dirs = system_info.get_paths(self, section, key)
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
    libraries lapack not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
    NOT AVAILABLE

  c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  non-existing path in 'scipy\\integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Dell\AppData\Local\Temp\pip-build-kjouyblt\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\Dell\AppData\Local\Temp\pip-build-kjouyblt\scipy\setup.py", line 412, in setup_package
      setup(**metadata)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\Dell\AppData\Local\Temp\pip-build-kjouyblt\scipy\setup.py", line 336, in configuration
      config.add_subpackage('scipy')
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
      caller_level = 2)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
      caller_level = caller_level + 1)
    File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command c:\users\dell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-build-kjouyblt\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).


  ----------------------------------------
  Failed cleaning build dir for scipy
Failed to build scipy
Installing collected packages: scipy
  Running setup.py install for scipy ... error
    Complete output from command c:\users\dell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-build-kjouyblt\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dell\AppData\Local\Temp\pip-mcg9wgb_-record\install-record.txt --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.10.1-sse2-32\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\lib', 'C:\\', 'c:\\users\\dell\\appdata\\local\\programs\\python\\python36-32\\libs']
      NOT AVAILABLE

    c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-kjouyblt\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-kjouyblt\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\Dell\AppData\Local\Temp\pip-build-kjouyblt\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\dell\appdata\local\programs\python\python36-32\lib\site-packages\numpy\distutils\misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "c:\users\dell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dell\\AppData\\Local\\Temp\\pip-build-kjouyblt\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dell\AppData\Local\Temp\pip-mcg9wgb_-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Dell\AppData\Local\Temp\pip-build-kjouyblt\scipy\

C:\Users\Dell>

**Comment by ilayn** [comment] 2017-07-23 14:16
@kartikeyasaxena1012  Download the wheel that is suitable for your own system from http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy and then use `pip install <file name>.whl`
