### ISSUE TITLE
scipy.signal.butter: wrong error message

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#15542] opened 2022-02-07 11:22 UTC
With Wn=2 I correctly got the message

`ValueError: Digital filter critical frequencies must be 0 < Wn < 1`

But actually Wm=1 is accepted without error.  The message should be changed to  `0 < Wn <= 1` if 1 is allowed.

**Comment by roryyorke** [comment] 2022-03-05 16:28
This is a duplicate of gh-11235, and I think was fixed by scipy 1.5; it's certainly fixed in 1.7:

```
>>> import scipy
>>> from scipy.signal import butter
>>> print(scipy.__version__)
1.7.3
>>> butter(2, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rory/miniconda3/envs/work/lib/python3.9/site-packages/scipy/signal/filter_design.py", line 2956, in butter
    return iirfilter(N, Wn, btype=btype, analog=analog,
  File "/home/rory/miniconda3/envs/work/lib/python3.9/site-packages/scipy/signal/filter_design.py", line 2424, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1
>>> butter(2, 5, fs=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rory/miniconda3/envs/work/lib/python3.9/site-packages/scipy/signal/filter_design.py", line 2956, in butter
    return iirfilter(N, Wn, btype=btype, analog=analog,
  File "/home/rory/miniconda3/envs/work/lib/python3.9/site-packages/scipy/signal/filter_design.py", line 2422, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < fs/2 (fs=10 -> fs/2=5.0)
```

**Comment by j-bowhay** [comment] 2022-03-05 19:45
Agree with @roryyorke I couldn't replicate this issue. @keithbriggs what version of scipy are you using?

**Comment by keithbriggs** [comment] 2022-03-06 09:27
I have since upgraded and the problem has gone away.   I can no longer check what version I was previously using.

**Comment by j-bowhay** [comment] 2022-03-06 18:40
Ok I think this issue can be closed then

**Closed** 2022-03-07 13:30 UTC
Labels: scipy.signal
