### ISSUE TITLE
Installing scipy on aarch64

### ISSUE THREAD

**Issue by odidev** [scipy/scipy#11555] opened 2020-02-19 12:21 UTC
Summary
----------
Installing scipy on aarch64 via pip using command "pip3 install scipy" tries to build wheel from source code

Problem description
----------------------
Scipy don't have wheel for aarch64 on PyPI repository. So, while installing scipy via pip on aarch64, pip builds wheel for same resulting in it takes more time to install scipy. Making wheel available for aarch64 will benefit aarch64 users by minimizing scipy installation time.

Expected Output
-------------------
Pip should be able to download scipy wheel from PyPI repository rather than building it from source code.

@scipy-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make scipy wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by tylerjereddy** [comment] 2020-02-20 00:20
The SciPy team is on the path to providing these pre-built binaries. For example, you can see that our upstream OpenBLAS binaries are now built for multiple architectures including ARMv8:

https://travis-ci.org/MacPython/openblas-libs/builds/652316285?utm_source=github_status&utm_medium=notification

However, there are quite a few moving parts in the release process, and we haven't quite ironed everything out yet. We're also in the process of migrating our wheel builds to a different infrastructure now too, so maintenance tasks can slow down the progress a bit here.

**Comment by rgommers** [comment] 2020-03-27 13:31
This is a duplicate of gh-11724 and gh-11170, so closing. Thanks @odidev

**Closed by rgommers** 2020-03-27 13:31 UTC
Labels: Build issues, Official binaries
