### ISSUE TITLE
Scipy fails tests on master branch

### ISSUE THREAD

**Issue by owahltinez** [scipy/scipy#9164] opened 2018-08-21 05:33 UTC
After I checkout SciPy and run the tests as-is, I'm seeing >50 test failures. The steps being followed are:

```sh
conda create -n scipy python=3
conda install -y mkl numpy setuptools matplotlib cython pytest
git clone https://github.com/scipy/scipy
cd scipy
python setup.py build_ext --inplace
python runtests.py -v
```

I have also tried:

```sh
apt-get install -yq build-essential ca-certificates gcc gfortran git python3 python3-pip
pip3 install cython matplotlib mkl numpy pytest setuptools
git clone https://github.com/scipy/scipy
cd scipy
python setup.py build_ext --inplace
python runtests.py -v
```

These steps were followed in the continuumio/anaconda3 Docker image. I have also had similar luck trying to do this on OSX. For what it's worth, the OSX binaries from Conda output two failures when I run:

```sh
python -c 'import scipy; scipy.test("full")'
```

What is the right way to build SciPy in a way that passes all tests?

**Comment by ilayn** [comment] 2018-08-21 05:42
What are the test failures? Can you include them here too?

**Comment by owahltinez** [comment] 2018-08-23 04:32
Sure, here is the output from the tests:
- https://pastebin.com/XDwMh1bE for the SciPy built on Debian (Docker image continuumio/anaconda3)
- https://pastebin.com/X91F9bwZ for the output of running tests on OSX binaries (from Conda)

**Comment by ilayn** [comment] 2018-08-23 05:57
This looks like a duplicate of #8325

**Comment by owahltinez** [comment] 2018-08-30 17:08
But I'm not using Conda at all. And when I install gcc via Conda I get a different set of errors (see https://pastebin.com/GvHMeXnT). I understand that this may not be entirely Scipy's fault but I have yet not found a way to compile Scipy successfully.

**Comment by pv** [comment] 2018-08-30 18:52
Also your Debian build is building with Conda's Python. This matters because compiler flags etc come from Conda's Python configuration, and I'm not sure if that's meant to generally work on any Linux distribution.

**Comment by pv** [comment] 2018-08-30 18:58
On the OSX failures, I'd uninstall mkl_fft and any other Conda packages that monkeypatch numpy/scipy, and then try again.

**Comment by rgommers** [comment] 2018-09-02 10:02
> Also your Debian build is building with Conda's Python. This matters because compiler flags etc come from Conda's Python configuration, and I'm not sure if that's meant to generally work on any Linux distribution. 

Pretty sure it is. 

I'm using conda, and it works fine with MKL - no failures on master currently. Gcc is as packaged by Arch Linux, never had issues.
```
$ gcc --version
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rgommers@machine:~/code/scipy (issue-9103-spearmanr)$ python --version
Python 3.6.4 :: Anaconda custom (64-bit)
```

**Comment by rgommers** [comment] 2018-09-02 10:05
> For what it's worth, the OSX binaries from Conda output two failures when I run:

Those look like test precision issues, numerical output is almost identical.

**Comment by owahltinez** [comment] 2018-09-13 06:57
Thank you everyone for the help so far. Sorry for being thick here, but I'm still unable to build binaries of Scipy that can pass the self-test.

> conda is not included in this set (and we can't help with problems with conda as those builds are not something controlled by us)

That makes sense. It is unfortunate that binaries built with Conda can't pass the self-test, and I wonder what they are doing differently. Precision is one of the features I look for in a numerical library...

> I'm using conda, and it works fine with MKL - no failures on master currently. Gcc is as packaged by Arch Linux, never had issues

Good to know that there's at least one configuration that works, I still have not been able to get it right on any of my machines or Docker images; can someone point me to the configuration used in build servers? So far I have tried:

- Conda's Python binaries (with and without a mix of tools from `apt` as I mentioned in [1](https://github.com/scipy/scipy/issues/9164#issuecomment-415287022) and [2](https://github.com/scipy/scipy/issues/9164#issuecomment-417394970))
- Docker's `python:latest` image
- Docker's `ubuntu:bionic` image
- Docker's `debian:stretch` image

The steps that I'm following are what I mentioned in the [first comment](https://github.com/scipy/scipy/issues/9164#issue-352391465) but I'll copy/paste again here for convenience:
```sh
apt-get install build-essential ca-certificates gcc gfortran git
pip3 install cython matplotlib mkl numpy pytest setuptools

git clone https://github.com/scipy/scipy
cd /scipy

python setup.py build_ext --inplace
python runtests.py -v
```

I am now seeing `ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory` in all 3 different configurations, so there must be something I'm missing with the build steps. I couldn't find a way to resolve this problem after a cursory search for that error.

**Comment by ilayn** [comment] 2018-09-13 07:04
Can you follow the steps given here https://github.com/davisking/dlib/issues/587 ?

**Comment by owahltinez** [comment] 2018-09-14 00:43
I think I finally found a winning configuration which results in `python runtests.py -v` finishing with a success return code. If I add `ldconfig`, which leaves the build script like this:

```sh
apt-get install build-essential ca-certificates gcc gfortran git
pip3 install cython matplotlib mkl numpy pytest setuptools
ldconfig

git clone https://github.com/scipy/scipy
cd /scipy

python setup.py build_ext --inplace
python runtests.py -v
```

Then the final output is:
- `python:latest` : 13883 passed, 1289 skipped, 1217 deselected, 87 xfailed, 7 xpassed in 455.82 seconds
- `debian:stretch` : 13873 passed, 1299 skipped, 1217 deselected, 87 xfailed, 7 xpassed in 444.03 seconds
- `ubuntu:bionic` : 13883 passed, 1289 skipped, 1217 deselected, 87 xfailed, 7 xpassed in 439.99 seconds

The follow-up questions are: what does "xfailed" mean? Are 87 xfailures expected? How about the skipped tests? The full output is too large to upload somewhere, so I grepped for `xfail` and here's the result: https://pastebin.com/MfVUTFfE

Also, I am happy to contribute by adding my build scripts in the form of a `Dockerfile`. If that's something you guys are interested in, what would be the best location within the source for it?

**Comment by rgommers** [comment] 2018-09-14 02:00
`xfailed` is "expected failure", so those you can ignore - we marked them as failures for known issues but wanted to keep the tests around for future use / fixing.

> Also, I am happy to contribute by adding my build scripts in the form of a Dockerfile. If that's something you guys are interested in, what would be the best location within the source for it?

I don't think it's something we want in the repo, as it shouldn't be needed and requires maintenance. Would be nice if you could post it as a gist and link to it from this issue.

**Comment by rgommers** [comment] 2019-03-05 01:59
Since `python runtests.py -v` worked for the issue reporter and that that is our recommended development setup, I think there isn't anything actionable left to do here - closing. Thanks all!

**Closed by rgommers** 2019-03-05 01:59 UTC
Labels: Build issues
