### ISSUE TITLE
LinearNDInterpolator returns NaN when called with points passed to the constructor

### ISSUE THREAD

**Issue by chrisranderson** [scipy/scipy#9737] opened 2019-01-31 20:00 UTC
My issue is about LinearNDInterpolator returning NaN when it ought not. I would expect it to return a value for every source point that I passed in. When I call it with the same points it was constructed with, it sometimes returns a nan.

I can paste the following into a new file and run it as is and get the issue.

### Reproducing code example:
```
import numpy as np
from scipy.interpolate.interpnd import LinearNDInterpolator
some_points = np.array([[42.95140444448968, 324.3801108160104, 8.915229885057471],
                        [42.94872182954715, 324.3805993217575, 8.943965517241379],
                        [42.94886055081152, 324.3806075832518, 9.030172413793105],
                        [42.94870954506439, 324.3804284884243, 8.96551724137931],
                        [42.94869726058163, 324.3802576550909, 8.994252873563218],
                        [42.95140444448968, 324.3801108160104, 8.915229885057471]])
interpolator = LinearNDInterpolator(some_points[:, :2], some_points[:, 2])
print(interpolator(some_points[:, :2]))
``` 
Result:
```
[8.91522989 8.94396552 9.03017241        nan 8.99425287 8.91522989]
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```

```
1.1.0 1.15.2 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by AtsushiSakai** [comment] 2020-07-20 12:31
This issue seems to be fixed in my environment. This is result of the provided code:
`[8.91522989 8.94396552 9.03017241 8.96551724 8.99425287 8.91522989]` 

This is my environment:
OS: Mac OS Catalina 10.15.6
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
# 1.5.1 1.19.0 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
```

**Comment by peterbell10** [comment] 2020-07-20 21:11
I can confirm. I was able to reproduce by downgrading to 1.3 but anything 1.4+ doesn't give nans.

**Closed by peterbell10** 2020-07-20 21:11 UTC
Labels: scipy.interpolate
