### ISSUE TITLE
BUG: power_divergence is raising on master when it does not in 1.6 or earlier

### ISSUE THREAD

**Issue by bashtage** [scipy/scipy#13362] opened 2021-01-07 18:47 UTC
My issue is about a bug appearing in the unreleased SciPy  1.7.0.dev0+9b9f2e8. This is appearing in the statsmodels pip-pre run.

#### Reproducing code example:

```
from numpy import array
from scipy import stats


f_obs = array([44, 74, 48, 24,  8,  2])
f_exp = array([43.93623589, 71.60431015, 52.20297275, 23.22015199,  7.16316534,
        1.59334208])
chi2 = stats.chisquare(f_obs , f_exp )

```

#### Error message:

```
>               raise ValueError(msg)
E  ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected 
E frequencies to a relative tolerance of 1e-08, but the percent differences are:
E  0.0014010692380163618
```

**Comment by bashtage** [comment] 2021-01-07 18:48
The full log of the run showing the error in power_divergence:

[statsmodels-pip-pre-log.txt](https://github.com/scipy/scipy/files/5783403/statsmodels-pip-pre-log.txt)

**Comment by bashtage** [comment] 2021-01-07 18:51
blame 5fb232730b41b60a79f822db7fd47909dd5f6947

**Comment by bashtage** [comment] 2021-01-07 18:52
xref #13193

**Comment by WarrenWeckesser** [comment] 2021-01-07 19:07
Check the sums of your observed and expected arrays:
```
In [136]: f_obs = array([44, 74, 48, 24,  8,  2]) 
     ...: f_exp = array([43.93623589, 71.60431015, 52.20297275, 23.22015199,  7.16316534, 
     ...:         1.59334208])                                                                 

In [137]: f_obs.sum()                                                                          
Out[137]: 200

In [138]: f_exp.sum()                                                                          
Out[138]: 199.72017820000002
```
They are not the same.  This check was added in https://github.com/scipy/scipy/pull/13193.  For meaningful results, the sums should be the same.  The addition of the check is, in effect, a bug fix, and it will prevent users from getting questionable results from data where the sums are not the same.

**Comment by bashtage** [comment] 2021-01-10 23:03
> The addition of the check is, in effect, a bug fix, and it will prevent users from getting questionable results from data where the sums are not the same.

I don't see anything in the definition of Pearson's test statistic that requires the that actual and expected number are the same.  In large samples when the observed differ from the expected it will eventually always reject. 

https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test

This fix appears to be wrong at least for the Pearson test (`chisquare`) which lead to this error being detected.

**Comment by mdhaber** [comment] 2021-01-22 06:59
@bashtage at that article, I see:
> In this context, the frequencies of both theoretical and empirical distributions are unnormalised counts, and for a chi-squared test the total sample sizes _N_ of both these distributions (sums of all cells of the corresponding contingency tables) have to be the same.

Is there a different context in which the unnormalized counts do not have to be the same for the test to make sense?

@sam-data-guy you brought this up in gh-12282. Thoughts on this?

**Comment by sam-data-guy** [comment] 2021-01-24 14:54
I don't think so.  The whole point of comparing observed and expected
totals is that they represent different alternatives under the assumption
that the frequencies sum to the same.
First of all, if you go to the description of the chi square test (
https://en.wikipedia.org/wiki/Chi-squared_test), under "Pearson chi squared
test", it mentions that the sum of the observed x_i frequencies and m_i
have to be equal.  Similarly, the chisqure test here calls the
power_divergence function, which also says "Also, the sum of the observed
and expected frequencies must be the same for the test to be valid;
`power_divergence` raises an error if the sums do not agree within a
relative tolerance of ``1e-8``."  As line 6353 of
https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py shows, it
does the check for tolerance mentioned above.  I'm not sure whether the
feature to power_divergence was added after my note.
So if the code works as expected, the above check on the relative_diff in
power_divergence should stop the error.  If I wasn't getting it originally,
does that mean that the check on the tolerance was added afterwards?

**Comment by mdhaber** [comment] 2021-01-25 05:55
> If I wasn't getting it originally, does that mean that the check on the tolerance was added afterwards?

Yes, we added the check on the tolerance in response to your issue gh-12282. 

If we're still in agreement that this is the right thing to do, we should add that language about the tolerance to `chisquare`

**Comment by sam-data-guy** [comment] 2021-01-25 10:44
Sounds like a good idea.

**Comment by bashtage** [comment] 2021-02-24 13:12
> "Also, the sum of the observed and expected frequencies must be the same for the test to be valid;

The problem with this statement is that validity is only something that one can assert under the null, not the alternative. This doesn't require that the number of observations is identical when the null is false. 

> do you still think this behavior is wrong, or do you think it is more appropriate to update the test in `statsmodels`?

I think the tolerance check is fundamentally wrong, at least as an Exception. A warning that the data likely doesn't satisfy something the user intended seems like a much more reasonable approach since determining criteria for "validity" are only relevant under the null hypothesis, where this could not be the case.

**Comment by bashtage** [comment] 2021-02-24 13:15
I would not suggest altering the users' inputs either.  Just a warning that the inputs do not satisfy the usual condition that they should sum to the same within some tolerance.

**Comment by sam-data-guy** [comment] 2021-02-24 14:04
" The problem with this statement is that validity is only something that
one can assert under the null, not the alternative."
Your statement doesn't make sense to me. Validity of inputs is something
that has to do with the test, not whether the null or alternative
hypotheses are true.  Validity has to do with the requirements/assumptions
of the test, not with how likely the values are to occu.  For instance, all
the observed and expected values have to be non-negative as well.  This is
an input requirement.  It's true that one or the other may be true, but
inputs need to be valid in order to conduct the test and return a result
that makes sense.  The chi square test determines something about how
likely the observed frequencies are to have have happened given the
expected ones.  As I showed before, if the observed are rescaled by a
constant, the resulting p-value is different.  If you check at
https://en.wikipedia.org/wiki/Chi-squared_test, where x_i are the observed
and m_i are expected, they have to sum to the same.  That is simply a
requirement of the test.

**Comment by bashtage** [comment] 2021-02-24 14:13
> Your statement doesn't make sense to me. Validity of inputs is something that has to do with the test, not whether the null or alternative hypotheses are true.

This is not true in frequentist hypothesis testing (in general).  The hypothesis testing procedure, including the sampling distribution, has its properties determined when the null hypothesis is true.  In almost all cases that use an asymptotic distribution (as is the case here), the behavior under the alternative is not specified other than a statement that the statistic diverges when the null is not true (i.e., the test is consistent) as the sample size increases.

>   Validity has to do with the requirements/assumptions of the test, not with how likely the values are to occu. 

The requirements of the test are determined when the null is true, and so only need to hold when the null holds. 

>   The chi square test determines something about how likely the observed frequencies are to have have happened given the expected ones.

I agree with this, and it only has a chi-square distribution when both the same sizes and probabilities of each category are equal.  If either of these two conditions are not satisfied, then the statistic does not have a chi-square (which is perfectly fine and expected)

>  As I showed before, if the observed are rescaled by a constant, the resulting p-value is different. 

Of course. These are different points under the alternative, and so should not have the same p-value.  

> That is simply a requirement of the test.

It is a requirement under the null. If when null is false, they don't have to be the same.

**Comment by sam-data-guy** [comment] 2021-02-24 14:26
" It is a requirement under the null. If when null is false, they don't
have to be the same."  ---Again, this statement doesn't make sense.  The
function is conducting the frequentist statistical test.  The property we
are talking about, that is, that the values have to sum to the same, is
about what are the valid inputs.  Yes, of course the distribution of values
in the observed does not have to follow the distribution specified by the
null.  But it DOES have to have valid values to compare to what would be
true under the null.  You might as well say it can have a different number
of entries (which it can't) and say it doesn't have to be the same
distribution.  When you say the distribution can differ from the null, this
is in terms of the underlying proportions in each category differing from
those expected (that is, the null).  But the totals have to be the same.

**Comment by bashtage** [comment] 2021-02-24 14:36
> Again, this statement doesn't make sense.  The
function is conducting the frequentist statistical test.  The property we
are talking about, that is, that the values have to sum to the same, is
about what are the valid inputs.  

The test is whether two sequences are equal.  That is it.  

> But it DOES have to have valid values to compare to what would be
true under the null.  You might as well say it can have a different number
of entries (which it can't) and say it doesn't have to be the same
distribution. 

If it has a different number of entries then presumable the p-value should be 0 since the null cannot be true.

>   When you say the distribution can differ from the null, this
is in terms of the underlying proportions in each category differing from
those expected (that is, the null).

The Pearson test is in a joint test that the number of observations is the same and the probabilities are identical.  If you take a sequence where p_i is the same for both O and E but the number of N_O/N_E -> lambda != 1 then the test statistic diverges.  If you set N_O/N_E = 1 and let p_O_i != p_E_i for some i, then the test diverges.  It is consistent against either violation.  It only has a chi-square distribution when both N_O/N_E=1 and p_O_i = p_E_i for all i. This is precisely the reason why it should be allowed to have N_O != N_E.

**Comment by josef-pkt** [comment] 2021-02-24 14:42
In the traditional interpretation of the test it compares distributions, but the computation just compares counts.
E,g, in the failing test case in statsmodels I was comparing expected versus truncated counts, where the truncation probability was 1e-4 or something like that. 
I was just being lazy when writing the unit test, but the null hypothesis was not rejected, the truncated counts where still close enough to expected counts.

The main point is that either an exception or a warning prevents user error.
A few days ago, I made a mistake with numpy multinomial using cdf instead of pmf, and because of the exception I found the mistake right away.

**Comment by sam-data-guy** [comment] 2021-02-24 16:30
" If it has a different number of entries then presumable the p-value
should be 0 since the null cannot be true."
No, again.  If you give two inputs that are incompatible from the point of
view of the test, and you return a p-value, this implies that the test was
performed correctly (i.e., with compatible inputs) and that the p-value
actually means the value 0.  If the inputs are incompatible, the test
cannot be conducted.  A p-value of 0 implies a probability of 0, which is
not the correct thing to return.  This is particularly true because you
ALSO return a test statistic.  Now, you can't say that the test statistic
has any meaning if the inputs are incompatible, and therefore the p-value
calculated from it is meaningless and not 0-value; for instance, you can
have two different (illegal) test statistics which would have the same
p-value of 0 (because the inputs are incompatible), which is nonsensical
since two nonequal statistics can't (exactly) the same p-value in this
case.  So the p-value is not a real probability.

Just curious, it seems to me like you guys are still debating what to even
do about this---Kevin seems to think it works fine.  What is still the
debate?

**Comment by josef-pkt** [comment] 2021-06-27 19:22
I'm closing this. I think the issue is settled.

A tight tolerance prevents us from ignoring negligible (1e-5) terms and so it is more work.

But I had again a case where I used the wrong variable, and with the exception I found the mistake much faster.
I guess almost all cases where the counts don't add up to the same number are either sloppy (at larger tolerance) or user mistakes, so the exception is useful. (even if rejection of the null hypothesis could be justified by unequal count sums)

**Closed** 2021-06-27 19:23 UTC
Labels: scipy.stats

**Comment by mysticaltech** [comment] 2022-02-07 14:06
Folks, for instance, for this `stats.chisquare([214598,241153],[227877,227877])`, both vectors sum up to 455754, but I get this error: 

```
For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
6.582541782683966e-06
```

Please find a way, as that's a bug, not a feature!

**Comment by sam-data-guy** [comment] 2022-02-07 15:26
Actually the first sums to 455751, the other sums to 455754, hence the
error.

**Comment by sam-data-guy** [comment] 2022-02-07 15:29
> Folks, for instance, for this `stats.chisquare([214598,241153],[227877,227877])`, both vectors sum up to 455754, but I get this error:
> 
> ```
> For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
> 6.582541782683966e-06
> ```
> 
> Please find a way, as that's a bug, not a feature!

Actually the first sums to 455751, the other sums to 455754, hence the
error.

**Comment by mysticaltech** [comment] 2022-02-07 20:29
Indeed, I do not know how that happened, because doubled checked 🤯, you are right, thanks for catching it.

**Comment by mdhaber** [comment] 2022-11-08 04:09
Please consider opening a PR to fix the referenced package, instead. Please see the discussion in gh-12282, which demonstrates that the `chisquare` test does not provide a meaningful p-value when the observed and expected number of observations do not match.

**Comment by kvak** [comment] 2022-11-08 07:56
What is said in that discussion is not in general correct. It's wrong in the context of non parametric statistics. Look at page 143 of (Elements of Simulation, Byron J.T. Morgan) ( https://books.google.cz/books?id=EIbxfCGfzgcC&lpg=PP1&pg=PA143#v=onepage&q&f=false ) where the expected and realized counts don't sum to the same thing.

**Comment by mdhaber** [comment] 2022-11-08 15:13
@kvak he said

> If it has a different number of entries then presumable the p-value should be 0 since the null cannot be true

I can get behind that. Is this what you want the behavior of `chisquare` to be? It was not before this error was raised.

**Comment by kvak** [comment] 2022-11-08 15:43
@mdhaber  not really. The null can never be true, but anyway the problem is not with the number of entries, it's with the sum of the entries.

**Comment by mdhaber** [comment] 2022-11-08 15:46
OK, could you also reply to the question above it? 

> In the meantime, can you tell me the null hypothesis of the `gap_test` there? Is it that digits are IID samples from a discrete uniform on `[0, 1]` (i.e. Bernoulli trials with $p=0.5$)? I tried generating samples from that null hypothesis, and the distribution of test p-values was not uniform.

**Comment by josef-pkt** [comment] 2022-11-08 17:16
A guess based on a quick code check

The skidmarks.gap_test function truncates the array of expected observations.
So, AFAICS, egaps should not add up to one

```
    egaps = [l * (exp ** ii) for ii in range(1, len(ogaps) + 1)]
    chi, pval = chisquare(np.array(ogaps), np.array(egaps))
```

In statsmodels I had a similar problem. I truncated expected counts eg. for poisson, which was negligible before the change in scipy and raised after for some cases.
My fix, AFAIR, was to add the missing probability to the last count, which also makes sense for chisquare test if truncation is even of a nonnegligible amount.

Also chisquare test requires that expected count in each cell is large enough. So relying on tiny cells is not good for pvalues either.

**Comment by josef-pkt** [comment] 2022-11-08 17:22
I kind of like the exception. The transition as a bugfix was a bit abrupt.

However, it not only prevents bugs but also sloppy coding (even if those are in some cases negligible)

**Comment by kvak** [comment] 2022-11-08 17:54
> A guess based on a quick code check
> 
> The skidmarks.gap_test function truncates the array of expected observations. So, AFAICS, egaps should not add up to one
> 
> ```
>     egaps = [l * (exp ** ii) for ii in range(1, len(ogaps) + 1)]
>     chi, pval = chisquare(np.array(ogaps), np.array(egaps))
> ```
> 
> In statsmodels I had a similar problem. I truncated expected counts eg. for poisson, which was negligible before the change in scipy and raised after for some cases. My fix, AFAIR, was to add the missing probability to the last count, which also makes sense for chisquare test if truncation is even of a nonnegligible amount.
> 
> Also chisquare test requires that expected count in each cell is large enough. So relying on tiny cells is not good for pvalues either.

I can only speak for the gap test in skidmarks. This is how I solved it internally by patching the code. But that's not a solution. The original function was giving the same result as the book example. That way it won't. Tho it will "Klose enuf" on that example, whose to say it won't be wrong on some other book example. And then how do you ascertain what  implementation is correct?

**Comment by kvak** [comment] 2022-11-08 17:56
> I kind of like the exception. The transition as a bugfix was a bit abrupt.
> 
> However, it not only prevents bugs but also sloppy coding (even if those are in some cases negligible)

sure, always a good motivation, but at what cost? Now we have a function that won't return the correct (hand calculated) values 
from the example on the package's demo page. Perhaps, on this occasion, the desire for preventing sloppy coding has gone a bit too far? Maybe a warning would have hit that sweet middle ground?

**Comment by rkern** [comment] 2022-11-08 18:28
Your implementation is just incorrect. Even in the book that you cite, it deals with the truncation. I also think you are missing a `(1-exp)` term. See the section on the Gap test in Knuth's _Seminumerical Algorithms_, probably the most authoritative source, for the correct formulae.
