### ISSUE TITLE
fourier_uniform returning strange result

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#9195] opened 2018-08-31 01:00 UTC
When running `fourier_uniform` from SciPy's `ndimage`, seem to be getting an inaccurate result with SciPy 1.0.0+. The problem is not present in SciPy pre-1.0.0 (e.g. 0.19.1).

### Reproducing code example:

From SciPy 0.19.1:

```python
In [1]: import numpy as np

In [2]: import scipy.ndimage as spimg

In [3]: spimg.fourier_uniform(np.arange(5, dtype=float), 1)
Out[3]: array([ 0.        ,  0.93548928,  1.51365346,  2.27048019,  3.74195714])
```

From SciPy 1.1.0:

```python
In [1]: import numpy as np

In [2]: import scipy.ndimage as spimg

In [3]: spimg.fourier_uniform(np.arange(5, dtype=float), 1)
Out[3]: 
array([0.00000000e+000, 5.25819693e-315, 5.28483274e-315, 5.31059453e-315,
       5.34108739e-315])
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.1 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by jakirkham** [comment] 2018-08-31 01:13
Interestingly this problem does not exist for `np.float32`.

**Comment by WarrenWeckesser** [comment] 2018-08-31 01:35
Thanks for reporting the problem.

Looks like the bug is here: https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_fourier.c#L427
The second argument of that macro should be `npy_double`.

I'll prepare a pull request with a fix.

**Comment by WarrenWeckesser** [comment] 2018-08-31 01:41
Closing this as a duplicate of the `fourier_gaussian` bug.

**Closed by WarrenWeckesser** 2018-08-31 01:41 UTC
Labels: defect, duplicate, scipy.ndimage
