### ISSUE TITLE
issue with gamma.fit() and automatic start-values

### ISSUE THREAD

**Issue by raphaelquast** [scipy/scipy#10212] opened 2019-05-23 14:32 UTC
I've recognized a rather strange behaviour of `gamma.fit()` with my dataset:

Using the automatically evaluated start-value the fit fails completely....
however, using almost any other start-value the fit works perfectly!

I can't really determine what's happening here and where the issue might come from.

... digging a bit more into the issue, I've realized that using `data = data[:65093]` causes the fit to perform correctly while `data = data[:65094]` causes the fit to fail... the additional (single!!) value is `0.0418202979878212` which is not an outlier or so...

I've added my dataset as well as  the code to reproduce the issue:
here's the data: [data.zip](https://github.com/scipy/scipy/files/3212202/data.zip)

![Figure_1](https://user-images.githubusercontent.com/22773387/58261229-33caff80-7d78-11e9-8207-968a1efebbe3.png)

### Reproducing code example:
```
import numpy as np
from scipy.stats import gamma
import matplotlib.pyplot as plt

data_path = 'PATH TO data.csv'

data = np.genfromtxt(data_path, 
              skip_header=1, usecols=1, delimiter=',')

alpha_start_auto = gamma._fitstart(data)[0]

alpha_starts = [0, 1, 1.2, 1.28, 1.3, 1.5, 2]

f, ax = plt.subplots(figsize=(10,6))
# plot histogram
ax.hist(data, density=True, bins=100, cumulative=False, color='k', alpha=0.25, label='')
ax.hist(data, density=True, bins=100, cumulative=False, color='k', histtype='step', label='')
# store y-limits to avoid stupid plot-limits due to very high values of the fitted pdf
ylimits = ax.get_ylim() 

for i, [startvals, label] in enumerate(zip([[]] + [[i] for i in alpha_starts], 
                                [rf'automatic $\alpha$ = {alpha_start_auto:.4f}',
                                 *[rf'fixed         $\alpha$ = {i:.4f}' for i in alpha_starts]
                                 ])):

    fit_alpha, fit_loc, fit_scale = gamma.fit(data, *startvals)
    
    ax.plot(np.linspace(data.min(), data.max(), 1000), 
            gamma.pdf(np.linspace(data.min(), data.max(), 1000), 
                      fit_alpha, loc=fit_loc, scale=fit_scale),
            label = label + rf'  || FIT:  $\alpha$={fit_alpha:.2f}, loc={fit_loc:.2f}, scale={fit_scale:.2f}',
            lw=len(alpha_starts) + 1 - i)
    # reset y-limits
    ax.set_ylim(ylimits)
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

1.2.1 1.16.3 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment] 2019-05-23 23:27
Thanks for reporting the problem, and for providing a detailed description along with data that can be used to reproduce the problem.  I can reproduce the problem with the master development branch.  I haven't looked into what the cause might be yet, but I agree, it *is* strange!

**Comment by raphaelquast** [comment] 2019-05-24 11:47
Hey, thanks for the reply (and good to know that an upgrade to scipy v 1.3 is not going to solve this...)
If I find some more clues to what's happening here, I'll let you know!

**Comment by mdhaber** [comment] 2020-12-12 00:18
I think the problem is that the data is not actually distributed according to the gamma distribution, and that's just causing the optimizer to choke.

The `_fitstart` method of `gamma` is overridden based on the fact that the skewness of a gamma distribution is `2 / sqrt(a)`: `_fitstart` chooses `a = 4 / (1e-8 + _skew(data)**2)` (where the `1e-8` is to deal with degenerate data). 

At first, I wondered whether the author of that code made a mistake`*` (see footnote). For instance, perhaps `_skew` was not the right function to call. (I get confused about central vs noncentral moments, etc..., in SciPy.) But I generated data for a gamma distribution with known `a`, and then tried to fit the data, and the formula `a = 4 / (1e-8 + _skew(data)**2)` was very close to the the value of `a` from which the data were generated. So I think that code is right.

Here are some observations that suggest that the data are not gamma distributed.

Observation 1:
As you noted, you can successfully fit your data using almost any other guess of `a`, and it looks like this:
![image](https://user-images.githubusercontent.com/6570539/101965401-5eceab80-3bc9-11eb-9f1f-ebf9c890e705.png)

If you measure the skewness of the fitted gamma distribution, or if you generate random data from the fitted distribution and measure the skew, it does not match the skew of your original data:
```
fit_alpha, fit_loc, fit_scale = gamma.fit(data, 0)
g = gamma(fit_alpha, fit_loc, fit_scale)
data2 = g.rvs(size=len(data))
print(skew(data))
print(skew(data2))
print(g.stats(moments='s'))
```
```
1.7674055695288915
0.8464624612202976
0.8417291391291958
```
So the fit is not really that good.

Observation 2:
I tried fixing `alpha` to match the skew of your data, and the fit looks pretty bad:
```
falpha = 4/skew(data)**2
fit_alpha, fit_loc, fit_scale = gamma.fit(data, f0=falpha)
g = gamma(fit_alpha, fit_loc, fit_scale)
x = np.linspace(data.min(), data.max(), 1000)
pdf = g.pdf(x)
ax.plot(x, pdf)
data2 = g.rvs(size=len(data))
print(skew(data))
print(skew(data2))
print(g.stats(moments='s'))
```
Here's the console output:
```
1.7674055695288915
1.720015944208805
1.7674055695288915
```
and here's the plot:
![image](https://user-images.githubusercontent.com/6570539/101965602-254a7000-3bca-11eb-888f-5ec017c09b02.png)

Observation 3:
```
> len(data)
69120
```
We should be getting a _lot_ better fit than the plot above if the data is really distributed according to the gamma distribution. If we generate that many data points from the fitted gamma distribution, the histogram (red) matches the fitted distribution much better.

![image](https://user-images.githubusercontent.com/6570539/101965807-bf121d00-3bca-11eb-8764-cea16aa80782.png)

So I don't think we have a SciPy bug here; we're just having trouble forcing a round peg in a square hole. It would be nice if we could guarantee that the optimizer would converge to a reasonable-looking result for arbitrary combinations of distributions and data, but numerical optimization just isn't perfect. In some cases, maybe it's better if it doesn't fit nicely - it might be telling us something about the data!

Thanks for reporting the issue; it was interesting to look into! Do you agree we can close this, or would you like to see some other change to SciPy to address this?

---
`*` They did make a small typo: they wrote "The skewness of the gamma distribution is `4 / np.sqrt(a)`", but they meant `4 / np.sqrt(a)`. The code is correct, though.

**Comment by WarrenWeckesser** [comment] 2020-12-22 17:26
I agree with @mdhaber; it looks like the default initial guess that is passed to the numerical optimizer just doesn't work for this data set.  For initial guesses near 1.28, the solver appears to end up pushing the `loc` parameter very close to the lower value of the input data, which means it is probably hitting a lot of cases where the objective function penalty kicks in (i.e . when the `loc` parameter exceeds the minimum value of the data).

As an experiment, I used the `optimizer` argument to try a couple different optimizers.  Using `fmin_bfgs` also failed, but `fmin_powell` converged.

While we can't guarantee convergence, it would be nice if the method could detect the bad result and raise an exception or warning, and/or provide some additional information that could be used to assess the quality of the result.  @mdhaber and I have talked about this, and something like this might end up in `fit` eventually.

**Comment by mdhaber** [comment] 2021-01-09 19:34
I'll go ahead and close this since it does not indicate a problem with `gamma`'s fit-start. There are many improvements to be made to `fit`, but I don't think we need this issue to remind us. Thanks for reporting @raphaelquast, as it is definitely an undesirable behavior, but it's more of a shortcoming of the algorithms than a fixable bug. Please re-open if we've missed something!

**Closed by mdhaber** 2021-01-09 19:34 UTC
Labels: defect, scipy.stats

**Comment by raphaelquast** [comment] 2021-01-11 08:57
@mdhaber 
sorry for not responding in time!  (i was quite busy recently...)

I agree that this does not seem as a real "fixable bug", but it serves well as a worst-case example to remind users to be cautious when trusting automated fit-procedures... 

Thank's a lot for having a detailed look into this!
