### ISSUE TITLE
Problems with scipy's optimize

### ISSUE THREAD

**Issue by Mike-HubGit** [scipy/scipy#12075] opened 2020-05-09 21:27 UTC
I have a random bug with scipy's optimize . I use it in the context of SageMath 9 (Python 3.7.3). I checked 3 algorithms : shgo, dual_annealing and full_optimize. All don't work well (at all !).

I optimise with a 3 parameters functions with given bounds. The algorithm randomly sends to my error function the "1e-8" value for any of the 3 parameters. I displayed the vector + error to understand it. AS you can see, in this case, the first parameter is 1e-8 whereas it is outside the bounds. Sometimes it happens for the second parameter, or the 3rd .... Here is an example, I displayed the values. First the vector of parameters, then the error.
```

[3.95049282e-19 3.03055607e-20 1.96212098e+29] 0.0030238733573031864
[3.95273920e-19 3.05821352e-20 1.90997635e+29] 0.002957956545311753
[3.95037412e-19 3.04080173e-20 1.93312145e+29] 0.0029572689364709224
sage.all_cmdline:33: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
[1.00000000e-08 3.04080173e-20 1.93312145e+29] 1.0713560755245306
Overflow
[3.95037412e-19 3.04080173e-20 1.93312145e+29] 0.0029572689364709224
```
The behaviour is the same for all of them. However the value inserted is not always the same, I noticed 3 : 1e-10, 1e-8 and 1.49011612e-08

full_optimize works the "best" as this behaviour comes when the optimization has already workd for a while. For the two others methods it's ... awful ...

my bounds are :

> bounds = [(1*e,4*e),(0.1*e,0.5*e),(1e5,1e40)]

with e=1.6e-19

Is there an alternative for optimization in sagemath ?

regards, Mike

**Comment by mdhaber** [comment] 2020-05-09 21:44
@Mike-HubGit we'd be happy to assess whether this is a bug if you can include SciPy code that reproduces the issue. We don't provide support for SageMath here, though, even if it uses SciPy as a dependency. This is for bugs reports and feature requests for SciPy.

**Comment by Stefan-Endres** [comment] 2020-05-09 21:53
> e=1.6e-19

I don't think this problem is a bug with the solvers, but it is likely that you will need to play around with a lot of the tolerances of the solvers. As an example I will assume you used the default behaviour of shgo which calls [SLSQP](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-slsqp.html#optimize-minimize-slsqp) in the local minimisation step by default. The default step size used for numerical approximation of the Jacobian is 'eps' = 1.4901161193847656e-08 so that is probably why you get this value outside your bounds.

Try passing

```Python
minimizer_kwargs = {'eps': e * 1e-8, 
                    'ftol':  e * 1e-06}
```
or similar to [shgo](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.shgo.html) as well as modifying the tolerances of the other solvers.

**Comment by Mike-HubGit** [comment] 2020-05-09 22:10
Dear Stefan,

 thanks a lot ! I am however surprized, I believed these algorithms were based on random generation and could not give values outside the bounds. It does not work like genetic algorithm ? Is there a genetic algorithm somewhere in scipy ?
I have a very last question : is it possible to enable multiple processors computation of these optimizations ?
Thanks again, best regards,
   Mike

**Comment by Stefan-Endres** [comment] 2020-05-09 22:23
>I believed these algorithms were based on random generation and could not give values outside the bounds.

The sampling in the global optimization step can not sample outside the bounds. The issue is that the local minimization step (using a different sovler) that tries to compute a Jacobian step that is larger than your bounds. This can also be resolved by using for example a non-gradient descent local optimizer such as [Nelder-Mead](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-neldermead.html#optimize-minimize-neldermead). It is also possible third variable in your problem might also lead to floating point errors because the bounds for the first two variables are relatively small. It is likely that it will take some further work to find the right settings for solving your particular problem.

> Is there a genetic algorithm somewhere in scipy ?

The [differential evolution](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html) algorithm is purely stochastic. 

> is it possible to enable multiple processors computation of these optimizations ?

You can supply the `workers` argument to DE for this purpose (see the [documentation]((https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html) )). Not all algorithms support multiple processors yet.

**Comment by Mike-HubGit** [comment] 2020-05-09 22:39
I am sorry but ... I do not understand.
I read in the differential_evolution algorithm documentation :

> Differential Evolution is stochastic in nature (does not use gradient methods) to find the minimum, and can search large areas of candidate space, but often requires larger numbers of function evaluations than conventional gradient based techniques.

So there is no gradient estimation I guess ? Or do you say these algorithms combine two optimizations, one stochastic + one deterministic using for example a gradient ? That was not what I guessed when I displayed the values, I believed every evaluation was based on stochastic parameters. But I perhaps dit not understand the pattern.

The minimization methods you mention seem to work with the "minimize" function and not with the differential_evolution function, isn't it ? 
There are instead "strategies" but I think they are not described in the documentation.

Perhaps may I switch to the "minmize" function ?

I am sorry for all these questions ...

**Comment by Stefan-Endres** [comment] 2020-05-09 23:03
A deterministic algorithm does not always need to evaluate a gradient, but to try and keep it simple:

- Differential evolution: purely stochastic
- shgo: purely deterministic 

The two algorithms are both global optimisation algorithms, but only DE should be considered stochastic or a GA.

>The minimization methods you mention seem to work with the "minimize" function and not with the differential_evolution function, isn't it ?

Yes, they are for the local step in shgo which calls the `scipy.optimize.minimize` function. The shgo algorithm has 2 steps per iteration. The first step tries to understand the geometry of the global objective function surface and attempts to generate subproblems with locally unimodal sub-domains. In the second step these subproblems can then be solved using any of the the local `minimize` routines. These routines may, or may not, need to compute the gradient.

- shgo (with default settings): deterministic sampling _without_ computing gradients + deterministic  step using gradient 
- shgo (using a gradient free local solver): deterministic sampling _without_ computing gradient + deterministic step without using gradient

>There are instead "strategies" but I think they are not described in the documentation.

It is technically described, but the connection is very difficult to make since it relies on calling other functions documented on a separate page. It is more appropriate to describe this in an optimisation tutorial than the documentation. In general many deterministic global optimisation algorithms are hybrid algorithms and work very differently from GA.

>Perhaps may I switch to the "minmize" function ?

If you don't need the global minimum and/or more than one minima and/or your problem is convex/unimodal; yes. We can't really tell you which solver is the best solver without knowing more about your problem (solver selection in general is not an easy task), but either way I do not think this is the appropriate platform, the user mailing list might be more appropriate as this is not an issue with the code currently in scipy.

**Comment by Mike-HubGit** [comment] 2020-05-09 23:15
Thanks Stefan, again ...

However, I still do not understand why, when using a pure _stochastic algorithm_, It can feed my function with values outside the bounds : differential_evolution sends me, when the optimization has enougth advanced, values outside the bounds, randomly on one or another variable. Is this normal ? 

Thanks again,
   Mike

**Comment by andyfaff** [comment] 2020-05-09 23:21
I'd be surprised if differential_evolution sends your objective function outside the bounds, unless it's at the polishing stage at the end (polish=True).
Please send a minimal working example that can reproduce the problem.

**Comment by Mike-HubGit** [comment] 2020-05-09 23:43
Dear Andyfaff,
  you are right ! the problem was polish=True. with polish=False everything is ok (I tested 4 times and no problem). 
  Very Nice ! So finally, by default, the Differential_Evolution algorithm is not fully stochastic ;-)
Thanks a lot,
   Mike
P.S. : Problem solved.

**Comment by andyfaff** [comment] 2020-05-09 23:46
In the last stage DE uses `minimize` to get to the very best possible location. The default method for that polish step is LBFGSB. If the bounds are so tight I can imagine there may be problems.

**Closed** 2020-05-09 23:46 UTC
