### ISSUE TITLE
scipy.stats.spearmanr p-value issue with very large matrices

### ISSUE THREAD

**Issue by medmaca** [scipy/scipy#4221] opened 2014-12-02 15:01 UTC
It appears that scipy.stats.spearmanr can only cope with matrices up to 15,968 in length, anything above this results in correct rho values but zeros for the p-values in all following rows.

**Comment by rgommers** [comment] 2018-09-02 03:46
Still getting `MemoryError` for 
```
n = 16000
x2 = np.random.randn(n, n)
res = stats.spearmanr(x2, x2)
```
on a machine with close to 64 GB RAM. The problem is very likely fixed though, with the rewrite of `tiecorrect` (gh-5554) that fixed `rankdata` which is used in `spearmanr`. So I'll close this.

**Closed by rgommers** 2018-09-02 03:46 UTC
Labels: defect, scipy.stats
