### ISSUE TITLE
BUG: test failures on aarch in wheel builder repo

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15051] opened 2021-11-17 06:37 UTC
The aarch builds on https://github.com/MacPython/scipy-wheels have two failures currently:

```
=========================== short test summary info ============================
FAILED optimize/tests/test_optimize.py::test_equal_bounds[callback-constraints0-<lambda>-kwds0-TNC]
FAILED optimize/tests/test_optimize.py::test_equal_bounds[callback-constraints1-<lambda>-kwds0-TNC]
XPASS optimize/tests/test_optimize.py::TestOptimizeWrapperDisp::test_powell_gh14014 This part of test_powell fails on some platforms, but the solution returned by powell is still valid.
XPASS optimize/tests/test_optimize.py::TestOptimizeWrapperNoDisp::test_powell_gh14014 This part of test_powell fails on some platforms, but the solution returned by powell is still valid.
XPASS optimize/tests/test_optimize.py::TestOptimizeNoWrapperDisp::test_powell_gh14014 This part of test_powell fails on some platforms, but the solution returned by powell is still valid.
XPASS optimize/tests/test_optimize.py::TestOptimizeNoWrapperNoDisp::test_powell_gh14014 This part of test_powell fails on some platforms, but the solution returned by powell is still valid.
XPASS optimize/tests/test_linprog.py::TestLinprogIPSparse::test_bug_6690 Fails with ATLAS, see gh-7877
XPASS optimize/tests/test_linprog.py::TestLinprogIPSparsePresolve::test_bug_6690 Fails with ATLAS, see gh-7877
XPASS linalg/tests/test_matfuncs.py::TestFractionalMatrixPower::test_singular Too unstable across LAPACKs.
XPASS linalg/tests/test_solve_toeplitz.py::test_unstable Instability of Levinson iteration
XPASS special/tests/test_basic.py::TestCephes::test_fdtri_mysterious_failure Returns nan on i686.
= 2 failed, 33683 passed, 2515 skipped, 101 xfailed, 9 xpassed, 59 warnings in 836.82s (0:13:56) =
```

E.g. this [build](https://app.travis-ci.com/github/MacPython/scipy-wheels/builds/241742976) from master (though happening also in more recent PRs).

<details>

```
=================================== FAILURES ===================================
_________ test_equal_bounds[callback-constraints0-<lambda>-kwds0-TNC] __________
[gw7] linux -- Python 3.10.0 /venv/bin/python
/venv/lib/python3.10/site-packages/scipy/optimize/tests/test_optimize.py:2495: in test_equal_bounds
    assert_allclose(res.fun, fd_res.fun)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 0.00015936
E   Max relative difference: 1.23582398e-07
E    x: array(1289.475255)
E    y: array(1289.475414)
        bound_type = <function setup_test_equal_bounds.<locals>.<lambda> at 0xffff79d927a0>
        bounds     = [(0.0, 3.0), (2.0, 2.0), (-1.0, 2.0), (-1.0, -1.0)]
        callback   = <function setup_test_equal_bounds.<locals>.callback at 0xffff79d92440>
        constraints = (None, None)
        expected   =      fun: 1289.4752548690583
     jac: array([-1.75951145e-05,             nan,  4.24487110e-05,             nan])
 me...  nfev: 19
     nit: 7
  status: 1
 success: True
       x: array([ 1.41369615,  2.        ,  0.87977221, -1.        ])
        fd_needed  = False
        fd_res     =      fun: 1289.4754142650613
     jac: array([ 0.46138667, -0.53325948])
 message: 'Converged (|f_n-f_(n-1)| ~= 0)'
    nfev: 108
     nit: 9
  status: 1
 success: True
       x: array([1.41398439, 0.87942374])
        fun        = <function test_equal_bounds.<locals>.fun at 0xffff7054feb0>
        i_eb       = array([False,  True, False,  True])
        kwds       = {'bounds': [(0.0, 3.0), (2.0, 2.0), (-1.0, 2.0), (-1.0, -1.0)], 'callback': <function setup_test_equal_bounds.<locals>...t 0xffff79d92440>, 'constraints': None, 'fun': <function setup_test_equal_bounds.<locals>.func at 0xffff79d92320>, ...}
        lb         = array([ 0.,  2., -1., -1.])
        method     = 'TNC'
        reference_constraints = None
        res        =      fun: 1289.4752549085974
     jac: array([-0.00122782,         nan, -0.01091394,         nan])
 message: 'Converge...nfev: 156
     nit: 10
  status: 1
 success: True
       x: array([ 1.4136954 ,  2.        ,  0.87976504, -1.        ])
        test_constraints = None
        ub         = array([ 3.,  2.,  2., -1.])
        x0         = array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])
_________ test_equal_bounds[callback-constraints1-<lambda>-kwds0-TNC] __________
[gw7] linux -- Python 3.10.0 /venv/bin/python
/venv/lib/python3.10/site-packages/scipy/optimize/tests/test_optimize.py:2495: in test_equal_bounds
    assert_allclose(res.fun, fd_res.fun)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 0.00015936
E   Max relative difference: 1.23582398e-07
E    x: array(1289.475255)
E    y: array(1289.475414)
        bound_type = <function setup_test_equal_bounds.<locals>.<lambda> at 0xffff79d927a0>
        bounds     = [(0.0, 3.0), (2.0, 2.0), (-1.0, 2.0), (-1.0, -1.0)]
        callback   = <function setup_test_equal_bounds.<locals>.callback at 0xffff79d92440>
        constraints = ([], [])
        expected   =      fun: 1289.4752548690583
     jac: array([-1.75951145e-05,             nan,  4.24487110e-05,             nan])
 me...  nfev: 19
     nit: 7
  status: 1
 success: True
       x: array([ 1.41369615,  2.        ,  0.87977221, -1.        ])
        fd_needed  = False
        fd_res     =      fun: 1289.4754142650613
     jac: array([ 0.46138667, -0.53325948])
 message: 'Converged (|f_n-f_(n-1)| ~= 0)'
    nfev: 108
     nit: 9
  status: 1
 success: True
       x: array([1.41398439, 0.87942374])
        fun        = <function test_equal_bounds.<locals>.fun at 0xffff7054fac0>
        i_eb       = array([False,  True, False,  True])
        kwds       = {'bounds': [(0.0, 3.0), (2.0, 2.0), (-1.0, 2.0), (-1.0, -1.0)], 'callback': <function setup_test_equal_bounds.<locals>... at 0xffff79d92440>, 'constraints': [], 'fun': <function setup_test_equal_bounds.<locals>.func at 0xffff79d92320>, ...}
        lb         = array([ 0.,  2., -1., -1.])
        method     = 'TNC'
        reference_constraints = []
        res        =      fun: 1289.4752549085974
     jac: array([-0.00122782,         nan, -0.01091394,         nan])
 message: 'Converge...nfev: 156
     nit: 10
  status: 1
 success: True
       x: array([ 1.4136954 ,  2.        ,  0.87976504, -1.        ])
        test_constraints = []
        ub         = array([ 3.,  2.,  2., -1.])
        x0         = array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])
```

</details>

**Comment by h-vetinari** [comment] 2021-11-17 06:41
It's basically a (relative) tolerance violation by three orders of magnitude (~1e-4 instead of 1e-7), but I would still propose to just skip this test on aarch. CC @rgommers @tylerjereddy

**Comment by andyfaff** [comment] 2021-11-17 06:44
I think this will be due to #14879, and should be fixed by #14882

**Comment by andyfaff** [comment] 2021-11-17 06:45
Rather than just skip the test I would suggest we review and merge the PR, then see if the problem is fixed.

**Comment by h-vetinari** [comment] 2021-11-17 06:47
Sure, if there's a proposed fix, that's great! :)

**Comment by h-vetinari** [comment] 2021-11-17 06:49
> 
> 
> Rather than just skip the test I would suggest we review and merge the PR, then see if the problem is fixed.

I don't see though how #14882 should be aarch-specific? I mean yes, if a general refactor of that module fixes it great, but not sure how long that review process is going to take, and whether it's feasible before 1.8.0?

**Comment by rgommers** [comment] 2021-11-17 07:06
Seems fine to me to add a skip in master now, and remove it again in your PR @andyfaff

**Comment by andyfaff** [comment] 2021-11-17 09:37
It should definitely be feasible to include it by 1.8.0, but perhaps a skip now is better, and I can remove it later.

An aside, how do we keep track of the test skips/knownfails that we need to undo in the future?

The TNC callback has bad side effects. In order to call back to Python it [unscales x, sends x to the callback, then scales x](https://github.com/scipy/scipy/blob/master/scipy/optimize/tnc/tnc.c#L800). Unfortunately the unscale/scale round trip does not result in an `x` that is unchanged. The fix that I applied was to copy x to a temp array, unscale the temp array and send the temp array to the callback.  With the [scale](https://github.com/scipy/scipy/blob/master/scipy/optimize/tnc/tnc.c#L459)/[unscale](https://github.com/scipy/scipy/blob/master/scipy/optimize/tnc/tnc.c#L449) function there's plenty of potential for there to be arch specific FP issues. The reason I think it's due to #14882 is because the failing test is parameterised to run a TNC minimisation with and without the callback. It only fails when it's run with the callback.

**Comment by rgommers** [comment] 2021-11-20 11:20
> An aside, how do we keep track of the test skips/knownfails that we need to undo in the future?

We can either leave the issue open with a milestone set to ensure we revisit it, or comment on the related PR (in this case you have an open PR that may fix it, so let's do that).

**Closed** 2021-11-20 11:22 UTC
Labels: defect
