### ISSUE TITLE
FAIL/ERROR: test_syr_her (test_blas.TestFBLAS2Simple) linked with OpenBLAS on Ubuntu 14.04.1 Server, python 2.7.9, scipy0.15.1, numpy0.19.1

### ISSUE THREAD

**Issue by zym1010** [scipy/scipy#4453] opened 2015-01-22 04:45 UTC
The python 2.7.9 (along with pip) is installed by creating a conda environment (say, `conda create -n testenv python pip`). To compile scipy and numpy, I also installed cython using pip.

OpenBLAS is the 0.2.13 version downloaded from github, compiled with gfortran and default parameters, resulting in libopenblas_haswellp-r0.2.13.a and libopenblas_haswellp-r0.2.13.so (I guess this is pthread build?).

scipy0.15.1, numpy0.19.1 are downloaded from github, and manually compiled to link against my OpenBLAS (in ~/lib/OpenBLAS). numpy.\_\_config\_\_.show() shows:

```
import numpy
numpy.__config__.show()
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/yimengzh/lib/OpenBLAS/lib']
    language = f77
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/yimengzh/lib/OpenBLAS/lib']
    language = f77
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/yimengzh/lib/OpenBLAS/lib']
    language = f77
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/yimengzh/lib/OpenBLAS/lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
```
However, when I run scipy.test(), test_syr_her sometimes fails and sometimes errs. Attached are two possible outputs of python -c "import scipy; scipy.test()".

FIRST TIME:
```
======================================================================
ERROR: test_syr_her (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/scipy/linalg/tests/test_blas.py", line 316, in test_syr_her
    resz_reverse, rtol=rtol)
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/numpy/testing/utils.py", line 673, in assert_array_compare
    raise ValueError(msg)
ValueError:
error during assertion:
Traceback (most recent call last):
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    val = comparison(x[~x_id], y[~y_id])
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/numpy/testing/utils.py", line 1292, in compare
    return np.allclose(x, y, rtol=rtol, atol=atol)
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/numpy/core/numeric.py", line 2234, in allclose
    r = all(less_equal(abs(x - y), atol + rtol * abs(y)))
ValueError: operands could not be broadcast together with shapes (15,) (16,)
Not equal to tolerance rtol=1e-07, atol=0
 x: array([[  0. +0.000000e+00j,   0. +0.000000e+00j,   0. +0.000000e+00j,
          0. +0.000000e+00j],
       [  0. +0.000000e+00j,   0. +0.000000e+00j,   0. +0.000000e+00j,...
 y: array([[-15.+112.j, -13. +82.j, -11. +52.j,  -9. +22.j],
       [  0.  +0.j, -11. +60.j,  -9. +38.j,  -7. +16.j],
       [  0.  +0.j,   0.  +0.j,  -7. +24.j,  -5. +10.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j,  -3.  +4.j]])
----------------------------------------------------------------------
Ran 17000 tests in 130.046s
FAILED (KNOWNFAIL=97, SKIP=1205, errors=1)
```

SECOND TIME:

```
======================================================================
FAIL: test_syr_her (test_blas.TestFBLAS2Simple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/scipy/linalg/tests/test_blas.py", line 316, in test_syr_her
    resz_reverse, rtol=rtol)
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/yimengzh/anaconda/envs/theano_clean/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0
(mismatch 100.0%)
 x: array([[  0.000000e+00 +0.000000e+00j,   0.000000e+00 +0.000000e+00j,
          0.000000e+00 +0.000000e+00j,   0.000000e+00 +0.000000e+00j],
       [  0.000000e+00 +0.000000e+00j,   0.000000e+00 +0.000000e+00j,...
 y: array([[-15.+112.j, -13. +82.j, -11. +52.j,  -9. +22.j],
       [  0.  +0.j, -11. +60.j,  -9. +38.j,  -7. +16.j],
       [  0.  +0.j,   0.  +0.j,  -7. +24.j,  -5. +10.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j,  -3.  +4.j]])
----------------------------------------------------------------------
Ran 17000 tests in 124.205s
FAILED (KNOWNFAIL=97, SKIP=1205, failures=1)
```

However, when using the scipy and numpy from conda (linked against ATLAS statically), the test can be passed. I don't know what's wrong. Is it scipy, numpy, or OpenBLAS? Thanks.

**Comment by pv** [comment] 2015-01-22 09:29
OpenBLAS may be the most likely explanation.

Interestingly, both tests correspond to failures when c/zsyr is called with negative incx.
Maybe this does not work correctly in OpenBLAS? Writing a pure-fortran test code
might be useful, and if it fails, it's certainly an openblas issue.

**Comment by zym1010** [comment] 2015-01-22 14:26
@pv Thanks. So you suggest I simply translated the current test code for test_syr_her into another language (say fortran, but I guess I'm more comfortable with C) and link it against OpenBLAS again?

**Comment by pv** [comment] 2015-01-22 14:41
Yes --- if the problem is with openblas not dealing with negative incx, a simple C test case with *incx==-3 probably would reveal it, likely doesn't have to be exactly the same test as what we have.

**Comment by zym1010** [comment] 2015-01-23 21:40
@pv Indeed. I translated the test code for zsyr into C and called f77blas routines, and OpenBLAS gave me the wrong result (for negative incx), and ATLAS gave me the correct one. Maybe I should open an issue on OpenBLAS.

**Comment by pv** [comment] 2015-01-25 13:28
Ok, closing this issue --- needs to be fixed in openblas.

**Closed by pv** 2015-01-25 13:28 UTC
