### ISSUE TITLE
Overflow Error from binned_statistic_dd

### ISSUE THREAD

**Issue by KeironO** [scipy/scipy#9010] opened 2018-07-09 13:42 UTC
### Error message:
```
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-86-0811ef0d48f7> in <module>()
     16         sl = SpectrumList([x for x in spectrum_list if x.id in ids])
     17         print sl.tolist()
---> 18         sl_df = make_spectrumlist(sl)
     19 
     20         pls_df = pd.concat([sl_df, mtd["Diagnosis"]], axis=1).dropna(axis=0)

<ipython-input-63-51c201b1e4f9> in make_spectrumlist(sl)
      1 def make_spectrumlist(sl):
----> 2     sl.binning(bin_size=0.5, mass_statistic="max")
      3     sl.value_imputation(method="basic", threshold=0.1)
      4     sl.normalise(method="tic")
      5     sl.transform(method="log10")

/home/keo7/ProjectsNew/metabolomics/denisa-saliva/env/local/lib/python2.7/site-packages/dimepy/SpectrumList.pyc in binning(self, bin_size, int_statistic, mass_statistic, inplace)
    174 
    175         for spectrum in self._spectrum:
--> 176             bins, intensities = _apply_binning(spectrum, bins)
    177             if inplace:
    178                 spectrum.masses = bins

/home/keo7/ProjectsNew/metabolomics/denisa-saliva/env/local/lib/python2.7/site-packages/dimepy/SpectrumList.pyc in _apply_binning(spectrum, bins)
    160                 spectrum.intensities,
    161                 bins=bins,
--> 162                 statistic=int_statistic)
    163             indx = np.invert(np.isnan(b_i))
    164 

/home/keo7/ProjectsNew/metabolomics/denisa-saliva/env/local/lib/python2.7/site-packages/scipy/stats/_binned_statistic.pyc in binned_statistic(x, values, statistic, bins, range)
    177 
    178     medians, edges, binnumbers = binned_statistic_dd(
--> 179         [x], values, statistic, bins, range)
    180 
    181     return BinnedStatisticResult(medians, edges[0], binnumbers)

/home/keo7/ProjectsNew/metabolomics/denisa-saliva/env/local/lib/python2.7/site-packages/scipy/stats/_binned_statistic.pyc in binned_statistic_dd(sample, values, statistic, bins, range, expand_binnumbers)
    534     for i in xrange(Ndim):
    535         # Find the rounding precision
--> 536         decimal = int(-np.log10(dedges[i].min())) + 6
    537         # Find which points are on the rightmost edge.
    538         on_edge = np.where(np.around(sample[:, i], decimal) ==

OverflowError: cannot convert float infinity to integer
```

**Comment by rgommers** [comment] 2019-08-11 01:54
there have been fixes to `binned_statistic_dd` recently IIRC. this is not actionable without a standalone example that reproduces an issue. So I'll close this. If anyone has a reproducer with scipy 1.3.x or master, please comment and I'll reopen.

**Comment by rlucas7** [comment] 2019-08-12 02:00
Ralf, I think you’re referring to this PR? 

https://github.com/scipy/scipy/pull/10351

Tyler has marked it as 1.4.0 release. The recent 1.3.x release didn’t mention in release notes so not sure if it is there, it is in master branch.

**Comment by tylerjereddy** [comment] 2019-08-12 03:27
> Tyler has marked it as 1.4.0 release. The recent 1.3.x release didn’t mention in release notes so not sure if it is there, it is in master branch.

Hmm, I don't think it is in 1.3.1--there's no backport label on the PR & I haven't gone through to cleanup the labels yet. If you / Ralf feel that it should be backported we could add that label? I may need a little breather before doing a 1.3.2 though, if we need it.

**Comment by KeironO** [comment] 2019-08-12 07:19
I will test this sometime today.

Thank you,

Keiron

**Comment by rlucas7** [comment] 2019-08-12 14:03
I’m not sure what qualifies for backport vs a new release. Also not sure if this is impacting anyone currently.

Let’s see what Keiron, finds?

**Comment by rgommers** [comment] 2019-08-12 14:36
> I’m not sure what qualifies for backport vs a new release. 

important bug fixes only for backports. we usually decide at merge time if we do find something important, by adding a "backport-candidate" label.

we can always reopen this, but only if we have a reproducible example of something that fails

**Comment by rlucas7** [comment] 2019-08-13 02:16
Not the exact same message but if any input types are `np.inf` or `None` then I get a similar error when calling the function. I'd guess the issue here is input data that is resulting in one of the types that cause the above or similar. Not sure if SciPy code or not. Should we throw and error/exception in this case? (IIRC `nan_policy` still has some issues, cf.  https://github.com/scipy/scipy/issues/9815)

```
(scipy-dev) Lucass-MacBook:scipy rlucas$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import scipy.stats as ss
>>> w = np.random.random(100)
>>> u = np.random.random(100) + 1e6
>>> #no error
... res = ss.binned_statistic(u, w, 'std', bins=10)
>>> res
BinnedStatisticResult(statistic=array([0.26547547, 0.30319976, 0.28624087, 0.24237511, 0.33770664,
       0.27437196, 0.25342354, 0.1997773 , 0.17371537, 0.28025148]), bin_edges=array([1000000.0081482 , 1000000.10681714, 1000000.20548609,
       1000000.30415503, 1000000.40282397, 1000000.50149291,
       1000000.60016185, 1000000.69883079, 1000000.79749974,
       1000000.89616868, 1000000.99483762]), binnumber=array([ 5,  5,  7,  2, 10,  9, 10,  9, 10,  7,  3,  6,  1,  1,  7,  7,  8,
        3,  3,  3,  1,  7,  3,  8,  4,  2,  6,  8, 10, 10,  9,  1,  1,  7,
        8,  4,  3,  3,  5,  6,  7,  7,  3,  3,  6,  8,  2,  7,  5,  3,  5,
        2,  4,  4,  3,  6,  7,  1,  1, 10,  6,  1, 10,  2,  6,  2, 10,  1,
        6,  1,  5,  9,  8,  1,  1,  2,  1,  4, 10,  6,  8,  1,  4,  4, 10,
        7,  1,  2,  2,  6,  7,  4,  5, 10,  4,  5,  3,  5,  4, 10]))
>>> u[99]=np.inf
>>> #throws error
... res = ss.binned_statistic(u, w, 'std', bins=10)
/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/numpy/core/function_base.py:133: RuntimeWarning: invalid value encountered in multiply
  y *= step
/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/numpy/lib/function_base.py:1174: RuntimeWarning: invalid value encountered in subtract
  a = op(a[slice1], a[slice2])
/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_binned_statistic.py", line 181, in binned_statistic
    [x], values, statistic, bins, range)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_binned_statistic.py", line 583, in binned_statistic_dd
    decimal = int(-np.log10(dedges[i].min())) + 6
ValueError: cannot convert float NaN to integer
>>> w[99]=np.inf
>>> u[99]=u[98]
>>> #also throws error
... res = ss.binned_statistic(u, w, 'std', bins=10)
/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
>>> w[99]=w[98]
>>> u[99]=None
>>> #also throws error
... res = ss.binned_statistic(u, w, 'std', bins=10)
/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_binned_statistic.py", line 181, in binned_statistic
    [x], values, statistic, bins, range)
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_binned_statistic.py", line 583, in binned_statistic_dd
    decimal = int(-np.log10(dedges[i].min())) + 6
ValueError: cannot convert float NaN to integer
>>> u[99]=u[98]
>>> # now no error
... res = ss.binned_statistic(u, w, 'std', bins=10)
```

Interestingly `np.nan` does not yield similar results and it looks like the `np.nan` is propogated through the calculations.

```
w[99]=np.nan
res = ss.binned_statistic(u, w, 'std', bins=10)
>>> res
BinnedStatisticResult(statistic=array([0.26547547, 0.30319976, 0.28624087,        nan, 0.33770664,
       0.27437196, 0.25342354, 0.1997773 , 0.17371537, 0.27717484]), bin_edges=array([1000000.0081482 , 1000000.10681714, 1000000.20548609,
       1000000.30415503, 1000000.40282397, 1000000.50149291,
       1000000.60016185, 1000000.69883079, 1000000.79749974,
       1000000.89616868, 1000000.99483762]), binnumber=array([ 5,  5,  7,  2, 10,  9, 10,  9, 10,  7,  3,  6,  1,  1,  7,  7,  8,
        3,  3,  3,  1,  7,  3,  8,  4,  2,  6,  8, 10, 10,  9,  1,  1,  7,
        8,  4,  3,  3,  5,  6,  7,  7,  3,  3,  6,  8,  2,  7,  5,  3,  5,
        2,  4,  4,  3,  6,  7,  1,  1, 10,  6,  1, 10,  2,  6,  2, 10,  1,
        6,  1,  5,  9,  8,  1,  1,  2,  1,  4, 10,  6,  8,  1,  4,  4, 10,
        7,  1,  2,  2,  6,  7,  4,  5, 10,  4,  5,  3,  5,  4,  4]))
```
I'm happy to open a PR and add an exception if input contains non-finite values if we agree that is the best way to move forward.

**Comment by rgommers** [comment] 2019-08-13 04:02
> Interestingly np.nan does not yield similar results and it looks like the np.nan is propogated through the calculations.

gives the same error for me:

```
>>> import numpy as np
>>> from scipy import stats
>>> w = np.random.random(100)
>>> u = np.random.random(100) + 1e6
>>> u[99] = np.nan
>> stats.binned_statistic(u, w, 'std', bins=10)
...
ValueError: cannot convert float NaN to integer
```

Using inf/nan should give an error here, because with bins being an integer the bin edge determination should span all values. If you use, e.g., `bins=np.arange(11)` instead of `bins=10`, then there's no error.

The error message could be a lot clearer though, and some tests with `inf`/`nan` would be nice to have. So reopening.

**Comment by rlucas7** [comment] 2019-08-13 17:31
Looked at this a little more today because I wasn't satisfied and the error wasn't fully reproduced.
Looking at the stacktrace from @KeironO it looks like one of the edges of the bins was numerically 0. For example, if I run: 

```
c4b301c872df:~ rlucas$ python3
Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 21 2017, 18:29:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> int(-np.log10(0.0)) + 6
__main__:1: RuntimeWarning: divide by zero encountered in log10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
>>> 
```
That reproduces the last part of the stack trace posted. 
The issue is that a 0 goes into:

https://github.com/scipy/scipy/blob/master/scipy/stats/_binned_statistic.py#L583

which looks like gets produced from one of the calculations here:

https://github.com/scipy/scipy/blob/master/scipy/stats/_binned_statistic.py#L546-L567

AFAIK the bin calculation doesn't restrict the bin edges to be non-zero. For this function the bin edges need to be non-zero for the logarithm. 

Couple of ways to fix this part, either check for 0 bin and shift slightly ***or*** make the bin calculation not return a bin edge that is numerically 0. 

The check and shift is easier to implement and would result in slightly different bin widths. 
The fix in the bin calculation is more vague, could shift all bins by an epsilon to not have a 0 bin edge would be the most straightforward way to fix that part.

**Comment by rlucas7** [comment] 2019-08-15 00:43
Quick status update, I've got a reproducing test and throwing ValueError for `np.nan` and `np.inf` I'm still working on the reproducing example and fix on the 0 bin edge defect. I expect to have a PR (with both tests and fixes) up by the weekend.

**Closed** 2019-10-26 20:11 UTC
Labels: defect, scipy.stats
