### ISSUE TITLE
RBFInterpolator gives Segmentation fault for large images

### ISSUE THREAD

**Issue by czgdp1807** [scipy/scipy#14234] opened 2021-06-15 09:40 UTC
`scipy.interpolate.RBFInterpolator` gives `Segmentation fault` for large images/2D arrays. Moreover, for some dimensions (example - 250 x 250) the algorithm is a bit slow. I am not sure whether the issue is with Pythran or with the implementation `RBFInterpolator` or is it just something specific to my system.

#### Reproducing code example:

Reference - https://stackoverflow.com/questions/21690608/numpy-inpaint-nans-interpolate-and-extrapolate/21697401#21697401
```python
import numpy as np
import pythran
import scipy
from scipy.interpolate import RBFInterpolator

print("Pythran Version: ", pythran.__version__)
print("Scipy Version: ", scipy.__version__)
print("NumPy Version: ", np.__version__)

num_points = [10, 100, 500]
for num in num_points:
    x = np.linspace(0, 1, num)
    y = x[:, None]
    image = x + y
    print(image.shape)

    # Destroy some values
    mask = np.random.random(image.shape) > 0.7
    image[mask] = np.nan

    valid_mask = ~np.isnan(image)
    coords = np.array(np.nonzero(valid_mask)).T
    values = image[valid_mask]

    it = RBFInterpolator(coords, values)

    filled = it(list(np.ndindex(image.shape))).reshape(image.shape)

    del x, y, image, it, filled

    print("Completed Successfully for %d x %d image."%(num, num))
```

#### Error message:

```
Pythran Version:  0.9.12.dev0
Scipy Version:  1.8.0.dev0+1285.ac3b219
NumPy Version:  1.20.3
(10, 10)
Completed Successfully for 10 x 10 image.
(100, 100)
Completed Successfully for 100 x 100 image.
(500, 500)
Segmentation fault
```

#### Scipy/Numpy/Python version information:
```bash
1.8.0.dev0+1285.ac3b219 1.20.3 sys.version_info(major=3, minor=9, micro=4, releaselevel='final', serial=0)
```

#### Comments

Related PR - https://github.com/scipy/scipy/pull/13595

**Comment by czgdp1807** [comment] 2021-06-15 09:42
ping @rgommers

**Comment by rgommers** [comment] 2021-06-15 09:52
Thanks for the report @czgdp1807! I can reproduce this.

This looks like a bug in Pythran, guessing it should raise a `MemoryError` rather than segfault. Cc @serge-sans-paille 

`(500, 500)` points doesn't seem like an unusually large amount of points to evaluate at once either, that's a regular image size. Any thoughts on this @treverhines?

**Comment by czgdp1807** [comment] 2021-06-15 10:10
> (500, 500) points doesn't seem like an unusually large amount of points to evaluate at once either, that's a regular image size.

Thanks Ralf. I can try finding the bottlenecks and will raise a PR if I observe any improvements locally. Let me know @treverhines if there's a scope or if its the best that can be obtained from RBF Interpolator.

**Comment by czgdp1807** [comment] 2021-06-15 10:29
I looked more about `RBFInterpolator` and it seems like the traditional implementation is O(N^3) in time complexity and space complexity is O(N^2). One way to improve is to parellize the nested loops and use parallel implementations for `np.linalg.norm`, etc. Here is a [link](https://www.alglib.net/interpolation/fastrbf.php) which claims to have an O(N.logN) implementation.

**Comment by treverhines** [comment] 2021-06-15 11:41
In the case of `num=500` you are interpolating about 175000 data points, which means that `RBFInterpolator` will need to make a 175000 x 175000 matrix. So it makes sense that you are running out of memory. If you add the argument `neighbors=50` when you create `RBFInterpolator`, then it will break the interpolation problem into one small interpolation problem for each evaluation point, using only the 50 closest data points. That takes about 25 seconds on my machine. If you lower `neighbors` to 20, then it takes about 11 seconds. Evaluation can definitely be sped up with parallelization. 

>  Here is a link which claims to have an O(N.logN) implementation. A paper which has O(N.lgN) implementation of RBF interpolator.

Thanks for pointing these out.  I have used compact RBFs and iterative solvers in the past with some success. Adding that functionality to `RBFInterpolator` may be useful but it would be a large undertaking.

**Comment by czgdp1807** [comment] 2021-06-15 11:59
> Adding that functionality to `RBFInterpolator` may be useful but it would be a large undertaking.

Yeah. Totally Agreed. It needs reading the relevant literature and then implementing all the details.



>  If you add the argument `neighbors=50` when you create `RBFInterpolator`, then it will break the interpolation problem into one small interpolation problem for each evaluation point, using only the 50 closest data points. That takes about 25 seconds on my machine. If you lower `neighbors` to 20, then it takes about 11 seconds

How does the value of neighbor argument affects the quality of results? Is there any way with which we can select best of these values (according to the maximum available memory on a system) for a given input automatically?

**Comment by treverhines** [comment] 2021-06-15 12:41
> How does the value of neighbor argument affects the quality of results? Is there any way with which we can select best of these values (according to the maximum available memory on a system) for a given input automatically?

If you are trying to interpolate a smooth function, then the error in the interpolant will generally decrease with a larger value for `neighbors`. In your example, you are interpolating a plane, which can be reproduced exactly regardless of the value for `neighbors` (although `neighbors` does need to be large enough so that the neighborhood of data points is not collinear).  

It is hard to come up with a good way to automatically pick a value for `neighbors`. It depends on how many data points you have, and there is also a trade-off between speed/memory and accuracy.  If you have fewer than about 5000 data points, then the fastest and most accurate RBF interpolation would probably be with `neighbors=None`. Setting `neighbors` to `None` uses all the data points but it avoids to cost of finding the nearest neighbors. When interpolating images (> 5000 data points), there is not too much to gain from having a large value for `neighbors` unless the image values are smooth over a large neighborhood. So I like to use `neighbors=20` for image inpainting, and I also set `kernel="linear"`, which is faster and also prevents the interpolant from overshooting the data.

**Comment by czgdp1807** [comment] 2021-06-16 03:04
I was wondering if we can at least raise `MemoryError`/`std::bad_alloc` instead of a generic `SegmentationFault` if too large amounts are requested.

**Comment by serge-sans-paille** [comment] 2021-06-16 05:56
Should be fixed by https://github.com/serge-sans-paille/pythran/pull/1806

**Comment by czgdp1807** [comment] 2021-06-16 12:18
Hi. I was thinking that why are we making a matrix at all for passing it to Fortran function (degsv). Can we use iterative methods (like Gauss-Seidel, Jacobi method) to solve the system of equations implicitly? The time complexity will then be O(N * N * number_of_iterations) and space complexity will be O(N). I have explained my thought process below.

Say the number of data points is N for which the system is to be built. As of now, the LHS matrix is explicitly generated and then passed to Fortran function (degsv) to obtain the solution. This requires O(N.N) memory. However, Gauss-Seidel, Jacobi method will require O(N) memory and O(N.N) time for each iteration. I noticed in the update equations (in https://en.wikipedia.org/wiki/Jacobi_method and https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method) that the coefficients (aii, aij) can be generated in constant time in our case. Basically, in LHS matrix the value of each element is a function of input and indices (i, j) (like the upper left of LHS is the kernel matrix, the upper right is transpose of polynomial matrix, lower left is polynomial matrix and lower right is 0 and the values in kernel matrix and polynomial matrix are functions of input which is taking O(N) space). So, we can define this function and get the values of aii, aij in constant time. We won't be required to pre-compute and store this in a memory beforehand. That way one may be able to do RBF interpolation by consuming less space. I also see that there is a scope of parallelization in Jacobi method, like the updated values only depend on previous values and all of these can be generated simultaneously. By using parallel computation one can reduce the effective time complexity to O(N).

Please let me know if there is a flaw in above thought process. I was just curious so written everything here in an abstract sense. There are many details which might need to be figured out.

**Comment by treverhines** [comment] 2021-06-16 12:54
A robust iterative solver that does not require O(N^2) memory would be nice. I think there are two issues to be aware of: 1) The matrices being solved tend to be really poorly conditioned and you would need to find a good pre-conditioner if you want the solver to converge. 2) Creating the matrix components is pretty time consuming (especially for the Gaussian and thin plate spline kernel), and so the matrix-vector product for LHS would be slow if the components are not stored in memory. But perhaps that matrix-vector product could be made reasonably fast if written in pythran. Once that matrix-vector product is written, you could then use `scipy.sparse.linalg.LinearOperator` with one of the iterative solvers in `scipy.sparse.linalg`.

**Comment by czgdp1807** [comment] 2021-06-25 03:22
I noticed that, `openmp` directives aren't there in `_rbfinterp_pythran.py`, so OpenMP isn't used I believe. Should we add them?

**Comment by rgommers** [comment] 2021-06-25 09:13
> I noticed that, `openmp` directives aren't there in `_rbfinterp_pythran.py`, so OpenMP isn't used I believe. Should we add them?

No we shouldn't add any directives here. OpenMP isn't portable, and hence not allowed in SciPy binaries (see https://github.com/scipy/scipy/issues/10239#issuecomment-795030817). Let me comment on your other question in gh-13308 in more detail.

**Comment by ev-br** [comment] 2021-07-08 06:30
So a short/medium term solution is to bump the python requirement once the released pythran version contains https://github.com/serge-sans-paille/pythran/pull/1806 -- not sure which version it is though.

**Comment by rgommers** [comment] 2021-07-08 07:42
pythran `0.9.12` will come out in a couple of days with that fix. So we should bump to that version for scipy `1.7.1`

**Comment by rgommers** [comment] 2021-11-16 11:23
`1.7.2` indeed bumped the version to `pythran>=0.9.12,<0.10.0`: https://github.com/scipy/scipy/blob/maintenance/1.7.x/pyproject.toml#L16

So this can be closed.

**Closed by rgommers** 2021-11-16 11:23 UTC
Labels: defect, scipy.interpolate
