### ISSUE TITLE
Support Normal-inverse-gamma distribution at scipy.stats

### ISSUE THREAD

**Issue by Foo2000** [scipy/scipy#13644] opened 2021-03-05 01:03 UTC
**Is your feature request related to a problem? Please describe.**

This is a feature request for Normal-inverse-gamma distribution support at `scipy.stats` subpackage.

I will implement and open a pull request if approved.

**Describe the solution you'd like**

Normal-inverse-gamma distribution distribution is the conjugate prior of a Normal distribution with unknown mean and variance [1], which is is commonly used in Bayesian statistics.

[1] Murphy, Kevin. (2007). Conjugate Bayesian analysis of the Gaussian distribution. 

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by tirthasheshpatel** [comment] 2021-03-05 05:18
This is a duplicate of #6528. A PR (stalled) implementing this distribution -> #2648.

A while ago, I also put a [proposal](https://mail.python.org/pipermail/scipy-dev/2020-May/024185.html) to implement the [Normal Inverse Wishart](https://en.wikipedia.org/wiki/Normal-inverse-Wishart_distribution) distribution which is a multivariate generalization of the Normal Inverse Gamma distribution.

I can help review if you are willing to implement a PR.

Best,
Tirth

**Comment by mdhaber** [comment] 2021-03-20 23:35
Closing this duplicate of gh-6528, which has more discussion. I will mention there that there is additional support for it here.

**Closed by mdhaber** 2021-03-20 23:35 UTC
Labels: enhancement, scipy.stats
