### ISSUE TITLE
Same initial guess but getting different outputs

### ISSUE THREAD

**Issue by dineshbatta** [scipy/scipy#3976] opened 2014-09-08 08:47 UTC
I am using optimizer from scipy package(version 0.14.0)  (scipy.optimize.minimize) to minimize my objective function. The problem  involves multivarite variables. The solver is "SLSQP" and each property  has upper and lower limits which are given as constraints on the  variable. Inequality constraints are set.Tolerance is set at the default  value given in the optimizer. Jacobian and Hessian are computed by the  optimizer itself.Initially i was expecting same solution regardless the  number of times i run the optimizer with the same initial guess. The  problem is that when i run the optimizer few times with the same initial  guess, sometimes it gives me different solutions. Some times it says  "positive directional derivative for line search" and some times it  terminates successfully(converges). I am confused and couldn't conclude  anything. Did someone face the same problem before?Can someone explain  me why is this algorithm giving me different solution? Also i would like  to know any stochastic behavior associated with this algorithm?

**Comment by pv** [comment] 2016-04-02 20:21
Closing --- example code would be needed. Moreover, code involving linear algebra may not necessarily give reproducible results due to certain compiler optimizations.

**Closed by pv** 2016-04-02 20:21 UTC
Labels: scipy.optimize
