### ISSUE TITLE
DOC: incorrect example for stats.cramervonmises

### ISSUE THREAD

**Issue by Yalikesifulei** [scipy/scipy#17999] opened 2023-02-18 19:03 UTC
### Issue with current documentation:

Documentation contains three examples of using `cramervonmises`, but all of them seem to have discrepancies between values of `res.statistic, res.pvalue` and descriptions below. For example, first one:
```Python
>>> import numpy as np
>>> from scipy import stats
>>> rng = np.random.default_rng()
>>> x = stats.norm.rvs(size=500, random_state=rng)
>>> res = stats.cramervonmises(x, 'norm')
>>> res.statistic, res.pvalue
(0.49121480855028343, 0.04189256516661377)
```
And the description is _"The p-value 0.79 exceeds our chosen significance level, so we do not reject the null hypothesis that the observed sample is drawn from the standard normal distribution"_. Indeed, the null hypothesis shouldn't be rejected here as `x` clearly has standard normal distribution.
The same code on my laptop outputs far more different values, which are closer to what is described:
```Python
>>> res.statistic, res.pvalue
(0.10486572818633237, 0.561716331166968)
```

Two other examples share the same issue (see screenshot).

### Idea or request for content:

Check and fix the numbers in code examples.

### Additional context (e.g. screenshots, GIFs)

<img width="674" alt="image" src="https://user-images.githubusercontent.com/9929658/219883582-201420d5-88a3-4625-9d6b-95e09113966f.png">

**Comment by mdhaber** [comment] 2023-02-18 20:11
Thanks @Yalikesifulei. We'll fix this shortly.

**Comment by mdhaber** [comment] 2023-02-18 20:34
The reason you can't reproduce the results is that the random seed used to produce the values, `1638083107694713882823079058616272161`, is hidden from the public documentation. The numbers will always be different from what SciPy generates unless you use the same seed, but the conclusion of the test will be correct most of the time.

This has come up several times since gh-13863/gh-13778 (e.g. gh-14313, gh-15644, gh-15696) and I'm not sure what the ultimate resolution should be. Showing random seeds in documentation is surprisingly contentious, so I'm not sure what can be done other than avoiding use of `rng` in documentation altogether. @tupui, where are we headed here?

**Comment by tupui** [comment] 2023-02-19 01:36
I would just document once that such things are stochastic and in the text don't refer to fixed values.
I would close this issue. Nothing extra to keep track that we don't already track or know.

**Comment by mdhaber** [comment] 2023-02-19 01:43
We can close it when the example is fixed in gh-17945.

**Closed** 2023-02-20 22:44 UTC
Labels: scipy.stats, Documentation
