### ISSUE TITLE
Symbol hiding when using GNU linker in the Meson build should be implemented

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#15996] opened 2022-04-17 15:40 UTC
We're using a `build_ext` override in `setup.py` to insert a linker script that does symbol hiding for Python extension modules with GCC on Linux: https://github.com/scipy/scipy/blob/main/setup.py#L166-L206. See gh-8463 for why. 

The script `tools/check_pyext_symbol_hiding.sh` is run in CI on Azure (see below CI config snippet), but not in combination with a Meson build yet:
```
- script: ./tools/check_pyext_symbol_hiding.sh build
  displayName: "Check dynamic symbol hiding works"
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
  failOnStderr: true
```
I just ran it locally on a Meson build and get:
```
$ ./tools/check_pyext_symbol_hiding.sh ./build-install/lib/python3.10/site-packages/scipy/linalg/_cythonized_array_utils.cpython-310-x86_64-linux-gnu.so: too many public symbols!
000000000005c550 T _fini
0000000000008000 T _init
000000000000d791 T PyInit__cythonized_array_utils
00000000000734a0 B __pyx_module_is_main_scipy__linalg___cythonized_array_utils
```
Note that the script exits after the first non-compliant extension module is encountered. If I delete this one, I get the same on the next `.so`. Meson does have a builtin feature for this: https://mesonbuild.com/Release-notes-for-0-48-0.html#keyword-argument-for-gnu-symbol-visibility and the description in https://mesonbuild.com/Reference-manual_functions.html#arguments9. If I try to use that, I then get:
```
$ ./tools/check_pyext_symbol_hiding.sh 
./build-install/lib/python3.10/site-packages/scipy/linalg/_matfuncs_expm.cpython-310-x86_64-linux-gnu.so: too many public symbols!
0000000000050744 T _fini
0000000000008000 T _init
000000000000bdc7 T PyInit__matfuncs_expm
```
So that hides the `B` (global uninitialized data) symbols, but not the `T` (global text symbol) ones. (see [this link](https://www.ibm.com/docs/en/zos/2.1.0?topic=scd-nm-display-symbol-table-object-library-executable-files)) for symbol explanations).

I've also tried `'inlineshidden'` instead of `'hidden'` with the same result, plus a warning which seems to be a minor issue in Meson:
```
cc1: warning: command line option '-fvisibility-inlines-hidden' is valid for C++/ObjC++ but not for C
```

Trying on `special/_specfun.<>.so` gives me a huge amount of symbols, but I see the same in a conda-forge installed SciPy:

<details>
 
```
$ cd build-install/lib/python3.10/site-packages/scipy/
$ nm -D --defined-only special/_specfun.cpython-310-x86_64-linux-gnu.so
0000000000044560 T airya_
000000000001d7a0 T airyb_
000000000002b860 T airyzo_
0000000000019080 T ajyik_
000000000000dab0 T array_from_pyobj
0000000000037120 T aswfa_
00000000000458f0 T aswfb_
0000000000028a00 T bernoa_
00000000000288c0 T bernob_
000000000001af30 T beta_
00000000000264b0 T bjndd_
0000000000013040 T cbk_
000000000003cdd0 T cchg_
000000000001c430 T cerf_
000000000002c030 T cerror_
00000000000385b0 T cerzo_
00000000000182d0 T cfc_
00000000000174c0 T cfs_
0000000000015c90 T cgama_
0000000000049af0 T ch12n_
000000000003aeb0 T chgm_
0000000000038af0 T chgu_
000000000001afa0 T chgubi_
000000000001b820 T chguit_
000000000001be80 T chgul_
000000000001c150 T chgus_
000000000000fa50 T cik01_
0000000000039c80 T ciklv_
0000000000052bc0 T cikna_
0000000000022550 T ciknb_
000000000004d5f0 T cikva_
000000000004b580 T cikvb_
000000000002a4e0 T cisia_
000000000002a1a0 T cisib_
000000000001ad70 T cjk_
0000000000029620 T cjylv_
00000000000204d0 T cjynb_
000000000002e780 T cjyva_
00000000000328e0 T cjyvb_
0000000000027490 T clpmn_
00000000000398b0 T clpn_
0000000000050ee0 T clqmn_
000000000002ae20 T clqn_
0000000000039390 T comelp_
000000000000e7f0 T copy_ND_array
00000000000460c0 T cpbdn_
0000000000016210 T cpdla_
0000000000026820 T cpdsa_
0000000000054150 T cpsi_
000000000001e7d0 T cv0_
000000000002c880 T cva1_
000000000001f3a0 T cva2_
000000000001e360 T cvf_
000000000001e000 T cvql_
000000000001e250 T cvqm_
0000000000014440 T cy01_
00000000000485d0 T cyzo_
00000000000169a0 T dinf_
000000000000ef00 T dnan_
000000000001cad0 T dvla_
000000000001ce90 T dvsa_
0000000000045410 T e1xa_
0000000000011110 T e1xb_
000000000001a560 T e1z_
000000000003ac00 T eix_
000000000003adb0 T eixz_
000000000003a6d0 T elit_
000000000003a9c0 T elit3_
0000000000020180 T envj_
0000000000050690 T enxa_
00000000000501a0 T enxb_
000000000002be70 T error_
000000000002a400 T eulera_
000000000002c730 T eulerb_
000000000000eeb0 T F2PyCapsule_AsVoidPtr
000000000000eee0 T F2PyCapsule_Check
000000000000e810 T F2PyCapsule_FromVoidPtr
000000000000d700 T F2PyDict_SetItemString
000000000000d850 T F2PyGetThreadLocalCallbackPtr
000000000000d750 T F2PySwapThreadLocalCallbackPtr
000000000000ef10 T fcoef_
000000000004f6b0 T fcs_
0000000000044d30 T fcszo_
0000000000043c10 T ffk_
000000000005486c T _fini
0000000000026740 T gaih_
000000000001d740 T gam0_
00000000000112a0 T gamma2_
0000000000012d40 T gmn_
000000000004fe40 T herzo_
000000000003b630 T hygfx_
000000000003e190 T hygfz_
000000000001a000 T ik01a_
0000000000046b40 T ik01b_
0000000000042810 T ikna_
0000000000042bd0 T iknb_
000000000004ab00 T ikv_
00000000000394f0 T incob_
0000000000035260 T incog_
0000000000006000 T _init
0000000000042310 T itairy_
00000000000358d0 T itika_
00000000000354c0 T itikb_
0000000000047d30 T itjya_
0000000000047910 T itjyb_
0000000000038210 T itsh0_
000000000002ab40 T itsl0_
0000000000045ad0 T itth0_
000000000002d720 T ittika_
000000000002cfb0 T ittikb_
0000000000028f00 T ittjya_
0000000000028b30 T ittjyb_
0000000000028140 T jdzo_
0000000000054650 T jelp_
0000000000034aa0 T jy01a_
000000000001d140 T jy01b_
00000000000375c0 T jyna_
0000000000024000 T jynb_
0000000000023850 T jynbh_
0000000000024180 T jyndd_
0000000000035c90 T jyv_
000000000004a1d0 T jyzo_
0000000000011f50 T klvna_
0000000000048c20 T klvnb_
00000000000496b0 T klvnzo_
00000000000137f0 T kmn_
000000000002e490 T lagzo_
0000000000038f60 T lamn_
000000000002dab0 T lamv_
0000000000036db0 T legzo_
0000000000045d80 T lgama_
00000000000431b0 T lpmn_
00000000000165f0 T lpmns_
0000000000045550 T lpmv_
0000000000016cd0 T lpmv0_
0000000000047080 T lpn_
0000000000048380 T lpni_
0000000000026d30 T lqmn_
00000000000252f0 T lqmns_
0000000000045f30 T lqna_
000000000002d310 T lqnb_
0000000000020380 T msta1_
00000000000201f0 T msta2_
00000000000437a0 T mtu0_
0000000000053710 T mtu12_
0000000000065170 B _npy_f2py_ARRAY_API
0000000000049520 T othpl_
00000000000379d0 T pbdv_
0000000000050770 T pbvv_
0000000000047470 T pbwa_
00000000000169b0 T psi_spec_
000000000000d920 T PyFortranObject_New
000000000000d8c0 T PyFortranObject_NewAsAttr
0000000000064f80 D PyFortran_Type
000000000000caa0 T PyInit__specfun
00000000000135d0 T qstar_
000000000004fb80 T rctj_
0000000000048190 T rcty_
000000000001e630 T refine_
0000000000024580 T rmn1_
000000000001f9c0 T rmn2l_
00000000000252a0 T rmn2so_
0000000000025c70 T rmn2sp_
00000000000499c0 T rswfo_
000000000002a090 T rswfp_
0000000000044790 T scka_
0000000000014160 T sckb_
0000000000011770 T sdmn_
0000000000052590 T segv_
0000000000047200 T sphi_
0000000000024280 T sphj_
0000000000050490 T sphk_
000000000001f7c0 T sphy_
000000000001ccb0 T vvla_
0000000000011470 T vvsa_
```

</details>

The reason the symbols are visible in a conda build is because the check in `setup.py` probes for `gcc`/`g++` in the compiler name, however the conda compilers are named like: `x86_64-conda-linux-gnu-cc`, `x86_64-conda-linux-gnu-c++`.

Looking at the `build.ninja` file, the C++ extensions seem to default to `-fvisibility=hidden -fvisibility-inlines-hidden` already in Meson. C and Fortran extensions do not. And the C++ extension modules still have a large number of symbols, so it looks like the effect of these flags is different from the linker script we're using. 

This needs more investigation. It's a pretty niche issue, because no one complained about symbols not being hidden in the conda build. That said, we shouldn't regress on this so I marked it for `1.9.0`.

The Meson docs link to https://gcc.gnu.org/wiki/Visibility, which says:
_Some people may suggest that GNU linker version scripts can do just as well. Perhaps for C programs this is true, but for C++ it cannot be true - unless you laboriously specify each and every symbol to make public (and the complex mangled name of it), you must use wildcards which tend to let a lot of spurious symbols through. And you have to update the linker script if you decide to change names to the classes or the functions. In the case of the library above, the author couldn't get the symbol table below 40,000 symbols using version scripts. Furthermore, using linker version scripts doesn't permit GCC to better optimise the code._

The reason that that comment doesn't apply for Python extensions, I think, is that there's only a single `PyInit_` symbol that needs to be public. Public symbols are coming from https://github.com/python/cpython/blob/75eee1d57eb28283a8682a660d9949afc89fd010/Lib/distutils/command/build_ext.py#L686-L698

@eli-schwartz do you have any insights or advice here?

**Comment by eli-schwartz** [comment] 2022-04-18 03:35
In setup.py, you currently have the following logic:

For each extension:
- given an extension named `foo.bar`
- write a file `link-version-foo.bar.map`, with the text contents: `{global: PyInit_foo_bar; local: *; };`
- pass `'-Wl,--version-script=path/to/link-version-foo.bar.map'` as a link_args

You can pass a version script as a link_args with Meson as well (perhaps first checking that the compiler `get_argument_syntax()` is gcc rather than msvc).

In the process, I suggest the following optimization. Rather than generating per-extension linker version maps containing the exact name of the PyInit function, simply use the following version map:

```diff
diff --git a/link-version-foo.bar.map b/link-version-pyinit.map
similarity index 61%
rename from link-version-foo.bar.map
rename to link-version-pyinit.map
index a82d35f..ceb90ae 100644
--- a/link-version-foo.bar.map
+++ b/link-version-pyinit.map
@@ -1,6 +1,6 @@
 {
     global:
-        PyInit_foo_bar;
+        PyInit_*;
     local:
         *;
 };
```

ld itself already supports wildcards, and you know you want all "PyInit_" style functions exported, and nothing else... so there's no reason to specialize the file for each extension, especially if it requires doing file I/O during the build.

Add e.g. `version_link_args = ['-Wl,--version-script=' + meson.project_source_root() / 'link-version-pyinit.map'])` and apply version_link_args to each `extension_module()`.

In the long run it's on my TODO list to add support for passing an ld version script as a kwarg to library/shared_module/py.extension_module, and also smooth over handling for msvc/gcc/apple differences in how such things work (see for example GNU libtool's `-export-symbols` option).

**Comment by eli-schwartz** [comment] 2022-04-18 04:28
> Looking at the `build.ninja` file, the C++ extensions seem to default to `-fvisibility=hidden -fvisibility-inlines-hidden` already in Meson. C and Fortran extensions do not. And the C++ extension modules still have a large number of symbols, so it looks like the effect of these flags is different from the linker script we're using.

Note that they are indeed *very* different, because:
- version scripts hide all symbols at link time, due to wildcard fallthrough
- GCC symbol visibility hides whichever symbols you mark as internal/private at compile time, doing aggressive codegen optimizations in the process

Notice that in the above listed examples, you show:
- a cythonized module, which exports an extraneous `_fini` and `_init`
- a fortran module, which exports tons of functions

cython already behaves pretty well here IIRC, because it knows that it's generating python modules and optimizes the symbol table for this use case (everything is static).

Other code that isn't generated may very well need / be able to take advantage of gnu_symbol_visibility to hide everything other than PyMODINIT_FUNC (which automatically has Py_EXPORTED_SYMBOL applied).

Regardless, you do end up by default (and without the use of ld version scripts) with two text symbols that the compiler/linker implementation create for internal reasons, which may be ugly and may be unneeded but should not cause symbol clashes. These symbol clashes as per gh-8130 are the original reason for implementing this symbol hiding anyway. So I think you don't need to worry about those two symbols, particularly.

In that case, just using gnu_symbol_visibility may be fine.

**Comment by rgommers** [comment] 2022-04-18 09:01
Thanks for the detailed replies @eli-schwartz!

> In the process, I suggest the following optimization. Rather than generating per-extension linker version maps containing the exact name of the PyInit function, simply use the following version map:

That makes sense. We can then also just store that script, rather than writing it out dynamically.

> In that case, just using `gnu_symbol_visibility` may be fine.

Your analysis sounds right to me. I'm considering treating Cython extension modules the same as all other extension modules, which could be nice for review/maintenance. But on the other hand, using `gnu_symbol_visibility` will be slightly faster probably. I don't have a good feeling for how slow a linker script is, but probably negligible compared to overall build time.

**Comment by eli-schwartz** [comment] 2022-04-18 13:10
I don't know that a linker script is meaningfully slow at link time.

On the other hand, symbol visibility has (some) *runtime* performance benefits. It can generate smaller code that doesn't have to go through the symbol table.

That might not be all that noticeably faster either, but every little bit helps and micro-optimization of runtime performance has bigger payoffs than micro-optimization of build-time performance.

...

Now I wonder if maybe Meson should default gnu_symbol_visibility to 'hidden' for py.extension_module, since we know that it should always work (python itself guarantees that the init function when declared via the Python macro uses public visibility where the compiler supports it).

Users who find that that "somehow" breaks (I can't think why but anything is possible) can of course manually set the kwarg to 'default' and get back the old behavior.

**Comment by rgommers** [comment] 2022-04-18 13:42
> Now I wonder if maybe Meson should default gnu_symbol_visibility to 'hidden' for py.extension_module, since we know that it should always work

That sounds like a good idea.

Related: `dependencies: [py3_dep]` should probably also be added automatically. I can't think of a reason not to do that (any extension module should need this), and it would save a lot of boilerplate.

**Comment by eli-schwartz** [comment] 2022-04-19 03:56
> Other code that isn't generated may very well need / be able to take advantage of gnu_symbol_visibility to hide everything other than PyMODINIT_FUNC (which automatically has Py_EXPORTED_SYMBOL applied).


> Now I wonder if maybe Meson should default gnu_symbol_visibility to 'hidden' for py.extension_module, since we know that it should always work (python itself guarantees that the init function when declared via the Python macro uses public visibility where the compiler supports it).

My attempts to add this by default ran into trouble. I tracked the trouble down to https://bugs.python.org/issue11410

Apparently, CPython only actually defined this since 3.9, despite the original patch to implement it being submitted in 2011. This makes it somewhat more compelling to have Meson handle it, in order to if/else based on the version... also looks like PyPy supported it since sometime in the 2.7 series.

**Comment by rgommers** [comment] 2022-04-19 10:40
Adding it conditional on Python version sounds useful indeed. We're dropping Python 3.8 in one year from now (https://numpy.org/neps/nep-0029-deprecation_policy.html), so it's not too far off to have complete support.

**Comment by robertmaynard** [comment] 2022-05-05 17:12
> Your analysis sounds right to me. I'm considering treating Cython extension modules the same as all other extension modules, which could be nice for review/maintenance. But on the other hand, using `gnu_symbol_visibility` will be slightly faster probably. I don't have a good feeling for how slow a linker script is, but probably negligible compared to overall build time.

As discussed in https://github.com/scikit-build/scikit-build/issues/668 and https://github.com/scikit-build/scikit-build/pull/703 the linker script approach invalidates the required function markup to ensure that function level static variables are correctly fused across multiple compilation units.

In general the compile time visibility controls are the safest / correct approach as it allows projects to still express any required external unique symbols for correct execution. This doesn't happen with the linker script approach.

**Comment by eli-schwartz** [comment] 2022-05-05 17:42
Yeah, if people want the linker script approach they are free to manually define it in their projects, but I wouldn't consider it reasonable to have Meson automatically define one you didn't ask for. Setting the default visibility is a much safer and more moderate approach (which I plan to implement).

**Comment by eli-schwartz** [comment] 2022-05-08 20:44
I have posted a PR for Meson to set the default visibility: https://github.com/mesonbuild/meson/pull/10369

**Comment by rgommers** [comment] 2022-05-28 15:56
With `gnu_symbol_visibility: 'hidden'`, which will arrive in Meson 0.63.0, more symbols indeed get hidden - although `f2py` is still a bit leaky. Currently:
```
$ nm -D --defined-only build/scipy/linalg/_flapack.cpython-310-x86_64-linux-gnu.so
000000000011c6d0 T array_from_pyobj
000000000011d410 T copy_ND_array
000000000011dad0 T F2PyCapsule_AsVoidPtr
000000000011db00 T F2PyCapsule_Check
000000000011d430 T F2PyCapsule_FromVoidPtr
000000000011c320 T F2PyDict_SetItemString
000000000011c470 T F2PyGetThreadLocalCallbackPtr
000000000011c370 T F2PySwapThreadLocalCallbackPtr
000000000011ba00 T f2pywrapclange_
000000000011b960 T f2pywrapdlamch_
000000000011b9d0 T f2pywrapdlange_
000000000011b980 T f2pywrapslamch_
000000000011b9a0 T f2pywrapslange_
000000000011ba30 T f2pywrapzlange_
000000000011db78 T _fini
0000000000027000 T _init
000000000020d998 B _npy_f2py_ARRAY_API
000000000011c540 T PyFortranObject_New
000000000011c4e0 T PyFortranObject_NewAsAttr
000000000020d780 D PyFortran_Type
000000000011b260 T PyInit__flapack
000000000011db20 T wcdotc_
000000000011db30 T wcdotu_
000000000011db60 T wcladiv_
000000000011db40 T wzdotc_
000000000011db50 T wzdotu_
000000000011db70 T wzladiv_
```

With `gnu_symbol_visibility: 'hidden'`:
```
$ nm -D --defined-only build/scipy/linalg/_flapack.cpython-310-x86_64-linux-gnu.so
000000000011b9c0 T f2pywrapclange_
000000000011b920 T f2pywrapdlamch_
000000000011b990 T f2pywrapdlange_
000000000011b940 T f2pywrapslamch_
000000000011b960 T f2pywrapslange_
000000000011b9f0 T f2pywrapzlange_
000000000011db48 T _fini
0000000000027000 T _init
000000000011b220 T PyInit__flapack
000000000011daf0 T wcdotc_
000000000011db00 T wcdotu_
000000000011db30 T wcladiv_
000000000011db10 T wzdotc_
000000000011db20 T wzdotu_
000000000011db40 T wzladiv_
```

Cython also isn't always nicely clean. E.g. for `_qmc_cy` (both with and without `gnu_symbol_visibility: 'hidden'`):
```
$ nm -D --defined-only build/scipy/stats/_qmc_cy.cpython-310-x86_64-linux-gnu.so
0000000000029438 T _fini
0000000000008000 T _init
000000000000aa74 T PyInit__qmc_cy
0000000000035460 B __pyx_module_is_main_scipy__stats___qmc_cy
000000000000b3f0 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFP7_objectllll18__Pyx_memviewsliceS4_EllllS5_S4_EEEEE6_M_runEv
000000000000cb10 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFP7_objectllll18__Pyx_memviewsliceS5_EllllS5_S5_EEEEE6_M_runEv
000000000000b4a0 W _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFvPFd18__Pyx_memviewslicellERdS3_llP7_objectES5_St17reference_wrapperIdES3_llS8_EEEEE6_M_runEv
0000000000021da0 W _ZNSt6vectorISt6threadSaIS0_EE12emplace_backIJS0_EEERS0_DpOT_
0000000000021c20 W _ZNSt6vectorISt6threadSaIS0_EE17_M_realloc_insertIJS0_EEEvN9__gnu_cxx17__normal_iteratorIPS0_S2_EEDpOT_
0000000000021be0 W _ZNSt6vectorISt6threadSaIS0_EED1Ev
0000000000021be0 W _ZNSt6vectorISt6threadSaIS0_EED2Ev
0000000000032738 V _ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJPFP7_objectllll18__Pyx_memviewsliceS4_EllllS5_S4_EEEEEE
0000000000032750 V _ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJPFP7_objectllll18__Pyx_memviewsliceS5_EllllS5_S5_EEEEEE
0000000000032720 V _ZTINSt6thread11_State_implINS_8_InvokerISt5tupleIJPFvPFd18__Pyx_memviewslicellERdS3_llP7_objectES5_St17reference_wrapperIdES3_llS8_EEEEEE
000000000002d840 V _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFP7_objectllll18__Pyx_memviewsliceS4_EllllS5_S4_EEEEEE
000000000002d8c0 V _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFP7_objectllll18__Pyx_memviewsliceS5_EllllS5_S5_EEEEEE
000000000002d7a0 V _ZTSNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFvPFd18__Pyx_memviewslicellERdS3_llP7_objectES5_St17reference_wrapperIdES3_llS8_EEEEEE
0000000000032790 V _ZTVNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFP7_objectllll18__Pyx_memviewsliceS4_EllllS5_S4_EEEEEE
00000000000327b8 V _ZTVNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFP7_objectllll18__Pyx_memviewsliceS5_EllllS5_S5_EEEEEE
0000000000032768 V _ZTVNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFvPFd18__Pyx_memviewslicellERdS3_llP7_objectES5_St17reference_wrapperIdES3_llS8_EEEEEE
```

This seems to happen when using `cdef extern from`. For this module it's:
```cython
cdef extern from "<thread>" namespace "std" nogil:
```
Related discussion: https://github.com/cython/cython/pull/360

These are probably all safe. It may be worth seeing if anyone complains for `1.9.0`, and working on improvements in `f2py` and `cython` if needed - that way this is no longer a scipy-only solution, but helps other projects too.

**Comment by tylerjereddy** [comment] 2022-07-03 23:23
This may be at least loosely related to https://github.com/scipy/scipy/issues/16540, which is indeed causing problems for me with release process now that `0.63.0` is out.

**Comment by eli-schwartz** [comment] 2022-07-04 01:25
That regression is now fixed, and going forward, the CI will be using a version of Meson that does GNU symbol visibility automatically so there should not be any further regressions that aren't caught in CI before merging.

Is this ticket now effectively solved, or is there further symbol hiding that should be done?

**Comment by rgommers** [comment] 2022-07-04 08:37
> Is this ticket now effectively solved, or is there further symbol hiding that should be done?

I think code-wise we're probably good, however I still need to re-enable this in CI somehow. The `tools/check_pyext_symbol_hiding.sh` checks that there's exactly one public symbol, while with the Meson build we are now getting 3-4 symbols in most extensions (at least `_fini` and `init`) - plus with Cython and F2py many more, see 3 comments up.

I think I'd prefer to fix this in Cython/F2py though, and not re-enable the SciPy-specific linker script.

**Comment by eli-schwartz** [comment] 2022-07-07 01:45
> plus with Cython and F2py many more, see 3 comments up.


Ah, right.

As far as the fortran situation goes, does fortran have some equivalent to `__attribute__((visibility ("default")))`? Based on essentially zero knowledge of the subject, but looking at the symbol table and comparing it to the sources, it appears that as a general rule of thumb, if a fortran subroutine `foo` exists it gets exported in the shared library as the `foo_` symbol. This is also evident in the symbol table for my openblas/lapack shared libraries.

**Comment by rgommers** [comment] 2022-07-09 12:39
> As far as the fortran situation goes, does fortran have some equivalent to `__attribute__((visibility ("default")))`?

It doesn't look like it. I can't find anything useful on Fortran symbol visibility, not in the gfortran docs nor in a blog post or other such resource. I guess it has to be managed with either a linker script or a post-processing tool like `patchelf`. 

Side note: after I saw in the the Meson 0.63.0 release notes that `mold` is now supported, I had a look at `mold` and found these notes interesting/relevant: https://github.com/rui314/mold/blob/main/docs/design.md#linker-script

**Comment by rgommers** [comment] 2022-09-19 15:25
I'll try to implement the linker script now. It doesn't seem difficult, just tedious because there's no way to do this globally for all Python extension modules.

**Closed** 2022-09-21 07:19 UTC
Labels: Meson
