### ISSUE TITLE
Issue: runtime error after building with Intel compiler

### ISSUE THREAD

**Issue by samcom12** [scipy/scipy#13853] opened 2021-04-13 05:22 UTC
My issue is about running a scipy in simulation. It gives below error while running-

```
from scipy.optimize import minpack2
ImportError: /home/apps/spack/opt/spack/linux-centos7-skylake_avx512/intel-2020.2.254/py-scipy-1.6.2-e46dp6s42ng4i5up3nlivam667tqll7x/lib/python3.9/site-packages/scipy/optimize/minpack2.cpython-39-x86_64-linux-gnu.so: undefined symbol: for_cpystr
```

#### Error message:

```
from scipy.optimize import minpack2
ImportError: /home/apps/spack/opt/spack/linux-centos7-skylake_avx512/intel-2020.2.254/py-scipy-1.6.2-e46dp6s42ng4i5up3nlivam667tqll7x/lib/python3.9/site-packages/scipy/optimize/minpack2.cpython-39-x86_64-linux-gnu.so: undefined symbol: for_cpystr
  ...
```

#### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.2 1.20.2 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
```

**Comment by tupui** [comment] 2021-04-13 07:14
From reading this thread https://github.com/xianyi/OpenBLAS/issues/1956#issuecomment-452730500, it might be a linking on your system. Can you check this?

How did you install SciPy?

**Comment by samcom12** [comment] 2021-04-13 11:46
> From reading this thread [xianyi/OpenBLAS#1956 (comment)](https://github.com/xianyi/OpenBLAS/issues/1956#issuecomment-452730500), it might be a linking on your system. Can you check this?
> 
> How did you install SciPy?

Thanks!
I have referred to that thread earlier but couldn't get it working for me.

I have built **py-scipy** with spack.

**Comment by tupui** [comment] 2021-04-13 13:13
Reading threads like this: https://github.com/spack/spack/issues/10361. It might be a spack packaging issue.

Could you try on this machine to install scipy following our install guide?

**Comment by tupui** [comment] 2021-04-15 11:57
@samcom12 did you manage to fix your issue? Without more information I would close the issue as I cannot reproduce.

**Closed** 2021-04-19 06:25 UTC
Labels: Build issues
