### ISSUE TITLE
Segfaults or test failures on Linux when linked to MKL

### ISSUE THREAD

**Issue by drudd** [scipy/scipy#3193] opened 2014-01-08 19:15 UTC
I've been hunting through the archives and it looks like there's been a lot of work done recently on abi compatibility issues on osx, so I'm sorry to re-open the problem on a different platform.  I have problems with builds on Linux (specifically Scientific Linux 6.4) using the GNU compiler and linked to MKL.  If I configure and build scipy without modification, I get segfaults in the test suite that can be traced back to complex blas functions.  If I add -ff2c to the fortran flags, the same tests fail with errors rather than segfaults, and many are skipped, complaining about not finding clapack.  I am building using gcc/gfortran 4.4.7, MKL 10.3, and numpy 1.8.  All numpy tests pass fine, and the error in scipy occurs for 0.11, 0.13, and 0.13.2.

Without -ff2c, the following occurs with the complex dot function (taken from the test_dot function). 
from scipy.linalg.fblas import cdotu
cdotu([0],[0])
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
SystemError: NULL result without error in PyObject_Call
cdotu([1],[1])
Segmentation fault

With -ff2c, that test succeeds and produces correct results, however the formerly segfaulting tests cases give incorrect results, e.g.
# 
## FAIL: test_dot (test_blas.TestFBLAS1Simple)

Traceback (most recent call last):
 File "/software/python-2.7-2014q1-el6-x86_64/lib/python2.7/site-packages/scipy/lib/blas/tests/test_blas.py", line 85, in test_dot
   assert_almost_equal(f([3,-4,5],[2,5,1]),-9)
 File "/software/python-2.7-2014q1-el6-x86_64/lib/python2.7/site-packages/numpy/testing/utils.py", line 470, in assert_almost_equal
   raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 7 decimals
ACTUAL: 0.0
DESIRED: -9

The list of test cases that generate segfaults or errors are:
test_broyden1
test_broyden2
test_hermitian_modes
test_complex_nonsymmetric_modes
test_real_nonsymmetric_modes
test_standard_nonsymmetric_starting_vector
test_general_nonsymmetric_starting_vector
test_standard_nonsymmetric_no_convergence
est_svd_simple_complex
test_abi
test_convergence
test_dot
test_complex_dotc
test_complex_dotu

Any suggestions?  I am happy to provide better debugging traces or additional configuration/build information if it will be useful.

**Comment by hahnjo** [comment] 2015-02-12 08:07
For reference: I got it working with the Intel MKL, but there were some issues that I needed to patch:
#4520 #4521 #4522 

Used versions:
scipy 0.15.1
GCC 4.4.7 (RedHat 6.6)
Intel Compiler 15.0.2.164 with Intel MKL

numpy-site.cfg:
```
[mkl]
library_dirs = <Path to Intel Compiler>/lib/intel64:<Path to Intel Compiler>/mkl/lib/intel64
include_dirs = <Path to Intel Compiler>/mkl/include
lapack_libs =
mkl_libs = iomp5,mkl_rt
```
Linking with iomp5 is needed to use multiple threads.

**Comment by rgommers** [comment] 2015-04-29 20:32
Can someone confirm that this is now fixed in master (after gh-4581)?

**Comment by hahnjo** [comment] 2015-04-30 06:59
If that's worth anything: I can confirm that it's now fixed because it's my pull request ;-)

**Comment by rgommers** [comment] 2015-04-30 19:03
@hahnjo it's worth something, but I kind of knew that already:) So was hoping for someone else who had issues before to confirm this. 

There's also still links to patches of @drudd and @pv to do build-time detection of incompatibilities, which may still be useful. So leaving this issue open for now.

**Comment by ilayn** [comment] 2018-09-30 20:00
Judging by the lack of repros, assuming this is not an issue anymore. So closing but we can revisit this if needed.

**Closed by ilayn** 2018-09-30 20:00 UTC
Labels: Build issues, defect, scipy.linalg
