### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0 in theilslopes

### ISSUE THREAD

**Issue by SubrahmanyaG** [scipy/scipy#10029] opened 2019-04-08 10:50 UTC
Following changes related to theilslopes is avalable in git master repo but, when I examined same in local machine library these changes are not been added. it is showing older implementation of theilslopes.

https://github.com/scipy/scipy/blob/fcdc3d7b7c1b950d874ac3e890cccde3e2de1c6c/scipy/stats/mstats_basic.py#L661

**Comment by ilayn** [comment] 2019-04-08 10:58
@SubrahmanyaG What is your local machine version?

**Comment by SubrahmanyaG** [comment] 2019-04-08 11:07
@ilayn Thanks for reaching out. 
I m using these versions:
scipy==1.2.1
pip 18.1

**Comment by ilayn** [comment] 2019-04-08 11:18
Can you please clarify exactly what the problem is? There is none in terms of the code; current master

https://github.com/scipy/scipy/blob/dadbbff/scipy/stats/_stats_mstats_common.py#L147-L266 

and 1.2.1 

https://github.com/scipy/scipy/blob/v1.2.1/scipy/stats/_stats_mstats_common.py#L133-L252

**Comment by SubrahmanyaG** [comment] 2019-04-09 11:15
@ilayn while calculating theilslopes(y, x) I m getting exceptions. When I examined, all x values are the same. slopes = [ ] because of deltax>0 in line 712 of below commit
https://github.com/scipy/scipy/commit/8010f1432f9ea485685adf009ddcf3ee5cc536cb#diff-7c8f751928853be5df035e83e867ab29R712

delta = slopes[[Rl, Ru]]  # gives out of index error

**Comment by ilayn** [comment] 2019-04-09 11:17
@SubrahmanyaG Without a reproducible code snippet, I don't think we can find out what the problem is. Can you paste a code that when I copy paste I could create the problem?

**Comment by SubrahmanyaG** [comment] 2019-04-09 11:21
sure @ilayn  here is code snippet, 
```
x=[87.61071014, 87.61071014, 87.61071014, 87.61071014, 87.61071014, 87.61071014,
 87.61071014, 87.61071014, 87.61071014, 87.61071014, 87.61071014, 87.61071014,
 87.61071014, 87.61071014, 87.61071014, 87.61071014, 87.61071014, 87.61071014,
 87.61071014, 87.61071014, 87.61071014]

y=[12.72428626, 12.64285769, 12.39857196, 12.24285767, 12.38571482, 12.3214291,
 12.19714338, 12.27714339, 12.2214291,  12.24714338, 12.10571481, 12.10714338,
 11.99142909, 12.02142909, 12.30714339, 12.3114291,  11.8957148,  12.12571481,
 12.09000052, 12.18571481, 12.17285767]
stats.theilslopes(y, x)
```

**Comment by chrisb83** [comment] 2019-04-09 18:11
all your x-values are the same, so fitting a slope through the vertical line cannot work / does not make sense.

**Comment by SubrahmanyaG** [comment] 2019-04-09 18:28
@chrisb83 
In all x-values are the same case it should return respective slopes and intercepts.
or Return NaN or inf slope instead of failing in between( without any proper error messages)

**Comment by ilayn** [comment] 2019-04-10 08:56
This thread is morphing from one issue to another. @SubrahmanyaG are we done with the master branch and the 1.2.1 issue? 

And the other problem is basically a documentation or a better error message issue that has nothing to do with the original one. Do you mind if we close this for the original issue? 

If you have a better error handling idea please consider sending a PR about it so we can discuss in a more focused manner

**Comment by SubrahmanyaG** [comment] 2019-04-10 09:11
agree with @ilayn there is no more issue with master and 1.2.1 version issue.

**Closed** 2019-04-10 09:15 UTC
