### ISSUE TITLE
stats standardized distributions - request for expected API

### ISSUE THREAD

**Issue by mountaindust** [scipy/scipy#5888] opened 2016-02-23 16:31 UTC
I'm a mathematician trying to plot several distributions (notably in this case Gamma and truncated Normal) in order to do some basic notebook-style exploration for different parameter choices. I first started with truncated normal, and after over half an hour, I still could not get scipy.stats.truncnorm to plot a simple normal distribution with mean = 18, standard distribution = 1.5, but truncated at 12 and 24. This includes after trying to follow the formula in the documentation for a and b - the behavior was always surprising, typically cutting the distribution in half and throwing it's support way beyond 24. I finally settled for just plotting a regular normal distribution when I couldn't get it to work.

Now I'm messing around with the gamma distribution, and the API is again surprising. I would suggest that in the spirit of "batteries included", the user shouldn't have to do the sort of computations described in http://docs.scipy.org/doc/scipy/reference/tutorial/stats.html, shape parameter section, just to use the gamma distribution with its two typical parameters (k and theta, or alpha and beta, it doesn't matter - they are easy to translate between) as described on wikipedia https://en.wikipedia.org/wiki/Gamma_distribution. 

My request is that these standardized functions which lack a typical, full parameterization expose some kind of API allowing the user to specify all their typical parameters directly and get back a distribution with no further work required.

**Comment by mountaindust** [comment] 2016-02-23 16:35
I believe I mis-spoke on the case of the Gamma distribution - the scale parameter is equivalent to beta.  Just a small edition to the doc string making this parameterization choice clear would be helpful.

**Comment by ev-br** [comment] 2016-02-23 16:43
Cross-ref https://github.com/scipy/scipy/issues/4538.
PRs welcome I guess.

**Comment by mountaindust** [comment] 2016-02-23 16:45
Ah, thanks! I searched for the issue figuring I couldn't possibly be the only one having trouble with this, but didn't find it with the key words I was using.

**Comment by josef-pkt** [comment] 2016-02-23 16:46
I put link to paramnormal on 4538

All distribution are in the standard location scale form which can be a bit painful for support bounds that are not inf or zero.

**Comment by ev-br** [comment] 2016-02-23 20:14
OK, I'm going to close this as a duplicate of gh-4538. @mountaindust this is not to say we do not value your report, this is only to say that one issue is enough to track progress on this. Contributions welcome!

**Closed by ev-br** 2016-02-23 20:14 UTC
Labels: scipy.stats

**Comment by mountaindust** [comment] 2016-02-23 21:55
No problem - I understand. Thanks!!
