### ISSUE TITLE
CI is failing in recent pull requests.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#17350] opened 2022-11-05 18:23 UTC
CI is failing in recent pull requests.  The important error message appears to be

```
ERROR: Could not detect Ninja v1.8.2 or newer
```
For example:

<details>
<summary>The full CircleCI log from a recent PR (103 lines).</summary>

```
💻  meson setup /home/circleci/repo/build --prefix 
/home/circleci/repo/build-install
The Meson build system
Version: 0.63.3
Source dir: /home/circleci/repo
Build dir: /home/circleci/repo/build
Build type: native build
Project name: SciPy
Project version: 1.10.0.dev0
C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: ccache c++ (gcc 11.3.0 "c++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C supports arguments -Wno-unused-function: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
Library m found: YES
Fortran compiler for the host machine: gfortran (gcc 11.3.0 "GNU Fortran (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
Fortran linker for the host machine: gfortran ld.bfd 2.38
Compiler for Fortran supports arguments -Wno-conversion: YES 
Checking if "-Wl,--version-script" : links: YES 
Program cython found: YES (/home/circleci/.pyenv/versions/3.8.15/bin/cython)
Program pythran found: YES (/home/circleci/.pyenv/versions/3.8.15/bin/pythran)
Program cp found: YES (/usr/bin/cp)
Program python3 found: YES (/home/circleci/.pyenv/versions/3.8.15/bin/python3.8)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency threads found: YES
Library npymath found: YES
Library npyrandom found: YES
Run-time dependency openblas found: YES 0.3.20
Dependency openblas found: YES 0.3.20 (cached)
Program _build_utils/cythoner.py found: YES (/home/circleci/.pyenv/versions/3.8.15/bin/python3.8 /home/circleci/repo/scipy/_build_utils/cythoner.py)
Compiler for C supports arguments -Wno-maybe-uninitialized: YES 
Compiler for C supports arguments -Wno-discarded-qualifiers: YES 
Compiler for C supports arguments -Wno-empty-body: YES 
Compiler for C supports arguments -Wno-implicit-function-declaration: YES 
Compiler for C supports arguments -Wno-parentheses: YES 
Compiler for C supports arguments -Wno-switch: YES 
Compiler for C supports arguments -Wno-unused-label: YES 
Compiler for C supports arguments -Wno-unused-variable: YES 
Compiler for C++ supports arguments -Wno-cpp: YES 
Compiler for C++ supports arguments -Wno-deprecated-declarations: YES 
Compiler for C++ supports arguments -Wno-class-memaccess: YES 
Compiler for C++ supports arguments -Wno-format-truncation: YES 
Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
Compiler for C++ supports arguments -Wno-sign-compare: YES 
Compiler for C++ supports arguments -Wno-switch: YES 
Compiler for C++ supports arguments -Wno-terminate: YES 
Compiler for C++ supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C++ supports arguments -Wno-unused-function: YES 
Compiler for C++ supports arguments -Wno-unused-local-typedefs: YES 
Compiler for C++ supports arguments -Wno-unused-variable: YES 
Compiler for C++ supports arguments -Wno-int-in-bool-context: YES 
Compiler for Fortran supports arguments -Wno-argument-mismatch: YES 
Compiler for Fortran supports arguments -Wno-conversion: YES (cached)
Compiler for Fortran supports arguments -Wno-intrinsic-shadow: YES 
Compiler for Fortran supports arguments -Wno-maybe-uninitialized: YES 
Compiler for Fortran supports arguments -Wno-surprising: YES 
Compiler for Fortran supports arguments -Wno-uninitialized: YES 
Compiler for Fortran supports arguments -Wno-unused-dummy-argument: YES 
Compiler for Fortran supports arguments -Wno-unused-label: YES 
Compiler for Fortran supports arguments -Wno-unused-variable: YES 
Compiler for Fortran supports arguments -Wno-tabs: YES 
Compiler for Fortran supports arguments -Wno-argument-mismatch: YES (cached)
Compiler for Fortran supports arguments -Wno-conversion: YES (cached)
Compiler for Fortran supports arguments -Wno-maybe-uninitialized: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-dummy-argument: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-label: YES (cached)
Compiler for Fortran supports arguments -Wno-unused-variable: YES (cached)
Compiler for Fortran supports arguments -Wno-tabs: YES (cached)
Checking for function "open_memstream" : NO 
Configuring messagestream_config.h using configuration
Compiler for Fortran supports arguments -w: YES 
Checking for size of "void*" : 8
Compiler for C supports arguments -Wno-unused-variable: YES (cached)
Compiler for C supports arguments -Wno-parentheses: YES (cached)
Compiler for C supports arguments -Wno-unused-label: YES (cached)
Compiler for C supports arguments -Wno-implicit-function-declaration: YES (cached)
Compiler for C supports arguments -Wno-switch: YES (cached)
Compiler for Fortran supports arguments -w: YES (cached)
Checking for size of "void*" : 8
Build targets in project: 206

SciPy 1.10.0.dev0

  User defined options
    prefix: /home/circleci/repo/build-install


ERROR: Could not detect Ninja v1.8.2 or newer

A full log can be found at /home/circleci/repo/build/meson-logs/meson-log.txt
Meson build setup failed!

Exited with code exit status 1
```
</details>

<details>
<summary>Azure 'Install SciPy from SDist' log (147 lines).</summary>

```
2022-11-05T18:38:55.0186849Z ##[section]Starting: Install SciPy from SDist
2022-11-05T18:38:55.0191897Z ==============================================================================
2022-11-05T18:38:55.0192344Z Task         : Command line
2022-11-05T18:38:55.0192731Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2022-11-05T18:38:55.0193109Z Version      : 2.201.1
2022-11-05T18:38:55.0193384Z Author       : Microsoft Corporation
2022-11-05T18:38:55.0193755Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2022-11-05T18:38:55.0194200Z ==============================================================================
2022-11-05T18:38:55.1431747Z Generating script.
2022-11-05T18:38:55.1439434Z ========================== Starting Command Output ===========================
2022-11-05T18:38:55.1458892Z [command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/3460713b-d899-4fc5-848d-e38b36b879cc.sh
2022-11-05T18:38:55.1511616Z /home/vsts/work/_temp/3460713b-d899-4fc5-848d-e38b36b879cc.sh: line 2: build: command not found
2022-11-05T18:38:55.1514179Z Build sdist via  (uses pyproject.toml)
2022-11-05T18:38:55.2693673Z * Creating venv isolated environment...
2022-11-05T18:38:59.4442129Z * Installing packages in isolated environment... (Cython>=0.29.32, meson-python>=0.9.0, numpy; python_version>='3.12', numpy; python_version>='3.8' and platform_python_implementation=='PyPy', numpy==1.19.5; python_version=='3.8' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64' and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy', numpy==1.19.5; python_version=='3.8' and platform_machine=='aarch64' and platform_python_implementation != 'PyPy', numpy==1.19.5; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy', numpy==1.21.0; python_version=='3.8' and platform_machine=='arm64' and platform_system=='Darwin', numpy==1.21.0; python_version=='3.9' and platform_machine=='arm64' and platform_system=='Darwin', numpy==1.21.6; python_version=='3.10' and (platform_system!='Windows' and platform_machine!='loongarch64') and platform_python_implementation != 'PyPy', numpy==1.22.0; platform_machine=='loongarch64', numpy==1.22.3; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy', numpy==1.23.2; python_version=='3.11' and platform_python_implementation != 'PyPy', pybind11>=2.10.0, pythran>=0.12.0, wheel)
2022-11-05T18:39:06.1845092Z * Getting build dependencies for sdist...
2022-11-05T18:39:06.2454989Z * Building sdist...
2022-11-05T18:39:10.6941218Z The Meson build system
2022-11-05T18:39:10.6942162Z Version: 0.63.3
2022-11-05T18:39:10.6942597Z Source dir: /home/vsts/work/1/s
2022-11-05T18:39:10.6943855Z Build dir: /home/vsts/work/1/s/.mesonpy-29pghtjg/build
2022-11-05T18:39:10.6944447Z Build type: native build
2022-11-05T18:39:10.6944942Z Project name: SciPy
2022-11-05T18:39:10.6945424Z Project version: 1.10.0.dev0
2022-11-05T18:39:10.6946330Z C compiler for the host machine: ccache cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
2022-11-05T18:39:10.6947047Z C linker for the host machine: cc ld.bfd 2.34
2022-11-05T18:39:10.6947976Z C++ compiler for the host machine: ccache c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
2022-11-05T18:39:10.6948699Z C++ linker for the host machine: c++ ld.bfd 2.34
2022-11-05T18:39:10.6949252Z Host machine cpu family: x86_64
2022-11-05T18:39:10.6949735Z Host machine cpu: x86_64
2022-11-05T18:39:10.6950521Z Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
2022-11-05T18:39:10.6951371Z Compiler for C supports arguments -Wno-unused-function: YES 
2022-11-05T18:39:10.6952204Z Compiler for C supports arguments -Wno-conversion: YES 
2022-11-05T18:39:10.6953060Z Compiler for C supports arguments -Wno-misleading-indentation: YES 
2022-11-05T18:39:10.6953938Z Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
2022-11-05T18:39:10.6955065Z Library m found: YES
2022-11-05T18:39:10.6956045Z Fortran compiler for the host machine: gfortran (gcc 9.4.0 "GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
2022-11-05T18:39:10.6956790Z Fortran linker for the host machine: gfortran ld.bfd 2.34
2022-11-05T18:39:10.6957623Z Compiler for Fortran supports arguments -Wno-conversion: YES 
2022-11-05T18:39:10.6958432Z Checking if "-Wl,--version-script" : links: YES 
2022-11-05T18:39:10.6959294Z Program cython found: YES (/tmp/build-env-oaxud807/bin/cython)
2022-11-05T18:39:10.6960170Z Program pythran found: YES (/tmp/build-env-oaxud807/bin/pythran)
2022-11-05T18:39:10.6960789Z Program cp found: YES (/usr/bin/cp)
2022-11-05T18:39:10.6961566Z Program python found: YES (/tmp/build-env-oaxud807/bin/python)
2022-11-05T18:39:10.6962366Z Found pkg-config: /usr/bin/pkg-config (0.29.1)
2022-11-05T18:39:10.6963128Z Run-time dependency threads found: YES
2022-11-05T18:39:10.6963661Z Library npymath found: YES
2022-11-05T18:39:10.6964158Z Library npyrandom found: YES
2022-11-05T18:39:10.6964856Z Run-time dependency openblas found: YES 0.3.8
2022-11-05T18:39:10.6965469Z Dependency openblas found: YES 0.3.8 (cached)
2022-11-05T18:39:10.6966509Z Program _build_utils/cythoner.py found: YES (/tmp/build-env-oaxud807/bin/python /home/vsts/work/1/s/scipy/_build_utils/cythoner.py)
2022-11-05T18:39:10.6967754Z Compiler for C supports arguments -Wno-maybe-uninitialized: YES 
2022-11-05T18:39:10.6968651Z Compiler for C supports arguments -Wno-discarded-qualifiers: YES 
2022-11-05T18:39:10.6969480Z Compiler for C supports arguments -Wno-empty-body: YES 
2022-11-05T18:39:10.6970334Z Compiler for C supports arguments -Wno-implicit-function-declaration: YES 
2022-11-05T18:39:10.6971220Z Compiler for C supports arguments -Wno-parentheses: YES 
2022-11-05T18:39:10.6972033Z Compiler for C supports arguments -Wno-switch: YES 
2022-11-05T18:39:10.6972872Z Compiler for C supports arguments -Wno-unused-label: YES 
2022-11-05T18:39:10.6973736Z Compiler for C supports arguments -Wno-unused-variable: YES 
2022-11-05T18:39:10.6974528Z Compiler for C++ supports arguments -Wno-cpp: YES 
2022-11-05T18:39:10.6975369Z Compiler for C++ supports arguments -Wno-deprecated-declarations: YES 
2022-11-05T18:39:10.6976265Z Compiler for C++ supports arguments -Wno-class-memaccess: YES 
2022-11-05T18:39:10.6977104Z Compiler for C++ supports arguments -Wno-format-truncation: YES 
2022-11-05T18:39:10.6977953Z Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
2022-11-05T18:39:10.6978803Z Compiler for C++ supports arguments -Wno-sign-compare: YES 
2022-11-05T18:39:10.6979634Z Compiler for C++ supports arguments -Wno-switch: YES 
2022-11-05T18:39:10.6980459Z Compiler for C++ supports arguments -Wno-terminate: YES 
2022-11-05T18:39:10.6981296Z Compiler for C++ supports arguments -Wno-unused-but-set-variable: YES 
2022-11-05T18:39:10.6982195Z Compiler for C++ supports arguments -Wno-unused-function: YES 
2022-11-05T18:39:10.6983097Z Compiler for C++ supports arguments -Wno-unused-local-typedefs: YES 
2022-11-05T18:39:10.6983979Z Compiler for C++ supports arguments -Wno-unused-variable: YES 
2022-11-05T18:39:10.6984835Z Compiler for C++ supports arguments -Wno-int-in-bool-context: YES 
2022-11-05T18:39:10.6985710Z Compiler for Fortran supports arguments -Wno-argument-mismatch: YES 
2022-11-05T18:39:10.6986614Z Compiler for Fortran supports arguments -Wno-conversion: YES (cached)
2022-11-05T18:39:10.6987493Z Compiler for Fortran supports arguments -Wno-intrinsic-shadow: YES 
2022-11-05T18:39:10.6988368Z Compiler for Fortran supports arguments -Wno-maybe-uninitialized: YES 
2022-11-05T18:39:10.6989215Z Compiler for Fortran supports arguments -Wno-surprising: YES 
2022-11-05T18:39:10.6990062Z Compiler for Fortran supports arguments -Wno-uninitialized: YES 
2022-11-05T18:39:10.6990943Z Compiler for Fortran supports arguments -Wno-unused-dummy-argument: YES 
2022-11-05T18:39:10.6991885Z Compiler for Fortran supports arguments -Wno-unused-label: YES 
2022-11-05T18:39:10.6992818Z Compiler for Fortran supports arguments -Wno-unused-variable: YES 
2022-11-05T18:39:10.6993532Z Compiler for Fortran supports arguments -Wno-tabs: YES 
2022-11-05T18:39:10.6997389Z Compiler for Fortran supports arguments -Wno-argument-mismatch: YES (cached)
2022-11-05T18:39:10.6998306Z Compiler for Fortran supports arguments -Wno-conversion: YES (cached)
2022-11-05T18:39:10.6999034Z Compiler for Fortran supports arguments -Wno-maybe-uninitialized: YES (cached)
2022-11-05T18:39:10.6999785Z Compiler for Fortran supports arguments -Wno-unused-dummy-argument: YES (cached)
2022-11-05T18:39:10.7000514Z Compiler for Fortran supports arguments -Wno-unused-label: YES (cached)
2022-11-05T18:39:10.7001215Z Compiler for Fortran supports arguments -Wno-unused-variable: YES (cached)
2022-11-05T18:39:10.7001911Z Compiler for Fortran supports arguments -Wno-tabs: YES (cached)
2022-11-05T18:39:10.7002370Z Checking for function "open_memstream" : NO 
2022-11-05T18:39:10.7002812Z Configuring messagestream_config.h using configuration
2022-11-05T18:39:10.7003429Z Compiler for Fortran supports arguments -w: YES 
2022-11-05T18:39:10.7003833Z Checking for size of "void*" : 8
2022-11-05T18:39:10.7004452Z Compiler for C supports arguments -Wno-unused-variable: YES (cached)
2022-11-05T18:39:10.7005124Z Compiler for C supports arguments -Wno-parentheses: YES (cached)
2022-11-05T18:39:10.7005956Z Compiler for C supports arguments -Wno-unused-label: YES (cached)
2022-11-05T18:39:10.7006672Z Compiler for C supports arguments -Wno-implicit-function-declaration: YES (cached)
2022-11-05T18:39:10.7007371Z Compiler for C supports arguments -Wno-switch: YES (cached)
2022-11-05T18:39:10.7008022Z Compiler for Fortran supports arguments -w: YES (cached)
2022-11-05T18:39:10.7008442Z Checking for size of "void*" : 8
2022-11-05T18:39:10.7008812Z Build targets in project: 206
2022-11-05T18:39:10.7009015Z 
2022-11-05T18:39:10.7009320Z SciPy 1.10.0.dev0
2022-11-05T18:39:10.7009505Z 
2022-11-05T18:39:10.7009796Z   User defined options
2022-11-05T18:39:10.7010388Z     Native files: /home/vsts/work/1/s/.mesonpy-native-file.ini
2022-11-05T18:39:10.7010791Z     debug       : false
2022-11-05T18:39:10.7011114Z     optimization: 2
2022-11-05T18:39:10.7011497Z     prefix      : /opt/hostedtoolcache/Python/3.9.15/x64
2022-11-05T18:39:10.7011738Z 
2022-11-05T18:39:10.7011891Z 
2022-11-05T18:39:10.7012237Z ERROR: Could not detect Ninja v1.8.2 or newer
2022-11-05T18:39:10.7012468Z 
2022-11-05T18:39:10.7013093Z A full log can be found at /home/vsts/work/1/s/.mesonpy-29pghtjg/build/meson-logs/meson-log.txt
2022-11-05T18:39:10.7736133Z + meson setup --native-file=/home/vsts/work/1/s/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/opt/hostedtoolcache/Python/3.9.15/x64 /home/vsts/work/1/s /home/vsts/work/1/s/.mesonpy-29pghtjg/build
2022-11-05T18:39:10.7739433Z Traceback (most recent call last):
2022-11-05T18:39:10.7740442Z   File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
2022-11-05T18:39:10.7798031Z     main()
2022-11-05T18:39:10.7799410Z   File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 333, in main
2022-11-05T18:39:10.7800247Z     json_out['return_val'] = hook(**hook_input['kwargs'])
2022-11-05T18:39:10.7801110Z   File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 302, in build_sdist
2022-11-05T18:39:10.7801786Z     return backend.build_sdist(sdist_directory, config_settings)
2022-11-05T18:39:10.7802572Z   File "/tmp/build-env-oaxud807/lib/python3.9/site-packages/mesonpy/__init__.py", line 961, in build_sdist
2022-11-05T18:39:10.7803110Z     with _project(config_settings) as project:
2022-11-05T18:39:10.7803629Z   File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/contextlib.py", line 119, in __enter__
2022-11-05T18:39:10.7849825Z     return next(self.gen)
2022-11-05T18:39:10.7850811Z   File "/tmp/build-env-oaxud807/lib/python3.9/site-packages/mesonpy/__init__.py", line 948, in _project
2022-11-05T18:39:10.7851646Z     with Project.with_temp_working_dir(
2022-11-05T18:39:10.7852160Z   File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/contextlib.py", line 119, in __enter__
2022-11-05T18:39:10.7852638Z     return next(self.gen)
2022-11-05T18:39:10.7853489Z   File "/tmp/build-env-oaxud807/lib/python3.9/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
2022-11-05T18:39:10.7854065Z     yield cls(source_dir, tmpdir, build_dir)
2022-11-05T18:39:10.7854859Z   File "/tmp/build-env-oaxud807/lib/python3.9/site-packages/mesonpy/__init__.py", line 682, in __init__
2022-11-05T18:39:10.7855494Z     self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
2022-11-05T18:39:10.7856339Z   File "/tmp/build-env-oaxud807/lib/python3.9/site-packages/mesonpy/__init__.py", line 713, in _configure
2022-11-05T18:39:10.7856819Z     self._meson(
2022-11-05T18:39:10.7857496Z   File "/tmp/build-env-oaxud807/lib/python3.9/site-packages/mesonpy/__init__.py", line 696, in _meson
2022-11-05T18:39:10.7858165Z     return self._proc('meson', *args)
2022-11-05T18:39:10.7858891Z   File "/tmp/build-env-oaxud807/lib/python3.9/site-packages/mesonpy/__init__.py", line 691, in _proc
2022-11-05T18:39:10.7859402Z     subprocess.check_call(list(args))
2022-11-05T18:39:10.7860081Z   File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/subprocess.py", line 373, in check_call
2022-11-05T18:39:10.8077698Z     raise CalledProcessError(retcode, cmd)
2022-11-05T18:39:10.8079417Z subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/home/vsts/work/1/s/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/opt/hostedtoolcache/Python/3.9.15/x64', '/home/vsts/work/1/s', '/home/vsts/work/1/s/.mesonpy-29pghtjg/build']' returned non-zero exit status 1.
2022-11-05T18:39:10.9759641Z 
2022-11-05T18:39:10.9761495Z ERROR Backend subprocess exited when trying to invoke build_sdist
2022-11-05T18:39:11.0084107Z ##[error]Bash exited with code '1'.
2022-11-05T18:39:11.0118037Z ##[section]Finishing: Install SciPy from SDist
```

</details>

**Comment by WarrenWeckesser** [comment] 2022-11-05 18:54
This might be an interaction with `meson-python` and `ninja`.  The CI logs show that `ninja` 1.11.1 is being installed; 1.11.1 was just released today.

**Comment by WarrenWeckesser** [comment] 2022-11-05 19:01
I can reproduce this locally if I upgrade to ninja 1.11.1.

Ping @rgommers, @eli-schwartz, and any other CI/meson/ninja gurus.

**Comment by WarrenWeckesser** [comment] 2022-11-05 19:24
This looks like a bug in ninja.  With ninja 1.10.4.2, when `ninja --version` is run in a shell, the return code is 0:
```
$ ninja --version
1.10.2.git.kitware.jobserver-1
$ echo $?
0

```
With ninja 1.11.1, the return code is 245:
```
$ ninja --version
1.11.1.git.kitware.jobserver-1
$ echo $?
245
```
`meson` requires the return code to be 0.

**Comment by eli-schwartz** [comment] 2022-11-06 00:42
Basically, this is a problem with scikit-build's patched ninja, not ninja itself. The real issue is at https://github.com/scikit-build/ninja-python-distributions/issues/157

**Comment by henryiii** [comment] 2022-11-06 01:02
Can you retry it? It seems like it might be an issue with building newer versions of ninja with manylinux1. I've uploaded manylinux2010 64bit wheels.

**Comment by henryiii** [comment] 2022-11-06 03:52
This is fixed, I believe. manylinux2010 images are working elsewhere. The manylinux1 images might get removed at some point, but they actually do work on manylinux1 I believe (since cibuildwheel's tests passed). I've also been able to reproduce the failure and the fix in CI tests.

Also, please do not pin if there's a broken release & it's not an intentional breakage; instead just block out that release (`!=1.11.1` in this case). However, in this case, 1.11.1 itself was fixed, since it was not a code problem.

**Comment by WarrenWeckesser** [comment] 2022-11-06 15:18
Thanks for the quick response @henryiii.  The new wheel works for me locally, and in https://github.com/scipy/scipy/pull/17359, it looks like the jobs that were failing are working again.

> Also, please do not pin if there's a broken release & it's not an intentional breakage; instead just block out that release (!=1.11.1 in this case). 

:+1:

**Comment by rgommers** [comment] 2022-11-08 11:11
This was fixed, so closing. Thanks @WarrenWeckesser & all.

**Closed by rgommers** 2022-11-08 11:11 UTC
Labels: defect, CI
