### ISSUE TITLE
scipy.optimize.linprog(method="highs"): status=4, message="The solver did not provide a solution nor did it report a failure."

### ISSUE THREAD

**Issue by klenze** [scipy/scipy#13767] opened 2021-03-29 13:13 UTC
While using scipy.optimize.linprog(method="highs"), I encountered a status message stating "The solver did not provide a solution nor did it report a failure" and asking for a bug report, which I am hereby writing :-)

As I have little experience in numerics, I make no claims about the qualities (feasibility, boundedness, etc) of the problem I was trying to solve. (I was trying to deactivate bounds I did not require by setting b_ub elements to a large value (100000.0). I have no idea if that is part of the problem.)

#### Reproducing code example:

Please see the attached file for problem parameters: [bug_reproducer.py.gz](https://github.com/scipy/scipy/files/6221882/bug_reproducer.py.gz) (Some 3MB uncompressed. As I have no idea what is causing the problem, I can not build a minimal reproducer, sorry).
Gist of the code:
```
import numpy, scipy.optimize

c=...
A_ub=...
b_ub=...
res=scipy.optimize.linprog(c=c, A_ub=A_ub, b_ub=b_ub, method='highs')
print('status=', res.status)
print('message=', res.message)
```

#### Error message:

```
/home/philipp/.local/lib/python3.7/site-packages/scipy/optimize/_linprog_highs.py:317: OptimizeWarning: model_status is not optimal, using scaled_model_status instead.
  lb, ub, options)
status= 4
message= The solver did not provide a solution nor did it report a failure. Please submit a bug report.
```

#### Scipy/Numpy/Python version information:
```
>import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.1 1.20.1 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

Thanks for your time, 
   Philipp

**Comment by klenze** [comment] 2021-03-29 13:27
Seems like the problem is related to the fact that the negative element of b_ub is very small (-1). If I increase it somewhat, the problem goes away.
 Perhaps some precision-related issue? Practically, I can now work around it.

**Comment by mdhaber** [comment] 2021-03-29 16:23
Hi @klenze. This looks like a duplicate of gh-13610 - do you think it is the same? If you're able to build SciPy from source, does gh-13626 fix your issue?

**Comment by mckib2** [comment] 2021-03-30 02:02
I agree with @mdhaber -- please try of of current master or a branch that gh-13626.  If you can provide the problem as a gist or plain text instead of a zipped file (I know, it's big...), then I'd be happy to take a look at it

**Comment by tupui** [comment] 2021-03-30 06:30
On master the script which is provided gives:
```python
status= 4
message= An optimal solution to the scaled model was found but was HiGHS Status Code 0: HighsModelStatusNOTSET in the unscaled model. For more information run with the option `disp: True`.
```
So fixed?

**Comment by klenze** [comment] 2021-03-30 15:52
gist is here: https://gist.github.com/klenze/9c03afc6d6963131c9f41313391fd22c
FWIW, here is the output with scipy master branch with options={"disp":True}

```
>>> res=scipy.optimize.linprog(c=c, A_ub=A_ub, b_ub=b_ub, method='highs', options={"disp":True})
Presolve : Reductions: rows 368(-236); columns 988(-176); elements 2801(-625)
INFO   : Solving the presolved LP
INFO   : Scaling: Improvement factor is 1.192e+09 >= 1 so scale LP
INFO   : Basis condition estimate of           1 is within the tolerance of 1e+14
WARNING: Number of OMP threads available = 0 < 1 = Number of HiGHS threads to be used: Parallel performance will be less than anticipated
INFO   : Using dual simplex solver - serial
       Iteration        Objective     Infeasibilities num(sum)
DuPh2          0     0.0000000000e+00 Pr: 1(0.0078125)
DuPh2         50     4.0369838873e-08 Pr: 1(0.00128)
DuPh2        100     6.3557079979e-08 Pr: 1(0.01); Du: 0(3.06394e-21)
DuPh2        150     1.0781646532e-07 Pr: 1(0.03125)
DuPh2        200     2.6687638207e-06 Pr: 1(0.3125)
DuPh2        250     5.4686612224e-04 Pr: 2(0.00164042)
DuPh2        300     1.3499342615e-03 Pr: 2(0.000899888)
DuPh2        350     2.0409178692e-03 Pr: 6(0.0259687)
DuPh2        400     2.7232458159e-03 Pr: 16(0.00467956)
DuPh2        441     2.8040947227e-03 Pr: 0(1.03781e-07)
DuPh2        441     2.8039637089e-03 Pr: 0(1.03781e-07)
INFO   : Dual simplex iterations [Ph1 0; Ph2 441; Pr 0] Total 441
INFO   : Have 1 primal and 0 dual unscaled infeasibilities
INFO   : Possibly re-solve with feasibility tolerances of 7.8125e-10 primal and 1e-07 dual
INFO   : Not re-solving with refined tolerances
INFO   : Solving the original LP from the solution after postsolve
INFO   : Scaling: Improvement factor is 9.274e+10 >= 1 so scale LP
INFO   : Basis condition estimate of   9.806e+04 is within the tolerance of 1e+14
INFO   : Have 1 primal and 0 dual unscaled infeasibilities
INFO   : Possibly re-solve with feasibility tolerances of 1.5625e-09 primal and 1e-07 dual
INFO   : Not re-solving with refined tolerances
Postsolve  : 0
Time       :     0.02
Time Pre   :     0.00
Time PreLP :     0.02
Time PostLP:     0.00
For LP                 : Presolve     0.00 ( 20%): Solve presolved LP     0.02 ( 73%): Solve original LP     0.00 (  5%)
>>> res.status,res.message
(4, 'An optimal solution to the scaled model was found but was HiGHS Status Code 0: HighsModelStatusNOTSET in the unscaled model. For more information run with the option `disp: True`.')
```
Also notice that the solution provided in res.x seems ok:
```
>>> max(A_ub @ res.x - b_ub )
1.1028257595624572e-09
```
For my particular application, I would argue that the problem seems to be solved.

**Comment by mdhaber** [comment] 2021-03-30 16:22
OK. If I remember correctly, this is caused because the scaled problem is solved to default tolerances, but HiGHS isn't happy with the error when the solution is applied to the original (unscaled problem). It's tough to pick tolerances that will work for every problem. That said, now that the solution `x` is returned in this case (whereas I don't think it was before gh-13626), I think we've done about all we can. Also, HiGHS is aware of examples like this, so they will likely improve in this regard through time. Does that sound about right @mckib2?
In that case, I'm closing, but if we missed something, please feel free to re-open.

**Closed by mdhaber** 2021-03-30 16:22 UTC
Labels: defect, scipy.optimize
