### ISSUE TITLE
solve is very slow since #6775

### ISSUE THREAD

**Issue by zerothi** [scipy/scipy#7847] opened 2017-09-11 08:08 UTC
Since the merge of #6775 `scipy.linalg.solve` has been terribly slow for anything but `NRHS << N`.

This is rather unfortunate because it has left `solve` unusable (too slow) for anything but `NRHS << N`. The merge done in #6775 was done primarily based on the performance comparison of `gesv` and `gesvx` for `NRHS << N`. Secondly, in the merge there was no reference of the used LA library, MKL, OpenBLAS, ATLAS, etc.?

Here I show a benchmark on _both_ `NRHS << N` and `NRHS == N` which is not every corner case, but should highlight that `gesvx` is only useful for the former (unless precision is of utmost importance). For the case of `NRHS > N` the trend follows. I _only_ show performance benchmark for OpenBLAS.

(I also think there is a bug in handling the deprecated flag `sym_pos` in the `solve` code. I.e. `sym_pos` redefines `assume_a` _after_ its meaning has been digested.)

### Reproducing code example:
This code has also been used to reproduce the following images.
```
from time import time as T
import numpy as np
import scipy as sp
import scipy.linalg as sl
la = sl.lapack

ITT = 25
N = np.arange(100, 1401, 50)

def performance():
    t = np.zeros([len(N), 4])
    for i, n in enumerate(N):
        print(n)
        A = np.random.rand(n, n) * 10.
        B = np.random.rand(n, 3) * 10.
        C = np.random.rand(n, n) * 10.

        t0 = T()
        for _ in range(ITT):
            la.dgesvx(A, B)
        t[i, 0] = (T() - t0) / ITT

        t0 = T()
        for _ in range(ITT):
            la.dgesv(A, B)
        t[i, 1] = (T() - t0) / ITT

        t0 = T()
        for _ in range(ITT):
            la.dgesvx(A, C)
        t[i, 2] = (T() - t0) / ITT

        t0 = T()
        for _ in range(ITT):
            la.dgesv(A, C)
        t[i, 3] = (T() - t0) / ITT

def accuracy():
    acc = np.zeros([len(N), 4])
    for it in range(ITT):
        print(it)
        for i, n in enumerate(N):
            A = np.random.rand(n, n) * 10.
            B = np.random.rand(n, 3) * 10.
            C = np.random.rand(n, n) * 10.

            x = la.dgesvx(A, B)[7]
            acc[i, 0] += ((dot(A, x) - B) ** 2).sum() ** .5

            x = la.dgesv(A, B)[2]
            acc[i, 1] += ((dot(A, x) - B) ** 2).sum() ** .5

            x = la.dgesvx(A, C)[7]
            acc[i, 2] += ((dot(A, x) - C) ** 2).sum() ** .5

            x = la.dgesv(A, C)[2]
            acc[i, 3] += ((dot(A, x) - C) ** 2).sum() ** .5
    acc /= ITT

performance()
accuracy()
```

### Error message:
There is no error message, only bad performance.

### Scipy/Numpy/Python version information:
```
scipy: 0.19.1
numpy: 1.13.1
OpenBLAS: 0.2.20
```

Here I show timings `T(gesvx) / T(gesv)`:
`NRHS == 3`:
![solve3_time_vxov](https://user-images.githubusercontent.com/4789793/30261799-8c3b517a-96ce-11e7-8506-09c019a15726.png)
`NRHS == N`:
![solven_time_vxov](https://user-images.githubusercontent.com/4789793/30261806-9b06680c-96ce-11e7-8c8d-4ff6faa3d698.png)

As seen the performance is really bad for `NRHS == N`. 80 times slower for matrices `N >= 1000`. I think this justifies a couple of changes to `solve`:

1. Revert default to `gesv` routines, also given the fact that `gesv` was the default routine in previous `scipy` releases.
2. Add an optional flag `refine=False` which determines the use of `gesvx` routines, if `refine=True`. Whether this is an appropriate name for the flag, I don't know. If you have another idea, let me know.

If you agree to this I would be happy to contribute a PR. I have implemented a copy of `solve` in one of my own projects to keep using some of the functionality available in scipy, but not in numpy. You may see a re-defined `solve` here: https://github.com/zerothi/sisl/blob/c04ed44cbaf1ed0d485747045e4bc7cfcf9ecdfa/sisl/_numpy_scipy.py#L86
This also fixes the `sym_pos` flag. I.e. `sym_pos` has precedence. If you want a PR and you want `assume_a` to have precedence, I can do that as well.

To complete the analysis I have also created an accuracy test to compare the accuracy of `gesv` and `gesvx`, they can be seen below where it is clear that `gesvx` is an order of magnitude more precise (given `dot` is numerically exact), however the Frobenius norm I would say is showing an adequate precision for this problem.  
Yes, this leaves condition numbers and other analysis out of the `solve` routine. But currently I cannot use `solve` and I suspect others will also be surprised of the inferior performance since 0.19.1 (or was it 0.19.0?). As you can see in my linked `solve` I have added an example of how to decide whether `refine` is applicable for ones application.

The accuracy is shown in two plots, one with the actual Frobenius norm, and one with the relative difference
`NRHS == 3`:
![solve3_acc](https://user-images.githubusercontent.com/4789793/30264411-db660eac-96d8-11e7-8bfc-8022cccd3873.png)
`gesv / gesvx`
![solve3_acc_vovx](https://user-images.githubusercontent.com/4789793/30264414-df2f67fe-96d8-11e7-8546-cda62a35d7d3.png)
`NRHS == N`:
![solven_acc](https://user-images.githubusercontent.com/4789793/30264418-e2703cb8-96d8-11e7-8d91-bce80872847d.png)
`gesv / gesvx`
![solven_acc_vovx](https://user-images.githubusercontent.com/4789793/30264422-e62ee354-96d8-11e7-9ada-7bab0854619d.png)

@ilayn, sorry for bashing your PR, your PR is most valuable! I was just surprised when I updated scipy and my code ran 50 times slower!

**Comment by rgommers** [comment] 2017-09-11 09:15
This is a regression so I added it to the 1.0.0 milestone. Fix can be backported after 1.0.x is branched next weekend.

**Comment by zerothi** [comment] 2017-09-11 09:36
@rgommers how would you like me to proceed? Should I create a PR, or wait until 1.0.x is branched?

**Comment by rgommers** [comment] 2017-09-11 09:37
No need to wait. @ilayn was been pretty active lately, so will probably respond soon. I'm hoping you work it out together, and in case the fix comes in after the branch was created we'll just backport that fix.

**Comment by zerothi** [comment] 2017-09-11 09:40
@ilayn what do you think? Should I push a PR?

**Comment by ilayn** [comment] 2017-09-11 10:04
@zerothi  First thanks for the lucid analysis. That is actually correct and also I was aware of it. The reason I have been trying to switch to expert routines is before anything else (if you follow the numpy and scipy issues), condition number reporting and near singular matrix warnings. If you search online, you will find loads of pages about how NumPy/SciPy fails to detect singular matrices. So that is an indispensable property that was missing. That is the main reason why I switched to "expert" routines. To be honest, without this property, none of the speed gained is justified in my opinion.  As stated in the previous discussions, for example (https://github.com/numpy/numpy/issues/2074#issuecomment-11929188) we are somewhat avoiding the problem and shrugging. In the same vein, I thought if one needs speed they can always use `numpy.linalg.solve`

So back to the point yes, the performance is important but so is precision. I might have pushed it to the precision side too much but the other case is also unusable for my code because I can't check whether an equation set is well-conditioned or not off the top of my head and I need this check and solution precision. For me going back to `gesv` is also a regression and I mean no offence by this statement. Because then it is silently useless for any `N` and `NHRS` since NumPy's `rcond` is also broken (https://github.com/numpy/numpy/issues/8090).  

As Ralf mentioned I'm hovering around the low-hanging fruits lately about `linalg` routines and I'm actually quite happy that someone else has been bothered by such issues and of course it would be great if you also create a better API design. 

I've also asked for opinion about the polyalgorithmic `linalg.solve` similar to matlab that things are handled internally after checking the condition number (see e.g.. https://github.com/scipy/scipy/issues/6634#issuecomment-254064492). Should we attack that problem instead of going back and forth between `gesv/gesvx`?

**Comment by ilayn** [comment] 2017-09-11 10:08
Regarding the `sym_pos` issue, I was preferring the old behavior over the new one by overriding. In case somebody is not aware of the API change, and still using `sym_pos` it is clear that they have been using the old syntax hence I've chosen to override the `assume_a` behavior. Hence the inverted order.

**Comment by zerothi** [comment] 2017-09-11 11:46
@ilayn thanks for your thorough response!

I agree that ensuring correct behaviour of LA is paramount for the inner works. But ultimately I think it is the user's responsibility to ensure correct usage of functions. As @pv comments in numpy/numpy#2074 I think it is ultimately the users responsibility to use the correct routines.

From my perspective `scipy`'s goal is to be usable and fast for a wide variety of users.
The defaults should be relatively stable, but if people experience problems they should realize so due to the nature of their numerical problems at hand. `scipy` shouldn't be a general _analyzer of the problem_ and the _solver_, from my perspective ;).

See e.g. #7308 where it is suggested that `scipy` checks whether a matrix _is_ Hermitian. Something I cannot see any benefit of. If I call `eigh`, it is because it is a Hermitian matrix, not because it should _only_ do `eig` iff `M` is not Hermitian.

As I see it your problems with `gesv` is justified by your problems with the accuracy of `gesv`, however, how many have actually really seen this exposed in scipy? Is your field a corner case, or am I in the corner case? :)  
I don't think that we should force a specific routine for _any_ of the generic utilities. I.e. my proposed `solve` can use either `gesv` OR `gesvx`. I still very much think we should revert the default to `gesv`, yes it is a regression for you, but it has broken the backwards compatibility (from my perspective ;)), and I believe so for a great deal of persons (who may or may not be aware of these changes), and how many will actually read the documentation to see if they can run a calculation 50-100 times faster by switching a simple boolean keyword?

Another example of something unfortunate (sorry for diverging) in scipy is that `eigh` currently uses the `evr` routines for EVP, whereas for GEVP it uses `gvd`, where if only the eigenvalues are requested it uses `gvx`. 3 different routines depending on flags and arguments(???).
I think the diagonalization routine should be fully customizable from the users perspective, but the used routine should probably be fixed. Note that `evr` could also be used in the generalized case with back-transforms. Something the user may care, or may not care about. 
Secondly, the MRRR method _may_ have numerical problems for some matrices, https://arxiv.org/abs/1304.1864 (yes it is for the ScaLAPACK equivalent, but numerical accuracy I think is also a problem for LAPACK implementation, correct me if I am wrong).

The question is whether scipy's generic routines should catch all problems by condition checking matrices and/or formats? If scipy's core developers think this is the way forward, then the current `solve` is good.  
I think that is _not_ the way forward. It will not take long for package developers to create their own wrapper functions which calls the low-level LAPACK functions to bypass some checks that they _know_ are non-existing in their problems. Something that will diverge the development of scipy's into the sub-packages. Something I think could be explicitly beneficial in scipy's development, and which shouldn't be present in off-site packages.

Perhaps I am too biased ;)

I see a couple of possiblities:
1) Do nothing
2) Use my solve with `refine=False` which uses `gesv`
3) Use my solve with `refine=True` which uses `gesvx`

I really dislike 1), the performance penalty of gesvx vs. gesv is so drastic that I cannot let that away. I would be ok with 3). ;)

@ilayn secondly for the `sym_pos` flag, see here:
https://github.com/scipy/scipy/blob/0c42ad1b50c1d6c738c964e2aa60351e34ac2812/scipy/linalg/basic.py#L167
`assume_a` isn't used beyond that line, so those 2 lines should simply be moved up before line 153 (`assume_a` isn't used after redefinition for `sym_pos`). Again, see my code for the correct placement.

Perhaps it is good to do all the checking of matrices, but this is something I have never really cared for in my own programming with fortran where I explicitly define all calls. So I have been quite surprised at the performance difference between fortran and Python for the same algorithms (something which is completely governed by the LAPACK/BLAS calls).

Thanks for all your points. :)

**Comment by ilayn** [comment] 2017-09-11 12:22
Yes, I completely agree with all points except the 

> scipy shouldn't be a general analyzer of the problem and the solver, from my perspective ;).

This problem is really not a corner case, I can assure you about that much. Among many others, [this one](http://www.walkingrandomly.com/?p=5092) includes even Nick Higham :) 

> See e.g. #7308 where it is suggested that scipy checks whether a matrix is Hermitian. Something I cannot see any benefit of. If I call eigh, it is because it is a Hermitian matrix, not because it should only do eig iff M is not Hermitian.

Yes, that's something I completely agree. We can safely blame matlab for spoiling users about function calls and horrible legacy names.

I am in no position to dictate what should be the way forward but I really don't want `scipy` a soft wrapper around LAPACK routines but an actual numerical science tool. If I have to construct a condition checker for every use of `linalg.solve` I'll use `?gesvx` directly anyways. In the same manner, I would argue that it's users responsibility to optimize further which would be a unhelpful argument because it won't take us forward. 

Regarding the polyalgorithms, it is really not that sophisticated (though nontrivial) to implement auto-structure check. Cythonizing the check should be sufficient get into the ballpark of other solvers in other software. Almost all other numerical software does it and so do additional dedicated toolboxes ([another example](https://www.advanpix.com/2016/10/20/architecture-of-eigenproblem-solver/) which relates to your `eigh/eig` point). 

In my opinion, the frontend is the main reason why people prefer one to the other. The specialized users already know what to do. 

This is getting really complicated to put all perspectives together :) I am also with you about the item 3 but the signature is already getting complicated. MAybe we can inject `?gecon` and switch based on its response or maybe you have a better idea. I do sound like I am the owner of `linalg.solve` but I'm really looking for ideas to resolve this. We can revert back to `?gesv` as you say but I'm suspicious that there might be better ways to handle this. I don't have a sentimental attachment to `?gesvx`. Backwards compatibility is another issue that is holding us back about the new keywords are going to the end of the signature (python 2). 


Another minor detail : There is an issue with the `get_lapack_funcs` which takes unnecessary time to check.

**Comment by pv** [comment] 2017-09-11 12:38
As I understand, the relatively standard behavior is that condition 
number is detected and a warning is issued if the matrix is badly 
conditioned. Raising an exception by default is questionable, because 
the threshold of how badly conditioned a matrix can be before raising is 
ambiguous. Producing garbage silently is also bad for unsuspecting users.

Now, it may be the warning and check should be something the user can 
turn off manually, or select between off/warning/error.

Regarding the polyalgorithm issue, I think some routines recently added 
`assume_a=...` keywords, which perhaps could take `assume_a='auto'` and 
`assume_a='generic'` to signify automatic structure detection and 
generic solver without structure detection.

I'm however surprised that the condition number estimate is 80x 
expensive --- also, it should not depend on the RHS? Maybe there is some 
other substantial change in the original PR, I don't recall the details 
any more?

In particular, perhaps just a `gecon` call would be significantly less 
expensive than extra stuff done by `gesvx`?

**Comment by ilayn** [comment] 2017-09-11 12:42
After the BLAS issue, I'll check if I screwed up before the call that causes that ridiculous cost. It is indeed unacceptable and somehow I didn't see when I was testing it. I have been using MKL at the time though.

**Comment by pv** [comment] 2017-09-11 12:42
Basically, gesvx seems to not only calculate the condition number, but 
also stuff like error bounds etc. These are not typically needed, and 
maybe they account for the increased runtime.

**Comment by zerothi** [comment] 2017-09-11 12:47
You are probably right. Having the check may be beneficial, especially when adapting from MatLAB.

I agree the signature is closing in on too long argument list. However, I think it is ok, `sym_pos` is deprecated, `debug` is deprecated, and `transpose` only has a meaning for `assume_a = 'gen'`. 

@pv, I just saw your drop-in, `gesvx` also applies equilibration which are extra steps in `gesvx` besides the condition number, however, I have just checked whether `fact='E'/'N'` changes the performance, to no avail.

It may be that OpenBLAS isn't fully optimized for the `gesvx` routine, whereas it may be for `gesv`, however, having something workable for OpenBLAS I think would be nice given the popularity of OpenBLAS.

So, is the conclusion I should make a PR with option 3), i.e. a `solve` with added argument `refine` with added gecon checks? 
Do you think `refine` is good?

**Comment by pv** [comment] 2017-09-11 12:56
I would expect gesv+gecon is faster than gesvx, and has similar 
performance as the old behavior with gesv alone.

**Comment by zerothi** [comment] 2017-09-12 07:18
Hmm, this requires some more work in the internals of scipy.linalg.lapack (there are no interfaces for sycon/hecon/pocon.

I will see if I can get the time to implement this and make a PR.

**Comment by ilayn** [comment] 2017-09-12 08:09
I can get those in quickly once I'm done with #7843.

**Comment by zerothi** [comment] 2017-09-12 08:11
Great, once it has been merged, I can check. :)

**Comment by larsoner** [comment] 2017-09-17 02:21
I am a bit worried about issuing a 1.0 release with a potentially serious speed regression in `linalg.solve`. It's a core function that is used in a lot of places in SciPy and elsewhere. I'd be in favor of delaying release until we resolve this.

**Comment by rgommers** [comment] 2017-09-17 02:27
Yes, would be good to have this issue resolved before 1.0.0rc1, now planned for 27 Sep

**Comment by zerothi** [comment] 2017-09-17 05:34
Sounds great! I have a working solution which I will pr Monday or Tuesday.

**Comment by zerothi** [comment] 2017-09-17 06:10
Would it be nice to be able to request the condition number? If so I will add a keyword `return_cond=False`?

**Comment by ilayn** [comment] 2017-09-17 20:24
That's a tricky one. I think a separate function would be better for that. But there is also `numpy.linalg.cond` (though not in its best shape) and there is an urge to reduce the overlap between NumPy and SciPy so I guess we have to get core members' opinions on that one.

**Comment by zerothi** [comment] 2017-09-17 20:25
Ok, I haven't added it due to the, already now, complex argument list.

**Comment by rgommers** [comment] 2017-09-23 22:08
Fix for 1.0.0 is in, the final change for 1.1.0 not yet. So changing the milestone to 1.1.0

**Comment by rmjarvis** [comment] 2018-01-28 04:37
I'm confused from the above discussion whether the speed regression is thought to have been fixed or not.  I'm finding scipy 1.0.0 to be an order of magnitude slower than 0.19.1 for largish matrices, so from my perspective the regression still seems to be present.  But the above commit is named "fix speed regression in solve()".  Can someone clarify?

Here is a sscce showing the regression I'm seeing:
```
import numpy as np
import scipy.linalg
import time

niter = 10
n = 1000
gen_time = 0
pos_time = 0

for iter in range(niter):
    a = np.random.random(size=(n,n))
    a = np.dot(a.T, a)  # Make positive definite
    b = np.random.random(size=n)

    t0 = time.time()
    x = scipy.linalg.solve(a, b)
    t1 = time.time()
    y = scipy.linalg.solve(a, b, assume_a='pos')
    t2 = time.time()

    gen_time += t1-t0
    pos_time += t2-t1

print('total_time for gen = ',gen_time)
print('total_time for pos = ',pos_time)
```
With 0.19.1, the output is:
```
total_time for gen =  3.6522068977355957
total_time for pos =  0.49095916748046875
```
With 1.0.0, the output is:
```
total_time for gen =  35.58575081825256
total_time for pos =  0.5906229019165039
```
Now, LU decomposition should be a factor of 2-3 slower than Cholesky, so 7x slower seems a bit much already, but ok.  But the extra factor of 10 slower with scipy 1.0 is pretty unforgivable.

In my particular use case, my matrix is symmetric, but not necessarily positive definite, so I'd rather use LU, even with the factor of 7 slow down.  However, the additional factor of 10 is more than I can deal with. 

Is there any known workaround for this?  Some additional options that will avoid whatever cruft got added to make it so slow?  I don't see any documented [here](https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.linalg.solve.html), but if there is a private attribute or function I can set, that would be acceptable to me until this is fixed in the public API.

**Comment by zerothi** [comment] 2018-01-28 07:16
@rmjarvis Could you compare against 0.18.1?

The speed regression is *fixed* in the sense of NRHS ~ N. This was the main argument for switching back to the gesv routines.

Basically:
0.19.X) uses gesvx routine for 'gen'
<0.19) uses gesv without condition calculation
>0.19) uses gesv with condition calculation

So if 0.18 is far slower than 1.0.0, then it *must* be because of condition numbers and/or the added complexity of more calls. However, my guess is that you would see the same speed in 0.18.

Also, are you sure the linked LAPACK is the same for both installations? It does seem like a big difference. I just checked the initial script shown in the first post for a NRHS == 1, and even in that case I find that gesv is faster than gesvx, contrary to what you find.

**Comment by rmjarvis** [comment] 2018-01-28 07:53
> However, my guess is that you would see the same speed in 0.18.

With 0.18.1, the speed was even faster than 0.19.  For both gen and pos:
```
total_time for gen =  0.840801477432251
total_time for pos =  0.17911601066589355
```

> Also, are you sure the linked LAPACK is the same for both installations? 

I'm using the conda-forge release of each for python 3.6.  I *think* these are both using openblas, although it does seem to change the version of openblas from 0.2.19 to 0.2.20.  Not sure if that is relevant.

In case it's helpful, here is the output from updating to scipy 1.0.0:
```
$ conda install scipy==1.0.0
[...snip...]
The following packages will be UPDATED:

    numpy:        1.13.3-py36_blas_openblas_200 conda-forge [blas_openblas] --> 1.14.0-py36_blas_openblas_200 conda-forge [blas_openblas]
    openblas:     0.2.19-2                      conda-forge --> 0.2.20-7                      conda-forge
    scikit-learn: 0.19.1-py36_blas_openblas_200 conda-forge [blas_openblas] --> 0.19.1-py36_blas_openblas_201 conda-forge [blas_openblas]
    scipy:        0.19.1-py36_blas_openblas_202 conda-forge [blas_openblas] --> 1.0.0-py36_blas_openblas_201  conda-forge [blas_openblas]
```
The system is RedHat 4.4.7-18, linux version 2.6.32-696.18.7.el6.x86_64 in case relevant.  If you want more information about the system or conda installation, let me know.

**Comment by pv** [comment] 2018-01-28 14:06
For me the code above gives:
``
1.0.0
total_time for gen =  0.39351868629455566
total_time for pos =  0.2753422260284424
0.19.1
total_time for gen =  0.5669620037078857
total_time for pos =  0.38414525985717773
```
so no significant difference. (Both versions use the same openblas
version in this case.)

**Comment by zerothi** [comment] 2018-01-28 14:21
As pv writes, I can't reproduce either. I have also tried to exemplify this via this snippet.
As you see I have taken out the time-consuming routine calls.

```
from time import time as T
import numpy as np
import scipy as sp
import scipy.linalg as sl
la = sl.lapack

ITT = 10
N = np.arange(100, 2001, 50)

def performance():
    t = np.zeros([len(N), 4])
    for i, n in enumerate(N):
        print(n)
        A = np.random.random(size=(n, n)) * 10.
        B = (np.random.random(size=n) * 10.).reshape(-1, 1)

        X = sp.linalg.solve(A, B)

        t0 = T()
        for _ in range(ITT):
            (_, _, _, _, _, _, _, xx, _, _, _, info) = la.dgesvx(A, B)
            assert info == 0
        t[i, 0] = (T() - t0) / ITT

        t0 = T()
        for _ in range(ITT):
            TT = la.dgesv(A, B)
            x = TT[2]
            assert TT[-1] == 0
        t[i, 1] = (T() - t0) / ITT

        t0 = T()
        for _ in range(ITT):
            lu, ipvt, info = la.dgetrf(A)
            assert info == 0
            x1, info = la.dgetrs(lu, ipvt, B)
            assert info == 0
            anorm = la.dlange('1', A)
            rcond, _ = la.dgecon(lu, anorm, '1')
        t[i, 2] = (T() - t0) / ITT

        t0 = T()
        for _ in range(ITT):
            lu, ipvt, info = la.dgetrf(A)
            assert info == 0
            xd, info = la.dgetrs(lu, ipvt, B)
            assert info == 0
        t[i, 3] = (T() - t0) / ITT

        print('gesvx', np.allclose(X, xx), np.abs(np.dot(A, xx) - B).max())
        print('gesv', np.allclose(X, x), np.abs(np.dot(A, x) - B).max())
        print('gesv1', np.allclose(X, x1), np.abs(np.dot(A, x1) - B).max())
        print('gesvd', np.allclose(X, xd), np.abs(np.dot(A, xd) - B).max())

    return t

t = performance()
```

The plot of these results in this:
![performance](https://user-images.githubusercontent.com/4789793/35483124-ae09d5a0-043e-11e8-8e40-f10ba5a0619b.png)

**Comment by pv** [comment] 2018-01-28 14:32
It looks possible there is some difference either in the BLAS installed, or, perhaps there are bigger differences with old processors. Indeed, if the machine runs an EOL'd Redhat version and old kernel, maybe the processor or memory bus are also older models with different performance characteristics that maybe matter for this operation?

FWIW, [the benchmarks](https://pv.github.io/scipy-bench/#linalg.Bench.time_solve?p-size=1000&p-contiguous='contig'&p-module='numpy'&p-module='scipy'&y-axis=zoom&x-axis=date) that are run on a slow atom processor, don't show a 10x difference in solve performance either.

**Comment by rmjarvis** [comment] 2018-01-28 16:09
Well, I'm glad to learn this is just a system-specific regression.  (Indeed other systems I tried this on show results more in line with what you get.)  The hardware on this cluster is indeed rather old at this point, but nonetheless still in active use, and it's where I run most of my analysis code.  

I'll see if I can find some combination of BLAS and scipy versions that work better on those machines than the current default combination from conda-forge.

**Comment by ilayn** [comment] 2018-01-28 16:24
Speaking of which, should we open a new PR for the GESVX parts ? Or are you still WIP on this one @zerothi ?

**Comment by zerothi** [comment] 2018-01-28 18:56
@ilayn I did not do any work on this. I seemed to gather that having an even more complex argument list was not inline with scipy development plans.

**Comment by chrisgmorton** [comment] 2018-02-17 00:47
There are large slowdowns using scpicy.sparse solve routines with 1.0.0 compared to 0.19.1 on MacOSX 10.13.2 using Accelerate and MKL. The same large slowdowns show up on Ubuntu 16.04 with both OpenBlas and with MKL. I've stayed with 0.19.1 because the slowdowns are severe for my application. I can go back to my tests and quantify and profile code if needed but I would have thought these performance hits would be readily visible in some decent sized factorizations/solves of sparse matrices with 10k+ unknowns. I will help as I can although I'm not familiar with the innards of Scipy. Appreciate the fine work you guys are doing.

**Comment by zerothi** [comment] 2018-02-17 09:07
@chrisgmorton, this issue is related to scipy.solve, not the sparse solve.

**Comment by chrisgmorton** [comment] 2018-02-19 17:20
Please forward to the appropriate person or move to a separate issue. Thanks.

**Comment by rgommers** [comment] 2018-03-26 00:28
This issue is still open, but it's not clear to me that there's anything left to do. Can someone summarize the current state?

**Comment by zerothi** [comment] 2018-03-26 09:11
AFAIK the status is this:

- The gesv + con routines are now standard
- The gesvx calls is completely removed from the code base
- @ilayn still needs the gesvx routines for some specific high-precision calculations, I gathered from the above discussion that `solve` is already complex enough with all its arguments. Thus it seemed that an *additional* argument to control the driver was not the path to go?

So I think it boils down to figuring out what to do about `svx` routines for high-precision solves. If desired I think this should be opened in a new issue with links to this discussion.

**Comment by ilayn** [comment] 2018-03-27 00:55
I am under the impression that ?svx routines are not needed other than myself so far. So if there is no objection we can leave it to a later stage when someone else also shows some interest. There is even `dsgesv` and `zcgesv` ([example](https://stackoverflow.com/questions/36241631/when-to-use-dsgesv-versus-dgesv-to-solve-a-system-of-linear-equations) and for other array types which tries to solve it in the single precision and refines the solution for faster times. 

Hence there are even more esoteric options for linalg.solve but so far nobody needed them. I guess that gives a strong message about the need :) 

I'm still trying to create some time to design a polyalgorithm such that the array type is automatically detected and the appropriate solver is selected. But I can't make it to v1.1 at all. Thus, I guess we can close this if there is no extra work left.

**Closed** 2018-03-27 05:49 UTC
Labels: defect, scipy.linalg

**Comment by rgommers** [comment] 2018-03-27 16:46
Thanks all!

**Comment by isaacgerg** [comment] 2022-11-30 16:55
I am using scipy 1.9.0 on windows and have the problem where 
        self.cholesky, = get_lapack_funcs(('potrf',), (self.hess,)) on line 239 of _trustregion_exact.py
is very slow.

Is there a fix for this?
