### ISSUE TITLE
ENH: convolve numbers should be updated

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#10427] opened 2019-07-08 20:22 UTC
Now that `scipy.fft` exists, the `oneD_bigO` and `big_O_constant` should be updated in `signal/signaltools.py`, e.g. from this commit:

https://github.com/scipy/scipy/commit/dea7712e31f1b57e6abc21cdbd33c4dfcd62e71f

See previous discussions here:

https://github.com/scipy/scipy/pull/5608

I couldn't find one of the linked gists that I think was used for the benchmark, hopefully @endolith can find his copy!

**Comment by larsoner** [comment] 2019-07-24 11:05
@endolith any luck tracking down the optimization script?

**Comment by endolith** [comment] 2019-07-24 14:09
I didn't actually look yet.  I was trying to set up a dev environment so I could test such things myself.  

Actually, I think my timing heuristics weren't included, and those constants were from @stsievert 's instead?  Though I might have a copy of that script, too.

**Comment by stsievert** [comment] 2019-07-24 16:44
I have the script lying around, but it's far from reproducible. I've uploaded the notebook: https://gist.github.com/stsievert/268c5ef3b71c6fb9ed7e6792687. This includes the same number on  [signaltools.py#L476][1] (`34519.21021589`).

I'll put this on my todo list to clean and re-run.

[1]:https://github.com/scipy/scipy/blob/8e40c067b64016dc344c537655f56454fd1788ba/scipy/signal/signaltools.py#L476

**Comment by larsoner** [comment] 2019-07-24 17:23
That would be great, thanks @stsievert

**Comment by larsoner** [comment] 2019-07-24 17:23
@peterbell10 you're also welcome to try this optimization if you're interested

**Comment by peterbell10** [comment] 2019-07-24 18:21
@stsievert that gist 404s for me, is it private?

**Comment by stsievert** [comment] 2019-07-24 18:30
Huh. It's fixed now.

**Comment by stsievert** [comment] 2019-07-27 07:23
I've made the script more reproducible at https://github.com/stsievert/scipy-convolve-timings. This is still preliminary; I still need to add 1D timings and verify the timings.

**Comment by larsoner** [comment] 2019-07-30 15:51
Running `Generate-Test-Data.ipynb` I get:
```
actual_fastest	constant	direct_time	fft_time	mode	predicted_fastest	shape1	shape2
0	fft	81261.988432	0.067815	0.001530	full	fft	(53, 53)	(31, 31)
1	direct	81261.988432	0.000031	0.000193	full	direct	(3, 3)	(8, 8)
2	fft	81261.988432	0.000325	0.000174	full	direct	(6, 6)	(27, 27)
3	fft	81261.988432	0.465322	0.000941	full	fft	(118, 118)	(48, 48)
4	direct	81261.988432	0.000054	0.000248	full	direct	(5, 5)	(6, 6)
```
And for `Run-2D.ipynb` then `Visualize-2D.ipynb` I get:
```
constant	std
same	44423.559969	6298.257112
valid	1.000000	inf
full	35711.603272	4672.363286
```
![download](https://user-images.githubusercontent.com/2365790/62144609-28d4a400-b2c0-11e9-8485-83799e45f3a0.png)

**Comment by endolith** [comment] 2019-07-30 16:17
Note that my 1D tests had more resolution and showed different shapes for each type: https://github.com/scipy/scipy/pull/5608#issuecomment-223459552    

So I had multiple quick boundaries for each to cut down on the heuristic time, like `if h.size <= 90 or x.size <= 90` for `valid` mode, to jump immediately to `direct` if either input is small, regardless of the size of the other.

`valid` also has that line up the diagonal where it's faster to do `direct` because of the small output, which I only handled as the exact `if x.size == h.size` but could probably be widened somehow.  

Of course all these boundaries might vary from one system to the next.

**Comment by stsievert** [comment] 2019-07-30 16:25
I'm about a factor of 2 off on my constants on my old hardware (early 2015 macbook pro):

``` 
 	constant 	std
same 	81261.988432 	1.044320e+04
valid 	1.000000 	inf
full 	64347.407399 	7.356725e+03
```



> Running `Generate-Test-Data.ipynb` I get:

`Generate-Test-Data.ipynb` has the constant hard-coded. I've added a note about this in README.md.  @larsoner what accuracy do you get in `Visualize-Test.ipynb` without changing that constant?

On my machine, the fastest method is correctly predicted 93.74% of the time *on my machine*. I'm curious to see how it generalizes to @larsoner's machine. The accuracy on my machine will likely improve with more resolution (which I'll implement after the 1D tests).

**Comment by peterbell10** [comment] 2019-07-30 17:04
I think that the `fft_time` calculation might need to be changed:
https://github.com/scipy/scipy/blob/8ee6d179ce9acedcf9715c2094345d5f5e09e0ef/scipy/signal/signaltools.py#L487-L488

The 3 FFT calls are all done with the same shape so `x.shape` and `h.shape` shouldn't come in to this (will change slightly after #10510 is implemented). Also, the different modes all just calculate `mode=full` and crop the output, so `valid` and `same` shouldn't be any faster.

I think the test should actually be closer to
```python
# fft_shape is out_shape for mode='full'
fft_shape = [n + k - 1 for n, k in zip(x.shape, h.shape)]
fft_time = sum(n * math.log(n) for n in fft_shape)
```
and I would expect `big_O_constant` to be very similar between different modes.

**Comment by endolith** [comment] 2019-07-30 17:13
> Also, the different modes all just calculate mode=full and crop the output, so valid and same shouldn't be any faster.

Maybe I'm misunderstanding what you mean, but `direct` method should be much faster than `fft` for `valid` mode with small output since `direct` *doesn't* calculate full and then crop it, right?  But for `full` mode, `fft` would be faster than `direct`.

**Comment by peterbell10** [comment] 2019-07-30 17:19
In that quote I'm talking exclusively about `fftconvolve` and `fft_time`. Of course `method='direct'` has completely different characteristics.

**Closed** 2019-11-14 20:10 UTC
Labels: enhancement, scipy.signal
