### ISSUE TITLE
BUG: 1.10.0rc2 Windows wheel tests runs all segfault

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#17644] opened 2022-12-22 00:38 UTC
The wheel build jobs are here: https://github.com/scipy/scipy/actions/runs/3753070381

The non-informative failures were originally discussed here, and Ralf and I kind of went for trying to build the wheels anyway, because it wasn't clear there was a genuine SciPy issue: https://github.com/scipy/scipy/pull/17640#issuecomment-1362081751

We have just slightly more information from the `cibuildwheel` testing now, but not too much more--we now know it is a segfault:

```
 D:\a\scipy\scipy/tools/wheels/cibw_test_command.sh: line 11:  1391 Segmentation fault      python -c "import sys; import scipy; sys.exit(not scipy.test())"
```

For now, I'm tentatively labeling this is an upstream bug since it started with NumPy `1.24.0`.

Two solutions I can think of:
- try to identify the problematic test and skip it with NumPy >= 1.24.0 pending further investigation, on Windows only
- (easier, I think?): pin the runtime testing for Windows wheel builds on GitHub actions to NumPy < 1.24.0 temporarily

**Comment by andyfaff** [comment] 2022-12-22 00:44
Do you know if there's an incantation of the test call that would give more verbose output?

**Comment by tylerjereddy** [comment] 2022-12-22 02:48
Yeah, there is, I tried it on my fork here: https://github.com/tylerjereddy/scipy/pull/64

We get a bit more info, pasted below, perhaps a collection stage error/issue of some sort. There's a way to login to GitHub actions runners with a specific addon/action thingy, I've done that before.. could try that perhaps.

```
Run mkdir tmp

    Directory: D:\a\scipy\scipy

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          12/22/[20](https://github.com/tylerjereddy/scipy/actions/runs/3754374273/jobs/6378537293#step:14:21)22  2:41 AM                tmp
============================= test session starts =============================
platform win32 -- Python 3.9.13, pytest-7.2.0, pluggy-1.0.0 -- C:\hostedtoolcache\windows\Python\3.9.13\x64\python.exe
cachedir: .pytest_cache
rootdir: D:\a\scipy\scipy, configfile: pytest.ini
plugins: timeout-2.1.0, xdist-3.1.0
collecting ... 
Error: Process completed with exit code 1.
```

**Comment by tylerjereddy** [comment] 2022-12-22 02:50
Ah, maybe it doesn't work with the Windows runners though: https://github.com/marketplace/actions/debugging-with-ssh

**Comment by andyfaff** [comment] 2022-12-22 03:32
Not clear to me why the collection process would result in an error. The last pytest release was in late October. 5

**Comment by rgommers** [comment] 2022-12-22 14:03
Test collection imports all test files, so we get some running code and imports of all scipy submodules. Perhaps there's an invalid instruction or some such thing. Error code 139 in Windows seems to be nontrivial to diagnose, but some sort of memory corruption. There is already a long list of fixes merged for numpy 1.24.1, including for things like comparison operators - which we will be using during test collection.

**Comment by andyfaff** [comment] 2022-12-22 23:15
Perhaps a bisection may be in order. Somewhere between 1.23 and 1.24. Is it quicker to build numpy on windows with meson than with setup.py?

**Comment by rgommers** [comment] 2022-12-23 09:28
Yes, but you can't bisect with Meson, because Windows support was only very recently merged.

**Comment by tylerjereddy** [comment] 2022-12-23 19:32
I'm showing a segfault with SciPy `1.10.0rc1` (wheel built locally with `cibuildwheel`) and NumPy `1.23.5` AND NumPy `1.24.0`, and also if I switch to latest SciPy `main` and use `cibuildwheel` locally to produce the SciPy wheel artifact.

However, if I pull in the original `1.10.0rc1` wheel from PyPI, that will not segfault with NumPy `1.23.5` or NumPy `1.24.0` (even if NumPy wheel is built locally).

diffing logs last night showed `attrs` and `coverage` versions changed vs. last successful `cibuildwheel` run on Windows. I know that a test-time/run-time change of `attrs` has no effect on the segfault, and seems like an indirect dep at best.

`cibuildwheel` is already pinned to latest stable, and if I can repro locally, right down to the collection stage segfault, that would seem to rule out some kind of actions image change.

**Comment by rgommers** [comment] 2022-12-23 20:16
That is all very random. I checked the rtools compiler toolchain, it hasn't been updated since February. I don't see anything suspicious in the build log.

To narrow it down, it may be useful to run tests for different submodules separately. Are they all crashing immediately, or is it a single submodule?

**Comment by rgommers** [comment] 2022-12-23 20:29
I've checked the GitHub Actions images as well - very minor differences in OS and MSVC versions, but nothing that looks like a likely root cause.

**Comment by tylerjereddy** [comment] 2022-12-23 20:40
The best I've been able to do is keyboard interrupt during the test collection phase where the segfault occurs (I can see the errors accumulating in the pytest counter so I press ctrl+c during the collection). I guess we'd need to believe that my local segfault/errors reflect the true situation on the runners vs. say me not working on Windows very often. If we believe that, then here's a sample error from the collection phase:

<details>

```
_______________________________________________________________ ERROR collecting stats/tests/test_contingency.py ________________________________________________________________
ImportError while importing test module 'C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\stats\tests\test_contingency.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\..\python310_venv_windows\lib\site-packages\_pytest\python.py:618: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
..\..\..\python310_venv_windows\lib\site-packages\_pytest\pathlib.py:533: in import_path
    importlib.import_module(module_name)
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:992: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:992: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:883: in exec_module
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
..\..\..\python310_venv_windows\lib\site-packages\scipy\stats\__init__.py:485: in <module>
    from ._stats_py import *
..\..\..\python310_venv_windows\lib\site-packages\scipy\stats\_stats_py.py:53: in <module>
    from ._hypotests import _all_partitions
..\..\..\python310_venv_windows\lib\site-packages\scipy\stats\_hypotests.py:13: in <module>
    from scipy.fft import ifft
..\..\..\python310_venv_windows\lib\site-packages\scipy\fft\__init__.py:92: in <module>
    from ._helper import next_fast_len
E   ImportError: cannot import name 'next_fast_len' from 'scipy.fft._helper' (C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\_helper.py)
```
</details>

**Comment by rgommers** [comment] 2022-12-23 21:01
`scipy.fft._helper.next_fast_len` does use a very unusual code construct - a dummy pure Python function, wrapped by `functools.lru_cache`, and then a C function patched in. If you use it directly in an interpreter, does it break as well?

**Comment by tylerjereddy** [comment] 2022-12-23 21:29
```
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.10.0rc1'
>>> import scipy.fft
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\__init__.py", line 92, in <module>
    from ._helper import next_fast_len
  File "C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\_pocketfft\__init__.py", line 3, in <module>
    from .basic import *
  File "C:\Users\treddy\python310_venv_windows\lib\site-packages\scipy\fft\_pocketfft\basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: DLL load failed while importing pypocketfft: A dynamic link library (DLL) initialization routine failed.
>>> import scipy.spatial
>>> import scipy.sparse
>>> import scipy.linalg
>>> import scipy.stats
Segmentation fault
(python310_venv_windows)
```

**Comment by rgommers** [comment] 2022-12-23 21:52
Now we're getting somewhere. Maybe `libpthread` leaked into `pypocketfft.dll` somehow, or it's about the C++ standard library. Does one of these methods tell you what the missing dependency is? https://stackoverflow.com/questions/7378959/how-to-check-for-dll-dependency

**Comment by tylerjereddy** [comment] 2022-12-23 22:40
` ~/Downloads/Dependencies_x64_Release/Dependencies.exe -imports pypocketfft.cp310-win_amd64.pyd > ~/local_broken_imports.txt`

`~/Downloads/Dependencies_x64_Release/Dependencies.exe -imports pypocketfft.cp310-win_amd64.pyd > ~/pypi_working_imports.txt`

```
$ git diff --no-index --word-diff local_broken_imports.txt pypi_working_imports.txt
```

```diff
diff --git a/local_broken_imports.txt b/pypi_working_imports.txt
index 042431b..c320ac2 100644
--- a/local_broken_imports.txt
+++ b/pypi_working_imports.txt
@@ -132,7 +132,6 @@ Import from module python310.dll :
         Function PyCapsule_GetPointer
         Function PyCapsule_New
         Function PyCapsule_SetContext
-       Function PyCapsule_SetName- 
         Function PyCapsule_SetPointer
         Function PyCapsule_Type
         Function PyDict_Copy
```

**Comment by rgommers** [comment] 2022-12-24 14:28
That makes me suspect `pybind11`, because:
- scipy 1.10.0rc1 was built with pybind11 2.10.1
- scipy 1.10.0rc2 was built with pybind11 2.10.2 ([released Dec 21st](https://pypi.org/project/pybind11/#history))
- There is exactly one use of [`PyCapsule_SetName`](https://github.com/pybind/pybind11/blob/0694ec6a15863bff2e0ea5efe07c78de39b9a33c/include/pybind11/pytypes.h#L1926), which was touched in a nontrivial PR: https://github.com/pybind/pybind11/pull/4254

Can you check if the problem goes away with pybind11 `2.10.1`?

**Comment by tylerjereddy** [comment] 2022-12-24 17:47
Interesting catch, yup I can check that for sure

**Comment by tylerjereddy** [comment] 2022-12-24 18:42
Yup, excluding that version of `pybind11` did the trick, related PR/issues cross-linked above.

**Closed** 2022-12-25 11:07 UTC
Labels: Official binaries, upstream bug

**Comment by rwgk** [comment] 2022-12-26 07:33
@Lalaland (@skylion007, @henryiii FYI)

Hi Erin, it looks like pybind/pybind11#4254 is leading to a segfault here.

Questions to be answered:

* Is there a (new) bug in pybind11? (this would be on the pybind11 maintainers)
* Was there a problem all along, but pybind/pybind11#4254 happens to be a perturbation making existing UB more obvious? (this would be on the scipy maintainers)

**Comment by rwgk** [comment] 2022-12-26 07:43
>Further investigation revealed that there was a difference in declared imports between Pybind 2.10.1 and 2.10.2 - the 2.10.2 binary no longer imported Function PyCapsule_SetName (with Import from module python310.dll).

I only have a few minutes to look at this right now:

I'm not familiar with the "declared imports" mechanism.

I don't think pybind11 declares anything of that sort. Currently, the only one occurance of `PyCapsule_SetName()` is in pybind11/pytypes.h (simply a call).

How are those "declared imports" built?

**Comment by rgommers** [comment] 2022-12-26 07:51
Thanks for having a look @rwgk 

> I'm not familiar with the "declared imports" mechanism.

That may just be an unusual phrasing kind of thing, simply wording that the dependency checking tool that was used prints out. There is no usage of `PyCapsule_*` APIs in [`scipy/fft/_pocketfft/pypocketfft.cxx`](https://github.com/scipy/scipy/blob/main/scipy/fft/_pocketfft/pypocketfft.cxx). If that file has non-idiomatic usage, it'd be good to know. I don't see it, but maybe it's easier to spot for a `pybind11` expert.

**Comment by rwgk** [comment] 2022-12-26 08:15
> That may just be an unusual phrasing kind of thing, simply wording that the dependency checking tool that was used prints out. There is no usage of `PyCapsule_*` APIs in [`scipy/fft/_pocketfft/pypocketfft.cxx`](https://github.com/scipy/scipy/blob/main/scipy/fft/_pocketfft/pypocketfft.cxx). If that file has non-idiomatic usage, it'd be good to know. I don't see it, but maybe it's easier to spot for a `pybind11` expert.

Hm ... I'm completely lost TBH.

Maybe this is not a good direction to pursue?

What do I need to reproduce the segfault?  —  That'll be a prerequisite for a fix, basically no matter what.

Is it a Windows-only problem?

Do you run the same testing on other platforms? Does "it" (with pybind11 v2.10.2) work there?

**Comment by rgommers** [comment] 2022-12-26 10:39
> Hm ... I'm completely lost TBH. Maybe this is not a good direction to pursue?

Sorry, the description is confusing because we're not Windows experts (I don't even have a Windows dev machine at hand), and we got to identify the pybind11 problem in a roundabout way. We are sure it's the pybind11 release that make SciPy start segfaulting on Windows, and given that the difference between 2.10.1 and 2.10.2 makes the segfault show up and the DLL analyzer tool identifies the one missing symbol used in the segfaulting extension module corresponds with the identified `pybind11` PR is a pretty strong clue. So it is the right direction I'd say. We haven't touched the relevant module in a long time, `pybind11` 2.4.3 - 2.10.1 have always been unproblematic.

> Is it a Windows-only problem?

Yes it is, and CI passes on all other platforms. What may matter here too is that we're building with Mingw-w64 on Windows.

> What do I need to reproduce the segfault?

Clone this repo, install `cibuildwheel` in a Python (3.8-3.11 from python.org all show the issue) on Windows, and then:
```
cibuildwheel --platform windows
# Install the wheel produced with Pip, then:
python -c "import scipy.fft"  # will segfault
```
Note that `cibuildwheel` doesn't have a CLI argument to select the Python version to build for, so you may want to edit the `skip = "cp36-* ...` on line 143 of `pyproject.toml` first to avoid building for all of Python 3.8-3.11

**Comment by Lalaland** [comment] 2022-12-26 11:48
@rwgk I can take over debugging if you wish, since it's likely my change and I have a Windows machine handy.

**Comment by rwgk** [comment] 2022-12-26 13:11
> @rwgk I can take over debugging if you wanr, since it's likely my change and I have a Windows machine handy.

That'll be awesome!

I don't have any Windows machine at all and was thinking of debugging via GHA. (And I'm traveling with family, therefore only a few minutes per day, for the next ~3 weeks.)

Sorry for mixing up your name before. Corrected.

**Comment by henryiii** [comment] 2022-12-26 14:07
If it's something we need to fix, happy to push a release.

**Comment by Lalaland** [comment] 2022-12-26 16:18
@rgommers I'm having trouble building scipy on windows. Is there a set of the most up to date instructions somewhere? Is https://docs.scipy.org/doc/scipy/dev/contributor/windows.html#build-windows still accurate?

**Comment by rgommers** [comment] 2022-12-26 16:31
That looks a little outdated, and talks about building OpenBLAS from source too which I wouldn't recommend. I suggest doing what our GitHub Actions CI job does (install that Mingw-w64 and download that OpenBLAS binary, then the few build steps): https://github.com/scipy/scipy/blob/main/.github/workflows/windows.yml#L39-L81

**Comment by Lalaland** [comment] 2022-12-26 16:38
>  fatal error: io.h: No such file or directory

There is something special about that windows-2019 image that I can't seem to replicate locally.

**Comment by ilayn** [comment] 2022-12-26 16:40
@Lalaland Basically, OpenBLAS is(was) the annoying step back in the day with OpenBLAS not being available so we went in that rabbit hole in those instructions. However now you can download OpenBLAS from https://anaconda.org/multibuild-wheels-staging/openblas-libs/files . Once you have it, install MinGW64 and add the bin folder to the path so that you have a working gcc and gfortran on the path. Then make an environment variable 

```powershell
$env:PKG_CONFIG_PATH="C:\opt\64\lib\pkgconfig\"
```
(wherever you downloaded the OpenBLAS to) pointing to the OpenBLAS. Then you can use 
```powershell
python dev.py build --win-cp-openblas
```
to build. If you encounter pythran issues also add the environment variable 

```powershell
$env:SCIPY_USE_PYTHRAN=0  
```

**Comment by rgommers** [comment] 2022-12-26 16:47
@Lalaland if you don't get it to work with any of the above instructions, I may be able to strip down the build in a fork so it just builds the relevant `pypocketfft.cxx`. Maybe not today, but it shouldn't take me that long.

**Comment by matthew-brett** [comment] 2022-12-26 16:52
I think this guide to building on Windows is more up-to-date: https://github.com/scipy/scipy/wiki/Easy-Windows-10-Build-Scipy-from-source . @rgommers - is it up-to-date on OpenBLAS binaries?

**Comment by rgommers** [comment] 2022-12-26 17:09
Looks like it is. The "Easy" in the title of that page may be a little optimistic though:)

**Comment by tylerjereddy** [comment] 2022-12-26 18:33
I excised the reproducer from SciPy in case it helps: https://github.com/tylerjereddy/pybind_repro

Basically one `meson.build` file, and C++ source + header is sufficient. That probably cuts down the iteration times a bit at least.

**Comment by tylerjereddy** [comment] 2022-12-26 18:35
A bet a C++ expert could cut the reproducer in size way more even beyond that (to make it testsuite appropriate), but that would take me much longer than a regular C++ dev.

**Comment by rwgk** [comment] 2022-12-27 01:12
Quick questions from the sidelines (hoping it might give clues for @Lalaland):

> I bet a C++ expert could cut the reproducer in size way more even beyond that (to make it testsuite appropriate), but that would take me much longer than a regular C++ dev.

* IIUC meson is just a build tool? How much trouble is it to post a log showing the versions of: python, ninja, meson, gcc/g++ and the build output (highest log level)?

* For pybind11 testing we're using GHA, there isn't really anything special. Could you create a PR that adds .github/workflows/debug_scipy_segfault.yml? Basically your instructions formalized in GHA/yml syntax.

Even if it doesn't work, fixing up is probably easier for us then starting from scratch.

________

OPTIONAL, to make the pybind11 GHA quicker and less noisy:

cd pybind11/.github
git rm *.yml
cd workflows
git rm *.yml

Also apply this patch:
```
diff --git a/.appveyor.yml b/.appveyor.yml
index 360760ac..934edfbd 100644
--- a/.appveyor.yml
+++ b/.appveyor.yml
@@ -2,6 +2,8 @@ version: 1.0.{build}
 image:
 - Visual Studio 2017
 test: off
+skip_commits:
+  message: /.*/  # Skip ALL commits.
 skip_branch_with_pr: true
 build:
   parallel: true
```

Then (almost) the only thing that runs will run is the new debug_scipy_segfault.yml workflow.

**Comment by tylerjereddy** [comment] 2022-12-27 04:48
@rwgk here you go: https://github.com/pybind/pybind11/pull/4424#issuecomment-1365608721

You'll need to approve CI to run it in your project (1st time contributor block), or you can just look at the reproduction linked in my fork from there (https://github.com/tylerjereddy/pybind11/pull/1)

**Comment by Lalaland** [comment] 2022-12-27 15:43
Ah, figured it out. Meson had a bug: https://github.com/mesonbuild/meson/pull/11220

I can confirm that I can reproduce with your wonderful minimal example @tylerjereddy 

Debugging this now

**Comment by Lalaland** [comment] 2022-12-27 16:43
@rwgk Git bisect claims that your inc_ref commit is the first bad commit? I manually double checked it as well. Still debugging, but just wanted to give you an FYI.

```
65374c8e62488c557dccf70c9276e3f9fe04b007 is the first bad commit
commit 65374c8e62488c557dccf70c9276e3f9fe04b007
Author: Ralf W. Grosse-Kunstleve <rwgk@google.com>
Date:   Thu Dec 8 22:06:51 2022 -0800

    `pybind11::handle` `inc_ref()` & `dec_ref()` `PyGILState_Check()` **excluding** `nullptr` (#4246)

    * pybind11/pytypes.h `inc_ref()`, `dec_ref()` `PyGILState_Check()` **excluding** `nullptr`

    Guarded by `PYBIND11_ASSERT_GIL_HELD_INCREF_DECREF`

    * Disable `PYBIND11_ASSERT_GIL_HELD_INCREF_DECREF` for PyPy under Windows.

    * Add reference to PR #4268 (PyPy Windows)

 include/pybind11/detail/common.h |  9 +++++++++
 include/pybind11/pytypes.h       | 10 ++++++++++
 2 files changed, 19 insertions(+)
```

**Comment by tylerjereddy** [comment] 2022-12-27 17:13
When this is all sorted out a short summary will probably be useful too, so that Ralf and I can decide what is best for the next SciPy release--for example, if we'll need any `meson` version pin adjustments on Windows.

**Comment by Lalaland** [comment] 2022-12-27 18:17
Ok. Figured this out. scipy has a bug here in that it is calling Python functions before Python is initialized. This is undefined behavior and in general quite bad. On pybind11's side, we just started trying to detect that error case, but we should probably make the error logging much better here.

I'll submit a PR in an hour or so here to fix the bug within scipy.

I'll separately submit a PR to pybind11 to improve the logging for this edge case.

CC @rwgk

**Comment by Lalaland** [comment] 2022-12-27 18:52
> When this is all sorted out a short summary will probably be useful too, so that Ralf and I can decide what is best for the next SciPy release--for example, if we'll need any meson version pin adjustments on Windows.

The meson fix is only necessary if you are using BitLocker.

**Comment by rwgk** [comment] 2022-12-27 22:21
Thanks a ton for figuring this out Ethan!

Sorry I had no idea the GIL-check error reporting is this unobvious on some platforms. Note that I started cleaning up around the Google codebase (which uses many 3rd party packages) already in October 2021, on-and-off; i.e. this was a long-term effort. With the Google toolchain the error reporting is crystal clear.
