### ISSUE TITLE
ENH: scipy.optimize.minimize should return OptimizationResult with lowest function value.

### ISSUE THREAD

**Issue by VolodyaCO** [scipy/scipy#17673] opened 2022-12-28 19:36 UTC
### Is your feature request related to a problem? Please describe.

I have a function that I want to minimise. Starting from a particular initial point, the optimisation routine does not provide a lower value for the function than the function evaluated at said initial point.

I think that any optimisation routine should not return the last value explored, but the best value explored. To reproduce my example you need to use version 1.9.3 (the latest at the moment of writing):

```python
import numpy as np
import warnings
from scipy.optimize import minimize, Bounds

# Definition of the function
langer_c = np.array([6, 1, 4, 4, 8])
langer_A = np.array([[4, 6, 3, 5],
       [8, 7, 9, 9],
       [2, 7, 8, 8],
       [9, 2, 6, 9],
       [5, 4, 1, 4]])
def langermann(x: np.ndarray) -> float:
    if np.any((x > 10) | (x < 0)):
        warnings.warn(
            "The Langer function should be evaluated in the [0, 10] box", UserWarning
        )
    sum_ = np.sum(np.subtract(langer_A, x) ** 2, axis=1)
    vec = np.exp(-1 / np.pi * sum_) * np.cos(np.pi * sum_)
    result = np.dot(langer_c, vec)
    print(f"For input {x} the function value is {result}")
    return result

# Definition of the optimiser
x0 = np.array([4.65116802, 4.42985893, 1.74720157, 4.29727392])
rs = minimize(langermann, x0, method="Powell", bounds=Bounds(lb=np.zeros(4), ub=np.ones(4) * 10), options={"maxfev": 1000})
print(rs)
```

And the output is
```zsh
For input [4.65116802 4.42985893 1.74720157 4.29727392] the function value is -7.069104766469421
For input [3.81966011 4.42985893 1.74720157 4.29727392] the function value is 2.7306909544124496
[...]
For input [1.49204384 3.85194607 5.35824627 2.87694152] the function value is -0.0076045305834336
For input [1.49204384 3.85194607 5.35824627 2.87697487] the function value is -0.007604529917968068
For input [1.49204384 3.85194607 5.35824627 2.87690816] the function value is -0.007604529739767902
   direc: array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
     fun: -0.0076045305834336
 message: 'Optimization terminated successfully.'
    nfev: 62
     nit: 1
  status: 0
 success: True
       x: array([1.49204384, 3.85194607, 5.35824627, 2.87694152])
```
As you can see, at `x0` the function has its lowest value, yet the result from the optimisation routine shows a much higher minimum.

### Describe the solution you'd like.

I would like the result from any call to `minimize` to return all the information relevant to the lowest value reached through optimisation.

### Describe alternatives you've considered.

Wrapping the function to save the best function value (lowest) and its corresponding input.

**Comment by mdhaber** [comment] 2022-12-28 23:23
This has been reported several times, so please see gh-15089, gh-12111, gh-12120, gh-10324 for more information. 

The decision in those was that unless there is evidence that the algorithm is not behaving as the algorithm is supposed to behave, the fact that an algorithm does not converge to the best point visited is not a bug. `minimize` wraps local optimizers that are designed to converge to a local minimum - a point lower than all surrounding points. Something about the way the default `method='powell'` works apparently causes it to escape the initial basin and converge to the local minimum of a different basin. If you don't like the way `'powell'` works, you have several options:

1. Use a different method. Other minimizers that support bounds (e.g. `slsqp`, `l-bfgs-b`) converge to a lower value than the initial point for this problem.
2. Make your objective function a method of an object, and store information about `x`/`fun` to an attribute of that object.
3. consider a [global optimizer](https://docs.scipy.org/doc/scipy/reference/optimize.html#global-optimization)

As for an enhancement that makes it easy to access the lowest function value visited, we can't change the behavior without the user opting in because that would not be backward compatible. Since there are many other things that users may want along these lines, rather than continuing to complicate the `minimize` signature, we are pursuing work on the callback interface. Starting in SciPy 1.11.0, `minimize` will pass more information to the `callback` function, which is called once per iteration of the algorithm, if the `callback` function accepts a single argument named `intermediate_result`. In the main branch, `intermediate_result` already includes `x` and `fun`, and we'll continue to add information about whether constraints are satisfied, Please see the [development version](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.minimize.html) of the documentation and gh-17486/gh-17616 for more information. We welcome PRs to support this work, such as those that would add additional information to the `OptimizeResult` object that gets passed into the `callback`.

I'll go ahead and close this according to the precedent set in the other issues (gh-12120, gh-10324).

**Closed by mdhaber** 2022-12-28 23:23 UTC
Labels: enhancement

**Comment by VolodyaCO** [comment] 2023-01-02 13:45
Sounds good @mdhaber. Thanks for your quick response. Yes, I was checking the callbacks, but they are not enabled for powell as of now. I'm glad they will be enabled in the future for intermediate results, as this would certainly solve what I want.

**Comment by mdhaber** [comment] 2023-01-02 16:23
Would you like to take this for a test drive? Nightly wheels are at https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/. The 1.11 dev wheels should have them soon (although perhaps not yet, since gh-17616 only merged five days ago).

**Comment by VolodyaCO** [comment] 2023-01-03 22:10
Hi @mdhaber . I've added this:
```python
# Callback
class MyCallback:
    best_val = np.inf
    best_x = None
    def __call__(self, intermediate_result: OptimizeResult) -> None:
        x = intermediate_result.x
        fval = intermediate_result.fun
        if fval < self.best_val:
            self.best_val = fval
            self.best_x = x
```
and I'm running `minimize` as
```python
# Definition of the optimiser
x0 = np.array([4.65116802, 4.42985893, 1.74720157, 4.29727392])
callback = MyCallback()
rs = minimize(langermann, x0, method="Powell", bounds=Bounds(lb=np.zeros(4), ub=np.ones(4) * 10), options={"maxfev": 1000}, callback=callback)
print(rs)
print(callback.best_x, callback.best_val)```

but I'm getting a strange error:
```zsh
File ~/micromamba/envs/zapata/lib/python3.8/site-packages/scipy/optimize/_optimize.py:3421, in _minimize_powell(func, x0, args, callback, bounds, xtol, ftol, maxiter, maxfev, disp, direc, return_all, **unknown_options)
   3419     allvecs.append(x)
   3420 intermediate_result = OptimizeResult(x=x, fun=fval)
-> 3421 if _call_callback_maybe_halt(callback, intermediate_result):
   3422     break
   3423 bnd = ftol * (np.abs(fx) + np.abs(fval)) + 1e-20

File ~/micromamba/envs/zapata/lib/python3.8/site-packages/scipy/optimize/_optimize.py:180, in _call_callback_maybe_halt(callback, res)
    178     return False
    179 try:
--> 180     callback(res)
    181     return False
    182 except StopIteration:

File ~/micromamba/envs/zapata/lib/python3.8/site-packages/scipy/optimize/_optimize.py:155, in _wrap_callback.<locals>.wrapped_callback(res)
    154 def wrapped_callback(res):
--> 155     return callback(np.copy(res.x))

Cell In [1], line 10, in MyCallback.__call__(self, intermediate_result)
      9 def __call__(self, intermediate_result: OptimizeResult) -> None:
---> 10     x = intermediate_result.x
     11     fval = intermediate_result.fun
     12     if fval < self.best_val:

AttributeError: 'numpy.ndarray' object has no attribute 'x'
```
which doesn't make sense. It is clear that `intermediate_result` is an `OptimizeResult` instance, with `x` and `fun` defined.

**Comment by mdhaber** [comment] 2023-01-03 22:28
mmm we may have an issue because as a method of a class, your `__call__` actually accepts _two_ arguments technically. So the signature of this method is not what is expected, and the method only gets passed an array `x`.

> It is clear that `intermediate_result` is an `OptimizeResult` instance, with x and fun defined.

I think it's clear that `intermediate_result` is _not_ an `OptimizeResult`; it is an array.

**Comment by VolodyaCO** [comment] 2023-01-06 15:11
Hi, the version is `1.11.0.dev0+0.3bac8f1`, which I think is the correct one. This is the new code:
```python
import numpy as np
import warnings
from scipy.optimize import minimize, Bounds, OptimizeResult
import scipy

print("Scipy version", scipy.__version__)

# Definition of the function
langer_c = np.array([6, 1, 4, 4, 8])
langer_A = np.array([[4, 6, 3, 5],
       [8, 7, 9, 9],
       [2, 7, 8, 8],
       [9, 2, 6, 9],
       [5, 4, 1, 4]])
def langermann(x: np.ndarray) -> float:
    if np.any((x > 10) | (x < 0)):
        warnings.warn(
            "The Langer function should be evaluated in the [0, 10] box", UserWarning
        )
    sum_ = np.sum(np.subtract(langer_A, x) ** 2, axis=1)
    vec = np.exp(-1 / np.pi * sum_) * np.cos(np.pi * sum_)
    result = np.dot(langer_c, vec)
    print(f"For input {x} the function value is {result}")
    return result

# Callback
class MyCallback:
    best_val = np.inf
    best_x = None
    def __call__(self, intermediate_result: OptimizeResult) -> None:
        x = intermediate_result.x
        fval = intermediate_result.fun
        if fval < self.best_val:
            self.best_val = fval
            self.best_x = x

# Definition of the optimiser
x0 = np.array([4.65116802, 4.42985893, 1.74720157, 4.29727392])
my_cb_object = MyCallback()
callback = lambda x: my_cb_object(x)
rs = minimize(langermann, x0, method="Powell", bounds=Bounds(lb=np.zeros(4), ub=np.ones(4) * 10), options={"maxfev": 1000}, callback=callback)
print(rs)
print(callback.best_x, callback.best_val)
```

But I keep getting the same error: 
```zsh
AttributeError                            Traceback (most recent call last)
Cell In [2], line 41
     39 my_cb_object = MyCallback()
     40 callback = lambda x: my_cb_object(x)
---> 41 rs = minimize(langermann, x0, method="Powell", bounds=Bounds(lb=np.zeros(4), ub=np.ones(4) * 10), options={"maxfev": 1000}, callback=callback)
     42 print(rs)
     43 print(callback.best_x, callback.best_val)

File ~/micromamba/envs/zapata/lib/python3.8/site-packages/scipy/optimize/_minimize.py:700, in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    697     res = _minimize_neldermead(fun, x0, args, callback, bounds=bounds,
    698                                **options)
    699 elif meth == 'powell':
--> 700     res = _minimize_powell(fun, x0, args, callback, bounds, **options)
    701 elif meth == 'cg':
    702     res = _minimize_cg(fun, x0, args, jac, callback, **options)

File ~/micromamba/envs/zapata/lib/python3.8/site-packages/scipy/optimize/_optimize.py:3421, in _minimize_powell(func, x0, args, callback, bounds, xtol, ftol, maxiter, maxfev, disp, direc, return_all, **unknown_options)
   3419     allvecs.append(x)
   3420 intermediate_result = OptimizeResult(x=x, fun=fval)
-> 3421 if _call_callback_maybe_halt(callback, intermediate_result):
   3422     break
   3423 bnd = ftol * (np.abs(fx) + np.abs(fval)) + 1e-20

File ~/micromamba/envs/zapata/lib/python3.8/site-packages/scipy/optimize/_optimize.py:180, in _call_callback_maybe_halt(callback, res)
    178     return False
    179 try:
--> 180     callback(res)
    181     return False
    182 except StopIteration:

File ~/micromamba/envs/zapata/lib/python3.8/site-packages/scipy/optimize/_optimize.py:155, in _wrap_callback.<locals>.wrapped_callback(res)
    154 def wrapped_callback(res):
--> 155     return callback(np.copy(res.x))

Cell In [2], line 40, in <lambda>(x)
     38 x0 = np.array([4.65116802, 4.42985893, 1.74720157, 4.29727392])
     39 my_cb_object = MyCallback()
---> 40 callback = lambda x: my_cb_object(x)
     41 rs = minimize(langermann, x0, method="Powell", bounds=Bounds(lb=np.zeros(4), ub=np.ones(4) * 10), options={"maxfev": 1000}, callback=callback)
     42 print(rs)

Cell In [2], line 31, in MyCallback.__call__(self, intermediate_result)
     30 def __call__(self, intermediate_result: OptimizeResult) -> None:
---> 31     x = intermediate_result.x
     32     fval = intermediate_result.fun
     33     if fval < self.best_val:

AttributeError: 'numpy.ndarray' object has no attribute 'x'
```

**Comment by mdhaber** [comment] 2023-01-06 16:39
It depends on when build was created. This feature didn't merge very long ago. I'll test out this code and report back.

**Comment by mdhaber** [comment] 2023-01-06 17:38
Oops, I meant `callback = lambda intermediate_result: my_cb_object(intermediate_result)`. 

![image](https://user-images.githubusercontent.com/6570539/211063077-c19d6e1f-90a7-4ab1-8e63-6881feadf2a5.png)

But I'll fix this so that the new callback interface can be used by methods of classes.

---

Unfortunately, it looks like `callback` is not called from the initial point, which has the best objective function value, so the best objective function value still does not end up in `best_x`.

When the constraints are inexpensive to evaluate, there is always the option to store the result in the objective function itself to make sure you don't miss a thing:
```python3
def langermann(x: np.ndarray) -> float:
    if np.any((x > 10) | (x < 0)):
        warnings.warn(
            "The Langer function should be evaluated in the [0, 10] box", UserWarning
        )
    sum_ = np.sum(np.subtract(langer_A, x) ** 2, axis=1)
    vec = np.exp(-1 / np.pi * sum_) * np.cos(np.pi * sum_)
    result = np.dot(langer_c, vec)
    # print(f"For input {x} the function value is {result}")
    if result < langermann.best_val and np.all(x < 10) and np.all(x > 0):
        langermann.best_val = result
        langermann.best_x = x
    return result
langermann.best_val = np.inf
langermann.best_x = None
```
