### ISSUE TITLE
DOC: scipy.interpolate.RegularGridInterpolator and interpn works for rectilinear grids, not just regular grids.

### ISSUE THREAD

**Issue by mountaindust** [scipy/scipy#16121] opened 2022-05-04 23:05 UTC
### Issue with current documentation:

The documentation for scipy.interpolate.RegularGridInterpolator describes the class as for "Interpolation on a regular grid in arbitrary dimensions" and there is this statement, "The data must be defined on a regular grid; the grid spacing however may be uneven." Isn't such a grid a rectilinear grid, and not explicitly *not* a regular grid? See [Regular Grid](https://en.wikipedia.org/wiki/Regular_grid).

The really odd thing about all of this is that the code on which this class is based, *regulargrid* by Johannes Buchner, seems to make the same mistake. In the README for the [regulargrid repo](https://github.com/JohannesBuchner/regulargrid), it even links the wikipedia article I've just referenced here at the top. Then it goes on to describe a Cartesian Grid as one with equal spacing between points (correct, but that spacing has to also be equal across each dimension) and a Regular Grid as having unequal spacing between points (incorrect). Beneath this definition of "Cartesian grid", there's an example of a grid which is Regular but not Cartesian. 

Just to make sure that the "Regular grid" was actually rectilinear, I checked regulargrid/test/test_regulargrid.py.  On line 13, the breaks are distributed randomly in each of two spatial dimensions, making it in fact rectilinear and not regular.

I can also confirm that the same mistake is made in scipy.interpolate.interpn - I've used this code on rectilinear grids and it seems to work fine, despite the method saying that a "regular grid" is required many times in the documentation.

I think correcting this is important - I tried for hours to find a rectilinear grid interpolator so that I could use it instead of interpn... it turns out I need not have bothered!

### Suggested fix:

The documentation for scipy.interpolate.RegularGridInterpolator and scipy.interpolate.interpn should be updated to specify that the interpolation happens on a rectilinear grid rather than a regular grid.

**Comment by tupui** [comment] 2022-05-05 09:03
Hi @mountaindust, thank you for reporting. Isn't this a duplicate of the discussion we had in #14926?

**Comment by ev-br** [comment] 2022-05-05 10:49
Just to add to what Pamphile said, https://github.com/scipy/scipy/pull/16073 went in yesteday, so the word _rectilinear _ is now live in the dev version of the documentation (to become 1.9.0 when it is released):  

http://scipy.github.io/devdocs/reference/generated/scipy.interpolate.RegularGridInterpolator.html#scipy.interpolate.RegularGridInterpolator

If you have a better wording or additions to the docstring, pull requests are most welcome!

**Comment by ev-br** [comment] 2022-05-05 15:03
For the record, and in my personal opinion, it starts pushing towards the overly rigoristic territory.  A user cannot expect that all Bravais lattices (and its N-D generalizations) are magically supported. However, personal opinions aside, would you be interested in sending a PR e.g. your wording @mountaindust ?

**Closed** 2022-05-05 20:43 UTC
Labels: scipy.interpolate, Documentation

**Comment by mueslo** [comment] 2023-04-12 09:39
> For the record, and in my personal opinion, it starts pushing towards the overly rigoristic territory. A user cannot expect that all Bravais lattices (and its N-D generalizations) are magically supported. However, personal opinions aside, would you be interested in sending a PR e.g. your wording @mountaindust ?

On the contrary, in a project like **sci**py, you would expect rigorous correctness.

**Comment by tupui** [comment] 2023-04-12 10:32
@mueslo to add on to what Evgeni said. The nuance is around "overly" rigoristic. Our goal is to have robust, proven and rigorous implementations, but we have to make decisions around API, usability, discoverability, etc. It has a cost and we do sometimes need to make some compromises. From not including some methods, to some simplifications in the documentation, or in the code. Having said that, we are happy to discuss things and enhancements on the doc, etc. are always welcomed 😃
