### ISSUE TITLE
scipy.stats.kendaltau() p value not in agreement with R, SPSS and Excel's Real Statistics kendall tau-b tests

### ISSUE THREAD

**Issue by gmonkman** [scipy/scipy#6314] opened 2016-06-26 13:50 UTC
Running scipy.stats.kendalltau on attached data gives tau = 0.12017 and two-tailed p = 0.0666

Running same test (kenall tau-b) in R (cor.test), SPSS (NONPAR CORR) and the Excel Real-Statistics addin gives same value of tau but p = 0.099 in all 3 packages.
[fmmnonzero.txt](https://github.com/scipy/scipy/files/333596/fmmnonzero.txt)

**Comment by jeffrutledge** [comment] 2016-06-28 20:50
Using the definitions of tau-a and tau-b on the [Kendall tau Wikipedia page](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), the problem with the current implementation of the `scipy.stats.kendalltau` is that the z-statistic it uses does not correct for ties.
Thus, the p value it generates is not the correct tau-b p value.

The current scipy implementation calculates the tau-b statistic, but uses the z_A statistic, defined on the Wikipedia page, to calculate the p value. This z-statistic is intended for use with tau-a, which does not correct for ties.

If the Wikipedia page is correct then the function should be modified so it uses the z_B statistic, defined on the Wikipedia page, which is intended for the tau-b statistic and does account for ties.

**Comment by WarrenWeckesser** [comment] 2016-07-04 04:45
This issue looks like a duplicate of https://github.com/scipy/scipy/issues/5755.

**Comment by ev-br** [comment] 2016-11-06 22:30
On master, running it with the attachment from OP produces

```
In [2]: data = np.loadtxt('/home/br/temp/kendalltau_data_gh6314.txt', delimiter=',')

In [3]: data.shape
Out[3]: (107, 2)

In [4]: import scipy.stats as stats

In [5]: stats.kendalltau(data[:, 0], data[:, 1])
Out[5]: KendalltauResult(correlation=0.12016561327309691, pvalue=0.099325137498545532)
```

So the issue has been fixed by gh-6677.

**Closed by ev-br** 2016-11-06 22:30 UTC
Labels: defect, scipy.stats
