### ISSUE TITLE
ETA for next release

### ISSUE THREAD

**Issue by skoudoro** [scipy/scipy#9078] opened 2018-07-26 15:29 UTC
Hi Scipy Team, 

We were wondering when will be the next `Scipy` release.

We have some issue due to `scipy.fftpack` since `numpy 1.15` released a few days ago. As you can see [here](https://travis-ci.org/nipy/dipy/jobs/408195332#L10000) and [here](https://travis-ci.org/nipy/dipy/builds/408195331), all our Travis buildbots are failing. The good news is that the fix is already in your master (PR #8879 ) and we wonder whether we should wait for your release or we should create a temporary patch in our repo.

**Comment by rgommers** [comment] 2018-07-26 15:36
We aim to release every 6 months, so about the end of October.

The failures are not due to an exception, but due to the `FutureWarning` being repeated so TravisCI aborts after log length becomes too large. That's unforeseen. You should probably just change the behavior of that warning from `always` to the default behavior (once).

**Comment by rgommers** [comment] 2018-07-26 15:36
Closing because the issue is already fixed. Feel free to continue the discussion though.

**Closed by rgommers** 2018-07-26 15:36 UTC
Labels: query

**Comment by skoudoro** [comment] 2018-07-26 16:06
> We aim to release every 6 months, so about the end of October.

Good to know, thanks for this info.

> You should probably just change the behavior of that warning from always to the default behavior (once).

Thanks for the feedback @rgommers
