### ISSUE TITLE
special.softmax() should support pd.DataFrame as input

### ISSUE THREAD

**Issue by thenineteen** [scipy/scipy#12164] opened 2020-05-19 12:22 UTC
**Is your feature request related to a problem? Please describe.**
when the input df is of type pandas.core.frame.DataFrame, softmax(df) doesn't work:

gives this error

```
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py in _align_method_FRAME(left, right, axis)
    662             else:
    663                 raise ValueError(
--> 664                     "Unable to coerce to DataFrame, shape "
    665                     f"must be {left.shape}: given {right.shape}"
    666                 )
```

**Describe the solution you'd like**
should be able to run softmax(df)

**Describe alternatives you've considered**
currently have to either run:
```
softmax(df.values)
```

or 

```
softmax(np.array(df))
```

**Additional context (e.g. screenshots)**

**Comment by tirthasheshpatel** [comment] 2020-05-19 12:59
The problem is that pandas ``DataFrame`` cannot operate on multidimensional arrays that are not of the same shape as DataFrame. I think that this is a pandas issue rather than SciPy's. SciPy actually preserves the dimension of the input array to avoid NumPy's right align broadcast property.

**Comment by thenineteen** [comment] 2020-05-19 13:25
why can't it convert the df to np.array or take its values and then return in the original df format?

**Comment by tirthasheshpatel** [comment] 2020-05-19 14:31
SciPy was never made to support DataFrames in the first place. It only supports numpy arrays and Python lists. As pandas uses numpy backend, DataFrame objects get coerced to numpy arrays which are supported by SciPy. It would be a pretty big (and daunting) task to support pandas DataFrames as backend and maybe SciPy will support them in future.

**Comment by ev-br** [comment] 2020-05-19 15:16
FWIW, here's a -1 on explicitly special-casing DataFrames.

**Comment by josef-pkt** [comment] 2020-05-19 15:32
I don't think that's special casing pandas.

The function is missing `asarray` to support general "array_like"

**Comment by ilayn** [comment] 2020-05-19 16:07
To be honest, `df.values` or `df.to_numpy()` is more than enough convenience. If this is happening too often make a tiny wrapper for it.

**Comment by josef-pkt** [comment] 2020-05-19 16:36
it's the same problem with other `__array__`
currently it's just priority for numpy minus if input is list

I thought asarray is the standard pattern, and the other functions have it

**Comment by thenineteen** [comment] 2020-05-19 17:45
> To be honest, `df.values` or `df.to_numpy()` is more than enough convenience for my taste. If this is happening too often make a tiny wrapper for it. Missing asarray is another story.

One loses the structure of the DataFrame when using the .values attribute. Say the df represents two-categorical dimensions. After running `softmax(df.values)` the indices and columns need to be reindex_like or equivalent.

**Comment by josef-pkt** [comment] 2020-05-19 18:56
FWIW, I agree that a pandas or xarray or ... data structures shouldn't be returned.
Especially, scipy.special wouldn't be the place to start to support it, IMO, because those are in general not typical datascience functions for end users.

`pd.DataFrame(special.softmax(df), index=df.index, columns=df_columns)`
should work (after fixing asarray), 
(but maybe you want to change column names.)

**Comment by WarrenWeckesser** [comment] 2020-05-19 18:57
I agree with @josef-pkt, we should pass `x` through `asarray` in `softmax`; this will prevent the exception.  The return value will be a numpy array, as it is for many numpy and scipy functions:

```
In [144]: df
Out[144]: 
   0  1
0  1  1
1  3  2
2  5 -1
3  0  1

In [145]: softmax(np.asarray(df))
Out[145]: 
array([[0.01466089, 0.01466089],
       [0.10833011, 0.03985242],
       [0.80045724, 0.00198414],
       [0.00539344, 0.01466089]])
```

**Comment by WarrenWeckesser** [comment] 2020-05-19 19:24
Actually, we can use `asanyarray`, to preserve subclasses.  For example, here `m` is a `numpy.matrix`, which is a subclass of `numpy.ndarray`:

```
In [181]: m
Out[181]: 
matrix([[ 1,  1],
        [ 3,  2],
        [ 5, -1],
        [ 0,  1]])

In [182]: softmax(np.asanyarray(m))
Out[182]: 
matrix([[0.01466089, 0.01466089],
        [0.10833011, 0.03985242],
        [0.80045724, 0.00198414],
        [0.00539344, 0.01466089]])
```
The function will still return a numpy array when given a Pandas DataFrame, because a DataFrame is not a subclass of `numpy.ndarray`.

**Comment by rlucas7** [comment] 2020-07-05 15:46
FWIW we do already have functions in stats that will perform calculations on pandas dataframes via passing through `_chk2_asarray()`, IIRC there was some inconsistency in usage of that vs `_chk_asarray()` which only handled 1-d arrays. 

see e.g. my answer here: 

https://stackoverflow.com/a/59014338/3164100

IIRC that function coerces to numpy array.

**Comment by mdhaber** [comment] 2024-09-08 10:09
Incidentally, this was fixed by gh-16186. `softmax` is still not a ufunc, so it does not *return* a Pandas DF like `ndtr` and such, but the concensus here was just that it should accept DFs as input (e.g. by calling `asarray`) and now it does.

**Closed by mdhaber** 2024-09-08 10:09 UTC
Labels: defect, scipy.special
