### ISSUE TITLE
travis failing on OSX - scipy.stats.tests.test_mstats_extras.test_hdmedian and mpmath.libmp.BACKEND

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#8326] opened 2018-01-25 06:03 UTC
From travis logs:

```
=================================== FAILURES ===================================
________________________________ test_hdmedian _________________________________
[gw2] darwin -- Python 3.6.4 /Users/travis/build/scipy/scipy/venv/bin/python
    def test_hdmedian():
        # 1-D array
        x = ma.arange(11)
>       assert_equal(ms.hdmedian(x), 5)
E       AssertionError: 
E       Arrays are not equal
E       
E       (mismatch 100.0%)
E        x: MaskedArray(5.)
E        y: array(5)
x          = masked_array(data=[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
             mask=False,
       fill_value=999999)
scipy/stats/tests/test_mstats_extras.py:23: AssertionError
=============================== warnings summary ===============================
build/testenv/lib/python3.6/site-packages/scipy/linalg/tests/test_basic.py::TestLstsq::()::test_simple_exact
  /Users/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/linalg/tests/test_basic.py:956: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
    overwrite_b=overwrite)
build/testenv/lib/python3.6/site-packages/scipy/linalg/tests/test_basic.py::TestLstsq::()::test_simple_overdet
  /Users/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/linalg/tests/test_basic.py:988: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
    overwrite_b=overwrite)
```

**Comment by andyfaff** [comment] 2018-01-25 09:57
Not sure it's a numpy thing. I wonder if it's a ccache issue somehow.

**Comment by andyfaff** [comment] 2018-01-26 10:27
Don't know what's going on. Travis seems to be suddenly working again.

**Comment by pv** [comment] 2018-01-26 10:30
When reporting travis failures, note also which of the builders failed. 
If it's the one that uses numpy master, then spurious failures that 
appear and disappear can be caused by changes in numpy development version.

**Comment by pv** [comment] 2018-01-26 10:33
Ok, it looks like the osx builder. Then the reason for the failure is 
really unclear...

**Comment by andyfaff** [comment] 2018-01-26 10:33
It was the osx test which uses pip installed numpy.

**Comment by andyfaff** [comment] 2018-01-26 10:36
https://travis-ci.org/scipy/scipy/jobs/332820399

**Comment by andyfaff** [comment] 2018-01-27 01:54
Another weird issue is that sometimes the OSX test fails when examining the mpmath backend.
This line also fails on my home computer (which uses conda numpy 1.14 and conda mpmath):

```
(dev3) 192-168-1-3:scipy andrew$ python -c 'import mpmath.libmp; assert mpmath.libmp.BACKEND == "gmpy"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
(dev3) 192-168-1-3:scipy andrew$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  3 2017, 12:34:11) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mpmath
>>> import mpmath.libmp
>>> mpmath.libmp.BACKEND
'python'
```

**Comment by andyfaff** [comment] 2018-01-27 02:01
So two recent tests that differ are:

https://travis-ci.org/scipy/scipy/jobs/333969335 (gets past this point and succeeds)
but
https://travis-ci.org/andyfaff/scipy/builds/333993409 fails the mpmath assertion.

The different forks aren't too dissimilar. Sometimes restarting the job works.

**Comment by andyfaff** [comment] 2018-01-27 02:09
It appears the default backend on mpmath-1.0.0 (conda or pip installed) is 'python'.
Does it matter if the `mpmath.libmp.BACKEND=="gmpy"`?

**Comment by andyfaff** [comment] 2018-01-28 03:52
I think the hdmedian problem has been fixed, and I've not seen the mpmath backend problem so far, so closing.

**Comment by matthew-brett** [comment] 2018-06-04 16:23
I'm seeing this problem again in the scipy-wheel tests, only on macOS, and (perhaps coincidentally) with Scipy linked against OpenBLAS:

* [Build matrix](https://travis-ci.org/matthew-brett/scipy-wheels/builds/387819608)
* [Example failure](https://travis-ci.org/matthew-brett/scipy-wheels/jobs/387819627)

**Comment by matthew-brett** [comment] 2018-06-05 10:51
Tests failing on Python 3 and not Python 2.7.

**Comment by matthew-brett** [comment] 2018-06-05 18:17
Oops - I was testing the 1.0.0 release commit.  Now I'm testing master, I'm getting missing symbols, so closing this one again for now, will reopen, if fixing the missing symbols brings back the error.

**Closed by matthew-brett** 2018-06-05 18:17 UTC
