### ISSUE TITLE
"bool any" error for scipy.spatial.SphericalVoronoi

### ISSUE THREAD

**Issue by sbh9** [scipy/scipy#6982] opened 2017-01-25 19:57 UTC
Hello everyone! I've been working on a program that uses scipy.spatial.SphericalVoronoi, and I've run into a problem when running it with large numbers.

For starters, I have been using the example code found [here](http://scipy.github.io/devdocs/generated/scipy.spatial.SphericalVoronoi.html). I have changed only two things in this code: 
1. I commented out the lines that plotted generator points and Voronoi vertices by placing a # in front of the line.
2. I commented out the line that provided a set of points, and have instead been using a separate program to generate an array of Fibonacci points in the form of (x, y, z) coordinates.

[Here](https://github.com/scipy/scipy/files/730776/base.txt) is my modified example code.

I've been using spyder for everything. So far, the modified example code has been working well. However, I have run into some difficulties when using it on arrays larger than 30,000 total points. I receive one of two error messages when a run a larger array:

>  Traceback (most recent call last):
> 
>   File "<ipython-input-1-5987efb2fda1>", line 1, in <module>
>     runfile('C:/Users/shurtt1/Desktop/sphfib.py', wdir='C:/Users/shurtt1/Desktop')
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
> 
>   File "C:/Users/shurtt1/Desktop/sphfib.py", line 27, in <module>
>     sv = SphericalVoronoi(points, radius, center)
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 229, in __init__
>     self._calc_vertices_regions()
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 268, in _calc_vertices_regions
>     -1) == generator_indices).any(axis=1))
> 
> AttributeError: 'bool' object has no attribute 'any'

or

> Traceback (most recent call last):
> 
>   File "<ipython-input-4-5987efb2fda1>", line 1, in <module>
>     runfile('C:/Users/shurtt1/Desktop/sphfib.py', wdir='C:/Users/shurtt1/Desktop')
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
> 
>   File "C:/Users/shurtt1/Desktop/sphfib.py", line 27, in <module>
>     sv = SphericalVoronoi(points, radius, center)
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 229, in __init__
>     self._calc_vertices_regions()
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 268, in _calc_vertices_regions
>     -1) == generator_indices).any(axis=1))
> 
>   File "C:\Users\shurtt1\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\_methods.py", line 38, in _any
>     return umr_any(a, axis, dtype, out, keepdims)
> 
> MemoryError

I would say about 80% of error messages I get are the bool any error, while the remaining 20% are the memory error. The memory error makes sense to me - I am working with a lot of points, on a 12 GB computer. However, the bool any error really confuses me. I can't see any reason why I would be getting the bool any error message, especially because once I go above about 30,000 total points there doesn't seem to be any rhyme or reason as to whether the program will run, and which error message it will return if it fails to run. Does anyone have any suggestions as to what could be causing the bool any error?

**Comment by pv** [comment] 2017-01-25 21:40
@tylerjereddy, cf

**Comment by tylerjereddy** [comment] 2017-01-28 01:09
This matches the memory traceback recently reported by another user in #6811. The space complexity of the code in scipy 0.18.1 is indeed rather poor. I patched the issue in the master branch in a recently-merged PR (see: #6828 ). 

@sbh9 if you could test your code with the master branch (scipy 0.19) and confirm that the issue is resolved that would be most helpful -- I'm missing the `fs1` module needed to execute your code.

That said, this is a traceback to the exact same line with the same error message, so I suspect it is the same problem that has recently been resolved. As an aside, the code should tolerate at least 10 million points pretty well now, and appears to be exhibiting loglinear time complexity (should be much faster in master branch). Note that 10 million points should take a few minutes to run, but more normal data sizes should be quite fast!

**Comment by tylerjereddy** [comment] 2018-03-30 17:14
Issue should be resolved now as discussed above & no additional discussion / complaints here for > 1 year. If there is still a problem this can be reopened if I'm provided with a reproducible example of failure using the current master branch.

**Closed by tylerjereddy** 2018-03-30 17:14 UTC
Labels: scipy.spatial
