### ISSUE TITLE
Compiled code coverage with `--gcov` doesn't work with Meson

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#15896] opened 2022-03-29 19:32 UTC
For how this is supposed to work, see the PR description of gh-3021. It works with `python runtests.py --gcov`, but doesn't work with `dev.py`:
```
$ python dev.py --gcov
Removing previous GCOV .gcda files...
The Meson build system
Version: 0.62.0
Source dir: /home/rgommers/code/scipy
Build dir: /home/rgommers/code/scipy/build
Build type: native build
Project name: SciPy
Project version: 1.9.0.dev0

meson.build:1:0: ERROR: Executables created by c compiler /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc --coverage are not runnable.

A full log can be found at /home/rgommers/code/scipy/build/meson-logs/meson-log.txt
```
I made no attempt to figure out why yet.

Full log:

<details>

```
$ cat build/meson-logs/meson-log.txt 
Build started at 2022-03-29T22:07:44.629711
Main binary: /home/rgommers/anaconda3/envs/scipy-dev/bin/python3.10
Build Options: -Dprefix=/home/rgommers/code/scipy/build-install
Python system: Linux
The Meson build system
Version: 0.62.0
Source dir: /home/rgommers/code/scipy
Build dir: /home/rgommers/code/scipy/build
Build type: native build
Project name: SciPy
Project version: 1.9.0.dev0
Sanity testing C compiler: /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc --coverage
Is cross compiler: False.
Sanity check compiler command line: /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc --coverage sanitycheckc.c -o sanitycheckc.exe -Wno-unused-function -Wno-conversion -Wno-misleading-indentation -Wno-incompatible-pointer-types -D_FILE_OFFSET_BITS=64 -pthread -B /home/rgommers/anaconda3/envs/scipy-dev/compiler_compat -shared -Wl,-rpath,/home/rgommers/anaconda3/envs/scipy-dev/lib -Wl,-rpath-link,/home/rgommers/anaconda3/envs/scipy-dev/lib -L/home/rgommers/anaconda3/envs/scipy-dev/lib -Wl,-rpath,/home/rgommers/anaconda3/envs/scipy-dev/lib -Wl,-rpath-link,/home/rgommers/anaconda3/envs/scipy-dev/lib -L/home/rgommers/anaconda3/envs/scipy-dev/lib --coverage
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/rgommers/code/scipy/build/meson-private/sanitycheckc.exe

meson.build:1:0: ERROR: Executables created by c compiler /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc --coverage are not runnable.
```

</details>

@Smit-create is this something you could look at?

**Comment by rgommers** [comment] 2022-03-29 19:35
Once that works, `--lcov-html` should work too (assuming `lcov` is installed - easiest on Linux).

**Comment by Smit-create** [comment] 2022-03-29 19:54
Yeah, I'll look into it.

**Comment by eli-schwartz** [comment] 2022-03-29 20:44
Why is the C compiler `x86_64-conda-linux-gnu-cc --coverage`? It might make more sense to use Meson's `-Db_coverage=true`.

(This also sets up Meson's own coverage report generation targets, but creating in-tree coverage data might require figuring out editable installs, so that's a problem for a different time, probably.)

**Comment by Smit-create** [comment] 2022-03-31 13:22
> It might make more sense to use Meson's `-Db_coverage=true`.

I followed the following steps:
1. `$ meson setup build -Db_coverage=true --prefix=$PWD/build-install`
2. `$ ninja -C build`
3.
```
$ meson test
No tests defined.
```
4.
```
$ meson compile coverage-html

ERROR: Can't invoke target `coverage-html`: target not found
```

**Comment by eli-schwartz** [comment] 2022-03-31 14:32
Right, my suggestion was about adding the right compiler flags automatically since Meson knows how to do that. I didn't say you should use `meson test`.

(You already have a test harness that AFAIK is performing admirably, so there's no pressing need to replace it like there was a need to replace numpy.distutils)

I would just use meson's coverage option to ensure that compiler detection of coverage compiler flags is done, and at the right place, solely as a replacement for passing `--coverage` as the $CC or $CFLAGS. Ignore Meson's gcovr/lcov integration.

**Comment by eli-schwartz** [comment] 2022-03-31 14:35
Particularly I don't think coverage should be in the $CC as that affects meson `compiler.links()` tests, the sanity check "does this compiler work to create valid executables" test, and similar. Those should not be compiled with coverage, and doing so might be what is causing your errors. I got some really weird warnings when I tested doing that myself.

**Comment by Smit-create** [comment] 2022-04-09 08:59
I think the following works:
1. Setting up meson build:
```
meson setup build --prefix=$PWD/build-install -Db_coverage=true
```
2. Building and Installing with `dev.py`:
```
python dev.py --gcov
```
3. Generating lcov
```
python dev.py --lcov-html
```

**Comment by rgommers** [comment] 2022-04-12 10:32
Works with `runtests.py`:
```
$ python runtests.py --gcov
$ find build -name '*.gcno' -type f -exec gcov -pb {} +
....
File 'build/src.linux-x86_64-3.10/build/src.linux-x86_64-3.10/build/src.linux-x86_64-3.10/scipy/sparse/linalg/_isolve/iterative/fortranobject.c'
Lines executed:2.38% of 504
Branches executed:1.32% of 454
Taken at least once:0.66% of 454
Calls executed:2.78% of 108
Creating 'build#src.linux-x86_64-3.10#build#src.linux-x86_64-3.10#build#src.linux-x86_64-3.10#scipy#sparse#linalg#_isolve#iterative#fortranobject.c.gcov'

File 'build/src.linux-x86_64-3.10/build/src.linux-x86_64-3.10/build/src.linux-x86_64-3.10/scipy/sparse/linalg/_eigen/arpack/fortranobject.c'
Lines executed:9.13% of 504
Branches executed:7.93% of 454
Taken at least once:4.41% of 454
Calls executed:9.26% of 108
Creating 'build#src.linux-x86_64-3.10#build#src.linux-x86_64-3.10#build#src.linux-x86_64-3.10#scipy#sparse#linalg#_eigen#arpack#fortranobject.c.gcov'
```

**Comment by rgommers** [comment] 2022-04-12 10:53
`python runtests.py --lcov-html` works as well, as noted on gh-15968:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/98330/162944326-7d01c6c3-afa5-4c0c-aac1-58d4eb7f722a.png">

Unclear if the results are correct, test coverage seems incomplete. I only had a brief look, but this should be a start to be able to fix things up.

**Comment by rgommers** [comment] 2022-04-12 10:57
See also this short blog post for some explanation: https://emptysqua.re/blog/code-coverage-python-c-extensions/

**Comment by Smit-create** [comment] 2022-04-23 04:47
I was trying to generate the html report using `runtests.py` but was unable to do so. I used the following steps:
```
$ python runtests.py --gcov

$ find build -name '*.gcno' -type f -exec gcov -pb {} +
...
File 'scipy/interpolate/interpnd.c'
Lines executed:31.84% of 9102
Branches executed:32.12% of 5399
Taken at least once:17.19% of 5399
Calls executed:30.49% of 1584
Creating 'scipy#interpolate#interpnd.c.gcov'

$ python runtests.py --lcov-html
...
geninfo: WARNING: /home/admin-pc/Smitlunagariya/scipy/build/temp.linux-x86_64-3.10/scipy/interpolate/src/_fitpackmodule.gcno: Overlong record at end of file!
geninfo: WARNING: cannot find an entry for __fitpack.h##18350a1cd763f8c00cdda54abc712d55.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for __multiarray_api.h##f5877d835142285458de2973122a6506.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for _fitpackmodule.c##0069da34f212e4ba6a39a797207c071c.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for ndarraytypes.h##8b8b9fad941d415b08a73d5fd909717f.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for object.h##4d6ce8ad5ef5f4d125b18c0382a8112e.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for string3.h##f5632556f1e10ac4360f8614efefb3b2.gcov in .gcno file, skipping file!
Generating lcov HTML output...
genhtml: ERROR: no valid records found in tracefile /home/admin-pc/Smitlunagariya/scipy/build/lcov.out
genhtml failed!

```
Am I missing something?

**Comment by czgdp1807** [comment] 2024-11-18 05:29
Current status - I executed, `python dev.py build --gcov` doesn't produce anything inside `build`,

```zsh
(scipy-dev) 10:58:55:~/Quansight/scipy/build % python
Python 3.12.6 | packaged by conda-forge | (main, Sep 22 2024, 14:07:06) [Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import glob
>>> glob.glob("*/*.gc*")
[]
>>> glob.glob("*/*.a*")
['scipy/libdummy_g77_abi_wrappers.a', 'scipy/libdummy_g77_abi_wrappers.a.p', 'scipy/lib_fortranobject.a', 'scipy/lib_fortranobject.a.p']
```

So I guess, its still not working and needs work. I will fix this.

**Comment by czgdp1807** [comment] 2024-11-19 15:15
Ok so, I executed the following commands in order as mentioned,

1. `python dev.pu build --gcov`
2. `python dev.py test --coverage`
3. `lcov --capture --directory build --output-file coverage.info`
4. `genhtml -q coverage.info  --output-directory out --legend --highlight`

 It doesn't work on `macOS`. I get the following error in step 2, i.e., `python dev.py test --coverage` command,

```zsh
.
.
.
ImportError while importing test module '/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/stats/tests/test_stats.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/stats/__init__.py:617: in <module>
    from ._stats_py import *
scipy/stats/_stats_py.py:38: in <module>
    from scipy import sparse
scipy/__init__.py:136: in __getattr__
    return _importlib.import_module(f'scipy.{name}')
/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/sparse/__init__.py:312: in <module>
    from . import csgraph
scipy/sparse/csgraph/__init__.py:187: in <module>
    from ._laplacian import laplacian
scipy/sparse/csgraph/_laplacian.py:7: in <module>
    from scipy.sparse.linalg import LinearOperator
scipy/sparse/linalg/__init__.py:132: in <module>
    from ._eigen import *
scipy/sparse/linalg/_eigen/__init__.py:9: in <module>
    from .arpack import *
scipy/sparse/linalg/_eigen/arpack/__init__.py:20: in <module>
    from .arpack import *
scipy/sparse/linalg/_eigen/arpack/arpack.py:50: in <module>
    from . import _arpack
E   ImportError: dlopen(/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_llvm_gcda_emit_arcs'
________________ ERROR collecting build-install/lib/python3.12/site-packages/scipy/stats/tests/test_survival.py ________________
ImportError while importing test module '/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/stats/tests/test_survival.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/stats/__init__.py:617: in <module>
    from ._stats_py import *
scipy/stats/_stats_py.py:38: in <module>
    from scipy import sparse
scipy/__init__.py:136: in __getattr__
    return _importlib.import_module(f'scipy.{name}')
/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/sparse/__init__.py:312: in <module>
    from . import csgraph
scipy/sparse/csgraph/__init__.py:187: in <module>
    from ._laplacian import laplacian
scipy/sparse/csgraph/_laplacian.py:7: in <module>
    from scipy.sparse.linalg import LinearOperator
scipy/sparse/linalg/__init__.py:132: in <module>
    from ._eigen import *
scipy/sparse/linalg/_eigen/__init__.py:9: in <module>
    from .arpack import *
scipy/sparse/linalg/_eigen/arpack/__init__.py:20: in <module>
    from .arpack import *
scipy/sparse/linalg/_eigen/arpack/arpack.py:50: in <module>
    from . import _arpack
E   ImportError: dlopen(/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_llvm_gcda_emit_arcs'
___________ ERROR collecting build-install/lib/python3.12/site-packages/scipy/stats/tests/test_tukeylambda_stats.py ____________
ImportError while importing test module '/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/stats/tests/test_tukeylambda_stats.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/stats/__init__.py:617: in <module>
    from ._stats_py import *
scipy/stats/_stats_py.py:38: in <module>
    from scipy import sparse
scipy/__init__.py:136: in __getattr__
    return _importlib.import_module(f'scipy.{name}')
/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/sparse/__init__.py:312: in <module>
    from . import csgraph
scipy/sparse/csgraph/__init__.py:187: in <module>
    from ._laplacian import laplacian
scipy/sparse/csgraph/_laplacian.py:7: in <module>
    from scipy.sparse.linalg import LinearOperator
scipy/sparse/linalg/__init__.py:132: in <module>
    from ._eigen import *
scipy/sparse/linalg/_eigen/__init__.py:9: in <module>
    from .arpack import *
scipy/sparse/linalg/_eigen/arpack/__init__.py:20: in <module>
    from .arpack import *
scipy/sparse/linalg/_eigen/arpack/arpack.py:50: in <module>
    from . import _arpack
E   ImportError: dlopen(/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_llvm_gcda_emit_arcs'
_______________ ERROR collecting build-install/lib/python3.12/site-packages/scipy/stats/tests/test_variation.py ________________
ImportError while importing test module '/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/stats/tests/test_variation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/stats/__init__.py:617: in <module>
    from ._stats_py import *
scipy/stats/_stats_py.py:38: in <module>
    from scipy import sparse
scipy/__init__.py:136: in __getattr__
    return _importlib.import_module(f'scipy.{name}')
/Users/czgdp1807/mambaforge/envs/scipy-dev/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/sparse/__init__.py:312: in <module>
    from . import csgraph
scipy/sparse/csgraph/__init__.py:187: in <module>
    from ._laplacian import laplacian
scipy/sparse/csgraph/_laplacian.py:7: in <module>
    from scipy.sparse.linalg import LinearOperator
scipy/sparse/linalg/__init__.py:132: in <module>
    from ._eigen import *
scipy/sparse/linalg/_eigen/__init__.py:9: in <module>
    from .arpack import *
scipy/sparse/linalg/_eigen/arpack/__init__.py:20: in <module>
    from .arpack import *
scipy/sparse/linalg/_eigen/arpack/arpack.py:50: in <module>
    from . import _arpack
E   ImportError: dlopen(/Users/czgdp1807/Quansight/scipy/build-install/lib/python3.12/site-packages/scipy/sparse/linalg/_eigen/arpack/_arpack.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_llvm_gcda_emit_arcs'
.
.
.
```

On Linux both of these command work, and `gcda` files are generated,

```zsh
(scipy-dev) czgdp18079@scipy-linux-9:~/Quansight/scipy$ python
Python 3.12.6 | packaged by conda-forge | (main, Sep 22 2024, 14:16:49) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import Path
>>> gcda_files = list(Path(".").rglob("*.gcda"))
>>> len(gcda_files)
841
>>> gcda_files[0:2]
[PosixPath('build/scipy/libdummy_g77_abi_wrappers.a.p/_build_utils_src_wrap_dummy_g77_abi.c.gcda'), PosixPath('build/scipy/lib_fortranobject.a.p/f98a5737d97829eed02255ad2e9ce27f72e97b78_site-packages_numpy_f2py_src_fortranobject.c.gcda')]
```

On Linux it works. Here's the output (some screenshots). It shows the coverage C/C++ code. You can check the full output at https://github.com/czgdp1807/scipy-lcov-genhtml-coverage-output and explore further.

<img width="1352" alt="Screenshot 2024-11-19 at 8 37 48 PM" src="https://github.com/user-attachments/assets/63ef98b1-092b-4150-8554-f3071698cbb4">
<img width="1352" alt="Screenshot 2024-11-19 at 8 38 23 PM" src="https://github.com/user-attachments/assets/2e4d25c5-8d14-40a2-8606-52103cd1629c">
<img width="1352" alt="Screenshot 2024-11-19 at 8 38 46 PM" src="https://github.com/user-attachments/assets/f483a9c9-39a2-4887-accd-404382202867">

Here's what I noticed somethings,

1. HTML outputs for coverage reports of Python files (this goes into `build/coverage`) and C/C++ code (for this it goes into the directory specified in `--output-directory` option of `genhtml`) go into different directories. We can provide `build/coverage` in `--output-directory` option of `genhtml`. However, I think it would be better to merge the two outputs so that a user can see everything under the same HTML page they load locally. Something for later.
2. I think when `--coverage` option is provided in `python dev.py test`, then last two commands (out of the four which I mentioned in the beginning of this comment), should execute automatically. Right now I guess they don't. May be that's something which we should to close this issue? Am I making sense here?

So that's all for now. cc: @rgommers

**Comment by eli-schwartz** [comment] 2024-11-19 15:27
IIRC the issue is that clang specifically hates the idea of linking to internal utility libraries providing helper symbols  for instrumentation, because it wants to statically link them (why?) and not inline them (interestinger and interestinger, though understandable) and as a result cannot provide them in multiple DSOs so it will only provide them for "main executables". Which means when you build shared libraries (and that's what a python extension is) you get outright load errors unless you also build cpython itself with instrumentation. Go figure.

**Comment by rgommers** [comment] 2024-11-19 18:55
I'm fine with this only working with GCC, since that was the status quo before the move to Meson as well. Let's make sure that that is reflected in the docs though, and that on macOS the user gets an informative error message rather than a confusing traceback.

>  then last two commands (out of the four which I mentioned in the beginning of this comment), should execute automatically. Right now I guess they don't. May be that's something which we should to close this issue

Yes please, that sounds like a useful thing to do. This should be as easy as possible, so `test --coverage` should prepare the coverage report and inform the developer how to open it ideally.

**Comment by czgdp1807** [comment] 2024-11-20 05:50
> Which means when you build shared libraries (and that's what a python extension is) you get outright load errors unless you also build cpython itself with instrumentation.

Just curious. By "build cpython itself with instrumentation" you mean building it with "clang" with "--coverage" flag, correct?

**Closed** 2024-12-03 17:55 UTC
Labels: Meson
