### ISSUE TITLE
BUG: scipy.optimize.curve_fit doesn't fit

### ISSUE THREAD

**Issue by sinall** [scipy/scipy#15437] opened 2022-01-20 06:32 UTC
### Describe your issue.

I want to use curve_fit to do exponential regression, so I can calculate the yearly growth rate of my data.

x is the year, y is assets. If it could fit, the growth-rate should be exp(b) - 1. But it returns (1.0, 1.0, 1.0) as popt.

### Reproducing Code Example

```python
import pandas as pd
import numpy as np
import scipy.stats as stats
from datetime import datetime
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

df = pd.DataFrame([
    [2011, 255],
    [2012, 349],
    [2013, 449],
    [2014, 554],
    [2015, 658]
], columns=['x', 'y'])

def func(x, a, b, c):
    return a * np.exp(b * x + c)

popt, pcov = curve_fit(func, df['x'], df['y'])
print('popt', popt)

df['y1'] = func(df['x'], *popt)
print('df\n', df)

plt.plot(df['x'], df['y'])
plt.plot(df['x'], df['y1'], 'g--',
            label='fit: a=%5.3f, b=%5.3f, c=%5.3f' % tuple(popt))
plt.xlabel('x')
plt.xlabel('y')
plt.legend()
plt.show()
```

### Error message

```shell
popt [1.0 1.0 1.0]
df
       x    y   y1
0  2011  255  inf
1  2012  349  inf
2  2013  449  inf
3  2014  554  inf
4  2015  658  inf
```

### SciPy/NumPy/Python version information

1.2.0 1.14.6 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)

**Comment by tupui** [comment] 2022-01-20 11:03
Hi @sinall, thanks for reporting. There is no issue here. You are trying to fit a linear relationship with an exponential model and this is why it's not working. Just change your model to `a*x+b` and you will have a great fit. I am closing this since it's not a bug but a user related question.

**Closed by tupui** 2022-01-20 11:03 UTC
Labels: defect
