### ISSUE TITLE
BUG: wrong results in sparse.linalg.lobpcg

### ISSUE THREAD

**Issue by ogauthe** [scipy/scipy#14784] opened 2021-09-29 20:50 UTC
### Describe your issue.

As first discussed in #10974 , I obtained wrong results when trying to approximate the SVD of a matrix with LOBPCG. ARPACK is fine.

The matrix can be found as a txt file at https://gist.github.com/ogauthe/63b70fd32329eac90150fa91dfb1ac67. It is pretty small with shape (504, 504), square but not symmetric, with ~78 non-zero singular values, without any degeneracy.

For `k=1`, everything is fine. For `k=2`, the result is completely wrong. For `k>7`, the functions crashes, so I suppose the problem comes from an undetected Cholesky failure, as in  #10974.

ping @lobpcg 

### Reproducing Code Example

```python
import numpy as np
import scipy.linalg as lg
import scipy.sparse.linalg as slg

A = np.loadtxt("lobpcg_fail.txt")
x = lg.norm(A)
print(A.shape, A.dtype)

k = 2
u0, s0, v0 = lg.svd(A)
u1, s1, v1 = slg.svds(A, k=k, solver="lobpcg")
u2, s2, v2 = slg.svds(A, k=k, solver="arpack")

print("dense  truncation", lg.norm(u0[:,:k] * s0[:k] @ v0[:k] - A) / x) 
print("arpack truncation", lg.norm(u2 * s2 @ v2 - A) / x) 
print("lobpcg truncation", lg.norm(u1 * s1 @ v1 - A) / x)
```

### Error message

```shell
(504, 504) float64
dense  truncation 0.002749949291553053
arpack truncation 0.0027499492915530536
lobpcg truncation 1.2256989944723657
```

### SciPy/NumPy/Python version information

1.6.2 1.20.3 sys.version_info(major=3, minor=7, micro=11, releaselevel='final', serial=0)

**Comment by lobpcg** [comment] 2021-09-29 20:57
@ogauthe thanks for reporting! I confirm the bug, getting:
(504, 504) float64
dense  truncation 0.002749949291553054
arpack truncation 0.002749949291553054
lobpcg truncation 1.9614737344923372

**Comment by ogauthe** [comment] 2021-09-29 20:59
Maybe I am missing something and `lobpcg` has different conventions than arpack, I also note that `u1`  and `v1` are not isometries: `u1.T @ u1 != np.eye(2)` and `v1 @ v1.T != np.eye(2)`

**Comment by lobpcg** [comment] 2021-09-29 21:48
The issue here is that the default tol is small while the default number of iterations is large. For this funny matrix with a very large percentage of zero singular values, lobpcg in fact converges in 1-2 iterations, as can be seen from running
`u1, s1, v1 = slg.svds(A, k=k, solver="lobpcg", maxiter=2)`
Then lobpcg starts diverging, generating meaningless output and/or crashing. For larger k>8, lobpcg typically crashes here even with maxiter=1.

The problem could be circumvented by adding a small noise to the data matrix A prior to lobpcg call, but finding a proper factor that controls the noise amplitude may be a bit tricky.  Here is a winning combination that works for me:

import numpy as np
import scipy.linalg as lg
import scipy.sparse.linalg as slg

A = np.loadtxt("lobpcg_fail.txt")
x = lg.norm(A)
m = A.shape[0]
n = A.shape[1]
factor = x * 1e-8
As = A + np.random.randn(m, n) * factor
print(A.shape, A.dtype)

for k in range(1, 78):
    try:   
        print(k)
        u0, s0, v0 = lg.svd(A)
        print("dense  truncation", lg.norm(u0[:,:k] * s0[:k] @ v0[:k] - A) / x)
        u2, s2, v2 = slg.svds(A, k=k, solver="arpack")
        print("arpack truncation", lg.norm(u2 * s2 @ v2 - A) / x)
        u1, s1, v1 = slg.svds(As, k=k, solver="lobpcg", maxiter=2)
        print("lobpcg truncation", lg.norm(u1 * s1 @ v1 - A) / x)
    except ValueError as err: 
         print(k, err)

**Comment by lobpcg** [comment] 2021-09-29 22:31
So I think that it is just the same issue as  #10974 . It's unclear how to fix it automatically in the `lobpcg` code. The algorithm of `lobpcg` is just not designed for such matrices with very high multiplicity of eigenvalues, especially zero. May be we should at least add a warning in the function docs.

**Comment by tupui** [comment] 2021-09-30 08:38
@ogauthe if it's indeed the same issue, please consider closing this one. Also PRs to improve doc/warnings are always welcomed 😃

**Comment by lobpcg** [comment] 2021-09-30 17:59
It's the same root cause, with a different manifestation. In  #10974, the code fails with a cryptic error. Here, it's much worse - the output is plain wrong with no warning. The changes in the code would likely be different to address these - let's keep both open.

**Comment by ogauthe** [comment] 2021-09-30 21:10
@tupui in #10974 the focus is on the error message, a crash was expected. I think this is different, their is no crash but a silent wrong result.

**Comment by lobpcg** [comment] 2021-09-30 21:19
There are two possible independent enhancements in lobpcg code to fix this: 
1. Always store the previous best solution and output the best solution rather than the last one (at the cost of extra storage)
2. Add post-processing that calculates the actual residuals of the output and posts a warning flag if the tolerance is not met (at the cost of extra calculations)

**Comment by lobpcg** [comment] 2021-10-01 15:39
After #14790 is merged, I plan to fix this issue as described just above in https://github.com/scipy/scipy/issues/14784#issuecomment-931712902

**Comment by lobpcg** [comment] 2021-10-16 17:42
#14790 is merged, so I have started https://github.com/scipy/scipy/pull/14868

**Closed** 2021-10-29 22:49 UTC
Labels: defect
