### ISSUE TITLE
BUG: wheel runs have a *lot* of test fails at the moment.

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#19605] opened 2023-11-28 12:17 UTC
### Describe your issue.

Nightly wheels haven't been uploaded for `macos_arm64` or `windows_amd64` for at least a month, because the tests during the wheel build fails for both those targets.

You can see an example of the `macos_arm64` fails at https://cirrus-ci.com/task/5937923254648832. There there are only 3 [fails](https://cirrus-ci.com/task/5937923254648832?logs=cibuildwheel#L4620):
```
FAILED signal/tests/test_signaltools.py::TestSOSFilt::test_rank1[G] - TypeError: array type complex128 is unsupported in linalg
FAILED signal/tests/test_signaltools.py::TestSOSFilt::test_rank2[G] - TypeError: array type complex128 is unsupported in linalg
FAILED signal/tests/test_signaltools.py::TestSOSFilt::test_rank3[G] - TypeError: array type complex128 is unsupported in linalg
```

The windows fails are [here](https://github.com/scipy/scipy/actions/runs/7016550755/job/19088012284), they are much more numerous, 430 fails. There's a smorgasbord of fails, several mention `long long`, some are pythran related. Given that there are so many fails I'm wondering if something changed in numpy that caused a fail cascade.

It could do with several eyes on the build setup. It appears that the tests aren't failing in everyday CI, probably because numpy1.26.x is being used. The wheel builds use numpy2.0 though.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
The wheel build systems.
```

**Comment by andyfaff** [comment] 2023-11-29 08:35
@tylerjereddy I'm thinking it'd be good to get these test issues (with numpy 2.0) get knocked on the head before branching.

**Comment by rgommers** [comment] 2023-11-29 10:21
The main changes in NumPy are probably the defaulting to NEP 50 casting behavior and the changes for default integer type on Windows. 

I'll also note that after branching we need to change wheel build scripts to target released NumPy versions rather than 2.0-dev, because after the numpy 2.0 timeline change we're releasing 1.12 before numpy 2.0

I'm getting a Windows machine within days now, that'll help with working through some of the Windows-specific failures.

**Comment by rgommers** [comment] 2023-12-08 20:19
I'll start looking into what remains here.

**Comment by rgommers** [comment] 2023-12-12 19:23
macOS is fixed after gh-19686.

The Windows failures are mostly
```
Buffer dtype mismatch, expected 'long' but got 'long long'
```
and that's all going to have the same root cause I think. Trying to reproduce things locally now.

**Comment by tylerjereddy** [comment] 2023-12-12 19:46
Yeah, I was able to reproduce them all locally, thanks for helping with that, I got pulled away to other stuff. A few seemed a little harder for me to understand, but most fit the pattern as you say.

I admit that some of my patches basically just kicked the can down the road by restoring the original effective behavior via `np.dtype("long")`.

**Comment by rgommers** [comment] 2023-12-14 14:11
> I admit that some of my patches basically just kicked the can down the road by restoring the original effective behavior via `np.dtype("long")`.

I missed that when it happens - looks like a can worth kicking down that road, it doesn't seem particularly urgent to resolve in a better way.

**Comment by tylerjereddy** [comment] 2024-01-07 17:07
I went ahead and self-merged the cross-linked PR that should get us across the line here, I think the reviewer comments were all addressed and the full CI including wheel builds was passing.

I'll go ahead and close this--current intention is to have the NumPy 2.x support in 1.13.0, but if we really wanted I could backport the various Windows int shim PRs.. If there are new issues that show up in the weeklies we can up new tickets for those before 1.13.0.

**Closed by tylerjereddy** 2024-01-07 17:07 UTC
Labels: defect, Official binaries
