### ISSUE TITLE
BUG: RecursionError: maximum recursion depth exceeded in cdist function

### ISSUE THREAD

**Issue by shuds13** [scipy/scipy#21236] opened 2024-07-23 00:44 UTC
### Describe your issue.

In my github Actions CI I get the following error when running cdist.

E   RecursionError: maximum recursion depth exceeded
!!! Recursion detected (same locals & position)

Can be seen at
https://github.com/Libensemble/libensemble/actions/runs/10045133836/job/27761752552#step:20:55

The test is test_rec.py is shown below. This works in a simpler workflow where numpy 2.0.0 is used, but this workflow has dependencies on numpy<2. This is run through pytest.

### Reproducing Code Example

```python
import numpy as np
import sys
import scipy
from scipy.spatial.distance import cdist

def test_cdist():

    print(f"Python version: {sys.version}")
    print(f"NumPy version: {np.__version__}")
    print(f"SciPy version: {scipy.__version__}")

    a = [[0.0, 0.0]]
    b = [[0.0, 0.0],
        [0.0, 0.0],
        [0.0, 0.0],
        [0.0, 0.0]]

    print(f"a: {a}")
    print(f"b: {b}")

    distances = cdist(a, b, "euclidean")
    print(distances)

test_cdist()
```

### Error message

```shell
test_rec.py:24: in <module>
    test_cdist()
test_rec.py:21: in test_cdist
    distances = cdist(a, b, "euclidean")
/home/runner/miniconda3/envs/condaenv/lib/python3.12/site-packages/scipy/spatial/distance.py:2980: in cdist
    return cdist_fn(XA, XB, out=out, **kwargs)
/home/runner/miniconda3/envs/condaenv/lib/python3.12/site-packages/numpy/core/_dtype.py:46: in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
/home/runner/miniconda3/envs/condaenv/lib/python3.12/site-packages/numpy/core/_dtype.py:100: in _construction_repr
    return _scalar_str(dtype, short=short)
/home/runner/miniconda3/envs/condaenv/lib/python3.12/site-packages/numpy/core/_dtype.py:143: in _scalar_str
    elif np.issubdtype(dtype, np.number):
/home/runner/miniconda3/envs/condaenv/lib/python3.12/site-packages/numpy/core/numerictypes.py:417: in issubdtype
    arg1 = dtype(arg1).type
/home/runner/miniconda3/envs/condaenv/lib/python3.12/site-packages/numpy/core/_dtype.py:46: in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
E   RecursionError: maximum recursion depth exceeded
!!! Recursion detected (same locals & position)
```

### SciPy/NumPy/Python version and system information

```shell
NumPy version: 1.26.4
SciPy version: 1.14.0

Python 3.9 to 3.12
```

**Comment by lucascolley** [comment] 2024-07-23 00:52
I suspect this is a duplicate of gh-21072 - can you upgrade your NumPy version?

**Closed by lucascolley** 2024-07-23 00:52 UTC
Labels: defect

**Comment by shuds13** [comment] 2024-07-23 01:44
@lucascolley Closed as duplicate of another closed issue?

**Comment by lucascolley** [comment] 2024-07-23 09:30
@shuds13 yeah. We were able to conclude in the other issue that this is an upstream bug in NumPy 1.26, so your best bet is to follow the NumPy tracker and create a minimal reproducer if there isn't one already.
