### ISSUE TITLE
scipy.special.gammainc ValueError: invalid number of arguments

### ISSUE THREAD

**Issue by EdoLu** [scipy/scipy#15074] opened 2021-11-20 20:39 UTC
I noticed an apparently erratic behaviour of the special.gammainc function, which I can't explain. Apparently, when parameter names are explicitly indicated the function returns the error "ValueError: invalid number of arguments".
This doesn't happen when parameter names are not specified.

import scipy.special as ss
print(ss.gammainc(2, float("Inf"))) # returns 1
print(ss.gammainc(a=2, x=float("Inf"))) # returns error

Thanks in advance for helping

**Comment by daniel-s-ingram** [comment] 2021-11-20 22:20
`a` and `x` aren't keyword arguments, so I believe this is the expected behavior here.
https://github.com/scipy/scipy/blob/701ffcc8a6f04509d115aac5e5681c538b5265a2/scipy/special/_precompute/gammainc_data.py#L33

**Comment by daniel-s-ingram** [comment] 2021-11-20 22:42
I'm not sure how it happens exactly, but `a` and `x` somehow end up as position-only arguments in the version of the function I'm importing (despite that not being the case in the version I see in the code: https://github.com/scipy/scipy/blob/296b5502788af19409fc543bc32fa8e840cc4f9f/scipy/special/_precompute/gammainc_data.py#L33)

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.special as ss
>>> type(ss.gammainc)
<class 'numpy.ufunc'>
>>> ss.gammainc.__doc__
'gammainc(x1, x2, /, out=None, *, where=True, casting=\'same_kind\', order=\'K\', dtype=None, subok=True[, signature, extobj])\n\ngammainc(a, x)\n\nRegularized lower incomplete gamma function.\n\nIt is defined as\n\n.. math::\n\n    P(a, x) = \\frac{1}{\\Gamma(a)} \\int_0^x t^{a - 1}e^{-t} dt\n\nfor :math:`a > 0` and :math:`x \\geq 0`. See [dlmf]_ for details.\n\nParameters\n----------\na : array_like\n    Positive parameter\nx : array_like\n    Nonnegative argument\n\nReturns\n-------\nscalar or ndarray\n    Values of the lower incomplete gamma function\n\nNotes\n-----\nThe function satisfies the relation ``gammainc(a, x) +\ngammaincc(a, x) = 1`` where `gammaincc` is the regularized upper\nincomplete gamma function.\n\nThe implementation largely follows that of [boost]_.\n\nSee also\n--------\ngammaincc : regularized upper incomplete gamma function\ngammaincinv : inverse of the regularized lower incomplete gamma\n    function with respect to `x`\ngammainccinv : inverse of the regularized upper incomplete gamma\n    function with respect to `x`\n\nReferences\n----------\n.. [dlmf] NIST Digital Library of Mathematical functions\n          https://dlmf.nist.gov/8.2#E4\n.. [boost] Maddock et. al., "Incomplete Gamma Functions",\n   https://www.boost.org/doc/libs/1_61_0/libs/math/doc/html/math_toolkit/sf_gamma/igamma.html\n\nExamples\n--------\n>>> import scipy.special as sc\n\nIt is the CDF of the gamma distribution, so it starts at 0 and\nmonotonically increases to 1.\n\n>>> sc.gammainc(0.5, [0, 1, 10, 100])\narray([0.        , 0.84270079, 0.99999226, 1.        ])\n\nIt is equal to one minus the upper incomplete gamma function.\n\n>>> a, x = 0.5, 0.4\n>>> sc.gammainc(a, x)\n0.6289066304773024\n>>> 1 - sc.gammaincc(a, x)\n0.6289066304773024'
```

I suspect it has something to do with the type being a `numpy.ufunc`, which it must be getting wrapped somewhere as.

**Comment by person142** [comment] 2021-11-21 05:51
The implementation you are looking at is not the actual implementation-it’s a variant we use for comparison in tests.

The actual function is a C kernel that a ufunc  (docs here https://numpy.org/doc/stable/reference/ufuncs.html) is generated from-and yes it has the limitation that the arguments are positional only. That’s not really something we can solve without making large changes to NumPy.

Closing this since there’s not much SciPy can do about the limitation-feel free to keep discussing though.

**Closed by person142** 2021-11-21 05:51 UTC

**Comment by EdoLu** [comment] 2021-11-21 09:32
Thanks a lot for your prompt help!
