### ISSUE TITLE
BUG: `sym=False` is incorrect for odd lengths

### ISSUE THREAD

**Issue by OverLordGoldDragon** [scipy/scipy#18033] opened 2023-02-23 12:16 UTC
### Describe your issue.

Not zero-phase, unlike MATLAB.

PS, bunch of other signal stuff's flawed, including STFT and (especially) CWT - I recommend [ssqueezepy](https://github.com/OverLordGoldDragon/ssqueezepy), which I authored. I plan to open a detailed issue about CWT later.

### Reproducing Code Example

```python
from scipy.signal.windows import hann
from numpy import abs, imag, max
from numpy.fft import rfft, ifftshift

print(max(abs(imag(rfft(ifftshift(hann(128, sym=False)))))))
print(max(abs(imag(rfft(ifftshift(hann(129, sym=False)))))))
```
```
1.8324520941133646e-15  # good
0.7853205304496667      # bad
```
The un-shifted window is zero-phase, but that's [not what matters](https://github.com/librosa/librosa/issues/1279); one can confirm absence of [DFT-symmetry](https://www.wikiwand.com/en/Window_function#/DFT-symmetry).

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

<details><summary>expand</summary>

```
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['D:/Anaconda/envs/jgpu-env\\Library\\lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['D:/Anaconda/envs/jgpu-env\\Library\\lib']
    include_dirs = ['D:/Anaconda/envs/jgpu-env\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['D:/Anaconda/envs/jgpu-env\\Library\\lib']
    include_dirs = ['D:/Anaconda/envs/jgpu-env\\Library\\include']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['D:/Anaconda/envs/jgpu-env\\Library\\lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda/envs/jgpu-env\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

</details>

**Comment by tupui** [comment] 2023-02-23 14:06
Thanks for the report @OverLordGoldDragon. Would you also be interested in making PRs?

**Comment by OverLordGoldDragon** [comment] 2023-04-25 12:57
If suggesting/asking others make PRs, please include that they may be closed if incomplete, to not waste people's time. @tupui

**Comment by tupui** [comment] 2023-04-25 13:06
@OverLordGoldDragon thank you for pointing this out, I will also reply on the PR.

GitHub does not really allow us to "transfer" or "re-assign" a PR to someone else. On your PR, you indicated that you did not want to pursue this work. Hence we don't really have other options than closing it. Still, the fix is there for other to see if they would want to continue the work.

cc @melissawm

**Comment by tupui** [comment] 2023-04-25 16:26
> @tupui That's (this + other reply) all fine, but what's it to do with making others work for nothing? Informing potential contributors of such policies is your responsibility.

@OverLordGoldDragon To be clear, we value all contributions. We are conscious that contributing to SciPy or any other project involves time (and for most part, personal time) and its paramount for us to acknowledge it. See bellow for the rest.

> "`needs-work` isn't an option" is more of an added reason to disclaim contribution requests.

I understand, but the project is currently not using this label for that. Note that we are also not using this label that much and it would not necessarily have the impact that you seem to assume it would.

> My sentiment is beyond this PR. I could have submitted code or testing changes that others can no longer build upon because the codebase moved forward incompatibly.

Keeping PRs in sync is a universal concern. In practice though the number of merge conflict is small. We even quantified this here https://devstats.scientific-python.org/_generated/scipy.html#mergeability-of-open-prs (not up to date but still has some recent statistics.)

> "Only maintainers can commit" says scipy rather have no fix than an incomplete fix - and that's fine, but not common sense.

Maintainers are responsible of what get's into SciPy. This means that 20 years from now (SciPy is >20 years old), someone will have to keep maintaining the code. Hence we have a very strict policy that we are tying to extensively describe in our guide. See here for instance https://scipy.github.io/devdocs/dev/hacking.html#contributing-new-code

If something is not clear there, we are happy to get some feedbacks and improve the documentation. Also, when opening the PR, you should have seen a description with a few links. Did you read these? Was anything unclear?

We know that there is a lot of information and that it can be overwhelming, but you also have to understand that SciPy is not a trivial project to contribute to. Regardless of who is making a contribution, we are following very strict processes, which takes time, effort and investment from everyone. There is no shortcut here and as I said, the issue you are pointing out seems to not be critical in regards of what is currently on our plates.

A side note here: `scipy.signal` is not my area and there are only a few active maintainers around for this submodule usually. There is nothing we can do here to "speed" the process. The majority of our maintainers are doing this on their spare time and on a voluntary basis. Hence, it's expected to have a slow reply. But again, in this case the timeline was very reasonable as you received a comment asking for a test almost immediately.

We are trying to ease things and are actively looking into improving the onboarding path for newcomers. We have newcomers hours every months and everyone is welcomed to our bi-monthly contributors meeting. We also have a presence on social media such as a Slack channel with a newcomers channel. You can find more details here: https://scipy.org/community/

> Another option is asking to extend a fork's commit permissions.

I am not sure I follow here. You can do what you want on your fork and merge a PR in your own fork if you want. You can do whatever you want on your own version, we don't have any control (nor do we want to 😃).

> Separately, there were test failures due to a _correction_. A legitimacy-concerned repository would open an issue on that. There's a case for you to do a public relations advertising against yourselves and disclaim much of your code, because much of it is indeed severely flawed, and it's affecting research.

We are concerned about any legitimate bug and as such this issue is still open. I do not see a need for more issue to be open on that specific point. I did not check the tests on your PR, but what I can say is that it's usually not that clear. Most of the time what we see is that the use case from the issue is fixed, but it's not taking into account other correct cases.

Again, SciPy being very old and used widely, people rely on its stability and sometimes even on some failures and don't even realise that they compensate for it. On our side, we need to be careful when we "fix" something as we could be breaking a lot of code.

As for the "severely flawed", SciPy has many open issues and we only know what is reported in our issue tracker. Wether SciPy is "severely flawed" is a matter of perspective I suppose, although judging by our academic reputation and the quality of our sofware, I would think we are doing an ok job.

**Comment by OverLordGoldDragon** [comment] 2023-04-26 12:22
Expecting reading of "terms and conditions" for marginal contributions isn't a reasonable or productive standard. I saw an issue, I reported, I was suggested to look into it, I found a fix, I submitted. I'm not cussing anyone out in the PR, or doing anything that requires a self-check; if the rules make sense, I've done nothing wrong. I'm aware there's more to contributor guidelines than don't-dos. Appending a clause to your sentence clarifying this policy is something that takes zero effort on your part (after the first time of formulating the sentence), and spares much for others. If you rather people learn the hard way, up to you.

To briefly self-correct, there's only one major feature in `scipy.signal` that's "severely flawed", others are minor or moderate. I should've worded that more carefully. That's not to agree with your response on it though.

Partial response for now, may revisit.

**Comment by melissawm** [comment] 2023-04-26 12:35
Hi @OverLordGoldDragon - indeed, you did nothing wrong. I closed your PR because you mentioned you didn't have any interest in pursuing it further, but please feel free to reopen if you feel like there's anything else that can be done there. Like @tupui said, unfortunately there's not much we can do around GitHub workflows and how permissions are structured. If you need any extra help or guidance let us know.

**Comment by OverLordGoldDragon** [comment] 2023-04-27 15:12
Another option is transfer of ownership. I get that both options are awkward, but to me it's better than scrapping.

I've worked with Github for years, used many of its features in building projects (including collaborative), and I wasn't aware there's not less awkward options. If that's true of me, I'll let you extrapolate. The point stands that there shouldn't be _unexpected_ closures, and that `scipy`'s policy isn't widespread. If saying it each time is a pain, then it could be inserted into the PR interface.

**Comment by tupui** [comment] 2023-04-27 16:34
Thanks @ilayn for the supportive comment.

@OverLordGoldDragon if your current concern is not receiving credit for your work, I want to reassure you that we would credit your contribution in the commit history. We are usually very careful about that.

I want to make something clear one last time. Melissa made the right call when closing your PR. Having an open PR which is discontinued by its original owner simply does not work well with GitHub's workflow.

GitHub does not allow us to do a transfer of ownership. When you create a PR, you can check or not a box saying that you would allow maintainers to make changes to your branch. Meaning, anyone else would not be able to participate unless you manually edit the permissions on your fork to add these contributors...

The only exception I would see would be that a maintainer would express the interest to pick-up the PR and work on it. In practice, this happens from time to time and we do re-open or even create a branch from a fork's branch (because again, this is more convenient for the tools and GitHub.)

We have way too many open PRs which receive close to no attention and having yet another one would only add more noise to our backlog. And the worse part is, people would assume that this issue is being handled as there is already an open PR.

All that to say, it is not because your PR is closed today that it signals your contribution was bad nor that it won't be used. It's simply a way for us maintainer to know that we should not review more this PR and ask you to work on it as you expressed no interest in doing so.

On the doc side, feel free to suggest some rewording of either our PR template or newcomers documentation.

We can argue about our way of managing PRs (and I am happy to discuss), but this is not the place. In the interest of keeping the focus of this issue, on the issue at hand, I would suggest that you join one of our meeting or our Slack channel. https://scipy.org/community

**Comment by DietBru** [comment] 2024-09-10 10:37
Finally found some time to look at this:

* I double checked with Matlab and obtained identical results, i.e, obtaining 0.7853 for the 129 sample window.
* `hann()` implements the [Hann function], which per convention is not symmetric for odd sample length.

Hence, closing as not producible.

[Hann function]: https://en.wikipedia.org/wiki/Hann_function

**Closed** 2024-09-10 12:17 UTC
Labels: scipy.signal, invalid
