### ISSUE TITLE
Examples missing import numpy as np?

### ISSUE THREAD

**Issue by fabianpedd** [scipy/scipy#13049] opened 2020-11-08 02:39 UTC
Hi

a bunch of examples seem to be missing `import numpy as np`. At least for me they throw `NameError: name 'np' is not defined`.

Following examples seem to be missing `import numpy as np` (non exhaustive):
- scipy.signal.spectrogram
- scipy.signal.periodogram
- scipy.signal.welch

`scipy.__version__` gives `1.4.1`. However, the examples seem to be the same in the current master.

Maybe I am missing something? Any help is appreciated! 
Thanks :)

**Comment by mdhaber** [comment] 2020-11-08 02:42
No, this is not your fault; it's common throughout much of the documentation.

I think we should include complete code, but other developers argue that it should be omitted since it is common to almost every example.

As a user, what do you think?

**Comment by fabianpedd** [comment] 2020-11-08 02:47
Ahh, okay. Thanks for clearing that up for me. 

I am not sure. But when trying to "reproduce" the code it would be helpful to have all needed imports at the top. So that one, just as you stated, can just copy and paste the code.

As of right now, you either have to go through all example code and look for used dependencies or run it once in order to get the error message.

**Comment by ilayn** [comment] 2020-11-08 02:50
Our assumption is that `np` is a well-established shortcut for numpy and evident that it is required. But it is an assumption. 

This allows us skip a few hundreds of identical lines for each example in the catalogue.

**Comment by fabianpedd** [comment] 2020-11-08 03:02
That is indeed a valid argument.

However, `import matplotlib.pyplot as plt` is not omitted in the examples. Even though one could argue `plt` is also a well-established shortcut.

Are there any other packages that are not `imported` by default in the examples (similar to `np`)?

**Comment by mdhaber** [comment] 2021-05-11 05:00
@rajpratyush I'm not sure I follow. This issue is not about installing dependencies. It's about docstrings assuming that `import numpy as np`. 

@tupui what do you think about having this as a topic at the meetup? If we get a reasonable number of developers, it would be nice to have a vote.
1. Should `import numpy as np` _allowed_ in docstring examples? If so,
2. Is it recommended practice for new PRs (e.g. new functions and PRs that involve updates to docstrings)? If so,
3. Do we want a mass PRs adding it to old examples?

**Comment by andyfaff** [comment] 2021-05-11 06:15
Some docstrings have multiple examples, but these are often interspersed with lots of text. Should a numpy import happen once in a docstring, or with each example (as previous comments suggest)? The latter is bloat-worthy.

numpy is ubiquitous, so knowing what `np.sum` means without the import being included in a docstring doesn't seem like an egregious act. Even then it's only a websearch away. A single websearch is small fry compared to 'ugliness' caused by adding an explicit numpy import.

Besides, there are inline code snippets in multiple places that implicitly use np: `np.std(pop) <= atol + tol * np.abs(np.mean(population_energies))` is present in the docstring, do they deserve an import?

In a typical interpreter session (Python/IPython) you only need to do the import once (18 characters worth), and it lasts for the duration of the session. I would argue that the cost of typing that is miniscule compared to the cost incurred by adding the numpy import to every example.

**Comment by tylerjereddy** [comment] 2021-05-12 02:28
> If we get a reasonable number of developers, it would be nice to have a vote.

Just to nitpick a little--for substantive decisions probably best to "vote" by mailing list or similar rather than "people who happen to be at the meeting." Time issues aside, some devs simply feel more comfortable expressing their views outside of live meetings, etc.

**Comment by andyfaff** [comment] 2021-05-12 02:41
Plus it's difficult for a lot of devs to make meetings due to time zone issues.

**Comment by tupui** [comment] 2021-05-12 08:44
@tylerjereddy @andyfaff I agree and hear your points. As a large and diverse community, it's hard to get a way of operating things which suits to everyone. Still, having opportunities to have synchronous discussions is important and can fast forward a lot of things. To give a recent example: on a PR of Matt, Robert, him and I happened to be on GitHub at the same time and we this allowed to resolve a lot of questions because we could be synchronous.

Of course, important decisions should have their space. But, the mailing list is failing at this IMO. First of all, it's hard to keep track of things there and most importantly, some things just sit there forever without decisions (such as my last proposal about sensitivity analysis which just had inputs from Robert and Ilhan. And there is still no go/no go). The same happens on GitHub. We have tons of flags, but are they really used? Like the priority ones and need-decision just to name these.

This is why I am proposing to update our way of working as a community. We are one of the most important Python library and as such we could improve all together. Just comparing our operations with similar size libraries: the difference is staggering and also puzzling to me.

I am not asking that we do weekly calls with compulsory videos, give everyone strong assignments or start monitoring everyones performance. Not at all, I would just like that we add a bit of structure to help us evolve the library and be more welcoming to newcomers.

The meetup format that I propose is to be discussed and, as I said on the mail list, the time could vary every other meetup. I will also propose to discuss the idea of a slack/discord server. Hence, doing one-one and time zone management would be more tractable.

As I said in my emails, I am happy to discuss with anyone if you want.

**Comment by ilayn** [comment] 2021-05-12 10:37
If I put my PM hat on, this is probably at the bottom of our priority list. Even a full PEP8 compliance cleanup is above this so if we are going to touch lots of files I am -1 on this being the reason because evidently we had +0. issues regarding this, meaning that the need for this is just noise. So newcomer argument is not a very convincing one for me.

If we want to put this in while we are fixing something else then I am -0. No strong opinions though. I think everybody knows what np is at this stage. The examples are not self-contained yes but it would hardly be the case that the numpy is not imported already in the namespace given the fact that everyone is using ipython or notebooks already and IDE folks can see it right away. 

Another anecdotal evidence I just checked, everyone I know who uses spyder around me, enables the auto import of numpy scipy plt and pandas and alike. Here is mine

![image](https://user-images.githubusercontent.com/1303842/117961086-fd4c6d80-b31d-11eb-8033-4f7e3deb85c2.png)

**Comment by tylerjereddy** [comment] 2021-05-12 10:49
Also -1 on the explicit import for docstrings.

**Comment by ilayn** [comment] 2021-05-12 14:09
@tylerjereddy @rgommers @ev-br  Could you enable the discussions tab? Look for the "Discussions" checkbox in the repository settings page. I think we can use that instead of the ML which I also find a bit strange for discussions.

**Comment by tupui** [comment] 2021-05-12 14:11
> @tylerjereddy @rgommers @ev-br Could you enable the discussions tab? Look for the "Discussions" checkbox in the repository settings page. I think we can use that instead of the ML which I also find a bit strange for discussions.

We had recently a discussion on the mail list about improving the workflow and said that `Discussions` do not provide sufficient moderating tools. Maybe discord or slack would be more appropriate?

**Comment by ilayn** [comment] 2021-05-12 14:13
At least would be better than ML imho. We needed to have some issues converted to discussions anyways so if not for this then for other things we'll need it anyways.

**Comment by tupui** [comment] 2021-05-12 14:16
Here is the discussion I am referring to for reference: https://mail.python.org/pipermail/scipy-dev/2021-February/024578.html

**Comment by ev-br** [comment] 2021-05-12 14:30
I'm with Ilhan and Tyler on this one: -1 for cluttering examples with numpy imports.

**Comment by rkern** [comment] 2021-05-12 14:31
Also -1.

**Comment by WarrenWeckesser** [comment] 2021-05-12 15:20
@andyfaff wrote

> Some docstrings have multiple examples, but these are often interspersed with lots of text. Should a numpy import happen once in a docstring, or with each example (as previous comments suggest)?

We would only need one import at the beginning of the Examples section.  My understanding is that Sphinx treats the entire section as a single session.  So you can do

    >>> import numpy as np

    Some interesting comments.

    >>> x = np.std([1, 2, 3, 4])

    Some more comments.

    >>> x
    1.118033988749895

**Comment by WarrenWeckesser** [comment] 2021-05-12 15:55
I'm +0.  The arguments for not including the import have never seemed very compelling, but issues like this one have rarely come up, so I guess it is rare for users to get tripped up by having `np` not defined explicitly.

There is enough negative feedback that I suspect we *won't* do this, but if we did, I would suggest we fix *all* the docstrings at once.  It is an easy (if tedious) change that adds just one line to any given docstring.

Whatever the policy it, we should not make it optional--either we require the import, or we require that it not be used.  Making it optional would create an unnecessary inconsistency in the docstrings.

**Comment by rgommers** [comment] 2022-01-01 21:58
Given that we had two new PRs adding `import numpy as np` in a single example, I think it's time to make a final decision here and close the issue. I just read through the discussion here, and till now there:
- 2 users requesting imports,
- 2 maintainers (@mdhaber, @tupui) in favor of imports
- 5 maintainers (@andyfaff, @ilayn, @tylerjereddy, @rkern, @ev-br) against imports.
- 1 maintainer (@WarrenWeckesser) undecided (+0)

> The arguments for not including the import have never seemed very compelling, but issues like this one have rarely come up, so I guess it is rare for users to get tripped up by having `np` not defined explicitly.

This seems like a decent summary to me.

If we'd started from scratch I'd be ~ +0 too I think, however now that we have had this policy for 10+ years with very few complaints, I'd say we should not change it now - there's little benefit, and a reasonable amount of churn plus adding ~5,000 LoC. So I propose we close this with a decision that we won't change the current implicit/assumed import.

> There is enough negative feedback that I suspect we won't do this, but if we did, I would suggest we fix all the docstrings at once. 
>
> Whatever the policy it, we should not make it optional--either we require the import, or we require that it not be used. Making it optional would create an unnecessary inconsistency in the docstrings.

Completely agreed with this.

**Comment by ChristinaCzaikowski** [comment] 2022-01-02 14:36
Teaching person here. I want to add another perspective on this topic bc y'all seem to look from an too advanced coder pov. 

1. We exspect complete codes from our students in exams, so obviously the professional officials should set a good example. 
Bc if they do not, it only leads to riots.    It does not matter which page I open, it has to contain a complete executable example without any further thinking or implying. Students looove mistakes like this. They will always only talk about how not even the official page can write proper code, how/why am I - the student-  supposed to know ... 
2. From my pov, the "numpy has already been imported" argument is nonsense. If I look up and try sth new I do it in an own file / notebook before potentially destroying my code.  Also I do not like the inconsistency with the plt import. (Other frequently used imports are given in examples). And I am really sick of these repeating discussions with students.  
It's the same with all science classes. 
And I am sure that you do not get this kind of feedback often bc users at that stage usually do not use github xD
 
Love from Germany :)

**Comment by ev-br** [comment] 2022-01-02 15:02
As a data point, I'm teaching numerical analysis (with numpy et al of course) , both undergraduate and graduate level. My experience is different: no real issues with numpy import being implicit in examples.
It very well might be that my teaching has more serious problems, and the issue you mention simply falls down the students' priority list :-). 

If anything, I'd be rather inclined to making plt important implicit (FTR, I'm more like +0 on this).

**Comment by tupui** [comment] 2022-01-02 15:40
If that can help the discussion, I would offer to add the imports. So this should not be part of the discussion. It's a boring task, but a simple one shot one especially since we have a CI for our examples.

**Comment by mdhaber** [comment] 2022-01-02 18:09
And I can review those PRs, @tupui, or we can tag-team it.

**Comment by matthew-brett** [comment] 2022-01-02 20:31
I would personally prefer to add the imports.   My typical use of an example is just to copy paste it into an IPython session or Jupyter notebook.  I guess about 50% of the time the example errors, and then I  see immediately what the problem is, and type `import numpy as np` before copy-pasting the example again.   For me, that's just very slightly annoying, but I am sure it will be more frustrating, and possibly a little confusing, for beginners.  I guess the argument for missing it out is that it would add a lot of lines to the doctests, but that does seem like a very small cost.

**Comment by mdhaber** [comment] 2022-01-02 23:09
To be fair, IDEs can be set up to automatically perform the imports when a console is launched. And as noted above, the beginning of the tutorial introduction has:
![image](https://user-images.githubusercontent.com/6570539/147891739-7148e97f-28ea-4295-a3c0-18fe10881a93.png)

But I only set up my IDE that way recently, so I don't imagine that beginners would know/think to do that. And not everyone sees, reads the tutorials from the very beginning. 

I agree it's more efficient to print it in exactly one place, and it's more convenient to set up the IDE to do the imports automatically, but I think it's more convenient for users to have it in every example. We do a lot of things for user convenience, after all.

**Comment by edmundsj** [comment] 2022-06-03 20:24
Adding my two cents from a couple of perspectives here having encountered this issue many times. I won't comment on the associated difficulty of making the changes required, but I suspect you could write a very simple crawler to look through all the examples, check if they have a "np" in them, and if so, add the import statement at the top.

As an advanced user, this is mildly annoying. Anytime example code has partial imports it leads to delays in my workflow. If I see import statements specified, I expect to be able to copy-paste the relevant code and have it just work. When it does not, and I have to take the time to debug why exactly it does not, my time is wasted and I like the underlying library a little less. Maybe 3% less. Having *partial* import statements is arguably worse than no import statements - because I will assume that the code should just work as-is, and it won't.

As a beginner user, this was a major source of confusion - I didn't know the common aliases for packages (plt, np, etc.) and having everyone just assume that I knew what they were was a big frustration and led to hours of confusion - as lots of people give code without explicit imports. How am I supposed to know that "plt" means matplotlib if I've never used the matplotlib library before, or am only just now getting started with python?

**Comment by ilayn** [comment] 2022-06-03 20:40
I still don't like the addition of import statement which I think everyone knows about by now in the Python community. Because users of SciPy won't survive more than a few lines of code without using a NumPy command and thus would be importing it.

However, judging by the hits of this issue I think the fair thing to do here for me is to reconsider my dislike and bite the bullet on this one. The implementation of it is still a daunting task regardless, just judging by the open Pull Requests that will be affected by this. 

A middle ground might be to come up with another rubric trick such that it includes a code block with the necessary imports at the documentation generation step and not necessarily putting the import statement into the docstring. But I'd like to emphasize that these are just quick thoughts and not necessarily well-thought-through suggestions.

**Comment by edmundsj** [comment] 2022-06-03 20:52
I'm in support of adding this type of rubric trick to look through the example and identify dependencies from common aliases and auto-generate the import statements. I'm happy to manually add a few hundred, but 5,000 copy-paste actions sounds like a very aggravating afternoon.

**Comment by ev-br** [comment] 2022-06-03 21:29
-1 from me. 

Our current default is a single assumed `import numpy as np`. No more, no `plt`, no `pd` etc etc. Therefore the main premise of  https://github.com/scipy/scipy/issues/13049#issuecomment-1146333767 is not really applicable, there is no gazillion of aliases to know by heart or agonizingly discover. So for a novice user I won't buy that it leads to _hours of confusion_. Even if there is some, it's a one-timer. From that point on, this import is a line noise, repeated 1000s of times in all docstring examples for all users.

**Comment by edmundsj** [comment] 2022-06-03 22:11
I guarantee when I was first learning python this specific problem caused me hours of confusion. Perhaps I'm just slow. But I'm an engineering Ph.D., so probably not *that* slow. XD 

I'll defer to those that maintain the package to weigh whether the change is worth making.

**Comment by mdhaber** [comment] 2022-06-03 22:29
@melissawm thought you might have an opinion here, since this comes up every few months as a sticking point for new users.

**Comment by ev-br** [comment] 2022-06-03 23:01
> I guarantee when I was first learning python this specific problem caused me hours of confusion

This specific problem being a single assumed import or a whole lot of them, across the ecosystem? For the latter I'm totally not surprised.

**Comment by melissawm** [comment] 2022-06-06 13:20
Not a maintainer, but I'll add my two cents from a user/contributor perspective.

I can see the argument for this being overall an implicit expectation, but for those learning I don't think it is obvious at all. If it was, we wouldn't see issues around it. In my opinion, this means the documentation is insufficient, and I don't think it is bad practice to repeat yourself if it improves clarity and prevents these sorts of issues/PRs from being created. So I am personally +1 on finding a way to add the import statements somewhere *once* per page, at least.

**Comment by josef-pkt** [comment] 2022-06-06 17:11
I'm now +0.5

In general I think it's unnecessary, when I copy examples then it is usually in an already active notebook where numpy is already imported as np.

However, many users in stats will be mainly using pandas and might be less familiar with with working directly with numpy. For those users having the explicit import in the example will be useful, and advertise numpy.

I checked several docstrings in stats. Most of them are long enough that an additional import will not distract much.

**Comment by tupui** [comment] 2022-06-06 19:08
Updated poll:

4 users requesting imports,
5 maintainers (@mdhaber, @tupui, @matthew-brett, @josef-pkt (0.5), @melissawm (counting here since you are more than a user here and involved with newcomers experience)) in favor of imports
5 maintainers (@andyfaff, @ilayn, @tylerjereddy, @rkern, @ev-br) against imports.
2 maintainer (@WarrenWeckesser, @rgommers) undecided (+0)

**Comment by bsipocz** [comment] 2022-06-06 22:40
Another +1 from the sidelines. I like the idea of having fully executable snippets in the docs (with the logical size of one docstring, or one narrative docs page, no need to repeat imports within those, but ideally it's repeated for the different methods of a class, etc.). And it includes all the imports the example is using, if it pulls in mpl or pandas, then import those, if it directly uses numpy import it.

**Comment by AtsushiSakai** [comment] 2022-06-09 23:10
I’m +1 personally. I think almost beginners just google their problem and, find and check an API page which they are interested in without checking the whole doc. So, I think self contained examples might help not to wasting time a little for beginners.

**Comment by stefanv** [comment] 2022-06-10 21:55
I don't have a horse in this race, but I wanted to mention an alternative that came up on https://github.com/networkx/networkx/issues/5720

We could ask IPython/Jupyter whether they could detect common missing names and give an error message after a NameError with some guidance, such as:

```
Hint: it looks like you are missing an import; to use SciPy, try `import scipy as sp` first
```

This is a best-of-both-worlds type scenario, where we don't need to repeat the same imports over and over in the docstrings, but users get helpful feedback for common package imports (`np`, `sp`, `plt`, `pd`, `nx`, etc).

**Comment by tupui** [comment] 2022-06-29 14:33
Based on exchanges here and during the community meetings, the decision is leading toward adding the necessary imports to examples.

I will let this open until the 8th of July and close with this decision if there are no more discussions.

As said earlier, @mdhaber and I proposed to do the work. It should be fairly straightforward as it would mostly consist in removing the hidden import and fixing all related failures.

**Comment by j-bowhay** [comment] 2022-06-30 18:54
@tupui also happy to work on this if required

**Comment by tupui** [comment] 2022-07-10 00:27
Waiting period is over, hence the decision is to include imports in our examples.

I will start to work on this when I have some time. Meanwhile, new PRs should be self sufficient and not require hidden imports.

Thank you everyone for sharing your thoughts and helping moving this forward 😃

**Comment by mdhaber** [comment] 2022-07-29 14:54
Here are the rules we have been working under when adding `import numpy as np` and `import matplotlib.pyplot as plt`:

- Add them a maximum of once per "Example" section.
- Add them to the top of the code block where they are first needed. If both are needed at the top of the same block, the NumPy import goes first.
- For now, leave existing imports alone, even if they don't follow these rules. (And, of course, don't add duplicate imports).

**Comment by WarrenWeckesser** [comment] 2022-11-09 04:56
Closed by https://github.com/scipy/scipy/pull/17366

**Closed by WarrenWeckesser** 2022-11-09 04:56 UTC
Labels: Documentation
