### ISSUE TITLE
DOC: How ndimage.label() works (which algorithm) ?

### ISSUE THREAD

**Issue by Simpsonguitar** [scipy/scipy#12447] opened 2020-06-29 14:55 UTC
Hi,
I can't find any  information in the documentation of the ndimage.label()  function about how it works.
The cited paper in the documentation seems not to describe the algorithm but the property of centrosymmetric matrices.
I tried to check in the source code but it refers to the _ni_label._label() function which seems to be compiled and has no doc string.
I suspect it uses a classic enclosing or opening filter but it would be great to have it explained on the documentation of the ndimage.label() function.
Thanks in advance,
Simon

**Comment by sethtroisi** [comment] 2020-07-17 10:09
`_ni_label._label()` is defined at [scipy/ndimage/src/_ni_label.pyx#L202](https://github.com/scipy/scipy/blob/v1.5.1/scipy/ndimage/src/_ni_label.pyx#L202)

It doesn't give an algorithm but `mark_for_merge` and `label_line_with_neighbor` make it look like it iterates over a bunch of different lines/regions/blocks by stride and labels each group in that region. It merges labels between regions using a [union-find/disjoint-set](https://en.wikipedia.org/wiki/Disjoint-set_data_structure).

**Comment by dschmitz89** [comment] 2023-10-15 07:59
Duplicate of #14557

**Closed by dschmitz89** 2023-10-15 07:59 UTC
Labels: scipy.ndimage, Documentation
