### ISSUE TITLE
BUG: Scipy - stats failing import np

### ISSUE THREAD

**Issue by DanielIAvila** [scipy/scipy#19323] opened 2023-09-29 09:26 UTC
### Describe your issue.

I cannot run Pearson correlations with `stats` from `scipy`

### Reproducing Code Example

```python
`from scipy import stats

stats.pearsonr(df['X'], df['y'])`
```

### Error message

```shell
~\lib\site-packages\scipy\stats\stats.py:4018 in pearsonr

NameError: name 'np' is not defined
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.21.2 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: c:/opt/openblas/if_32/64/include
    lib directory: c:/opt/openblas/if_32/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= PRESCOTT MAX_THREADS=4
    pc file directory: c:/opt/openblas/if_32/64/lib/pkgconfig
    version: 0.3.18
  lapack:
    detection method: pkgconfig
    found: true
    include directory: c:/opt/openblas/if_32/64/include
    lib directory: c:/opt/openblas/if_32/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= PRESCOTT MAX_THREADS=4
    pc file directory: c:/opt/openblas/if_32/64/lib/pkgconfig
    version: 0.3.18
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.33
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-yajwq4a4\overlay\Lib\site-packages\pythran
    version: 0.12.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-5o1gjg1j\cp38-win_amd64\build\venv\Scripts\python.exe
  version: '3.8'


Output from spyder call 'get_namespace_view':
C:\Users\daav4777\Anaconda3\envs\nmodeling\lib\site-packages\spyder_kernels\utils\nsview.py:427: UserWarning: legacy printing option can currently only be '1.13', '1.21', or `False`
  np.set_printoptions(**np_printoptions)
```

**Comment by tupui** [comment] 2023-09-29 10:49
Hi @DanielIAvila, thank you for reporting.

You might have an environment issue. I see some references of conda env and yet the error message points to `~\lib\site-packages\scipy`.

Looking at the source of `scipy\stats\stats.py` on the 1.10.x branch shows a different structure https://github.com/scipy/scipy/blob/maintenance/1.10.x/scipy/stats/stats.py

Locally I cannot reproduce your issue (both with SciPy 1.10.1 and `main`).

**Comment by DanielIAvila** [comment] 2023-09-29 11:53
Hi @tupui,

I have solved the problem uninstalling `numpy` and `scipy`, closing `Spyder` and then installing `scipy` directly without prior installation of `numpy`

**Comment by tupui** [comment] 2023-09-29 11:56
Thank you for the confirmation and glad you got it working. I am closing this then 😃

**Closed by tupui** 2023-09-29 11:56 UTC
Labels: scipy.stats, invalid
