### ISSUE TITLE
FAIL: test_decomp_update.TestQRinsert_D.test_economic_1_col_bad_update

### ISSUE THREAD

**Issue by sbecuwe** [scipy/scipy#5338] opened 2015-10-09 10:52 UTC
I'm using Python 2.7.10, numpy 1.9.2 and scipy 0.16.0, together with MKL 11.2.3.187 (on SL 6.7)

Running python -c 'import numpy; import scipy; scipy.test(verbose=2)' results in 

[...]
test_decomp_update.TestQRinsert_D.test_economic_1_col ... ok
test_decomp_update.TestQRinsert_D.test_economic_1_col_bad_update ... Fatal Python error: PyEval_RestoreThread: NULL tstate

After removing the test from test_decomp_update.py, no more crashes, only 13 failures.
Some of the failures are mentioned in #4885 already.

**Comment by ewmoore** [comment] 2015-10-09 12:37
Can you test against master instead of 0.16.0?  There have been a few fixes since 0.16.0 was released.  Additionally, can you paste either here or into a gist the output from the tests?

**Comment by sbecuwe** [comment] 2015-10-10 06:35
Test was negative: still same crash. However, the number of failures has been reduced from 13 to 8. 

```
======================================================================
FAIL: test_lorentz (test_odr.TestODR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/odr/tests/test_odr.py", line 293, in test_lorentz
    3.7798193600109009e+00]),
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([  1.000000e+03,   1.000000e-01,   3.800000e+00])
 y: array([  1.430678e+03,   1.339051e-01,   3.779819e+00])

======================================================================
FAIL: test_multi (test_odr.TestODR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/odr/tests/test_odr.py", line 190, in test_multi
    0.5101147161764654, 0.5173902330489161]),
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([ 4. ,  2. ,  7. ,  0.4,  0.5])
 y: array([ 4.379988,  2.433306,  8.002885,  0.510115,  0.51739 ])

======================================================================
FAIL: test_pearson (test_odr.TestODR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/odr/tests/test_odr.py", line 236, in test_pearson
    np.array([5.4767400299231674, -0.4796082367610305]),
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([ 1.,  1.])
 y: array([ 5.47674 , -0.479608])

======================================================================
FAIL: test_iv_cephes_vs_amos (test_basic.TestBessel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/tests/test_basic.py", line 2340, in test_iv_cephes_vs_amos
    self.check_cephes_vs_amos(special.iv, special.iv, rtol=5e-9, atol=1e-305)
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/tests/test_basic.py", line 2322, in check_cephes_vs_amos
    assert_tol_equal(c1, c2, err_msg=(v, z), rtol=rtol, atol=atol)
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/_testutils.py", line 50, in assert_tol_equal
    verbose=verbose, header=header)
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=5e-09, atol=1e-305
(-20.0, 700.6)
(mismatch 100.0%)
 x: array(2.11168739263566e+302)
 y: array((2.093671436001725e+302+0j))

======================================================================
FAIL: Real-valued Bessel I overflow
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/tests/test_basic.py", line 2448, in test_ticket_503
    assert_tol_equal(special.iv(1, 700), 1.528500390233901e302)
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/_testutils.py", line 50, in assert_tol_equal
    verbose=verbose, header=header)
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(1.5306870843952584e+302)
 y: array(1.528500390233901e+302)

======================================================================
FAIL: test_data.test_boost(<Data for gammainccinv: gamma_inv_small_data_ipp-gamma_inv_small_data>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/apps/Python/2.7.10/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/tests/test_data.py", line 481, in _test_factory
    test.check(dtype=dtype)
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/_testutils.py", line 292, in check
    assert_(False, "\n".join(msg))
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError:
Max |adiff|: 7.10543e-15
Max |rdiff|: 1
Bad results (1 out of 229) for the following points (in output 0):
          0.004994133487343788              0.9688677787780762 =>                            0.0 !=         1.094258942968236e-302  (rdiff                            1.0)

======================================================================
FAIL: test_data.test_local(<Data for ellipeinc: ellipeinc_neg_m>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/apps/Python/2.7.10/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/tests/test_data.py", line 481, in _test_factory
    test.check(dtype=dtype)
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/special/_testutils.py", line 292, in check
    assert_(False, "\n".join(msg))
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError:
Max |adiff|: 1.48857e+138
Max |rdiff|: 1.26522e-15
Bad results (1 out of 2304) for the following points (in output 0):
                        1e-149                         -1e+305 =>        1.5811402929846682e-146 !=        1.5811402929846702e-146  (rdiff          1.265215290137423e-15)

======================================================================
FAIL: test_stats.test_chisquare_masked_arrays
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/apps/Python/2.7.10/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 2054, in test_chisquare_masked_arrays
    mat.assert_array_almost_equal(g, expected_g, decimal=15)
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/ma/testutils.py", line 224, in assert_array_almost_equal
    header='Arrays are not almost equal')
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/ma/testutils.py", line 189, in assert_array_compare
    verbose=verbose, header=header)
  File "/apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal

(mismatch 50.0%)
 x: array([ 22.18071 ,   0.505343])
 y: array([ 22.18071 ,   0.505343])

----------------------------------------------------------------------
Ran 18593 tests in 169.550s

FAILED (KNOWNFAIL=97, SKIP=1190, failures=8)
Running unit tests for scipy
NumPy version 1.9.2
NumPy is installed in /apps/numpy/1.9.2-Python-2.7.10/lib/python2.7/site-packages/numpy
SciPy version 0.17.0.dev0+Unknown
SciPy is installed in /tmp/t/apps/Python/2.7.10/lib/python2.7/site-packages/scipy
Python version 2.7.10 (default, Sep  9 2015, 16:13:28) [GCC Intel(R) C++ gcc 4.9 mode]
nose version 1.3.7
```

**Comment by rgommers** [comment] 2015-10-10 11:25
@sbecuwe did you close this issue on purpose?

**Comment by sbecuwe** [comment] 2015-10-12 12:34
Oeps, sorry, made a mistake. No, I did not mean to close the issue.

**Comment by rgommers** [comment] 2015-10-14 20:53
The ``TestODR`` failures are due to compiling with ``-O3`` in combination with MKL (see gh-4885). 

The ``special`` failures are mostly corner cases and a number of them look familiar.

The ``qr_insert`` crash is the real worry here. It would be good to check if it remains when compiling with ``-O1``. Also make sure to really clean your previous build with ``git clean -xdf``; other methods like ``rm -rf build/`` or ``python setup.py clean`` are not to be trusted.

**Comment by jmwoloso** [comment] 2015-11-07 02:22
If some tests fail, does that mean the scipy build shouldn't be used at all or just that you cannot use, with any confidence, the specific functions that failed?

**Comment by rgommers** [comment] 2015-11-07 10:57
The latter - anything but the function under test will work fine.

**Comment by jmwoloso** [comment] 2015-11-09 04:31
Alright, thank you!

**Comment by cgohlke** [comment] 2016-07-11 06:03
I can reproduce the `TestQRinsert_F.test_economic_1_col_bad_update ... Fatal Python error: PyEval_RestoreThread: NULL tstate` crash with scipy-0.18.0rc2.win32-py3.4 (msvc10, ifort16, mkl-11.3). The debug build (disabled optimization `/Od`) does not crash.

**Comment by pv** [comment] 2016-07-11 08:31
@cgohlke: can you open a new issue for that?

**Comment by cgohlke** [comment] 2017-12-12 20:08
I can reproduce the `test_decomp_update.TestQRinsert_D.test_economic_1_col_bad_update ... Fatal Python error: PyEval_RestoreThread: NULL tstate` crash with scipy-1.0 on Windows, Python 3.7.0a3 64-bit, Visual Studio 2017.5.1, Intel Fortran 18, MKL 2018.1. The debug build (disabled optimization /Od) does not crash.

Standalone code that crashes:

```
import numpy as np
from scipy import linalg
from scipy.linalg._decomp_update import *
from pytest import raises as assert_raises

dtype = 'complex128'
q = np.eye(5, 3, dtype=dtype)
r = np.eye(3, dtype=dtype)
u = np.array([1, 0, 0, 0, 0], dtype)
assert_raises(linalg.LinAlgError, qr_insert, q, r, u, 0, 'col')
```

**Comment by cgohlke** [comment] 2017-12-12 22:11
> Can it be related to the pytest

Probably not. Any other build (Py 3.6, Py 3.7 32-bit, etc) seems to work.

Since this might be threading related, I tried removing the `with nogil` statements in the `qr_insert_col` function.  No more crashes. Not that it proves anything... I looked a the output of `cython -a _decomp_update.pyx` and the compiler warnings but did not notice anything obvious.

**Comment by pv** [comment] 2017-12-12 22:34
Cython bug or compiler bug (as hinted by no fail with `/Od`)? iiuc, it shouldn't be possible to get null threadstate.

**Comment by cgohlke** [comment] 2017-12-13 07:56
I think I found the culprit. At https://github.com/scipy/scipy/blob/master/scipy/linalg/_decomp_update.pyx.in#L1966, `&float`/`&double` are cast to `float_complex*`/`double_complex*`. At https://github.com/scipy/scipy/blob/master/scipy/linalg/_decomp_update.pyx.in#L662 and L660, the imaginary part of the complex number, which does not have a valid memory address, is written to. This corrupts memory and/or crashes. I'll prepare a PR.

**Closed** 2017-12-22 14:41 UTC
Labels: defect, scipy.linalg
