### ISSUE TITLE
Segmentation Fault in scipy/linalg/_flapack.cpython-37m-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by SamuelePolimi** [scipy/scipy#13147] opened 2020-11-26 16:23 UTC
#### Description:

I experience ```Segmentation Fault``` when executing a script. I am unable to detect what exactly causes the crash, nor to deliver a minimal reproducing code. However, I can share the ```backtrace``` from ```gdb```:

#### Error Message:

```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

#### Backtrace:
```
from /home/samuele/.conda/envs/rl-new/lib/python3.7/site-packages/scipy/linalg/_flapack.cpython-37m-x86_64-linux-gnu.so
#1  0x00005555556cc61b in _PyObject_FastCallKeywords ()
#2  0x0000555555728a79 in _PyEval_EvalFrameDefault ()
#3  0x0000555555669059 in _PyEval_EvalCodeWithName ()
#4  0x00005555556cb2a5 in _PyFunction_FastCallKeywords ()
#5  0x0000555555723a66 in _PyEval_EvalFrameDefault ()
#6  0x0000555555669059 in _PyEval_EvalCodeWithName ()
#7  0x00005555556cb2a5 in _PyFunction_FastCallKeywords ()
#8  0x0000555555727e6e in _PyEval_EvalFrameDefault ()
#9  0x00005555556cb07b in _PyFunction_FastCallKeywords ()
#10 0x0000555555723a66 in _PyEval_EvalFrameDefault ()
#11 0x0000555555669919 in _PyEval_EvalCodeWithName ()
#12 0x000055555566a134 in _PyFunction_FastCallDict ()
#13 0x00005555557251ab in _PyEval_EvalFrameDefault ()
#14 0x0000555555669919 in _PyEval_EvalCodeWithName ()
#15 0x000055555566a134 in _PyFunction_FastCallDict ()
#16 0x00005555557251ab in _PyEval_EvalFrameDefault ()
#17 0x0000555555669059 in _PyEval_EvalCodeWithName ()
#18 0x00005555556cb307 in _PyFunction_FastCallKeywords ()
#19 0x0000555555723a66 in _PyEval_EvalFrameDefault ()
#20 0x000055555566a06b in _PyFunction_FastCallDict ()
---Type <return> to continue, or q <return> to quit---
#21 0x0000555555680a03 in _PyObject_Call_Prepend ()
#22 0x00005555556c3baa in slot_tp_call ()
#23 0x00005555556758d2 in PyObject_Call ()
#24 0x00005555557251ab in _PyEval_EvalFrameDefault ()
#25 0x0000555555669059 in _PyEval_EvalCodeWithName ()
#26 0x000055555566a134 in _PyFunction_FastCallDict ()
#27 0x0000555555680a03 in _PyObject_Call_Prepend ()
#28 0x00005555556c3baa in slot_tp_call ()
#29 0x00005555556758d2 in PyObject_Call ()
#30 0x00005555557251ab in _PyEval_EvalFrameDefault ()
#31 0x0000555555669059 in _PyEval_EvalCodeWithName ()
#32 0x000055555566a134 in _PyFunction_FastCallDict ()
#33 0x00005555557251ab in _PyEval_EvalFrameDefault ()
#34 0x00005555556cb07b in _PyFunction_FastCallKeywords ()
#35 0x00005555557238b0 in _PyEval_EvalFrameDefault ()
#36 0x00005555556cb07b in _PyFunction_FastCallKeywords ()
#37 0x00005555557238b0 in _PyEval_EvalFrameDefault ()
#38 0x000055555566a06b in _PyFunction_FastCallDict ()
#39 0x0000555555680a03 in _PyObject_Call_Prepend ()
#40 0x00005555556758d2 in PyObject_Call ()
#41 0x0000555555775ef7 in t_bootstrap ()
#42 0x00007ffff79266db in start_thread (arg=0x7fff117fa700)
    at pthread_create.c:463
---Type <return> to continue, or q <return> to quit---
#43 0x00007ffff764f71f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

#### Scipy/Numpy/Python version information:

```
sys==1.5.2 
scipy==1.19.2 
sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

#### System Information:

```
Ubuntu 18.84.5 LTS 64-bit
AMD® Ryzen 9 3900x 12-core processor × 24
GNOME 3.28.2
```

**Comment by rgommers** [comment] 2022-02-22 21:40
There is no useful information in here unfortunately; it may be a duplicate of another issue, or already fixed. Since this isn't actionable, I'll close the issue. Thanks for the report though @SamuelePolimi

**Closed by rgommers** 2022-02-22 21:40 UTC
Labels: defect, scipy.linalg
