### ISSUE TITLE
Dendrogram: RuntimeError

### ISSUE THREAD

**Issue by pyk** [scipy/scipy#6109] opened 2016-04-28 10:22 UTC
I use dendrogram with the following `ndarray`

``` shell
>>> Z.shape
(36951, 4)
>>> dendrogram(Z)
```

It returns the following error:

``` shell
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyk/.virtualenvs/project-lisa/local/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 2294, in dendrogram
    above_threshold_color=above_threshold_color)
  File "/home/pyk/.virtualenvs/project-lisa/local/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 2582, in _dendrogram_calculate_info
....
    leaf_label_func, i, labels)
  File "/home/pyk/.virtualenvs/project-lisa/local/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 2332, in _append_singleton_leaf_node
    ivl.append(str(int(i)))
RuntimeError: maximum recursion depth exceeded while getting the str of an object

```

Scipy version

``` shell
% pip freeze
scipy==0.17.0
```

**Comment by pyk** [comment] 2016-04-28 10:28
Update:

I try to reproduce with random `ndarray` and it works:

```shell
>>> import numpy as np
>>> Z = np.random.rand(36951, 4)
>>> Z
array([[ 0.51846635,  0.05964583,  0.01571646,  0.71119299],
       [ 0.09680092,  0.82641855,  0.442856  ,  0.65574763],
       [ 0.74517431,  0.45615698,  0.93298234,  0.5392694 ],
       ..., 
       [ 0.12003866,  0.13969445,  0.54501751,  0.91367931],
       [ 0.78631613,  0.62170308,  0.45758332,  0.46003873],
       [ 0.66776504,  0.71397659,  0.12939779,  0.95735639]])
>>> Z.shape
(36951, 4)
>>> from scipy.cluster.hierarchy import dendrogram, linkage
>>> dendrogram(Z)
{'ivl': ['0', '0'], 'dcoord': [[0.0, 0.12939779006029051, 0.12939779006029051, 0.0]], 'leaves': [0, 0], 'color_list': ['g'], 'icoord': [[5.0, 5.0, 15.0, 15.0]]}
>>> 
```

hmmm 😞 , something wrong with my previous `ndarray`

I will close this issue

**Comment by rcompton** [comment] 2017-01-10 18:16
Hmmm, I just ran into this as well. Any idea what was wrong with your array?

**Comment by rgommers** [comment] 2017-01-10 18:48
@rcompton if it looks like a real issue, can you post a reproducible example? then I'll reopen this

**Comment by WarrenWeckesser** [comment] 2017-01-10 19:39
I can reproduce this:

````
In [60]: from scipy.cluster.hierarchy import dendrogram, linkage

In [61]: np.random.seed(123)

In [62]: x = np.random.randn(4000, 4)

In [63]: z = linkage(x)

In [64]: result = dendrogram(z)
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-59-54fad9755b7e> in <module>()
----> 1 result = dendrogram(z)

/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-0.19.0.dev0+677074c-py3.5-macosx-10.6-x86_64.egg/scipy/cluster/hierarchy.py in dendrogram(Z, p, truncate_mode, color_threshold, get_leaves, orientation, labels, count_sort, distance_sort, show_leaf_counts, no_plot, no_labels, leaf_font_size, leaf_rotation, leaf_label_func, show_contracted, link_color_func, ax, above_threshold_color)
   2363         contraction_marks=contraction_marks,
   2364         link_color_func=link_color_func,
-> 2365         above_threshold_color=above_threshold_color)
   2366 
   2367     if not no_plot:

<snip>

/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-0.19.0.dev0+677074c-py3.5-macosx-10.6-x86_64.egg/scipy/cluster/hierarchy.py in _dendrogram_calculate_info(Z, p, truncate_mode, color_threshold, get_leaves, orientation, labels, count_sort, distance_sort, show_leaf_counts, i, iv, ivl, n, icoord_list, dcoord_list, lvs, mhr, current_color, color_list, currently_below_threshold, leaf_label_func, level, contraction_marks, link_color_func, above_threshold_color)
   2649             level=level + 1, contraction_marks=contraction_marks,
   2650             link_color_func=link_color_func,
-> 2651             above_threshold_color=above_threshold_color)
   2652 
   2653     max_dist = max(uamd, ubmd, h)

... last 405 frames repeated, from the frame below ...

/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-0.19.0.dev0+677074c-py3.5-macosx-10.6-x86_64.egg/scipy/cluster/hierarchy.py in _dendrogram_calculate_info(Z, p, truncate_mode, color_threshold, get_leaves, orientation, labels, count_sort, distance_sort, show_leaf_counts, i, iv, ivl, n, icoord_list, dcoord_list, lvs, mhr, current_color, color_list, currently_below_threshold, leaf_label_func, level, contraction_marks, link_color_func, above_threshold_color)
   2649             level=level + 1, contraction_marks=contraction_marks,
   2650             link_color_func=link_color_func,
-> 2651             above_threshold_color=above_threshold_color)
   2652 
   2653     max_dist = max(uamd, ubmd, h)

RecursionError: maximum recursion depth exceeded while getting the str of an object

````

**Comment by rgommers** [comment] 2018-08-21 23:53
Closing as a duplicate of gh-7271, which has more details.

**Closed by rgommers** 2018-08-21 23:53 UTC
Labels: defect, scipy.cluster
