### ISSUE TITLE
and some more test failures

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5542] opened 2015-11-26 11:24 UTC
For completeness and to check the system of #5541, #5540 and #5539, these tests fail for both scipy 0.16.1 superpack installers and my homemade build:

```
======================================================================
FAIL: test_correlate (test_filters.TestThreading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\scipy\ndimage\tests\test_filters.py", line 156, in test_correlate
    assert_array_equal(os, ot)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 719, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 84.4332%)
 x: array([[[ -0.47639956,   3.1331553 ,  10.35781802, ...,   9.18432613,
          -2.55174618,  -4.26523813],
        [ 12.99837238,  13.49555098,  -5.12679432, ...,  -8.76131474,...
 y: array([[[ -0.47639956,   3.1331553 ,  10.35781802, ...,   9.18432613,
          -2.55174618,  -4.26523813],
        [ 12.99837238,  13.49555098,  -5.12679432, ...,  -8.76131474,...

======================================================================
FAIL: test_correlate1d (test_filters.TestThreading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\scipy\ndimage\tests\test_filters.py", line 147, in test_correlate1d
    assert_array_equal(os, ot)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 719, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 41.12%)
 x: array([[  3.21790167,  -0.93421372,  -2.55252719, ...,  -8.14940241,
        -14.68842249, -14.25442978],
       [  3.21790167,  -0.93421372,  -2.55252719, ...,  -8.14940241,...
 y: array([[  3.21790167,  -0.93421372,  -2.55252719, ...,  -8.14940241,
        -14.68842249, -14.25442978],
       [  3.21790167,  -0.93421372,  -2.55252719, ...,  -8.14940241,...

======================================================================
FAIL: test_uniform_filter1d (test_filters.TestThreading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\scipy\ndimage\tests\test_filters.py", line 172, in test_uniform_filter1d
    assert_array_equal(os, ot)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 719, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 98.54%)
 x: array([[-0.63712208, -0.53668664, -0.25268181, ..., -0.74188017,
        -0.85684177, -1.13660049],
       [-0.63712208, -0.53668664, -0.25268181, ..., -0.74188017,...
 y: array([[-0.63712208, -0.53668664, -0.25268181, ..., -0.74188017,
        -0.85684177, -1.13660049],
       [-0.63712208, -0.53668664, -0.25268181, ..., -0.74188017,...

======================================================================
FAIL: test_qhull.TestUtilities.test_more_barycentric_transforms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\scipy\spatial\tests\test_qhull.py", line 384, in test_more_barycentric_transforms
    unit_cube_tol=1e7*eps)
  File "C:\Python27\lib\site-packages\scipy\spatial\tests\test_qhull.py", line 311, in _check_barycentric_transforms
    assert_(ok.all(), "%s %s" % (err_msg, np.where(~ok)))
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 35, in assert_
    raise AssertionError(msg)
AssertionError: ndim=5 (array([7345, 7346]),)

======================================================================
FAIL: test_data.test_boost(<Data for btdtri_comp: ibeta_inv_data_ipp-ibeta_inv_data>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\scipy\special\tests\test_data.py", line 481, in _test_factory
    test.check(dtype=dtype)
  File "C:\Python27\lib\site-packages\scipy\special\_testutils.py", line 292, in check
    assert_(False, "\n".join(msg))
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 35, in assert_
    raise AssertionError(msg)
AssertionError: 
Max |adiff|: 7.90146e-13
Max |rdiff|: 8.34159e-07
Bad results (1 out of 1210) for the following points (in output 0):
        0.00022049853578209877                    107380.34375               0.135563462972641 =>          6.19326407745025e-293 !=         6.193269243624209e-293  (rdiff           8.34159432765113e-07)

======================================================================
FAIL: test_continuous_basic.test_cont_basic(<scipy.stats._continuous_distns.nct_gen object at 0x02F69710>, (14, 0.24045031331198066), 'nct')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\testing\decorators.py", line 215, in knownfailer
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\scipy\stats\tests\test_continuous_basic.py", line 380, in check_ppf_private
    npt.assert_(not np.any(np.isnan(ppfs)), msg + 'ppf private is nan')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 35, in assert_
    raise AssertionError(msg)
AssertionError: nctppf private is nan 
```

**Comment by rgommers** [comment] 2015-12-01 21:13
The ``qhull`` and ``boost`` failures I also see (not always reproducibly) on 32-bit Linux. I think there are other issues for them.

**Comment by rgommers** [comment] 2015-12-01 21:24
And the other failures I cannot reproduce with the numpy-vendor setup. Probably depends on CPU. Do you see them on your old XP system, or also under Wine?

**Comment by ev-br** [comment] 2015-12-01 22:10
Not on Wine, no.

**Comment by rgommers** [comment] 2015-12-01 22:12
good, then this is all low prio I would think.

**Comment by ev-br** [comment] 2015-12-01 22:18
yup, bumped the milestone

**Comment by rgommers** [comment] 2016-06-04 16:18
Superpack installers not produced anymore, so closing this as wontfix. If we encounter these test failures also with MingwPy, let's open new issues for them.

**Closed by rgommers** 2016-06-04 16:18 UTC
Labels: defect
