### ISSUE TITLE
savemat does not save keys starting with underscore

### ISSUE THREAD

**Issue by daskol** [scipy/scipy#6052] opened 2016-04-10 19:38 UTC
If one tries to save key with the underscore prefix, mat-file will not contain that key. Mat-file has not ASCII string for the key in hex editor. Try this code
```python
In [1]: savemat('test.mat', {'_key': 0})
In [2]: whosmat('test.mat')
Out[2]: []
```
So the issue is in `savemat` method of `scipy.io` and I probably have solution.

Is there any reason to ignore key with the underscore prefix?

**Comment by ev-br** [comment] 2016-04-10 20:15
Duplicate of https://github.com/scipy/scipy/issues/5435

**Closed** 2016-04-10 22:04 UTC
Labels: scipy.io
