### ISSUE TITLE
_superlu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: dtrsm_

### ISSUE THREAD

**Issue by sciunto** [scipy/scipy#5800] opened 2016-02-02 18:44 UTC
Hi,

I experienced similar issues as described in https://github.com/scikit-learn/scikit-learn/issues/6115 and it's obviously a problem with numpy-scipy.

Here is the minimal steps to reproduce (I use pew to make virtualenv, but should not matter).

```
$ pew mkproject bug_scipy
# Now I'm in my venv.
$ pip install numpy
Collecting numpy
Installing collected packages: numpy
Successfully installed numpy-1.10.4

$ pip install scipy
[...]

$ python -c 'from scipy.sparse.linalg import lsqr as sparse_lsqr'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fr/.local/share/virtualenvs/bug_scipy/lib/python3.5/site-packages/scipy/sparse/linalg/__init__.py", line 113, in <module>
    from .dsolve import *
  File "/home/fr/.local/share/virtualenvs/bug_scipy/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/__init__.py", line 60, in <module>
    from .linsolve import *
  File "/home/fr/.local/share/virtualenvs/bug_scipy/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 10, in <module>
    from . import _superlu
ImportError: /home/fr/.local/share/virtualenvs/bug_scipy/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/_superlu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: dtrsm_

```

Now, if I use a older numpy version

```
$ pip install numpy==1.10.1

$ pip install --upgrade --no-cache-dir  --force-reinstall scipy

$ python -c 'from scipy.sparse.linalg import lsqr as sparse_lsqr'

```

It works.

I'm using archlinux. Some other users reported the same issues on other platforms but some others could not reproduce.

Edit: I identified the minimal version. It's numpy 1.10.2

Full output:
```
[fr:~] % pew mktmpenv 
Using base prefix '/usr'
New python executable in /home/fr/.local/share/virtualenvs/36625cab9272bb/bin/python3
Also creating executable in /home/fr/.local/share/virtualenvs/36625cab9272bb/bin/python
Installing setuptools, pip, wheel...done.
This is a temporary environment. It will be deleted when you exit
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
[fr:~] [36625cab9272bb] %  pip install numpy==1.10.2 --no-cache-dir && pip install scipy --no-cache-dir
Collecting numpy==1.10.2
  Downloading numpy-1.10.2.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 179kB/s 
Installing collected packages: numpy
  Running setup.py install for numpy ... done
Successfully installed numpy-1.10.2
Collecting scipy
  Downloading scipy-0.17.0.tar.gz (12.4MB)
    100% |████████████████████████████████| 12.4MB 2.8MB/s 
Installing collected packages: scipy
  Running setup.py install for scipy ... done
Successfully installed scipy-0.17.0
[fr:~] [36625cab9272bb] % python -c 'from scipy.sparse.linalg import lsqr as sparse_lsqr'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fr/.local/share/virtualenvs/36625cab9272bb/lib/python3.5/site-packages/scipy/sparse/linalg/__init__.py", line 113, in <module>
    from .dsolve import *
  File "/home/fr/.local/share/virtualenvs/36625cab9272bb/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/__init__.py", line 60, in <module>
    from .linsolve import *
  File "/home/fr/.local/share/virtualenvs/36625cab9272bb/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 10, in <module>
    from . import _superlu
ImportError: /home/fr/.local/share/virtualenvs/36625cab9272bb/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/_superlu.cpython-35m-x86_64-linux-gnu.so: undefined symbol: dtrsm_
```

Thanks.

**Comment by pv** [comment] 2016-02-02 18:51
Why does your new virtualenv already have scipy installed?
Is the relevant command actually just the scipy reinstall one?

Most likely, this is something specific to your configuration and not something to do with scipy/numpy (e.g. incompatible packages stored in pip's caches, incompatible packages installed somewhere).

**Comment by sciunto** [comment] 2016-02-02 18:59
good point. Let me try to reinstall numpy and scipy without the cache.

**Comment by sciunto** [comment] 2016-02-02 20:38
I still have the problem, even with --no-cache-dir passed to pip

**Comment by pv** [comment] 2016-02-02 20:51
Can you try exactly the same set of commands, starting from `pew mkproject bug_scipy`, and only varying the numpy version. Then please paste the exact commands used and the output to gist.github.com and link here.

Also, (based on what you write above) why does your virtualenv have scipy installed immediately after creation?

I don't have time to return to this, but maybe someone else wants to spend time on it.

**Comment by sciunto** [comment] 2016-02-02 23:10
I'll try the different versions.

To answer your question, no scipy is not installed immediately after creation. 

```
$ pew mkproject empty
$ python -c 'import scipy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'scipy'
```

**Comment by sciunto** [comment] 2016-02-06 21:49
Extra test with numpy 1.10.2. I updated the first message.

**Comment by rgommers** [comment] 2016-02-07 10:02
Hmm, that's four different people with the exact same issue, something is fishy here. This is a BLAS-related issue, and there's one PR that went into numpy 1.10.2 that looks related: https://github.com/numpy/numpy/pull/6717. The issue discussed there was fixed recently in https://github.com/numpy/numpy/pull/6757, and that also went into 1.10.2. All people with issues were using Arch or Debian, and it looks like it only shows up if ATLAS is not installed.

@sciunto can you check if the problem disappears if you install ATLAS with your package manager? And please run pip with the ``-v`` flag, so we get the full build log.

**Comment by sciunto** [comment] 2016-02-07 12:43
Hi Ralf.

I confirm that replacing blas by atlas (package atlas-lapack-base on archlinux) solves the issue.
Next, I try the verbose option.

**Comment by sciunto** [comment] 2016-02-07 13:22
@rgommers https://gist.github.com/sciunto/72082b85fac814652a89

**Comment by rgommers** [comment] 2016-02-13 21:20
@sciunto unfortunately there's no build output even though you provided ``-v``. ``pip`` is quite annoying with that, and its behavior can depend on the version you have installed. Could you please try again? You can specify multiple ``-v``s for more verbosity and maybe ``-q`` as well (that makes ``setuptools`` noisier IIRC). Sorry to not be more specific, this is a bit of a pain.

**Comment by sciunto** [comment] 2016-02-13 21:59
@rgommers I tried actually with numpy, but nothing more (-v, -vv or -vvv). pip --help tells me that 3v is the maximum. -q is for quiet, nothing I could get from that. I also tried to dump in a LOG with --log. No difference.

I'm using pip 8.0.2

**Comment by rgommers** [comment] 2016-02-14 13:47
Unbelievable, now even this is broken in ``pip``. I'm still trying to find the exact change that caused the problem, but ``-v`` in ``pip`` 7.0.0 shows you the build log while in 8.0.1 it doesn't anymore. I'll file a bug against ``pip``.

**Comment by rgommers** [comment] 2016-02-14 14:05
Submitted https://github.com/pypa/pip/issues/3486. @sciunto this should work:

    pip install pip==7.1.2 --user   # assuming your pip is currently in user dir
    # now re-build scipy with ``-v``
    pip install --upgrade pip --user

**Comment by sciunto** [comment] 2016-02-14 14:07
I confirm. 7.0.0 gives me details. i'll post that.

**Comment by sciunto** [comment] 2016-02-14 15:10
@rgommers 

Part1: https://gist.github.com/sciunto/404eb11cab6bd3875d9a (numpy)
Part2: https://gist.github.com/sciunto/6d346e3b64575dbb1af1 (scipy + test)

**Comment by rgommers** [comment] 2016-02-14 15:35
It's definitely a numpy bug not completely fixed by https://github.com/numpy/numpy/pull/6717, an ``-lcblas`` seems to have gone missing there (see discussion at the end).

I'm not sure whether it's also an issue in ``dsolve`` though, because that's the only scipy submodule that suffers here. There are a bunch of compile warnings for it like these:

    scipy/sparse/linalg/dsolve/SuperLU/SRC/dgstrs.c:191:3: attention : implicit declaration of function ‘dtrsm_’ [-Wimplicit-function-declaration]
       dtrsm_("L", "L", "N", "U", &nsupc, &nrhs, &alpha,
       ^
    scipy/sparse/linalg/dsolve/SuperLU/SRC/dgstrs.c:194:3: attention : implicit declaration of function ‘dgemm_’ [-Wimplicit-function-declaration]
       dgemm_( "N", "N", &nrow, &nrhs, &nsupc, &alpha,
       ^

**Comment by rgommers** [comment] 2016-02-14 15:41
> It's definitely a numpy bug not completely fixed by numpy/numpy#6717, an -lcblas seems to have gone missing there (see discussion at the end).

The issue for building numpy itself against CBLAS was probably fixed completely in https://github.com/numpy/numpy/pull/6757.

**Comment by rgommers** [comment] 2016-02-14 16:01
``_superlu.so`` does have ``-llapack -lcblas`` flags:

    gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-3.5/scipy/sparse/linalg/dsolve/_superlumodule.o
    build/temp.linux-x86_64-3.5/scipy/sparse/linalg/dsolve/_superlu_utils.o build/temp.linux-x86_64-3.5/scipy/sparse/linalg/dsolve/_superluobject.o
    -L/usr/lib64 -L/usr/lib -Lbuild/temp.linux-x86_64-3.5 -lsuperlu_src -llapack -lcblas -lpython3.5m
    -o build/lib.linux-x86_64-3.5/scipy/sparse/linalg/dsolve/_superlu.cpython-35m-x86_64-linux-gnu.so

**Comment by sciunto** [comment] 2016-02-14 16:21
I installed numpy from master and scipy from pip, and I can run
`python -c 'from scipy.sparse.linalg import lsqr as sparse_lsqr'` without error.

**Comment by rgommers** [comment] 2016-02-14 16:28
So 1.10.2-1.10.4 are all problematic, but master is OK? I'll have a browse through the commit log to see possible candidates that could explain this. 

Would be good to try 1.11.0b3 as well, would be nice if that worked too.

**Comment by sciunto** [comment] 2016-02-14 16:34
yes, master looks good (I should have started from that). I'll give a try again 1.11.0b3

**Comment by sciunto** [comment] 2016-02-14 17:44
beta 3 looks good to me.

@AndreRoehrig @sgargbugreporter @fkraus Would you mind to check that numpy-1.11.0b3 solves the problem also for you?

**Comment by rgommers** [comment] 2016-02-14 19:39
Thanks @sciunto. That means this was fixed by either gh-7005 or gh-7048.

**Comment by johncant** [comment] 2016-02-22 20:25
Hi, I'd like to confirm that the bug is fixed in master, but I'm pretty sure it's still present in 1.11.0b3. Thankyou for fixing it!

**Comment by erbridge** [comment] 2016-03-05 22:22
I also had this issue on Arch, and updating to `1.11.0rc1` and reinstalling `scipy` solved the problem.

**Comment by Tommalla** [comment] 2016-04-19 17:18
I just had the exact same problem with `1.10.4`. A downgrade to `1.10.1` and reinstalling `scipy` fixed the issue. I haven't tried `1.11`.

**Comment by pv** [comment] 2016-05-07 21:02
Apparently confirmed fixed (and also a numpy issue), so closing.

**Closed by pv** 2016-05-07 21:02 UTC
Labels: Build issues
