### ISSUE TITLE
basinhopping result violates constraints

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#7799] opened 2017-08-27 16:49 UTC
`scipy.optimize.basinhopping` fails when constraints are specified, returning a result that violates the constraints, even though the minimizer can easily find the solution that fits the constraints.

### Reproducing code example:
```
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize


def func(x):
    return (x**2-8)**2+(x+2)**2


x0 = -4
x = np.linspace(-5, 5, 10000)
plt.plot(x, func(x))
plt.plot(x0, func(x0), 'x')

# Constrain to func value >= 50
limit = 50
cons = ({'type': 'ineq', 'fun': lambda x: func(x) - limit},)
plt.axhspan(limit, np.amax(func(x)), alpha=0.1)

# This returns an invalid result
result_bh = optimize.basinhopping(func, x0, disp=True,
                                  minimizer_kwargs={'constraints': cons})

plt.plot(result_bh['x'], result_bh['fun'], 'ro')
print(result_bh)
print('---------------------------------')

# This finds the correct result easily
result_min = optimize.minimize(func, x0, constraints=cons)

plt.plot(result_min['x'], result_min['fun'], 'go')
print(result_min)
```

### Results:
`scipy.optimize.basinhopping` (red dot at -3.816, 46.353306367220874):
```
                        fun: 46.353306367220874
 lowest_optimization_result:      fun: 46.353306367220874
     jac: array([-103.789])
 message: 'Positive directional derivative for linesearch'
    nfev: 113
     nit: 28
    njev: 24
  status: 8
 success: False
       x: array([-3.816])
                    message: ['requested number of basinhopping iterations completed successfully']
      minimization_failures: 49
                       nfev: 7064
                        nit: 100
                       njev: 1444
                          x: array([-3.816])
```

`scipy.optimize.minimize` (green dot at -3.85, 49.99991873706809):
```
    fun: 49.99991873706809
     jac: array([-108.809])
 message: 'Optimization terminated successfully.'
    nfev: 28
     nit: 10
    njev: 6
  status: 0
 success: True
       x: array([-3.85])
```

![green good red bad](https://user-images.githubusercontent.com/58611/29752116-0586cc8a-8b26-11e7-97bb-94cf9ad44b4b.png)

### Scipy/Numpy/Python version information:
```
0.19.0 1.13.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment] 2017-08-28 09:07
I can reproduce this. I have the feeling that if you want constraints in a global optimizer, it'll be more robust to have your function return +inf in the forbidden regions, rather than relying on the local minimizer that's used under the hood. Likely still a bug though, and there'll probably be more of those.

**Comment by endolith** [comment] 2017-08-28 22:58
So the minimizer converges to the bad value if you give it an x0 outside of the constraints:

![starting at -3](https://user-images.githubusercontent.com/58611/29797015-7b7d4e94-8c22-11e7-8eb5-bec818b839ba.png)

The basinhopping algorithm notices that the local minimizer has failed, prints a warning, but then keeps the result anyway.  Is there any legitimate reason why it should do this? Whether from constraints/boundaries failure or for some other reason, I would think a failed minimization should be discarded.

**Comment by endolith** [comment] 2017-08-28 23:28
Though I was also thinking that basinhopping should have a `bounds=` parameter, which rejects steps that go outside bounds, and these bounds are also passed to the minimizer, but then I realized there might be cases where *starting* your search outside of bounds allows you to find a better minimum inside of bounds, so that isn't a great idea.  (Also bounding the starting points can be done (in a more complicated way) using a `take_step` function as here: https://stackoverflow.com/a/21967888/125507)

**Comment by endolith** [comment] 2017-08-29 04:20
Also it seems the accept_test doesn't apply to the first minimization, but it probably should work the same way for each?  Or the first init shouldn't minimize at all and should just evaluate the value you give it?  But that's still behaving differently.  I feel like it should behave the same each time. 

https://www.hindawi.com/journals/aai/2012/674832/alg1/  this shows a first minimization stage though

**Comment by rgommers** [comment] 2017-08-29 06:59
> The basinhopping algorithm notices that the local minimizer has failed, prints a warning, but then keeps the result anyway. Is there any legitimate reason why it should do this?

Not that I can think of.

> Whether from constraints/boundaries failure or for some other reason, I would think a failed minimization should be discarded.

Agreed

> Though I was also thinking that basinhopping should have a bounds= parameter,

That's a feature request. Could make sense, probably not that much work. Need to think carefully about the API though - if the bounds keyword of the local solvers is not uniform, then this may be quite annoying.

**Comment by endolith** [comment] 2017-08-30 01:28
(Also it seems a little odd that the default RandomDisplacement uses uniform distribution for each variable, so the distribution of steps is rectangular instead of spherical.  Probably doesn't make much practical difference?)

I'm reading through how it works and making changes to docstrings, etc.

**Comment by matthuszagh** [comment] 2020-06-02 17:28
I'm experiencing the same issue. What's the recommended way to work around this given that it sounds like the bug has not yet been fixed? Should I make my cost function return `np.Inf` for values violating the constraints?

**Comment by JorgenPhi** [comment] 2020-06-02 18:01
I agree it seems like this has been put on hold for an official fix. I also
tried the Inf in my objective function  and it didn’t help get me closer to
better results. I forked scipy and merged the incomplete PR in, added a few
edits and that is working well enough for me now.

**Comment by endolith** [comment] 2020-06-02 18:30
@JorgenPhi You mean you merged https://github.com/scipy/scipy/pull/7819?  Can you comment on that PR and say whether you think it's a good solution or not?  It's probably very out of date at this point

**Comment by andreamoro-git** [comment] 2022-10-19 20:25
> 



> I'm experiencing the same issue. What's the recommended way to work around this given that it sounds like the bug has not yet been fixed? Should I make my cost function return `np.Inf` for values violating the constraints?

np.Inf is not a good idea because it creates a flat region ...  there are at least two options which I use
1) create a loss function that takes a large value outside the bounds, but increasing with the distance from the bounds
2) if the bounds are "simple", transform the variable e.g. if the variable x is in [a,b], transform x'=a+b*(exp(x)/exp(x+1)) and maximize over the unconstrained x. YOu may want to experiment with using a different exponential such as 1.2**x / 1.2**(x+1) to make the transformation less sensitive, depending on your problem

**Comment by mdhaber** [comment] 2022-10-20 19:44
@endolith gh-7819 introduces an `InvalidResult` class, but that is not essential to fixing this problem and may not be a desired enhancement. I'd be happy to review and merge a new PR targeted at fixing this bug. Actually, I'd suggest three separate PRs to resolve this issue at different levels.

1. Ultimately, the _bug_ is that the `update` method of the `Storage` class accepts a new global minimum whether or not local search was successful

https://github.com/scipy/scipy/blob/f5508d8f10f7e6e649059f91bb0de94ae682cdea/scipy/optimize/_basinhopping.py#L23-L28

This cannot be correct because this can cause `basinhopping` to return an infeasible solution even when at least one locally optimal solution has been found. The minimal fix to this issue is to change line 24 to `if minres.fun < self.minres.fun and minres.success:`. Nothing else is required to close this issue, All the rest would be enhancements.

2. Note that part 1 does not change whether or not the step is accepted because it is arguable that sometimes a step should be accepted even if it is not feasible. I think that the suggestion https://github.com/scipy/scipy/pull/7819#issuecomment-1272782869 is a little heavy-handed because it prevents user-defined acceptance test from accepting steps from unsuccessful local search. Nonetheless, the _default_ behavior should probably not accept steps from unsuccessful local search. So I would suggest that `Metropolis` call method should be passed _all_ information about the previous and current step results, i.e. the whole `OptimizeResult` object, and it should never accept a step from an unsuccessful local search if the previous local search was successful. (We might also want to pass the result from the best minimum found so far, e.g. `support.get_lowest`, but that can be decided as we review the PR.) A simple way to make this change for `Metropolis` only is to check whether `isinstance(test, Metropolis)` here:

https://github.com/scipy/scipy/blob/f5508d8f10f7e6e649059f91bb0de94ae682cdea/scipy/optimize/_basinhopping.py#L118-L134

and if so, call the test with both old and new `OptimizeResult`s.

3. It is reasonable for user-defined tests to have access to the same information as `Metropolis` so that it can make an informed decision about whether to accept a step from failed local search. To do this, we can use the `inspect` module to do introspection about the signature of the `accept_test` callable and, if it satisfies the new interface, we pass it both old and new optimize results instead of giving it only the old and new function values and decision variables.

How does this sound?

**Comment by endolith** [comment] 2022-10-21 23:26
@mdhaber 

> The minimal fix to this issue is to change line 24 to if minres.fun < self.minres.fun and minres.success:.

So exclude the out-of-bounds results from `minres`, but always keep them as intermediate steps?  So it would say that the step was accepted (`accepted 1`) but not `found new global minimum`?  I think that makes sense.

Is it guaranteed that the result of a failed minimization is still a legitimate function value?

> So I would suggest that Metropolis call method should be passed all information about the previous and current step results, i.e. the whole OptimizeResult object

That makes sense to me.

> and it should never accept a step from an unsuccessful local search if the previous local search was successful. 

Should this be built into the Metropolis class, or should it be its own entry in the `accept_tests` list?  So each test can be used independently? 

https://github.com/scipy/scipy/blob/f5508d8f10f7e6e649059f91bb0de94ae682cdea/scipy/optimize/_basinhopping.py#L708-L716

> To do this, we can use the inspect module to do introspection about the signature of the accept_test callable and, if it satisfies the new interface, we pass it both old and new optimize results instead of giving it only the old and new function values and decision variables.

Can you give an example of how that would work?

**Comment by mdhaber** [comment] 2022-10-22 00:08
> Is it guaranteed that the result of a failed minimization is still a legitimate function value?

It will be a value of the function returned by the user-provided function. Whether that is legitimate or not depends on the user's function. (I'm not aware of any `minimize` methods that tack on, say, a penalty to the objective function value when it doesn't satisfy the constraints and include that in the result returned to the user, if that's what you're getting at. If that's not what you were thinking of, see details below.)

<details>
Sometimes an objective function value is perfectly legitimate even when the decision variables `x` violate the constraints. For example, suppose the objective function is the (negative of the) distance a cannonball is fired, our decision variables are the angle of the shot and the exit velocity of the cannonball, and there are bounds on the decision variables because there are limits on the amount of gunpowder that can be used and the angles to which the cannon can be tilted.

The objective function will probably still give a reasonable result for the distance even if the exit velocity exceeds the allowed bound by a little bit; this is what _would_ happen if more gunpowder could be packed in. But if the tilt angle were _straight down into the ground_ (which probably violates the bound constraints), I can imagine that some ways of writing the objective function would give an inaccurate result. Others would give a reasonable answer like `0`. It depends on the way the user writes the function. `minimize` just evaluates the function whether the decision variables satisfy the constraints or not, and it shows the result returned by the function.
</details>

> Should this be built into the Metropolis class, or should it be its own entry in the accept_tests list?

Oops, you're right, appending it to the default list might be easier. 

> So each test can be used independently?

I don't think `Metropolis` or this new test would be public, so we would control whether they are used together or independently. Just wanted to make sure that is clear.

Perhaps the question is whether, for step 2, we always want to reject steps from failed optimization or only when the user does not provide `accept_test`. Maybe it would be best to always reject steps from failed optimizations (unless the user uses `"force accept"`). In that case, they would not need to be independent.

**Closed** 2022-12-10 15:07 UTC
Labels: defect, scipy.optimize

**Comment by mdhaber** [comment] 2022-12-10 16:42
gh-17483 completed 1 and 2 from https://github.com/scipy/scipy/issues/7799#issuecomment-1286053309 and everything required for 3, really, except for making the new interface public (documenting it). I don't know if that needs to be tracked as a separate issue, but a PR for that would be welcome.
