### ISSUE TITLE
BUG: Cannot compile for 3.11

### ISSUE THREAD

**Issue by rishacha** [scipy/scipy#16262] opened 2022-05-24 18:19 UTC
### Describe your issue.

**Version used**
[Uploading scipy-compile.log…]()
 : `Using cached scipy-1.6.1.tar.gz (27.3 MB)`

I've attached the log file and the suspected issue - 

### Reproducing Code Example

```python
pip install scipy
Pip version - pip 22.1.1 from /home/rishacha/.local/lib/python3.11/site-packages/pip (python 3.11)
Python version - Python 3.11.0b1
OS - elementaryOS
```

### Error message

```shell
2022-05-24T23:43:03,313   scipy/cluster/_vq.c:196:12: fatal error: longintrepr.h: No such file or directory
2022-05-24T23:43:03,313     196 |   #include "longintrepr.h"
2022-05-24T23:43:03,313         |            ^~~~~~~~~~~~~~~
2022-05-24T23:43:03,313   compilation terminated.
```

### SciPy/NumPy/Python version information

>>> import sys, numpy; print("Numpy version: ", numpy.__version__,"\nSys version: ", sys.version_info) Numpy version:  1.22.3  Sys version:  sys.version_info(major=3, minor=11, micro=0, releaselevel='beta', serial=1)

**Comment by ev-br** [comment] 2022-05-24 18:37
> Using cached scipy-1.6.1.tar.gz

Can you retry with a more recent version? I don't think 1.6.1 is really supported anymore.

**Comment by rishacha** [comment] 2022-05-24 18:57
Command I used - `pip install --no-cache-dir --upgrade scipy` and my pip is the latest version (pip 22.1.1 from /home/rishacha/.local/lib/python3.11/site-packages/pip (python 3.11). 

Can you help me solve this issue? I can't seem to find the latest scipy

```
$ pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in ./.local/lib/python3.11/site-packages (22.1.1)
$ pip install scipy==1.8.1
Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement scipy==1.8.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0rc1, 1.6.0rc2, 1.6.0, 1.6.1)
ERROR: No matching distribution found for scipy==1.8.1
```

**Comment by ev-br** [comment] 2022-05-24 19:22
Your pip listing indeed has 1.6.1 as the last version, which is weird. At any rate this is not a scipy issue. Maybe try a different machine / different pip version.

**Comment by tupui** [comment] 2022-05-24 22:03
Also you would need to compile manually. Installing SciPy from source from PyPi does not work.

I don't think there is any issues there since we have Python 3.11-beta in the CI. I will let you be the final judge and close @ev-br

**Comment by andyfaff** [comment] 2022-05-24 22:04
Python3.11 is not yet released, only Beta versions, so there are no wheels available on PyPI. That is why pip starts off a build process. If you downgrade to Python 3.10 you'll have an easier time installing a pre-built wheel.

If you want to persist with 3.11 the error message you're seeing is because the longintrepr.h file has been moved, https://github.com/cython/cython/issues/4461https://github.com/cython/cython/issues/4461. If you upgrade to the latest version of cython you may have more success.

**Comment by rishacha** [comment] 2022-05-25 12:03
@andyfaff -  Installed Cython from source - No change
@tupui - Tried installing scipy from source and get this error - `FileNotFoundError: [Errno 2] No such file or directory: '/media/rishacha/DATA/code/open_sauce/scipy-main/scipy/_lib/highs/CMakeLists.txt'`

**Comment by tupui** [comment] 2022-05-25 12:47
You have to follow our guidelines to compile SciPy from source otherwise it will not work https://docs.scipy.org/doc/scipy/dev/contributor/contributor_toc.html#development-environment 

> Any idea when PyPi will support Python 3.11 for scipy?

SciPy wheels for Python 3.11 will only be available on PyPi after Python 3.11 releases. Not before, and it will certainly take up to a couple of month to make it happen.

**Comment by tupui** [comment] 2022-05-25 12:49
On the submodule init, seems like it is trying to get the `master` branch which does not exist and got renamed to `main` on all the org repository including boost.

**Comment by rishacha** [comment] 2022-05-25 13:14
Do I put in a fix for this?

**Comment by tupui** [comment] 2022-05-25 13:16
I do not think there are any issues to fix. What do you mean concretely?

**Comment by tupui** [comment] 2022-05-25 13:22
Which instruction did you follow? This is really not clear.

**Comment by rishacha** [comment] 2022-05-25 13:46
If I follow the second last point here, I get the same error. 

**I don't want to go the conda route**. Is there no guide for normal python-based compilation?

![image](https://user-images.githubusercontent.com/30197357/170275003-6e040e68-a777-4b67-81b0-a9461fbf6e82.png)

I followed the first step - 
![image](https://user-images.githubusercontent.com/30197357/170275602-f20ec9e7-c0aa-4ee0-b85b-aaa29ccf8762.png)

It doesn't work because it __can't find the submodules__. Also, I found the options a bit confusing. None of the above have worked for me. It still doesn't compile, even after `git submodule --init/git submodule --update` command.

**Comment by rishacha** [comment] 2022-05-25 14:45
Yes, I did everything from scratch, including cloning SciPy. 

I will however, give it another shot with a totally new docker image (just to be sure it's not my machine causing issues). 

I tried using conda too. Still not able to build the package.

```sh
(scipy-dev) rishacha@msi:.../code/open_sauce/scipy$ python setup.py install
/media/rishacha/DATA/code/open_sauce/scipy/setup.py:123: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.command.sdist import sdist

Note: for reliable uninstall behaviour and dependency installation
and uninstallation, please use pip instead of using
`setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


Running from SciPy source directory.
Cythonizing sources
Running scipy/linalg/_generate_pyx.py
Running scipy/special/_generate_pyx.py
Running scipy/stats/_generate_pyx.py
scipy/linalg/_generate_pyx.py: all files up-to-date
scipy/special/_generate_pyx.py: all files up-to-date
scipy/cluster/_hierarchy.pyx has not changed
scipy/cluster/_optimal_leaf_ordering.pyx has not changed
scipy/linalg/_matfuncs_sqrtm_triu.pyx has not changed
scipy/linalg/_solve_toeplitz.pyx has not changed
scipy/linalg/_cythonized_array_utils.pyx has not changed
scipy/linalg/_decomp_update.pyx.in has not changed
scipy/ndimage/src/_cytest.pyx has not changed
scipy/ndimage/src/_ni_label.pyx has not changed
scipy/io/matlab/_mio_utils.pyx has not changed
scipy/optimize/_group_columns.pyx has not changed
scipy/optimize/cython_optimize/_zeros.pyx.in has not changed
scipy/optimize/_lsq/givens_elimination.pyx has not changed
scipy/optimize/_trlib/_trlib.pyx has not changed
scipy/optimize/tnc/_moduleTNC.pyx has not changed
scipy/optimize/_highs/cython/src/_highs_constants.pyx has not changed
scipy/optimize/_highs/cython/src/_highs_wrapper.pyx has not changed
scipy/interpolate/_bspl.pyx has not changed
scipy/signal/_peak_finding_utils.pyx has not changed
scipy/signal/_sosfilt.pyx has not changed
scipy/signal/_spectral.pyx has not changed
scipy/signal/_upfirdn_apply.pyx has not changed
scipy/sparse/_csparsetools.pyx.in has not changed
scipy/sparse/csgraph/_flow.pyx has not changed
scipy/sparse/csgraph/_matching.pyx has not changed
scipy/sparse/csgraph/_min_spanning_tree.pyx has not changed
scipy/sparse/csgraph/_reordering.pyx has not changed
scipy/sparse/csgraph/_shortest_path.pyx has not changed
scipy/signal/_max_len_seq_inner.pyx has not changed
scipy/interpolate/_ppoly.pyx has not changed
scipy/spatial/_ckdtree.pyx has not changed
scipy/spatial/_hausdorff.pyx has not changed
scipy/spatial/_qhull.pyx has not changed
scipy/linalg/cython_blas.pyx has not changed
scipy/linalg/cython_lapack.pyx has not changed
scipy/special/cython_special.pyx has not changed
scipy/special/_ellip_harm_2.pyx has not changed
scipy/fftpack/convolve.pyx has not changed
scipy/special/_ufuncs.pyx has not changed
scipy/special/_ufuncs_cxx.pyx has not changed
scipy/special/_comb.pyx has not changed
scipy/stats/_qmc_cy.pyx has not changed
scipy/stats/_sobol.pyx has not changed
scipy/stats/_stats.pyx has not changed
scipy/stats/_biasedurn.pyx has not changed
scipy/stats/_levy_stable/levyst.pyx has not changed
scipy/stats/_unuran/unuran_wrapper.pyx has not changed
scipy/stats/_boost/src/beta_ufunc.pyx has not changed
scipy/stats/_boost/src/binom_ufunc.pyx has not changed
scipy/stats/_boost/src/hypergeom_ufunc.pyx has not changed
scipy/stats/_boost/src/nbinom_ufunc.pyx has not changed
scipy/stats/_boost/src/ncf_ufunc.pyx has not changed
scipy/_lib/messagestream.pyx has not changed
scipy/_lib/_ccallback_c.pyx has not changed
scipy/_lib/_test_deprecation_call.pyx has not changed
scipy/_lib/_test_deprecation_def.pyx has not changed
scipy/spatial/transform/_rotation.pyx has not changed
scipy/linalg/_matfuncs_expm.pyx.in has not changed
scipy/cluster/_vq.pyx has not changed
scipy/special/_test_round.pyx has not changed
scipy/interpolate/interpnd.pyx has not changed
scipy/sparse/csgraph/_tools.pyx has not changed
scipy/sparse/csgraph/_traversal.pyx has not changed
scipy/io/matlab/_mio5_utils.pyx has not changed
scipy/optimize/_bglu_dense.pyx has not changed
scipy/io/matlab/_streams.pyx has not changed
scipy/spatial/_voronoi.pyx has not changed
INFO: lapack_opt_info:
INFO: lapack_armpl_info:
INFO: customize UnixCCompiler
INFO: C compiler: /home/rishacha/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -fPIC -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -fPIC

creating /tmp/tmpw2mg16sk/tmp
creating /tmp/tmpw2mg16sk/tmp/tmpw2mg16sk
INFO: compile options: '-MMD -MF /tmp/tmpw2mg16sk/file.c.d -c'
INFO: x86_64-conda-linux-gnu-cc: /tmp/tmpw2mg16sk/file.c
INFO:   libraries armpl_lp64_mp not found in ['/home/rishacha/anaconda3/envs/scipy-dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: lapack_mkl_info:
INFO:   libraries mkl_rt not found in ['/home/rishacha/anaconda3/envs/scipy-dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: openblas_lapack_info:
INFO: C compiler: /home/rishacha/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -fPIC -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -fPIC

creating /tmp/tmpttvo_ord/tmp
creating /tmp/tmpttvo_ord/tmp/tmpttvo_ord
INFO: compile options: '-c'
INFO: x86_64-conda-linux-gnu-cc: /tmp/tmpttvo_ord/source.c
INFO: /home/rishacha/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc /tmp/tmpttvo_ord/tmp/tmpttvo_ord/source.o -L/home/rishacha/anaconda3/envs/scipy-dev/lib -lopenblas -o /tmp/tmpttvo_ord/a.out
INFO:   FOUND:
INFO:     libraries = ['openblas', 'openblas']
INFO:     library_dirs = ['/home/rishacha/anaconda3/envs/scipy-dev/lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
INFO:   FOUND:
INFO:     libraries = ['openblas', 'openblas']
INFO:     library_dirs = ['/home/rishacha/anaconda3/envs/scipy-dev/lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/system_info.py:937: UserWarning: Specified path /usr/local/include/python3.10 is invalid.
  return self.get_paths(self.section, key)
non-existing path in 'scipy/linalg': 'src/lapack_deprecations/LICENSE'
INFO: blas_opt_info:
INFO: blas_armpl_info:
INFO:   libraries armpl_lp64_mp not found in ['/home/rishacha/anaconda3/envs/scipy-dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: blas_mkl_info:
INFO:   libraries mkl_rt not found in ['/home/rishacha/anaconda3/envs/scipy-dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: blis_info:
INFO:   libraries blis not found in ['/home/rishacha/anaconda3/envs/scipy-dev/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
INFO:   NOT AVAILABLE
INFO: 
INFO: openblas_info:
INFO: C compiler: /home/rishacha/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -fPIC -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/rishacha/anaconda3/envs/scipy-dev/include -fPIC

creating /tmp/tmp4161pv39/tmp
creating /tmp/tmp4161pv39/tmp/tmp4161pv39
INFO: compile options: '-c'
INFO: x86_64-conda-linux-gnu-cc: /tmp/tmp4161pv39/source.c
INFO: /home/rishacha/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc /tmp/tmp4161pv39/tmp/tmp4161pv39/source.o -L/home/rishacha/anaconda3/envs/scipy-dev/lib -lopenblas -o /tmp/tmp4161pv39/a.out
INFO:   FOUND:
INFO:     libraries = ['openblas', 'openblas']
INFO:     library_dirs = ['/home/rishacha/anaconda3/envs/scipy-dev/lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
INFO:   FOUND:
INFO:     libraries = ['openblas', 'openblas']
INFO:     library_dirs = ['/home/rishacha/anaconda3/envs/scipy-dev/lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
Traceback (most recent call last):
  File "/media/rishacha/DATA/code/open_sauce/scipy/setup.py", line 532, in <module>
    setup_package()
  File "/media/rishacha/DATA/code/open_sauce/scipy/setup.py", line 528, in setup_package
    setup(**metadata)
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "/media/rishacha/DATA/code/open_sauce/scipy/setup.py", line 438, in configuration
    config.add_subpackage('scipy')
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 1054, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 1020, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "/media/rishacha/DATA/code/open_sauce/scipy/scipy/setup.py", line 18, in configuration
    config.add_subpackage('optimize')
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 1054, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 1020, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "/media/rishacha/DATA/code/open_sauce/scipy/scipy/optimize/setup.py", line 147, in configuration
    config.add_subpackage('_highs')
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 1054, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 1020, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/home/rishacha/.local/lib/python3.10/site-packages/numpy/distutils/misc_util.py", line 962, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "/media/rishacha/DATA/code/open_sauce/scipy/scipy/optimize/_highs/setup.py", line 63, in configuration
    _major_dot_minor = _get_version(
  File "/media/rishacha/DATA/code/open_sauce/scipy/scipy/optimize/_highs/setup.py", line 50, in _get_version
    with open(CMakeLists, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/rishacha/DATA/code/open_sauce/scipy/scipy/_lib/highs/CMakeLists.txt'
```

**Comment by rgommers** [comment] 2022-05-26 08:56
Why this picked up scipy 1.6.1 at first: because that was the last version which did not have an upper bound on supported Python versions.

Why the `FileNotFoundError`: because you need to run `git submodule update --init` after cloning the SciPy repo. Then things will work on Python 3.11-dev with current `main` branch.

This is not a bug, so I'll close the issue. Please feel free to continue commenting though @rishacha if you run into more trouble.

**Closed by rgommers** 2022-05-26 08:56 UTC
Labels: defect

**Comment by rishacha** [comment] 2022-05-27 07:05
@rgommers  and @tupui - I got it to work on docker and can finally confirm it's **not a bug** -
```docker
FROM continuumio/miniconda3
RUN git clone https://github.com/scipy/scipy.git
WORKDIR /scipy
SHELL ["/bin/bash", "-c"]
RUN conda init bash && \
source /root/.bashrc &&\
conda env create -f environment.yml &&\ 
conda activate scipy-dev &&\
git submodule update --init &&\
python -m pip install .
```

Build output - `Successfully installed scipy-1.9.0.dev0+2157.26eb830`

I haven't tried for `python3.11`, but I'm guessing it will work as expected. 

Thank you for all your support and patience @rgommers @tupui @andyfaff @ev-br

**Comment by rgommers** [comment] 2022-05-27 07:41
Thanks for confirming @rishacha

**Comment by dstansby** [comment] 2022-07-11 21:36
Are there any plans to do a release with 'support' (I guess removing the Python version pinning) for 3.11 betas in the near future?

**Comment by rgommers** [comment] 2022-07-12 05:07
@dstansby SciPy 1.9.rc2 is already up on PyPI, final release should not be more than 2 weeks off. And we'll add 3.11 wheels after Python 3.11 RC1 is out (which is the point in the release cycle where Python is ABI-stable).

**Comment by rgommers** [comment] 2022-07-12 05:07
You can install that already with `pip install scipy --pre`.
