### ISSUE TITLE
BUG: A bug of Wilcoxon signed rank test

### ISSUE THREAD

**Issue by hengzhe-zhang** [scipy/scipy#20752] opened 2024-05-20 07:32 UTC
### Describe your issue.

I found a bug when using the signed rank test; the p-values are not consistent when flipping the order of two lists. I have checked this in R language, and I found the p-value should be the same when flipping the order. Thus, I believe it is a bug in SciPy. Is there any way to fix it? Thanks!

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import wilcoxon

a= np.array(
    [5.0, 11.0, 13.0, 15.0, 6.0, 5.0, 7.0, 4.0, 48.0, 5.0, 11.0, 7.0, 36.0, 6.0, 12.0, 6.0, 43.0, 7.0, 4.0, 8.0, 19.0,
     27.0, 7.0, 8.0, 6.0, 63.0, 30.0, 9.0, 6.0, 27.0]
)
b= np.array(
    [8.0, 3.0, 2.0, 4.0, 3.0, 1.0, 4.0, 24.0, 20.0, 22.0, 9.0, 11.0, 9.0, 3.0, 4.0, 2.0, 2.0, 11.0, 8.0, 35.0, 7.0, 4.0,
     5.0, 3.0, 11.0, 24.0, 3.0, 29.0, 28.0, 30.0]
)

_, p_value = wilcoxon(a, b)
print(p_value)
_, p_value = wilcoxon(b,a)
print(p_value)
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
SciPy: 1.13.0 
NumPy: 1.26.1
Python: 3.11
```

**Comment by mdhaber** [comment] 2024-05-20 07:53
Duplicate of gh-19872. Will work on this for next release.

**Closed by mdhaber** 2024-05-20 07:53 UTC
Labels: defect, duplicate
