### ISSUE TITLE
Abort Trap 6 in unit tests for morestats

### ISSUE THREAD

**Issue by rlucas7** [scipy/scipy#9785] opened 2019-02-08 03:01 UTC
My issue is about ...

### Reproducing code example:

```
(scipy-dev) Lucass-MacBook:scipy rlucas$ python runtests.py -v -s stats
```

### Error message:

```
                                                                                                               [ 55%]
scipy/stats/tests/test_morestats.py::TestMood::test_mood_order_of_args PASSED                                                                                                 [ 55%]
scipy/stats/tests/test_morestats.py::TestMood::test_mood_with_axis_none PASSED                                                                                                [ 55%]
scipy/stats/tests/test_morestats.py::TestMood::test_mood_2d PASSED                                                                                                            [ 55%]
scipy/stats/tests/test_morestats.py::TestMood::test_mood_3d PASSED                                                                                                            [ 55%]
scipy/stats/tests/test_morestats.py::TestMood::test_mood_bad_arg PASSED                                                                                                       [ 55%]
scipy/stats/tests/test_morestats.py::TestProbplot::test_basic PASSED                                                                                                          [ 55%]
scipy/stats/tests/test_morestats.py::TestProbplot::test_sparams_keyword PASSED                                                                                                [ 55%]
scipy/stats/tests/test_morestats.py::TestProbplot::test_dist_keyword PASSED                                                                                                   [ 55%]
scipy/stats/tests/test_morestats.py::TestProbplot::test_plot_kwarg Abort trap: 6
```

### Scipy/Numpy/Python version information:

```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.0.dev0+6683b5f 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

I did a clean run of the tests, i.e. I first ran 

```
git clean -xdf
``` 
To clean up artifacts in my dev environment.

**Comment by pvanmulbregt** [comment] 2019-02-08 03:26
I have the same issue.  Temporarily worked around it by changing line 25 of `scipy/stats/tests/test_morestats.py` from
```
    have_matplotlib = True
```
to
```
    have_matplotlib = False
```

### Scipy/Numpy/Python version information:
```
1.3.0.dev0+e119b57 1.16.0 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```
Occurred after I built a new condo env, upgrading from
`1.3.0.dev0+a00b057 1.14.2 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)`.

**Comment by ilayn** [comment] 2019-02-08 06:33
I couldn't reproduce it with 

```bash
1.3.0.dev0+b955206 1.17.0.dev0+c009e1b sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

Also I have matplotlib `2.2.2` and also just tested with `3.0.2`

**Comment by rlucas7** [comment] 2019-02-09 15:34
looks like I have matplotlib version 3.0.1

(scipy-dev) Lucass-MacBook:stats rlucas$ pip3 install matplotlib
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/site-packages (3.0.1)

**Comment by rlucas7** [comment] 2019-02-09 15:41
I tried installing matplotlib 3.0.2 into conda virtual env and I still get the abort trap.

**Comment by rlucas7** [comment] 2019-02-09 15:49
I just tried the switch on matplotlib.pyplot to false and that fixes stops the abort trap from happening.
To be clear this only happens when I run the testing harness with the -s stats flag. If I run the full test harness `python runtests.py -v` I do not get the abort trap 6 message.

**Comment by pvanmulbregt** [comment] 2019-02-09 23:21
I fixed by setting the backend in matplotlib's rc file.  Before, with the Abort Trap 6
```
$ python -c "import numpy, matplotlib; print(matplotlib.get_backend())"
MacOSX
```
My fix (no more Abort Trap 6)
```
$ echo "backend: TkAgg" >> ~/.matplotlib/matplotlibrc
$ python -c "import numpy, matplotlib; print(matplotlib.get_backend())"
TkAgg
```
One could also set `MPLBACKEND=TkAgg` in the environment to have the same effect.

Other backends may also work (pyqt, GTKCairo, ...)  

[I must admit that I don't know why I didn't see this Abort Trap 6 in my earlier conda env, which differs only slightly from the current one. Hence the above may not be a real solution, but instead it just masks the real culprit.]

**Comment by rgommers** [comment] 2019-02-09 23:31
not sure why the segfault only shows up now, but the test should use the `Agg` backend, similar to https://github.com/scipy/scipy/blob/master/scipy/spatial/tests/test__plotutils.py#L9

**Comment by rlucas7** [comment] 2019-02-10 00:42
@rgommers thanks for pointing this out. 
Adding the line you indicated 
https://github.com/scipy/scipy/blob/master/scipy/spatial/tests/test__plotutils.py#L9
to the tests fixed the issue for me. I opened the bug (not sure if this should be called a bug) fix just now as a PR. Hopefully this fixes the issue for @pvanmulbregt too.

**Closed** 2019-02-11 04:16 UTC
Labels: Build issues, scipy.stats
