### ISSUE TITLE
Extra null-modes when diagonalizing a semi-positive-definite matrix with scipy.sparse.linalg.eigsh

### ISSUE THREAD

**Issue by giopina** [scipy/scipy#6354] opened 2016-07-07 12:29 UTC
I'm using scipy.sparse.linalg.eigsh to find the smallest eigenvalues of a sparse semi positive-definite symmetric matrix.
I'm calling 
e_val,e_vec=eigsh(mat, k=MAXVEC,sigma=0.0)
I'm comparing the results with eigh
The 639x639 matrix I'm analyzing has 6 zero eigenvalues, but  eigsh returns 7 zero-eigenvalues. The following eigenvalues seem to be fine but shifted by one position (see below).
FIRST EIGENVALUES  
        eigsh                    eigh  
    0 0.000000e+00            0 0.000000e+00  
    1 0.000000e+00            1 0.000000e+00  
    2 0.000000e+00            2 0.000000e+00  
    3 0.000000e+00            3 0.000000e+00  
    4 0.000000e+00            4 0.000000e+00  
    5 0.000000e+00            5 0.000000e+00  
    6 0.000000e+00            6 1.482104e-03  
    7 1.493611e-03            7 2.796294e-03  
    8 2.806717e-03            8 4.419883e-03  
    9 4.431705e-03            9 5.111717e-03  
   10 5.154981e-03           10 7.166125e-03  
   11 7.195160e-03           11 1.052578e-02  
   12 1.055332e-02           12 1.441648e-02  
   13 1.447979e-02           13 1.886737e-02  
   14 1.887667e-02           14 2.292426e-02  
   15 2.294213e-02           15 2.695276e-02                                               

Thanks in advance for any help

**Comment by pv** [comment] 2016-07-07 12:33
Please attach the matrix (eg in npy, mat, or h5 format), otherwise it is 
not possible to say much.

**Comment by giopina** [comment] 2016-07-07 12:52
Here it is

[matrix.npy.zip](https://github.com/scipy/scipy/files/352148/matrix.npy.zip)

**Comment by pv** [comment] 2016-07-07 13:20
I think the problem is due to using the shift-invert transformation with 
sigma exactly equal to one of the eigenvalues, which makes the transform 
undefined (in exact arithmetic the matrix is exactly singular, but in 
floating point it is only very close to singular). You can try 
displacing sigma a bit to reduce the error in inversion.
.
Don't close the issue though, since there may be something done to 
detect the near singularity.

**Comment by giopina** [comment] 2016-07-07 14:21
Thanks a lot for the quick reply.

It makes sense. In fact if I use a small non-zero sigma I obtain the expected results.

I didn't run extensive tests yet but it seems to have problems if sigma is too small (~1e-15) or too big compared to the first non-zero eigenvalue. I'd like to find a general recipe that doesn't rely on previous knowledge of the eigenvalues I'm computing. 
Maybe I'm being paranoid, but I'm wondering if there's a general recipe to optimally tune the value of sigma.

**Comment by pv** [comment] 2016-07-07 14:41
The singular values of a symmetric matrix are absolute values of its 
eigenvalues, so reasonable conditioning for the inverse is obtained if 
``min(abs(lambda - sigma)) > const * max(abs(lambda - sigma))`` where 
``const ~ sqrt(eps) ~ 1e-8`` or so, and lambda are the eigenvalues.

**Comment by lobpcg** [comment] 2019-10-12 22:46
To be safe, use a slightly negative very small sigma. Or do not use shift-and-invert. Or try https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lobpcg.html 

It appears that the issue can be safely closed.

**Comment by tylerjereddy** [comment] 2019-10-15 20:13
> It appears that the issue can be safely closed.

Ok, thanks

**Closed by tylerjereddy** 2019-10-15 20:13 UTC
Labels: scipy.sparse.linalg
