### ISSUE TITLE
DOC: bad formatting of *args, **kwargs in autosummary

### ISSUE THREAD

**Issue by pv** [scipy/scipy#10723] opened 2019-08-25 11:47 UTC
The distribution list table in scipy.stats documentation (reference/stats.html) currently looks like this: (https://scipy.github.io/devdocs/stats.html)
```
Continuous distributions

alpha(\*args, \*\*kwds) | An alpha continuous random variable.
anglit(\*args, \*\*kwds) | An anglit continuous random variable.
arcsine(\*args, \*\*kwds) | An arcsine continuous random variable.
argus(\*args, \*\*kwds) | Argus distribution
beta(\*args, \*\*kwds) | A beta continuous random variable.
...
```
Note the backslashes before the asterisks. Apparently, there is some problem in quoting.

This is probably due to some recent numpydoc change --- or some bad interaction with the stats documentation generation, because in some other places these seem to appear fine without backslashes.

#### Reproducing code example:
See https://scipy.github.io/devdocs/stats.html

#### Scipy/Numpy/Python version information:

Current master at e68ff057be595d6787e5870ea8d84033313e8d0f.

**Comment by larsoner** [comment] 2019-08-25 13:34
This is probably fixed by https://github.com/numpy/numpydoc/pull/221

**Comment by rossbar** [comment] 2019-12-17 07:47
I built the scipy docs with numpy/numpydoc#221 and unfortunately it looks like the arguments are removed all together. I've published the result to the gh-pages for my fork of scipy, so the rendered result can be seen [here](https://rossbar.github.io/scipy/stats.html#module-scipy.stats).

The docs were built from scipy 47ffc1ef2 with thequackdaddy/numpydoc@611d59a

**Comment by sethtroisi** [comment] 2020-05-28 22:03
[devdocs](https://scipy.github.io/devdocs/stats.html) looks good 

[1.4.1 docs](https://docs.scipy.org/doc/scipy-1.4.1/reference/stats.html
) and [1.4.0 docs](https://docs.scipy.org/doc/scipy-1.4.0/reference/stats.html) show `\*args, \*\*kwds`

[1.3.3 docs](https://docs.scipy.org/doc/scipy-1.3.3/reference/stats.html) omit `*args and **kdws`

**Comment by rgommers** [comment] 2020-05-29 07:28
I'm not sure we want to go back and fix this for older branches, but if so (that's @charris's call as release manager) then yes I think updating the `doc/sphinxext/numpydoc` submodule is the way to go.

**Comment by mdhaber** [comment] 2022-03-13 22:52
Looks like this was just rendered incorrectly in 1.4.0 and 1.4.1. It rendered as intended in 1.5.0, and since 1.7.0 it has rendered without `(*args, **kwds)` again.

**Closed by mdhaber** 2022-03-13 22:52 UTC
Labels: scipy.stats, Documentation
