### ISSUE TITLE
Attribute error when building the scipy docs

### ISSUE THREAD

**Issue by SuperKogito** [scipy/scipy#10289] opened 2019-06-10 12:56 UTC
My issue is about the scipy docs.
I am trying to build the scipy sphinx documentation. I managed to install scipy from source and successfully run the tests. However when running `sudo make html`, I get the following error: 

### Error message:
```
Exception occurred:
  File "ckdtree.pyx", line 164, in init scipy.spatial.ckdtree
AttributeError: type object 'scipy.spatial.ckdtree.coo_entries' has no attribute '__reduce_cython__'
The full traceback has been saved in /tmp/sphinx-err-2wsd1gah.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:109: recipe for target 'html' failed
```

The full traceback can be found in [logs-file.txt](https://github.com/scipy/scipy/files/3272103/log-file.txt)

### System specs:
- Sphinx-build: 2.1.0
- Scipy: 1.4.0
- Numpy: 1.16.4
- Cython: 0.29.7
- Python: 3.6.7
- OS: Ubuntu 18.04.2 LTS x86_64

**Comment by rgommers** [comment] 2019-06-10 13:18
I've never seen that particular issue. It looks like you're picking up the wrong SciPy or NumPy install though:
```
RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
```
please check that you're using the versions you think you are (e.g. if you did an in-place build, is the build dir on PYTHONPATH?).

Also, never use `sudo`. Simply `make html` will do.

**Comment by peterbell10** [comment] 2019-06-10 13:33
I've had similar errors from the `scipy.spatial` tests. They went away when I upgraded to Python 3.7

**Comment by rgommers** [comment] 2019-08-11 03:20
okay, this is not a bug I think - closing. thanks all

**Closed by rgommers** 2019-08-11 03:20 UTC
Labels: Build issues, Documentation

**Comment by larsoner** [comment] 2019-08-12 20:15
I can reproduce this on CircleCI:

https://circleci.com/gh/scipy/scipy-sphinx-theme/12

No idea why it's happening, but I'm going to resort to building SciPy from source instead of `pip` installing then building the docs.
