### ISSUE TITLE
Broken Source Link on Online Docs

### ISSUE THREAD

**Issue by ddasilva** [scipy/scipy#7683] opened 2017-07-30 02:14 UTC
On this page, clicking the link **[source]** brings you to a 404 page:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.trapz.html

**Comment by ev-br** [comment] 2017-07-30 20:58
Thanks for the report @ddasilva. This seems to be a duplicate ofhttps://github.com/scipy/scipy/issues/3250.

**Comment by pv** [comment] 2017-07-30 21:01
I think this is actually different -- it's the source link generated by sphinx.
The problem is that this code https://github.com/scipy/scipy/blob/master/doc/source/conf.py#L313 doesn't know where numpy sources are.

**Closed** 2017-08-02 19:09 UTC
