### ISSUE TITLE
Cannot subscribe to mailing lists / read direct archives

### ISSUE THREAD

**Issue by thewtex** [scipy/scipy#4950] opened 2015-06-11 03:38 UTC
The [links for Archives and Subscribe](http://www.scipy.org/scipylib/mailing-lists.html) for the scipy-dev and scipy-user lists yield "cannot connect to server".

**Comment by rgommers** [comment] 2015-06-11 06:01
Thanks. Closing as duplicate of https://github.com/numpy/numpy/issues/5957 (same server).

**Closed by rgommers** 2015-06-11 06:01 UTC
