### ISSUE TITLE
Invalid next size error while building scipy

### ISSUE THREAD

**Issue by TakshKamlesh** [scipy/scipy#11580] opened 2020-02-24 08:17 UTC
I am in the process of following the exact steps as mentioned in the scipy contributer guide in order to obtain a development version of scipy . When I run the code ' python3 runtests.py -v ' on terminal , on after passing 22% of the test , it gives an error : 

scipy/linalg/tests/test_decomp.py::TestEigh::test_eigh_integer realloc(): invalid next size
Fatal Python error: Aborted

Sorry its not really possible to reproduce the error.

Specs :
Ubuntu  :  16.04

**Comment by andyfaff** [comment] 2020-02-24 08:24
duplicate of #11576

**Closed by andyfaff** 2020-02-24 08:24 UTC

**Comment by TakshKamlesh** [comment] 2020-02-24 08:40
Thanks
