### ISSUE TITLE
BUG: Errors at compiling through pip for python 3.13 with option "disable-gil"

### ISSUE THREAD

**Issue by olegmikul** [scipy/scipy#21675] opened 2024-10-08 07:30 UTC
### Describe your issue.

Python has installed from source properly and passed all tests beside 2. Pip installed all packages beside scipy and its  derivatives (e.g. scikit-learn). Errors happened only when configuring with option "--disable-gil". 

### Reproducing Code Example

```python
in Python 3.13 directory:
./configure --enable-optimizations --enable-experimental-jit --disable-gil 
make 
make test
make install
python3 -m venv myenv
source myenv/bin/activate
pip install numpy (installation ok)
pip install scipy (errors)

When configuring without "--disable-gil" everything is ok
```

### Error message

```shell
[858/1383] Compiling C object scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o
      FAILED: scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o
      ccache cc -Iscipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p -Iscipy/special -I../scipy/special -Iscipy/_lib -I../scipy/_lib -I../scipy/_build_utils/src -I../../../pip-build-env-3gxasc3d/overlay/lib/python3.13t/site-packages/numpy/_core/include -I/usr/include/openblas -I/home/ol/local/include/python3.13t -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c17 -O3 -Wno-unused-but-set-variable -Wno-unused-function -Wno-conversion -Wno-misleading-indentation -fPIC -DSP_SPECFUN_ERROR -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -DCYTHON_CCOMPLEX=0 -Wno-maybe-uninitialized -MD -MQ scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o -MF scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o.d -o scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o -c scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:3434:80: error: unknown type name ‘__pyx_vectorcallfunc’; did you mean ‘vectorcallfunc’?
       3434 | static CYTHON_INLINE PyObject *__Pyx_PyVectorcall_FastCallDict(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw);
            |                                                                                ^~~~~~~~~~~~~~~~~~~~
            |                                                                                vectorcallfunc
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c: In function ‘__pyx_f_5scipy_7special_11_ellip_harm_lame_coefficients’:
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:10803:3: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
      10803 |   Py_UNICODE __pyx_v_t;
            |   ^~~~~~~~~~
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:10818:3: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
      10818 |   Py_UNICODE __pyx_t_3;
            |   ^~~~~~~~~~
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c: At top level:
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:85648:69: error: unknown type name ‘__pyx_vectorcallfunc’; did you mean ‘vectorcallfunc’?
      85648 | static PyObject *__Pyx_PyVectorcall_FastCallDict_kw(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw)
            |                                                                     ^~~~~~~~~~~~~~~~~~~~
            |                                                                     vectorcallfunc
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:85693:80: error: unknown type name ‘__pyx_vectorcallfunc’; did you mean ‘vectorcallfunc’?
      85693 | static CYTHON_INLINE PyObject *__Pyx_PyVectorcall_FastCallDict(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw)
            |                                                                                ^~~~~~~~~~~~~~~~~~~~
            |                                                                                vectorcallfunc
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c: In function ‘__Pyx_CyFunction_CallAsMethod’:
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:86382:6: error: unknown type name ‘__pyx_vectorcallfunc’; did you mean ‘vectorcallfunc’?
      86382 |      __pyx_vectorcallfunc vc = __Pyx_CyFunction_func_vectorcall(cyfunc);
            |      ^~~~~~~~~~~~~~~~~~~~
            |      vectorcallfunc
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:3524:45: error: initialization of ‘int’ from ‘vectorcallfunc’ {aka ‘struct _object * (*)(struct _object *, struct _object * const*, long unsigned int,  struct _object *)’} makes integer from pointer without a cast [-Wint-conversion]
       3524 | #define __Pyx_CyFunction_func_vectorcall(f) (((PyCFunctionObject*)f)->vectorcall)
            |                                             ^
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:86382:32: note: in expansion of macro ‘__Pyx_CyFunction_func_vectorcall’
      86382 |      __pyx_vectorcallfunc vc = __Pyx_CyFunction_func_vectorcall(cyfunc);
            |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:86385:16: error: implicit declaration of function ‘__Pyx_PyVectorcall_FastCallDict’; did you mean ‘__Pyx_PyObject_FastCallDict’? [-Wimplicit-function-declaration]
      86385 |         return __Pyx_PyVectorcall_FastCallDict(func, vc, &PyTuple_GET_ITEM(args, 0), (size_t)PyTuple_GET_SIZE(args), kw);
            |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |                __Pyx_PyObject_FastCallDict
      scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_ufuncs.c:86385:16: error: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
      86385 |         return __Pyx_PyVectorcall_FastCallDict(func, vc, &PyTuple_GET_ITEM(args, 0), (size_t)PyTuple_GET_SIZE(args), kw);
            |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      [859/1383] Generating 'scipy/optimize/_lsq/givens_elimination.cpython-313t-x86_64-linux-gnu.so.p/givens_elimination.c'
      [860/1383] Generating 'scipy/optimize/_highs/_highs_wrapper.cpython-313t-x86_64-linux-gnu.so.p/_highs_wrapper.cpp'
      [861/1383] Generating 'scipy/linalg/cython_lapack.cpython-313t-x86_64-linux-gnu.so.p/cython_lapack.c'
      [862/1383] Compiling C++ object scipy/special/_ufuncs_cxx.cpython-313t-x86_64-linux-gnu.so.p/ellint_carlson_wrap.cxx.o
      [863/1383] Compiling C++ object scipy/special/_gufuncs.cpython-313t-x86_64-linux-gnu.so.p/_gufuncs.cpp.o
      [864/1383] Generating scipy/linalg/flapack_module with a custom command
      [865/1383] Compiling C++ object scipy/special/_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/special_wrappers.cpp.o
      In file included from ../scipy/special/special/amos.h:3,
                       from ../scipy/special/special/airy.h:3,
                       from ../scipy/special/special_wrappers.cpp:3:
      In function ‘void special::amos::unik(std::complex<double>, double, int, int, double, int*, std::complex<double>*, std::complex<double>*, std::complex<double>*, std::complex<double>*, std::complex<double>*)’,
          inlined from ‘int special::amos::unk1(std::complex<double>, double, int, int, int, std::complex<double>*, double, double, double)’ at ../scipy/special/special/amos/amos.h:5485:13:
      ../scipy/special/special/amos/amos.h:5177:5: warning: ‘initd’ may be used uninitialized [-Wmaybe-uninitialized]
       5177 |     if (*init == 0) {
            |     ^~
      ../scipy/special/special/amos/amos.h: In function ‘int special::amos::unk1(std::complex<double>, double, int, int, int, std::complex<double>*, double, double, double)’:
      ../scipy/special/special/amos/amos.h:5282:20: note: ‘initd’ was declared here
       5282 |         jc, ipard, initd, ic;
            |                    ^~~~~
      [866/1383] Compiling C++ object scipy/special/_special_ufuncs.cpython-313t-x86_64-linux-gnu.so.p/_special_ufuncs.cpp.o
      In file included from ../scipy/special/special/amos.h:3,
                       from ../scipy/special/special/airy.h:3,
                       from ../scipy/special/_special_ufuncs.cpp:8:
      In function ‘void special::amos::unik(std::complex<double>, double, int, int, double, int*, std::complex<double>*, std::complex<double>*, std::complex<double>*, std::complex<double>*, std::complex<double>*)’,
          inlined from ‘int special::amos::unk1(std::complex<double>, double, int, int, int, std::complex<double>*, double, double, double)’ at ../scipy/special/special/amos/amos.h:5485:13:
      ../scipy/special/special/amos/amos.h:5177:5: warning: ‘initd’ may be used uninitialized [-Wmaybe-uninitialized]
       5177 |     if (*init == 0) {
            |     ^~
      ../scipy/special/special/amos/amos.h: In function ‘int special::amos::unk1(std::complex<double>, double, int, int, int, std::complex<double>*, double, double, double)’:
      ../scipy/special/special/amos/amos.h:5282:20: note: ‘initd’ was declared here
       5282 |         jc, ipard, initd, ic;
            |                    ^~~~~
      [867/1383] Compiling C++ object scipy/special/_ufuncs_cxx.cpython-313t-x86_64-linux-gnu.so.p/meson-generated__ufuncs_cxx.cpp.o
      ninja: build stopped: subcommand failed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

### SciPy/NumPy/Python version and system information

```shell
python - 3.13.0 sys.version_info(major=3, minor=13, micro=0, releaselevel='final', serial=0)
numpy - 2.1.2
scipy - 1.14.1
gcc - 14.2.1
linux - 6.11.2-zen1-1-zen
```

**Comment by tylerjereddy** [comment] 2024-10-08 22:59
I suppose the obvious observation is that we do provide regular Python 3.13 wheels for our latest stable release (`1.14.1`) on PyPI but *not* free-threaded Python 3.13 wheels, so that's likely why you're hitting the source build in the free-threaded case.

IIRC we weren't quite ready to fully support free-threaded Python in SciPy just yet. sklearn seems to be waiting for us at https://github.com/scikit-learn/scikit-learn/issues/28978#issuecomment-2393173700.

Let me poke a bit locally..

**Comment by lucascolley** [comment] 2024-10-08 23:36
x-ref gh-20669

**Comment by tylerjereddy** [comment] 2024-10-09 00:11
I can reproduce locally on Linux in a Python `3.13.0` stable release (free-threaded) venv when `pip` pulls in the `1.14.1` tarball and tries to build it from source. Some of this is discussed elsewhere like here:

https://github.com/scikit-learn/scikit-learn/issues/28978#issuecomment-2127587244

where `__pyx_vectorcallfunc` problem is described as fixed in newer Cython. I also seem to have some weird PATH behavior issues with `venv` in Python `3.13.0`.. and those also seem to be mentioned in above thread, that's annoying!

**Comment by olegmikul** [comment] 2024-10-09 04:54
> I suppose the obvious observation is that we do provide regular Python 3.13 wheels for our latest stable release (`1.14.1`) on PyPI but _not_ free-threaded Python 3.13 wheels, so that's likely why you're hitting the source build in the free-threaded case.
> 
> IIRC we weren't quite ready to fully support free-threaded Python in SciPy just yet. sklearn seems to be waiting for us at [scikit-learn/scikit-learn#28978 (comment)](https://github.com/scikit-learn/scikit-learn/issues/28978#issuecomment-2393173700).
> 
> Let me poke a bit locally..

Yes, now it is clear. Free-threaded version is very new and provides some slowdowns now. So we can wait for more optimizations.

**Comment by rgommers** [comment] 2024-12-18 15:32
SciPy 1.15.0rc1 is up on PyPI and it does have `cp313t` (free-threaded) wheels for macOS, Linux and Windows. So I'll close this issue.

You can install the wheels with `pip install scipy --pre` right now, and the `--pre` flag won't be needed anymore once 1.15.0 is final in January.

Thanks all!

**Closed by rgommers** 2024-12-18 15:32 UTC
Labels: defect, Build issues, Official binaries, free-threading
