### ISSUE TITLE
 Just a question

### ISSUE THREAD

**Issue by andportnoy** [scipy/scipy#7464] opened 2017-06-06 02:44 UTC
Why is it that the top 4 contributors have deleted more lines than they have added? How can this be explained?

**Comment by josef-pkt** [comment] 2017-06-06 03:24
That's not really an issue/bug/...

It's mostly house cleaning: several subpackages have been removed, cython generated c code has been removed in favor of creating during build.

I have no idea why Travis has a negative addition balance (before my time). For pre-github changes the additions might also not be correctly recorded or assigned to a committer/author.

**Comment by josef-pkt** [comment] 2017-06-06 03:32
interesting related topic
scipy went from being a C/C++ package to being a Python package
https://www.openhub.net/p/scipy/analyses/latest/languages_summary

**Comment by pv** [comment] 2017-06-06 07:48
Or, there's something wrong with how Github counts changed lines. That's 
not a mission critical component for them, so it would not be surprising 
if it somewhat broken.

**Comment by rgommers** [comment] 2017-06-06 08:06
nice to know indeed but not a bug, so closing:)

**Closed by rgommers** 2017-06-06 08:06 UTC
Labels: invalid
