### ISSUE TITLE
Speedup linprog when condition has a unique solution

### ISSUE THREAD

**Issue by jcstudio-jeff-chen** [scipy/scipy#14834] opened 2021-10-10 02:58 UTC
My program need to solve thousands of LP problem. It used to run 34-35 seconds, but then I realized the constraint A_eq x = b will have unique solution 99% of the time. (The shape of A_eq and b were dynamically determined by the situation)

So I added an if statement:

If A_eq.shape[0] == A_eq.shape[1]:
    x = solve(A_eq, b)
else:
    #do the original linprog

And now it finished in 2 seconds. I wonder could this be included in the function linprog by default?

**Comment by mckib2** [comment] 2021-10-10 03:31
Hi @jcstudio-jeff-chen , which linprog method are you using?  If you're not already using it, I'd be curious to know if `method="highs"` runs any faster for you

**Comment by jcstudio-jeff-chen** [comment] 2021-10-10 04:44
@mckib2 It runs 3 times faster, took 11.0-11.1 seconds, but still much slower than my modification.

**Comment by mckib2** [comment] 2021-10-16 01:56
`method="highs"` uses the dual simplex solver, you can also try `method="highs-ipm"` for an interior point solver.

Another experiment: try `linprog(..., method="highs", options={"presolve": False})` to see if removing presolve steps could speed up your problem.  

I'm uncomfortable with the idea that you can always use the least squares solution -- I'm sure if this were true the very smart developers who write high performance solvers like HiGHS would be doing this.  There are the bounds to consider for one and then you'd have to find some way to solve for the duals/shadow prices for any inequality constraints.  There's more information in the solution than just the point that is minimized.  I'm also not sure there would be a straightforward way to get statuses like primal/dual unboundedness and infeasibility.

If @mdhaber has anything else to add, I'll let him, but I think we can close this issue as while it seems to be a fantastic optimization for your use case, determining and checking for very special-cases of linear programs doesn't serve the purpose of the general-purpose linear program solvers bundled with scipy.

**Closed by mckib2** 2021-10-16 01:56 UTC
Labels: enhancement, scipy.optimize

**Comment by mdhaber** [comment] 2021-10-16 12:25
I agree, @mckib2. The suggested code above would also need to `try` solve `Aeq@x=beq`, which can fail. If the solver does not fail and if the solution satisfies the constraints, return it; otherwise run the LP solver. So if the problem is a legitimate optimization problem (i.e. `Aeq` has redundant rows), it will always take longer because it has to `try` and fail the regular solve+check first. Since the main focus is linear programming, i think it's ok to expect users to check whether their problem can be solved with a simpler algorithm.

The idea is fine, I'm just not sure that we have enough user data to be confident that this would be an overall speedup that is worth the time it takes to write and review a PR.

Thanks @jcstudio-jeff-chen, but does that make sense? I think it's great to do this in your own code, but I'm not sure adding this would be a win for everyone.

**Comment by jcstudio-jeff-chen** [comment] 2021-11-29 13:56
Sure, I originally think it will cost near zero time since it is only checking the shape is square or not. If it will add even 0.1% of the time in normal use cases, then don't do it.

**Comment by mdhaber** [comment] 2021-12-06 20:40
@jcstudio-jeff-chen Ok. Perhaps suggest this to the authors of HiGHS to see if they want to include it upstream. If they think it is a good optimization to have but don't want to include it in HiGHS, we may consider a PR here.
