### ISSUE TITLE
scipy.fftpack.fftn unexpected handling of axes

### ISSUE THREAD

**Issue by sjpet** [scipy/scipy#5403] opened 2015-10-22 12:27 UTC
## Tested on scipy verison 0.16.0

with

```
x = np.random.randn(4, 3, 4096)
```

the calls

```
scipy.fftpack.fftn(x, axes=(0, 2)).shape
scipy.fftpack.fftn(x, axes=(-3, -1)).shape
scipy.fftpack.fftn(x, axes=(-1, -3)).shape
scipy.fftpack.fftn(x, axes=(2, 0)).shape
```

all return (4, 3, 4096), but

```
scipy.fftpack.fftn(x, axes=(0, -1)).shape
```

returns (4096, 3, 4096).

**Comment by rgommers** [comment] 2015-10-24 13:58
I can reproduce this. Weird. Looks like something needs fixing.

**Comment by sjpet** [comment] 2015-10-28 07:40
Since the implementation is written in fortran unless I'm mistaken, I'm afraid I won't be of much help fixing it. Based on the observed behaviour however, I would venture a guess that it's related to some sorting behaviour.

**Comment by ewmoore** [comment] 2015-10-28 13:37
The problem is [here](https://github.com/scipy/scipy/blob/master/scipy/fftpack/basic.py#L516-L518)
```
    id = numpy.argsort(axes)
    axes = [axes[i] for i in id]
    s = [s[i] for i in id]
```
For this to work right axes have to all positive.  Adding 
```
    a = numpy.array(axes, numpy.intc)
    axes = numpy.where(a < 0, a+x.ndim, a)
```
before the line starting `id =` fixes this for me.  Probably worth doing this (or the equivalent) much earlier as well as providing a nicer error message when an out of bounds axes is provided.

(Feel free to take this, my time is very limited ATM.)

**Comment by Eric89GXL** [comment] 2017-04-10 14:40
Fixed by @sjpet

**Closed by Eric89GXL** 2017-04-10 14:40 UTC
Labels: defect, scipy.fftpack
