### ISSUE TITLE
BUG: Unexpected results for Kummer's hypergeometric function

### ISSUE THREAD

**Issue by Fantomet271828** [scipy/scipy#17598] opened 2022-12-14 14:07 UTC
### Describe your issue.

There is a serious bug in the implementation of  Kummer's hypergeometric function. If the first two parameters a, b are real, we have that hyp1f1(a, b, z) should be the conjugate of  hyp1f1(a, b,  np.conj(z)). This is not always the case. Examples are provided below.

Mathematica is one of the industry standards for doing scientific computations. For many arguments hyp1f1(a, b, z) does not agree with Mathematica's output given the same input. Examples are provided below.

If one does not have Mathematica installed, one can go to https://www.wolframalpha.com/. There one can generate the output for one of the examples below by entering 
`z =  (5+10*Pi*I); N[Hypergeometric1F1[1/3,1+1/3,z], 10]`
in the input cell.

```python
"""

EXAMPLE NUMBER 1:



Code Mathematica:

s =  (-4.559190954155+51.659216953928I);
sconj=Conjugate[s];
Hypergeometric1F1[1/2,3/2,-s]
Hypergeometric1F1[1/2,3/2,-sconj]


Output Mathematica:
Out[12]= 1.\[VeryThinSpace]+1.99922*^-11 \[ImaginaryI]

Out[13]= 1.\[VeryThinSpace]-1.99922*^-11 \[ImaginaryI]

For the given value of s we see that Mathematica computes that the function 
value equals 1 for all practical purposes.
"""

# Code Python:
import scipy.special as sc
import numpy as np
 
# Parameters, arguments etc:
p=2 
s = -4.559190954155 + 51.659216953928*1j

# Evaluation:
result = sc.hyp1f1(1/p, 1/p + 1, -s) 
tol = 1e-6
msg = f'The above  output of {result} from scipy is far from 1, i.e. in large disagreement with Mathematica'
assert abs(result - 1)<tol, msg

# print(f'sc.hyp1f1(1/p, 1/p + 1, -s) = {result}')


"""

EXAMPLE NUMBER 2:

Because the parameters 1/p and 1/p+1 are real, we know that if we replace 
s by its conjugate, the output should be the conjugate of the first output. 
This turns out not to be the case:
"""

# z complex:
z = 5+10*np.pi*1j
result1 = sc.hyp1f1(1/3, 1+1/3, z)
result2 = sc.hyp1f1(1/3, 1+1/3, np.conj(z))
print(f'sc.hyp1f1(1/3, 1+1/3, z) = {result1}')
print(f'sc.hyp1f1(1/3, 1+1/3, np.conj(z)) = {result2}')
tol = 1e-6
msg = f'np.conj(result2) does not equal result1 as it should'
assert abs(result1-np.conj(result2))<tol , msg


"""
Code Mathematica:

z =  (5+10*Pi*I);
zconj=Conjugate[z];
N[Hypergeometric1F1[1/3,1+1/3,z], 10]
N[Hypergeometric1F1[1/3,1+1/3,zconj], 10]

Output Mathematica:
Out[15]= 0.449118650-1.390784314 \[ImaginaryI]

Out[16]= 0.449118650+1.390784314 \[ImaginaryI]
"""

tol = 1e-6
result1_mathematica = 0.449118650-1.390784314j
result2_mathematica = 0.449118650+-1.390784314j

assert abs(result1-result1_mathematica)<tol, 'result1 not eqal result1_mathematica'
assert abs(result2-result2_mathematica)<tol, 'result2 not eqal result2_mathematica'
```

### Reproducing Code Example

```python
"""
EXAMPLE NUMBER 1:

Code Mathematica:

s =  (-4.559190954155+51.659216953928I);
sconj=Conjugate[s];
Hypergeometric1F1[1/2,3/2,-s]
Hypergeometric1F1[1/2,3/2,-sconj]

Output Mathematica:
Out[12]= 1.\[VeryThinSpace]+1.99922*^-11 \[ImaginaryI]

Out[13]= 1.\[VeryThinSpace]-1.99922*^-11 \[ImaginaryI]

For the given value of s we see that Mathematica computes that the function 
value equals 1 for all practical purposes.
"""

# Code Python:
import scipy.special as sc
import numpy as np
 
# Parameters, arguments etc:
p=2 
s = -4.559190954155 + 51.659216953928*1j

# Evaluation:
result = sc.hyp1f1(1/p, 1/p + 1, -s) 
tol = 1e-6
msg = f'The above  output of {result} from scipy is far from 1, i.e. in large disagreement with Mathematica'
assert abs(result - 1)<tol, msg

# print(f'sc.hyp1f1(1/p, 1/p + 1, -s) = {result}')


"""
EXAMPLE NUMBER 2:

Because the parameters 1/p and 1/p+1 are real, we know that if we replace 
s by its conjugate, the output should be the conjugate of the first output. 
This turns out not to be the case:
"""

# z complex:
z = 5+10*np.pi*1j
result1 = sc.hyp1f1(1/3, 1+1/3, z)
result2 = sc.hyp1f1(1/3, 1+1/3, np.conj(z))
print(f'sc.hyp1f1(1/3, 1+1/3, z) = {result1}')
print(f'sc.hyp1f1(1/3, 1+1/3, np.conj(z)) = {result2}')
tol = 1e-6
msg = f'np.conj(result2) does not equal result1 as it should'
assert abs(result1-np.conj(result2))<tol , msg


"""
Code Mathematica:

z =  (5+10*Pi*I);
zconj=Conjugate[z];
N[Hypergeometric1F1[1/3,1+1/3,z], 10]
N[Hypergeometric1F1[1/3,1+1/3,zconj], 10]

Output Mathematica:
Out[15]= 0.449118650-1.390784314 \[ImaginaryI]

Out[16]= 0.449118650+1.390784314 \[ImaginaryI]
"""

tol = 1e-6
result1_mathematica = 0.449118650-1.390784314j
result2_mathematica = 0.449118650+-1.390784314j

assert abs(result1-result1_mathematica)<tol, 'result1 not eqal result1_mathematica'
assert abs(result2-result2_mathematica)<tol, 'result2 not eqal result2_mathematica'
```

### Error message

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-47-f81c740ef128> in <module>
     40 tol = 1e-6
     41 msg = f'The above  output of {result} from scipy is far from 1, i.e. in large disagreement with Mathematica'
---> 42 assert abs(result - 1)<tol, msg
     43 
     44 # print(f'sc.hyp1f1(1/p, 1/p + 1, -s) = {result}')

AssertionError: The above  output of (0.833788272795157+0.18152681828629416j) from scipy is far from 1, i.e. in large disagreement with Mathematica
```

### SciPy/NumPy/Python version information

import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

**Comment by WarrenWeckesser** [comment] 2022-12-14 16:41
Thanks for reporting the problem (again!).  This looks like a duplicate of your previous report in https://github.com/scipy/scipy/issues/13129, so I'm closing this one.

**Closed by WarrenWeckesser** 2022-12-14 16:41 UTC
Labels: defect, scipy.special

**Comment by Fantomet271828** [comment] 2022-12-14 20:08
Last time the bug was reported the reply was that it was reported the wrong place and it should be reported here.
Since the bug did not get fixed I assumed that it might help reporting it here.
 
As far as I understand from the last reply there seems to be no plans to fix the bug although the implementation of .hyp1f1 in scipy.special is seriously wrong. People who make calculations based on the functions offered in scipy.special risk making quite mistaken conclusions if the output of the function is not to be trusted.

**Comment by Fantomet271828** [comment] 2022-12-14 20:17
In the bug report here one finds more information on how one can actually perform tests on that the output is to be trusted. For instance using available output from wolfram alpha that is readily available for free.

I am a bit curious on what kind of tests are done on functions that are available in scipy. For a of complex analytic function F (as e.g. hyp1f1) which is real on the real line, a very basic fact is that F(conj(z)) = conj(F(z)). If this test is not performed, doesn't that mean that one most question many parts of the library?

**Comment by steppi** [comment] 2022-12-15 04:16
Hi @Fantomet271828. For hypergeometric functions of a complex variable, SciPy uses Fortran implementations from the book Computation of Special Functions by S. Zhang and J.M Jin. Unfortunately, these implementations are quite bug ridden.  @person142 and myself hope to fix this situation by rewriting them piece by piece in Cython. We've made some good strides for the Gaussian hypergeometric function [hyp2f1](https://github.com/scipy/scipy/blob/main/scipy/special/_hyp2f1.pxd) and were able to close out the longstanding open issues gh-8054 and gh-7340. Progress has stalled for much of this year due to lack of time on my part. 

For testing the reliability of output, one does not need to use proprietary software. The Python package [mpmath]() has arbitrary precision implementations of [hypergeometric functions](https://mpmath.org/doc/current/functions/hypergeometric.html). I hope you will find the [set of tests](https://github.com/scipy/scipy/blob/main/scipy/special/_precompute/hyp2f1_data.py) for `hyp2f1` sufficiently thorough.

I now have a couple hours per week to devote to SciPy, so will be getting back to this project. After completing work on `hyp2f1`, I'll start taking a closer look at `hyp1f1`.  It's going to be a while before all of the problems with the hypergeometric functions are cleaned up, but we're aware of these problems and are planning to fix them.
