### ISSUE TITLE
interpn returns nan with perfectly valid data

### ISSUE THREAD

**Issue by ideasrule** [scipy/scipy#9524] opened 2018-11-23 02:20 UTC
interpn returns nan when one of the dimensions of the grid has length 1, even if the inputs are perfectly valid.  I know this is an edge case, but it's crucial to my program, and working around it requires ugly hacks.

### Reproducing code example:

```
values = np.array([0.1,1,10]).reshape((1,3))
xi = np.array([[1, 2.2], [1, 3.2], [1, 3.8]])
print(scipy.interpolate.interpn(([1], [2,3,4]), values, xi))
```

### Error message:

No error message, but returns array([nan, nan, nan])

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.1 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment] 2018-12-21 22:56
Duplicate of gh-7560, gh-5890?

**Closed** 2022-05-01 23:02 UTC
Labels: scipy.interpolate
