### ISSUE TITLE
TypeError: data type "<i0" not understood

### ISSUE THREAD

**Issue by sadaf2605** [scipy/scipy#4755] opened 2015-04-19 08:31 UTC
I got this following error while `wavfile.read("a.wav")`:

/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py:42: WavFileWarning: Unknown wave file format
  warnings.warn("Unknown wave file format", WavFileWarning)
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    fs, data = wavfile.read('../test/blueberry.wav') # load the data
  File "/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 166, in read
    data = _read_data_chunk(fid, comp, noc, bits, mmap=mmap)
  File "/usr/lib/python2.7/dist-packages/scipy/io/wavfile.py", line 71, in _read_data_chunk
    data = numpy.fromstring(fid.read(size), dtype=dtype)
TypeError: data type "<i0" not understood

**Comment by rgommers** [comment] 2015-04-19 09:44
@sadaf2605 thanks for the report. Can you provide the .wav file needed to reproduce this issue?

**Comment by sadaf2605** [comment] 2015-04-19 15:06
I tried with this one: http://www.moviesoundclips.net/download.php?id=1238&ft=wav

**Comment by rgommers** [comment] 2015-05-03 14:32
Thanks @sadaf2605. I can reproduce this, but it's not immediately clear why the format parsing results in ``bits=0``.

Header looks like:

    'RIFF>\xef\x01\x00WAVEfmt \x1e\x00\x00\x00U\x00\x01\x00\x80\xbb\x00
    \x00@\x1f\x00\x00\x01\x00\x00\x00\x0c\x00\x01\x00'

**Comment by endolith** [comment] 2020-05-14 05:55
This errors out now because the format type is 0x0055 = 85 = MP3 format, which is not supported.  There is a list of formats at https://github.com/voidqk/basicwav

**Comment by larsoner** [comment] 2020-05-20 18:50
Fixed by #12110

**Closed by larsoner** 2020-05-20 18:50 UTC
Labels: defect, scipy.io
