### ISSUE TITLE
Bug in scipy.stats.ks_2samp for two-sided auto and exact modes on a few thousand samples (when n1!=n2) 

### ISSUE THREAD

**Issue by sigallev** [scipy/scipy#12999] opened 2020-10-26 06:43 UTC
When you run have a few thousand samples for each group, and different a number of samples than auto goes to exact.
One sided - gets an exception and shifts to 'asymp'
Two sided - doesn't get an exception but may well finish with prob = 0 or 1, which is not the real probability.
                   the "finally" statement whould change to 'asymp' mode, if it was prob < 0 or >1, but not at 0 and 1.
                   I think this should change to prob <=0 or >=1.

This causes the code snippet below to work well for 1000, 1010 samples worse for 2000,2010 and fail completely for 3000,3010 and above, until 10,000 when the 'asymp' mode kicks in no matter what. 

#### Reproducing code example:

print("look at the p_values going to 1, for 3000 and above when in 'auto' mode. This is clearly not the right probability.")
for x in range(1000, 12000,1000):
    print("For %d vs %d auto" % (x, x))
    print(scipy.stats.ks_2samp([random.normalvariate(100,10) for i in range(x)], [random.normalvariate(95,10) for i in range(x)]))
    print("For %d vs %d asymptotic (not exact)" % (x, x))
    print(scipy.stats.ks_2samp([random.normalvariate(100, 10) for i in range(x)],
                               [random.normalvariate(95, 10) for i in range(x)], mode='asymp'))
    print()

#### Scipy/Numpy/Python version information:

1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by chrisb83** [comment] 2020-11-02 20:19
There were some bugs of `ks_2samp` in SciPy 1.4, e.g. #11184, that were fixed in 1.5. Could you check if the problem still exists if you upgrade SciPy?

**Comment by sigallev** [comment] 2020-11-03 09:52
The results actually changed, *and are now even weirder*.

My code is very simple:
import random
import scipy
import scipy.stats

print(scipy.__version__)
for x in range(1000, 12000, 1000):
    vals1 = [random.normalvariate(100, 10) for i in range(x)]
    vals2 = [random.normalvariate(95, 10) for i in range(x+10)]
    print("\n%d" % x)
    print(scipy.stats.ks_2samp(vals1, vals2))
    print(scipy.stats.ks_2samp(vals1, vals2, mode='asymp'))
    # these two p-values should be in line with each other
print()

And look how it behaves. There are some major discrepancies between the two
values, but only for some of the xs (for some number of samples, not for
others):
1.5.3

1000
KstestResult(statistic=0.20679207920792078, pvalue=2.6391393024758554e-19)
KstestResult(statistic=0.2067920792079208, pvalue=2.639139302475824e-19)

2000
KstestResult(statistic=0.17853980099502487, pvalue=2.0522704781112646e-28)
KstestResult(statistic=0.17853980099502487, pvalue=2.0522704781112646e-28)

3000
KstestResult(statistic=0.22652380952380952, pvalue=3.2773195020948264e-68)
KstestResult(statistic=0.22652380952380957, pvalue=3.277319502094573e-68)

4000
KstestResult(statistic=0.22134351620947632, pvalue=2.220446049250313e-15)
KstestResult(statistic=0.2213435162094763, pvalue=1.254472004892521e-86)

5000
KstestResult(statistic=0.20126586826347306, pvalue=2.5567455151927657e-89)
KstestResult(statistic=0.20126586826347304, pvalue=2.5567455151929115e-89)

6000
KstestResult(statistic=0.2133230726566833, pvalue=4.107825191113079e-15)
KstestResult(statistic=0.21332307265668327, pvalue=2.2822895371211086e-120)

7000
KstestResult(statistic=0.18743896474424293, pvalue=3.4202940876631045e-108)
KstestResult(statistic=0.18743896474424288, pvalue=3.420294087663611e-108)

8000
KstestResult(statistic=0.19601404494382021, pvalue=2.5827118221855017e-12)
KstestResult(statistic=0.1960140449438202, pvalue=3.389282533241279e-135)

9000
KstestResult(statistic=0.2069876680231841, pvalue=0.006901878771671144)
KstestResult(statistic=0.20698766802318413, pvalue=1.2018998948969596e-169)

10000
KstestResult(statistic=0.20650299700299696, pvalue=1.5122150846105846e-187)
KstestResult(statistic=0.20650299700299696, pvalue=1.5122150846105846e-187)

11000
KstestResult(statistic=0.20663826273635538, pvalue=1.6137073644802917e-206)
KstestResult(statistic=0.20663826273635538, pvalue=1.6137073644802917e-206)


*Sigal Peled-Leviatan*

**Comment by chrisb83** [comment] 2020-11-03 19:37
For the last two cases, it is expected that you get the same result since `auto` switches to `asymp` if one of the samples is larger than 10000. 

In the other cases, I am not sure how accurate the values are but for practical purposes, it looks like the pvalue is essentially zero as expected, i.e. the test detects that the samples have a different mean.

If `mode == 'exact'`, the p-value looks indeed a bit large, so potentially the switch to `asymp` should happen earlier? See comment in #11184:

> In general, the exact two-sided computation is best suited to situations in which one of the sample sizes is at most a few thousand, or the statistic d is "small", as the computation is O(N1 N2 d).

in your case, d is very large and so are N1 and N2.

@pvanmulbregt any view on this?

**Comment by sigallev** [comment] 2020-11-03 20:14
I know that atx10,000 it changes to asymp, but what's interesting is before
that.
Sometimes it computes arround 10**-15 and decides its good, and other times
arround -10**-15, realises this is less than 0 so does not make sense and
moves to asymp.

This suggests to me that any pvalue in this range is not trust worthy, and
should be replaced by the asymp calculation.

You can also see the problem by noting that 4000 points from the
distribution should be more significant than 1000 or 200, and is not. You
must agree this is a problem....

Sigal Peled-Leviatan

בתאריך יום ג׳, 3 בנוב׳ 2020, 21:37, מאת Christoph Baumgarten ‏<
notifications@github.com>:

**Comment by chrisb83** [comment] 2020-11-04 18:47
Indeed, that is linked to my statement above that the switch to `asymp` might need to happen earlier.

Note that `exact` does not mean the value is precise up to a certain number of digits. it just means the exact distribution of the test statistic is used. For any practical purpose, the numbers above should be small enough to reject the assumption that the distribution of the two samples is the same :)

**Comment by sigallev** [comment] 2020-11-04 19:04
Not necessarily, when you are dealing with multiple hypothesis testing
(GWAS, for example).
And I agree that moving to asymp earlier would have solved this, but this
needs some research with a bigger set of distributions to decide when to
move.
In general if a random partial set of samples gives a lower pvalue then
something is very wrong with an estimation.

Good luck with the code, we rely on your keeping up the great work.

Sigal Peled-Leviatan

בתאריך יום ד׳, 4 בנוב׳ 2020, 20:47, מאת Christoph Baumgarten ‏<
notifications@github.com>:

**Comment by pvanmulbregt** [comment] 2020-11-29 18:16
The computation in stats._compute_prob_inside_method() returns the complementary probability, and this number may be very close to 1 if the samples do not not come for the same distribution. For large-sized mismatched samples, the accuracy of the computed probability p may not be sufficient for use when needing 1-p.  Certainly it won't be if the actual, probability is less than 1e-16, as in the examples above.
gh-13168 looks for insufficient accuracy and backs off to the asymptotic calculation in that situation.

**Comment by t-vi** [comment] 2021-02-17 07:16
Cross posting from the PR: I wrote up a more stable recursion for the inner method / 2-sided 2-sample in https://arxiv.org/abs/2102.08037

The basic trick that you can do instead of doing 1-A(m,n)/Binom(m+n,n) at the end, you can do the entire recursion on values of this form 1-A(i,j)/Binom(i+j,j). It seems to be about 4x slower than the current implementation, which I think it is due to the extra compute, but then both the current implementation and the stable recursion can be moved to numba / other ways to compile to speed them up. I can also make a PR of it if it helps.

**Comment by srcoulombe** [comment] 2021-03-21 05:05
Commenting to bump this issue, 

Here's another example of when things go wrong:
```
import numpy as np
print(np.__version__)
import scipy
print(scipy.__version__)
from scipy.stats import ks_2samp

np.random.seed(1)
x = np.random.normal(10, 1, 5_000_000)
y = np.random.normal(12, 1, 5_000)
print(ks_2samp(x, y, mode='auto', alternative = 'two-sided'))
print(ks_2samp(x, y, mode='exact', alternative = 'two-sided'))

```
Gives:
```
1.18.5
1.5.2
KstestResult(statistic=0.6859724, pvalue=0.0)
KstestResult(statistic=0.6859724, pvalue=1.0)

```

**Comment by ErikPoppleton** [comment] 2021-04-23 21:59
Commenting to further bump.  I was using ks_2samp to determine whether or not a set of experimental measurements were different.  For reference, here is a histogram of the first two measurement sets which have sizes 5971 and 6000, respectively:

![image](https://user-images.githubusercontent.com/36451772/115933279-689fcf80-a443-11eb-9afc-c445c33b577f.png)

Running `kstest(sample1, sample2)` returns the following:
```KstestResult(statistic=0.8563704013844694, pvalue=1.0)```

If I switch `alternative='greater'`, I get 
```KstestResult(statistic=0.8563704013844694, pvalue=0.0)```
which does not surprise me since these are very large and very different distributions

Switching to `mode='asymp'` makes the `pvalue=0.0`.

I also ran @srcoulombe 's code above and got the same result with a newer version of scipy
```python
import numpy as np
print(np.__version__)
import scipy
print(scipy.__version__)
from scipy.stats import ks_2samp

np.random.seed(1)
x = np.random.normal(10, 1, 5_000_000)
y = np.random.normal(12, 1, 5_000)
print(ks_2samp(x, y, mode='auto', alternative = 'two-sided'))
print(ks_2samp(x, y, mode='exact', alternative = 'two-sided'))
```
```
1.19.2
1.6.2
KstestResult(statistic=0.6859724, pvalue=0.0)
KstestResult(statistic=0.6859724, pvalue=1.0)
```

**Comment by mdhaber** [comment] 2021-04-23 23:43
Yup, still in master:
```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import ks_2samp

ps = []
sizes = np.arange(4000, 5000, 10)
for size in sizes:
    np.random.seed(1)
    x = np.random.normal(10, 1, size)
    y = np.random.normal(12, 1, size + 1)
    ps.append(ks_2samp(x, y, mode='exact', alternative = 'two-sided').pvalue)

plt.plot(sizes, ps)
plt.xlabel('Size of Smaller Sample')
plt.ylabel('p-value')
plt.title('behavior of ks_2samp')
```
![image](https://user-images.githubusercontent.com/6570539/115939399-e6b7a280-a452-11eb-9dba-1e90dab16c63.png)

**Comment by mdhaber** [comment] 2021-04-24 00:06
@t-vi I just took a look at your paper. Looks useful to me - would you be interested in submitting a PR?

**Comment by mdhaber** [comment] 2021-04-24 03:35
@t-vi Any chance that in your paper the roles of `m` and `n` should be reversed in 
![image](https://user-images.githubusercontent.com/6570539/115942375-d7d6ed00-a45e-11eb-8a86-eb1932b96137.png)
?
I wrote up the recursion for A_ij and confirmed that I could use it to get p-values returned by ks_2samp. I then adapted it to C_ij. The two were only related by

![image](https://user-images.githubusercontent.com/6570539/115942432-24222d00-a45f-11eb-8659-31f3800537bc.png)

after I swapped those terms.

**Comment by t-vi** [comment] 2021-04-24 14:02
I'll send a PR. The n and m should match so that the fractions run between 0 and 1, thank you for pointing that out.

**Comment by mdhaber** [comment] 2021-04-24 14:19
Thank you! BTW, if possible, could you start by patching the existing function rather than a rewrite? We can explore a compiled (e.g. Cython) implementation later, but initially if we could keep the structure of the function but normalize differently, it would be a much faster review process.

**Comment by t-vi** [comment] 2021-04-24 14:51
To use the other computation, I would want to change
https://github.com/scipy/scipy/blob/6b076041d64b55322e8a8a3825d656a74f8241e8/scipy/stats/stats.py#L7066
and replace `1 - _compute_prob_inside_method` with `_compute_outer_prob_inside_method` (and lat the latter function replace the former) if that is OK.

**Comment by mdhaber** [comment] 2021-04-24 21:33
Yes, that's fine. But is it possible to keep most of the structure of `_compute_prob_inside_method` in the new `_compute_outer_prob_inside_method`? For instance, if I'm reading correctly, it seems that for every element of `A` calculated in in `_compute_prob_inside_method`, your `_compute_outer_prob_inside_method` would calculate an element of a matrix `C`, and these elements can be calculated in the same order. The structure of the `for` loop that calculates one column at a time could remain intact, and the vectorized parts (e.g. use of `cumsum`) would have the same indices. The thing that would change is the scaling - I think the existing scaling using `np.ldexp` and `np.frexp` could be removed and replaced with your scaling. Is that right?  The hope is that if we only need to change and review how the scaling is done, this fix could be merged faster. 

If it's too difficult to work within the existing function, I understand. It's just that if we were going to do a rewrite, I wouldn't trouble you with it! I already wrote a few versions of your method yesterday, starting with straightforward recursion, turning that recursion into a while loop to avoid exceeding the maximum recursion depth, and then getting a 50x speedup by converting to Cython. But after all that, I think it would be best if initially we keep the structure of the existing function rather than a rewrite, and since you've thought about this enough to write a paper, I thought you could work with the existing structure better than I could! Thanks for considering it!

**Comment by Celebio** [comment] 2021-04-29 22:07
I believe there is a bug on the `alternative` argument when it is not `two-sided`.

> If I switch `alternative='greater'`, I get
> `KstestResult(statistic=0.8563704013844694, pvalue=0.0)`
> which does not surprise me since these are very large and very different distributions
> 
It is wrong too, your `sample1` is less than `sample2`, it should return pvalue=1.0. It should return p=0.0 for alternative='less'.

In fact, it behaves the opposite way of `mannwhitneyu`, `ttest_ind` or `brunnermunzel`.

**Comment by mdhaber** [comment] 2021-04-29 22:16
@Celebio please see if gh-13188 resolved that issue. For the KS test, "less" and "greater" refer to the CDF, not the "location" of the distribution. The meaning may be opposite of intuition, but it is not necessarily wrong if it is documented clearly.

**Comment by srcoulombe** [comment] 2021-07-18 03:05
@t-vi Any updates on your PR? I saw you also referenced your work in https://github.com/scipy/scipy/pull/13168. I'm down to help in any way I can.

**Comment by t-vi** [comment] 2021-07-18 21:42
@srcoulombe Thank you for reminding me. So I submitted a patch with @mdhaber's suggestion to stick to the existing structure as much as possible, but it is just terribly slow.

**Closed** 2021-09-21 17:26 UTC
Labels: defect, scipy.stats
