### ISSUE TITLE
Inverse Wishart Log PDF Incorrect for Non-diagonal Scale Matrix?

### ISSUE THREAD

**Issue by michaelwooley** [scipy/scipy#8844] opened 2018-05-18 15:59 UTC
I believe that there might be a bug in the implementation of the log PDF for the Inverse Wishart distribution for certain cases. When I attempt to match my own version of the Log PDF I found that - if the scale matrix has non-zero, off-diagonal entries - then the results do not match. If the scale matrix is diagonal, however, I can get a match.

### Reproducing code example:
```python
import numpy as np
from scipy import stats
import scipy.special as scipy_sp

# NumPy Version of Inverse Wishart Log PDF
np_iw_logpdf = (lambda X, df, PSI: (df/2) * np.log(np.linalg.det(PSI)) - 
      (df*X.shape[0] / 2) * np.log(2.) - 
      scipy_sp.multigammaln(df/2., X.shape[0]) - 
      ((df + X.shape[0] + 1) / 2.) * np.log(np.linalg.det(X)) - 
      0.5 * np.trace(PSI.dot(np.linalg.inv(X))))

# Common parameters
p = np.random.choice(range(2, 15)) # Number of dimensions
nu = np.random.choice(range(p + 2, 150)) # dof > p+1

# DISAGREE: Non-Diagonal Scale Matrix
psi0 = np.random.uniform(-10, 10, size=(p, p))
psi0 = psi0.T.dot(psi0) # NON-DIAGONAL, PSD Scale Matrix

# AGREE: Diagonal Scale Matrix
psi1 = np.diag(np.random.uniform(-10, 10, size=(p,)))
psi1 = psi1.T.dot(psi1) # NON-DIAGONAL, PSD Scale Matrix

rv = stats.invwishart.rvs(df=nu, scale=psi0) # Sample from distribution

print('DISAGREE: Non-Diagonal Scale Matrix')
print('       SciPy: ', stats.invwishart.logpdf(rv,  df=nu, scale=psi0))
print('np_iw_logpdf: ', np_iw_logpdf(rv, nu, psi0))

print('\nAGREE: Diagonal Scale Matrix')
print('       SciPy: ', stats.invwishart.logpdf(rv,  df=nu, scale=psi1))
print('np_iw_logpdf: ', np_iw_logpdf(rv, nu, psi1))
```

Looking through the [scipy source code](https://github.com/scipy/scipy/blob/v0.19.0/scipy/stats/_multivariate.py), it appears that any differences are coming from the computations of the determinants or the trace(Psi.dot(X^{-1})).

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment] 2018-05-19 05:50
@michaelwooley Thanks for reporting this issue.  I can confirm that there is a bug in the `logpdf` method of the `invwishart` distribution.  I just submitted a pull request with a fix: https://github.com/scipy/scipy/pull/8846

**Comment by michaelwooley** [comment] 2018-05-22 14:27
Great, thanks for the quick follow up! What is the etiquette for closing this? Should I keep it open until I have the time to run tests or close the issue and go to the pull request or what?

**Comment by ilayn** [comment] 2018-05-22 14:32
Once that PR is merged this is going to be closed automatically

**Comment by WarrenWeckesser** [comment] 2018-05-22 16:05
As @ilayn said, you don't have to do anything else.  Because I put the line "Closes gh-8844." in one of my commit messages, github will close this issue automatically when that commit is merged in the master branch.

You are welcome to review and comment on the pull request if you like, but that is not required.

**Closed** 2018-06-10 03:58 UTC
Labels: defect, scipy.stats
