### ISSUE TITLE
SciPy unnecessarily warns user when new point.point version of NumPy is installed

### ISSUE THREAD

**Issue by mossbeachlarry** [scipy/scipy#18611] opened 2023-06-01 19:32 UTC
### Describe your issue.

Intel oneAPI Python 3.9 bundles SciPy and Numpy:

> `$ conda list`
> `# packages in environment at /opt/intel/oneapi/intelpython/latest:`
> `#`
> `# Name                    Version                   Build  Channel`
> `<snip>`
> `numpy                     1.23.5           py39h52df89b_7    file:///opt/intel/oneapi/conda_channel`
> `<snip>`
> `scipy                     1.7.3            py39h4ca98da_8    file:///opt/intel/oneapi/conda_channel`
> `<snip>`

SciPy is unnecessarily picky about the point version (actually, the point.point version) of NumPy installed and issues a warning message to the user when SciPy is imported.  This causes unnecessary concern for the user, and unnecessary help requests to support staff.

This is more a request to make SciPy smarter about its dependency checks, not really an installation or computation bug.

### Reproducing Code Example

```python
$ python3
Python 3.9.16 (main, Feb 22 2023, 01:57:33) 
[GCC 11.2.0] :: Intel Corporation on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import scipy
/opt/intel/oneapi/intelpython/python3.9/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
>>> quit()
```

### Error message

```shell
/opt/intel/oneapi/intelpython/python3.9/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
```

### SciPy/NumPy/Python version and system information

```shell
$ python3
Python 3.9.16 (main, Feb 22 2023, 01:57:33) 
[GCC 11.2.0] :: Intel Corporation on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
/opt/intel/oneapi/intelpython/python3.9/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
1.7.3 1.23.5 sys.version_info(major=3, minor=9, micro=16, releaselevel='final', serial=0)
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/intel/oneapi/intelpython/latest/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/intel/oneapi/intelpython/latest/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/intel/oneapi/intelpython/latest/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/intel/oneapi/intelpython/latest/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/intel/oneapi/intelpython/latest/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/intel/oneapi/intelpython/latest/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/intel/oneapi/intelpython/latest/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/intel/oneapi/intelpython/latest/include']
>>> quit()
```

**Comment by ilayn** [comment] 2023-06-01 19:42
well it should cause some concern since 1.7 is very old compared to the things introduced with numpy 1.23.5. So I'm not sure what you mean by being picky. We are constantly monitoring which version goes well with which version of NumPy.

**Comment by mossbeachlarry** [comment] 2023-06-01 20:22
I refer to the test of `UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy`, which seems unnecessarily restrictive when NumPy released 1.23.x.  When NumPy releases a new version without a change to the API or semantics which affects backwards compatibility, this should not cause a SciPy warning.  This is the advantage of normal shared run-time libraries, which Python packages somewhat mimic.  I understand this is a bit of a guessing game, since the numbering of releases is arbitrary.

Intel packages the version of Python we use.  We have no control over which version of SciPy they use.  Why they use what you say is a very old version of SciPy and a newer version of NumPy I cannot say.  If you recommend filing an issue with Intel, I can try to do that.  I am not sure whether they have the same kind of opportunity as SciPy to communicate directly with the developers without a support contract.

**Comment by ilayn** [comment] 2023-06-01 20:35
I don't quite get the argument, Intel bundles some packages and we have no control over what Intel provides but somehow we need to adjust things so that there is no warning popping up. I don't see how it is relevant for us. There is a reason why we are putting upper bounds. Why do you think it is unnecessarily restrictive? Because we have a constant stream of backwards compatibility breaking changes between scipy and numpy and cython and pythran and openblas and many others. So is there a specific reason for that claim? 

If we don't issue a warning then the rest of the ecosystem starts telling why we don't warn users. If we warn them then we get complaints why we are warning them. This should have been an issue to Intel not to us as to why they are shipping out outdated packages.

**Comment by mossbeachlarry** [comment] 2023-06-01 21:19
The fact that SciPy only makes this a warning does not prevent the user from proceeding.  That makes this a minor annoyance, not a bug.  Thank you.

SciPy can certainly know that there is a requirement for the minimum version of a dependency.  A warning is perfectly reasonable in that case.  However, SciPy cannot foresee the future and cannot therefore know what the requirement is for the maximum version of a dependency.  That depends on the promises made by the dependent library to maintain backwards compatibility.  And, of course, whether they keep their promises.  In that case, perhaps an informational message is more appropriate, rather than a warning message.  Something to the effect of "this version of SciPy has not been tested with NumPy x.x.x".  This is what Intel does, for example, when their oneAPI packages are installed on an OS version that is not one that is known to work.

It does not sound to me like there is any interest in being more precise about the messages the user sees.  I think you should close this issue.  I will request that Intel upgrade the SciPy they bundle with their Python.

**Comment by rgommers** [comment] 2023-06-01 21:42
The warning in SciPy 1.7 seems to be off by one minor version; the requirement is `<1.24.0`: https://github.com/scipy/scipy/blob/maintenance/1.7.x/pyproject.toml#L55

In SciPy 1.10.x this is not an issue (both `<1.27.0`):
- https://github.com/scipy/scipy/blob/maintenance/1.10.x/pyproject.toml#L78
- https://github.com/scipy/scipy/blob/maintenance/1.10.x/scipy/__init__.py#L139

The problem is already solved, and the minor annoyance for 1.7.x we unfortunately cannot fix anymore. So I propose we close this issue.

**Closed** 2023-06-01 21:43 UTC
Labels: defect

**Comment by mossbeachlarry** [comment] 2023-06-02 04:59
Ralf,
> The warning in SciPy 1.7 seems to be off by one minor version; the requirement is <1.24.0: https://github.com/scipy/scipy/blob/maintenance/1.7.x/pyproject.toml#L55
> 
Thank you for the tip.  I will see about patching the Intel oneAPI Python 3.9 installation on our cluster.

Larry Baker
***@***.***

**Comment by mossbeachlarry** [comment] 2023-07-12 01:36
Ralf,

After a couple of tries I managed to find all the places that needed patching to increase the acceptable version of NumPy from <1.23.0 to <1.24.0.  Thank you for your guidance.

While reading the relevant SciPy code, I found that the upper limit on the NumPy version number is actually a guess, using a formula based on the highest NumPy version tested plus a fudge factor beyond that to set the maximum acceptable NumPy version number.  I request doing away with the test for a maximum version altogether.  Or at least permitting Python to continue after issuing a warning.  It is based on a supposition that beyond a particular release, NumPy cannot be relied on to maintain backwards compatibility.  The message from SciPy indicates a certainty which is not actually known to be true.  At most I think there should be a warning message only under these circumstances and no hard failure caused by the requires.txt file in the egg-info directory.

I, and many others I expect, encountered this situation using the latest release of the Intel oneAPI Python for Linux.  Ilhan pointed out how old the SciPy is in that release.  Even so, I have no control over that.  My desire is to obtain the speedups Intel makes possible by incorporating their libraries for performance and parallel execution.  They supply their own conda package manager, and, as I am sure you know, mixing Python package managers is a recipe for disaster.

Respectfully,

Larry Baker
***@***.***

**Comment by rgommers** [comment] 2023-07-12 08:09
I'll note that Intel addressed this problem by uploading packages for SciPy 1.10.1 5 days ago (the last version was 1.7.3) - see https://anaconda.org/intel/scipy/files.

> I request doing away with the test for a maximum version altogether. Or at least permitting Python to continue after issuing a warning. It is based on a supposition that beyond a particular release, NumPy cannot be relied on to maintain backwards compatibility.

I'm sorry, we will not do that. We are careful about shipping packages that work in a larger stack, so we're not going to remove upper bounds in a way that is pretty much guaranteed to break packages ~18 months after release. This was purely an Intel-caused problem, they simply need to be a little better at keeping packages as widely used as SciPy up-to-date.
