### ISSUE TITLE
BUG: `scipy.optimize.milp` sometimes crashes with `HiGHS` assertion failure in `1.9.2`

### ISSUE THREAD

**Issue by woutervbk** [scipy/scipy#17220] opened 2022-10-13 11:26 UTC
### Describe your issue.

Background: just upgraded from `1.9.1` to `1.9.2` to test out the fix for #16545. 

Some MILP models that solved perfectly fine with `scipy.optimize.milp` in `1.9.1` crash hard in `1.9.2` from deep within the `HiGHS` code:
```
Running HiGHS 1.2.0 [date: 2021-07-09, git hash: n/a]
Copyright (c) 2022 ERGO-Code under MIT licence terms

Presolve is switched off

Solving MIP model with:
   358 rows
   332 cols (101 binary, 0 integer, 0 implied int., 231 continuous)
   961 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   0               inf                  inf        0      0      0         0     0.0s
         0       0         0   0.00%   111.5580767     inf                  inf        0      0      7        46     0.0s
Assertion failed: (fracval < localdom.col_upper_[col] - mipsolver.mipdata_->feastol), function selectBranchingCandidate, file HighsSearch.cpp, line 279
```

I tried to investigate this myself by looking into the `HiGHS` logs and the funny thing is that this assertion does not fail when I pass `highs_debug_level` with a value of 1, 2 or 3 (default=0) as a verbatim option to `scipy.optimize.milp()`.

Also, I noticed that somehow the `HiGHS` version was downgraded from `1.2.2` to `1.2.0` between `1.9.1` and `1.9.2`. Is this intentional? If not, I guess that might be the underlying culprit?

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
Assertion failed: (fracval < localdom.col_upper_[col] - mipsolver.mipdata_->feastol), function selectBranchingCandidate, file HighsSearch.cpp, line 279
```

### SciPy/NumPy/Python version information

1.9.2 1.23.4 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)

**Comment by woutervbk** [comment] 2022-10-13 11:42
This ring a bell to you guys @mckib2 @mdhaber ?

**Comment by mdhaber** [comment] 2022-10-13 18:08
I don't think we intentionally downgraded HiGHS, and @mckib2 confirmed. How are you checking the HIGHS version?

**Comment by woutervbk** [comment] 2022-10-13 18:25
Yeah that's also how I found out. What would be the course of action now? Bump HiGHS back to 1.2.2 in SciPy 1.9.3?

**Comment by mckib2** [comment] 2022-10-14 02:55
The version numbers are inconsequential, the reason they show up differently is based on the way you build them in scipy:
- distutils builds will report the version [scraped from](https://github.com/scipy/scipy/blob/075e40fbe4f70f3ce774e75e2da7ee7f34f9c27d/scipy/optimize/_highs/setup.py#L65) the `CMakeLists.txt` (which doesn't always get incremented regularly by upstream maintainers)
- meson builds will currently [always report 1.2.0](https://github.com/scipy/scipy/blob/075e40fbe4f70f3ce774e75e2da7ee7f34f9c27d/scipy/optimize/_highs/meson.build#L6) (because we don't want to do dark magic to have meson be able to scrape the `CMakeLists.txt`)

The HiGHS submodule [hash itself](https://github.com/scipy/highs/tree/4a122958a82e67e725d08153e099efe4dad099a2) hasn't changed in the past 3 months, so the variability may be in whether you are using a distutils build or a meson build (which would be insidious!).

Can you provide a reproducer so I can try to reproduce the error?  (it also occurs to me, we probably want to be building in release which would remove assert statements, but it's also nice to catch these errors...)

**Comment by woutervbk** [comment] 2022-10-14 08:55
The underlying optimisation model is quasi-infeasible due to its inherent poor numerical quality, and HiGHS trips on a feasibility tolerance check in the branch and bound phase.

In 1.9.1, HiGHS reported this particular model to be infeasible, which the Python code then would be able to handle properly. In 1.9.2, the assertion in HiGHS just nukes the whole Python process without any possibility errors...) of recovery. Needless to say, I prefer the 1.9.1 way of working.

The `milp` call is done quite deep in a program, and it would not be trivial to extract its exact input data.

**Comment by mckib2** [comment] 2022-11-27 04:14
@woutervbk gh-17430 I believe should resolve this issue.  Are you able to pull a nightly wheel or build from main to confirm if the issue is resolved or not?

**Comment by woutervbk** [comment] 2022-11-30 10:02
@mckib2 I can confirm that I was able to successfully run all my unit tests with `https://anaconda.org/scipy-wheels-nightly/scipy/1.10.0.dev0/download/scipy-1.10.0.dev0-cp39-cp39-macosx_12_0_arm64.whl`, including the one for which I opened this issue.

**Comment by mckib2** [comment] 2022-12-06 02:34
Great! I'll close this and it should be available in the next upcoming release

**Closed by mckib2** 2022-12-06 02:34 UTC
Labels: defect, scipy.optimize
