### ISSUE TITLE
DEP: add deprecation warnings to kwargs `turbo` / `eigvals` of `linalg.eigh`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#16252] opened 2022-05-23 13:14 UTC
Deprecated in documentation only since https://github.com/scipy/scipy/pull/11304

CC @ilayn

**Comment by hfactor13** [comment] 2022-07-17 21:12
Isn't this issue just a duplicate of #16355? After looking at that issue number, they seem very similar. I suggest adding a duplicate tag if that's the case.

**Comment by h-vetinari** [comment] 2022-07-17 21:51
> Isn't this issue just a duplicate of #16355? After looking at that issue number, they seem very similar.

This is the issue and #16355 is the PR intended to close this issue - no duplication, but a very intimate relation.

**Closed** 2022-12-06 03:41 UTC
Labels: scipy.linalg, good first issue, deprecated
