### ISSUE TITLE
test_arpack.test_real_nonsymmetric_modes hangs with Macports

### ISSUE THREAD

**Issue by cdeil** [scipy/scipy#4383] opened 2015-01-08 10:01 UTC
On Mac OS X 10.10 with the latest `py34-scipy @0.14.1_2+gcc48` from Macports a lot of `arpack` tests fail and finally the `test_arpack.test_real_nonsymmetric_modes` test hangs:
```
test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LR', None, (0.1+0.1j), <class 'scipy.sparse.csr.csr_matrix'>, 'i') ... ERROR
test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LR', None, None, <class 'scipy.sparse.csr.csr_matrix'>, None) ... ERROR
test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LR', None, 0.1, <function aslinearoperator at 0x106add1e0>, 'r') ... ^C^C^CTerminated: 15
```

Here's the Macports issue which includes links to the full config and log output:
https://trac.macports.org/ticket/46428

This issue can be seen on the `ci.scipy.org` machine ... anyone that wants ssh access to debug it can email me.

**Comment by pv** [comment] 2015-01-08 10:08
Try running it in gdb and obtain a traceback to see what exactly fails.

**Comment by cdeil** [comment] 2015-01-08 10:31
How can I run a specific test?

I tried the `label` option of the `test` function like this
```
scipy.test(label='test_arpack.test_real_nonsymmetric_modes')
scipy.test(label='test_arpack', verbose=10)
scipy.test(label='test_real_nonsymmetric_modes', verbose=10)
```
but it doesn't work. The first line gives an `AttributeError` and the other two run the `test_interpolate_wrapper.Test` test!?

When I sample the process with the "Activity Monitor" tool on OS X I get this output:
https://gist.github.com/cdeil/6c31938c15da92d6e7e5#file-gistfile1-txt-L18
Does this mean anything to you?

How would I run `gdb` to obtain a meaningful traceback?

**Comment by pv** [comment] 2015-01-08 11:02
The call graph from activity monitor is good enough.
.
Most likely explanation is ABI mismatch. If so, the issue should be
present also with 0.14.0, assuming macports build options are the same.

**Comment by cdeil** [comment] 2015-01-08 12:03
@pv - I don't know if the issue was present with 0.14.0.

It could also be new now because of the changes by @seanfarley to the Macports scipy build:
https://trac.macports.org/log/trunk/dports/python/py-scipy/Portfile?rev=131020

**Comment by seanfarley** [comment] 2015-01-08 17:41
@pv - do you mean ABI mismatch between fortran versions? If so, which two libraries are mismatched?

**Comment by pv** [comment] 2015-01-08 18:08
Yes, Fortran --- since it's the single-precision tests that are
failing but not the double precision ones, Fortran ABI mismatch comes
to mind. Previously failures of this kind were due to ABI mismatch in
Accelerate ABI vs. the ARPACK code.
.
However, there are two reasons speaking against this now: (i) Scipy
has ABI wrappers that are used when Accelerate is used to account for
Accelerate's g77 ABI, and (ii) macports apparently compiles Scipy with
-ff2c. So I'm not sure what is going on here.
.
Note that the -ff2c flag should not be needed for Scipy >= 0.14.0
together with Accelerate, due to the presence of ABI wrappers.
.
Is the failure limited to Python 3, or does it also occur with Python 2?

**Comment by cdeil** [comment] 2015-01-08 18:13
Same failures with Python 2.7.

**Comment by seanfarley** [comment] 2015-01-08 18:31
I can reproduce with both python 2 and 3. Also, thanks for the explanation, this is invaluable to me :-)

Tracing through annotate, '-ff2c' is from Jack Howarth back in 2013 with no explanation given besides "fixes compilation." I will test removing it and see if that fixes the hanging.

**Comment by pv** [comment] 2015-01-08 19:22
0.14.0 seems to show the same behavior. Omitting -ff2c didn't seem to
fix the issue. Also fails for homebrew using their gcc+gfortran.
clang+macports-gfortran works. clang+homebrew-gfortran also works. The
reason may then be connected to what "-D__ACCELERATE__" exactly does (no
idea), and why it is needed, as it seems the issue may be that the
Accelerate ABI wrapper .c files are not compiled correctly.

**Comment by seanfarley** [comment] 2015-01-08 19:58
I, also, have no idea what that does. It was needed to [fix building with gcc](http://trac.macports.org/ticket/46395). Doing some searching seems to indicate that no one really knows what it does and we all just found the same R mailing list post :-)

**Comment by pv** [comment] 2015-01-08 20:20
Identical homebrew issue is here: https://github.com/Homebrew/homebrew-python/issues/110

**Comment by pv** [comment] 2015-01-08 20:38
Compiling with `gcc -flax-vector-conversions`, as gcc tells you to do in the original compilation failure message, seems to fix the issue. It seems Accelerate headers contain some stuff that's gcc doesn't like unless it's told to.

`__ACCELERATE__` could be some internal Accelerate define not meant to be used by users, which could explain why it makes things break.

**Comment by pv** [comment] 2015-01-08 20:43
Closing, please reopen if fixing the compiler flags doesn't help.

**Comment by seanfarley** [comment] 2015-01-11 18:48
Ok, so I finally got around to trying `-flax-vector-conversions` but get the interesting:

```
building 'arpack_scipy' library
compiling C sources
C compiler: /opt/local/bin/gcc-mp-4.9 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/include -flax-vector-conversions

creating build/temp.macosx-10.10-x86_64-2.7/opt
creating build/temp.macosx-10.10-x86_64-2.7/opt/local
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports/build
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy/py27-scipy
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy/py27-scipy/work
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy/py27-scipy/work/scipy-0.15.0
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy/py27-scipy/work/scipy-0.15.0/scipy
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy/py27-scipy/work/scipy-0.15.0/scipy/_build_utils
creating build/temp.macosx-10.10-x86_64-2.7/opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy/py27-scipy/work/scipy-0.15.0/scipy/_build_utils/src
compile options: '-Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -c'
gcc-mp-4.9: /opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy/py27-scipy/work/scipy-0.15.0/scipy/_build_utils/src/wrap_g77_abi_c.c
In file included from /usr/include/os/object.h:27:0,
                 from /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/LinearAlgebra/base.h:6,
                 from /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/LinearAlgebra/LinearAlgebra.h:10,
                 from /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vecLib.h:65,
                 from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20,
                 from /opt/local/var/macports/build/_Users_sean_projects_macports_dports_python_py-scipy/py27-scipy/work/scipy-0.15.0/scipy/_build_utils/src/wrap_g77_abi_c.c:1:
/usr/include/os/base.h:113:20: error: missing binary operator before token "("
 #if __has_extension(attribute_overloadable)
```

This seems crazy. Googling seems to indicate that Apple is using a clang dialect in their header file which ... is unfortunate. Any ideas here?

**Comment by pv** [comment] 2015-01-11 18:53
The lax-vector-conversions worked when I tried it, but apparently things are nasty :/

Replacing `#include <Accelerate/Accelerate.h>` with `#include <cblas.h>` might be enough, since we only need those function prototypes.

**Comment by seanfarley** [comment] 2015-01-11 19:22
Ok, I'll test that and see if it works :-)

**Comment by seanfarley** [comment] 2015-01-12 00:56
Yep, that works!

**Comment by charris** [comment] 2015-01-12 02:18
There was a problem with `cblas.h` on OS X  10.10 and also MKL. See https://github.com/numpy/numpy/pull/5047#issuecomment-55203072 and after.

**Comment by seanfarley** [comment] 2015-01-12 02:39
Using `cblas.h` actually removed the need to `-flax-vector-conversions`. Also, MKL is not in MacPorts so wouldn't be a problem here.

**Comment by pv** [comment] 2015-01-12 09:11
These files are only compiled when using Accelerate, so switching to
cblas.h shouldn't be a problem here.

**Comment by seanfarley** [comment] 2015-01-12 15:46
@pv does it make sense that `-flax-vector-conversions` is no longer needed?

**Comment by pv** [comment] 2015-01-12 15:52
Yes, cblas.h probably doesn't include the rest of the Accelerate headers.

**Comment by seanfarley** [comment] 2015-01-12 16:39
:+1

**Closed** 2015-01-15 20:46 UTC
Labels: Build issues
