### ISSUE TITLE
ValueError: cannot set WRITEABLE flag to True of this array for scipy sparse 

### ISSUE THREAD

**Issue by LKChenLK** [scipy/scipy#14179] opened 2021-06-04 19:01 UTC
I was running a piece of code that does adversial attack on a graph ([source](https://github.com/danielzuegner/nettack/blob/master/nettack/nettack.py) ). I suppose it runs into problems when calling ```.tocsr```, and googling yields no results. 
In the code below, ```adj``` is an adjacency matrix in ```lil_matrix``` format (with dimension, and ```edges``` is a 2-D tensor (shape 2109*2), if that helps.

#### Reproducing code example:

```
    degs = np.squeeze(np.array(np.sum(adj,0)))
    existing_edges = np.squeeze(np.array(adj.tocsr()[tuple(edges.T)]))
    if existing_edges.size > 0:
        edge_degrees = degs[np.array(edges)] + 2*(1-existing_edges[:,None]) - 1
    else:
        ...
```

#### Error message:

```
Traceback (most recent call last):
  File "/Users/.../main.py", line 102, in <module>
    multi_test_poison()
  File "/Users/.../main.py", line 88, in multi_test_poison
    model.attack_surrogate()
  File "/Users/.../attacker.py", line 459, in attack_surrogate
    singleton_filter = filter_singletons(self.potential_edges, self.adj)
  File "/Users/.../attacker.py", line 515, in filter_singletons
    existing_edges = np.squeeze(np.array(adj.tocsr()[tuple(edges.T)]))
  File "/usr/local/lib/python3.9/site-packages/scipy/sparse/_index.py", line 68, in __getitem__
    row, col = _broadcast_arrays(row, col)
  File "/usr/local/lib/python3.9/site-packages/scipy/sparse/_index.py", line 23, in _broadcast_arrays
    x.flags.writeable = a.flags.writeable
ValueError: cannot set WRITEABLE flag to True of this array
```

#### Scipy/Numpy/Python version information:

Scipy version: 1.6.3 
Numpy version: 1.20.1 
Python version: 3.9.5 (default, May  4 2021, 03:36:27)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin

**Comment by ogauthe** [comment] 2021-06-08 11:04
Hello,

I cannot reproduce your error.
```
import numpy as np
import scipy.sparse

adj =  scipy.sparse.csr_matrix(np.eye(100))
edges = np.array([[1, 1], [5, 4], [8, 2]])
adj[tuple(edges.T)]
```
This works. It returns a dense np.matrix object, which is a bit surprising, but it does not crash. Could you provide cases where it fails with given values of `adj` and `edges` please?

**Comment by rgommers** [comment] 2022-02-22 20:29
No follow-up, and this is not actionable without a reproducer - so I'll close this issue. @LKChenLK if you can provide a self-contained code snippet to reproduce the problem, we can reopen and investigate.

**Closed by rgommers** 2022-02-22 20:29 UTC
Labels: scipy.sparse
