### ISSUE TITLE
BUG: binom.pmf - RuntimeWarning: divide by zero

### ISSUE THREAD

**Issue by Lena506** [scipy/scipy#15101] opened 2021-11-25 07:40 UTC
### Describe your issue.

Since installing scipy 1.7.0 with Python 3.10 I get a RuntimeWarning divide by zero encountered counducting the binom.pdf() procedure (see example). Working with scipy 1.6.3 and Python 3.9 I didn't get this warning. Because of that I pressume a connection with the new C++ _boost library which is now used for tests using the binomial distribution. In detail I found out the difference between the _boost_binom_pdf() and the former _pmf (_discrete_distns.py) is on the one hand the incomplete beta function is used to calculate the binomial coefficient and on the other hand the logarithm of the absolute value of the gamma function is used. This difference seems to lead to the division by zero error in certain constellations.

### Reproducing Code Example

```python
from scipy.stats import binom

n = 208
k = 207
p = 0.0003

X = binom.pmf(k, n, p)
```

### Error message

```shell
C:\subversion\testrep\07_Envs\Standard\venv_3.10\lib\site-packages\scipy\stats\_discrete_distns.py:67: RuntimeWarning: divide by zero encountered in _binom_pdf
  return _boost._binom_pdf(x, n, p)
```

### SciPy/NumPy/Python version information

1.7.2 1.21.4 sys.version_info(major=3, minor=10, micro=0, releaselevel='final', serial=0)

**Comment by siddharthpaliwal** [comment] 2021-11-30 10:55
Can replicate and confirm the issue with scipy=1.7.3 as well. 
Although the warning does not lead to any error in the calculation of the pmf. The example below results in the two calculations (first with scipy.stats.binom Warning and second with a more direct calculation) to be within tolerance.

### Code (compare with alternate calculation)
```
import numpy as np
from scipy.special import comb
from scipy.stats import binom

n = 1000 # divide by zero warning at n=400 but not with say n=300
p = 0.01
klo = 30
khi = 998
k = np.arange(klo, khi, dtype=np.int32)
print('Run scipy binom.pmf...')
res1 = binom.pmf(k, n, p) # Use scipy binom module
print('Run alternative binomial pmf calculation...')    
# Definition: binom.pmf(k) = choose(n, k) * p**k * (1-p)**(n-k)
res2 = comb(n, k) * (p**k) * ((1-p)**(n-k)) # Alternate (likely inefficient) calculation
print('Are the two calculations close?:',np.allclose(res1, res2))
```

### Output
```
Run scipy binom.pmf...
c:\Users\PaliwalS.RABONETEU\Miniconda3\envs\testbinom\lib\site-packages\scipy\stats\_discrete_distns.py:67: RuntimeWarning: divide by zero encountered in _binom_pdf
  return _boost._binom_pdf(x, n, p)
Run alternative pmf calculation...
Are the two calculations close?: True
```

### SciPy/NumPy/Python version information
1.7.3  1.21.4   sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by mdhaber** [comment] 2022-03-15 15:26
@mckib2 can we ignore the divide warnings, too?

**Comment by bbbbbbbbba** [comment] 2022-07-12 15:14
I should first mention that in `binom.pmf(k, 1000, 0.01)`, the warning actually starts appearing at 995, not 996. Remember that `np.arange(291, 995)` does not include 995.

From my debugging, the divide-by-zero happens at https://github.com/boostorg/math/blob/db2a7cbb44a84c4c9cba62232c07f18b22bd965d/include/boost/math/special_functions/beta.hpp#L392-L393:
```cpp
            T p1 = pow(b1, a / b);
            T l3 = (log(p1) + log(b2)) * b;
```
Here `b1` is pretty close to `p` when `k` is close to `n`,  `a` is `k + 1`, and `b` is `n - k + 1`. In regimes such as `k, n, p = 995, 1000, 0.01`, `pow(b1, a / b)` underflows, and `log(p1)` gives the divide-by-zero.

To demonstrate (approximately since `b1` is not exactly equal to `p`):
```python console
>>> 0.01 ** ((994 + 1) / (6 + 1))
5.179474679231323e-285
>>> 0.01 ** ((995 + 1) / (5 + 1))
0.0
```

**Comment by mdhaber** [comment] 2022-07-12 17:12
Thanks @bbbbbbbbba, @mckib2!
In the meantime, does it look like this will ever happen when the probability mass is distinguishable from zero?
If not, would you open a PR that suppresses the warning with `np.errstate`? If so, I can review and merge.

**Comment by mckib2** [comment] 2022-07-12 18:06
>  In the meantime, does it look like this will ever happen when the probability mass is distinguishable from zero?

It looks to me like this code path is only encountered when trying to handle potential overflows and still does the "right thing", i.e., the infinity encountered after the log seems to be handled correctly.  I'll create a PR with a quick fix until boost upstream properly resolves

**Comment by taldcroft** [comment] 2023-02-09 12:05
I'm still seeing a variation of this problem in v1.10.0:
```
In [1]: import scipy

In [2]: scipy.__version__
Out[2]: '1.10.0'

In [4]: from scipy.stats import binom
   ...: 
   ...: n = 2000
   ...: k = 3
   ...: p = 0.9999
   ...: 
   ...: X = binom.pmf(k, n, p)
/Users/aldcroft/miniconda3/envs/ska3-flight-2023.1rc4/lib/python3.10/site-packages/scipy/stats/_discrete_distns.py:77: RuntimeWarning: divide by zero encountered in _binom_pdf
  return _boost._binom_pdf(x, n, p)
```
What is curious is that it does not seem that the fix in #16588 got into the v1.10.0 release.
https://github.com/scipy/scipy/blob/v1.10.0/scipy/stats/_discrete_distns.py#L75
??

**Comment by mdhaber** [comment] 2023-02-11 06:48
Interesting! I'll follow up in gh-16588.

**Comment by mdhaber** [comment] 2023-02-11 06:56
@mckib2 @mborland The original issue here was for `binom` with small `p`, and it looks like that was indeed resolved, but now we're seeing a divide by zero for large `p`. Does it look related?

**Comment by mborland** [comment] 2023-02-11 16:28
> @mckib2 @mborland The original issue here was for `binom` with small `p`, and it looks like that was indeed resolved, but now we're seeing a divide by zero for large `p`. Does it look related?

Confirmed that this is setting the `FE_DIVBYZERO` flag with the above parameters. Not sure if it is related, but I will open an issue on the boost side.

**Comment by mborland** [comment] 2023-02-11 17:20
It was very similar to the other issue just on a different special handling path. Should be fixed by https://github.com/boostorg/math/pull/949.

**Comment by taldcroft** [comment] 2023-02-11 19:29
Thanks for looking into this. So until the upstream boost fix gets in, is it safe to ignore the divide by zero warning?

**Comment by mdhaber** [comment] 2023-02-12 03:40
I'll let @mborland reply to that one because I don't know firsthand (without reviewing the code in detail).

**Comment by mborland** [comment] 2023-02-12 05:16
I believe it's safe to ignore. The flag is not being set by an actual divide by zero but a defined response to log(0) by the C++ standard library in addition to returning -infinity as it should.

**Comment by mdhaber** [comment] 2023-02-13 16:06
Thanks @mborland!

**Closed** 2023-02-27 22:24 UTC
Labels: defect, scipy.stats
