### ISSUE TITLE
BUG: circe-ci eigenvalue-LOBPCG benchmarks do not check accuracy so the reported timing may be meaningless

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#18568] opened 2023-05-27 16:00 UTC
### Describe your issue.

circe-ci benchmarks for iterative solvers run a fixed number of iterations and report only the timing, but do not control or even report accuracy. In many cases, specifically easy to see for `lobpcg` eigen- and svd-value solver that luckily issues a warning if no convergence. E.g., in some of the tests, LOBPCG actually diverges according to the warnings, e.g., sakurai 400 in https://circleci.com/api/v1.1/project/github/lobpcg/scipy/5/output/104/0?file=true&allocation-id=6404e834b184783f39b98eb9-0-build%2F5CDB6F39 :
For parameters: 400, 'lobpcg'
/home/circleci/repo/benchmarks/benchmarks/sparse_linalg_lobpcg.py:104: UserWarning: Exited at iteration 500 with accuracies
[129749.23860412 12190.46851306 4488.84973568]
not reaching the requested tolerance 1e-06.
Use iteration 0 instead with accuracy
1.9704540387834288.

Moreover, if the prescribed number of iterations has been modified inside a solver, the benchmark is unable to catch that the change in performance is artificial. This is exactly what has happed in `lobpcg` when the line
`maxIterations = min(n, maxIterations)`
has been removed between scipy releases 1.2 and 1.3, the benchmarking has reported a dramatic sudden loss of performance especially for small `n`, as noticed in https://github.com/scipy/scipy/issues/17672 and illustrated, e.g., in https://pv.github.io/scipy-bench/#sparse_linalg_lobpcg.Bench.time_sakurai?cpu=Intel(R)%20Core(TM)%20i7%20CPU%20920%20%40%202.67GHz&machine=i7&num_cpu=8&os=Linux&ram=16416652&python=3.7&numpy=1.14.5&Cython=0.29.21&pybind11=2.5.0&pythran=&setuptools=%5Bnone%5D 

### Reproducing Code Example

```python
Run benchmark or look at a log of the benchmarks run by circle-ci for any PR.
```

### Error message

```shell
E.g., sakurai 400 in https://circleci.com/api/v1.1/project/github/lobpcg/scipy/5/output/104/0?file=true&allocation-id=6404e834b184783f39b98eb9-0-build%2F5CDB6F39 :
For parameters: 400, 'lobpcg'
/home/circleci/repo/benchmarks/benchmarks/sparse_linalg_lobpcg.py:104: UserWarning: Exited at iteration 500 with accuracies
[129749.23860412 12190.46851306 4488.84973568]
not reaching the requested tolerance 1e-06.
Use iteration 0 instead with accuracy
1.9704540387834288.
```

### SciPy/NumPy/Python version and system information

```shell
current main
```

**Comment by tupui** [comment] 2023-05-27 17:12
Hi @lobpcg, I don't really say there is a "bug" in the sense that it's besides the point.

Our use of this benchmarking suite is only to report speed change. Accuracy and everything else is out of scope. What matters is just what happens in terms of time for a given set of parameters. The test suite is here to cover the accuracy part and we should not do the work twice here. You can actually see that in most benchmarks we only call the function and don't do any inspection nor checks.

Will leave this open a bit in case other maintainers want to argue with that.

**Comment by lobpcg** [comment] 2023-05-27 17:26
I understand, but an unfortunate consequence of this metric alone is that the ultimate performance will be achieved by a code that computes nothing in zero time, while the current benchmarking is unable to catch such a scenario. 
Reporting the accuracy is probably an overkill, but checking for some trivial required accuracy should probably be done and if the accuracy is not met the run should be considered as failed and no timing reported.

Algorithm development, especially for iterative methods, often faces the choice of increasing the speed at the cost of declining accuracy, so benchmarking is untrivial.

**Comment by tupui** [comment] 2023-05-28 09:28
> I understand, but an unfortunate consequence of this metric alone is that the ultimate performance will be achieved by a code that computes nothing in zero time, while the current benchmarking is unable to catch such a scenario.

Benchmarking is never an easy task as you are always making assumptions and this only verify a given use case. Which means that we want to use "easy" and reproducible cases. Ultimately, the case and result could make no sense that it would not be relevant nor matter.

> Reporting the accuracy is probably an overkill, but checking for some trivial required accuracy should probably be done and if the accuracy is not met the run should be considered as failed and no timing reported.

Convergence and accuracy are out of scope. These have to be checked in the test suite itself. Here we would want to look at numbers of iterations, common cases, etc.

> Algorithm development, especially for iterative methods, often faces the choice of increasing the speed at the cost of declining accuracy, so benchmarking is untrivial.

There is benchmark and benchmark. What we are interested in this case is purely the implementation part. i.e. is our implementation of a given algorithm fast or slow. It has nothing to do with the "performance" of the method itself, the algorithmic part.

The performance or convergence, should be thorouly checked during the design and implementation phase. Tests are here to ensure that the performance stays the same while benchmark are here to ensure that the speed and memory stay the same or improves.

Another point that could help to make the distinction, in optimize we have a special benchmark suite which is only used to check the performance in terms of convergence of an algorithm. This suite is different than the benchmarking suite that we run in the CI and that we use to determine speed or memory regressions.

**Comment by lobpcg** [comment] 2023-07-23 17:34
@tupui yes, we are interested in this case is purely the implementation part. i.e. is our implementation of a given algorithm fast or slow. But the baseline must be meaningful, rather than outputting garbage.

Also, specific to iterative methods, there is little point to improve the performance of an implementation if this implementation breaks the convergence at the same time. For example, it is very easy to take any iterative solver and modify it such that every iteration runs faster, but this modification would often deteriorate convergence. A benchmark that runs a fixed number of iterations and does not assert the accuracy of the output would be misleading for such modifications. This is exactly the issue with the present benchmarking of LOBPCG, and possibly other iterative solvers.

**Comment by tupui** [comment] 2023-07-24 09:01
> A benchmark that runs a fixed number of iterations and does not assert the accuracy of the output would be misleading for such modifications.

I am afraid this is not how our tooling works. ASV benchmarks are really just to check speed, nothing else.

How we handle what you describe is actually on the testing side, with Pytest. We use known problems and expect the solution in `n` iterations. This does not check speed. The speed part is handled on the benchmark suite side. This strategy is not perfect but works in practice. It's also what we can do with the tools we have.

**Comment by h-vetinari** [comment] 2023-07-25 09:24
To be fair, I do see the argument that the benchmarks should be apples-to-apples comparisons. I don't think the benchmarks should retest the functionality of the algorithms, but I would find it reasonable to ensure that we're not comparing converged vs. unconverged, for example.

Ideally, the API should ensure that already (e.g. built-in default tolerance must be reached), or it can be ensured with the parameters chosen for the benchmarks (out of the critical regions), or we a law resort, with some small amount of glue code. But by and large, benchmarks should be barely more than calling a function, and whatever setup is necessary to pass the parameters

**Comment by lobpcg** [comment] 2023-07-25 14:19
> > A benchmark that runs a fixed number of iterations and does not assert the accuracy of the output would be misleading for such modifications.
> 
> I am afraid this is not how our tooling works. ASV benchmarks are really just to check speed, nothing else.
> 
> How we handle what you describe is actually on the testing side, with Pytest. We use known problems and expect the solution in `n` iterations. This does not check speed. The speed part is handled on the benchmark suite side. This strategy is not perfect but works in practice. It's also what we can do with the tools we have.

Pytese examples are unrelated to ASV benchmarks at least in case of LOBPCG and thus the former cannot be used to validate the latter. 

Benchmark is a tool, not a philosophical concept. It is a tool for a user to choose a better performing solver. If a benchmark is meaningless computing garbage because the solver is called in a wrong way or the comparison baseline is wrong, it fails this goal - the issue with the present benchmark.

It is also a tool for a developer to validate that changes in a code do not degrade performance. For iterative solvers, performence is determined by a total execution time, which is the time per iteration times the number of iterations needed to get the requested accuracy. The present benchmark does not check the accuracy, so fails this goal too, i.e., is quite useless and misleading. The property that for a known problem a code of an iterative solver gives a guaranteed accuracy in a known fixed number of iterations is desired but not given and has to be checked and rechecked with every chance of the code.

A meaningless, misleading, and useless benchmark has little if any positive value to the user as well as to the developer, which is the case of the benchmark discussed here.

**Comment by tupui** [comment] 2023-07-25 15:40
> The present benchmark does not check the accuracy, so fails this goal too, i.e., is quite useless and misleading.

This is because you are misunderstanding the current goal of the benchmark suite. Which is to check speed and memory consumption. This is the current state of things. If we would want to change that, we need first to take a decision with all maintainers.

> The property that for a known problem a code of an iterative solver gives a guaranteed accuracy in a known fixed number of iterations is desired but not given and has to be checked and rechecked with every chance of the code.

You don't need to check the convergence every time you change a line. In software engineering you have a test hierarchy going from unit test, integration tests, to validation or system level tests. The frequency at which you run all of that depends on so many things. It's very unlikely to break system level tests if all the underlying tests are fine.

I also have some benchmarks on the side for QMC and it never breaks because I am confident in the unit and integration tests I wrote. I am testing all code paths independently and this ensures that the convergence properties are not changed. i.e. I don't need and want to do any science in my testing suite.

> Pytest examples are unrelated to ASV benchmarks at least in case of LOBPCG and thus the former cannot be used to validate the latter.

Then we should update the tests themselves. This is our current structure. The main reason for that is that tests are run on various platforms, and with a wide range of versions on the dependencies, various Python versions, etc. On the other hand, ASV benchmarks are only being run in a single job. It would not be a good thing to rely on that.

> Benchmark is a tool, not a philosophical concept. It is a tool for a user to choose a better performing solver.

My view is that ASV is not a great tool for that. Let me use a very concrete example: https://locust.io 

This is an excellent benchmarking tool for assessing backends/APIs. You could run similar benchmark tasks with ASV, but the developer experience would be horrific (after you managed to add a lot of custom things). And I think we are in a similar situation here.

We have a benchmark suite, following what you want here with checks on convergence, for optimization. And the experience is really bad compare to something like Locust. I just don't think it's the right tool and in terms of maintenance I would not want to try to hack something around ASV.

**Comment by lobpcg** [comment] 2023-08-04 15:30
@tupui sorry I missed the community meeting.
 
https://mail.python.org/archives/list/scipy-dev@python.org/thread/J5JMUHICHSNDCZX46G5UQ4O737MHL3SU/ @rgommers supports meaningful benchmarks but suggests duplicating the runs in the test suite that is ran way more often and on a much wider range of platforms, so it is a much better place for check of the accuracy.

**Closed** 2023-10-05 21:55 UTC
Labels: defect, Benchmarks, needs-decision
