### ISSUE TITLE
Unexpected change in sparse matrix format following point-wise multiply

### ISSUE THREAD

**Issue by hickmanw** [scipy/scipy#12645] opened 2020-07-30 23:37 UTC
I multiply (point-wise) a sparse matrix in CSC format by a 1-D numpy array. I expected the result to be a sparse matrix in CSC format, but instead it returns in COO format. Is this intended? How could I preserve the CSC format? 

The docs for `multiply` don't mention the format changing, and the docs for the COO format say it does not directly support arithmetic operations, which makes the resulting COO format more unexpected to me.

```python
import numpy as np
import scipy.sparse as sp_sparse

x = np.random.rand(20)
spmat = sp_sparse.identity(x.shape[0], format="csc")
print(type(spmat))
print(type(spmat.multiply(x)))
```

> <class 'scipy.sparse.csc.csc_matrix'>
> <class 'scipy.sparse.coo.coo_matrix'>

**Comment by zhaog6** [comment] 2021-01-28 09:30
Dear hickman,

This feature is currently supported. You can add:
```python
y = spmat.multiply(x).asformat(format="csc", copy=False)
```

Thanks,
Gang

**Comment by perimosocordiae** [comment] 2021-01-28 18:02
For some context, we handle CSR/CSC point-wise multiplication against dense ndarrays with this code path, which internally converts the matrix to COO format first: https://github.com/scipy/scipy/blob/d02a18605714180550bc4287f3964699d6466517/scipy/sparse/compressed.py#L423

In general, we try not to make any guarantees about the format of sparse matrices that result from various operations, as different formats are more convenient/efficient for different functions.

As @zhaog6 suggested, if you need to keep a specific format, you can always use `.asformat()` or equivalently in this case `.tocsr()`. I might recommend leaving your matrix in COO format, however, unless you need specific functionality that it doesn't support.

**Comment by perimosocordiae** [comment] 2021-01-28 18:02
I'll close this now as "working as intended", but feel free to continue the discussion if you like.

**Closed by perimosocordiae** 2021-01-28 18:02 UTC
Labels: scipy.sparse
