### ISSUE TITLE
Build failure on 14.04.2

### ISSUE THREAD

**Issue by 317070** [scipy/scipy#4719] opened 2015-04-12 21:36 UTC
On my pretty bare linux ubuntu-gnome 14.04.2 (formatted today) this fails:

```
sudo pip install git+http://github.com/scipy/scipy/
```

```
x86_64-linux-gnu-gcc: build/src.linux-x86_64-2.7/scipy/signal/lfilter.c

scipy/signal/lfilter.c.src: In function ‘scipy_signal_sigtools_linear_filter’:

scipy/signal/lfilter.c.src:285:37: error: lvalue required as left operand of assignment

             PyArray_BASE(arVi_view) = arVi;

                                     ^

scipy/signal/lfilter.c.src: In function ‘scipy_signal_sigtools_linear_filter’:

scipy/signal/lfilter.c.src:285:37: error: lvalue required as left operand of assignment

             PyArray_BASE(arVi_view) = arVi;

                                     ^

error: Command "x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -Iscipy/signal -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c build/src.linux-x86_64-2.7/scipy/signal/lfilter.c -o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/scipy/signal/lfilter.o" failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-CZiYha-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-n7SWZu-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-CZiYha-build
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 51: ordinal not in range(128)
```

This works fine:
```
sudo pip install git+http://github.com/scipy/scipy.git@maintenance/0.15.x
```
Numpy version is '1.10.0.dev0+3c5409e', installed with
```
sudo pip install git+http://github.com/numpy/numpy/
```

**Comment by 317070** [comment] 2015-04-12 21:39
Probably caused by: 643cd58b6ad838a777c8fe578cebc15ac61bd10e

**Comment by ewmoore** [comment] 2015-04-12 21:55
It's absolutely caused by that commit. I'm not sure why this is fsing
though. It worked fine here, and on Travis.  I'm also not sure how to set
the base pointer if that doesn't do it. I'll try to look at this tomorrow,
but if someone sees has some thoughts…

**Comment by ev-br** [comment] 2015-04-12 22:09
Just a stupid question: what happens if you install things into a clean virtualenv instead of installing it all system-wide?

**Comment by 317070** [comment] 2015-04-12 22:15
In this case, it ought to be exactly the same result. Let me copy-paste the commands executed between formatting and installing scipy:
```
sudo pip install cython
sudo apt-get install pip
sudo apt-get install python-pip gfortran libopenblas-dev liblapack-dev
sudo pip install cython
sudo apt-get install python-dev
sudo pip install cython
sudo pip install git+http://github.com/numpy/numpy/
sudo apt-get install git
sudo pip install git+http://github.com/numpy/numpy/
sudo pip install git+http://github.com/scipy/scipy/
```
And the last one failed unexpectedly.

**Comment by 317070** [comment] 2015-04-12 22:39
I checked and it still doesn't compile (after having a working 0.15.x version installed), both system-wide or in a clean virtualenv.

**Comment by ev-br** [comment] 2015-04-12 22:45
Sorry, I don't have a ready answer: does it compile with a released version of numpy rather than a dev version?

**Comment by 317070** [comment] 2015-04-12 23:38
Same problem with numpy 1.9

**Comment by rgommers** [comment] 2015-04-13 06:05
Hmm, it looked odd to me when reviewing, but it worked and I specifically searching for other left side uses like this in the Scipy code base. And there are, in ``sparse/linalg/dsolve/_superluobject.c``.

**Comment by pv** [comment] 2015-04-13 07:24
The difference here is that the build for sigtools uses numpy_nodepr_api
(superlu module does not) since a35804b0, and PyArray_BASE is not an
lvalue with NPY_NO_DEPRECATED_API.
.
arr->base can be set via PyArray_SetBaseObject, available starting from
Numpy >= 1.7, so needs guarding with `#if NPY_API_VERSION >= 0x00000007`.

**Comment by ewmoore** [comment] 2015-04-13 12:40
I see.  That should be easy enough to fix then.  I guess pip does something different than running `./setup.py install`?  This still builds here against Numpy 1.9.1 using either `./setup.py build_ext -i` or `./setup.py install`.

**Comment by ewmoore** [comment] 2015-04-13 13:28
Should be fixed in #4722.

**Comment by 317070** [comment] 2015-04-13 13:41
./setup.py install
does work fine on my system as well. I wonder what pip is doing differently?

**Comment by pv** [comment] 2015-04-13 13:51
I would imagine this is some mess due use of `setup_requires`.

**Closed** 2015-04-13 19:33 UTC
Labels: Build issues
