### ISSUE TITLE
ENH: Implement Poisson Binomial Distribution

### ISSUE THREAD

**Issue by alifa98** [scipy/scipy#21338] opened 2024-08-07 23:58 UTC
### Is your feature request related to a problem? Please describe.

Yes, currently SciPy does not have an implementation of the Poisson binomial distribution. This distribution is useful for modeling the number of successes in a series of independent Bernoulli trials where each trial has a different probability of success. The absence of this functionality in SciPy limits its use in scenarios where varying success probabilities are essential, such as in quality control, reliability engineering, and epidemiology.

### Describe the solution you'd like.

I would like to see an implementation of the Poisson binomial distribution added to SciPy's stats module. This implementation should include at least:
- Probability mass function (PMF)
- Cumulative distribution function (CDF)
- Mean
- Variance

These functions should be optimized for performance, possibly leveraging numerical methods such as the discrete Fourier transform for efficient computation, especially for large $n$ or dynamic programming.

### Describe alternatives you've considered.

Currently, users have to implement their own solutions or rely on other libraries that might not be as robust or widely adopted as SciPy. Some possible alternatives include:

- Custom implementations using recursive methods or Fourier transforms.
- Using approximations like the normal distribution for large $n$ or the Poisson distribution for small $p_i$.

However, these alternatives either require substantial effort to implement correctly or do not provide the exact distribution, leading to potential inaccuracies.

### Additional context (e.g. screenshots, GIFs)

There is a library for this in R, called [poibin](https://cran.r-project.org/package=poibin). There's also one for Python, [poibin-python](https://github.com/tsakim/poibin), but based on my testing, the Python library is outdated and not very accurate. :(

Here is an example of usage/interface for expected implementation:

```python
import numpy as np
from scipy.stats import poisson_binomial

# Probabilities of success for each trial
probabilities = [0.1, 0.2, 0.3, 0.4, 0.5]

# Create a Poisson binomial distribution
pb_dist = poisson_binomial(probabilities)

# Probability mass function for k successes
pmf = pb_dist.pmf(k)

# Cumulative distribution function for k successes
cdf = pb_dist.cdf(k)

# Mean and variance
mean = pb_dist.mean()
variance = pb_dist.var()
```

Here is the wikipedia page: https://en.wikipedia.org/wiki/Poisson_binomial_distribution

Regards,
Ali

**Comment by mdhaber** [comment] 2024-08-08 00:30
Closing as duplicate of gh-6000.

**Closed by mdhaber** 2024-08-08 00:30 UTC
Labels: scipy.stats, enhancement
