### ISSUE TITLE
odeint returning NaN

### ISSUE THREAD

**Issue by hasancicekk** [scipy/scipy#13570] opened 2021-02-16 09:49 UTC
```python
import matplotlib.pyplot as plt
import numpy as np
import scipy.integrate as sc

v0=0
h0=0
y0=[0,0]
v=[0]
h=[0]


def x_dot_dot(u,t,r,T,Cd,A,m,g):
    
    v0=y0[0]
    x_dot,x=u
    return [(T-0.5*r*Cd*A*v0**2-m*g)/m,x_dot]


t=np.arange(0,100)
for i in range(1,100):
    if i<=4:
        T=1000
    else:
        T=0
    r=1.2
    Cd=0.5
    m=15
    g=9.81
    A=np.pi*0.126**2/4

  
    sol=sc.odeint(x_dot_dot,y0,t,args=(r,T,Cd,A,m,g))
    
    v.append(sol[1][0])
    h.append(sol[1][1])
    y0=sol[1]
#print(sol[0])
#print(sol[1])
#print(sol[2])
print(sol)
plt.figure(figsize=(18,5))

ax1=plt.subplot(1,3,1)
plt.plot(t,h)
plt.xlabel('t')
plt.ylabel('h')

ax2=plt.subplot(1,3,2)
plt.plot(t,v)
plt.xlabel('t')
plt.ylabel('v')

ax3=plt.subplot(1,3,3)
plt.plot(h,v)
plt.xlabel('x')
plt.ylabel('v')

plt.show()
```

**Comment by tupui** [comment] 2021-02-17 08:01
Hi, I am Not sure there is a bug here. 

If you try just the first 50 iterations, you will see that this is going to diverge.

I might be wrong, but It looks more like a support question and you would have better luck asking on StackOverflow. I am closing for now. If you have more evidence that this is indeed a bug, feel free to re-open and give more details.

**Closed by tupui** 2021-02-17 08:01 UTC

**Comment by hasancicekk** [comment] 2021-02-17 08:06
> Hi, I am Not sure there is a bug here.
> 
> If you try just the first 50 iterations, you will see that your script is working but this is going to diverge.
> 
> I might be wrong, but It looks more like a support question and you would have better luck asking on StackOverflow. I am closing for now. If you have more evidence that this is indeed a bug, feel free to re-open and give more details.

I am getting erreo like this

Traceback (most recent call last):
  File "e:/dhfgnfg/Python/rocket_3dof.py", line 68, in <module>
    states=odeint(equ_of_motions,states0,t,args=(m,g,T,r,Cd,A))
  File "C:\Users\Casper\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\integrate\odepack.py", line 244, in odeint
    int(bool(tfirst)))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

**Comment by tupui** [comment] 2021-02-17 08:09
You have this at the very first iteration? Are you running just this or something else is calling this file?

**Comment by hasancicekk** [comment] 2021-02-17 08:13
> You have this at the very first iteration? Are you running just this or something else is calling this file?

No,I am just running this file.There is no something else.

**Comment by tupui** [comment] 2021-02-17 08:18
I am sorry but I cannot reproduce your issue with what you provided. I would suggest you print the values of all the parameters so that you can tell us exactly what is going inside the function and makes it crash.
