### ISSUE TITLE
BUG: interpolate: `RecursionError` when importing `BSpline`

### ISSUE THREAD

**Issue by BartSchuurmans** [scipy/scipy#21072] opened 2024-06-28 10:31 UTC
### Describe your issue.

In my code, I import `sklearn.neighbors`. During this import, scipy.stats is imported, which causes a `RecursionError` (only on my production system, not locally)

### Reproducing Code Example

```python
from sklearn.neighbors import KernelDensity
```

### Error message

```shell
RecursionError: maximum recursion depth exceeded
Traceback:
<snipped>
File "/usr/local/lib/python3.12/site-packages/redacted.py", line 9, in <module>
    from sklearn.neighbors import KernelDensity
File "/usr/local/lib/python3.12/site-packages/sklearn/__init__.py", line 96, in <module>
    from .base import clone
File "/usr/local/lib/python3.12/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr
File "/usr/local/lib/python3.12/site-packages/sklearn/utils/__init__.py", line 13, in <module>
    from ._chunking import gen_batches, gen_even_slices
File "/usr/local/lib/python3.12/site-packages/sklearn/utils/_chunking.py", line 8, in <module>
    from ._param_validation import Interval, validate_params
File "/usr/local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 14, in <module>
    from .validation import _is_arraylike_not_scalar
File "/usr/local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 29, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
File "/usr/local/lib/python3.12/site-packages/sklearn/utils/_array_api.py", line 11, in <module>
    from .fixes import parse_version
File "/usr/local/lib/python3.12/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
File "/usr/local/lib/python3.12/site-packages/scipy/stats/__init__.py", line 610, in <module>
    from ._stats_py import *
File "/usr/local/lib/python3.12/site-packages/scipy/stats/_stats_py.py", line 49, in <module>
    from . import distributions
File "/usr/local/lib/python3.12/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
File "/usr/local/lib/python3.12/site-packages/scipy/stats/_continuous_distns.py", line 12, in <module>
    from scipy.interpolate import BSpline
File "/usr/local/lib/python3.12/site-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *
File "/usr/local/lib/python3.12/site-packages/scipy/interpolate/_interpolate.py", line 12, in <module>
    from . import _fitpack_py
File "/usr/local/lib/python3.12/site-packages/scipy/interpolate/_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/scipy/interpolate/_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
            ^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
<snipped>
```

### SciPy/NumPy/Python version and system information

```shell
scipy version: 1.14.0

numpy version: 1.26.4

python version: sys.version_info(major=3, minor=12, micro=4, releaselevel='final', serial=0)

{'Compilers': {'c': {'name': 'gcc', 'linker': 'ld.bfd', 'version': '10.2.1', 'commands': 'cc'}, 'cython': {'name': 'cython', 'linker': 'cython', 'version': '3.0.10', 'commands': 'cython'}, 'c++': {'name': 'gcc', 'linker': 'ld.bfd', 'version': '10.2.1', 'commands': 'c++'}, 'fortran': {'name': 'gcc', 'linker': 'ld.bfd', 'version': '10.2.1', 'commands': 'gfortran'}, 'pythran': {'version': '0.16.1', 'include directory': '../../tmp/pip-build-env-ufvy_lvk/overlay/lib/python3.12/site-packages/pythran'}}, 'Machine Information': {'host': {'cpu': 'x86_64', 'family': 'x86_64', 'endian': 'little', 'system': 'linux'}, 'build': {'cpu': 'x86_64', 'family': 'x86_64', 'endian': 'little', 'system': 'linux'}, 'cross-compiled': False}, 'Build Dependencies': {'blas': {'name': 'scipy-openblas', 'found': True, 'version': '0.3.27.dev', 'detection method': 'pkgconfig', 'include directory': '/opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas32/include', 'lib directory': '/opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas32/lib', 'openblas configuration': 'OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64', 'pc file directory': '/project'}, 'lapack': {'name': 'scipy-openblas', 'found': True, 'version': '0.3.27.dev', 'detection method': 'pkgconfig', 'include directory': '/opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas32/include', 'lib directory': '/opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas32/lib', 'openblas configuration': 'OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64', 'pc file directory': '/project'}, 'pybind11': {'name': 'pybind11', 'version': '2.12.0', 'detection method': 'config-tool', 'include directory': 'unknown'}}, 'Python Information': {'path': '/opt/python/cp312-cp312/bin/python', 'version': '3.12'}}
```

**Comment by lucascolley** [comment] 2024-06-28 11:21
suspiciously similar traceback to gh-21014, although upgrading to SciPy 1.14.0 fixed that issue, so probably different.

**Comment by lucascolley** [comment] 2024-06-28 11:24
the circularity looks like it's coming from NumPy. Let's try to create a more minimal reproducer. @BartSchuurmans could you help try:

- eliminating scikit-learn - can you reproduce with just `from scipy.interpolate import BSpline`?

If that reproduces, we can try to eliminate SciPy too.

**Comment by lucascolley** [comment] 2024-06-28 11:26
Could you also try upgrading NumPy to 2.0?

**Comment by BartSchuurmans** [comment] 2024-06-28 11:57
`from scipy.interpolate import BSpline` results in the same error.
I will now try upgrading NumPy, although I believe my application itself is not compatible with 2.0.
Thanks for your quick response!

**Comment by lucascolley** [comment] 2024-06-28 12:19
to eliminate SciPy, we want to figure out which dtype `dfitpack_int` is on your production machine, and try to reproduce the error with `np.array([], the_dtype`).

**Comment by BartSchuurmans** [comment] 2024-06-28 14:33
NumPy 2.0.0 also fixes this bug (but I unfortunately cannot upgrade yet due to a Pyomo incompatibility)

**Comment by lucascolley** [comment] 2024-06-28 14:36
okay, let's assume that the answer is just a bug in NumPy which is now fixed 👍

**Closed by lucascolley** 2024-06-28 14:36 UTC
Labels: defect, scipy.interpolate, upstream bug

**Comment by BartSchuurmans** [comment] 2024-06-28 17:00
I've been trying to figure out the underlying type of `dfitpack_int`, but I don't think I can access `scipy.interpolate._dfitpack.types.intvar.dtype` without running `__init__` of `scipy.interpolate`, which causes the RecursionError.

On my local machine, which runs without issue, the value is this:
```
<class 'numpy.dtypes.Int32DType'>
int32
```

**Comment by ev-br** [comment] 2024-06-28 19:15
Can you cd into the directory where scipy is installed (somewhere in some site-packages) and import dfitpack directly?

**Comment by BartSchuurmans** [comment] 2024-06-29 16:06
I took some juggling because I don't have shell access to the production server, but:

```python
import _dfitpack

print(type(_dfitpack.types.intvar.dtype))
print(_dfitpack.types.intvar.dtype)
```

Local:
```
<class 'numpy.dtypes.Int32DType'>
int32
```

Production:
```
<class 'numpy.dtypes.Int32DType'>
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 42, in __str__
    return dtype.name
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 362, in _name_get
    if _name_includes_bit_suffix(dtype):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 339, in _name_includes_bit_suffix
    elif np.issubdtype(dtype, np.flexible) and _isunsized(dtype):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^

<snip>

  File "/usr/local/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/numpy/core/_dtype.py", line 104, in _scalar_str
    byteorder = _byte_order_str(dtype)
                ^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

So it's supposedly the same dtype, but printing it is impossible on production.

**Comment by ev-br** [comment] 2024-06-30 08:58
So a numpy 1.26 issue indeed. Thank you for digging through, and hopefully it will get fixed upstream.

**Comment by hosford42** [comment] 2024-07-28 02:29
Oh wow, same infinite recursion upon trying to import freshly installed sklearn in a brand new virtual environment. Glad I found this clue!
