### ISSUE TITLE
BUG: support for Matlab 7.3 SET files

### ISSUE THREAD

**Issue by cmadjar** [scipy/scipy#17509] opened 2022-11-28 21:59 UTC
### Describe your issue.

We are running into issues reading and writing SET files that were created with Matlab 7.3 (using the HDF5 format). We were wondering whether there was a plan to support more recent versions of Matlab and the HDF5 format for electrophysiological recordings. 

Here is part of a traceback we get when running scipy on such files:
```
  File "/opt/loris/bin/mri/python/lib/utilities.py", line 177, in update_set_file_path_info
    dataset = scipy.io.loadmat(set_file)
  File "/opt/loris/bin/mri/python_virtualenvs/loris-mri-python/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/opt/loris/bin/mri/python_virtualenvs/loris-mri-python/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 80, in mat_reader_factory
    raise NotImplementedError('Please use HDF reader for matlab v7.3 files')
NotImplementedError: Please use HDF reader for matlab v7.3 files
```

Could you kindly let us know if that is on your roadmap and if it is, when approximately do you expect to have the fix out?

Thank you very much in advance for your feedback. Best,

### Reproducing Code Example

```python
dataset = scipy.io.loadmat(set_file)
```
```


### Error message

```shell
File "/opt/loris/bin/mri/python/lib/utilities.py", line 177, in update_set_file_path_info
    dataset = scipy.io.loadmat(set_file)
  File "/opt/loris/bin/mri/python_virtualenvs/loris-mri-python/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/opt/loris/bin/mri/python_virtualenvs/loris-mri-python/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 80, in mat_reader_factory
    raise NotImplementedError('Please use HDF reader for matlab v7.3 files')
NotImplementedError: Please use HDF reader for matlab v7.3 files
```
```


### SciPy/NumPy/Python version information

1.9.3

**Comment by j-bowhay** [comment] 2022-11-28 23:21
closing as a duplicate of #11351

In the mean time maybe try http://www.h5py.org/ or https://github.com/skjerns/mat7.3

**Closed by j-bowhay** 2022-11-28 23:21 UTC
Labels: enhancement, scipy.io, duplicate
