### ISSUE TITLE
shortest_path fails edge deleting

### ISSUE THREAD

**Issue by shumovskaya** [scipy/scipy#10772] opened 2019-09-05 09:14 UTC
My issue is about ssp.csgraph.shortest_path Function. If you remove an edge (place zero in the adjacency matrix), then the shortest_path function does not provide a correct answer.

#### Reproducing code example:

```python
import scipy.sparse as ssp
import numpy as np

matrix = np.array([
    [0, 1, 0, 0],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [0, 0, 1, 0]
])

sp_matrix = ssp.csr_matrix(matrix)
ssp.csgraph.shortest_path(sp_matrix, unweighted=True, directed=False)
```

#### We observe:

```python
array([[0., 1., 2., 3.],
       [1., 0., 1., 2.],
       [2., 1., 0., 1.],
       [3., 2., 1., 0.]])
```

#### After deleting one edge:

```python
sp_matrix = ssp.csr_matrix(matrix)
sp_matrix[0, 1] = 0
sp_matrix[1, 0] = 0
ssp.csgraph.shortest_path(sp_matrix, unweighted=True, directed=False)
```

#### We observe:

```python
array([[0., 1., 2., 3.],
       [1., 0., 1., 2.],
       [2., 1., 0., 1.],
       [3., 2., 1., 0.]])
```

#### But we should have got the other result. I found that if I convert the matrix to numpy and then to sparse format, then it works well.

```python
ssp.csgraph.shortest_path(sp_matrix.todense(), unweighted=True, directed=False)
```

#### We observe:

```python
array([[ 0., inf, inf, inf],
       [inf,  0.,  1.,  2.],
       [inf,  1.,  0.,  1.],
       [inf,  2.,  1.,  0.]])
```

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
In [ ]:

```

**Comment by rgommers** [comment] 2019-09-06 01:21
Hi @shumovskaya, thanks for the report. This isn't a bug, there's a little subtlety here: setting an element to zero doesn't change the sparsity structure so it's not the same as not having that element at all. This will fix your example:
```
>>> sp_matrix.eliminate_zeros()                                                    
>>> ssp.csgraph.shortest_path(sp_matrix, unweighted=True, directed=False)          
array([[ 0., inf, inf, inf],
       [inf,  0.,  1.,  2.],
       [inf,  1.,  0.,  1.],
       [inf,  2.,  1.,  0.]])
```

It's not a bug, so I'll close the issue.

**Closed by rgommers** 2019-09-06 01:21 UTC
Labels: scipy.sparse.csgraph
