### ISSUE TITLE
Error from compiled Lomb-Scargle

### ISSUE THREAD

**Issue by khider** [scipy/scipy#13812] opened 2021-04-05 20:18 UTC
Error message from Lomb Scargle. Line doesn't exist in the code and running the function from the linked file doesn't result an error. The data files used in the 

#### Reproducing code example:

```
import numpy as np
from scipy import signal

freq= np.genfromtxt('freq.csv',delimiter=',')
freq_angular = 2 * np.pi * freq
data = np.genfromtxt('series.csv',delimiter=',')

psd = signal.lombscargle(data[:,0],data[:,1],freq)
```

#### Error message:

```
Traceback (most recent call last):

  File "<ipython-input-7-9307315b943e>", line 1, in <module>
    psd = signal.lombscargle(data[:,0],data[:,1],freq)

  File "/Users/deborahkhider/opt/anaconda3/envs/pyleoclim/lib/python3.8/site-packages/scipy/signal/spectral.py", line 150, in lombscargle
    pgram = _lombscargle(x, y, freqs)

  File "_spectral.pyx", line 92, in scipy.signal._spectral._lombscargle

ZeroDivisionError: float division
```

#### Scipy/Numpy/Python version information:

There is no line 92 in the mentioned file. And running this function (non compiled) doesn't return the error on the data attached. 

[Archive.zip](https://github.com/scipy/scipy/files/6260423/Archive.zip)

**Comment by jakevdp** [comment] 2021-04-05 20:24
This error will arise if your `freq` array includes a zero entry; here's a short self-contained repro:
```python
import numpy as np
from scipy import signal

freq = np.linspace(0, 10)
x = np.arange(1000)
y = np.random.randn(1000)
psd = signal.lombscargle(x, y, freq)
```
```pytb
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-9-6bf30b20a510> in <module>()
      5 x = np.arange(1000)
      6 y = np.random.randn(1000)
----> 7 signal.lombscargle(x, y, freq)

/usr/local/lib/python3.7/dist-packages/scipy/signal/spectral.py in lombscargle(x, y, freqs, precenter, normalize)
    151         pgram = _lombscargle(x, y - y.mean(), freqs)
    152     else:
--> 153         pgram = _lombscargle(x, y, freqs)
    154 
    155     if normalize:

_spectral.pyx in scipy.signal._spectral._lombscargle()

ZeroDivisionError: float division
```
A workaround is to remove the zero frequency from the computation:
```
signal.lombscargle(x, y, freq[1:])
```
```
array([0.94139363, 1.82734097, 0.199     , 0.42317497, 1.46817019,
       0.74056362, 0.76093447, 2.02765316, 0.85648092, 1.72798817,
       0.72119209, 0.42574166, 1.16009672, 0.472545  , 1.0713406 ,
       0.27964419, 2.40535946, 0.11306119, 2.15427671, 0.3376739 ,
       0.97987302, 0.82628897, 0.03194144, 0.42389891, 2.04300923,
       1.40779985, 0.52263883, 1.81880164, 0.24201322, 0.69182562,
       0.03877762, 0.5175559 , 2.57092647, 1.77161196, 0.22881956,
       1.77675916, 0.97461079, 0.22829129, 0.44507955, 1.54104105,
       0.8356165 , 0.44266347, 0.17102332, 3.46695115, 1.49800155,
       1.20644403, 0.58413279, 0.12025526, 0.01208122])
```

**Comment by khider** [comment] 2021-04-05 23:11
I've seen this before, yes. but in this case, the zero frequency has been removed and I'm still getting the error. 

Line 92 from the error doesn't exist in the code that's linked. And running the scipy.signal._spectral._lombscargle.py manually doesn't create the same error. So not sure what code is actually in use here.

**Comment by jakevdp** [comment] 2021-04-05 23:40
I see, thanks. Perhaps a duplicate of this issue? https://github.com/scipy/scipy/issues/8787

**Comment by jakevdp** [comment] 2021-04-05 23:45
I suspect you have a combination of inputs for which one of the denominator terms here happens to be zero: https://github.com/scipy/scipy/blob/20642e52fb3b158d41e4f7fea0c800ffd42b6955/scipy/signal/_spectral.pyx#L90-L93

I'm not sure what this implies in terms of interpreting periodic analysis with the Lomb-Scargle algorithm.

**Comment by khider** [comment] 2021-04-05 23:48
According to the latest commit: https://github.com/scipy/scipy/blob/master/scipy/signal/_spectral.py These lines don't actually exist. but running the code inside that file manually doesn't generate an error. So really not sure what scipy is actually using.

**Comment by jakevdp** [comment] 2021-04-05 23:52
This is in `_spectral.pyx`, not `_spectral.py`

**Comment by khider** [comment] 2021-04-06 00:03
But the formula is the same between the 2. So not sure why one gives an error and the other doesn't.

**Comment by jakevdp** [comment] 2021-04-06 01:25
True, but one uses C functions and one uses numpy functions, so floating point errors are likely to accumulate differently.

This is likely happening because of some strangeness in your data (for example, are all `x` values identical to floating point precision? That seems to be the issue in #8787) Without a complete reproducible example, it's difficult to say more.

**Comment by khider** [comment] 2021-04-06 19:35
I attached the data to run the code in archive.zip in the first comment. One file contains x/y and the other the frequency vector used. The frequency vector was obtained using the method highlighted in REDFIT.

**Comment by mdhaber** [comment] 2024-10-18 05:25
Using the posted file, I could not reproduce this on Colab in SciPy 1.14 or locally with main, so closing.

**Closed by mdhaber** 2024-10-18 05:25 UTC
Labels: scipy.signal
