### ISSUE TITLE
BUG: ImportError: undefined symbol: ndarray_from_pyobj

### ISSUE THREAD

**Issue by DerWeh** [scipy/scipy#18262] opened 2023-04-08 18:20 UTC
### Describe your issue.

I am trying to run SciPy's test suit to create a pull request, but following the steps in https://scipy.github.io/devdocs/dev/contributor/conda_guide.html
 errors at step 5. `python dev.py test -v`.
The test yields hundreds of errors of the kind 
```
E   ImportError: PATH/scipy/build-install/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/_iterative.cpython-310-x86_64-linux-gnu.so: undefined symbol: ndarray_from_pyobj
```

I added the output to the file: [output.txt](https://github.com/scipy/scipy/files/11183859/output.txt)

### Reproducing Code Example

```python
git submodule update --init
mamba env create -f environment.yml
mamba activate scipy-dev
python dev.py build
python dev.py test -v
```

### Error message

```shell
_ ERROR collecting build-install/lib/python3.10/site-packages/scipy/cluster/tests/test_disjoint_set.py _
ImportError while importing test module 'PATH/scipy/build-install/lib/python3.10/site-packages/scipy/cluster/tests/test_disjoint_set.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
PATH/mambaforge/envs/scipy-dev/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/cluster/__init__.py:27: in <module>
    from . import vq, hierarchy
scipy/cluster/vq.py:72: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:110: in <module>
    from ._kdtree import *
scipy/spatial/_kdtree.py:4: in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
_ckdtree.pyx:10: in init scipy.spatial._ckdtree
    ???
scipy/sparse/__init__.py:289: in <module>
    from . import csgraph
scipy/sparse/csgraph/__init__.py:185: in <module>
    from ._laplacian import laplacian
scipy/sparse/csgraph/_laplacian.py:7: in <module>
    from scipy.sparse.linalg import LinearOperator
scipy/sparse/linalg/__init__.py:120: in <module>
    from ._isolve import *
scipy/sparse/linalg/_isolve/__init__.py:4: in <module>
    from .iterative import *
scipy/sparse/linalg/_isolve/iterative.py:9: in <module>
    from . import _iterative
E   ImportError: PATH/scipy/build-install/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/_iterative.cpython-310-x86_64-linux-gnu.so: undefined symbol: ndarray_from_pyobj
```

### SciPy/NumPy/Python version and system information

```shell
$ python -c "import sys, numpy; print(numpy.__version__, sys.version_info);"

1.24.2 sys.version_info(major=3, minor=10, micro=10, releaselevel='final', serial=0)
```

Addendum: Git SHA: `85e0d3ed4f0d88c97c832251fbc17e3688ab519a`

**Comment by rgommers** [comment] 2023-04-08 20:01
`ndarray_from_pyobj` comes from `numpy.f2py`, but I've never seen an issue with it. @DerWeh do you happen to have a self-built numpy version installed? Or PYTHONPATH set up to point to some numpy build, or another such thing?

**Comment by DerWeh** [comment] 2023-04-09 06:33
Thanks for the hint. Never did any self-building, and `NumPy` seems to be rightly detected as the one installed by `mamba`:

```
$ python -c "import numpy as np; print(np.__file__)"
PATH/mambaforge/envs/scipy-dev/lib/python3.10/site-packages/numpy/__init__.py
```

I have not set `PYTHONPATH`, and `sys.path` evaluates to:
```
$ python -c "import sys; print(sys.path)"
[
    '',
    'PATH/mambaforge/envs/scipy-dev/lib/python310.zip',
    'PATH/mambaforge/envs/scipy-dev/lib/python3.10',
    'PATH/mambaforge/envs/scipy-dev/lib/python3.10/lib-dynload',
    'PATH/mambaforge/envs/scipy-dev/lib/python3.10/site-packages',
    'REPOPATH/scipy'
]
```

Admittedly, I have a plethora of different Python installations, but to me, it seems like everything is cleanly pointing to the `SciPy` environment.
I'll try if a clean micromamba environment would work.

**Comment by DerWeh** [comment] 2023-04-09 12:28
Ok, a fresh installation of `micromamba` works after all.
Took me way too long to figure out that I should run `rm -r build` after changing the environment, maybe a command `python dev.py clean` would be helpful?

**Comment by rgommers** [comment] 2023-04-10 10:17
Ah that makes sense as a cause. I don't think that `python dev.py clean` is helpful though, because there's no way to clean every possible root cause. E.g., you may need `git clean -xdf` and we definitely can't run that automatically from `dev.py` -`setup.py clean` was always unreliable too for similar reasons. 

The better way is to detect potential problems and raise an informative error message, rather than letting an obscure error about missing symbols bubble up. I'm still not 100% clear on how to do that in this case. Can you tell me what the old and new `numpy` and `python` versions in your environment were? If I can reproduce with that, I should be able to improve the error message.

**Comment by rgommers** [comment] 2023-04-24 22:50
`python dev.py` won't re-run when the meson version changes. If that's the same but environment changes, there may be ways to get around this. That's user error though - I'm not quite sure how to prevent it, or even to reproduce this. So I'll close the issue. With a clean reproducer this can be improved perhaps (but not 100% sure about that).

**Closed by rgommers** 2023-04-24 22:50 UTC
Labels: Build issues
