### ISSUE TITLE
cKDTree returns only inf values in case number of data points is smaller than k.

### ISSUE THREAD

**Issue by heistermann** [scipy/scipy#6515] opened 2016-08-24 10:06 UTC
The following behaviour was found in `scipy 0.18.0`. It differs from previous versions. Is this intended?

``` python
>>> from scipy.spatial import cKDTree
>>> import numpy as np
>>> src = np.vstack( (np.array([1, 7]), np.array([5, 4])) ).T
>>> trg = np.vstack( (np.array([1, 10]), np.array([1, 10])) ).T
>>> print(src)
[[1 5]
 [7 4]]
>>> print(trg)
[[ 1  1]
 [10 10]]
>>> tree = cKDTree(src)
>>> dists, ix = tree.query(trg, k=2)
>>> print(dists.round(1))
[[  4.    6.7]
 [  6.7  10.3]]
>>> dists, ix = tree.query(trg, k=3)
>>> print(dists)
[[ inf  inf  inf]
 [ inf  inf  inf]]

```

**Comment by ev-br** [comment] 2016-08-24 21:38
@sturlamolden @rainwoodman thoughts?

**Comment by rainwoodman** [comment] 2016-08-24 22:09
This looks like #6425, fixed in #6431.  Is it possible for @heistermann to check against new master?

**Comment by sturlamolden** [comment] 2016-08-24 22:09
An odd corner case. Raising a ValueError would probably suffice. Also, @rainwoodman recently fixed a very similar problem, so master and 0.18.1 will probably behave differently than 0.18.0. It might not even be an issue we need to fix.

**Comment by rainwoodman** [comment] 2016-08-24 22:13
I thought the API is to return inf in dist and -1 in ix instead of raising ValueError. Maybe adding in a 'mode' argument that takes value of 'raise' or 'cval'? The current behaviour (when there are no bugs) is `cval`.

**Comment by sturlamolden** [comment] 2016-08-24 22:18
Yes, if no points are permissible due to ```distance_upper_bound```. But here ```k``` is bigger than the number of points, which seems more like a ```ValueError``` in my opinion.

**Comment by sturlamolden** [comment] 2016-08-24 22:26
Asking for the third nearest neighbor in a collection of two points feels like an absurdity which could warrant a ValueError, but padding with inf and -1 and letting it pass silent would to too. I don't think we need a keyword to control how this corner case is handled.

**Comment by rainwoodman** [comment] 2016-08-24 22:27
In `cval` mode, even if there are no data points, the query is still defined.
In `raise` mode, whenever a query is not full filled, an exception is raised.

It does feel the raise mode is just one more line,
```
assert all(ix >= 0)
```
so I am in for not adding in an additional argument for this.

**Comment by peterbell10** [comment] 2020-06-24 17:06
I've confirmed the original issue is fixed and the current behaviour is consistent with the `KDTree` result. So, this can be closed. 

As for raising an error, I don't see why we should break the `k > tree.n` case by raising an error. Sure, it would be a weird thing to do intentionally. But I think a more likely scenario would be code that uses a fixed `k` on arbitrary sets of points, in which case this is a valid edge case that should be handled gracefully.

**Closed by peterbell10** 2020-06-24 17:06 UTC
Labels: scipy.spatial
