### ISSUE TITLE
U matrix is always random in scipy.sparse.linalg.svd

### ISSUE THREAD

**Issue by JiteshPshah** [scipy/scipy#7807] opened 2017-08-29 08:11 UTC
How to stop randomized value of U matrix in scipy.sparse.linalg.svd ?
I got random values every time when I run the function .

**Comment by ewmoore** [comment] 2017-08-30 21:41
You're looking for the `v0` parameter.  ARPACK needs a starting vector, which is by default (`v0=None`) selected randomly.  If you use the same initial vector, you should see the same outputs each time.

**Comment by ewmoore** [comment] 2017-08-30 21:42
Closing.  Not a bug.

**Closed by ewmoore** 2017-08-30 21:42 UTC

**Comment by JiteshPshah** [comment] 2017-08-31 05:02
How do I initialize it , can you give any example ?

**Comment by ewmoore** [comment] 2017-08-31 15:32
```
In [1]: import numpy as np

In [2]: from scipy.sparse.linalg import svds

In [3]: a = np.random.randn(5,5)

In [4]: v0 = np.random.randn(5)

In [5]: svds(a, k=2, v0=v0)
Out[5]: 
(array([[-0.58932449,  0.11705767],
        [ 0.50214963,  0.47477022],
        [-0.27012526, -0.49414944],
        [-0.29318024, -0.14666878],
        [ 0.49154866, -0.70370118]]),
 array([ 2.22265497,  3.54900943]),
 array([[-0.64148022, -0.47963019, -0.49945106,  0.32402638, -0.06335257],
        [-0.29929184,  0.85247962, -0.38313886,  0.10962365,  0.15776618]]))

In [6]: svds(a, k=2, v0=v0)
Out[6]: 
(array([[-0.58932449,  0.11705767],
        [ 0.50214963,  0.47477022],
        [-0.27012526, -0.49414944],
        [-0.29318024, -0.14666878],
        [ 0.49154866, -0.70370118]]),
 array([ 2.22265497,  3.54900943]),
 array([[-0.64148022, -0.47963019, -0.49945106,  0.32402638, -0.06335257],
        [-0.29929184,  0.85247962, -0.38313886,  0.10962365,  0.15776618]]))

In [7]: 
```

**Comment by JiteshPshah** [comment] 2017-09-01 05:53
Thanks Buddy....
