### ISSUE TITLE
`scipy.sparse.linalg.eigsh` is non-deterministic and plattform dependent

### ISSUE THREAD

**Issue by GeislerSimon** [scipy/scipy#12494] opened 2020-07-06 05:52 UTC
My issue is about `scipy.sparse.linalg.eigsh`

#### Reproducing code example:

```
import numpy as np
from scipy import sparse as sp
from scipy.sparse.linalg import eigsh

np.random.seed(0)

A = sp.csr_matrix(np.random.rand(100,100) > 0.5)
D = A.sum(-1).A1
D[D == 0] = 1
D = sp.diags(D ** (-1/2))
L = sp.eye(*A.shape) - D @ A @ D
eigsh(L, k=10, which='SM')[0]
```

On my Mac I get different results each execution. E.g.
`([-0.0065401 ,  0.80065443,  0.80663355,  0.81676304,  0.82418536, 0.82525194,  0.82584799,  0.82882288,  0.83281599,  0.8343768 ]`
The results also differ from my Linux machine:
`[-0.01216965,  0.80576331,  0.81269594,  0.81530367,  0.82356752, 0.82470864,  0.82817419,  0.82923541,  0.82930345,  0.83027089]`

I assume this is caused by the use of a random starting vector via `ARPACK` (not via numpy). Setting `v0` manually, at least gives consistent results: 
e.g `eigsh(L, k=10, which='SM', v0=100*[0.1])[0]`
returns `[-0.00491898,  0.8024341 ,  0.81182509,  0.82095066,  0.82200956, 0.82278322,  0.82411053,  0.83036532,  0.83053034,  0.83250892]` on my Mac and Linux machine.

Should we rather use bumpy (e.g. `randn`) for generating `v0`?  However, I don't know how many other methods might be affected. I am happy to submit a pull request, in case you agree and point me to further locations we should fix.

**Comment by GeislerSimon** [comment] 2020-07-06 06:07
Experimenting a little bit more I find that there are still _minor_ differences between MacOS and Linux. `eigsh(L, k=num_clusters, which='SM', return_eigenvectors=True, v0=np.random.randn(L.shape[0]))[0]` results in:
- Linux: `[-1.28811634e-16,  6.59315698e-01,  7.54563514e-01,  7.76094457e-01, 7.92383543e-01,  7.96876377e-01]`
- Mac: `[-6.49680221e-17,  6.59315698e-01,  7.54563514e-01,  7.76094457e-01, 7.92383543e-01,  7.96876377e-01]`

**Comment by pv** [comment] 2020-07-12 10:53
Duplicate of #10374

**Closed by pv** 2020-07-12 10:53 UTC
Labels: scipy.sparse
