### ISSUE TITLE
BUG: regression: eval_chebyt gives wrong results for complex arguments

### ISSUE THREAD

**Issue by oscarbenjamin** [scipy/scipy#20129] opened 2024-02-21 18:16 UTC
### Describe your issue.

The function `eval_chebyt` gives incorrect results for complex arguments.

This is a regression since SciPy 1.12 seen in the SciPy nightly builds. I haven't bisected but this only started showing in SymPy CI in the last few days so it probably comes from something changed during the last week.

I might be missing it but it doesn't look like SciPy has any tests for `eval_chebyt` with complex arguments.

### Reproducing Code Example

```python
In [1]: from scipy.special import eval_chebyt

In [2]: eval_chebyt(7, 2)
Out[2]: np.float64(5042.0)

In [3]: eval_chebyt(7, 2+0j)
Out[3]: np.complex128(4117.78617477417+0j)
```

### Error message

```shell
There is no error message. Just the computed values are completely wrong.
```

### SciPy/NumPy/Python version and system information

```shell
The bug is only seen very recently in the SciPy nightly builds.

With SciPy 1.12 there is no problem:

In [1]: from scipy.special import eval_chebyt

In [2]: eval_chebyt(7, 2)
Out[2]: 5042.0

In [3]: eval_chebyt(7, 2+0j) # scipy 1.12 gets the correct result
Out[3]: (5042+0j)
```

**Comment by lucascolley** [comment] 2024-02-21 18:40
cc @ilayn @steppi

**Comment by steppi** [comment] 2024-02-21 18:48
Yeah, it's just a directly call to `hyp2f1`

https://github.com/scipy/scipy/blob/a6654813680ed4018d04d494d51491dc8842aa18/scipy/special/orthogonal_eval.pxd#L251-L260

`hyp2f1` is probably the best tested function in special, https://github.com/scipy/scipy/blob/main/scipy/special/_precompute/hyp2f1_data.py, and @ilayn's new implementation from https://github.com/scipy/scipy/pull/19824 passed over 3 million test cases, but it looks like this specific situation isn't covered. It shouldn't be too hard to figure out what the issue is. This would also likely be fixed by merging https://github.com/scipy/scipy/pull/20089.

**Comment by steppi** [comment] 2024-02-21 18:51
Hold on. The ufunc `hyp2f1` is mostly written in Cython and only falls back to the Fortran implementation from `specfun` for some situations, but `orthogonal_eval.pxd` just directly uses the Fortran implementation. These cases for the Fortran implementation thus aren't tested and that's why we missed this failure.

This should be able to fix directly by using the Cython `hyp2f1` in `orthogonal_eval.pxd`.

**Comment by oscarbenjamin** [comment] 2024-02-21 19:08
What exactly is it that has caused this to change?

It looks like `othogonal_eval.pxd` has not been changed for some time. That suggests that one of the functions that it calls was previously giving a correct result and is now giving an incorrect result. If that is the case then I would have thought that the first thing to do would be to identify exactly which of those functions has changed and investigate that before considering the use of a different function instead.

Looking at
https://github.com/scipy/scipy/blob/a6654813680ed4018d04d494d51491dc8842aa18/scipy/special/orthogonal_eval.pxd#L47-L53
I would guess that it is `chyp2f1_wrap`.

**Comment by lucascolley** [comment] 2024-02-21 19:13
What has changed is that the Fortran 77 specfun code was rewritten in C - see gh-19824

**Comment by oscarbenjamin** [comment] 2024-02-21 19:23
It looks like there were some changed to `chyp2f1_wrap` and also that `chyp2f1_wrap` is not used anywhere outside of `orthogonal_eval.pxd`.

**Comment by steppi** [comment] 2024-02-21 19:34
> It looks like there were some changes to `chyp2f1_wrap` and also that `chyp2f1_wrap` is not used anywhere outside of `orthogonal_eval.pxd

There were no changes to `chyp2f1_wrap` as far as I'm aware, like @lucascolley said, the function `chyp2f1_wrap` calls was changed. We recently replaced the specfun Fortran library with a C translation here https://github.com/scipy/scipy/pull/19824. The Cython implementation of `hyp2f1` is extensively tested but the Fortran implementation itself was not, which allowed this bug in the Fortran implementation to escape undetected.I consider it an oversight that `orthogonal_eval.pxd` was using the Fortran implementation, because the Cython implementation made considerable improvements. The currently unmerged C++ translation of `hyp2f1`made even further improvements as can be seen in the tables in #20089.

Thanks for bringing this to our attention. I'll submit a fix shortly.

**Comment by oscarbenjamin** [comment] 2024-02-21 19:45
> There were no changes to `chyp2f1_wrap` as far as I'm aware

The code in the function was changed in cd4b295970ec4aa1ce91506848a03d41e945991f. The significant change seems to be that it calls `specfun_hygfz` rather than a Fortran `hygfz` function.

**Closed** 2024-02-21 23:56 UTC
Labels: defect, scipy.special
