### ISSUE TITLE
vectorize expm

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#13943] opened 2021-04-27 09:39 UTC
I would like to compute the matrix exponential of many small matrices at once.  This works, but is slow:
```python
import numpy as np
import scipy.linalg


A = np.random.rand(3, 3, 777)

exp_A = np.array([
    scipy.linalg.expm(dt * W[..., k])
    for k in range(m)
])

scipy.linalg.expm(A)
```
It'd be great of `expm` could be vectorized.

**Comment by ilayn** [comment] 2021-04-27 09:41
Duplicate of #12838

**Comment by ilayn** [comment] 2021-04-27 09:42
Let's continue in the linked one. I guess we need this since more than 3 times this has come up

**Closed by ilayn** 2021-04-27 09:41 UTC

**Comment by nschloe** [comment] 2021-04-27 09:55
Thanks for point that out!
