### ISSUE TITLE
Segfault with LinearNDInterpolator

### ISSUE THREAD

**Issue by julietbravo** [scipy/scipy#11088] opened 2019-11-19 18:06 UTC
`LinearNDInterpolator` results in a segfault, but depending on the system/Scipy version. `1.3.1` on a Linux system works fine, `1.3.2` on MacOS segfaults, without any further information.

#### Reproducing code example:

```
from scipy.interpolate import LinearNDInterpolator
import numpy as np

points = np.array([[ 1.63384076,  0.34794974],
                   [-0.54400365,  0.36948117],
                   [ 1.63165793,  0.38948119]])

values = np.array([-5.28483478, -4.92881225, -2.56240522])

ip = LinearNDInterpolator(points, values)
```

#### Error message:

The only output/"traceback" is:
```
Segmentation fault: 11
```

#### Scipy/Numpy/Python version information:
```
scipy 1.3.2
numpy 1.15.4
Python 3.7.4)
```

**Comment by rgommers** [comment] 2019-11-19 18:18
Hi @julietbravo thanks for the report. How did you install SciPy and Python itself?

**Comment by julietbravo** [comment] 2019-11-19 18:30
Python 3.7 through Homebrew, Scipy using pip3

**Comment by pv** [comment] 2019-11-19 18:32
Does `scipy.spatial.Delaunay(points)` crash for you?  (FWIW, not reproducible here.)

**Comment by julietbravo** [comment] 2019-11-19 18:33
That segfaults as well

**Comment by pv** [comment] 2019-11-19 18:35
Possibly Qhull bug and may be fixed in upcoming 1.4.0. You may want to check if it occurs in the latest prerelease package: https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/

**Comment by rgommers** [comment] 2019-11-19 18:40
Other option (unlikely but not impossible): binary incompatibility because of Homebrew Python. From https://github.com/MacPython/wiki/wiki/Spinning-wheels#question-will-pip-give-me-a-broken-wheel:

_Homebrew and Macports Python have the SDK for the macOS they were first installed / last updated on, and x86_64 architecture only._

And we have wheels incorrectly labelled with the 10.6 SDK (gh-10485)

**Comment by julietbravo** [comment] 2019-11-19 18:50
@pv I tried with `1.4.0.dev0+f999f4b`, but that also results in the same segfault.

**Comment by julietbravo** [comment] 2019-11-19 19:41
I asked a friend to try this on his MacBook, the same installation procedure (Python via Homebrew, Scipy via pip), same Scipy version, and there it works fine. So something is a bit fishy about my Python/packages installation, I'll look further into it.

**Comment by paulf81** [comment] 2019-12-10 20:34
I may be late to this, I posted a similar question on stack and was directed to scipy github.  Has there bee any solution found to this?  I'm observing this same issue for the above code, and also for griddata

**Comment by paulf81** [comment] 2020-01-07 20:42
Wanted to check if this issue is still open?  Is there a recommended workaround?  Thank you!

**Comment by rgommers** [comment] 2020-01-07 21:23
@paulf81 do you have the same combo of Python 3.7 from Homebrew + SciPy 1.3.x/1.4.x installed with `pip`?

If we can't reproduce it's hard to suggest a workaround for that particular Python version. Installing Python with Anaconda/Miniconda or from the python.org installers should fix it.

**Comment by paulf81** [comment] 2020-01-08 18:29
Thank you for this comment.  I must've been using the setup you mention, I set up a new conda environment and this did resolve the issue.  Thank you!

**Comment by tupui** [comment] 2021-08-28 12:08
Latest on macOS doe not segfault. Not sure we should keep this open.

**Comment by rgommers** [comment] 2021-08-30 20:36
Agreed, tried in a couple more setups, all working. Closing.

**Closed by rgommers** 2021-08-30 20:36 UTC
Labels: defect, scipy.interpolate
