### ISSUE TITLE
KDTree.sparse_distance_matrix suggestions

### ISSUE THREAD

**Issue by jjgreen** [scipy/scipy#5563] opened 2015-11-30 23:26 UTC
I was delighted to find the `KDTree` method `sparse_distance_matrix` as I was looking to find all distances between pairs of points closer than a certain distance apart from two large sets of points.  It was only after unexpected results and a certain amount of head-scatching that I realised that this is not what the method does, it returns a sparse matrix of pairs which are a  _positive_ distances less than a certain value, since  the results are stored in a DoK sparse matrix which throws away zero values.  I found a work-around for my problem (essentially re-implementation via `query_ball_tree`), but thought I'd  make the following suggestion
- a kwarg option, `zero` which replaces the zero-distance value in the DoK matrix (if this were present, I could have used a small positive value like `2.2251e-308`), or
- the ability to pass a function to the method, this function to be applied to the distance and the result saved in the DoK matrix

**Comment by perimosocordiae** [comment] 2015-12-01 20:05
I'm not familiar with the KDTree code, but it probably wouldn't be too hard to store the result in a sparse matrix format that allows storing zeros (COO, CSC/CSR, etc). I know that it can be tricky to change sparse formats in public-facing functions, though, as some users may be relying on the result being DOK.

How about we add a keyword argument which controls the output matrix format, which will default to `'dok'` for back-compat? Internally, the matrix would be constructed in COO format (preserving zeros) and converted to the appropriate output format if needed.

**Comment by jjgreen** [comment] 2015-12-03 19:56
That would be even better, it is _so_ depressing that `cKDTree.sparse_distance_matrix` constructs `coo`, with zero distances for co-incident points, and then throws that valuable information away by converting to `dok` for its return value.

**Comment by perimosocordiae** [comment] 2015-12-03 20:49
Actually, it looks like `cKDTree` supports something like what I described as of 11 days ago (PR #4980):
https://github.com/scipy/scipy/blob/master/scipy/spatial/ckdtree.pyx#L1117

Just pass `output_type='coo_matrix'` and you should be good to go. The interface is a little clunky, but it'll get the job done.

Also see issue #2353, which is rather similar to this one. I'll close this issue for now, but if your problem isn't resolved feel free to reopen.

**Closed by perimosocordiae** 2015-12-03 20:49 UTC

**Comment by sturlamolden** [comment] 2015-12-03 21:44
The interface is clunky because we needed to preserve backwards compatibility. The problem is that the default return type (dok) is basically a defect. It truncates all distances above threshold to zero. However to change this defective behavior we need to go through the full deprecation process.

**Comment by jjgreen** [comment] 2015-12-03 21:59
Outstanding! Thanks very much!

**Comment by BrenBarn** [comment] 2015-12-04 06:47
If it is agreed that the existing behavior is a defect, are you going to begin that deprecation process now?

**Comment by sturlamolden** [comment] 2015-12-04 07:21
I am not sure it is agreed, it is just my opinion. The code has been this way since @aarchiba wrote ```scipy.spatial.KDTree```. Only recently has ```cKDTree``` been extended beyond its Python prototype. One thing that occurs to me is that all query functions except ```query``` are special cases of the so-called "range query". They also have different performance, ```query_ball_point``` is by far the faster. It might be better to just write a general range query based on ```query_ball_point``` rather than trying to fix ```sparse_distance_matrix```.  The kd-tree and ball-tree in scikit-learn also have a general range query method (called ```query_radius```) instead of a myriad of special cases.

Currently ```cKDTree.sparse_distance_matrix``` will internally accumulate a C++ ```std::vector<coo_entry>``` with 
```C++
struct coo_entry {
    npy_intp i;
    npy_intp j;
    npy_float64 d;
}
```
You can get a view of this C++ vector (without making a copy) by specifying ```output_type='ndarray'```. It is the raw output from the query method.

**Comment by sturlamolden** [comment] 2015-12-04 07:31
As I see it, returning ```dok_matrix``` would not have been a defect is distances had been returned as ```1/d```. That was truncating to zero would have made sense, and 0 distances would be returned as ```inf```.
