### ISSUE TITLE
linalg.solve test crashes on Windows

### ISSUE THREAD

**Issue by dalito** [scipy/scipy#8064] opened 2017-10-22 00:11 UTC
Running the scipy 1.0.0rc2 tests crashes Python 3.6.3-64bit. 

### Reproducing code example:
```
import scipy
scipy.test(verbose=2)
```

Error message:
```
::TestSolve::test_assume_a_keyword <- ..\..\dev_amd64\Python36\lib\site-packages\scipy\linalg\tests\test_basic.py PASSED
::TestSolve::test_all_type_size_routine_combinations <- ..\..\dev_amd64\Python36\lib\site-packages\scipy\linalg\tests\test_basic.py
<<Python interpreter crashes>>
````

Scipy/Numpy/Python version information:
```
scipy 1.0.0rc2 
numpy 1.13.3 
Python 3.6.3-64bit
Windows 10 Pro
```
Also #7500 reports an error in this test but not an interpreter crash.

**Comment by xoviat** [comment] 2017-10-22 03:53
Is the version that you built yourself or the version that's from pypi?

**Comment by xoviat** [comment] 2017-10-22 03:55
If it's the version that you built yourself you probably built openblas incorrectly and didn't even know it. Try to reproduce using the pypi version.

**Comment by dalito** [comment] 2017-10-22 10:24
The crash happens with both the version from pypi and with my own build.

This morning I tried to reproduce the crash on two other machines. I did not get the segfault (all machines had Python 3.6.3-64bit from python.org, one has Win 7 Pro German the other Win10 Pro German). Both the scipy from pypi and my own build were OK on these two other machines.

On the machine where I observed the segfault, I also completely removed the Python 3.6 installation and reinstalled. The crash is reproducible. When I looked for differeces between the machines, I found out that the installed versions of VC redistributables differ. Maybe this is the cause of the problem.

Since I can reproduce the segfault only on one machine, this issue can probably be closed.

**Comment by pv** [comment] 2017-10-22 10:27
What are the VC redistributable versions, and can you reproduce it on other machines if you downgrade (if that is possible to do)?

**Comment by dalito** [comment] 2017-10-22 10:40
On the machine which segfaults:
![vcredistributables_when-segfaulting_s](https://user-images.githubusercontent.com/2648874/31861058-eb24c384-b725-11e7-9bce-b9b271092d62.png)
There is no VC redistributable from VS2017. I will no update to the latest versions and test again.

**Comment by dalito** [comment] 2017-10-22 11:05
Success. After applying[ Microsoft Visual C++ 2015 Redistributable Update 3 RC](https://www.microsoft.com/en-us/download/details.aspx?id=52685) (to version 14.0.24123) the scipy tests complete fine.
```
import scipy; scipy.test()
(....)
============================ 577 tests deselected =============================
 12057 passed, 1382 skipped, 577 deselected, 74 xfailed, 6 xpassed in 597.50 seconds
True
too many axes: 2 (effrank=2), expected rank=1
too many axes: 2 (effrank=2), expected rank=1
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 3 but got 5
0-th dimension must be fixed to 3 but got 15
```

**Comment by xoviat** [comment] 2017-10-22 16:04
I'm not sure what we can do about this. I thought Windows update was supposed to keep the redistributables updated.

**Comment by ilayn** [comment] 2017-10-22 16:07
I thought we need to have NumPy > 1.13.x for the builds. Can it be related?

**Comment by pv** [comment] 2017-10-22 16:11
Now, is it a bug in that specific version of the CRT, or is there a more general version incompatibility issue?

@ilayn: I don't think so. 1.14 is required only for the numpy.distutils changes.

**Comment by dalito** [comment] 2017-10-22 16:16
It looks like a bug in that specific version of the CRT. People should maybe be warned in the release notes for 1.0.0 to update their CRT. I am not sure if windows update does normally take care of updating the CRTs. Obviously it did not on this machine.

**Comment by xoviat** [comment] 2017-10-22 18:01
What is the action required to close this issue? There is nothing that we can do about this

**Comment by rgommers** [comment] 2017-10-24 04:46
> It looks like a bug in that specific version of the CRT. People should maybe be warned in the release notes for 1.0.0 to update their CRT. I am not sure if windows update does normally take care of updating the CRTs. Obviously it did not on this machine.

That doesn't look like a warning that we'd like to include. Too detailed and probably won't mean much to most users.

**Comment by rgommers** [comment] 2017-10-24 04:53
I do think we should skip the test for the coming release. Seems like that should have happened anyway due to gh-7500 but that fell through the cracks.

**Comment by matthew-brett** [comment] 2017-10-24 08:21
Am I wrong to worry that the same routine that gives a significant test error on Accelerate gives a segfault on Windows, for some versions of the MS CRT?   Is it possible we've got a nasty bug in there?

**Comment by pv** [comment] 2017-10-24 08:31
Doesn't sound so likely --- the Accelerate failure is only about 
precision issues in inverting 1000x1000 float32 matrix. Moreover, the 
test and the code that caused it has been changed since, so it's not 
necessarily the case that it fails on Accelerate any more.

I would be tempted to just ignore issues with a single CRT version...

**Comment by rgommers** [comment] 2017-10-24 08:59
Perhaps not ignore, but just keep an eye on it and see if multiple people run into this in their own code or not.

**Comment by ilayn** [comment] 2017-10-24 14:43
It would be great help if anyone who can replicate the problem can also try to extract at which spin it is causing problems. Is it a segfault or a generic crash ? Usually terminal segfaults include a accompanying message too if they are related to LAPACK issues.

**Comment by rgommers** [comment] 2017-10-24 19:57
Skipping this test for 1.0.0 (see gh-8071). Marked for 1.1.0 to either resolve or skip on some platforms permanently.

**Comment by cgohlke** [comment] 2018-01-03 19:28
I am unable to reproduce this issue with official binaries:

Windows 10 Pro
VC140.CRT 14.0.24210.0
Python-3.6.3-amd64
numpy-1.13.3
scipy-1.0.0rc2

I verified that CRT 14.0.24210.0 is used.

However, when enabling page heap verification for the python process during `test_basic.py::TestPinvSymmetric::test_simple_complex`, there's a segfault in `libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll`. This crash is not dependent on the VC140 CRT.

To enable page heap verification:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\python.exe]
"GlobalFlag"="0x02000000"
"VerifierFlags"=dword:00000001
"PageHeapFlags"="0x3"
```

**Comment by xoviat** [comment] 2018-01-03 19:52
OpenBLAS issues will be resolved after we (NVIDIA, ARM, some other contributors, and myself) track down and resolve all of the remaining issues with flang (fortran compiler). However, if we can't reproduce the issue then should it be closed?

**Comment by pv** [comment] 2018-01-03 21:36
how can flang resolve openblas bugs? those are not unlikely due to bugs in
the kernels written in c/asm?

3.1.2018 20.53 "xoviat" <notifications@github.com> kirjoitti:

**Comment by pv** [comment] 2018-01-03 21:39
iow so far there are no known issues arising from the gfortran/msvc mix,
and no plausible theoretical issues are identified either, right?

3.1.2018 22.36 "Pauli Virtanen" <pav@iki.fi> kirjoitti:

how can flang resolve openblas bugs? those are not unlikely due to bugs in
the kernels written in c/asm?

3.1.2018 20.53 "xoviat" <notifications@github.com> kirjoitti:

**Comment by rgommers** [comment] 2018-03-31 02:11
Not sure what's best for the next release here. Permanently skip the test?

**Comment by matthew-brett** [comment] 2018-03-31 09:28
Can I check? - there are two different crashes here:

1) Crash in `TestSolve::test_all_type_size_routine_combinations` with MSVC 2015 RT 14.0.24210
2) Crash in `test_basic.py::TestPinvSymmetric::test_simple_complex` with page heap verification enabled.

We decided there was nothing to do about the first one.  Did we have a decision about the second?

**Comment by ilayn** [comment] 2018-03-31 09:40
Especially after #8520, if linalg.solve test is still crashing, it is more likely to be a problem of that platform rather than scipy code.

**Comment by pv** [comment] 2018-04-12 21:06
Going to skip the test also for 1.1.x.

**Comment by tylerjereddy** [comment] 2018-11-06 04:06
Are we going to keep cherry-picking this test skip in to maintenance branches or perhaps we should just accept that we need skip now & commit to master?

**Closed** 2018-11-07 03:29 UTC
Labels: defect, needs-decision, scipy.linalg
