### ISSUE TITLE
BUG: `DifferentialEvolution` test failure on OpenSuse/tumbleweed aarch64

### ISSUE THREAD

**Issue by ggardet** [scipy/scipy#21475] opened 2024-08-29 12:07 UTC
### Describe your issue.

[  360s] =========================== short test summary info ============================
[  360s] FAILED optimize/tests/test__differential_evolution.py::TestDifferentialEvolutionSolver::test_L4
[  360s] FAILED linalg/tests/test_basic.py::TestLstsq::test_random_exact[True-gelsd-200-float32]
[  360s] FAILED linalg/tests/test_basic.py::TestLstsq::test_random_exact[True-None-200-float32]
[  360s] FAILED linalg/tests/test_basic.py::TestLstsq::test_random_exact[False-gelsd-200-float32]
[  360s] FAILED linalg/tests/test_basic.py::TestLstsq::test_random_exact[False-None-200-float32]
[  360s] FAILED linalg/tests/test_basic.py::TestLstsq::test_random_complex_exact[True-gelsd-200-complex64]
[  360s] FAILED linalg/tests/test_basic.py::TestLstsq::test_random_complex_exact[True-None-200-complex64]
[  360s] FAILED linalg/tests/test_basic.py::TestLstsq::test_random_complex_exact[False-gelsd-200-complex64]
[  360s] FAILED linalg/tests/test_basic.py::TestLstsq::test_random_complex_exact[False-None-200-complex64]
[  360s] FAILED sparse/linalg/_eigen/tests/test_svds.py::Test_SVDS_PROPACK::test_small_sigma_sparse[float32-shape1]
[  360s] = 10 failed, 49558 passed, 2220 skipped, 159 xfailed, 11 xpassed in 322.18s (0:05:22) =

### Reproducing Code Example

```python
Build and test on openSUSE Tumbleweed aarch64
```

### Error message

Error message is too long to be copied/pasted here. So, please see: https://paste.opensuse.org/pastes/a0777d295fec

### SciPy/NumPy/Python version and system information

```shell
SciPy: 1.14.0
Numpy: 1.26.4
Python: 3.10
```

**Comment by andyfaff** [comment] 2024-08-29 21:51
Did you install from wheels? What is the output of `scipy.show_config()`?

**Comment by tylerjereddy** [comment] 2024-08-29 22:09
FWIW, on G-H `aarch64` `SUSE Linux Enterprise Server 15 SP5` with `CC=gcc-12 CXX=g++-12 FC=gfortran-12 python dev.py test -j 32` as my incantation the full test suite passes on latest SciPy `main` (149f9fd32a) at the time of writing, alongside an OpenBLAS from `spack`: `openblas@0.3.27~bignuma~consistent_fpcsr+dynamic_dispatch+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none`

**Comment by andyfaff** [comment] 2024-08-30 02:42
Assuming that you didn't install from wheels, where did you get your BLAS from?

Many of the developers here (well at least me) will try to reproduce this by firing up a docker container. It would help if the instructions to reproduce would include all info to reproduce the issue from a clean docker container.

e.g. I had to find out that the OpenSUSE package manager was called zypper, search for how to install python, search for how to install all other build tools, etc.

I can't repeat these test fails using `opensuse/tumbleweed`, installing `python3` (which corresponds to python3.11), pip installing scipy and running the tests.

**Comment by ggardet** [comment] 2024-09-02 09:37
`blas 3.12.0` and `openblas 0.3.27` are both from openSUSE Tumbleweed aarch64.

The automated build log is available at: https://build.opensuse.org/package/live_build_log/openSUSE:Factory:ARM/python-scipy:test/standard/aarch64

**Comment by andyfaff** [comment] 2024-09-02 09:46
I use `docker run -it -v $PWD:/src opensuse/tumbleweed`, then:

```
zypper update
zypper install openblas
```

results in:

> Loading repository data...
Reading installed packages...
'openblas' not found in package names. Trying capabilities.
No provider of 'openblas' found.

So saying that openblas is available is not true, it must be a different package name. What are the exact commands I have to issue to get to the same point that you do?

**Comment by ggardet** [comment] 2024-10-07 08:58
You likely want `zypper in openblas-common-devel`.

**Comment by ggardet** [comment] 2024-10-07 08:58
Current error is limited to `TestDifferentialEvolutionSolver.test_L4`:
```
[  261s] =================================== FAILURES ===================================
[  261s] ___________________ TestDifferentialEvolutionSolver.test_L4 ____________________
[  261s] [gw0] linux -- Python 3.10.15 /usr/bin/python3.10
[  261s] 
[  261s] self = <scipy.optimize.tests.test__differential_evolution.TestDifferentialEvolutionSolver object at 0xffff96acf730>
[  261s] 
[  261s]     @pytest.mark.fail_slow(5)
[  261s]     def test_L4(self):
[  261s]         # Lampinen ([5]) test problem 4
[  261s]         def f(x):
[  261s]             return np.sum(x[:3])
[  261s]     
[  261s]         A = np.zeros((4, 9))
[  261s]         A[1, [4, 6]] = 0.0025, 0.0025
[  261s]         A[2, [5, 7, 4]] = 0.0025, 0.0025, -0.0025
[  261s]         A[3, [8, 5]] = 0.01, -0.01
[  261s]         A = A[1:, 1:]
[  261s]         b = np.array([1, 1, 1])
[  261s]     
[  261s]         def c1(x):
[  261s]             x = np.hstack(([0], x))  # 1-indexed to match reference
[  261s]             return [x[1]*x[6] - 833.33252*x[4] - 100*x[1] + 83333.333,
[  261s]                     x[2]*x[7] - 1250*x[5] - x[2]*x[4] + 1250*x[4],
[  261s]                     x[3]*x[8] - 1250000 - x[3]*x[5] + 2500*x[5]]
[  261s]     
[  261s]         L = LinearConstraint(A, -np.inf, 1)
[  261s]         N = NonlinearConstraint(c1, 0, np.inf)
[  261s]     
[  261s]         bounds = [(100, 10000)] + [(1000, 10000)]*2 + [(10, 1000)]*5
[  261s]         constraints = (L, N)
[  261s]     
[  261s]         with suppress_warnings() as sup:
[  261s]             sup.filter(UserWarning)
[  261s]             res = differential_evolution(
[  261s]                 f, bounds, strategy='best1bin', seed=1234,
[  261s]                 constraints=constraints, popsize=3, tol=0.05
[  261s]             )
[  261s]     
[  261s]         f_opt = 7049.248
[  261s]     
[  261s]         x_opt = [579.306692, 1359.97063, 5109.9707, 182.0177, 295.601172,
[  261s]                 217.9823, 286.416528, 395.601172]
[  261s]     
[  261s]         assert_allclose(f(x_opt), f_opt, atol=0.001)
[  261s]         assert_allclose(res.fun, f_opt, atol=0.001)
[  261s]     
[  261s]         # use higher tol here for 32-bit Windows, see gh-11693
[  261s]         if (platform.system() == 'Windows' and np.dtype(np.intp).itemsize < 8):
[  261s]             assert_allclose(res.x, x_opt, rtol=2.4e-6, atol=0.0035)
[  261s]         else:
[  261s]             # tolerance determined from macOS + MKL failure, see gh-12701
[  261s] >           assert_allclose(res.x, x_opt, rtol=5e-6, atol=0.0024)
[  261s] 
[  261s] A          = array([[ 0.    ,  0.    ,  0.    ,  0.0025,  0.    ,  0.0025,  0.    ,
[  261s]          0.    ],
[  261s]        [ 0.    ,  0.    ,  0.... ,  0.0025,
[  261s]          0.    ],
[  261s]        [ 0.    ,  0.    ,  0.    ,  0.    , -0.01  ,  0.    ,  0.    ,
[  261s]          0.01  ]])
[  261s] L          = <scipy.optimize._constraints.LinearConstraint object at 0xffff88738c70>
[  261s] N          = <scipy.optimize._constraints.NonlinearConstraint object at 0xffff88738e50>
[  261s] b          = array([1, 1, 1])
[  261s] bounds     = [(100, 10000), (1000, 10000), (1000, 10000), (10, 1000), (10, 1000), (10, 1000), ...]
[  261s] c1         = <function TestDifferentialEvolutionSolver.test_L4.<locals>.c1 at 0xffff888f67a0>
[  261s] constraints = (<scipy.optimize._constraints.LinearConstraint object at 0xffff88738c70>, <scipy.optimize._constraints.NonlinearConstraint object at 0xffff88738e50>)
[  261s] f          = <function TestDifferentialEvolutionSolver.test_L4.<locals>.f at 0xffff888f7370>
[  261s] f_opt      = 7049.248
[  261s] res        =              message: Optimization terminated successfully.
[  261s]              success: True
[  261s]                  fun: 7049.2480...0],
[  261s]                              [ 0.000e+00,  0.000e+00, ...,  0.000e+00,
[  261s]                                1.000e+00]])]
[  261s] self       = <scipy.optimize.tests.test__differential_evolution.TestDifferentialEvolutionSolver object at 0xffff96acf730>
[  261s] sup        = <numpy.testing._private.utils.suppress_warnings object at 0xffff887396c0>
[  261s] x_opt      = [579.306692, 1359.97063, 5109.9707, 182.0177, 295.601172, 217.9823, ...]
[  261s] 
[  261s] /usr/lib64/python3.10/site-packages/scipy/optimize/tests/test__differential_evolution.py:1255: 
[  261s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  261s] 
[  261s] args = (<function assert_allclose.<locals>.compare at 0xffff888f70a0>, array([ 579.29921775, 1359.97690891, 5109.97189848,  1...array([ 579.306692, 1359.97063 , 5109.9707  ,  182.0177  ,  295.601172,
[  261s]         217.9823  ,  286.416528,  395.601172]))
[  261s] kwds = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=5e-06, atol=0.0024', 'strict': False, ...}
[  261s] 
[  261s]     @wraps(func)
[  261s]     def inner(*args, **kwds):
[  261s]         with self._recreate_cm():
[  261s] >           return func(*args, **kwds)
[  261s] E           AssertionError: 
[  261s] E           Not equal to tolerance rtol=5e-06, atol=0.0024
[  261s] E           
[  261s] E           Mismatched elements: 1 / 8 (12.5%)
[  261s] E           Max absolute difference among violations: 0.00747425
[  261s] E           Max relative difference among violations: 1.29020583e-05
[  261s] E            ACTUAL: array([ 579.299218, 1359.976909, 5109.971898,  182.017076,  295.601124,
[  261s] E                   217.982924,  286.415952,  395.601124])
[  261s] E            DESIRED: array([ 579.306692, 1359.97063 , 5109.9707  ,  182.0177  ,  295.601172,
[  261s] E                   217.9823  ,  286.416528,  395.601172])
[  261s] 
[  261s] args       = (<function assert_allclose.<locals>.compare at 0xffff888f70a0>, array([ 579.29921775, 1359.97690891, 5109.97189848,  1...array([ 579.306692, 1359.97063 , 5109.9707  ,  182.0177  ,  295.601172,
[  261s]         217.9823  ,  286.416528,  395.601172]))
[  261s] func       = <function assert_array_compare at 0xffffa5fb6200>
[  261s] kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=5e-06, atol=0.0024', 'strict': False, ...}
[  261s] self       = <contextlib._GeneratorContextManager object at 0xffffa6f929b0>
[  261s] 
[  261s] /usr/lib64/python3.10/contextlib.py:79: AssertionError
[  261s] =========================== short test summary info ============================
[  261s] FAILED optimize/tests/test__differential_evolution.py::TestDifferentialEvolutionSolver::test_L4
[  261s] = 1 failed, 49627 passed, 2222 skipped, 159 xfailed, 11 xpassed in 234.25s (0:03:54) =
```

**Comment by andyfaff** [comment] 2024-10-09 00:36
*Please provide a full list of instructions from an empty docker container (opensuse/tumbleweed), that will allow us to reproduce the problem*.

**Comment by ggardet** [comment] 2024-10-25 12:17
I am able to reproduce, but please note that it depends on aarch64 host! 
* The test **fails** on **AWS M6g.metal**, cpu flags: `fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asi mddp`
* The test **succeeds** on **SolidRun Honeycomb LX2k**, cpu flags: `fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid`

My steps to reproduce (and be as close as possible to the openSUSE build):
```
podman run -dt opensuse/tumbleweed
podman attach <ID>


zypper in numpy-devel openblas-devel patch gcc-c++ gcc-fortran meson python-rpm-macros pkg-config python3-threadpoolctl python3-scipy python3-pythran python3-pytest python3-pytest-xdist python3-pytest-timeout python3-pooch python3-matplotlib python3-hypothesis python3-pybind11-devel python3-pip python3-meson-python python3-devel python3-Cython

curl -O -L https://files.pythonhosted.org/packages/source/s/scipy/scipy-1.14.1.tar.gz
tar xf scipy-1.14.1.tar.gz
cd scipy-1.14.1/
mkdir build

curl -O -L https://github.com/scipy/scipy/pull/21063.patch
patch -p1 < 21063.patch

export 'CFLAGS=-mbranch-protection=standard -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fno-strict-aliasing'
python3 -mpip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build .
python3 -mpip install --verbose --progress-bar off --disable-pip-version-check --root /home/abuild/rpmbuild/BUILDROOT/python-scipy-1.14.1-1.1.aarch64 --no-compile --ignore-installed --no-deps --no-index --find-links ./build --prefix /usr scipy==1.14.1


python3 scipy/datasets/_download_all.py scipy-datasets/scipy-data
export XDG_CACHE_HOME=$PWD/scipy-datasets
mv scipy scipy.dont-import-me
pytest -v --pyargs scipy -n auto -m 'not (slow or xslow )' -k 'not ((TestLinprogIPSpecific and test_solver_select) or test_gh12922 or (TestPeriodogram and test_nd_axis_m1) or (TestPeriodogram and test_nd_axis_0) or (TestPdist and test_pdist_jensenshannon_iris) or (test_rotation and test_align_vectors_single_vector) or (test_lobpcg and test_tolerance_float32) or (test_iterative and test_maxiter_worsening) or (test_resampling and test_bootstrap_alternative) or (TestNoData and test_nodata) or (TestBSR and test_scalar_idx_dtype) or (test_cont_basic and 500-200-ncf-arg74) or (test_lobpcg and test_failure_to_run_iterations))'
```

**Comment by ggardet** [comment] 2024-10-25 14:13
This has been reproduced on Apple M1 inside docker as well. cpu flags: ` fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp flagm2 frint`

**Comment by ggardet** [comment] 2024-10-30 07:39
Building `numpy` with `openblas-devel` instead of `blas-devel` + `lapack-devel` resolves this test problem.

**Comment by ggardet** [comment] 2024-11-04 09:29
> Building `numpy` with `openblas-devel` instead of `blas-devel` + `lapack-devel` resolves this test problem.

Building lapack with `-ffp-contract=off` also fixes the problem.

**Comment by andyfaff** [comment] 2024-11-04 10:46
I think we might close this now. Any adjustments would probably be relaxing of a test tolerance anyway.

**Closed by andyfaff** 2024-11-04 10:46 UTC
Labels: defect, scipy.optimize

**Comment by ggardet** [comment] 2024-11-04 10:48
> I think we might close this now. Any adjustments would probably be relaxing of a test tolerance anyway.

Yes, we can close this one, but not sure if we should relax the tolerance or not.

**Comment by andyfaff** [comment] 2024-11-04 10:50
Leave for the time being.

**Comment by StefanBruens** [comment] 2024-11-04 17:34
I think the `TestDifferentialEvolutionSolver.test_L4` is quite bogus:

- The checked result is after the implicit minimization (`polish=True', default)
- The `minimize` tolerance defaults to 1e-8, but for the result vector, not for its individual components

Instead, polishing should be disabled, and the convergence of the DE algorithm only should be checked.

Pessimizing the computations on some architectures, just to enforce a specific sequence of intermediate values, is the wrong approach. This does not only affect SciPy, but every other application using Lapack.

**Comment by andyfaff** [comment] 2024-11-05 03:01
Thanks for the feedback @StefanBruens. I appreciate where you're coming from.

One difficulty with those constrained tests is that some of them are very slow to run. This is not great when running them in continuous integration. This is why the `popsize` is low. 
The main purpose of the test is to know that DE has found the correct minimum, whilst still obeying the bounds and 
constraints. If polishing is disabled one would have to figure out a different (more relaxed) tolerance criterion.

I have just double checked this locally. The polishing step is not masking the underlying DE having found the wrong solution. The testing asserts all succeed if polishing is turned off, but I did have to increase `popsize` and decrease `tol` to 0.01. 
In the end the polishing makes it easier to figure out if the solve worked, because it's likely to be closer to the known solution.
