### ISSUE TITLE
improve numerical accuracy of the lognorm distribution.

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5940] opened 2016-03-08 11:42 UTC
Reported on http://stackoverflow.com/questions/35862472/scipy-lognormal-cfd-and-sf-give-me-0-most-of-the-time/35866299#35866299

```
In [52]: from scipy.stats import norm, lognorm

In [53]: x2, mu, sigma
Out[53]: (201.68, 195, 0.149)

In [54]: lognorm.sf(x2-mu, s=sigma)
Out[54]: 0.0

In [55]: norm.sf(np.log(x2-mu)/sigma)
Out[55]: 1.6458720667149256e-37
```

`lognorm` only defines `_cdf`. It should grow `_sf`, `_logsf` and `_logcdf`.

**Comment by maniteja123** [comment] 2016-03-08 13:36
Hi, I have a small doubt here. Would the following changes be sufficient to improve or is there a need to explicitly define ``logsf`` and ``logcdf`` ? Thanks.

```
def _sf(self, x, s):
    return _norm_sf(log(x) / s)
```

```
>>>lognorm.sf(x2-mu, s=sigma)
1.6458720667149256e-37
>>>norm.sf(np.log(x2-mu)/sigma)
1.6458720667149256e-37
>>> lognorm.logcdf(x2-mu, s=sigma)
0.0
>>> norm.logcdf(np.log(x2-mu)/sigma)
0.0
>>> lognorm.logsf(x2-mu, s=sigma)
-84.697378065290948
>>> norm.logsf(np.log(x2-mu)/sigma)
-84.697378065290948
```

**Comment by ev-br** [comment] 2016-03-08 14:53
Explicit methods probably won't hurt.

**Comment by maniteja123** [comment] 2016-03-08 18:04
I am not sure why the issue hadn't closed when PR is merged. I suppose it can be closed if the issue is now solved.

**Comment by Eric89GXL** [comment] 2016-03-08 18:53
You needed to say "resolves #" instead of "solves #"

https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues

**Comment by maniteja123** [comment] 2016-03-08 18:54
Oops I forgot. Thanks for reminding !

**Closed by Eric89GXL** 2016-03-08 18:53 UTC
Labels: easy-fix, scipy.stats
