### ISSUE TITLE
Do not use numpy 1.20(conda-forge) if you are setting up a development environment on MacOSX

### ISSUE THREAD

**Issue by charlotte12l** [scipy/scipy#13722] opened 2021-03-22 07:34 UTC
I was setting up  a development environment following the instructions in https://github.com/scipy/scipy/blob/a3762621acffe970fc50471acddb927253821ec5/doc/source/dev/contributor/quickstart_mac.rst. After I successfully built the package , I run the tests and found that I failed one case:

```
===================================== FAILURES =====================================
___________________ TestPareto.test_fit_MLE_comp_optimzer[5-2-1] ___________________
scipy/stats/tests/test_distributions.py:1220: in test_fit_MLE_comp_optimzer
    data = stats.pareto.rvs(size=100, b=rvs_shape, scale=rvs_scale,
        rvs_loc    = 2
        rvs_scale  = 5
        rvs_shape  = 1
        self       = <scipy.stats.tests.test_distributions.TestPareto object at 0x7fbc0d0c5190>
scipy/stats/_distn_infrastructure.py:1083: in rvs
    vals = self._rvs(*args, size=size, random_state=random_state)
        args       = [array(1)]
        cond       = True
        discrete   = None
        kwds       = {'b': 1, 'loc': 2, 'scale': 5, 'size': 100}
        loc        = array(2)
        random_state = RandomState(MT19937) at 0x7FC916407340
        rndm       = None
        scale      = array(5)
        self       = <scipy.stats._continuous_distns.pareto_gen object at 0x7fc91cfba940>
        size       = (100,)
scipy/stats/_distn_infrastructure.py:1002: in _rvs
    Y = self._ppf(U, *args)
        U          = array([0.67187408, 0.57133891, 0.35709936, 0.06427347, 0.70781964,
       0.23479277, 0.78527427, 0.35995472, 0.071321...75, 0.69749849, 0.32637725, 0.30588742, 0.87462436,
       0.86471158, 0.7347657 , 0.2771359 , 0.35753846, 0.27735148])
        args       = (array(1),)
        random_state = RandomState(MT19937) at 0x7FC916407340
        self       = <scipy.stats._continuous_distns.pareto_gen object at 0x7fc91cfba940>
        size       = (100,)
scipy/stats/_continuous_distns.py:6247: in _ppf
    return pow(1-q, -1.0/b)
E   RuntimeWarning: invalid value encountered in reciprocal
        b          = array(1)
        q          = array([0.67187408, 0.57133891, 0.35709936, 0.06427347, 0.70781964,
       0.23479277, 0.78527427, 0.35995472, 0.071321...75, 0.69749849, 0.32637725, 0.30588742, 0.87462436,
       0.86471158, 0.7347657 , 0.2771359 , 0.35753846, 0.27735148])
        self       = <scipy.stats._continuous_distns.pareto_gen object at 0x7fc91cfba940>
============================= short test summary info ==============================
FAILED scipy/stats/tests/test_distributions.py::TestPareto::test_fit_MLE_comp_optimzer[5-2-1]
= 1 failed, 31512 passed, 2070 skipped, 11112 deselected, 91 xfailed, 5 xpassed in 379.08s (0:06:19) =
```

I spent a lot of time debugging and I found this numpy issue:
https://github.com/conda-forge/numpy-feedstock/issues/229

I found that when I installed pythran, it will update my numpy from 1.19(defaults) to 1.20.1(conda-forge) automatically. If I downgraded numpy to 1.19.5 (conda-forge)and rebuild it, I can pass all the tests.

**Comment by rgommers** [comment] 2021-03-25 11:50
Thanks for the report @charlotte12l! That's good detective work, the conda-forge issue indeed looks the same.

> it will update my numpy from 1.19(defaults) to 1.20.1(conda-forge) automatically. If I downgraded numpy to 1.19.5 (conda-forge)and rebuild it, I can pass all the tests.

Glad you solved it for now. If this happens again, you can also just ignore the test failure because it's a harmless one (it won't affect the work you're trying to do).

**Comment by rgommers** [comment] 2021-03-25 12:05
I can reproduce this issue. It's specific to conda-forge, and is unrelated to this `stats` test - `np.ones(120)**-1` gives the same warning, so if we silence it in this test it will just show up somewhere else most likely.

This must be solved in either conda-forge or in numpy, so I'll close this issue.

**Closed by rgommers** 2021-03-25 12:05 UTC
Labels: defect, scipy.stats
