### ISSUE TITLE
curve_fit not fitting properly on non_linear function

### ISSUE THREAD

**Issue by napsternxg** [scipy/scipy#5980] opened 2016-03-17 23:08 UTC
I have used scipy.curve_fit before and was able to fit my data to the following non_linear function. I don't remember the older version number. 

However, now I am trying to fit the curve on the same data and am getting no fit at all. 

There are the details of my function and the code I am using to fit it:

$f(x) = \frac{b}{1 + e^{-(c + dx)}}$

```
import numpy as np
from scipy.optimize import curve_fit

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])
y = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.26899724779580747, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7596293832300737, 1.2214165441700262, 1.044997340851686, 0.7705897033203687, 1.280988851538506, 1.4403870545862594, 1.439644250890874, 1.280013863325763, 0.9349706185969648, 0.7035165962457238, 0.914155421686925])

def func(x, b, c, d): 
    return (b/(1.0+np.exp(-(c+d*x))))

popt, pcov = optimize.curve_fit(func,x,y)
```

For the following function I am getting the following values of `popt` and `pcov`
```
In [58]: popt
Out[58]: array([  1.18051483e-04,  -9.14914194e+00,  -3.28458902e+00])

In [59]: pcov
Out[59]: 
array([[  2.57893572e+21,  -8.19487728e+20,   8.36267888e+16],
       [ -8.19487728e+20,   2.60402046e+20,  -2.65734143e+16],
       [  8.36267888e+16,  -2.65734143e+16,   2.71530926e+12]])

```

Below is the plot of the data and the fitted function. As we can see the fitted function is almost zero. When I use the analytic formula for the derivative of the function I find that the function is decreasing and then becoming constant. Shouldn't this be an increasing function which reaches a maxima near some value and then becomes constant ?

![image](https://cloud.githubusercontent.com/assets/112678/13863717/d32dbc8c-ec69-11e5-801b-25afef151a15.png)

```
$ python -c 'import scipy; print "Scipy=", scipy.__version__; import numpy; print "Numpy=", numpy.__version__;'
Scipy= 0.17.0
Numpy= 1.10.4

```

**Comment by nmayorov** [comment] 2016-03-18 08:46
Hi @napsternxg, it worked for me (gave a good fit) starting from [0.5, 0.5, 0.5], the default starting point is [1, 1, 1] (check it for yourself to be sure). The solution you got is a local minimum (the gradient of the sum of squares is small), but not a useful solution.

I'm not sure why it worked for you earlier (from the default starting point), btw are you sure it did? As far as I can tell nothing was changed for your example, i.e. the starting point is the same, the calling signature of MINPACK's routine is the same.

Do you consider this issue as resolved?

P.S.: Are you aware of `least_squares` routine? It requires a little bit more effort to setup, but gives more flexibility and an option to print optimization progress by iterations (which I find useful a lot of time).

**Comment by ev-br** [comment] 2016-03-21 20:36
OK, seems to be resolved. Closing as not a bug, but feel free to continue discussing. Thanks @napsternxg @nmayorov

**Closed by ev-br** 2016-03-21 20:36 UTC

**Comment by napsternxg** [comment] 2016-03-31 05:20
@nmayorov thanks a lot for the suggestion. I haven't tried least squares, but can you give an example for the least squares method ? Also, what were the values of `popt` and `pcov` which you got when you initialized using `[0.5, 0.5, 0.5]`. This is what I got:

```
[   1.38577 -200.       -12.598  ] [[  8.65596238e+188  -6.24631035e+188   6.18678916e+180]
 [ -6.24631035e+188   4.50745870e+188  -4.46450721e+180]
 [  6.18678909e+180  -4.46450716e+180   1.33561201e+184]]
[1.4403870545862594, -338.0, -26]
[  1.18051483e-04  -9.14914194e+00  -3.28458902e+00] [[  2.57893572e+21  -8.19487728e+20   8.36267888e+16]
 [ -8.19487728e+20   2.60402046e+20  -2.65734143e+16]
 [  8.36267888e+16  -2.65734143e+16   2.71530926e+12]]
/content/smishra8/SOFTWARE/anaconda2/lib/python2.7/site-packages/scipy/optimize/minpack.py:690: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
p0=[0.5, 0.5, 0.5] [   1.10306802 -357.68085207   22.40466715] [[ inf  inf  inf]
 [ inf  inf  inf]
 [ inf  inf  inf]]
testing.py:8: RuntimeWarning: overflow encountered in exp
  return (b/(1.0+np.exp(-(c+d*x))))
p0=[1.4403870545862594, -338.0, -26] [   1.44038705 -338.          -26.        ] [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  inf]]
```

As you can see that the co-variance was infinite. 
Here is my code:

```
import numpy as np
from scipy.optimize import curve_fit

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])
y = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.26899724779580747, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7596293832300737, 1.2214165441700262, 1.044997340851686, 0.7705897033203687, 1.280988851538506, 1.4403870545862594, 1.439644250890874, 1.280013863325763, 0.9349706185969648, 0.7035165962457238, 0.914155421686925])

def func(x, b, c, d):
  return (b/(1.0+np.exp(-(c+d*x))))

popt, pcov = curve_fit(func,x,y, p0=[1.38577 , -200 , -12.598])
print popt, pcov
x_spread = x.max() - x.min()
y_spread = y.max()
x_shift = x.mean()
b_init = y_spread
d_init = -x_spread
c_init = d_init*x_shift

print [b_init, c_init, d_init]

popt, pcov = curve_fit(func,x,y)
print popt, pcov
popt, pcov = curve_fit(func,x,y, p0=[0.5, 0.5, 0.5])
print "p0=%s" % [0.5, 0.5, 0.5], popt, pcov
popt, pcov = curve_fit(func,x,y, p0=[b_init, c_init, d_init])
print "p0=%s" % [b_init, c_init, d_init], popt, pcov

```

**Comment by nmayorov** [comment] 2016-03-31 11:12
Here is what I have:

```
from __future__ import print_function

import numpy as np
from scipy.optimize import curve_fit

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])
y = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.26899724779580747, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.7596293832300737, 1.2214165441700262, 1.044997340851686, 0.7705897033203687, 1.280988851538506, 1.4403870545862594, 1.439644250890874, 1.280013863325763, 0.9349706185969648, 0.7035165962457238, 0.914155421686925])

def func(x, b, c, d):
    return (b/(1.0+np.exp(-(c+d*x))))

popt, pcov = curve_fit(func,x,y, p0=[0.5 , 0.5 , 0.5])

print(popt)
print(pcov)
```

The result:

```
[   1.10306802 -357.68081765   22.404665  ]
[[  2.99445208e-03   6.85591874e+05  -4.28494927e+04]
 [  6.85591917e+05   2.36536619e+16  -1.47835387e+15]
 [ -4.28494962e+04  -1.47835387e+15   9.23971169e+13]]
```

This covariance estimate doesn't look reliable or useful, I suggest to simply ignore it (even if you get infinities).

As for `least_squares`, please read first its docstring and the tutorial for scipy.optimize http://scipy.github.io/devdocs/tutorial/optimize.html
