### ISSUE TITLE
BUG: systematic error in integrate.quad for integration of tails of distributions

### ISSUE THREAD

**Issue by rgutzen** [scipy/scipy#15990] opened 2022-04-14 14:07 UTC
### Describe your issue.

When integrating over the tail of a narrow distribution, e.g. a normal distribution with scale=0.0005, from x to an either finite or infinite integration limit a systematic error occurs between the result of integrate.quad and the true value (determined by the error function). In this example, the shift occurs for x > 0.001. For other values for the scale or the upper integration limit, this value differs but the error persists.
I guess the error is likely due to the algorithm having difficulties with narrow distributions and "small" tails. However, the regime of values in this example is still quite ordinary and far off any precision limits, therefore having at least a warning would be very helpful to not run into unexpected calculation errors.

This issue is probably related to #14101 (although not in a noisy regime), and #10305 (although the wrong values are non-zero).

### Reproducing Code Example

```python
from scipy.stats import norm  # scipy version 1.8.0
from scipy.special import erf
from scipy.integrate import quad
import numpy as np
import matplotlib.pyplot as plt

sigma = 0.0005

x = np.linspace(0, 0.002, 100)

y_quad = [quad(norm.pdf, xi, np.inf, args=(0, sigma))[0] for xi in x]
y_erf = .5 * (1 + erf(-x / (sigma * np.sqrt(2))))

fig, ax = plt.subplots(figsize=(15,5))
ax.plot(x, y_quad, marker='.', linestyle='None', label='quad')
ax.plot(x, y_erf, marker='+', linestyle='None', label='erf')
ax.set_yscale('log')
plt.legend()
```

### Error message

```shell
y_erf - y_quad [x < 0.001] ~= 10e-16
y_erf - y_quad [x > 0.001] ~= 0.02

(no warning or error message)
```

### SciPy/NumPy/Python version information

1.8.0 1.22.2 sys.version_info(major=3, minor=10, micro=0, releaselevel='final', serial=0)

**Comment by tupui** [comment] 2022-04-15 13:15
Hi @rgutzen, thank you for reporting. It's the same issue as before: precision. 

```python
norm.pdf(0.01, loc=0, scale=0.0005)
# 1.1041896724319527e-84
```

I don't think we can do much here.

**Comment by WarrenWeckesser** [comment] 2022-04-15 14:02
You are computing the survival function (also known as the complementary CDF) of the normal distribution, so instead of using `quad`, you can call the `sf()` method of `scipy.stats.norm`.  But let's suppose you have other reasons for using `quad`--maybe this is just a simplified example of a more complicated problem.

`quad` can handle this, but you have to adjust the error tolerances with the parameters `epsabs` and `epsrel`.

For example, here's `quad` with the default tolerances--this result is wrong:
```
In [33]: sigma = 0.0005

In [34]: x0 = 0.0015

In [35]: quad(norm.pdf, x0, np.inf, args=(0, sigma))
Out[35]: (1.4098357723820912e-11, 2.7873365073426358e-11)
``` 
Note that the error estimate is larger than the numerically computed integral!

Here are two ways to compute the same result, so we know what the correct result should be:
```
In [36]: norm.sf(x0, 0, sigma)  # The computed expression is the survival function.
Out[36]: 0.0013498980316300933

In [37]: import mpmath

In [38]: mpmath.mp.dps = 100

In [39]: float(1 - mpmath.ncdf(x0, 0, sigma))  # mpmath provides the CDF of the normal distribution.
Out[39]: 0.0013498980316300946
```
We get a good result from `quad` if we lower `epsabs` significantly:
```
In [49]: quad(norm.pdf, x0, np.inf, args=(0, sigma), epsabs=1e-13)
Out[49]: (0.0013498980316298656, 8.628896393647482e-13)
```

**Comment by tupui** [comment] 2022-04-15 14:22
Thank you @WarrenWeckesser for the precisions. Well this reads like user support and not a bug. At most we can clarify something in the doc. Let's close this for now then.

**Closed by tupui** 2022-04-15 14:22 UTC
Labels: scipy.integrate

**Comment by rgutzen** [comment] 2022-04-15 17:31
Thank you @tupui and @WarrenWeckesser for the explanation to adjust the error tolerances.

Just to note, that it is not just a precision issue as the deviation occurs already for e.g. `x=0.0015` where
```python
norm.pdf(0.0015, loc=0, scale=0.0005)
# 8.863696823876015
```

**Comment by WarrenWeckesser** [comment] 2022-04-16 00:07
@rgutzen, I'm not sure what your last example is supposed to demonstrate.  That is the correct value of the PDF.

**Comment by rgutzen** [comment] 2022-04-16 09:46
Sorry for the confusion. This was just in response to the example of @tupui, using a larger value for `x`.

> Hi @rgutzen, thank you for reporting. It's the same issue as before: precision. Using this scale, over a wide range you have almost only 0. And the algorithm behind `quad` is just not fit for that as indicated in other issues.
> 
> ```python
> norm.pdf(0.01, loc=0, scale=0.0005)
> # 1.1041896724319527e-84
> ```
