### ISSUE TITLE
BUG: `scipy.optimize.shgo` cannot handle constraints that return more than a single value

### ISSUE THREAD

**Issue by lhg1992** [scipy/scipy#18235] opened 2023-04-02 23:19 UTC
### Describe your issue.

"scipy.optimize.shgo" bug in handling multi-dimensional variables.
My obj is a function of a two-dimensional variable. As the error message shows below,  'shgo' seems can't handle (m,) shape variables.
However, even after I have changed "if g(self.x_a, *args) < 0.0:" to  "if any(g(self.x_a, *args) < 0.0):", there is still an error which leads to a failure result with the msg:
'Failed to find a feasible minimizer point. Lowest sampling point = None'

My obj and constraint functions work well with other solvers such as  opt.minimize,  opt.differential_evolution.
Besides, if I reduce the dimension of my variable to a scalar, it also works fine.

### Reproducing Code Example

```python
obj=lambda x: ObjL(np.block([ np.ones([PKzM.shape[0],1])*x[0], 
                             np.ones([PKzM.shape[0],1])*x[1],
                             PKzM ]), # shape: (n,3)
                   PCM, VKM, VCM, rM)

...

res = opt.shgo(obj, bounds, constraints=cons, options={'f_tol':1e-3},
                        callback=print_xk)
```

### Error message

```shell
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py", line 631, in __getitem__
    return self.cache[x]
KeyError: (0, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo.py", line 426, in shgo
    shc.construct_complex()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo.py", line 751, in construct_complex
    self.iterate()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo.py", line 894, in iterate
    self.iterate_complex()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo.py", line 916, in iterate_hypercube
    self.HC = Complex(self.dim, self._raw_func, self.args,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py", line 25, in __init__
    self.n_cube(dim, symmetry=symmetry)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py", line 76, in n_cube
    self.C0.add_vertex(self.V[origintuple])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py", line 635, in __getitem__
    xval = Vertex(x, bounds=self.bounds,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\scipy\optimize\_shgo_lib\triangulation.py", line 552, in __init__
    if g(self.x_a, *args) < 0.0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### SciPy/NumPy/Python version and system information

```shell
scipy version: '1.10.0'
```

**Comment by andyfaff** [comment] 2023-04-03 00:14
In future please provide a minimal working example (MWE) to help debug these kinds of issues. Otherwise a lot of time is taken up trying to reproduce the issue.

Here is a MWE:
```
import numpy as np
from scipy.optimize import minimize, NonlinearConstraint, rosen, shgo
from scipy.optimize._constraints import new_constraint_to_old

# return two values from constraint function
def quad_cube(x):
    return np.sum(x**2), np.sum(x**3)

nlc = NonlinearConstraint(quad_cube, [2.2, 4], [3, 5])
oldc = new_constraint_to_old(nlc, np.array([1.0, 1.0]))

# works
minimize(rosen, np.array([0.1, 0.1]), method='SLSQP', constraints=(nlc,))

# doesn't work
shgo(rosen, [(0, 10), (0, 10)], constraints=oldc)

# expressing constraints in the old-type dict doesn't work either
def constraint(x):
    x = np.asarray(x)
    sqr = np.sum(x**2)
    cube = np.sum(x**3)
    return np.array([sqr - 2.2, 3 - sqr, cube - 4.0, 5.0 - cube])

con = {'type':'ineq', 'fun': constraint}
shgo(rosen, [(0, 10), (0, 10)], constraints=con)
```
The stack trace is:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo_lib/triangulation.py:630, in VertexCache.__getitem__(self, x, indexed)
    629 try:
--> 630     return self.cache[x]
    631 except KeyError:

KeyError: (0, 0)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[44], line 1
----> 1 shgo(rosen, [(0, 10), (0, 10)], constraints=con)

File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo.py:426, in shgo(func, bounds, args, constraints, n, iters, callback, minimizer_kwargs, options, sampling_method)
    420 shc = SHGO(func, bounds, args=args, constraints=constraints, n=n,
    421            iters=iters, callback=callback,
    422            minimizer_kwargs=minimizer_kwargs,
    423            options=options, sampling_method=sampling_method)
    425 # Run the algorithm, process results and test success
--> 426 shc.construct_complex()
    428 if not shc.break_routine:
    429     if shc.disp:

File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo.py:751, in SHGO.construct_complex(self)
    749         break
    750     # Iterate complex, process minimisers
--> 751     self.iterate()
    752     self.stopping_criteria()
    754 # Build minimiser pool
    755 # Final iteration only needed if pools weren't minimised every iteration

File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo.py:894, in SHGO.iterate(self)
    893 def iterate(self):
--> 894     self.iterate_complex()
    896     # Build minimizer pool
    897     if self.minimize_every_iter:

File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo.py:916, in SHGO.iterate_hypercube(self)
    910 # Iterate the complex
    911 if self.n_sampled == 0:
    912     # Initial triangulation of the hyper-rectangle. Note that
    913     # we use `self.raw_func` as `self.func` is a *wrapped* function
    914     # that already takes the original function arguments into
    915     # account.
--> 916     self.HC = Complex(self.dim, self._raw_func, self.args,
    917                       self.symmetry, self.bounds, self.g_cons,
    918                       self.g_args)
    919 else:
    920     self.HC.split_generation()

File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo_lib/triangulation.py:25, in Complex.__init__(self, dim, func, func_args, symmetry, bounds, g_cons, g_args)
     22 self.V = VertexCache(func, func_args, bounds, g_cons, g_args)
     24 # Generate n-cube here:
---> 25 self.n_cube(dim, symmetry=symmetry)
     27 # TODO: Assign functions to a the complex instead
     28 if symmetry:

File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo_lib/triangulation.py:76, in Complex.n_cube(self, dim, symmetry, printout)
     74 else:
     75     self.C0 = Cell(0, 0, origin, supremum)  # Initial cell object
---> 76     self.C0.add_vertex(self.V[origintuple])
     77     self.C0.add_vertex(self.V[supremumtuple])
     79     i_parents = []

File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo_lib/triangulation.py:634, in VertexCache.__getitem__(self, x, indexed)
    632 if indexed:
    633     self.index += 1
--> 634     xval = Vertex(x, bounds=self.bounds,
    635                   func=self.func, func_args=self.func_args,
    636                   g_cons=self.g_cons,
    637                   g_cons_args=self.g_cons_args,
    638                   index=self.index)
    639 else:
    640     xval = Vertex(x, bounds=self.bounds,
    641                   func=self.func, func_args=self.func_args,
    642                   g_cons=self.g_cons,
    643                   g_cons_args=self.g_cons_args)

File ~/miniconda3/envs/dev3/lib/python3.9/site-packages/scipy/optimize/_shgo_lib/triangulation.py:552, in Vertex.__init__(self, x, bounds, func, func_args, g_cons, g_cons_args, nn, index)
    550 if g_cons is not None:
    551     for g, args in zip(g_cons, g_cons_args):
--> 552         if g(self.x_a, *args) < 0.0:
    553             self.f = np.inf
    554             self.feasible = False

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by andyfaff** [comment] 2023-04-03 00:15
Note: `triangulation.py` has been removed in 1.11, so any fix won't be able to be directly backported.

**Comment by andyfaff** [comment] 2023-04-03 00:24
@Stefan-Endres can you recommend a solution for this? Is it as simple as replacing:
```
            if g(v.x_a, *args) < 0.0:
                v.f = np.inf
                v.feasible = False
                break
```
with
```
            if np.any(g(v.x_a, *args)) < 0.0:
                v.f = np.inf
                v.feasible = False
                break
```
?

There are two places to change, https://github.com/scipy/scipy/blob/main/scipy/optimize/_shgo_lib/_vertex.py#L333 and https://github.com/scipy/scipy/blob/main/scipy/optimize/_shgo_lib/_vertex.py#L438

**Comment by lhg1992** [comment] 2023-04-03 00:40
Hi, be careful, it shouldn't be 
```python
if np.any(g(v.x_a, *args)) < 0.0:
...
This statement is always False because "np.any(g(v.x_a, *args))" -> True(1) or False(0) >0.
The correct should be:
```python
if any(g(v.x_a, *args) < 0.0):
...

**Comment by andyfaff** [comment] 2023-04-03 00:46
The test example can be 
```
from scipy.optimize import minimize, NonlinearConstraint, rosen, shgo
from scipy.optimize._constraints import new_constraint_to_old

def quad(x):
    x = np.asarray(x)
    return [np.sum(x**2)]

nlc = NonlinearConstraint(quad, [2.2], [3])
oldc = new_constraint_to_old(nlc, np.array([1.0, 1.0]))
shgo(rosen, [(0, 10), (0, 10)], constraints=oldc)
```

**Comment by andyfaff** [comment] 2023-04-03 00:52
This is a duplicate of #15514

**Closed by andyfaff** 2023-04-03 00:52 UTC
Labels: defect
