### ISSUE TITLE
There's a typo in the documentation of "scipy.optimize.rosen"

### ISSUE THREAD

**Issue by sam1902** [scipy/scipy#9501] opened 2018-11-18 10:54 UTC
https://github.com/scipy/scipy/blob/fcdc3d7b7c1b950d874ac3e890cccde3e2de1c6c/scipy/optimize/optimize.py#L160

Should be 
`sum(100.0*(x[1:] - x[:-1]**2.0)**2.0 + (1 - x[:-1])**2.0 )`

**Comment by ilayn** [comment] 2018-11-18 11:35
@sam1902 thanks for taking the time to report it. Care to send a PR ?

**Comment by sam1902** [comment] 2018-11-18 11:51
https://github.com/scipy/scipy/blob/dbf668065ed784e4dbbbce44db9d436b62f2b556/scipy/optimize/optimize.py#L171

The typo is fixed in `maintenance/1.2.x`
Should I still send a PR ?

**Comment by ilayn** [comment] 2018-11-18 12:10
Oh I thought you were looking at the master branch. Then no, we don't need to modify anything further since 1.2.x is branched out from the current master. I'll find the PR that fixed and mark this as a duplicate. Thanks anyways for your help though.

**Comment by ilayn** [comment] 2018-11-18 12:11
Duplicate of #6161

**Closed by ilayn** 2018-11-18 12:11 UTC
Labels: Documentation, scipy.optimize
