### ISSUE TITLE
CI failing: Travis CI Py36 refguide and Linux_Python_36_32bit_full scipy.{optimize,special}

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#11270] opened 2019-12-24 22:09 UTC
CI testing unexpectedly fails for some recent PRs gh-9719 and gh-11267.

#### Error message:

<s>
* Travis-CI fails building the refguide using Py3.6 with 4 `scipy.sparse` errors involving int64 and longlong such as

```
Expected:    
  <2x3 sparse matrix of type '<class 'numpy.int64'>'      
   with 2 stored elements in Compressed Sparse Column format>
Got:    
  <2x3 sparse matrix of type '<class 'numpy.longlong'>'    	
   with 2 stored elements in Compressed Sparse Column format>
```
</s>

* Linux_Python_36_32bit_full has 11 failures in `scipy.optimize` (`scipy.optimize.tests.test_linprog.TestLinprogIPSparse` and `scipy.optimize.tests.test_trustregion_krylov`) and `scipy.special` (comparing with `mpmath`).
https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=4378&view=logs&j=dca3794b-c3dc-52e6-709a-3545ea017448&t=42f16a10-8379-5482-623d-4749ae3e519a
The 4+7=11 errors are:
```
TestLinprogIPSparsePresolve.test_bug_6139
TestLinprogIPSparse.test_bug_6139
TestKrylovQuadraticSubproblem.test_for_the_easy_case
TestKrylovQuadraticSubproblem.test_for_very_close_to_zero
TestEllip.test_ellipkinc
TestEllip.test_ellipkinc_singular
TestSystematic.test_e1
TestSystematic.test_e1_complex
TestSystematic.test_ei
TestSystematic.test_ei_complex
TestSystematic.test_ker
```

gh-11267 is rebased on master 76da841e4 Mon Dec 23 02:15:40 2019 -0800 so is current.
The two PRs are in `stats` and shouldn't affect units tests in `optimize` or `special`.  Are these tests known to fail with Py3.6?

**Comment by pvanmulbregt** [comment] 2019-12-24 22:11
gh-11266 is the same as the Travis-CI issue.

**Comment by pv** [comment] 2020-01-04 13:20
The Travis CI issue was fixed.

The Linux_Python_36_32bit_full Azure failures do not appear related to actual code changes in Scipy --- they first appear for builds in between 7b84b5345...76da841e4, which contains only docstring changes.

Logs: [last successful build log](https://dev.azure.com/scipy-org/df8ffb44-7275-43bc-90f9-aa5c93ef5c51/_apis/build/builds/4348/logs/65) and the [first failing log](https://dev.azure.com/scipy-org/df8ffb44-7275-43bc-90f9-aa5c93ef5c51/_apis/build/builds/4362/logs/61).

Comparing the logs, it appears Numpy was upgraded from 1.17.4 to 1.18.0.

**Comment by pv** [comment] 2020-01-04 18:36
Reproducible locally in 32-bit ubuntu 18.04 VM.

The problem seems to be that Numpy 1.18.0 adds `-std=c99` flag unconditionally, which also turns on `-fexcess-precision=standard` and this apparently changes the meaning of comparisons such as:
```
       if (fabs(phi) >= NPY_PI_2) {
```
The problem here is that the `NPY_PI_2` macro additional decimals beyond the double precision, and gcc apparently then generates code that is different from `(double)NPY_PI_2` due to the 387 FPU excess precision. The issue is reproducible also on x86_64 (also with Numpy 1.17) when compiling with `OPT="-std=c99 -mfpmath=387" python3 setup.py ...`.

E.g. the `ellipkinc` is fixed by:
```
diff --git a/scipy/special/cephes/ellik.c b/scipy/special/cephes/ellik.c
index b21a4a1dd..d108266bc 100644
--- a/scipy/special/cephes/ellik.c
+++ b/scipy/special/cephes/ellik.c
@@ -84,7 +84,7 @@ double ellik(double phi,  double m)
        return (phi);
     a = 1.0 - m;
     if (a == 0.0) {
-       if (fabs(phi) >= NPY_PI_2) {
+       if (fabs(phi) >= (double)NPY_PI_2) {
            sf_error("ellik", SF_ERROR_SINGULAR, NULL);
            return (NPY_INFINITY);
        }
```
and the issue with `ker` failures appears to be similar (i.e. Fortran code sets `x = 1e300`, and in C code `x != 1e300` but `x == (double)1e300`).

Obviously, other bugs of this type may be lurking around, as I'm sure this will cause also other problems.

**Comment by pv** [comment] 2020-01-05 12:32
Was fixed.

**Closed by pv** 2020-01-05 12:32 UTC
Labels: defect, scipy.sparse
