### ISSUE TITLE
Wrong p-value and unwanted warning when using scipy.stats.pearsonr

### ISSUE THREAD

**Issue by moinfar** [scipy/scipy#9396] opened 2018-10-21 16:35 UTC
My issue is taking a warning, while it is not logical.

### Reproducing code example:

```
import numpy as np
from scipy.stats import pearsonr, spearmanr
x = np.asarray([0.20411998265592482, 0.07918124604762482])
y = np.asarray([0.017448610113466535, 0.012129956392826626])
print(pearsonr(x,y))
```

### Warning message:

```
/usr/local/lib/python3.5/dist-packages/scipy/stats/stats.py:3020: RuntimeWarning: invalid value encountered in double_scalars
  prob = _betai(0.5*df, 0.5, df/(df+t_squared))
```

### Output
Below + warning above.
```
(0.9999999999999999, nan)
```

### Expected Output
I expect getting no warning. in addition p-value must be 0 not nan!
```
(1.0, 0.0)
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.5 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment] 2018-10-21 17:07
seems like the duplicate of #8980

**Comment by chrisb83** [comment] 2018-10-21 17:56
Looks related to #7730 as well

**Comment by ilayn** [comment] 2018-10-21 18:04
yes that's a better fit I think

**Comment by chrisb83** [comment] 2018-10-22 20:07
Closing this issue, it is a duplicate of 7730

**Closed by chrisb83** 2018-10-22 20:07 UTC
Labels: defect, scipy.stats

**Comment by mdhaber** [comment] 2025-10-24 06:51
This was partially fixed for `spearmanr`, but it still has a NaN p-value whereas in gh-7730 it was discussed that the correct two-sided p-value is `1.0`.
```python3
import numpy as np
from scipy import stats
x = np.asarray([0.20411998265592482, 0.07918124604762482])
y = np.asarray([0.017448610113466535, 0.012129956392826626])

stats.spearmanr(x, y)
# SignificanceResult(statistic=np.float64(0.9999999999999999), pvalue=np.float64(nan))

stats.pearsonr(x, y)
# PearsonRResult(statistic=np.float64(1.0), pvalue=np.float64(1.0))
```

`spearmanrho` does not produce a warning, and it produces the correct p-value.
```python3
stats.spearmanrho(x, y)
# SignificanceResult(statistic=np.float64(1.0), pvalue=np.float64(1.0))
```
