### ISSUE TITLE
MatrixLinearOperator implements _adjoint(), but not _transpose()

### ISSUE THREAD

**Issue by c-f-h** [scipy/scipy#7396] opened 2017-05-11 10:32 UTC
See title. Given a matrix `A`, this works:

    aslinearoperator(A).H

but this not:

    aslinearoperator(A).T

This seems like a basic oversight; is there a reason?

**Comment by ilayn** [comment] 2017-05-11 12:55
How about this https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.transpose.html ?

**Comment by c-f-h** [comment] 2017-05-11 14:55
Isn't that the documentation for the method on the abstract base class `LinearOperator`? It doesn't seem to be implemented for `MatrixLinearOperator`.

**Comment by pv** [comment] 2017-05-11 15:24
Indeed, .T raises an error (note that this back-and-forth would have 
been avoided with code example and error message).

**Comment by brd4790** [comment] 2017-12-23 13:40
I'd like to make a PR on this, because I've never done one before & this seems like an easy one - is this OK? It will probably take me a bit to work through all the first time stuff.

As far at this change goes, to me this seemed like just adding _transpose method with a one-liner "return MatrixLinearOperator(self.A.T)". However, I was comparing transpose to adjoint method and I'm pretty confused about the implementation of the adjoint method... why does it return an AdjointMatrixOperator?? Seemed really odd to me, that's like if you took the adjoint of a matrix and got an AdjointMatrix instead of a just a Matrix. I wonder if there's a reason for this, and if I should follow suit in the implementation of transpose.
Thanks!

**Comment by c-f-h** [comment] 2017-12-31 13:30
From reading the code, it seems that it caches both the adjoint operator as well as the adjoint of the adjoint (i.e., the original matrix) so that if you do `.H` repeatedly, it won't have to compute the adjoint matrix several times, and if you do `.H.H` it will give you back the original matrix. So it seems to be an optimization that sounds reasonable to have also for the transpose.

**Comment by pv** [comment] 2019-10-06 19:48
This was fixed in the meantime.

**Closed by pv** 2019-10-06 19:48 UTC
Labels: defect, scipy.sparse.linalg

**Comment by lorentzenchr** [comment] 2023-02-14 06:40
For reference: This is a predating duplicate of #8486 and was fixed in #9064.
