### ISSUE TITLE
When running tests for sklearn, there will be a crash happened in SciPy side

### ISSUE THREAD

**Issue by huzq85** [scipy/scipy#6158] opened 2016-05-13 09:41 UTC
**Test Env:**
1. Windows 8.1
2. SciPy installed via Anaconda (https://www.continuum.io/downloads), Anaconda for Windows Python2.7, Windows 64-bit.
3. scikit-learn latest source code (I believe if use scikit-learn binary, still can re-produce this issue)
**Re-produce step:**
1. Navigate to the folder where put the scikit-learn source code.
2. Open cmd prompt and type: python setup.py install
3. After install done, type: nosetests -v sklearn
**Test Results:**
Crash will happen when running case: sklearn.datasets.tests.test_mldata
**Expect Results:**
At least SciPy should not cause crash.
**Investigation Results:**
Actually this is a strange issue, it just happen in Windows platform, not under Linux.
And now based on the investigation results, I might say this could not a SciPy bug, but might be a bug from Anaconda release. See details in following link:
https://github.com/scikit-learn/scikit-learn/issues/6776
And hope someone can help!

**Comment by ev-br** [comment] 2016-05-13 09:51
Please add a short self-contained example to trigger the crash with only scipy and a mat file (please place it somewhere public).

**Comment by kevin-coder** [comment] 2016-05-13 10:18
Actually no self-contained example, just typing command: nosetests -v scipy (I have tried this command just now) will cause this crash. Attached the mat files. (I don't think this issue is caused by mat files)
[data.zip](https://github.com/scipy/scipy/files/262989/data.zip)
Related code might cause crash in SciPy (**mio5.py**):
============
    def read_var_header(self):
        ''' Read header, return header, next position

        Header has to define at least .name and .is_global

        Parameters
        ----------
        None

        Returns
        -------
        header : object
           object that can be passed to self.read_var_array, and that
           has attributes .name and .is_global
        next_position : int
           position in stream of next variable
        '''
        mdtype, byte_count = self._file_reader.read_full_tag() <== **Crash here!**
============
I think you can have a test whether crash issue can be re-produced here. Also I think it is more likely a bug introduced by Anaconda release instead of SciPy itself.

**Comment by ev-br** [comment] 2016-05-13 13:28
It could be useful to try reproducing it with e.g. Gohlke binaries. If both they and Anaconda crash, it's likely a a scipy issue; if they do not, it's likely something for Anaconda people.

**Comment by kevin-coder** [comment] 2016-05-13 14:33
@ev-br , yes, agree with you, I have tested on 3 different machines with Windows platform installed Anaconda, all of them were crashed, but I also tested on Linux (Ubuntu 16.04 LTS), no crash happen, so I think it should be Anaconda's issue. How could we report this issue to them?

**Comment by ev-br** [comment] 2016-05-13 15:45
I think it's https://github.com/ContinuumIO/anaconda-issues

**Comment by kevin-coder** [comment] 2016-05-14 04:53
Thank you, I will report this issue to them.

**Comment by pv** [comment] 2016-05-16 07:49
Maybe useful to check the code for strict aliasing violations?
These are one thing in which the (unspecified) behavior is different in 
old and new gcc versions...

**Comment by rgommers** [comment] 2019-08-11 01:06
Anaconda issue was filed and fixed. No more instances of this in the last 3 years, so let's close this. Thanks all.

**Closed by rgommers** 2019-08-11 01:06 UTC
Labels: 3rd party binaries, scipy.io
