### ISSUE TITLE
BUG: Wilcoxon signed rank test not always using normal approximation when ties exist

### ISSUE THREAD

**Issue by jconoranderson** [scipy/scipy#15856] opened 2022-03-23 19:22 UTC
### Describe your issue.

I'm running a pre-post hypothesis test on a small dataset using the Wilcoxon signed rank test (scipy.stats.wilcoxon), and noticed when I validated the results the p-value did not match. It looks like it is not using the normal approximation even though ties exist. 

Per the documentation the expected approach is:

"To derive the p-value, the exact distribution (mode == 'exact') can be used for sample sizes of up to 25. The default mode == 'auto' uses the exact distribution if there are **at most 25 observations and no ties**, otherwise a normal approximation is used (mode == 'approx')."

The example demonstrates this by running the out of the box wilcoxon then testing for ties and running the "mode = 'approx'" if they exist.

You will find the first result when running the regular test is ```pvalue=0.01220703125``` and the second with logic built in to test for ties is ```pvalue=0.014944844395687155```

In this dataset they exist in both the pre and post period.

### Reproducing Code Example

```python
dfgh = pd.DataFrame({'ID':[1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,13,13],
                    'Period':['0 Month','3 Month','0 Month','3 Month','0 Month','3 Month',
                            '0 Month','3 Month','0 Month','3 Month','0 Month','3 Month',
                            '0 Month','3 Month','0 Month','3 Month','0 Month','3 Month',
                            '0 Month','3 Month','0 Month','3 Month','0 Month','3 Month',],
                    'Scale':['Something','Something','Something','Something','Something',
                            'Something','Something','Something','Something','Something',
                            'Something','Something','Something','Something','Something',
                            'Something','Something','Something','Something','Something',
                            'Something','Something','Something','Something',],
                    'Value':[18,26,23,4,24,3,27,26,9,0,40,3,17,10,33,9,6,7,8,1,9,4,26,9,]
                            })

dfhb = dfgh.query('Period == "0 Month"')
dfh3 = dfgh.query('Period == "3 Month"')

print('run standard wilcoxon:')
print(wilcoxon(dfhb.Value, dfh3.Value,alternative='two-sided', correction=True,))
print('\ntest for ties and selct normal approximation if the exist')
if (dfhb['Value'].nunique() < len(dfhb['Value'])) or (dfh3['Value'].nunique() < len(dfh3['Value'])):
    print('ties identified - use approx:')
    pval = wilcoxon(dfhb.Value, dfh3.Value, alternative='two-sided', correction=True,mode ='approx',)
else:
    print('no ties')
    plav = wilcoxon(dfhb.Value, dfh3.Value,alternative='two-sided', correction=True,mode ='exact',)
print(pval)
print('SciPy Version: ' + scipy.__version__)
```

### Error message

```shell
There is no associated error.
```

### SciPy/NumPy/Python version information

1.6.2

**Comment by mdhaber** [comment] 2022-03-24 20:02
Yes, there was some confusion about "ties" vs "zeros" in the past. This is a duplicate of gh-13689, so I'll close this one.

In the meantime, if you want a p-value that accounts for ties in your observations:
```python3
import numpy as np
from scipy import stats

x = np.array([18, 23, 24, 27,  9, 40, 17, 33,  6,  8,  9, 26])
y = np.array([26,  4,  3, 26,  0,  3, 10,  9,  7,  1,  4,  9])
z = x - y

def statistic(z):
    # 'approx' because we only need the test statistic 
    # 'less' because we want `r_plus`, not `min(r_plus, r_minus)`
    # (we can do one- or two-sided test with `permutation_test` regardless
    return stats.wilcoxon(z, method='approx', alternative='less').statistic

res = stats.permutation_test((z,), statistic, permutation_type='samples',
                             vectorized=False)  # pvalue=0.0107421875
```
The "exact" method of `wilcoxon` is not exact because you have ties, but it is more accurate than the normal approximation in this case. Both are conservative (less chance of Type I error) compared the permutation test.
```python3
stats.wilcoxon(z)   
# WilcoxonResult(statistic=7.5, pvalue=0.01220703125, zstatistic=nan)
stats.wilcoxon(z, method='approx')
# WilcoxonResult(statistic=7.5, pvalue=0.013399677168553005, zstatistic=-2.472966316733408)
```

**Closed by mdhaber** 2022-03-24 20:02 UTC
Labels: defect, scipy.stats
