### ISSUE TITLE
AD test for double Gaussian 

### ISSUE THREAD

**Issue by suvenduat** [scipy/scipy#13590] opened 2021-02-19 10:19 UTC
I am trying the Anderson–Darling (AD) test for a distribution that is well-fitted by a double Gaussian than the single Gaussian. 

There is an option to check the normality or a few other distributions but non for double Gaussian functions.  

I have tried ADtest_ksample with the data and the best-fitted double Gaussian model but the critical values are found to be the same as the one I get using a single Gaussian. Is there any workaround?

**Comment by tupui** [comment] 2021-02-19 18:30
Hi, could you provide some reproducible example of what you are doing? It seems more like a support question than a bug. StackOverflow would be better indicated if that would be the case.

**Comment by josef-pkt** [comment] 2021-02-19 19:21
what's a double gaussian distribution?

If parameters are estimated, then tabulated p-values are not correct, and cannot be tabulated for other than loc-scale families.
In other cases, simulated or bootstrap p-values will be more appropriate.

**Comment by tupui** [comment] 2021-02-19 19:39
I guess double gaussian means a bi-modal distribution here.

**Comment by tupui** [comment] 2021-02-24 16:26
@suvenduat Could you give more details so that we can help?

**Comment by suvenduat** [comment] 2021-02-24 17:10
I actually posted the issue in StackOverflow but there is no response yet. 

To give details, I fit the distribution of my data using 1) normal, 2) log-normal, and 3) bi-model (or double normal) distribution. The data distribution is best fitted by a double normal as per the curve_fit chi^2 minimization and visual inspection (see the attached plot also). Now, I am trying the KS test and AD test to see if the bi-model distribution is indeed the best one to present the data distribution. But, I am not finding the expected result. Here, I give a detailed example code based on the KS test. 

First, I fit the histogram of the data using the above functions and estimate the parameters and then use those best-fit parameters in the KS test.
`def normal(x, mean1, stdv1):
    return stats.norm.pdf(x, mean1, stdv1)`
`def log_normal(x, stdv1, scale1):
    return stats.lognorm.pdf(x, stdv1, scale=scale1)`
`def double_normal(x, weight1, mean1, stdv1, weight2, mean2, stdv2):
    return weight1 * stats.norm.pdf(x, mean1, stdv1) + weight2 * stats.norm.pdf(x, mean2, stdv2)`
`def double_normal_cdf(x, weight1, mean1, stdv1, weight2, mean2, stdv2):
    return (weight1*stats.norm.cdf(x, mean1, stdv1) + weight2*stats.norm.cdf(x, mean2, stdv2))`  

`ydata, bin_edg = np.histogram(original_data, 40, density=True)`
`xdata = 0.5*(bin_edg[1:]+bin_edg[:-1])`
`popt1, pcov1 = curve_fit(normal,        xdata, ydata, p0=[4, 3])`     
`popt2, pcov2 = curve_fit(log_normal,    xdata, ydata, p0=[3, np.exp(4)])`
`popt3, pcov3 = curve_fit(double_normal, xdata, ydata, p0=[0.2, 4, 0.3, 0.3, 5, 0.3])` 

and then do the KS test using the kstest and ks_2samp

`stat1, pvalue1 = stats.kstest(ydata, cdf=stats.norm.cdf, args=(popt1))`
`stat11, pvalue11 = stats.ks_2samp(ydata, stats.norm.pdf(xdata, *popt1))`
`stat2, pvalue2 = stats.kstest(ydata, cdf=stats.lognorm.cdf, args=(popt2))`
`stat22, pvalue22 = stats.ks_2samp(ydata, stats.lognorm.pdf(xdata, popt2[0], scale=popt2[1]))`
`stat3, pvalue3 = stats.kstest(ydata, cdf=double_normal_cdf,args=(popt3))`
`stat33, pvalue33 = stats.ks_2samp(ydata, double_normal(xdata, *popt3))`

The stat1 and stat11 results are also different. 
This also happens for 2 and 22, 3 and 33. 
I get the lowest Dstat for stat22 which is for log-normal. 
This shouldn't be as the best-fit should be double normal.

The output results are 
stat1 =0.99,stat11=0.40,stat2 =1.0,stat22=0.22,stat3 =0.99,stat33=0.40

So, is there anything wrong with my computation? 

[pdf.pdf](https://github.com/scipy/scipy/files/6037632/pdf.pdf)

**Comment by rkern** [comment] 2021-02-24 17:23
Generally speaking, doing least-squares, especially unweighted least-squares, to fit PDFs to histograms is not a good idea for several reasons. The primary one here is that the error bars are not the same size for each histogram bin. The bins at the peak will have larger absolute magnitude error bars than the ones in the tails. But `curve_fit()` treats them the same. The bin that seems to be driving the least-squares fit to prefer the bimodal distribution is very likely to be just random noise.

**Comment by tupui** [comment] 2021-02-24 17:24
But when you call `ks_2samp`, why do you do it with the PDF? You have to do it with the samples, not the probabilities.

**Comment by suvenduat** [comment] 2021-02-24 17:42
@tupui I didn't get it! For ks_2samp, we should compare two data distribution, right? Only, the ydata (histogram of data) and its best fit model (double_normal(xdata, *popt3)) are compared. What should it be?

**Comment by suvenduat** [comment] 2021-02-24 17:43
> Generally speaking, doing least-squares, especially unweighted least-squares, to fit PDFs to histograms is not a good idea for several reasons. The primary one here is that the error bars are not the same size for each histogram bin. The bins at the peak will have larger absolute magnitude error bars than the ones in the tails. But `curve_fit()` treats them the same. The bin that seems to be driving the least-squares fit to prefer the bimodal distribution is very likely to be just random noise.

Agree, but KS test, we also don't include the errorbar. That's why I purposely didn't consider the errorbar in curve_fit.

**Comment by tupui** [comment] 2021-02-24 17:43
> @tupui I didn't get it! For ks_2samp, we should compare two data distribution, right? Only, the ydata (histogram of data) and its best fit model (double_normal(xdata, *popt3)) are compared. What should it be?

No you have to compare two population of samples that you are sampling from the distributions.

**Comment by suvenduat** [comment] 2021-02-24 18:06
@tupui: Thanks for the clarification but still Gaussian seems to be more preferable compared to the double Gaussian. Also, what about calling stats.kstest, I guess, it is correct to call cdf?

**Comment by rkern** [comment] 2021-02-24 18:15
The KS test doesn't compare PDFs to histograms. That's why it doesn't account for histogram error bars.

One other thing is that your double-normal fitting isn't normalized. `weight1 + weight2` should be constrained to equal 1 (or preferably, reparameterize to a single parameter and derive the correctly-normalized weights). Thus your fitted CDF is also probably not normalized. The KS test is likely picking up on that.

Looking at the data you've provided, a single Gaussian is very likely to be a better model than a double-Gaussian, even when properly fit. If you want to test this, you should set up maximum-likelihood fits, and use a single-parameter double-Gaussian (I like `weight1=exp(theta)/(1+exp(theta)); weight2=1/(1+exp(theta))`).

**Comment by tupui** [comment] 2021-02-24 18:41
> @tupui: Thanks for the clarification but still Gaussian seems to be more preferable compared to the double Gaussian. Also, what about calling stats.kstest, I guess, it is correct to call cdf?

You're welcome 😄 . For the CDF, yes you can provide a callable to the CDF function.

I am closing this as it is more of a support question. (Does not mean we cannot continue to discuss this of course 😄 ). Feel free to re-open it in the even there is in fact a bug or an unexpected behaviour.

**Closed by tupui** 2021-02-24 18:41 UTC

**Comment by josef-pkt** [comment] 2021-02-24 18:52
just an aside:

Single gaussian is nested in double (weighted) gaussian, so double gaussian is always at least as good in fit as single gaussian.

There needs to be some penalization for the number of components or parameters, as for example in AIC, BIC, to choose single gaussian when it fits "well enough".
