### ISSUE TITLE
Bug in lbfgsb.py?

### ISSUE THREAD

**Issue by johny-c** [scipy/scipy#7196] opened 2017-03-18 13:04 UTC
Hi all, I'm trying to make my code compatible with old scipy versions and I'm stuck in errors coming from fmin_l_bfgs_b from the lbfgsb module in optimize. In particular for scipy version 0.9. I've simplified my inputs to the function as much as possible. Even with just passing the first two parameters, I get:

File "/usr/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 190, in fmin_l_bfgs_b
    isave, dsave)
_lbfgsb.error: failed in converting 4th argument `u' of _lbfgsb.setulb to C/Fortran array

'u' is supposed to be the upper bound constraints for the optimization, but it should be handled as None if nothing is passed (no bounds). I tried passing `bounds=[(-np.inf, np.inf)]*len(x0)` explicitly and a few other things but to no avail. I am calling the optimizer like this:

`x, loss, info = optimize.fmin_l_bfgs_b(func=loss_grad, x0=np.asfortranarray(x0))`

The code runs normally with later versions of scipy and python 3. Any ideas?

**Comment by pv** [comment] 2017-03-18 15:01
Not a bug in current scipy version, apparently, so closing.
Feel free to continue discussion.

**Closed by pv** 2017-03-18 15:01 UTC
