### ISSUE TITLE
jn_zeros() hangs when trying to compute zeros for several bessel orders.

### ISSUE THREAD

**Issue by Berxue** [scipy/scipy#11994] opened 2020-05-01 21:34 UTC
jn_zeros() is not able to compute the first 100 zeros of the following Bessel orders below 1000(I only tested it till 1000):
231,244,281,288,347,348,357,405,406,419,437,
505,506,507,570,582,591,643,644,655,658,679,
706,713,722,752,756,757,764,775,793,796,811,
820,840,855,875,886,916,942,948,966

#### Reproducing code example:
``` 
from scipy import special 
special.jn_zeros(231,5)
```

#### Error message:

No error message! The command just hangs while using 100% CPU on one core. 

#### Scipy/Numpy/Python version information:

1.4.1 1.18.2 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)

**Comment by pukhlyakova** [comment] 2020-12-08 10:33
I have same problem.

```
>>> from scipy import special
>>> special.jn_zeros(1200,5)
array([1219.81758084, 1234.77622746, 1247.10400581, 1258.06004816,
       1268.12511012])
>>> special.jn_zeros(1250,5)
```
Here it is hanging =(

My scipy version
```
>>> import scipy
>>> print (scipy.__version__)
1.5.4
```

**Comment by WarrenWeckesser** [comment] 2021-02-14 01:08
@Berxue and @pukhlyakova, thanks for reporting the problem.  This issue is a duplicate of https://github.com/scipy/scipy/issues/4690, so I'm closing this one.

**Closed by WarrenWeckesser** 2021-02-14 01:08 UTC
Labels: defect, duplicate, scipy.special
