### ISSUE TITLE
linprog does not yield expected result with certain method

### ISSUE THREAD

**Issue by hexchain** [scipy/scipy#11940] opened 2020-04-26 13:11 UTC
I am trying some example LP problems in a paper but `scipy.optimize.linprog` does not give a solution similar to the result in that paper with a certain method.

Parameters in the original problem are described in the code snippet below (variable `c`, `A` and `b`), and the solution I'm expecting is something like `np.array([0.698, 0.1538, 0.1481, 0])`. With `simplex` and `revised simplex` I am able to get something reasonable, but `interior-point` says the problem is infeasible.

#### Reproducing code example:

```python
import numpy as np
from scipy import optimize, stats

A = np.array([
    [0.675, 0.1875, 0, 0],
    [0.325, 0, 0.1563, 0],
    [0, 0.8125, 0, 0.625],
    [0, 0, 0.8437, 0.375],
])
b = np.array([0.5, 0.25, 0.125, 0.125])
c = stats.entropy(A, base=2, axis=0)

r1 = optimize.linprog(c, A_eq=A, b_eq=b, method='simplex', options={'tol': 1e-4})
print("r1:", r1.x, r1.message)

r2 = optimize.linprog(c, A_eq=A, b_eq=b, method='revised simplex', options={'tol': 1e-4})
print("r2:", r2.x, r2.message)

r3 = optimize.linprog(c, A_eq=A, b_eq=b, options={'tol': 1e-4})
print("r3:", r3.x, r3.message)
```

#### Output:
```
test.py:14: OptimizeWarning: The pivot operation produces a pivot value of: 6.8e-01, which is only slightly greater than the specified tolerance 1.0e-04. This may lead to issues regarding the numerical stability of the simplex method. Removing redundant constraints, changing the pivot strategy via Bland's rule or increasing the tolerance may help reduce the issue.
  r1 = optimize.linprog(c, A_eq=A, b_eq=b, method='simplex', options={'tol': 1e-4})
test.py:14: OptimizeWarning: The pivot operation produces a pivot value of: 1.6e-01, which is only slightly greater than the specified tolerance 1.0e-04. This may lead to issues regarding the numerical stability of the simplex method. Removing redundant constraints, changing the pivot strategy via Bland's rule or increasing the tolerance may help reduce the issue.
  r1 = optimize.linprog(c, A_eq=A, b_eq=b, method='simplex', options={'tol': 1e-4})
test.py:14: OptimizeWarning: The pivot operation produces a pivot value of: 8.1e-01, which is only slightly greater than the specified tolerance 1.0e-04. This may lead to issues regarding the numerical stability of the simplex method. Removing redundant constraints, changing the pivot strategy via Bland's rule or increasing the tolerance may help reduce the issue.
  r1 = optimize.linprog(c, A_eq=A, b_eq=b, method='simplex', options={'tol': 1e-4})
r1: [0.69797868 0.15384615 0.14815693 0.        ] Optimization terminated successfully.
r2: [0.69797868 0.15384615 0.14815693 0.        ] Optimization terminated successfully.
r3: [0.79929405 0.04109058 0.13028819 0.42017539] The algorithm terminated successfully and determined that the problem is infeasible.
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.3 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment] 2020-04-26 15:37
What happens when you don't specify a tolerance in `options`?

Curious- why such a coarse tolerance?

**Comment by hexchain** [comment] 2020-04-26 15:51
Without specifying that tolerance, it fails either with an exception or claiming that the question is infeasible. I guess it is because the numbers are not exact (the data in the paper has only 4 decimal digits), so the tolerance needs to be on that level?

**Comment by mdhaber** [comment] 2020-04-26 15:57
The problem is infeasible. You have four equality constraints and four unknowns. The only solution to the equality constraints is:
```
>>>from scipy.linalg import solve
>>>solve(A, b)
array([ 7.69230769e-01, -1.02564103e-01,  1.95147653e-13,  3.33333333e-01])
```
The second element is less than zero, which is not allowed by the default bound of `linprog`, `(0, np.inf)`.

I'm going to close the issue because there's not a bug, but I'm curious what your application is, and why you are using `linprog` in this case.

**Closed by mdhaber** 2020-04-26 15:57 UTC

**Comment by hexchain** [comment] 2020-04-26 16:02
The paper is https://arxiv.org/abs/1712.08500 and what I'm trying to reproduce is the latter part of their Example 1. The problem is feasible according to the paper. I'm not sure if it is made infeasible because of the truncation of decimals.

**Comment by mdhaber** [comment] 2020-04-26 16:07
I would contact the authors. I don't understand why they would solve a square linear equality as a linear program. Is allowing the constraints to be violated slightly supposed to be required?

**Comment by hexchain** [comment] 2020-04-26 16:12
In its setting, there could be more than 4 unknowns. It happens to be 4 in this example because of their data.
