### ISSUE TITLE
BUG: pytest scipy/linalg/tests/test_extending.py fails with Cython file compilation error

### ISSUE THREAD

**Issue by tuhinsharma121** [scipy/scipy#20540] opened 2024-04-20 16:36 UTC
### Describe your issue.

`pytest scipy/linalg/tests/test_extending.py` fails with the attached error. I am using editable install as per the contributing documentation.

 Out of the 65k+ test cases this is the only test that fails. 

### Reproducing Code Example

```python
pytest scipy/linalg/tests/test_extending.py
```

### Error message

```shell
==================================================================================================== test session starts =====================================================================================================
platform darwin -- Python 3.11.8, pytest-8.1.1, pluggy-1.4.0
rootdir: /Users/tuhinsharma/Documents/Git/scipy
configfile: pytest.ini
plugins: cov-5.0.0, hypothesis-6.100.1, anyio-4.3.0, xdist-3.6.0, timeout-2.3.1
collected 1 item

scipy/linalg/tests/test_extending.py F                                                                                                                                                                                 [100%]

========================================================================================================== FAILURES ==========================================================================================================
________________________________________________________________________________________________________ test_cython _________________________________________________________________________________________________________

tmp_path = PosixPath('/private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0')

    @pytest.mark.skipif(platform.machine() in ["wasm32", "wasm64"],
                        reason="Can't start subprocess")
    @pytest.mark.skipif(cython is None, reason="requires cython")
    def test_cython(tmp_path):
        srcdir = os.path.dirname(os.path.dirname(__file__))
>       extensions, extensions_cpp = _test_cython_extension(tmp_path, srcdir)

srcdir     = '/Users/tuhinsharma/Documents/Git/scipy/scipy/linalg'
tmp_path   = PosixPath('/private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0')

scipy/linalg/tests/test_extending.py:17:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
scipy/_lib/_testutils.py:295: in _test_cython_extension
    subprocess.check_call(["meson", "compile", "-vv"], cwd=target_dir)
        build_dir  = PosixPath('/private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples')
        mod_name   = 'linalg'
        srcdir     = '/Users/tuhinsharma/Documents/Git/scipy/scipy/linalg'
        target_dir = PosixPath('/private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples/build')
        tmp_path   = PosixPath('/private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['meson', 'compile', '-vv'],), kwargs = {'cwd': PosixPath('/private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples/build')}
retcode = 1, cmd = ['meson', 'compile', '-vv']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.

        The arguments are the same as for the call function.  Example:

        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['meson', 'compile', '-vv']' returned non-zero exit status 1.

cmd        = ['meson', 'compile', '-vv']
kwargs     = {'cwd': PosixPath('/private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples/build')}
popenargs  = (['meson', 'compile', '-vv'],)
retcode    = 1

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py:413: CalledProcessError
---------------------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------------------
The Meson build system
Version: 1.4.0
Source dir: /private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples
Build dir: /private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples/build
Build type: native build
Project name: random-build-examples
Project version: undefined
C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
C linker for the host machine: cc ld64 1053.12
C++ compiler for the host machine: c++ (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
C++ linker for the host machine: c++ ld64 1053.12
Cython compiler for the host machine: cython (cython 3.0.10)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/Users/tuhinsharma/.virtualenvs/scipy/bin/python)
Found pkg-config: YES (/usr/local/bin/pkg-config) 0.29.2
Run-time dependency python found: YES 3.11
Build targets in project: 3

Found ninja-1.11.1.git.kitware.jobserver-1 at /Users/tuhinsharma/.virtualenvs/scipy/bin/ninja
[1/7] /Users/tuhinsharma/.virtualenvs/scipy/bin/meson --internal copy ../extending.pyx extending_cpp.pyx
[2/7] cython -M --fast-fail -3 /private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples/extending.pyx -o extending.cpython-311-darwin.so.p/extending.pyx.c
FAILED: extending.cpython-311-darwin.so.p/extending.pyx.c
cython -M --fast-fail -3 /private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples/extending.pyx -o extending.cpython-311-darwin.so.p/extending.pyx.c

Error compiling Cython file:
------------------------------------------------------------
...
#!/usr/bin/env python3
#cython: language_level=3
#cython: boundscheck=False
#cython: wraparound=False

from scipy.linalg.cython_blas cimport cdotu
^
------------------------------------------------------------

/private/var/folders/24/q83vy1q54_181scf16svmls40000gn/T/pytest-of-tuhinsharma/pytest-10/test_cython0/linalg/tests/_cython_examples/extending.pyx:6:0: 'scipy/linalg/cython_blas.pxd' not found
[3/7] cython -M --fast-fail -3 --cplus extending_cpp.pyx -o extending_cpp.cpython-311-darwin.so.p/extending_cpp.pyx.cpp
FAILED: extending_cpp.cpython-311-darwin.so.p/extending_cpp.pyx.cpp
cython -M --fast-fail -3 --cplus extending_cpp.pyx -o extending_cpp.cpython-311-darwin.so.p/extending_cpp.pyx.cpp

Error compiling Cython file:
------------------------------------------------------------
...
#!/usr/bin/env python3
#cython: language_level=3
#cython: boundscheck=False
#cython: wraparound=False

from scipy.linalg.cython_blas cimport cdotu
^
------------------------------------------------------------

extending_cpp.pyx:6:0: 'scipy/linalg/cython_blas.pxd' not found
ninja: build stopped: subcommand failed.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /Users/tuhinsharma/.virtualenvs/scipy/bin/ninja -v
================================================================================================== short test summary info ===================================================================================================
FAILED scipy/linalg/tests/test_extending.py::test_cython - subprocess.CalledProcessError: Command '['meson', 'compile', '-vv']' returned non-zero exit status 1.
===================================================================================================== 1 failed in 4.51s ======================================================================================================
```

### SciPy/NumPy/Python version and system information

```shell
Machine - Intel x86_64 MacOS Sonoma 14.4.1
Scipy - latest from the main branch
numpy==1.26.4
Python - 3.11.8
```

**Comment by tuhinsharma121** [comment] 2024-04-20 16:45
I am not sure if we should skip this test for `platform.machine()== 'x86_64' `

**Comment by j-bowhay** [comment] 2024-04-20 16:50
cc @thalassemia

**Comment by ilayn** [comment] 2024-04-20 18:44
Could you please use `python dev.py test -s linalg` in the root folder of the repo?

**Comment by thalassemia** [comment] 2024-04-20 18:46
I can reproduce the failure with all three `test_extending.py` files (linalg, special, optimize) on my macOS ARM machine, so it is not an architectural problem. This appears to be a quirk of `meson-python`'s editable install. In fact, you get the same failure if you try run `pip install -e . --no-build-isolation` on a cloned Numpy repo and test `pytest numpy/random/tests/test_extending.py` (which these tests were based on). Not sure if there's anything we can do about that. Things work fine with the `python dev.py` builds/tests.

**Comment by rgommers** [comment] 2024-04-20 19:23
These tests should be skipped for editable installs. Editable installs are fundamentally incomplete - they are only guaranteed to work at the Python level (`import scipy` etc. works), but things like generated headers (which is what `.pxd` files are) cannot be installed in the right place.

This should work to check for an editable install (in meson-python >=0.16.0):
```
IS_EDITABLE = 'editable' in scipy.__path__[0]
```

**Comment by thalassemia** [comment] 2024-04-20 20:25
Skipping the tests with the suggested `IS_EDITABLE` flag works for me. Is it expected that even non-generated headers like `scipy/optimize/cython_optimize.pxd` fail to be picked up in editable installs?

**Comment by tuhinsharma121** [comment] 2024-04-20 20:43
> Could you please use `python dev.py test -s linalg` in the root folder of the repo?

@ilayn this is the last line of the output
```
====================================================================== 4259 passed, 5 skipped, 7 deselected, 12 xfailed, 3 xpassed in 54.86s ======================================================================
```

**Comment by rgommers** [comment] 2024-04-21 09:52
> Is it expected that even non-generated headers like `scipy/optimize/cython_optimize.pxd` fail to be picked up in editable installs

It should be possible, but it depends on internal implementation details of Cython. I haven't checked in detail, but I suspect that when looking for `pxd` files, Cython relies on the `__path__` attribute of the top-level module. Which won't work. `__file__` would have worked. However, the only correct and modern way of locating files is (I believe) [importlib.resources.files](https://docs.python.org/3.11/library/importlib.resources.html#importlib.resources.files). So this would need improving on the Cython end.

**Comment by tuhinsharma121** [comment] 2024-04-21 14:31
Thanks all for indulging in the discussion. So what i understand is this issue is beyond scipy.

**Comment by lucascolley** [comment] 2024-04-21 19:40
> These tests should be skipped for editable installs.

Let's keep this open until this is addressed.

**Closed** 2024-04-22 22:45 UTC
Labels: defect, scipy.linalg
