### ISSUE TITLE
BUG: hypergeom.pmf slowed down by more than a factor of 1000 after version 1.7.3

### ISSUE THREAD

**Issue by anakin4** [scipy/scipy#17519] opened 2022-12-01 17:26 UTC
### Describe your issue.

Ever since version 1.8.0 certain all calls to hypergeom.pmf seem to be slower with certain set of parameters being processed so slow that it is code breaking. For the code shown below, my computer needs ~0.08s to process the loop using scipy 1.7.3 but ~262s on scipy 1.9.3, slowing down the process by more than a factor of 3000.

### Reproducing Code Example

```python
import numpy as np
import time
from scipy.stats import hypergeom

start = time.time()

for i in range(0, 1000):
    odds = hypergeom.pmf(np.arange(0, 201), 100000, 50000, 200)

end = time.time()
print("test: " f'{(end - start):0.5}' + "s")
```

### Error message

```shell
no error
```

### SciPy/NumPy/Python version information

1.7.3 1.22.4 sys.version_info(major=3, minor=10, micro=5, releaselevel='final', serial=0)

**Comment by mdhaber** [comment] 2022-12-01 18:53
This looks like a duplicate of https://github.com/scipy/scipy/issues/16079.

**Closed** 2022-12-01 19:13 UTC
Labels: defect
