### ISSUE TITLE
CI: some Azure cleanups and reactivating Pythran on Windows

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#15281] opened 2021-12-25 21:00 UTC
A few potentially useful things to do after the merge of gh-15268:

- [ ]  probably most important, find a way to turn Pythran usage back on for some of the Windows jobs (possible MSVC version bump issue/ after azure base image update? see discussion in that PR related to the sudden switch away from using `clang-cl` for the build--ideally Pythran would support both native cl the clang-cl driver interchangeably; could also be the flags we are using can't be swapped between the two)
- [ ] there's a usage of `SCIPY_USE_PYTHRAN` that happens *after* the SciPy build happens and before `runtests.py` with `-n` flag used, which looks like an oversight/accident (I added a second earlier usage to temporarily disable Pythran there)
- [ ] for the 32-bit Linux Azure CI job, since I switched that to using `pip install ..`, perhaps helpful to decide if we're going to then lean on the PEP-compliant deps specified in `pyproject.toml`, or if we should continue to pin to some older deps to i.e., protect/mirror the wheels repo 32-bit builds (until they disappear?)--if the latter, perhaps consider using the `--no-build-isolation` flag to retain relevance on the pins

**Comment by rgommers** [comment] 2021-12-27 12:53
Tried to work on this, and gave up on re-enabling Pythran in Windows CI. There's something very weird going on with the image that I cannot figure out: https://github.com/rgommers/scipy/pull/106#issuecomment-1001540904. The Meson build uses Pythran unconditionally right now, and the build system integration is much more robust there.

The 32-bit Linux job does look wrong and may still need cleaning up indeed.

**Comment by saudet** [comment] 2022-02-03 07:18
It's not something that entirely depends only on the Windows image. Here, locally on my laptop, I am able to build 1.8.0rc2 with Pythran and clang-cl gets called normally, but it fails with both 1.8.0rc3 and 1.8.0rc4. So, there's something that changed between rc2 and rc3 that caused this to happen. The only "big" change that I can see there is the switch from LooseVersion to _pep440, which I think is a big enough change that could trigger a bug like that somewhere in setup.py.

**Comment by rgommers** [comment] 2022-02-03 08:28
> So, there's something that changed between rc2 and rc3 that caused this to happen.

Are you sure? That seems quite unlikely. Note that numpy `1.22.0` was released in between rc2 and rc3, so if you are not building in the exact same environment with the same numpy version, that's a far more likely culprit.

Also, our troubles with Pythran & clang-cl selection started well before rc2.

**Comment by saudet** [comment] 2022-02-03 08:32
Yes, exact same environment, exact same session of MSYS2, exact same binaries of NumPy 1.22.1.
I merely have to change rc2 from rc3 on this line and it fails:
https://github.com/bytedeco/javacpp-presets/blob/b9b55590b48a08f78b0fc1eed94efc4be0133786/scipy/cppbuild.sh#L12
But if I change it back to rc2, clean everything, and try again, it succeeds!

**Comment by rgommers** [comment] 2022-02-03 08:55
Okay that is convincing, and your build logs show that you do have this `clang.exe` to `cl.exe` switching problem. I'll have a look at all commits between rc2 and rc3.

**Comment by rgommers** [comment] 2022-02-03 11:28
>  The only "big" change that I can see there is the switch from LooseVersion to _pep440, which I think is a big enough change that could trigger a bug like that somewhere in setup.py.

I agree, that does seem like the one likely problematic commit. Not because of the use of `LooseVersion` itself, but because of a change in import order & the monkey patching going on. `distutils` is still imported first, on line 217 for the `sdist` command, but that may still not have the same effect.

@saudet if you'd be able to appy this diff and see if that fixes your build, that'd be helpful:
```diff
diff --git a/setup.py b/setup.py
index 51fc85b88..29993a03d 100755
--- a/setup.py
+++ b/setup.py
@@ -24,6 +24,7 @@ import subprocess
 import textwrap
 import warnings
 import sysconfig
+from distutils.version import LooseVersion
 import importlib
```

**Comment by saudet** [comment] 2022-02-03 12:21
Nope, unfortunately it doesn't help :(

**Comment by rgommers** [comment] 2022-02-03 12:35
Hmm, thanks for trying that. It remains a mystery then.

**Comment by saudet** [comment] 2022-02-03 23:53
In any case, if everything works with Meson and you're planning on deprecating setuptools anyway, it's not worth spending too much time on this I think.

**Comment by saudet** [comment] 2022-02-04 11:03
FWIW, I confirmed that the commit that breaks it for me is https://github.com/scipy/scipy/commit/d4b4af0fa3a2ce7b06fd60ded4a5b003367131da. It works fine until the previous commit https://github.com/scipy/scipy/commit/b9d00c62431a635df1d241ab7a99f7d37b871045.

**Comment by saudet** [comment] 2022-02-04 22:49
It's also apparently when the CI problems for Pythran on Windows started, see https://github.com/scipy/scipy/pull/15256#issuecomment-998339651.

**Comment by tylerjereddy** [comment] 2022-02-04 23:12
Note also that the change is in response to increasingly annoying problems with setuptools/distutils, so it may be tricky to uncouple a mistake in that particular commit from say something around the same time coming from the ecosystem.

**Comment by rgommers** [comment] 2023-04-13 08:24
I've added a usage of `-Duse-pytran=false` for a Meson build in gh-15814. @tylerjereddy can we close this? I'm not sure there's more to do.

**Comment by rgommers** [comment] 2023-04-19 04:59
Okay, I'll close this. I think we're good here. The `clang-cl` usage is no longer required with Meson I believe, because we only use Pythran as a transpiler. That can be revisited with an MSVC-based CI job (xref gh-16957).

**Closed by rgommers** 2023-04-19 04:59 UTC
Labels: CI
