### ISSUE TITLE
ValueError: Linkage 'Z' uses the same cluster more than once thrown when clustering ward

### ISSUE THREAD

**Issue by lucyantie** [scipy/scipy#7108] opened 2017-02-28 15:49 UTC
Hi all, I' new to python and having this error when trying to use scipy.cluster.hierarchy.ward() for my clustering. 

I understand that this issue has been resolved in gh-6785 and gh-6495 but I have no idea how it actually solved. 

Please can someone guide me through this? Thank you.

Lucy

**Comment by rgommers** [comment] 2017-03-02 10:35
Hi Lucy, the fix was basically a rewrite of the whole algorithm. I suspect what you want to know is whether you have that fix in your scipy install, and if not then how to get it?

The fix is in 0.19.0, which is not yet released (probably next week it will be). If you're on Linux or OS X, you can grab a wheel of the daily builds at https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/. If you're on Windows, I suggest to wait a week (building SciPy yourself is no fun on Windows).

**Comment by rgommers** [comment] 2017-03-02 10:35
I'm going to close this issue because it's not a bug. Feel free to continue the discussion though.

**Closed by rgommers** 2017-03-02 10:35 UTC
Labels: query, scipy.cluster

**Comment by ev-br** [comment] 2017-03-02 10:53
Turns out, Christoph Gohlke has 0.19rc2 Windows builds already: http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy
Would be great if you test it.

**Comment by lucyantie** [comment] 2017-03-02 19:40
It works with 0.19rc2! Thanks, guys!
