### ISSUE TITLE
Wilcoxon signed rank test "pratt" zero method bug

### ISSUE THREAD

**Issue by BLMeltdown** [scipy/scipy#6398] opened 2016-07-21 01:03 UTC
Hello
As presented here:
http://stackoverflow.com/questions/38454893/error-in-scipy-wilcoxon-signed-rank-test-for-equal-series?noredirect=1#comment64315624_38454893
(without no answer to disprove it as a mistake from me),
I wish to report that maybe there is a problem with the results of scipy.wilcoxon signed rank test;

import scipy as sp
x1=[29.39958, 29.21756, 29.350915, 29.34911, 29.212635]
sp.wilcoxon(x1,x1,zero_method="wilcox",correction=True)

returns statistic=0.0, pvalue=nan

But with zero_method="pratt", it returns statistic=0.0, pvalue=0.043114446783075355 instead.
I think there is a mistake there. The statistics (for z-score, if I am not mistaken) are the same, but the results are different for the p-value, while they should not, actually.
When both series are identical, there should be no good p-value, but this is confident with alpha=0.05.

Maybe "pratt" zero_method is wrongly implemented. It is said to be more conservative, but instead it has also constantly given better /lower p-values on a large array of test values.

**Comment by rgommers** [comment] 2016-11-23 09:10
duplicate of gh-6805, which has more details. so closing.

**Closed by rgommers** 2016-11-23 09:10 UTC
