### ISSUE TITLE
macOS: Unable to compile universal scipy

### ISSUE THREAD

**Issue by sashkab** [scipy/scipy#7564] opened 2017-07-05 17:25 UTC
When using universal Python version and trying to install scipy, I'm getting a build of scipy that does not work for one of the architectures. 

Apparently, issue is due to fact that `gfortran` unable to build binaries with multiple architectures. 

```
$ gfortran -arch i386 -arch x86_64 x.f
gfortran: warning: x86_64 conflicts with i386 (arch flags ignored)
```

On top of that, numpy.distutils replace architecture `i386` with `i686`, which doesn't work even by itself

```
$ gfortran -arch i686 x.f
gfortran: error: this compiler does not support i686
```

`gfortran` was installed as part of Homebrew's gcc package:

```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/7.1.0/libexec/gcc/x86_64-apple-darwin16.5.0/7.1.0/lto-wrapper
Target: x86_64-apple-darwin16.5.0
Configured with: ../configure --build=x86_64-apple-darwin16.5.0 --prefix=/usr/local/Cellar/gcc/7.1.0 --libdir=/usr/local/Cellar/gcc/7.1.0/lib/gcc/7 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-7 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-checking=release --with-pkgversion='Homebrew GCC 7.1.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-nls
Thread model: posix
gcc version 7.1.0 (Homebrew GCC 7.1.0)
```
### Reproducing code example:

```
arch -32 python -mscipy.special
```

### Error message:
```
$ arch -32 python -mscipy.special
Traceback (most recent call last):
  File "/usr/local/Cellar/python27/2.7.13_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/local/Cellar/python27/2.7.13_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: dlopen(/Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/special/_ufuncs.so, 2): no suitable image found.  Did find:
    /Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/special/_ufuncs.so: mach-o, but wrong architecture
    /Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/special/_ufuncs.so: mach-o, but wrong architecture

$ file /Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/special/_ufuncs.so
/Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/special/_ufuncs.so: Mach-O 64-bit bundle x86_64
```

But some libraries were built as universal binaries:

```sh
$ file /Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/_lib/*.so
/Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/_lib/_ccallback_c.so:    Mach-O universal binary with 2 architectures: [i386: Mach-O bundle i386] [x86_64: Mach-O 64-bit bundle x86_64]
/Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/_lib/_ccallback_c.so (for architecture i386): Mach-O bundle i386
/Users/user/.virtualenvs/d/lib/python2.7/site-packages/scipy/_lib/_ccallback_c.so (for architecture x86_64):   Mach-O 64-bit bundle x86_64
```

### Scipy/Numpy/Python version information:

```sh
$ lipo -info /usr/local/Cellar/python27/2.7.13_2/bin/python2.7
Architectures in the fat file: /usr/local/Cellar/python27/2.7.13_2/bin/python2.7 are: x86_64 i386
```

* Python 2.7.13 or 3.6.1
* Numpy 1.12.1
* Scipy 0.19.1

**Comment by rgommers** [comment] 2017-07-06 11:40
There was a temporary OS X build issue that was fixed just a couple of days ago. Can you try again?

If it remains, then looks like a regression in ``gfortran``

**Comment by sashkab** [comment] 2017-07-06 12:42
@rgommers Could you please point me to issue/commits? I didn't find them while searching.

**Comment by rgommers** [comment] 2017-07-09 01:30
@sashkab that was gh-7558

**Comment by rgommers** [comment] 2017-07-09 01:32
OS X build is fine for me right now, with gfortran 4.9.1 (also installed with Homebrew). If your issue is not solved with current master, checking that you can build with 4.9.1 but not with 7.1.0 anymore would be helpful.

**Comment by sashkab** [comment] 2017-07-09 02:48
Build is fine, but a lot of .so's are built as thin binaries x86_64; while others are fat with i386 x86_64.

**Comment by rgommers** [comment] 2017-07-09 03:41
That's weird, can you put your full build log in a gist and link to it?

Note that SciPy should work for you now, ``i386`` is basically irrelevant by now.

**Comment by sashkab** [comment] 2017-07-12 15:41
> i386 is basically irrelevant by now.

Unfortunately not for us. We sometimes need to run our code in the 32-bit environment on 64-bit macOS system. Not only we couldn't built scipy as universal build, we failed to build it as 32-bit version as well, due to [the code in the numpy's distuils](https://github.com/numpy/numpy/blob/v1.13.1/numpy/distutils/fcompiler/gnu.py#L291). We managed to built 32-bit only version by removing L291-292 and  changing L295 to `for arch in ["i386"]:`. 

Not sure if it matters, gfortran is version 7.1.0 from homebrew.

**Comment by rgommers** [comment] 2017-07-13 12:00
Hmm, that code on L291-295 hasn't been changed in 7 years, so must be something in newer gfortran. That definitely used to work.

**Comment by rgommers** [comment] 2017-07-13 12:02
> Unfortunately not for us. We sometimes need to run our code in the 32-bit environment on 64-bit macOS system.

Out of interest: can you share why you need this?

**Comment by dhermes** [comment] 2017-08-26 03:50
I'm currently having this problem too, but really just because I'm curious what the "best" way to create a fat binary with `gfortran` on OS X is (I have the Homebrew `gfortran`, version 7.2.0).

The following example "works", but it is inelegant. TL;DR, but two static binaries and combine them with `lipo` (yes, the tool's name is an inside-joke about fat-binaries).

----

Simple subroutine in `foo.f90`:

```fortran
subroutine bar(x, y, z) bind(c, name='bar')
  integer, intent(in) :: x, y
  integer, intent(out) :: z

  z = x + y

end subroutine bar
```

Compile two static binaries:

```
$ gfortran -arch i386 -c foo.f90 -o foo.o
$ ar -rcs libfoo_i386.a foo.o
$ rm -f foo.o
$
$ gfortran -arch x86_64 -c foo.f90 -o foo.o
$ ar -rcs libfoo_x86_64.a foo.o
$ rm -f foo.o
```

and then combine them:

```
$ lipo \
>   libfoo_i386.a libfoo_x86_64.a \
>   -create \
>   -output libfoo.a
$
$ # Inspect our work
$ otool -L libfoo.a
Archive : libfoo.a
libfoo.a(foo.o):
$ file libfoo.a
libfoo.a: Mach-O universal binary with 2 architectures
libfoo.a (for architecture i386):       current ar archive random library
libfoo.a (for architecture x86_64):     current ar archive random library
```

Then if we want to, for example, use it from a Cython module `wrapper.pyx`:

```cython
cdef extern void bar(int *x, int *y, int *z)


def triple_bar(int x, int y):
    cdef int z
    bar(&x, &y, &z)
    return 3 * z
```

We can make a fat binary Python extension module (this is a bit stripped down / let `distutils` do this for you):

```
$ cython wrapper.pyx
$ clang \
>   -arch i386 -arch x86_64 \
>   -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 \
>   -c wrapper.c \
>   -o wrapper.o
$ clang \
>   -arch i386 -arch x86_64 \
>   -bundle \
>   -undefined dynamic_lookup \
>   -L. -lfoo \
>   wrapper.o \
>   -o wrapper.so
$
$ file wrapper.so
wrapper.so: Mach-O universal binary with 2 architectures
wrapper.so (for architecture i386):     Mach-O bundle i386
wrapper.so (for architecture x86_64):   Mach-O 64-bit bundle x86_64
```

once doing this, we can use the fat binary:

```
$ arch -32 /usr/bin/python -c 'import wrapper; print(wrapper.triple_bar(3, 7))'
30
$ arch -64 /usr/bin/python -c 'import wrapper; print(wrapper.triple_bar(2, 3))'
15
```

**NOTE**: The above uses the OS X system Python 2.7 so you may have a different include dir than `/System/Library/.../python2.7` and a different executable than `/usr/bin/python`

(Empirically, I've observed that the `x86_64` non-fat binary works just fine with `arch -32`, but the `i386` non-fat binary **does not** work with `arch -64`.)

**Comment by rgommers** [comment] 2019-03-05 01:43
NumPy dropped 32-bit macOS support and didn't fix a bug related to that: https://mail.python.org/pipermail/numpy-discussion/2018-August/078582.html. So we're not supporting it anymore either; 32-bit macOS is not relevant anymore. So closing as wontfix.

**Closed by rgommers** 2019-03-05 01:43 UTC
Labels: Build issues
