### ISSUE TITLE
Add Normal-inverse-gamma distribution

### ISSUE THREAD

**Issue by FlorianWilhelm** [scipy/scipy#6528] opened 2016-08-31 07:22 UTC
Right now the [Normal-inverse-gamma distribution](https://en.wikipedia.org/wiki/Normal-inverse-gamma_distribution) is missing in `scipy.stats`. I think it qualifies as useful addition since it is the [conjugate prior](https://en.wikipedia.org/wiki/Conjugate_prior) of the normal distribution in case mean and variance are unknown. Therefore the Normal-inverse-gamma distribution is important for Bayesian inference which has been for years and still is a trending topic in the domain of data science.

**Comment by WarrenWeckesser** [comment] 2016-09-07 01:49
I agree, it would be great to have it.  In fact, there is already a (stalled) pull request for it that was started three years ago, https://github.com/scipy/scipy/pull/2648, so I'm closing this issue.

If you are interested in reviving that pull request, add your comments there.

**Comment by FlorianWilhelm** [comment] 2016-09-07 05:58
@WarrenWeckesser You are linking the normal [Normal-inverse Gaussian](https://en.wikipedia.org/wiki/Normal-inverse_Gaussian_distribution) which is not equal to the [Normal-inverse Gamma](https://en.wikipedia.org/wiki/Normal-inverse-gamma_distribution) distribution or do I miss something here?

**Comment by WarrenWeckesser** [comment] 2016-09-07 13:01
>  ... or do I miss something here?

No, *I'm* the one who missed something.  Sorry about that!

**Comment by josef-pkt** [comment] 2016-09-28 19:55
@FlorianWilhelm  What methods and use cases do you have in mind for it?

Given that it is a bivariate distribution it would have to go with the multivariate distributions.  There is no strict pattern for those, AFAIK, and not much that can be inherited. So the features and implementation are mostly distribution specific. (in contrast to univariate models that has an elaborate "framework" and inherited methods, and have a more rigid structure).

scipy has a good collection of distribution, and I think it would be useful to keep expanding it also to new kinds of distributions. However, there is no established pattern and it would need some thoughts about what and how this should be implemented and what the API should be.

**Comment by FlorianWilhelm** [comment] 2016-09-29 06:12
@josef-pkt I actually learned about that distribution when I was looking for the conjugate prior of a normal distribution with unknown mean μ and precision τ, check [Wikipedia](https://en.wikipedia.org/wiki/Conjugate_prior). Since I haven't found the Normal-inverse-Gamma distribution I started to think about if the conjugate prior of a normal distribution with known precision would also do it and in my bayesian inference related to user profiling and I think it does. 

This means I am not working on the implementation of the Normal-inverse-Gamma right now but I still think it would be a valuable addition to Scipy.

**Comment by parulsethi** [comment] 2016-10-08 12:15
Isn't normal-inverse-wishart the multivariate one, and normal-inverse-gamma for the univariate. And i am interested in adding it's implementation to Scipy, but what all methods need to be added for this.
I guess PDF, CDF and random variate generation are the necessary ones, so apart from them what more would be required?

**Comment by josef-pkt** [comment] 2016-10-08 14:45
I think that mode and some moments mean, variance, median and some conditional or marginal distribution properties would be useful. What's easily feasible depends on which distribution.
E,g, the univariate case the conditional and marginal distributions method could return the corresponding univariate distribution instance. 
cdf in the general multivariate case will be difficult, rvs might be useful for users also to use MonteCarlo integration directly.

In general: IMO, it would be in the scope of scipy to provide the basic distribution facilities for basic Bayesian natural conjugates. I'm not a Bayesian anymore, but using the normal-normal conjugate pair assuming known variance is quite simple and useful (e.g. it's generalized Ridge regression or L2 penalized linear model.) Last week we had a question on the statsmodels mailing list on posterior from beta-binomial especially for the posterior confidence interval.
https://groups.google.com/d/msg/pystatsmodels/QaQc88bX718/7hONQuuADQAJ
There might be some license compatible packages in python or julia where some ideas for the implementation are available.

**Comment by parulsethi** [comment] 2016-10-08 18:01
There's a julia implementation https://github.com/JuliaStats/ConjugatePriors.jl/blob/master/src/normalinversegamma.jl to refer. But I need some help in adding it to scipy, like under which module would this go in stats?

**Comment by josef-pkt** [comment] 2016-10-08 18:15
@ev-br and @rgommers  are now essentially the main maintainers for stats.
If it's just this distribution to be added, then I would suggest continuing with https://github.com/scipy/scipy/blob/master/scipy/stats/_multivariate.py
But given that the module is already getting a bit large, and if there is the possibility to add more conjugate priors like in the julia package, then I would start a new module, maybe a variation on `conjugate`

**Comment by Naereen** [comment] 2017-05-15 11:34
Hi!
Any update on this?

**Comment by rgommers** [comment] 2017-07-21 10:17
> Any update on this?

Open PR is gh-6739, so that's the place to ask and where I will comment.

**Comment by mdhaber** [comment] 2021-03-20 23:35
This was requested again in gh-13644. Seems like it would be a valuable addition.

**Comment by MartinaCadiz** [comment] 2021-10-07 22:17
Any update? : ( Im looking for this conjugate prior

**Comment by tirthasheshpatel** [comment] 2023-03-07 22:57
From https://github.com/scipy/scipy/pull/18109#issuecomment-1458993415:

> It looks like the distribution is an oddball - it doesn't fit our univariate distribution infrastructure or the multivariate distribution infrastructure.
> 
> To summarize (from #6739 and #6528), here's where we stand on the issue:
> 
> - From https://github.com/scipy/scipy/pull/6739#issuecomment-261706648: Julia's [`ConjugatePriors.jl`](https://github.com/JuliaStats/ConjugatePriors.jl) package considers both `x` and `sig2` as random variates while R's [`PIGShift`](https://cran.r-project.org/web/packages/PIGShift/PIGShift.pdf) package considers only `x` as the random variate. Should SciPy follow the former or the latter convention?
> - From https://github.com/scipy/scipy/pull/6739#issuecomment-344051109: Would the implementation of the distribution be useful? The marginal distributions for `x` and `sig2` are already implemented in SciPy and it's easy to compute the full distribution using those.
> - From https://github.com/scipy/scipy/pull/6739#issuecomment-344051109: The CDF on Wikipedia seems incorrect. Probably best to avoid implementing it before confirming the closed form is correct.
> 
> To start, I am leaning more towards considering this a multivariate distribution with x and sig2 themselves being univariate random variates. We can iterate over it to allow multivariate sig2. As far as the usefulness of the distribution is concerned, I think it has gotten more user requests and attention than most other distributions. So, usefulness seems justified. But it would be nice to get some more opinions on these points.
> 
> I think that covers the major points discussed on the issue and on the PR. Feel free to add to the above list if I missed anything.

**Comment by MatteoRaso** [comment] 2023-03-20 17:10
I've played around with the PDF a bit, and it seems to only integrate to 1 if you integrate across both variables (there's also a large imaginary component, but I assume that's because of mpmath). That confirms that `x` and `sig2` both have to be treated as random variates, and it also means some of the formulas need to be reworked. That being said, I'm not sure if returning a random sample of `sig2` as well as `x` in the rvs method is the right way to go, since the `sig2` can be obtained from the invgamma rvs method. Anyways, I'm getting ahead of myself. I know a lot of Scipy maintainers also work on Numpy, which is busy preparing for a 2.0 release. I don't want to overload them with work, so I'm not going to work on this until Numpy 2.0 comes out. In the meantime, discussion here is dead, so we should move the conversation over to the mailing list. @tirthasheshpatel, sound good to you?

**Closed** 2024-10-20 06:14 UTC
Labels: scipy.stats, enhancement
