### ISSUE TITLE
Generate lowpass with output = "sos"

### ISSUE THREAD

**Issue by lcouka** [scipy/scipy#13592] opened 2021-02-20 00:20 UTC
Hello,
My issue is about lowpass generated in sos form
```
>>> print(signal.butter(2, 1, 'low', analog=True, output = "sos"))
>>> print(signal.butter(2, 1, 'high', analog=True, output = "sos"))
[[1.         0.         0.         1.         1.41421356 1.        ]]
[[1.         0.         0.         1.         1.41421356 1.        ]]
```
As you can see generating a lowpass and a highpass gives the same coefficients.
Same issue with the cheby1 filter type.
Like the sos configuration doesn't like to see b2 = 0
Cheers,

**Comment by roryyorke** [comment] 2021-02-20 10:34
This is likely related to, or essentially a duplicate of, gh-5668:

```
In [36]: print(signal.tf2sos(*signal.butter(2, 1, 'high', analog=True, output = "ba")))
[[1.         0.         0.         1.         1.41421356 1.        ]]
In [37]: print(signal.tf2sos(*signal.butter(2, 1, 'low', analog=True, output = "ba")))
[[1.         0.         0.         1.         1.41421356 1.        ]]
```

**Comment by lcouka** [comment] 2021-02-20 13:29
Yes it's exactly the same issue.

**Comment by tupui** [comment] 2021-02-20 16:51
Ok thanks  @lcouka. I am closing this one then.

**Closed by tupui** 2021-02-20 16:51 UTC
Labels: duplicate
