### ISSUE TITLE
API for representing censored data

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#13757] opened 2021-03-27 20:44 UTC
In https://github.com/scipy/scipy/pull/13699, I am implementing the fitting of distributions to censored data.   To represent censored data, I created a fairly simple class called `CensoredData`, and updated the `fit` method of the univariate continuous distributions to be able to handle an instance of the class.  There have been questions about the API for representing censored data in the PR.  Instead of having that discussion in the PR (where we also discuss implementation details), it seems cleaner to break out the API discussion to its own issue.

The wikipedia article [Censoring (statistics)](https://en.wikipedia.org/wiki/Censoring_(statistics)) provides an overview of what censored data is.  In the `CensoredData` class, we want to represent a data set that contains a mix of regular (i.e. not censored) data, right-censored data, left-censored data and interval-censored data.  The first three cases require a single number for each data point, while the last, interval-censored, requires two values to define the interval.

A common case of censoring is a data set that is a mix of regular values and censored values that all have the same type.  For example, the data shown in [this page](https://support.sas.com/documentation/cdl/en/qcug/63922/HTML/default/viewer.htm#qcug_reliability_sect004.htm) are either not censored or right censored.  The same is true for the first example in [this set of slides](http://www.ams.sunysb.edu/~zhu/ams588/Lecture_3_likelihood.pdf).  It would be nice if the API makes it easy to create an instance of `CensoredData` for such data sets.

The following are two possible constructors for the `CensoredData` class.

*Alternative 1: CensoredData(lower, upper)*

At the time of writing this comment, the `CensoredData` class has a constructor with the signature `__init__(self, lower, upper)`, where `lower` and `upper` are expected to be 1D arrays of numbers.  A number can be ±inf.  This API follows from the fact that we can represent all four cases (not censored, left-censored, right-censored or interval-censored) as an interval, if we allow ±inf as an end point, and if we interpret an interval of length 0 as an uncensored point.  The meaning of those points in the interval-censored case is as expected.  For a left-censored data point, the left value of the pair is set to -inf (i.e. the pair [-inf, 1] represents a left-censored value that is less than 1).  Likewise, for a right-censored data point, the right value is set to +inf.  For data points that are not censored, the two values are set to the same value (i.e. it is an "interval" with length 0).

Above I mentioned the common case of data that is a mix of uncensored and right-censored points.  A simple example in the docstring for `CensoredData` has four regular values, [13, 22, 17, 15], and two right-censored values, [20, 18].  To create a `CensoredData` instance for this data using the constructor, one would write:

    CensoredData(lower=[13, 22, 17, 15, 20, 18], upper=[13, 22, 17, 15, np.inf, np.inf])

The first four pairs ``(lower[i], upper[i])`` represent the uncensored data points, and the last two represent the right-censored data.

This API is very similar to the API provided by the R function [`fitdistcens`](https://www.rdocumentation.org/packages/fitdistrplus/versions/1.1-3/topics/fitdistcens) that is part of the [`fitdistrplus`](https://www.rdocumentation.org/packages/fitdistrplus/versions/1.1-3) package.  `fitdistcens` expects the censored data set to be represented as a data frame with two columns, named `left` and `right`.  The interpretion of the values in those columns is the same as that used in the current implemention of `CensoredData`, except that the R function uses `NA` instead of ±inf to indicate that a data point is left- or right-censored.   The above example in R would be

    data = data.frame(left=c(13, 22, 17, 15, 20, 18), right=c(13, 22, 17, 15, NA, NA))

To make it a bit easier to create data sets of this form, `CensoredData` has two alternative constructors implemented as class methods, `left_censored` and `right_censored`.  These take two arguments, a 1D array `x` of numbers and a boolean array of the same length that indicates if the corresponding value in `x` is censored.  With the `right_censored` method, the example above is created with

    CensoredData.right_censored(13, 22, 17, 15, 20, 18], [False, False, False, False, True, True])

So instead of having to create a copy of the values and assign `inf` where appropriate, the user supplies a boolean array.  A 0/1 flag is pretty common in the examples that I've found on the web where the data is shown in a textual format, so it is likely that such boolean array would be easily created when, say, reading the data from a file.

*Alternative 2: CensoredData(x=None, left=None, right=None, intervals=None)*

This is an alternative API, in which the constructor has a parameter for each type of censoring.  The parameters are

`x`: a 1D array of uncensored measurements
`left`: a 1D array of left-censored measurements
`right`: a 1D array of right-censored measurements
`intervals`: a 2D array with shape (m, 2) containing the intervals for `m` interval-censored values

The nice thing about this API is its explicitness, and that it doesn't require the user to use ±inf to create left- or right-censored values. The simple example given above can be represented as

    CensoredData(x=[13, 22, 17, 15], right=[20, 18])

That is a clean API for creating a right-censored data set, so the convenience provided by the alternative constructor `CensoredData.right_censored` is less important.  If we went with this API, I would probably remove the `left_censored` and `right_censored` methods.

There is redundancy here, because (assuming we interpret intervals containing ±inf and intervals with length 0 the same as they are interpreted in the other API), any value that can be represent with `x`, `left` or `right` can also be represented as an interval.  That is, the right-censored example could also be represented as

    CensoredData(intervals=[[13, 13], [22, 22], [17, 17], [15, 15], [20, np.inf], [20, np.inf]])

But that isn't necessarily a problem.

**Comment by rkern** [comment] 2021-03-27 21:21
There are a few existing packages for doing survival analysis. We may want to think about how this representation interfaces with them. The one I am most familiar with is [`lifelines`](https://pypi.org/project/lifelines/). [This is its basic tutorial that walks through how it works with censored data.(https://lifelines.readthedocs.io/en/latest/Survival%20analysis%20with%20lifelines.html)

**Comment by WarrenWeckesser** [comment] 2021-03-29 02:26
I took a look at some of the survival analysis packages. (This is not a thorough survey.)

* [`lifelines`](https://pypi.org/project/lifelines/)
   Their [`KaplanMeierFitter`](https://lifelines.readthedocs.io/en/latest/fitters/univariate/KaplanMeierFitter.html) class has separate methods for fitting [right-censored](https://lifelines.readthedocs.io/en/latest/fitters/univariate/KaplanMeierFitter.html#lifelines.fitters.kaplan_meier_fitter.KaplanMeierFitter.fit), [left-censored](https://lifelines.readthedocs.io/en/latest/fitters/univariate/KaplanMeierFitter.html#lifelines.fitters.kaplan_meier_fitter.KaplanMeierFitter.fit), and [interval-censored](https://lifelines.readthedocs.io/en/latest/fitters/univariate/KaplanMeierFitter.html#lifelines.fitters.kaplan_meier_fitter.KaplanMeierFitter.fit) data.  For fitting left- and right-censored data, the user provides an array of durations and a boolean "event" array that indicates if the "death" event was observed (i.e. this is a flag that indicates censoring). For interval-censored data, the user gives two arrays that hold the lower and upper bounds of the intervals.
* [`scikit-survival`](https://pypi.org/project/scikit-survival/)
  An example of how this package handles right-censored data is in the section [Survival Data](https://scikit-survival.readthedocs.io/en/stable/user_guide/00-introduction.html#Survival-Data): like the other packages, there are durations with boolean flags to indicated right-censoring.
* [`pysurvival`](https://pypi.org/project/pysurvival/) (last release April 2019)
  The [`fit`](https://square.github.io/pysurvival/models/coxph.html#methods) method of their Cox proportional hazard class [`CoxPHModel`](https://square.github.io/pysurvival/models/coxph.html) accepts arguments `T` and `E` similar the those used in `lifelines`: `E` is a boolean flag that indicates censored data.
* [`survive`](https://pypi.org/project/survive/) (last release August 2018)
  This package has a [`SurvivalData`](https://survive-python.readthedocs.io/generated/survive.SurvivalData.html#survive.SurvivalData) class that can represent censored data.  The relevant constructor parameters look similar to the parameters described above: an array of times, and a boolean array (called `status` in this case) to specify if the data is right-censored.  It has another optional array, `entry`, described as "Entry/birth times of the observations (for left-truncated data)."

Given the above APIs, and given the frequency with which I found examples in which the censoring was indicated as a 0/1 status column in a table of durations, I think it would probably be useful to keep the [alternative constructors](https://campus.datacamp.com/courses/object-oriented-programming-in-python/inheritance-and-polymorphism?ex=4) `right_censored(x, censored)` and `left_censored(x, censored)` (where `x` is the array of observations and `censored` is the boolean array holding the censored flag), regardless of the signature of the `CensoredData` constructor.  Then the constructor can provide a flexible way to create an arbitrary mix of different types of censored and uncensored data, while the alternative constructors provide a clean simple API to handle some common use-cases.

**Comment by WarrenWeckesser** [comment] 2021-04-02 19:55
I do like the constructor API with `x`, `left`, `right` and `intervals` given explicitly, so the user doesn't have to fill in ±inf values for left- and right-censored data.   I'm currently updating the [PR](https://github.com/scipy/scipy/pull/13699) so that the signature of the constructor is `def __init__(self, x=None, *, left=None, right=None, intervals=None):`.

**Comment by mdhaber** [comment] 2021-04-03 00:25
@WarrenWeckesser has thought about this the most carefully, so whatever he decides sounds good to me. 

But I think that the original `lower`/`upper` API was fine and would be most familiar to users. 

The R package `fitdistrplus` uses `left` and `right` to mean the same things:
> Censored data may thus contain left-censored, right-censored and interval-censored values, with several lower and
upper bounds. Before their use in package fitdistrplus, such data must be coded into a dataframe with two columns,
respectively named `left` and `right`, describing each observed value as an interval. The `left` column contains either
`NA` for `left` censored observations, the left bound of the interval for interval censored observations, or the observed value
for non-censored observations. The `right` column contains either `NA` for right censored observations, the right bound
of the interval for interval censored observations, or the observed value for non-censored observations.

Looking elsewhere within SciPy, we have the very similar concept of lower and upper bounds in our optimizers. For instance, the `Bounds` class accepts these as `lb` and `ub`:

> `lb`, `ub`       array_like, optional
Lower and upper bounds on independent variables. Each array must have the same size as `x` or be a scalar, in which case a bound will be the same for all the variables. Set components of `lb` and `ub` equal to fix a variable. Use `np.inf` with an appropriate sign to disable bounds on all or some variables. Note that you can mix constraints of different types: interval, one-sided or equality, by setting different components of `lb` and `ub` as necessary.

This is what Matlab `fmincon` does, too:

> `x = fmincon(fun,x0,A,b,Aeq,beq,lb,ub)` defines a set of lower and upper bounds on the design variables in x, so that the solution is always in the range `lb ≤ x ≤ ub`... If `x(i)` is unbounded below, set `lb(i) = -Inf`, and if `x(i)` is unbounded above, set `ub(i) = Inf`.

So I don't see a need to reinvent this API if the documentation is clear.

**Comment by WarrenWeckesser** [comment] 2021-04-04 20:37
I updated the `CensoredData` implementation to use the four inputs.  I think it is a better API because each input represents the input type with only the relevant information, with no redundancy and no extra boilerplate.  In more detail:

* There is no need to enter the same value twice to represent an uncensored value (DRY!).  A regular (i.e. uncensored) value is just a single number, so it is simpler to be able to enter it as such.

  After using the lower/upper API for a while (in R and in the first version of the PR), I started to find the use of duplicated values to represent uncensored data to be a nuisance.  If one enters an example such as `CensoredData(lower=[1.4, 2.0, 0.9, 4.5, 4.0, 4.4, 4.0, 0.3], upper=[1.4, 2.0, 0.9, 4.6, 4.0, 4.4, 4.1, 0.3])`, one has to inspect those two sequences carefully to figure out which, if any, are interval-censored.  The new version, `CensoredData(x=[1.4, 2.0, 0.9, 4.0, 4.4, 0.3], intervals=[[4.5, 4.6], [4.0, 4.1]])` is much clearer.

  Also note that there is no  advantage *in the code* in using the lower/upper version with the repeated values for uncensored data. The code has to check for this case and handle these values differently than the case where `lower[i] < upper[i]`.

* There is no need to enter ±inf (with the appropriate sign in the appropriate slot) to represent left- or right-censored data.  In the lower/upper implementation, those ±inf value served as flags to indicate the censoring type.  The code didn't actually evaluate any function at ±inf. Instead, it checked for those values and called the `cdf` or `sf` method as appropriate.  So those ±inf values were basically boilerplate used to provide information that can be given in a simpler form with the `left` and `right` parameters.

**Comment by mdhaber** [comment] 2022-08-29 03:50
*Moved from gh-13699*

This PR introduces a `CensoredData` class to represent censored data, i.e., data which is not known precisely, but known to be within an interval. For example, suppose I want to fit a distribution to four observations:

- The first observation is not censored; it is known to be exactly 1.
- The second observation is "left-censored" - less than 2, but otherwise unknown.
- The third observation is "right-censored" - greater than 3, but otherwise unknown.
- The fourth observation is "interval-censored" - known to lie somewhere between 4 and 5.

Maximum likelihood estimation is naturally extended to data in this form using the CDF/SF in place of PDF. I've reviewed the implementation details in this PR, but I need your opinion on the interface.

There are two APIs for `CensoredData` on the table.

One concept (say A) would have an initializer where in which the user specifies the lower and upper bounds for the range each observation is known to lie within, like `bounds` in optimization.:
```python3
x = CensoredData(lower=[1, -np.inf, 3, 4], 
                 upper=[1, 2, np.inf, 5])
```

The other (B) have uncensored, left-censored, right-censored, and interval-censored data specified separately:
```python3
x = CensoredData(x=[1], left=[2], right=[3], intervals=[4, 5])
```

[`fitdistrplus`](https://cran.r-project.org/web/packages/fitdistrplus/fitdistrplus.pdf) (which is probably the most popular and advanced software for doing this sort of thing, at least in R) uses `left` and `right` bounds, like option A, but with different names:
![image](https://user-images.githubusercontent.com/6570539/187116958-87fcbc10-40f9-4fa7-9e54-e64eb2b2edbd.png)

SAS seems to specify lower and upper limits with `rc` and `lc`.
https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/etsug/etsug_severity_examples06.htm

Statgraphics has left and right columns:
https://www.statgraphics.com/blog/classificationregressiontrees-0

Apparently, Matlab only does right-censored data.
![image](https://user-images.githubusercontent.com/6570539/187116489-7c1c3466-a1d6-45bc-b987-76d98e8bfde3.png)

A few other examples are in the comment above https://github.com/scipy/scipy/issues/13757#issuecomment-809022298.

Which option do you think we should go with?
@tupui @tirthasheshpatel @chrisb83 @ev-br et al

**Comment by tupui** [comment] 2022-08-29 06:16
My vote goes for A (bounds interface). To me it's clearer and closer to what SciPy users are used to.

**Comment by mdhaber** [comment] 2023-01-08 07:50
@tupui That was my preference, too, but whatever we pick as the interface of the class itself, we can use classmethods for the rest. (E,g,, there are already `right_censored` and `left_censored` classmethods.) In an enhancement, I think we will add an `interval_censored` classmethod, and I think that would address what we're looking for.

For the main class itself, it is good to _store_ the four separate kinds of censored data separately because they are used differently in the fitting procedure, so it is reasonable for the main constructor to accept the four different kinds separately.

If it sounds good to you, I'll close this with the conclusion that gh-13699 implements what is described in https://github.com/scipy/scipy/issues/13757#issuecomment-813095887.

**Comment by tupui** [comment] 2023-01-09 12:39
Fine with me 👍

**Closed** 2023-02-20 10:30 UTC
Labels: scipy.stats, enhancement
