### ISSUE TITLE
improve simps accuracy with some number of points

### ISSUE THREAD

**Issue by JrPhy** [scipy/scipy#9871] opened 2019-02-25 06:21 UTC
**### Problem**
As I used simpson in scipy, I found there some issue about it. Simpson's 1/3 rule use parabola eq. to approximate every curve in the segment, to determine the parabola, it needs 3 points, so that is the constraint of 1/3 rule. It just apply to odd number well, but inaccurate as the number is even. 
**### Solution**
Combine 1/3 and 3/8 rule, so that simpson's rule apply every number of point.
**### Result**
```
import numpy as np
from scipy.integrate import simps
def f(x):
    return x**3


x = np.linspace(1.0, 4.0, 20)
y = f(x)
a = simps(y,x)

x = np.linspace(1.0, 4.0, 19)
y = f(x)
b = simps(y,x)

print (a, b)

correct result is 63.75
```
result1 should be more accurate than result2 because of the smaller h, 
but result1 = 63.7549, result2 = 63.7499
I just write a C version and I uploaded it in my github, there is also the derivation of simpson rule.
https://github.com/JrPhy/numerical/tree/master/Integration

**Comment by SyedSaifAliAlvi** [comment] 2019-03-03 00:34
After plotting a graph for this code, what I have observed is that except the value 2 of **h** the value for every _even_ **h** the result is always higher than the odd **h**. Simpson's 1/3 rule works when n is even, but from graph it is observed that Simpson's 3/8 rule works for the **multiple of 3** therefore if we take **h** as **prime** numbers which are neither **even** nor **odd** numbers then the result will always be **smaller** than even number as well as for odd numbers.
![figure_1](https://user-images.githubusercontent.com/43503954/53689346-89939b00-3d79-11e9-8560-fd6b1233b003.png)

**Comment by JrPhy** [comment] 2019-03-04 02:52
I found this issue has been brought out in the following post,
[](https://github.com/scipy/scipy/issues/5618)
and it seems that simps apply trapezoidal rule as h is multiple of 2.
https://github.com/scipy/scipy/blob/v1.2.1/scipy/integrate/quadrature.py#L366-L488
So using 1/3 and 3/8 rule when h is prime number, that is much more accurate than trapezoidal rule, and it can apply n interval (n >= 2, and n is positive integer).
For example, n is even, then just apply 1/3 rule. n is prime, then use 3/8 rule for first 3 interval, then apply 1/3 for the others.

**Comment by mdhaber** [comment] 2022-04-16 06:37
This seems to be a duplicate of gh-5618. Let's track this over there.

**Closed by mdhaber** 2022-04-16 06:37 UTC
Labels: scipy.integrate
