### ISSUE TITLE
ordering of curve_fit input

### ISSUE THREAD

**Issue by oxlade39** [scipy/scipy#10287] opened 2019-06-10 10:16 UTC
The ordering of x and y data appears to have significant (at lest to me) impact on the output parameters.

In my naive interpretation of `curve_fit` I would expect the output to be the same curve irrespective of the order of points.

I suspect this is just my misunderstanding, if that's the case it would be good to have something captured in the docs as a guide.

### Reproducing code example:

```python
import pytest
from pytest import fixture
from scipy.optimize import curve_fit

import numpy as np

def nelson_siegel(time, beta_0, beta_1, beta_2, tau):
    t_tau = time / tau
    exp_t_tau = np.exp(-t_tau)
    return beta_0 + beta_1 * (1 - exp_t_tau) / (t_tau) + beta_2 * ((1 - exp_t_tau) / (t_tau) - exp_t_tau)

@fixture
def data():
    return np.array([
        [5.4294, 5.4293],
        [5.8674, 5.8718],
        [2.7585, 2.7524],
        [1.9344, 1.9374],
        [2.9423, 2.9491],
        [1.241, 1.243],
        [3.6387, 3.657],
        [4.6849, 3.5774]
    ])


def scipy_example(x, a, b, c):
    """
    the example from the scipy curve_fit docs
    """
    return a * np.exp(-b * x) + c


# @pytest.mark.xfail(reason="curve_fit seems to be order dependent")
@pytest.mark.parametrize("curve_fit_func", [
    (nelson_siegel),
    (scipy_example),
])
def test_curve_fit_order_independent(data, curve_fit_func):
    attempt1 = run_curve_fit(curve_fit_func, data)

    shuffled_data = np.copy(data)
    np.random.shuffle(shuffled_data)
    attempt2 = run_curve_fit(curve_fit_func, shuffled_data)

    np.testing.assert_allclose(attempt1, attempt2)


def run_curve_fit(curve_fit_func, data):
    xdata = data[:, 0]
    ydata = data[:, 1]
    optimized_params, _ = curve_fit(curve_fit_func, xdata=xdata, ydata=ydata)
    return optimized_params

```
### Scipy/Numpy/Python version information:

scipy: 1.3.0
numpy: 1.16.1
sys.version_info: major 3, minor 7 micro 1

**Comment by ewmoore** [comment] 2019-06-11 02:29
I don't think that this is something that you should expect.  It is probably true in general, when the model fits well and the scaling is good, etc. 

For both of your examples, you aren't providing `p0`, the initial parameter guess, to `curve_fit`.  If you don't provide `p0`, it will be set to all ones.  This is a is a very poor guess for these fits.  Providing `p0` won't correct your issue, but you really shouldn't be calling `curve_fit` without it.

For your `scipy_example`, I find `curve_fit` results of 
```
In [110]: a = curve_fit(scipy_example, data[:,0], data[:,1])
C:\Users\eric.moore\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\minpack.py:785: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)

In [111]: a
Out[111]: 
(array([ 8.91539935, 19.40919999,  3.42717501]), array([[inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf]]))

In [112]: datas = data.copy()

In [113]: np.random.shuffle(datas)

In [114]: b = curve_fit(scipy_example, datas[:,0], datas[:,1])
C:\Users\eric.moore\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\minpack.py:785: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)

In [115]: b
Out[115]: 
(array([ 8.91539935, 19.40919999,  3.42717501]), array([[inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf]]))
```
This would pass your `assert_allclose` test, but the fits are garbage (plot them and see).  That you shouldn't trust these results is hinted at by failure to estimate the covariance matrix.

For your `nelson_seigel` example I find
```
In [116]: a = curve_fit(nelson_siegel, data[:,0], data[:,1])

In [117]: a
Out[117]: 
(array([ 181.1834945 , -181.09100325, 3440.81058124, 1931.68636674]),
 array([[ 3.95971915e+12, -3.95971718e+12, -3.92355895e+12,
          2.19975822e+10],
        [-3.95971718e+12,  3.95971522e+12,  3.92355708e+12,
         -2.19975299e+10],
        [-3.92355880e+12,  3.92355693e+12,  3.93584394e+12,
          3.94158802e+09],
        [ 2.19976625e+10, -2.19976102e+10,  3.94150762e+09,
          1.38904774e+10]]))

In [118]: b = curve_fit(nelson_siegel, datas[:,0], datas[:,1])

In [119]: b
Out[119]: 
(array([ 180.95497736, -180.86276529, 2793.92663671, 1585.94850365]),
 array([[ 2.35748741e+12, -2.35748532e+12, -2.21966178e+12,
          7.56884325e+10],
        [-2.35748532e+12,  2.35748324e+12,  2.21965988e+12,
         -7.56883320e+10],
        [-2.21966170e+12,  2.21965980e+12,  2.11187576e+12,
         -5.94991805e+10],
        [ 7.56884741e+10, -7.56883737e+10, -5.94992221e+10,
          8.72604768e+09]]))

In [120]: nelson_siegel(data[:,0], *a[0]) - nelson_siegel(data[:,0], *b[0])
Out[120]: 
array([ 2.84462726e-04,  4.55701267e-04, -2.08491184e-04, -1.69056518e-04,
       -2.04953960e-04, -6.57759994e-05, -1.50775528e-04,  5.17928821e-05])
```
This time the fit results seem quite different, but the difference in values of `nelson_siegel` is pretty small.  Given the size of the entries in the covariance matrix, I'd say that the difference is meaningless.  This is handwavy, but doesn't have to be.  Any estimate of the uncertainty in your fit parameters that you would like to make from the computed covariance matrix will certainly be larger than the differences observed in the optimal parameters here. 

In general, an `allclose` like approach is not a sufficient way to evaluate the results of curve fitting.

I'm going to close this, but the discussion can continue and feel free to re-open if there is something actionable here.

**Closed by ewmoore** 2019-06-11 02:29 UTC

**Comment by oxlade39** [comment] 2019-06-11 11:15
thanks @ewmoore, very informative and helpful write up.

**Comment by oxlade39** [comment] 2019-06-11 11:47
@ewmoore potentially stupid question but _why_ is it wrong to expect the results to be the same?

**Comment by ewmoore** [comment] 2019-06-12 01:07
I think there are at least two issues.  Since this runs on a computer, changing the data means that you've reordered the arithmetic which can change your results.  Secondly, curve fitting is local minimization and small changes can push you from ending up in one local minima to another.  These kinds of things are why even though your `nelson_siedel` results are not numerical identical they are probably statistically indistinguishable.

Can I ask what you are trying to do?  Does it really matter if you get identical results with the data shuffled?  If you don't control the order the data is in, you could always sort it first to ensure it is at least in a consistent order.

I once read a paper that looked at the condition number for polynomial regression when the independent data was on [-1, 1] vs elsewhere.   I mention this, since I swear someone linked to in here, but I'm not having any luck locating it again.
