### ISSUE TITLE
`linalg` test failures on ARMv7

### ISSUE THREAD

**Issue by person142** [scipy/scipy#8638] opened 2018-03-31 19:13 UTC
On SciPy master and Numpy 1.14.2 compiled against OpenBLAS 0.2.19 there are a number of `linalg` test failures on ARMv7. The pytest report is below; note that it is not an exhaustive list because some of the failures are random (I've seen between 16 and 20 failures in various runs). The OpenBLAS test suite itself does not pass on ARMv7, and there are some open issues related to that, see e.g.

https://github.com/xianyi/OpenBLAS/issues/1469.

On the other hand, I also built SciPy and NumPy against the reference BLAS from Netlib and still got 16 failures. In particular a number of QR tests failed, so it's possible there's a Lapack bug here.

<details><p>

```
=================================== FAILURES ===================================
__________________ TestQRdelete_D.test_non_unit_strides_1_row __________________
scipy/linalg/tests/test_decomp_update.py:413: in test_non_unit_strides_1_row
    self.base_non_simple_strides(make_strided, [0], 1, 'row', True)
scipy/linalg/tests/test_decomp_update.py:387: in base_non_simple_strides
    assert_allclose(q1o, qs[qind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 100.0%)
E    x: array([[ 0.114976+0.004246j, -0.437634+0.403144j,  0.236101+0.209689j,
E           -0.039197+0.28843j ,  0.066607+0.081378j,  0.161066+0.088853j,
E            0.399468+0.493763j],...
E    y: array([[-0.353762-0.304882j, -0.402985+0.085972j,  0.125009+0.263682j,
E            0.014609+0.130363j,  0.00994 +0.016723j,  0.671656+0.206726j,
E            0.011925-0.050819j],...
__________________ TestQRdelete_D.test_non_unit_strides_p_row __________________
scipy/linalg/tests/test_decomp_update.py:416: in test_non_unit_strides_p_row
    self.base_non_simple_strides(make_strided, [0], 3, 'row', True)
scipy/linalg/tests/test_decomp_update.py:388: in base_non_simple_strides
    assert_allclose(r1o, r[rind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 75.0%)
E    x: array([[ 2.073943+0.083551j,  1.068157+0.622862j,  1.723715+0.455052j,
E            1.246242+0.489663j,  1.891564-0.075042j,  1.490349+0.367032j,
E            1.350679+0.357184j,  1.036061+0.432541j],...
E    y: array([[ 0.      +0.j      ,  0.      +0.j      ,  0.      +0.j      ,
E           -0.876327+0.j      , -0.062765+0.0082j  , -0.23834 -0.361606j,
E           -0.555406+0.230921j, -0.140526-0.182979j],...
__________________ TestQRdelete_D.test_non_unit_strides_1_col __________________
scipy/linalg/tests/test_decomp_update.py:419: in test_non_unit_strides_1_col
    self.base_non_simple_strides(make_strided, [0], 1, 'col', True)
scipy/linalg/tests/test_decomp_update.py:387: in base_non_simple_strides
    assert_allclose(q1o, qs[qind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 100.0%)
E    x: array([[-0.470378+0.148768j, -0.327539+0.427345j, -0.352683-0.062644j,
E            0.045918-0.062432j,  0.001171+0.310381j, -0.009056-0.045637j,
E            0.195359+0.228491j,  0.378469-0.016649j],...
E    y: array([[-0.171986-0.066641j, -0.58084 +0.088611j, -0.008821-0.44756j ,
E            0.13044 -0.255786j, -0.172191+0.020917j,  0.084916-0.326408j,
E           -0.167073+0.035869j,  0.373178+0.160072j],...
____________________ TestQRdelete_D.test_overwrite_qr_1_row ____________________
scipy/linalg/tests/test_decomp_update.py:510: in test_overwrite_qr_1_row
    self.base_overwrite_qr('row', 1, True, True)
scipy/linalg/tests/test_decomp_update.py:498: in base_overwrite_qr
    assert_allclose(r2, r[rind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 62.5%)
E    x: array([[ 1.297803-1.312569j,  1.020581-0.513708j,  1.494556-1.261963j,
E            1.175505-0.642718j,  1.338209-1.39818j ,  1.581688-1.040621j,
E            1.380648-1.063749j,  1.192893-0.696832j],...
E    y: array([[ 0.      +0.j      , -1.338042+0.j      , -0.644328-0.171459j,
E           -1.31287 -0.474762j, -0.254964-0.284247j, -0.409102+0.141397j,
E           -0.541556-0.288711j, -1.20341 -0.112267j],...
_______________ TestQRdelete_D.test_overwrite_economic_qr_1_row ________________
scipy/linalg/tests/test_decomp_update.py:514: in test_overwrite_economic_qr_1_row
    self.base_overwrite_qr('row', 1, True, True, 'economic')
scipy/linalg/tests/test_decomp_update.py:498: in base_overwrite_qr
    assert_allclose(r2, r[rind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 62.5%)
E    x: array([[ 1.297803-1.312569j,  1.020581-0.513708j,  1.494556-1.261963j,
E            1.175505-0.642718j,  1.338209-1.39818j ,  1.581688-1.040621j,
E            1.380648-1.063749j,  1.192893-0.696832j],...
E    y: array([[ 0.      +0.j      , -1.338042+0.j      , -0.644328-0.171459j,
E           -1.31287 -0.474762j, -0.254964-0.284247j, -0.409102+0.141397j,
E           -0.541556-0.288711j, -1.20341 -0.112267j],...
____________________ TestQRdelete_D.test_overwrite_qr_1_col ____________________
scipy/linalg/tests/test_decomp_update.py:519: in test_overwrite_qr_1_col
    self.base_overwrite_qr('col', 1, True, True)
scipy/linalg/tests/test_decomp_update.py:505: in base_overwrite_qr
    assert_allclose(q3, q[qind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 62.5%)
E    x: array([[-0.171986-0.066641j, -0.58084 +0.088611j, -0.008821-0.44756j ,
E           -0.16087 -0.024818j, -0.296091-0.072194j,  0.244529-0.00627j ,
E            0.095314-0.262859j,  0.252873+0.314691j],...
E    y: array([[-0.171986-0.066641j, -0.58084 +0.088611j, -0.008821-0.44756j ,
E            0.13044 -0.255786j, -0.172191+0.020917j,  0.084916-0.326408j,
E           -0.167073+0.035869j,  0.373178+0.160072j],...
____________________ TestQRdelete_D.test_overwrite_qr_p_row ____________________
scipy/linalg/tests/test_decomp_update.py:523: in test_overwrite_qr_p_row
    self.base_overwrite_qr('row', 3, True, True)
scipy/linalg/tests/test_decomp_update.py:505: in base_overwrite_qr
    assert_allclose(q3, q[qind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 100.0%)
E    x: array([[-0.350984+0.10057j ,  0.15951 -0.602123j, -0.476243-0.303238j,
E           -0.023296+0.040536j, -0.320374+0.234763j],
E          [-0.222921+0.020288j,  0.483365-0.139828j, -0.148692+0.367559j,...
E    y: array([[-0.141229-0.17327j ,  0.494585+0.247272j, -0.024942-0.369029j,
E           -0.016727+0.066348j, -0.234192-0.305776j],
E          [ 0.135869+0.435051j, -0.094888+0.164944j,  0.062619+0.297246j,...
_______________ TestQRdelete_D.test_overwrite_economic_qr_p_row ________________
scipy/linalg/tests/test_decomp_update.py:527: in test_overwrite_economic_qr_p_row
    self.base_overwrite_qr('row', 3, True, True, 'economic')
scipy/linalg/tests/test_decomp_update.py:497: in base_overwrite_qr
    assert_allclose(q2, q[qind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 100.0%)
E    x: array([[-0.350984+0.10057j ,  0.15951 -0.602123j, -0.476243-0.303238j,
E           -0.023296+0.040536j, -0.320374+0.234763j],
E          [-0.222921+0.020288j,  0.483365-0.139828j, -0.148692+0.367559j,...
E    y: array([[-0.141229-0.17327j ,  0.494585+0.247272j, -0.024942-0.369029j,
E           -0.016727+0.066348j, -0.234192-0.305776j],
E          [ 0.135869+0.435051j, -0.094888+0.164944j,  0.062619+0.297246j,...
____________________ TestQRdelete_D.test_overwrite_qr_p_col ____________________
scipy/linalg/tests/test_decomp_update.py:532: in test_overwrite_qr_p_col
    self.base_overwrite_qr('col', 3, False, True)
scipy/linalg/tests/test_decomp_update.py:498: in base_overwrite_qr
    assert_allclose(r2, r[rind], rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 22.5%)
E    x: array([[-2.142752+0.j      , -1.364091-0.531449j, -2.066515-0.388599j,
E           -1.685997-0.313984j, -1.278609-0.455343j],
E          [ 0.      +0.j      , -1.338042+0.j      , -0.644328-0.171459j,...
E    y: array([[-2.142752+0.j      , -1.364091-0.531449j, -2.066515-0.388599j,
E           -1.612225-0.548939j, -2.00215 +0.054686j],
E          [ 0.      +0.j      , -1.338042+0.j      , -0.644328-0.171459j,...
___________________ TestQRinsert_D.test_overwrite_qu_rank_1 ____________________
scipy/linalg/tests/test_decomp_update.py:1067: in test_overwrite_qu_rank_1
    assert_allclose(q2, q, rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 100.0%)
E    x: array([[-0.311333+0.008185j, -0.254161+0.083238j,  0.368645-0.291183j,
E            0.478632+0.165724j, -0.216685-0.242922j,  0.026033+0.023933j,
E           -0.144524+0.24679j ,  0.394915+0.096303j],...
E    y: array([[-0.171986-0.066641j, -0.58084 +0.088611j, -0.008821-0.44756j ,
E            0.13044 -0.255786j, -0.172191+0.020917j,  0.084916-0.326408j,
E           -0.167073+0.035869j,  0.373178+0.160072j],...
___________________ TestQRinsert_D.test_overwrite_qu_rank_p ____________________
scipy/linalg/tests/test_decomp_update.py:1098: in test_overwrite_qu_rank_p
    assert_allclose(q2, q, rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 100.0%)
E    x: array([[-0.322805-0.183455j, -0.133701-0.168817j,  0.125567+0.043635j,
E           -0.16314 -0.130849j, -0.379647-0.431314j, -0.506883-0.145399j,
E            0.120827-0.34626j ,  0.08207 -0.069945j],...
E    y: array([[-0.171986-0.066641j, -0.58084 +0.088611j, -0.008821-0.44756j ,
E            0.13044 -0.255786j, -0.172191+0.020917j,  0.084916-0.326408j,
E           -0.167073+0.035869j,  0.373178+0.160072j],...
_________________ TestQRupdate_D.test_non_unit_strides_rank_1 __________________
scipy/linalg/tests/test_decomp_update.py:1408: in test_non_unit_strides_rank_1
    self.base_non_simple_strides(make_strided, 'full', 1, True)
scipy/linalg/tests/test_decomp_update.py:1354: in base_non_simple_strides
    assert_allclose(r1o, r, rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 56.25%)
E    x: array([[-2.227355+1.463994j, -2.179129+0.168082j, -3.270039+0.665583j,
E           -3.215793+0.835159j, -3.205343+1.323253j, -2.902124+0.867753j,
E           -2.239301+1.434655j, -2.458821-0.147473j],...
E    y: array([[-2.142752+0.j      , -1.364091-0.531449j, -2.066515-0.388599j,
E           -1.612225-0.548939j, -2.00215 +0.054686j, -1.736561-0.270973j,
E           -1.685997-0.313984j, -1.278609-0.455343j],...
_____________ TestQRupdate_D.test_non_unit_strides_economic_rank_1 _____________
scipy/linalg/tests/test_decomp_update.py:1411: in test_non_unit_strides_economic_rank_1
    self.base_non_simple_strides(make_strided, 'economic', 1, True)
scipy/linalg/tests/test_decomp_update.py:1367: in base_non_simple_strides
    assert_allclose(v, v0.conj(), rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 100.0%)
E    x: array([0.193606+0.615199j, 0.340402+0.305685j, 0.617014+0.394481j,
E          0.888258+0.809212j, 0.896568+0.615594j, 0.674335+0.534635j,
E          0.249524+0.940595j, 0.556358+0.1725j  ])
E    y: array([0.193606-0.615199j, 0.340402-0.305685j, 0.617014-0.394481j,
E          0.888258-0.809212j, 0.896568-0.615594j, 0.674335-0.534635j,
E          0.249524-0.940595j, 0.556358-0.1725j  ])
__________________ TestQRupdate_D.test_overwrite_qruv_rank_1 ___________________
scipy/linalg/tests/test_decomp_update.py:1483: in test_overwrite_qruv_rank_1
    assert_allclose(r3, r, rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 56.25%)
E    x: array([[-2.227355+1.463994j, -2.179129+0.168082j, -3.270039+0.665583j,
E           -3.215793+0.835159j, -3.205343+1.323253j, -2.902124+0.867753j,
E           -2.239301+1.434655j, -2.458821-0.147473j],...
E    y: array([[-2.142752+0.j      , -1.364091-0.531449j, -2.066515-0.388599j,
E           -1.612225-0.548939j, -2.00215 +0.054686j, -1.736561-0.270973j,
E           -1.685997-0.313984j, -1.278609-0.455343j],...
______________ TestQRupdate_D.test_overwrite_qruv_rank_1_economic ______________
scipy/linalg/tests/test_decomp_update.py:1505: in test_overwrite_qruv_rank_1_economic
    assert_allclose(r2, r, rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 57.142857142857146%)
E    x: array([[-3.249952+0.035729j, -2.793   +0.35533j , -3.161003+1.45326j ,
E           -4.078968+1.803646j, -3.754566+2.475408j, -3.896384+1.859669j,
E           -2.348558+1.930153j],...
E    y: array([[-3.199241+0.j      , -2.189955+0.23893j , -1.646726+0.472932j,
E           -2.403326+0.417764j, -2.488816+0.371479j, -2.192566+0.199489j,
E           -2.120478-0.066419j],...
__________________ TestQRupdate_D.test_overwrite_qruv_rank_p ___________________
scipy/linalg/tests/test_decomp_update.py:1535: in test_overwrite_qruv_rank_p
    assert_allclose(r2, r, rtol=self.rtol, atol=self.atol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=2.22045e-15
E   
E   (mismatch 56.25%)
E    x: array([[ 5.408811+0.j      ,  7.300227-1.419856j,  7.039324+0.615977j,
E            6.502788-0.020488j,  8.139834-0.164839j,  6.349751-0.927466j,
E            5.914325-1.766192j,  4.898647-0.784424j],...
E    y: array([[-2.142752+0.j      , -1.364091-0.531449j, -2.066515-0.388599j,
E           -1.612225-0.548939j, -2.00215 +0.054686j, -1.736561-0.270973j,
E           -1.685997-0.313984j, -1.278609-0.455343j],...
____________________ TestInterpolativeDecomposition.test_id ____________________
scipy/linalg/tests/test_interpolative.py:47: in test_id
    self.check_id(dtype)
scipy/linalg/tests/test_interpolative.py:89: in check_id
    assert_(np.allclose(A, B, eps))
E   AssertionError
___________________________________ test_rot ___________________________________
scipy/linalg/tests/test_lapack.py:518: in test_rot
    assert_(a is u)
E   AssertionError
== 18 failed, 1332 passed, 3 skipped, 3 xfailed, 2 xpassed in 324.43 seconds ===
```

</p></details>

### Scipy/Numpy/Python version information:
```
1.1.0.dev0+e122026 1.14.2 sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
```

**Comment by stuartarchibald** [comment] 2018-04-30 13:15
I've been looking at this and writing notes in https://github.com/numba/numba/pull/1968. The following is from building the NumPy/SciPy/Numba stack on a RPi 3B+ running Raspbian GNU/Linux 9 (stretch) with Python from [Berryconda](https://github.com/jjhelmus/berryconda). Everything below is based on running near-latest development versions from github, built from source, and Netlib LAPACK 3.8 compiled with `-O0 -g` using stock compilers.

The tests above ostensibly involving failures from BLAS/LAPACK all use `np.complex128` dtypes and the BLAS function `zrot` (QR updates will likely apply planar rotations to reorthogonalise, this can be done in-place with `zrot`).
* First, writing some Fortran for the equivalent of the above failing operations confirms Netlib BLAS `zrot` works fine when compiled with stock compilers, it doesn't appear to be at fault.
* Second, messing about in gdb for a bit I noticed that the when the rotations were being applied, sometimes they were not applied in-place and in fact an allocation path was taken whereby the result of the rotation applied to an array column ended up in new memory (hence wrong results as the original array wasn't being updated). This was about 3 layers deep in templated autogenerated code, so you'll have to excuse my not presenting the source, however the point is moot as will transpire below.
* Third, whilst debugging the Numba typing system (which sporadically kept dispatching the to the wrong compiled specialisation) it became apparent that allocations of the type `complex128` were not always aligned.

Essentially, I think the above fails are down to NumPy making incorrect assumptions about the alignment of the base pointer for `complex128` allocations. Whilst incorrectly aligned data is seemingly often read ok, anything depending on aligned data will sporadically fail at the whim of whether the memory has been allocated at a declared-aligned address or not. This I think explains:
 * Why the failures are inconsistent (malloc sometimes hits the right alignment and sometimes does not).
 * Why LAPACK appears to be at fault (but it is not the fault of LAPACK, it is the wrapper dispatching to LAPACK that decides to allocate new memory as it can't write to an unaligned address).

Looking at the NumPy source, I think the root cause of the problem stems from here:

https://github.com/numpy/numpy/blob/36d969994d59cd0ce960e773b230b8e48082adfc/numpy/core/src/multiarray/arraytypes.c.src#L4367

which when expanded out from `np.complex128` looks like:
```
    /* alignment */
    2 * _ALIGN(npy_double) > NPY_MAX_COPY_ALIGNMENT ?
        NPY_MAX_COPY_ALIGNMENT : 2 * _ALIGN(npy_double),
```

evaluating this yields:
```
 2 * 8 > NPY_MAX_COPY_ALIGNMENT ? NPY_MAX_COPY_ALIGNMENT : 2 * 8
```

`NPY_MAX_COPY_ALIGNMENT`  is defined here:

https://github.com/numpy/numpy/blob/36d969994d59cd0ce960e773b230b8e48082adfc/numpy/core/src/private/npy_config.h#L9-L22

and, due to the lack of identification for ARMv7 as 32bit here:

https://github.com/numpy/numpy/blob/36d969994d59cd0ce960e773b230b8e48082adfc/numpy/core/include/numpy/npy_cpu.h#L25

the `alignment` member of the struct ends up as `16`.

Fixing this issue locally in NumPy to force the allocation to behave as per a 32 bit machine leads to SciPy having no test failures related to QR/`zrot` or indeed sporadic failures. Running the test suite again merely yields the following two failures:

<details>

```
=================================== FAILURES ===================================
_______________________ TestNdimage.test_white_tophat03 ________________________

self = <scipy.ndimage.tests.test_ndimage.TestNdimage object at 0x6d235630>

    def test_white_tophat03(self):
        array = numpy.array([[1, 0, 0, 0, 0, 0, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 0, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 0, 0, 0, 0, 0, 1]], dtype=numpy.bool_)
        structure = numpy.ones((3, 3), dtype=numpy.bool_)
        expected = numpy.array([[0, 1, 1, 0, 0, 0, 0],
                                [1, 0, 0, 1, 1, 1, 0],
                                [1, 0, 0, 1, 1, 1, 0],
                                [0, 1, 1, 0, 0, 0, 1],
                                [0, 1, 1, 0, 1, 0, 1],
                                [0, 1, 1, 0, 0, 0, 1],
                                [0, 0, 0, 1, 1, 1, 1]], dtype=numpy.bool_)

        output = ndimage.white_tophat(array, structure=structure)
>       assert_array_equal(expected, output)
E       AssertionError:
E       Arrays are not equal
E
E       (mismatch 51.02040816326531%)
E        x: array([[False,  True,  True, False, False, False, False],
E              [ True, False, False,  True,  True,  True, False],
E              [ True, False, False,  True,  True,  True, False],...
E        y: array([[False,  True,  True,  True,  True,  True,  True],
E              [ True, False, False, False, False, False,  True],
E              [ True, False, False, False, False, False,  True],...

array      = array([[ True, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False],
  ...],
       [False,  True,  True,  True,  True,  True, False],
       [False, False, False, False, False, False,  True]])
expected   = array([[False,  True,  True, False, False, False, False],
       [ True, False, False,  True,  True,  True, False],
  ...],
       [False,  True,  True, False, False, False,  True],
       [False, False, False,  True,  True,  True,  True]])
output     = array([[False,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False,  True],
  ...],
       [ True, False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True, False]])
self       = <scipy.ndimage.tests.test_ndimage.TestNdimage object at 0x6d235630>
structure  = array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

scipy/ndimage/tests/test_ndimage.py:4424: AssertionError
_______________________________ TestIQR.test_rng _______________________________

self = <scipy.stats.tests.test_stats.TestIQR object at 0x6078bc90>

    def test_rng(self):
        x = np.arange(5)
        assert_equal(stats.iqr(x), 2)
        assert_equal(stats.iqr(x, rng=(25, 87.5)), 2.5)
        assert_equal(stats.iqr(x, rng=(12.5, 75)), 2.5)
        assert_almost_equal(stats.iqr(x, rng=(10, 50)), 1.6)  # 3-1.4

        assert_raises(ValueError, stats.iqr, x, rng=(0, 101))
>       assert_raises(ValueError, stats.iqr, x, rng=(np.nan, 25))
E       Failed: DID NOT RAISE <class 'ValueError'>

self       = <scipy.stats.tests.test_stats.TestIQR object at 0x6078bc90>
x          = array([0, 1, 2, 3, 4])

scipy/stats/tests/test_stats.py:1701: Failed
```

</details>

I hope to patch NumPy to address the above.

**Comment by jjhelmus** [comment] 2018-05-11 18:44
I've found that the `test_white_tophat03` unit test is failing on Power8 as well with the SciPy 1.1.0 release.  I am not certain if this has a similar cause but it may be of interest that this is failing on another non-x86 architecture

<details>
  <summary>Details</summary>

```
self = <scipy.ndimage.tests.test_ndimage.TestNdimage object at 0x3fff8551b080>

    def test_white_tophat03(self):
        array = numpy.array([[1, 0, 0, 0, 0, 0, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 0, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 0, 0, 0, 0, 0, 1]], dtype=numpy.bool_)
        structure = numpy.ones((3, 3), dtype=numpy.bool_)
        expected = numpy.array([[0, 1, 1, 0, 0, 0, 0],
                                [1, 0, 0, 1, 1, 1, 0],
                                [1, 0, 0, 1, 1, 1, 0],
                                [0, 1, 1, 0, 0, 0, 1],
                                [0, 1, 1, 0, 1, 0, 1],
                                [0, 1, 1, 0, 0, 0, 1],
                                [0, 0, 0, 1, 1, 1, 1]], dtype=numpy.bool_)

        output = ndimage.white_tophat(array, structure=structure)
        print("expected", expected)
        print("output", output)
>       assert_array_equal(expected, output)
E       AssertionError:
E       Arrays are not equal
E
E       (mismatch 51.02040816326531%)
E        x: array([[False,  True,  True, False, False, False, False],
E              [ True, False, False,  True,  True,  True, False],
E              [ True, False, False,  True,  True,  True, False],...
E        y: array([[False,  True,  True,  True,  True,  True,  True],
E              [ True, False, False, False, False, False,  True],
E              [ True, False, False, False, False, False,  True],...

array      = array([[ True, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False],
  ...],
       [False,  True,  True,  True,  True,  True, False],
       [False, False, False, False, False, False,  True]])
expected   = array([[False,  True,  True, False, False, False, False],
       [ True, False, False,  True,  True,  True, False],
  ...],
       [False,  True,  True, False, False, False,  True],
       [False, False, False,  True,  True,  True,  True]])
output     = array([[False,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False,  True],
  ...],
       [ True, False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True, False]])
self       = <scipy.ndimage.tests.test_ndimage.TestNdimage object at 0x3fff8551b080>
structure  = array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

scipy/ndimage/tests/test_ndimage.py:4426: AssertionError
```
</details>

**Comment by stuartarchibald** [comment] 2018-05-11 20:15
Thanks @jjhelmus , interesting that it is "wrong" in the same way, i.e. value mismatch at the same locations. I'll try and take a look at it sometime next week. Is this the only failure on Power8?

**Comment by stuartarchibald** [comment] 2018-05-14 22:55
I've narrowed the failure below down a bit  (from `test_white_tophat03`):

<details>

```
_______________________ TestNdimage.test_white_tophat03 ________________________

self = <scipy.ndimage.tests.test_ndimage.TestNdimage object at 0x6d235630>

    def test_white_tophat03(self):
        array = numpy.array([[1, 0, 0, 0, 0, 0, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 1, 1, 1, 0, 1, 0],
                             [0, 1, 1, 1, 1, 1, 0],
                             [0, 0, 0, 0, 0, 0, 1]], dtype=numpy.bool_)
        structure = numpy.ones((3, 3), dtype=numpy.bool_)
        expected = numpy.array([[0, 1, 1, 0, 0, 0, 0],
                                [1, 0, 0, 1, 1, 1, 0],
                                [1, 0, 0, 1, 1, 1, 0],
                                [0, 1, 1, 0, 0, 0, 1],
                                [0, 1, 1, 0, 1, 0, 1],
                                [0, 1, 1, 0, 0, 0, 1],
                                [0, 0, 0, 1, 1, 1, 1]], dtype=numpy.bool_)

        output = ndimage.white_tophat(array, structure=structure)
>       assert_array_equal(expected, output)
E       AssertionError:
E       Arrays are not equal
E
E       (mismatch 51.02040816326531%)
E        x: array([[False,  True,  True, False, False, False, False],
E              [ True, False, False,  True,  True,  True, False],
E              [ True, False, False,  True,  True,  True, False],...
E        y: array([[False,  True,  True,  True,  True,  True,  True],
E              [ True, False, False, False, False, False,  True],
E              [ True, False, False, False, False, False,  True],...
```

</details>

At least part of the issue appears to come from C code in `_nd_image`, this is a reproducer (based on walking the above test execution on x86_64 and ARMv7 simultaneously watching for when they differed):
```python
import numpy as np
from scipy.ndimage import _nd_image as c_nd_image

input_arr = np.array([[ True, False, False, False, False, False, False],
                      [False,  True,  True,  True,  True,  True, False],
                      [False,  True,  True,  True,  True,  True, False],
                      [False,  True,  True,  True,  True,  True, False],
                      [False,  True,  True,  True, False,  True, False],
                      [False,  True,  True,  True,  True,  True, False],
                      [False, False, False, False, False, False,  True]])

footprint = np.array([[ True,  True,  True],
                      [ True,  True,  True],
                      [ True,  True,  True]])
structure = np.array([[1., 1., 1.],
                      [1., 1., 1.],
                      [1., 1., 1.]])

out_arr = np.array([[False, False, False, False, False, False, False],
                    [False, False, False, False, False, False, False],
                    [False, False, False, False, False, False, False],
                    [False, False, False, False, False, False, False],
                    [False, False, False, False, False, False, False],
                    [False, False, False, False, False, False, False],
                    [False, False, False, False, False, False, False]])
mode = 2
cval = 0.0
origins = [0, 0]
minimum = 1

# Output goes in all False
print(out_arr)
c_nd_image.min_or_max_filter(input_arr, footprint, structure, out_arr, mode, cval, origins, minimum)

# This should be mutated
print(out_arr)
```
x86_64 gives:
```
$ python problem1.py                                                                                                            
[[False False False False False False False]                                                                                    
 [False False False False False False False]                                                                                    
 [False False False False False False False]                                                                                    
 [False False False False False False False]                                                                                    
 [False False False False False False False]                                                                                    
 [False False False False False False False]                                                                                    
 [False False False False False False False]]                                                                                   
[[False False  True  True  True  True  True]                                                                                    
 [False False  True  True  True  True  True]                                                                                    
 [ True  True False False False False False]                                                                                    
 [ True  True False False False False False]                                                                                    
 [ True  True False False False False False]                                                                                    
 [ True  True False False False  True False]                                                                                    
 [ True  True False False False False False]] 
```
ARMv7 gives:
```
$ python problem1.py
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]
```

The function `min_or_max_filter` is implemented here https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/nd_image.c#L296-L331 with most of the work deferred to https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_filters.c#L529-L667. It is worth noting that if the `dtype` of the input and output array are switched to `np.float64` the output mutation is consistent across architectures (but is different from the boolean output on `x86_64`).

**Comment by jjhelmus** [comment] 2018-05-15 19:46
@stuartarchibald I found the same issue on ppc64le.  I've been using the following to test:

``` Python
import numpy
import scipy.ndimage as ndimage

input = numpy.array([
    [1, 0, 0],
    [0, 1, 1],
    [0, 0, 0]], dtype=numpy.bool_)

footprint = numpy.ones((3,3), dtype=numpy.bool_)
structure = numpy.ones((3, 3), dtype=numpy.float64)
output = numpy.zeros((3, 3), dtype=numpy.bool_)

mode = 2
cval = 0.0
origins = [0, 0]
minimum = 1
ndimage._nd_image.min_or_max_filter(
        input, footprint, structure, output,
        mode, cval, origins, minimum)
print(output)
```

x86_64 gives:
```
[[False False  True]
 [False False  True]
 [ True  True False]]
```

ppc64le gives
```
[[False False False]
 [False False False]
 [False False False]]
```

This seems to have been broken for some time, at least since 1.0.0, but was not causing a test failure until #8455 was merged.  #8455 in no way is the cause of the issue just illuminated it.



> Is this the only failure on Power8?

There are a few other failures on Power8 but adjusting the tolerance limits in the effected tests gets them to a passing state.  I'll open a separate issue for these and submit fixes shortly.

**Comment by stuartarchibald** [comment] 2018-07-04 21:44
https://github.com/numpy/numpy/pull/11016 Is now merged. Now only two issues remain.

**Comment by ilayn** [comment] 2021-08-28 15:24
Seems like we haven't heard back from this for quite some time. Closing but please reopen if something persists.

**Closed by ilayn** 2021-08-28 15:24 UTC
Labels: defect, scipy.linalg
