### ISSUE TITLE
Iterative solvers don't return iterations to converge

### ISSUE THREAD

**Issue by CorbinFoucart** [scipy/scipy#10474] opened 2019-07-16 23:56 UTC
https://github.com/scipy/scipy/blob/a9fb36bc44bad4bbd2c1a41cb43c6f10925b38ae/scipy/sparse/linalg/isolve/iterative.py#L276

It seems that there is no way to retrieve the number of iterations to convergence for `scipy.sparse.linalg.cg` and other similar iterative solvers, becuase the `info` returned is 0 if the iterative solve converges.

When comparing iterative solvers, the number of iterations until convergence is extremely important information. Is there a way to access it without using global variables in the `callback` function? If not, can this be added as a feature request? I can't believe I'm the only one who wants this information.

**Comment by CorbinFoucart** [comment] 2019-07-24 18:48
While I still feel that iterations to convergence is an important feature of a sparse iterative solver, I did find a work-around without global variables that I wanted to post in case someone else has the same request.

Writing a wrapper class

```python
class IterativeSolverWrapper(object):
    
    def __init__(self, A, b):
        self.A = A
        self.b = b
        self.residuals = []
        self.iterations = 0
        
    def _iterative_callback(self, xk):
        norm = np.linalg.norm(self.b - self.A @ xk)
        self.residuals.append(norm)
        self.iterations += 1
        
    def solve(self, **kwargs):
        self.residuals = []
        self.iterations = 0
        x, info = scipy.sparse.linalg.bicgstab(self.A, self.b,
                callback=self._iterative_callback, **kwargs)
        return x, info, self.iterations, self.residuals
```

Allows the user to use the callback function to compute diagnostic information, via

```python
isw = IterativeSolverWrapper(A, b)
x, info, iterations, residuals = isw.solve(tol=1e-2, x0=x0)
```

**Comment by PhilipVinc** [comment] 2021-09-08 13:17
Bump.
What would it take to make a feature request to Scipy for this feature?

**Comment by mdhaber** [comment] 2021-09-08 13:41
This issue is a feature request (already). Someone just needs to be interested in doing it and submit a PR. One of the difficulties could be that because the solvers currently return a tuple, adding an element to be returned could break backward compatibility. A solution is to return a bunch object (see use of `make_tuple_bunch` in `scipy/stats/stats.py`) that can be indexed/unpacked like a namedtuple to get existing items but can be extended with other items accessible only as attributes.

**Comment by mdhaber** [comment] 2024-10-16 15:26
Closing as duplicate of gh-1702.

**Closed by mdhaber** 2024-10-16 15:26 UTC
Labels: enhancement, scipy.sparse.linalg
