### ISSUE TITLE
20 test failures on Win32 with updated OpenBLAS wheel

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#8759] opened 2018-04-19 22:50 UTC
Building from the scipy-wheels repository, I just updated the Windows OpenBLAS wheel to a recent commit that has a fix for https://github.com/numpy/numpy/issues/10742 . For convenience, I used the pre-installed mingw gcc 6.3 to build the OpenBLAS libs, instead of gcc 7.1 from msys2 (the latest version [no longer works](https://github.com/xianyi/OpenBLAS/issues/1503)). 

This build gets 20 failures of various sorts on 32-bit Windows, but not 64-bit Windows:

* [32-bit log with failures](https://ci.appveyor.com/project/scipy/scipy-wheels/build/1.0.107/job/tjahp2uixl6ai6cv)
* [Build matrix](https://ci.appveyor.com/project/scipy/scipy-wheels/build/1.0.107)

Failures:

```
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_non_unit_strides_economic_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_non_native_byte_order_economic_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_sqr_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_non_unit_strides_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_non_native_byte_order_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_tall_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_non_itemsize_strides_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_non_itemsize_strides_economic_rank_p
FAIL scipy/sparse/tests/test_base.py::TestLIL::()::test_expm
FAIL scipy/sparse/tests/test_base.py::TestCOO::()::test_expm
FAIL scipy/sparse/tests/test_base.py::TestCSCNonCanonical::()::test_expm
FAIL scipy/sparse/linalg/tests/test_matfuncs.py::TestExpM::()::test_padecases_dtype_float
FAIL scipy/sparse/linalg/tests/test_onenormest.py::TestOnenormest::()::test_onenormest_table_5_t_1
FAIL scipy/sparse/tests/test_base.py::TestCSC::()::test_expm
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_fat_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_neg_strides_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_overwrite_qruv_rank_p
FAIL scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::()::test_neg_strides_economic_rank_p
FAIL scipy/sparse/tests/test_base.py::TestDIA::()::test_expm
FAIL scipy/sparse/tests/test_base.py::TestCSRNonCanonical::()::test_expm
```

Forgive my ignorance, but are these OpenBLAS bugs that need to be reported, or did something else happen to cause these failures?

**Comment by ilayn** [comment] 2018-04-19 22:54
Can you also check why they are failing? Probably they are failing due to missing sufficient precision for the array equivalences.

**Comment by matthew-brett** [comment] 2018-04-19 22:59
I find the pytest failure log pretty hard to read, but have a look at e.g. https://ci.appveyor.com/project/scipy/scipy-wheels/build/1.0.107/job/tjahp2uixl6ai6cv#L7103 . It doesn't look like a precision problem to me ...

**Comment by matthew-brett** [comment] 2018-04-19 23:29
Or memory corruption ...

**Comment by matthew-brett** [comment] 2018-04-20 16:04
Same failures with OpenBLAS built with gcc 7.1 : https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/1.0.3

**Comment by pv** [comment] 2018-04-20 16:18
From the test failures,

TestOnenormest.test_onenormest_table_5_t_1
seems the simplest since it's just a little bit of linear algebra:

n = 100
alpha = 1 - 1e-6
A = -scipy.linalg.inv(np.identity(n) + alpha*np.eye(n, k=1))
first_col = np.array([1] + [0]*(n-1))
first_row = np.array([(-alpha)**i for i in range(n)])
B = -scipy.linalg.toeplitz(first_col, first_row)
assert_allclose(A, B)

Around here,

>>> abs(A - B).max()
6.661338147750939e-16

but maybe that openblas build produces significant error in the result?

**Comment by matthew-brett** [comment] 2018-04-20 17:13
18 failures for gcc 7.1, latest commit on OpenBLAS devel : https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/1.0.4

**Comment by matthew-brett** [comment] 2018-04-20 17:42
Oops:

```Python
In [6]: abs(A - B).max()
Out[6]: 0.999999
```

True for n=100, but not n=70.   Difference is (predictably enough) in the result of `inv`:

On OSX:

```Python
n = 100
alpha = 1 - 1e-6
A = -scipy.linalg.inv(np.identity(n) + alpha*np.eye(n, k=1))
np.save('A.npy', A)
```

Copy `A.npy` to Windows machine, then, with [this](https://ci.appveyor.com/api/buildjobs/5x64aq3vkya54e40/artifacts/scipy-1.2.0.dev0%2Bc728360-cp36-none-win32.whl) copy of Scipy on Windows, Python 3.6 32-bit:

```Python
n = 100
alpha = 1 - 1e-6
A = -scipy.linalg.inv(np.identity(n) + alpha*np.eye(n, k=1))
A_osx = np.load('A.npy')
print(np.abs(A - A_osx).max())
```

gives 0.999999, as does:

```Python
n = 100
alpha = 1 - 1e-6
A = -scipy.linalg.inv(np.identity(n) + alpha*np.eye(n, k=1))
A_np = -np.linalg.inv(np.identity(n) + alpha*np.eye(n, k=1))
print(np.abs(A - A_np).max())
```

**Comment by pv** [comment] 2018-04-20 18:47
Looks like openblas bug or miscompilation then.
The matrix has small condition number, so inversion should be stable.

**Comment by pv** [comment] 2018-04-20 21:03
@matthew-brett: can you try this: https://github.com/pv/OpenBLAS/tree/getrf-smoketest/utest
```
cp libopenblas_2c7392f0_gcc6_3_0.a OpenBLAS/
cd OpenBLAS/utest
make LIBNAME=libopenblas_2c7392f0_gcc6_3_0.a
```
I cannot reproduce the failure with this test with that openblas binary, but perhaps it's processor-specific.

**Comment by matthew-brett** [comment] 2018-04-20 22:32
See: https://github.com/xianyi/OpenBLAS/issues/1533#issuecomment-383238373 - the Scipy failure is processor-specific.   Sorry, will try your smoke test tomorrow, late here.

**Comment by matthew-brett** [comment] 2018-04-21 23:48
@pv - your test passes for me too : https://ci.appveyor.com/project/matthew-brett/appvfutz/build/job/1us93k0q4sa61dx7

**Comment by pv** [comment] 2018-04-22 01:11
It's however more or less what scipy inv() does, so there's then something unclear here.

**Comment by pv** [comment] 2018-04-22 01:12
Sorry, I see that the above appveyor ran only the BLAS test, not LAPACK ones, so the new test was not run. There' shoult be `dgetrf` in the test output.

**Comment by matthew-brett** [comment] 2018-04-22 10:46
Ah - any suggestions on what I should do to enable the lapack tests?

**Comment by pv** [comment] 2018-04-22 11:38
`make LIBNAME=... NO_LAPACK=0`

**Comment by pv** [comment] 2018-04-24 23:57
Was this resolved in OpenBLAS?

**Comment by matthew-brett** [comment] 2018-04-25 22:06
Hmm - I thought yes, but the scipy-wheels build failed on the latest OpenBLAS devel commit.  Cross-ref: https://github.com/xianyi/OpenBLAS/issues/1533#issuecomment-383373132 . I'm trying a few tests to see what's going on.

**Comment by matthew-brett** [comment] 2018-04-26 00:07
There's something very strange going on.  I built a new OpenBLAS archive reverting https://github.com/xianyi/OpenBLAS/pull/1333 and this passed all scipy tests - see: https://github.com/xianyi/OpenBLAS/issues/1533#issuecomment-383373132 . OpenBLAS then did that revert on their `develop` branch.  I rebuilt the library with the OpenBLAS devel branch, as of commit `8a3b6fa1`, which included this revert, and a couple of other incidental and apparently irrelevant other commits, and this failed the 32-bit tests again: https://ci.appveyor.com/project/scipy/scipy-wheels/build/1.0.109 .  It's very hard to believe the incidental commits are the cause (they appear to be for the POWER architecture, and modifying some tests).

**Comment by matthew-brett** [comment] 2018-04-26 00:15
I did notice these:

```
scipy/interpolate/tests/test_interpolate.py::TestPPoly::()::test_roots_croots
  C:\Python36\lib\site-packages\scipy\conftest.py:35: FPUModeChangeWarning: FPU mode changed from 0x9001f to 0xc001f during the test
    category=FPUModeChangeWarning, stacklevel=0)
scipy/special/tests/test_digamma.py::test_consistency
  C:\Python36\lib\site-packages\scipy\conftest.py:35: FPUModeChangeWarning: FPU mode changed from 0x9001f to 0xc001f during the test
    category=FPUModeChangeWarning, stacklevel=0)
```

https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/job/70mbt97s7t98l49m

A passing test run has these:

```
scipy/interpolate/tests/test_interpolate.py::TestPPoly::()::test_roots_croots
  C:\Python36\lib\site-packages\scipy\conftest.py:35: FPUModeChangeWarning: FPU mode changed from 0x9001f to 0xc001f during the test
    category=FPUModeChangeWarning, stacklevel=0)
scipy/special/tests/test_basic.py::TestBessel::()::test_yv_cephes_vs_amos
  C:\Python36\lib\site-packages\scipy\conftest.py:35: FPUModeChangeWarning: FPU mode changed from 0x9001f to 0xc001f during the test
    category=FPUModeChangeWarning, stacklevel=0)
scipy/signal/tests/test_dltisys.py::Test_bode::()::test_pole_one
  C:\Python36\lib\site-packages\scipy\conftest.py:35: FPUModeChangeWarning: FPU mode changed from 0x9001f to 0xc001f during the test
    category=FPUModeChangeWarning, stacklevel=0)
```
https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/1.0.9/job/76h70mvd4lnc3f9w

I have no idea whether these are significant.

**Comment by matthew-brett** [comment] 2018-04-30 22:39
Further tests find that reverting either or both of the apparently unrelated extra commits on OpenBLAS devel, cause the tests to pass:

* [both](https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/1.0.12)
* [first innocuous](https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/1.0.14)
* [second innocuous](https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/1.0.15)

It's very difficult to believe that either of these commits have anything to do with the failure:

* [first commit](https://github.com/xianyi/OpenBLAS/commit/8a3b6fa108b15331c2af8777d1ea0206f85673b8)
* [second commit](https://github.com/xianyi/OpenBLAS/commit/86f49c529d308ce16b3c7bb3c546686c5387e597)

The FPU mode switching warnings vary between the three passing runs.

I would speculate that some randomness in testing order from the parallel test run is revealing memory corruption unrelated to these commits, but the failing run is completely consistent in the 32-bit test failures:

https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/1.0.11

Any thoughts?

**Comment by matthew-brett** [comment] 2018-04-30 22:41
I notice there are no FPU mode switching warnings in the 64 bit logs.

**Comment by pv** [comment] 2018-04-30 22:54
The FPU mode warnings are likely MSVC bugs, I'm doubtful that they are related to this issue.

**Comment by pv** [comment] 2018-04-30 22:58
You can probably exclude the FPU stuff by running only the linalg tests

**Comment by matthew-brett** [comment] 2018-05-01 17:49
Yes, 12 test failures running just scipy.linalg, no FPU warnings:

https://ci.appveyor.com/project/matthew-brett/scipy-wheels/build/1.0.20

**Comment by sethtroisi** [comment] 2020-05-20 10:24
@matthew-brett I'm doing a triage over old bugs, I suspect that 2 years later this is no longer relevant, but possible not. Did this get resolved (READ: can this be closed)?

**Comment by rgommers** [comment] 2020-05-20 18:27
Azure builds cover 32/64-bit with all Python versions we support and that passes. So yes, can be closed.

**Closed by rgommers** 2020-05-20 18:27 UTC
Labels: Build issues
