### ISSUE TITLE
Python 3 scipy.linalg.svd returns matrix with nan elements.

### ISSUE THREAD

**Issue by bchu** [scipy/scipy#5586] opened 2015-12-07 09:42 UTC
On Python 3.4.2, scipy 0.16.1, I get the following:

```
>>> matrix.shape
(24983, 100)
>>> np.sum(np.isnan(scipy.linalg.svd(matrix, full_matrices=False)[0]))
24983
>>> np.sum(np.isnan(scipy.linalg.svd(matrix, full_matrices=False)[0]))
0
```

(The expected output of `np.sum(np.isnan(scipy.linalg.svd(matrix, full_matrices=False)[0]))` is 0; the bug is that the first call to `scipy.linalg.svd` returns a U matrix with a column of nans (all in the same column). But subsequent calls do not have the same problem. Calling scipy.linalg.svd on some other matrix before calling this code block also doesn't make the problem disappear.

The problem does not show up on Python 2.7.9, or if I use `numpy.linalg.svd`.

**Comment by pv** [comment] 2015-12-07 09:59
(i) What platform? Linux/OSX/Windows?
(ii) Which scipy binaries are you using (iow how did you install it)?
(iii) What BLAS/LAPACK is linked in?
.
This sort of issue is more likely than not due to the blas/lapack
libraries used in your installation.

**Comment by pv** [comment] 2016-01-07 09:02
Closing: the report does not contain enough information to be actionable, and the issue is likely due to the specific blas/lapack combination in use (and so not a bug in scipy).

**Closed by pv** 2016-01-07 09:02 UTC

**Comment by anbai106** [comment] 2020-02-25 22:38
Sorry to reopen this issue. I encountered the same issue:

1) Platform: Ubuntu 18.04
2) scipy version 1.3.1

error from this code:
`U, S, V = svd(X, full_matrices=False, lapack_driver='gesvd')`

The returned U contained Nan values....

Do you have any ideas for this?

Best regards

Hao

**Comment by anbai106** [comment] 2020-02-25 23:13
I found the reason why I got those Nan values (It's not a reason actually). The error came only for this version of numpy (1.17.2) and  scipy(1.3.0). I ran the same job on another ubuntu machine who has numpy (1.16.4) and scipy (1.3.0). It worked without this issue...

I don't know why, but it seems that numpy==1.16.4 impacted somehow and gave wrong results for svd function
