### ISSUE TITLE
multivariate regression

### ISSUE THREAD

**Issue by jl2922** [scipy/scipy#7399] opened 2017-05-12 23:40 UTC
Hi, I am writing a multivariate version of the scipy.stats.linregress function, and planning to add that to scipy. However, I am not quite sure what's the best way to integrate. Is it better for me to have another function like 'multilinregress', or extend the current 'linregress' function with some changes to its interface?

**Comment by ev-br** [comment] 2017-05-20 15:54
I'd say there's value in keeping `linregress` simple.

For more complicated uses (e.g. multivariate) a question what does a new function add to what's available in scikit-learn, http://scikit-learn.org/stable/modules/linear_model.html and statsmodels, http://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html

**Comment by mdhaber** [comment] 2022-03-15 00:48
Opinons here and in gh-7438 seem to be that we can leave this to statmodels. I'd agree, and since it's been five years without a PR, I think we can close this.

**Closed by mdhaber** 2022-03-15 00:48 UTC
Labels: scipy.stats, enhancement, needs-decision
