### ISSUE TITLE
BUG: operator** behaviour is inconsistent for sparse matrices

### ISSUE THREAD

**Issue by cahitkargi** [scipy/scipy#15950] opened 2022-04-07 07:28 UTC
### Describe your issue.

** operator raises a sparse matrix to a power, but it is element-wise power when we use it on .A of the same sparse matrix.
I am not sure this is a bug in numpy or scipy, or if it is intentional.
It at least looks like an inconsistency between numpy arrays and scipy.sparse

### Reproducing Code Example

```python
import scipy.sparse as sp

someMatrix = sp.csc_matrix(([1, -1], ([0, 1], [1, 0])), shape=(2, 2))

# print the matrix
print(someMatrix.A)

# raises the matrix to a power
print((someMatrix**2).A)

# element-wise power
print((someMatrix.A)**2)
```

### Error message

```shell
No error messages.
```

### SciPy/NumPy/Python version information

1.8.0/1.22.1/3.10.1

**Comment by tupui** [comment] 2022-04-07 07:40
Hi @cahitkargi thanks for reporting but it's a duplicate of #15948.

**Closed by tupui** 2022-04-07 07:40 UTC
Labels: defect
