### ISSUE TITLE
can't install Scipy any version on Python 3.8.10, M1(macOS)

### ISSUE THREAD

**Issue by xcellentbird** [scipy/scipy#14011] opened 2021-05-09 20:54 UTC
My issue is about ...

#### Reproducing code example:

```
Sample code to reproduce the problem
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by ilayn** [comment] 2021-05-10 03:06
Duplicate of #13409

**Closed by ilayn** 2021-05-10 03:06 UTC
