### ISSUE TITLE
Can you please explain where should that method get "gfk" variable from? Running Neuton-CG method calls that code and returns ""

### ISSUE THREAD

**Issue by freekotya** [scipy/scipy#8240] opened 2017-12-20 16:29 UTC
https://github.com/scipy/scipy/blob/11509c4a98edded6c59423ac44ca1b7f28fba1fd/scipy/optimize/optimize.py#L1519

**Comment by ilayn** [comment] 2017-12-20 17:22
Duplicate of #8241

**Closed by ilayn** 2017-12-20 17:22 UTC
