### ISSUE TITLE
ENH: Roadmap Item: Support for newer LAPACK features

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10881] opened 2019-09-29 01:46 UTC
Currently there is a [roadmap item](https://scipy.github.io/devdocs/roadmap.html):

> Support for newer LAPACK features. In SciPy 1.2.0 we increased the minimum supported version of LAPACK to 3.4.0. Now that we dropped Python 2.7, we can increase that version further (MKL + Python 2.7 was the blocker for >3.4.0 previously) and start adding support for new features in LAPACK.

After gh-10797 is merged, I'd be interested in working toward this, but I have a few questions.
1. What are the current constraints on the versions of LAPACK that we can support? 
2. Should we increase the minimum supported version now (or as soon as there is enough interest in making it happen), or is there a reason to wait?
3. SciPy's [Cython wrappers for LAPACK](https://scipy.github.io/devdocs/linalg.cython_lapack.html#module-scipy.linalg.cython_lapack) are complete through LAPACK 3.4. If we increase the minimum supported version to 3.X (above), we would want to add the Cython wrappers through 3.X. There are some example PRs I could use to figure out how to work on this (gh-4021, gh-8670), but I'd appreciate the thoughts of someone with experience.  @insertinterestingnamehere Even after the machinery was set up in gh-4021, gh-8670 looks like it was a lot of work. How much of an ordeal would it be to update again? Is this something I want to get myself into?
4. SciPy's [_Python_ wrappers for LAPACK](https://scipy.github.io/devdocs/linalg.lapack.html#module-scipy.linalg.lapack) are not nearly complete through LAPACK 3.4. This is because they have all been generated manually to have a simplified signature, and this is certainly appreciated. But would it be nice to add something that allows the easy use of all the Cython-wrappers (with the original LAPACK signature) directly from Python, at least for use by SciPy developers? (Or is this already easy?)
5. Regarding manually-generated, simplified signature wrappers of LAPACK functions, what should we prioritize? What LAPACK routines are on your wishlist?

For reference, here are the 392 routines for which we have a Cython interface but no Python interface;
'geql2', 'hpcon', 'lag2s', 'rscl', 'lanhe', 'latrs', 'ungtr', 'gtsvx', 'hetf2', 'orgr2', 'laprec', 'latbs', 'gbbrd', 'spr', 'pbstf', 'lasd3', 'lag2z', 'lagtf', 'erbla_array', 'lalsa', 'gerq2', 'lanhf', 'getf2', 'lags2', 'tgexc', 'lasv2', 'opmtr', 'geqrt3', 'ptcon', 'lantp', 'tprfb', 'laed9', 'pptri', 'sytrs', 'lanst', 'lat2c', 'sposv', 'unml2', 'ppsv', 'orgl2', 'lapmt', 'lanht', 'laeda', 'lasd0', 'laqge', 'laed8', 'trsna', 'pttrf', 'gerfs', 'hetrs2', 'lasdt', 'lagv2', 'larrj', 'laqr5', 'sgesv', 'orml2', 'laslc', 'larz', 'sptrs', 'orgbr', 'unmr3', 'laqr1', 'laein', 'ormql', 'larft', 'porfs', 'lauplo', 'ggqrf', 'lag2', 'srscl', 'hptrs', 'latps', 'heswapr', 'lasd1', 'larrr', 'laed5', 'lat2s', 'lartgs', 'lahr2', 'hpgvd', 'gebak', 'tgsja', 'sbgv', 'poequ', 'gbequ', 'ormr3', 'larrf', 'cmax1', 'hpevx', 'isnan', 'latrans', 'orm2l', 'ungl2', 'lacrm', 'gsvj1', 'laset', 'tbrfs', 'ggrqf', 'pbequ', 'tpqrt2', 'gbrfs', 'pprfs', 'gehd2', 'ungr2', 'larfx', 'hetri2x', 'larnv', 'gsvj0', 'geevx', 'potf2', 'pbsvx', 'stevx', 'symv', 'lantb', 'larrc', 'geqr2', 'larcm', 'laruv', 'spsv', 'lanhb', 'stevr', 'laqgb', 'latrz', 'hsein', 'laed3', 'spmv', 'tbcon', 'latrd', 'ormlq', 'unmtr', 'lasd2', 'laqhb', 'unmhr', 'zsum1', 'hpev', 'sptri', 'ggbal', 'unmbr', 'syr', 'org2l', 'bdsqr', 'pbrfs', 'spgvd', 'lapll', 'lassq', 'trsen', 'lapy3', 'laic1', 'larzt', 'lasd6', 'pbcon', 'lanv2', 'tprfs', 'ladlc', 'larra', 'ung2l', 'csum1', 'pbtf2', 'lae2', 'cposv', 'gebrd', 'laln2', 'orgtr', 'lasq3', 'larrb', 'lahqr', 'spcon', 'unbdb', 'hetri2', 'lansb', 'lasda', 'lartgp', 'ppequ', 'hptrf', 'ladiv', 'laed4', 'hbgvx', 'gelq2', 'lahef', 'sptrd', 'hbgst', 'lacpy', 'lacp2', 'uncsd', 'lasrt', 'unmlq', 'ormbr', 'unmql', 'sytri2', 'ggglm', 'hbgv', 'trti2', 'lagtm', 'tptri', 'larrk', 'lasq4', 'sbgst', 'upmtr', 'laed2', 'lar2v', 'cgesv', 'hbtrd', 'tgsna', 'gghrd', 'trcon', 'hpsvx', 'laqhe', 'heevx', 'gttrs', 'unm2l', 'syrfs', 'laqr2', 'larfgp', 'tgsy2', 'ladiag', 'bdsdc', 'lascl', 'laqps', 'lanhp', 'lapy2', 'gtrfs', 'hetrs', 'hpgst', 'larrd', 'larrv', 'hpgv', 'gttrf', 'ormhr', 'sytri', 'laebz', 'sbgvx', 'sytrs2', 'gesc2', 'lantr', 'orcsd', 'ptsvx', 'spev', 'tptrs', 'orgql', 'laqsy', 'tgevc', 'larre', 'ung2r', 'sptrf', 'lacgv', 'syswapr', 'gbtf2', 'ungql', 'lanhs', 'gejsv', 'hpevd', 'laexc', 'orm2r', 'upgtr', 'trevc', 'bbcsd', 'lasq2', 'lals0', 'orbdb', 'hetd2', 'hptri', 'ungbr', 'eeeck', 'spgvx', 'largv', 'lamrg', 'drscl', 'geqr2p', 'disna', 'ggevx', 'pptrs', 'laqsb', 'lazlr', 'lasy2', 'unglq', 'langb', 'gebd2', 'geqrt2', 'sytd2', 'laqhp', 'laneg', 'unmr2', 'hprfs', 'hbev', 'geqrfp', 'laqp2', 'lacrt', 'las2', 'sprfs', 'tftri', 'larfb', 'spevd', 'ptrfs', 'gelqf', 'hegs2', 'steqr', 'laqr4', 'lasr', 'poequb', 'spgst', 'lapmr', 'ggbak', 'orglq', 'hptrd', 'pptrf', 'gbcon', 'laed6', 'laed7', 'ptts2', 'pteqr', 'lansf', 'getc2', 'trrfs', 'sbgvd', 'ggesx', 'lacn2', 'hla_transtype', 'geqlf', 'syevx', 'laesy', 'ppsvx', 'lasyf', 'org2r', 'lartv', 'lansp', 'ormrq', 'gtcon', 'gbequb', 'hseqr', 'unmrq', 'lasdq', 'geesx', 'larzb', 'lazlc', 'ppcon', 'herfs', 'lasd8', 'laqr0', 'laed1', 'opgtr', 'labrd', 'hpgvx', 'hpsv', 'lacon', 'stegr', 'laclr', 'laqtr', 'labad', 'lag2d', 'lauu2', 'spsvx', 'hbgvd', 'sbtrd', 'sygs2', 'lalsd', 'gbsvx', 'lasq6', 'tgsyl', 'laslr', 'zmax1', 'lag2c', 'hgeqz', 'spevx', 'latdf', 'laqr3', 'laqsp', 'stedc', 'laev2', 'spgv', 'gtts2', 'lasd5', 'laed0', 'lar1v', 'lasd7', 'tbtrs', 'ormtr', 'pttrs', 'lansy', 'lagts', 'lasq1', 'tgex2', 'stevd', 'tpcon', 'sytri2x', 'langt', 'hetri', 'ladlr', 'gesvj', 'laclc', 'ormr2', 'unm2r', 'trexc'

@insertinterestingnamehere @larsoner @zerothi @sturlamolden @ilayn @pv It looks like you've all worked on this sort of stuff in the past, so I thought I'd bring this to your attention.

**Comment by ilayn** [comment] 2019-09-29 08:43
> What are the current constraints on the versions of LAPACK that we can support?

Back then, when I was continuously annoying everyone about this issue, [this requirement(https://github.com/scipy/scipy/pull/6051#issuecomment-329542591) from @cgohlke defined the constraint LAPACK v3.4. Otherwise I would have preferred to anchor to 3.5.1. I think it is not valid anymore but then the question is what the new version is .

> Should we increase the minimum supported version now (or as soon as there is enough interest in making it happen), or is there a reason to wait?

Same as above and actually this roadmap item was there because of Accelerate support. Once we got rid of that, we bumped the minimum version to 3.4.0 (there was too many critical bugs between 3.1 and 3.4) See wiki page for details https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate

> How much of an ordeal would it be to update again? Is this something I want to get myself into?

I think Ian can give a better estimate but last time it wasn't as difficult as the first one if I remember correctly. 

> But would it be nice to add something that allows the easy use of all the Cython-wrappers (with the original LAPACK signature) directly from Python, at least for use by SciPy developers? (Or is this already easy?)

The problem is the user convenience level. On Cython side, you work in a typed system hence the a call to an incorrect flavor is not that much of a deal. Also you get an error on compile time. On the scipy.linalg level, we are doing a lot of protective stuff in those manual wrappers to avoid the trivial crashes. We don't guarantee any safety but still not fun to get a segfault because of a typo. It gets exceedingly difficult to find the right arguments when done natively. And you have to create a lot of dummy arrays `work`, `iwork` etc. with the right type just to make it run without a crash.

> Regarding manually-generated, simplified signature wrappers of LAPACK functions, what should we prioritize? What LAPACK routines are on your wishlist?

So far it went via user requests here or in mailing list. 

> For reference, here are the 392 routines for which we have a Cython interface but no Python interface;

Most of those are related to packed format `?.p...` or other formats such as RFP or helper functions such as `srscl` which all are rarely requested. Probably if you are using those storage schemes you are already doing it at a lower level language. But if need be, I'm all in for adding them.

**Comment by sturlamolden** [comment] 2019-09-30 01:04
Actually, the Cython wrappers are outdated too. They make assumptions about the Fortran ABI and strictly speaking they are not portable. We now allow Fortran 2003, so we have the ability to write portable C or Cython wrappers for Fortran code. In the long run, all Fortran code in SciPy should be wrapped using the Fortran 2003 ISO C bindings. We have discussed this before. Obviously, the migration will be gradual. I will suggest we do not procratinate the issue by adding more ABI-dependent Fortran wrappers to the code base. Instead, we should make an effort to produce portable wrappers with Cython and Fortran 2003. LAPACK is not a bad place to start.

**Comment by pv** [comment] 2019-09-30 13:48
For the Cython wrappers, generating iso C binding code should be simple, and since its all autogenerated whether new functions are added before this probably wont matter very much. The advantage from f2003 is mostly limited to getting compile time error instead of runtime error in case of type mismatches. The fact that everyone calls lapack wrong probably forces compiler vendors to maintain status quo for foreseeable future.

The issue is more complex for the handwritten wrappers, and addressing that requires at least fixing it in f2py.

**Comment by sturlamolden** [comment] 2019-09-30 14:25
But getting compile-time instead of run-time errors is a good thing. Remember Ariane V...

**Comment by insertinterestingnamehere** [comment] 2019-09-30 16:16
I agree with pretty much everything that's been said here.

It'd be good to get past LAPACK 3.4. I was thinking of moving to LAPACK 3.6 since that's the latest version available in Ubuntu 16.0.4. It's all kind-of arbitrary, but that seems like a reasonable jump. It'd also let us finally close https://github.com/scipy/scipy/issues/5266. For reference, the latest MKL and OpenBLAS now support the LAPACK 3.8 interface and we can actually use the latest versions there since we're no longer tied down by the old Python 2.7 Windows compiler ABI issues.

Semi-related to this, LAPACK 3.9 will probably be released soon (https://github.com/Reference-LAPACK/lapack/commit/8a2b4dce36d0dbcf173353737a8f64220b21c7b5 seems to imply that, but they haven't released it yet). My plan had been to tackle updating the wrappers to something more recent once 3.9 is finalized. We can do it before then though too. The reason to wait is to see if there are any unexpected ABI compatibility breaks in routines that we would be adding in the update. That's unlikely, but there have been some compatibility breaks between LAPACK minor versions before.

Adding support for new LAPACK versions isn't especially hard. If someone else wants to do it, great, otherwise I can still take care of it. The main thing that's involved is tweaking the code in https://github.com/scipy/scipy/blob/master/scipy/linalg/_cython_signature_generator.py to handle any new pathological signatures that crop up in the new LAPACK version we want to support. Most routines can be parsed fine with f2py, but there are usually a few that can't and a few that you don't actually want to wrap. The only hard thing here is determining which routines to exclude. I have a script that generates https://gist.github.com/insertinterestingnamehere/baf36ce759b1712f2dfb which gives me the info I need to determine which routines have a stable ABI across the different LAPACK versions we support. I can post that up on a gist too or just update the version info gist if people are interested.

WRT the Fortran 2003 ABI, it'd be great to switch to using Fortran standardized interfaces instead of implementation defined details, and our LAPACK wrappers are probably the most sensible place to start this process. That said, Fortran compilers' backwards compatibility constraints will make it so that the code we have will work for the foreseeable future. Updating the LAPACK versions we support is a much higher priority in my mind. The LAPACK devs haven't been adding routines that would need custom ABI wrappers on our end for quite some time, so adding the new routines won't conflict in any way with switching to Fortran 2003 ISO C bindings. The two changes should be mostly orthogonal.

**Comment by insertinterestingnamehere** [comment] 2019-10-07 19:39
> Does this mean that the handwritten Python wrappers (that is, the F2PY source in [scipy/linalg/flapack_gen.pyf.src](https://github.com/scipy/scipy/blob/master/scipy/linalg/flapack_gen.pyf.src)) will require substantial changes at some point in the future, so it is not helpful to write more of them right now?

I'm not totally clear on where the subtlety would be, but it doesn't seem like any needed changes would require any major changes. As I understand it, we want to replace the wrappers in https://github.com/scipy/scipy/tree/master/scipy/_build_utils/src with Fortran 2003 ISO C bindings. That shouldn't need any modifications to our f2py wrappers. F2py should eventually also be made to use the ISO C bindings internally too. Once that's done, we could also change our f2py based wrappers to not use the ABI wrappers at all. That change should also only be a few lines. It's totally possible I'm missing something though.

**Comment by sturlamolden** [comment] 2019-10-20 10:52
Actually, using the Fortran 2003 ISO C bindings would make those wrappers obsolete. Those wrappers are a hack to compensate for ABI differences between g77 and gfortran. If we use Fortran 2003 we would no longer need anything like that. The main work is that we must either generate a Fortran 2003 and a Cython wrapper for each LAPACK subroutine or update f2py to emit Fortran 2003 wrappers. 

There was a GSoC project some years ago that intended to replace f2py with a generator that emitted Cython and Fortran 2003. It might be possible to wrap LAPACK using something like this. The code is still here: https://github.com/kwmsmith/fwrap

**Comment by ilayn** [comment] 2019-10-20 13:24
Actually that's precisely what I am trying to do for the, never-ending, overhaul of the `scipy.linalg.solve`. First discovering the structure of the array and then calling the appropriate solver also using C bindings via Cython to get rid of the overhead of investigating which routine with which flavor of LAPACK should be used.

**Comment by mdhaber** [comment] 2019-10-20 16:05
>  Actually, using the Fortran 2003 ISO C bindings would make those wrappers obsolete. Those wrappers are a hack to compensate for ABI differences between g77 and gfortran. If we use Fortran 2003 we would no longer need anything like that.

To be clear - we're talking about the f2py wrappers in [flapack_gen.pyf.src](https://github.com/scipy/scipy/blob/master/scipy/linalg/flapack_gen.pyf.src) like:

```
subroutine <prefix>getrf(m,n,a,piv,info)
    ! lu,piv,info = getrf(a,overwrite_a=0)
    ! Compute an LU factorization of a  general  M-by-N  matrix  A.
    ! A = P * L * U
    threadsafe
    callstatement {int i;(*f2py_func)(&m,&n,a,&m,piv,&info);for(i=0,n=MIN(m,n);i\<n;--piv[i++]);}
    callprotoargument int*,int*,<ctype>*,int*,int*,int*

    integer depend(a),intent(hide):: m = shape(a,0)
    integer depend(a),intent(hide):: n = shape(a,1)
    <ftype> dimension(m,n),intent(in,out,copy,out=lu) :: a
    integer dimension(MIN(m,n)),depend(m,n),intent(out) :: piv
    integer intent(out):: info

end subroutine <prefix>getrf
```

I see the the wrapper above as defining a relationship between the user-friendly Python interface `lu,piv,info = getrf(a,overwrite_a=0)` and the original interface `getrf(m,n,a,piv,info)`. I really don't know anything about Fortran 2003 ISO C bindings - what information from the wrapper above would no longer be needed? Presumably we will still need to _somehow_ define a bridge between the desired Python interface and the original interface. Will that definition be dramatically simplified compared to what f2py requires? What might it look like?

**Comment by ilayn** [comment] 2019-10-20 16:22
The wrapper is between the `linalg.lapack.getrf(m,n,a,piv,info)` and the underlying BLAS/LAPACK call in the lower level langauge that f2py bridges. 

Instead of f2py, we are considering generating wrappers by other means such that the resulting wrapper uses the newer bindings (or f2py is updated such that it spits out newer kind of wrappers).

If we can succeed all `linalg.lapack.?XXXX` functions will be Cythonized functions calls. Not much will be different from the API point of view but more of a backend update.

**Comment by sturlamolden** [comment] 2019-10-20 16:23
The Fortran 2003 ISO C bindings is a Fortran API for making C functions callable from Fortran and Fortran subroutines callable from C. The problem with the above code is the callstatement
"""
{int i;(*f2py_func)(&m,&n,a,&m,piv,&info);for(i=0,n=MIN(m,n);i\<n;--piv[i++]);}
"""
There is no reason this should work, as it depends on reverse engineering Fortran compilers. Fortran does not dictate a particular binary interface, and indeed the callstatement will be different from Fortran compiler to Fortran compiler. With Fortran 2003, we can write a wrapper for ```SUBROUTINE GETRF``` that would make it callable from C like
```
getrf(m, n, a, m, piv, &info);
```
or even
```
info = getrf(m, n, a, m, piv);
```
With such a C interface, we can access Fortran from Cython.

**Comment by ilayn** [comment] 2019-11-21 10:08
Just a heads up for Lapack 3.9.0 is released https://github.com/Reference-LAPACK/lapack/releases/tag/v3.9.0

**Comment by insertinterestingnamehere** [comment] 2019-11-23 18:33
I'm in the middle of another deadline at the moment but I will hopefully be able to get back to this in another two weeks or so. Given that the 1.4 release is already in progress, I propose we do the version bump to LAPACK 3.6 in release 1.5. Does that sound good?

**Comment by mdhaber** [comment] 2019-11-23 18:42
Sounds great to me!

**Comment by insertinterestingnamehere** [comment] 2020-02-18 20:18
I'm late in following up on this, but here's the updated LAPACK version comparison https://gist.github.com/insertinterestingnamehere/baf36ce759b1712f2dfb and the script used to generate it https://gist.github.com/insertinterestingnamehere/8f087a99c2ae34f275ac268ff4210f28. It looks like (except for the stuff I need to go back and check by hand) the `*lahef_aa` and `*lasef_aa` routines are the only ones that need to be excluded out of what LAPACK 3.6 provides.

**Comment by mdhaber** [comment] 2020-02-19 01:05
Very cool! Thank you for working in this!

**Comment by anntzer** [comment] 2020-06-26 08:21
I would like to kindly request a python wrapper for pptrf (Cholesky factorization in packed format).  Note that there is already e.g. tpsv (triangular solve in packed format) which could benefit from such a packed factorization.
(It feels a bit silly to open a separate issue for each LAPACK wrapper request, but I can do that instead too, if you prefer.)

**Comment by ilayn** [comment] 2020-06-26 10:56
@anntzer Better keep this issue for handling the LAPACK versioning. You can add a single issue with multiple lapack wrapper proposals

**Comment by ilayn** [comment] 2020-06-26 10:57
By the way, since 1.5 is out should we consider the bump to LAPACK v3.6?

**Comment by anntzer** [comment] 2020-06-26 11:37
Sure, done at https://github.com/scipy/scipy/issues/12431.

**Comment by insertinterestingnamehere** [comment] 2020-06-27 15:59
Yah, I got delayed in getting this out. Ubuntu 16.04 is still supported till 2021, so I think the reasoning behind using LAPACK 3.6 still holds. I haven't seen as many Ubuntu 16.04 machines out in the wild lately though, so in practice we'd probably be fine with using something newer if people want that.

**Closed** 2022-09-25 00:00 UTC
Labels: enhancement, scipy.linalg
