### ISSUE TITLE
Inconsistent behaviour with interp1d 'cubic'

### ISSUE THREAD

**Issue by deeuu** [scipy/scipy#2690] opened 2013-08-05 12:20 UTC
Hi,

I'm getting inconsistent outputs when using interp1d for cubic interpolation.

Here's some code:

```
from scipy.interpolate import interp1d
#data set i'm using
x = r_[20, 25, 31.5, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500, 630, 750, 800, 1000, 1250, 1500, 1600, 2000, 2500, 3000, 3150, 4000, 5000, 6000, 6300, 8000, 9000, 10000, 11200, 12500, 14000]

y = r_[78.5, 68.7, 59.5, 51.1, 44, 37.5, 31.5, 26.5, 22.1, 17.9, 14.4, 11.4, 8.6, 6.2, 4.4, 3, 2.4, 2.2, 2.4, 3.5, 2.4, 1.7, -1.3, -4.2, -5.8, -6.0, -5.4, -1.5, 4.3, 6, 12.6, 13.9, 13.9, 13, 12.3, 18.4]

xIn = r_[13000.0] 
for i in range(50):
    yOut = interp1d(x,y,'cubic')(xIn)
    print yOut #fluctuates between 2 values
```

**Comment by ev-br** [comment] 2016-10-22 09:34
FWIW, I reproducibly get  `[ 13.10552023]` with current master. The number is slighly different because `find_smoothest` is no longer used. At any rate, I think the issue can be closed.

**Comment by andyfaff** [comment] 2017-08-03 09:57
I see the same as @ev-br, following his recommendation and closing.

**Closed by andyfaff** 2017-08-03 09:57 UTC
Labels: defect, scipy.interpolate
