### ISSUE TITLE
To solve a sparse linear system is much slower in Scipy than in Matlab

### ISSUE THREAD

**Issue by hongchengkuan** [scipy/scipy#9586] opened 2018-12-11 19:48 UTC
My issue is about to solve a sparse linear system is much slower in Scipy than in Matlab.

### Reproducing code example:

I tried the following script in python
```import scipy.sparse
import numpy as np
import scipy.sparse.linalg
import time
N = 6 
diagonals = np.zeros((3, N))   # 3 diagonals
diagonals[0,:] = np.linspace(-1, -N, N)
diagonals[1,:] = -2
diagonals[2,:] = np.linspace(1, N, N)
time1 = time.time()
A = scipy.sparse.spdiags(diagonals, [-1,0,1], N, N, format='csc')
print "spdiags takes " + str(time.time()-time1)
x = np.linspace(-1, 1, N)  # choose solution
b = A.dot(x)               # sparse matrix vector product
time1 = time.time()
x = scipy.sparse.linalg.spsolve(A, b)
print "solve a linear system takes" + str(time.time()-time1)
print x
```

Result:

```
spdiags takes 0.000300168991089
solve a linear system takes0.000184059143066
[-1.  -0.6 -0.2  0.2  0.6  1. ]
```
I also tried the following code in Matlab:
```
N = 6;
diagonals = zeros(N, 3);
diagonals(:,1) = linspace(-1, -N, N);
diagonals(:,2) = -2;
diagonals(:,3) = linspace(1, N, N);
tic
A = spdiags(diagonals, -1:1,N,N);
toc
x = linspace(-1, 1, N)';
b = A * x;           
tic
x = A\b;
toc
x
```

Result:
```
Elapsed time is 0.000452 seconds.
Elapsed time is 0.000073 seconds.

x =

   -1.0000
   -0.6000
   -0.2000
    0.2000
    0.6000
    1.0000
```
It only takes 0.000073 seconds in Matlab while 0.000184059143066 in Scipy.
### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('1.1.0', '1.13.3', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

**Comment by hongchengkuan** [comment] 2018-12-11 23:32
It is just an example.
If N=1000,
then for matlab, the results is 
```
Elapsed time is 0.000406 seconds.
Elapsed time is 0.000056 seconds.
'''
For Scipy, the result is 
```
spdiags takes 0.000359058380127
solve a linear system takes0.00070595741272
```

**Comment by ilayn** [comment] 2018-12-11 23:36
OK it takes more time but we don't distinguish the structure in the matrix. How do you think we should  fix this problem?

**Comment by rgommers** [comment] 2019-08-10 23:27
@perimosocordiae do you want to leave this open? some useful info perhaps, but not a bug and may be covered by gh-6331 already?

**Comment by perimosocordiae** [comment] 2019-08-12 14:04
Let's close as a duplicate of the linked issue and PR.

**Closed by perimosocordiae** 2019-08-12 14:04 UTC
Labels: scipy.sparse

**Comment by denis-bz** [comment] 2020-04-10 16:28
Just a comment, there's a testbench for sparse solvers on random matrices under
[gist.github](https://gist.github.com/denis-bz/c76e5ea59f58acfcafc7d9dbf5429b65) . Sample output, `A` singular + various `diag I`:

      1472 msec  cpu 3.8  solver spsolve  n  10000  diag 0.0001  tol 1e-05:  |b-Ax| 2.3e+02   |x| 5.18579e+21
     14513 msec  cpu   1  solver lgmres   n  10000  diag 0.0001  tol 1e-05:  |b-Ax| 0.019     |x| 0.00291334
    681956 msec  cpu   1  solver gmres    n  10000  diag 0.0001  tol 1e-05:  |b-Ax| 0.018     |x| 0.00216753

      1234 msec  cpu 3.7  solver spsolve  n  10000  diag 1       tol 1e-05:  |b-Ax| 1.6e-15   |x| 6.58673
     14719 msec  cpu   1  solver lgmres   n  10000  diag 1       tol 1e-05:  |b-Ax| 0.026     |x| 0.105505
    682843 msec  cpu   1  solver gmres    n  10000  diag 1       tol 1e-05:  |b-Ax| 0.026     |x| 0.100704

      1162 msec  cpu 3.8  solver spsolve  n  10000  diag 1.2     tol 1e-05:  |b-Ax| 3.2e-17   |x| 0.158854
       104 msec  cpu   1  solver lgmres   n  10000  diag 1.2     tol 1e-05:  |b-Ax| 5.8e-07   |x| 0.158856
        79 msec  cpu   1  solver gmres    n  10000  diag 1.2     tol 1e-05:  |b-Ax| 6.3e-07   |x| 0.158855

It's easy to run different solvers and parameters, e.g.

    python  test_sparse_solvers.py  'solvers="lgmres"'  n=1e5  tols=0

in a shell or IPython.

Should arpack always use `lgmres` instead of `gmres` ?
On one little testcase (Suitesparse plbuckle, 1282^2), eigsh with Minv,
lgmres took 12 sec, gmres 269 sec.
