### ISSUE TITLE
multivariate_normal.rvs: LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by alumbreras** [scipy/scipy#4524] opened 2015-02-14 16:08 UTC
-----
Edit by @jakevdp: this is a nonconvergence of the SVD of a large matrix which appears to be happening only on windows (possibly 32 bit issue?). See discussion below. Here is a short script which reproduces the error on windows (could not reproduce on OSX), along with the traceback:
``` python
# !curl -O http://albertolumbreras.net/temp/Sigma_post.txt

import numpy as np
import scipy
print("numpy version:", np.__version__)
print("scipy version:", scipy.__version__)
from scipy.stats import multivariate_normal

Sigma = np.loadtxt('Sigma_post.txt') 
N = multivariate_normal.rvs(mean=np.zeros(Sigma.shape[0]), cov=Sigma)
```
```
numpy version: 1.9.0
scipy version: 0.14.0
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-12-f547f444e2bc> in <module>()
----> 1 multivariate_normal.rvs(mean = np.zeros(1001), cov = Sigma_post)

C:\Users\lumbrerasa\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\stats\_multivariate.pyc in rvs(self, mean, cov, size)
    404         """
    405         dim, mean, cov = _process_parameters(None, mean, cov)
--> 406         out = np.random.multivariate_normal(mean, cov, size)
    407         return _squeeze_output(out)
    408 

C:\Users\lumbrerasa\AppData\Local\Continuum\Anaconda\lib\site-packages\numpy\random\mtrand.pyd in mtrand.RandomState.multivariate_normal (numpy\random\mtrand\mtrand.c:23189)()

C:\Users\lumbrerasa\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\linalg\decomp_svd.pyc in svd(a, full_matrices, compute_uv, overwrite_a, check_finite)
    101 
    102     if info > 0:
--> 103         raise LinAlgError("SVD did not converge")
    104     if info < 0:
    105         raise ValueError('illegal value in %d-th argument of internal gesdd'

LinAlgError: SVD did not converge
```
/edit

-----------------------
Original info:

 scipy.stats.multivariate_normal raises an excepction with a  covariance matrix (1001x1001) that seems to be definite positive, and has no infinites and no NaNs.

A file with the covariance matrix is here:
http://albertolumbreras.net/temp/Sigma_post.txt

To reproduce the error:

    import numpy as np
    from scipy.stats import multivariate_normal

    with file("Sigma_post.txt","r") as f:
        Sigma = np.loadtxt(f)

    multivariate_normal.rvs(mean = np.zeros(Sigma.shape[0]), cov = Sigma)

scipy: 0.14.0
numpy 1.9.0

**Comment by jakevdp** [comment] 2015-02-14 16:27
Missing the link to ``Sigma_post.txt`` file?

**Comment by alumbreras** [comment] 2015-02-14 16:39
Yeap, trying to share it by dropbox, give a few minutes

**Comment by alumbreras** [comment] 2015-02-14 16:49
@jakevdp ready

**Comment by jakevdp** [comment] 2015-02-14 20:30
(FYI for any others reading this: the txt file is 24.3MB)

**Comment by jakevdp** [comment] 2015-02-14 20:48
I can't reproduce the error.
``` python
# !curl -O http://albertolumbreras.net/temp/Sigma_post.txt

import numpy as np
import scipy

print("numpy version:", np.__version__)
print("scipy version:", scipy.__version__)

from scipy.stats import multivariate_normal

Sigma = np.loadtxt('Sigma_post.txt')    
print("matrix shape:", Sigma.shape)

N = multivariate_normal.rvs(mean=np.zeros(Sigma.shape[0]), cov=Sigma)
print("Size of result:", N.shape)
```
Output:
```
numpy version: 1.9.1
scipy version: 0.14.0
matrix shape: (1001, 1001)
Size of result: (1001,)
```
One question: the scipy stats operation is a thin wrapper on ``np.random.multivariate_normal``. Do you see the error if you use that directly?
``` python
N = np.random.multivariate_normal(np.zeros(Sigma.shape[0]), cov=Sigma)
print("Size of numpy result:", N.shape)
```
Output: 
```
Size of numpy result: (1001,)
```

**Comment by jakevdp** [comment] 2015-02-14 20:54
Note: looks related to #3689

**Comment by alumbreras** [comment] 2015-02-14 23:24
Yes, I see the same error with `np.random.multivariate_normal`

   Python 2.7.8
   Anaconda 2.1;0 (64-bit) (default; Jul 2 2014) [MSC v.1 500 64 bit (AMD64)] on win32.

**Comment by jakevdp** [comment] 2015-02-14 23:36
I just tried with Python 2.7, same package versions, and it ran without error.

In any case, it sounds like this is some sort of Windows-related bug in numpy. Could you paste the traceback here?

**Comment by alumbreras** [comment] 2015-02-14 23:43
yeap, it definitely looks a Windows-related bug... here is the trace:


    ---------------------------------------------------------------------------
    LinAlgError                               Traceback (most recent call last)
    <ipython-input-12-f547f444e2bc> in <module>()
    ----> 1 multivariate_normal.rvs(mean = np.zeros(1001), cov = Sigma_post)

    C:\Users\lumbrerasa\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\stats\_multivariate.pyc in rvs(self, mean, cov, size)
        404         """
        405         dim, mean, cov = _process_parameters(None, mean, cov)
    --> 406         out = np.random.multivariate_normal(mean, cov, size)
        407         return _squeeze_output(out)
        408 

    C:\Users\lumbrerasa\AppData\Local\Continuum\Anaconda\lib\site-packages\numpy\random\mtrand.pyd in mtrand.RandomState.multivariate_normal (numpy\random\mtrand\mtrand.c:23189)()

    C:\Users\lumbrerasa\AppData\Local\Continuum\Anaconda\lib\site-packages\scipy\linalg\decomp_svd.pyc in svd(a, full_matrices, compute_uv, overwrite_a, check_finite)
        101 
        102     if info > 0:
    --> 103         raise LinAlgError("SVD did not converge")
        104     if info < 0:
        105         raise ValueError('illegal value in %d-th argument of internal gesdd'

    LinAlgError: SVD did not converge

**Comment by jakevdp** [comment] 2015-02-15 00:41
Got it. My guess is that this has to do with the linear algebra library that your numpy installation is linked against. I'm not sure where to go with that... @pv, any ideas what may be causing this?

**Comment by jakevdp** [comment] 2015-02-15 00:43
Just noticed something: you're running 64-bit Anaconda on win32. I would bet that this error has to do with your linear algebra libraries running natively in 32 bit. If we could reproduce on another 32-bit system, that would confirm my guess.

**Comment by alumbreras** [comment] 2015-02-15 00:52
In then meanwhile I can try to install Anaconda 32-bit to see if it works.

**Comment by alumbreras** [comment] 2015-02-15 12:15
Eureka, it works on Anaconda 32-bit.

    import numpy as np
    import scipy

    print("numpy version:", np.__version__)
    print("scipy version:", scipy.__version__)

    from scipy.stats import multivariate_normal

    Sigma = np.loadtxt('Sigma_post.txt')    
    print("matrix shape:", Sigma.shape)

    N = multivariate_normal.rvs(mean=np.zeros(Sigma.shape[0]), cov=Sigma)
    print("Size of result:", N.shape)

    ('numpy version:', '1.9.0')
    ('scipy version:', '0.14.0')
    ('matrix shape:', (1001, 1001))
    ('Size of result:', (1001,))

**Comment by jakevdp** [comment] 2015-02-15 15:11
Great! Yeah, it's probably some incompatibility between the 64-bit Python install and the win32 BLAS/LAPACK defaults. This may even be an Anaconda bug; I'm not sure. That kind of stuff is well beyond my own realm of knowledge...

**Comment by alumbreras** [comment] 2015-02-15 21:52
For info, it seems that it was running in 64 bits.

from stackoverflow http://stackoverflow.com/questions/28526062/does-64-bit-anaconda-on-win32-uses-32-bit-or-64-bit

    Anaconda 2.1;0 (64-bit) (default; Jul 2 2014) [MSC v.1 500 64 bit (AMD64)] on win32
    Here win32 indicates that the system is Windows. The name of the Windows API on both x86 and      x64 is Win32. It's exactly the same API but with different sized pointers. It is a little confusing but     when you read win32, interpret that as meaning desktop Windows.

    What matters here is the AMD64. That indicates the machine on which the code executes. Which     is the x64 machine.

    Your code is running in a 64 bit process.

**Comment by jakevdp** [comment] 2015-02-16 16:34
OK – still, it's probably some issue with the windows LAPACK.

**Comment by rgommers** [comment] 2015-10-24 18:22
The ``Sigma.txt`` link doesn't work anymore, and anyway this doesn't look like an issue in Scipy. Any objections to closing it?

**Comment by jakevdp** [comment] 2015-10-25 12:56
I think we can close it.

**Comment by rgommers** [comment] 2015-10-25 14:13
Thanks Jake. Closing.

**Closed by rgommers** 2015-10-25 14:13 UTC
Labels: scipy.stats
