### ISSUE TITLE
distance matrix in python different from R used in clustering algo

### ISSUE THREAD

**Issue by geraldstanje** [scipy/scipy#6054] opened 2016-04-11 04:39 UTC
Hi, 

Im currently porting some code from R to python.
I would like to calculate the distance matrix, but see a different result as in R. why is that?
The distance matrix is the input of a hierarchical clustering algo -> linkage

also how can i use cut_tree to group into 15 groups after calling the clustering (linkage)? how can i plot the dendogram for that?

## Python
```
import numpy as np
from scipy.spatial.distance import pdist, squareform

m = np.zeros((4, 2))
val = 1
for i in range(0,4):
  for j in range(0,2):
    m[i,j] = val
    val = val + 1
      
d = squareform(pdist(m, 'euclidean'))
print d.shape
print d
print m
```

## Python output
```
(4, 4)
[[ 0.          2.82842712  5.65685425  8.48528137]
 [ 2.82842712  0.          2.82842712  5.65685425]
 [ 5.65685425  2.82842712  0.          2.82842712]
 [ 8.48528137  5.65685425  2.82842712  0.        ]]
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]
```

## R
```
m = matrix(0, 4, 2)
val = 1
for (i in 1:dim(m)[1]) {
  for (j in 1:dim(m)[2]) {
    m[i,j] = val
    val = val + 1
    print (val)
  }
}
d <- dist(m, method = "euclidean")
print (dim(as.matrix(d)))
print (d)
print (m)
```

## R output
```
> print (dim(as.matrix(d)))
[1] 4 4
> print (d)
         1        2        3
2 2.828427                  
3 5.656854 2.828427         
4 8.485281 5.656854 2.828427
> print (m)
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8
```

**Comment by ev-br** [comment] 2016-04-11 05:12
The matrix is the same within the output accuracy. Furthermore, usage questions are better asked on Stackoverflow or scipy-user mailing list. This tracker is for bug reports. This is not a bug, so closing.

**Closed by ev-br** 2016-04-11 05:12 UTC

**Comment by geraldstanje** [comment] 2016-04-11 13:08
@ev-br "The matrix is the same within the output accuracy. " what do you mean? this was supposed to be a question...
