### ISSUE TITLE
 scipy.integrate.quad gives wrong result when change an argument a little

### ISSUE THREAD

**Issue by Lisong86** [scipy/scipy#14101] opened 2021-05-21 07:33 UTC
In the following integral function, when n2=22144 the integral value is w= 0.4256854383924181. But with matlab, integral value will be 11768644300129.305. I checked the value and found matlab is right. When n2=22145,the values in scipy and matlab are  the same.

#### Reproducing code example:

```
from math import sqrt, log, exp
import numpy as np
from scipy.integrate import quad

def integrand(x, r1, r2):
    a = r1 + r2
    b = r1 * r2
    R = a * x / 2
    R1 = R ** 2 - a ** 2
    R2 = R ** 2 - (r1 - r2) ** 2
    vdw = -7e-21 * (2 * b / R1 + 2 * b / R2 + log(R1 / R2))
    edl = 7.8e-12 * b / a * log(1 + exp(-328774227 * (R - a)))
    force = vdw + edl
    return exp(force / 4.11447e-21) / x ** 2

n1 = 5010
n2 = 22144
radius1 = 1.05 * 10 ** -8 * n1 ** (1 / 1.8)
radius2 = 1.05 * 10 ** -8 * n2 ** (1 / 1.8)
w = quad(integrand, 2, np.inf, args=(radius1, radius2))
print('w=', w[0])
```

#### Scipy/Numpy/Python version information:

1.5.4 1.19.5 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)

**Comment by ilayn** [comment] 2021-05-21 08:00
Are you possibly using vpa or some other high precision library on matlab? You are essentially working with practical zeros for standard double floats. 

`exp(force / 4.11447e-21) / x ** 2` this is practically divide by zero unless `force` is pathetically close to zero. Similarly other parts of the problem is ill conditioned too. 

Note that standard floating point number precision is ~2e-16. Anything past that point is just noise even though it might work occasionally when the operation is well defined. However in general there is no guarantee for accuracy. You might want to scale your data so that you are operating away from the precision.

**Comment by Lisong86** [comment] 2021-05-25 03:27
I didn't use vpa in matlab. I should revise the results from matlab as follows.
```
n2 = 22144, w = 1.1772e+13
n2 = 22145, w = 1.1775e+13
```
In scipy, I got: 
```
n2 = 22144, w = 0.4256854383924181
n2 = 22145, w = 11774635265351.027   # 1.1775e +13
```
It is clear that, when n2=22145, the results from scipy and matlab are close to each other, but not in the case of n2=22144.

In` exp(force / 4.11447e-21) / x ** 2`, the force is close to zero, because `vdw `and `edl `are both small value. In fact, I can calculate the corrent value of `exp(force / 4.11447e-21) / x ** 2`  and plot its cruve. Also, I can get a very close (correct) integral value with` scipy.integrate.trapz`. 

A BBS user told me that he/she copy the code and obtain (He/She used scipy 1.5.2, but I did not get the same results with scipy 1.5.2 ):
```
n2=22144, w= 11772040939067.406  
n2=22145, w= 11774635265351.027
```

If change 4.11447 in ` exp(force / 4.11447e-21) / x ** 2` to 4.1145 and 4.1144, I will get (puzzling):
```
#4.1145
n2=22144, w= 11768644300129.305
n2=22145, w= 11771237857123.924

#4.1144
n2=22144, w= 0.42568494248362776
n2=22145, w= 0.4256854757392548
```

**Comment by ilayn** [comment] 2021-05-25 05:42
Yes as I mentioned you are working in the numerical noise. Matlab can also get confused and it won't be Matlab's fault.

**Comment by tupui** [comment] 2022-04-15 13:04
Seems like there is nothing to do here. Closing.

**Closed by tupui** 2022-04-15 13:04 UTC
Labels: scipy.integrate
