### ISSUE TITLE
BUG: dblquad ignores error tolerances

### ISSUE THREAD

**Issue by ketch** [scipy/scipy#6898] opened 2016-12-29 06:54 UTC
Due to https://github.com/scipy/scipy/commit/1b0a1dd95157c6931a46f3181ba5280d34ee1431, `dblquad` simply throws away the arguments `epsabs` and `epsrel`.  See also https://github.com/scipy/scipy/issues/6889.  It seems that we need tests that use non-default error tolerances.

This breaks the build in Clawpack, in two ways: modified return values cause a regression, and the inability to specify a loose error tolerance causes one test to take more than 100x longer than it should.

Paging people involved in the PR that introduced this: @woodscn @certik @rgommers

**Comment by certik** [comment] 2016-12-29 12:32
Hi David,

Sorry about that, we need to write some tests for that.

Nate, would you mind looking into that please?

Ondrej


Sent from my mobile phone.

On Dec 28, 2016 11:54 PM, "David Ketcheson" <notifications@github.com>
wrote:

Due to 1b0a1dd
<https://github.com/scipy/scipy/commit/1b0a1dd95157c6931a46f3181ba5280d34ee1431>,
dblquad simply throws away the arguments epsabs and epsrel. See also #6889
<https://github.com/scipy/scipy/issues/6889>. It seems that we need tests
that use non-default error tolerances.

This breaks the build in Clawpack, in two ways: modified return values
cause a regression, and the inability to specify a loose error tolerance
causes one test to take more than 100x longer than it should.

Paging people involved in the PR that introduced this: @woodscn
<https://github.com/woodscn> @certik <https://github.com/certik> @rgommers
<https://github.com/rgommers>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scipy/scipy/issues/6898>, or mute the thread

**Comment by woodscn** [comment] 2016-12-29 15:46
As a temporary solution, you can use scipy.integrate.nquad directly, which gives the control you need (and more). I'll put together a patch to fix this as soon as I can.

**Comment by ketch** [comment] 2016-12-29 18:03
Thanks!  I think we'll just force our test script to use 0.17.1 for now, but using `nquad` may also be a good option.

**Comment by rgommers** [comment] 2017-01-16 09:35
Hmm, wrote my email about 0.19.x a bit too quick. This one is a blocker I think. @woodscn do you have time to look into this in the near future?

**Comment by woodscn** [comment] 2017-01-16 16:14
I'll take a look at it today. I should be able to take care of it, if it's a simple fix. 






On Mon, Jan 16, 2017 at 2:35 AM -0700, "Ralf Gommers" <notifications@github.com> wrote:












Hmm, wrote my email about 0.19.x a bit too quick. This one is a blocker I think. @woodscn do you have time to look into this in the near future?

**Comment by ev-br** [comment] 2017-02-15 17:14
Fixed by https://github.com/scipy/scipy/pull/6965. Note however that https://github.com/scipy/scipy/pull/6965 does not have a test, so it'd be great if someone who uses this writes one.

**Closed by ev-br** 2017-02-15 17:14 UTC
Labels: defect, scipy.integrate
