### ISSUE TITLE
Why does scipy.stats.ncx2.cdf return nan if noncentrality parameter is zero?

### ISSUE THREAD

**Issue by rhstanton** [scipy/scipy#10120] opened 2019-05-01 20:12 UTC
If I try to calculate a noncentral chi-square cdf with a noncentrality parameter of zero, I get a nan returned. A non-centrality parameter of zero yields a perfectly well-defined (central) chi-squared distribution, so why not just return a value? I.e., implement internally the test that I currently have to perform:

c = ncx2.cdf(x, df, nonCent) if nonCent > 0 else chi2.cdf(x, df)

**Comment by WarrenWeckesser** [comment] 2019-05-01 20:53
@rhstanton, thanks for reporting this.

I agree, `ncx2` should handle `nc=0`.

**Comment by ev-br** [comment] 2019-05-20 20:54
Duplicate of https://github.com/scipy/scipy/issues/5441

**Comment by sethtroisi** [comment] 2020-05-23 07:11
Fixed by https://github.com/numpy/numpy/pull/6613 (also a duplicate)

**Closed by sethtroisi** 2020-05-23 07:11 UTC
Labels: defect, scipy.stats
