### ISSUE TITLE
ks_2samp: example description does not match example output

### ISSUE THREAD

**Issue by MER-C** [scipy/scipy#14313] opened 2021-06-28 12:40 UTC
The text describing the example no longer matches the output of the code.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html
https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L7454

> For a slightly different distribution, we cannot reject the null hypothesis at a 10% or lower alpha since the p-value at 0.144 is higher than 10%

```
rvs3 = stats.norm.rvs(size=n2, loc=0.01, scale=1.0, random_state=rng)
stats.ks_2samp(rvs1, rvs3)
KstestResult(statistic=0.07833333333333334, pvalue=0.4379658456442945)
```

This is a regression, a much earlier version is correct:
https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.ks_2samp.html

**Comment by mdhaber** [comment] 2021-06-29 14:48
@tupui It looks like this happened because seeds were removed in gh-13863.

Perhaps more confusing is the next one:

> For an identical distribution, we cannot reject the null hypothesis since the p-value is high, 41%:
```
>>> rvs4 = stats.norm.rvs(size=n2, loc=0.0, scale=1.0, random_state=rng)
>>> stats.ks_2samp(rvs1, rvs4)
KstestResult(statistic=0.12166666666666667, pvalue=0.05401863039081145)
```
If the chosen significance level were 10%, as suggested in the previous part, then the null hypothesis would be rejected here. 

Besides the rendered documentation, without an explicit seed, the user will see different numbers than those here. I know we use an explicit seed under the hood, but it is misleading to give an example like this without an explicit seed.

It might be best if the example were rewritten as a practical example with real data, but in the meantime, can we add an explicit seed back (and rewrite the text accordingly)?

**Comment by tupui** [comment] 2021-06-29 14:55
> It might be best if the example were rewritten as a practical example with real data, but in the meantime, can we add an explicit seed back (and rewrite the text accordingly)?

I am really not sure about explicit seeding. I am afraid this would open the door to more exceptions and in no time we are back to having seeds everywhere. But if we must, then put something generated by a `SeedSequence` and with a clear warning in the doc to say not to copy the value.
```python
from numpy.random import SeedSequence
print(SeedSequence().entropy)
```

I would prefer to either have a real example as you suggest, or just to make the text less precise about values (or use the new values as we have a seed under the hood).

**Comment by josef-pkt** [comment] 2021-06-29 15:08
In many cases I had chosen seeds explicitly for docs to have a nice example to illustrate the method. In those cases, the seed was not arbitrary.
(I random generated a seed, printed it out, and kept one that "looked nice".)

The point of an example is to show the given function or method. not explain Life, Universe and Everything.

IMO, examples should be deterministic and replicable by users, unless they are just a partial code snippet.

**Comment by rkern** [comment] 2021-06-29 15:19
As long as the seeds are large (128 bits), I don't mind that approach. I'm not too concerned about people literally copy-pasting the examples (so I don't care to have an explicit warning) so much as seeing every example with tiny seeds. The cumulative effect of _every_ example with `seed=0` or `seed=1234` has had a bad effect on production code, I think.

**Comment by josef-pkt** [comment] 2021-06-29 15:28
@rkern 
Weren't seeds limited to 6 digits in the old times?

my default seed has been something like 987146 for a long time, or variations of it if I didn't like the outcome.

**Comment by josef-pkt** [comment] 2021-06-29 15:33
@tupui I only had skimmed parts of the discussion, since I didn't want to go through the details.

I don't think anyone made the point that seeds are not random in the doc examples.
E.g. we want an example that does not reject the null, or rejects the null depending on what the "true" hypothesis and data generating process is.

**Comment by rkern** [comment] 2021-06-29 15:40
In the olden-times (`RandomState`), they were limited to 32 bits, about 10 digits, for dumb reasons (I bungled the 64-bit `long` logic in the days before I had access to 64-bit machines). But now they are arbitrary length, and 128 bits is the preferred length.

> I don't think anyone made the point that seeds are not random in the doc examples.

For most examples, they _are_ pretty arbitrary. They just control what gets printed out in the output, which is usually not referenced in the prose or matters much to the understanding of the example. Not too many tell a narrative like did here. For these, if the [implicit documentation seed](https://github.com/scipy/scipy/blob/master/scipy/_lib/_util.py#L542-L550) doesn't tell the story that you want, I'll support using an explicit 128-bit seed in the example.

**Comment by tupui** [comment] 2021-06-29 15:41
@josef-pkt all examples are using the new `np.random.Generator` hence they accept 128 bits seeding (and preferably using the `SeedSequence` as I showed). You are right that `np.random.RandomState` does not allow 128 bits seeding.

Yes the examples have the seed fixed in the background by replacing `>>> rng = np.random.default_rng()` with a seed (generated using `SeedSequence`). I still think that we should be able to craft examples with this constrains. Here, just changing the number of sample might be enough to get what we want...

**Comment by jraman** [comment] 2021-07-10 15:59
Using a seed generated by `SeedSequence` (as @tupui suggests) makes it replicable (as @josef-pkt suggests) and protects against copy and paste (because rerunning the code generates a different seed).

Simply print the seed for replicability.

Example below:
``` py
>>> from scipy import stats
>>> import numpy as np

>>> seed = np.random.SeedSequence().entropy
>>> print(seed)
183891471810357162447429969345361050521

>>> rng = np.random.default_rng(seed)
>>> n1, n2 = 200, 300

>>> rvs1 = stats.norm.rvs(size=n1, loc=0., scale=1, random_state=rng)
>>> rvs2 = stats.norm.rvs(size=n2, loc=0.5, scale=1.5, random_state=rng)
>>> print(stats.ks_2samp(rvs1, rvs2))
KstestResult(statistic=0.24, pvalue=1.5876939054582095e-06)

>>> rvs3 = stats.norm.rvs(size=n2, loc=0.01, scale=1.0, random_state=rng)
>>> print(stats.ks_2samp(rvs1, rvs3))
KstestResult(statistic=0.08, pvalue=0.4115432028915931)

>>> rvs4 = stats.norm.rvs(size=n2, loc=0.0, scale=1.0, random_state=rng)
>>> print(stats.ks_2samp(rvs1, rvs4))
KstestResult(statistic=0.06333333333333334, pvalue=0.7048747432345441)
```

Whoever wants to reproduce the result can easily do so by explicitly setting the seed to the one printed.

This method also protects against blind copy-and-paste, because `SeedSequence` ensures a different seed for each run.  Also, the documentation should make it explicit that if the code is copied and run it would generate different results because of a different seed.

I am happy to submit a pull-request if this method is acceptable.

**Comment by rkern** [comment] 2021-07-10 16:09
Our current policy for the docstring example is just to use `rng = np.random.default_rng()` per gh-13863. The documentation generator will [replace that with an implicit seed](https://github.com/scipy/scipy/blob/master/scipy/_lib/_util.py#L542-L550), so use that seed when you run the rest of your example.

**Comment by jraman** [comment] 2021-07-10 16:54
Hmm.  Good to know, thanks.  But ...

 1. Does `_fixed_default_rng` mean that the documentation ends up being written for the current hard-coded seed in `_fixed_default_rng`?  Imagine changing the hard-coded seed (1638083107694713882823079058616272161) to some other value.  That would break the documentation in other places and hence makes it hard to change this value, right?
 2. As @josef-pkt  pointed out, some seeds work better than others in the sense that they illustrate the example better.  Also, in some cases the hard-coded seed may do poorly.  For example, using a seed of 130833722220271600325062290764672999418 results in `ks_2samp(rvs1, rvs4)` having a p-value of 0.005755608668250978 which can be confusing.  

I think that there should be flexibility in setting the seed for each example while protecting against cut-and-paste.

Is there a way perhaps to specify in the doc a seed for `_fixed_default_rng` -- this seed would be printed out automatically as part of the documentation (or even hidden in comments since this is a replicability thing)?

**Comment by rkern** [comment] 2021-07-10 17:04
1. We're not going to change it.
2. I've [already addressed this in this thread](https://github.com/scipy/scipy/issues/14313#issuecomment-870692394).
3. There are certainly ways to surface that seed somewhere in the documentation so that users and documenters are more aware of it (and so it's easier to access when constructing examples), but printing it out in each example is probably too much.

**Comment by jraman** [comment] 2021-07-13 12:32
`kstest` has a similar issue ([source][source]):

```
    >>> x = stats.norm.rvs(loc=0.2, size=100, random_state=rng)
    >>> stats.kstest(x, 'norm', alternative='less')
    KstestResult(statistic=0.1002033514..., pvalue=0.1255446444...)

    Reject null hypothesis in favor of alternative hypothesis: less
```

Documentation in an earlier version is consistent with the results: https://docs.scipy.org/doc/scipy-1.6.0/reference/generated/scipy.stats.kstest.html

[source]: https://github.com/scipy/scipy/blob/v1.7.0/scipy/stats/stats.py#L7622-L7626

**Comment by mdhaber** [comment] 2022-03-12 07:06
The original issue was fixed by gh-15651.

**Closed by mdhaber** 2022-03-12 07:06 UTC
Labels: scipy.stats, Documentation
