### ISSUE TITLE
dtype conversion when copying sparse matrices

### ISSUE THREAD

**Issue by jeremiedbb** [scipy/scipy#11522] opened 2020-02-14 16:33 UTC
The copy of a sparse matrix does not preserves the dtype of indices and indptr
```py
>>> import numpy as np
>>> from scipy.sparse import random

>>> X = random(10, 10, format='csr')
>>> X.indices.dtype
dtype('int32')

>>> X.indices = X.indices.astype(np.int64)
# Now I have a sparse matrix with int64 indices
>>> X.indices.dtype
dtype('int64')

# But its copy has int32 indices
>>> X.copy().indices.dtype
dtype('int32')
```

I observed this with scipy 1.4.1. Did not check previous versions.

**Comment by perimosocordiae** [comment] 2020-02-18 15:17
The `.copy()` method ends up calling the `csr_matrix` constructor, which in turn calls `get_index_dtype(..., check_contents=True)`. This means that we look inside the index and indptr arrays to find the minimum acceptable dtype out of int32 and int64. This isn't new behavior, but I do understand that it's a bit surprising.

I should also note that there's a possibly undocumented constraint on sparse matrix backing arrays: `indices` and `indptr` must have the same dtype. This is required for ease of interacting with native code. Your scenario still happens when both arrays are manually changed to int64, though.

**Comment by perimosocordiae** [comment] 2020-02-18 15:20
Also, issue gh-11496 proposed a change that would likely resolve this issue. @evansd hasn't opened a PR yet, but stay tuned for that.

**Comment by jeremiedbb** [comment] 2020-02-19 09:47
Thanks for the details

> This isn't new behavior, but I do understand that it's a bit surprising.

Beyond surprising, it could be considered an unwanted behavior in some situations. For instance using cython's typed memoryviews might lead to a dtype mismatch depending on whether you copied you matrix or not.

> Also, issue gh-11496 proposed a change that would likely resolve this issue. @evansd hasn't opened a PR yet, but stay tuned for that.

I'll follow that, thanks !

**Comment by jjerphan** [comment] 2023-05-26 17:47
This is related to discussions in #16774.

#18509 has removed downcasting for indices and indices pointers arrays, and I guess addressing it for copy also makes sense. What do people think?

**Comment by ivirshup** [comment] 2023-05-26 18:14
I think this behavior actually did change in https://github.com/scipy/scipy/pull/18509, but the indices/ inptr are still homogenized. If one of the arrays is 64 bit, then the copy will have both 64bit.

I don't know if this is worth it unless heterogenous dtypes are supported in compiled code (as discussed in:

* https://github.com/scipy/scipy/issues/16774

**Comment by jjerphan** [comment] 2023-05-26 19:09
I still can reproduce as of 8cf86bc casting `indices` and `indptr` to `np.int64`:
```python
import scipy
import numpy as np
from scipy.sparse import random

print("Scipy version:", scipy.__version__)

X = random(10, 10, format='csr')
print(X.indices.dtype, X.indptr.dtype)

X.indices = X.indices.astype(np.int64)
X.indptr = X.indptr.astype(np.int64)

print(X.indices.dtype, X.indptr.dtype)

X_copy = X.copy()

print(X_copy.indices.dtype, X_copy.indptr.dtype)
```

```
Scipy version: 1.11.0.dev0+2197.8cf86bc
int32 int32
int64 int64
int32 int32
```

**Comment by ivirshup** [comment] 2023-05-26 19:20
If the compiled code could work with mixed dtypes, I would be 100% maintaining dtypes

But, otherwise there are a upcasts/ allocation when any compiled code is hit. So I don't know if it's worth being a more optimal in the case when someone copies, but then doesn't do anything with the copy.

**Comment by perimosocordiae** [comment] 2023-07-24 03:37
We have a separate issue now for discussion of mixed dtypes (#16774) so I'll close this issue as "Working as Intended" for now.

**Closed by perimosocordiae** 2023-07-24 03:37 UTC
Labels: scipy.sparse
