### ISSUE TITLE
BUG: scipy 1.9.2+ MILP presolver causes failed assertion in HIGHS source in some cases where there is a solution

### ISSUE THREAD

**Issue by jdclouse** [scipy/scipy#17379] opened 2022-11-09 16:43 UTC
### Describe your issue.

Until v1.9.2, the below code snippet would find a solution with the default presolver setting. Since 1.9.2, something in the presolver activity causes a failed assertion in the HIGHS source and kills the python process.

Interestingly, nearby versions of A, in the code snippet below, still work with the presolver. 

I suspect this is related to [this bug](https://github.com/scipy/scipy/issues/17220), but I'd like to point out there appear to be different assertions failing.

### Reproducing Code Example

```python
from scipy.optimize import milp, LinearConstraint
import numpy as np

c = \
np.array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1., -10., -10., -10., -10., -10., -10.,
       -10., -10.])

integrality = \
np.array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2.])

A = \
np.array([[ -0.        ,  -0.        ,  -0.54042498,   1.13371461,
             0.        ,   0.        ,   0.4826131 ,  -1.13366954,
             0.        ,   0.        ,  -0.4826131 ,   0.61947086,
             0.        ,   0.        ,   0.54067354,  -0.61847659,
             7.06155181,   7.06155181,   7.06155181,   7.06155181,
           -18.36003472, -18.36003472, -18.36003472, -18.36003472],
          [ -0.54042498,   0.54042498,   0.        ,   0.88718253,
             0.4826131 ,  -0.4826131 ,  -0.        ,  -0.88718253,
             0.4826131 ,  -0.4826131 ,  -0.        ,  -0.88668539,
            -0.54067354,   0.54067354,   0.        ,   0.88658917,
           -17.59908189, -16.13027912,   2.25969658,   3.72849936,
             3.72849936,   2.25969658, -16.13027912, -17.59908189],
          [ -1.13371461,   1.13371461,   0.88718253,   0.        ,
            -1.13366954,   1.13366954,   0.88718253,   0.        ,
             0.61947086,  -0.61947086,  -0.88668539,   0.        ,
             0.61847659,  -0.61847659,  -0.88658917,   0.        ,
             0.        ,   0.        ,  -0.        ,  -0.        ,
             0.        ,   0.        ,   0.        ,   0.        ]])

b_l = np.array([0., 0., 0.])
b_u = np.array([0., 0., 0.])
constraints = LinearConstraint(A, b_l, b_u)

u = \
np.array([1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.05, 1.05, 1.05, 1.05, 1.05, 1.05,
       1.05, 1.05])

l = \
np.array([0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005,
       0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.5  , 0.5  ,
       0.5  , 0.5  , 0.5  , 0.5  , 0.5  , 0.5  ])

r = milp(c=c,
    constraints=constraints,
    integrality=integrality,
    bounds=np.array([l,u]),
    options={'presolve': False})
print(r)

# Dies in Highs.cpp in SciPy 1.9.2+, kills python
r = milp(c=c,
    constraints=constraints,
    integrality=integrality,
    bounds=np.array([l,u]))
print(r)
```

### Error message

```shell
python3: ../../scipy/_lib/highs/src/lp_data/Highs.cpp:1014: HighsStatus Highs::run(): Assertion `assessLp(reduced_lp, options_) == HighsStatus::kOk' failed.
Aborted (core dumped)
```

### SciPy/NumPy/Python version information

1.9.3 1.23.4 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by jgborch** [comment] 2022-11-09 23:27
@nboudrie and I will be taking on this issue.

**Comment by jajhall** [comment] 2022-11-25 22:56
I can't reproduce this behaviour. The MIP is infeasible, since the only feasible assignment of the variables is a vector of 1's and the row sums don't add up to 0.

This failure is unrelated to https://github.com/scipy/scipy/issues/17220

**Comment by mckib2** [comment] 2022-11-27 04:15
@jdclouse @jgborch gh-17430 should (at least partially) resolve this issue.  Can you test against the latest SciPy main branch to see if the issue has been resolved?

**Comment by mckib2** [comment] 2022-12-06 04:27
I just tested this example against gh-17430 and it does not crash.  I'll close this issue for now -- @jdclouse please reopen if you're still encountering issues or open a new issue if something comes up!

**Closed by mckib2** 2022-12-06 04:27 UTC
Labels: defect, scipy.optimize
