### ISSUE TITLE
Fisk distribution documentation typo

### ISSUE THREAD

**Issue by gregorp90** [scipy/scipy#13996] opened 2021-05-06 13:00 UTC
I'm using scipy's Fisk distribution. The [documentation](https://github.com/scipy/scipy/blob/v1.6.3/scipy/stats/_continuous_distns.py) says the pdf is:

`f(x, c) = c x^{-c-1} (1 + x^{-c})^{-2}`,

but it should be:

`f(x, c) = c x^{c-1} (1 + x^{c})^{-2}`.

I think the same applies to the documentation of the Burr distribution. I'm not sure if this is worthy of an issue, just wanted to mention it because it could potentially confuse users.

**Comment by mdhaber** [comment] 2021-05-06 18:34
@gregorp90, do you agree this is a duplicate of gh-6073?

**Comment by gregorp90** [comment] 2021-05-07 07:33
@mdhaber yes, I agree. My bad, I should have checked for the issues. I read through the other two issues and it turns out this is actually the same formula, just rearranged (checked on paper):
```
(c * x**(c - 1)) / (1 + x**c)**2
(c * x**(-c - 1)) / (1 + x**(-c))**2
```
Not really intuitive (for me at least), but nevertheless the same. I agree that a comment on this in the documentation would help in avoiding similar confusion. As noted in one of the other two issues, the first one is probably more common.

**Comment by mdhaber** [comment] 2021-05-07 16:40
No, that is not obvious to me either! For the record:
```python3
from sympy import symbols, simplify
x, c = symbols('x, c')
f = (c * x**(c - 1)) / (1 + x**c)**2
f2 = (c * x**(-c - 1)) / (1 + x**(-c))**2
simplify(f - f2)  # 0
```
In that case, I'd actually suggest that we add the second definition, e.g. "This is equivalent to...", to the notes. And maybe make the one without the negative sign the primary one. 
I hope you don't mind, but rather than fixing it right away, I think I'll leave this open as a good first issue.

**Comment by rajpratyush** [comment] 2021-05-08 04:50
Hi @mdhaber I am first time contributor to this project  Can I Fix this issue?

**Comment by mdhaber** [comment] 2021-05-09 13:33
@rajpratyush of course! But it looks like someone already posted a PR, gh-14003. Are there other issues with the "good first issue" label that interest you?

**Comment by rajpratyush** [comment] 2021-05-09 13:37
@mdhaber yess i have commented in few of them 
 Can you suggest me some ??
I am well versed with sphinx and python , html, css as well

Btw i had a question should i ask here or open a new issue?

**Comment by mdhaber** [comment] 2021-05-10 04:48
Yes, there is an upcoming developer meeting; see details [here](https://mail.python.org/pipermail/scipy-dev/2021-May/024779.html). Please join the mailing list for announcements like that.

> Btw i had a question should i ask here or open a new issue?

Depends on the question. If it is a bug report or feature request, a new issue would be appropriate. If it is a usage question, please use stackoverflow.

> Can you suggest me some

Specific ones from [this list](https://github.com/scipy/scipy/labels/good%20first%20issue)? Otherwise I don't have any other suggestions right now, unfortunately.

**Comment by gregorp90** [comment] 2021-05-10 06:45
> I hope you don't mind, but rather than fixing it right away, I think I'll leave this open as a good first issue.

No, of course, I don't mind. Thank you for the clarification!

**Comment by mdhaber** [comment] 2022-03-12 07:20
This was fisked in gh-14003 : )

**Closed by mdhaber** 2022-03-12 07:20 UTC
Labels: scipy.stats, Documentation, good first issue
