### ISSUE TITLE
scipy.special import error in cygwin

### ISSUE THREAD

**Issue by PikalaxALT** [scipy/scipy#7350] opened 2017-04-29 01:50 UTC
Attempting to import scipy.special raises an import error in cygwin-64.  Scipy was compiled using gcc-fortran and lapack0-devel from the cygwin package manager, and `pip install scipy`.

### Reproducing code example:
```
import scipy.special as sc
```

### Error message:
```
  File "/usr/lib/python2.7/site-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: No such file or directory
```

### Scipy/Numpy/Python version information:
```
('0.19.0', '1.12.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

**Comment by rgommers** [comment] 2017-06-05 10:11
That's not much to go on. We need at least a full build log to be able to help.

**Comment by cycleuser** [comment] 2017-11-14 17:25
There seems to be  nothing named _ufuncs at that location of 'site-packages/scipy/special/'

what else do you need as build log?

Tell us maybe?

**Comment by ilayn** [comment] 2017-11-14 18:38
@cycleuser OP mentions that SciPy is built from source and we need to see what went wrong during the build. 

And there are all kinds of `_ufuncs` files in the directory 

![image](https://user-images.githubusercontent.com/1303842/32797823-3a628706-c973-11e7-9b7c-94f22ace0ad6.png)

**Comment by gety9** [comment] 2018-11-16 03:11
Having same problem:

```
Traceback (most recent call last):
  File "/usr/bin/bean-extract", line 4, in <module>
    from beancount.ingest.extract import main; main()
  File "/usr/lib/python3.6/site-packages/beancount/ingest/extract.py", line 203, in main
    args, config, downloads_directories = scripts_utils.parse_arguments(parser)
  File "/usr/lib/python3.6/site-packages/beancount/ingest/scripts_utils.py", line 56, in parse_arguments
    mod = runpy.run_path(args.config)
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Btycoon.import", line 9, in <module>
    from importers import chase
  File "/cygdrive/r/Bldgr/office/importers/chase/__init__.py", line 21, in <module>
    from smart_importer import PredictPostings
  File "/cygdrive/c/cygwin64/smart_importer/smart_importer/__init__.py", line 9, in <module>
    from smart_importer.predictor import EntryPredictor
  File "/cygdrive/c/cygwin64/smart_importer/smart_importer/predictor.py", line 7, in <module>
    from sklearn.pipeline import make_pipeline, FeatureUnion
  File "/usr/lib/python3.6/site-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/usr/lib/python3.6/site-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/usr/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 13, in <module>
    from .validation import (as_float_array,
  File "/usr/lib/python3.6/site-packages/sklearn/utils/validation.py", line 22, in <module>
    from ..utils.fixes import signature
  File "/usr/lib/python3.6/site-packages/sklearn/utils/fixes.py", line 83, in <module>
    from scipy.special import boxcox  # noqa
  File "/usr/lib/python3.6/site-packages/scipy/special/__init__.py", line 586, in <module>
    from ._ufuncs import *
ImportError: No such file or directory
```

**Comment by gety9** [comment] 2018-11-16 03:19
@PikalaxALT did you manage to solve the issue?

**Comment by mckib2** [comment] 2021-01-16 04:42
@gety9 The puush link has (quite reasonably) expired by now.  @PikalaxALT and @gety9 , are you still experiencing these issues?

I suspect a lot has changed since original issue report.  I installed scipy master from source using most recent Cygwin x86_64 on Windows 10 using this command: `python setup.py build_ext --inplace`.  Cygwin gave me these versions out of the box:
- gcc 8.1.0 (but MSVC 2019 is used from MSVC 2019 build tools)
- gfortran 8.1.0
- python3.9

Python packages:
- `numpy==1.19.5`
- `scipy` master at ac63126f4
- `Cython==0.29.21`

This issue has reports on Python2.7 and Python3.6 (both no longer supported).  I used the same openblas binary that the CI does because that was easy for me to set up, but I don't think there will be build differences because of this based on the issue report.

`python -c "import scipy.special as sc"` runs without issue.  All but one of the `scipy.special` tests also pass:
```python
test = <Data for ellip_harm_2: ellip>, dtype = <class 'numpy.float64'>

    def _test_factory(test, dtype=np.double):
        """Boost test"""
        with suppress_warnings() as sup:
            sup.filter(IntegrationWarning, "The occurrence of roundoff error is detected")
            with np.errstate(all='ignore'):
>               test.check(dtype=dtype)
E               AssertionError:
E               Max |adiff|: 0
E               Max |rdiff|: 0
E               Bad results (1 out of 400) for the following points (in output 0):
E                                          76.                            175.                             14.                              1.                          20.456 =>
             nan !=              2.82846091362e-19  (rdiff                             0.)

dtype      = <class 'numpy.float64'>
sup        = <numpy.testing._private.utils.suppress_warnings object at 0x0000027A9E811CA0>
test       = <Data for ellip_harm_2: ellip>

scipy\special\tests\test_data.py:575: AssertionError
=================================================================================== short test summary info ===================================================================================
FAILED scipy/special/tests/test_data.py::test_local[<Data for ellip_harm_2: ellip>] - AssertionError:
============================================================= 1 failed, 1515 passed, 196 skipped, 23 xfailed, 1 xpassed in 31.16s =============================================================
```

@rgommers If we don't hear anything back, maybe time to close this issue as it seems to have resolved itself over time?  Is the above failure interesting to us or can it safely be ignored on cygwin?  if an actual issue, I can open a new ticket

**Comment by rgommers** [comment] 2021-01-16 11:03
Thanks for trying this @mckib2. If you get a working Cygwin build, then nothing is fundamentally broken I'd say, and this was either an issue with how the reporters tried to build SciPy or install its dependencies, or the issue was real and it got solved in the meantime.

So I'd say we can close it now. If we get a full reproducer of someone who still has an issue, we can reopen or open a new issue.

**Closed by rgommers** 2021-01-16 11:03 UTC
Labels: Build issues
