### ISSUE TITLE
BUG?: complete License Text is put in field where only Licensename is expected?

### ISSUE THREAD

**Issue by andife** [scipy/scipy#19163] opened 2023-08-30 13:03 UTC
Hi
https://github.com/scipy/scipy/blob/c3ec353c503d23c1357e78ebff750755b3def8c6/pyproject.toml#L38C33-L38C33
lists the complets content of the file License

All the other packages I know display one the License name here: In this case here probably "BSD-3-Clause"

**Comment by tylerjereddy** [comment] 2023-08-30 16:02
> All the other packages I know display one the License name here: In this case here probably "BSD-3-Clause"

NumPy seems to do the same as us, no? https://github.com/numpy/numpy/blob/main/pyproject.toml#L22
And `pandas`: https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L29

**Comment by rkern** [comment] 2023-08-30 17:23
Either one is valid.

https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#license
https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-license

I haven't double-checked if we are word-for-word perfect on this, but I think using the [SPDX identifier `BSD-3-Clause`](https://spdx.org/licenses/BSD-3-Clause.html) would also be fine.

**Comment by rgommers** [comment] 2023-08-30 21:42
This is waiting for https://peps.python.org/pep-0639/ to be finally finalized and implemented by PyPI. Not much we can do here for now.

**Comment by j-bowhay** [comment] 2023-08-31 05:58
Closing as this is a duplicate of #17470

**Closed by j-bowhay** 2023-08-31 05:58 UTC
Labels: upstream bug
