### ISSUE TITLE
bug: unnessesary validity check for block dimension in scipy.sparse.block_diag

### ISSUE THREAD

**Issue by GiggleLiu** [scipy/scipy#4908] opened 2015-05-26 10:11 UTC
the result is that it will raise an error when any of the sub-block has a 0 dimension.

<error infomation>
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 579, in bmat
    raise ValueError('blocks[:,%d] is all None' % bcol_lengths.argmin())
ValueError: blocks[:,0] is all None

**Comment by argriffing** [comment] 2015-05-26 12:52
This issue superficially reminds me of https://github.com/scipy/scipy/issues/4596 which is also related to zero-size sub-blocks of a block diagonal matrix. Is it a duplicate?

**Comment by GiggleLiu** [comment] 2015-05-26 13:11
In [72]: b=zeros([2,0])
In [73]: a=ones([2,2])
In [74]: block_diag([a,b],format='csr')

raises error unexpectedly. which is not fixed in the latest version?

**Comment by argriffing** [comment] 2015-05-26 13:23
FWIW this also fails with the dense `scipy.linalg.block_diag`.

@GiggleLiu Just to make sure I understand, you are expecting the output to look like `ones([2, 2])`?

**Comment by pv** [comment] 2015-05-26 13:26
The result shape probably should be 4x2 matrix?

**Comment by argriffing** [comment] 2015-05-26 13:38
> The result shape probably should be 4x2 matrix?


@pv Currently we have
```python
>>> scipy.linalg.block_diag([[]], b)
array([[ 1.,  1.],
       [ 1.,  1.]])
>>> np.shape([[]])
(1, 0)
```
which would conflict with that interpretation.

**Comment by GiggleLiu** [comment] 2015-05-26 13:39
I wish it not raise an Error, and the the shape should be 4x2.
and, this error only occur in sparse.block_diag(not linalg.block_diag).

**Comment by argriffing** [comment] 2015-05-26 13:42
> this error only occur in sparse.block_diag(not linalg.block_diag).

@GiggleLiu On my system, this gives an error with the dense linalg block diag:
```python
>>> b = np.zeros([2, 0])
>>> a = np.ones([2, 2])
>>> scipy.linalg.block_diag(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../scipy/linalg/special_matrices.py", line 538, in block_diag
    out[r:r + rr, c:c + cc] = arrs[i]
ValueError: could not broadcast input array from shape (2,0) into shape (0,0)
```

**Comment by GiggleLiu** [comment] 2015-05-26 13:45
however, 
>>> b = np.zeros([2, 0])
>>> a = np.ones([2, 2])
>>> scipy.linalg.block_diag(a, b)

returns 
array([[ 1.,  1.],
       [ 1.,  1.],
       [ 0.,  0.],
       [ 0.,  0.]])
for me, and the version of my scipy:
In [80]: scipy.version.version
Out[80]: '0.15.1'

**Comment by argriffing** [comment] 2015-05-26 13:46
I was using
```python
>>> scipy.__version__
'0.17.0.dev0+831dd2b'
```
I'm pretty sure the behavior has been changed recently in https://github.com/scipy/scipy/pull/4672.

**Comment by GiggleLiu** [comment] 2015-05-26 13:48
what about your sparse lib, functioning well?

**Comment by argriffing** [comment] 2015-05-26 15:43
@GiggleLiu Sorry, my last comment was poorly worded.  I'm showing the current behavior on my system for dense and sparse block diagonals and reporting the numpy and scipy versions:
```python
>>> import scipy
>>> import numpy as np
>>> np.__version__
'1.10.0.dev0+9dba7a4'
>>> scipy.__version__
'0.17.0.dev0+831dd2b'
>>> b = np.zeros([2, 0])
>>> a = np.zeros([2, 2])
>>> scipy.linalg.block_diag(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/scipy/linalg/special_matrices.py", line 538, in block_diag
    out[r:r + rr, c:c + cc] = arrs[i]
ValueError: could not broadcast input array from shape (2,0) into shape (0,0)
>>> import scipy.sparse
>>> scipy.sparse.block_diag([a, b], format='csr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/scipy/sparse/construct.py", line 668, in block_diag
    return bmat(rows, format=format, dtype=dtype)
  File "[...]/scipy/sparse/construct.py", line 585, in bmat
    raise ValueError('blocks[:,%d] is all None' % bcol_lengths.argmin())
ValueError: blocks[:,1] is all None
```

**Comment by Madder** [comment] 2015-12-03 14:53
This check is a bug, (n,0) shaped blocks have legitimate uses for constructing sparse block_diag matrices. Indeed i've been using them and it's blocking me from upgrading to more recent scipy versions.

**Comment by GiggleLiu** [comment] 2016-10-26 07:40
The same problem for scipy.linalg.block_diag.
```python
In [1]: from numpy import random; from scipy.linalg import block_diag

In [2]: block_diag(random.random([2,2]),random.random([2,0]))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-9225b960b7cc> in <module>()
----> 1 block_diag(random.random([2,2]),random.random([2,0]))

/usr/local/lib/python2.7/dist-packages/scipy-0.17.0-py2.7-linux-x86_64.egg/scipy/linalg/special_matrices.py in block_diag(*arrs)
    537     r, c = 0, 0
    538     for i, (rr, cc) in enumerate(shapes):
--> 539         out[r:r + rr, c:c + cc] = arrs[i]
    540         r += rr
    541         c += cc

ValueError: could not broadcast input array from shape (2,0) into shape (0,0)
```

It's not even compatible with itself, I'd go mad with line 533:
```python
shapes = np.array([a.shape if a.size > 0 else [0, 0] for a in arrs])
```
**what is the reason to make a bug by telling the program the wrong shape [0,0]?**

**Comment by rgommers** [comment] 2016-10-26 08:23
We have an implementation here that used to meet some users' expectation (until 0.15.x at least), but the behavior never had any tests for either the dense or sparse version. The dense and sparse versions of ``block_diag`` now both raise an exception, but not the same one. So it would be very helpful if someone could spell out the expected results in general, and for a specific case (why should ``(2,2)`` and ``(2,0``) yield a ``(4,2)`` output?).

**Comment by akhmerov** [comment] 2016-10-26 08:28
"All the dimensions are added up" seems to be a sufficient spelling out.

**Comment by GiggleLiu** [comment] 2016-10-26 08:57
(2,2) and (2,0) should yield a (4,2).

If a computer do not logic like a computer, how can we get correct expectations?
**The most important thing is that, this feature is useful sometime, and you just not encountered in that case.** A least, scipy should use a warning instead of exception.

**Comment by ilayn** [comment] 2016-10-26 09:05
I think you are mistaken (2,0) with (2,). 2,0 doesn't make any sense in the dense version and current code uses number of elements check to see whether there is anything to put on the diagonal. 

In Matlab lingo this is the same with blkdiag (1,2, [])

I'm in the phone now but i can justify that code if need be for the dense version later if need be. Empty matrices show up a lot in dense computations and that line is crucial. So it is not nonsense at all.

**Comment by rgommers** [comment] 2016-10-26 09:16
That's what I thought as well - nothing can go on the diagonal for size 0 inputs. The sparse docstring says nothing, and the dense one says:

    Empty sequences (i.e., array-likes of zero size) are ignored.

> scipy should use a warning instead of exception.

The warning means you have to implement a behavior. And that behavior needs to be consistent between the dense and sparse versions. 

It could well be that we need to treat this like a regression and fix it, but what we need is actual reasoning, and a fix + docs/tests to make sure things then stay fixed. What we could do without is more bold letters.

**Comment by ilayn** [comment] 2016-10-26 10:18
However, we can use this opportunity to fix the dense behavior as shape `2,0` should have been ignored too instead of raising exception since it is a zero-size matrix. I dug up an old version from my library before I discovered that block_diag was available on scipy. It skips succesfully for the reported case, it is not production ready and very much like scipy version but hopefully gives an idea about the regularization of the different types of input. I think a simple `_asarrayvalidated` would make things much smoother.  

```

#TODO : type checking.
def blockdiag(*args):
    """
    Places its arguments on the diagonal of a matrix. Empty matrices are
    skipped.
    """

    # Get the size info of the args
    try:
        diags = tuple([m.shape for m in args if m.size > 0])
    except AttributeError:
        args = [np.atleast_2d(x) for x in args]
        diags = tuple([m.shape for m in args if m.size > 0])
    # only get items with nonzero size
    poppedargs = tuple([x for x in args if x.size >0])
    tot = np.zeros(tuple(map(sum,zip(*diags))))# Sum shapes for the final size
    rind,cind=(0,0)

    # Place each of them and move the index to the next diag pos
    for ind,mat in enumerate(poppedargs):
        tot[rind:rind+diags[ind][0], cind:cind+diags[ind][1]] = mat
        rind += diags[ind][0]
        cind += diags[ind][1]
    return tot

a = np.random.rand(2,2)
b = np.random.rand(2,0)

c = blockdiag(a,b)
```

**Comment by akhmerov** [comment] 2016-10-26 15:14
@ilayn I'm not actually sure why zero-sized arrays should be *ignored*. Can you make a real-life use example?

I have encountered several cases where the special treatment of such arrays resulted in a need to make a workaround.

**Comment by ilayn** [comment] 2016-10-26 15:22
Let's first clarify what you mean by `(2,0)` before we branch off. Zero eigenvector doesn't mean unless you mean `(0,0,....,0)`. If you can elaborate on that it would be much easier.

**Comment by akhmerov** [comment] 2016-10-26 15:34
I mean zero *amount* of eigenvectors. Example code:
```
eigvals, eigvecs = np.linalg.eigh(mat)
relevant_eigvecs = eigvecs[:, eigvals > 2]
```
This can produce a 2-dimensional numpy array with one dimension being zero, and so shape `(2, 0)`. I don't have any opinion about behavior of `bmat` with a `(2,)`-shaped array as input, because that isn't even a matrix, but rather a vector.

**Comment by ev-br** [comment] 2016-10-26 16:04
To a degree to which the logic behind https://github.com/scipy/scipy/pull/4672 is relevant, I think the reasoning was based on the array *sizes*, not dimensions:
```
In [22]: np.ones((2, 0)).size == np.ones((4, 0)).size == 0
Out[22]: True
```

OTOH, in that PR, @argriffing linked a text by de Boor which is probably worth considering if the behavior here is revisited.

**Comment by GiggleLiu** [comment] 2016-10-26 16:14
Also, I find (2,0) size matrix useful when I tried to perform svd decomposition to a block diagonal matrix, and compress it by truncating out subspace with small singular values.

User can filter out matrices with 0-size easily, but adding zeros to keep vector spaces unchanged is difficult.

**Comment by ilayn** [comment] 2016-10-26 19:59
I still don't see the use case here. Maybe it is my ignorance but I don't see how `(2,0)` can be used in a meaningful manner. There is no element in the array which is very easy to check with having no elements. Now you would like to put this on a diagonal of a nonzero matrix and expect the array shape to change. That part is not some algebra that I'm familiar with using finite dimensional vector spaces. What it amounts to, as far as I can see, is that you are trying to span the vector space defined by the empty set with vectors that do not exist which is not correct because there is no basis for it. 

Again long story short, I'm not against of having zero sized and arbitrary shaped arrays but taking them into account in a block diagonal enumeration (kronecker sum) is not meaningful.

**Comment by akhmerov** [comment] 2016-10-26 20:28
@ilayn 

> Maybe it is my ignorance but I don't see how (2,0) can be used in a meaningful manner.

As I have already explained, I [have](https://gitlab.kwant-project.org/kwant/kwant/merge_requests/15/diffs#359a7de88de19933dce643bda293f2fb64070630_19_39) a use case where it is the only reasonable thing to do.

Once again, let me repeat my question: for a comparison, do you know of an application where it is logical to skip the zero-sized arrays?

> Again long story short, I'm not against of having zero sized and arbitrary shaped arrays but taking them into account in a block diagonal enumeration (kronecker sum) is not meaningful.

Please don't say "not meaningful" after both @GiggleLiu and I brought up specific examples where it is the only sane thing to do. Numpy and scipy support zero-sized arrays to simplify handling of corner cases in formulas, and it is exactly essence of this issue. That our proposed behavior is more consistent can be seen from the dimensions of a resulting block *always* being equal to the sum of dimensions of the constituent arrays. If zero-sized arrays are skipped, the shape of the resulting array does not have any simple behavior.

As an additional argument consider that if the behavior was changed, and somebody would hypothetically desire a different behavior, they could implement their own replacement as a one-liner:
`block_diag(*(matrix in matrices if matrix.size))`. The reverse is a whole lot more code.

**Comment by ilayn** [comment] 2016-10-26 20:49
@akhmerov Please let's not loose the focus for this. I'm only commenting about block diagonalization of one zero sized entry. Let's take your example what you have is an empty set, in other words no vector satisfies your condition. This has no meaning in terms of the vector space. I am using meaningful in a very rigorous way. Empty set is a subset of every set. This is the main argument of linear algebra. There are no different sized empty sets. You can argue that you will zero out one of the dimensions and assign meaning to it that is your interpretation. And I really don't have any objection. Though I have to say this is a very very obscure and specialized interpretation. 

Now back to the reason of this issue. You cannot block diagonalize an nonzero matrix (2,2) and (2,0) and end up a 4,2 matrix because then you have to justify what the remaining entries are. Would you have zero ? What should the remaining matrix satisfy when I write `mat[3,1]` ? Zero or empty matrix? How can I distinguish a nonzero 4,2 matrix and an empty 4,2 matrix. 

Please let's keep it to point of block diagonalization. What you and @GiggleLiu provided are use cases for empty arrays not block diagonalizing them.

**Comment by akhmerov** [comment] 2016-10-26 21:10
> Please let's keep it to point of block diagonalization. What you and @GiggleLiu provided are use cases for empty arrays not block diagonalizing them.

If you take a look at the [code I linked above](https://gitlab.kwant-project.org/kwant/kwant/merge_requests/15/diffs#359a7de88de19933dce643bda293f2fb64070630_19_39), you will see that I **exactly** create block-diagonal arrays with zero-sized entries by implementing a workaround of this issue.

>  Let's take your example what you have is an empty set, in other words no vector satisfies your condition. This has no meaning in terms of the vector space.

A `(2, 0)`-shaped operator is a linear map from a 0-dimensional vector space to a 2-dimensional vector space. A direct sum of two operators is a map from a space with dimension equal to the sum of the two source spaces to a space with a dimension equal to the sum of the target spaces. Therefore if one operator maps from 2D space to a 2D space, and another from 0D to 2D, then their direct sum maps from a 2D space (2D + 0D) to a 4D space (2D + 2D).

> Now back to the reason of this issue. You cannot block diagonalize an nonzero matrix (2,2) and (2,0) > and end up a 4,2 matrix because then you have to justify what the remaining entries are. Would you have zero ?

Yes. Is there any single alternative?

> What should the remaining matrix satisfy when I write mat[3,1] ? Zero or empty matrix? How can I distinguish a nonzero 4,2 matrix and an empty 4,2 matrix.

The preferred behavior (and the only one I can internally justify) should be:
```
>>> block_diag(np.ones((2, 2)), np.ones((2, 0)).todense()
array([[ 1.,  1.],
       [ 1.,  1.],
       [ 0.,  0.],
       [ 0.,  0.]])
```
This behavior is fully consistent with behavior of `block_diag` in regular cases. I am not sure what you mean by "empty matrix" here, but the answer to your question should be 0.

**Comment by ilayn** [comment] 2016-10-26 21:42
I can't see where you do block diagonalization in the kwant code but anyways: 

>A (2, 0)-shaped operator is a linear map from a 0-dimensional vector space to a 2-dimensional vector space. A direct sum of two operators is a map from a space with dimension equal to the sum of the two source spaces to a space with a dimension equal to the sum of the target spaces. Therefore if one operator maps from 2D space to a 2D space, and another from 0D to 2D, then their direct sum maps from a 2D space (2D + 0D) to a 4D space (2D + 2D).

That's exactly what I am disagreeing with. What is that linear mapping that maps empty set to 2D? I sincerely don't know and I'm ready to learn. But I am pretty sure that you have to end up with a choice of your liking as you had in the last example you have provided which is an embedding not a direct sum Now you **can** see this as a special case of block diagonalization and I can relate to that. But this is not what I expect from block_diag. My choice might be 
 ```
array([[ 1.,  1.],
       [ 1.,  1.],
       [ NaN,  NaN],
       [ NaN,  NaN]])
```  
And before we go into category theory, I would reemphasize that you have a choice injection involved whereas in the existing case there is no such choice involved following direct sum rules which involves ignoring empty sets. Because I also have corner cases where it relies on the behavior that if the shape doesn't change after block diagonalization, that means I run out of columns to consider (oversimplifying greatly). Otherwise I will keep adding empty zero rows. 

I don't see how this is fully consistent but anyway I'll stop and let developers decide. I see your point but I can't justify it at all contrary to what you are claiming.

**Comment by person142** [comment] 2016-10-26 21:44
@ilayn re

> That's exactly what I am disagreeing with. What is that linear mapping that maps empty set to 2D? I sincerely don't know and I'm ready to learn.

Not the empty set--it's the set `{0}`. I suggest giving the paper by de Boor that @ev-br linked a read. I found it really enlightening!

**Comment by ilayn** [comment] 2016-10-26 21:53
I actually did during my PhD but I can't convince myself for the behavior described here even with that reasoning. But anyways, it's not me to decide in this discussion. I hope I made myself clear enough.

**Comment by akhmerov** [comment] 2016-10-26 21:54
> I can't see where you do block diagonalization in the kwant code but anyways

Sorry, the link was unspecific; [here is the corrected one](https://gitlab.kwant-project.org/kwant/kwant/blob/15db5e196cbbee85176184f9fd2ce33ccf802917/kwant/system.py#L42)

> My choice might be
> ```
array([[ 1.,  1.],
       [ 1.,  1.],
       [ NaN,  NaN],
       [ NaN,  NaN]])
```

That would be inconsistent with the behavior of `block_diag` on non-empty arrays since that one never inserts `NaN`s, and therefore not a reasonable choice.

**Comment by ilayn** [comment] 2016-10-26 22:51
>Not the empty set--it's the set {0}. I suggest giving the paper by de Boor that @ev-br linked a read. I found it really enlightening! 

It is not set {0} but he defines an algebra over empty sets and uses regular algebraic identity to arrive to that conclusion which is what I meant by choice injection. 

And just to clarify I still don't see where this behavior is needed. In the linked code it is the block_diag that you wish to have but not a use case.

**Comment by akhmerov** [comment] 2016-10-26 23:05
> In the linked code it is the block_diag that you wish to have but not a use case.

Search for calls to `block_diag` further down in that module.

**Comment by akhmerov** [comment] 2016-10-26 23:44
Comparing with the current code, it appears that this issue was anyway in the due time happily resolved in #5977 and I see now:
```python
In [9]: sparse.block_diag([np.ones((2, 2)), np.ones((2, 0))]).todense()
Out[9]: 
matrix([[ 1.,  1.],
        [ 1.,  1.],
        [ 0.,  0.],
        [ 0.,  0.]])
```

Most of the issue discussion pertains to the behavior of `scipy.linalg.block_diag`, which performs the same "overzealous" checks.

**Comment by person142** [comment] 2016-10-27 17:08
Ok, let's see if we can move this forward. I feel convinced by @akhmerov + de Boor that the behavior on master for `sparse.block_diag` is "correct". In particular I found this argument:

>A (2, 0)-shaped operator is a linear map from a 0-dimensional vector space to a 2-dimensional vector space. A direct sum of two operators is a map from a space with dimension equal to the sum of the two source spaces to a space with a dimension equal to the sum of the target spaces. Therefore if one operator maps from 2D space to a 2D space, and another from 0D to 2D, then their direct sum maps from a 2D space (2D + 0D) to a 4D space (2D + 2D).

to be pretty convincing. (Add to that the fact that the sole linear map from a 0D space to any other vector space is the 0 map and we have the current behavior!)

I wonder how @pv @rgommers @ev-br @perimosocordiae @argriffing feel?

If enough folks agree maybe the next step is to make the `linalg.block_diag` behavior match and call this resolved? If that were to happen I wonder if @akhmerov or @GiggleLiu would be interested in a PR?

**Comment by perimosocordiae** [comment] 2016-10-27 17:33
I'm +1 for making `linalg.block_diag` match the current `sparse.block_diag`.

**Comment by WarrenWeckesser** [comment] 2016-10-27 17:44
I also agree with @akhmerov and others.  I don't see the need for any special handling of an array with one of its dimensions having length 0.  The following does what I expect (`block_diag` is `scipy.sparse.block_diag`):

```
In [205]: block_diag(([[1, 2], [3, 4]], np.empty((2, 0)), [10, 11, 12], np.empty((0, 3)), 99), dtype=int).A
Out[205]: 
array([[ 1,  2,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 10, 11, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 99]])
```

**Comment by person142** [comment] 2016-10-27 17:54
(Oops, sorry @WarrenWeckesser for not including you!)

**Comment by WarrenWeckesser** [comment] 2016-10-27 17:59
No problem, these days I'm nowhere near as active as that group.

**Comment by GiggleLiu** [comment] 2016-10-27 18:14
@person142 I'm glad to pull a request.

**Comment by akhmerov** [comment] 2016-10-27 19:02
In relation to treatment of odd shapes, the issue with `scipy.linalg.block_diag` was *introduced* as a fix to #4596.

It is clear why `scipy.linalg.block_diag([[]], np.eye(2))` returned (and should return) a matrix with shape `(3 2)`. This happens because `np.array([[]]).shape() == (1, 0)`, and all makes sense.

However I do not understand why `scipy.linalg.block_diag(np.zeros((1,)), np.eye(2))` is working at all. Here one of the arguments is a 1D array and not even a matrix. Is `block_diag` perhaps too liberal with input here?

**Comment by WarrenWeckesser** [comment] 2016-10-27 19:22
>However I do not understand why scipy.linalg.block_diag(np.zeros((1,)), np.eye(2)) is working at all. Here one of the arguments is a 1D array and not even a matrix. Is block_diag perhaps too liberal with input here?

That is explained in the docstring:

    A, B, C, ... : array_like, up to 2-D
        Input arrays.  A 1-D array or array_like sequence of length `n` is
        treated as a 2-D array with shape ``(1,n)``.

**Comment by person142** [comment] 2016-10-27 20:18
Hm, so the fix is to revert https://github.com/scipy/scipy/commit/4739653e7662c597be40e054e084668331282cb4 (which closed #4596).

Any PR should add an explanation of the behavior to the docs so that we don't go through this merry-go-round again.

**Comment by akhmerov** [comment] 2016-10-27 20:23
Since the problem in #4596 was seemingly due to a misunderstanding of how `np.array([[]])` works, the explanation in the docs might not be appropriate since it would not be specific to `scipy.linalg.block_diag`.

Perhaps a warning in the test would suffice? The issue arouse partially due to a lack of unit test.

**Comment by person142** [comment] 2016-10-28 18:16
Seems like we have enough of a consensus, so @GiggleLiu I look forward to your PR!

Re

> the explanation in the docs might not be appropriate

maybe an example in the docs? I just want some way of indicating to users who won't see the tests that this is the expected behavior. (Though +1 to a warning in the test too.)

**Comment by GiggleLiu** [comment] 2016-10-29 06:01
OK, Let's make it more specific,
1. Modify the program.
2. A test for zero-sized input(what is a warning in the test? a comment?).
3. An example in the doc.

-------------------------------------
One last confusion,  
version 1: [] should be treated as shape (1,0) according to the doc string, then #4596 is no longer treated as a bug.
version 2: Raise an error when input array is 1D, Does 1D array have any practical usage in generating  block diagonal matrices? indeed it helps a lot in making lazy coders to produce bugs.

which one do you like better?

**Comment by person142** [comment] 2016-10-29 14:47
> what is a warning in the test

I'd say a comment which explains the history and points to all of the relevant discussions.

I'd go with version 1. There is a mathematical reason to not treat #4596 as a bug, but the treatment of 1D arrays is a matter of convention. IMO it's reasonable in this case to break back-compatibility for mathematics but not for matters of convention.

**Comment by GiggleLiu** [comment] 2016-10-29 15:34
ok, I'll go version 1 :)

**Comment by akhmerov** [comment] 2016-10-29 15:38
@GiggleLiu

> [] should be treated as shape (1,0) according to the doc string

I believe this isn't completely accurate.`[]` is treated as shape `(1,)` according to the behavior of `np.asanyarray`, and then 1D arrays are treated as having an additional dimension. I believe it's important to emphasize that non-array arguments are treated just like passing them through a `np.asarray`.

**Comment by WarrenWeckesser** [comment] 2016-10-29 15:50
> arguments are treated just like passing them through a np.asarray.

You could even say that arguments are treated by passing them through `np.atleast_2d`.  That defines how empty, scalar, and 1-d arrays are handled.

**Comment by GiggleLiu** [comment] 2016-10-30 05:16
Done, check pr #6742, I think it is the time to close this issue.

**Comment by rgommers** [comment] 2016-10-30 07:31
@GiggleLiu thanks for the PR! We're closing issues once they're actually fixed (i.e. the PR is merged), so reopening this for now.

**Closed** 2016-11-15 08:20 UTC
Labels: defect, scipy.sparse
