### ISSUE TITLE
Failing test on 32 bit windows wheel build, msvc 2017.

### ISSUE THREAD

**Issue by charris** [scipy/scipy#14797] opened 2021-10-02 19:30 UTC
[Here](https://ci.appveyor.com/project/scipy/scipy-wheels/builds/40998533/job/eqlrdamm2bp6kkxp) This is on Python 3.9, 3.8 passed.

```
C:\Python39\lib\site-packages\scipy\integrate\tests\test__quad_vec.py:108: in test_quad_vec_pool

...

C:\Python39\lib\multiprocessing\popen_spawn_win32.py:123: in terminate
    _winapi.TerminateProcess(int(self._handle), TERMINATE)
E   PermissionError: [WinError 5] Access is denied
        self       = <multiprocessing.popen_spawn_win32.Popen object at 0x137C0748>
```

It isn't clear if this is an upstream problem or misuse on scipy's part.

**Comment by charris** [comment] 2021-10-02 21:05
Seems to be an inconsistent error.

**Comment by rgommers** [comment] 2021-11-05 18:07
Closing as duplicate of gh-14797.

**Closed by rgommers** 2021-11-05 18:07 UTC
Labels: scipy.integrate, Official binaries
