### ISSUE TITLE
BUG: `zsh: abort      python` after `scipy.linalg.sqrtm` on empty `np.array` on M1 Macbook via conda

### ISSUE THREAD

**Issue by mlondschien** [scipy/scipy#20901] opened 2024-06-05 06:27 UTC
### Describe your issue.

I installed scipy=1.13.1 and numpy=1.26.4 via `conda` from `conda-forge` on an M1 Macbook (13.2.1). Running `scipy.linalg.sqrtm` on an empty array yields `zsh: abort      python` (see traceback below).

### Reproducing Code Example

```python
(base) ~/code/scipy-testing [main] $ conda create -n scipy-testing scipy numpy -y    
Channels:
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mlondschien/mambaforge/envs/scipy-testing

  added / updated specs:
    - numpy
    - scipy


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h93a5062_5 
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2024.6.2-hf0a4a13_0 
  libblas            conda-forge/osx-arm64::libblas-3.9.0-22_osxarm64_openblas 
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-22_osxarm64_openblas 
  libcxx             conda-forge/osx-arm64::libcxx-17.0.6-h5f092b4_0 
  libexpat           conda-forge/osx-arm64::libexpat-2.6.2-hebf3989_0 
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5 
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-13_2_0_hd922786_3 
  libgfortran5       conda-forge/osx-arm64::libgfortran5-13.2.0-hf226fd6_3 
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-22_osxarm64_openblas 
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.27-openmp_h6c19121_0 
  libsqlite          conda-forge/osx-arm64::libsqlite-3.45.3-h091b4b1_0 
  libzlib            conda-forge/osx-arm64::libzlib-1.3.1-hfb2fe0b_1 
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-18.1.6-hde57baf_0 
  ncurses            conda-forge/osx-arm64::ncurses-6.5-hb89a1cb_0 
  numpy              conda-forge/osx-arm64::numpy-1.26.4-py312h8442bc7_0 
  openssl            conda-forge/osx-arm64::openssl-3.3.1-hfb2fe0b_0 
  pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0 
  python             conda-forge/osx-arm64::python-3.12.3-h4a7b5fc_0_cpython 
  python_abi         conda-forge/osx-arm64::python_abi-3.12-4_cp312 
  readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1 
  scipy              conda-forge/osx-arm64::scipy-1.13.1-py312h14ffa8f_0 
  setuptools         conda-forge/noarch::setuptools-70.0.0-pyhd8ed1ab_0 
  tk                 conda-forge/osx-arm64::tk-8.6.13-h5083fa2_1 
  tzdata             conda-forge/noarch::tzdata-2024a-h0c530f3_0 
  wheel              conda-forge/noarch::wheel-0.43.0-pyhd8ed1ab_1 
  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0 



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate scipy-testing
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) ~/code/scipy-testing [main] $ conda activate scipy-testing
(scipy-testing) ~/code/scipy-testing [main] $ python
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:35:20) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> import numpy as np
>>> 
>>> A = np.empty(shape=(0,0), dtype=np.float64)
>>> _ = scipy.linalg.sqrtm(A)
```

### Error message

```shell
** On entry to DGEES  parameter number  6 had an illegal value
Fatal Python error: F2PySwapThreadLocalCallbackPtr: F2PySwapThreadLocalCallbackPtr: PyLong_AsVoidPtr failed
Python runtime state: initialized
_flapack.error: ((lwork==-1)||(lwork >= MAX(1,2*n))) failed for 3rd keyword lwork: dgees:lwork=0

Current thread 0x0000000207b38140 (most recent call first):
  File "/Users/mlondschien/mambaforge/envs/scipy-testing/lib/python3.12/site-packages/scipy/linalg/_decomp_schur.py", line 166 in schur
  File "/Users/mlondschien/mambaforge/envs/scipy-testing/lib/python3.12/site-packages/scipy/linalg/_matfuncs_sqrtm.py", line 174 in sqrtm
  File "<stdin>", line 1 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, scipy._lib._ccallback_c, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering (total: 40)
zsh: abort      python
```
```


### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.13.1 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
/Users/mlondschien/mambaforge/envs/scipy-testing/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "16.0.6",
      "commands": "arm64-apple-darwin20.0.0-clang",
      "args": "-ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1716470295081/work=/usr/local/src/conda/scipy-split-1.13.1, -fdebug-prefix-map=/Users/mlondschien/mambaforge/envs/scipy-testing=/usr/local/src/conda-prefix, -D_FORTIFY_SOURCE=2, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -mmacosx-version-min=11.0, -mmacosx-version-min=11.0",
      "linker args": "-Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/mlondschien/mambaforge/envs/scipy-testing/lib, -L/Users/mlondschien/mambaforge/envs/scipy-testing/lib, -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1716470295081/work=/usr/local/src/conda/scipy-split-1.13.1, -fdebug-prefix-map=/Users/mlondschien/mambaforge/envs/scipy-testing=/usr/local/src/conda-prefix, -D_FORTIFY_SOURCE=2, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -mmacosx-version-min=11.0, -mmacosx-version-min=11.0"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "16.0.6",
      "commands": "arm64-apple-darwin20.0.0-clang++",
      "args": "-ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++, -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1716470295081/work=/usr/local/src/conda/scipy-split-1.13.1, -fdebug-prefix-map=/Users/mlondschien/mambaforge/envs/scipy-testing=/usr/local/src/conda-prefix, -D_FORTIFY_SOURCE=2, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -mmacosx-version-min=11.0, -mmacosx-version-min=11.0",
      "linker args": "-Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/mlondschien/mambaforge/envs/scipy-testing/lib, -L/Users/mlondschien/mambaforge/envs/scipy-testing/lib, -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++, -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1716470295081/work=/usr/local/src/conda/scipy-split-1.13.1, -fdebug-prefix-map=/Users/mlondschien/mambaforge/envs/scipy-testing=/usr/local/src/conda-prefix, -D_FORTIFY_SOURCE=2, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -mmacosx-version-min=11.0, -mmacosx-version-min=11.0"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "12.3.0",
      "commands": "/Users/runner/miniforge3/conda-bld/scipy-split_1716470295081/_build_env/bin/arm64-apple-darwin20.0.0-gfortran",
      "args": "-march=armv8.3-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1716470295081/work=/usr/local/src/conda/scipy-split-1.13.1, -fdebug-prefix-map=/Users/mlondschien/mambaforge/envs/scipy-testing=/usr/local/src/conda-prefix",
      "linker args": "-Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs, -Wl,-rpath,/Users/mlondschien/mambaforge/envs/scipy-testing/lib, -L/Users/mlondschien/mambaforge/envs/scipy-testing/lib, -march=armv8.3-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe, -isystem, /Users/mlondschien/mambaforge/envs/scipy-testing/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/scipy-split_1716470295081/work=/usr/local/src/conda/scipy-split-1.13.1, -fdebug-prefix-map=/Users/mlondschien/mambaforge/envs/scipy-testing=/usr/local/src/conda-prefix"
    },
    "pythran": {
      "version": "0.16.0",
      "include directory": "../../_build_env/venv/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "arm64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": true
  },
  "Build Dependencies": {
    "blas": {
      "name": "blas",
      "found": true,
      "version": "3.9.0",
      "detection method": "pkgconfig",
      "include directory": "/Users/mlondschien/mambaforge/envs/scipy-testing/include",
      "lib directory": "/Users/mlondschien/mambaforge/envs/scipy-testing/lib",
      "openblas configuration": "unknown",
      "pc file directory": "/Users/mlondschien/mambaforge/envs/scipy-testing/lib/pkgconfig"
    },
    "lapack": {
      "name": "lapack",
      "found": true,
      "version": "3.9.0",
      "detection method": "pkgconfig",
      "include directory": "/Users/mlondschien/mambaforge/envs/scipy-testing/include",
      "lib directory": "/Users/mlondschien/mambaforge/envs/scipy-testing/lib",
      "openblas configuration": "unknown",
      "pc file directory": "/Users/mlondschien/mambaforge/envs/scipy-testing/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.12.0",
      "detection method": "pkgconfig",
      "include directory": "/Users/mlondschien/mambaforge/envs/scipy-testing/include"
    }
  },
  "Python Information": {
    "path": "/Users/mlondschien/mambaforge/envs/scipy-testing/bin/python",
    "version": "3.12"
  }
}
```
```

**Comment by rgommers** [comment] 2024-06-05 07:19
Thanks for the report @mlondschien. This is indeed a bug. It happens to already be fixed: gh-20295. That fix will become available in 1.14.0 soon.

Since the fix and a regression test for this issue are present in `main`, I'll close this issue. I'll also add that if you really need the fix right now, we have nightly builds: https://anaconda.org/scientific-python-nightly-wheels/scipy/

**Closed by rgommers** 2024-06-05 07:19 UTC
Labels: defect
