### ISSUE TITLE
SciPy reference guide URL schema change - not found page

### ISSUE THREAD

**Issue by Shandelier** [scipy/scipy#14270] opened 2021-06-21 11:43 UTC
Auto generated links are broken -- all google links points to Not Found page.

Example link from google:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html

working link:
https://docs.scipy.org/doc/scipy/reference/reference/generated/scipy.stats.ttest_rel.html
doubled part '/reference'

**Comment by ilayn** [comment] 2021-06-21 11:46
Duplicate of #14267 

Thanks for letting us know @Shandelier we are fixing it as we speak. Let's keep track of it there

**Closed by ilayn** 2021-06-21 11:46 UTC
