### ISSUE TITLE
Add an option for periodic boundaries for Voronoi and Delaunay Triangulation ENH: 

### ISSUE THREAD

**Issue by adyotag** [scipy/scipy#18469] opened 2023-05-15 22:07 UTC
### Is your feature request related to a problem? Please describe.

Yes, many simulations can be set up to be periodic along a certain direction (e.g. periodic along x, non-periodic along y). For post-processing purposes, it would be great to implement this feature.

### Describe the solution you'd like.

With respect to Voronoi diagrams, voro++ could be used or called to allow for mixed periodic boundary conditions. With respect to Delaunay diagrams, perhaps the standard could be used, and triangles that appear across the periodic boundary could be appended on afterwards.

### Describe alternatives you've considered.

Voro++ is a great alternative to obtaining Voronoi diagrams that are periodic along a certain direction. However, no alternative exists for generating Delaunay triangulation. Either the libraries allow for ALL boundaries to be periodic (so no mixed conditions, like periodic along x) or no periodicity at all. One could construct Delaunay diagrams from the voro++, however it would be far more convenient to use an integrated implementation.

**Comment by tylerjereddy** [comment] 2023-05-15 22:54
This is probably a duplicate of gh-11858. Since I work on both `spatial` and in the MD simulation community, I certainly agree on the usefulness. Are you happy to have that issue be the main one? Feel free to chime in/upvote over there. Admittedly, not much has happened since that issue opened.

**Comment by adyotag** [comment] 2023-05-16 19:36
Yeah, that seems like a duplicate. I will participate in that thread.

**Closed** 2023-05-16 20:09 UTC
Labels: enhancement, scipy.spatial
