### ISSUE TITLE
MemoryError in BinaryErosion with large arrays/kernels

### ISSUE THREAD

**Issue by soupault** [scipy/scipy#6042] opened 2016-04-07 14:43 UTC
See [the reported issue](https://github.com/scikit-image/scikit-image/issues/954) and particularly https://github.com/scikit-image/scikit-image/issues/954#issuecomment-177239362 for the details.

From what I've succeded to track, this may be related to a direct `malloc` call:
[1](https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/nd_image.c#L835-L837) -> [2](https://github.com/scipy/scipy/blob/05dc7b8b0662c9c973203b36044458ca35084833/scipy/ndimage/src/ni_morphology.c#L114-L115) -> [3](https://github.com/scipy/scipy/blob/05dc7b8b0662c9c973203b36044458ca35084833/scipy/ndimage/src/ni_support.c#L518).

**Comment by ewmoore** [comment] 2016-04-07 15:05
See #4878. Maybe we should change its title to some thing more descriptive.

**Comment by soupault** [comment] 2016-04-07 15:22
@ewmoore looks pretty much the same.
Please, feel free to close the issue if you're considering it as a duplicate.

**Comment by ewmoore** [comment] 2016-04-14 17:00
Duplicate of #4878.  This needs a champion.

**Closed by ewmoore** 2016-04-14 17:00 UTC
