### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by rkedge** [scipy/scipy#7668] opened 2017-07-27 13:42 UTC
Obligatory "not sure if this is the right place" disclaimer.

The example code links in the tutorial documentation are missing here:
https://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html
If you click Source Code:
https://docs.scipy.org/doc/scipy/reference/tutorial/interpolate.html
you get a 404 error
Suggested solutions: Fix the links or enable prompt folding, or both.

Also suggest changing all "Source Code" links to "Example Code". Source code should refer to the actual module code.

I looked at some other Tutorial pages, and they have similar issues. Some with no links at all, most with no prompt folding. I think there needs to be uniformity on the formatting. Either all with Source Code links, all without links (not my favorite idea), prompt folding should be enabled site wide. 

I wonder if prompt folding would be an issue on some browsers or if javascript is restricted by security policies. In that case having example code links

Related issues #3250 #7369

**Comment by ev-br** [comment] 2017-07-27 21:19
Seems to be a duplicate of https://github.com/scipy/scipy/issues/3250, hence closing as a duplicate. Thanks for the report @rkedge --- if you feel like working on fixing this, it'd be greatly appreciated!

**Closed by ev-br** 2017-07-27 21:19 UTC
