### ISSUE TITLE
memory issues with ndimage binary_opening and binary_closing

### ISSUE THREAD

**Issue by terot** [scipy/scipy#9804] opened 2019-02-11 07:45 UTC
My issue is about randomly occuring segmentation fault with scipy.ndimage.binary_opening and scipy.ndimage.binary_closing.

Even if the issue is random, it can be consistently run by setting
 [PYTHONMALLOC](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONMALLOC) environment variable.

### Reproducing code example:
The issue can be reproduced with a minimal example by running the example with PYTHONMALLOC=debug
```
import numpy as np
from scipy import ndimage as ndim

binaryMat = np.random.choice(2, size=(104, 52, 95))
structElem1= np.random.choice(2, size=(3,3,5))

ndim.binary_opening(binaryMat, structElem1, iterations=3)

# similar issue with binary closing
# ndim.binary_closing(binaryMat, structElem1, iterations=3)
```

### Error message:
```
Debug memory block at address p=0x3a72450: API 'r'
    24 bytes originally requested
    The 7 pad bytes at p-7 are FORBIDDENBYTE, as expected.
    The 8 pad bytes at tail=0x3a72468 are FORBIDDENBYTE, as expected.
    The block was made by call #385558 to debug malloc/realloc.
    Data at p: 00 00 00 00 00 00 00 00 ... 00 00 00 00 00 00 00 00

Fatal Python error: bad ID: Allocated using API 'r', verified using API 'm'

Current thread 0x00007ffb2f007740 (most recent call first):
  File "/home/tero/.local/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 250 in _binary_erosion
  File "/home/tero/.local/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 376 in binary_erosion
  File "/home/tero/.local/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 628 in binary_opening
  File "test03.py", line 8 in <module>
Aborted (core dumped)
```

### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
produces
```
1.2.0 1.16.1 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by grlee77** [comment] 2023-02-20 16:02
closing as unable to reproduce

**Closed by grlee77** 2023-02-20 16:02 UTC
Labels: defect, scipy.ndimage
