### ISSUE TITLE
add extra methods to scipy.stats.combine_pvalues function

### ISSUE THREAD

**Issue by fkloosterman** [scipy/scipy#15481] opened 2022-01-29 14:41 UTC
I would propose to also add the "Friston" and "Nichols" methods (I am not sure if these are the official names for these methods) for computing a combined p-value. See: https://stats.stackexchange.com/a/160804/94255. 

The statistic for both methods is `S = np.max(pvalues)`, and the combined p-value is `S**len(pvalues)` for the "Friston" method and `S` for the "Nichols" method.

**Comment by tupui** [comment] 2022-02-02 00:35
Hi @fkloosterman thank you for reporting and the PR. I am not opposed to adding these, but I don't see a clear benefit either. What is the motivation to add them?  From what you linked, there does not seem to be any real conclusions. I just fear that we would only add confusion by adding 2 new methods that we don't really know when to recommend.

**Comment by tupui** [comment] 2022-02-02 16:22
Thanks @josef-pkt. So for now we are +1 for Friston but -1 for Nichols. @fkloosterman can you update your PR?

**Comment by matthew-brett** [comment] 2022-02-21 08:55
Only to say - I was the second author of the Nichols paper introducing the Nichols method, and discussing these methods in the field they arose - brain imaging:

https://fil.ion.ucl.ac.uk/spm/doc/papers/NicholsBrett.pdf

The Friston method was initially proposed as a test of *conjunction* of tests - the probability of the observed data in the situation that *none* of the effects is truly null - but is invalid for that interpretation, and that caused a lot of confusion, that our paper was designed to address.  The Nichols test is valid for the conjunction interpretation - but still - it seems a bit niche for Scipy.

Has someone found a good use for the Friston method when interpreted correctly (null of all effects null)?  Otherwise, I would have thought it would be more confusing than useful.  And the Nichols method is so simple it would be reasonable to leave that out too.

**Comment by tupui** [comment] 2022-02-21 09:33
@matthew-brett thanks for the insights! So your suggestion is to leave both out correct? Since you authored one of the method, I would fully trust your judgment	on this one.

**Comment by matthew-brett** [comment] 2022-02-21 10:13
Yes, I would leave both out - I think they are just confusing.   And they are both very easy to calculate.

**Comment by tupui** [comment] 2022-02-21 10:18
Ok then we can close this and the linked PR.

@fkloosterman thank you again for your contribution. I am sorry it did not go through, it happens sometimes (very often). The size and reach of SciPy forces us to discuss in length and be on the conservative side.

**Closed by tupui** 2022-02-21 10:18 UTC
Labels: scipy.stats, enhancement
