### ISSUE TITLE
special.factorial test failure with Python 3.9

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#11579] opened 2020-02-24 08:15 UTC
With Python 3.9a3
```
_____________________________________________________________________ TestFactorialFunctions.test_mixed_nan_inputs ______________________________________________________________________
scipy/special/tests/test_basic.py:1835: in test_mixed_nan_inputs
    result = special.factorial(x, exact=True)
scipy/special/_basic.py:2354: in factorial
    val = math.factorial(un[0])
E   DeprecationWarning: Using factorial() with floats is deprecated
```

**Comment by person142** [comment] 2020-02-25 01:18
@rlucas7 looks like our abstract discussion of whether to ban floats in this case has become less abstract.

**Comment by rlucas7** [comment] 2020-02-25 04:05
@person142 yeah, that's going to be fun to fix :) 
I guess we should start with a deprecation warning? 
I'm assuming we want to also deprecate float inputs-IIRC we both wanted to deprecate but it was messy... 
for ref: https://github.com/scipy/scipy/pull/11254
I think the warning or value error was getting consumed in the build and ignored by cython:
https://github.com/scipy/scipy/pull/11254#discussion_r365528511

I'd be +1 for adding deprecation warning for floats in the upcoming release.

**Comment by andyfaff** [comment] 2020-02-25 04:13
It seems to only deprecated in Python 3.9a3 at the moment, so we may have a while?

**Comment by rlucas7** [comment] 2020-02-25 13:08
@andyfaff that is true, it doesn’t look like 3.9 is released until October 2020 so that deprecation won’t go in effect until after the next scipy release. I looked around and couldn’t find the deprecation policy for the math library, not sure how long we have to deprecate, I’d guess until 4.0 python release.

Sincerely, 

-Lucas Roberts

**Comment by beantowel** [comment] 2020-08-31 15:57
sorry, but i'm here just to complain, why keep changing the position of this function from `scipy.misc.common` -> `scipy.misc` -> `scipy.special` ?

**Comment by ev-br** [comment] 2020-08-31 18:59
scipy.misc is being emptied

**Comment by cclauss** [comment] 2020-09-26 23:18
How does one install scipy on Python 3.9 release candidate 2 on Ubuntu?

**Comment by rgommers** [comment] 2020-11-24 21:33
This was a duplicate of a couple of other issues. Closing this; remaining open issue is gh-13122 and PR (with discussion) is gh-13121.

**Closed by rgommers** 2020-11-24 21:33 UTC
Labels: Cython, scipy.special
