### ISSUE TITLE
any scipy.interpolate.lagrange alternative?

### ISSUE THREAD

**Issue by brupelo** [scipy/scipy#6460] opened 2016-08-05 14:07 UTC
Hi, I've tried to solve https://projecteuler.net/problem=101 problem using scipy's lagrange method and the solutions i was getting were wrong.

After that I've decided to give it a shot to a custom lagrange function of mine and the problem was solved perfectly. So, am i missing something or that scipy's method is definitely buggy?

Regards.

**Comment by aarchiba** [comment] 2016-08-05 15:56
Indeed there are several alternatives to scipy.interpolate.lagrange; it is
basically the worst option. But all the scipy alternatives work in
floating-point, when this problem is better handled with exact
(rational/integer) arithmetic. If you want to work in floating-point,
scipy.interpolate.BarycentricInterpolator is the most stable option. For
integer/rational options, try sympy or mpmath.

Anne

**Comment by pv** [comment] 2016-08-08 18:10
Question answered, closing.
The reason for scipy.interpolate.lagrange is that it construct a power basis representation, which is numerically unstable. Feature, not a bug. BarycentricInterpolator uses more stable lagrange representation.

**Closed by pv** 2016-08-08 18:10 UTC
