### ISSUE TITLE
BUG: build issue on Ubuntu 22.04 

### ISSUE THREAD

**Issue by WillTirone** [scipy/scipy#20507] opened 2024-04-17 16:31 UTC
### Describe your issue.

Myself and @nickodell have run into an issue building scipy locally, both on Ubtuntu 22.04. We're both following the [Contributor Quickstart Guide](https://docs.scipy.org/doc/scipy/dev/dev_quickstart.html) and running `python dev.py build`. The full error text is below. The error indicates that _note: 'malloc' is defined in header '<cstdlib>'; did you forget to '#include <cstdlib>'?_ This is outside of my realm of understanding so wondering if this is a bug or a system issue or what.

I have a few of @nickodell's logs here, I hope they're okay to post so let me know if not - not sure what I can / should upload, but the build logs might be helpful.

[meson-log.txt](https://github.com/scipy/scipy/files/15014503/meson-log.txt)
[ninja.log](https://github.com/scipy/scipy/files/15014504/ninja.log)

### Reproducing Code Example

```python
python dev.py build
```

### Error message

```shell
../../../.miniforge3/envs/scipy-dev/lib/python3.11/site-packages/pythran/pythonic/types/raw_array.hpp: In instantiation of '{anonymous}::pythonic::types::raw_array<T>::raw_array(size_t) [with T = double; size_t = long unsigned int]':
../../../.miniforge3/envs/scipy-dev/lib/python3.11/site-packages/pythran/pythonic/utils/shared_ref.hpp:25:9:   required from {anonymous}::pythonic::utils::shared_ref<T>::memory::memory(Types&& ...) [with Types = {long int}; T = {anonymous}::pythonic::types::raw_array<double>]'
../../../.miniforge3/envs/scipy-dev/lib/python3.11/site-packages/pythran/pythonic/utils/shared_ref.hpp:42:13:   required from '{anonymous}::pythonic::utils::shared_ref<T>::shared_ref(Types&& ...) [with Types = {long int}; T = {anonymous}::pythonic::types::raw_array<double>]'
../../../.miniforge3/envs/scipy-dev/lib/python3.11/site-packages/pythran/pythonic/types/ndarray.hpp:477:9:   required from '{anonymous}::pythonic::types::ndarray<T, pS>::ndarray(const {anonymous}::pythonic::types::numpy_expr<Op, Args ...>&) [with Op = {anonymous}::pythonic::operator_::functor::sub; Args = {{anonymous}::pythonic::types::ndarray<double, {anonymous}::pythonic::types::array_base<long int, 2, {anonymous}::pythonic::types::tuple_version> >, {anonymous}::pythonic::types::broadcasted<{anonymous}::pythonic::types::ndarray<double, {anonymous}::pythonic::types::pshape<long int> >&>}; T = double; pS = {anonymous}::pythonic::types::pshape<long int, long int>]'
scipy/stats/_stats_pythran.cpython-311-x86_64-linux-gnu.so.p/_stats_pythran.cpp:631:139:   required from 'typename {anonymous}::__pythran__stats_pythran::siegelslopes::type<argument_type0, argument_type1, argument_type2>::result_type {anonymous}::__pythran__stats_pythran::siegelslopes::operator()(argument_type0, argument_type1, argument_type2) const [with argument_type0 = {anonymous}::pythonic::types::ndarray<double, {anonymous}::pythonic::types::pshape<long int> >; argument_type1 = {anonymous}::pythonic::types::ndarray<double, {anonymous}::pythonic::types::pshape<long int> >; argument_type2 = {anonymous}::pythonic::types::str; typename type<argument_type0, argument_type1, argument_type2>::result_type = {anonymous}::pythonic::types::array_base<double, 2, {anonymous}::pythonic::types::tuple_version>]'
scipy/stats/_stats_pythran.cpython-311-x86_64-linux-gnu.so.p/_stats_pythran.cpp:1056:84:   required from here
../../../.miniforge3/envs/scipy-dev/lib/python3.11/site-packages/pythran/pythonic/types/raw_array.hpp:26:25: error: 'malloc' was not declared in this scope
   26 |       : data((T *)malloc(n * sizeof(T))), external(false)
      |                   ~~~~~~^~~~~~~~~~~~~~~
../../../.miniforge3/envs/scipy-dev/lib/python3.11/site-packages/pythran/pythonic/types/raw_array.hpp:8:1: note: 'malloc' is defined in header '<cstdlib>'; did you forget to '#include <cstdlib>'?
    7 | #include <cstdlib>
  +++ |+#include <cstdlib>
    8 | #include <sstream>
```

### SciPy/NumPy/Python version and system information

```shell
I can't manage to get `import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()` to run, I think because I can't build scipy, so just manually entering stuff below.

@nickodell system info: 
OS: Ubuntu 22.04.4
Python version: Python 3.11.8
Pythran: 0.15
Linux xxxxxxxx 5.19.0-42-generic #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

My machine: 
`sys.version_info(major=3, minor=11, micro=8, releaselevel='final', serial=0)`
numpy.__version__ == `1.26.4`
```

**Comment by dschmitz89** [comment] 2024-04-17 21:09
How did you create your environment/install compilers etc.? Sounds like compiler version issue to me.

**Comment by nickodell** [comment] 2024-04-17 22:04
Thanks for making this issue, Will.

One more point of comparison I want to check is `dist-upgrade`. When you got your 22.04.4 system, did you do so by installing it with a 22.04 ISO, or did you do a `dist-upgrade`? The reason why I ask is that the system where I'm having trouble was originally Ubuntu 20.10.

**Comment by andyfaff** [comment] 2024-04-17 22:17
Looking at how the various CI entries compile scipy is also a good source of build information (possibly not for total neophytes though). I often find docker to be useful in figuring out issues, because one is starting from a fresh slate. Crud that builds up can often lead to hard to reproduce issues.
Anyway, I've checkout out building on Ubuntu 22.04 and don't experience this problem. I start up the container with `docker run -it ubuntu:22.04`. I then issue the following commands:

```
apt-get update
apt-get install build-essential libopenblas-dev pkg-config gfortran python3-dev git python3-venv
git clone https://github.com/scipy/scipy.git scipy
python3 -m venv scipy-dev
source scipy-dev/bin/activate
pip install numpy cython meson ninja pythran pybind11 click rich-click doit pydevtool
cd scipy
git submodule update --init
python dev.py build
```

The build completes without issues.

```
root@baebf67a5dfc:/# uname -a
Linux baebf67a5dfc 6.4.16-linuxkit #1 SMP PREEMPT Tue Oct 10 20:38:06 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by WillTirone** [comment] 2024-04-17 22:19
@dschmitz89 I used the suggested code from the guide that uses mamba, but with conda did: 

`conda env create -f environment.yml  # works with `conda` too`

I actually have two machines - one where the build fails and one where it doesn't (an Ubuntu desktop and laptop). Both have gcc version == 11.4.0. 

@andyfaff I agree, probably some weird hard to diagnose issue. As far as debugging, would you then just work on scipy development in the docker container? I haven't done this but should probably try :)

**Comment by andyfaff** [comment] 2024-04-17 22:26
My main computers are all macOS. This means whenever I develop for Linux I do it in a docker container. Most of the development work I do on Linux is CI work: getting linux CI entries to work, working on wheel building in CI environments, etc. If one can't build in a fresh container there's something wrong. However, working continuously in a container would be draining. 

I didn't try using conda/mamba. I usually only use conda/mamba for installing Python. Other tools are installed separately. e.g. pip for python packages and apt for build-essential, gfortran, etc.

**Comment by WillTirone** [comment] 2024-04-18 12:30
> Thanks for making this issue, Will.
> 
> One more point of comparison I want to check is `dist-upgrade`. When you got your 22.04.4 system, did you do so by installing it with a 22.04 ISO, or did you do a `dist-upgrade`? The reason why I ask is that the system where I'm having trouble was originally Ubuntu 20.10.
> 
> This SO issue has a few ways to check: https://askubuntu.com/questions/732334/how-to-check-if-an-ubuntu-installation-has-been-upgraded-from-previous-versions

I actually think the system that builds correctly was upgraded from 21.04 to 22.04 and works fine, while the system that doesn't build was a 22.04 ISO

**Comment by rgommers** [comment] 2024-04-19 08:39
This seems to have been fixed in `pythran` 3 years ago: https://github.com/serge-sans-paille/pythran/issues/1796. The traceback doesn't quite make sense, since `#include <cstdlib>` clearly is present already in that file. So not sure what's happening there, but it's probably some issue in the compiler toolchain you're using.

> while the system that doesn't build was a 22.04 ISO

ISOs can often lack necessary upgraded. If you do `sudo apt upgrade` or `sudo apt full-upgrade` the problem will likely go away.

**Closed** 2024-04-19 12:57 UTC
Labels: defect, Build issues
