### ISSUE TITLE
import scipy raises OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by maltekliemann** [scipy/scipy#13809] opened 2021-04-05 10:01 UTC
I'm running win10 in a Parallels Desktop virtual machine. It runs Python 3.7.9 (installed via Add/Remove Software, or whatever that's called). scipy is installed via pip.

Doing `import scipy` raises an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\malte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:\Users\malte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

I've never encountered this problem on macOS or Linux. I get the same error in a clean virtualenv under win10. #13213 may be related, but I can't say that I have multiple versions of Python installed, nor does uninstalling and reinstalling fix the issue. I'm not sure if #12400 is related.

### Scipy/Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version_info)
1.20.2 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```

(I'm using scipy 1.6.2.)

**Comment by ilayn** [comment] 2021-04-05 10:06
Does it happen outside the virtual environment? Never heard of parallel desktops to be honest and apart from the python version i have bunch of containers and venvs on win 10 working without any issues

**Comment by maltekliemann** [comment] 2021-04-05 11:37
@ilayn Yes, the error occurs inside and outside the virtualenv. The win10 installation was brand new before installing Python, by the way.

I don't think that the VM is responsible - I just mentioned that for the sake of completeness. Is there any other information that I can provide?

**Comment by ilayn** [comment] 2021-04-05 12:08
This issue is well known #12400 but you shouldn't be hitting it anymore especially with such new versions and windows. That's why I am asking for outside. I cannot reproduce this in any config I have

**Comment by maltekliemann** [comment] 2021-04-05 14:06
I just ran some experiments. I've tried 3.7.9 (installation via Windows software manager, or whatever it's called; this pops up if you call `python` in command promt if Python is not installed), 3.7.9 (python.org), 3.9.4 (python.org), all on a blank VM. Only the first one caused the issue. The direkt downloads worked just fine.

So at least there's a workaround.

**Comment by ilayn** [comment] 2021-04-11 08:31
I see. That windows store thing is really causing troubles all the time. So good that we have identified it. I'll close this one just for bookkeeping but please feel free to update it if you have any other insights.

**Closed by ilayn** 2021-04-11 08:31 UTC
