### ISSUE TITLE
Test failures on macOS Big Sur (Version 11.4) with Apple M1 chip

### ISSUE THREAD

**Issue by czgdp1807** [scipy/scipy#14596] opened 2021-08-17 18:20 UTC
My issue is about ...

#### Reproducing code example:

```python
import scipy
scipy.test()
```

#### Error message:

```
=================================== FAILURES ===================================
_________________________ TestSmirnovi.test_round_trip _________________________
scipy/special/tests/test_kolmogorov.py:169: in test_round_trip
    FuncData(_sm_smi, dataset, (0, 1), 2, rtol=_rtol).check(dtypes=[int, float, float])
E   AssertionError: 
E   Max |adiff|: 0.484375
E   Max |rdiff|: 1337.21
E   Bad results (2 out of 7) for the following points (in output 0):
E                                3                           0.125 =>                       0.609375 !=                          0.125  (rdiff                          3.875)
E                               10                          0.0001 =>            0.13382053040755335 !=                         0.0001  (rdiff             1337.2053040755336)
        _sm_smi    = <function TestSmirnovi.test_round_trip.<locals>._sm_smi at 0x17ab99d30>
        _smc_smci  = <function TestSmirnovi.test_round_trip.<locals>._smc_smci at 0x17ab99820>
        dataset    = array([[1.00e+00, 4.00e-01, 4.00e-01],
       [1.00e+00, 6.00e-01, 6.00e-01],
       [2.00e+00, 8.75e-01, 8.75e-01],
 ...,
       [3.00e+00, 1.25e-01, 1.25e-01],
       [1.00e+01, 9.99e-01, 9.99e-01],
       [1.00e+01, 1.00e-04, 1.00e-04]])
        self       = <scipy.special.tests.test_kolmogorov.TestSmirnovi object at 0x17ab86b20>
______________________ TestSmirnovi.test_x_equals_0point5 ______________________
scipy/special/tests/test_kolmogorov.py:186: in test_x_equals_0point5
    FuncData(smirnovi, dataset, (0, 1), 2, rtol=_rtol).check(dtypes=[int, float, float])
E   AssertionError: 
E   Max |adiff|: 0.13456
E   Max |rdiff|: 0.708588
E   Bad results (7 out of 11) for the following points (in output 0):
E                                4                             0.5 =>                          0.125 !=                 0.255520481121  (rdiff             0.5108024239324789)
E                                5                             0.5 =>                            0.1 !=                 0.234559536069  (rdiff             0.5736690067012106)
E                                6                             0.5 =>            0.08333333333333333 !=                  0.21715965898  (rdiff             0.6162577629530716)
E                                7                             0.5 =>            0.07142857142857142 !=                 0.202722580034  (rdiff              0.647653599236002)
E                                8                             0.5 =>                         0.0625 !=                 0.190621765256  (rdiff               0.67212558379121)
E                                9                             0.5 =>            0.05555555555555555 !=                 0.180363501362  (rdiff             0.6919800561863548)
E                               10                             0.5 =>                           0.05 !=                  0.17157867006  (rdiff             0.7085884860716352)
        dataset    = array([[ 1.        ,  0.5       ,  0.5       ],
       [ 2.        ,  0.5       ,  0.3660254 ],
       [ 2.        ,  ...       ,  0.19062177],
       [ 9.        ,  0.5       ,  0.1803635 ],
       [10.        ,  0.5       ,  0.17157867]])
        self       = <scipy.special.tests.test_kolmogorov.TestSmirnovi object at 0x17ac6fe50>
=========================== short test summary info ============================
FAILED scipy/special/tests/test_kolmogorov.py::TestSmirnovi::test_round_trip
FAILED scipy/special/tests/test_kolmogorov.py::TestSmirnovi::test_x_equals_0point5
```

#### Scipy/Numpy/Python version information:
```
1.8.0.dev0+1551.d92e048 1.21.1 sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)
```
I am using macOS Big Sur (Version 11.4) with Apple M1 chip. Though the conda environment is having Intel software and hence using Rosetta to run on the hardware.

**Comment by czgdp1807** [comment] 2021-08-17 18:21
I can look into this, if this needs to be fixed.

**Comment by rgommers** [comment] 2021-08-20 17:41
Looking into this would be great @czgdp1807, thanks. I cannot reproduce it, and it'd be nice to take this along for the `1.7.2` release.

**Comment by czgdp1807** [comment] 2021-08-20 18:30
With ARM binaries (from `mambaforge`) the following tests fail. Though it seems like they are related to slightly higher error than (though still very low in absolute sense) the allowed tolerance. May be due to the difference in processor architectures?

```python
============================================================= FAILURES ==============================================================
________________________________________ TestHyp2f1.test_a_b_negative_int[hyp2f1_test_case2] ________________________________________
scipy/special/tests/test_hyp2f1.py:389: in test_a_b_negative_int
    assert_allclose(hyp2f1(a, b, c, z), expected, rtol=rtol)
E   AssertionError: 
E   Not equal to tolerance rtol=5e-11, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 2.69263521e-14
E   Max relative difference: 8.43561629e-11
E    x: array(-0.000305-9.261359e-05j)
E    y: array(-0.000305-9.261359e-05j)
        a          = -8
        b          = 8.095813935368371
        c          = 4.0013768449590685
        expected   = (-0.0003054674127221263-9.261359291755414e-05j)
        hyp2f1_test_case = Hyp2f1TestCase(a=-8, b=8.095813935368371, c=4.0013768449590685, z=(0.9473684210526314-0.10526315789473695j), expected=(-0.0003054674127221263-9.261359291755414e-05j), rtol=5e-11)
        rtol       = 5e-11
        self       = <scipy.special.tests.test_hyp2f1.TestHyp2f1 object at 0x11e303760>
        z          = (0.9473684210526314-0.10526315789473695j)
________________________________________ TestHyp2f1.test_a_b_negative_int[hyp2f1_test_case3] ________________________________________
scipy/special/tests/test_hyp2f1.py:389: in test_a_b_negative_int
    assert_allclose(hyp2f1(a, b, c, z), expected, rtol=rtol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-13, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 5.49472805e-16
E   Max relative difference: 1.17502468e-13
E    x: array(-0.002081-0.004188j)
E    y: array(-0.002081-0.004188j)
        a          = -4
        b          = -3.956227226099288
        c          = -3.9316537064827854
        expected   = (-0.0020809502580892937-0.0041877333232365095j)
        hyp2f1_test_case = Hyp2f1TestCase(a=-4, b=-3.956227226099288, c=-3.9316537064827854, z=(1.1578947368421053-0.3157894736842106j), expected=(-0.0020809502580892937-0.0041877333232365095j), rtol=1e-13)
        rtol       = 1e-13
        self       = <scipy.special.tests.test_hyp2f1.TestHyp2f1 object at 0x11e560e80>
        z          = (1.1578947368421053-0.3157894736842106j)
_____________________ TestHyp2f1.test_a_b_neg_int_after_euler_hypergeometric_transformation[hyp2f1_test_case1] ______________________
scipy/special/tests/test_hyp2f1.py:454: in test_a_b_neg_int_after_euler_hypergeometric_transformation
    assert_allclose(hyp2f1(a, b, c, z), expected, rtol=rtol)
E   AssertionError: 
E   Not equal to tolerance rtol=5e-12, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 6.31453328e-11
E   Max relative difference: 5.78868492e-12
E    x: array(4.079317-10.116942j)
E    y: array(4.079317-10.116942j)
        a          = 8.5
        b          = -3.9316537064827854
        c          = 1.5
        expected   = (4.0793167523167675-10.11694246310966j)
        hyp2f1_test_case = Hyp2f1TestCase(a=8.5, b=-3.9316537064827854, c=1.5, z=(0.9473684210526314-0.10526315789473695j), expected=(4.0793167523167675-10.11694246310966j), rtol=5e-12)
        rtol       = 5e-12
        self       = <scipy.special.tests.test_hyp2f1.TestHyp2f1 object at 0x11e56f5e0>
        z          = (0.9473684210526314-0.10526315789473695j)
____________________________________________ TestHyp2f1.test_region1[hyp2f1_test_case3] _____________________________________________
scipy/special/tests/test_hyp2f1.py:556: in test_region1
    assert_allclose(hyp2f1(a, b, c, z), expected, rtol=rtol)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-12, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 6.19291275e-13
E   Max relative difference: 1.49879074e-12
E    x: array(-0.407528-0.068193j)
E    y: array(-0.407528-0.068193j)
        a          = 2.02764642551431
        b          = 16.088264119063613
        c          = 8.031683612216888
        expected   = (-0.4075277891264672-0.06819344579666956j)
        hyp2f1_test_case = Hyp2f1TestCase(a=2.02764642551431, b=16.088264119063613, c=8.031683612216888, z=(0.3157894736842106-0.736842105263158j), expected=(-0.4075277891264672-0.06819344579666956j), rtol=1e-12)
        rtol       = 1e-12
        self       = <scipy.special.tests.test_hyp2f1.TestHyp2f1 object at 0x11e3f05b0>
        z          = (0.3157894736842106-0.736842105263158j)
====================================================== short test summary info ======================================================
FAILED scipy/special/tests/test_hyp2f1.py::TestHyp2f1::test_a_b_negative_int[hyp2f1_test_case2] - AssertionError: 
FAILED scipy/special/tests/test_hyp2f1.py::TestHyp2f1::test_a_b_negative_int[hyp2f1_test_case3] - AssertionError: 
FAILED scipy/special/tests/test_hyp2f1.py::TestHyp2f1::test_a_b_neg_int_after_euler_hypergeometric_transformation[hyp2f1_test_case1]
FAILED scipy/special/tests/test_hyp2f1.py::TestHyp2f1::test_region1[hyp2f1_test_case3] - AssertionError: 
========================= 4 failed, 1925 passed, 3 skipped, 180 deselected, 52 xfailed, 1 xpassed in 16.98s =========================
False
```

**Comment by rgommers** [comment] 2021-08-20 18:55
> Though it seems like they are related to slightly higher error than (though still very low in absolute sense) the allowed tolerance. May be due to the difference in processor architectures?

Probably. For all of these it looks like just bumping the tolerance up a bit is the right thing to do. The tolerances are just set in an ad-hoc fashion, and we often do such small bumps to make platforms pass that aren't covered in CI. Do you want to submit a PR for these?

**Comment by rgommers** [comment] 2021-12-26 19:29
These were fixed, closing.

**Closed by rgommers** 2021-12-26 19:29 UTC
Labels: defect, scipy.special
