### ISSUE TITLE
scipy.sparse.linalg.eigsh occasionally fails on the identity matrix with "ARPACK error 3"

### ISSUE THREAD

**Issue by zoonek** [scipy/scipy#14089] opened 2021-05-19 10:47 UTC
#### Reproducing code example:

```
import scipy.sparse.linalg
import numpy as np
for i in range(1000):
    # Fails every few hundred iterations
    scipy.sparse.linalg.eigsh( np.eye(100) )
```

#### Error message:

```
ArpackError                               Traceback (most recent call last)
<ipython-input-1-a7993f1fbc1b> in <module>
      2 import numpy as np
      3 for i in range(1000):
----> 4     scipy.sparse.linalg.eigsh( np.eye(100) )

~/miniconda3/envs/py38/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in eigsh(A, k, M, sigma, which, v0, ncv, maxiter, tol, return_eigenvectors, Minv, OPinv, mode)
   1688     with _ARPACK_LOCK:
   1689         while not params.converged:
-> 1690             params.iterate()
   1691 
   1692         return params.extract(return_eigenvectors)

~/miniconda3/envs/py38/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in iterate(self)
    570                 self._raise_no_convergence()
    571             else:
--> 572                 raise ArpackError(self.info, infodict=self.iterate_infodict)
    573 
    574     def extract(self, return_eigenvectors):

ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV. 
```

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.2 1.20.1 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment] 2021-05-19 11:59
I can't reproduce this on Win10 same config but py 3.9.2. Is it maybe an MKL thing, do you have any access to another implementation that is not *conda but regular pip installed?

**Comment by zoonek** [comment] 2021-05-19 12:21
With Python 3.9.4, and pip-installed scipy, the problem disappears.

With Python 3.9.4 (instead of 3.8), and conda-installed scipy, the problem is still there.

**Comment by tupui** [comment] 2021-05-19 15:08
I also cannot reproduce the issue on macOS. Could you try the development version?

`1.7.0.dev0+985.f62f568 1.20.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)`

**Comment by zoonek** [comment] 2021-05-19 15:40
It also fails with the development version (on Linux, with everything but scipy installed with Conda).

```
>>> for i in range(1000):
...     _ = scipy.sparse.linalg.eigsh( np.eye(100) )
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/zoonek/tmp/2021-05-19/scipy/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1690, in eigsh
    params.iterate()
  File "/home/zoonek/tmp/2021-05-19/scipy/scipy/sparse/linalg/eigen/arpack/arpack.py", line 572, in iterate
    raise ArpackError(self.info, infodict=self.iterate_infodict)
scipy.sparse.linalg.eigen.arpack.arpack.ArpackError: ARPACK error 3: No shifts could be applied during a cycle of the Implicitly restarted Arnoldi iteration. One possibility is to increase the size of NCV relative to NEV. 
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.7.0.dev0+1022.7b90b3a 1.20.2 sys.version_info(major=3, minor=9, micro=4, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment] 2021-05-19 16:03
Smells like an MKL-ARPACK friction to me. Don't know what might be the problem to be honest.

**Comment by theodorju** [comment] 2023-05-31 21:25
I've stumbled into the same issue with scipy installed via pip. More specifically:
- Ubuntu
- conda env
- scipy version 1.10.1 installed via pip

**Comment by ilayn** [comment] 2024-08-22 23:09
Apart from the ARPACK's inherent shortcoming on failing on cluster of eigenvalues, there is also a problem with the random vector generation that amplifies this shortcoming. That is you can't reliably regenerate the failing case.

We are rewriting ARPACK in the meantime and the seed issue is being handled but the very close clustered eigenvalues issue is essentially inherent, losing the shift precision. So I'll close this one but let us know if you have concerns about it.

**Closed by ilayn** 2024-08-22 23:09 UTC
Labels: scipy.sparse.linalg
