### ISSUE TITLE
BUG: special: silent precision loss in `kv` near `(1.5, -1)`

### ISSUE THREAD

**Issue by tpudlik** [scipy/scipy#5844] opened 2016-02-13 22:52 UTC
For `n = 1.5` and `z = -1 + 1j*e` for real `e` small (less than 1e-5), `kv` returns inaccurate values.  Example:

```
>>> scipy.special.kv(1.5, -1 - 1j*1e-20)
(-5.6498675426425281e-17+2.2204460492503131e-16j)
>>> mpmath.besselk(1.5, -1 - 1j*1e-20)
mpc(real='-3.4068610448155485e-20', imag='-1.7034305224077743e-40')
```

There may be other points in `(n, z)` space with similar issues, but this is the only one I've been able to find.

**Comment by person142** [comment] 2016-03-18 04:38
FWIW, the issue is that ``kv`` has a zero at ``n = 1.5`` and ``z = -1`` and at the zero the continuation formula it's using (DLMF 10.34.2 with ``m = 1``) suffers from catastrophic cancellation. For orders of the form ``n = 2*i + 1.5`` there's also a zero on the negative real axis (it moves further out the axis as ``n`` increases) which will cause a similar loss in precision. For example, at ``n = 3.5`` there's a zero at approximately ``z = -2.322185354626086 + 0j`` and we have
```
>>> kv(3.5, z)
(-3.734975229435317e-17-1.1102230246251565e-15j)
>>> mp.besselk(3.5, z)
mpc(real='0.0', imag='-8.9342613861852027e-16')
```

**Comment by person142** [comment] 2019-08-19 05:31
I'm closing this-loss of relative accuracy around zeros is just a fact of life. We could special-case the `n = 1.5` case to solve this particular problem, but as there are similar problems for other orders I don't see much of an advantage in that.

**Closed by person142** 2019-08-19 05:31 UTC
Labels: defect, scipy.special
