### ISSUE TITLE
zoom behavior changed in 1.1.0

### ISSUE THREAD

**Issue by pllim** [scipy/scipy#8845] opened 2018-05-18 17:18 UTC
Not sure if this is a feature or a bug, but `zoom` is giving me slightly different results now.

### Reproducing code example:
```python
import numpy as np
from scipy.ndimage.interpolation import zoom
a = np.arange(100).reshape(10, 10)
zoom(a, 0.5)
```

scipy 1.0.1
```python
array([[0, 2, 4, 7, 9],
       [22, 25, 27, 29, 31],
       [45, 47, 49, 52, 54],
       [68, 70, 72, 74, 77],
       [90, 92, 95, 97, 99]])
```

scipy 1.1.0
```python
array([[0, 2, 5, 7, 9],
       [22, 25, 27, 29, 31],
       [45, 47, 50, 52, 54],
       [68, 70, 72, 74, 77],
       [90, 92, 95, 97, 99]])
```

Note: `4 -> 5` and `49 -> 50`
### Error message:

N/A

### Scipy/Numpy/Python version information:

scipy versions as stated above.

```python
>>> import numpy as np
>>> np.__version__
'1.14.2'
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment] 2019-08-08 21:39
@pllim Is it still relevant? If it is, it'd be helpful if you could `git bisect` it.

**Comment by pllim** [comment] 2019-08-08 21:43
I adjusted my test results accordingly depending on Scipy version and that worked for me. :woman_shrugging: 

If this change is expected on your side, then feel free to close.

**Comment by ev-br** [comment] 2019-08-08 22:18
No idea, TBH. Might have been accidental. ndimage is not very actively maintained (as you might have noticed, sorry!). As a rule, we try rather hard to avoid small breakages like this. If this is something you think is worth fixing, help is appreciated. 
Here's the list of PRs which touched ndimage, note that they are tagged with the release they went in:
https://github.com/scipy/scipy/pulls?page=2&q=is%3Apr+label%3Ascipy.ndimage+is%3Aclosed

**Comment by pllim** [comment] 2019-08-09 14:19
In that case, can we please keep this open? If I can't get to it fast enough, maybe someone else can. I can't say this is high on my todo list. 😬

**Comment by pllim** [comment] 2019-10-03 21:13
I did try a `bisect` but failed to get anything useful. Not sure how to bisect across different release branches. Am I doing this wrong?

```
$ git bisect start
$ git bisect good v1.0.1
$ git bisect bad v1.1.0
$ git bisect run pytest -qqq test_script.py

Bisecting: a merge base must be tested
^[[A[14acd976fbe1e980953f564705ba77ef40526a97] Merge pull request #7868 from rgommers/relnotes
(py37) westeros> git bisect run pytest -qqq test_script.py
running pytest -qqq test_script.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File ".../_pytest/main.py", line 213, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File ".../_pytest/main.py", line 256, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File ".../pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File ".../pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File ".../pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File ".../pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File ".../pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File ".../pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File ".../_pytest/warnings.py", line 126, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File ".../contextlib.py", line 112, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File ".../_pytest/warnings.py", line 83, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File ".../_pytest/warnings.py", line 21, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File ".../warnings.py", line 266, in _getcategory
INTERNALERROR>     raise _OptionError("invalid module name: %r" % (module,)) from None
INTERNALERROR> warnings._OptionError: invalid module name: 'scipy._lib._testutils'

The merge base 14acd976fbe1e980953f564705ba77ef40526a97 is bad.
This means the bug has been fixed between 14acd976fbe1e980953f564705ba77ef40526a97 and [83eb32d32f9a4d8fcb03dc75478f39c8f1cb7686].
bisect run failed:
'bisect_state bad' exited with error code 3
```

Referenced commits:
* 14acd976fbe1e980953f564705ba77ef40526a97
* 83eb32d32f9a4d8fcb03dc75478f39c8f1cb7686

My test script:
```python
import numpy as np
from scipy.ndimage.interpolation import zoom

a = np.arange(100).reshape(10, 10)
result = zoom(a, 0.5)
ans = np.array([[0, 2, 4, 7, 9],
                [22, 25, 27, 29, 31],
                [45, 47, 49, 52, 54],
                [68, 70, 72, 74, 77],
                [90, 92, 95, 97, 99]])
assert np.testing.assert_array_equal(result, ans)
```

**Comment by rgommers** [comment] 2019-10-04 13:46
Hi @pllim, thanks for tackling this!
 
> `git bisect run pytest -qqq test_script.py`

This does not actually build SciPy, so you are testing some installed version on your path, or the non-built SciPy sources inside your repo. What you want to do instead is `git bisect run some-shell-script`, with the script doing something like:
```
python setup.py develop   # best to do this in a conda env / virtualenv that doesn't have SciPy installed already
pushd ../tmp/
pytest -qqq thing_that_fails
popd
```

**Comment by pllim** [comment] 2019-10-09 20:28
Thanks, @rgommers ! I switched to a Bash script as you suggested, ran it in a clean `conda` end with the Numpy version I originally reported, and it ran for a while...

```
$ more test_script.sh
#!/bin/bash
python setup.py develop
pytest test_script.py
$ git bisect start
$ git bisect good v1.0.1
$ git bisect bad v1.1.0
$ git bisect run test_script.sh
```

But then it crashed here:

```
Processing dependencies for scipy==1.0.0.dev0+14acd97
Finished processing dependencies for scipy==1.0.0.dev0+14acd97
= test session starts =
platform linux -- Python 3.6.9, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: .../scipy, inifile: pytest.ini
collected 0 items / 1 errors                                                                                                                                                                                      

= ERRORS =
_ ERROR collecting test_script.py _
ImportError while importing test module 'test_script.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_script.py:2: in <module>
    from scipy.ndimage.interpolation import zoom
scipy/ndimage/__init__.py:161: in <module>
    from .filters import *
scipy/ndimage/filters.py:37: in <module>
    from scipy.misc import doccer
scipy/misc/__init__.py:67: in <module>
    from scipy.interpolate._pade import pade as _pade
scipy/interpolate/__init__.py:175: in <module>
    from .interpolate import *
scipy/interpolate/interpolate.py:21: in <module>
    import scipy.special as spec
scipy/special/__init__.py:640: in <module>
    from ._ufuncs import *
E   ImportError: .../scipy/scipy/special/_ufuncs.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _gfortran_stop_numeric_f08
!!! Interrupted: 1 errors during collection !!!
= 1 error in 0.34s =
The merge base 14acd976fbe1e980953f564705ba77ef40526a97 is bad.
This means the bug has been fixed between 14acd976fbe1e980953f564705ba77ef40526a97 and [83eb32d32f9a4d8fcb03dc75478f39c8f1cb7686].
bisect run failed:
'bisect_state bad' exited with error code 3
```

**Comment by pllim** [comment] 2019-10-09 20:52
(Trying it in a slightly different way, will report back.)

**Comment by pllim** [comment] 2019-10-09 21:12
Directory structure:
```
scipy/
    source checkout is here
    test_script.sh
ztmp_bisect/
    test_script.py
```

<details><summary>Content of `test_script.sh`</summary>
<p>
#!/bin/bash<br/>
python setup.py develop<br/>
pushd ../ztmp_bisect/<br/>
pytest test_script.py<br/>
popd
</p>
</details>

<details><summary>Content of `test_script.py`</summary>
<p>
import numpy as np<br/>
from scipy.ndimage.interpolation import zoom<br/>
<br/>
a = np.arange(100).reshape(10, 10)<br/>
result = zoom(a, 0.5)<br/>
ans = np.array([[0, 2, 4, 7, 9],<br/>
&nbsp;&nbsp; &nbsp; &nbsp;[22, 25, 27, 29, 31],<br/>
&nbsp;&nbsp; &nbsp; &nbsp;[45, 47, 49, 52, 54],<br/>
&nbsp;&nbsp; &nbsp; &nbsp;[68, 70, 72, 74, 77],<br/>
&nbsp;&nbsp; &nbsp; &nbsp;[90, 92, 95, 97, 99]])<br/>
assert np.testing.assert_array_equal(result, ans)
</p>
</details>

To find the commit hashes:
```
git log --after="2018-03-23 00:00:00" --before="2018-05-05"
```
That gave me 250c68d012d1fffa27f78a3ea2ca76ee054b36df..f5a8260e76bd6eeb397e1ea467d453a9248b5cf5. So I use these instead of release tags.

Then in the `scipy` directory, I do this:
```
git bisect start
git bisect bad f5a8260e76bd6eeb397e1ea467d453a9248b5cf5
git bisect good 250c68d012d1fffa27f78a3ea2ca76ee054b36df
git bisect run test_script.sh
```

It ran for a while, but unfortunately crashed in a fashion as #8325 and then blamed #8740, which I don't think is what I am looking for.

**Comment by grlee77** [comment] 2019-10-09 21:30
If I run the example provided in the first comment but with `dtype=np.float64` and inspect
element `result[0][2]`, the value is extremely close to 4.5

 with the result in SciPy 1.0 being just below 4.5:
`4.4999999999999964`

and that for SciPy >= 1.1 being just above 4.5:
`4.500000000000002`

This tiny difference is resulting in rounding to a different integer when the input dtype is of integer type. Given that the observed differences are at the threshold of double point precision, I think the most likely culprit is in refactoring of the spline coefficient calculations out into a separate file where some uses of `sqrt` in 1.0 were replaced with explicit values. e.g.:
https://github.com/scipy/scipy/blob/2d6327e205ccf76ae3dcae45db4587c7961ee3f4/scipy/ndimage/src/ni_splines.c#L132-L135

**Comment by pllim** [comment] 2019-10-09 21:49
@grlee77 , thank you! So is this a bug or feature?

**Comment by grlee77** [comment] 2019-10-09 22:11
I wouldn't really consider it a bug given that the issue seems to be at the threshold of floating point precision.  I think the change in behaviour was likely unintended, but I don't think I would advocate changing it back at this point.

What do others here think?

**Comment by grlee77** [comment] 2019-10-09 22:22
For reference, the refactoring of the spline coefficient calculation code was done in #8512. Note that I haven't verfied that this commit is definitely the source of the difference, but I think it is fairly likely.

**Comment by sethtroisi** [comment] 2020-05-29 08:12
@rgommers I attempted to verify that #8512 was the cause of this behavior change but cython fails to build 2018-03 code (likely due to Python2). I buy @grlee77's explanation so I vote we close this as working as intended.

**Comment by rgommers** [comment] 2020-05-29 10:59
I agree, makes sense. Thanks for looking into it @grlee77 and @sethtroisi. Closing.

**Closed by rgommers** 2020-05-29 10:59 UTC
Labels: scipy.ndimage
