### ISSUE TITLE
linprog returns an incorrect message

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [scipy/scipy#12485] opened 2020-07-04 15:52 UTC
On scipy/scipy/optimize/_linprog_util.py, line 512, the method _presolve generates the incorrect message
            message = ("The problem is (trivially) infeasible due to a row "
                       "of zeros in the equality constraint matrix with a "
                       "nonzero corresponding  constraint value."
after testing zero_row = np.array(np.sum(A_ub != 0, axis=1) == 0).flatten(). 
The message should be
  message = ("The problem is (trivially) infeasible due to a row "
                       "of zeros in the INEQUALITY constraint matrix with a "
                       "nonzero corresponding  constraint value."

**Comment by mdhaber** [comment] 2020-07-09 22:59
This can be addressed in gh-12510.
Currently, it appears the gh-12510 removes these messages entirely. @rafaelrojasmiliani would that be a good solution, or is the information about why the problem is infeasible helpful?

**Comment by rafaelrojasmiliani** [comment] 2020-07-16 09:25
Hello @mdhaber. In my opinion such an information is very useful because it allows the implementer to correct a poor problem formulation. In fact, one of the major difficulties in optimization is to formulate the correct and feasible problem. These messages can help to debug errors in the code and the theory behind the program.

**Closed** 2022-02-09 14:28 UTC
Labels: scipy.optimize
