### ISSUE TITLE
BUG: special.factorial2: incorrect result for `n=-1`

### ISSUE THREAD

**Issue by aewjones** [scipy/scipy#21501] opened 2024-09-03 15:41 UTC
### Describe your issue.

scipy.special.factorial2(n) computes the double factorial of n (i.e., n!!). By definition, -1!! = 1 (see [https://mathworld.wolfram.com/DoubleFactorial.html](url)); however, factorial2(n) returns 0 if n < 0.

### Reproducing Code Example

```python
from scipy.special import factorial2

# should print 1, but actually prints 0
print(factorial2(-1))
```

### Error message

```shell
(no error message)
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 1.26.4 sys.version_info(major=3, minor=12, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Jones/AppData/Local/anaconda3/Library/include
    lib directory: C:/Users/Jones/AppData/Local/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_efv75hqhju\croot\scipy_1717521501389\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Jones/AppData/Local/anaconda3/Library/include
    lib directory: C:/Users/Jones/AppData/Local/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_efv75hqhju\croot\scipy_1717521501389\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  pybind11:
    detection method: pkgconfig
    include directory: C:/Users/Jones/AppData/Local/anaconda3/Library/include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: clang-cl.exe
    linker: lld-link
    name: clang-cl
    version: 14.0.6
  c++:
    commands: clang-cl.exe
    linker: lld-link
    name: clang-cl
    version: 14.0.6
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: ifort
    linker: xilink
    name: intel-cl
    version: 2021.6.0
  pythran:
    include directory: ..\..\_h_env\Lib\site-packages\pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\b\abs_efv75hqhju\croot\scipy_1717521501389\_h_env\python.exe
  version: '3.12'
```

**Comment by lucascolley** [comment] 2024-09-03 15:44
gh-18409 is relevant. cc @h-vetinari

**Comment by h-vetinari** [comment] 2024-09-04 00:14
This is a duplicate of #18813. Please read that issue for context (also [this](https://github.com/scipy/scipy/pull/19716#issuecomment-1871892216) may help). The choice whether `factorial(-1)` is 0 or 1 is arbitrary, though 1 would be much worse for the extensions that people want to have for the factorial functions.

In other words, we've made that change intentionally, and it's highly unlikely to change. If you rely on recursion, you can either stop the recursion earlier (i.e. at 0 instead of -1, or similar), or use your own wrapper that puts ones at negative integers (for `factorial`, `k=1` below):
```python
from scipy.special import factorialk
def my_factorialk(n, k):
    res = factorialk(n, k, exact=True)
    if isinstance(n, np.ndarray):
        res[(n > -k) & (n < 0)] = 1
    else:
        res = 1 if (n > -k) and (n < 0) else res
    return res
```

**Closed** 2024-09-04 04:32 UTC
Labels: defect, scipy.special, duplicate
