### ISSUE TITLE
`scipy.stats.mode` - UnboundLocalError on empty sequence

### ISSUE THREAD

**Issue by cel4** [scipy/scipy#4550] opened 2015-02-24 07:23 UTC
`scipy.stats.mode` assumes that its input is never an empty array. Probably needs to be beautified :)

```python
from scipy import stats
stats.mode([])
```

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-101-1fe8797e2f6f> in <module>()
----> 1 stats.mode([])

/Users/ch/miniconda/envs/sci34_dev/lib/python3.4/site-packages/scipy/stats/stats.py in mode(a, axis)
    634         oldcounts = np.maximum(counts, oldcounts)
    635         oldmostfreq = mostfrequent
--> 636     return mostfrequent, oldcounts
    637 
    638 

UnboundLocalError: local variable 'mostfrequent' referenced before assignment
```

This issue was discovered in this stackoverflow thread: http://stackoverflow.com/questions/28687531/python-unboundlocalerror-local-variable-mostfrequent-referenced-before-assig

**Comment by rgommers** [comment] 2015-02-24 07:27
Probably should return empty arrays instead of raising an error.

**Comment by maniteja123** [comment] 2015-02-24 10:01
I was looking at the source code and observed some other peculiar behavior also

The documentation says this is the behavior

     >>> a = np.array([[6, 8, 3, 0],
                      [3, 2, 1, 7],
                      [8, 1, 8, 4],
                      [5, 3, 0, 5],
                      [4, 7, 5, 9]])
    >>> from scipy import stats
    >>> stats.mode(a)
    (array([[ 3.,  1.,  0.,  0.]]), array([[ 1.,  1.,  1.,  1.]]))

It is actually giving the following output:

    (array([[ 3,  1,  0,  0]]), array([[ 1.,  1.,  1.,  1.]]))

It is because of [this](https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L629) is
   
    oldmostfreq = np.zeros(testshape, dtype=a.dtype)

is causing ``vals`` to be of same type as the input array. I guess the ``vals`` should should preserve the dtype, while the ``count`` should probably might be an integer.

Also the behavior for scalars is ambiguous

    >>>stats.mode(np.array(4),axis=None)
    (array([4]), array([ 1.]))
    >>>stats.mode(np.array(4))
    IndexError: list assignment index out of range

**Comment by rgommers** [comment] 2015-02-25 07:30
Dtype should be preserved here, so the actual return is OK and the docstring example needs fixing.

**Comment by rgommers** [comment] 2015-02-25 07:33
The behavior for scalars is also wrong, nice catch. I'd say that it should be treated as a 1-D array of size 1. So needs an ``atleast_1d`` in there.

This makes it 3 things to fix, all straightforward.

**Comment by maniteja123** [comment] 2015-02-25 14:37
So, is it necessary to change the behavior of _ckk_array in general to return a 1D array in case a scalar is passed. As of now, if axis is None, it is returning a 1D array, else it is returning a scalar array, since

    >>>np.asarray(4)
    array(4)
    >>>np.ravel(4)
    array([4])

Or should the scalar case be handled only in this function ?

Also, dtype should be preserved for the ``vals``, but wouldn't it better if we use dtype as ``np.int`` for the ``counts``. It is currently returning floats.

It is currently defined as 

    oldcounts = np.zeros(testshape)

but would it be better if it was

   oldcounts = np.zeros(testshape, dtype=np.int)

Coming to the actual problem, if  the input is an empty array, should a empty array be returned as ``vals`` and what about the ``counts`` ??

    >>>np.mode([])
    (array([]),array[0])

Is the above better or even the ``counts`` should be empty ?

    >>>np.mode([])
    (array([]),array[])

**Comment by rgommers** [comment] 2015-02-26 15:43
I had a look at the functions in ``stats.py``, I think going to 1-D arrays would be better for all of them. A lot fail now with strange errors. Adding this to ``_chk_asarray`` seems to work:

    if len(a.shape) == 0:
        a = a.reshape(1)

I get one warning from ``test_nanmedian_scalars`` that can be fixed by adapting the test. Note that while ``nanmedian`` works now, ``stats.nanmean(1)`` doesn't.

Note that I didn't check the ``mstats`` functions that use ``_chk_asarray``, but I expect they'll also be improved. 

Adding tests for this change will be a bit cumbersome, because of the large amount of functions added. On the other hand, it not very difficult.

**Comment by rgommers** [comment] 2015-02-26 15:44
Agreed that ``counts`` should contain integers.

**Comment by rgommers** [comment] 2015-02-26 15:54
actually never mind the ``stats.nan*`` functions - they're deprecated.

**Comment by maniteja123** [comment] 2015-02-26 16:11
I actually was just looking into the code, when I saw the deprecation warning :) 

With regards to ``mstats``, only ``mstats_basic.py`` uses ``_chk_asarray`` and I think ``_chk_asarray``[this](https://github.com/scipy/scipy/blob/master/scipy/stats/mstats_basic.py#L63) also would show same behavior for scalars, since

    >>>np.ma.asanyarray(4)
    masked_array(data = 4,
                            mask = False,
                   fill_value = 999999 )

and moreover there were no tests for scalars.

**Comment by aeklant** [comment] 2015-03-05 21:29
Hi guys, my name is Abraham and I would like to start contributing to the community. I read this issue thread and I would like for it to be my first contribution. I just want to make sure I got the gist of it so as to not waste your time nor mine.

The changes would be the following:

1) `scipy.stats.mode` should return an empty array instead of raising an error when receiving an empty array
2) Add `dtype=int` for `counts`
3) Update docstring to reflect `dtype=a.dtype`
4) Add tests for points 1 and 2

There's also the change to `_chk_asarray` to handle scalars. Should that be in another patch? (since it doesn't really pertain to the issue addressed here)

I think if `_chk_asarray` is to be changed, we should consider making the same update to `_chk2_asarray` (perhaps even changing `_chk2_asarray` to use `_chk_asarray` internally to avoid code redundancy). Could I get your opinion?

**Comment by maniteja123** [comment] 2015-03-06 00:31
Hi Abraham, even I am new to the community. Welcome !
The first three changes I think are the one needed for this issue as such.

Coming to the behavior of `_chk_array`, the whole `stats.py` uses it , hence any change would warrant adding a lot of new tests to check the scalars issue. Note that the actual cause is the working of `asarray` function on scalars. Maybe that needs to be changed. Yeah, you are also right about the `_chk_array2`. It is best to leave that to other PR I guess.

**Comment by maniteja123** [comment] 2015-03-08 05:41
The following change to ``_chk_asarray`` 

    if len(np.array(a).shape) == 0:
        a = np.atleast_1d(a)

causes a warning to be raised in ``test_nanmedian_scalars`` as @rgommers pointed out.

   ERROR: test_nanmedian_scalars (test_stats.TestNanFunc)
   ----------------------------------------------------------------------
   Traceback (most recent call last):
   File "/home/FOSS/venv2/local/lib/python2.7/site-packages/scipy/stats/tests/test_stats
   .py", line 226, in test_nanmedian_scalars
    assert_equal(stats.nanmedian(np.nan), np.median(np.nan))
    File "/home/FOSS/venv2/local/lib/python2.7/site-packages/numpy/lib/utils.py", line 97
    , in newfunc

Since the nanfunctions are deprecated, is it preferable to modify the tests to check for the ``RuntimeWarning`` or better to write a whole new set of tests ?

Also the change to ``chk_asarra`` is handling the case of scalar inputs properly.

**Comment by aeklant** [comment] 2015-03-09 04:45
Hello again,

I've been working on this and familiarising myself with the code in an attempt to make my first contribution, but I do have a couple of doubts:

1) What is a good definition for "an empty array"? is it `numpy.empty_like([])`? or maybe `numpy.array([])`? or something else?

2) Should the `count` (in the case of receiving an empty array as a parameter, of course) also be an "empty array" or should it be something like: `numpy.array([0])`?

3) In the case of the change of `count`'s to `dtype = int` I think it would be a good idea to change the test cases for clarity. What I mean is they should now look like this: `assert_equal(vals[0][0],6)` instead of this: `assert_almost_equal(vals[0][0],6)` (which I assume is due to the possible inaccuracy of the current float representation). The tests still pass just fine so I believe there is really no practical need to make that change other than clarity and conciseness, but I think that those reasons ought to be more than enough. 

What do you guys think?


The other thing is that (it may be because I'm fairly new, but) having the other issue of the `_chk_array` (and `_chk2_array` for that matter) makes it a little more confusing for me to understand where one problem ends and the other begins and since I think you agree this should be made as another PR, maybe we should create a new issue for it so as to be able to close this and work on that one in isolation. Let me know if you agree and if so, would you mind if I created the issue myself? I know it may be silly to ask but since I'm new and I want to get the ball rolling on contributing, it is kind of a big deal to me.

**Comment by rgommers** [comment] 2015-03-09 05:13
Hi @aeklant, the ``_chk_asarray`` would be good to address first if you want to split this issue in two parts. No need to open a new issue I think, just refer to this one (because all the discussion is here).

To answer your questions:

(1) the most common way to make an empty array is ``np.array([])``. If a function takes ``array_like`` input then you can also simply pass in an empty list. Note that there are other ways to create empty arrays that are not of shape ``(0,)``, but I don't think you need to worry about those.

(2) I changed my mind: I think ``counts`` should also be empty. Reason: ``vals`` and ``counts`` should be of the same size.

**Comment by maniteja123** [comment] 2015-03-09 09:13
@aeklant If you want to change the behavior of

**Comment by maniteja123** [comment] 2015-03-09 09:47
Sorry for the incomplete comment before, If you want to change the working of ``_chk_array``,  if we use 

    if len(a.shape) == 0:
        a = a.reshape(1)

some tests were failing, probably when is not a ndarray, but a list or something like that. So, it would be better to have 

    if len(np.array(a).shape) == 0:
        a = np.atleast_1d(a)

Hope it helps :)

**Comment by aeklant** [comment] 2015-03-10 16:29
Hi @rgommers, this may be a little bit off topic but I believe it is still relevant in the broad picture of the `scipy.stats` module.

I would like to work on the GSoC with you, specifically on the `scipy.stats` improvements idea. The reason why I mention this is because I am aware that submitting a PR is a requisite in order to apply and I think I have worked out the original issue involving the `scipy.stats.mode` empty arrays. I have also implemented the latest suggestion by @maniteja123 to the `_chk_asarray` and ran a full regression test; it seems to fix the problem of scalars without breaking any functionality. 

The problem that I found is with the implementation of regression tests for scalars. I have found that there are close to forty functions that use `_chk_asarray` or `_chk2_asarray` if we consider both `scipy.stats` and `scipy.mstats.basic` so while it would be fairly simple to do, each one involves some time getting to know the function and its purpose in order to make meaningful tests for each of them which makes it a time consuming task.

**My question is the following: would it be acceptable for you if I submitted the patch for the empty arrays for your consideration while I continue adding the regression tests for the scalars in all those functions?** (this way I could keep contributing and also take care of the requirement for the GSoC application) or is that not acceptable and you think I should take another issue, specific to a StatisticsCleanup issue for example in order to meet the GSoC requirement? (in which case I would have to shift my focus to that and get back to this once I'm done there, considering I still have to dedicate a fair amount of time to my official proposal).

I will definitely keep working on this because by now I'm hooked but also because it would be a great exercise on getting to know the inner workings of `scipy.stats` and furthermore, some of the almost forty functions (like `ss`, `square_of_sums` and even `_chk_asarray` itself) are part of the StatisticsCleanup milestone which is a big part of the `scipy.stats` improvements project. I just want to make sure that my efforts are well prioritised to avoid time turning into an issue with my GSoC proposal.

Could I get your feedback on this?

**Comment by rgommers** [comment] 2015-03-10 21:18
@aeklant good to see you're enjoying yourself:) Yes, it's fine to submit the PR for empty arrays first, and leave the behavior of scalars for a second PR. I think it should be possible to merge that first PR, however even if it's not then it's possible to submit it. Typically we do this for things that need feedback before completing; we then prepend ``WIP: `` (Work In Progress) to the title of the PR.

**Comment by rgommers** [comment] 2015-03-10 21:19
and if you have a first draft of your proposal, please ping me. my experience is that it takes at least a few iterations to get it right.

**Comment by aeklant** [comment] 2015-03-11 01:38
@rgommers, I just made the PR; this is my first PR ever so if you find anything wrong with it, let me know, I am eager to learn. 

I will definitely need a few iterations for the proposal since I have some doubts that I will need your help to clarify. My intention was to upload my first draft to the mailing list. Is there a better or more direct way to ping you? (this thread is obviously not the place, of that I am aware).

**Comment by rgommers** [comment] 2015-03-11 06:38
The mailing list is perfect - it's always good for people to see that you're active and what you're working on, and there's a good chance you get feedback from multiple people.

**Comment by aeklant** [comment] 2015-04-05 07:27
Hello guys, 

Here is the list of all the functions in `stats` that make use of the helper functions `_chk_asarray` or `_chk2_asarray`:

`nanmean`
`nanstd`
`nanmedian`
`mode`
`tmin`
`tmax`
`moment`
`variation`
`skew`
`kurtosis`
`describe`
`skewtest`
`kurtosistest`
`normaltest`
`sem`
`spearmanr`
`ttest_1samp`
`ttest_ind`
`ttest_rel`
`ss`
`square_of_sums`

I just did a PR for the `_chk_asarray` handling of scalars and I added test cases for most of them. Here are some notes:

1) `nan*` functions were ignored when adding test coverage since they are deprecated.
2) The expected results in the test cases added are based on the results with the input of `[4.]`. Please check if those results are appropriate. I'm especially uncertain about `spearmanr` and `sem`; should they raise a ValueError instead of returning `nan`, maybe?
3) I'm not sure how (or if) I should test for scalars in `ttest_*` functions so I did not include it. Input appreciated.
4) `ss` and `square_of_sums` have null test coverage but since they are part of the StatisticsCleanup milestone I will reserve the addition of test cases until after their scope within the milestone has been properly defined (see issues 663 and 665 respectively).
5) `mstats_basic` has a nearly identical list of functions but since the implementation is completely independent with slight differences in the results which touches on one topic of "`scipy.stats` improvements" (making `mstats` compatible with its `stats` counterparts) I decided to not include it here because it will just be reworked so I don't think it is worth it at this time.

I appreciate any and all input you guys may have.

**Comment by rgommers** [comment] 2015-04-05 09:24
> 1) nan* functions were ignored when adding test coverage since they are deprecated.

makes sense

> 2) The expected results in the test cases added are based on the results with the input of [4.]. Please check if those results are appropriate. I'm especially uncertain about spearmanr and sem; should they raise a ValueError instead of returning nan, maybe?

I replied to ``sem`` and ``spearmanr``, will check the rest later.

> 3) I'm not sure how (or if) I should test for scalars in ttest_* functions so I did not include it. Input appreciated.

I would start by simply checking what it does now for size-1 array input and if that's sensible. If it is, just test for that expected result:

    In [35]: stats.ttest_1samp([1], [2])
    Out[35]: (array([ nan]), array([ nan]))

    In [36]: stats.ttest_1samp(1, 2)
    ---------------------------------------------------------------------------
    IndexError 
    ....
    <fixme.....>

> 4) ss and square_of_sums have null test coverage but since they are part of the StatisticsCleanup milestone I will reserve the addition of test cases until after their scope within the milestone has been properly defined (see issues 663 and 665 respectively).

That's fine, as long as you checked that you didn't break something that worked before. Looks like that's the case:

    In [37]: stats.ss(1)
    Out[37]: 1

    In [38]: stats.ss([1])
    Out[38]: 1

    In [39]: stats.square_of_sums(1)
    Out[39]: 1.0

    In [40]: stats.square_of_sums([1])
    Out[40]: 1.0

> 5) mstats_basic has a nearly identical list of functions but since the implementation is completely independent with slight differences in the results which touches on one topic of "scipy.stats improvements" (making mstats compatible with its stats counterparts) I decided to not include it here because it will just be reworked so I don't think it is worth it at this time.

That makes sense. ``stats.mstats`` has its own implementation of ``_chk_asarray``,``_chk_asarray2`` and ``_chk_size`` so not touching those at all now doesn't break anything.

**Comment by rgommers** [comment] 2015-04-12 19:44
@aeklant just double checking: we can close this issue now right?

**Comment by aeklant** [comment] 2015-04-12 20:00
Yes, @rgommers. I think we've dealt with every topic in the discussion. +1 for closing this issue.

**Comment by rgommers** [comment] 2015-04-12 20:03
Great, done.

**Closed by rgommers** 2015-04-12 20:03 UTC
Labels: defect, easy-fix, scipy.stats
