### ISSUE TITLE
Failure with TestQRdelete_F.test_delete_last_p_col

### ISSUE THREAD

**Issue by zchelseal** [scipy/scipy#10550] opened 2019-07-29 18:35 UTC
Hi! I recently set up my dev environment following the [quickstart guide for macOS](https://scipy.github.io/devdocs/dev/contributor/quickstart_mac.html#quickstart-mac), but upon running `python runtests.py -v` all tests passed except `TestQRdelete_F.test_delete_last_p_col`, with an error message similar to #5335. 

#### Error message:

```Python
================================================================================================= FAILURES =================================================================================================
__________________________________________________________________________________ TestQRdelete_F.test_delete_last_p_col ___________________________________________________________________________________

self = <scipy.linalg.tests.test_decomp_update.TestQRdelete_F object at 0x123e020b8>

    def test_delete_last_p_col(self):
        a, q, r = self.generate('tall', 'full')
        q1, r1 = qr_delete(q, r, 0, a.shape[1], 'col')
>       assert_unitary(q1)

a          = array([[0.36852294+0.7065659j , 0.9763755 +0.8815727j ,
        0.73179656+0.5390478j , 0.6848747 +0.2577209j ,
      ...0.8069605j ,
        0.2923851 +0.9023696j , 0.08459105+0.7541054j ,
        0.8391204 +0.23152167j]], dtype=complex64)
q          = array([[-0.11519074-0.22085421j,  0.4031076 +0.25545135j,
         0.20641464-0.02725353j,  0.04916074+0.12054591j,
  ....17945503j,  0.10257003-0.11285198j,
        -0.05898733+0.03267026j,  0.5694973 -0.06679238j]],
      dtype=complex64)
q1         = array([[-0.11519074-0.22085421j,  0.4031076 +0.25545135j,
         0.20641464-0.02725353j,  0.04916074+0.12054591j,
  ....17945503j,  0.10257003-0.11285198j,
        -0.05898733+0.03267026j,  0.5694973 -0.06679238j]],
      dtype=complex64)
r          = array([[-3.1992414 +0.j        , -2.1899545 +0.23892963j,
        -1.6467261 +0.47293147j, -2.4033258 +0.41776413j,
  ...        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ]], dtype=complex64)
r1         = array([], shape=(12, 0), dtype=complex64)
self       = <scipy.linalg.tests.test_decomp_update.TestQRdelete_F object at 0x123e020b8>

scipy/linalg/tests/test_decomp_update.py:327: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = array([[-0.11519074-0.22085421j,  0.4031076 +0.25545135j,
         0.20641464-0.02725353j,  0.04916074+0.12054591j,
  ....17945503j,  0.10257003-0.11285198j,
        -0.05898733+0.03267026j,  0.5694973 -0.06679238j]],
      dtype=complex64)
rtol = 0.0001, atol = 2.384185791015625e-07, assert_sqr = True

    def assert_unitary(a, rtol=None, atol=None, assert_sqr=True):
        if rtol is None:
            rtol = 10.0 ** -(np.finfo(a.dtype).precision-2)
        if atol is None:
            atol = 2*np.finfo(a.dtype).eps
    
        if assert_sqr:
            assert_(a.shape[0] == a.shape[1], 'unitary matrices must be square')
        aTa = np.dot(a.T.conj(), a)
>       assert_allclose(aTa, np.eye(a.shape[1]), rtol=rtol, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=0.0001, atol=2.38419e-07
E       
E       Mismatch: 1.39%
E       Max absolute difference: 3.57627869e-07
E       Max relative difference: inf
E        x: array([[ 1.000000e+00+0.000000e+00j, -1.676381e-08+1.490116e-08j,
E                0.000000e+00+1.490116e-08j, -2.793968e-08-2.980232e-08j,
E               -2.235174e-08-1.862645e-08j, -2.095476e-08+5.587935e-09j,...
E        y: array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
E              [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
E              [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],...

a          = array([[-0.11519074-0.22085421j,  0.4031076 +0.25545135j,
         0.20641464-0.02725353j,  0.04916074+0.12054591j,
  ....17945503j,  0.10257003-0.11285198j,
        -0.05898733+0.03267026j,  0.5694973 -0.06679238j]],
      dtype=complex64)
aTa        = array([[ 1.0000001e+00+0.0000000e+00j, -1.6763806e-08+1.4901161e-08j,
         0.0000000e+00+1.4901161e-08j, -2.793967...3484e-08-4.4703484e-08j,
        -8.3819032e-09-2.9802322e-08j,  9.9999994e-01+0.0000000e+00j]],
      dtype=complex64)
assert_sqr = True
atol       = 2.384185791015625e-07
rtol       = 0.0001

scipy/linalg/tests/test_decomp_update.py:21: AssertionError
```

#### Scipy/Numpy/Python version information:

1.4.0.dev0+8e40c06

**Comment by tylerjereddy** [comment] 2019-07-30 21:22
I always have to wonder what linear algebra backend is being used when linalg tests fail on a mac. I think you can dig this up from the `FOUND` lines in the build log.

**Comment by zchelseal** [comment] 2019-07-30 21:45
There are the lines from `build.log`:
```
  FOUND:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/envs/scipydev/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/envs/scipydev/include']
```

**Comment by ev-br** [comment] 2019-07-30 22:16
possibly related to (or is a duplicate of) gh-5117

**Comment by mdhaber** [comment] 2024-08-22 06:27
Same test for a different dtype, so let's consolidate under gh-5117.

**Closed by mdhaber** 2024-08-22 06:27 UTC
Labels: scipy.linalg
