### ISSUE TITLE
scipy.special.wofz and np.float128

### ISSUE THREAD

**Issue by klaykulik** [scipy/scipy#10109] opened 2019-04-29 20:18 UTC
```scipy.special.wofz``` generates an error when given an input array of type ```np.float128```.

### Reproducing code example:

```
import numpy as np
from scipy.special import wofz

x1 = np.linspace(100, 200, 352, dtype=np.float64)
wofz(x1)
print('ok')

x2 = np.linspace(100, 200, 352, dtype=np.float128)
wofz(x2)
print('ok2')
```

### Output:

```
ok
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    wofz(x2)
TypeError: ufunc 'wofz' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Scipy/Numpy/Python version information:

```
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by person142** [comment] 2019-04-29 20:27
Unfortunately the issue is pretty much what it says--we don't have an implementation of `wofz` for `np.float128`. (Most of our implementations are double-precision only.) Creating one would likely be a large undertaking too (and there's all the annoyance around `np.float128` meaning different things on different platforms), so it's unlikely to happen.

**Comment by person142** [comment] 2019-04-29 20:30
One notes that a previous PR adding long double implementations for different functions was not met with enthusiasm: https://github.com/scipy/scipy/pull/8079, so it's not clear that it's something we even want to support.

**Comment by rgommers** [comment] 2019-04-29 21:24
Yeah, I'd prefer not to support float128. We could cast them to float64, but perhaps an error is just clearer - then the user knows what precision they get, and casting by hand is not a big burden

**Comment by person142** [comment] 2019-06-18 03:09
Closing as a won't do.

**Closed by person142** 2019-06-18 03:09 UTC
Labels: scipy.special
