### ISSUE TITLE
scipy.sparse.coo_matrix.tocsr modifies the row, col, and data attributes of the original coo_matrix

### ISSUE THREAD

**Issue by michaelbynum** [scipy/scipy#6429] opened 2016-07-28 15:09 UTC
In scipy-0.18.0, scipy.sparse.coo_matrix.tocsr() modifies the row, col, and data attributes of the original matrix. This is not the case in scipy-0.17.0. Consider the following example:

**********************************************************************************

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg

row = [0, 1, 2, 0, 0, 1, 2, 3, 4, 5, 3, 4, 5, 6, 7, 6, 7, 6, 7]
col =[3, 4, 5, 7, 6, 7, 6, 0, 1, 2, 3, 4, 5, 2, 0, 0, 1, 6, 7]
data = [-1, -1, -1, -1, 1, 1, -1, 0, 0, 1, 1, 1, 0, -1, -1, 1, 1, 0.491, 0.491]

A = scipy.sparse.coo_matrix((data, (row,col)), shape=(8,8))
print A.toarray()

print A.row
print A.col
print A.data

B = A.tocsr()

print A.row
print A.col
print A.data

print A.toarray()

**********************************************************************************

In both 0.17.0 and 0.18.0, the matrix A does not change. However in 0.18.0, A.row, A.col, and A.data chage after A.tocsr() is called. This is problematic when, for example, I need to create A, convert to csr, solve a linear system, update only the data of A, repeat.

Scipy has been a tremendous asset to my work, so I'd like to thank the development team. Also, thanks for help with this issue.

**Comment by pv** [comment] 2016-07-28 15:39
Some of the sparse matrix operations need to canonicalize the 
representation in order to work. Which of them do, is not currently 
explicitly specified in the API, and so you can expect it to change 
between releases.

**Comment by perimosocordiae** [comment] 2016-07-28 15:45
In this particular case, you can get the old behavior by specifying `A.tocsr(copy=True)`.

**Comment by pv** [comment] 2016-07-28 15:49
A.tocsr(copy=True) doesn't do it, because this is about sum_duplicates.

**Comment by perimosocordiae** [comment] 2016-07-28 15:51
Ah, fair enough. In that case, one could just sum the duplicates once before the loop, then carry on as before.

Sounds like this is a "works as intended" case, so I'll close the issue.

**Closed by perimosocordiae** 2016-07-28 15:51 UTC

**Comment by michaelbynum** [comment] 2016-07-28 15:54
Usually when a method returns a copy of an object, the original object is unchanged...? The documenation:

coo_matrix.tocsr()
Return a copy of this matrix in Compressed Sparse Row format

Duplicate entries will be summed together.
