### ISSUE TITLE
TST/MAINT: `AssertionError`s with fresh build on M1 macOS

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#19117] opened 2023-08-23 14:52 UTC
### Describe your issue.

I am getting 6 `AssertionError`s from `python dev.py test` on a fresh build from source. This is on an M1 MacBook Air 2020 running macOS Ventura 13.5.

### Reproducing Code Example

```python
python dev.py test
```

### Error message

```shell
================================================================================================= FAILURES =================================================================================================
__________________________________________________________________________________ test_dst4_definition_ortho[1-float32] ___________________________________________________________________________________
scipy/fft/_pocketfft/tests/test_real_transforms.py:382: in test_dst4_definition_ortho
    assert_array_almost_equal(y, y2, decimal=dec)
        dec        = 6
        dt         = dtype('float32')
        mdata_x    = array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])
        rdt        = <class 'numpy.float32'>
        x          = array([ 0.        ,  0.71428573,  1.4285715 ,  2.142857  ,  2.857143  ,
        3.5714285 ,  4.285714  ,  5.        ,  5.714286  ,  6.428571  ,
        7.142857  ,  7.857143  ,  8.571428  ,  9.285714  , 10.        ],
      dtype=float32)
        y          = array([ 2.2527182e+01, -3.0485203e+00,  6.8829376e-01, -6.5594608e-01,
        1.3825622e-01, -3.0407611e-01,  2.43382... -1.2823799e-01, -3.5893470e-02, -9.6654691e-02,
       -4.9417440e-02, -7.6473922e-02, -6.1873209e-02], dtype=float32)
        y2         = array([ 2.25271838e+01, -3.04852029e+00,  6.88293833e-01, -6.55946133e-01,
        1.38256458e-01, -3.04076803e-01,  2...4780e-02, -1.28238488e-01, -3.58937516e-02, -9.66546037e-02,
       -4.94173596e-02, -7.64740413e-02, -6.18725511e-02])
../../../../../../mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
        args       = (array([ 2.2527182e+01, -3.0485203e+00,  6.8829376e-01, -6.5594608e-01,
        1.3825622e-01, -3.0407611e-01,  2.4338...780e-02, -1.28238488e-01, -3.58937516e-02, -9.66546037e-02,
       -4.94173596e-02, -7.64740413e-02, -6.18725511e-02]))
        func       = <function assert_array_almost_equal at 0x10d475a20>
        kwds       = {'decimal': 6}
        self       = <contextlib._GeneratorContextManager object at 0x10d473ee0>
../../../../../../mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Arrays are not almost equal to 6 decimals
E   
E   Mismatched elements: 1 / 15 (6.67%)
E   Max absolute difference: 2.20676786e-06
E   Max relative difference: 1.06287481e-05
E    x: array([ 2.252718e+01, -3.048520e+00,  6.882938e-01, -6.559461e-01,
E           1.382562e-01, -3.040761e-01,  2.433828e-02, -1.844277e-01,
E          -1.595955e-02, -1.282380e-01, -3.589347e-02, -9.665469e-02,
E          -4.941744e-02, -7.647392e-02, -6.187321e-02], dtype=float32)
E    y: array([ 2.252718e+01, -3.048520e+00,  6.882938e-01, -6.559461e-01,
E           1.382565e-01, -3.040768e-01,  2.433815e-02, -1.844278e-01,
E          -1.595948e-02, -1.282385e-01, -3.589375e-02, -9.665460e-02,
E          -4.941736e-02, -7.647404e-02, -6.187255e-02])
        args       = (<function assert_array_almost_equal.<locals>.compare at 0x28a892f80>, array([ 2.2527182e+01, -3.0485203e+00,  6.88293...780e-02, -1.28238488e-01, -3.58937516e-02, -9.66546037e-02,
       -4.94173596e-02, -7.64740413e-02, -6.18725511e-02]))
        func       = <function assert_array_compare at 0x10d475870>
        kwds       = {'err_msg': '', 'header': 'Arrays are not almost equal to 6 decimals', 'precision': 6, 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x10d473e50>
_____________________________________________________________________________________________ test_uint64_max ______________________________________________________________________________________________
scipy/ndimage/tests/test_datatypes.py:62: in test_uint64_max
    assert_(x[2] == int(float(big)))
E   AssertionError
        arr        = array([18446744073709550591, 18446744073709550591, 18446744073709550591],
      dtype=uint64)
        big        = 18446744073709550591
        inds       = array([[-0.1,  0.9,  1.9]])
        x          = array([                   0, 18446744073709549568, 18446744073709551615],
      dtype=uint64)
__________________________________________________________________________________________ test_quat_double_cover __________________________________________________________________________________________
scipy/spatial/transform/tests/test_rotation.py:84: in test_quat_double_cover
    assert_allclose((r*r.inv()).as_quat(canonical=False),
        q          = array([0.70710678, 0.        , 0.        , 0.70710678])
        r          = <scipy.spatial.transform._rotation.Rotation object at 0x14717ae20>
        r3         = <scipy.spatial.transform._rotation.Rotation object at 0x14717af10>
../../../../../../mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=0
E   
E   Mismatched elements: 1 / 4 (25%)
E   Max absolute difference: 4.26642159e-17
E   Max relative difference: 0.
E    x: array([4.266422e-17, 0.000000e+00, 0.000000e+00, 1.000000e+00])
E    y: array([0, 0, 0, 1])
        args       = (<function assert_allclose.<locals>.compare at 0x2b0817880>, array([4.26642159e-17, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]), array([0, 0, 0, 1]))
        func       = <function assert_array_compare at 0x10d475870>
        kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-07, atol=0', 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x10d473e50>
_________________________________________________________ TestHyp2f1.test_a_b_neg_int_after_euler_hypergeometric_transformation[hyp2f1_test_case0] _________________________________________________________
scipy/special/tests/test_hyp2f1.py:530: in test_a_b_neg_int_after_euler_hypergeometric_transformation
    assert_allclose(hyp2f1(a, b, c, z), expected, rtol=rtol)
        a          = -0.5
        b          = -0.9629749245209605
        c          = -15.5
        expected   = (0.9778506962676361+0.044083801141231616j)
        hyp2f1_test_case = Hyp2f1TestCase(a=-0.5, b=-0.9629749245209605, c=-15.5, z=(1.1578947368421053-1.1578947368421053j), expected=(0.9778506962676361+0.044083801141231616j), rtol=1e-12)
        rtol       = 1e-12
        self       = <scipy.special.tests.test_hyp2f1.TestHyp2f1 object at 0x146822ad0>
        z          = (1.1578947368421053-1.1578947368421053j)
../../../../../../mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-12, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 2.83181888e-12
E   Max relative difference: 2.89302401e-12
E    x: array(0.977851+0.044084j)
E    y: array(0.977851+0.044084j)
        args       = (<function assert_allclose.<locals>.compare at 0x2b09c04c0>, array(0.9778507+0.0440838j), array(0.9778507+0.0440838j))
        func       = <function assert_array_compare at 0x10d475870>
        kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-12, atol=0', 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x10d473e50>
_______________________________________________________________________________ TestHyp2f1.test_region4[hyp2f1_test_case47] ________________________________________________________________________________
scipy/special/tests/test_hyp2f1.py:1394: in test_region4
    assert_allclose(hyp2f1(a, b, c, z), expected, rtol=rtol)
        a          = -0.5
        b          = -15.5
        c          = -7.949900487447654
        expected   = (-2258.1590330318213+8860.193389158803j)
        hyp2f1_test_case = Hyp2f1TestCase(a=-0.5, b=-15.5, c=-7.949900487447654, z=(0.4172413793103451-0.8724137931034484j), expected=(-2258.1590330318213+8860.193389158803j), rtol=1e-10)
        rtol       = 1e-10
        self       = <scipy.special.tests.test_hyp2f1.TestHyp2f1 object at 0x146a02a70>
        z          = (0.4172413793103451-0.8724137931034484j)
../../../../../../mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-10, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 1.09362783e-06
E   Max relative difference: 1.19608052e-10
E    x: array(-2258.159032+8860.19339j)
E    y: array(-2258.159033+8860.193389j)
        args       = (<function assert_allclose.<locals>.compare at 0x2b09c1900>, array(-2258.159032+8860.19338952j), array(-2258.15903303+8860.19338916j))
        func       = <function assert_array_compare at 0x10d475870>
        kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-10, atol=0', 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x10d473e50>
________________________________________________________________________________ TestHyp2f1.test_region5[hyp2f1_test_case3] ________________________________________________________________________________
scipy/special/tests/test_hyp2f1.py:1891: in test_region5
    assert_allclose(hyp2f1(a, b, c, z), expected, rtol=rtol)
        a          = 16.087593263474208
        b          = 1.0
        c          = -15.964218273004214
        expected   = (85592537010.05054-8061416766688.324j)
        hyp2f1_test_case = Hyp2f1TestCase(a=16.087593263474208, b=1.0, c=-15.964218273004214, z=(0.6448275862068968+0.8724137931034486j), expected=(85592537010.05054-8061416766688.324j), rtol=1e-14)
        rtol       = 1e-14
        self       = <scipy.special.tests.test_hyp2f1.TestHyp2f1 object at 0x146a036d0>
        z          = (0.6448275862068968+0.8724137931034486j)
../../../../../../mambaforge/envs/scipy-dev/lib/python3.10/contextlib.py:79: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-14, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 0.13428089
E   Max relative difference: 1.66562939e-14
E    x: array(8.559254e+10-8.061417e+12j)
E    y: array(8.559254e+10-8.061417e+12j)
        args       = (<function assert_allclose.<locals>.compare at 0x2b09c1bd0>, array(8.5592537e+10-8.06141677e+12j), array(8.5592537e+10-8.06141677e+12j))
        func       = <function assert_array_compare at 0x10d475870>
        kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-14, atol=0', 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x10d473e50>
========================================================================================= short test summary info ==========================================================================================
FAILED scipy/fft/_pocketfft/tests/test_real_transforms.py::test_dst4_definition_ortho[1-float32] - AssertionError: 
FAILED scipy/ndimage/tests/test_datatypes.py::test_uint64_max - AssertionError
FAILED scipy/spatial/transform/tests/test_rotation.py::test_quat_double_cover - AssertionError: 
FAILED scipy/special/tests/test_hyp2f1.py::TestHyp2f1::test_a_b_neg_int_after_euler_hypergeometric_transformation[hyp2f1_test_case0] - AssertionError: 
FAILED scipy/special/tests/test_hyp2f1.py::TestHyp2f1::test_region4[hyp2f1_test_case47] - AssertionError: 
FAILED scipy/special/tests/test_hyp2f1.py::TestHyp2f1::test_region5[hyp2f1_test_case3] - AssertionError: 
=================================================== 6 failed, 43245 passed, 2449 skipped, 12698 deselected, 145 xfailed, 14 xpassed in 283.89s (0:04:43) ===================================================
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0.dev0+1532.f8036bc 1.25.2 sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Users/lucascolley/mambaforge/envs/scipy-dev/include
    lib directory: /Users/lucascolley/mambaforge/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=0 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=128
    pc file directory: /Users/lucascolley/mambaforge/envs/scipy-dev/lib/pkgconfig
    version: 0.3.23
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /Users/lucascolley/mambaforge/envs/scipy-dev/include
    lib directory: /Users/lucascolley/mambaforge/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=0 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=128
    pc file directory: /Users/lucascolley/mambaforge/envs/scipy-dev/lib/pkgconfig
    version: 0.3.23
  pybind11:
    detection method: pkgconfig
    include directory: /Users/lucascolley/mambaforge/envs/scipy-dev/include
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /Users/lucascolley/mambaforge/envs/scipy-dev/include, -D_FORTIFY_SOURCE=2, -isystem,
      /Users/lucascolley/mambaforge/envs/scipy-dev/include
    commands: arm64-apple-darwin20.0.0-clang
    linker: ld64
    linker args: -Wl,-pie, -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs,
      -Wl,-rpath,/Users/lucascolley/mambaforge/envs/scipy-dev/lib, -L/Users/lucascolley/mambaforge/envs/scipy-dev/lib,
      -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /Users/lucascolley/mambaforge/envs/scipy-dev/include, -D_FORTIFY_SOURCE=2, -isystem,
      /Users/lucascolley/mambaforge/envs/scipy-dev/include
    name: clang
    version: 15.0.7
  c++:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++,
      -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    commands: arm64-apple-darwin20.0.0-clang++
    linker: ld64
    linker args: -Wl,-pie, -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs,
      -Wl,-rpath,/Users/lucascolley/mambaforge/envs/scipy-dev/lib, -L/Users/lucascolley/mambaforge/envs/scipy-dev/lib,
      -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -stdlib=libc++,
      -fvisibility-inlines-hidden, -fmessage-length=0, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include,
      -D_FORTIFY_SOURCE=2, -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    name: clang
    version: 15.0.7
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.0
  fortran:
    args: -march=armv8.3-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe,
      -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    commands: /Users/lucascolley/mambaforge/envs/scipy-dev/bin/arm64-apple-darwin20.0.0-gfortran
    linker: ld64
    linker args: -Wl,-pie, -Wl,-headerpad_max_install_names, -Wl,-dead_strip_dylibs,
      -Wl,-rpath,/Users/lucascolley/mambaforge/envs/scipy-dev/lib, -L/Users/lucascolley/mambaforge/envs/scipy-dev/lib,
      -march=armv8.3-a, -ftree-vectorize, -fPIC, -fno-stack-protector, -O2, -pipe,
      -isystem, /Users/lucascolley/mambaforge/envs/scipy-dev/include
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../../mambaforge/envs/scipy-dev/lib/python3.10/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /Users/lucascolley/mambaforge/envs/scipy-dev/bin/python3.10
  version: '3.10'
```

**Comment by tylerjereddy** [comment] 2023-08-23 14:56
Partial duplicate of gh-18308 I think, some errors may differ slightly.

**Comment by Pranavchiku** [comment] 2023-08-23 15:23
We also encountered similar problems, documented at :https://github.com/certik/scipy/commit/c5e44bff1c99bbb38139e2cd757f620329c4ddb9

**Comment by Kai-Striega** [comment] 2023-08-24 13:37
I've just tried this on my laptop (m2 mac). I've got the same 6 tests failing. However, these are not failing in our CI, so what's different between the two?

**Comment by rgommers** [comment] 2023-09-06 13:11
I'm seeing these as well, trying to fix them all up right now.

**Closed** 2023-09-06 16:58 UTC
Labels: defect
