### ISSUE TITLE
BUG: `dev.py` adds a `-std=c++14` with conda clang

### ISSUE THREAD

**Issue by alugowski** [scipy/scipy#18645] opened 2023-06-08 04:23 UTC
### Describe your issue.

Noticed this while [adding a new extension that requires C++17](https://github.com/scipy/scipy/pull/18631).

You can ask meson for C++17 for a particular extension like this:
```
  override_options: ['cpp_std=c++17'],
```

This works in the CI and my macOS with system default or Homebrew compilers, but breaks with the  `clang-11` from conda. The build commands generated by `python dev.py build` include a `-std=c++14` argument that appears *after* the meson-added `-std=c++17`. The last `-std` argument is used, so this causes the build to fail.

Everything works properly with Clang-11 from Homebrew.

Here are the build commands in `build/compile_commands.json` for one of the C++17 files for the two Clang 11 versions:

Conda clang-11 build command:

```
clang++ -Iscipy/io/_fast_matrix_market/_core.cpython-310-darwin.so.p -Iscipy/io/_fast_matrix_market -I../scipy/io/_fast_matrix_market -I../scipy/io/_fast_matrix_market/fast_matrix_market/include -I../../../../../../opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev-clang11/lib/python3.10/site-packages/numpy/core/include -I../scipy/io/_fast_matrix_market/fast_matrix_market/dependencies/fast_float/include -Iscipy/io/_fast_matrix_market/fast_matrix_market/dependencies/ryu -I../scipy/io/_fast_matrix_market/fast_matrix_market/dependencies/ryu -I/opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev-clang11/include -I/opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev-clang11/include/python3.10 -fvisibility=hidden -fvisibility-inlines-hidden -fcolor-diagnostics -Wall -Winvalid-pch -std=c++17 -O2 -g -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -std=c++14 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev-clang11/include -D_FORTIFY_SOURCE=2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev-clang11/include -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -DFMM_FROM_CHARS_INT_SUPPORTED -DFMM_TO_CHARS_INT_SUPPORTED -DFMM_USE_FAST_FLOAT -DFMM_USE_RYU -MD -MQ scipy/io/_fast_matrix_market/_core.cpython-310-darwin.so.p/src__core_write_csc.cpp.o -MF scipy/io/_fast_matrix_market/_core.cpython-310-darwin.so.p/src__core_write_csc.cpp.o.d -o scipy/io/_fast_matrix_market/_core.cpython-310-darwin.so.p/src__core_write_csc.cpp.o -c ../scipy/io/_fast_matrix_market/src/_core_write_csc.cpp
```

Homebrew clang-11 build command:

```
clang++ -Iscipy/io/_fast_matrix_market/_core.cpython-310-darwin.so.p -Iscipy/io/_fast_matrix_market -I../scipy/io/_fast_matrix_market -I../scipy/io/_fast_matrix_market/fast_matrix_market/include -I../../../../../../opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/lib/python3.10/site-packages/numpy/core/include -I../scipy/io/_fast_matrix_market/fast_matrix_market/dependencies/fast_float/include -Iscipy/io/_fast_matrix_market/fast_matrix_market/dependencies/ryu -I../scipy/io/_fast_matrix_market/fast_matrix_market/dependencies/ryu -I/opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/include -I/opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/include/python3.10 -I/opt/homebrew/opt/llvm@11/include -fvisibility=hidden -fvisibility-inlines-hidden -fcolor-diagnostics -Wall -Winvalid-pch -std=c++17 -O2 -g -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/include -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -DFMM_FROM_CHARS_INT_SUPPORTED -DFMM_TO_CHARS_INT_SUPPORTED -DFMM_USE_FAST_FLOAT -DFMM_USE_RYU -MD -MQ scipy/io/_fast_matrix_market/_core.cpython-310-darwin.so.p/src__core_write_csc.cpp.o -MF scipy/io/_fast_matrix_market/_core.cpython-310-darwin.so.p/src__core_write_csc.cpp.o.d -o scipy/io/_fast_matrix_market/_core.cpython-310-darwin.so.p/src__core_write_csc.cpp.o -c ../scipy/io/_fast_matrix_market/src/_core_write_csc.cpp
```

### Reproducing Code Example

```python
Compile a module with C++17. In some `meson.build`'s `extension` section add:
  override_options: ['cpp_std=c++17'],

Add to environment.yml:
  - clang=11.1.0

export CC=clang-11
export CXX=clang++
python dev.py build
```

### Error message

```shell
C++17 code does not compile
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0.dev0+0.c4bfa2e 1.24.3 sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/include
    lib directory: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH= DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK=
      NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=3
    pc file directory: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/include
    lib directory: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH= DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK=
      NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=3
    pc file directory: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/lib/pkgconfig
    version: 0.3.21
  pybind11:
    detection method: pkgconfig
    include directory: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: clang-11
    linker: ld64
    name: clang
    version: 11.1.0
  c++:
    commands: clang++
    linker: ld64
    name: clang
    version: 11.1.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/bin/arm64-apple-darwin20.0.0-gfortran
    linker: ld64
    name: gcc
    version: 11.3.0
  pythran:
    include directory: ../../../../../../opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/lib/python3.10/site-packages/pythran
    version: 0.12.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /opt/homebrew/Caskroom/miniconda/base/envs/scipy-dev/bin/python3.10
  version: '3.10'
```

**Comment by rgommers** [comment] 2023-06-08 04:50
Thanks for tracking this down @alugowski!

The problem is caused by the conda compiler activation setting `-std=c++14` in `CXXFLAGS`:
```
% echo $CXXFLAGS 
% mamba activate scipy-dev
% echo $CXXFLAGS
-ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -std=c++14 -isystem /Users/rgommers/mambaforge/envs/scipy-dev/include
```
This seems to be yet another case of conda-forge setting too many compile flags. Because it's in the `CXXFLAGS` environment variable, that takes precedence over anything set in `meson.build` files. Luckily though, the problem was fixed upstream already: https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/75. That fix wasn't backported to clang 11.x, but it's gone in 14.x which is the version I get now when I recreate a dev env with `mamba env create -f environment.yml`.

There is no good way to detect this problem I think, but hopefully this issue is easy enough to find for folks running into it. There's nothing left to do, so I will close this issue.

**Closed by rgommers** 2023-06-08 04:50 UTC
Labels: defect
