### ISSUE TITLE
Building from source on Windows Subsystem for Linux (WSL) fails

### ISSUE THREAD

**Issue by scottshambaugh** [scipy/scipy#17338] opened 2022-11-04 03:55 UTC
I'm building scipy from the latest source for the first time, running on Ubuntu in WSL2 on Windows 11. I tried following [the conda guide](https://scipy.github.io/devdocs/dev/contributor/conda_guide.html#conda-guide), but am getting errors when building. Searching around for the error it seems like it might be a unix/dos file ending mismatch, but I'm not sure how to fix it.

Terminal output:
```
(scipy-dev) scott@DESKTOP-M5S4AGS:/mnt/c/Users/Scott/Documents/Documents/Coding/scipy$ python dev.py build
💻  ninja -C /mnt/c/Users/Scott/Documents/Documents/Coding/scipy/build
ninja: Entering directory `/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/build'
[1/1533] Generating 'scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c'.
FAILED: scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c 
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py ../scipy/_lib/_ccallback_c.pyx scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c
/usr/bin/env: ‘python3\r’: No such file or directory
[2/1533] Generating 'scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c'.
FAILED: scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c 
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py ../scipy/_lib/_test_deprecation_call.pyx scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c
/usr/bin/env: ‘python3\r’: No such file or directory
[3/1533] Generating 'scipy/_lib/_test_deprecation_def.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_def.c'.
FAILED: scipy/_lib/_test_deprecation_def.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_def.c 
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py ../scipy/_lib/_test_deprecation_def.pyx scipy/_lib/_test_deprecation_def.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_def.c
/usr/bin/env: ‘python3\r’: No such file or directory
[4/1533] Generating 'scipy/_lib/messagestream.cpython-310-x86_64-linux-gnu.so.p/messagestream.c'.
FAILED: scipy/_lib/messagestream.cpython-310-x86_64-linux-gnu.so.p/messagestream.c 
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py ../scipy/_lib/messagestream.pyx scipy/_lib/messagestream.cpython-310-x86_64-linux-gnu.so.p/messagestream.c
/usr/bin/env: ‘python3\r’: No such file or directory
[6/1533] Generating scipy/generate-version with a custom command
fatal: bad revision '^v1.8.0'
[10/1533] Compiling C object scipy/special/libcephes.a.p/cephes_gamma.c.o
ninja: build stopped: subcommand failed.
Build failed!
```

**Comment by rgommers** [comment] 2022-11-04 11:05
> `/usr/bin/env: ‘python3\r’: No such file or directory`

This seems related to gh-17020. https://github.com/scipy/scipy/issues/17020#issuecomment-1275502707 confirmed that this does work for that user on WSL. @scottshambaugh do you have `python3` as an executable?

**Comment by scottshambaugh** [comment] 2022-11-05 15:05
I'll dig into that issue, but yes I have that as an executable.
```
(scipy-dev) scott@DESKTOP-M5S4AGS:/mnt/c/Users/Scott/Documents/Documents/Coding/scipy$ which python3
/home/scott/anaconda3/envs/scipy-dev/bin/python3
```

**Comment by scottshambaugh** [comment] 2022-11-05 15:15
I'm not super familiar with build systems, but tried to change the shebang in [cythoner.py](https://github.com/tylerjereddy/scipy/commit/2db3440cfd768009847fb355f3da53fc8c562ea3) back to `#!python3` and got "not found" errors. I tried changing it to `#!/home/scott/anaconda3/envs/scipy-dev/bin/ python3`, and got file permission errors that I'm not sure how to interpret given that permissions on my whole scipy directory structure are totally open:
```
(scipy-dev) scott@DESKTOP-M5S4AGS:/mnt/c/Users/Scott/Documents/Documents/Coding/scipy$ python dev.py build
💻  ninja -C /mnt/c/Users/Scott/Documents/Documents/Coding/scipy/build
ninja: Entering directory `/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/build'
[1/1513] Generating 'scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c'.
FAILED: scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c 
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py ../scipy/_lib/_ccallback_c.pyx scipy/_lib/_ccallback_c.cpython-310-x86_64-linux-gnu.so.p/_ccallback_c.c
/bin/sh: 1: /mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py: Permission denied
[2/1513] Generating 'scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c'.
FAILED: scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c 
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py ../scipy/_lib/_test_deprecation_call.pyx scipy/_lib/_test_deprecation_call.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_call.c
/bin/sh: 1: /mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py: Permission denied
[3/1513] Generating 'scipy/_lib/_test_deprecation_def.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_def.c'.
FAILED: scipy/_lib/_test_deprecation_def.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_def.c 
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py ../scipy/_lib/_test_deprecation_def.pyx scipy/_lib/_test_deprecation_def.cpython-310-x86_64-linux-gnu.so.p/_test_deprecation_def.c
/bin/sh: 1: /mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py: Permission denied
[4/1513] Generating 'scipy/_lib/messagestream.cpython-310-x86_64-linux-gnu.so.p/messagestream.c'.
FAILED: scipy/_lib/messagestream.cpython-310-x86_64-linux-gnu.so.p/messagestream.c 
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py ../scipy/_lib/messagestream.pyx scipy/_lib/messagestream.cpython-310-x86_64-linux-gnu.so.p/messagestream.c
/bin/sh: 1: /mnt/c/Users/Scott/Documents/Documents/Coding/scipy/scipy/_build_utils/cythoner.py: Permission denied
[6/1513] Generating scipy/generate-version with a custom command
fatal: bad revision '^v1.8.0'
[10/1513] Compiling C object scipy/special/libcephes.a.p/cephes_owens_t.c.o
ninja: build stopped: subcommand failed.
Build failed!
```

**Comment by rgommers** [comment] 2022-11-09 17:46
Hmm, very odd. I have no idea what is going on there. It would be great if a maintainer who uses WSL could look at this.

**Comment by scottshambaugh** [comment] 2022-11-21 01:01
Tried again after updating meson and the main branch, and am now failing earlier in the build flow, with the following logs. I can't seem to find open_memstream as something to install while googling around.

```Checking for function "open_memstream" : NO ```
```
Compiler stderr:
 /mnt/c/Users/Scott/Documents/Documents/Coding/scipy/build/meson-private/tmpz650tlp4/testfile.c: In function 'main':
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/build/meson-private/tmpz650tlp4/testfile.c:12:14: error: #error "No definition for __builtin_open_memstream found in the prefix"
   12 |             #error "No definition for __builtin_open_memstream found in the prefix"
      |              ^~~~~
/mnt/c/Users/Scott/Documents/Documents/Coding/scipy/build/meson-private/tmpz650tlp4/testfile.c:17:18: error: #error "__builtin_open_memstream not found"
   17 |                 #error "__builtin_open_memstream not found"
      |                  ^~~~~
```

**Comment by rgommers** [comment] 2022-11-21 09:08
That's an optional internal function, it should not fail on that. The snippet you posted above is from `meson-log.txt`, that's only a try-compile step, nothing is wrong yet. Can you post the actual failure from the build log that's visible in the terminal?

**Comment by scottshambaugh** [comment] 2022-11-21 15:45
Ah, looks like I had a clock skew error later on that I hadn't noticed (maybe something to do with not restarting since daylight savings time?), and running `sudo hwclock -s` resolved that. The build failure is now back to the original issue.

**Comment by rgommers** [comment] 2022-11-21 21:55
okay thanks. still not sure what is going on - but it looks like we need a maintainer with WSL to dig into that.

**Comment by JozsefKutas** [comment] 2022-12-26 23:57
I ran into a similar issue when I first tried building scipy using WSL. I think that if you clone in Windows, git may alter line endings depending on the value of the `core.autocrlf` option in your git config. This changes the `python3` in the shebang line of `cythoner.py` to `python3\r`, which will break the build process. You should be able to avoid this by cloning in WSL.

There's more explanation in [this blog post](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/).

**Comment by rgommers** [comment] 2022-12-27 09:58
Thanks @JozsefKutas, that is very helpful!

I will close this as a duplicate of gh-17020 and reopen that, given that it has more discussion.

**Closed by rgommers** 2022-12-27 09:58 UTC
Labels: Build issues
