### ISSUE TITLE
Import Error: cannot import name '_ellipsoid'

### ISSUE THREAD

**Issue by leo247** [scipy/scipy#8847] opened 2018-05-20 09:43 UTC
Not able to import seaborn and the trace back refers to error in scipy. I installed all packages using pip

### Reproducing code example:
```
import seaborn as sns
```

### Error message:
```
ImportError                               Traceback (most recent call last)
<ipython-input-13-8c064911bb40> in <module>()
      2 import numpy; print(numpy.__version__)
      3 import scipy; print(scipy.__version__)
----> 4 import seaborn

C:\Anaconda3\lib\site-packages\seaborn\__init__.py in <module>()
      4 
      5 # Import seaborn objects
----> 6 from .rcmod import *
      7 from .utils import *
      8 from .palettes import *

C:\Anaconda3\lib\site-packages\seaborn\rcmod.py in <module>()
      6 import matplotlib as mpl
      7 
----> 8 from . import palettes, _orig_rc_params
      9 
     10 

C:\Anaconda3\lib\site-packages\seaborn\palettes.py in <module>()
     10 from .external.six.moves import range
     11 
---> 12 from .utils import desaturate, set_hls_values, get_color_cycle
     13 from .xkcd_rgb import xkcd_rgb
     14 from .crayons import crayons

C:\Anaconda3\lib\site-packages\seaborn\utils.py in <module>()
      5 
      6 import numpy as np
----> 7 from scipy import stats
      8 import pandas as pd
      9 import matplotlib as mpl

C:\Anaconda3\lib\site-packages\scipy\stats\__init__.py in <module>()
    343 from __future__ import division, print_function, absolute_import
    344 
--> 345 from .stats import *
    346 from .distributions import *
    347 from .morestats import *

C:\Anaconda3\lib\site-packages\scipy\stats\stats.py in <module>()
    167 from scipy._lib.six import callable, string_types
    168 from scipy._lib._version import NumpyVersion
--> 169 import scipy.special as special
    170 import scipy.linalg as linalg
    171 from . import distributions

C:\Anaconda3\lib\site-packages\scipy\special\__init__.py in <module>()
    646 from .orthogonal import *
    647 from .spfun_stats import multigammaln
--> 648 from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
    649 from .lambertw import lambertw
    650 from ._spherical_bessel import (spherical_jn, spherical_yn, spherical_in,

C:\Anaconda3\lib\site-packages\scipy\special\_ellip_harm.py in <module>()
      5 
      6 from ._ufuncs import _ellip_harm
----> 7 from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
      8 
      9 

ImportError: cannot import name '_ellipsoid'
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
1.14.0
1.0.0
```

**Comment by ilayn** [comment] 2018-05-20 10:06
Your environment seems to have a faulty SciPy installation. Often this happens when two installed versions compete with each other. Make sure you don't have more than one SciPy installed. This problem is related to how conda arranges packages and we don't have much to offer as a solution. 

This is a duplicate of #8040

**Closed by ilayn** 2018-05-20 10:06 UTC
