### ISSUE TITLE
BUG: Eigenvector signs flipped compared to NumPy

### ISSUE THREAD

**Issue by zmitchell** [scipy/scipy#15350] opened 2022-01-03 23:40 UTC
### Describe your issue.

I have an 8x8 symmetric matrix (see the code example) that I need to diagonalize. I have been using NumPy via `eig`, but as part of optimizing my code I decided to call the LAPACK routine directly through SciPy. However, I've discovered that the array of eigenvectors has its sign flipped, mostly. The absolute values of the elements in each eigenvector array match up, but the signs are different depending on the column even after checking that I'm converting between C-ordering and Fortran-ordering (though it's possible I'm not doing this correctly). The eigenvalues are the same (within the precision that matters).

### Reproducing Code Example

```python
import numpy as np
from numpy.linalg import eig
from scipy.linalg.lapack import sgeev


#  8x8 symmetric matrix
mat = np.array(
[1.23173633e+04,-1.05782761e+02,5.37019730e+00,-6.70276976e+00,6.09752131e+00,-1.52399693e+01,-3.03456998e+00,1.44657955e+01,
-1.05782761e+02,1.25887666e+04,3.74389763e+01,9.07318878e+00,2.52209330e+00,1.20760717e+01,7.43583441e+00,1.93305194e+00,
5.37019730e+00,3.74389763e+01,1.20711895e+04,-4.97901192e+01,-1.31220031e+00,-1.04191551e+01,3.82905126e+00,5.58278441e-01,
-6.70276976e+00,9.07318878e+00,-4.97901192e+01,1.22322129e+04,-7.63941879e+01,-1.70483589e+01,-6.27258606e+01,-2.01500845e+00,
6.09752131e+00,2.52209330e+00,-1.31220031e+00,-7.63941879e+01,1.25343633e+04,4.54885712e+01,1.86784089e+00,4.05107403e+00,
-1.52399693e+01,1.20760717e+01,-1.04191551e+01,-1.70483589e+01,4.54885712e+01,1.24763633e+04,3.38840561e+01,-1.18371887e+01,
-3.03456998e+00,7.43583441e+00,3.82905126e+00,-6.27258606e+01,1.86784089e+00,3.38840561e+01,1.24451006e+04,-1.32585564e+01,
1.44657955e+01,1.93305194e+00,5.58278441e-01,-2.01500845e+00,4.05107403e+00,-1.18371887e+01,-1.32585564e+01,1.25974297e+04],
dtype=np.float32).reshape((8,8))


def main():
    np_e_vals, np_e_vecs = eig(mat)
    e_vals_fortran_order, _, _, e_vecs_fortran_order, _ = sgeev(mat)
    sp_e_vals = np.copy(e_vals_fortran_order, order="C")
    sp_e_vecs = np.copy(e_vecs_fortran_order, order="C")
    #breakpoint()  # uncomment to poke around


if __name__ == "__main__":
    main()
```

### Error message

```shell
np_e_vals:
array([12051.7607, 12213.2217, 12281.0225, 12630.8818, 12581.3223, 12600.4268, 12431.1475, 12473.0049], dtype=float32)
sp_e_vals:
array([12051.7734, 12213.2119, 12281.0127, 12630.8877, 12581.3262, 12600.4287, 12431.1494, 12473.0078], dtype=float32)

np_e_vecs:
array([[0.0431, 0.0927, 0.9385, 0.3198, -0.0576, -0.0232, -0.0499, -0.0083],
       [0.0810, 0.0283, 0.3123, -0.9089, 0.1197, 0.2094, -0.0511, -0.0909],
       [-0.9472, -0.2959, 0.0885, -0.0566, -0.0066, 0.0137, -0.0626, -0.0077],
       [-0.2998, 0.8927, -0.0536, 0.0177, 0.2420, 0.0424, 0.2156, -0.0554],
       [-0.0482, 0.2102, -0.0530, -0.0864, -0.8211, -0.0832, -0.1324, -0.4946],
       [-0.0280, -0.0177, 0.0700, -0.1586, -0.4148, -0.1380, 0.6968, 0.5407],
       [-0.0372, 0.2480, -0.0367, -0.0903, -0.1993, -0.1190, -0.6644, 0.6575],
       [-0.0027, 0.0073, -0.0436, 0.1653, -0.1945, 0.9558, 0.0076, 0.1391]], dtype=float32)
sp_e_vecs:
array([[-0.0431, -0.0928, -0.9385, -0.3198, 0.0576, 0.0232, -0.0499, -0.0083],
       [-0.0810, -0.0283, -0.3123, 0.9089, -0.1197, -0.2094, -0.0510, -0.0909],
       [0.9472, 0.2959, -0.0885, 0.0566, 0.0066, -0.0137, -0.0626, -0.0077],
       [0.2998, -0.8927, 0.0537, -0.0177, -0.2420, -0.0425, 0.2156, -0.0554],
       [0.0482, -0.2102, 0.0530, 0.0864, 0.8211, 0.0833, -0.1324, -0.4946],
       [0.0280, 0.0177, -0.0700, 0.1586, 0.4148, 0.1380, 0.6967, 0.5407],
       [0.0372, -0.2480, 0.0367, 0.0903, 0.1993, 0.1190, -0.6644, 0.6574],
       [0.0027, -0.0073, 0.0436, -0.1653, 0.1946, -0.9558, 0.0076, 0.1391]], dtype=float32)
```

### SciPy/NumPy/Python version information

1.7.3 1.21.3 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

**Comment by rkern** [comment] 2022-01-04 00:38
Eigenvectors are determined only up to a sign, so slight differences in the calculation can create sign flips. In this case, note that the eigenvalues are also a little different. If I'm reading the source of `np.linalg.eig()` correctly, it looks like it actually always uses the `float64` variant of the gufunc (by specifying the signature `d->DD`) even if the input is `float32` (it casts the results back to `float32` later). So I think it's using `DGEEV` underneath instead of `SGEEV`. So all of the intermediate values inside the algorithm are actually being done in `float64` arithmetic. That is likely the cause of the detectable difference in the eigenvalues and the sign flips at the same time.

**Comment by mdhaber** [comment] 2022-01-04 00:43
For that reason (both are valid eigenvectors), I don't think this is a bug, so I'll close the issue. Please reopen, @zmitchell, if you still think there is something to be fixed.

**Closed by mdhaber** 2022-01-04 00:43 UTC
Labels: defect

**Comment by zmitchell** [comment] 2022-01-04 17:34
You are correct. When I do all of the calculations in `float64`/`dgeev` it works as expected. Thank you!
