### ISSUE TITLE
ENH: Add support for free threaded python

### ISSUE THREAD

**Issue by rain1** [scipy/scipy#22018] opened 2024-12-07 15:20 UTC
### Is your feature request related to a problem? Please describe.

Starting from python 3.13t there is experimental support for free threading where the global interpreter lock (GIL) is disabled.

While `pip install SciPy` works fine with normal python 3.13 it fails with free threading python.

Steps to reproduce:
1) `python3.13t -m venv venv` - here is important to specifically use `python3.13t` instead of `python` as `python` will generate normal environment, but `python3.13t`  setup free threading environment.
2) `.\venv\Scripts\activate.bat`
3) `pip install SciPy`

```
Collecting SciPy
  Using cached scipy-1.14.1.tar.gz (58.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      + meson setup C:\Users\User\AppData\Local\Temp\pip-install-7v1gk5si\scipy_21e95c57515e4ba799d0bebdad0b3947 C:\Users\User\AppData\Local\Temp\pip-install-7v1gk5si\scipy_21e95c57515e4ba799d0bebdad0b3947\.mesonpy-wb39zov0 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\User\AppData\Local\Temp\pip-install-7v1gk5si\scipy_21e95c57515e4ba799d0bebdad0b3947\.mesonpy-wb39zov0\meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: C:\Users\User\AppData\Local\Temp\pip-install-7v1gk5si\scipy_21e95c57515e4ba799d0bebdad0b3947
      Build dir: C:\Users\User\AppData\Local\Temp\pip-install-7v1gk5si\scipy_21e95c57515e4ba799d0bebdad0b3947\.mesonpy-wb39zov0
      Build type: native build
      Project name: scipy
      Project version: 1.14.1
      Activating VS 17.11.0 Preview 5.0
      C compiler for the host machine: cl (msvc 19.41.34117 "Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34117 for x64")
      C linker for the host machine: link link 14.41.34117.0
      C++ compiler for the host machine: cl (msvc 19.41.34117 "Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34117 for x64")
      C++ linker for the host machine: link link 14.41.34117.0
      Cython compiler for the host machine: cython (cython 3.0.11)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (C:\dir\venv\Scripts\python.exe)
      Run-time dependency python found: YES 3.13
      Program cython found: YES (C:\Users\User\AppData\Local\Temp\pip-build-env-kz4h1ath\overlay\Scripts\cython.EXE)
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: NO
      Compiler for C supports arguments -Wno-conversion: NO
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Library m found: NO
     
      ..\meson.build:84:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang-new'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --help` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --help` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang-new --help` gave "[WinError 2] The system cannot find the file specified"
      Running `flang-new --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang-new -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --help` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --help` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --help` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"
     
      A full log can be found at C:\Users\User\AppData\Local\Temp\pip-install-7v1gk5si\scipy_21e95c57515e4ba799d0bebdad0b3947\.mesonpy-wb39zov0\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Describe the solution you'd like.

I would like to have free threading support added. It would be nice to have it with binaries so that I don't have to compile them myself.

### Describe alternatives you've considered.

I have tried `pip install SciPy --only-binary=:all:` but that ended with `ERROR: No matching distribution found for SciPy`. 

### Additional context (e.g. screenshots, GIFs)

From your website I see that latest SciPy release was in 2024-08-20. Free threading python was released 2024-10-07.

**Comment by tylerjereddy** [comment] 2024-12-07 15:49
Preliminary support is coming in SciPy `1.15.0` with `3.13t` wheels, we'd be happy to get feedback on free-threading support during the release candidate stage that starts next week and will provide `3.13t` pre-release binaries. The draft release notes are at https://github.com/scipy/scipy/pull/21982.

**Comment by lucascolley** [comment] 2024-12-07 16:13
let's close as duplicate of https://github.com/scipy/scipy/issues/20669

**Closed by lucascolley** 2024-12-07 16:13 UTC
Labels: enhancement
