### ISSUE TITLE
BUG: Scipy Sparse slice indexing assignment Bug with zeros 

### ISSUE THREAD

**Issue by m-richards** [scipy/scipy#12819] opened 2020-09-05 03:03 UTC
My issue is about assigning to a subset of a sparse matrix, taking assigned values from another sparse matrix, in particular the case where the other matrix is all zeros. 

#### Reproducing code example:

```python
from scipy.sparse import lil_matrix
from numpy.random import rand, seed
seed(30)
# behaviour as normal
A = lil_matrix((10, 10))
A[0, :2] = rand(2)

B = lil_matrix((10, 10))
B[0, :] = rand(10)
B[0, 0:3] = A[0, 0:3] # at least 1 nonzero works
print(A[0, :3].todense())
print(B[0, :3].todense())

# strange behaviour
B = lil_matrix((10, 10))
B[0, :] = rand(10)
tmp = A[0, 2:4]
B[0, 2:4] = tmp # this is all zero and doesn't change B

print(A[0, 0:4].todense())
print(B[0, 0:4].todense())
```
This code is adapted from the usage information page for scipy.sparse. It is a bit contrived, since here I explicitly know that I am assigning zeros, but in my actual case where I spotted this is, this was a trick to work out.
The code doesn't produce an exception, but it doesn't produce expected behaviour - this is the output:
```
[[0.64414354 0.38074849 0.        ]]
[[0.64414354 0.38074849 0.        ]]
[[0.64414354 0.38074849 0.         0.        ]]
[[0.51817635 0.76685511 0.93385014 0.08970338]]
```
In the first two lines where we had a nonzero element, we have the same thing. In the second two, we would expect that the final two entries in each row would be zero, but they are not.

This issue is only present in the case where the assignment is a slice, not a scalar. As best  I can tell, this is because for the scalar case, the equivalent of ```tmp``` in the above is a numpy float, but in the slice case it's a sparse matrix (lil_matrix in this case)

I had a look with a debugger, following the ```B[0, 2:4] = tmp``` line back, the issue seems to be in ```scipy/sparse/_index.py```
around line 112 where the size is checked, found to be zero since all elements are zero and then no assignment is done. Commenting this check out locally seems to "fix" the problem, but probably has unforeseen consequences.

#### Scipy/Numpy/Python version information:
```
1.5.2 1.19.1 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
```

**Comment by m-richards** [comment] 2020-09-05 06:25
To elaborate on the check done, this is the snippet of code
```
        if isspmatrix(x):
            if i.ndim == 1:
                # Inner indexing, so treat them like row vectors.
                i = i[None]
                j = j[None]
            broadcast_row = x.shape[0] == 1 and i.shape[0] != 1
            broadcast_col = x.shape[1] == 1 and i.shape[1] != 1
            if not ((broadcast_row or x.shape[0] == i.shape[0]) and
                    (broadcast_col or x.shape[1] == i.shape[1])):
                raise ValueError('shape mismatch in assignment')
            if x.size == 0:
                return
```
There is a similar check in the following block, where ```x``` is passed through ```np.asarray(x)``` and the zero size case is checked again. There's obviously a discrepancy here, since the sparse matrix 'size' attribute is the number of nonzeros, but the numpy array size is the dot product of the shape. In either case though, this returning and doing nothing without any sort of warning seems like strange behavior. 

I certainly could be wrong though, I am far from familiar with the code base.

**Comment by WarrenWeckesser** [comment] 2020-09-08 05:39
@m-richards, thanks for reporting the issue and investigating the cause.  This is definitely a bug.

In this simplified example, `B` is a `lil_matrix` with shape `(1, 5)`:
```
In [105]: B = lil_matrix(np.ones((1, 5), dtype=int))                                                

In [106]: B.A                                                                                       
Out[106]: array([[1, 1, 1, 1, 1]])
```
We can use another `lil_matrix` to assign values into `B`, if the values being assigned are not all zero:
```
In [107]: B[0, 2:4] = lil_matrix([[98, 99]])    

In [108]: B.A 
Out[108]: array([[ 1,  1, 98, 99,  1]])
```
But if the values are all zero, the assignment is ignored:
```
In [109]: B[0, 2:4] = lil_matrix([[0, 0]]) 

In [110]: B.A                   
Out[110]: array([[ 1,  1, 98, 99,  1]])
```
As you pointed out, the checks for `x.size == 0` at https://github.com/scipy/scipy/blob/c734dacd61c5962a86ab3cc4bf2891fc94b720a6/scipy/sparse/_index.py#L112 and https://github.com/scipy/scipy/blob/c734dacd61c5962a86ab3cc4bf2891fc94b720a6/scipy/sparse/_index.py#L121 are not correct.  The fix might be as simple as removing those shortcuts; ping @perimosocordiae.

(By the way, I think most folks would agree that the `size` attribute returning the number of nonzero values instead of having the same meaning as the `size` attribute of a regular numpy array is an unfortunate API wart.)

**Comment by perimosocordiae** [comment] 2020-09-08 06:29
Yup, I've also confirmed the bug on my end, and I agree with both Warren's assessment and sentiment about the `.size` attr. A PR will be inbound soon.

**Closed** 2020-09-09 02:12 UTC
Labels: defect, scipy.sparse
