### ISSUE TITLE
Problem with shortest_path

### ISSUE THREAD

**Issue by Skulldron** [scipy/scipy#8905] opened 2018-06-05 10:51 UTC
Hello. 
I am using wntr library which uses SciPy.
While freezing code with cx_Freeze I encountered problem with WNTR and SciPy . While trying to launch application - windows returns traceback:

> Traceback (most recent call last):
> 0 File "C:\DEV\Python\lib\site-packagesch_Freeze\initscripts\_startup_.py", line 14, in run
> 
> module.run()
> 
> File "C:\DEV\Python\lib\site-packages\cx_Freeze\initscripts\ConsoIe.py", line 26, in run
> e\ec(code, m._dict_)
> 
> File "SampleAPP.py", line 18, in < module>
> 
> File "C:\DEV\Python\lib\site-packageszntrLinit_.py", line 1, in < module>
> from wntr import epanet
> 
> File "C\DEV\Python\lib\site- packages\wntr\epanet\_init_.py", line 4, in < module>
> from .io import IoniIe #, BinFiIe, HydFile, RptFiIe
> 
> File "C:\DEV\Python\lib\site-packageszntr\epanet\io.py", line 32, in < module>
> import wntr.network
> 
> File "C\DEV\Python\lib\site- packages\wntr\network\_init_.py", line 6, in < module>
> from .eIements import Junction, Reservoir, Tank, Pipe, Pump, Valve, Pattern, TimeSeries, Demands, Curve, Source
> 
> File "C\DEV\Python\lib\site- packages\wntr\network\elements.py", line 37, in < module>
> from scipy.optimize import fsolve
> 
> File "C\DEV\Python\lib\site- packages\scipy\optimize\_init_.py", line 271, in < module>
> from ._minimize import *
> 
> File "C:\DEV\Python\lib\site-packages\scipy\optimize\_minimize.py", line 21, in < module>
> from scipy.sparse.linalg import LinearOperator
> 
> File "C\DEV\Python\lib\site-packages\scipy\parse\_init_.py", line 241, in < module>
> from . import csgraph
> 
> File "C\DEV\Python\lib\site-packages\scipstparse\csgraphLinit_.py", line 165, in < module>
> from ._shortest_path import shortest_path, floyd_warshall, dijkstraA
> 
> ImportError: cannot import name 'shortest_path'

Converted this traceback from image with ocr so it can contain some typos. 
Anyone else encountered this problem and knows how to solve it? I would be really thankfull for any hinds that could help me make it work. I'm beginning my journey with coding, so big apologies if this issue was already discussed.

![traceback](https://user-images.githubusercontent.com/33962400/40969991-966c27ce-68b9-11e8-85f5-207de173cd6b.png)

I can provide more information if needed.
Im using newest version of wntr, python 3.6.5. 64 bit.

Scipy/Numpy/Python version information:
Scipy: 1.1.0
Numpy: 1.14.3

**Comment by pv** [comment] 2018-06-05 11:55
That's probably problem with cx_Freeze not including necessary files.
You can try asking on cx_Freeze forums for help with that.

**Comment by Skulldron** [comment] 2018-09-29 07:44
@Fehrox 
Hello friend. Yes i made it work. When cx_Freeze copies the 'ckdtree.cp36-win_amd64.pyd' file from the lib into your new build folder (\build\exe.win-amd64-3.6\lib\scipy\spatial), it copies it as 'cKDTree.cp36-win_amd64.pyd'.

Simply changing the capitalization on the file should solve  import problem.

**Comment by Fehrox** [comment] 2018-10-03 01:53
Thanks @Skulldron.

In the end I changed to pyinstaller to produce my build, but hopefully this message will help someone in our position in the future, thanks for posting your solution.

**Comment by ilayn** [comment] 2018-10-03 06:56
Looks like the issue is settled and not strictly a SciPy issue, hence closing.

**Closed by ilayn** 2018-10-03 06:56 UTC
