### ISSUE TITLE
stats.gamma.fit returns nan for alpha, also no input parameter named "a"?

### ISSUE THREAD

**Issue by gbrand-salesforce** [scipy/scipy#6967] opened 2017-01-18 11:43 UTC
I've got a numpy.ndarray of shape (24569,) (also tried with (24569,1)) with samples of random variables (not the distribution)

`fit_alpha, fit_loc, fit_beta=stats.gamma.fit(data)`

results in fit_alpha and fit_loc being nans, while fit_beta = 1

`I've tried to suggest starting parameters by using stats.gamma.fit(data,a=k,loc=0,scale=theta)`
where k = 4/skew^2, theta=variance/mean are the shape and scale parameters respectively.

But I got the following error:
```

/usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.pyc in fit(self, data, *args, **kwds)
   1916         if floc is None:
   1917             # loc is not fixed.  Use the default fit method.
-> 1918             return super(gamma_gen, self).fit(data, *args, **kwds)
   1919 
   1920         # Special case: loc is fixed.

/usr/local/lib/python2.7/dist-packages/scipy/stats/_distn_infrastructure.pyc in fit(self, data, *args, **kwds)
   2126         # by now kwds must be empty, since everybody took what they needed
   2127         if kwds:
-> 2128             raise TypeError("Unknown arguments: %s." % kwds)
   2129 
   2130         vals = optimizer(func, x0, args=(ravel(data),), disp=0)

TypeError: Unknown arguments: {'a': 0.14115690248522836}.

```

after using floc=0 as a parameter (which is not documented anywhere as far as I can tell) I got an exception pointing out that negative values are not allowed in data (I got one negative "error" value in the data) - after fixing this, I got results which made sense... 

The documentation on that fit function is lacking - it also does not mention that the parameters returned are shape, loc, scale, as well as that fa, floc and fscale are not suggestions of initial fit, but are constraints on the fit to keep these values fixed. There appears to be no way to suggest initial parameters.

**Comment by ev-br** [comment] 2017-01-18 12:40
Thanks for the report!  This seems to be a duplicate of https://github.com/scipy/scipy/issues/5362

The issue is that a keyword argument, `a=k`, is not recognized as a starting value (https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L2177).

A workaround is to use the positional argument for the starting value of the shape parameter, `gamma.fit(data, k, loc=0, scale=theta)`. Can you check that it works for you?

**Comment by ev-br** [comment] 2017-01-18 12:56
It would be nice to fix this actially. Note that https://github.com/scipy/scipy/issues/5362 contains a start in this direction, but it needs some more work to detect impossible combinations of arguments, e.g. `gamma.fit(data, 1, a=2)` (is the starting value of `a` 1 or 2? should likely be a TypeError), `gamma.fit(data, a=2, fix_a=3)` (also a TypeError or a ValueError) etc.

Pull requests welcome, I'd say.

**Comment by WarrenWeckesser** [comment] 2017-02-17 21:26
This is the first part of the issue:

> I've got a numpy.ndarray of shape (24569,) (also tried with (24569,1)) with samples of random variables (not the distribution)
>
>fit_alpha, fit_loc, fit_beta=stats.gamma.fit(data)
>
>results in fit_alpha and fit_loc being nans, while fit_beta = 1

Without the actual data, it is hard to know what is happening.  The only way I've been able to reproduce this is to put a `nan` in the input.  E.g.:

```
In [1]: import numpy as np

In [2]: from scipy import stats

In [3]: data = np.random.randn(100)

In [4]: data[0] = np.nan

In [5]: stats.gamma.fit(data)
Out[5]: (nan, nan, 1.0)
```

Can you check if your `data` contains `nan`?  E.g. check if `np.any(np.isnan(data))` is True.

**Comment by mdhaber** [comment] 2021-01-17 23:31
@gbrand-salesforce it sounds like there was difficulty reproducing the first part of this issue (`fit` returning `nan` for alpha), and the rest of the issue is covered in gh-5362. If you can provide data so that we can reproduce `fit` returning `nan`, please re-open! Otherwise, I think it's safe to close this.

**Closed by mdhaber** 2021-01-17 23:31 UTC
Labels: defect, scipy.stats
