### ISSUE TITLE
NaN handling of stats.wilcoxon

### ISSUE THREAD

**Issue by jthermiz** [scipy/scipy#11409] opened 2020-01-24 00:10 UTC
The stats.wilcoxon function has unexpected behavior when passing in an array with nans. Adding nans seems to make the p-values do go down: Why does this happen? The behavior of this function is not described in the documentation. 

#### Reproducing code example:

```
import numpy as np
import scipy.stats as st

x1 = np.array([1,2,3])
x2 = np.array([1,2,3,np.nan])
print(st.wilcoxon(x1))
print(st.wilcoxon(x2))

```

#### Result:

```
WilcoxonResult(statistic=0.0, pvalue=0.10880943004054568)
WilcoxonResult(statistic=0.0, pvalue=0.06788915486182899)
  ...
```

**Comment by chrisb83** [comment] 2020-01-24 21:54
I agree, this is not good. The code produces quite a few warnings though when the input contains nan. The problem is that `stats.rankdata` does not complain about nan:

```
stats.rankdata([2, 1, np.nan, 4])
array([2., 1., 4., 3.])

stats.rankdata([2, 1, np.nan, np.nan, 4])
array([2., 1., 4., 5., 3.])
```

**Comment by mdhaber** [comment] 2022-03-12 05:24
This is fixed in gh-13312.

**Closed by mdhaber** 2022-03-12 05:24 UTC
Labels: defect, scipy.stats, Documentation
