### ISSUE TITLE
Very noisy doc builds after jupyterlite-sphinx integration

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#20277] opened 2024-03-18 15:55 UTC
I just built the docs locally, and there is a ton of new noise after gh-20019. First there was a lot related to fonts and Matplotlib output, and then so much of this caching-related output that it swamped my terminal (couldn't retrieve the fonts/MPL content anymore):
```
[LiteBuildApp] Reading path from disk: 8d1b003b_6495_4026_81c5_67af6e7db1db.ipynb
[LiteBuildApp] Reading path from disk: 8d1b003b_6495_4026_81c5_67af6e7db1db.ipynb
[LiteBuildApp] Reading path from disk: 8d1b003b_6495_4026_81c5_67af6e7db1db.ipynb
.  post_build:federated_extensions:patch
-- post_build:federated_extensions:settings
-- post_build:mimetypes:patch
[LiteBuildApp] Exiting application: jupyter
[jupyterlite-sphinx] JupyterLite build done
build succeeded.
```

I don't see that commented on at all in gh-20019, so opening a new issue. This is with latest `jupyterlite-sphinx` (0.12.0) from conda-forge, and current SciPy `main` branch.

Cc @steppi

**Comment by steppi** [comment] 2024-03-18 15:59
Thanks for the ping @rgommers. I'll try to solve this today.

**Comment by tylerjereddy** [comment] 2024-03-18 16:17
yeah, I've noticed this too

**Comment by steppi** [comment] 2024-03-18 17:27
Part of the problem is that jupyterlite-sphinx hardcodes the logging level in the call to `jupyter lite build` to `DEBUG`.

https://github.com/jupyterlite/jupyterlite-sphinx/blob/09be95849eaf7bba1287fc95e56c49360526ad40/jupyterlite_sphinx/jupyterlite_sphinx.py#L576-L590

Changing this doesn't suppress everything, but it gets rid of a lot of the noise. I'll look into the other stuff. Fortunately I didn't put a hard pin on the jupyterlite-sphinx version, so I can fix this in jupyterlite-sphinx without having to touch things on the SciPy side.

**Comment by steppi** [comment] 2024-03-18 21:04
I've determined that the issue results from 

1. `jupyter lite build` getting a hard coded `--debug` flag in `jupyterlite-sphinx`.
2. `doit` having hardcoded max verbosity in `jupyterlite_core`.

See https://github.com/jupyterlite/jupyterlite-sphinx/issues/149#issuecomment-2004950653.

I want to push for making suppressing this stuff the default so we don't have to make changes in SciPy.

**Comment by steppi** [comment] 2024-03-19 18:26
This has been fixed in jupyterlite-sphinx [0.13.0](https://jupyterlite-sphinx.readthedocs.io/en/latest/changelog.html). See https://github.com/jupyterlite/jupyterlite-sphinx/pull/150. I've confirmed that the noise is suppressed locally.

**Comment by steppi** [comment] 2024-03-19 18:33
I've created a PR to pin the jupyterlite-sphinx version to `>=0.13.0` instead of `>=0.12.0`.

**Comment by tylerjereddy** [comment] 2024-03-19 19:31
I confirmed the verbosity fix locally as well with that new version, and merged the PR bumping the min version, so closing this.

**Comment by steppi** [comment] 2024-03-20 02:07
Reopening, because this only fixed the verbosity by breaking `jupyterlite-sphinx`, causing no compilation to happen. It seems this will require a fix within `jupyterlite` itself.

**Comment by steppi** [comment] 2024-03-20 02:55
I have another fix in the works, https://github.com/jupyterlite/jupyterlite-sphinx/pull/153, but which will require setting a config variable in SciPy's sphinx `conf.py`.

**Comment by rgommers** [comment] 2024-03-20 15:05
A config variable is fine for us. I'd suggest also having reasonable defaults though, because the current level of noise is very far from that. There may be useful content to log, but O(1,000) lines of this should not be default behavior, it's pretty much useless even if you are wanting to debug something:
```
[LiteBuildApp] Reading path from disk: 8d1b003b_6495_4026_81c5_67af6e7db1db.ipynb
```

**Closed** 2024-03-22 15:19 UTC
Labels: Documentation, DX
