### ISSUE TITLE
optimize.linprog test failures on macOS

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#13846] opened 2021-04-12 11:23 UTC
This one I observe locally:
```
__________________________________________ TestLinprogIPSparsePresolve.test_bug_10466 __________________________________________
../scipy/optimize/tests/test_linprog.py:1595: in test_bug_10466
    assert_allclose(res.fun, -8589934560)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=0
E   
E   x and y nan location mismatch:
E    x: array(nan)
E    y: array(-8589934560)
        A_eq       = [[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...], [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...], [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ...], [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, ...], [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, ...], [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...], ...]
        b_eq       = [314572800.0, 419430400.0, 524288000.0, 1006632960.0, 1073741820.0, 1073741820.0, ...]
        c          = [-8.0, -0.0, -8.0, -0.0, -8.0, -0.0, ...]
        o          = {'_sparse_presolve': True, 'autoscale': True, 'sparse': True}
        res        =      con: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
     fun: nan
 message: 'The solution does not sat...float64)
  status: 4
 success: False
       x: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
        self       = <scipy.optimize.tests.test_linprog.TestLinprogIPSparsePresolve object at 0x140ae7130>
        sup        = <numpy.testing._private.utils.suppress_warnings object at 0x140ae7b20>
```

And this one I see on the `scipy-wheels` repo (macOS and Linux on Azure):
```
______________ TestBoundedNelderMead.test_outside_bounds_warning _______________
[gw2] darwin -- Python 3.8.8 /Users/runner/hostedtoolcache/Python/3.8.8/x64/bin/python
../../../../hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/scipy/optimize/tests/test_minimize_constrained.py:738: in test_outside_bounds_warning
    minimize(prob.fun, [-10, 8],
E   Failed: DID NOT RAISE <class 'UserWarning'>
        bounds     = Bounds(array([-inf,   1.]), array([4., 5.]))
        prob       = <scipy.optimize.tests.test_minimize_constrained.Rosenbrock object at 0x123f55670>
        self       = <scipy.optimize.tests.test_minimize_constrained.TestBoundedNelderMead object at 0x123f559d0>
```

The local one just came in with gh-13515 (Cc @AtsushiSakai). The scipy-wheels probably too, but not sure - CI runs have been infrequent.

**Comment by AtsushiSakai** [comment] 2021-04-12 12:46
Thank you for letting me know the test failure. It does not happen in my environment.. My environment is Docker ubuntu on Mac OS. I will try to reproduce it on Mac OS.

**Comment by rgommers** [comment] 2021-04-12 12:50
I suspect the issue is old GCC on `manylinux1`. That may deal with nan/inf differently. If it's not easy to fix, we can just verify after dropping `manylinux1` (hopefully before the next release).

**Comment by rgommers** [comment] 2021-04-12 12:59
Failures silenced in gh-13847.

**Comment by tupui** [comment] 2021-04-12 15:03
Weird also the CI was green before I merged (appart from the usual doc_build).

**Comment by tupui** [comment] 2021-04-12 15:19
I cannot reproduce the bug locally (`1.7.0.dev0+272f7b2 1.20.2 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)`) I am also on macOS BigSur and running in conda.

**Comment by rgommers** [comment] 2021-04-12 18:51
`nan`/`inf` behavior is very often platform and compiler dependent, so that's not very surprising.

**Comment by mdhaber** [comment] 2022-02-02 18:50
@rgommers are you still seeing these, especially `TestLinprogIPSparsePresolve.test_bug_10466`?

**Comment by rgommers** [comment] 2022-02-08 21:46
> @rgommers are you still seeing these, especially `TestLinprogIPSparsePresolve.test_bug_10466`?

That's passing now. Environment has changed in the meantime of course, so not sure if it'll be completely gone for everyone. But maybe worth unskipping the tests and seeing what happens.

**Comment by mdhaber** [comment] 2022-02-08 22:10
Meh I think I'll leave it alone, since it's looking like we'll deprecate the old solvers in gh-15512. I was wondering whether we could close this issue when that merges.

**Comment by rgommers** [comment] 2022-05-20 08:44
This is now also regularly failing in the Azure CI job `prerelease_deps_coverage_64bit_blas` ([example log](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=18222&view=logs&j=7902a2c1-7b88-5b2d-6408-84b88759c642&t=5471a576-12f4-5533-4de4-506800a17112):

```
FAILED scipy/optimize/tests/test_linprog.py::TestLinprogIPSparseCholmod::test_bug_10466
FAILED scipy/optimize/tests/test_linprog.py::TestLinprogIPSparsePresolve::test_bug_10466
```

**Comment by rgommers** [comment] 2022-05-20 13:50
thanks!

**Closed** 2022-05-20 17:54 UTC
Labels: defect, scipy.optimize
