### ISSUE TITLE
MAINT: local `Python.h` lint failures

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21302] opened 2024-08-02 13:58 UTC
As mentioned by Tyler somewhere recently, I can also see

```
Header before Python.h in file scipy/ndimage/src/nd_image.c
Python.h on line 37, other header(s) on line(s) [36]
Python-including header not used before python constructs in file scipy/odr/__odrpack.c
Construct on line 55
Python-including header not used before python constructs in file scipy/special/_gufuncs.cpp
Construct on line 90
Python-including header not used before python constructs in file scipy/special/_special_ufuncs.cpp
Construct on line 825
```

locally. We should investigate why these are occurring locally but not in CI.

**Comment by lucascolley** [comment] 2024-08-09 10:51
I now can't reproduce these.

**Comment by rgommers** [comment] 2024-08-11 11:28
Those files all look fine as far as I can tell. I suggest we close this since it's not actionable. In case it happens again and you can reproduce locally, it'd be good to get more details.

**Closed** 2024-08-11 12:35 UTC
Labels: maintenance
