### ISSUE TITLE
Seg fault when importing torch

### ISSUE THREAD

**Issue by jdavidberger** [scipy/scipy#11237] opened 2019-12-17 16:43 UTC
In the latest release, if you import scipy and then pytorch, it'll segfault. This did not happen in 1.3.3. It started at 1.4.0rc2

#### Reproducing code example:
```
# From a new virtualenv...
(venv) $ pip3 install torch
Collecting torch
  Using cached https://files.pythonhosted.org/packages/f9/34/2107f342d4493b7107a600ee16005b2870b5a0a5a165bdf5c5e7168a16a6/torch-1.3.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting numpy (from torch)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/9b/af/4fc72f9d38e43b092e91e5b8cb9956d25b2e3ff8c75aed95df5569e4734e/numpy-1.17.4-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: numpy, torch
Successfully installed numpy-1.17.4 torch-1.3.1
(venv) $ python3 -c "import scipy;import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
(venv) $ pip3 install scipy
Collecting scipy
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/37/9d/a606dc7b17ef0b7326afd128e132b7a483d5611da603334842df75d92d3c/scipy-1.4.0-cp37-cp37m-manylinux1_x86_64.whl (26.1MB)
    100% |████████████████████████████████| 26.1MB 47kB/s 
Requirement already satisfied: numpy>=1.13.3 in ./venv/lib/python3.7/site-packages (from scipy) (1.17.4)
Installing collected packages: scipy
Successfully installed scipy-1.4.0
(venv) $ python3 -c "import scipy;import torch"
Segmentation fault (core dumped)
```

#### Error message:

Since it's a segfault, I posted the GDB stacktrace here: https://gist.github.com/jdavidberger/b1d9870f4501a16fc4346bda46f98413

#### Scipy/Numpy/Python version information:
```
1.4.0 1.17.4 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment] 2019-12-17 16:46
can you import torch? I don't see how this is related to scipy

**Comment by jdavidberger** [comment] 2019-12-17 16:52
Oops, yes, I failed to mention: Importing torch on it's own is fine; as is importing torch before scipy. 

I can also post an issue on pytorch's issue tracker, but the thing that changed in my dev environment was going from scipy 1.3.3 to 1.4.0. I don't know where the bug is exactly; but I figured since 1.4 is just out it'd be good to post here.

**Comment by ilayn** [comment] 2019-12-17 17:09
The remaining permutation is can you import a standalone scipy? I don't remember any issues and also I can't reproduce it on my installation (other than the 3.8 windows wheel cannot install via pip `ModuleNotFoundError: No module named 'tools.nnwrap'`)

**Comment by jdavidberger** [comment] 2019-12-17 17:18
Yes, importing scipy on its own works.

I suspect there is an issue in some underlying binaries, so it is probably
relevant that I'm seeing this in Linux.

Here is a docker image with the bug:
https://hub.docker.com/repository/registry-1.docker.io/jdavidberger/torchimportbug/tags

**Comment by peterbell10** [comment] 2019-12-17 17:25
This looks similar to a few existing `pytorch` issues I could see. It sounds like there is a binary incompatibility problem between the two different `pybind11` libraries compiled by `pytorch` and `scipy`.

The suggested fix is to compile with a different version of gcc but, if I understand correctly, SciPy's gcc version is fixed by manylinux1 compliance.
Ref: https://github.com/pytorch/pytorch/issues/9129#issuecomment-406063804

**Comment by rgommers** [comment] 2019-12-17 17:28
PEP 513 says that `manylinux1` uses GCC 4.2 - I don't think we're building with that, it's way too old. Unless I'm misreading.

Pybind11 incompatibility definitely makes sense, that is what changed between SciPy 1.3.3 and 1.4.0

**Comment by rgommers** [comment] 2019-12-17 17:30
For the record: workaround is to use `conda`. When you install multiple things with complex C++ like PyTorch and SciPy (and/or Tensorflow, PyArrow, and so on), this kind of thing is not uncommon with `pip`.

**Comment by jklaise** [comment] 2019-12-17 17:31
We are seeing a segfault with `scipy 1.14` in a clean conda environment importing our own library (https://github.com/SeldonIO/alibi/blob/master/setup.py), everything works fine with `1.13`. `scipy` is an indirect dependency so not sure what is going wrong, we don't use `torch` but we do use `tensorflow`.

**Comment by peterbell10** [comment] 2019-12-17 17:32
Similar stack trace is seen in pybind/pybind11#1262. Issue states that pybind11 v2.4 included a possible fix. Do we know what version used in the public wheels?

**Comment by rgommers** [comment] 2019-12-17 17:47
> Similar stack trace is seen in [pybind/pybind11#1262](https://github.com/pybind/pybind11/issues/1262). Issue states that pybind11 v2.4 included a possible fix. Do we know what version is used in the public wheels?

2.3.0, https://travis-ci.org/MacPython/scipy-wheels/jobs/625693851 has `export PYBIND11_BUILD_DEP="pybind11==2.3.0"`

**Comment by rgommers** [comment] 2019-12-17 17:52
Nice find @peterbell10, we should release a 1.4.1 built with pybind11 2.4.0 asap I think, a lot of people are going to hit this problem quickly:(

**Comment by rgommers** [comment] 2019-12-17 18:00
Let's see if our wheel builds are happy with the latest Pybind11: https://github.com/MacPython/scipy-wheels/pull/60

**Comment by peterbell10** [comment] 2019-12-17 23:49
The latest wheel build from [rackcdn.com](https://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/) have fixed the `torch` incompatibility on my machine. Hopefully that extends to other `pybind11` users as well.

**Comment by tylerjereddy** [comment] 2019-12-18 19:49
Attempted wheel builds for SciPy `1.4.1` are underway --- I'll check back on their status later today/tonight to see if I'm able to proceed with release process:

https://travis-ci.org/MacPython/scipy-wheels/builds/626867501
https://ci.appveyor.com/project/scipy/scipy-wheels/builds/29635664

**Comment by andyfaff** [comment] 2019-12-18 20:00
I wonder if we should add a test for this? Identify a popular package made with pybind11 and try to install it at the same time

**Comment by smiles3983** [comment] 2019-12-19 14:22
I am seeing the same issue.  I had to pin the previous version of scipy prior to installing torch.  Interested to see a solution where all I need to do is remove the pinning..

**Comment by loretoparisi** [comment] 2019-12-19 15:53
I'm having the same issue:

```
>>> import transformers
Segmentation fault (core dumped)
```

root@261246f307ae:~/src# python --version
Python 3.6.8

on Ubuntu16.04.

**Comment by tylerjereddy** [comment] 2019-12-19 16:01
The patched wheels are up on PyPI now, so this may help if you use pip:

`pip install scipy==1.4.1`

**Comment by loretoparisi** [comment] 2019-12-19 16:04
@tylerjereddy please wait we have just pinned 1.3.3, now retrying to 1.4.1 💯

**Comment by mihaimaruseac** [comment] 2019-12-19 16:44
Confirmed that `pip install tf-nightly scipy==1.4.1` fixes the TF issues. Thank you

**Comment by tylerjereddy** [comment] 2019-12-19 16:50
Great, I'll close the issue then. Let us know if anything else crops up.

**Closed by tylerjereddy** 2019-12-19 16:50 UTC
Labels: Official binaries, defect
