### ISSUE TITLE
Segfault after modifying csr_matrix.indices and converting to numpy array

### ISSUE THREAD

**Issue by anag004** [scipy/scipy#12131] opened 2020-05-16 10:27 UTC
After modifying the value of the `indices` attribute of a `csr_matrix`, several operations on the matrix produce segfaults. However, other sparse matrix types (`lil_matrix` and `coo_matrix`) do not. Therefore, I suspect this is because CSR matrix compresses the row indices. 

I have not come across any legitimate use case for modifying `indices` directly. Although I have not dug into the source code, perhaps the easiest fix would be to make `indices` read-only from outside the `_cs_matrix` class. 

I would be happy to open a PR if needed. 

#### Reproducing code example:

```
from scipy.sparse import csr_matrix
import numpy as np

a = csr_matrix(np.arange(16).reshape((4, 4)))
b = csr_matrix(np.eye(4))

a.indices = [0] # This should not be allowed

# Each of these lines run individually produce segfaults 

# print(a.toarray()) 
# print(np.sum(a))
# print(a @ b)
```

Note that this is not an exhaustive list of operations. There are likely other operations which segfault as well. 

#### Error message:

This is the backtrace for the first line that segfaults (`print(a.toarray())`)

```
#0  0x00007fffe7a9373c in ?? ()
   from /home/anag004/.local/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so
#1  0x00007fffe7a7e77e in ?? ()
   from /home/anag004/.local/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so
#2  0x000000000050a2bf in ?? ()
#3  0x000000000050bfb4 in _PyEval_EvalFrameDefault ()
#4  0x0000000000507d64 in ?? ()
#5  0x0000000000509a90 in ?? ()
#6  0x000000000050a48d in ?? ()
#7  0x000000000050bfb4 in _PyEval_EvalFrameDefault ()
#8  0x0000000000507d64 in ?? ()
#9  0x000000000050ae13 in PyEval_EvalCode ()
#10 0x0000000000634c82 in ?? ()
#11 0x0000000000634d37 in PyRun_FileExFlags ()
#12 0x00000000006384ef in PyRun_SimpleFileExFlags ()
#13 0x0000000000639091 in Py_Main ()
#14 0x00000000004b0d00 in main ()
```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.4 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```

**Comment by perimosocordiae** [comment] 2020-05-17 21:14
Thanks for filing this issue. Whenever possible we should try to avoid segfaults and raise Python errors instead.

That said, I don't agree that the correct solution here is to make the internal members of sparse matrices readonly. There are many operations which require direct manipulation of this state for performance reasons, and a significant amount of existing code that would break if we limit that access.

I expect that these segfaults are possible to prevent with some low-cost checking before dropping into the native-compiled sparse matrix routines. A PR along those lines would be very much appreciated!

**Comment by perimosocordiae** [comment] 2021-03-01 15:43
Closing as duplicate of gh-8778, please feel free to continue discussion there.

**Closed by perimosocordiae** 2021-03-01 15:43 UTC
Labels: scipy.sparse
