### ISSUE TITLE
Handle NaNs in ndimage.shift

### ISSUE THREAD

**Issue by cracraft** [scipy/scipy#9293] opened 2018-09-20 15:33 UTC
I tried to use scipy.ndimage.interpolation.shift on a combined Hubble image, but because the edges of my input image were NaNs where there were no valid data points, the output image had all pixels set to NaN. I had to put a line in my code to set all NaNs in my input image to 0 before running the shift task.

It would help the users if this task could handle NaNs somewhere in the image without setting all values in the output image to NaN.

The code simply read in an image with fits.open, ran shift, and saved the output image, which displayed as all NaNs.

There was no error printed to screen, so no traceback message to show here, just the behavior of the task. 

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```
>>> print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.14.3 sys.version_info(major=3, minor=5, micro=5, releaselevel='final', serial=0)

By setting the NaNs to 0 in my input image, I was able to get the task to work to my satisfaction, but it would be a serious improvement if the code could properly handle NaNs without needing a work-around.

**Comment by rgommers** [comment] 2019-08-11 02:10
this is by design - NaN's in your input usually indicate something went wrong. this isn't actionable and not specific to `ndimage.shift` (many functions work like this), so closing.

**Closed by rgommers** 2019-08-11 02:10 UTC
Labels: scipy.ndimage

**Comment by cracraft** [comment] 2019-08-12 13:33
Many astronomical images have a few NaNs in locations of bad pixels or edge effects. Those few pixels are considered bad and do not need to be treated. However, the remainder of the image consists of good pixels, and those good pixels should not be set to NaN in the output image. A few bad NaN pixels do not mean the entire image is bad. If marking the entire image bad due to a handful of NaN pixels is by design, then this is basically useless for astronomy.
