### ISSUE TITLE
BUG: stats.mode: failure with array of Pandas integers

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#18254] opened 2023-04-06 16:26 UTC
### Describe your issue.

Another pre-test failure in statsmodels unit testing

https://github.com/scipy/scipy/pull/17561/files#diff-c850dba4f9919cabafa6e3ffbc1d0c61cf315d1e06755a867317fd891f9e2aaaR580
added [()] to results which looks like it breaks if the value is already a scalar

from failing unit test https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=5078&view=logs&j=aabc21e9-9439-578e-0393-ea6ef34c273c&t=3c5b382f-2ffe-594f-225e-664c15c6a882

```
        # `axis`, `nan_policy`, and `keepdims` are handled by `_axis_nan_policy`
    
        if a.size == 0:
            return ModeResult(np.nan, np.int64(0))
    
        vals, cnts = np.unique(a, return_counts=True)
        modes, counts = vals[cnts.argmax()], cnts.max()
>       return ModeResult(modes[()], counts[()])
E       TypeError: 'int' object is not subscriptable
```

This goes from statsmodels through pandas and then scipy.stats

I cannot extract the example (with pdb) because I don't have dev versions installed

### Reproducing Code Example

```python
-
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version and system information

```shell
scipy main
```

**Comment by mdhaber** [comment] 2023-04-06 18:30
It could be the NaNs, which are Python floats instead of NumPy floats. It's fine with NumPy floats:
```python3
import numpy as np
x = np.float64(1)
x[()]
```

So this might have been fixed by gh-18217. Let's see if that does the trick.

**Comment by mdhaber** [comment] 2023-04-06 18:38
It will only break if the value is a Python scalar. 
```python3
import numpy as np
np.float64(1)[()]  # 1.0
```
I'll have to see what is producing a regular int.

**Comment by mdhaber** [comment] 2023-04-09 18:12
In any case, for best results (for now), please convert the input to a NumPy numerical array before calling `stats` functions. Whether `stats` functions currently work seamlessly with pandas arrays is hit or miss, and I'm not aware of a policy that they should, so I'm changing this to an enhancement request.

**Comment by tupui** [comment] 2023-04-10 09:59
I think in general there is a wish to support the array API and use this mechanism as a way to bridge the gap between various arrays and libraries. I think we can close this in favour of this work (I don't know the status here though. Last thing I've seen was #15395)

**Comment by rgommers** [comment] 2023-04-10 22:19
> Whether `stats` functions currently work seamlessly with pandas arrays is hit or miss, and I'm not aware of a policy that they should, so I'm changing this to an enhancement request.

This does not sound quite right to me. @josef-pkt linked to the exact change that introduced a regression. By design, SciPy functions (for better or worse) start with coercing their array-like inputs to an actual `numpy.ndarray` with `np.asarray`. The linked PR removes an `asarray` call, and the `@axis_nan_policy_decorator` decorator does not add it back. So, unless I'm missing something, that is a regression and may also break other things.

> I think in general there is a wish to support the array API and use this mechanism as a way to bridge the gap between various arrays and libraries.

Arrays are a separate topic from pandas series/dataframe and other array-like input. `pandas.Series` instances are not arrays and won't be covered by the work you're referring to.

**Comment by rgommers** [comment] 2023-04-10 22:22
`pd.Series` has a `__array__` attribute, so we consider that array-like and supported - it cannot break like this. So I'm sure enough this is a defect that I changed the labels back.

**Comment by rgommers** [comment] 2023-04-10 22:43
That said, the reproducer is fairly simple but does run into a deprecation warning that for some reason the `statsmodels` CI does not show:

```python
>>> s = pd.array([1, 2, 3], dtype="Int64")
>>> stats.mode(s, keepdims=False)
<ipython-input-15-0431395f3b31>:1: DeprecationWarning: Support for non-numeric arrays has been deprecated as of SciPy 1.9.0 and will be removed in 1.11.0. `pandas.DataFrame.mode` can be used instead, see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html.
  stats.mode(s, keepdims=False)
ModeResult(mode=1, count=1)
```

now is:
```python
>>> s = pd.array([1, 2, 3], dtype="Int64")
>>> stats.mode(s, keepdims=False)
Traceback (most recent call last):
  Cell In[32], line 1
    stats.mode(s, keepdims=False)
  File ~/code/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:521 in axis_nan_policy_wrapper
    res = hypotest_fun_out(*samples, **kwds)
  File ~/code/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_stats_py.py:511 in mode
    return ModeResult(modes[()], counts[()])
TypeError: 'int' object is not subscriptable
```

So there's two separate issues:
1. While pandas series instances are valid input to `scipy.stats` functions, that is only true if those series are backed by numpy arrays with regular numpy dtypes. In this case, `Int64` gets turned into object dtype - that needs fixing in `statsmodels`.
2. It's unclear (to me at least) whether `axis_nan_policy_decorator` is correctly implemented. We have very few tests with custom array-like's, so we can't rely on our test suite; there must be clear coercion to numpy arrays.

**Comment by rgommers** [comment] 2023-04-10 22:53
> `TypeError: 'int' object is not subscriptable`

What would be helpful here in SciPy is to finalize this deprecation:
```
DeprecationWarning: Support for non-numeric arrays has been deprecated as of
SciPy 1.9.0 and will be removed in 1.11.0. 
```
and emit a clear exception for object array input. Here is a test case that doesn't rely on pandas:
```python
>>> class ArrLike():
...     def __init__(self, x):
...         self._x = x
...
...     def __array__(self):
...         return self._x.astype(object)
...
>>> stats.mode(ArrLike(np.arange(3)))
```

**Comment by mdhaber** [comment] 2023-04-11 01:17
@rgommers thank you for your interest in this issue. Here are some responses to your comments.

> This does not sound quite right to me. @josef-pkt linked to the exact change that introduced a regression. By design, SciPy functions (for better or worse) start with coercing their array-like inputs to an actual numpy.ndarray with np.asarray. The linked PR removes an asarray call, and the @axis_nan_policy_decorator decorator does not add it back. So, unless I'm missing something, that is a regression and may also break other things.

One thing that is missing is that the decorator _does_ add back the coercion to a NumPy array. If you execute the [example above](https://github.com/scipy/scipy/issues/18254#issuecomment-1499468361), you will find that `a` is an array by the time it gets into `mode`.

The other thing that's missing is that it was not it's not the addition of the decorator that caused the problem. If you remove the `_axis_nan_policy` decorator and coerce to a NumPy array manually, you get the same error. 

The link provided by @josef-pkt pointed to something else being the problem, but that has not been changed for several years; it just happens to be the place where the error occurs.

The problem was caused by removal of explicit object support at the end of the deprecation period. If the pandas series were coerced to any NumPy data type instead of object, this would not be a problem. I can add a more explicit message, though.

--

When I wrote before:

> Whether stats functions currently work seamlessly with pandas arrays is hit or miss

I should have been more specific.

> Whether stats functions currently work seamlessly with pandas arrays with pandas dtypes is hit or miss.

`stats` is not unusual in having trouble with this input because, as you noted above, it gets converted to an object array. The first functions I tried in `linalg` and `special`, for example, failed with the same sort of input. 

So is the action on SciPy's side to raise a more informative error about the input type?

**Comment by rgommers** [comment] 2023-04-11 09:18
> The problem was caused by removal of special handling of object arrays at the end of the deprecation period.

That makes sense. And yes, an explicit check would be good. That's generically true I think if we deprecate support for some input type - we then have to check and raise a clear error. Also, the exception type has to be stable I'd say. NumPy itself raises `TypeError` mostly (and has a specific `UfuncTypeError` subclass of `TypeError`) for unsupported dtypes, so that seems like the best fit.

> the nice thing is that as we discover more, we only have to treat them in one place. [...] We should add a test with custom array-likes now that this has come up, but as discussed, it's dealing with them correctly in this case.

Agreed, that's a good thing - and adding a specific test should resolve the issue here.

> The enhancement I thought this was prompting was the ability to work on arrays that contain numeric data even if they get converted to object dtype. 

I think that that's not a good way to go. NumPy itself is going to deprecate and remove automatic creation of object arrays when `dtype=object` is not explicitly specified. We should not try to support object arrays in SciPy.

Supporting Pandas data structures is a separate topic from object array support, and also from an "issue logistics" point of view I would start a new issue for that rather than re-title this bug report. Surprisingly, I can't find a tracking issue for pandas (or better, general dataframe) data structure support. This may become feasible - I guess we'll let scikit-learn invent this particular wheel, and maybe we can then copy their way of doing that.

> IIUC, the actions on SciPy's side are to

Yes, that sounds right.

I wanted to do some quick tests of  `_axis_nan_policy_factory` from within IPython, and it failed with a hard to understand `inspect.signature` traceback:


```python
>>> def f(x):
...     x
...
>>> _axis_nan_policy_factory(f)([1])
Traceback (most recent call last):
  Cell In[16], line 1
    _axis_nan_policy_factory(f)([1])
  File ~/code/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:612 in axis_nan_policy_decorator
    sig = inspect.signature(axis_nan_policy_wrapper)
...
ValueError: callable [1] is not supported by signature
```

That led me to look at that factory function closer, and it's using `inspect` quite a bit - which tends to be not a good idea at runtime. Aside from robustness, some benchmarking shows large performance regressions:

```python
>>> import numpy as np
>>> from scipy import stats
>>> z = np.random.randint(10000)
>>> scipy.__version__
'1.10.1'
>>> %timeit stats.mode(z, keepdims=True)
47.9 µs ± 235 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
compared to `main`:
```python
>>> %timeit stats.mode(z, keepdims=True)
229 µs ± 2.45 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

I have not been involved in review of that machinery - I assume some of this was discussed already? My first impression is that the ~250 line implementation of `_axis_nan_policy_factory` looks a bit scary.

> [#18265 (comment)](https://github.com/scipy/scipy/issues/18265#issuecomment-1501187246) also notes that the definition of "array_like" is quite broad (e.g. `scipy.stats` is "array_like", according to the definition) so use of "array_like" in the documentation may need to be qualified.
> 
> I will also look at what stats functions _do_ work with `object` arrays with numerical elements. Is expanding support for this still an enhancement request?

In my opinion, no. I'll comment on gh-18265 instead. For this issue, let's close it once a clear exception is raised. I'll open a new one for the `_axis_nan_policy` issue.

**Comment by rgommers** [comment] 2023-04-11 09:35
On the statsmodels side, this seems fixed already in its `main` branch - see https://github.com/statsmodels/statsmodels/issues/8776.

**Closed** 2023-04-14 07:46 UTC
Labels: defect, scipy.stats, Documentation
