### ISSUE TITLE
optimize: Incorrect size of Jacobian returned by `minimize(..., method='SLSQP')`?

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#6676] opened 2016-10-12 17:23 UTC
This issue was reported on stackoverflow: http://stackoverflow.com/questions/39880436/understanding-the-jacobian-output-of-scipy-optimize-minimize

Here is a simple example:

```
In [8]: from scipy.optimize import minimize

In [9]: def func(x):
   ...:     return (x[0] - 1)**2 + 2*(x[1] - 1)**2 + 0.5*(x[2] - 1)**2
   ...: 

In [10]: minimize(func, [0, 0, 0], method='SLSQP')
Out[10]: 
     fun: 1.9584774719821135e-16
     jac: array([ -4.70504750e-11,  -2.99378300e-11,  -1.30978561e-10,
         0.00000000e+00])
 message: 'Optimization terminated successfully.'
    nfev: 27
     nit: 5
    njev: 5
  status: 0
 success: True
       x: array([ 0.99999999,  0.99999999,  0.99999999])
```
`jac` should have length 3.

This is a development version of scipy:

```
In [11]: import scipy

In [12]: scipy.__version__
Out[12]: '0.19.0.dev0+9efd16a'
```

**Comment by person142** [comment] 2016-10-13 03:54
The issue is here:

https://github.com/scipy/scipy/blob/master/scipy/optimize/slsqp.py#L387

Fix should just require returning `g[:-1]`.

**Comment by andyfaff** [comment] 2016-10-13 04:20
I wonder why slsqp wants g redimensioned to n+1.

**Comment by pv** [comment] 2016-10-13 07:56
That comment should be fixed to say why it does (the answer probably is 
in the fortran source, or it's some quirk of the specific f2py wrapping).

**Closed** 2016-10-20 19:32 UTC
Labels: defect, scipy.optimize
