### ISSUE TITLE
BUG: several failing tests in `interpolate` on macOS15

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#21946] opened 2024-11-25 21:11 UTC
### Describe your issue.

Building against Accelerate and running the test suite on macOS15 gives several fails. Four of these are in `interpolate`, and appear to have been added in ~August in #21167 and #21373.

It's not clear to me if these test fails are originally caused by a problem in Accelerate (#21862), or for different reasons.
 
@j-bowhay would it be possible to look into them?

### Reproducing Code Example

```python
python dev.py build --with-accelerate
python dev.py test
```

### Error message

```shell
_______________________________________________________________________________________________ TestAAA.test_residues ________________________________________________________________________________________________
scipy/interpolate/tests/test_bary_rational.py:196: in test_residues
    assert_allclose(r.residues()[ii], -1 - 1j, atol=1e-15)
        ii         = array([6])
        r          = <scipy.interpolate._bary_rational.AAA object at 0x109818410>
        self       = <scipy.interpolate.tests.test_bary_rational.TestAAA object at 0x10827a990>
        x          = array([-1.33700000e+00, -1.33077425e+00, -1.32454851e+00, -1.31832276e+00,
       -1.31209701e+00, -1.30587127e+00, -1...0,  1.96887127e+00,
        1.97509701e+00,  1.98132276e+00,  1.98754851e+00,  1.99377425e+00,
        2.00000000e+00])
/Users/andrew/miniforge3/envs/dev3/lib/python3.13/contextlib.py:85: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=1e-15
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference among violations: 4.55232929e-06
E   Max relative difference among violations: 3.21898291e-06
E    ACTUAL: array([-0.999997-0.999997j])
E    DESIRED: array(-1.-1.j)
        args       = (<function assert_allclose.<locals>.compare at 0x109818180>, array([-0.99999678-0.99999678j]), array(-1.-1.j))
        func       = <function assert_array_compare at 0x103bc8860>
        kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-07, atol=1e-15', 'strict': False, ...}
        self       = <contextlib._GeneratorContextManager object at 0x1039aa040>
_________________________________________________________________________________________ TestAAA.test_poles_zeros_residues __________________________________________________________________________________________
scipy/interpolate/tests/test_bary_rational.py:223: in test_poles_zeros_residues
    assert_allclose(r.residues().prod(), 10, atol=1e-8)
        f          = <function TestAAA.test_poles_zeros_residues.<locals>.f at 0x109b1bec0>
        r          = <scipy.interpolate._bary_rational.AAA object at 0x109b1bd90>
        self       = <scipy.interpolate.tests.test_bary_rational.TestAAA object at 0x108410c00>
/Users/andrew/miniforge3/envs/dev3/lib/python3.13/contextlib.py:85: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=1e-08
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference among violations: 2.0752338e-05
E   Max relative difference among violations: 2.0752338e-06
E    ACTUAL: array(9.999996+2.038139e-05j)
E    DESIRED: array(10)
        args       = (<function assert_allclose.<locals>.compare at 0x109b1bc40>, array(9.99999609+2.03813876e-05j), array(10))
        func       = <function assert_array_compare at 0x103bc8860>
        kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-07, atol=1e-08', 'strict': False, ...}
        self       = <contextlib._GeneratorContextManager object at 0x1039aa040>
________________________________________________________________________________________________ TestAAA.test_spiral _________________________________________________________________________________________________
scipy/interpolate/tests/test_bary_rational.py:247: in test_spiral
    assert_allclose(np.sort(np.abs(r.poles()))[:4], [1, 1, 3, 3], rtol=9e-7)
        r          = <scipy.interpolate._bary_rational.AAA object at 0x109b48410>
        self       = <scipy.interpolate.tests.test_bary_rational.TestAAA object at 0x108414a00>
        z          = array([ 0.60653066+0.00000000e+00j,  0.60646275+2.86287286e-02j,
        0.60504355+5.72510466e-02j,  0.60227352+8.580...273459 +2.31840580e-01j, -1.63810676+1.55002604e-01j,
       -1.64523961+7.76653108e-02j, -1.64872127+8.88608645e-15j])
/Users/andrew/miniforge3/envs/dev3/lib/python3.13/contextlib.py:85: in inner
    return func(*args, **kwds)
E   AssertionError: 
E   Not equal to tolerance rtol=9e-07, atol=0
E   
E   Mismatched elements: 2 / 4 (50%)
E   Max absolute difference among violations: 2.70837477e-05
E   Max relative difference among violations: 9.02791589e-06
E    ACTUAL: array([1.      , 1.      , 2.999973, 3.000023])
E    DESIRED: array([1, 1, 3, 3])
        args       = (<function assert_allclose.<locals>.compare at 0x109b48220>, array([0.99999993, 1.00000003, 2.99997292, 3.00002326]), array([1, 1, 3, 3]))
        func       = <function assert_array_compare at 0x103bc8860>
        kwds       = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=9e-07, atol=0', 'strict': False, ...}
        self       = <contextlib._GeneratorContextManager object at 0x1039aa040>
____________________________________________________________________________________________ TestAAA.test_spiral_cleanup _____________________________________________________________________________________________
scipy/interpolate/tests/test_bary_rational.py:258: in test_spiral_cleanup
    assert r.clean_up() >= 1
E   assert 0 >= 1
E    +  where 0 = clean_up()
E    +    where clean_up = <scipy.interpolate._bary_rational.AAA object at 0x109b48050>.clean_up
        n_spurious = np.int64(0)
        r          = <scipy.interpolate._bary_rational.AAA object at 0x109b48050>
        self       = <scipy.interpolate.tests.test_bary_rational.TestAAA object at 0x108414320>
        z          = array([ 0.60653066+0.00000000e+00j,  0.60646275+2.86287286e-02j,
        0.60504355+5.72510466e-02j,  0.60227352+8.580...273459 +2.31840580e-01j, -1.63810676+1.55002604e-01j,
       -1.64523961+7.76653108e-02j, -1.64872127+8.88608645e-15j])

During handling of the above exception, another exception occurred:
scipy/interpolate/tests/test_bary_rational.py:257: in test_spiral_cleanup
    with pytest.warns(RuntimeWarning):
E   Failed: DID NOT WARN. No warnings of type (<class 'RuntimeWarning'>,) were emitted.
E    Emitted warnings: [].
        n_spurious = np.int64(0)
        r          = <scipy.interpolate._bary_rational.AAA object at 0x109b48050>
        self       = <scipy.interpolate.tests.test_bary_rational.TestAAA object at 0x108414320>
        z          = array([ 0.60653066+0.00000000e+00j,  0.60646275+2.86287286e-02j,
        0.60504355+5.72510466e-02j,  0.60227352+8.580...273459 +2.31840580e-01j, -1.63810676+1.55002604e-01j,
       -1.64523961+7.76653108e-02j, -1.64872127+8.88608645e-15j])
============================================================================================== short test summary info ===============================================================================================
FAILED scipy/interpolate/tests/test_bary_rational.py::TestAAA::test_residues - AssertionError: 
FAILED scipy/interpolate/tests/test_bary_rational.py::TestAAA::test_poles_zeros_residues - AssertionError: 
FAILED scipy/interpolate/tests/test_bary_rational.py::TestAAA::test_spiral - AssertionError: 
FAILED scipy/interpolate/tests/test_bary_rational.py::TestAAA::test_spiral_cleanup - Failed: DID NOT WARN. No warnings of type (<class 'RuntimeWarning'>,) were emitted.
======================================================================== 4 failed, 1197 passed, 17 skipped, 4 deselected, 1 xfailed in 6.09s ===============================
```

### SciPy/NumPy/Python version and system information

```shell
N/A
```

**Comment by j-bowhay** [comment] 2024-11-25 22:26
Hmm looks like poor accuracy for solving the generalized eigenvalue problem, or less likely the SVD.

**Comment by j-bowhay** [comment] 2024-11-25 22:28
Any known issues with ggev?

**Comment by lucascolley** [comment] 2024-11-25 22:40
https://github.com/scipy/scipy/issues/21862#issuecomment-2467600002 noted problems with gges

**Comment by j-bowhay** [comment] 2024-11-25 23:02
Ok I'm fairly confident that would be the issue

**Comment by j-bowhay** [comment] 2024-11-25 23:17
Actually I misread I think it is ggev that is used but maybe it has a similar issue

**Comment by rgommers** [comment] 2024-11-27 13:57
> It's not clear to me if these test fails are originally caused by a problem in Accelerate (#21862), or for different reasons.

I can confirm that these are due to Accelerate, and the failures are gone in macOS 15.2 beta 4. Given that we understand the issue and are tracking it in gh-21862, let's close this one.

**Comment by rgommers** [comment] 2024-11-27 13:58
The failures are also not too bad, just slightly decreased accuracy.

**Closed by rgommers** 2024-11-27 13:57 UTC
Labels: defect, scipy.interpolate
