### ISSUE TITLE
minimize with LinearConstraint IndexError: boolean index did not match indexed array along dimension 0;

### ISSUE THREAD

**Issue by yl-hz** [scipy/scipy#9970] opened 2019-03-21 07:18 UTC
Hi, I am trying to minimize a function with method('trust-constr') and I construct a linear constraint. But there occurs this error: **"IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 6"**
![image](https://user-images.githubusercontent.com/48391886/54737666-7cebb100-4b87-11e9-9f78-1665f0378681.png)

My code is as follows:
![image](https://user-images.githubusercontent.com/48391886/54737735-aefd1300-4b87-11e9-859c-6cd4f06e0afd.png)
Here is the text version:

```python
from scipy.optimize import SR1
from numpy import np
init_guess = [0.1,0.1,0.1,0.1,0.6] 
a = np.matrix(np.identity(5))
b = np.matrix([1,1,1,1,1])
c = np.concatenate((a, b), axis=0)
lb = [0,0,0,0,0,1]
ub = [1,1,1,1,1,1]
constr = scipy.optimize.LinearConstraint(c, lb, ub, keep_feasible=True)

max_sharpe = scipy.optimize.minimize(neg_sharpe, init_guess, args =(COV, mu, rf),
                                     constraints=[constr], jac="2-point", hess=SR1(),
                                     method='trust-constr',
                                     options={'verbose': 1, 'disp': True, 'maxiter': 10000})
```
I wonder if anyone can help me with this. Thanks a lot!

**Comment by ilayn** [comment] 2019-03-21 08:31
Hi @yl-hz . Could you please post your code as text and not as an image?

**Comment by yl-hz** [comment] 2019-03-21 13:17
> Hi @yl-hz . Could you please post your code as text and not as an image? Also try with your bounds being 2D arrays instead

Sure! I have updated my question! Thanks!

**Comment by yl-hz** [comment] 2019-03-21 13:20
> > Hi @yl-hz . Could you please post your code as text and not as an image? Also try with your bounds being 2D arrays instead
> 
> Sure! I have updated my question! Thanks!

I tried to convert all c, lb and ub into np.array and it works! Thank you so much!!

**Comment by ilayn** [comment] 2019-03-21 14:01
@yl-hz Glad that it works. We can close this then.

@mdhaber @Kai-Striega when you have time could you please check whether we should update the docs or the entrance code such that lists already works? The example is not reproducible but maybe it is a genuine docs issue.

**Closed by ilayn** 2019-03-21 14:01 UTC

**Comment by mdhaber** [comment] 2019-03-21 21:20
@antonior92 Do you have a moment to check this? I think this is more in your domain, since it is about using a `LinearConstraint` object for use with `'trust-constr'`.

**Comment by antonior92** [comment] 2019-03-22 07:41
Hi @ilayn, the problem here is not the use of lists (which works), but rather the use of np.matrix.

The current expected type for `A` is ``A : {array_like, sparse matrix}, shape (m, n)``. Do you think we should change it?

**Comment by ilayn** [comment] 2019-03-22 09:02
Since we are trying to get rid of `numpy.matrix` eventually, I'd vote for not mentioning it. Do you think an explicit `asarray()` needed to conform with `array_like` acceptance spec?

**Comment by antonior92** [comment] 2019-03-22 09:56
We already do some treatment of the matrix ``A``:
```
class LinearVectorFunction(object):
    """Linear vector function and its derivatives.
    Defines a linear function F = A x, where x is n-dimensional vector and
    A is m-by-n matrix. The Jacobian is constant and equals to A. The Hessian
    is identically zero and it is returned as a csr matrix.
    """
    def __init__(self, A, x0, sparse_jacobian):
        if sparse_jacobian or sparse_jacobian is None and sps.issparse(A):
            self.J = sps.csr_matrix(A)
            self.sparse_jacobian = True
        elif sps.issparse(A):
            self.J = A.toarray()
            self.sparse_jacobian = False
        else:
            self.J = np.atleast_2d(A)
            self.sparse_jacobian = False

        self.m, self.n = self.J.shape

        self.x = np.atleast_1d(x0).astype(float)
        self.f = self.J.dot(self.x)
        self.f_updated = True

        self.v = np.zeros(self.m, dtype=float)
        self.H = sps.csr_matrix((self.n, self.n))
```
I sincerely thing it is enought to comply with the specification. What do you think?

**Comment by ilayn** [comment] 2019-03-22 10:08
Same here, I also think it is sufficient. I was just a bit surprised that `np.matrix` doesn't get normalized after `atleast_2d`.

**Comment by antonior92** [comment] 2019-03-22 10:18
> I was just a bit surprised that np.matrix doesn't get normalized after atleast_2d.

Me too :)
