### ISSUE TITLE
BUG: in version 1.10 No matching signature found when trying to use scipy.interpolate.RegularGridInterpolator

### ISSUE THREAD

**Issue by amirone2** [scipy/scipy#17761] opened 2023-01-10 12:35 UTC
### Describe your issue.

with scipy1.10 scipy.interpolate.RegularGridInterpolator object gives the following error message when the __call__ method is used:
 

### Reproducing Code Example

```python
import scipy
import scipy.interpolate
import numpy as np

foo = scipy.interpolate.RegularGridInterpolator(
            [np.arange(4), np.arange(5)],
            np.zeros([4,5],"f"),
            bounds_error=False,
            method="linear",
            fill_value=None,
        )
print( foo(  (0,0)))
print( foo( [ (0,0), (0,0) ]))
print( foo(np.zeros([20,21,2],"f")))
```

### Error message

```shell
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print( foo(  (0,0)))
  File "/tmp/pippo/lib/python3.8/site-packages/scipy/interpolate/_rgi.py", line 336, in __call__
    result = evaluate_linear_2d(self.values,
  File "_rgi_cython.pyx", line 19, in scipy.interpolate._rgi_cython.__pyx_fused_cpdef
TypeError: No matching signature found
```

### SciPy/NumPy/Python version information

1.10.0 1.24.1 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment] 2023-01-10 12:37
Hi @amirone2, thank you for reporting. This is a duplicate of #17718, hence I will close this issue.

**Closed by tupui** 2023-01-10 12:37 UTC
Labels: defect
