### ISSUE TITLE
Negative arguments in scipy.special.mathieu_a yield NaN

### ISSUE THREAD

**Issue by mgely** [scipy/scipy#10316] opened 2019-06-17 13:57 UTC
Entering negative values for the first argument of scipy.special.mathieu_a yields NaN
```
from scipy.special import mathieu_a
mathieu_a(-1,1)
```

Whereas it should be well defined according to Mathematica.
See evaluation of the function at this link:
http://functions.wolfram.com/webMathematica/FunctionPlotting.jsp?name=MathieuCharacteristicA&ptype=1&r=-1&q=2&type=0&line=0&free=q&xMin=-5&xMax=5

### Scipy/Numpy/Python version information:
 1.2.1 1.16.3 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by person142** [comment] 2019-06-17 16:14
Duplicate of https://github.com/scipy/scipy/issues/3075 I believe, so closing in favor of that one.

**Closed by person142** 2019-06-17 16:14 UTC
