### ISSUE TITLE
eigh with subset index sometimes returns no eigenvalues (when top eigenvalues are similar?)

### ISSUE THREAD

**Issue by jameschapman19** [scipy/scipy#13913] opened 2021-04-21 15:43 UTC
My issue is about using scipy.linalg.eigh.

When we use eigh with subset index set to return the k largest eigenvalues, sometimes eigh returns nothing. In particular it seems inconsistent in particular examples such as the one given below. When we ask for the top-1 and top-3 we get the correct eigenvalues but nothing for the top-2.

#### Reproducing code example:

```
from scipy.linalg import eigh
import numpy as np

a = np.array(
    [0.93496897457839744927,0.02252353209815662061,-0.05953165551175491205,0.01489025994825254710,-0.12836839955836318317,-0.04802246266146838194,-0.06886406875564750341,0.04046562569985315966,0.03714156517414783643,-0.01840270452651875804,0.07197525245559413531,
0.02252353209815659979,0.92300109622231607531,-0.10446398043662012689,0.06368964318517553180,0.08081190940668661615,0.03276043172122361513,0.07485362171880013960,-0.02750224638393315019,-0.10909283641841856227,-0.03176972346464808361,0.00163502488118470713,
-0.05953165551175491205,-0.10446398043662009913,0.43689356064293466408,-0.04106527517776534242,0.02664014770883954553,0.09124845509262786980,0.02562290752314816747,-0.01184945912116573338,-0.09351301483316641627,-0.16978156327404037018,0.10678633516502221423,
0.01489025994825254537,0.06368964318517553180,-0.04106527517776532160,0.79151280781075117332,0.07906392851745978889,0.05470555765353874583,-0.00899202233660690436,0.06682515975862708679,0.06991049787262886006,-0.09114607417272743706,-0.05255290100401767417,
-0.12836839955836318317,0.08081190940668663003,0.02664014770883954900,0.07906392851745977501,0.51317613385971905249,0.13369911938120618289,-0.21078674631355023839,-0.00270646289126244251,0.04143438188034744007,0.19613412836894378311,0.26763418534029265183,
-0.04802246266146840276,0.03276043172122358044,0.09124845509262786980,0.05470555765353875971,0.13369911938120621064,0.44124749836332827213,-0.04337796788306534645,0.01830259335537800028,0.28519226959990168213,-0.11805040819010775843,-0.19472560800690397187,
-0.06886406875564751728,0.07485362171880013960,0.02562290752314816747,-0.00899202233660692171,-0.21078674631355029390,-0.04337796788306535339,0.85461910705366384011,-0.04265722515539969312,0.16331372758759191144,0.10808523737411603050,0.06733876708529103194,
0.04046562569985316660,-0.02750224638393311549,-0.01184945912116572644,0.06682515975862707291,-0.00270646289126241259,0.01830259335537801416,-0.04265722515539972087,0.69871970807505956458,0.14911240832667113643,0.25689421976827003791,-0.04791037128627000791,
0.03714156517414782949,-0.10909283641841854839,-0.09351301483316641627,0.06991049787262884618,0.04143438188034744007,0.28519226959990162662,0.16331372758759188368,0.14911240832667116418,0.59163762387054974479,-0.12495295168958074628,0.12285074933595317714,
-0.01840270452651873723,-0.03176972346464800728,-0.16978156327404034243,-0.09114607417272743706,0.19613412836894375535,-0.11805040819010775843,0.10808523737411605825,0.25689421976827003791,-0.12495295168958077403,0.64038391168924624353,-0.04536311088567369920,
0.07197525245559412144,0.00163502488118470604,0.10678633516502224199,-0.05255290100401769499,0.26763418534029276286,-0.19472560800690397187,0.06733876708529097643,-0.04791037128627004954,0.12285074933595314939,-0.04536311088567370614,0.78541651994482397647
]).reshape(11, 11)

[eigvals, eigvecs] = eigh(a, subset_by_index=[10, 10])

print(eigvals)

[eigvals, eigvecs] = eigh(a, subset_by_index=[9, 10])

print(eigvals)

[eigvals, eigvecs] = eigh(a, subset_by_index=[8, 10])

print(eigvals)

[eigvals, eigvecs] = eigh(a)

print(eigvals)
```

```
[1.]
[]
[1. 1. 1.]
[1.55431223e-15 9.35710688e-03 4.22925331e-01 5.03963181e-01
 6.75331324e-01 1.00000000e+00 1.00000000e+00 1.00000000e+00
 1.00000000e+00 1.00000000e+00 1.00000000e+00]
```

#### Scipy/Numpy/Python version information:

```
1.6.1 1.20.1 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment] 2021-04-21 18:06
Hi @jameschapman19 thanks for the report. This is indeed a LAPACK bug and I'm impressed how quickly people started to find these examples once we enabled `subset_by_index` though these routines are decades old. See #13220

LAPACK folks are also a bit confused about this bug and we haven't heard from them yet. For a workaround you can play around with the lower key. I still don't know why but that seems to fix the issue (fingers crossed). I'll pass the example to them

**Comment by jameschapman19** [comment] 2021-04-21 18:19
Thanks for the response and interesting to hear it's a bug at LAPACK level. In my application I should be able to just follow your suggestion (indeed it's what I was already doing as a quick plaster earlier today) and change the lower key if it doesn't return anything as will still be quicker than getting all the eigenvalues.

**Comment by lucascolley** [comment] 2023-12-22 11:46
going to close this as a duplicate of gh-13220 as the example was reported on Reference-LAPACK/lapack#466, please follow those issues if you're still interested in this being resolved 👍

**Closed by lucascolley** 2023-12-22 11:46 UTC
Labels: defect, scipy.linalg, 3rd party binaries
