### ISSUE TITLE
Inaccuracy in special.hyp1f1 function

### ISSUE THREAD

**Issue by jacksonvanover** [scipy/scipy#11085] opened 2019-11-19 01:15 UTC
The scipy implementation of the hyp1f1 function exhibits a huge inaccuracy based on a comparison to mpmath's arbitrary-precision and double-precision implementations (shown below) as well as GSL, all of which agree (GSL gives `1.649746910616242567826e+00`). The input here comes from GSL's included tests.

#### Reproducing code example:

```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpmath import *
>>> from scipy import special
>>> mp.hyp1f1(100, 200, 1.0)
mpf('1.6497469106162459')
>>> fp.hyp1f1(100, 200, 1.0)
1.6497469106162461
>>> special.hyp1f1(100, 200, 1.0)
4.654116242484843e+42
```

#### Scipy/Numpy/Python version information:
1.3.1 1.17.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)

**Comment by peterbell10** [comment] 2019-11-19 02:40
This is a duplicate of gh-5349.

**Closed by peterbell10** 2019-11-19 02:40 UTC
Labels: defect, duplicate, scipy.special
