### ISSUE TITLE
Does scipy has limitation on number of parameters or constraints?

### ISSUE THREAD

**Issue by shiyilin890** [scipy/scipy#8378] opened 2018-02-07 20:45 UTC
I wrote a python code for nonlinear optimization, I have 720 variables and 984 constraints. I run my code but did not get correct results. (It seems that the results I got were all initial values). Is scipy able to handle such large amount of variables and constraints? Thank you

Part of my code are:
from scipy.optimize import minimize
... (objective function, initial guess, boundaries, constraints)
result = minimize(f, toVector(w, z,y,t),method='SLSQP',bounds=bnds,constraints=cons)

**Comment by pv** [comment] 2018-02-07 21:07
Was `result.success == True`?  If it is False, the SLSQP algorithm reported failure to make progress in the solution, in which case you may need to add `minimize(..., options=dict(maxiter=10000))`.

If `result.success` was True, then it would be necessary to understand whether that's an issue in the solver, or some issue with problem specification.

**Comment by shiyilin890** [comment] 2018-02-08 05:38
Thank you for your quick response! I checked, it is false :(
so I added the "options=dict(maxiter=10000)" line and run again (even as less as 1000), still false

result.success==false
message="singular matrix c in lsq subproblem (exit mode 6)"
(For a small number of variables and constraints, like 40, the code works)

**Comment by pv** [comment] 2018-02-08 13:04
The error message looks like the SLSQP algorithm can't easily be made to 
solve the problem --- there's in principle no upper limit to the number 
of conditions, but this may depend on details of the problem. SLSQP is 
fortran code from 1981, so finding out why would require some work (and 
requires to have a fully reproducible test case).

In case you're not using the latest released scipy version, it may be 
worth trying to upgrade since there were some minor fixes. There's also 
a less antique solver in the works in gh-8328, but that probably doesn't 
help you now, so you probaly can look into other dedicated optimization 
packages for Python (ipopt, cvxopt, etc.)

**Comment by josef-pkt** [comment] 2018-02-08 14:23
IIRC, slsqp is sensitive to scaling problems.
One check would be to see how close to singular the jacobian of the function is and whether it can be improved by scaling or reparameterization.

**Comment by brandondube** [comment] 2018-02-08 18:17
@shiyilin890 720 vars and 984 constraints is overconstrained, I don't think you can expect any pseudoinversion or lagrangian-esque optimization algorithm to be successful in that scenario.

**Comment by antonior92** [comment] 2018-02-08 18:24
Some of these constraits may be inequality constraints (that do not need to be active at the solution). In this case it would not be a problem.

**Comment by shiyilin890** [comment] 2018-02-08 18:59
Thank you all! I tried to solve an engineer non-linear optimization problem.
720 variables are from two 24X14 matrices+three 24x1 matrices;
984 constrains are from ten matrices, about half are inequal constrains and half are equal ones.
It would be great if I can use matrices directly, but scipy only takes in scalar functions (not vector functions). So I have to flatten all my matrices and feed into scipy, which end up with a huge number of parameters :(
I am thinking about how to rephrase the problem and maybe split into several parts (so each part will contain less parameters).

@antonior92 Some of these constraits may be inequality constraints (that do not need to be active at the solution), do you mean I can delete some constraints, how to realize this?

**Comment by rkern** [comment] 2018-02-08 19:06
No, he just means that the true solution lies on the boundary of some of the inequality constraints but not others, so it's probably not truly overdetermined (which it would be if you had 984 equality constraints and only 720 variables). Don't delete any constraints.

**Comment by antonior92** [comment] 2018-02-08 19:07
Actually, I don’t think you should delete inactive inequality constraints. My comment was just to explain to @brandondube that your problem was not necessarily ill-conditioned.

Once the optimization problem have been solved (if the solver converge), however, you will be able to check each inequality contraints are active at the solution and each are not. You just need to check for which inequalities constraints the equality does hold

**Comment by ev-br** [comment] 2019-08-08 21:06
This issue does not look actionable, so I'm going to close it. shiyilin890 Can you check with a recent scipy version, using the SLSQP and trust-constr solvers? If the problem persists, please open a new issue with a reproducible example.

**Closed by ev-br** 2019-08-08 21:06 UTC
Labels: query, scipy.optimize
