### ISSUE TITLE
scipy.special.sph_harm gives wrong results

### ISSUE THREAD

**Issue by mzaffalon** [scipy/scipy#5443] opened 2015-10-31 07:05 UTC
I get wrong numerical results (real component is off, imaginary component always near underflow) for `sph_harm` for scipy 0.16.0 that comes with Miniconda3. scipy on Miniconda seems OK.

    Python 3.4.3 |Continuum Analytics, Inc.| (default, Oct 19 2015, 21:52:17) 
    IPython 4.0.0 -- An enhanced Interactive Python.
    In [1]: from scipy.special import sph_harm
    In [2]: sph_harm(2,5,0.2,0.5)
    Out[2]: (0.44798449902914189+3.1149082468549677e-310j)

    Python 2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:50:01) 
    IPython 4.0.0 -- An enhanced Interactive Python.
    In [1]: from scipy.special import sph_harm
    In [2]: sph_harm(2,5,0.2,0.5)
    Out[2]: (0.41262104797366594+0.17445338099189969j)

`conda list` reports for Miniconda3 and Miniconda respectively

    scipy                     0.16.0              np110py34_1 
    scipy                     0.16.0               np19py27_1
(I have not updated the scipy version in a while for Python2.)

**Comment by pv** [comment] 2015-10-31 09:00
duplicate of gh-5376

**Closed by pv** 2015-10-31 09:00 UTC

**Comment by mzaffalon** [comment] 2015-10-31 12:05
Apologies. I even searched the open issues.
