### ISSUE TITLE
Qhull Imprecision

### ISSUE THREAD

**Issue by ketograph** [scipy/scipy#10464] opened 2019-07-15 08:40 UTC
The Qhull library used for the Voronoi diagram calculation has floating number imprecision. If the points differ only 5 digits after the decimal point (e.g. geographic coordinates), only one region is determined.
These imprecisions are already mentioned in the  [Qhull documentation](http://www.qhull.org/html/qh-impre.htm).

Is a note/warning in the documentation appropriate? Maybe with a link to the correct Qhull flag Or could a check be added to get a warning, if there are probably imprecison?

### Reproducing code example:
```
from scipy.spatial import voronoi_plot_2d, Voronoi
import numpy as np
import matplotlib.pyplot as plt

data_x = 40 + np.random.random(50) / 1000
data_y = 10 + np.random.random(50) / 1000
points = list(zip(data_x, data_y))

vor = Voronoi(points)
voronoi_plot_2d(vor)
plt.show()
```

![grafik](https://user-images.githubusercontent.com/15113257/61204212-e4a4a980-a6ec-11e9-895a-e79b40e2af4a.png)

### Scipy/Numpy/Python version information:

```
1.3.0 1.17.0rc1 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by tylerjereddy** [comment] 2019-07-17 03:46
I thought our default Qhull options were pretty good at handling degeneracy scenarios. I was able to reproduce the issue of the assigned 2D Voronoi regions containing multiple generators using the code provided above.

To remedy, I used one of the old school choices--joggled input with: `vor = Voronoi(points, qhull_options='QJ') `. Not sure if that is acceptable for your use case, but the before and after results appear reasonable:

![test](https://user-images.githubusercontent.com/7903078/61345451-75c17080-a812-11e9-86cc-125144f009ed.png)

I think the correct Qhull flag may vary on a case-by-case basis & `QJ` is just one option in the toolbox. The docs do direct the user to Qhull documentation for the options.

**Comment by ketograph** [comment] 2019-07-19 11:12
Thanks for the hint, but apparently my data points are even closer to each other.

```python
from scipy.spatial import voronoi_plot_2d, Voronoi
import numpy as np
import matplotlib.pyplot as plt

data_x = 40 + np.random.random(50) / 10000  # changed
data_y = 10 + np.random.random(50) / 10000  # changed
points = list(zip(data_x, data_y))

vor = Voronoi(points, qhull_options='QJ')
voronoi_plot_2d(vor)
plt.show()
```
 When I then run it with `qhull_options='QJ'`, qhull just quits because of round of errors. 
```
scipy.spatial.qhull.QhullError: QH6229 qhull precision error: 101 attempts to construct a convex hull
        with joggled input.  Increase joggle above 'QJ1e-06'
```

I tried a different joggle `QJ1e-04`, but then no regions are calculated. I tried other combinations too, but that never got me a correct result.

As a workaround for now I just add an offset to all my data points and correct it afterwards:

```python
from scipy.spatial import voronoi_plot_2d, Voronoi
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
data_x = 40 + np.random.random(50) / 10000
data_y = 10 + np.random.random(50) / 10000
points = list(zip(data_x, data_y))


points = np.array(points, dtype=np.float64)
offset = np.mean(points, axis=0)
points_workaround = points - offset

vor = Voronoi(points)
vor_workaround = Voronoi(points_workaround)
f, (ax, ax_workaround) = plt.subplots(1, 2)
voronoi_plot_2d(vor, ax=ax)
voronoi_plot_2d(vor_workaround, ax=ax_workaround)
ax.set_title("uncorrected")
ax_workaround.set_title("workaround using an offset")
plt.show()
```

![qhull](https://user-images.githubusercontent.com/15113257/61531319-cad5d000-aa26-11e9-9c36-db06b9acc8d0.png)

**Comment by pv** [comment] 2019-07-19 11:43
Offsetting points to zero is the right solution, but I don't see a qhull flag for doing that for Voronoi; "QbB" is probably closest, but at least the vertex coordinates are then in the scaled system.

**Comment by pv** [comment] 2019-07-19 11:47
In principle, we might want to change the behavior of scipy.spatial.Voronoi to center points by default (and undo the centering by itself).

**Comment by pv** [comment] 2019-08-08 19:48
duplicate of #6918

**Closed by pv** 2019-08-08 19:48 UTC
Labels: duplicate, scipy.spatial
