### ISSUE TITLE
ValueError on DSBRDB  called by scipy.linalg.eigvalsh

### ISSUE THREAD

**Issue by gauthe** [scipy/scipy#6666] opened 2016-10-09 19:00 UTC
Hello,

I am getting an error with large arrays when using scipy.linalg.eigvalsh:

`>>> import numpy as np`
`>>> from scipy.linalg import eigvalsh`
`>>> eigvalsh(np.zeros((6143,6143)))`
`array([ 0.,  0.,  0., ...,  0.,  0.,  0.])`
`>>> eigvalsh(np.zeros((6144,6144)))`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/users/gauthe/Library/anaconda2/lib/python2.7/site-packages/scipy/linalg/decomp.py", line 684, in eigvalsh`
`    check_finite=check_finite)`
`  File "/users/gauthe/Library/anaconda2/lib/python2.7/site-packages/scipy/linalg/decomp.py", line 345, in eigh`
`    iu=a1.shape[0], overwrite_a=overwrite_a)`
`ValueError: On entry to DSBRDB parameter number 12 had an illegal value`

The issue seems close to #5401, but refers to another LAPACK function. It is a pure effect of size, since 6143 * 6143 is ok, but 6144 * 6144 is not. 6144 = 3 * (2**11) is big, but not that big. I have no problem on my macbook, with an older scipy (0.14.0), I think it's a LAPACK bug.

Version I'm using;
scipy version 0.18.1
numpy version 1.11.1
Python 2.7.12 
Anaconda 4.2.0 (64-bit)
openSUSE 13.2 (Harlequin)

`>>> scipy.__config__.show()`
lapack_opt_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/users/gauthe/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/users/gauthe/anaconda2/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/users/gauthe/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/users/gauthe/anaconda2/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/users/gauthe/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/users/gauthe/anaconda2/include']
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/users/gauthe/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/users/gauthe/anaconda2/include']
mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/users/gauthe/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/users/gauthe/anaconda2/include']

**Comment by rgommers** [comment] 2016-10-22 09:34
Can't reproduce this with ATLAS 3.10.4.

**Comment by pv** [comment] 2016-10-22 10:55
Note that DSBRDB is not called directly by Scipy. Since the parameters Scipy passed to LAPACK are probably fine since they don't trigger a problem at the parameter checks made by the outer routine, this is probably a bug in LAPACK (or in this case, MKL since you are probably using their version of lapack).

If so, there's nothing to change in Scipy and the issue should be reported to MKL authors (possibly after isolating it to a simpler test case.)

**Comment by pv** [comment] 2016-10-22 10:56
Closing (looks like a mkl/lapack bug, not fixable by us + no repro on upstream lapack).

**Closed by pv** 2016-10-22 10:56 UTC
Labels: defect, scipy.linalg
