### ISSUE TITLE
integrate.quad 

### ISSUE THREAD

**Issue by d-v-t** [scipy/scipy#10305] opened 2019-06-14 17:18 UTC
My issue is about ...
Scipy yields a value that's obviously wrong for an integral and says that the error is zero.

### Reproducing code example:
For various applications, integrating a Gaussian/Normal distribution can be invaluable. As I was writing some code to do so, I got a value of zero in a place that it didn't make sense. So after going back and checking the code, I determined that the integral had failed for whatever reason, as I expected the integral of exp(-x**2) from -inf to 38 to be imperceptibly close to sqrt(pi). Instead, the following occurred:

```
import numpy as np
from scipy import integrate

integrate.quad(lambda x: np.exp(-x**2), -np.inf, 38)
```
yields
```
(9.678108002074318e-38, 0.0)
```
Given that the integrand at 38 evaluates to zero, there should be no way that the output should be anything other than sqrt(pi).

With values significantly less than 38, integrate works perfectly. There are also other values for the upper bound that make this integral spit out a blatantly incorrect value and zero error, but I do not remember what those were.

To solve my problem, I know it is possible to simply add 1/2*sqrt(pi) to the integral and integrate from zero, which fixes the problem. However, the fact that it failed in this case makes me question the reliability of the algorithm used.

I looked at issue #3483 and tried converting the bounds to floats, but this did not change the result.

I suspect this has more to do with the algorithm used (I suspect is Simpson quadrature or adaptive Simpson quadrature) than anything else.

### Error message:
No error message.

### Scipy/Numpy/Python version information:
scipy version: 1.3.0
numpy version: 1.16.4
python version 3.7.?

**Comment by ev-br** [comment] 2019-06-14 19:30
Yes, it's an adaptive quadrature, and it gets confused at finite or semi-finite bounds, and misses this tiny bump over a huge integration range and finally decides that the function is effectively zero everywhere.

The issue is though, there is likely no way around it. You simply cannot rely on an adaptive quadrature to find this small part of the integration interval without some help. Either give it all infinite bounds, or split the interval, or change variables.

I'm going to close this since this is not really a bug which we can do something about.

**Closed by ev-br** 2019-06-14 19:30 UTC
Labels: defect, scipy.integrate

**Comment by d-v-t** [comment] 2019-06-28 00:49
I'd be surprised if there isn't a way around it. In MATLAB, the integral() function took the same bounds and same function and returned sqrt(pi).
That being said, I'm not sure how they do this and it may be more work than it's worth at this current juncture. Just thought I'd put this out there.
Also got similar results with 1/(1+x^2), that is MATLAB still solved the problem correctly and integrate.quad failed from -inf to 1e6. This isn't really a surprise, just a test case for if this ever gets looked into deeper.

**Comment by d-v-t** [comment] 2019-06-28 01:00
Okay, after further review, I've determined that MATLAB is significantly better than integrate.quad, but still fails when the bump appears to be too small (~100 for the Gaussian curve).
