### ISSUE TITLE
BUG: segfault on Windows with latest nightly wheels

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#19713] opened 2023-12-19 20:27 UTC
As seen in [many MNE-Python CIs](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=28502&view=logs&jobId=dded70eb-633c-5c42-e995-a7f8d1f99d91&j=dded70eb-633c-5c42-e995-a7f8d1f99d91&t=696f2e49-e3ef-5e19-60e9-ed2e10d75470) starting yesterday (things were okay using nightly wheels on Friday Dec 15 ), locally on Windows I can replicate with:
```
Python 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:23:48) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import faulthandler
>>> faulthandler.enable()
>>> import scipy
>>> import scipy.sparse
Windows fatal exception: access violation

Current thread 0x00000a7c (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
```
Not sure how to debug further. Nothing obviously jumps out to me based on commits in the last few days :(

**Comment by larsoner** [comment] 2023-12-19 20:34
Okay fortunately we print out versions, last one that worked according to MNE-Python CIs [was](https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=28451&view=logs&jobId=dded70eb-633c-5c42-e995-a7f8d1f99d91&j=dded70eb-633c-5c42-e995-a7f8d1f99d91&t=696f2e49-e3ef-5e19-60e9-ed2e10d75470):
```
├☑ numpy                2.0.0.dev0+git20231212.9726755 (OpenBLAS 0.3.23.dev with 2 threads)
├☑ scipy                1.12.0.dev0+1884.1fd74eb
```
and locally where it fails I can see:
```
>>> import scipy
>>> scipy.__version__
'1.12.0.dev0+1884.1fd74eb'
>>> import numpy
>>> numpy.__version__
'2.0.0.dev0+git20231215.08e6252'
```
So I actually wonder if it's a problem with some change in the NumPy version that got installed. Maybe the pip-pre wheel just needs to be recompiled against this newer version or something?

**Comment by andyfaff** [comment] 2023-12-19 20:36
I'm assuming that you're getting the nightly wheels from https://anaconda.org/scientific-python-nightly-wheels/scipy / https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/scipy/.

The last *windows* nightly wheels uploaded to there was 1 month 25 days ago.

**Comment by lucascolley** [comment] 2023-12-19 20:38
Yeah, the commit matches 1fd74ebc2fe61d432c6fa347d8d8c4a2d0d1619f

**Comment by larsoner** [comment] 2023-12-19 21:26
That's correct. Is the advice then *not* to test the nightly wheels, or are they expected to be updated at some point? This would be a bit of a shame since the nightly wheels for other packages do seem available (or at least were a couple of months ago I think), and seems best to test on Windows if possible.

If people shouldn't test them, I wonder if it's possible to yank the wheels from there? Seems like the wheels going away might be better than them staying there unusable with the other nightly wheels.

**Comment by lucascolley** [comment] 2023-12-19 21:30
cc @rgommers who was looking into the failures causing gh-19605.

**Comment by tylerjereddy** [comment] 2023-12-19 21:38
I think we'll get that stuff patched up pretty soon, a lot of the cases you can just cheat and use `np.dtype("long")` to restore the old NumPy behavior for now. It is super annoying to do NumPy `main` + SciPy `main` on Windows though, and Ralf and I got pulled to other stuff I think.

As for deleting the nightly wheels, you can do that with the push of a button if you have the right permissions. I actually can't do that because there was a decision to scope privileges so that no one person had "too much power" if compromised or whatever. I think the folks with permissions may be documented somewhere though.

**Comment by rgommers** [comment] 2023-12-19 22:13
Yeah ... that doesn't make too much sense. There's 10 people with access, with only 3 from SciPy, with me the only one actually likely to actively deal with wheels right now. We should add you to that list @tylerjereddy (If you'd be compromised, we'd have much bigger problems than a few nightlies:)). And we should add @andyfaff as well. Should I put in a request for both of you?

> Is the advice then _not_ to test the nightly wheels _EDIT: on Windows_, or are they expected to be updated at some point?

They should update if we fix the issues, but I'd normally only test nightlies on a single platform (x86-64 Linux). 

Maybe this situation is exceptional though, because at least for debugging towards the end of the numpy 2.0 release cycle, you may need other wheels - building everything you need from source on Windows is quite challenging, SciPy in particular. I'd suggest that the wheels for all other platforms should stay, but preferably not be used in regular CI.

**Comment by rgommers** [comment] 2023-12-19 22:15
Should I delete the Windows ones right now? There's something to say for that either way, since they still work with numpy 1.2x. But if they don't work with 2.0.0.dev0 then yes, probably not helpful right this minute.

**Comment by andyfaff** [comment] 2023-12-19 23:40
@rgommers, yes that would be useful. Happy to use 2FA.

> Should I delete the Windows ones right now?

I would. The usefulness of the nightly wheels is directly related to their freshness.

**Comment by rgommers** [comment] 2023-12-20 11:21
Okay, deleted everything that was 2 months old. The wheels for all platforms except Windows are present and <=4 days old right now.

**Comment by lucascolley** [comment] 2023-12-20 11:25
Since the wheels are no longer available should be okay to close this as a duplicate of gh-19605 now

**Closed** 2023-12-20 11:25 UTC
Labels: Official binaries, duplicate

**Comment by rgommers** [comment] 2023-12-20 11:29
@andyfaff and @tylerjereddy can you share your username for anaconda.org, to request permissions for?

**Comment by tylerjereddy** [comment] 2023-12-20 15:44
username: `treddy`

**Comment by andyfaff** [comment] 2023-12-20 22:03
username: `andyfaff`
