### ISSUE TITLE
Circle CI builds not being triggered by pull requests

### ISSUE THREAD

**Issue by jjhelmus** [scipy/scipy#6839] opened 2016-12-07 20:37 UTC
Recently pull requests no longer seem to trigger a Circle CI build (for example #6836).  We have seem similar behavior in the `conda-forge` repositories and when asked about this were told this was due to a bug fix by Circle CI, conda-forge/status#30.  

Wanted to ping the scipy folks to see if they were aware of this and see if there is a fix.

**Comment by Eric89GXL** [comment] 2016-12-07 21:09
I noticed this problem on some other repos but didn't know the cause. I just switched on permissive mode for SciPy (and some others), hopefully that fixes it. Thanks for the links.

**Comment by jjhelmus** [comment] 2016-12-07 21:33
> I just switched on permissive mode for SciPy (and some others)

Please note that environment variables set in the UI, checkout keys, and other secret data can be leaked by a malicious pull request if this mode is turned on. See the [Circle CI documentation](https://circleci.com/docs/fork-pr-builds/#security-implications-of-running-builds-for-pull-requests-from-forks) on the topic.  This may not be a concern for SciPy.

**Comment by Eric89GXL** [comment] 2016-12-07 21:44
I think we should be okay. @rgommers do you agree? I don't think we do anything special with CircleCI, and the env keys in the UI are empty.

**Comment by pv** [comment] 2016-12-18 22:37
Resolved for us, closing. I don't see security concerns as we're using it only for building+hosting documentation artefacts.

**Closed by pv** 2016-12-18 22:37 UTC
