### ISSUE TITLE
BUG: scipy.sparse.csr_matrix fails with np.float16 since scipy==1.13.0

### ISSUE THREAD

**Issue by kimdwkimdw** [scipy/scipy#20447] opened 2024-04-11 09:09 UTC
### Describe your issue.

scipy.sparse.csr_matrix fails with np.float16 since scipy==1.13.0

### Reproducing Code Example

```python
import numpy as np
import scipy

k = np.random.rand(100,100)
k[::2,::2] = 0
scipy.sparse.csr_matrix(k.astype(np.float16))
```

### Error message

```shell
ValueError: Output dtype not compatible with inputs.
```

### SciPy/NumPy/Python version and system information

```shell
1.13.0 1.26.4 sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0)
```

**Comment by lucascolley** [comment] 2024-04-11 09:29
Duplicate of gh-20200 I think?

**Closed** 2024-04-11 09:32 UTC
Labels: scipy.sparse, duplicate, wontfix
