### ISSUE TITLE
TST: ARM64 test failure for test_two_sided_pvalues1

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#14169] opened 2021-06-02 17:12 UTC
cc: @mdhaber @WarrenWeckesser maybe

Original log of example failure: https://travis-ci.com/github/MacPython/scipy-wheels/jobs/510441882

Pasted text of the failure:

```
=================================== FAILURES ===================================

____________________ TestBinomTest.test_two_sided_pvalues1 _____________________

[gw1] linux -- Python 3.7.10 /venv/bin/python

/venv/lib/python3.7/site-packages/scipy/stats/tests/test_morestats.py:791: in test_two_sided_pvalues1

    assert_allclose(res.pvalue, 0.9966892187965, rtol=rtol)

E   AssertionError: 

E   Not equal to tolerance rtol=1e-13, atol=0

E   

E   Mismatched elements: 1 / 1 (100%)

E   Max absolute difference: 1.49060764e-11

E   Max relative difference: 1.49555911e-11

E    x: array(0.996689)

E    y: array(0.996689)

        res        = BinomTestResult(k=10079990, n=21000000, alternative='two-sided', proportion_estimate=0.4799995238095238, pvalue=0.9966892187815939)

        rtol       = 1e-13

        self       = <scipy.stats.tests.test_morestats.TestBinomTest object at 0xffff9825eed0>
```

**Comment by mdhaber** [comment] 2021-06-02 17:48
@WarrenWeckesser is the author of the new `binomtest`, yes. 

For reference, do you have any suggestions for debugging issues like this that come up before release? Do we know when (after what commit) this failure appeared (e.g. after gh-13433 merged)? Is there a way to interact with the ARM64 instance so we can reproduce the failure?

I see there were similar issues addressed in gh-13838, so presumably this appeared after that merged?

**Comment by tylerjereddy** [comment] 2021-06-02 17:56
I haven't tried to bisect to the first bad commit. Open source devs certainly can get access to Linux ARM64 for interactive testing using the gcc compile farm machines, though if you don't have access it can take a few days to get approved. I could probably test a fix there if provided.

Reducing the dissonance between main repo and wheels repo is probably a long-term solution, but fair bit of work. Switching to something other than Travis CI to avoid the credit-charging situation is going to have to happen for ARM testing (and we do have options like drone I think.. just takes some time & effort).

**Comment by mdhaber** [comment] 2021-06-02 18:08
I see. I will apply for an account for the future, but I will let @WarrenWeckesser debug this one.

**Comment by rgommers** [comment] 2021-06-03 06:11
This just needs a small tolerance bump to `rtol=1e-11`, there's nothing interesting to debug.

**Comment by mdhaber** [comment] 2021-06-03 16:37
A bump is fine for now. My guess is that the search in the second tail is not converging to the same value, and this could be amplifying a tiny numerical difference from the order of machine-precision to something on the order 1e-11. But since `binomtest` has seen a lot of work recently, I'm a lot more confident that gh-14014 is not a (small) bug than I am about this one.

**Comment by WarrenWeckesser** [comment] 2021-06-03 16:50
If we drop the tolerance to 1e-11 in `test_two_sided_pvalues1`, `test_two_sided_pvalues2` and `test_edge_cases`, perhaps we can get rid of those `xfail_on_32bit` decorators, too.  I'll create a PR.

**Comment by mdhaber** [comment] 2021-06-03 17:40
Oh, I didn't realize it already had the decorator. In that case, we had already decided that this sort of thing was OK. Sounds good.

**Closed** 2022-03-15 18:09 UTC
Labels: scipy.stats
