### ISSUE TITLE
Large memory usage when indexing sparse matrices with `np.ix_`

### ISSUE THREAD

**Issue by ivirshup** [scipy/scipy#12173] opened 2020-05-20 06:31 UTC
My issue is about high memory usage when using orthogonal indexing on sparse arrays, dependent on the shape of the indexers.

#### Reproducing code example:
```python
%load_ext memory_profiler
from scipy import sparse
import numpy as np

s = sparse.random(10000, 10000, format="csr")
idx = np.arange(10000)

# This uses a reasonable amount of memory
%memit s[idx.reshape(-1, 1), idx]
# peak memory: 135.93 MiB, increment: 46.52 MiB

# This does not
%memit s[np.ix_(idx, idx)]
# peak memory: 2066.09 MiB, increment: 1930.15 MiB
```

As far as I can tell, the results are exactly the same. Only performance is different.

It looks like this is (at least partially) a known issue (https://github.com/scipy/scipy/issues/12015#issuecomment-625854928).

Initially discovered in https://github.com/theislab/anndata/issues/380

#### Scipy/Numpy/Python version information:

```
# 1.4.1 1.18.4 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
```

**Comment by ewmoore** [comment] 2020-05-20 16:01
This is a duplicate of #11255 and is fixed in master.  

On master: 
```
In [1]: import numpy as np

In [2]: from scipy import sparse

In [3]: %load_ext memory_profiler

In [4]: s = sparse.random(10000, 10000, format='csr')

In [5]: idx = np.arange(10000)

In [6]: %memit s[idx.reshape(-1, 1), idx]
peak memory: 100.10 MiB, increment: 11.83 MiB

In [7]: %memit s[np.ix_(idx, idx)]
peak memory: 100.10 MiB, increment: 0.00 MiB

In [8]: s[idx.reshape(-1, 1), idx] == s[np.ix_(idx, idx)]
/home/ewm/venv/scipy/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3331: SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.
  exec(code_obj, self.user_global_ns, self.user_ns)
Out[8]:
<10000x10000 sparse matrix of type '<class 'numpy.bool_'>'
        with 100000000 stored elements in Compressed Sparse Row format>

In [9]: np.all(_8.data)
Out[9]: True
```
The fix was #11335.

**Closed by ewmoore** 2020-05-20 16:01 UTC
Labels: duplicate, scipy.sparse
