### ISSUE TITLE
how to compute the exact p

### ISSUE THREAD

**Issue by jingydz** [scipy/scipy#20940] opened 2024-06-11 12:12 UTC
import scipy.stats as ss
...
stat, p =ss.ranksums(d1,d2)
      print stat, p

The scipy p-value returns 0.0. But I want to know the true p value, and I have run it again and again, it always returns 0.0.

**Comment by lucascolley** [comment] 2024-06-11 12:16
duplicate of gh-20939

**Closed** 2024-06-11 12:15 UTC
