### ISSUE TITLE
refguide check in CI broken on `svds` example

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18464] opened 2023-05-15 10:17 UTC
Seen on current main in job `ci/circleci: refguide_check`:
```
===================
scipy.sparse.linalg
===================

scipy.sparse.linalg.svds
------------------------

File "build-install/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 280, in svds
Failed example:
    s_a(u2[:, :1], u[:, :1]) + s_a(u2[:, 1:], u[:, 1:]) > 1e-3
Expected:
    True
Got:
    array([False])


File "build-install/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 283, in svds
Failed example:
    (s_a(vT2[:1, :].T, vT[:1, :].T) +
     s_a(vT2[1:, :].T, vT[1:, :].T)) > 1e-3
Expected:
    True
Got:
    array([False])


ERROR: refguide or doctests have errors
```

Both are _potentially_ only marginal tolerance violations, AFAICT.

An old similar issue I found while searching for this: #16900

**Comment by ev-br** [comment] 2023-05-15 12:26
This docstring problematic for long time. Looks like these examples need to be made more robust.

**Comment by rgommers** [comment] 2023-05-15 13:42
This is a duplicate of gh-18381 from 3 weeks ago, so I'll close this issue. It's indeed annoying, I'll try to have a look at it right now.

**Closed by rgommers** 2023-05-15 13:42 UTC
Labels: scipy.sparse.linalg, duplicate, CI

**Comment by h-vetinari** [comment] 2023-05-15 20:57
Sorry about that, not sure how my search didn't find that one.
