### ISSUE TITLE
Scipy build failure in AIX with Python 3.7

### ISSUE THREAD

**Issue by ayappanec** [scipy/scipy#12797] opened 2020-09-01 09:31 UTC
Trying to build the master branch of scipy in AIX with python 3.7 fails with the below error message
```
Traceback (most recent call last):
    File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 590, in <module>
      setup_package()
    File "setup.py", line 586, in setup_package
      setup(**metadata)
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in _install_setup_requires
      dist.parse_config_files(ignore_option_errors=True)
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 665, in parse_config_files
      self._parse_config_files(filenames=filenames)
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 572, in _parse_config_files
      filenames = self.find_config_files()
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 350, in find_config_files
      check_environ()
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 182, in check_environ
      os.environ['PLAT'] = get_platform()
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 107, in get_platform
      return get_host_platform()
    File "/tmp/pip-build-env-9id221km/overlay/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 82, in get_host_platform
      from _aix_support import aix_platform
  ModuleNotFoundError: No module named '_aix_support'
```

Looks like it's a problem with latest setuptools.  _aix_support is added through this changeset https://github.com/python/cpython/commit/39afa2d3147e4b05a1161cc90dbf09b95072c2bb which targets python 3.9

**Comment by rgommers** [comment] 2020-09-01 09:43
Thanks for the report @ayappanec! That's the second issue with `setuptools 0.50.0`. We already had to pin to `<0.50` on Windows as well.

Could you try if `import setuptools` right at the top of SciPy's `setup.py` (above any `disutils` imports) fixes things for you?

**Comment by ayappanec** [comment] 2020-09-01 12:00
> Thanks for the report @ayappanec! That's the second issue with `setuptools 0.50.0`. We already had to pin to `<0.50` on Windows as well.
> 
> Could you try if `import setuptools` right at the top of SciPy's `setup.py` (above any `disutils` imports) fixes things for you?

I tried importing setuptools and it is the same error. I am using "pip install ."

**Comment by rgommers** [comment] 2020-09-01 12:35
Thanks @ayappanec. I found the root cause now (see gh-12798). Can you try setting the `SETUPTOOLS_USE_DISTUTILS` to `stdlib`?

See https://setuptools.readthedocs.io/en/latest/history.html#v50-0-0

**Comment by ayappanec** [comment] 2020-09-01 13:58
> Thanks @ayappanec. I found the root cause now (see [gh-12798](https://github.com/scipy/scipy/pull/12798)). Can you try setting the `SETUPTOOLS_USE_DISTUTILS` to `stdlib`?
> 
> See https://setuptools.readthedocs.io/en/latest/history.html#v50-0-0

Setting SETUPTOOLS_USE_DISTUTILS=stdlib worked.

**Comment by rgommers** [comment] 2021-02-06 19:55
The `setuptools` switch to their vendored copy of `distutils` was reverted in after this bug report was made, but they'll switch back to doing that again soon.

The workaround remains `export SETUPTOOLS_USE_DISTUTILS=stdlib`, or pinning `setuptools` to a version that works. In the `1.6.x` branch we limit to `<= 51.0.0` and that should work. There's not much else we can do here. In master we are leaving `setuptools` unpinned for as long as we can.

I'll close the issue, because aside from pinning `setuptools` sensibly, it is what it is.

**Closed by rgommers** 2021-02-06 19:55 UTC
Labels: Build issues
