### ISSUE TITLE
scipy.optimize maxiter option not working as expected

### ISSUE THREAD

**Issue by nunocalaim** [scipy/scipy#4921] opened 2015-05-29 16:44 UTC
When minimizing a function through scipy.optimize and setting maxiter:n and disp:True as options, the program outputs Iterations: n+1. With no value it runs a maximum of 101 iterations, so I guess the default value is 100. Either there is something wrong with the printing or with computing the number of iterations. 

Either way one would expect that setting maxiter:n, one would see Iterations: i, where i <= n

Thank you for your work, you make my work much easier

**Comment by dlax** [comment] 2015-05-29 18:46
Which "minimizing function" are you referring to exactly?

**Comment by nunocalaim** [comment] 2015-05-29 21:49
This is the actual code, I am solving a quadratic programming problem
```python
def loss(r):
    return (np.dot(r.T, np.dot(H, r)) / 2 + np.dot(c, r) + c0)
def jac(r):
    return np.dot(r.T, H) + c
cons = {'type':'ineq', 'fun':lambda x: b - np.dot(A, x), 'jac':lambda x: -A}
opt = {'disp':True,'maxiter':203}
res_cons = optimize.minimize(loss, x0, jac = jac, constraints = cons, method = 'SLSQP', options = opt, tol = 1e-16)
```

**Comment by argriffing** [comment] 2015-05-29 22:05
Sorry for off-topic, but is `H` positive semi-definite? I think [cvxpy](https://github.com/cvxgrp/cvxpy) is better for these 'structurally convex' problems.

**Comment by nunocalaim** [comment] 2015-05-29 22:09
@argriffing I am actually using the cvxopt package to solve this, I was using the scipy.optimize.minimize to compare results.

**Comment by mdhaber** [comment] 2019-08-08 22:01
Confirmed for `slsqp` and `trust-constr`. Didn't try others.
```
import numpy as np
import scipy.optimize
m, n = 100, 200
np.random.seed(0)
A = np.random.rand(m, n)
b = np.random.rand(m)
c = np.random.rand(n)
x0 = np.random.rand(n)
def loss(r):
    return (np.sum(r))
cons = {'type':'ineq', 'fun':lambda x: b - np.dot(A, x), 'jac':lambda x: -A}
opt = {'disp':True,'maxiter':5}
res_cons = scipy.optimize.minimize(loss, x0, constraints = cons, method = 'trust-constr', options = opt, tol = 1e-16)
```
```
The maximum number of function evaluations is exceeded.
Number of iterations: 6
```
@antonior92 Since you implemented `trust-constr` relatively recently (compared to this issue being posted) and it has the same behavior, I wonder if this was a conscious choice?

**Comment by antonior92** [comment] 2019-08-12 12:40
For `trust-constr`, I think this is happening because it stops when `niter > maxiter`. So it does count the iteration when the optimization process gets interrupted after the counter is increased, hence it exceeds the value by one. I imagine SLSQP have a similar implementation.

I wouldn't say this is a (completely) conscious choice. But I probably looked over this detail to make the implementation more convenient. Nevertheless, I do agree that is a very weird choice, and I agree that it might be a good idea to fix that (even though I think it is a quite low priority issue).

**Comment by mdhaber** [comment] 2019-08-12 20:10
OK, we'll leave this open. Since this will be quite easy to fix for the Python-based solvers, I'm marking it as a good first issue. In addition to solving the off-by-one issue, a unit test should be added to confirm that all the solvers obey the iteration limit.

**Comment by AtsushiSakai** [comment] 2020-02-09 08:14
@mdhaber Hi. This issue cannot be closed by #10780 ?

**Comment by mdhaber** [comment] 2020-02-09 15:56
@AtsushiSakai no, I don't think so because `SLSQP` and `TNC` still don't pass the test.

**Comment by AtsushiSakai** [comment] 2020-02-15 11:23
@mdhaber OK. Thank you so much. I fixed it in #11526

**Closed** 2020-03-25 21:28 UTC
Labels: defect, good first issue, scipy.optimize

**Comment by Jayshah25** [comment] 2022-07-02 08:13
I am facing the same issue. Keeping the `maxiter` to 'n' for methods 'BFGS' and 'Powell', the function yet executes for much more iterations than n.

**Comment by AtsushiSakai** [comment] 2022-07-04 10:42
@Jayshah25 Thank you for reporting. Could you please create an new issue? This issue is for SLSQP. 
Also, if you can provide a self contained code to reproduce your issue, it would be very helpful.
