### ISSUE TITLE
error-in-scipy-wilcoxon-signed-rank-test-for-equal-series

### ISSUE THREAD

**Issue by BLMeltdown** [scipy/scipy#6805] opened 2016-11-22 09:26 UTC
Hello
As presented here:
http://stackoverflow.com/questions/38454893/error-in-scipy-wilcoxon-signed-rank-test-for-equal-series?noredirect=1#comment64315624_38454893
(without no answer to disprove it as a mistake from me),
I wish to report that maybe there is a problem with the results of scipy.wilcoxon signed rank test;

import scipy as sp
x1=[29.39958, 29.21756, 29.350915, 29.34911, 29.212635]
sp.wilcoxon(x1,x1,zero_method="wilcox",correction=True)
returns statistic=0.0, pvalue=nan

But with zero_method="pratt", it returns statistic=0.0, pvalue=0.043114446783075355 instead.
I think there is a mistake there. The statistics (for z-score, if I am not mistaken) are the same, but the results are different for the p-value, while they should not, actually.
When both series are identical, there should be no good p-value, but this is confident with alpha=0.05.

Maybe "pratt" zero_method is wrongly implemented. It is said to be more conservative, but instead it has also constantly given better /lower p-values on a large array of test values.

**edit** josef

It looks like there are two issues
- corner case when all differences are zero needs special handling to return nan p-value
- current implementation of Pratt method is wrong if there are "zeros", if (x == y).sum() > 0

**Comment by josef-pkt** [comment] 2016-11-22 14:15
R package coin raises an exception if diff is zero. I guess we could set the pvalue to nan to match the "wilcox" case, so users still get the zero for the diff instead of an exception.

(Briefly reading the code, I'm not sure whether `r` is empty in "pratt". )

```
> library(coin)
> zz = c(1,2,3,4.5)
> zz2 = c(1,2,3,4.50000001)
> wilcoxsign_test(zz ~ zz2, zero.method="Pratt")

        Asymptotic Wilcoxon-Signed-Rank Test (zeros handled a la Pratt)

data:  y by x (neg, pos)
Z = -1, p-value = 0.3173
alternative hypothesis: true mu is not equal to 0

> wilcoxsign_test(zz ~ zz, zero.method="Pratt")
Error in wilcoxsign_test.IndependenceProblem(object = <S4 object of class "IndependenceProblem">,  : 
  all pairwise differences equal zero
```

I'm not sure about small differences in the two arrays, the pratt version looks a bit strange.

```
>>> stats.wilcoxon(np.array([1,2,3,4.5]), np.array([1,2,3,4.50000001]), zero_method="wilcox", correction=False)
WilcoxonResult(statistic=0.0, pvalue=0.31731050786291415)
>>> stats.wilcoxon(np.array([1,2,3,4.5]), np.array([1,2,3,4.50000001]), zero_method="pratt", correction=False)
WilcoxonResult(statistic=0.0, pvalue=0.06788915486182899)
>>> stats.wilcoxon(np.array([1,2,3,4.5]), np.array([1,2,3,5.0]), zero_method="pratt", correction=False)
WilcoxonResult(statistic=0.0, pvalue=0.06788915486182899)
>>> import scipy
>>> scipy.__version__
'0.17.0'
```

In R pratt and wilcoxon give the same pvalue in the example (?)

```
> wilcoxsign_test(zz ~ zz2, zero.method="Pratt", distribution="asympt")

        Asymptotic Wilcoxon-Signed-Rank Test (zeros handled a la Pratt)

data:  y by x (neg, pos)
Z = -1, p-value = 0.3173
alternative hypothesis: true mu is not equal to 0
```

(R commands taken from here, found by google)
https://stat.ethz.ch/pipermail/r-help/2011-April/274931.html

**Comment by BLMeltdown** [comment] 2016-11-22 14:42
I actually am not well versed enough in R to say whether they made a mistake too, but the behavior seemed more regular than scipy's, hence my report. Sorry that I can't help more (except by doing tests, if you suggest these)

**Comment by josef-pkt** [comment] 2016-11-22 15:15
Based on a quick look, pratt doesn't have unit tests where some values in x and y are identical.

What I find a bit strange in pratt is that the mean `mn` uses count (i.e. number of observations) and not non-identical count len(d[d!=0]).

Also, checking a few more examples with R, scipy agrees if there are no common values, but not if there are common values between x and y.

(bug is starting to look more likely. However, if all d = x - y are zero, then we should just get nans independent of any calculations.)

**Comment by BLMeltdown** [comment] 2016-11-22 15:19
That was more or less what I observed;)

**Comment by josef-pkt** [comment] 2016-11-22 17:21
I think I found the bug, it took me some time to find a reference with the formulas for the normal approximation for the p-values 

https://github.com/scipy/scipy/blob/master/scipy/stats/morestats.py#L2409
both `mn` and `se` need to be adjusted for the zeros. However, because rank are assigned when zeros are still included, it is not just changing `count`

```
if zero_method == "pratt":
    ...
    countz = len(d == 0)
    mn -= countz * (countz + 1.) * 0.25
    se -= countz * (countz + 1.) * (2. * countz + 1.)
```

where countz is the number of zeros

I will add references (they are on another computer)

A PR to verify and change this would be welcome with unit tests against R wilcoxsign_test
(I'm not eager enough to get back on the contributor list with commits to set up scipy for development again : )

**Comment by josef-pkt** [comment] 2016-11-22 17:27
BTW: this issue is a duplicate of #6398 which should be closed 
(I guess I didn't see it or didn't pay attention during vacation)

**Comment by BLMeltdown** [comment] 2016-11-23 08:18
Awesome research;)
Sorry for the duplicate, could not find it before posting...

**Comment by chrisb83** [comment] 2019-03-03 08:34
@josef-pkt could you send me the article by Cureton if you have access? I would like to fix this issue

**Closed** 2019-04-12 21:39 UTC
Labels: defect, scipy.stats
