### ISSUE TITLE
Numerically significant inconsistencies between spsolve and solve

### ISSUE THREAD

**Issue by mitar** [scipy/scipy#6488] opened 2016-08-13 01:04 UTC
I implemented a Python algorithm using `numpy.linalg.solve` and wanted to optimize it with `scipy.sparse.linalg.spsolve`. To my surprise, results are numerically significantly different.

I made a [reproduction](https://github.com/mitar/peer-voting/blob/250a70fc305efcc6a45a4a2addcf8d86069432d4/voting.py). I compute a solution to a linear equations system and then compute an average of the resulting vector. Results are 0.02872638 (solve) vs. 0.027811508380662039 (spsolve). This is pretty scary to me.

**Comment by WarrenWeckesser** [comment] 2016-08-13 02:12
You should also check how well each solution solve the system.  In each case, what is `np.max(np.abs(A.dot(x) - b))`?

**Comment by mitar** [comment] 2016-08-13 02:20
solve: 7.84095011142e-16
spsolve: 1.98742234534

**Comment by WarrenWeckesser** [comment] 2016-08-13 04:55
I tweaked your code a bit so that the loop only ran once, with random seed 123, and with `size = 16`.  In this case, `checkEqual(results)` returns False.  In the `._solve` method of `LinearDelegation` and `SparseLinearDelegation` I added a statement to print `a`, and it turns out that they print different arrays.  So I suspect this is a bug in your code.

If you are sure the problem is not a bug in your code, please pare your example down to the smallest amount of code the produces the problem.  Or find a case that demonstrates the problem, save the arrays `a` and `b` to files, and share the files.  Then we can just load the files and run `solve` and `spsolve` ourselves.

**Comment by mitar** [comment] 2016-08-13 22:48
It seems the reason why `a`s are sometimes different is because in one step before I use least-square algorithm to find a solution needed to set some elements of `a`. I found an example which shows large difference between `numpy.linalg.lstsq` and `scipy.sparse.linalg.lsqr` for the same inputs:

```python
import numpy as np
import scipy.sparse.linalg

np.set_printoptions(precision=20)

a = np.array([[1.0, 0.99999999999890998303, 0.0, 0.0, 0.0], [0.99999999999898536718, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0], [0.75108179735286206835, 0.0, 0.0, 1.0, 0.24891820264586014821], [0.0, 0.0, 0.0, 0.0, 1.0]])
b = np.array([[0.0], [0.0], [1.0], [0.0], [1.0]])

print np.linalg.lstsq(a, b)[0]
print scipy.sparse.linalg.lsqr(scipy.sparse.csr_matrix(a), b)[0].reshape((-1, 1))
```

So it seems the issue is in instability/difference between least-squares.

**Comment by pv** [comment] 2016-08-13 23:27
The solution to least-square problems is not unique. In this case, both
solutions are correct and give the same 2-norm residual.

**Comment by pv** [comment] 2016-08-13 23:33
Closing, please reopen if you find a case where the solutions are not correct.

**Closed by pv** 2016-08-13 23:33 UTC

**Comment by mitar** [comment] 2016-08-13 23:34
Hm hm. Thanks. Will look more into it.
