### ISSUE TITLE
scipy.stats.ks_2samp for masked and unmasked data give different results when no values are masked

### ISSUE THREAD

**Issue by oliverangelil** [scipy/scipy#8341] opened 2018-01-29 05:47 UTC
This is a copy of my[ stackoverflow question](https://stackoverflow.com/questions/48494814/scipy-stats-ks-2samp-for-masked-and-unmasked-data-give-different-results-when-no). 

There are two versions of the scipy.stats.ks_2samp function. [scipy.stats.ks_2samp](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.ks_2samp.html) is the standard version, and [scipy.stats.mstats.ks_2samp](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.stats.mstats.ks_2samp.html) is the version in which "Missing values are discarded". Given distributions in which no entires are missing, the results are different. Why? Code:

### Reproducing code example:
```
import numpy as np
from scipy.stats import ks_2samp
from scipy.stats.mstats import ks_2samp as ks_2sampm

a = np.array([1, 3, 6, 8, 8])
b = np.array([2, 3, 4, 6])

ks_2samp(a, b)# statistic=0.40000000000000002, pvalue=0.75428850089034016
ks_2sampm(a, b) #(statistic=0.39999999999999997, pvalue=0.86916357240334474)
```

Why the different p-values?

### Scipy/Numpy/Python version information:
scipy version is 1.0.0

**Comment by andyfaff** [comment] 2018-01-29 07:04
From a cursory glance the algorithm behind both seems to be different. 
For the default two-sided test (for the masked version), I'm not sure why the masked values aren't just discarded and the normal `ks_2samp` function called.

**Comment by andyfaff** [comment] 2018-01-29 08:21
Using the example from the `stats.ks_2samp` docstring  - the non-masked version is consistent with this [webpage](http://www.physics.csbsju.edu/stats/KS-test.n.plot_form.html), while the masked version is consistent with this [webpage](http://scistatcalc.blogspot.com.au/2013/11/kolmogorov-smirnov-test-calculator.html).

The latter was tested against Octave, it's not clear where the first one arises from. It could be that the first uses scipy behind the scenes.

**Comment by oliverangelil** [comment] 2018-01-29 09:23
> Using the example from the stats.ks_2samp docstring - the non-masked version is consistent with this webpage, while the masked version is consistent with this webpage.

I can confirm that. That's odd. As if there are two different ways to calculate the p-value.

The result using the [kstest2 function](https://au.mathworks.com/help/stats/kstest2.html) in MATLAB (R2016a) is same as the non-masked scipy version and the first website you mention.
statistic=0.4000, pvalue=0.7543

**Comment by andyfaff** [comment] 2018-01-29 10:57
> As if there are two different ways to calculate the p-value.

Actually, there may well be. I found the following:
https://daithiocrualaoich.github.io/kolmogorov_smirnov/
Scroll down to the `Two Sample Test`, and read therein.
Perhaps I'd better stop commenting and wait for the experts to jump in. @josef-pkt

**Comment by josef-pkt** [comment] 2018-01-29 13:49
stats.ks_2samp uses `prob = distributions.kstwobign.sf((en + 0.12 + 0.11 / en) * d)`  (en is already sqrt)
mstats_basic.ks_twosamp uses `prob = special.kolmogorov(np.sqrt(n)*d)`

Neither one has a reference for it.
My guess is that they use different approximation for small samples, if both results show up in other packages

andyfaff's link provides some information, but no reference either. 
(IIRC, the test was initially written my Kolmogorov and then extended by Smirnov or Kolmogorov/Smirnov)

```
>>> x, y = np.random.randn(2, 1000)
>>> stats.ks_2samp(x, y)
Ks_2sampResult(statistic=0.033000000000000029, pvalue=0.64060501846211892)
>>> stats.mstats.ks_twosamp(x, y)
(0.033000000000000022, 0.64755728777074251)

>>> x, y = np.random.randn(2, 50000)
>>> stats.ks_2samp(x, y)
Ks_2sampResult(statistic=0.0037800000000000056, pvalue=0.86675347822793614)
>>> stats.mstats.ks_twosamp(x, y)
(0.0037800000000000086, 0.86735222763245623)

>>> stats.ks_2samp(x, y+0.05)
Ks_2sampResult(statistic=0.021060000000000079, pvalue=4.5219755347520314e-10)
>>> stats.mstats.ks_twosamp(x, y+0.05)
(0.021059999999999478, 4.6777541417251546e-10)
```

**Comment by josef-pkt** [comment] 2018-01-29 16:54
I don't find a reference for the adjustment factor in the stats version, which andyfaffs link attributes to Numerical Recipes
the mstats version seems to be standard Smirnov, and shows up in text books, assuming special.kolmogorov is computes the expression with the infinite sum of exp.

(Stephens has several articles that were using different sample size corrections for the gof tests, but I don't find those references anymore given that I haven't looked at this in years. One of Stephens main summary article is in a book, I have a copy/pdf of the chapter somewhere.)

It would be possible to add a keyword argument to choose the correction, but even better would be to add the exact distribution for smaller samples and then add a more general keyword.

**Comment by oliverangelil** [comment] 2018-02-01 01:09
I think at least the default use of both functions should yield the same p-value; whichever p-value calculation we go for. But I'll trust your judgement...

**Comment by andyfaff** [comment] 2018-02-01 01:15
> I think at least the default use of both functions should yield the same p-value; whichever p-value calculation we go for.

That seems reasonable. It should at least be documented, with preferably a citation.

**Comment by josef-pkt** [comment] 2018-02-01 16:12
The correction in the stats version `D(sqrt(n) + 0.12 + 0.11/sqrt(n))` is in the first reference on the Wikipedia page
Stephens, M. A. (1974). "EDF Statistics for Goodness of Fit and Some Comparisons". Journal of the American Statistical Association. American Statistical Association. 69 (347): 730–737. doi:10.2307/2286009. JSTOR 2286009.
(I didn't manage to find the book chapter of Stephens which was written later.)

In Stephens 1974 it is for the one-sample KS test against a known distribution. The is the same except for the different definition of `n` as used in both ks 2sample functions.

So if pvalues are made consistent, then I think the stats version with the above correction is better.

**Comment by josef-pkt** [comment] 2018-02-01 21:38
Just another reference:
I managed to get the book D'Agostini and Stephens but it is also one for one-sample ks_test.
It has a similar table of modification as Stephens 1974, but attributes it to an earlier articles which is also only for one-sample

Stephens, Michael A. "Use of the Kolmogorov-Smirnov, Cramér-Von Mises and related statistics without extensive tables." Journal of the Royal Statistical Society. Series B (Methodological) (1970): 115-122.

As cross-check, the critical values in Stephens 1970 for KS are the same as `stats.kstwobign.isf([0.15, 0.1, 0.05, 0.025, 0.01])` at 3 decimal print precision.

**Comment by chrisb83** [comment] 2018-06-23 19:01
I did a few simple checks aginst the R implementation `ks.test`. The `mstat` version seems to coincide with the R version that is based on asymptotics (`exact = FALSE`). 

The values of `stats.ks_2sample` cannot be reproduced if `exact = TRUE`

Same values as above (probably not a good test case since there are ties):
```
x <- c(1, 3, 6, 8, 8)
y <- c(2, 3, 4, 6)
ks.test(x, y, "two.sided", exact = FALSE) # p=0.8692
ks.test(x, y, "two.sided", exact = TRUE) # warns about ties, p as above
```

More examples:
```
x <- c(0.1, 0.2, 0.3, 0.4, 0.5)
y <- c(0.25, 3, 1, 0.7)
ks.test(x, y, "two.sided", exact = FALSE) # p=0.1641
ks.test(x, y, "two.sided", exact = TRUE) # p=0.1429
```
vs.

```
x = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
y = np.array([0.25, 3, 1, 0.7])
ks_2samp(x, y) # p=0.0822
ks_2sampm(x, y) # p=0.1641
```
and 
```
x <- 1:20
y <- x - 7.1
ks.test(x, y, "two.sided", exact = FALSE) # p=0.0815
ks.test(x, y, "two.sided", exact = TRUE) # p=0.0811
```
vs
```
x = np.arange(1, 21)
y = x - 7.1
ks_2samp(x, y) # p=0.0591
ks_2sampm(x, y) # p=0.081
```

**Comment by josef-pkt** [comment] 2018-06-23 20:06
@chrisb83 
Can you do a brief monte carlo simulation to see the empirical size, rejection rate under the null for the two version, or if possible including R's "exact" values.
e,g, sample sizes 5, 10 20 30 and uniform and gaussian, which both won't have ties.

**Comment by MarvinT** [comment] 2018-06-27 21:20
Wanted to see if the p values converge at higher number of samples but that doesn't seem to be the case:

![scipy](https://user-images.githubusercontent.com/1386198/42000250-f8015ee8-7a14-11e8-9063-85f8958bb518.png)

code:
```
%matplotlib inline
import scipy as sp
import numpy as np
import matplotlib.pylab as plt

samp_sizes = np.arange(5, 1000)
rolls_per_size = 10
idx = 0
data = np.zeros((2, len(samp_sizes) * rolls_per_size))
data_samp_size = np.zeros(len(samp_sizes) * rolls_per_size)
for samp_size in samp_sizes:
    for i in xrange(rolls_per_size):
        x1 = [random.randint(0, 10) for j in xrange(samp_size)]
        x2 = [random.randrange(0, 10, 2) for j in xrange(samp_size)]
        data[0, idx] = sp.stats.mstats.ks_twosamp(x1, x2, alternative='two-sided')[1]
        data[1, idx] = sp.stats.ks_2samp(x1, x2)[1]
        data_samp_size[idx] = samp_size
        idx += 1

plt.plot(data_samp_size, data[1,:] / data[0, :], '.')
plt.xlabel('sample size')
plt.ylabel('ks_2samp pval / mstats.ks_twosamp pval')
```

**Comment by josef-pkt** [comment] 2018-06-27 22:00
@MarvinT 
This looks to me it's mostly about tie handling or tie breaking if you use integer random numbers.
To check p-values it would be better to use a continuous distribution

**Comment by MarvinT** [comment] 2018-06-28 11:05
well if you replace the lines with 
```
x1 = [random.normalvariate(0, 1) for j in xrange(samp_size)]
x2 = [random.normalvariate(0, 2) for j in xrange(samp_size)]
```
you get 

![scipy](https://user-images.githubusercontent.com/1386198/42030616-3ee22374-7a88-11e8-970c-fbcea9b91eaa.png)

and a joint plot for good measure:

![scipy_joint](https://user-images.githubusercontent.com/1386198/42030628-4beafba4-7a88-11e8-8902-01a0c9a42c9e.png)

The statistic results are all the same up to an epsilon so its just the mapping from the statistic to the p value.

**Comment by josef-pkt** [comment] 2018-06-28 13:00
One more:
you are simulating under the alternative, the distribution of x1 and x2 are not the same.
The pvalues should be very small for larger sample size and relative difference or ratio will be like 1e-20/ 2e-20

- simulate under the null where x1 and x2 come from the same distribution, In this case both p-values should be uniform in [0, 1]
- compute difference in p-values instead of ratio when using the alternative.

IMO, the difference looks to large in the plots, I think both should be asymptotically the same.

BTW: you can use numpy.random, then you don't need the list comprehension

**Comment by chrisb83** [comment] 2018-07-30 21:14
@josef-pkt @pvanmulbregt any opinion how to close this issue? i would argue that the `mstats` version is preferable since I am not aware of a reference that proposes the adjustment in `stats` for the *two-sided* case and the result does not look much better based on the small test i did (https://gist.github.com/chrisb83/6b053181865bb9c5ec5b635ca54fa160).

**Comment by josef-pkt** [comment] 2018-07-30 22:11
Based on the plots in `In [74]` it looks like mstats will have closer size on average but will be liberal over some ranges.

Related aside: this looks a bit similar to the debate for binomial proportions: Because of the discreteness of the possible test statistics, it is not possible to get the correct size/rejection rate. The debate is whether it is better to have the correct size on average or whether size should be maintained (rejection rate shouldn't exceed nominal rate) which ends up being conservative, i.e. can under-reject by a large amount.

a quick MC for empirical size of test, i.e. rejection rates compared to nominal

```
[ 0.001  0.01   0.025  0.05   0.075  0.1    0.2  ]

5 [ 0.      0.01    0.01    0.0745  0.0745  0.0745  0.0745] stats
5 [ 0.      0.      0.01    0.01    0.01    0.0745  0.0745] mstats

6 [ 0.      0.0035  0.0265  0.0265  0.0265  0.142   0.142 ] stats
6 [ 0.      0.0035  0.0035  0.0265  0.0265  0.0265  0.142 ] mstats

7 [ 0.      0.0105  0.0105  0.062   0.062   0.062   0.208 ] stats
7 [ 0.      0.      0.0105  0.0105  0.062   0.062   0.062 ] mstats

8 [ 0.0005  0.017   0.017   0.091   0.091   0.091   0.2875] stats
8 [ 0.0005  0.0015  0.017   0.017   0.017   0.091   0.091 ] mstats

10 [ 0.0015  0.0145  0.0145  0.0505  0.0505  0.0505  0.1645] stats
10 [ 0.0015  0.004   0.0145  0.0145  0.0505  0.0505  0.1645] mstats

12 [ 0.0025  0.011   0.0335  0.0335  0.098   0.098   0.252 ] stats
12 [ 0.001   0.011   0.011   0.0335  0.0335  0.098   0.098 ] mstats

15 [ 0.      0.0065  0.0245  0.0245  0.0755  0.0755  0.1875] stats
15 [ 0.      0.0065  0.0065  0.0245  0.0245  0.0755  0.1875] mstats

20 [ 0.0005  0.014   0.0375  0.0375  0.0975  0.0975  0.199 ] stats
20 [ 0.      0.004   0.014   0.0375  0.0375  0.0975  0.199 ] mstats

30 [ 0.001   0.0085  0.019   0.043   0.071   0.071   0.1315] stats
30 [ 0.      0.0085  0.019   0.043   0.071   0.071   0.1315] mstats

50 [ 0.0015  0.009   0.022   0.0355  0.068   0.109   0.168 ] stats
50 [ 0.001   0.004   0.022   0.0355  0.068   0.068   0.168 ] mstats
```

script is just a quick adjustment of part of the notebook

```
import numpy as np
from scipy import stats
from scipy.stats import mstats


sample_sz = [5, 6, 7, 8, 10, 12, 15, 20, 30, 50]
n_sim = {5: 2000,
         8: 2000,
         10: 6000,
         15: 10000,
         20: 12000}
distr_dn = {}
distr_dn_m = {}

alphas = np.array([0.001, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2])
print(alphas)

np.random.seed(2339)

for sz in sample_sz:
    ks_stat = []
    ks_mstat = []
    for i in range(2000): #n_sim[sz]):
        x, y = stats.norm.rvs(size=sz), stats.norm.rvs(size=sz)
        s = stats.ks_2samp(x, y)[1]
        sm = mstats.ks_2samp(x, y)[1]
        ks_stat.append(s)
        ks_mstat.append(sm)

    distr_dn[sz] = np.array(ks_stat)
    distr_dn_m[sz] = np.array(ks_mstat)
    
    
    reject = (distr_dn[sz][:, None] <= alphas).mean(0)
    reject_m = (distr_dn_m[sz][:, None] <= alphas).mean(0)
    print()
    print(sz, reject, 'stats')
    print(sz, reject_m, 'mstats')
```

**Comment by chrisb83** [comment] 2018-08-02 20:42
@josef-pkt the fact that the `mstats` version is more conservative is probably a good argument to stick to that version. once `n` is large (maybe > 200), one could use the unadjusted version in `stats`. Would you be supportive of a PR in that case?

**Comment by josef-pkt** [comment] 2018-08-11 03:51
I'm not sure

**Comment by rgommers** [comment] 2018-08-11 03:53
@josef-pkt did you mean to close this?

**Comment by josef-pkt** [comment] 2018-08-11 03:56
Sorry, must be some mistake here that this got closed. (I'm shutting down open windows and tabs in my summer notebook. I guess I closed the issue when closing chrome and its tabs)

**Comment by chrisb83** [comment] 2018-08-13 19:17
@josef-pkt We can also add a parameter `method` with values asymptotic, approximate (Stevens approximation) and auto (use Stevens method for small n, otherwise asymptotic).

**Comment by pvanmulbregt** [comment] 2018-08-14 03:12
I also spent sometime looking for the justification of the `(en + 0.12 + 0.11 / en)` multiplier in `distributions.kstwobign.sf((en + 0.12 + 0.11 / en) * d)`.
I also spent sometime looking for the justification of any multipliers or adjustments in the Kolmogorov-Smirnov stats.

1. For 1-sided, one-sample, an exact formula is both known and effectively computable, and  the asymptotic behaviour is `exp(-2nx^2)`, but a theoretically justified better way to approach it is `exp(-2n(x+1/(6n))^2`[Maag-Dicaire, 1971].
2. For 2-sided, one-sample, algorithms to compute `Pr(D>x)` have been known for a while but computationally expensive, at least until 2000s.
The asymptotic behaviour is `K(z)= 2*sum (-1)^(k+1) (exp(-2z^2))^2`, for `z=sqrt(n)*d`.  
Stephens[1970] lists `z=(sqrt(n) + 0.12 + 0.11 /sqrt(n))*d` as the modified form to use for `d=Dn`, `Dn+`, and `Dn-`. This appears to be a numeric formula which worked well, not necessarily a theoretically justified one.

Neither of these adjustments is used in `kstest`.

For the two-sample test with `m, n` observations respectively , set `N=mn/(m+n)`. Smirnov showed that `Pr{sqrt(N)*D+ >= Z} -> exp(-2Z^2)` and `Pr{sqrt(N)*D >= Z} -> K(Z)`, under the additional condition that `m/n -> q` for some `q`.   Hence the adjustments for the one-sample tests may also be used for the two-sample test. But there are some caveats.
The probabilities `Pr{sqrt(N)*Dm,n >= Z}` depend subtly on  `m`, `n`, not just `N=mn/(m+n)`.  In particular the rate of convergence is not uniform.  Hodges [1958] showed that even when `m/n->1`, `[(Pr{sqrt(N)*D+ >= Z}/exp(-2Z^2)) - 1] *sqrt(N)` doesn't have a limit so the oscillations are substantial.

`kstest` and `ks_samp` could let the user decide whether to use Stephens' adjustment or not, except that 99.99% of users won't know enough to be able to competently decide, if the elapsed time and effort spent on this Issue are any indication. 
`kstest` can exactly compute 1-sided probs, and my plan is to add one of the recent algorithms  to exactly compute the two-sided probs, so I would suggest not modifying the use of `kstwobign.sf()` in that routine.  

I agree with @josef-pkt on the usefulness of Stephens work. I'd be tempted to make his adjustment used in `ks_2samp`.

**Comment by chrisb83** [comment] 2018-08-14 21:01
@pvanmulbregt thanks for the information. having an exact method for the two-sample finite samples would be the best option of course. do you have a reference? any idea when you could add such a method?

i would say if a quick fix is considered worthwhile, it does not matter so much if we do the adjustment or not. even for n=20, the two versions are pretty close (and if there are less observations, one needs to be careful in any case). at the moment, the situation is bad because of the inconsistency between stats and mstats + there are no references, so the user is not aware of the method used.

**Comment by pvanmulbregt** [comment] 2018-08-14 21:26
@chrisb83 Clarification: Adding exact calculation is for the two-sided *one-sample* situation.  It is a non-trivial computation, I have an initial implementation in Cython, but it is not ready.  It won't get much of my attention after gh-8737 is accepted.  Computations for the two-sample situation, either one-sided or two-sided, hadn't been on my radar...

**Closed** 2020-05-25 21:39 UTC
Labels: scipy.stats
