### ISSUE TITLE
scipy.sparse.linalg.eigsh gives segmentation fault

### ISSUE THREAD

**Issue by flrgsr** [scipy/scipy#4937] opened 2015-06-03 20:35 UTC
calling eigsh(corr_matrix, k=1, which='LM', maxiter=1000) on a quite large matrix gives a segmentation fault. 
scipy version '0.15.1' on OS X

**Comment by aarchiba** [comment] 2015-06-04 06:57
Can you provide a piece of code that demonstrates it? Perhaps generate a suitable matrix to trigger the segfault?

**Comment by ewmoore** [comment] 2016-02-22 14:19
Closing this due to providing insufficient information to reproduce the failure.

**Closed by ewmoore** 2016-02-22 14:19 UTC
Labels: scipy.sparse.linalg

**Comment by kpws** [comment] 2018-04-14 09:56
This bug also affected me. I construct a 11778624x11778624 **sparse.lil_matrix**, apply **linalg.eigsh(Hmat, k=1,which='SA')**  and get a segfault when executing this line:
https://github.com/kpws/latticePT/blob/563cf4665b7e1b9d25c70a312f1b4aafcc0e3314/finite.py#L220

scipy.__version__: '1.0.1'
uname -a: 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kpws** [comment] 2018-04-14 10:58
The crash happens not immediately but a few minutes in. The terminal output is:
"Segmentation fault (core dumped)"

**Comment by ev-br** [comment] 2018-04-14 11:00
A reproducible example would be helpful. Otherwise, it's not really actionable.

**Comment by kpws** [comment] 2018-04-15 17:26
Did running the code I linked to not reproduce the bug on your machine?

**Comment by kpws** [comment] 2018-04-15 17:30
Note that about 25 GB memory is necessary to hold the sparse matrix.

**Comment by pv** [comment] 2018-04-15 17:37
Please open a new issue if you have a reproducible testcase --- it's
not given that the crash is related to the old closed issue.
