### ISSUE TITLE
BUG: "xl" not returned if success = False for scipy.optimize.shgo

### ISSUE THREAD

**Issue by greenwoodms06** [scipy/scipy#17639] opened 2022-12-20 21:59 UTC
### Describe your issue.

The lists `xl` and `funl` are not returned if the optimization did not return with `success = True`. It would seem that these lists should be populated and returned for access to the user. The code below is taken from the documentation with `n` changed to a small number such that the issue is reproduced.

### Reproducing Code Example

```python
import scipy.optimize as sopt
def eggholder(x):
        return (-(x[1] + 47.0)
                * np.sin(np.sqrt(abs(x[0]/2.0 + (x[1] + 47.0))))
                - x[0] * np.sin(np.sqrt(abs(x[0] - (x[1] + 47.0))))
                )
    
    bounds = [(-512, 512), (-512, 512)]
    result = sopt.shgo(eggholder, bounds, n=2, sampling_method='sobol')
```

### Error message

```shell
result
Out[27]: 
     fun: -25.460337185286313
 message: 'Failed to find a feasible minimizer point. Lowest sampling point = -25.460337185286313'
    nfev: 2
     nit: 2
   nlfev: 0
   nlhev: 0
   nljev: 0
 success: False
       x: array([0., 0.])
```

### SciPy/NumPy/Python version information

1.9.3

**Comment by tupui** [comment] 2022-12-23 09:18
Hi @greenwoodms06, thank you for reporting. I don't think this is an issue but the expected behaviour. If no point is satisfying the criteria to be marked as solution, then there is no solution to list. The list is not the list of all previous values but the list of extrema (still considering some criteria).

**Comment by tupui** [comment] 2022-12-26 10:27
I am closing the issue as I still believe this is intended.

**Closed by tupui** 2022-12-26 10:27 UTC
Labels: defect, scipy.optimize
