### ISSUE TITLE
The dependencies of pythran are very confusing.

### ISSUE THREAD

**Issue by whenyd** [scipy/scipy#14374] opened 2021-07-09 08:43 UTC
When I compile scipy 1.7.0, an error occured that says "ModuleNotFoundError: No module named 'pythran'". Then I execute `pip install pythran`, something confusing happened.

**17 packages been installed**:

`pythran decorator beniget ply networkx gast six numpy pandas scipy matplotlib python-dateutil pytz cycler kiwisolver pillow pyparsing`

Even the scipy is in the list, and other scientific packages include `numpy pandas matplotlib pillow`.

First, is it a cyclic dependency for scipy?
Second, pythran is just a compiler to efficiently compile scientific programs, why these packages are installed as its dependencies.
Third, if it is possible to compile scipy without pythran.

environment:
Python: 3.9.2
Pip: 21.1.3
numpy: 1.20.1
Cython: 0.29.21
pybind11: 2.6.2

**Comment by ilayn** [comment] 2021-07-09 08:57
Yes we have just found this out too when dependency of `pythran`, `networkx` changed its dependencies too. We are working on it in #14335

**Comment by ilayn** [comment] 2021-07-09 08:57
Duplicate of #14335

**Closed** 2021-07-09 08:58 UTC

**Comment by whenyd** [comment] 2021-07-09 09:01
> Yes we have just found this out too when dependency of `pythran`, `networkx` changed its dependencies too. We are working on it in #14335 Let's keep track of this issue there.

Ok, well
