### ISSUE TITLE
Ifilter in scipy result is different compare with matlab(use butterworth )

### ISSUE THREAD

**Issue by xiangjan** [scipy/scipy#7145] opened 2017-03-09 08:45 UTC
I'm woring at convert matlab code to python code. Now, I have some problem in using scipy.signal.Ifilter. I generate filter coefficient with butterworth function in python. When I generate bandpass filter coefficient using butter function and filtering with scipy.signal.Ifilter function, the result is the some with matlab. But, I use butter function to generate highpass filter and filtering with the Ifilter function, the result is almost some... In my attention, the value are different with 0.005*** between matlab and python. But, the number of value are 100,000, so the summery different is too big. In my case, in matlab the sum of result is 10.0022 and the python result is 6.992

So, I think the problem is the coefficient which generated by butter function. I got the coefficient from matlab, and import it to python, but the result of sum is 7.002. I don't understand why make so different result in high pass filter. when I using bandpass filter. The sum of result is almost same.

band pass:

Fn = SampFreq / 2.0
Wn = np.divide([FreqCen - Freqband / 2, FreqCen + Freqband / 2], Fn)
b, a = butter(FiterOrder, Wn, 'bandpass')
FiltSignal = sp.signal.lfilter(b, a, Signals)

High pass:
Fn = SampFreq / 2.0
Wn = FreqCut / Fn
b, a = butter(FiterOrder, Wn, 'high')
FiltSignal = sp.signal.lfilter(b, a, Signals)

I want to know that where the issue in. 
Thanks to others comment.

**Comment by WarrenWeckesser** [comment] 2017-03-09 15:33
For the high pass filter, what are the values that you use for `SampFreq`, `FreqCut` and `FilterOrder`?

Can you provide the matlab code that you used to generate the high pass filter?  Also show the actual filter coefficients created by matlab, because many of us do not have matlab and we won't be able to run the matlab code.

**Comment by xiangjan** [comment] 2017-03-10 01:29
Thank you for your advise. 
The matlab code is like below.
function [ fIltSignal ] = op_filter( signal,filtType,sampFreq,freqCut,freqCen,freqBand,filtOrder,graph)
switch filtType
    case 2 % high pass filter (butterworth type)
        Wn=freqCut;
        Fn=sampFreq/2;
        [b,a]=butter(filtOrder,Wn/Fn,'high');
        fIltSignal=filter(b,a,signal);
case 3 % band pass filter (butterworth type)
        Wn=[freqCen-freqBand/2 freqCen+freqBand/2];
        Fn=sampFreq/2;
        band=Wn/Fn;
        [b,a]=butter(filtOrder,band,'bandpass');
        fIltSignal=filter(b,a,signal);

I give the value for highpass like below
sampFreq : 10000 filtOrder: 5 FreqCut : 5
so, I can get coefficient like below
a =1.000000000000000
-4.989833593835297
9.959386034085437
-9.939156377088317
4.959489027575896
-0.989885090737415
b=0.994929691353824
-4.974648456769119
9.949296913538237
-9.949296913538237
4.974648456769119
-0.994929691353824

Thank you for your help.

**Comment by Eric89GXL** [comment] 2017-03-15 14:14
I am trying to replicate, but it's difficult given the snippets you've pasted so far.

For both MATLAB and Python, can you give the minimal set of lines (with all variables defined) to reproduce the issue?

**Comment by xiangjan** [comment] 2017-03-16 00:32
Thank you for your comment. The Python code and Matlab code are written blow.
[Python]
`def opHPFilter(Signal, SampFreq, FreqCut,FilterOrder):

    Fn = SampFreq / 2.0
    Wn = FreqCut / Fn
    b, a = butter(FilterOrder, Wn, 'high')
    FiltSignal = sp.signal.lfilter(b, a, Signal)


    return  FiltSignal`

[Matlab]
`function [ fIltSignal ] = op_filter( signal,filtType,sampFreq,freqCut,freqCen,freqBand,filtOrder,graph)
 case 2 % high pass filter (butterworth type)
        Wn=freqCut;
        Fn=sampFreq/2;
        [b,a]=butter(filtOrder,Wn/Fn,'high');
        fIltSignal=filter(b,a,signal);`

**Comment by Eric89GXL** [comment] 2017-03-16 13:52
For future reference, it's easier if you give self-contained minimal examples for people to reproduce. Every additional step someone else has to take to reproduce your issue makes it more time consuming for them.

Here are the self-contained examples that I ran:
```Python
>>> from scipy.signal import butter
>>> filtOrder = 5
>>> Fn = 10000 / 2.0
>>> Wn = 5. / Fn
>>> b, a = butter(filtOrder, Wn, 'high')
>>> print(b)
[ 0.99492969 -4.97464846  9.94929691 -9.94929691  4.97464846 -0.99492969]
>>> print(a)
[ 1.         -4.98983359  9.95938603 -9.93915638  4.95948903 -0.98988509]
```
And in MATLAB:
```MATLAB
>> Wn=5;
>> Fn=10000/2;
>> filtOrder = 5;
>> [b,a]=butter(filtOrder,Wn/Fn,'high');
>> format long
>> b
b =
   0.994929691353824  -4.974648456769119   9.949296913538237  -9.949296913538237   4.974648456769119  -0.994929691353824
>> a
a =
   1.000000000000000  -4.989833593835296   9.959386034085437  -9.939156377088317   4.959489027575896  -0.989885090737415
```
So far these look equivalent. Can you try extending these self-contained code snippets to show a mismatch?

**Comment by xiangjan** [comment] 2017-03-20 00:08
@Eric89GXL  Than you for your test.
The result of butter function is ok. but, using the sample input which I was given. The final result of ifilter function is different. 
I mentioned problem is that the sum of filtering result is difference. (The sum of result from matlab is almost 10, the sum of result from python is just 6.....)
Thank you for your help.

**Comment by Eric89GXL** [comment] 2017-03-20 02:44
Can you add to my example code to make minimal self-contained (copy-paste) examples in both languages that show the difference? It's okay to use the linked data if necessary.

**Comment by xiangjan** [comment] 2017-03-20 04:12
I have copy your code to my test environment. the result is the same with which I given by the link. I don't know the ifilter function or any other place have problem.

**Comment by Eric89GXL** [comment] 2017-03-20 13:46
Okay since you can't reproduce with minimal examples anymore, it might have been a bug in your code (?). Closing for now, feel free to reopen if you can reliably reproduce.

**Closed by Eric89GXL** 2017-03-20 13:46 UTC
Labels: scipy.signal

**Comment by esigalas** [comment] 2017-11-20 08:16
I have tried to convert some matlab code that uses the butterworth filter into python code.
From the plots it is clear that the two codes do something differently regarding the edge values of the signal. I am not sure if that is a known issue but I think that is relevant to this topic.
Python: 2.7.13
scipy: '0.18.1'
The code that can reproduce the plots is the following:
MATLAB:
`function fLFP = filt_LFP(sig1, lower_limit, upper_limit, sF)`
`% fLFP = filt_LFP(sig1, lower_limit, upper_limit)`
`% uses a butterworth filter to bandpass filter the signal between lower and upper limit`
`% INPUTS:`
`% sig1 = signal to be filtered`
`%lower_limit = lower end of bandpass`
`%upper_limit = upper end of bandpass`
`%sF = sampling frequency (default = 2000 Hz)`
`if nargin < 4 % if input variable ‘sF’ is not entered, this provides a default value`
`sF = 2000;`
`end`
`if isempty(sF) % if input variable ‘sF’ is entered as an empty vector, this provides a default`
`sF = 2000;`
`end`
`Nyquist_freq = sF/2;`
`lowcut = lower_limit/Nyquist_freq;`
`highcut = upper_limit/Nyquist_freq;`
`filter_order = 3; % may need to be changed depending on the bandpass limits`
`passband = [lowcut highcut];`
`[Bc Ac] = butter(filter_order, passband);`
`fLFP = filtfilt(Bc, Ac, sig1);`
.....
`LFPtime = [0:0.0005:2];`
`LFP2Hz8Hz_A = sin(2*pi*2*LFPtime) + 0.5*sin(2*pi*8*LFPtime);`
`LFP2Hz8Hz_B = sin(2*pi*2*LFPtime) + 0.5*cos(2*pi*8*LFPtime);`
`plot(LFPtime, LFP2Hz8Hz_A)`
`hold on`
`plot(LFPtime, LFP2Hz8Hz_B, 'r')`
`f_LFP2Hz8Hz_A = filt_LFP(LFP2Hz8Hz_A, 6, 10); `
`f_LFP2Hz8Hz_B = filt_LFP(LFP2Hz8Hz_B, 6, 10);`
`figure()`
`plot(linspace(0,2,4001), f_LFP2Hz8Hz_A)`
`hold on`
`plot(linspace(0,2,4001), f_LFP2Hz8Hz_B, 'r')`
PYTHON:
`from scipy import signal`
`import numpy as np`
`import matplotlib.pylab as plt`
`def filt_LFP(sig1,lower_limit,upper_limit,sF=2000):`
`    Nyquist_freq = sF/2.`
`    lowcut = lower_limit/Nyquist_freq`
`    highcut = upper_limit/Nyquist_freq`
`    filt_order = 3`
`    passband = [lowcut,highcut]`
`    [Bc, Ac] = signal.butter(filt_order, passband, 'bandpass')`
`    fLFP = signal.lfilter(Bc,Ac,sig1)`
`    return fLFP`
`if __name__ == "__main__":`
`    LFPtime = np.linspace(0,2,int(2/.0005))`
`    LFP2Hz8Hz_A = np.sin(2*np.pi*2*LFPtime) + 0.5*np.sin(2*np.pi*8*LFPtime)`
`    LFP2Hz8Hz_B = np.sin(2*np.pi*2*LFPtime) + 0.5*np.cos(2*np.pi*8*LFPtime)`
`    plt.figure()`
`    plt.plot(LFPtime,LFP2Hz8Hz_A,LFPtime,LFP2Hz8Hz_B)`
`    f_LFP2Hz8Hz_A = filt_LFP(LFP2Hz8Hz_A,6,10)`
`    f_LFP2Hz8Hz_B = filt_LFP(LFP2Hz8Hz_B,6,10)`
`    plt.figure()`
`    plt.plot(LFPtime,f_LFP2Hz8Hz_A,LFPtime,f_LFP2Hz8Hz_B)`

**Comment by larsoner** [comment] 2017-11-20 14:59
In MATLAB you used `filtfilt` which does forward-backward filtering, in Python you used `lfilter` which does forward filtering only. Also `filtfilt` sometimes uses some initial condition states that you'd want to check to see if they're the same. You might get better traction sorting this out on StackOverflow, though.

**Comment by YikeStone** [comment] 2018-08-23 21:50
@xiangjan this might solve your issue https://stackoverflow.com/questions/16936558/matlab-filter-not-compatible-with-python-lfilter?rq=1
