### ISSUE TITLE
Failed tests 

### ISSUE THREAD

**Issue by xiaoweiz** [scipy/scipy#4400] opened 2015-01-13 01:32 UTC
Just updated to 15.0 via the Anaconda environment
numpy=1.9.1

Here is the failure info
```
======================================================================
FAIL: test_ndimage.TestNdimage.test_fourier_shift_complex01
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/ndimage/tests/test_ndimage.py", line 1336, in test_fourier_shift_complex01
    assert_array_almost_equal(a.real[1:, 1:], expected[:-1, :-1])
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 78.9247311828%)
 x: array([[  1.514934e-06,   1.000002e+00,   2.000001e+00,   3.000002e+00,
          4.000001e+00,   5.000002e+00,   6.000002e+00,   7.000002e+00,
          8.000001e+00,   9.000001e+00,   1.000000e+01,   1.100000e+01,...
 y: array([[   0.+0.j,    1.+0.j,    2.+0.j,    3.+0.j,    4.+0.j,    5.+0.j,
           6.+0.j,    7.+0.j,    8.+0.j,    9.+0.j,   10.+0.j,   11.+0.j,
          12.+0.j,   13.+0.j,   14.+0.j],...

======================================================================
FAIL: test_ndimage.TestNdimage.test_fourier_shift_real01
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/ndimage/tests/test_ndimage.py", line 1322, in test_fourier_shift_real01
    assert_array_almost_equal(a[1:, 1:], expected[:-1, :-1])
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([[  46.954332, -157.977735, -339.941516, -470.421044, -530.813966,
        -511.298085, -415.024098, -256.      ,  -58.002222,  149.259413,
         334.880048,  470.421044,  535.875433,  520.016407,  426.071989],...
 y: array([[   0.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
           9.,   10.,   11.,   12.,   13.,   14.],
       [  16.,   17.,   18.,   19.,   20.,   21.,   22.,   23.,   24.,...

======================================================================
FAIL: test_2d_real_same (test_signaltools.TestFFTConvolve)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/signal/tests/test_signaltools.py", line 220, in test_2d_real_same
    [16, 40, 73, 60, 36]]))
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([[-29.266667, -25.266667, -17.266667, -14.6     , -18.6     ],
       [ 23.971631,  29.515952,  74.875497,  84.152818,  60.484103],
       [ 30.295036,  65.750715,  81.39117 ,  56.447182,  39.115897]])
 y: array([[ 1,  4, 10, 12,  9],
       [ 8, 26, 56, 54, 36],
       [16, 40, 73, 60, 36]])

----------------------------------------------------------------------
Ran 16090 tests in 154.900s

FAILED (KNOWNFAIL=96, SKIP=1183, failures=3)
Out[2]: <nose.result.TextTestResult run=16090 errors=0 failures=3>
```

**Comment by rgommers** [comment] 2015-01-16 21:20
@xiaoweiz did you run an older Scipy release on this install without test failures? What OS X version?

**Comment by xiaoweiz** [comment] 2015-01-19 11:36
@rgommers It's 10.9.5 Mavericks
I didn't run the test suite with the 14.0 series

**Comment by WarrenWeckesser** [comment] 2015-01-19 19:29
FWIW, I'm also using version 10.9.5 of Mac OS X, and with Anaconda's numpy and scipy, the `ndimage` tests pass:

```
~$ python -c "from scipy import ndimage; ndimage.test('full')"
Running unit tests for scipy.ndimage
NumPy version 1.9.1
NumPy is installed in /Users/warren/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.15.0
SciPy is installed in /Users/warren/anaconda/lib/python2.7/site-packages/scipy
Python version 2.7.9 |Anaconda 1.8.0 (x86_64)| (default, Dec 15 2014, 10:37:34) [GCC 4.2.1 (Apple Inc. build 5577)]
nose version 1.3.4
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 447 tests in 1.576s

OK
```

I also don't get any failures when running the full scipy test suite.

**Comment by xiaoweiz** [comment] 2015-01-19 23:35
@WarrenWeckesser It's strange. I run the test on two Mac machines and got the same failure results. 

```
Running unit tests for scipy.ndimage
NumPy version 1.9.1
NumPy is installed in /Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.15.0
SciPy is installed in /Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy
Python version 2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:37:34) [GCC 4.2.1 (Apple Inc. build 5577)]
nose version 1.3.4
...............................................................................................................................................................................................................................................................................................FF..............................................................................................................................................................
======================================================================
FAIL: test_ndimage.TestNdimage.test_fourier_shift_complex01
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/ndimage/tests/test_ndimage.py", line 1336, in test_fourier_shift_complex01
    assert_array_almost_equal(a.real[1:, 1:], expected[:-1, :-1])
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 78.9247311828%)
 x: array([[  1.514934e-06,   1.000002e+00,   2.000001e+00,   3.000002e+00,
          4.000001e+00,   5.000002e+00,   6.000002e+00,   7.000002e+00,
          8.000001e+00,   9.000001e+00,   1.000000e+01,   1.100000e+01,...
 y: array([[   0.+0.j,    1.+0.j,    2.+0.j,    3.+0.j,    4.+0.j,    5.+0.j,
           6.+0.j,    7.+0.j,    8.+0.j,    9.+0.j,   10.+0.j,   11.+0.j,
          12.+0.j,   13.+0.j,   14.+0.j],...

======================================================================
FAIL: test_ndimage.TestNdimage.test_fourier_shift_real01
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/ndimage/tests/test_ndimage.py", line 1322, in test_fourier_shift_real01
    assert_array_almost_equal(a[1:, 1:], expected[:-1, :-1])
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

(mismatch 100.0%)
 x: array([[  46.954332, -157.977735, -339.941516, -470.421044, -530.813966,
        -511.298085, -415.024098, -256.      ,  -58.002222,  149.259413,
         334.880048,  470.421044,  535.875433,  520.016407,  426.071989],...
 y: array([[   0.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
           9.,   10.,   11.,   12.,   13.,   14.],
       [  16.,   17.,   18.,   19.,   20.,   21.,   22.,   23.,   24.,...

----------------------------------------------------------------------
Ran 447 tests in 2.189s

FAILED (failures=2)
```

**Comment by WarrenWeckesser** [comment] 2015-01-20 01:00
xiaoweiz: Are you using the version of Anaconda that includes MKL optimization?  I'm using the free version, which does not include MKL.

**Comment by xiaoweiz** [comment] 2015-01-20 01:29
@WarrenWeckesser Yes. I'm using the MKL version.

**Comment by WarrenWeckesser** [comment] 2015-01-20 01:37
So this might be a problem with Anaconda.  Please report this to Anaconda support, and see if they can reproduce the problem.  (But don't close this issue, since we don't yet know what the problem is.)

**Comment by xiaoweiz** [comment] 2015-01-20 01:54
I've filed a report on [Anaconda's google user group.](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/Bk89y5z2FGY)

**Comment by asmeurer** [comment] 2015-01-22 17:17
@xiaoweiz are you using `mklfft`?

**Comment by xiaoweiz** [comment] 2015-01-23 00:25
@asmeurer No. Are the failures related to it?

**Comment by asmeurer** [comment] 2015-01-23 02:54
As far as I can tell, the failures are coming from our `mklfft` package.

**Comment by xiaoweiz** [comment] 2015-01-23 03:06
@asmeurer You're right. After `conda remove mklfft`, the test is passed without any failure.

**Comment by WarrenWeckesser** [comment] 2015-01-23 04:43
It looks like this is a problem with Anaconda.  I'm closing the issue, but if this turns out to be a scipy problem, don't hesitate to reopen this issue.

**Closed by WarrenWeckesser** 2015-01-23 04:43 UTC
Labels: 3rd party binaries, defect, scipy.ndimage, scipy.signal
