### ISSUE TITLE
Convolutional Matrix in Scipy?

### ISSUE THREAD

**Issue by Sentient07** [scipy/scipy#7834] opened 2017-09-06 09:36 UTC
Hi, 

I would like to generate a convolutional matrix (A), given the kernel(k) and image(I) shape, such that the dot product of the generated Convolutional matrix(A) and the vectorised image will give the same result as the Convolution of image I and kernel K as the output. From searching scipy's doc, i was not able to find a way to do this. Forming Toeplitz matrix of the kernel(k) is the desired solution, but the way toeplitz matrix are generated in scipy is independent of the image shape, whereas I would need a `linalg.toeplitz` to generate the matrix based on desired output. Equivalent in matlab is [this](http://in.mathworks.com/help/signal/ref/convmtx.html)

Apologies if this is a repost. 

Ramana

**Comment by Lewn** [comment] 2017-09-20 08:35
I'm not 100% sure what you mean, but as far as I can tell, `linalg.toeplitz` has the same functionality as the matlab `toeplitz` function, which is used to implement the `convmtx` function. If you look at the [source code for the Octave version](https://sourceforge.net/p/octave/signal/ci/default/tree/inst/convmtx.m) of `convmtx`, you can port it to python, using the `linalg.toeplitz` function.

Without all checks and possible transpose, it becomes:

```
def convmtx(h,n):
    return linalg.toeplitz(np.hstack([h, np.zeros(n-1)]), np.hstack([h[0], np.zeros(n-1)]))
```

**Comment by rgommers** [comment] 2017-09-20 20:27
> If you look at the source code for the Octave version of convmtx, you can port it to python

Don't do that, Octave is GPL. You cannot translate GPL code or base your implementation on understanding you get from reading GPL source code.

**Comment by ahwillia** [comment] 2019-01-15 04:30
I'd like to also add that something like [`convmtx2`](https://www.mathworks.com/help/images/ref/convmtx2.html) would be a useful function to support. It would be great to support block-Toeplitz and doubly-block-Toeplitz matrices, similar to the suggestion by @Lewn for 1d convolutions...

**Comment by makslevental** [comment] 2019-05-10 21:13
> Don't do that, Octave is GPL. You cannot translate GPL code or base your implementation on understanding you get from reading GPL source code.

i know this is a thread from very long ago but i just had to respond to this: is this really true? you're not allowed to learn from GPL code? that sounds insane and completely unenforceable.

**Comment by ilayn** [comment] 2019-05-11 07:07
> i know this is a thread from very long ago but i just had to respond to this: is this really true? you're not allowed to learn from GPL code? that sounds insane and completely unenforceable.

You are entering the notorious Open Source Software/Free Software debate :-) And yes unfortunately it is true. This is the infamous property that is often, a bit unjustly, called ["The viral license"](https://en.wikipedia.org/wiki/Viral_license). As another example, a similar yet still different issue applies to the contributions that come from the famous [Numerical Recipes book](https://en.wikipedia.org/wiki/Numerical_Recipes#Criticism) too. We don't do that either. See #5716 code comments for the motivation.

I would strongly recommend that we do not go into this debate again. It is what it is 😃

**Comment by pv** [comment] 2019-05-11 12:25
Just to point out that the issue is not about licenses, but with
copyright itself --- you can make the same argument with BSD --- what
you wrote after reading other code may possibly be construed as a
derived work.

**Comment by rgommers** [comment] 2019-08-11 00:25
question seems answered. not high-prio for us, but a new function (not based on GPL'd code) seems welcome. closing this issue. thanks all

**Closed by rgommers** 2019-08-11 00:25 UTC
Labels: query, scipy.linalg
