### ISSUE TITLE
SciPy 0.19.0rc1 test errors and failures on Windows

### ISSUE THREAD

**Issue by cgohlke** [scipy/scipy#7055] opened 2017-02-15 22:50 UTC
Using a msvc14/ifort build of scipy 0.19.0rc1 with fixes for https://github.com/scipy/scipy/pull/7053, https://github.com/scipy/scipy/issues/6882, and https://github.com/scipy/scipy/issues/6336, I get the following test errors and failures on Python 3.5 64-bit for Windows:

```
NumPy version 1.11.3
NumPy relaxed strides checking option: False
NumPy is installed in X:\Python35\lib\site-packages\numpy
SciPy version 0.19.0rc1
SciPy is installed in X:\Python35\lib\site-packages\scipy
Python version 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
<snip>
======================================================================
ERROR: test_64bit_integer (test_mmio.TestMMIOArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 50, in test_64bit_integer
    self.check_exact(a, (2, 2, 4, 'array', 'integer', 'general'))
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 32, in check_exact
    mmwrite(self.fn, a)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 102, in mmwrite
    MMFile().write(target, a, comment, field, precision, symmetry)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 448, in write
    self._write(stream, a, comment, field, precision, symmetry)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 675, in _write
    raise OverflowError("mmwrite does not support integer "
OverflowError: mmwrite does not support integer dtypes larger than native 'int'.

======================================================================
ERROR: test_read_64bit_integer_dense (test_mmio.TestMMIOReadLargeIntegers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 320, in test_read_64bit_integer_dense
    over64=False)
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 287, in check_read
    b = mmread(self.fn)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 76, in mmread
    return MMFile().read(source)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 415, in read
    return self._parse_body(stream)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 516, in _parse_body
    a[i, j] = aij
OverflowError: Python int too large to convert to C long

======================================================================
ERROR: test_read_64bit_integer_sparse_general (test_mmio.TestMMIOReadLargeIntegers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 330, in test_read_64bit_integer_sparse_general
    over64=False)
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 287, in check_read
    b = mmread(self.fn)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 76, in mmread
    return MMFile().read(source)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 415, in read
    return self._parse_body(stream)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 596, in _parse_body
    V[entry_number] = int(l[2])
OverflowError: Python int too large to convert to C long

======================================================================
ERROR: test_read_64bit_integer_sparse_skew (test_mmio.TestMMIOReadLargeIntegers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 350, in test_read_64bit_integer_sparse_skew
    over64=False)
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 287, in check_read
    b = mmread(self.fn)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 76, in mmread
    return MMFile().read(source)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 415, in read
    return self._parse_body(stream)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 596, in _parse_body
    V[entry_number] = int(l[2])
OverflowError: Python int too large to convert to C long

======================================================================
ERROR: test_read_64bit_integer_sparse_symmetric (test_mmio.TestMMIOReadLargeIntegers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 340, in test_read_64bit_integer_sparse_symmetric
    over64=False)
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 287, in check_read
    b = mmread(self.fn)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 76, in mmread
    return MMFile().read(source)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 415, in read
    return self._parse_body(stream)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 596, in _parse_body
    V[entry_number] = int(l[2])
OverflowError: Python int too large to convert to C long

======================================================================
ERROR: test_64bit_integer (test_mmio.TestMMIOSparseCSR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 141, in test_64bit_integer
    self.check_exact(a, (2, 2, 4, 'coordinate', 'integer', 'general'))
  File "X:\Python35\lib\site-packages\scipy\io\tests\test_mmio.py", line 119, in check_exact
    mmwrite(self.fn, a)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 102, in mmwrite
    MMFile().write(target, a, comment, field, precision, symmetry)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 448, in write
    self._write(stream, a, comment, field, precision, symmetry)
  File "X:\Python35\lib\site-packages\scipy\io\mmio.py", line 675, in _write
    raise OverflowError("mmwrite does not support integer "
OverflowError: mmwrite does not support integer dtypes larger than native 'int'.

======================================================================
ERROR: test_matrix_io.test_save_and_load_random
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 30, in test_save_and_load_random
    _check_save_and_load(dense_matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 19, in _check_save_and_load
    loaded_matrix = _save_and_load(matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 12, in _save_and_load
    save_npz(file, matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\_matrix_io.py", line 61, in save_npz
    np.savez_compressed(file, **arrays_dict)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 600, in savez_compressed
    _savez(file, args, kwds, True)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 627, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 92, in zipfile_factory
    return zipfile.ZipFile(*args, **kwargs)
  File "X:\Python35\lib\zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\tmpb9evnyhj.npz'

======================================================================
ERROR: test_matrix_io.test_save_and_load_empty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 34, in test_save_and_load_empty
    _check_save_and_load(dense_matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 19, in _check_save_and_load
    loaded_matrix = _save_and_load(matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 12, in _save_and_load
    save_npz(file, matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\_matrix_io.py", line 61, in save_npz
    np.savez_compressed(file, **arrays_dict)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 600, in savez_compressed
    _savez(file, args, kwds, True)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 627, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 92, in zipfile_factory
    return zipfile.ZipFile(*args, **kwargs)
  File "X:\Python35\lib\zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\tmpy569nvou.npz'

======================================================================
ERROR: test_matrix_io.test_save_and_load_one_entry
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 39, in test_save_and_load_one_entry
    _check_save_and_load(dense_matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 19, in _check_save_and_load
    loaded_matrix = _save_and_load(matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\tests\test_matrix_io.py", line 12, in _save_and_load
    save_npz(file, matrix)
  File "X:\Python35\lib\site-packages\scipy\sparse\_matrix_io.py", line 61, in save_npz
    np.savez_compressed(file, **arrays_dict)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 600, in savez_compressed
    _savez(file, args, kwds, True)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 627, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "X:\Python35\lib\site-packages\numpy\lib\npyio.py", line 92, in zipfile_factory
    return zipfile.ZipFile(*args, **kwargs)
  File "X:\Python35\lib\zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\gohlke\\AppData\\Local\\Temp\\tmppah0meut.npz'

======================================================================
ERROR: test_sort_vertices_of_regions (test_spherical_voronoi.TestSphericalVoronoi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\spatial\tests\test_spherical_voronoi.py", line 112, in test_sort_vertices_of_regions
    sv.sort_vertices_of_regions()
  File "X:\Python35\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 306, in sort_vertices_of_regions
    self.regions)
  File "scipy\spatial\_voronoi.pyx", line 43, in scipy.spatial._voronoi.sort_vertices_of_regions (scipy\spatial\_voronoi.c:2607)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'

======================================================================
ERROR: test_sort_vertices_of_regions_flattened (test_spherical_voronoi.TestSphericalVoronoi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\scipy\spatial\tests\test_spherical_voronoi.py", line 121, in test_sort_vertices_of_regions_flattened
    sv.sort_vertices_of_regions()
  File "X:\Python35\lib\site-packages\scipy\spatial\_spherical_voronoi.py", line 306, in sort_vertices_of_regions
    self.regions)
  File "scipy\spatial\_voronoi.pyx", line 43, in scipy.spatial._voronoi.sort_vertices_of_regions (scipy\spatial\_voronoi.c:2607)
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long'

======================================================================
ERROR: Failure: ValueError (path is on mount 'X:', start on mount 'D:')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "X:\Python35\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "X:\Python35\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "X:\Python35\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "X:\Python35\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "X:\Python35\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "X:\Python35\lib\site-packages\scipy\special\tests\test_precompute_expn_asy.py", line 6, in <module>
    from scipy.special._precompute.expn_asy import generate_A
  File "X:\Python35\lib\site-packages\scipy\special\_precompute\expn_asy.py", line 38, in <module>
    """.format(os.path.relpath(__file__, '..'))
  File "X:\Python35\lib\ntpath.py", line 574, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'X:', start on mount 'D:'

======================================================================
FAIL: test_decomp.TestEig.test_falker
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python35\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_decomp.py", line 286, in test_falker
    self._check_gen_eig(A, B)
  File "X:\Python35\lib\site-packages\scipy\linalg\tests\test_decomp.py", line 228, in _check_gen_eig
    assert_allclose(w[:,perm], wt[:,permt], err_msg=msg)
  File "X:\Python35\lib\site-packages\numpy\testing\utils.py", line 1392, in assert_allclose
    verbose=verbose, header=header)
  File "X:\Python35\lib\site-packages\numpy\testing\utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -2.,  1.,  1.],
       [ 0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  1.,  1., -2.]])
array([[ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1., -1.,  0.],
       [ 0.,  0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  0.]])
(mismatch 16.66666666666667%)
 x: array([[  1.000000e+00 +0.000000e+00j,   1.264977e-16 +6.189609e-09j,
         -1.204097e-01 -1.570127e+00j,  -1.289389e-01 +1.681346e+00j,
         -2.475162e+00 +0.000000e+00j,   2.309522e-16 -1.130063e-08j],...
 y: array([[  1.000000e+00 +0.000000e+00j,   1.164811e-16 +1.003676e-08j,
         -1.204097e-01 -1.570127e+00j,  -1.289389e-01 +1.681346e+00j,
         -2.475162e+00 +0.000000e+00j,   2.126644e-16 -1.832452e-08j],...

----------------------------------------------------------------------
Ran 24192 tests in 225.067s

FAILED (KNOWNFAIL=92, SKIP=1800, errors=12, failures=1)
```

Additional failures on Python 2.7:
```
NumPy version 1.11.3
NumPy relaxed strides checking option: False
NumPy is installed in X:\Python27-x64\lib\site-packages\numpy
SciPy version 0.19.0rc1
SciPy is installed in X:\Python27-x64\lib\site-packages\scipy
Python version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
nose version 1.3.7
<snip>
======================================================================
ERROR: test_wavfile.test_read_early_eof
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27-x64\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "X:\Python27-x64\lib\site-packages\scipy\io\tests\test_wavfile.py", line 91, in test_read_early_eof
    assert_raises(ValueError, wavfile.read, fp, mmap=mmap)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 1142, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
  File "X:\Python27-x64\lib\unittest\case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "X:\Python27-x64\lib\site-packages\scipy\io\wavfile.py", line 281, in read
    return fs, data
UnboundLocalError: local variable 'data' referenced before assignment

======================================================================
FAIL: test_iterative.test_convergence(<function bicgstab at 0x000000000828C2E8>, <nonsymposdef>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27-x64\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "X:\Python27-x64\lib\site-packages\scipy\sparse\linalg\isolve\tests\test_iterative.py", line 195, in check_convergence
    assert_equal(info,0)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 381, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: -10
 DESIRED: 0

----------------------------------------------------------------------
Ran 24204 tests in 213.704s

FAILED (KNOWNFAIL=91, SKIP=1847, errors=11, failures=2)
```

**Comment by ev-br** [comment] 2017-02-16 19:30
This is an impressive set of failures :-).

`test_decomp.TestEig.test_falker` was also reported to fail under OS X in gh-7039. @person142 can it be related to https://github.com/scipy/scipy/pull/6469?

**Comment by ev-br** [comment] 2017-02-16 19:35
Josh @person142 I'm afraid I'm going to ping you once more, concering the file path failure in `special._precompute`.

**Comment by ev-br** [comment] 2017-02-16 19:46
@mp4096 any ideas of what's going on with `io.wavfile`?

**Comment by ev-br** [comment] 2017-02-16 19:51
@jotasi any ideas of what's going on with large integers in MMIO?

**Comment by ev-br** [comment] 2017-02-16 20:00
@jor- ping re `test_matrix_io`, any ideas?

**Comment by ev-br** [comment] 2017-02-16 20:07
I'm puzzled by the `test_convergence` failure, as I cannot find anything even remotely related in 0.19.0

**Comment by mp4096** [comment] 2017-02-16 22:26
Ouch. Concerning `io.wavfile`: Could not reproduce it on my Linux machine, neither with 2.7 nor with 3.5. Unfortunately, I don't have a Windows machine nearby right now. I'll dive into this issue next week.

As far as I can see right now, the [`while`-loop](https://github.com/scipy/scipy/blob/master/scipy/io/wavfile.py#L241) is skipped entirely, which just _should not_ happen.

**Comment by jotasi** [comment] 2017-02-17 05:57
Ouch, indeed. With regards to the MMIO:
I did some checking and it seems to stem from the fact, that even on 64bit Windows a C long and thus a python int is 32bit. Apparently, there is a difference between `np.intp(0).itemsize` that I used to check for the size of native ints in the tests and the size of an `int` that I wasn't aware of. Therefore, the tests assume that 64bit integers should work and then the code overflows because it uses `int(..)` casts and numpy's `can_cast(..., 'int')`.

I am also on my Linux box atm and there the test run just fine but I can set up on a Windows machine over the weekend to fix this.

**Comment by jor-** [comment] 2017-02-17 09:28
@ev-br: The failures in ``test_matrix_io`` seems to be already solved by #7067 thanks to @cgohlke.

**Comment by mp4096** [comment] 2017-02-17 09:58
Same for `io.wavfile.read`, see #7068 -- thanks @cgohlke :clap:

**Comment by jotasi** [comment] 2017-02-17 11:50
And for MMIO, see #7069. I haven't tried it on a Windows machine but the points that were fixed look good to me.
Thanks a lot @cgohlke

**Comment by cgohlke** [comment] 2017-02-17 19:00
The failure of `test_iterative.test_convergence` on Python 2.7 looks familiar (https://github.com/scipy/scipy/issues/3340) and is probably an [Intel Fortran bug](https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/505993). For Python 2.7 I have to use older ifort and MKL versions that are compatible with Visual Studio 2008.

**Comment by stonebig** [comment] 2017-02-23 06:41
Does the trick suggested in the link workaround the last blocking issue ? 
````
Using -O1 is a good workaround as it effectively tuns off more aggressive optimizations"
````

**Comment by ev-br** [comment] 2017-02-24 14:27
ifort bug we cannot do much about, the rest has been fixed AFAICS, so rc2 has been cut out. Please test.

**Comment by cgohlke** [comment] 2017-02-25 02:08
With https://github.com/scipy/scipy/pull/7095, rc2 passes all tests on Python 3.5, 64-bit, Windows.

**Comment by ev-br** [comment] 2017-02-25 08:47
Closing then. Thank you Christoph, all.

**Closed by ev-br** 2017-02-25 08:47 UTC
Labels: defect
