### ISSUE TITLE
scipy.sparse.dok_matrix has no method iteritems()

### ISSUE THREAD

**Issue by mountaindust** [scipy/scipy#5740] opened 2016-01-19 23:57 UTC
Scipy documentation lists scipy.sparse.dok_matrix as having three methods that return iterators:
- iteritems()
- iterkeys()
- itervalues() 

None of these seem to exist. Example:
```
from scipy import sparse
A = np.random.rand(100,100)
As = sparse.dok_matrix(A)
As.iteritems() #<------ This raises an AttributeError: iteritems not found.
```

**Comment by maniteja123** [comment] 2016-01-20 13:10
Hi, could you please tell the version of scipy used. I am unable to reproduce this on master.

```
>>> import scipy
>>> scipy.__version__
'0.18.0.dev0+566fe1f'
>>>import numpy as np
>>>A = np.random.rand(100,100)
>>>As = scipy.sparse.dok_matrix(A)
>>>dir(As).count('iteritems')
1
>>> As.iteritems
<built-in method iteritems of dok_matrix object at 0xb3c0a26c>
```

Hope it helps.

**Comment by mountaindust** [comment] 2016-01-21 17:03
I'm using the latest Anaconda version, which seems to be 0.16.0, so perhaps it is already fixed. As a possible point of interest, scipy.sparse.dok_matrix(A) also throws an AttributeError (module 'scipy' has no attribute 'sparse'). I have to load sparse explicitly via "from scipy import sparse".

**Comment by WarrenWeckesser** [comment] 2016-01-21 17:12
What version of Python are you using, 2 or 3?

> I have to load sparse explicitly via "from scipy import sparse".

This is normal; see http://docs.scipy.org/doc/scipy/reference/api.html#guidelines-for-importing-functions-from-scipy

**Comment by mountaindust** [comment] 2016-01-21 17:15
I'm using Python 3.5.1.

**Comment by WarrenWeckesser** [comment] 2016-01-21 17:30
`dok_matrix` inherits from `dict`, and in python 3, `dict` does not have the `iter*` methods.

**Comment by WarrenWeckesser** [comment] 2016-01-21 17:33
... so I guess we should either add a note to the documentation that `iteritems()`, `iterkeys()` and `itervalues()` are only available in Python 2, or add code so these are also available in Python 3.

**Comment by WarrenWeckesser** [comment] 2016-01-21 17:45
Also, the same applies to the methods `viewitems()`, `viewkeys()` and `viewvalues()`.

**Comment by mountaindust** [comment] 2016-01-21 17:48
Ah. Looking at PEP 469, that also explains why I was getting "RuntimeError: dictionary changed size during iteration" when trying to pop keys from the dok_matrix inside a loop. I went this direction because, among the different sparse matrix formats, it seems like the dok matrix might allow for the most efficient removal of non-zero entries satisfying some condition - it is easy to loop through the keys, and I think it's the only sparse matrix to offer a pop method.

**Comment by perimosocordiae** [comment] 2016-01-21 18:02
For that task, you might be better off with a format like CSR or CSC:

```python
foo = scipy.sparse.rand(5, 5, density=0.5, format='csr')
mask = foo.data > 0.33  # or whatever your condition really is
foo.data[mask] = 0
foo.eliminate_zeros()
```

If `foo` might have duplicate entries at the same location (a pretty rare case), just call `foo.sum_duplicates()` before you start working with `foo.data`.

**Comment by perimosocordiae** [comment] 2016-01-21 18:05
Also, see #4530 for a discussion about whether assigning zeros to the sparse matrix itself (not it's `.data` member) should store the explicit zero or "pop" the value and remove it from the sparsity structure.

**Comment by mountaindust** [comment] 2016-01-22 18:17
Interesting. I thought about the mask-eliminate_zeros way of doing things, but I figured it would take more memory (per the complaint in #4530) and perhaps be slower since it appears that three loops through the data are required - one to create the mask, one to set the entries equal to zero, and finally a third to eliminate those zeros. These loops are done within the library though, so I could see how it could be faster than one Python loop.
Without checking, I actually assumed that the sparse data structures supported explicit zeros - it didn't say otherwise, and the syntax seemed to suggest it. On the other hand, I was very surprised to discover that there was no way to remove entries efficiently, something like:
```
foo = scipy.sparse.rand(1000,1000, density=0.5, format='coo')
foo.remove(foo.data < 0.33)
```
which would effectively do the same thing as your example but with one internal loop and without the added step of creating explicit zeros. In my application, I am trying to remove negligible values (<1e-6) from the sparse matrix - something I would have thought would be pretty common, especially following certain floating point operations that might have round off error.

**Comment by perimosocordiae** [comment] 2016-01-22 19:39
I haven't done benchmarks, but I expect that for structured formats like CSR, the cost of changing the sparsity structure is more expensive than passing over the data a few times. So it's typically better to do some work up-front and remove everything at once, rather than removing one at time. If memory is a concern, you can avoid the mask array by assigning the zeros in a loop, then calling `eliminate_zeros()` at the end.

Sparse matrices do support explicit zeros, which is why this trick is possible in the first place. If you want to keep those explicit zeros, though, things become more difficult. I agree that some nice interface for removing entries would be useful. I'm not fully sure what that interface should look like to admit efficiency without exposing the internals too much.

@pv, do you have thoughts?

**Comment by perimosocordiae** [comment] 2016-01-31 22:09
Further discussion here should probably be a different issue. Closing.

**Closed by perimosocordiae** 2016-01-31 22:09 UTC
