### ISSUE TITLE
Elementwise boolean product for `csr_matrix` returns unexpected output

### ISSUE THREAD

**Issue by rodrigolece** [scipy/scipy#11554] opened 2020-02-19 11:14 UTC
The product of two boolean matrices that I expect to be elementwise and behave like the boolean product (i.e. obey the rules of boolean arithmetic) is not doing so.

#### Reproducing code example:

```python
from scipy.sparse import csr_matrix

a = csr_matrix([[1,0], [0,1]], dtype=bool)
b = csr_matrix([[1,0], [1,0]], dtype=bool)

print((a*b).todense())  # I expect elementwise "logical and": [[True, False], [False, False]]
# [[ True False]
#  [ True False]]
```

This means that `*` is not being interpreted as elementwise product, but rather as a matrix product (in fact I get the same result if I use `a @ b`). 

If I explicitly call the scalar product, I get the following behaviour with two different outputs for depending on the order of multiplication (again an unexpected result and probably a bug?):

```python
print((a._mul_scalar(b)).todense())  # the result I expect
# [[ True False]
#  [False False]]

print((b._mul_scalar(a)).todense())  # again the wrong output
# [[ True False]
#  [ True False]]
```

#### Scipy/Numpy/Python version information:

```python
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
# 1.3.2 1.17.4 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by peterbell10** [comment] 2020-02-19 12:17
Matrix multiplication is the intended behaviour. `scipy.sparse` follows the behaviour of `np.matrix`, not `np.array` (but there are efforts to change that, see #8162). You might want to try [pydata/sparse](https://sparse.pydata.org/en/latest/index.html) instead.

I can't see where this is said in the documentation though, so that could definitely be improved.

As for `_mul_scalar`, that implements the scalar-matrix product but you're trying to use it for a matrix-matrix multiply. Either way, it's not part of the public API so you shouldn't be using it.

**Comment by rodrigolece** [comment] 2020-02-19 14:02
> Matrix multiplication is the intended behaviour. scipy.sparse follows the behaviour of np.matrix, not np.array 

Yes, I think that I was getting to that same conclusion after a bit more experimenting. Understood, and well, even though I shouldn't be be playing with the private methods thank you for clarifying that too because it increased my understanding.

I agree that all that remains is clearly stating in the documentation that this is the behaviour.

**Comment by perimosocordiae** [comment] 2020-02-19 14:17
For completeness, if you do want an elementwise product, use the `.multiply()` method (same as with `np.matrix`):

```
In [3]: a.multiply(b).A                                                         
Out[3]: 
array([[ True, False],
       [False, False]])
```

**Comment by stefanv** [comment] 2021-10-09 06:48
I'm going to close this, as it is expected behavior for sparse matrices.  The desired behavior will be made possible by #14822.

**Closed by stefanv** 2021-10-09 06:48 UTC
Labels: scipy.sparse, Documentation
