### ISSUE TITLE
ValueError in tolil() after update to 0.18.1

### ISSUE THREAD

**Issue by elcombato** [scipy/scipy#6719] opened 2016-10-24 12:13 UTC
Hi,

after an update from 0.17.0 to 0.18.1, the `tolil()` function of `csr_matrix` is breaking with the following error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-42-617cefa9acaf> in <module>()
----> 1 y_lil = y_csr.tolil()

c:\anaconda3\lib\site-packages\scipy\sparse\csr.py in tolil(self, copy)
    147         lil = lil_matrix(self.shape,dtype=self.dtype)
    148 
--> 149         self.sum_duplicates()
    150         ptr,ind,dat = self.indptr,self.indices,self.data
    151         rows, data = lil.rows, lil.data

c:\anaconda3\lib\site-packages\scipy\sparse\compressed.py in sum_duplicates(self)
    974         M, N = self._swap(self.shape)
    975         _sparsetools.csr_sum_duplicates(M, N, self.indptr, self.indices,
--> 976                                         self.data)
    977 
    978         self.prune()  # nnz may have changed

ValueError: Output dtype not compatible with inputs.
```

The failing code, which worked in version 0.17.0:

``` python
...
y_csr = MultiLabelBinarizer(sparse_output=True).fit_transform(y_raw)
y_lil = y_csr.tolil()
```

Edit:
scikit-learn 0.18
python 3.5.1
numpy 1.11.1

**Comment by person142** [comment] 2016-10-24 13:49
@elcombato could you pare down your example to something self-contained? (i.e. a specific matrix that is failing.)

**Comment by pv** [comment] 2016-10-24 19:34
Or, show what `print(y_csr.indptr.dtype, y_csr.indices.dtype, y_csr.data.dtype, y_csr._swap(y_csr.shape), np.asarray(y_csr._swap(y_csr.shape)[0]).dtype)` produces.

**Comment by elcombato** [comment] 2016-10-25 07:41
**self-contained code:**
```python
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer

mat = np.array([["peter", "pan"], ["foo", "bla"]])
mat_bin = MultiLabelBinarizer(sparse_output=True).fit_transform(mat)
print(mat_bin.indptr.dtype, mat_bin.indices.dtype, mat_bin.data.dtype, mat_bin._swap(mat_bin.shape), np.asarray(mat_bin._swap(mat_bin.shape)[0]).dtype)
mat_bin.tolil()
```
**output:**
```
int32 int64 int32 (2, 4) int32

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-ee87571e70e1> in <module>()
      5 mat_bin = MultiLabelBinarizer(sparse_output=True).fit_transform(mat)
      6 print(mat_bin.indptr.dtype, mat_bin.indices.dtype, mat_bin.data.dtype, mat_bin._swap(mat_bin.shape), np.asarray(mat_bin._swap(mat_bin.shape)[0]).dtype)
----> 7 mat_bin.tolil()

c:\anaconda3\lib\site-packages\scipy\sparse\csr.py in tolil(self, copy)
    147         lil = lil_matrix(self.shape,dtype=self.dtype)
    148 
--> 149         self.sum_duplicates()
    150         ptr,ind,dat = self.indptr,self.indices,self.data
    151         rows, data = lil.rows, lil.data

c:\anaconda3\lib\site-packages\scipy\sparse\compressed.py in sum_duplicates(self)
    974         M, N = self._swap(self.shape)
    975         _sparsetools.csr_sum_duplicates(M, N, self.indptr, self.indices,
--> 976                                         self.data)
    977 
    978         self.prune()  # nnz may have changed

ValueError: Output dtype not compatible with inputs.
```

**Comment by perimosocordiae** [comment] 2016-10-25 17:36
I can reproduce locally, using the provided example. The issue is that the label binarizer class produces a CSR matrix with differing dtype for the `indices` and `indptr` arrays.

As a quick fix, you can insert:
```
mat_bin.check_format(full_check=False)
```
before the `tolil()` call, which brings the dtypes into agreement and prevents the error.

Seems like something we can handle better, though!

**Comment by perimosocordiae** [comment] 2016-10-25 17:52
The issue on sklearn's end is on this line: https://github.com/scikit-learn/scikit-learn/blob/788a458bba353c2cf3cfa5a15d6f68315149ef9e/sklearn/preprocessing/label.py#L735

`yt` is a CSR matrix with `int32` index arrays, but the `inverse` array is `int64` and the dtype of `yt.indices` is not preserved. It's a pretty easy fix there (`yt.indices = inverse[yt.indices].astype(yt.indices.dtype)`), but we can also work on a fix here.

**Comment by pv** [comment] 2016-10-25 18:12
The problem is that indptr and indices are not of the same type.
This is an invariant assumed by the CSR matrix code, and enforced at 
matrix construction time. Possibly whatever is constructing this matrix 
modifies the data structure directly?.

**Comment by ev-br** [comment] 2017-01-08 17:52
OK, is this something we can improve on our end or do we declare it a downstream responsibility and a wontfix for scipy.sparse?

**Comment by perimosocordiae** [comment] 2017-01-08 18:51
I think it's a downstream responsibility: the issue will only appear when a sparse matrix is modified in-place, bypassing the checks in the constructor.

It might be nice to add a note to the docs encouraging the use of `check_format()` in these cases, though.

**Closed by perimosocordiae** 2017-01-08 18:51 UTC
Labels: scipy.sparse
