### ISSUE TITLE
ENH: Scipy Optimize, equal Bounds should be directly passed to target function

### ISSUE THREAD

**Issue by Pi9GW** [scipy/scipy#17788] opened 2023-01-14 11:54 UTC
### Is your feature request related to a problem? Please describe.

When using Differential Evolution module with equal Bounds for some parameters the optimizer gets division by zero errors time to time. The equal Bounds also slows down the computation as does the real optimized parameter with unequal Bounds.

### Describe the solution you'd like.

In the case of equal Bounds the parameter should be passed to target function variable as is. This would make the bookkeeping of the non-optimized parameters unneeded and also behave as expected. Additional benefit of speeding up the calculation and simplifying the user code.

**Comment by tupui** [comment] 2023-01-15 18:10
Hi @Pi9GW, thank you for reporting. I am not sure I interpret correctly your message. My understanding is that you are trying to have for some parameters the same value for the upper and lower bounds. Is that correct? e.g.

```python
from scipy.optimize import Bounds, differential_evolution, rosen
bounds = Bounds([1., 0.], [1., 2.])
differential_evolution(rosen, bounds)
```

The above does work. Please provide a minimal reproducible example of what you are trying to do and how it fails for you. Thanks 😃

**Comment by mdhaber** [comment] 2023-01-15 18:27
It sounds to me like DE is saying that when the bounds are always being treated the same way, but this can be simplified if the upper and lower bounds are equal.

**Comment by Pi9GW** [comment] 2023-01-15 19:11
I run DE as RC-filter synthesis tool and for preliminary values use target ranges. Then for the actual realization some values are locked by making bounds equal and optimizer run again. Example bounds:

[(2.2e-07, 2.2e-07), (6.8e-08, 6.8e-08), (2.2e-07, 2.2e-07), (3.3e-09, 3.3e-09), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1.01, 2.2)]

Error:
/usr/lib/python3/dist-packages/scipy/optimize/_differentialevolution.py:1242: RuntimeWarning: invalid value encountered in true_divide return (parameters - self.__scale_arg1) / self.__scale_arg2 + 0.5

The result is usable and everything, but just not neat and slow for no reason apart from dragging the extra parameters along. In another case I separated the non-optimized parameters away at a setup stage, but they need to be fed for the target function anyway, so somewhat cumbersome.

**Comment by tupui** [comment] 2023-01-15 19:19
Maybe I am missing something, but isn't it the purpose of `args`? https://docs.scipy.org/doc/scipy-1.10.0/reference/generated/scipy.optimize.differential_evolution.html

**Comment by mdhaber** [comment] 2023-01-15 19:22
There are other ways of providing these arguments, yes, but the user explains why it's more convenient in this case to fix the bounds. Based on using things like this and fixing a similar problem in `minimize`, I think we can implement this.

**Comment by tupui** [comment] 2023-01-15 20:17
I do get it's convenient for users. I am just not 100% convinced it shouldn't stay in user land (cf our other discussion with `kwargs`). It might add quite some complexity on our side. We would need to wrap internally the function with partial (or other) before doing anything to change the dimension of the problem, etc. VS a simple logic on user side to build a partial or other. Might be the same on our side, but the inner logic being already complex it might be hard to properly cover all cases.

**Comment by mdhaber** [comment] 2023-01-15 20:39
The hesitation to adding `kwargs` wasn't just that users could already accomplish the same thing another way, but that it required adding something to the public API. This doesn't, so I don't think it's a similar case.

Furthermore, the lack of `kwargs` did not cause errors due to an undocumented limitation of the code. I don't think we document that all lower and upper boudns must be distinct, so _something_ should be done to close this (even if the preferred solution is to document that condition).

@andyfaff and I already went through far more trouble to fix this for `minimize` (gh-12889, gh-13096, gh-13143, gh-15504) than it would take with DE, so there is recent precedent for addressing this sort of thing. 

Note that I'm only saying that we should investigate the possibility of doing something simple to resolve the possibility of divide by zero errors. I would not advocate a tiny performance gain for a substantial code complication.

@Pi9GW can you give a minimum working example that causes the error you mentioned?

**Comment by andyfaff** [comment] 2023-01-15 21:16
The reason the minimisation would take longer is because the total population size is calculated as `N * popsize`, with default `popsize=15`. So if `N=10` there are 150 evaluations of the user function for each iteration of the minimiser. I think @Pi9GW is suggesting that by factoring out parameters with equal bounds `N` would be reduced. For example if 5 parameters have equal bounds there would only be 15 * 5 = 75 evaluations of the user function per iteration.

However, a simple approach that would require no modifications would be to reduce `popsize` accordingly. I.e. for this example popsize could be reduced to 8, which would lead to broadly the same number of function evaluations per iteration, 80. 

Modifications to factor out parameters with equal bounds would encompass: wrapping `func`, wrapping `callback`, wrapping the constraint functions, adjusting `init` if an initial population is provided, adjusting `x0` if one is provided, adjusting `integrality`. So there are quite a few changes. It's doable, but messy.

There is no Exception raised, but there is a `RuntimeWarning` due to how the parameters are scaled internally:
```
>>> def quad(x):
            return np.sum((x - 2)**2)

>>> differential_evolution(quad, [(1, 5), (3, 3)])

/Users/andrew/miniconda3/envs/dev3/lib/python3.10/site-packages/
scipy/optimize/_differentialevolution.py:1458: RuntimeWarning: invalid value encountered in divide
  return (parameters - self.__scale_arg1) / self.__scale_arg2 + 0.5

     fun: 1.0000000000014069
     jac: array([2.37587729e-06,            nan])
 message: 'Optimization terminated successfully.'
    nfev: 156
     nit: 4
 success: True
       x: array([2.00000119, 3.        ])
```

My initial thought would be to look into how the scaling is performed, to eliminate the `RuntimeWarning`. Then possibly 
document that reducing `popsize` is an option if you have equal bounds.

**Comment by tupui** [comment] 2023-01-15 21:21
Thanks @andyfaff for completing my answer about why the dimension matter and how it might be messy to support that.

I agree that we can have a look at eliminating the warning and documenting things 👍

**Comment by Pi9GW** [comment] 2023-01-15 21:21
Well, it gets greatly fasted with less search space...

from scipy.optimize import differential_evolution as de

def skf(comps):
    
    e = 0.1
    e += sum(comps)

    return e

#Error:
bounds = [(2.2e-07, 2.2e-07), (6.8e-08, 6.8e-08), (2.2e-07, 2.2e-07), (3.3e-09, 3.3e-09), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1.01, 2.2)]

#Works:
#bounds = [(2.2e-07, 2.2001e-07), (6.8e-08, 6.8001e-08), (2.2e-07, 2.2001e-07), (3.3e-09, 3.3001e-09), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1.01, 2.2)]

opt = de(skf, bounds, strategy='best1bin', maxiter=1000, popsize=15, atol=0.0001, disp=True)

print(  '\n', 'Iterations:', opt.nit,
            '\n Error function evaluations:', opt.nfev,
            '\n Remaining error:', opt.fun, '\n' )

**Comment by tupui** [comment] 2023-01-15 21:24
> Well, it gets greatly fasted with less search space...

Yes it's called the curse of dimensionality. And if you have a lot of params, you can change the sampling method to Sobol' for instance to try to fight that.

**Comment by andyfaff** [comment] 2023-01-15 21:57
@Pi9GW, here's how you reduce when there are equal bounds:
```
from scipy.optimize import differential_evolution as de

def skf(comps):
    
    e = 0.1
    e += sum(comps)

    return e

# RuntimeWarning:
bounds = [(2.2e-07, 2.2e-07), (6.8e-08, 6.8e-08), (2.2e-07, 2.2e-07), (3.3e-09, 3.3e-09), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1.01, 2.2)]

%timeit de(skf, bounds, strategy='best1bin', maxiter=1000, popsize=15, seed=1)
# reducing popsize proportionally will make the population smaller, and have the same effect as factoring out parameters.
%timeit de(skf, bounds, strategy='best1bin', maxiter=1000, popsize=7, seed=1)

bounds = [(2.2e-07, 2.2001e-07), (6.8e-08, 6.8001e-08), (2.2e-07, 2.2001e-07), (3.3e-09, 3.3001e-09), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1000.0, 100000.0), (1.01, 2.2)]

%timeit de(skf, bounds, strategy='best1bin', maxiter=1000, popsize=15, seed=1)
```
```
253 ms ± 2.42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
115 ms ± 501 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
262 ms ± 3.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by andyfaff** [comment] 2023-01-15 22:39
@mdhaber, @tupui I propose to eliminate the `RuntimeWarning` by changing how the scale factors are calculated. The divide by zero warning comes from a `0/0`:

```
   def _unscale_parameters(self, parameters):
        """Scale from parameters to a number between 0 and 1."""
        return (parameters - self.__scale_arg1) / self.__scale_arg2 + 0.5
```

I propose to add an additional attribute to the class `__recip_scale_arg2` which would make the code:

```
   def _unscale_parameters(self, parameters):
        """Scale from parameters to a number between 0 and 1."""
        return (parameters - self.__scale_arg1) * self.__recip_scale_arg2 + 0.5
```

This would remove the divide by zero possibility. `__recip_scale_arg2` would be set around [L710](https://github.com/scipy/scipy/blob/4463eb0d3f7c5168b03291fe30510364f0d9b100/scipy/optimize/_differentialevolution.py#L710).

```
self.__scale_arg2 = np.fabs(self.limits[0] - self.limits[1])
with np.errstate(divide='ignore'):
    self.__recip_scale_arg2 = 1 / self.__scale_arg2
    self.__recip_scale_arg2[~np.isfinite(self.__recip_scale_arg2)] = 0
```

Dividing by a number vs multiplying by that number's reciprocal should *mathematically* have the same effect. Computationally they don't. Fortunately `_unscale_parameters` is only used peripherally in the optimisation, so I think it'll have little effect.

**Comment by mdhaber** [comment] 2023-01-15 22:56
Fixing the warning/NaNs like that sounds fine. Would you like to submit the PR or review?

For the enhancement, can we simply change how the population size is calculated to consider number of _free_ parameters?

**Comment by andyfaff** [comment] 2023-01-15 23:08
I'll make the PR

**Comment by andyfaff** [comment] 2023-01-15 23:53
> For the enhancement, can we simply change how the population size is calculated to consider number of free parameters

what if people knew about changing `popsize` already and had already reduced it to take into account the smaller number of free parameters?

i.e. should a change be:

1. keep existing behaviour but adjust documentation to suggest reducing popsize if bounds are equal.
-or-
2. change behaviour to reduce popsize if bounds are equal and mention it in the documentation.

**Comment by mdhaber** [comment] 2023-01-16 02:08
I think #2 is fine. Or rather, I don't think `popsize` needs to change, just the definition of `N`. (Does that work?)

<details>

 It says,

> The population has `popsize * N` individuals.

where "`N`" the variable is not defined, but presumably it is the same as "N", of which it is said:

> The number of parameters, N, is equal to `len(x)`.

and 

> The total number of bounds is used to determine the number of parameters, N.

I wouldn't consider it a BC break to refine the definition of `N` to be the number of _free_ parameters.

If there is a concern, we can send an email to mailing list before doing it, and of course it would be mentioned in the release notes.

</details>

**Comment by tupui** [comment] 2023-01-16 12:52
2 might be fine as it would only make a difference when bounds are equal. i.e. it should have a lower impact as I don't think it's a very common case.

But again my preference goes for better doc as I don't like to add corner cases like these. I prefer opinionated APIs (while letting users still do what they need to do OC, which is the case here as you can do things in user land).

**Closed** 2023-01-19 11:52 UTC
Labels: defect, scipy.optimize
