### ISSUE TITLE
Dopri5 ODE integrator with step-size control

### ISSUE THREAD

**Issue by sbtlaarzc** [scipy/scipy#5306] opened 2015-10-03 11:10 UTC
I am trying to solve a simple example with the `dopri5` integrator in `scipy.integrate.ode`. As the documentation states

> This is an explicit runge-kutta method of order (4)5 due to Dormand & Prince (with stepsize control and dense output).

this should work. So here is my example:

    import numpy as np
    from scipy.integrate import ode
    import matplotlib.pyplot as plt

    def MassSpring_with_force(t, state, f):
        """ Simple 1DOF dynamics model: m ddx(t) + k x(t) = f(t)"""
        # unpack the state vector
        x = state[0]
        xd = state[1]

        # these are our constants
        k = 2.5 # Newtons per metre
        m = 1.5 # Kilograms

        # compute acceleration xdd
        xdd = ( ( -k*x + f) / m )

        # return the two state derivatives
        return [xd, xdd]

    def force(t):
        """ Excitation force """
        f0 = 1  # force amplitude [N]
        freq = 20  # frequency[Hz]
        omega = 2 * np.pi *freq  # angular frequency [rad/s]
        return f0 * np.sin(omega*t)

    # Time range
    t_start = 0
    t_final = 1
    
    # Main program
    state_ode_f = ode(MassSpring_with_force)
    
    state_ode_f.set_integrator('dopri5', rtol=1e-4, nsteps=500, 
                               first_step=1e-6, max_step=1e-1, verbosity=True)
    
    state2 = [0.0, 0.0]  # initial conditions
    state_ode_f.set_initial_value(state2, 0)
    state_ode_f.set_f_params(force(0))
    
    sol = np.array([[t_start, state2[0], state2[1]]], dtype=float)
    
    print("Time\t\t Timestep\t dx\t\t ddx\t\t state_ode_f.successful()")
    
    while state_ode_f.successful() and state_ode_f.t < (t_final):
        state_ode_f.set_f_params(force(state_ode_f.t))
        state_ode_f.integrate(t_final, step=True)
        sol = np.append(sol, [[state_ode_f.t, state_ode_f.y[0], state_ode_f.y[1]]], axis=0)
        print("{0:0.8f}\t {1:0.4e} \t{2:10.3e}\t {3:0.3e}\t {4}".format(
                state_ode_f.t, sol[-1, 0]- sol[-2, 0], state_ode_f.y[0], state_ode_f.y[1], state_ode_f.successful()))

The result I get is:

    Time		 Timestep	     dx		     ddx		 state_ode_f.successful()
    1.00000000	 1.0000e+00 	 0.000e+00	 0.000e+00	 True

Hence, only one time-step is computed which is obviously incorrect. 

This works with `vode` and `zvode` integrators

**Comment by sbtlaarzc** [comment] 2015-10-03 11:21
If I remove the `state_ode_f.successful()` condition and add the smaller `ifactor` (i.e. = 1), the compuation runs, howeber the `state_ode_f.successful()` condition is `False`, also the step-size remains constant and I get the following error:

> c:\python34\lib\site-packages\scipy\integrate\_ode.py:1018: UserWarning: dopri5: larger nmax is needed 
self.messages.get(idid, 'Unexpected idid=%s' % idid))

**Comment by tpudlik** [comment] 2015-10-10 16:45
The `step` keyword argument is apparently not supported by `dopri5` (see https://github.com/scipy/scipy/issues/2339).

Regardless of the step issue, wouldn't it be better to pass the `force` function to the integrator, rather than pass its current value at every step?  Or is the code just contrived to demonstrate the defect you described?

**Comment by pv** [comment] 2015-10-10 16:56
`step=True` is not supported for dopri*, duplicate of gh-2339

**Closed by pv** 2015-10-10 16:56 UTC
Labels: defect, scipy.integrate
