### ISSUE TITLE
least_squares will retrun the initial value when max_nfev=1

### ISSUE THREAD

**Issue by xichaoqiang** [scipy/scipy#12205] opened 2020-05-24 09:14 UTC
I want fitting curve with least_squares function. I want stop the process with RMS value,
I need run least_squares serval times,so I set max_nfev=1.
But the return x is as same as input x
#### Reproducing code example:

```
popt = least_squares(self.aimfuc, self.init, bounds=(self.lb, self.ub), method='trf', args=(self.omega, self.y_data),max_nfev=1)


for i in range(max_num):
   print(self.init)
   popt = least_squares(self.aimfuc, self.init, bounds=(self.lb, self.ub), method='trf', args=(self.omega, self.y_data),max_nfev=1)
   self.init = popt.x  
   print(self.init)      
```

#### Error message:

```
[5.0e+01 1.0e+02 1.5e+02 2.5e+02 3.5e-01 3.5e-01 3.5e-01 3.5e-01 2.0e+03
 2.0e+03 2.0e+03 2.0e+03 1.0e+00 5.0e+00 1.0e+01]
[5.0e+01 1.0e+02 1.5e+02 2.5e+02 3.5e-01 3.5e-01 3.5e-01 3.5e-01 2.0e+03
 2.0e+03 2.0e+03 2.0e+03 1.0e+00 5.0e+00 1.0e+01]

  ...
```

#### Scipy/Numpy/Python version information:

1.3.1 1.16.5 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by andyfaff** [comment] 2020-05-24 09:23
It's the same as the original x values because the objective function has only been allowed to be called once (max_nfev) In each fit I would expect the objective to be called 10s, if not hundreds of times. Least squares has not had a chance to do anything.

**Comment by xichaoqiang** [comment] 2020-05-24 09:28
Thansk your reply. If max_nfev=1, self.aimfuc will be call len(self.init) times.
I think max_nfev=1 can also adjust the value of x

**Comment by andyfaff** [comment] 2020-05-25 09:33
I'm guessing that is the number of function evaluations required for initialisation, but it's not enough to start doing a minimisation. Why not let least_squares run to completion?

**Comment by nmayorov** [comment] 2020-06-11 20:11
I think there was some confusion here.

I'll close it for now. 

@xichaoqiang reopen if you believe something is not correct. But it is expected behavior, because `least_squares` starts with evaluating the function at the start point and then must stop if `max_nfev=1`.

**Closed by nmayorov** 2020-06-11 20:11 UTC
