### ISSUE TITLE
[ENH] sparse.spmatrix.setdiag very slow (O(n**2) instead of O(n)?)

### ISSUE THREAD

**Issue by andrenarchy** [scipy/scipy#3501] opened 2014-03-27 16:47 UTC
The `setdiag` method of `sparse.spmatrix` is very slow as it simply iterates over all elements that are about to be set, see [source](https://github.com/scipy/scipy/blob/master/scipy/sparse/base.py#L730).

``` python
from scipy.sparse import spdiags
from time import time
import numpy

N = 10000
d = numpy.ones(N)

A = spdiags(d, [0], N, N, format='csr')

t = time()
A.setdiag(d)
print(time()-t)

t = time()
D = spdiags(-A.diagonal() + d, [0], *A.shape, format='csr')
A = A + D
print(time() - t)
```

results in

```
4.65157485008
0.00150895118713
```

Further increasing `N` leads to even more drastic differences and it seems like `setdiag` is in O(n**2) instead of O(n). Any ideas to improve this behavior?

**Comment by AtsushiSakai** [comment] 2020-06-18 13:11
I think we can close this issue because this issue was already solved. 
This is the benchmark result using v1.4.1:

> 0.0002830028533935547
> 0.0004878044128417969

**Closed by AtsushiSakai** 2020-06-18 13:11 UTC
Labels: enhancement, scipy.sparse

**Comment by nschloe** [comment] 2020-06-18 13:25
Confirmed with perfplot:
```python
from scipy.sparse import spdiags
import numpy
import perfplot


def setup(N):
    d = numpy.ones(N)
    A = spdiags(d, [0], N, N, format="csr")
    return A, d


def set_diag(data):
    A, d = data
    A.setdiag(d)
    return A


def add_matrices(data):
    A, d = data
    D = spdiags(-A.diagonal() + d, [0], *A.shape, format="csr")
    return A + D


perfplot.show(
    setup=setup,
    kernels=[set_diag, add_matrices],
    n_range=[2 ** k for k in range(20)],
    xlabel="n",
    equality_check=None,
)
```
![out](https://user-images.githubusercontent.com/181628/85025610-e3d78b80-b177-11ea-87c2-f1b1de1e37ec.png)
