### ISSUE TITLE
scipy.stats.mstats.kruskalwallis

### ISSUE THREAD

**Issue by steviebear** [scipy/scipy#3611] opened 2014-05-05 06:10 UTC
HI

I've applied the Kruskal Wallis test on 3 distinct datasets of varying lengths (481, 583, 1300) the data are likert scale responses (integers) that range from 1 to 7. The Hstat comes back negative but the same data in R (kruskal.test) comes back with the correct value. 

Any ideas as to why this would be?

**Comment by jmarrec** [comment] 2015-07-20 15:21
+1
I've just ran into this issue today (scipy 0.15.1) where the Mann Whitney test was giving prob = NaN. After investigating the source code I came to the conclusion that tiecorrect was the problem.

I've done a search in my local python lib trying to find the tiecorrect function, and ended up finding this code, found in the statsmodels\sandbox\stats\multicomp.py,  which is returning adequately positive values...
```python
def tiecorrect(xranks):
    '''

    should be equivalent of scipy.stats.tiecorrect (nope!)

    '''
    #casting to int rounds down, but not relevant for this case
    rankbincount = np.bincount(np.asarray(xranks,dtype=int))
    nties = rankbincount[rankbincount > 1]
    ntot = float(len(xranks));
    tiecorrection = 1 - (nties**3 - nties).sum()/(ntot**3 - ntot)
    return tiecorrection
```
in my case, nties is : `array([1170,  443,  139,   33,   15], dtype=int64)` which gives T = 1691274438, which is apparently overflowing in the case of the Cython implementation as an unsigned int.


Then I ended here and thought I would upvote as an update as it's still open.

**Comment by rgommers** [comment] 2018-09-02 01:45
CSV file has disappeared so cannot reproduce this, but given that gh-4017 (which looks like the same issue) was fixed, I'm assuming this is fixed as well. Closing.

**Closed by rgommers** 2018-09-02 01:45 UTC
Labels: defect, scipy.stats
