### ISSUE TITLE
Optimize.py: problem with stepsize of fmin_bfgs in new scipy 

### ISSUE THREAD

**Issue by vahmedmcgill** [scipy/scipy#5023] opened 2015-07-07 14:22 UTC
Hi, 
I am trying to optimize a function using fmin_bfgs, and logistic regression algorithm. There's no problem in convergence using the older version (scipy 0.10). However when using newer version 0.15 the optimizer crashes with warning: "Desired error not necessarily achieved due to precision loss”. 
I compared optimize.py code of older, and newer versions, and noticed initial stepsize is updated from **old_old_fval = old_fval + 5000** to **old_old_fval = None**. (https://github.com/scipy/scipy/commit/81474eb34d99bba0b2908e35ba832ca735e40154)
Then I tried changing the stepsize back to **old_old_fval = old_fval + 5000**, and this time fmin_bfgs worked perfectly. I am guessing there might be an issue with the initial stepsize (**old_old_fval = None**) for fmin_bfgs, and this stepsize may not be flexible for all gradient sizes. I see a similar issue still opened here: https://github.com/scipy/scipy/issues/3581.

**Comment by pv** [comment] 2015-07-13 21:42
Duplicate of gh-3581

**Closed by pv** 2015-07-13 21:42 UTC
Labels: scipy.optimize
