### ISSUE TITLE
DOC: False information in docs - scipy.stats.ttest_1samp

### ISSUE THREAD

**Issue by latteprog** [scipy/scipy#15696] opened 2022-03-04 14:22 UTC
### Describe your issue.

The documentation page for ttest_1samp provides example code and the results from running that code. However, the results are orders of magnitude off from what I get running the same code, and the results are also wrongly interpreted, saying the high p-value means that the null hypothesis should be rejected.

### Reproducing Code Example

```python
import numpy as np
from scipy import stats
rng = np.random.default_rng()
rvs = stats.norm.rvs(loc = 5, scale = 10, size = (50, 2), random_state = rng)
stats.ttest_1samp(rvs, 5.)
stats.ttest_1samp(rvs, 0.)
```

### Error message

```shell
Here's the result I got for the last two lines

Ttest_1sampResult(statistic=array([ 1.07810207, -0.38435094]), pvalue=array([0.28626709, 0.70238137]))
Ttest_1sampResult(statistic=array([4.38743017, 2.96982928]), pvalue=array([6.08529768e-05, 4.60362353e-03]))

And here's what's on the current doc page

Ttest_1sampResult(statistic=array([-2.09794637, -1.75977004]), pvalue=array([0.04108952, 0.08468867]))
Ttest_1sampResult(statistic=array([1.64495065, 1.62095307]), pvalue=array([0.10638103, 0.11144602]))
```

### SciPy/NumPy/Python version information

1.7.0 1.21.0 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

**Comment by mdhaber** [comment] 2022-03-04 15:03
Yup. This was fixed in gh-15646 and gh-15651. I'll see if we can backport those.

**Comment by mdhaber** [comment] 2022-03-04 15:08
Oops that was ttest. Looks like there are more of these to fix.

**Comment by latteprog** [comment] 2022-03-04 15:45
The seed in the test isn't the issue here. The results on that page is so far off (6.08e-05 vs 0.106), that it is unlikely to have come from the same code. The criterion for rejecting the null hypothesis is a small p-value, which 0.106 isn't.

**Comment by mdhaber** [comment] 2022-03-04 15:49
It is possible there are two issues, but the seed is definitely _an_ issue. If you think there is an inaccurate calculation, please provide an example where the seed or data is provided and the p-value is incorrect.

**Comment by rkern** [comment] 2022-03-04 16:17
Part of the issue is that `scale=10` is just so wide that the p-values for the second test (against 0) is still quite variable over many orders of magnitude. We got _really_ unlucky with that doc-seed. Bumping up the number of samples from 50 to 100 would solve the issue, though, at least for the doc-seed. When people go to replicate it with `rng = np.random.default_rng()`, they will still observe a false rejection of the true null hypothesis 5% of the time due to the nature of p-values. That can't really be fixed.

**Comment by latteprog** [comment] 2022-03-04 16:29
> If you mean that the numerical results with the provided seed are incorrect, which is incorrect - the data itself (not generated from a normal distribution with location 0) or the t-test (incorrect p-value for the given data)?
The p-value was the problem. In the 1.6.0 version it seems fine though. At least it's in the right direction.

**Comment by tupui** [comment] 2022-03-04 16:35
@mdhaber for the seed and instructions in the doc, there is gh-13955 in progress and hopefully will be merged soon. It will have this information.

**Comment by rkern** [comment] 2022-03-04 17:02
> The p-value was the problem.

To be clear, the calculated p-value for the given `rvs` data was completely correct. By bad, dumb luck, the means of the `rvs` columns were closer to 0 than they were to 5, thus ruining the story we were trying to tell.

**Closed** 2022-03-05 09:40 UTC
Labels: scipy.stats, Documentation
