### ISSUE TITLE
Build dependency cycle due to pythran/networkx

### ISSUE THREAD

**Issue by dlindelof** [scipy/scipy#14335] opened 2021-07-02 05:43 UTC
When I build from source on macOS 11.4 I get the following error:

```
ImportError while importing test module '/Users/dlindelof/Private/scipy/build/testenv/lib/python3.8/site-packages/scipy/stats/tests/test_tukeylambda_stats.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/stats/__init__.py:441: in <module>
    from .stats import *
scipy/stats/stats.py:37: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:102: in <module>
    from ._geometric_slerp import geometric_slerp
scipy/spatial/_geometric_slerp.py:8: in <module>
    from scipy.spatial.distance import euclidean
scipy/spatial/distance.py:124: in <module>
    from ..special import rel_entr
scipy/special/__init__.py:643: in <module>
    from . import _ufuncs
E   ImportError: dlopen(/Users/dlindelof/Private/scipy/build/testenv/lib/python3.8/site-packages/scipy/special/_ufuncs.cpython-38-darwin.so, 2): Symbol not found: _cephes_cosdg
E     Referenced from: /Users/dlindelof/Private/scipy/build/testenv/lib/python3.8/site-packages/scipy/special/_ufuncs.cpython-38-darwin.so
E     Expected in: flat namespace
E    in /Users/dlindelof/Private/scipy/build/testenv/lib/python3.8/site-packages/scipy/special/_ufuncs.cpython-38-darwin.so
```

#### Scipy/Numpy/Python version information:

These are the first lines I get when I start the build/tests:

```
$ python runtests.py -v
Building, see build.log...
Build OK (0:00:12.526099 elapsed)
=================================================== test session starts ===================================================
platform darwin -- Python 3.8.2, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Users/dlindelof/Private/scipy/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/dlindelof/Private/scipy, configfile: pytest.ini
```

The build seems ok, I installed OpenBLAS via Homebrew and set the path in `site.cfg` like this:

```
[openblas]
libraries = openblas
library_dirs = /usr/local/Cellar/openblas/0.3.15_1/lib
include_dirs = /usr/local/Cellar/openblas/0.3.15_1/include
runtime_library_dirs = /usr/local/Cellar/openblas/0.3.15_1/lib
```

I was able to build and run the tests for `numpy` in another repository without problems.

**Comment by tupui** [comment] 2021-07-02 15:44
Hi @dlindelof, thanks for reporting. Since you are on MacOS why not following exactly the relative doc https://scipy.github.io/devdocs/dev/contributor/quickerstart_conda.html or https://scipy.github.io/devdocs/dev/contributor/quickstart_mac.html#quickstart-mac

I am on macOS 11.4 as well and can build latest without issues.

**Comment by dlindelof** [comment] 2021-07-02 22:02
Thanks for your reply and suggestions. I was hoping it would be possible to build scipy without conda. I've tried the instructions in https://scipy.github.io/devdocs/dev/contributor/quickerstart_conda.html and it worked.

FYI https://scipy.github.io/devdocs/dev/contributor/quickstart_mac.html#quickstart-mac fails for me with

```
/usr/local/anaconda3/envs/scipydev/bin/gfortran -Wall -g -arch x86_64 -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.9-x86_64-3.8/scipy/integrate/_quadpackmodule.o -L/usr/local/anaconda3/envs/scipydev/lib -L/usr/local/anaconda3/envs/scipydev/lib/gcc/x86_64-apple-darwin13.4.0/9.3.0 -L/usr/local/anaconda3/envs/scipydev/lib/gcc/x86_64-apple-darwin13.4.0/9.3.0/../../.. -L/usr/local/anaconda3/envs/scipydev/lib/gcc/x86_64-apple-darwin13.4.0/9.3.0/../../.. -Lbuild/temp.macosx-10.9-x86_64-3.8 -lquadpack -lmach -llapack -lblas -llapack -lblas -lcblas -lblas -lcblas -lblas -lgfortran -o scipy/integrate/_quadpack.cpython-38-darwin.so
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
error: Command "/usr/local/anaconda3/envs/scipydev/bin/gfortran -Wall -g -arch x86_64 -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.9-x86_64-3.8/scipy/integrate/_quadpackmodule.o -L/usr/local/anaconda3/envs/scipydev/lib -L/usr/local/anaconda3/envs/scipydev/lib/gcc/x86_64-apple-darwin13.4.0/9.3.0 -L/usr/local/anaconda3/envs/scipydev/lib/gcc/x86_64-apple-darwin13.4.0/9.3.0/../../.. -L/usr/local/anaconda3/envs/scipydev/lib/gcc/x86_64-apple-darwin13.4.0/9.3.0/../../.. -Lbuild/temp.macosx-10.9-x86_64-3.8 -lquadpack -lmach -llapack -lblas -llapack -lblas -lcblas -lblas -lcblas -lblas -lgfortran -o scipy/integrate/_quadpack.cpython-38-darwin.so" failed with exit status 1
```

Thanks!

**Comment by rgommers** [comment] 2021-07-04 09:02
It should be possible to build without conda too, since we do it in CI (see `.github/workflows/macos.yml`). 

I cannot find any other instances of `Symbol not found: _cephes_cosdg`, so not sure what's going on there.

**Comment by dlindelof** [comment] 2021-07-08 20:54
I'm currently trying to follow the steps in `. github/workflows/macos.yml` by hand; I've noticed that towards the end we `pip install pythran`. On my machine, that pulls in `scipy` itself as a transitive dependency. Can that be a problem?

**Comment by tupui** [comment] 2021-07-08 21:17
Pythran has actually a dependency to Networkx which has a dependency to SciPy. I have no clue why this is not causing any issue normally. Looking at logs of recent PRs, Networkx is getting installed without SciPy.

**Comment by tupui** [comment] 2021-07-09 07:10
I can see the problem here too https://github.com/scipy/scipy/pull/14358/checks?check_run_id=3025723702#step:5:1101 
@serge-sans-paille can you clarify what is happening?

**Comment by rgommers** [comment] 2021-07-09 07:24
It is indeed a circular dependency, `pythran` depends on `networkx`, `networkx` depends on `scipy`. This should not be a problem _if_ you're on a platform where there's a scipy wheel. However, I can see a problem occurring with, say `pip install scipy --no-binary` or `pip install scipy` on a platform for which there is no wheel.

I'll give it a try. @dlindelof it would also be useful to have your complete build log. The snippets you added don't show where the problem occurs.

**Comment by tupuinui** [comment] 2021-07-09 07:28
> It is indeed a circular dependency, `pythran` depends on `networkx`, `networkx` depends on `scipy`. This should not be a problem _if_ you're on a platform where there's a scipy wheel. However, I can see a problem occurring with, say `pip install scipy --no-binary scipy` or `pip install scipy` on a platform for which there is no wheel.

ok I see, thanks Ralf! This is happening now on Nightly apparently.

**Comment by tupui** [comment] 2021-07-09 07:29
> It is indeed a circular dependency, `pythran` depends on `networkx`, `networkx` depends on `scipy`. This should not be a problem _if_ you're on a platform where there's a scipy wheel. However, I can see a problem occurring with, say `pip install scipy --no-binary scipy` or `pip install scipy` on a platform for which there is no wheel.

ok I see, thanks Ralf! This is happening now on Nightly apparently.

**Comment by serge-sans-paille** [comment] 2021-07-09 07:38
This is interesting: we end up in a situation where scipy may need to be boostrapped, i.e.

1. build a local version of scipy, *without* pythran
2. use that version ro resolve networkx dependency (and pythran dependency, as pythran also has an optional dependency on scipy)
3. build a full version of scipy with pythran-built kernels
This is a common process in compiler engineering, but that may be too heavy for scipy? The option of using the `N-1` version of scipy is also valid.

**Comment by tupuinui** [comment] 2021-07-09 07:42
>    ... The option of using the `N-1` version of scipy is also valid.

Why not, just not sure if we might run into problems as this is in the Nightly job.

**Comment by tupui** [comment] 2021-07-09 07:43
>    ... The option of using the `N-1` version of scipy is also valid.

Why not, just not sure if we might run into problems as this is in the Nightly job.

**Comment by rgommers** [comment] 2021-07-09 08:10
For `pip install scipy --no-binary scipy -vvvv` I see:
```
  Given no hashes to check 169 links for project 'pip': discarding no candidates
  Removed build tracker: '/private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-req-tracker-hjmyeff3'
  Installing build dependencies ... error
WARNING: Discarding https://files.pythonhosted.org/packages/bb/bb/944f559d554df6c9adf037aa9fc982a9706ee0e96c0d5beac701cb158900/scipy-1.7.0.tar.gz#sha256=998c5e6ea649489302de2c0bc026ed34284f531df89d2bdc8df3a0d44d165739 (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10). Command errored out with exit status 2: /Users/rgommers/mambaforge/envs/circdep/bin/python3.9 /private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-standalone-pip-rpavxdry/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-build-env-pydrahmt/overlay --no-warn-script-location -v --no-binary scipy --only-binary :none: -i https://pypi.org/simple -- 'wheel<0.37.0' 'setuptools<58.0.0' 'Cython>=0.29.18,<3.0' 'pybind11>=2.4.3,<2.7.0' pythran==0.9.11 'numpy==1.19.2; python_version=='"'"'3.7'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.19.2; python_version=='"'"'3.8'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.16.5; python_version=='"'"'3.7'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine!='"'"'aarch64'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_python_implementation != '"'"'PyPy'"'"'' 'numpy==1.20.0; python_version=='"'"'3.7'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' 'numpy; python_version=='"'"'3.8'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' 'numpy; python_version=='"'"'3.9'"'"' and platform_python_implementation=='"'"'PyPy'"'"'' Check the logs for full command output.
  Created temporary directory: /private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-unpack-cyhgd3ak
  Looking up "https://files.pythonhosted.org/packages/fe/fd/8704c7b7b34cdac850485e638346025ca57c5a859934b9aa1be5399b33b7/scipy-1.6.3.tar.gz" in the cache
  No cache entry available
  https://files.pythonhosted.org:443 "GET /packages/fe/fd/8704c7b7b34cdac850485e638346025ca57c5a859934b9aa1be5399b33b7/scipy-1.6.3.tar.gz HTTP/1.1" 200 27187987
  Downloading scipy-1.6.3.tar.gz (27.2 MB)

....

    Preparing wheel metadata ... done
  Source in /private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-install-_4kf1b09/scipy_2b96f0840820404c96b1603676443ff9 has version 1.6.3, which satisfies requirement scipy from https://files.pythonhosted.org/packages/fe/fd/8704c7b7b34cdac850485e638346025ca57c5a859934b9aa1be5399b33b7/scipy-1.6.3.tar.gz#sha256=a75b014d3294fce26852a9d04ea27b5671d86736beb34acdfc05859246260707
  Removed scipy from https://files.pythonhosted.org/packages/fe/fd/8704c7b7b34cdac850485e638346025ca57c5a859934b9aa1be5399b33b7/scipy-1.6.3.tar.gz#sha256=a75b014d3294fce26852a9d04ea27b5671d86736beb34acdfc05859246260707 from build tracker '/private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-req-tracker-hjmyeff3'

...

  Found link https://files.pythonhosted.org/packages/66/03/818876390c7ff4484d5a05398a618cfdaf0a2b9abb3a7c7ccd59fe181008/numpy-1.21.0.zip#sha256=e80fe25cba41c124d04c662f33f6364909b985f2eb5998aaa5ae4b9587242cce (from https://pypi.org/simple/numpy/) (requires-python:>=3.7), version: 1.21.0
Skipping link: not a file: https://pypi.org/simple/numpy/
Given no hashes to check 34 links for project 'numpy': discarding no candidates
Collecting numpy<1.23.0,>=1.16.5
  Created temporary directory: /private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-unpack-gpfif_jv
  Looking up "https://files.pythonhosted.org/packages/bf/3a/8c42772b0ba18e603b4b9131925bcd05e5f111d6f640c9b62331654ba881/numpy-1.21.0-cp39-cp39-macosx_10_9_x86_64.whl" in the cache
  No cache entry available
  https://files.pythonhosted.org:443 "GET /packages/bf/3a/8c42772b0ba18e603b4b9131925bcd05e5f111d6f640c9b62331654ba881/numpy-1.21.0-cp39-cp39-macosx_10_9_x86_64.whl HTTP/1.1" 200 16917897
  Downloading numpy-1.21.0-cp39-cp39-macosx_10_9_x86_64.whl (16.9 MB)
     |████████████████████████████████| 16.9 MB 9.0 MB/s eta 0:00:01  Ignoring unknown cache-control directive: immutable
  Updating cache with response from "https://files.pythonhosted.org/packages/bf/3a/8c42772b0ba18e603b4b9131925bcd05e5f111d6f640c9b62331654ba881/numpy-1.21.0-cp39-cp39-macosx_10_9_x86_64.whl"
  Caching due to etag
     |████████████████████████████████| 16.9 MB 9.0 MB/s 
  Added numpy<1.23.0,>=1.16.5 from https://files.pythonhosted.org/packages/bf/3a/8c42772b0ba18e603b4b9131925bcd05e5f111d6f640c9b62331654ba881/numpy-1.21.0-cp39-cp39-macosx_10_9_x86_64.whl#sha256=3537b967b350ad17633b35c2f4b1a1bbd258c018910b518c30b48c8e41272717 (from scipy) to build tracker '/private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-req-tracker-hjmyeff3'
  Removed numpy<1.23.0,>=1.16.5 from https://files.pythonhosted.org/packages/bf/3a/8c42772b0ba18e603b4b9131925bcd05e5f111d6f640c9b62331654ba881/numpy-1.21.0-cp39-cp39-macosx_10_9_x86_64.whl#sha256=3537b967b350ad17633b35c2f4b1a1bbd258c018910b518c30b48c8e41272717 (from scipy) from build tracker '/private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-req-tracker-hjmyeff3'
Created temporary directory: /private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-unpack-0rq8107e
Building wheels for collected packages: scipy
  Created temporary directory: /private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-wheel-k_g9acsa
  Destination directory: /private/var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/pip-wheel-k_g9acsa
  Running command /Users/rgommers/mambaforge/envs/circdep/bin/python3.9 /Users/rgommers/mambaforge/envs/circdep/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/jx/kgbqlb9d79bdryknhdp7wb040000gn/T/tmp931atsj6
  Running from SciPy source directory.
  lapack_opt_info:
  lapack_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/Users/rgommers/mambaforge/envs/circdep/lib', '/usr/local/lib', '/usr/lib']
    NOT AVAILABLE

...

<starts building 1.6.3>
<killed, redoing on my desktop to not melt my laptop>
```

This is not a good thing:(

> The option of using the N-1 version of scipy is also valid.

It happens to work right now (I think), because we only have a single version with a `pythran` build dependency released. But it cannot work with the current `pyproject.toml` for more versions - `pip` will keep going in circles till it hits `1.6.3`.

> This is a common process in compiler engineering, but that may be too heavy for scipy?

It doubles the from-source build time, even if there was a way to express this dependency to `pip`, so I think we need to look at other options - like not making `pythran` depend on `scipy` to begin with. To make matters worse, `pythran` now also depends on `matplotlib` and `pandas`. It cannot be a good thing for a transpiler to depend on a plotting library ....

**Comment by rgommers** [comment] 2021-07-09 08:16
I also have no clue why `networkx` has dependencies that heavy in its defaults. It used to only depend on `decorator`, with everything else in `[extras]`, it was changed about 10 months ago in https://github.com/networkx/networkx/commit/5f2445c1b5ff4db2dd0f943e006df1a107e8f00b. The fix in `pythran` would be to depend on `networkx < 2.6`.

Cc @jarrodmillman - this seems like a showstopper for using new `networkx` versions in a tool like `pythran`.

**Comment by rgommers** [comment] 2021-07-09 08:23
Ah, that's why I'm confused: `networkx` 2.6.0 was released yesterday, until yesterday it indeed only depended on `decorator` and everything else was in extras.

**Comment by rgommers** [comment] 2021-07-09 08:25
@dlindelof I'll rename this issue to be about the build dependency cycle, since we need to resolve that asap. It was not the original cause of your missing symbol problem. It seems you can build now, if you still see the `_cephes_cosdg` problem cropping up, can you open a new issue for it with a full build log?

**Comment by tupui** [comment] 2021-07-09 08:29
> Ah, that's why I'm confused: `networkx` 2.6.0 was released yesterday, until yesterday it indeed only depended on `decorator` and everything else was in extras.

This is the relevant PR https://github.com/networkx/networkx/pull/4190

**Comment by h-vetinari** [comment] 2021-07-09 08:46
Ideally, both networkx and pythran should have a core with as few dependencies as possible, and offer the "fully monty" as an `[extra]`-install.

Bootstrapping these dependency cycles can be really hairy & painful. In conda-forge we reliably hit these cycles when rebuilding for new python versions (like the upcoming cpython 3.10 or pypy 3.8).

**Comment by rgommers** [comment] 2021-07-09 08:55
For the `1.7.0` release our build requirement is `"pythran==0.9.11"`, so a pythran `0.9.12` release won't fix the problem. Basically the only thing that will fix the `scipy` 1.7.0 from source build with build isolation is yanking the `networkx` 2.6.0 and 2.6.1 releases from PyPI and never reintroducing any extra dependencies there. Which is probably a bit too much to ask of NetworkX. Cc also @rossbar @dschult. It seems like there's Homebrew packaging issues too due to NetworkX dependencies (https://github.com/dbt-labs/homebrew-dbt/issues/19), so maybe that is a healthy thing to do. NetworkX has gone from a very light pure Python dependency to a super-heavy dependency.

The other option for us is releasing `scipy` 1.7.1. 

This is why build dependencies are a pain - we should ensure that they're all transitively pinned to upper bounds.

**Comment by ilayn** [comment] 2021-07-09 09:08
It seems to me that the other option for Pythran is to vendor the networkx parts internally. As far as I can see they are discovering cycles and simple paths.

**Comment by andyfaff** [comment] 2021-07-09 09:28
I was concerned about this exact thing happening when accepting Pythran as a dependency. As one of the core scientific packages scipy should be looking to have a small dependency tree, Pythran increases that significantly.

scipy used to require `numpy` and `cython` to build+install. We also use `pybind11` but it's footprint is confined to itself.

Now we require pythran. When I `pip install pythran` it downloads and installs:
`six, pytz, python-dateutil, pyparsing, pillow, numpy, kiwisolver, cycler, scipy, pandas, matplotlib, gast, ply, networkx, decorator, beniget, pythran`. This is definitely not a small dependency tree. Can we ask the Pythran developers why all those packages get pulled in?

**Comment by rgommers** [comment] 2021-07-09 09:32
> Can we ask the Pythran developers why all those packages get pulled in?

@andyfaff please check my last message up. The dependency tree of Pythran was a few pure Python packages, till yesterday. The problem is NetworkX made a major breaking change.

**Comment by rgommers** [comment] 2021-07-09 09:48
Pythran itself is also pure Python by the way, we could vendor it if we wanted to - that would get rid of the dependency completely. Pythran's other dependencies include `six` and `decorator`, which we used to vendor and currently vendor, respectively. I don't really want to, but there is something appealing to having a completely self-contained package. That's a discussion for another time. Really it's due to distributing an `sdist` and having to decide which other packages and version ranges you accept unknown bugs for that you have no way of fixing post-release-time. Conda-forge, Homebrew, apt et al. don't have this issue, because none of those systems mix binary and from-source installs. It's actually madness what PyPI/pip do if you think about it. Perhaps the better solution is to stop distributing sdists altogether.

**Comment by ev-br** [comment] 2021-07-09 09:50
> It seems to me that the other option for Pythran is to vendor the networkx parts internally. As far as I can see they are discovering cycles and simple functional dependencies.

A big +1 from me too. This seems by far the best solution. To offset this sounding like "we have a problem, you deal with it", I wonder what's easier for pythran devs: vendor relevant parts of networkx themselves or make a list of actionable items to coordinate outside contributions (I'm pretty sure some of us could help).

**Comment by rgommers** [comment] 2021-07-09 09:51
> vendor relevant parts of networkx themselves or make a list of actionable items to coordinate outside contributions (I'm pretty sure some of us could help).

+1 this is easy for us to help with I've been contributing to Pythran and it's nice. 10x more approachable code base than Cython.

**Comment by ev-br** [comment] 2021-07-09 10:00
I'm not familiar with either pythran or networkx code, but just looking at https://github.com/serge-sans-paille/pythran/search?p=2&q=nx. , it does not look too bad. So may count me in if that's helpful.

**Comment by rossbar** [comment] 2021-07-09 10:09
I'm not sure this is particularly useful here (maybe for pythran) but all relevant NetworkX code will still work without the additional dependencies: `pip install --no-deps networkx`

**Comment by andyfaff** [comment] 2021-07-09 10:15
> The dependency tree of Pythran was a few pure Python packages, till yesterday

Yes. But there's still risk involved if the number of packages is large. If the other pure python packages involved start to have issues, we're then dependent on those issues being addressed in a timely manner. The bigger the surface, the bigger the risk.

**Comment by h-vetinari** [comment] 2021-07-09 10:16
> all relevant NetworkX code will still work without the additional dependencies

which would be an excellent argument for networkx not to default-depend on `numpy`, `scipy`, `pandas` & `matplotlib`...

I think that would be the most elegant solution still by a long shot, if @jarrodmillman & the networkx maintainers would be willing to revert that. Vendoring is possible of course, but comes with its own (IMO substantial) costs.

**Comment by rgommers** [comment] 2021-07-09 10:28
> Yes. But there's still risk involved if the number of packages is large. If the other pure python packages involved start to have issues, we're then dependent on those issues being addressed in a timely manner. The bigger the surface, the bigger the risk.

Agreed. We should start thinking about pruning the set of dependencies as far as possible. Of course, our most hairy build-time dependencies are BLAS/LAPACK and compilers, not pythran, pybind11 or cython. And we cannot even express those dependencies in `pyproject.toml` or `setup.py`. So the actual amount of room for improvement here is fairly limited.

**Comment by rossbar** [comment] 2021-07-09 10:30
>  if @jarrodmillman & the networkx maintainers would be willing to revert that.

I can't speak for everyone, but I think this is something we would consider - we intentionally had release candidates up for longer than usual for this release hoping to gather some feedback on this particular change. We had hoped that adding the main scientific Python libraries as dependencies wouldn't be particularly disruptive with the availability of wheels for most major platforms.

**Comment by rgommers** [comment] 2021-07-09 10:59
> We had hoped that adding the main scientific Python libraries as dependencies wouldn't be particularly disruptive with the availability of wheels for most major platforms.

Wheels have indeed made our life better, but unfortunately we have to deal with various from-source build scenarios as well. Both platforms without wheels (AIX, Alpine Linux, PowerPC, even macOS M1 still), and people who use `pip install --no-binary` for some reason (could be to build optimized binaries, or to work around some bug, or maybe other reasons too).

I do think NetworkX depending on NumPy is reasonable, and should not be too much of a problem (and Pythran depends on NumPy too). Perhaps even SciPy, depending on how important `sparse.csgraph` and `linalg` are. Why it should depend on pandas and especially Matplotlib is more questionable I'd think.

**Comment by jarrodmillman** [comment] 2021-07-09 12:23
Would removing pandas and matplotlib as default dependencies for networkx fix this problem?

**Comment by rgommers** [comment] 2021-07-09 12:30
> @rgommers Would removing pandas and matplotlib as default dependencies for networkx fix this problem? (I just woke up and need to get some coffee before I make any decisions.)

Drink your coffee first, not the complete house is on fire.

There's two problems:
1. "`scipy-1.7.0.tar.gz` on PyPI now has a circular dependency"
2. we don't want `scipy`, `pandas` and `matplotlib` as build dependencies

(1) is only fixable by a new scipy release, or by completely yanking networkx 2.6.0 and never putting anything back with more than only a `numpy` dependency.

(2) is best fixed by pruning the `pythran` dependencies

And then there's (3), which is "what makes sense from a first principles point of view for NetworkX itself and the packages that depend on it". Removing pandas and matplotlib as default dependencies I think is a reasonable thing for (3).

**Comment by jarrodmillman** [comment] 2021-07-09 18:01
I just yanked 2.6 and 2.6.1 from PyPI until we resolve https://github.com/networkx/networkx/pull/4967.

**Comment by rgommers** [comment] 2021-07-09 19:13
Thanks Jarrod!

**Comment by ilayn** [comment] 2021-07-09 22:09
Indeed thanks for the quick response @jarrodmillman . However I still feel like we can improve Pythran's dependency problem by understanding a bit better why they needed networkx in the first place. Many tools including f2py has a mini cyclic dependency checking engine in place for this type of usage. So maybe networkx folks can help us implement a simpler version of a graph to remove a full-blown dependency? 

As far as I can tell, the used functions are `networkx.DiGraph` and a few of its methods, `networkx.has_path`, `networkx.all_simple_paths`

**Comment by jarrodmillman** [comment] 2021-07-09 22:52
@ilayn see https://github.com/serge-sans-paille/pythran/pull/1839.

**Comment by rgommers** [comment] 2021-07-10 09:28
> I just yanked 2.6 and 2.6.1 from PyPI until we resolve [networkx/networkx#4967](https://github.com/networkx/networkx/pull/4967).

If you decide you want to put them back or do a `networkx` 2.6.2 release with a `scipy` dependency, please let us know - we then need to do a `scipy` 1.7.1 first (which should depend on `pythran` 0.9.12).

**Comment by dlindelof** [comment] 2021-07-10 21:21
> @dlindelof I'll rename this issue to be about the build dependency cycle, since we need to resolve that asap. It was not the original cause of your missing symbol problem. It seems you can build now, if you still see the `_cephes_cosdg` problem cropping up, can you open a new issue for it with a full build log?

Sure thing, I'm able to build now, after getting rid of everything from Conda. As for that circular dependency on `scipy`, I just `pip uninstall`ed scipy and it worked.

**Comment by rgommers** [comment] 2021-11-06 14:53
1.7.2 was released with an updated minimum Pythran version, so this has been solved. Thanks everyone!

**Closed by rgommers** 2021-11-06 14:53 UTC
Labels: prio-high, Build issues
