### ISSUE TITLE
misc.imresize with 'nearest' returns incorrect values when downsampling.

### ISSUE THREAD

**Issue by meetshah1995** [scipy/scipy#7280] opened 2017-04-09 09:56 UTC
I'm using the following code to resize the label images of semantic segmentation task [PASCAL VOC] ( images with values in range 0 to `n_classes` with `n_classes` = 21). 

        lbl = m.imread(lbl_path)
        lbl = np.array(lbl, dtype=np.int32)
        lbl = self.encode_segmap(lbl)
        print 'Unique: ', np.unique(lbl)
        plt.imshow(lbl)
        plt.show()
        lbl = m.imresize(lbl, (self.img_size, self.img_size), 'nearest')
        print 'Unique after resize: ', np.unique(lbl)
        plt.imshow(lbl)
        plt.show()

When I run this, I get this output: 
    
    Unique: [ 0  1 15] 
    Unique after resize: [ 0  17 255]

Shouldn't the values after resize ( using `nearest`) only belong to the set ( 0, 1, 15 )? 

The images I get as output are : 

Original
![original](https://cloud.githubusercontent.com/assets/6251729/24836419/be5704a2-1d38-11e7-94ef-2aab572c0201.png)

Resized
![resized](https://cloud.githubusercontent.com/assets/6251729/24836420/be5b2fd2-1d38-11e7-93e8-3307d127c20c.png)

**Comment by rgommers** [comment] 2017-09-16 06:27
Thanks for the report @meetshah1995. Yes, ``imresize`` has weird default behavior. This issue is a duplicate of gh-4458. We're addressing this for the next release, both by adding clear warnings in the documentation and probably by deprecating ``imresize``.

I'll close this issue as a duplicate.

**Closed by rgommers** 2017-09-16 06:27 UTC
Labels: defect, scipy.misc
