### ISSUE TITLE
test_constant_cost_matrix FAILED

### ISSUE THREAD

**Issue by EverLookNeverSee** [scipy/scipy#11644] opened 2020-03-08 05:35 UTC
My issue is about **test_constant_cost_matrix** located in **scipy/optimize/tests/test_linear_assignment.py**

#### Reproducing code example:
```
python3 runtests.py -v
```

#### Error message:
```
scipy/optimize/tests/test_linear_assignment.py:102: in test_constant_cost_matrix
    assert_array_equal(col_ind, np.arange(n))
E   AssertionError: 
E   Arrays are not equal
E   
E   Mismatched elements: 8 / 8 (100%)
E   Max absolute difference: 7
E   Max relative difference: 5.
E    x: array([7, 6, 5, 4, 3, 2, 1, 0])
E    y: array([0, 1, 2, 3, 4, 5, 6, 7])

```

#### Scipy/Numpy/Python version information:
python version: 3.8.1
numpy version: 1.18.1
scipy version: 1.5.0.dev0+2774bec

**Comment by ilayn** [comment] 2020-03-08 09:45
Duplicate of #11602

**Closed by ilayn** 2020-03-08 09:45 UTC
Labels: maintenance, scipy.optimize
