### ISSUE TITLE
optimize: consistency of names of function arguments?

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#8884] opened 2018-05-29 20:21 UTC
I noticed that the names of the arguments to functions in the optimize tree are not consistent. Even when I thought they might be.  

Many functions in `optimize` take a function as the first parameter, either for root-finding or minimization. Some use `f`, others use `func`. I did a quick count
```
   F  7 anderson, broyden1, broyden2, diagbroyden, excitingmixing, linearmixing, newton_krylov
   f  9 bisect, brenth, brentq, curve_fit, fmin_bfgs, fmin_cg, fmin_ncg, line_search, ridder
 fun  4 least_squares, minimize, minimize_scalar, root
func 18 basinhopping, bracket, brent, brute, check_grad, differential_evolution, 
        fixed_point, fmin, fmin_cobyla, fmin_l_bfgs_b, fmin_powell, fmin_slsqp, fmin_tnc, 
        fminbound, fsolve, golden, leastsq, newton
```

Even the `fmin_XXX` don't use the same name for a function. Perhaps no surprise.
But I do see a couple of issues with this.
1. For the user, being presented with a consistent API is usually a good thing. (And can be for the developer as well.)

But the real reason this came up for me was the next issue.

2. Writing a generic testing framework is more difficult if every function uses its own names for the same concepts.

I wanted to test the 1-d root solvers `bisect/brentq/.../newton` in a generic way, starting from a "test case" with a dictionary containing the function, any derivatives, a bracketing interval, x0 etc.  As long as the test case dictionary has keys matching the names of function arguments, Python's `inspect` can be used to grab the argument names and pull them out of the test case dict.  Knowledge of each function doesn't have to be hard-coded into the testing: which arguments they need and in what order doesn't impact the testing code.  But `newton` uses `func` as the name of the function to root-find, while all the others (`brentq/bisect/.../ridder`) use `f`.  (`newton` uses `fprime` and `fprime2` for the derivatives, but for some reason didn't use `f` for the function.)  So now the testing code needs to know that `'f'` and `'func'` mean the same thing.

Questions:
Is consistency a desirable feature for SciPy?  (Albeit perhaps at a lower priority than many other features.)
If the name of the passed-in function were to be changed to say `f` in all the methods above, would that cause problems for users?   The function names are all of type POSITIONAL_OR_KEYWORD without a default value, hence are perhaps unlikely to be used as `newton(func=np.sin,...)` but instead as `newton(np.sin,...)`.  What kind of consequences would such a change have?

### Scipy/Numpy/Python version information:
```
1.2.0.dev0+bbfd4d6 1.14.2 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)```

**Comment by rgommers** [comment] 2018-05-30 05:38
> Is consistency a desirable feature for SciPy?

Yes definitely. It cannot be at the cost of backwards compatibility though. That's why the unified interfaces `minimize`, `minimize_scalar` and `root` were introduced. The functions you're talking about here could maybe also benefit from such a thing? Symmetry says that `root_scalar` is still missing.

> If the name of the passed-in function were to be changed to say f in all the methods above, would that cause problems for users?

That's technically a backwards compat break, and it's quite hard to tell how many users would have written `func=`. So making this change is not a good idea.

**Comment by rgommers** [comment] 2018-06-29 17:55
Since this was a query not a bug, closing it.

**Closed by rgommers** 2018-06-29 17:55 UTC
Labels: maintenance, query, scipy.optimize

**Comment by anntzer** [comment] 2019-01-20 16:02
@rgommers I wrote a parameter-renaming decorator for Matplotlib (https://github.com/matplotlib/matplotlib/pull/13128) which would allow renaming `f` to `func` (or vice-versa, although my personal preference is `func`) while emitting a DeprecationWarning when `f` is passed in by keyword.  The overhead should be very low.
Would you be interested in using it here?

**Comment by rgommers** [comment] 2019-01-24 01:13
thanks @anntzer. We have `root_scalar` now so should be fine for this one. Good to know about that decorator though, could come in handy.
