### ISSUE TITLE
BUG: scipy.interpolate.{interp2d, RectBivariateSpline} do not extrapolate

### ISSUE THREAD

**Issue by TheFGFSEagle** [scipy/scipy#17082] opened 2022-09-23 17:31 UTC
### Describe your issue.

I cannot extrapolate with neither `scipy.interpolate.interp2d` nor `RectBivariateSpline`. Both return values clamped to the domain if values for coordinates outside of the domain are requested, instead of extrapolating, even though the docs state for both that for coordinates outside of the domain the value is extrapolated (https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html and https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectBivariateSpline.html).

### Reproducing Code Example

```python
a = [-1, 1]
b = [-1, 1]
c = [[-5, 5], [-10, 0]]
i = scipy.interpolate.interp2d(a, b, c)
i(1, -2)
i(2, -2)
i(2, 2)
i(-2, 2)
i(-2, -2)
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

`1.9.1 1.21.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)`

**Comment by ev-br** [comment] 2022-09-23 22:02
Thanks for the report @TheFGFSEagle. This is a duplicate of https://github.com/scipy/scipy/issues/8099 and https://github.com/scipy/scipy/issues/3361 (the former has a discussion and the latter has a pointer at how to address it if you're feeling brave). That said, I'd rather recommend using RegularGridInterpolator instead, it should properly extrapolate (please report if there are issues!). 

I'll close this issue, don't hesitate to continue discussing it however.

**Closed by ev-br** 2022-09-23 22:02 UTC
Labels: defect

**Comment by TheFGFSEagle** [comment] 2022-09-24 00:39
> That said, I'd rather recommend using RegularGridInterpolator instead, it should properly extrapolate (please report if there are issues!).

Thanks, I'll look into it tomorrow and let you know ! 😃

**Comment by TheFGFSEagle** [comment] 2022-09-24 17:25
Yep, I can confirm `RegularGridInterpolator` does what I want and extrapolates correctly - thank you for your help ! :)
