### ISSUE TITLE
BUG: Scipy Special beta function

### ISSUE THREAD

**Issue by Bhavana5N** [scipy/scipy#17558] opened 2022-12-07 19:21 UTC
### Describe your issue.

I am using scipy special beta function by passing positive values.
But after crossing a certain number the beta value comes as zero. 
These are the various value I tried.

Thanks in advance

### Reproducing Code Example

```python
These are the values of a and b respectively
490	589
491	589
492	589
493	589
494	589
494	590

I am getting beta as zero for all later values and a few more combinations from these values.
import scipy.special as sc
beta = sc.beta(a, b)
print(beta)
```

### Error message

```shell
beta value is coming as zero
```

### SciPy/NumPy/Python version information

1.9.3 1.23.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by Bhavana5N** [comment] 2022-12-07 23:21
> 
Yeah, this value is how to use it.
Any other way to handle this value? I am doing some calculations where I need beta value.

**Comment by WarrenWeckesser** [comment] 2022-12-08 01:05
> I am doing some calculations where I need beta value.

The exact value of `beta(494, 590)` is smaller than can be represented with standard double precision floating point.  As @josef-pkt pointed out, you can use `betaln` to compute the logarithm of the value.  If you really need the value, you can use a high precision library such as `mpmath`:

```
In [18]: from mpmath import mp

In [19]: mp.dps = 50

In [20]: mp.beta(494, 590)
Out[20]: mpf('5.2056389185213053996639719543105860879801968877161024e-326')
```
That will generally be significantly slower than a solution that uses numpy and scipy, and it will probably require other code to be converted to use `mpmath`, so it might not be a viable option.

If you can't continue your calculation with the log of the value, and a high precision library such as `mpmath` is not an option, then you'll have to look at the complete calculation in which the beta function is involved to see if you can rearrange it to avoid the need for computing `beta(494, 590)`.  If that result is later multiplied by something very large, you might be able to reformulate your calculation to avoid the tiny intermediate value.

As the issue reported is an inherent limitation of finite precision floating point and not a bug, I'm going to close it.  For ideas on how to work around the limitation, you can try asking over at [stackoverflow](https://stackoverflow.com/) or the [Computational Science](https://scicomp.stackexchange.com/) stackexchange site.

**Closed by WarrenWeckesser** 2022-12-08 01:05 UTC
Labels: scipy.special

**Comment by Bhavana5N** [comment] 2022-12-08 03:54
Thanks for suggestion
