### ISSUE TITLE
Unable to install development version on PyPy 7.3.1 (Python 3.6.9)

### ISSUE THREAD

**Issue by Sanjoth** [scipy/scipy#12255] opened 2020-05-28 16:00 UTC
macOS Catalina 10.15.4

NumPy 1.18.4
PyPy 7.3.1 (Python 3.6.9) with GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)] on darwin

Build issue after installing development version of SciPy as per the instructions mentioned in [INSTALL.rst.txt](https://github.com/scipy/scipy/blob/master/INSTALL.rst.txt#installing-scipy)

The issue seems to be happening only with pip_pypy3 (PyPy 7.3.1), it installs fine with pip (CPython)

Installation:
```
git clone https://github.com/scipy/scipy.git

cd scipy
git clean -xdf
python setup.py install --user
```
The log was more than 65536 characters so I have created a txt file: [Build Log](https://github.com/scipy/scipy/files/4696702/log.txt)

Troubleshooting Info: `pypy3 -c 'from numpy.f2py.diagnose import run; run()'`
<details>

```
------
os.name='posix'
------
sys.platform='darwin'
------
sys.version:
3.6.9 (?, Apr 18 2020, 02:46:07)
[PyPy 7.3.1 with GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)]
------
sys.prefix:
/usr/local/Cellar/pypy3/7.3.1_1/libexec
------
sys.path=':/usr/local/Cellar/pypy3/7.3.1_1/libexec/lib_pypy/__extensions__:/usr/local/Cellar/pypy3/7.3.1_1/libexec/lib_pypy:/usr/local/Cellar/pypy3/7.3.1_1/libexec/lib-python/3:/usr/local/Cellar/pypy3/7.3.1_1/libexec/lib-python/3/lib-tk:/usr/local/Cellar/pypy3/7.3.1_1/libexec/lib-python/3/plat-darwin:/usr/local/Cellar/pypy3/7.3.1_1/libexec/lib-python/3/plat-mac:/usr/local/Cellar/pypy3/7.3.1_1/libexec/lib-python/3/plat-mac/lib-scriptpackages:/usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages:/usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/setuptools-46.1.3-py3.6.egg:/usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/pyparsing-2.4.7-py3.6.egg:/usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/pip-20.0.2-py3.6.egg'
------
Found new numpy version '1.18.4' in /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/numpy/__init__.py
Found f2py2e version '2' in /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/numpy/f2py/f2py2e.py
error: module 'numpy.distutils' has no attribute '__version__'
------
Importing numpy.distutils.fcompiler ... ok
------
Checking availability of supported Fortran compilers:
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
/usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/numpy/distutils/fcompiler/gnu.py:353: UserWarning: Env. variable MACOSX_DEPLOYMENT_TARGET set to 10.3
  flags = GnuFCompiler.get_flags_linker_so(self)
Gnu95FCompiler instance properties:
  archiver        = ['/usr/local/bin/gfortran', '-cr']
  compile_switch  = '-c'
  compiler_f77    = ['/usr/local/bin/gfortran', '-Wall', '-g', '-ffixed-
                    form', '-fno-second-underscore', '-fPIC', '-O3', '-funroll
                    -loops']
  compiler_f90    = ['/usr/local/bin/gfortran', '-Wall', '-g', '-fno-second-
                    underscore', '-fPIC', '-O3', '-funroll-loops']
  compiler_fix    = ['/usr/local/bin/gfortran', '-Wall', '-g', '-ffixed-
                    form', '-fno-second-underscore', '-Wall', '-g', '-fno-
                    second-underscore', '-fPIC', '-O3', '-funroll-loops']
  libraries       = ['gfortran']
  library_dirs    = ['/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-
                    apple-darwin19/9.3.0',
                    '/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-
                    darwin19/9.3.0/../../..',
                    '/usr/local/Cellar/gcc/9.3.0_1/lib/gcc/9/gcc/x86_64-apple-
                    darwin19/9.3.0/../../..']
  linker_exe      = ['/usr/local/bin/gfortran', '-Wall', '-Wall']
  linker_so       = ['/usr/local/bin/gfortran', '-Wall', '-g', '-Wall', '-
                    g', '-undefined', 'dynamic_lookup', '-bundle']
  object_switch   = '-o '
  ranlib          = ['/usr/local/bin/gfortran']
  version         = LooseVersion ('9.3.0')
  version_cmd     = ['/usr/local/bin/gfortran', '-dumpversion']
Fortran compilers found:
  --fcompiler=gnu95  GNU Fortran 95 compiler (9.3.0)
Compilers available for this platform, but not found:
  --fcompiler=absoft  Absoft Corp Fortran Compiler
  --fcompiler=g95     G95 Fortran Compiler
  --fcompiler=gnu     GNU Fortran 77 compiler
  --fcompiler=ibm     IBM XL Fortran Compiler
  --fcompiler=intel   Intel Fortran Compiler for 32-bit apps
  --fcompiler=nag     NAGWare Fortran 95 Compiler
  --fcompiler=pg      Portland Group Fortran Compiler
Compilers not available on this platform:
  --fcompiler=compaq    Compaq Fortran Compiler
  --fcompiler=flang     Portland Group Fortran LLVM Compiler
  --fcompiler=hpux      HP Fortran 90 Compiler
  --fcompiler=intele    Intel Fortran Compiler for Itanium apps
  --fcompiler=intelem   Intel Fortran Compiler for 64-bit apps
  --fcompiler=intelev   Intel Visual Fortran Compiler for Itanium apps
  --fcompiler=intelv    Intel Visual Fortran Compiler for 32-bit apps
  --fcompiler=intelvem  Intel Visual Fortran Compiler for 64-bit apps
  --fcompiler=lahey     Lahey/Fujitsu Fortran 95 Compiler
  --fcompiler=mips      MIPSpro Fortran Compiler
  --fcompiler=nagfor    NAG Fortran Compiler
  --fcompiler=none      Fake Fortran compiler
  --fcompiler=pathf95   PathScale Fortran Compiler
  --fcompiler=sun       Sun or Forte Fortran 95 Compiler
  --fcompiler=vast      Pacific-Sierra Research Fortran 90 Compiler
For compiler details, run 'config_fc --verbose' setup command.
------
Importing numpy.distutils.cpuinfo ... ok
------
CPU information: CPUInfoBase__get_nbits getNCPUs is_64bit is_i386 ------

```

</details>

**Comment by peterbell10** [comment] 2020-05-28 17:01
Closing as duplicate of #12203

**Closed by peterbell10** 2020-05-28 17:01 UTC
