### ISSUE TITLE
scipy test error

### ISSUE THREAD

**Issue by MrWanter** [scipy/scipy#6833] opened 2016-12-07 06:44 UTC
Hi! I'm using scipy version 0.18.1 under ubuntu, but when I run scipy.test() in the terminal, it raise the following error:
```
======================================================================
ERROR: test_fitpack.TestSplder.test_kink
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/tests/test_fitpack.py", line 329, in test_kink
    splder(spl2, 2)  # Should work
  File "/usr/lib/python2.7/dist-packages/scipy/interpolate/fitpack.py", line 1186, in splder
    "and is not differentiable %d times") % n)
ValueError: The spline has internal repeated knots and is not differentiable 2 times

======================================================================
FAIL: Regression test for #651: better handling of badly conditioned
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/scipy/signal/tests/test_filter_design.py", line 36, in test_bad_filter
    assert_raises(BadCoefficients, tf2zpk, [1e-15], [1.0, 1.0])
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1020, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: BadCoefficients not raised

----------------------------------------------------------------------
Ran 8936 tests in 50.777s

FAILED (KNOWNFAIL=115, SKIP=199, errors=1, failures=1)
<nose.result.TextTestResult run=8936 errors=1 failures=1>

```
I don't know how to fix it, can anyone help me? thanks very much!

**Comment by rgommers** [comment] 2016-12-07 09:53
The ``test_kink`` error is a duplicate of gh-3013. That's still not fixed apparently, but only occurs rarely. The most details can be found at https://github.com/scipy/scipy/issues/3013#issuecomment-26903390

**Comment by rgommers** [comment] 2016-12-07 09:55
The second one is a duplicate of gh-5823. A fix is in progress, but it's a bit complicated. 

I'd say just ignore these errors, unless you want to dive into the debugging of the ``test_kink`` one. Then the comment I linked to above has next steps.

**Comment by rgommers** [comment] 2016-12-07 09:55
going to close this as duplicate, but feel free to keep commenting here or on the linked issues.

**Closed by rgommers** 2016-12-07 09:55 UTC
Labels: duplicate

**Comment by MrWanter** [comment] 2016-12-07 14:06
thank you very much!
