### ISSUE TITLE
BUG: Indexing broken for sparse arrays

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#21016] opened 2024-06-21 17:55 UTC
On latest scientific-python-nightly-wheels (on Linux at least): 
```
>>> import scipy.sparse
>>> x = scipy.sparse.eye_array(10, format='csr')[:, [1, 2]]
>>> assert x.shape == (10, 2), x.shape
AssertionError: (2, 10)
```
I assume this is from https://github.com/scipy/scipy/pull/20120 @dschult @stefanv @perimosocordiae @j-bowhay.

I assume this will break code for a lot of folks so if the fix might is not trivial, perhaps it's worth a revert for now?

**Comment by larsoner** [comment] 2024-06-21 18:22
Yes just the latest nightly wheel! Sorry should have been clearer, apologies if I scared you a bit @tylerjereddy :slightly_smiling_face:

**Comment by stefanv** [comment] 2024-06-21 20:36
Not sure it's worth a whole revert; we just need to fix that indexing error.

**Comment by stefanv** [comment] 2024-06-22 00:13
(But fine to roll back, we can always re-apply.)

**Comment by dschult** [comment] 2024-06-22 05:59
Thank you @larsoner for reporting this -- and for everyone doing nightly builds for constructing a system that gives quick feedback.

I've got a fix for this indexing issue (which involves mimicing numpy indexing's special case [fancy indexing using both slices and arrays](https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing)) in #21022. The problem is a mis-formed shape of the output. The fix involves adding a case for handling a single array-index when combined with basic indexing.  This is tested in the `test_base.py` test module, but only for spmatrix. A change to that test module to fully and directly test sparray is developing in #20894 and #20895.

**Closed** 2024-06-24 18:11 UTC
Labels: defect, scipy.sparse
