### ISSUE TITLE
BUG: build failure with Xcode 15 linker

### ISSUE THREAD

**Issue by adamjstewart** [scipy/scipy#19357] opened 2023-10-06 20:51 UTC
### Describe your issue.

I'm trying to build scipy on macOS Sonoma using Apple Clang 15 but I'm encountering a build issue (first reported in https://github.com/spack/spack/issues/40351). @rgommers asked me to open an issue here too.

### Reproducing Code Example

```console
$ spack install py-scipy
```

### Error message

```
[298/1619] Linking target scipy/special/_ellip_harm_2.cpython-311-darwin.so
  FAILED: scipy/special/_ellip_harm_2.cpython-311-darwin.so
  /Users/Adam/spack/lib/spack/env/clang/clang  -o scipy/special/_ellip_harm_2.cpython-311-darwin.so scipy/special/_ellip_harm_2.cpython-311-darwin.so.p/meson-generated__ellip_harm_2.c.o scipy/special/_ellip_harm_2.cpython-311-darwin.so.p/sf_error.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,dynamic_lookup -bundle -Wl,-undefined,dynamic_lookup -lm -Wl,-rpath,/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/openblas-0.3.24-lsn4jcy34p62ysj7qq2ghlsawu6sco6a/lib /Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/openblas-0.3.24-lsn4jcy34p62ysj7qq2ghlsawu6sco6a/lib/libopenblas.dylib
  ld: warning: duplicate -rpath '/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/openblas-0.3.24-lsn4jcy34p62ysj7qq2ghlsawu6sco6a/lib' ignored
  ld: duplicate LC_RPATH '/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/gcc-13.2.0-qhn4xdjhn2p7k2fnvllfz2ca6xhwl2yu/lib' in '/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/openblas-0.3.24-lsn4jcy34p62ysj7qq2ghlsawu6sco6a/lib/libopenblas-r0.3.24.dylib'
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### SciPy/NumPy/Python version and system information

```
scipy 1.11.3
numpy 1.25.2
python 3.11.4
```

**Comment by andyfaff** [comment] 2023-10-06 21:26
I've seen something like that, I can't remember how I got around it

**Comment by andyfaff** [comment] 2023-10-07 01:39
I (on Sonoma as well) get a whole load of the same `ld` warnings. But I don't get any errors with linking and the build completes successfully. Can you build scipy with `python dev.py build`, i.e. not via spack?

- which gfortran are you using?
- where did you get gfortran from?
- where did you get openblas from, what version?

I'm using https://github.com/fxcoudert/gfortran-for-macOS/releases/download/12.2-ventura/gfortran-ARM-12.2-Ventura.dmg for gfortran.
I think I use the openblas that scipy uses for building, installed into `/opt/arm64-builds/lib`.

I do need to set `DYLD_LIBRARY_PATH` for libgfortran.dylib when running the test suite, I didn't have to do that when on Ventura.

**Comment by andyfaff** [comment] 2023-10-08 08:50
I installed `spack`, but a simple `spack install py-scipy` started to build a huge number of packages, so I gave up. I'm guessing that the issue will have to lie with how spack interacts with the scipy build system (e.g. raising warnings to errors), because I can build the package directly.

**Comment by adamjstewart** [comment] 2023-10-08 15:53
> which gfortran are you using?

13.2.0

> where did you get gfortran from?

Built from source using Spack

> where did you get openblas from, what version?

Built from source using Spack, 0.3.24

**Comment by adamjstewart** [comment] 2023-10-08 16:02
> Can you build scipy with `python dev.py build`, i.e. not via spack?

I get the exact same error using dev.py.

**Comment by rgommers** [comment] 2023-10-09 08:47
> I get the exact same error using dev.py.

That's a different failure actually. The `_ellip_harm_2` target builds cleanly, and the failing target is `_flinalg` - so this involves gfortran:
```
[277/1619] Linking target scipy/linalg/_flinalg.cpython-311-darwin.so
FAILED: scipy/linalg/_flinalg.cpython-311-darwin.so 
gfortran  -o scipy/linalg/_flinalg.cpython-311-darwin.so scipy/linalg/_flinalg.cpython-311-darwin.so.p/meson-generated_..__flinalgmodule.c.o scipy/linalg/_flinalg.cpython-311-darwin.so.p/src_det.f.o scipy/linalg/_flinalg.cpython-311-darwin.so.p/src_lu.f.o -L/usr/local/gfortran/lib/gcc/aarch64-apple-darwin22/12.2.0 -L/usr/local/gfortran/lib/gcc/aarch64-apple-darwin22/12.2.0/../../.. -L/usr/local/gfortran/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,dynamic_lookup -bundle -Wl,-undefined,dynamic_lookup -Wl,-rpath,/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/openblas-0.3.24-lsn4jcy34p62ysj7qq2ghlsawu6sco6a/lib scipy/lib_fortranobject.a /Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/openblas-0.3.24-lsn4jcy34p62ysj7qq2ghlsawu6sco6a/lib/libopenblas.dylib -lgfortran -lm
-macosx_version_min has been renamed to -macos_version_min
ld: warning: ignoring duplicate libraries: '-lemutls_w', '-lgcc', '-lgfortran'
ld: duplicate LC_RPATH '/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/gcc-13.2.0-qhn4xdjhn2p7k2fnvllfz2ca6xhwl2yu/lib' in '/Users/Adam/spack/opt/spack/darwin-sonoma-m2/apple-clang-15.0.0/openblas-0.3.24-lsn4jcy34p62ysj7qq2ghlsawu6sco6a/lib/libopenblas-r0.3.24.dylib'
collect2: error: ld returned 1 exit status
```

The difference is the `-macosx_version_min` warning, which seems to be an issue that was resolved in GCC 14.0.0: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111481. The last message (which is about a perhaps not related Ada + XCode 15.0 issue) indicates that it may be possible to work around this with `-Wl,-ld_classic`. 

> `ld: warning: ignoring duplicate libraries: '-lemutls_w', '-lgcc', '-lgfortran'`

This one should be due to Homebrew gfortran, and only a warning not a cause of the linking failure: https://github.com/orgs/Homebrew/discussions/4794#discussioncomment-7044468

**Comment by andyfaff** [comment] 2023-10-09 12:12
I'm finding it difficult to help here, the spack stack is not easy to set up. e.g. openblas is not buildable via spack.

**Comment by rgommers** [comment] 2023-10-10 17:56
@adamjstewart it may be useful to try if `export LDFLAGS=-Wl,-ld_classic` fixes things. It's hard to diagnose bugs in a linker, but that's very likely the root cause here. So switching back to the old one may bypass the problem.

**Comment by adamjstewart** [comment] 2023-10-11 18:41
Thanks for the tip @rgommers, using the classic linker worked! I'll leave this issue open until we find a way to build scipy with the new linker. I expect the older linker to disappear before the new linker does.

**Comment by rgommers** [comment] 2023-10-11 18:59
Great, glad that solved it. I'm not yet convinced that we should use that flag by default, but if we get more complaints we may have to.

> I expect the older linker to disappear before the new linker does.

Well, I do expect Apple to fix the bugs in their new linker before they get rid of the old one completely. And if there's an additional Fortran compiler issue, I'd expect a compatible gfortran or Flang to show up soon.

**Comment by adamjstewart** [comment] 2023-10-11 19:17
True, I guess I shouldn't assume that the bug is in scipy, it could very well be a bug in the linker. A lot of the changes I've noticed so far (as evidenced by the warning messages) suggest that the new linker is simply stricter, but it could also contain bugs.

**Closed** 2023-10-18 03:41 UTC
Labels: defect, Build issues

**Comment by Negra785** [comment] 2024-08-05 14:08
# Número esperado de victorias con una tasa de ganancia del 30%
won_30pct = ____ * ____
print(won_30pct)

# Número esperado de victorias con una tasa de ganancia del 25%
won_25pct = ____
print(won_25pct)

# Número esperado de victorias con una tasa de victorias del 35%
won_35pct = ____
print(won_35pct)
