### ISSUE TITLE
BUG: Result of scipy filtfilt() and MATLAB filtfilt() are not the same 

### ISSUE THREAD

**Issue by snowuyl** [scipy/scipy#15382] opened 2022-01-08 10:03 UTC
### Describe your issue.

I use scipy filtfilt() and MATLAB filtfilt() to check result consistency. But I found  result of scipy filtfilt() and MATLAB filtfilt() are not the same. Please refer to the attached file for more detail.

[td_30.txt](https://github.com/scipy/scipy/files/7833017/td_30.txt)
[python3_filtfilt_30_result.txt](https://github.com/scipy/scipy/files/7833023/python3_filtfilt_30_result.txt)

[matlab_filtfilt_test_30.zip](https://github.com/scipy/scipy/files/7833032/matlab_filtfilt_test_30.zip)

[scipy_filtfilt_test_30.zip](https://github.com/scipy/scipy/files/7833033/scipy_filtfilt_test_30.zip)

[MATLAB_filtfilt_30_result.txt](https://github.com/scipy/scipy/files/7833012/MATLAB_filtfilt_30_result.txt)

### Reproducing Code Example

```python
import sys, scipy, numpy
from scipy import signal
import matplotlib.pyplot as plt

#print(scipy.__version__, numpy.__version__, sys.version_info)



b = [0.979972841549963,-5.87983704929978, 14.6995926232494, -19.5994568309993, 14.6995926232494, -5.87983704929978, 0.979972841549963]
a = [1, -5.95953942986552, 14.798514866178, -19.5986547008315, 14.6002692932459, -5.80093679890116, 0.960346770175509]
x = [15533041, 15664561, 15604100, 15392527, 15430503, 15653269, 15625920, 15419887, 15394668, 15634167, 15356747,
     15554813, 15667928, 15530125, 15357011, 15512619, 15669586, 15569659, 15370252, 15624583, 15418304, 15396501,
     15635446, 15643134, 15448808, 15369416, 15601116, 15658661, 15514278, 15670239]
y = signal.filtfilt(b, a, x)

print("x=", x)
print("b=", b)
print("a=", a)
print("y=", y)
```

### Error message

```shell
There are no error messages.
```

### SciPy/NumPy/Python version information

1.7.3 1.22.0 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment] 2022-01-08 16:07
Hi thanks @snowuyl for reporting. Please only post plain txt files for security reasons.

**Comment by SeanChen1992** [comment] 2022-01-08 16:07
您的邮件我已收到，我会加班加点的看完您珍贵的来信，尽快给您回复的！谢谢啦！陈鑫

**Comment by tupui** [comment] 2022-01-08 16:26
> 您的邮件我已收到，我会加班加点的看完您珍贵的来信，尽快给您回复的！谢谢啦！陈鑫

@SeanChen1992 please translate your text to English.

**Comment by snowuyl** [comment] 2022-01-09 13:22
Hi tupui,

     Since Github doesn't accept *.py and *.m. So I zip *.py and *.m. What is your suggestion to upload *.py and *.m to Github?

**Comment by ilayn** [comment] 2022-01-09 13:35
You can simply put your code in your description. Or if they are too long paste it in a gist. Or use pastebin or something else the point is that security wise it is not safe to download files online.

**Comment by pkaf** [comment] 2022-01-12 04:30
The difference is in the default padding length. In matlab's filtfilt, it is 3*(max(len(a), len(b)) - 1), and in scipy's filtfilt, it is 3*max(len(a), len(b)).

Refer to https://dsp.stackexchange.com/questions/11466/differences-between-python-and-matlab-filtfilt-function

**Comment by pkaf** [comment] 2022-01-12 04:31
Here is the result using python (purple) that resembles matlab output (blue)

<img width="737" alt="Screen Shot 2022-01-12 at 3 30 36 pm" src="https://user-images.githubusercontent.com/3498979/149064122-89a1396c-7bc0-433c-a2bd-1e5e4ddb0a53.png">
![Screen Shot 2022-01-12 at 3 31 09 pm](https://user-images.githubusercontent.com/3498979/149064154-cf637ca6-9416-41cc-8ea5-5993cb77b688.png)

**Comment by pkaf** [comment] 2022-01-12 04:33
![Screen Shot 2022-01-12 at 3 31 09 pm](https://user-images.githubusercontent.com/3498979/149064292-124da47f-4382-439b-91e8-99d74ed0053d.png)

We can close the issue or I can PR with new default for scipy that resembles matlab?

**Comment by WarrenWeckesser** [comment] 2022-01-12 04:49
@pkaf, thanks for the explanation!

Based on those observation, I'm closing the issue.  The documented default value of `padlen` has been that value for a *long* time.  While it would be nice if the default had been chosen to match Matlab back when the function was first implemented, we make no guarantees about compatibility with Matlab, so this is not a bug, and not something we can change now without potentially disrupting a lot of existing code that relies on the current default.

**Closed by WarrenWeckesser** 2022-01-12 04:49 UTC
Labels: defect

**Comment by pkaf** [comment] 2022-01-12 05:03
Makes perfect sense. Is it worth mentioning the caveat in the function/documentation? This issue keeps recurring every few years :) 

One from 2014: https://mail.python.org/pipermail/scipy-user/2014-April/035648.html
