### ISSUE TITLE
Segfault in scipy.test for 0.17.0 in Anaconda 64-bit python 2.7

### ISSUE THREAD

**Issue by lileipku00** [scipy/scipy#5917] opened 2016-03-02 16:50 UTC
`$ python -c "import scipy; scipy.test('full')"`

```
Running unit tests for scipy
NumPy version 1.10.4
NumPy relaxed strides checking option: False
NumPy is installed in /home/user/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.17.0
SciPy is installed in /home/user/anaconda/lib/python2.7/site-packages/scipy
Python version 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
/home/user/anaconda/lib/python2.7/site-packages/numpy/lib/utils.py:99: DeprecationWarning: `scipy.weave` is deprecated, use `weave` instead!
  warnings.warn(depdoc, DeprecationWarning)
.....................................................................................................................................................................................................................................................................K..................................................................................................................................................................................................................................................................................................................K.........................................................................................K....................................................................K..K................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................0-th dimension must be fixed to 3 but got 15
..0-th dimension must be fixed to 3 but got 5
..............0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
.0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
.0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
................................K............................................................................................................................................................................................................................................................................................................K...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Segmentation fault (core dumped)

```

**Comment by ev-br** [comment] 2016-03-02 17:51
Can you run `>>> scipy.test("full", verbose=10)` to *which* test fails?

**Comment by insertinterestingnamehere** [comment] 2016-03-02 18:01
More information about what OS and Python version you're using, what version of scipy you have installed, and how you installed it would be helpful as well.

**Comment by lileipku00** [comment] 2016-03-02 18:28
@insertinterestingnamehere  they are there, in the outputs
`Python version 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
`

**Comment by pv** [comment] 2016-03-02 18:29
It appears to be anaconda 64-bit python 2.7 on linux.

The failure is perhaps in `test_interpolative.TestInterpolativeDecomposition.test_rand` --- that's a crash that I can see for the scipy 0.17.0 binaries available from anaconda. Interestingly, it only occurs for environments created with `conda create -p $PWD/testenv python=2.7 scipy nose` but not for the main conda env. Of course, I don't see the failures in binaries compiled by myself. The traceback in this case is:
```
test_interpolative.TestInterpolativeDecomposition.test_rand ...
Program received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  master.0.id_srand (__entry=2, t=0x0, r=0x0, n=0x0) at scipy/linalg/src/id_dist/src/id_rand_subr_1.f:144
#1  0x00007fffdeb2bcfa in f2py_rout__interpolative_id_srando (capi_self=<optimized out>, capi_args=<optimized out>, capi_keywds=<optimized out>, f2py_func=0x7fffdeb76ca0 <id_srando>) at build/src.linux-x86_64-2.7/scipy/linalg/_interpolativemodule.c:1844
#2  0x00007ffff7a3bd23 in PyObject_Call (func=0x7fffdedcc148, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2546
...
```
iow, not particularly illuminating. Indeed, the `id_srando` routine (which is an fortran 77 entry point to id_srand routine) takes no parameters and modifies only an internal `save` array. I don't see how this can fail, except perhaps via compiler bugs --- iirc anaconda uses fairly old gcc/gfortran versions.

**Comment by pv** [comment] 2016-03-02 18:33
@lileipku00: please confirm whether your crash is the same as above

**Comment by lileipku00** [comment] 2016-03-02 18:44
@ev-br  loooooong outputs

```
$ python
Python 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import scipy
>>> scipy.test("full", verbose=10)
Running unit tests for scipy
NumPy version 1.10.4
NumPy relaxed strides checking option: False
NumPy is installed in /home/user/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.17.0
SciPy is installed in /home/user/anaconda/lib/python2.7/site-packages/scipy
Python version 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.config: INFO: Excluding tests matching ['f2py_ext', 'f2py_f90_ext', 'gen_ext', 'pyrex_ext', 'swig_ext']
/home/user/anaconda/lib/python2.7/site-packages/numpy/lib/utils.py:99: DeprecationWarning: `scipy.weave` is deprecated, use `weave` instead!
  warnings.warn(depdoc, DeprecationWarning)
....... ignore the middle parts ........
test_interpolative.TestInterpolativeDecomposition.test_id(<type 'numpy.float64'>,) ... ok
test_interpolative.TestInterpolativeDecomposition.test_id(<type 'numpy.complex128'>,) ... ok
test_interpolative.TestInterpolativeDecomposition.test_rand ... Segmentation fault (core dumped)

```

**Comment by insertinterestingnamehere** [comment] 2016-03-02 18:45
@pv thanks for the instructions for reproducing it. Yes, the binaries are built with a fairly old gfortran. Investigating locally now.

**Comment by lileipku00** [comment] 2016-03-02 18:47
@pv  Yes, exactly.

but I didn't create any new conda env.

**Comment by insertinterestingnamehere** [comment] 2016-03-02 19:02
I'm seeing this with Python 3.5, Ubuntu 15.10, on a root install as well.

**Comment by pv** [comment] 2016-03-02 19:03
@insertinterestingnamehere: what does "root install" mean --- packages provided by ubuntu, or compiled yourself, or built by anaconda? I am not able to replicate this except using anaconda binaries.

This is a duplicate of gh-2939, and is a known anaconda issue https://github.com/ContinuumIO/anaconda-issues/issues/59

**Comment by insertinterestingnamehere** [comment] 2016-03-02 19:06
Sorry for the ambiguity, I mean the root conda environment.

**Comment by lileipku00** [comment] 2016-03-02 19:21
And how abou these things

```
test_syr2k_wrong_c (test_blas.TestBLAS3Syr2k) ... 0-th dimension must be fixed to 3 but got 15
test_syrk_wrong_c (test_blas.TestBLAS3Syrk) ... 0-th dimension must be fixed to 3 but got 5
test_her2 (test_blas.TestFBLAS2Simple) ... 0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
test_syr2 (test_blas.TestFBLAS2Simple) ... 0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
test_syr_her (test_blas.TestFBLAS2Simple) ... 0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
0-th dimension must be fixed to 4 but got 2
```

Do they matter?

**Comment by pv** [comment] 2016-03-02 19:23
@lileipku00: No.

**Comment by lileipku00** [comment] 2016-03-03 16:57
what exactly is the influence of the failure of `test_interpolative.TestInterpolativeDecomposition.test_rand`?

Some functions of scipy would be unavailable?

**Comment by ilanschnell** [comment] 2016-03-03 22:31
I've rebuild all Linux `scipy` 0.17.0 conda packages using gfortran 4.4.7 (was 4.1.2), on and also updated `libgfortran` to 3.0.  I can run the tests without can segfaults.

**Comment by insertinterestingnamehere** [comment] 2016-03-03 23:37
Thanks @ilanschnell for updating the public repos! Thanks @groutr for spending some time on this with me on this yesterday as well. I can confirm that this fix is sufficient to avoid the crash. `conda update scipy` should be enough to fix this now.

**Comment by lileipku00** [comment] 2016-03-04 13:24
@insertinterestingnamehere 

I run `scipy.test` again. There are 5 failures. Do they matter?

``

======================================================================
FAIL: test_pilutil.test_imread_indexed_png
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/home/user/anaconda/lib/python2.7/site-packages/scipy/misc/tests/test_pilutil.py", line 143, in test_imread_indexed_png
    assert_array_equal(im, data)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 787, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 3.33333333333%)
 x: array([[[127,   0, 255, 255],
        [127,   0, 255, 255],
        [127,   0, 255, 255],...
 y: array([[[127,   0, 255, 255],
        [127,   0, 255, 255],
        [127,   0, 255, 255],...

======================================================================
FAIL: test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LR', None, None, <class 'scipy.sparse.csr.csr_matrix'>, None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/anaconda/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py", line 259, in eval_evec
    assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1359, in assert_allclose
    verbose=verbose, header=header)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.00178814, atol=0.000357628
error for eigs:standard, typ=f, which=LR, sigma=None, mattype=csr_matrix, OPpart=None, mode=normal
(mismatch 50.0%)
 x: array([[-0.138842+0.j, -1.071121+0.j],
       [ 0.089628+0.j, -1.398013+0.j],
       [-0.217014+0.j, -0.939684+0.j],...
 y: array([[-0.060206-0.084716j, -1.071120+0.j      ],
       [ 0.074975+0.105497j, -1.398013+0.j      ],
       [-0.133267-0.18752j , -0.939684+0.j      ],...

======================================================================
FAIL: test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LR', None, (0.1+0.1j), <function aslinearoperator at 0x7f44bbed36e0>, 'i')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/anaconda/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py", line 259, in eval_evec
    assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1359, in assert_allclose
    verbose=verbose, header=header)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.00178814, atol=0.000357628
error for eigs:standard, typ=f, which=LR, sigma=(0.1+0.1j), mattype=aslinearoperator, OPpart=i, mode=normal
(mismatch 50.0%)
 x: array([[-0.706668+0.j,  0.054353+0.j],
       [ 0.396467+0.j,  0.058940+0.j],
       [ 0.292872+0.j,  0.028156+0.j],...
 y: array([[-0.726096+0.j,  0.054353+0.j],
       [ 0.373738-0.j,  0.058940+0.j],
       [ 0.276852-0.j,  0.028156+0.j],...

======================================================================
FAIL: test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LR', None, 0.1, <function aslinearoperator at 0x7f44bbed36e0>, 'r')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/anaconda/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py", line 259, in eval_evec
    assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1359, in assert_allclose
    verbose=verbose, header=header)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.00178814, atol=0.000357628
error for eigs:standard, typ=f, which=LR, sigma=0.1, mattype=aslinearoperator, OPpart=r, mode=normal
(mismatch 50.0%)
 x: array([[-0.116497+0.j, -0.054353+0.j],
       [ 0.138007+0.j, -0.058940+0.j],
       [-0.212302+0.j, -0.028156+0.j],...
 y: array([[-0.056986+0.080185j, -0.054353+0.j      ],
       [ 0.064394-0.090609j, -0.058940+0.j      ],
       [-0.125040+0.175944j, -0.028156+0.j      ],...

======================================================================
FAIL: test_arpack.test_real_nonsymmetric_modes(False, <std-real-nonsym>, 'f', 2, 'LI', None, 0.1, <function aslinearoperator at 0x7f44bbed36e0>, 'r')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/anaconda/lib/python2.7/site-packages/scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py", line 259, in eval_evec
    assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1359, in assert_allclose
    verbose=verbose, header=header)
  File "/home/user/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.00178814, atol=0.000357628
error for eigs:standard, typ=f, which=LI, sigma=0.1, mattype=aslinearoperator, OPpart=r, mode=normal
(mismatch 100.0%)
 x: array([[ 0.057963+0.j,  0.026631+0.j],
       [ 0.061296+0.j, -0.050508+0.j],
       [ 0.029571+0.j,  0.108072+0.j],...
 y: array([[ 0.054282+0.j      , -0.042632+0.059987j],
       [ 0.059152+0.j      ,  0.051975-0.073134j],
       [ 0.028403+0.j      , -0.062187+0.087503j],...

----------------------------------------------------------------------
Ran 21567 tests in 1215.017s

FAILED (KNOWNFAIL=150, SKIP=1701, failures=5)
```

**Comment by insertinterestingnamehere** [comment] 2016-03-04 16:52
I don't know what would cause the first one. The others look like precision issues with ill conditioned problems and are likely not serious. It'd be nice if someone else could confirm that that's a reasonable assessment.

**Comment by caspervdw** [comment] 2016-03-04 19:46
Recently, I am getting `ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory` on Travis tests with conda scipy 0.16 on both Py2.7 and Py3.4.

The `ImportError` occurs at `from scipy.spatial import cKDTree`

The Travis configuration can be seen here: https://github.com/soft-matter/trackpy/blob/master/.travis.yml

Could this issue be related?

**Comment by insertinterestingnamehere** [comment] 2016-03-05 01:45
A few of these errors have been showing up today when the latest bugfix release for numpy or scipy isn't getting used. It looks like the issue in this case is that when you install scipy and numpy though. For example `conda crate -n testenv -y python=2.7 numpy=1.9 scipy=0.16` pulls in scipy 0.16.0 rather than 0.16.1. @ilanschnell we probably need a build of scipy 0.16.1 with numpy 1.9.3. Specifying libgfortran=1.0 should fix it temporarily, but that'll need to be removed once the other build is available.

**Comment by rgommers** [comment] 2018-09-02 11:43
I think this is no longer relevant.

**Closed by rgommers** 2018-09-02 11:43 UTC
Labels: 3rd party binaries
