### ISSUE TITLE
BUG: Import `scipy.optimize` adds `"constants"` to `sys.modules`

### ISSUE THREAD

**Issue by seberg** [scipy/scipy#13377] opened 2021-01-12 04:06 UTC
It seems that importing `scipy.optimize` adds at least `"constants"` to `sys.modules` which will cause overshadowing of a local `constants.py` further up `sys.path` if imported after `scipy.optimize` (in this case it was imported by sklearn).

I did not try/think it through, but I guess that the `setup.py` is incorrect and:
```
    ext = config.add_extension(
        'constants',
        sources=['cython/src/constants.cxx'],
        include_dirs=[
            'cython/src/',
            'src/',
            'src/io/',
            'src/lp_data/',
            'src/simplex/',
        ],
```
should not be `'constants'` but rather `'scipy.optimize._highs.constants'`?

#### Reproducing code example:

```
Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import sys

In [2]: "constants" in sys.modules.keys()  # as expected, not already imported
Out[2]: False

In [3]: from scipy import optimize

In [4]: sys.modules["constants"]  # Now it is the scipy module!
Out[4]: <module 'scipy.optimize._highs.constants' from '.../python3.8/site-packages/scipy/optimize/_highs/constants.cpython-38-x86_64-linux-gnu.so'>

In [5]: import scipy

In [6]: scipy.__version__
Out[6]: '1.6.0'
```

**Comment by mdhaber** [comment] 2021-01-12 06:48
Duplicate of gh-13350.

**Closed** 2021-01-12 06:49 UTC
