### ISSUE TITLE
isnan errors compiling scipy/special/Faddeeva.cc with clang++

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#5689] opened 2016-01-08 03:08 UTC
I'm seeing build failures with `clang++`, see: https://s3.amazonaws.com/archive.travis-ci.org/jobs/100974300/log.txt

```
[39mclang++: scipy/special/Faddeeva.cc[0m

scipy/special/Faddeeva.cc:213:14: error: use of undeclared identifier 'isnan'; did you mean 'std::isnan'?

    else if (my_isnan(x))

             ^

scipy/special/Faddeeva.cc:134:18: note: expanded from macro 'my_isnan'

#define my_isnan npy_isnan

                 ^

/Users/travis/build/MacPython/scipy-wheels/venv/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:153:30: note: expanded from macro 'npy_isnan'

        #define npy_isnan(x) isnan((x))

                             ^

/usr/include/c++/4.2.1/cmath:551:5: note: 'std::isnan' declared here

    isnan(_Tp __f) { return ::__gnu_cxx::__capture_isnan(__f); }
```

I guess this is related to : https://github.com/scipy/scipy/pull/5643

**Comment by rgommers** [comment] 2016-01-08 18:38
Hmm, odd. I'll see if I can reproduce this on OS X.

@ev-br this means that gh-5643 may need to be reverted for 0.17.0

**Comment by rgommers** [comment] 2016-01-08 19:06
On Ubuntu 14.04 with ``export CC=clang; export CXX=clang++``:

    building 'scipy.special._ufuncs_cxx' extension
    compiling C sources
    C compiler: clang -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC

    compile options: '-I/home/rgommers/Code/bldscipy/scipy/special -I/home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include -I/home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
    clang: scipy/special/sf_error.c
    compiling C++ sources
    C compiler: clang++ -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC

    compile options: '-I/home/rgommers/Code/bldscipy/scipy/special -I/home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include -I/home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
    clang++: scipy/special/_ufuncs_cxx.cxx
    In file included from scipy/special/_ufuncs_cxx.cxx:253:
    In file included from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:
    /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^

    ... <useless Cython warnings> ...

    18 warnings generated.
    clang++: scipy/special/Faddeeva.cc
    clang++: scipy/special/_faddeeva.cxx
    clang++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-i686-2.7/scipy/special/sf_error.o build/temp.linux-i686-2.7/scipy/special/_ufuncs_cxx.o build/temp.linux-i686-2.7/scipy/special/_faddeeva.o build/temp.linux-i686-2.7/scipy/special/Faddeeva.o -L/home/rgommers/.local/lib/python2.7/site-packages/numpy/core/lib -Lbuild/temp.linux-i686-2.7 -lnpymath -lm -o scipy/special/_ufuncs_cxx.so
    building 'scipy.special._ellip_harm_2' extension

Builds fine and tests pass.

**Comment by rgommers** [comment] 2016-01-08 19:08
And also on OS X 10.10 things work fine for me out of the box. Relevant part of build log:

    building 'scipy.special._ufuncs_cxx' extension
    compiling C sources
    C compiler: clang -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
    
    compile options: '-I/Users/rgommers/Code/scipy/scipy/special -I/Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/include -I/Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/include -I/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
    clang: scipy/special/sf_error.c
    compiling C++ sources
    C compiler: clang++ -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall
    
    compile options: '-I/Users/rgommers/Code/scipy/scipy/special -I/Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/include -I/Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/include -I/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
    clang++: scipy/special/_ufuncs_cxx.cxx
    In file included from scipy/special/_ufuncs_cxx.cxx:252:
    In file included from /Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:
    /Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    scipy/special/_ufuncs_cxx.cxx:4682:28: warning: unused function '__Pyx_PyObject_AsString' [-Wunused-function]
    
    ... <useless Cython warnings> ...
    
    18 warnings generated.
    clang++: scipy/special/Faddeeva.cc
    clang++: scipy/special/_faddeeva.cxx
    clang++ -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.9-x86_64-2.7/scipy/special/sf_error.o build/temp.macosx-10.9-x86_64-2.7/scipy/special/_ufuncs_cxx.o build/temp.macosx-10.9-x86_64-2.7/scipy/special/_faddeeva.o build/temp.macosx-10.9-x86_64-2.7/scipy/special/Faddeeva.o -L/Users/rgommers/Library/Python/2.7/lib/python/site-packages/numpy/core/lib -Lbuild/temp.macosx-10.9-x86_64-2.7 -lnpymath -o scipy/special/_ufuncs_cxx.so
    building 'scipy.special._ellip_harm_2' extension

**Comment by WarrenWeckesser** [comment] 2016-01-08 21:38
I get the same error as Matthew reported.  I have OS X 10.9.5.

**Comment by WarrenWeckesser** [comment] 2016-01-08 21:46
There was another issue involving `isinf`: https://github.com/scipy/scipy/pull/5314

**Comment by dhomeier** [comment] 2016-01-08 22:00
Builds on 10.11 as well, looks like a (<=?) 10.9 problem only:
```
building 'scipy.special._ufuncs_cxx' extension
compiling C sources
C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -Wstrict-prototypes -I/sw/include

compile options: '-I/scratch.noindex/fink.build/scipy-py35-0.17.0rc2-1/scipy-0.17.0rc2/scipy/special -I/sw/lib/python3.5/site-packages/numpy/core/include -I/sw/lib/python3.5/site-packages/numpy/core/include -I/sw/include/python3.5m -c'
clang: scipy/special/sf_error.c
compiling C++ sources
C compiler: clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -fwrapv -O3 -Wall -I/sw/include

compile options: '-I/scratch.noindex/fink.build/scipy-py35-0.17.0rc2-1/scipy-0.17.0rc2/scipy/special -I/sw/lib/python3.5/site-packages/numpy/core/include -I/sw/lib/python3.5/site-packages/numpy/core/include -I/sw/include/python3.5m -c'
clang++: scipy/special/_faddeeva.cxx
clang++: scipy/special/Faddeeva.cc
clang++: scipy/special/_ufuncs_cxx.cxx
In file included from scipy/special/_ufuncs_cxx.cxx:253:
In file included from /sw/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /sw/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /sw/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:
/sw/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by \
...
19 warnings generated.
clang++ -bundle -L/sw/lib/python3.5/config-3.5m -lpython3.5m -L/sw/lib -I/sw/include build/temp.macosx-10.11-x86_64-3.5/scipy/special/sf_error.o build/temp.macosx-10.11-x86_64-3.5/scipy/special/_ufuncs_cxx.o build/temp.macosx-10.11-x86_64-3.5/scipy/special/_faddeeva.o build/temp.macosx-10.11-x86_64-3.5/scipy/special/Faddeeva.o -L/sw/lib/python3.5/site-packages/numpy/core/lib -L/sw/lib -Lbuild/temp.macosx-10.11-x86_64-3.5 -lnpymath -o build/lib.macosx-10.11-x86_64-3.5/scipy/special/_ufuncs_cxx.cpython-35m-darwin.so -Wl,-undefined -Wl,dynamic_lookup -Wl,-bundle
building 'scipy.special._ellip_harm_2' extension
```

**Comment by matthew-brett** [comment] 2016-01-08 22:01
I'm on 10.9.5, I think the travis-ci machines are the same.

Like you (Ralf) I get no error when compiling for homebrew Python 2.7.11, but I do get this error compiling for Python.org 2.7.11.

Python.org uses the 10.6 SDK - could that be the problem?

**Comment by matthew-brett** [comment] 2016-01-08 22:24
I get the same error building with Python.org Python on OSX 10.11.2

**Comment by matthew-brett** [comment] 2016-01-08 22:59
I think it's the SDK - if I do `export MACOSX_DEPLOYMENT_TARGET=10.9` for the Python.org build, it works, if I then do `export MACOSX_DEPLOYMENT_TARGET=10.6` it breaks again.

**Comment by dhomeier** [comment] 2016-01-08 23:07
I could not fully penetrate the travis setup, but as it is building in `build/temp.macosx-10.6-intel-2.7`, that seems to be what it's using as well.

**Comment by matthew-brett** [comment] 2016-01-08 23:08
Yes, travis-ci will use the Python.org default which is `MACOSX_DEPLOYMENT_TARGET=10.6`.

**Comment by matthew-brett** [comment] 2016-01-08 23:10
Building with homebrew Python and `export MACOSX_DEPLOYMENT_TARGET=10.6` also generates the error for me.

**Comment by WarrenWeckesser** [comment] 2016-01-08 23:10
> if I do export `MACOSX_DEPLOYMENT_TARGET=10.9` [...]

That works for me, too. (Mac OS X 10.9.5, Anaconda Python 2.7.11).

**Comment by matthew-brett** [comment] 2016-01-08 23:14
Unfortunately `export MACOSX_DEPLOYMENT_TARGET=10.9` is not a good fix unless we want to give up on the 15 percent or so of OSX users using OSX < 10.9 : https://sparkle.adium.im/#osVersion

**Comment by WarrenWeckesser** [comment] 2016-01-08 23:33
FWIW, more data (Matthew may have already tried these): the error also occurs if I set `MACOSX_DEPLOYMENT_TARGET` to `10.7` or `10.8`.

**Comment by rgommers** [comment] 2016-01-09 16:49
The problem stems from ``cmath``, which conditionally undefines ``isnan``, ``isinf`` and some other C99 macros. Apparently the conditions for actually ``undef``ing changed from OS X 10.8 to 10.9. So we fixed something for when ``isnan`` was defined twice when including both ``cmath`` and ``npy_math.h``, but now we run into the situation that it's not defined at all. Sigh.

The workaround for ``isinf`` in gh-5314 was to define it inside the ``ckdtree`` code instead of using it from ``npy_math``. That's also what is recommended in various issues on Stackoverflow and other places. I couldn't find a good (easy) solution. ``npy_math`` itself can use builtins, but that's not easy to reuse (see https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/npy_math.h#L159)

The workaround would be to instead of ``npy_isnan`` use something like

    int isnan(double x) { return x != x; }

The offending ``cmath`` code from my OS X install:

    #if _GLIBCXX_USE_C99_MATH
    #if !_GLIBCXX_USE_C99_FP_MACROS_DYNAMIC
    // These are possible macros imported from C99-land. For strict
    // conformance, remove possible C99-injected names from the global
    // namespace, and sequester them in the __gnu_cxx extension namespace.

    _GLIBCXX_BEGIN_NAMESPACE(__gnu_cxx)

      template<typename _Tp>
        inline int
        __capture_isinf(_Tp __f) { return isinf(__f); }

      template<typename _Tp>
        inline int
        __capture_isnan(_Tp __f) { return isnan(__f); }

    _GLIBCXX_END_NAMESPACE

    // Only undefine the C99 FP macros, if actually captured for namespace movement
    #undef fpclassify
    #undef isfinite
    #undef isinf
    #undef isnan
    #undef isnormal
    #undef signbit
    #undef isgreater
    #undef isgreaterequal
    #undef isless
    #undef islessequal
    #undef islessgreater
    #undef isunordered

    _GLIBCXX_BEGIN_NAMESPACE(std)

      template<typename _Tp>
        inline int
        isinf(_Tp __f) { return ::__gnu_cxx::__capture_isinf(__f); }

      template<typename _Tp>
        inline int
        isnan(_Tp __f) { return ::__gnu_cxx::__capture_isnan(__f); }
    _GLIBCXX_END_NAMESPACE

    #endif /* _GLIBCXX_USE_C99_FP_MACROS_DYNAMIC */
    #endif

Useful to find back: ``cmath`` is located at ``/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1/cmath`` for me.

**Comment by rgommers** [comment] 2016-01-09 17:19
From http://stackoverflow.com/questions/18128899/is-isnan-in-the-std-namespace-more-in-general-when-is-std-necessary-optio:

    So to sum up: Either include <math.h> and use isnan or include <cmath> and 
    use std::isnan, everything else is non-portable.

Some more issues at http://stackoverflow.com/questions/2249110/how-do-i-make-a-portable-isnan-isinf-function.

Comment from ``Faddeeva.cc``:

    // use numpy's versions, since std:: versions only available in C++11
    #define my_isinf npy_isinf
    #define my_isnan npy_isnan

So ``std::isnan`` is also not portable. ``npy_math`` and ``cmath`` don't mix well. The two options seem to be:

- don't use ``npy_math`` but simply define ``isnan`` as ``x != x`` (and  ``isinf`` in a similar way)
- attempt to fix things by messing with compile options in ``setup.py`` when using both ``cmath`` and ``npy_math``.

Anyone have a better idea?

**Comment by rgommers** [comment] 2016-01-09 17:52
Educational and related (to answer the question I had "why use ``cmath`` at all?"): 

http://stackoverflow.com/questions/13889467/should-i-include-xxxx-h-or-cxxxx-in-c-programs
http://stackoverflow.com/questions/8734230/math-interface-vs-cmath-in-c

**Comment by rgommers** [comment] 2016-01-09 18:19
It's pretty difficult to find a description of what ``MACOSX_DEPLOYMENT_TARGET`` actually does, so more educational material (from [here](http://www.cocoabuilder.com/archive/xcode/287223-mac-os-deployment-target.html)):

> > What exactly does "Mac OS X Deployment Target" do? It seems to have
> > side-effects beyond controlling whether linking is strong or weak.

> Exactly: it sets the -mmacos-version-min flag to the compiler and linker.  This causes the compiler and linker to do the following:
• Generate code for the runtime model of that version of the OS
• Link against the runtime libraries for that version of the OS
• Weak-link against imported library symbols that are defined to exist in the system headers but are not implemented in the deployment target version
• Any other behaviors your project build settings, source or header files, or Info.plists base off of MACOSX_DEPLOYMENT_TARGET

**Comment by rgommers** [comment] 2016-01-09 20:34
Proposal for a fix at gh-5697. Still needs testing on OS X.

**Comment by andyfaff** [comment] 2016-01-13 00:44
Given that this prevent building on OS X should this issue be considered a blocker for the 0.17 release?

**Comment by dhomeier** [comment] 2016-01-13 01:09
Has anyone tested on 10.9 or below yet? On 10.10 I could trigger the error by explicitly building with
```
export MACOSX_DEPLOYMENT_TARGET=10.6
CC=clang CXX=clang++ FFLAGS=-ff2c FC=/sw/lib/gcc5/bin/gfortran ATLAS=None LAPACK=/usr/lib BLAS=/usr/lib python3.5 setup.py build --fcompiler gnu95
```
Same works now with gh-5697.

**Comment by rgommers** [comment] 2016-01-13 19:29
Yes, this is indeed a blocker for 0.17.0.

**Comment by ev-br** [comment] 2016-01-17 13:25
fixed in gh-5697, closing.

**Closed by ev-br** 2016-01-17 13:25 UTC
Labels: Build issues
