### ISSUE TITLE
[Feature Request]: scipy.sparse.linalg.pinv

### ISSUE THREAD

**Issue by zfrenchee** [scipy/scipy#8216] opened 2017-12-13 23:19 UTC
Hello, 

I'd like to get the pseudo-inverse of a sparse matrix. It seems like this isn't yet possible in scipy. 

My current options seem to be `np.linalg.pinv(sparse_matrix.todense())` or if my matrix was better behaved, `scipy.sparse.linalg.inv(sparse_matrix)`. The second of those currently gives me `RuntimeError: Factor is exactly singular` which I expect. I'm using the first of those to solve my immediate problem, but would love to see `scipy.sparse.linalg.pinv` implemented!

**Comment by charris** [comment] 2017-12-14 00:52
The pseudo-inverse of a sparse matrix is unlikely to be sparse. What is the problem that you want to solve?

**Comment by zfrenchee** [comment] 2017-12-14 01:01
@charris thanks for getting back to me! 

I'm computing the pseudo-inverse of a laplacian matrix of a graph. Having done the pinv of the dense matrix, from a quick manual inspection, it seems most of the entries are 0. Is there a better way of computing the pseudo-inverse of the laplacian of a graph? Or maybe some other matrix which captures roughly the same information which is easier to compute?

Thanks!

**Comment by charris** [comment] 2017-12-14 02:19
Let me ask for one more level back. Why do you want the pseudo inverse of the laplacian of a graph?

**Comment by zfrenchee** [comment] 2017-12-14 07:13
@charris I'd like a diffusion operator for vectors defined on the graph. The inverse of the laplacian typically looks like a diffusion operator. I think this might provide a more meaningful distance metric between vectors defined on the graph, like so: 

<img width="1136" alt="screen shot 2017-11-24 at 1 18 29 pm" src="https://user-images.githubusercontent.com/2761597/33979875-338930ac-e05b-11e7-9921-01a54fb1ffae.png">

**Comment by perimosocordiae** [comment] 2017-12-14 15:12
This might not be exactly what you're going for, but I might do this with Locality Preserving Projections (LPP), using my [`graphs` package](https://github.com/all-umass/graphs):

```python
In [1]: from graphs.generators import chain_graph

In [2]: G = chain_graph(5)

In [3]: G.laplacian().toarray()
Out[3]:
array([[ 1, -1,  0,  0,  0],
       [-1,  2, -1,  0,  0],
       [ 0, -1,  2, -1,  0],
       [ 0,  0, -1,  2, -1],
       [ 0,  0,  0, -1,  1]], dtype=int64)

In [4]: x = np.array([[1,0,0,0,0],[1,1,0,0,0],[1,0,0,0,1]], dtype=float).T

In [5]: proj = G.locality_preserving_projections(x)

In [6]: p1, p2, p3 = x.dot(proj).T

In [7]: np.linalg.norm(p1 - p2)
Out[7]: 1.7975634010071553

In [8]: np.linalg.norm(p1 - p3)
Out[8]: 2.7019846539606274
```

LPP uses the sparse Laplacian to compute a projection matrix, such that distances in the projected space approximate diffusion along the graph.

**Comment by zfrenchee** [comment] 2017-12-14 19:34
@perimosocordiae that's pretty awesome. I'll look into it! 

@charris Please feel free to do with this issue as you wish. If you don't think there is cause for a pinv op for sparse matrices, please close this issue. As I mentioned, I computed the pinv on the dense version of the matrix, and found anecdotally that most of the entries seemed to be zero, but that might be extraneous. Given that I've done this computation already with the dense matrix, and given @perimosocordiae's other interesting suggestion, I no longer "have" this issue.

**Comment by pmli** [comment] 2017-12-19 16:50
@zfrenchee As far as I can see, you don't need the pseudo-inverse explicitly, but just a way to multiply it with a vector, i.e. solve a least squares problem, for which you could use, e.g. `scipy.sparse.linalg.lsmr`. Here is an example:

```python
>>> import networkx as nx
>>> import scipy.sparse.linalg as spsla
>>> import numpy as np
>>> n = 5
>>> G = nx.path_graph(n)
>>> L = nx.laplacian_matrix(G)
>>> x1 = np.zeros((n,)); x1[0] = 1
>>> x2 = np.zeros((n,)); x2[:2] = 1
>>> x3 = np.zeros((n,)); x3[[0, -1]] = 1
>>> d12 = x1 - x2
>>> d13 = x1 - x3
>>> d12.dot(spsla.lsmr(L, d12)[0])
0.59999999999999909
>>> d13.dot(spsla.lsmr(L, d13)[0])
1.2000000000000008
```

This code should work fine for much larger `n`, e.g. `n = 10000`.

The general recommendation is to avoid using `inv` and `pinv`, and instead use a linear system or a least squares solver (I would guess this is what @charris was going for). Using `inv` or `pinv` is rarely justified, at least I'm only aware of the use of `inv` in the matrix sign function iteration.

**Comment by ilayn** [comment] 2018-01-22 01:22
Seems like the issue is settled so closing.

**Closed by ilayn** 2018-01-22 01:22 UTC
