### ISSUE TITLE
Calling `len()` on the `scipy.spatial.transform.rotation.Rotation` object with one rotation should return 1 

### ISSUE THREAD

**Issue by MatusGasparik** [scipy/scipy#13452] opened 2021-01-29 07:31 UTC
When calling the `len()` function on the `scipy.spatial.transform.rotation.Rotation` object with exactly one rotation, it currently raises a TypeError instead of returning 1.

([Link to source code](https://github.com/scipy/scipy/blob/0cb5a06c9465b99737f914dce48d9f5aa4400e31/scipy/spatial/transform/rotation.pyx#L537))

#### Reproducing code example:

```
from scipy.spatial.transform import Rotation as R

r = R.from_quat([1, 0, 0, 0])
print(len(r))    # raises TypeError
```

#### Error message:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-227-c5f861eb1f8a> in <module>
      4 try:
----> 5     print(len(r))
      6 except Exception as e:

rotation.pyx in scipy.spatial.transform.rotation.Rotation.__len__()

TypeError: Single rotation has no len().
```

Calling `len()` on an object with 2 rotations returns 2 as expected:

```
r = R.from_quat([[1, 0, 0, 0],
                 [1, 0, 0, 0]])
print(len(r))    # returns 2
```

Moreover, when creating a rotation object using the `from_euler()` class method, it correctly returns 1 for one rotation around a single coordinate axis, but raises the above error again for a rotation around more than one coordinate axes:

```
r = R.from_euler('x', [0.1])
print(len(r))    # returns 1

r = R.from_euler('xz', [0.1, 0.1])
print(len(r))    # raises TypeError
```

#### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.0 1.19.5 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)
```

**Comment by AtsushiSakai** [comment] 2021-01-29 11:25
I think the answer to this issue is in https://github.com/scipy/scipy/pull/12398

**Comment by rgommers** [comment] 2022-02-22 21:38
This still works this way and seems inconsistent. I don't immediately see how gh-12398 answers whether this is intended or not - looks like a bug to me.

**Comment by WarrenWeckesser** [comment] 2022-07-27 18:15
Based on the comments in https://github.com/scipy/scipy/issues/16663 (https://github.com/scipy/scipy/issues/16663#issuecomment-1194117213 in particular) I think this is intended behavior.  `r = Rotation([1, 0, 0, 0])` is like a *scalar* rotation, so the object has no length, and `len(r)` should raise a `TypeError`.  `r2 = Rotation([[1, 0, 0, 0], [0, 1, 0, 0]])` is like a sequence of two rotations, and `len(r2)` is 2.

If my interpretation is correct, we can close this issue.

**Closed** 2022-07-30 21:31 UTC
Labels: defect, scipy.spatial
