### ISSUE TITLE
dual_annealing import error

### ISSUE THREAD

**Issue by Lisenndre** [scipy/scipy#10060] opened 2019-04-13 09:17 UTC
Hi all, 
I got anaconda 3.7 and trying to import dual_annealing and getting attribure error:
module 'scipy.optimize' has no attribute 'dual_annealing'. 
It works with the other algorithms (differential_evolution, Nelder-Mead...), but I really prefer this one in my case, so are there any options to handle it?

**Comment by rgommers** [comment] 2019-04-13 10:27
`dual_annealing` was introduced in scipy 1.2.0. you can check what version you have installed via `$ conda list scipy` or `>>> scipy.__version__`. You probably just have to upgrade

**Comment by rgommers** [comment] 2019-04-13 10:28
I'm closing this because it's not a bug in scipy. Feel free to ask more questions of course.

**Closed by rgommers** 2019-04-13 10:27 UTC
