### ISSUE TITLE
ENH: Implement methods to get `loc` and `scale` of `rv_frozen`

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#15863] opened 2022-03-24 18:31 UTC
### Is your feature request related to a problem? Please describe.

May be needed to access.

### Describe the solution you'd like.

`.loc` and `.scale`, or methods.

### Describe alternatives you've considered.

No.

### Additional context (e.g. screenshots, GIFs)

Messing with args when differrent dists have different args and they can be either keyword or positional ones is extremily inconvenient. `loc` and `scale` are universal ones, so should be available easily.

**Comment by mdhaber** [comment] 2022-03-24 20:42
Please email the [scipy-dev mailing list](https://mail.python.org/mailman3/lists/scipy-dev.python.org/) proposing the idea. This seems very easy to implement, but all public API changes need to go to the mailing list before they are implemented. Please make a case why this would be useful (in general, not just to you) and invite people to discuss here (e.g. whether they can be attributes or should be methods).

**Comment by KOLANICH** [comment] 2022-04-16 19:12
I'm sorry, but I don't want to subscribe the mailing list. Could anyone do it for me?

**Comment by mdhaber** [comment] 2022-04-17 16:35
Closing as a duplicate of gh-9321.

**Closed by mdhaber** 2022-04-17 16:35 UTC
Labels: scipy.stats, enhancement
