### ISSUE TITLE
scipy.optimize.differential_evolution: workers problem

### ISSUE THREAD

**Issue by EylonCohen** [scipy/scipy#15047] opened 2021-11-16 10:09 UTC
I'm using the differential evolution algorithm to minimize some cost functions in a gym like env. at every cost evaluation, I'm computing the sum of several env costs. see code below .
the problem is, that if I use for instance workers=-1 I cant sum more the 2 env costs because the code seems to be stuck (it doesn't stop but the solver can't finish any iteration). the weird thing is that if I use 8 workers I can sum up to 5 env costs.
eventually, I need to sum at least 10 env costs and to use as many workers as possible...

p.s it is worth mentioning that I am not a software developer (I'm a mechanical engineer) and I have limited knowledge about multiprocessing.

code:
![image](https://user-images.githubusercontent.com/82363955/141962512-0128869a-b3b3-4ace-96fd-51d6ef56f281.png)
![image](https://user-images.githubusercontent.com/82363955/141962629-75958b35-93bd-496f-bf82-22541f58ad0e.png)

when I stop the code manually the this is what I get:
Process ForkPoolWorker-17:
Process ForkPoolWorker-10:
Process ForkPoolWorker-9:
Process ForkPoolWorker-6:
Process ForkPoolWorker-1:
Process ForkPoolWorker-11:
Process ForkPoolWorker-16:
Process ForkPoolWorker-7:
Process ForkPoolWorker-15:
Process ForkPoolWorker-13:
Process ForkPoolWorker-14:
Process ForkPoolWorker-5:
Process ForkPoolWorker-2:
Process ForkPoolWorker-8:
Process ForkPoolWorker-4:
Process ForkPoolWorker-12:
Traceback (most recent call last):
  File "/home/eilonn7/robosuite/robosuite/eylon's code/main.py", line 91, in <module>
    result = de(func=fitness_func, bounds=bounds, maxiter=1000, popsize=4, disp=True, workers=-1,
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py", line 329, in differential_evolution
    ret = solver.solve()
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py", line 854, in solve
    next(self)
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py", line 1208, in __next__
    trial_energies[feasible] = self._calculate_population_energies(
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/site-packages/scipy/optimize/_differentialevolution.py", line 972, in _calculate_population_energies
    calc_energies = list(self._mapwrapper(self.func,
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/site-packages/scipy/_lib/_util.py", line 471, in __call__
    return self._mapfunc(func, iterable)
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/eilonn7/Programs/anaconda3/envs/new_env/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by andyfaff** [comment] 2021-11-16 10:40
Github issues are intended for bugs/design requirements in the project, usage questions are better directed towards the user mailing list, https://scipy.org/mailing-lists/. When asking questions it's important to provide a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example) that enables people to help. It's not possible to do that here because you provided screenshots of the code, and the code doesn't look to be self contained.

In order to figure out whether it's an issue with `differential_evolution`, or your code it'll be worth trying to call your objective function in a parallel way, outside the `differential_evolution` code.

```
from multiprocessing import Pool

# let's assume that your objective function takes 5 parameters
# the following array is a proxy for a situation where we're going to
# call the objective function 20 times.
x = np.arange(100).reshape(20, 5)

with Pool(4) as pwl:
    output = pwl.map(func, x0)

print(output)
```

If you can't get something like this to work on your own objective function, then it definitely won't work inside of `differential_evolution`.

**Comment by andyfaff** [comment] 2022-08-16 21:52
Closing, as no MWE available.

**Closed by andyfaff** 2022-08-16 21:52 UTC
Labels: query
