### ISSUE TITLE
Savitzky Golay filter should have a module to account for error covariance

### ISSUE THREAD

**Issue by surhud** [scipy/scipy#5767] opened 2016-01-27 03:38 UTC
The module scipy.signal.savgol_filter (Savitzky-Golay filter) implementation in scipy does not account for the presence of errors or error covariance in the data, a very common case for any scientific use. The errors seem to have been neglected in the scientific literature often as well.

A separate code which implements these cases can be found here:
https://github.com/surhudm/savitzky_golay_with_errors

It would be good to incorporate this in scipy.signal. Please advise me on whether this should be separate from savgol_filter or included in it as a special case.

**Comment by rgommers** [comment] 2016-01-27 15:26
@surhud is your code based on a paper? Maybe @WarrenWeckesser (the original author of ``savitsky_golay``) understands what you mean, but it's not immediately obvious to me what your code is doing.

**Comment by ewmoore** [comment] 2016-01-27 16:20
One nice thing about savitzky golay is that its just a filter and we know how to make that fast.  Doing an explicit polynomial fit to each segment is equivalent but extremely slow.
```
In [37]: timeit xscipy = signal.savgol_filter(xm, 7, 3)
1000 loops, best of 3: 923 µs per loop

In [38]: timeit xnew1 = savgol_filter_werror(xm, 7, 3, np.ones_like(xm))
1 loops, best of 3: 6.9 s per loop

In [63]: np.allclose(xscipy, xnew1)
Out[63]: True
```
Here `xm` has 50,000 elements and there is a factor of ~7500 difference in run time.

@surhud, do you have some motivating example using real data?  And how did you decide that this was the appropriate approach?

**Comment by surhud** [comment] 2016-01-29 09:12
Sorry guys, I did not get notifications for your comments. I am attaching a pdf file of the document I wrote about this. The moderators on www.arxiv.org are giving me hard time to get this submitted. But I am attaching it here. See figure 1 in the attached file, where I sampled a simple sine curve with unequal errors on data points, and compare the modified filter to the traditional Savitzky-Golay filter. As expected, the modified filter does a better job by accounting for the errors and covariance.

I developed this code when I was facing a problem for using Savitzky Golay filter on noisy data with covariance (http://arxiv.org/abs/1601.06063v1 and submitted to the Astrophysical Journal).

[paper.pdf](https://github.com/scipy/scipy/files/109461/paper.pdf)

**Comment by surhud** [comment] 2016-01-29 09:19
@ewmoore Once you start accounting for errors or covariance, the implementation will be slow, but it definitely performs better (as shown in the attached image from the paper uploaded in the previous comment). In my use case I did not have to worry about time, as I had to do the filtering just once on a fairly small data set.

The traditional SG filter works by convolving with a fixed set of coefficients, which makes it really fast, but it is not useful when the errors are unequal as the outliers dominate the filtering (which is what I wanted to avoid). 

![image](https://cloud.githubusercontent.com/assets/456845/12671684/bd9bfa8a-c6b4-11e5-9a60-f4cd1c642e2f.png)

**Comment by josef-pkt** [comment] 2016-01-29 15:57
Just a general idea (I was playing a bit similarly with fft smoothing of data that is robust to outliers and to missing values. A home made algorithm based on some hints in the literature.)

Doing weighted regression (WLS) would not work with a convolution because of the different weights. However, it is possible to adjust the observations that are identified as outliers and shrink them towards the predicted/smoothed line, and then iterate a few times.

In my case, I used local MAD (median absolute deviation) to get the local variance estimate. With constant variance the standard error of the smoothing/prediction would just be constant, AFAICS.
(IIRC, I needed the median filter from scipy.ndimage or somewhere.)

**Comment by surhud** [comment] 2016-01-29 19:48
@josef-pkt That idea may be ok for the case when errors are not known. However with known errors or covariance, doesn't it make sense to just use them instead? I guess you are making the case for speed versus accuracy. I would like to suggest that the option should be present in the module so that the user can make this choice rather than the software deciding on it.

**Comment by josef-pkt** [comment] 2016-01-29 20:10
@surhud   If you already know the standard errors/weights, then you can skip the step to estimate the error variance.

I'm not a scipy.signal person, so here is just IMO:
IMO, the Savitzky-Golay filter is useful because it reduces to a fast convolution because we have a fixed equal spaced grid as explanatory variable. Without this feature it is just a special case of local polynomial estimation. (which is in statsmodels under kernel regression for general x, and is slow because of the explicit python loop over all observations that hasn't been moved to cython.)
If changing an option in a function of a long signal increases the computation time by a very large amount, will be at least an unexpected surprise for users, unless they read and remember the big warning in the docstring. 

My impression is that if we adjust the observations instead of using weights we get something very close (I didn't try the math) to your WLS version, but can be implemented using a few iterations of the fast convolution.

**Comment by josef-pkt** [comment] 2016-01-29 20:17
Phrased in another way: Doing the local polynomial fit with weights is useful, however I doubt merging it into Savitzky-Golay is a good idea.

**Comment by rkern** [comment] 2016-01-29 21:29
I would agree with that assessment.

**Comment by surhud** [comment] 2016-01-29 23:04
Although that requires explicit coding of the windowing used in the Savitzky Golay algorithm which this code does for you. Having a convenient function in a widely used library as scipy helps both to raise awareness (as I said many people use the filter even when the errors are known). I do not mean that this should be the standard used, it should be reverted to only when errors are known.

I should also add that it seems Matlab allows its Savitzky Golay filter to account for weights, although not the covariance.

As I said while raising the issue, I was seeking guidance as to whether to incorporate this here. If you feel it is not the right place I will keep the code separate.

Thanks for suggestions.

**Comment by josef-pkt** [comment] 2016-01-30 00:27
matlab `specifies a weighting vector w with length f` where f is frame, sounds like it's using a weighted polynomial, but weights relative to the window and not for given observations.
That's a change that doesn't affect the ability to use convolution.

**Comment by surhud** [comment] 2016-01-30 00:38
Thanks for checking that. It makes much more sense then how they manage to get it to run fast In that case.

If everyone agrees to keep this separate then please feel free to close the issue.

**Comment by ewmoore** [comment] 2016-02-02 13:45
Okay.  Let's close this then.

**Closed by ewmoore** 2016-02-02 13:45 UTC
Labels: query, scipy.signal

**Comment by nmayorov** [comment] 2016-08-22 18:57
(I was asked in #6493) @surhudm 

I need to learn and think about it . The first objection that comes to mind is that Savitzky-Golay requires equally spaced `xdata` so it sort of leans towards efficient. but restrictive usage (what others already said).

If we can figure out efficient implementation that I believe it can (and even should) be included. If not --- I tend to agree with others that it's a bit clunky "know-how" thing, which shouldn't be mixed with a classic efficient signal processing algorithm.

**Comment by surhudm** [comment] 2016-08-23 00:54
@nmayorov Even without equally spaced xdata, once you have unequal covariant errors, the efficiency is reduced. I am not at all advocating adding this in savgol_filter. But whether this can be morphed in to a separate function. As I said previously, I (and I can easily imagine many other astronomers who use savgol_filter) have to routinely deal with data with unequal covariant errors.

If there is an efficient implementation, then that is definitely great to know about and include. But shouldn't usability and accuracy trump efficiency?

**Comment by nmayorov** [comment] 2016-08-23 17:50
Maybe be can try to include it into optimize/curve fitting, as `piecewise_polyfit` (or similar). What do you think?

**Comment by surhudm** [comment] 2016-08-23 21:44
Given that it wont be returning parameters, I am a little bit surprised
that you think optimize/curve fitting would be a better place for this. I
guess as long as we advertise this new function from savgol_filter page, it
should be ok.

**Comment by nmayorov** [comment] 2016-08-23 22:34
Maybe it's a bad idea indeed. I just thought that it wasn't really approved in `signal` too.

By the way, can't this problem be solved using stats-models or scikit-learn?

**Comment by surhudm** [comment] 2016-08-24 00:56
I am not familiar with statsmodels. I am guessing one will need something like this and use the wrapper in my implementation:

http://statsmodels.sourceforge.net/devel/examples/notebooks/generated/gls.html

I can try to think hard about how to avoid matrix inversions. :)
