### ISSUE TITLE
`fft` dramatic slowdown upon multiplying by `signal.windows.dpss`

### ISSUE THREAD

**Issue by OverLordGoldDragon** [scipy/scipy#13764] opened 2021-03-29 01:55 UTC
```python
import numpy as np
import scipy.signal as sig
from scipy.fft import fft
from timeit import default_timer as dtime

dtype = 'float32'
n_fft = 598
A = np.random.randn(n_fft, 160000).astype(dtype)
v0 = sig.windows.dpss(n_fft, 4).astype(dtype)
v1 = sig.windows.dpss(n_fft, n_fft // 8).astype(dtype)
v = v1

#%%###############################################################
t0 = dtime()
fft(A)
print(dtime() - t0)

A *= v.reshape(-1, 1)
#%%###############################################################
t0 = dtime()
fft(A)
print(dtime() - t0)
```
```
>>> 1.3161122000001342
>>> 4.751361799999813
```
Equal if using `v = v0` or `dtype = 'float64'` instead. No clue why. ([more times](https://i.stack.imgur.com/35XrR.png))

_Note_: a workaround is `v = v1 + 1`, `v -= 1`, but this shouldn't be necessary.

Win 10 x64, numpy 1.18.5, scipy 1.6.1, Python 3.7.9.

**Comment by mreineck** [comment] 2021-03-29 06:54
The FFT algorithms themselves are completely independent of the actual values they are working on, i.e. there is never a branch depending on, say, whether an array entry is very large or very small.
I could imagine that the multiplication with the window creates a few denormals, which are processed more slowly by many CPUs, but I don't really know how to check for those and how to avoid them in this context.

**Comment by mreineck** [comment] 2021-03-29 07:02
Yes, it seems to be caused by denormals.
As far as I can tell, there is no builtin workaround for this in numpy/scipy, but you can use, e.g. the `ftz` package to flush all denormal numbers in your array to zero, and after that the FFT will be much quicker again.
(Note: flushing denormals to zero should give much more accurate results than the proposed +1/-1 workaround.)

**Comment by OverLordGoldDragon** [comment] 2021-03-29 16:02
@mreineck Thanks, `ftz(v)` does work, and it should be done _after_ type casting. But why's it more accurate than +1/-1?

**Comment by peterbell10** [comment] 2021-03-29 16:20
The workaround confirms that it's denormals. Since that's not a scipy-specific issue, I'll close this.

> But why's it more accurate than +1/-1?

Normal floating point numbers are stored as a fixed number of significant digits (in binary) after the leading 1. The smallest number you can do +1 and maintain even a single digit of precision is `finfo.eps`. On the other hand, the smallest representable normal number is `finfo.tiny`, which is many orders of magnitude smaller.

```python
In [1]: import numpy as np
   ...: finfo = np.finfo(np.float32)
   ...: print(finfo.eps, finfo.tiny)
1.1920929e-07 1.1754944e-38
```

All normal numbers less than `eps` are lost completely, and anything less than 1 will lose significant digits due to rounding.

**Closed by peterbell10** 2021-03-29 16:20 UTC

**Comment by OverLordGoldDragon** [comment] 2021-03-29 22:36
@mreineck Any alternatives to `ftz`? Fails in [ubuntu](https://github.com/OverLordGoldDragon/ssq/runs/2222840972?check_suite_focus=true#step:5:249) CI. This is something that `numpy` itself should provide.

**Comment by WarrenWeckesser** [comment] 2021-03-29 23:03
> This is something that numpy itself should provide.

See https://github.com/numpy/numpy/issues/4581

**Comment by OverLordGoldDragon** [comment] 2021-03-29 23:15
@WarrenWeckesser Thanks. I just went with below

```
def zero_denormals(x, parallel=True):
    # take a little bigger than smallest, seems to improve FFT speed
    tiny = 1000 * np.finfo(x.dtype).tiny
    fn = _zero_denormals_par if parallel else _zero_denormals
    fn(x.ravel(), tiny)

@jit(nopython=True, cache=True)
def _zero_denormals(x, tiny):
    for i in range(x.size):
        if x[i] > -tiny and x[i] < tiny:
            x[i] = 0

@jit(nopython=True, cache=True, parallel=True)
def _zero_denormals_par(x, tiny):
    for i in prange(x.size):
        if x[i] > -tiny and x[i] < tiny:
            x[i] = 0
```
```python
for dtype in ('float32', 'float64'):
    x = np.random.randn(160000).astype(dtype)
    x[2::2] = np.finfo(x.dtype).tiny
    x[3::3] = -np.finfo(x.dtype).tiny
    x0 = x.copy()
    x1 = x.copy()
    
    zero_denormals(x0, parallel=False)
    zero_denormals(x1, parallel=True)
    assert np.allclose(x0, x1)
```
