### ISSUE TITLE
Comparison operator overloading doesn't work with sparse matrices

### ISSUE THREAD

**Issue by SteveDiamond** [scipy/scipy#4819] opened 2015-05-06 19:16 UTC
I'm the developer of a modeling framework for optimization problems called cvxpy. I'd like to support operator overloading between scipy sparse matrices and cvxpy objects.

Currently operator overloading works for arithmetic operations, but I also need it to work for comparison operators. The issue is that all comparison operators route through the `_inequality` function in `scipy/sparse/compressed.py`, and there's no code path in that function that returns `NotImplemented`. 

Could you add some code path that returns `NotImplemented` like in the arithmetic operators? That way the reflection will be called on the cvxpy object. For example, if `A` is a sparse matrix and `x` is a cvxpy variable, the expression `A <= x` will first call `A.__le__(x)`. This needs to return `NotImplemented` so Python calls `x.__ge__(A)`, which creates a cvxpy constraint object.

The same issues apply to the `__eq__` method in `scipy/sparse/compressed.py`. There should be some code path that returns `NotImplemented`.

Another solution would be to check `__array_priority__` like in Numpy. The object with the higher `__array_priority__` would have its comparison operator called first.

**Comment by argriffing** [comment] 2015-05-06 23:05
The currently active discussion at https://github.com/numpy/numpy/issues/5844 looks related.

**Comment by SteveDiamond** [comment] 2015-06-22 01:19
A clarification: what I really want is a clean way to make ``<scipy sparse matrix>.__binop__(<cvxpy object>)`` return ``NotImplemented`` for all binops. Ideally this would be via a flag in cvxpy objects.

**Comment by ashwinpathak20** [comment] 2017-02-24 11:40
I was solving this issue, so shall I include various cases for dense matrix, sparse matrix ,etc: in the binary operator function that are there in add , subtract functions or should I just raise the error.

**Comment by perimosocordiae** [comment] 2017-02-24 12:14
I'm not sure what you mean. Feel free to open a pull request with some partial fixes and mark it WIP. That way we can discuss the code directly.

**Comment by adbugger** [comment] 2018-02-19 21:02
Hi, I'd like to work on this bug if nobody is working on it currently. The last activity seems to be a year ago?

If it's possible, a point in the right direction (in terms of what files to understand and what code to modify) would be a big help.

**Comment by ilayn** [comment] 2018-02-19 22:12
If I understand correctly this has to be done at `cvxpy` side with either `__array_priority__` (or `__array_ufunc__` for NumPy 1.13+).

**Comment by rileyjmurray** [comment] 2020-01-15 19:11
@ilayn the error isn't in the cvxpy side. Right now, cvxpy Expression objects already have ``__array_priority__ = 100``. The array priority of ``scipy.sparse.spmatrix`` subclasses is only ``10.1``.

The trouble is that much of ``scipy.sparse.spmatrix`` doesn't check for array priority before calling internal functions. For example, ``spmatrix.__matmul__`` doesn't check for array priority.

On cvxpy's end, we have an extremely hacky workaround for this. Basically, when you call ``import cvxpy``, we execute the code in [this file](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/interface/scipy_wrapper.py) to replace spmatrix function handles with our own overloaded versions.

(A small remark: although I contribute to cvxpy, I actually came here because I ran into this issue in another project. Until ``spmatrix`` changes to respect ``__array_priority__``, I'll be using the cvxpy-like workaround in my other project.)

**Comment by ilayn** [comment] 2020-01-16 13:20
It is probably not respected by the sparse type. Yet another bug for spmatrix then 😦

**Comment by rileyjmurray** [comment] 2020-01-17 17:36
@ilayn would you welcome a PR to have spmatrix check for ``__array_priority__`` in all binary operations? The changes should be pretty simple. For example, I would change
```
    def __matmul__(self, other):
        if isscalarlike(other):
            raise ValueError("Scalar operands are not allowed, "
                             "use '*' instead")
        return self.__mul__(other)
```
to
```
    def __matmul__(self, other):
        if hasattr(other, '__array_priority__') and other.__array_priority__ > self.__array_priority__:
            return other.__rmatmul__(self)
        elif isscalarlike(other):
            raise ValueError("Scalar operands are not allowed, "
                             "use '*' instead")
        return self.__mul__(other)
```
I could also add some unittests, to check behavior against a dummy class which has ``__array_priority__ = 11``.

**Comment by Viech** [comment] 2021-09-15 15:18
I'm working on another modeling framework for convex optimization and I am hitting the same issue, so I can confirm what @rileyjmurray said:

> The trouble is that much of scipy.sparse.spmatrix doesn't check for array priority before calling internal functions. For example, `spmatrix.__matmul__` doesn't check for array priority. I believe that not considering `__array_priority__` is both the cause of this issue, and a larger issue in-of-itself.

I can add an example to clarify:

```python
>>> import scipy.sparse, picos
>>> A = scipy.sparse.spdiags(range(4), 0, 4, 4)
>>> x = picos.RealVariable("x", 4)
>>> x.T*A  # PICOS gets to load A.
<1×4 Real Linear Expression: xᵀ·[4×4]>
>>> A*x  # SciPy tries to load x as a NumPy array, even though x has infinite priority.
Traceback (most recent call last):
  [...]
picos.valuable.NotValued: Mutable x is not valued.
```
Note that there is no such problem with NumPy, as `ndarray` respects `x.__array_priority__`:

```python
>>> import numpy
>>> A = numpy.diag(range(4))
>>> x.T*A  # PICOS loads A.
<1×4 Real Linear Expression: xᵀ·[4×4]>
>>> A*x  # NumPy leaves the operation to PICOS.
<4×1 Real Linear Expression: [4×4]·x
```

----

> On cvxpy's end, we have an extremely hacky workaround for the `__array_priority__` issue. Basically, when you call import cvxpy, we execute the code in this file to replace spmatrix function handles with our own overloaded versions.

I was just now wondering how you do it! This is good to know, I assumed that you just did not have an `__array__` interface on your expressions. This is weirdly appealing but no good for us as we don't import scipy.

**Comment by rileyjmurray** [comment] 2021-09-15 15:44
> This is weirdly appealing but no good for us as we don't import scipy.

@Viech do you mean you don't have SciPy as a dependency? You can still override SciPy's behavior when it's present. In a separate package I work on, I have to override some [SciPy behavior](https://github.com/rileyjmurray/sageopt/blob/master/sageopt/interop/scipy.py) and [CVXPY behavior](https://github.com/rileyjmurray/sageopt/blob/master/sageopt/interop/cvxpy.py). I have SciPy as a dependency so that change is always made. When I override CVXPY behavior I have to check if it's installed first.

**Comment by Viech** [comment] 2021-09-15 16:37
Thank you for the hint! We don't use SciPy as a dependency but I was actually referring to importing it (if it is present), as this would add time to `import picos`. I've measured it now and it seems to be in the order of 30-40 ms extra on a fast computer, which is faster than I expected, but it would still not feel particularly good to load a major library just to patch it.

**Comment by Viech** [comment] 2021-09-16 09:03
For now I'll allow the user to patch this issue via `picos.patch_scipy_array_priority()`. The implementation is as follows:

```python
def patch_scipy_array_priority():
    """Monkey-patch scipy.sparse to make it respect __array_priority__.

    This works around https://github.com/scipy/scipy/issues/4819 and is inspired
    by CVXPY's scipy_wrapper.py.
    """
    import scipy.sparse

    def teach_array_priority(operator):
        def respect_array_priority(self, other):
            if hasattr(other, "__array_priority__") \
            and self.__array_priority__ < other.__array_priority__:
                return NotImplemented
            else:
                return operator(self, other)

        return respect_array_priority

    base_type = scipy.sparse.spmatrix
    matrix_types = (type_ for type_ in scipy.sparse.__dict__.values()
        if isinstance(type_, type) and issubclass(type_, base_type))

    for matrix_type in matrix_types:
        for operator_name in (
            "__add__", "__div__", "__eq__", "__ge__", "__gt__", "__le__",
            "__lt__", "__matmul__", "__mul__", "__ne__", "__pow__", "__sub__",
            "__truediv__",
        ):
            operator = getattr(matrix_type, operator_name)

            # Wrap all binary operators of the base class and all overrides.
            if matrix_type is base_type \
            or operator is not getattr(base_type, operator_name):
                wrapped_operator = teach_array_priority(operator)
                setattr(matrix_type, operator_name, wrapped_operator)
```

@rileyjmurray and @SteveDiamond: I have not tested your wrapper as I have trouble installing CVXPY at work but I noticed two potential issues with it:

1. You are not wrapping `__ge__`, `__matmul__`, `__ne__`, `__pow__` or `__truediv__`. I assume that most of these use the other operators internally but maybe this can change in the future.
2. You do not seem to wrap operators that are overridden in subclasses (e.g. `scipy.sparse.csr_matrix.__le__`).

**Comment by lucascolley** [comment] 2023-12-05 01:08
Closed by gh-19593!

**Closed by lucascolley** 2023-12-05 01:08 UTC
Labels: enhancement, scipy.sparse

**Comment by rileyjmurray** [comment] 2023-12-05 03:51
Wohoo!
