### ISSUE TITLE
Warn users when using float32 input data to curve_fit and friends

### ISSUE THREAD

**Issue by jacklovell** [scipy/scipy#7117] opened 2017-03-01 13:39 UTC
I recently ran into an issue whereby curve_fit was failing to fit a function, even though the guesses were reasonable. The warning reported by Scipy was "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/scipy/optimize/minpack.py:690: OptimizeWarning: Covariance of the parameters could not be estimated".

After hours of searching, I discovered that the problem was that I was using np.float32 arrays for the x and y data. Simply using x.astype(np.float64) resolved the issue. Though the warning provided no help or hints as to the source of the problem.

This is similar to what was reported in this (rather old) email thread: http://scipy-user.scipy.narkive.com/wSafjCiz/curve-fit-with-float32-values, which proved to be very difficult to find. It would be useful to warn in the curve_fit documentation (and other minimisation functions) about using float32 inputs, particularly as the problem only manifests itself with certain data sets.

**Comment by ev-br** [comment] 2017-03-12 12:27
It'd be helpful to understand whether a difficulty is related to a specific data set, a specific fit function or  the algorithm itself.

**Comment by anyuzx** [comment] 2018-02-26 19:04
I encountered the exact same issue! The function is a simple linear function with only interception parameter but fails to fit the data (always return covariance to be np.inf). I think it probably would be better for curve_fit to automatically convert data to float64.

**Comment by fuglede** [comment] 2018-06-05 14:31
This one also just [came up on StackOverflow](https://stackoverflow.com/questions/50700890/scipy-curve-fit-returns-initial-estimates/).

The issue can also happen without any `OptimizeWarning` being raised *at all*, which is rather spooky.

Here's the example provided on StackOverflow:

```python
def hyperbola(x, s_1, s_2, o_x, o_y, c):
    b_2 = (s_1 + s_2) / 2
    b_1 = (s_2 - s_1) / 2
    return o_y + b_1 * (x - o_x) + b_2 * np.sqrt((x - o_x) ** 2 + c ** 2 / 4)

min_fit = np.array([-3.0, 0.0, -2.0, -10.0, 0.0])
max_fit = np.array([0.0, 3.0, 3.0, 0.0, 10.0])
guess = np.array([-2.5/3.0, 4/3.0, 1.0, -4.0, 0.5])
```

With that, let us try to run the optimization on inputs consisting of `np.float64` and `np.float32` values respectively.

```python
params = [-2, .4, -1, -5, 9.5]
xdata = np.array([-32, -16, -8, 4, 4, 8, 16, 32])
ydata = hyperbola(xdata, *params)
popt, _ = curve_fit(f=hyperbola, xdata=xdata, ydata=ydata, p0=guess, bounds=(min_fit, max_fit))
plt.plot(xdata, ydata, '.')
plt.plot(xs, hyperbola(xs, *popt))
```

![2](https://user-images.githubusercontent.com/6169306/40982572-d64ee47a-68dd-11e8-959e-eb5f285eecf6.png)

Now, let's change the type of the values in `xdata` to `np.float32` (noting that all the values in `xdata` were taken to be representable as `np.float32`s, but that the `ydata´ values need not be):

```
xdata = xdata.astype(np.float32)
ydata = hyperbola(xdata, *params)
popt, _ = curve_fit(f=hyperbola, xdata=xdata, ydata=ydata, p0=guess, bounds=(min_fit, max_fit))
plt.plot(xdata, ydata, '.')
plt.plot(xs, hyperbola(xs, *popt))
```

![3](https://user-images.githubusercontent.com/6169306/40982582-dcfa099e-68dd-11e8-924e-5a748fed2347.png)

**Comment by fuglede** [comment] 2018-06-05 16:03
Debugging each case line-by-line until a significant difference appears between the two cases, it becomes obvious that [`_numdiff.approx_derivative`](https://github.com/scipy/scipy/blob/0a9a4450d97d866125cf2dab0ac4d98dfcf75634/scipy/optimize/_numdiff.py#L178) is to blame; here, the initial step size is the [square root](https://github.com/scipy/scipy/blob/0a9a4450d97d866125cf2dab0ac4d98dfcf75634/scipy/optimize/_numdiff.py#L94) of the [machine epsilon of `np.float64`](https://github.com/scipy/scipy/blob/0a9a4450d97d866125cf2dab0ac4d98dfcf75634/scipy/optimize/_numdiff.py#L12). With a step size this small, the resulting [`df`s](https://github.com/scipy/scipy/blob/0a9a4450d97d866125cf2dab0ac4d98dfcf75634/scipy/optimize/_numdiff.py#L454) vanish in the `np.float32` case,

If one changes `_numdiff.EPS` to be `np.finfo(np.float32).eps`, then the expected result is obtained in the `np.float32` case as well (as in, `popt` ends up being `[-2.          0.40000021 -0.99999979 -5.00000208  9.4999949 ]` whereas the `np.float64` gives a result of `[-2.   0.4 -1.  -5.   9.5]`).

Of course, just because the `np.float32` case can be fixed, that doesn't mean that simply having a warning is not the preferable option, but there's the explanation at least.

**Comment by rgommers** [comment] 2018-06-06 03:36
`np.finfo(f0.dtype).eps` sounds reasonable, but casting to `float64` internally may be preferable -it'll give a more accurate result and avoid further nasty surprises. Plus it takes care of `float16` and perhaps other dtypes as well.

**Comment by fuglede** [comment] 2018-06-06 05:01
Also sounds reasonable to me, but I guess you'd have to be careful to make sure that the optimization objective behaves properly after casting; in the worst possible case, the objective is one that casts its inputs to `np.float32` before doing anything else. Is that a scenario that's worth supporting, or can one assume that the objective performs only type-preserving operations?

Also, if the solution of casting ends up being what is implemented, it might be worth doing the same in `minpack.py` which currently has a few instances where we use `epsfcn = sqrt(finfo(dtype).eps)`. If nothing else then for consistency.

**Comment by andyfaff** [comment] 2018-06-06 05:50
I think Ralf means cast to the dtype of the objective. Presumably that's
going to be stable.

**Comment by fuglede** [comment] 2018-06-06 07:05
Hm, depending a bit on how you go about doing it anyway; again, we could well be talking about different things, so let me just leave the observation that even if you redefine `f0` in `least_squares.least_squares` to be `f0 = fun_wrapped(x0).astype(np.float64)`, and the wrapped objective returned by `minpack._wrap_func` to be `return func(xdata, *params).astype(np.float64) - ydata`, then all objectives involved end up being `np.float64` but the issue survives.

That is, in the example above, the issue really lies with the inputs, and the cheapest fix I can see would be to patch `minpack.curve_fit` to use e.g. `xdata = np.asarray_chkfinite(xdata, dtype=np.float64)`. Downsides being that this makes the assumption that the objective is agnostic towards the types provided to it, and that it nullifies the existing fix for the minpack based methods (e.g. the case `method == 'lm'`), but again, that's probably a good thing for consistency.

**Comment by tylerjereddy** [comment] 2018-11-06 04:13
Extended discussion of an apparently tricky issue with no linked PR attempting to fix it -- I see little chance of resolution before the imminent branching of 1.2.x so bumping the milestone.

**Comment by TomDonoghue** [comment] 2018-12-09 18:16
I've just run into this issue, and it is a really thorny one to debug, to realize that it is the dtype of an input that is causing the covariance calculation to fail, and thus leading to nonsense outputs. In my case, this lead to an error downstream that was hard to trace back.

My first thought was also that type-casting internally might be the easiest - but given the discussion above, perhaps that does have some edge-case issues? If an actual solution in code is not clear / might take some more discussion / tweaking, is there anything stopping a note in the documentation being added right away? Just adding note that f32 inputs can cause the covariance warning would be enough to stop other people having to chase out this problem, since the user can fix this issue right away, if they know what the source is.

**Comment by denis-bz** [comment] 2019-04-14 14:41
h = sqrt( finfo.eps ) seems to me optimistic, good for smooth functions with no noise.
[Numerical Recipes p. 230](http://apps.nrbook.com/empanel/index.html?pg=230) derives

    h_opt ~ sqrt( finfo.eps ) * x_c   # or for central diff eps^(1/3)
    x_c = sqrt( f / f'' )   -- the "curvature scale over which f changes"

Is this curvature scale ~ 1, for any real problems ? For noise with tiny ripples, it can be huge:

    noise(x) = 1e-6 sin( x / wavelen )
    noise / noise'' = wavelen^2
    h_opt ~ sqrt( finfo.eps ) * wavelen

But h_opt for smooth() + noise() ? Dunno. Over to experiment:

Does anyone know of real-world non-smooth test functions, to run optimizations with a few different `h` ?
Rosenbrock is locally smooth, and afaik so are all the CUTEr functions.

**Comment by ev-br** [comment] 2019-04-20 14:07
This is not a duplicate of gh-9581. That one happens when xdata and ydata have different dtypes. This one is specific for both inputs being float32. The failure modes are different, too: one is OptimizeWarning, the covariance full of `inf`s and the initial guess being returned. The other one here, is that curve_fit silently produces garbage. 

Both this and gh-9581 can be fixed by casting xdata and ydata to float64, as gh-10076 does. 

I believe this is the right thing to do for curve_fit: it's a black box routine, which does quite a bit of magic already. Let it do some more magic. 

An option of doing all computations in float32 is IMO best left as an enhancement request for `least_squares`. I suspect it's not possible to make very robust, especially with estimating the derivatives in single precision. But if someone feels strongly about it, https://github.com/scipy/scipy/issues/7117#issuecomment-394766087 is an excellent starting point. I suspect there are more places where double precision is assumed, so it needs to be tracked down. Whether this is worth it, I don't know.

**Comment by rgommers** [comment] 2019-04-20 19:44
> Also sounds reasonable to me, but I guess you'd have to be careful to make sure that the optimization objective behaves properly after casting; in the worst possible case, the objective is one that casts its inputs to `np.float32` before doing anything else. Is that a scenario that's worth supporting, or can one assume that the objective performs only type-preserving operations?

no, such scenarios are not worth supporting, that's just weird. thinks that are designed to work with float32 also will work with float64 normally.

**Comment by rgommers** [comment] 2019-04-20 19:44
I plan to merge gh-10076 soon

**Comment by ev-br** [comment] 2020-07-20 10:13
Fat-fingered, sorry

**Closed** 2020-07-20 10:13 UTC
Labels: defect, scipy.optimize
