### ISSUE TITLE
Memory leak in SLSQP when interfacing with Matlab

### ISSUE THREAD

**Issue by mchirsa5** [scipy/scipy#10999] opened 2019-11-01 21:22 UTC
Hi. I have found a problem when I try to make communication between Matlab and python (using SLSQP). I have built a model in Matlab and tried to use Scipy to optimise the parameters in the model. Therefore, I wrote an objective function in python and use "matlab.engine" to interface between the two. However, I have found that the simulation time in each iteration increases when I call Matlab engine.

With the code below, the simulation time keeps increasing after finishing eacg interation.
eng = matlab.engine.start_matlab()
def opt_pf(x):
    y = eng.matlab_model(excel_path, x, nargout=0)
    return y
gc.collect()

# Run optimisation
from scipy.optimize import minimize
res = minimize(opt_pf, x0, method='SLSQP', constraints=[eq_cons], options={'ftol': 1e-09, 'disp': True}, bounds=bounds)

I first thought that the problem was from matlab.engine. However, there is no such problem when I put matlab.engine in a normal loop. So, I think that the optimizer didn't clear the cache from matlab.engine in each iteration.

**Comment by andyfaff** [comment] 2019-11-01 21:54
One way to test for leak of resources is to run slsqp repeatedly in python. If the timings/memory usage doesn't blow out then the issue is probably on the interface to matlab which isnt the responsibility of scipy.

**Comment by mchirsa5** [comment] 2019-11-01 21:58
Hi Andy, the simulation time increases from 1s at the first few iterations to more than 1 min after 100th iteration.

**Comment by andyfaff** [comment] 2019-11-01 22:22
Please provide a minimum working example that doesn't call any MATLAB code.

**Comment by andyfaff** [comment] 2020-01-20 09:29
Closing, because there is no MWE (minimum working example) showing leakage of resources in scipy.

**Closed by andyfaff** 2020-01-20 09:29 UTC
Labels: scipy.optimize
