### ISSUE TITLE
Still unable to install SciPy

### ISSUE THREAD

**Issue by nevess99** [scipy/scipy#15031] opened 2021-11-13 01:05 UTC
### Describe your issue.

Hi, I just got the MBA M1 and I am trying to install SciPy, but for some reason I am getting errors which I don't quite understand. Would appreciate any advice on how to move forward. I am running Monterey 12.0.1. I have been able to install most libraries, just scipy has been giving me problems. The whole error message is too long to post, but I can reply with relevant information, just get back to me on this thread. 

### Reproducing Code Example

```python
~ % brew --version
Homebrew 3.3.3
Homebrew/homebrew-core (git revision 4530cc439e5; last commit 2021-11-12)
Homebrew/homebrew-cask (git revision e60e8f7a05; last commit 2021-11-13)
~ % pip install cython pybind11 pythran numpy
Requirement already satisfied: cython in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.29.24)
Requirement already satisfied: pybind11 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (2.8.1)
Requirement already satisfied: pythran in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.10.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.21.4)
Requirement already satisfied: beniget~=0.4.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pythran) (0.4.1)
Requirement already satisfied: gast~=0.5.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pythran) (0.5.2)
Requirement already satisfied: ply>=3.4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pythran) (3.11)
~ % OPENBLAS=$(brew --prefix openblas) CFLAGS="-falign-functions=8 ${CFLAGS}" pip install --no-use-pep517 scipy==1.7.0
```

### Error message

```shell
ollecting scipy==1.7.0
  Using cached scipy-1.7.0.tar.gz (36.1 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scipy==1.7.0) (1.21.4)
Building wheels for collected packages: scipy
  Building wheel for scipy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lx/_pkqc2sj3x9g0yfndm_4n4vh0000gn/T/pip-install-otct1we2/scipy_443d1f5e1f1e403f84a3325c1b1e3401/setup.py'"'"'; __file__='"'"'/private/var/folders/lx/_pkqc2sj3x9g0yfndm_4n4vh0000gn/T/pip-install-otct1we2/scipy_443d1f5e1f1e403f84a3325c1b1e3401/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/lx/_pkqc2sj3x9g0yfndm_4n4vh0000gn/T/pip-wheel-uozvxwo6
       cwd: /private/var/folders/lx/_pkqc2sj3x9g0yfndm_4n4vh0000gn/T/pip-install-otct1we2/scipy_443d1f5e1f1e403f84a3325c1b1e3401/



 error: Command "ar rcs build/temp.macosx-10.9-universal2-3.9/libsc_cephes.a build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/scipy_iv.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/shichi.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/sici.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/sindg.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/sinpi.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/spence.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/stdtr.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/struve.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/tandg.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/tukey.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/unity.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/yn.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/yv.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/zeta.o build/temp.macosx-10.9-universal2-3.9/scipy/special/cephes/zetac.o" failed with exit status 1
    
    ########### CLIB COMPILER OPTIMIZATION ###########
    Platform      :
      Architecture: unsupported
      Compiler    : gcc
    
    CPU baseline  :
      Requested   : optimization disabled
      Enabled     : none
      Flags       : none
      Extra checks: none
      Requested   : optimization disabled
    
    CPU dispatch  :
      Enabled     : none
      Generated   : none
    CCompilerOpt.cache_flush[809] : write cache to path -> /private/var/folders/lx/_pkqc2sj3x9g0yfndm_4n4vh0000gn/T/pip-install-otct1we2/scipy_443d1f5e1f1e403f84a3325c1b1e3401/build/temp.macosx-10.9-universal2-3.9/ccompiler_opt_cache_clib.py
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lx/_pkqc2sj3x9g0yfndm_4n4vh0000gn/T/pip-install-otct1we2/scipy_443d1f5e1f1e403f84a3325c1b1e3401/setup.py'"'"'; __file__='"'"'/private/var/folders/lx/_pkqc2sj3x9g0yfndm_4n4vh0000gn/T/pip-install-otct1we2/scipy_443d1f5e1f1e403f84a3325c1b1e3401/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/lx/_pkqc2sj3x9g0yfndm_4n4vh0000gn/T/pip-record-bkv6xrzk/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/scipy Check the logs for full command output.
```

### SciPy/NumPy/Python version information

>>> print(numpy.__version__, sys.version_info) 1.21.4 sys.version_info(major=3, minor=9, micro=8, releaselevel='final', serial=0)

**Comment by ilayn** [comment] 2021-11-13 01:34
Hi @nevess99 could you please refer to the duplicate I'm linking as a duplicate? We have been trying M1 install since January and there is some promising results happened over that issue.

**Comment by ilayn** [comment] 2021-11-13 01:34
Duplicate of #13409

**Closed by ilayn** 2021-11-13 01:34 UTC
Labels: defect

**Comment by nevess99** [comment] 2021-11-13 01:42
Hey thanks for get back to me. I tried this #13409 solution but it didn't work for me. However, I found another alternative #4376, which is running fine so far. Will still have to test it out intensively on bigger datasets.

**Comment by psobolewskiPhD** [comment] 2021-11-14 10:25
I'm also on M1 Monterey. It looks like you are using the apple python install?
Perhaps try getting set up with a conda env using miniforge3 (or mamba):
https://github.com/conda-forge/miniforge
(make sure it's the MacOS arm64 version)
Then create an env:
`conda create -y -n scipy-test python=3.9`
(You can replace scipy-test with whatever name you want).
Did you install OpenBLAS using homebrew? If so you may want to export that so pip knows about it:
`export OPENBLAS=/opt/homebrew/opt/openblas/lib/`
(adjust this based on your shell, e.g. in fish it's `set -x OPENBLAS /opt/homebrew/opt/openblas/lib/`
Make sure you activate your new env: `conda activate scipy-test`
and then a simple:
`pip install scipy`
should work.

BTW If you don't want to be building scipy, you can always use conda to install a binary.

**Comment by nevess99** [comment] 2021-11-16 00:39
@psobolewskiPhD Thanks. 
I used pip install --pre -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy and it worked for me.
