### ISSUE TITLE
scipy triggering experimental array_api import from numpy 2.0.dev

### ISSUE THREAD

**Issue by pllim** [scipy/scipy#19065] opened 2023-08-14 18:15 UTC
https://github.com/scipy/scipy/blob/d4efe3665e69a6a46ab591ac3da359d8d98e7d10/scipy/__init__.py#L67

Somehow triggers the following downstream. Not sure how we can avoid this downstream without ignoring that warning altogether in our test suite. All we are trying to do is import scipy to make sure it is installed at the beginning of the test job.

```
scipy/__init__.py:67: in <module>
    _fun = getattr(np, _key)
numpy/__init__.py:325: in __getattr__
    import numpy.array_api as array_api
numpy/array_api/__init__.py:120: in <module>
    warnings.warn(
E   UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
```

Numpy has it imported "lazily" here:

https://github.com/numpy/numpy/blob/3493add1d364565103ac17f749b2e80a2cf6c9ac/numpy/__init__.py#L325

Example log: https://github.com/spacetelescope/jdaviz/actions/runs/5858523778/job/15882659355

**Comment by pllim** [comment] 2023-08-14 19:13
Might be related? Looks like the same machinery.

```
scipy/__init__.py:67: in <module>
    _fun = getattr(np, _key)
numpy/__init__.py:328: in __getattr__
    import numpy.distutils as distutils
numpy/distutils/__init__.py:31: in <module>
    warnings.warn("\n\n"
E   DeprecationWarning:
E
E     `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
E     of the deprecation of `distutils` itself. It will be removed for
E     Python >= 3.12. For older Python versions it will remain present.
E     It is recommended to use `setuptools < 60.0` for those Python versions.
E     For more details, see:
E       https://numpy.org/devdocs/reference/distutils_status_migration.html
```

**Comment by rgommers** [comment] 2023-08-15 05:19
What changed is that in numpy, `'array_api'` was added to `numpy.__all__`. That is reasonable though. The problem is in SciPy's main `__init__.py`, which does a weird little dance to try and deprecate all `scipy.<object>` items that come from `numpy`. The way it's implemented, it exposes more numpy objects in the main scipy namespace as they get added to numpy. And it triggers this warning. I'll put a band aid on it now.

**Comment by rgommers** [comment] 2023-08-15 06:28
Fixed now, and new nightly builds should trigger in a few hours. Thanks for the report @pllim!

**Closed** 2023-08-15 06:27 UTC
Labels: array types

**Comment by pllim** [comment] 2023-08-15 15:37
Is this something different? Same warning but different route now.

```
    from scipy.interpolate import interpn
scipy/interpolate/__init__.py:167: in <module>
    from ._interpolate import *
scipy/interpolate/_interpolate.py:13: in <module>
    from . import _fitpack_py
scipy/interpolate/_fitpack_py.py:10: in <module>
    from ._bsplines import BSpline
scipy/interpolate/_bsplines.py:9: in <module>
    from scipy.optimize import minimize_scalar
scipy/optimize/__init__.py:409: in <module>
    from ._optimize import *
scipy/optimize/_optimize.py:38: in <module>
    from ._numdiff import approx_derivative
scipy/optimize/_numdiff.py:9: in <module>
    from scipy._lib._array_api import atleast_nd, array_namespace
scipy/_lib/_array_api.py:16: in <module>
    import scipy._lib.array_api_compat.array_api_compat.numpy as array_api_compat_numpy
scipy/_lib/array_api_compat/array_api_compat/numpy/__init__.py:1: in <module>
    from numpy import *
numpy/__init__.py:327: in __getattr__
    import numpy.array_api as array_api
numpy/array_api/__init__.py:120: in <module>
    warnings.warn(
E   UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
```

Example log: https://github.com/spacetelescope/jdaviz/actions/runs/5868277077/job/15910732412?pr=2374

**Comment by tylerjereddy** [comment] 2023-08-15 20:58
@pllim we could check with @asmeurer on that perhaps, since it seems to traverse [`array_api_compat`](https://github.com/data-apis/array-api-compat), which we vendor. It does look similar to Ralf's original assessment of pulling in a bit too much from NumPy `__all__` perhaps?

**Comment by asmeurer** [comment] 2023-08-15 21:08
> What changed is that in numpy, 'array_api' was added to numpy.__all__.

When did this happen? If it's going to added there, we should remove the experimental warning.

It would also be a good idea to formally decide once and for all if we actually do want to keep numpy.array_api inside of numpy or move it out (I personally don't care either way, but it's likely a good idea to decide before numpy 2.0).

**Comment by pllim** [comment] 2023-08-15 21:13
All I can say is "recently". I had been battling numpy print failures before that. And this cropped up once that one was worked around.

**Comment by rgommers** [comment] 2023-08-16 09:16
> When did this happen? If it's going to added there, we should remove the experimental warning.

Agreed - I'll send a PR or two now, fixing it in two stages:
1. ensure `from numpy import *` doesn't emit any warnings
2. propose to remove the `numpy.array_api` warning
