### ISSUE TITLE
BUG: first shared library in scipy fails to be consumed by MSVC

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#20840] opened 2024-05-30 21:08 UTC
While [building](https://github.com/conda-forge/scipy-feedstock/pull/277) scipy 1.14.0rc1 for conda-forge, I ran into:
```
lld-link: error: undefined symbol: scipy_sf_error_get_action
```
@rgommers noted
> That is a shared library, new in 1.14.0: [scipy/scipy#20321](https://github.com/scipy/scipy/pull/20321). It's the first one, so not surprised there is a hiccup with it.

My analysis:
> In that case it's probably a regular symbol-visibility-in-shared-windows-libraries issue, which needs `__declspec(dllimport)` / `__declspec(dllexport)` to work ([example](https://github.com/abseil/abseil-cpp/blob/20240116.2/absl/base/config.h#L736-L753)), which could look like
> 
> ```c
> // SF_ERR_DLL
> // inspired by https://github.com/abseil/abseil-cpp/blob/20240116.2/absl/base/config.h#L736-L753
> //
> // When building sf_error_state as a DLL, this macro expands to `__declspec(dllexport)`
> // so we can annotate symbols appropriately as being exported. When used in
> // headers consuming a DLL, this macro expands to `__declspec(dllimport)` so
> // that consumers know the symbol is defined inside the DLL. In all other cases,
> // the macro expands to nothing.
> // Note: SF_ERR_DLL_EXPORTS is set in CMakeLists.txt when building shared sf_error_state
> //       SF_ERR_DLL_IMPORTS is set by us as part of the interface for consumers of the DLL
> #if defined(SF_ERR_DLL_EXPORTS)
> #define SF_ERR_DLL __declspec(dllexport)
> #elif defined(SF_ERR_DLL_IMPORTS)
> #define SF_ERR_DLL__declspec(dllimport)
> #else
> #define SF_ERR_DLL
> #endif // defined(SF_ERR_DLL_EXPORTS)
> ```
> 
> plus an equivalent of the following CMake code:
> 
> ```cmake
> # for building sf_error_state target
> if(WIN32 AND MSVC)
>   set_target_properties(sf_error_state PROPERTIES DEFINE_SYMBOL "SF_ERR_DLL_EXPORTS")
>   if(BUILD_SHARED_LIBS)
>     target_compile_definitions(sf_error_state INTERFACE SF_ERR_DLL_IMPORTS)
>   endif()
> endif()
> ```
> 
> I have more experience with this than I'd like to, e.g. from long [efforts](https://github.com/conda-forge/grpc-cpp-feedstock/pull/243) around shared library builds in conda-forge.
> 
> The takeaway: _**Shared libraries with MSVC generally need source-code level annotations.**_ There's one limited escape hatch on CMake (`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`), but even that doesn't work for global data symbols. Unless meson has a magic bullet here, that's what we'll need to do IMO.
> 
> CC @steppi

Moving to issue here as requested by Ralf:
> Oh yes, fair. We keep being caught out by not having CI coverage for this at all - nothing but MinGW in SciPy CI and wheel builds :(
>
> Could you please move this to a new SciPy issue? This is a blocker for 1.14.0.

**Comment by steppi** [comment] 2024-05-30 23:38
Thanks @h-vetinari. I’ll look into it.

**Comment by steppi** [comment] 2024-06-10 19:01
I've been trying to work on this, but I'm unable to build SciPy on Windows with meson using MSVC and ifx, in a conda-env with `compilers` commented out. I'm using

```
set CC=cl
set CXX=cl
set FC=ifx
python dev.py build --setup-args --buildtype=release
```

from an X64 native tools command prompt after running Intel's  `setvars.bat` to setup the Intel Fortran compiler.

I'm seeing the same error that was reported in https://github.com/scipy/scipy/issues/17928#issuecomment-1532562984.

```
../scipy/sparse/linalg/_propack/PROPACK/single/sblasext.F(154): catastrophic error: Declaration of routine 'PSNRM2' conflicts with a previous declaration
compilation aborted for ../scipy/sparse/linalg/_propack/PROPACK/single/sblasext.F (code 1)
```

@rgommers, I saw that this should have been fixed by https://github.com/scipy/scipy/pull/18411, https://github.com/scipy/scipy/pull/18421, and https://github.com/scipy/PROPACK/pull/6, but am not sure if that's been verified.

@h-vetinari, can you let me know how you usually build with this toolchain?

**Comment by rgommers** [comment] 2024-06-10 19:54
> It seems that the fortran args weren't getting picked up from `meson.build` for some reason. That error went away when I set them manually with

Probably due to `ifx` compiler name being different from `ifort`, so it was fixed for the latter but that didn't cover the former. See https://mesonbuild.com/Reference-tables.html#compiler-ids. If you use `intel-llvm-cl` where the code in gh-18411 added `intel-cl`, does the problem go away?

**Comment by steppi** [comment] 2024-06-10 20:03
> Probably due to `ifx` compiler name being different from `ifort`, so it was fixed for the latter but that didn't cover the former. See https://mesonbuild.com/Reference-tables.html#compiler-ids. If you use `intel-llvm-cl` where the code in [gh-18411](https://github.com/scipy/scipy/pull/18411) added `intel-cl`, does the problem go away

Indeed. That makes the problem go away.

**Comment by tylerjereddy** [comment] 2024-06-10 22:27
So there are two problems to resolve/blocking RC2 then?

1. `meson` shim to support the new llvm-flavored Intel compiler series args pass-through.
2. Whatever fix is needed for the original symbol visibility problem.

**Comment by steppi** [comment] 2024-06-10 23:43
> python dev.py build --setup-args --buildtype=release

I have those two fixed locally, but no I'm dealing with an error in Pythran

```
..\..\micromamba\envs\scipy-dev\Lib\site-packages\pythran\pythonic/include/types/ndarray.hpp(479): error C2559: 'std::enable_if<`anonymous-namespace'::pythonic::types::is_numexpr_arg<F>::value&&std::is_same<bool,F::dtype>::value&&F::value==1&&!`anonymous-namespace'::pythonic::types::is_pod_array<F>::value,`anonymous-namespace'::pythonic::types::numpy_vexpr<`anonymous-namespace'::pythonic::types::ndarray<double,`anonymous-namespace'::pythonic::types::pshape<long,long>>,`anonymous-namespace'::pythonic::types::ndarray<long,`anonymous-namespace'::pythonic::types::pshape<long>>>>::type `anonymous-namespace'::pythonic::types::ndarray<double,`anonymous-namespace'::pythonic::types::pshape<long,long>>::operator [](const F &) const': cannot overload a member function without ref-qualifier with a member function with ref-qualifier
```

**Comment by steppi** [comment] 2024-06-11 16:45
Thanks everyone for the help. I set `use-pythran` to false to avoid the Pythran error, which seems to be specific to my environment, and found that I get the same error as on @h-vetinari's conda build. The issue is that I was only passing the extra args as `cpp_args`, but the shared library is a C program. I'm still sorting some stuff out, but will hopefully be able to push a correct fix soon.

**Closed** 2024-06-13 07:33 UTC
Labels: defect, scipy.special, Build issues, C/C++, Meson
