### ISSUE TITLE
signal.resample is broken for even-length inputs

### ISSUE THREAD

**Issue by forrestv** [scipy/scipy#7584] opened 2017-07-11 03:49 UTC
signal.resample is broken for even-length inputs.

### Reproducing code example:
```
>>> from scipy.signal import resample
>>> resample(resample([1, 2, 3, 4], 6), 4)
array([ 1.25,  1.75,  3.25,  3.75])
```
I would expect resampling to a higher number of samples and back to be the identity operation as a consequence of Fourier resampling being "perfect" for band-limited signals. This appears to be due to incorrect handling of the Nyquist frequency component.

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('0.14.1', '1.8.2', sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0))
```

**Comment by WarrenWeckesser** [comment] 2017-07-11 05:50
Thanks for reporting the problem.  This appears to be a duplicate of https://github.com/scipy/scipy/issues/7278.  It has been fixed in the development version of scipy. @forrestv, feel free to comment if you think the problem is not the same.

**Closed by WarrenWeckesser** 2017-07-11 05:50 UTC
Labels: defect, duplicate, scipy.signal
