### ISSUE TITLE
Lomb-Scargle Periodogram returns a spurious value at the last frequency for "perfect signals"

### ISSUE THREAD

**Issue by khider** [scipy/scipy#13180] opened 2020-12-01 01:14 UTC
While conducting tests on the LS method, I found that in the case of a perfect harmonic signal with no missing data, the value for the last frequency is spurious. 

#### Reproducing code example:

Notebook documenting the issue [here](https://github.com/KnowledgeCaptureAndDiscovery/autoTS/blob/master/notebooks/Methods/Lomb%20Scargle%20Performance%20on%20Evenly%20Spaced%20Signal.ipynb)

#### Error message:

No error

#### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.0 1.18.5 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
```

**Comment by jakevdp** [comment] 2020-12-01 04:58
Can you provide scipy code that reproduces the issues you're seeing? I spent a bit of time trying to dig-in to the package used in the notebook and it's not clear to me what values are being passed to the scipy routines.

**Comment by WarrenWeckesser** [comment] 2020-12-15 21:28
I'll echo @jakevdp's request.  It will be easier to help you if you provide a minimal, self-contained example of the problem that doesn't depend on `pyleoclim`.

**Comment by DietBru** [comment] 2024-12-05 17:07
Closing as not reproducible, since original link to notebook does not exist anymore. Furthermore, there is a good chance that #21729 resolved this issue.

**Closed by DietBru** 2024-12-05 17:07 UTC
Labels: scipy.signal
