### ISSUE TITLE
Inconsistent result array shapes when minimizing 1D scalar functions

### ISSUE THREAD

**Issue by mirca** [scipy/scipy#8055] opened 2017-10-19 01:31 UTC
Hello,

I came across this minor inconsistency in shape when using different optimization methods provided by the ``minimize`` interface to optimize 1D scalar functions: 

```
In [1]: from scipy.optimize import minimize

In [2]: import numpy as np

In [3]: x = np.linspace(0, 10, 100)

In [4]: y = x + np.random.normal(size=len(x), scale=3)

In [5]: def affine_function(theta):
   ...:   return x * theta

In [5]: chi_sqr = lambda theta: np.sum((affine_function(theta) - y) ** 2)

In [6]: result_nm = minimize(chi_sqr, x0=1, method='Nelder-Mead')

In [6]: result_nm.x
Out[6]: array([ 1.17421875])

In [7]: result_p = minimize(chi_sqr, x0=1, method='Powell')

In [7]: result_p.x
Out[7]: array(1.1742389466088772)
```

I would expect ``result_nm.x`` and ``result_p.x`` to be of the same shape.

PS: that divergence seems not exist when minimizing higher dimension scalar functions.

```
In [8]: import scipy; scipy.__version__
Out[8]: '0.19.1'
```

```
In [9]: import numpy; numpy.__version__
Out[9]: '1.13.1'
```

Cheers,
Zé

**Comment by person142** [comment] 2017-10-23 14:55
Duplicate of https://github.com/scipy/scipy/issues/6673 I think, so closing in favor of that one.

**Closed by person142** 2017-10-23 14:55 UTC
Labels: duplicate, scipy.optimize
