### ISSUE TITLE
solve_toeplitz test failures on Windows

### ISSUE THREAD

**Issue by cgohlke** [scipy/scipy#4907] opened 2015-05-26 01:26 UTC
Using 64 bit numpy and scipy built with Visual Studio and Intel Composer XE 2013 SP1 Update 5:
```
NumPy version 1.9.2
NumPy is installed in X:\Python27-x64\lib\site-packages\numpy
SciPy version 0.16.0b2
SciPy is installed in X:\Python27-x64\lib\site-packages\scipy
Python version 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
nose version 1.3.6
<snip>
======================================================================
FAIL: test_solve_toeplitz.test_solve_equivalence
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27-x64\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "x:\python27-x64\lib\site-packages\scipy\linalg\tests\test_solve_toeplitz.py", line 29, in test_solve_equivalence

    assert_allclose(actual, desired)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([ -6.559608e-01 +9.433322e-01j,  -7.042839e-02 +7.879517e-01j,
        -3.581482e-01 -2.419431e+00j,   1.072833e+00 +7.807909e-02j,
         4.976722e-01 -2.343051e-01j,  -4.428613e-01 +1.610013e+00j,...
 y: array([-3.462743+3.469447j, -0.007407+5.276949j,  1.700926+4.108577j,
        2.991538-0.439018j, -1.325771-4.15963j , -3.285425-1.569889j,
        0.100705+1.945576j,  3.029490+2.907199j,  2.347309+4.743984j,
        1.806883+2.359116j])

======================================================================
FAIL: test_solve_toeplitz.test_multiple_rhs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27-x64\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "x:\python27-x64\lib\site-packages\scipy\linalg\tests\test_solve_toeplitz.py", line 48, in test_multiple_rhs
    assert_allclose(actual, desired)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([-0.289589+0.37337j ,  0.897719+1.245794j,  0.708426+1.344244j,
       -0.426592+0.201103j])
 y: array([ 0.242108+0.68784j , -0.206339+0.965875j,  0.836969+0.546491j,
       -0.164775+1.022614j])

======================================================================
FAIL: test_solve_toeplitz.test_reflection_coeffs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "X:\Python27-x64\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "x:\python27-x64\lib\site-packages\scipy\linalg\tests\test_solve_toeplitz.py", line 91, in test_reflection_coeffs

    assert_allclose(reflection_coeffs_z, ref_z[:-1])
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "X:\Python27-x64\lib\site-packages\numpy\testing\utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array([ 1.000000+0.j      ,  0.921721+0.068066j,  0.010937-0.056768j,
       -0.116593+1.490581j, -0.050739-0.016819j, -0.110217-0.361621j,
        1.138602-0.34801j , -0.397884+0.090909j, -0.219459-0.185754j])
 y: array([ 1.000000+0.j      ,  0.921721+0.068066j,  0.010937-0.056768j,
       -0.116593+1.490581j, -0.050739-0.016819j, -0.110217-0.361621j,
        1.138602-0.34801j , -0.571964+0.180935j, -0.219459-0.185754j])

----------------------------------------------------------------------
Ran 18372 tests in 165.063s

FAILED (KNOWNFAIL=97, SKIP=1178, failures=3)
```

**Comment by rgommers** [comment] 2015-05-26 20:23
Thanks @cgohlke.

Looks like there's something wrong with the test function; it always seems to report 100% mismatch. The last test looks like it has at least some numbers that are OK.

**Comment by rgommers** [comment] 2015-05-26 20:23
Link to PR that introduced ``solve_toeplitz``: gh-4302. @rmcgibbo would you mind having a look at this one?

**Comment by rmcgibbo** [comment] 2015-05-26 22:55
Yeah, absolutely. I'm currently on vacation; I'll take a look when I get
back.

**Comment by stonebig** [comment] 2015-06-27 09:48
no news on this ?

**Comment by rmcgibbo** [comment] 2015-06-27 23:25
Honestly I really have no idea how to debug this. I can't get a working build toolchain running on windows that includes fortran compilers. I just downloaded and installed Parallel Studio XE 2015 trial version, but i'm getting lots of link errors.

**Comment by ewmoore** [comment] 2015-06-28 00:31
Is that strictly necessary? Could you pull the needed pyx out as it's own module to debug this?

**Comment by rgommers** [comment] 2015-06-30 21:15
Not quite sure what to do with this one right now. Neither marking as knownfail nor removing the whole feature from 0.16.x feels right. Will have to choose one if I'm going to be tagging 0.16.0rc1 before going on holiday on Friday though. 

Thoughts?

**Comment by rmcgibbo** [comment] 2015-06-30 21:29
I'll try to pull out the pyx files as @ewmoore suggested on windows.

**Comment by rgommers** [comment] 2015-06-30 21:37
Thanks @rmcgibbo, that would be helpful. Ideally I'd like to tag rc1 on Thursday (or even tomorrow).

**Comment by rmcgibbo** [comment] 2015-06-30 22:51
It's really odd. I pulled out the files (now here: https://github.com/rmcgibbo/solve_toeplitz). I can reproduce the bug with 64 bit VC2010.

Changing the cython boundscheck compile flag here https://github.com/scipy/scipy/blob/master/scipy/linalg/_solve_toeplitz.pyx#L3 is sufficient to magically "fix" the test failures. Also adding a print statement after this line https://github.com/scipy/scipy/blob/master/scipy/linalg/_solve_toeplitz.pyx#L94 magically fixes the test failures.

**Comment by rmcgibbo** [comment] 2015-06-30 22:51
also cc @mpharrigan, since he seemed interested.

**Comment by rmcgibbo** [comment] 2015-07-01 00:24
think it's a compiler bug. we got it down, editing the c file, such that adding volatile in a couple places fixed the bug.

**Comment by rgommers** [comment] 2015-07-04 08:46
Fixed by gh-5008

**Closed by rgommers** 2015-07-04 08:46 UTC
Labels: defect, scipy.linalg
