### ISSUE TITLE
numerical differences in optimize with L-BFGS-B algorithm between 0.14 and 0.15 versions

### ISSUE THREAD

**Issue by sidenko** [scipy/scipy#5765] opened 2016-01-27 00:07 UTC
Hello,
I see numerous numerical differences in the optimize results (L-BFGS-B method) when switching between 0.14 and 0.15 versions
This has not been mentioned in the release notes
Can it be a potential bug?
Thanks

**Comment by rgommers** [comment] 2016-01-27 15:08
Can you give a self-contained example to reproduce your issue? And how much are the differences? If both answers are correct and within the specified tolerances, then very likely it's not a bug. We don't guarantee that every last digit will be identical between releases (we could never change anything in the code if that would be needed).

**Comment by sidenko** [comment] 2016-01-27 16:28
Unfortunately, I can't show you the function I'm working on as it involves quite a lot of data.
However, here is a simple example I came up with that shows the difference the versions.

import numpy as np
from scipy.optimize import minimize, rosen
minimize(rosen, np.zeros(1000), method='L-BFGS-B')

Since the function is not convex so there is no reason the method would converge, and in fact it does fail to optimize. If you compare the results, you'll see different end points, different numbers of function calls and different function values. It seems to me that the stopping conditions of the numerical implementation of BFGS have been changed, and I can't see anything in the documentation that would support it.

In the case of my function (which is convex, and the Jacobian is computed in closed form), I see the following diffs:
version 0.15:

  status: 0
 success: True
    nfev: 67
     fun: -2833756.9856198905
       x: array([ -79.74170293,  565.58597079, -191.16130584, ...,  128.23815986,
       -156.03194568, -317.89478782])
 message: 'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     jac: array([-0.28895737, -0.09018206, -0.89479308, ..., -0.17342956,
        0.29584287, -0.01748486])
     nit: 62

version 0.14:
  status: 0
 success: True
    nfev: 67
     fun: -2833757.2935406943
       x: array([ -79.7406223 ,  565.58320713, -191.16238346, ...,  128.2377021 ,
       -156.03135866, -317.8955933 ])
 message: 'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     jac: array([-0.28888252, -0.0901078 , -0.8946224 , ..., -0.17330353,
        0.29595101, -0.01745046])
     nit: 62

As you can see, both versions converged to the same minimum, however, they stopped at different points.

**Comment by pv** [comment] 2016-01-27 17:31
Looks just accumulated floating point rounding error to me. Both solutions appear to satisfy the convergence tolerances specified.

Rounding error in general is practice not reproducible in the usual case and can change if e.g. linear algebra libraries are not the same, or code was compiled with different optimization level etc. In particular, on my computer using the same linear algebra libraries for 0.14.0 and 0.15.0, the returned solutions are exactly the same. So I don't think there's any bug --- if you want solutions more accurate, you can tell the algorithm to use a stricter termination tolerance.

**Comment by pv** [comment] 2016-01-27 17:38
There are *no* code changes in lbfgs 0.14.0 vs 0.15.0.

**Comment by rgommers** [comment] 2016-01-27 20:10
seems to not be an issue in scipy, so closing

**Closed by rgommers** 2016-01-27 20:10 UTC
Labels: query, scipy.optimize
