### ISSUE TITLE
BUG: signal.decimate returns NaN with large float32 arrays

### ISSUE THREAD

**Issue by d-chambers** [scipy/scipy#15072] opened 2021-11-19 22:11 UTC
### Describe your issue.

When using decimate with large float32 arrays often arrays will all NaN values are returned.

### Reproducing Code Example

```python
import numpy as np
from scipy.signal import decimate

ar = np.random.random((10_000, 2))

out1 = decimate(ar, 10, axis=0)  # this works fine 

out2 = decimate(ar.astype(np.float32), 10, axis=0)  # returns all NaN

# It also works fine if the arrays smaller

out3 = decimate(ar.astype(np.float32)[::100], 10, axis=0)  # No NaNs in array
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

scipy: 1.6.2, Numpy: 1.18.5, Python: 3.8.5

**Comment by pantelisantonoudiou** [comment] 2021-11-20 15:11
I have replicated this issue with **scipy:1.7.1, Numpy: 1.21.2, Python 3.9.5.**

This error seems to happen only if the filter type is set **_iir_** and the downsampling factor _**q**_ is 9 or greater. I was able to trace down the error to the [_linear_filter](https://github.com/scipy/scipy/blob/1022323f9744c36148e3422f97152d40ce0ccd94/scipy/signal/_lfilter.c.in#L1) function.

```Python
# No NaNs
out1 = signal.decimate(ar.astype(np.float32), 10, axis=0, ftype='fir') 

# No NaNs
out2 = signal.decimate(ar.astype(np.float32), 8, axis=0, ftype='iir')

# returns NaNs
out3 = signal.decimate(ar.astype(np.float32), 9, axis=0, ftype='iir')
```

**Comment by roryyorke** [comment] 2021-11-24 14:13
This is a dupe of gh-13529, though this report is better since it has a motivating example.

I tested with a hacked version of `decimate` that uses `sosfilt` instead of `lfilter`, and the NaNs disappear.  

This should be fixed by gh-14371, though that PR seems to be stalled.

**Closed** 2022-11-20 19:56 UTC
Labels: defect, scipy.signal
