### ISSUE TITLE
Kolmogorov-Smirnov statistic on 2 different samples returns same result

### ISSUE THREAD

**Issue by fostiropoulos** [scipy/scipy#9468] opened 2018-11-12 06:27 UTC
The two pairs of observations will have a largest difference that's got the same small-integer numerator is not remotely surprising -- and they both do, it's 4/13.

The library should provide a warning with the p-value.
### Reproducing code example:

```
from scipy import stats

stats.ks_2samp([ 0.09434497,0.07581871,0.03280419,0.07415525,0.07232668,0.10093938,
  0.10348316,0.06529852,0.10967376,0.07681485,0.00863077,0.10323866,
  0.08247111],[ 0.05823918,0.09467191,0.04121951,0.13934854,0.07375773,0.06355782,
  0.13376396,0.08190715,0.05770731,0.07871597,0.03935798,0.04946341,
  0.08828953])

stats.ks_2samp([ 0.05422732,0.08636203,0.04473298,0.14424102,0.08507371,0.05459249,
  0.13365118,0.08124969,0.05057565,0.08800528,0.0478369,0.04308972,
  0.08636203],
[ 0.06545017,0.0973833,0.03399041,0.05891224,0.07687014,0.08660129,
  0.06096384,0.09967657,0.05154278,0.06509205,0.05573505,0.10797274,
  0.13980942])
```

### Error message:

```
Ks_2sampResult(statistic=0.3076923076923077, pvalue=0.48890821513441646) 

Ks_2sampResult(statistic=0.3076923076923077, pvalue=0.48890821513441646)
```

### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
('1.1.0', '1.11.3', sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0))

**Comment by chrisb83** [comment] 2018-11-14 17:04
What is the concern about the p-value?

**Comment by pvanmulbregt** [comment] 2019-02-09 20:44
I believe that this is functioning as intended.  When comparing any two samples of size `m` and `n`, the D value will always be a fraction between 0 and 1, with denominator `lcm(m, n) = m*n/gcd(m, n)`, so only a finite number of possibilities. The K-S test only uses the maximum difference, so many pairs of samples will generate the same D-value.
What is the warning you would like to see?

**Comment by rgommers** [comment] 2019-08-10 22:55
question is answered and no follow-up, so closing

**Closed by rgommers** 2019-08-10 22:55 UTC
Labels: query, scipy.stats
