### ISSUE TITLE
Precompiled wheels for Windows

### ISSUE THREAD

**Issue by matysek** [scipy/scipy#5461] opened 2015-11-06 12:08 UTC
It would be very helpful to have binary wheel packages for Windows platform.

I think it might work to build those wheels using Appveyor service: http://www.appveyor.com/

**Comment by rgommers** [comment] 2015-11-06 23:31
Would be nice, but there's no way the builds are going to be fast enough for Appveyor. Even for numpy it's quite hard to get Appveyor to work.

**Comment by hashtonmartyn** [comment] 2015-11-17 20:30
There are wheels for OSX version 0.16.1 but not for Windows, what's required to make this happen?

**Comment by pv** [comment] 2015-11-18 01:00
More or less: find someone who is interested to spend effort on it, and knows how to do it.
The discussion on Numpy wheels probably is relevant here, the situation is similar:
https://github.com/numpy/numpy/issues/5479

**Comment by ogrisel** [comment] 2015-12-15 21:10
Furthermore there is no fortran compiler on appveyor. There is the mingwpy that is promising but:

- it does not support Python 3.5 yet (neither in upstream mingw-w64)
- mingwpy is still very experimental and not packaged yet

**Comment by hofst** [comment] 2016-03-23 19:24
I strongly support this request. As it currently stands, scipy is the only package that requires heavy manual workarounds when installing

**Comment by rgommers** [comment] 2016-03-23 19:46
@hofst this is being worked on: you can follow the progress at http://mingwpy.github.io/ (see roadmap there, mailing list and https://github.com/mingwpy)

**Comment by hofst** [comment] 2016-03-23 21:49
@rgommers  great, thank you!

**Comment by cas--** [comment] 2017-03-15 21:11
I am curious as to the state of this issue. Perhaps wheels could be build locally and pushed to PyPi for each release in interim until appvoyeur usage is available. Did you know [ Christoph Gohlke](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy) is providing a range of windows wheels?

So with numpy wheels available on pypi it would be useful for those using Windows who only need to install Python and `pip install scipy` therefore dropping the requirement of bloated freemium Anaconda that seems to be pushed far too much.

**Comment by pv** [comment] 2017-03-15 21:22
You can read the discussion on the numpy ticket linked above to understand the issue in more detail.

**Comment by cas--** [comment] 2017-03-15 21:51
I did read some of it but there is no indication as to what is specifically the issue with providing scipy wheels since that ticket is closed and there are no recent status updates here. It would be good if you could just provide a quick summary?

I am asking because my concern is with the Python distribution ecosystem being fragmented by Anaconda. I was not aware of Anaconda until I started helping with introduction to Python workshops for scientists and was taken aback that they recommended Anaconda from the outset for an introduction series. Since Linux and OSX can use packages or pip wheels, only Windows users are left out now.

**Comment by rgommers** [comment] 2017-03-15 22:14
> I am asking because my concern is with the Python distribution ecosystem being fragmented by Anaconda.

That's a pretty wild mischaracterisation. Conda and pip have complementary strengths (as recognised by the whole Python/distutils-sig community, not just the scientific one), and Anaconda as a commercial distribution solves user issues that otherwise go unsolved. Note that the SciPy in ``conda-forge``, which uses free compilers, also has no Windows builds. 

The issue is simply with missing compiler support for Fortran on Windows, it can only be done reliably with Intel Fortran + Intel MKL at the moment which is $$-only. The most likely candidate to solve the compiler availability issue at this point is Flang, which will be open-sourced quite soon.

**Comment by ilayn** [comment] 2017-03-15 22:16
As a summary, MKL license, compiler license, lack of support by MS for Fortran, community size (compared to GNU umbrella), runtime mania (look at Add/Remove programs for Visual C++ entries at least 17 of them). DLL hell and so on. 

If @cgohlke stops providing those wheels, scientific stack would receive a major blow so s/he is doing an amazing service to the community.

**Comment by ogrisel** [comment] 2017-03-16 09:24
> The most likely candidate to solve the compiler availability issue at this point is Flang, which will be open-sourced quite soon.

+1, once we have an opensource flang working on windows and generating binary extensions that are compatible with programs built with the MS 2015 C/C++ toolchain we can generate windows wheels for scipy and upload them to PyPI (for Python 3.5+).

This might take some time to get there though.

**Comment by matthew-brett** [comment] 2017-03-16 17:01
On Wed, Mar 15, 2017 at 3:14 PM, Ralf Gommers <notifications@github.com>
wrote:

> I am asking because my concern is with the Python distribution ecosystem
> being fragmented by Anaconda.
>
> That's a pretty wild mischaracterisation. Conda and pip have complementary
> strengths (as recognised by the whole Python/distutils-sig community, not
> just the scientific one)
>

As Ralf knows, I don't think this is a much of a mischaracterization, and
the overlap between conda and pip is much greater than the difference.
Indeed, I think the support work for binary installation is fragmented.

There's a discussion of these issues over at https://github.com/scipy/
scipy.org/pull/179

That said, everyone does agree that we really really need to build Scipy
wheels for Windows.

As Olivier said, the problem we can't overcome at the moment is a lack of a
license compatible Fortran compiler that can link with the MS Visual C++
2015 runtimes used by the standard Python.org Windows binaries for Python
>= 3.5.

Options are:

* Intel Fortran modifies its run-time license for us and gives us some
licenses (see: https://software.intel.com/en-us/comment/1881526#comment-
1881526).
* mingw-w64 gets support for linking against MS Visual C++ runtimes.
Unfortunately the only person who appears to be in a position to do that
work is currently employed by Continuum, and we do not have the money to
pay Continuum for his development time;
* flang - an LLVM Fortran compiler that hasn't been released yet.   It
sounds as though it will need some work to get it to link to the MS VC++
runtimes, but we can't tell until we see some code we can play with - ETA
is 'real soon now'.

**Comment by rgommers** [comment] 2017-03-27 09:41
>  Intel Fortran modifies its run-time license for us and gives us some licenses (see:
> https://software.intel.com/en-us/comment/1881526#comment-1881526).

I'm pretty sure that that license won't change. Nathaniel also talked to some Intel people last year (more authoratative ones than on the support forum) and confirmed that building with Intel Fortran is not going to happen.

**Comment by xoviat** [comment] 2017-04-16 01:47
May I ask why @cgohlke is able to post the wheels on his website but numpy/scipy is not able to post the wheels on pip?

**Comment by matthew-brett** [comment] 2017-04-17 09:17
You may certainly ask :).   We do post numpy wheels.  Scipy wheels need Fortran, for which the only current option is Intel Fortran.   That makes the wheels susceptible to the Intel Fortran run-time license, which makes the person releasing the wheels responsible for any legal fees incurred by Intel if someone sues Intel as a result of using Scipy (compiled with Intel Fortran).   Christoph is very generously taking on that risk, but we (the scipy org) do not think we should or can take on that risk.

**Comment by xoviat** [comment] 2017-04-17 14:24
Another option is using `f2c` to translate to intermediate C that can then be compiled with MSVC.

**Comment by matthew-brett** [comment] 2017-04-17 18:40
Yes, that would be an option if the Fortran was all f77, but I believe that is no longer the case.

**Comment by rgommers** [comment] 2017-04-20 10:40
> Yes, that would be an option if the Fortran was all f77, but I believe that is no longer the case.

AFAIK we haven't merged any Fortran 90/95 code yet, but there is at least one PR that would add such code, and we don't want to block adding more later.

**Comment by xoviat** [comment] 2017-04-20 15:56
> AFAIK we haven't merged any Fortran 90/95 code yet, but there is at least one PR that would add such code, and we don't want to block adding more later.

Perhaps this could be placed in a separate folder so that only the f77 functions are available in the wheels. It's not an ideal solution but frankly the lack of available wheels is wasting everyone's time.

**Comment by rgommers** [comment] 2017-04-20 20:32
> Perhaps this could be placed in a separate folder so that only the f77 functions are available in the wheels. 

I don't think we want to ship incomplete versions of scipy like that. Plus ``f2c`` is not a great solution anyway. Within the next month or so we expect an announcement of a Fortran front-end for Clang being open sourced. That is currently the most promising way forward.

> It's not an ideal solution but frankly the lack of available wheels is wasting everyone's time.

It is a pain, but we have limited control over it. There's a reason that we strongly recommend users to use Anaconda, Canopy or similar. Windows + compilers + pip/wheels is a bad idea for scientific work even if we would have a wheel available.

**Comment by matthew-brett** [comment] 2017-05-24 22:09
See https://github.com/conda-forge/openblas-feedstock/issues/2#issuecomment-303798271 for update on Flang.  Summary: still some way off being useful to us, but at least it's open source now.

**Comment by xoviat** [comment] 2017-07-12 19:45
@matthew-brett Why not compile a dll with the gcc stack and then call wrapper c functions from the msvc stack?

**Comment by matthew-brett** [comment] 2017-07-13 23:41
Some possible progress on wheel building over at https://github.com/scipy/scipy/issues/7597

**Comment by matthew-brett** [comment] 2017-07-13 23:44
@xoviat - could you expand on your suggestion?   At the moment I am not sure what you mean.

**Comment by xoviat** [comment] 2017-07-14 02:47
@matthew-brett I actually found a blog post [here](https://blog.kitware.com/fortran-for-cc-developers-made-easier-with-cmake/) that explains the idea pretty well (nothing in computer science is a new idea anymore). 

Basically the only officially supported ABI bridge between gcc and msvc is through a DLL. It is therefore possible to automatically detect all calls to fortran code (because the caller is typically c or c++, not python which would make that impossible) and then generate wrappers:

1. On the MSVC side, replace the fortran calls with wrapper functions that create a load-time dependency on an imaginary DLL that we will create. Simply put, `__declspec(dllimport)`.
2. On the gfortran side, wrap all functions with C code that exports from the DLL. Simply put, `__declspec(dllexport)`.

Cmake apparently had this idea long before I did and makes this effortless. However, I am actually not familiar with the scipy build system so I am not sure what would be required here.

**Comment by pv** [comment] 2017-09-02 13:37
Prerelease wheels are available as explained [in a post on the mailing list](https://mail.python.org/pipermail/scipy-dev/2017-August/022050.html). Testing is welcome.

**Comment by Juanlu001** [comment] 2017-09-02 14:15
I did try them and work like a charm, no issues found.

**Comment by mikofski** [comment] 2017-09-07 17:42
@rgommers @ogrisel @matthew-brett and others, any news on the open-source Flang LLVM option? Will the [mingwpy + generic MSVCRT](https://github.com/scipy/scipy/issues/7597) be the final solution? What are the differences between the two proposals? Is anyone working on the Flang LLVM option, or still waiting for it to be open-sourced? I've found numerous online references to Flang, but I can figure out what or which is the most significant effort, and what their states are.

There seem to be at least two versions of Flang:
* https://github.com/llvm-flang/flang - this is the original FORTRAN front-end for LLVM
* https://github.com/flang-compiler/flang - I think this is the PGI effort

I hope this doesn't come across as favoring one solution (flang v. mingwpy) over another. I am extremely grateful for any solution. I am just curious. Thanks!

**Comment by xoviat** [comment] 2017-09-07 17:46
The latter of the two links is the correct effort but someone needs to implement windows support. It's even worse than that, though because even with the fortran compiler, we still could not link OpenBLAS.

**Closed** 2017-10-28 14:15 UTC
Labels: Build issues
