### ISSUE TITLE
BUG: Inconsistent Non central T pdf output

### ISSUE THREAD

**Issue by boricua-hg** [scipy/scipy#19450] opened 2023-10-29 19:39 UTC
### Describe your issue.

When trying to plot the non-central-t pdf for different degreed of freedom, the output is infinity (when it should not). For example, the code below with n = 13 will result in only 3 data points, the rest are inf. If one runs the code with n = 14 then a complete pdf is obtained. Can't figure out if it may be related to issue #8344

### Reproducing Code Example

```python
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from scipy import special

n = 15
alpha = 0.05
Kp = stats.norm.ppf(0.99)
nc1 = special.nctdtrinc(n - 1, 1 - alpha, -Kp * n ** 0.5)
print(nc1)
nctv = stats.nct(n - 1, nc1)
x = np.linspace(nctv.ppf(0.00001), nctv.ppf(0.99995), 150)
y = nctv.pdf(x)
plt.plot(-x / (n **0.5), y, alpha=0.6)
plt.show()
```

### Error message

```shell
No error message. Output does not make sense as one changes the degrees of freedom
```

### SciPy/NumPy/Python version and system information

```shell
1.11.3 1.26.1 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.36",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.14.0",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-dic8cvan\\overlay\\Lib\\site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.11.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-_etjukwv\\cp311-win_amd64\\build\\venv\\Scripts\\python.exe",
    "version": "3.11"
  }
}
```

**Comment by mdhaber** [comment] 2023-10-29 20:21
This is essentially a duplicate of gh-19348, so I don't think they need to be tracked separately. I'll include a note there that this issue has some additional test cases.

**Closed by mdhaber** 2023-10-29 20:21 UTC
Labels: defect, scipy.stats
