### ISSUE TITLE
DEP: Bump numpy minversion to 1.19?

### ISSUE THREAD

**Issue by pllim** [scipy/scipy#15209] opened 2021-12-13 19:18 UTC
Currently:

https://github.com/scipy/scipy/blob/f34de3a87010bebf6cc1e9474dc58d315d75f52d/setup.py#L542

But one can still do the following (say, in Python 3.9.7):

```
pip install "numpy==1.18.5"
pip install "scipy==1.7.3"  # Does not attempt to upgrade numpy
```

and then encounter this error:

```
>>> from scipy import signal

...\scipy\signal\__init__.py in <module>
    308 from .spectral import *
    309 from .wavelets import *
--> 310 from ._peak_finding import *
    311 from .windows import get_window  # keep this one in signal namespace
    312

...\scipy\signal\_peak_finding.py in <modul
e>
      6
      7 from scipy.signal.wavelets import cwt, ricker
----> 8 from scipy.stats import scoreatpercentile
      9
     10 from ._peak_finding_utils import (

...\scipy\stats\__init__.py in <module>
    439 """
    440
--> 441 from .stats import *
    442 from .distributions import *
    443 from .morestats import *

...\scipy\stats\stats.py in <module>
     41 import scipy.special as special
     42 from scipy import linalg
---> 43 from . import distributions
     44 from . import mstats_basic
     45 from ._stats_mstats_common import (_find_repeats, linregress, theilslope
s,

...\scipy\stats\distributions.py in <module
>
      9
     10 from . import _continuous_distns
---> 11 from . import _discrete_distns
     12
     13 from ._continuous_distns import *

...\scipy\stats\_discrete_distns.py in <mod
ule>
     17     _check_shape)
     18 import scipy.stats._boost as _boost
---> 19 from .biasedurn import (_PyFishersNCHypergeometric,
     20                         _PyWalleniusNCHypergeometric,
     21                         _PyStochasticLib3)

biasedurn.pyx in init scipy.stats.biasedurn()

ModuleNotFoundError: No module named 'numpy.random.bit_generator'
```

Workaround: Manually upgrade numpy.

ref: https://numpy.org/doc/stable/release/1.19.0-notes.html#numpy-random-bit-generator-moved-to-numpy-random-bit-generator

cc @duytnguyendtn

**Comment by rgommers** [comment] 2021-12-13 21:25
Thanks for the report @pllim. This is a duplicate of gh-14541 I believe. We cannot change the minimum required NumPy for `1.8.0` anymore; we'll bump it in master to `1.18.x` soon, and solve this `bit_generator` issue along the lines of https://github.com/scipy/scipy/issues/14541#issuecomment-968317738. If it turns out to be easy, then we could backport the fix to `1.8.1` or `1.8.2`.

I'll close this issue. In case I missed something here and it's not an exact duplicate, please let me know.

**Closed by rgommers** 2021-12-13 21:25 UTC
Labels: duplicate

**Comment by pllim** [comment] 2021-12-13 21:51
Thanks for the quick reply!

**Comment by duytnguyendtn** [comment] 2021-12-13 21:51
Thank you @rgommers for the insight and @pllim for escalating this issue!
