### ISSUE TITLE
appveyor: fix 32 bit build failures

### ISSUE THREAD

**Issue by xoviat** [scipy/scipy#7726] opened 2017-08-13 01:22 UTC
@matthew-brett @pv

**Comment by xoviat** [comment] 2017-08-13 01:23
> I suspect the 32-bit hang at least is an issue in CDFLIB, which at least locally according to gdb enters an infinite loop, as the code is ancient and not written with nans in mind. Moreover, it has persistent state that it apparently doesn't reset properly, giving a plausible mechanism for spurious failures e.g. due to test ordering. Not going to look at this today though.

**Comment by matthew-brett** [comment] 2017-08-13 21:35
The following from @pv in https://github.com/scipy/scipy/pull/7616#issuecomment-321995955:

"""
So as a summary on the 32-bit builds:

- `libopenblas_5f998ef_vanilla.a`: appveyor either successful + [one hang](https://ci.appveyor.com/project/scipy/scipy/build/1.0.94/job/pamjuv6wut9fytn5)
- `libopenblas_5f998ef_gcc7_1_0.a`: appveyor hangs
- `lapack.a`: all builds on appveyor were successful
- `libopenblas_5f998ef_mingwpy.a`: builds on appveyor fail

Locally, both `lapack.a` and `libopenblas_5f998ef_vanilla.a` hang in TestCephes::test_ncfdtridfn.
"""

Updating:

- `libopenblas_5f998ef_vanilla.a`: in "fast" mode - appveyor either [successful](https://ci.appveyor.com/project/scipy/scipy/build/1.0.89/job/1p4masjss5fnj1hp) + [one hang](https://ci.appveyor.com/project/scipy/scipy/build/1.0.94/job/pamjuv6wut9fytn5)
- `libopenblas_5f998ef_gcc7_1_0.a`: in 'fast' mode - appveyor [passes](https://ci.appveyor.com/project/matthew-brett/scipy/build/1.0.3/job/4ok2pu59uw5rvxcn), [hangs](https://ci.appveyor.com/project/scipy/scipy/build/1.0.91/job/qufwv3jg5sh86afb) , or [hangs with an extra failure near the start](https://ci.appveyor.com/project/scipy/scipy/build/1.0.90/job/p0rm4sx6tn471g49).  In "full" test mode, [one hang](https://ci.appveyor.com/project/matthew-brett/scipy/build/1.0.4/job/3hske4atsm0jbtyj) at `[00:21:27] ..\..\::TestEntropy::test_entropy_base <- ..\..\Python36\lib\site-packages\scipy\stats\tests\test_distributions.py`

So far, my guess is these hangs and single failure are not deterministic, and there is no difference between the `vanilla` and `gcc7_1_0` builds.

**Comment by pv** [comment] 2017-08-13 21:40
If you want to test without the hang complicating things, you can pick commits from gh-7727 to convert it to an ordinary test failure. This issue does not seem to be related to blas/lapack.

**Comment by matthew-brett** [comment] 2017-08-13 23:00
I merged gh-7727 - sure enough, no hang, single test failure from "full" tests:

https://ci.appveyor.com/project/matthew-brett/scipy/build/1.0.7

**Comment by matthew-brett** [comment] 2017-08-13 23:36
Oops - actually, 2 failures for Python 3.5:

```
[00:19:10] self = <scipy.special.tests.test_basic.TestCephes object at 0x0AF3EB90>
...
[00:19:11] self = <scipy.special.tests.test_mpmath.TestSystematic object at 0x0FFA40B0>
```

https://ci.appveyor.com/project/matthew-brett/scipy/build/1.0.7/job/y62y3wtay5aq7a4v/tests

**Comment by pv** [comment] 2017-08-14 16:17
Looks fine then, as far as openblas is concerned. I think we can switch to its more reproducible build if you like.

**Comment by pv** [comment] 2017-08-15 19:51
A minimal repro for the hang on 32-bit locally turns out to be:
```
import numpy as np
from scipy.special import ncfdtridfn
np.absolute(complex(np.inf, 0))
ncfdtridfn(0.926, 2, 0.25, 15)  # <- hangs here
```
It does not hang, if np.inf is changed to a finite fp value (inf and nan cause a hang in ncfdtridfn).

The hang only occurs with gfortran optimization levels larger than `-O0` used to compile cdflib.

Setting a breakpoint at the computational function `cdffnc_`, the value of the fp register `fctrl` differs in the two cases --- it's `0x027f` (53-bit precision) in the "good" case and `0x137f` (64-bit precision) in the "bad" case.

Doing `set $fctrl = 0x137f` or `set $fctrl = 0x037f` after entering `cdffnc_` in gdb results to a hang also in the "good" case, in the same place. (But this does not result to a hang on gfortran optimization level `-O0`.)

There are no long doubles in the code.

This occurs both with self-compiled numpy, and with the 32-bit numpy 1.13.1 wheels from pypi (with the distutils folder replaced after installation).

I do not immediately understand why np.absolute on complex np.nan/np.inf changes fp mode, but not if operating on finite values. I do not know if it is allowed to change the fp mode, or if it's a bug that it does.

Ideas @carlkl, @xoviat?

**Comment by xoviat** [comment] 2017-08-15 20:04
Well, if it doesn't occur on O0 then it's obviously an optimization bug. The simplest way to proceed would probably be to turn on one optimization flag at a time until it fails:

```
-fauto-inc-dec 
-fbranch-count-reg 
-fcombine-stack-adjustments 
-fcompare-elim 
-fcprop-registers 
-fdce 
-fdefer-pop 
-fdelayed-branch 
-fdse 
-fforward-propagate 
-fguess-branch-probability 
-fif-conversion2 
-fif-conversion 
-finline-functions-called-once 
-fipa-pure-const 
-fipa-profile 
-fipa-reference 
-fmerge-constants 
-fmove-loop-invariants 
-freorder-blocks 
-fshrink-wrap 
-fshrink-wrap-separate 
-fsplit-wide-types 
-fssa-backprop 
-fssa-phiopt 
-ftree-bit-ccp 
-ftree-ccp 
-ftree-ch 
-ftree-coalesce-vars 
-ftree-copy-prop 
-ftree-dce 
-ftree-dominator-opts 
-ftree-dse 
-ftree-forwprop 
-ftree-fre 
-ftree-phiprop 
-ftree-sink 
-ftree-slsr 
-ftree-sra 
-ftree-pta 
-ftree-ter 
-funit-at-a-time
```

Of course that's quite a bit of options but you can eliminate half at a time. (turn on first half only, does it happen).

**Comment by pv** [comment] 2017-08-15 20:09
Optimization or assumptions. Is the compiler allowed to assume something about the active floating point mode?

**Comment by xoviat** [comment] 2017-08-15 20:14
Possibly this:

> -fexcess-precision=style
> This option allows further control over excess precision on machines where floating-point operations occur in a format with more precision or range than the IEEE standard and interchange floating-point types. By default, -fexcess-precision=fast is in effect; this means that operations may be carried out in a wider precision than the types specified in the source if that would result in faster code, and it is unpredictable when rounding to the types specified in the source code takes place. When compiling C, if -fexcess-precision=standard is specified then excess precision follows the rules specified in ISO C99; in particular, both casts and assignments cause values to be rounded to their semantic types (whereas -ffloat-store only affects assignments). This option is enabled by default for C if a strict conformance option such as -std=c99 is used. -ffast-math enables -fexcess-precision=fast by default regardless of whether a strict conformance option is used.
> 
> -fexcess-precision=standard is not implemented for languages other than C. On the x86, it has no effect if -mfpmath=sse or -mfpmath=sse+387 is specified; in the former case, IEEE semantics apply without excess precision, and in the latter, rounding is unpredictable.

**Comment by pv** [comment] 2017-08-15 20:24
So is there something in the DLL calling convention that says that fp mode must have some specific value. Or is it up to the DLL called to set it as necessary? Does mingw  generate code that sets the fp mode on entry to DLL functions (apparently no)?

**Comment by xoviat** [comment] 2017-08-15 20:33
If it's this one function (and apparently it is), we should be able to reset the fp mode [here](https://github.com/scipy/scipy/blob/2526df72e5d4ca8bad6e2f4b3cbdfbc33e805865/scipy/special/cdf_wrappers.c#L247) with [_ctrlfp](https://msdn.microsoft.com/en-us/library/e9b52ceh.aspx).

**Comment by xoviat** [comment] 2017-08-15 20:38
>  Does mingw generate code that sets the fp mode on entry to DLL functions

It should. DLLs are supposed to set up their registers correctly on entry. They're less efficient for static libs partly for that reason.

**Comment by carlkl** [comment] 2017-08-15 22:03
Changing the FPU mode to 64-bit precision is an evil feature of vanilla mingw-w64. *BTW: mingwpy default behaviour is NOT to do that, as this is not standard Windows ABI.* Many libraries on Windows depends on correct FPU setting (53bit).

This FPU mode is only needed for long doubles but unfortunately also affects calculations with double precision values. A changed FPU setting should always be resetted to default by the callee, however, the mingw-w64 collaberation decided for a FPU default mode as used by Linux.

I guess the change of the FPU mode is the effect of using numpy OpenBLAS compiled with vanilla mingw-w64 or another DLL included in the scipy wheel (this has to be checked)

Linking `CRT_fp8.o` while using binutils helps to change mingw-w64 default to the standard 53bit precision setting.

I have no access to my dev machine at the moment, so a more detailed investigation is not possible right now.

**Comment by pv** [comment] 2017-08-15 22:08
Numpy issue: https://github.com/numpy/numpy/issues/9567

**Comment by pv** [comment] 2017-08-15 22:23
The precision mode change itself does not seem to be due to openblas --- the issue is reproducible without scipy at all (see numpy/numpy#9567) and is due to plain numpy functions that don't use linear algebra. Calling np.linalg functions also does not seem to change the precision mode, so it may be the issue is limited to only np.absolute.

**Comment by xoviat** [comment] 2017-08-15 22:24
@pv Nice job coming up with that Python extension!

**Comment by matthew-brett** [comment] 2017-08-16 01:52
@pv - from the discussion over at the Numpy thread, this should not happen on Python 2.7 - but I see I have a test failure on Python 2.7 : https://ci.appveyor.com/project/matthew-brett/scipy/build/1.0.7/job/f5l97s5l68cdqga5/tests

Does this failure have another cause?

**Comment by pv** [comment] 2017-08-16 02:56
that looks like a different failure i.e. not in ncfdtridfn, with likely a
different cause. Possible suspect for that one is the old msvc9 compiler
math library.

16.8.2017 3.52 "Matthew Brett" <notifications@github.com> kirjoitti:

**Comment by pv** [comment] 2017-08-16 19:42
The problematic MSVC function is now blacklisted in numpy, and the hang becomes just a wrong result compute due to the nan-safety changes in gh-7727. The right thing is probably to mark this one as an xfail on win32, as numpy seems like a better place to fix it.

**Closed** 2017-08-18 20:23 UTC
