### ISSUE TITLE
dblquad gives different results under scipy 0.17.1 and 0.18.1

### ISSUE THREAD

**Issue by ketch** [scipy/scipy#6889] opened 2016-12-26 14:00 UTC
We are seeing different results (leading to a test regression) when upgrading to scipy 0.18.1 from version 0.17.1.  The call that gives different results seems to be line 102 of https://github.com/clawpack/pyclaw/blob/master/examples/euler_3d/Sedov.py.  See also https://github.com/clawpack/pyclaw/issues/555.

**Comment by rgommers** [comment] 2016-12-27 04:01
@ketch there's a couple of bug fixes in 0.18.1, but it's not clear that those are wrong. Looking at your test result, it complains about:

    norm of expected data: 71.8833212966
    norm of test data    : 71.879558627
    test error           : 0.0107725438014
    reltol  : 1e-06

Are you sure that the expected result is correct? It seems to just be whatever ``dblquad`` gave you before.

If you do think that the results you got with 0.17.1 were more accurate, could you provide a reproducible example?

**Comment by ketch** [comment] 2016-12-27 06:23
Thanks for your attention to this.

That's right. My concern is that, as far as I can tell, none of those fixes were intended to change the numerical values returned by dblquad.  So this appears to be an unintended change -- a bug. 

 Was one of those commits expected to change the return value?  If you could point me to it then I could see if it should improve things for my application.

**Comment by pv** [comment] 2016-12-28 19:25
The relevant commits are here: https://github.com/scipy/scipy/commits/master/scipy/integrate/quadpack.py --- some things appear indeed wrong eg epsrel/epsabs are ignored, which is probably the cause.

**Comment by ketch** [comment] 2016-12-29 06:48
@pv Thanks, you're right!  We were also seeing a huge slowdown, which is explained by the fact that the error tolerances are ignored (you can see that in our code the tolerances are set very loose and we have to evaluate a large number of integrals.  This is definitely a bug.

**Comment by ev-br** [comment] 2017-01-03 23:02
Grr. This, gh-6898 and https://github.com/scipy/scipy/pull/6495 seem to make the case for a 0.18.2

**Comment by rgommers** [comment] 2017-01-04 03:49
I think gh-6495 is not super high prio, but if we can get this fixed well before we get to 0.19.0 then yes, agree that 0.18.2 makes sense.

**Comment by ev-br** [comment] 2017-02-15 17:15
Fixed by https://github.com/scipy/scipy/pull/6965.

**Closed by ev-br** 2017-02-15 17:15 UTC
Labels: defect, scipy.integrate
