### ISSUE TITLE
ENH: nested loops in pdist make it slow

### ISSUE THREAD

**Issue by ajenney** [scipy/scipy#18065] opened 2023-02-27 22:40 UTC
### Describe your issue.

Calling the scipy.spatial.distance.pdist is slower than manually calculating the redundant distance matrix and then converting to a reduced matrix with squareform. This is not a desirable workflow (for memory reasons) when N (the number of rows) is large. This is due to nested loops in source code _pdist_callable:

Working code that executes when pdist is called:
```
def _pdist_callable(X, *, out, metric, **kwargs):
    n = X.shape[0]
    out_size = (n * (n - 1)) // 2
    dm = _prepare_out_argument(out, np.double, (out_size,))
    k = 0
    for i in range(X.shape[0] - 1):
        for j in range(i + 1, X.shape[0]):
            dm[k] = metric(X[i], X[j], **kwargs)
            k += 1
    return dm
```

Suggestion to improve speed:
```
def _pdist_callable(X, *, out, metric, **kwargs):
    n = X.shape[0]
    dm = []
    for i in range(n - 1):
        j = i+1
        dm.append(metric(X[i], X, **kwargs)[j:])
    dm = np.concatenate(dm)
    return dm
```

This will work assuming function "metric" can handle 2D input. 

### Reproducing Code Example

```python
import numpy as np
from scipy.spatial.distance import squareform
from scipy.spatial.distance import pdist
# ---

N = 1000
y = 33

X = np.random.rand(N,y)

# Calculate manually (fast):
d = []
for i in range(N):
    d.append(np.max(np.abs(X[i,:] - X),axis=1))

d = np.reshape(np.concatenate(d),(N,N))
dvec=squareform(d)

# Calculate using pdist (slow)
def fdist(d1,d2):
    distance=abs(d1-d2).max()
    return distance

dvec_scipy_pdist = pdist(X, metric=fdist)
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version information

lapack_mkl_info:     libraries = ['mkl_rt', 'pthread']     library_dirs = ['/global/homes/a/ajenney/.conda/envs/plotenv/lib']     define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]     include_dirs = ['/global/homes/a/ajenney/.conda/envs/plotenv/include'] lapack_opt_info:     libraries = ['mkl_rt', 'pthread']     library_dirs = ['/global/homes/a/ajenney/.conda/envs/plotenv/lib']     define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]     include_dirs = ['/global/homes/a/ajenney/.conda/envs/plotenv/include'] blas_mkl_info:     libraries = ['mkl_rt', 'pthread']     library_dirs = ['/global/homes/a/ajenney/.conda/envs/plotenv/lib']     define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]     include_dirs = ['/global/homes/a/ajenney/.conda/envs/plotenv/include'] blas_opt_info:     libraries = ['mkl_rt', 'pthread']     library_dirs = ['/global/homes/a/ajenney/.conda/envs/plotenv/lib']     define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]     include_dirs = ['/global/homes/a/ajenney/.conda/envs/plotenv/include'] Supported SIMD extensions in this NumPy install:     baseline = SSE,SSE2,SSE3     found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2     not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL

**Comment by tupui** [comment] 2023-03-01 10:13
Hi @ajenney, thank you for reporting.

As you pointed out, improving the function would require some assumption on vectorisation abilities of the `callable`. One concern with updating the code is backward compatibility. One way I could see to support that feature would be to add an `axis` and/or `vectorize` parameter to `pdist`.

@tylerjereddy what do you think? Is this something we would want to support?

**Comment by tylerjereddy** [comment] 2023-03-01 16:41
@tupui I'm assuming that the reproducer here is what the user actually wants to calculate, rather than an abstract philosophical argument that we should provide faster custom-metric performance. I think, in general, if there's a heavily-used metric we don't support we should just add it to our C++/compiled metric backend. 

But here, for the "reproducer," I can easily outperform the described "fast" scenario by more than an order of magnitude by using `pdist` as intended with the built-in C++/compiled backend (see below), so i don't see any merit to the specific proposal at the moment.

```python
import time
import numpy as np
from numpy.testing import assert_allclose
from scipy.spatial.distance import squareform
from scipy.spatial.distance import pdist
# ---

N = 1000
y = 33

X = np.random.rand(N,y)

start = time.perf_counter()
# Calculate manually (fast):
d = []
for i in range(N):
    d.append(np.max(np.abs(X[i,:] - X),axis=1))

d = np.reshape(np.concatenate(d),(N,N))
dvec=squareform(d)
end = time.perf_counter()
print("Time for reported fast method (s):", end - start)

start = time.perf_counter()
# Calculate using pdist (slow)
def fdist(d1,d2):
    distance=abs(d1-d2).max()
    return distance

dvec_scipy_pdist = pdist(X, metric=fdist)
end = time.perf_counter()
print("Time for reported slow custom pdist method (s):", end - start)
assert_allclose(dvec_scipy_pdist, dvec)

start = time.perf_counter()
# calculate the distance using built-in compiled backend
dvec_scipy_built_in = pdist(X, metric="chebyshev")
end = time.perf_counter()
print("Time for intended usage of pdist (s):", end - start)
assert_allclose(dvec_scipy_built_in, dvec)
```

```
Time for reported fast method (s): 0.08268804987892509
Time for reported slow custom pdist method (s): 1.0133053730241954
Time for intended usage of pdist (s): 0.007285732077434659
```

So, if @ajenney can just do that, I suggest we close this. If they are genuinely arguing that we should support faster behavior with custom/arbitrary Python-defined distance functions, that seems like a more complicated discussion, but I think I'd prefer to see a specific example in that case, i.e., that can't be easily composed from our current offering of metrics.

**Comment by tupui** [comment] 2023-03-01 16:46
Thanks Tyler. Agreed let's close it then 👍 

For the record, I did not look at OP's code. I could see the argument been made in general. But I agree with your rational that if there is a missing useful metric, then we should just add it to our backend. In the end that's a conveniency we offer to also accept a callable and if users have more advanced needs, well there is less value with what we propose and they can as well build their custom solution.

**Closed by tupui** 2023-03-01 16:46 UTC
Labels: enhancement, scipy.spatial
