### ISSUE TITLE
cluster.hierarchy.linkage with method='single' causes infinite recursion.

### ISSUE THREAD

**Issue by IwoHerka** [scipy/scipy#7512] opened 2017-06-20 21:17 UTC
I'm trying to perform hierarchical clustering on sparse observation matrix. The matrix represents movie ratings for a number of users. However, running `linkage([ndarray], method='single')`
causes infinite recursion and `linkage([ndarray], method='single', metric='cosine')` crashes. `ward` works fine.

Cheers.

### Reproducing code example:
Data source: https://www.librec.net/datasets/filmtrust.zip
Data format (`ratings.dat`):
```
[...]
36 6 4
36 250 3.5
36 219 3.5
36 234 3
36 211 4
[...]
```
```
import numpy as np

from scipy.sparse import dok_matrix
from scipy.cluster import hierarchy

def load_ratings(path):
    ratings = {}
    items = set([])

    with open(path, 'r') as data:
        for line in data.readlines():
            rating = [e for e in line.replace('\n', '').split(' ')]
            items.add(int(rating[1]))

            if not int(rating[0]) in ratings:
                ratings[int(rating[0])] = {}

            ratings[int(rating[0])][int(rating[1])] = float(rating[2])

    return (ratings, items)

ratings, items = load_ratings('ratings.txt')

R = dok_matrix((max(items) + 1, max(ratings) + 1), dtype=np.float32)

for user in ratings:
    for item in ratings[user]:
        R[item, user] = ratings[user][item]

R = R.transpose().toarray()
Z = hierarchy.linkage(R, method='single')

# This exceeds maximum recursion depth
hierarchy.dendrogram(Z)
```
Input matrix (`R`):
```
[[ 0.   0.   0.  ...,  0.   0.   0. ]
 [ 0.   2.   4.  ...,  0.   0.   0. ]
 [ 0.   0.   0.  ...,  0.   0.   0. ]
 ..., 
 [ 0.   0.   0.  ...,  0.   0.   0. ]
 [ 0.   0.   4.  ...,  0.   0.   0. ]
 [ 0.   1.5  3.  ...,  0.   0.   0. ]]
```

### Error message 1
```
[...]
651, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/siegmeyer/.local/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 2651, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/siegmeyer/.local/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 2651, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/siegmeyer/.local/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 2618, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/home/siegmeyer/.local/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 2530, in _dendrogram_calculate_info
    leaf_label_func, i, labels)
  File "/home/siegmeyer/.local/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 2403, in _append_singleton_leaf_node
    ivl.append(str(int(i)))
RecursionError: maximum recursion depth exceeded while getting the str of an object
```
### Error message 2 (with `metric='cosine'`)
```
Traceback (most recent call last):
  File "cosine_similarity.py", line 100, in <module>
    Z = hierarchy.linkage(R, metric='cosine')
  File "/home/siegmeyer/.local/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 676, in linkage
    raise ValueError("The condensed distance matrix must contain only finite values.")
ValueError: The condensed distance matrix must contain only finite values.
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment] 2017-06-25 11:03
@IwoHerka thanks for the report. There's a couple of issues with your example (data file named ``ratings.txt`` not ``filmtrust_ratings.dat``), and missing the actual failing function call. Note that for single linkage it is ``dendrogram`` that is failing, not ``linkage``. Here's a reproducing version:

    import numpy as np

    from scipy.sparse import dok_matrix
    from scipy.cluster import hierarchy

    def load_ratings(path):
        ratings = {}
        items = set([])

        with open(path, 'r') as data:
            for line in data.readlines():
                rating = [e for e in line.replace('\n', '').split(' ')]
                items.add(int(rating[1]))

                if not int(rating[0]) in ratings:
                    ratings[int(rating[0])] = {}

                ratings[int(rating[0])][int(rating[1])] = float(rating[2])

        return (ratings, items)

    pack = load_ratings('ratings.txt')
    ratings = pack[0]
    items = pack[1]

    R = dok_matrix((max(items) + 1, max(ratings) + 1), dtype=np.float32)

    for user in ratings:
        for item in ratings[user]:
            R[item, user] = ratings[user][item]

    R = R.transpose().toarray()
    Z = hierarchy.linkage(R, method='single')

    # This exceeds maximum recursion depth
    hierarchy.dendrogram(Z)

That's indeed a problem, and a duplicate of issue https://github.com/scipy/scipy/issues/7271#issuecomment-295698326

**Comment by rgommers** [comment] 2017-06-25 11:15
The second one is not about ``cluster.hierarchy`` but about the distance metric. The issue is that with the ``cosine`` metric you'll get nans. The problem reduces to:

    R = R.transpose().toarray()
    dist = distance.pdist(R, 'cosine')
    assert np.isfinite(dist).all()

It looks like ``R`` has a bunch of zeros in them, and the definition of cosine is:

   1 - \frac{u \cdot v}
            {||u||_2 ||v||_2}.

which I guess explains the nans. You can't have zero vectors for ``'cosine'``, and it looks like ``R`` contains a lot of them. Can you check that?

**Comment by IwoHerka** [comment] 2017-06-25 11:33
@rgommers Updated the code example, thanks. Regarding your second comment - yeah, it fails the assertion.

**Comment by rgommers** [comment] 2017-06-25 11:50
Thanks for checking. Given that ``'cosine'`` is not supposed to work here and the ``dendrogram`` bug is a duplicate, I will close this issue.

**Closed by rgommers** 2017-06-25 11:50 UTC
Labels: defect, scipy.cluster
