### ISSUE TITLE
ordqz segfault on Python 3.4 in Wine

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5577] opened 2015-12-04 10:53 UTC
```
>>> from scipy import linalg as l
>>> l.test('full', verbose=10)            
Running unit tests for scipy.linalg
NumPy version 1.7.2
NumPy is installed in C:\Python34\lib\site-packages\numpy
SciPy version 0.17.0.dev0+Unknown
SciPy is installed in C:\Python34\lib\site-packages\scipy
Python version 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:24:06) [MSC v.1600 32 bit (Intel)]
...
<... all seems well for a while...>
...
test_vrectangular_complex (test_decomp.TestLUSingle) ... ok
test_check_finite (test_decomp.TestLUSolve) ... ok
test_lu (test_decomp.TestLUSolve) ... ok
test_cef (test_decomp.TestOrdQZ) ... wine: Unhandled page fault on read access to 0xffffffff at address 0x6d47e9c5 (thread 0009), starting debugger...
Unhandled exception: page fault on read access to 0xffffffff in 32-bit code (0x6d47e9c5).
Register dump:
 CS:0073 SS:007b DS:007b ES:007b FS:0033 GS:003b
 EIP:6d47e9c5 ESP:0042c924 EBP:00000001 EFLAGS:00010202(  R- --  I   - - - )
 EAX:0042d094 EBX:0042d094 ECX:00000001 EDX:00000040
 ESI:0042d074 EDI:00000006
Stack dump:
0x0042c924:  00000006 00000040 0042d094 00000010
0x0042c934:  0042d094 03996fd0 00000008 6d47f21f
0x0042c944:  0042d074 03996fc8 00000002 00000003
0x0042c954:  00000001 00000002 0042d0b4 00000003
0x0042c964:  00000003 6d47f100 0042d074 6d428cb1
0x0042c974:  00000001 00000003 00000000 3ff00000
Backtrace:
=>0 0x6d47e9c5 in _flapack.pyd (+0x3be9c5) (0x00000001)
0x6d47e9c5: 	
Modules:
Module	Address			Debug info	Name (121 modules)
PE	  440000-  450000	Deferred        _distance_wrap.pyd
PE	  470000-  47e000	Deferred        _socket.pyd
PE	 9460000- 9484000	Deferred        _lzma.pyd
PE	 9560000- 9840000	Deferred        _fblas.pyd
PE	 9840000- 9a2b000	Deferred        _flinalg.pyd
PE	 9a30000- 9d61000	Deferred        cython_blas.pyd
PE	 9f30000- 9ff4000	Deferred        _hashlib.pyd
PE	 a000000- a12a000	Deferred        _ssl.pyd
PE	 a1f0000- a457000	Deferred        _superlu.pyd
PE	 a4a0000- a83f000	Deferred        _arpack.pyd
PE	 a840000- a92b000	Deferred        _odepack.pyd
PE	 a970000- aa5d000	Deferred        lsoda.pyd
PE	10000000-10015000	Deferred        python3
PE	1d000000-1d00b000	Deferred        pythonw
PE	1d170000-1d180000	Deferred        _bz2.pyd
PE	1d1a0000-1d1b8000	Deferred        _ctypes.pyd
PE	1e000000-1e2a6000	Deferred        python34
PE	61b80000-61bb8000	Deferred        _hierarchy.pyd
PE	62380000-623b2000	Deferred        _dop.pyd
PE	62980000-62b21000	Deferred        vode.pyd
PE	62e00000-62e24000	Deferred        _traversal.pyd
PE	62f40000-62f82000	Deferred        _ellip_harm_2.pyd
PE	63700000-640b3000	Deferred        cython_lapack.pyd
PE	645c0000-645e1000	Deferred        _tools.pyd
PE	64780000-647b9000	Deferred        _shortest_path.pyd
PE	647c0000-64a41000	Deferred        _ufuncs.pyd
PE	64d80000-64dcf000	Deferred        _decomp_update.pyd
PE	64e00000-64f0a000	Deferred        multiarray.pyd
PE	65240000-6567f000	Deferred        _sparsetools.pyd
PE	65980000-65a78000	Deferred        _vq.pyd
PE	66000000-660cb000	Deferred        ckdtree.pyd
PE	67380000-673c6000	Deferred        _quadpack.pyd
PE	676c0000-676d8000	Deferred        _ufuncs_cxx.pyd
PE	67ac0000-67bdc000	Deferred        lapack_lite.pyd
PE	68b40000-68b64000	Deferred        scalarmath.pyd
PE	68bc0000-68d29000	Deferred        specfun.pyd
PE	69000000-69143000	Deferred        qhull.pyd
PE	69300000-6930e000	Deferred        fftpack_lite.pyd
PE	6af00000-6af2d000	Deferred        _solve_toeplitz.pyd
PE	6c3c0000-6c3cb000	Deferred        _compiled_base.pyd
PE	6c640000-6c6a3000	Deferred        _csparsetools.pyd
PE	6c9c0000-6c9ff000	Deferred        _reordering.pyd
PE	6d0c0000-6d826000	Stabs           _flapack.pyd
PE	6dec0000-6df12000	Deferred        umath.pyd
PE	6f140000-6f22a000	Deferred        _iterative.pyd
PE	6fb40000-6fbb9000	Deferred        mtrand.pyd
PE	710c0000-710e3000	Deferred        _min_spanning_tree.pyd
PE	78aa0000-78b5f000	Deferred        msvcr100
ELF	7b800000-7ba15000	Deferred        kernel32<elf>
  \-PE	7b810000-7ba15000	\               kernel32
ELF	7bc00000-7bcc3000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bcc3000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
ELF	7df8d000-7dfab000	Deferred        libgcc_s.so.1
ELF	7dfb3000-7dfe5000	Deferred        ws2_32<elf>
  \-PE	7dfc0000-7dfe5000	\               ws2_32
ELF	7dfe5000-7e0d7000	Deferred        oleaut32<elf>
  \-PE	7e000000-7e0d7000	\               oleaut32
ELF	7e0d7000-7e164000	Deferred        msvcrt<elf>
  \-PE	7e0f0000-7e164000	\               msvcrt
ELF	7e164000-7e21c000	Deferred        crypt32<elf>
  \-PE	7e170000-7e21c000	\               crypt32
ELF	7e21c000-7e25a000	Deferred        rsaenh<elf>
  \-PE	7e220000-7e25a000	\               rsaenh
ELF	7e25a000-7e2cf000	Deferred        rpcrt4<elf>
  \-PE	7e270000-7e2cf000	\               rpcrt4
ELF	7e2cf000-7e3d7000	Deferred        ole32<elf>
  \-PE	7e2f0000-7e3d7000	\               ole32
ELF	7e405000-7e439000	Deferred        uxtheme<elf>
  \-PE	7e410000-7e439000	\               uxtheme
ELF	7e439000-7e43f000	Deferred        libxfixes.so.3
ELF	7e43f000-7e44a000	Deferred        libxcursor.so.1
ELF	7e452000-7e47c000	Deferred        libexpat.so.1
ELF	7e47c000-7e4b0000	Deferred        libfontconfig.so.1
ELF	7e4b0000-7e4c1000	Deferred        libxi.so.6
ELF	7e4c1000-7e4c5000	Deferred        libxcomposite.so.1
ELF	7e4c5000-7e4ce000	Deferred        libxrandr.so.2
ELF	7e4ce000-7e4d8000	Deferred        libxrender.so.1
ELF	7e4d8000-7e4de000	Deferred        libxxf86vm.so.1
ELF	7e4de000-7e4e2000	Deferred        libxinerama.so.1
ELF	7e4e2000-7e504000	Deferred        imm32<elf>
  \-PE	7e4f0000-7e504000	\               imm32
ELF	7e504000-7e50b000	Deferred        libxdmcp.so.6
ELF	7e50b000-7e50f000	Deferred        libxau.so.6
ELF	7e50f000-7e530000	Deferred        libxcb.so.1
ELF	7e530000-7e54a000	Deferred        libice.so.6
ELF	7e54a000-7e67e000	Deferred        libx11.so.6
ELF	7e67e000-7e690000	Deferred        libxext.so.6
ELF	7e690000-7e699000	Deferred        libsm.so.6
ELF	7e699000-7e72c000	Deferred        winex11<elf>
  \-PE	7e6a0000-7e72c000	\               winex11
ELF	7e72c000-7e742000	Deferred        libz.so.1
ELF	7e742000-7e7dd000	Deferred        libfreetype.so.6
ELF	7e7dd000-7e7fc000	Deferred        libtinfo.so.5
ELF	7e7fc000-7e81e000	Deferred        libncurses.so.5
ELF	7e81e000-7e916000	Deferred        comctl32<elf>
  \-PE	7e830000-7e916000	\               comctl32
ELF	7e916000-7e980000	Deferred        shlwapi<elf>
  \-PE	7e920000-7e980000	\               shlwapi
ELF	7e980000-7eb91000	Deferred        shell32<elf>
  \-PE	7e990000-7eb91000	\               shell32
ELF	7eb91000-7ebaa000	Deferred        version<elf>
  \-PE	7eba0000-7ebaa000	\               version
ELF	7ebaa000-7ec0a000	Deferred        advapi32<elf>
  \-PE	7ebc0000-7ec0a000	\               advapi32
ELF	7ec0a000-7ecc7000	Deferred        gdi32<elf>
  \-PE	7ec20000-7ecc7000	\               gdi32
ELF	7ecc7000-7ee07000	Deferred        user32<elf>
  \-PE	7ece0000-7ee07000	\               user32
ELF	7ef90000-7ef9d000	Deferred        libnss_files.so.2
ELF	7ef9d000-7efa9000	Deferred        libnss_nis.so.2
ELF	7efa9000-7efc3000	Deferred        libnsl.so.1
ELF	7efc3000-7efcc000	Deferred        libnss_compat.so.2
ELF	7efcc000-7eff8000	Deferred        libm.so.6
ELF	7effa000-7f000000	Deferred        libuuid.so.1
ELF	b73d1000-b73d6000	Deferred        libdl.so.2
ELF	b73d6000-b757f000	Deferred        libc.so.6
ELF	b7580000-b759b000	Deferred        libpthread.so.0
ELF	b75a3000-b76e5000	Dwarf           libwine.so.1
ELF	b76e7000-b7709000	Deferred        ld-linux.so.2
ELF	b7709000-b770a000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) C:\Python34\pythonw.exe
	00000009    0 <==
0000000e services.exe
	00000020    0
	0000001f    0
	00000015    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001d    0
	0000001a    0
	00000014    0
	00000013    0
0000001b plugplay.exe
	00000021    0
	0000001e    0
	0000001c    0
00000022 explorer.exe
	00000023    0
```

**Comment by ev-br** [comment] 2015-12-04 11:01
Superpack binaries, SSE3 autodetected.
As a datapoint, same build for python 2.7 and 3.3 does not show this.

**Comment by rgommers** [comment] 2015-12-08 00:59
Grrr. I tested on 2.7 and 3.3. This really shouldn't depend on Python version.

**Comment by ev-br** [comment] 2015-12-08 07:28
Segfaults are in `test_decomp.py`, class `TestOrdQZ`, functions `test_lhp`, `test_iuc`, `test_ref` and `test_cef`. If I `skipif` these, the rest passes. Specifically, it seems that `mode="rhp"` is OK, but others aren't. Any chance this rings some bell @jseabold ?

**Comment by ev-br** [comment] 2015-12-08 07:35
A cool thing would be to use new Cython wrappers for `gges` and `tgsen` instead of f2py and see if this makes any difference.

A short-term option seems to be to skip the failing tests, document that modes other than `rhp` may or may not work and gather some real-world usage :-).

**Comment by jseabold** [comment] 2015-12-08 12:56
Not anymore than what we went through before. I don't have the ability to
debug this and it's still a bit of a mystery to me.

On Tue, Dec 8, 2015, 1:28 AM Evgeni Burovski <notifications@github.com>
wrote:

> Segfaults are in test_decomp.py, class TestOrdQZ, functions test_lhp,
> test_iuc, test_ref and test_cef. If I skipif these, the rest passes.
> Specifically, it seems that mode="rhp" is OK, but others aren't. Any
> chance this rings some bell @jseabold <https://github.com/jseabold> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/issues/5577#issuecomment-162799851>.
>
-- 

Sent from my mobile

**Comment by pv** [comment] 2015-12-08 18:29
I don't get this crash (at scipy commit db14b78e711): https://gist.github.com/pv/b9726c7f238dce8b0697
numpy/scipy built under wine 1.6.2 with numpy-vendor sse3 atlas.

**Comment by rgommers** [comment] 2015-12-08 22:21
@pv thanks, that helps. Did you also build the 0.15.x binaries with wine 1.6.2? numpy-vendor now installs 1.4. That's kind of important to document (and upgrade apparently).

**Comment by rgommers** [comment] 2015-12-08 22:39
And do you remember how you installed wine 1.6.2?

**Comment by pv** [comment] 2015-12-08 23:19
Yes, built both numpy+scipy with wine 1.6.2 (from ubuntu 15.10 repositories); mingw, atlas and pythons were from numpy-vendor. Of course, out of bound access etc. doesn't always crash, so this data point doesn't necessarily mean much...

**Comment by rgommers** [comment] 2015-12-08 23:25
Thanks. For 0.15.x I meant, on what config did you build the official installers that are on SF now?

**Comment by rgommers** [comment] 2015-12-08 23:25
I just started up my very old OS X box to check the wine version: scipy releases up to 0.14.0 and numpy up to 1.6.2 were built with wine 1.1.39.

**Comment by pv** [comment] 2015-12-08 23:42
IIRC, the 0.15.x installers were built on a windows 7 VM plus latest mingw at that time, numpy-vendor atlas, and numpy installer from SF. It would be fairly dismaying if the wine vs. windows vs. wine version is what matters here.

**Comment by ev-br** [comment] 2015-12-11 21:12
OK, under wine 1.6.1, scipy commit 5b2d599, SSE3 build on python 3.4, I still see the crash if I run `nosetests` and there is no crash if I do `>>> linalg.test("full")` from the interactive interpreter.

**Comment by ev-br** [comment] 2015-12-12 20:50
Here's progress report (or rather a report of the lack thereof). On wine 1.6.1 (the best I managed to install in the ubuntu precise box), using python 3.4 I get results consistent with what Pauli got above: no crash from running tests in REPL. But under python 3.3, ordqz does crash.
Also, under wine 1.6.1, I do not get the crash in `scipy.io.matlab` which happens for the stock wine.

Moreover, using wine 1.6.1 completely messes up python 2.7 --- there are lots of `fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x81b6 ignored` and trying to even build numpy fails with a "broken toolchain" message, https://gist.github.com/ev-br/3af5f1fe708893c1db96.
Googling around seems to point to bug in Wine which was supposed to be fixed in 1.5.something, but here we are (https://bugs.winehq.org/show_bug.cgi?id=33337).

Trying to upgrade to wine 1.7 does not help either: wine 1.7.18 does not play well with python 3.3 either.

I even tried to upgrade the VM to Ubuntu 15.10, but that does not seem to work with the 12.04 host. 

Thoughts?

**Comment by ev-br** [comment] 2015-12-13 13:23
Apparently, there's a LAPACK bug in `tgsen` fixed in the LAPACK 3.2 timeframe:
http://icl.cs.utk.edu/lapack-forum/archives/lapack/msg00613.html
AFAICS, numpy-vendor binaries use lapack-lite 3.1.1...

**Comment by pv** [comment] 2015-12-13 13:56
Lapack bugs are one possible suspect, but I'm not sure if it's that one (Q matrix seems always passed in). It might also be useful to check if lwork etc array sizes are the same as on linux, with a newer lapack.

**Comment by ev-br** [comment] 2015-12-13 15:23
And indeed, simply bundling tgsen sources from lapack 3.6.0 (https://github.com/scipy/scipy/compare/master...ev-br:tgsen?expand=1) does not fix it.

**Comment by pv** [comment] 2015-12-21 15:16
For triaging, best would be to try build on a Windows machine / VM, to eliminate wine issues. If that works, the issue is due to wine rather than the toolchain itself. If it does not work, it's a mingw issue.

I remember that for 0.15.x I did not get things working on wine, and gave up trying.

**Comment by ev-br** [comment] 2015-12-21 20:15
Yup, that would be helpful. My only problem with it is that I no longer have a Windows license. (And my only Win machine is XP and that is just too old to be useful, no Python 3 for one).

**Comment by rgommers** [comment] 2015-12-23 06:11
For the record, my ancient Wine 1.1.39 setup also crashes on this one.

**Comment by ev-br** [comment] 2015-12-24 09:09
https://github.com/scipy/scipy/pull/5625#issuecomment-167060174

It seems that this problem can be written off as a wine glitch.

**Comment by rgommers** [comment] 2015-12-29 10:01
OK, let's label this as wontfix then and close it. If this happens for any other compiler/OS combinations, the issue can be reopened.

**Closed by rgommers** 2015-12-29 10:01 UTC
Labels: defect, scipy.linalg
