### ISSUE TITLE
BUG: signal.decimate returns unexpected values with float32 arrays

### ISSUE THREAD

**Issue by varjak** [scipy/scipy#15393] opened 2022-01-10 23:31 UTC
### Describe your issue.

This may be a duplicate of gh-15072, but 1) I don't have a big array (50 values), and 2) this method did not return any NaN's, just unexpected large (negative or positive) values.

I finally caught the issue when I realized I had switched from scipy==1.4.1 to scipy==1.7.3 (before, it was working)

I'm attaching two plots made with the same code example, but each with a different scipy version. In the 1.4.1 one, the decimate result is correct and independent of the type of array, and in the 1.7.3, it's wrong for the float32 array:

![scipy1](https://user-images.githubusercontent.com/33642154/148854466-45337928-ee14-4f75-a977-21e32278a9f5.png)
![scipy2](https://user-images.githubusercontent.com/33642154/148854486-6cd0f9bf-de69-427a-ba98-add71b779041.png)

### Reproducing Code Example

```python
import scipy.signal as ssi
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(1)
n = 50
p = np.random.rand(n)
q = 20
p_d1 = ssi.decimate(np.asarray(p, dtype='float32'), q)
p_d2 = ssi.decimate(np.asarray(p, dtype='float64'), q)
print('max p_d1 (float32): ', max(p_d1))  # scipy==1.4.1: 0.526 / scipy==1.7.3: 5279  <- wrong
print('max p_d2 (float64): ', max(p_d2))  # scipy==1.4.1: 0.526 / scipy==1.7.3: 0.526

# Optionally plot
t = list(range(n))
t_d = [t[i * q] for i in range(len(p_d1))]
plt.plot(t, p, marker='o')
plt.plot(t_d, p_d1, marker='s')
plt.plot(t_d, p_d2, marker='x')
plt.legend(['float32', 'float32 > decimated', 'float64 > decimated'], loc='upper right')
plt.title('scipy==1.4.1')  # scipy==1.4.1 / scipy==1.7.3 (latest to date)
plt.show()
```

### Error message

```shell
None!!
```

### SciPy/NumPy/Python version information

No issue with scipy==1.4.1; Issue with scipy==1.7.3

**Comment by pkaf** [comment] 2022-01-12 09:48
I did a quick debugging and was able to track the source of the issue as far as _signal.filtfilt_  function. 

```python
from scipy import signal 

def decimate(p, q, dtype, n=None, ftype='iir', axis=-1, zero_phase=True):
    if dtype==32:
        x = np.asarray(p, dtype='float32')
    elif dtype==64:
        x = np.asarray(p, dtype='float64')
                
    x = np.asarray(x)
    q = operator.index(q)

    if n is not None:
        n = operator.index(n)

    if n is None:
        n = 8
    system = signal.dlti(*cheby1(n, 0.05, 0.8 / q))
    b, a = system.num, system.den

    result_type = x.dtype
    if result_type.kind in 'bui':
        result_type = np.float64
        
    b = np.asarray(b, dtype=result_type)
    a = np.asarray(a, dtype=result_type)

    sl = [slice(None)] * x.ndim
    a = np.asarray(a)

    y = signal.filtfilt(b, a, x, axis=axis)
    sl[axis] = slice(None, None, q)

    return a, b, x

np.random.seed(1)

n = 50
p = np.random.rand(n)
q = 20

a32, b32, x32 = decimate(p, q, 32)
a64, b64, x64 = decimate(p, q, 64)

def sig_fil(b, a, x, axis=-1):
    """a, b are something that is computed inside decimate function"""
    y = signal.filtfilt(b, a, x)
    sl = [slice(None)] * x.ndim
    sl[axis] = slice(None, None, q)
    return y[tuple(sl)]

print('bug:', sig_fil(b64, a64, x64), sig_fil(b32, a32, x32))

# Result with a64 vs instead of a32 gives ~identical result
print('gone bug:', sig_fil(b64, a64, x64), sig_fil(b32, a64, x32))
```

![Uploading Screen Shot 2022-01-12 at 8.47.05 pm.png…]()

**Comment by pkaf** [comment] 2022-01-14 22:38
I think this issue can be closed as it is not the bug due to scipy but numpy instead. Also, if one provides less precise input they get less precise output. It is not even a bug in a first place, it is the way it is no?

**Comment by varjak** [comment] 2022-01-14 23:58
Thanks for looking into it. I don't think that decimals stored in float32 should be downsampled to values x10000 larger. So I think the algorithm is at fault here, and although converting the inputs to float64 to reconvert them back at the end might work, it may not be a good solution. In scipy v. 1.4.1 it appears to work, so could we not use the same algorithm?

**Comment by roryyorke** [comment] 2022-01-22 04:49
I think this is related to #13529 - we need to switch to second-order sections, see stalled #14371.

Here's a not-heavily-tested `sos_decimate` that tends to create very high order filters.  It handles this test OK, though not brilliantly (I think at least partly due to "boundary-condition" issues combined with the high order filters; maybe having #11205 would help?).

I'm not sure about using `padlen=0`, but it's needed for this short input and, again, the high-order filters.

```python
def sos_dist_gain(sos):
    # distribute gain by scale factors of 2
    sos = sos.copy()

    # idea is to make gain of each section approximately equal
    # express gain as k * 2 ** m
    k, m = np.frexp(sos[0][0])
    d, q = divmod(m, sos.shape[0])
    sos[0][:3] *= 2.0 ** (-m + d + q)
    for i in range(1, sos.shape[0]):
        sos[i][:3] *= 2.0 ** d
    return sos


def sos_decimate(x, n, ftype='butter'):
    x = np.asarray(x)
    sos = signal.iirdesign(0.9/n, 1/n, 1.5, 20,
                           ftype=ftype, output='sos')

    # make DC gain 1
    sos[0][:3] /= signal.sosfreqz(sos, [0])[1][0].real

    # distribute gains to avoid underflow of coeffs in
    # single precision
    sos = sos_dist_gain(sos)

    if x.dtype in [np.float32, np.complex128]:
        sos = sos.astype(np.float32)

    return signal.sosfiltfilt(sos, x, padlen=0)[::n]
```

Here's an n=50 result (reproducing the above), then an n=500 result, which shows the boundary-condition effects:

![sosdec-n50](https://user-images.githubusercontent.com/110974/150625025-f1417118-8f79-475a-b9e1-298ada7ff203.png)

![sosdec-n500](https://user-images.githubusercontent.com/110974/150625033-fb6b85d5-d8d1-420f-bfdb-0165b1217983.png)

**Closed** 2022-11-20 19:56 UTC
Labels: defect
