### ISSUE TITLE
BUG: Wrong attributes when multiplying sparse array with dense vector

### ISSUE THREAD

**Issue by nirryde** [scipy/scipy#19477] opened 2023-11-06 08:45 UTC
### Describe your issue.

Hi,

I found an un-expected behavior when elementwise multiplying a sparse array or matrix with a dense vector which has some zero elements. When using the .row & .col attributes on the result of the multiplication we get the nonzero indices of the array prior to the multiplication. However, when using the .nonzero() method on the result of the multiplication we get the correct indices for the nonzero elements. 

This issue doesn't seem to occur when the dense vector has no zero elements. 
See toy example. 

### Reproducing Code Example

```python
import numpy as np 
import scipy.sparse as ssr

v = np.array([0,1,0,1])
m = np.array([[0,5,0,0], [5,0,0,3], [0,0,0,0]])
m_sparse = ssr.csr_array(m)

# Multiply (elementwise) each row of m with v. 
# In scipy notation terms, the nonzero indices of resulting multiplication should be: ( [0,1], [1,3] ). 
# When using the nonzero method to extract the nonzero positions we get the nonzero indices of m_sparse (i.e. before multiplying by v).

# With .multiply() (The issue doen't occur if v does not have any zeros):
(m_sparse.multiply(v)).row # output: [0,1,1]
(m_sparse.multiply(v)).col # output: [1,0,3]
(m_sparse.multiply(v)).nonzero() # output: ([0,1], [1,3])

# A different approach that doesn't cause a problem:
(m_sparse @ ssr.diags(v, offsets=0, format='csr')).tocoo().row # output: [0,1]
(m_sparse @ ssr.diags(v, offsets=0, format='csr')).tocoo().col # output: [1,3]
(m_sparse @ ssr.diags(v, offsets=0, format='csr')).nonzero() # output: ([0,1], [1,3])
```

### Error message

```shell
not applicable
```

### SciPy/NumPy/Python version and system information

```shell
print(scipy.__version__, numpy.__version__, sys.version_info)

1.10.1 1.25.0 sys.version_info(major=3, minor=9, releaselevel='final', serial=0)

scipy.show_config()

{
	"Compiliers": {
		"c": {
			"name": "gcc",
			"linker": "ld.bfd",
			"version": "10.2.1"
			"commands": "cc"
		},
		"cython": {
			"name": "cython",
			"linker": "cython",
			"version": "0.29.33",
			"commands": "cython"
		},
		"c++": {
			"name": "gcc",
			"linker": "ld.bfd",
			"version": "10.2.1",
			"commands": "c++"
		},
		"fortran": {
			"name": "gcc",
			"linker": "ld.bfd",
			"version": "10.2.1",
			"commands": "gfortran"
		},
		"pythran": {
			"version": "0.12.1",
			"include directory": "/tmp/pip-build-env-yjjniym9/overlay/lib/python3.9/site-packages/pythran"
		}
	},
	"Machine Information": {
		"host": {
			"cpu": "x86_64",
			"family": "x86_64",
			"endian": "little",
			"system": "linux"
		},
		"build": {
			"cpu": "x86_64",
			"family": "x86_64",
			"endian": "little",
			"system": "linux"
		},
		"cross-compiled": false
	},
	"Build Dependencies": {
		"blas": {
			"name": "OpenBLAS",
			"found": true,
			"version": "0.3.18",
			"detection method": "cmake",
			"include directory": "unknown",
			"lib directory": "unknown",
			"openblas configuration": "unknown",
			"pc file directory": "unknown"
		},
		"lapack": {
			"name": "OpenBLAS",
			"found": true,
			"version": "0.3.18",
			"detection method": "cmake",
			"include directory": "unknown",
			"lib directory": "unknown",
			"openblas configuration": "unknown",
			"pc file directory": "unknown"
		}
	},
	"Python Information": {
		"path": "/opt/python/cp39-cp39/bin/python",
		"version": "3.9"
	}
}
```

**Comment by SebastianMunozMora** [comment] 2023-11-11 13:54
Hi!,  I am trying to reproduce this issue and I get this error, why do we have inconsistent shapes? does this happen in your environment?, thanks
![image](https://github.com/scipy/scipy/assets/13369072/e49bbd34-4ba3-4918-9372-a8d9bf875562)

**Comment by dschult** [comment] 2023-11-12 03:17
This looks like a mix-up in the reporting of the error between using `csr_array` in the example, but using `csr_matrix` in the code that actually produced the results.  The Issue shows `csr_array` to create `m_sparse`, but the code that "doesn't cause a problem" seems to use `csr_matrix`. (I guess it is possible that it uses `@` instead of `*`... but `*` with `csr_array` creates the `ValueError` reported by @SebastianMunozMora )

Can you verify this @nirryde ?

**Further investigation** (assuming using `csr_matrix` to cause the error with `row` and `col`):
`m_sparse.multiply(v)` results in a `coo_matrix` with some of its "nonzero" values being `0`.
Look at `m_sparse.multiply(v).data` -> `array([5, 0, 3])`.

To remove those zero values, you need the extra step of eliminating the zeros. In your case:
`m_sparse.multiply(v).eliminate_zeros()`

Note that this means `m_sparse.row` shows the rows for the **stored values**, not for the **nonzero values**.  Perhaps this could be improved in the docs.

The choice not to remove zero values when doing element-wise multiplication is to avoid the extra computation. Note that any manipulations of the matrix are still numerically correct when zero values are stored in the matrix. The question is whether it is worth the time to remove them.

**Comment by nirryde** [comment] 2023-11-12 09:20
@dschult My bad, the * in the code that works was supposed to be a @ (I edited the post).
If I understand correctly the .row and .col properties should return the nonzero indices of the sparse COO array i.e they should coincide with the output of the .nonzero() method.  Otherwise this seems inconsistent with the .row and .col properties representing the 'ij' part in the 'ijv' triplet.

**Comment by dschult** [comment] 2023-11-12 15:48
The .row and .col properties represent the indices of the sparse COO array, but if the COO array stores some zeros, those values get rows and columns too. The attributes .row and .col only match .nonzero() **only if there aren't any zeros stored explicitly in the coo_array**.

```python
import scipy as sp;import numpy as np
A = np.arange(6).reshape(2,3)
Asp = sp.sparse.csr_array(A)
print(Asp.data)  # -> array([1 2 3 4 5])
# Add a zero value to the array
Asp[1, 0] = 0
print(Asp.data)  # -> array([1 2 0 4 5])

# switch to coo format
Acoo=Asp.tocoo(copy=False)
print("row: ", Acoo.row)     # -> array([0 0 1 1 1])
print("col: ", Acoo.col)     # -> array([1 2 0 1 2])
print("data:", Acoo.data)    # -> array([1 2 0 4 5])
print("nonzero: ", Acoo.nonzero())  # -> (array([0, 0, 1, 1], dtype=int32), array([1, 2, 1, 2], dtype=int32))

# eliminate zeros   This produces what you were expecting
Acoo.eliminate_zeros()
print("row: ", Acoo.row)     # -> array([0 0 1 1])
print("col: ", Acoo.col)     # -> array([1 2 1 2])
print("data:", Acoo.data)    # -> array([1 2 4 5])
```

This doesn't violate the idea that row and col represent the 'ij' in the 'ijv' triplet precisely when the 'v' in 'ijv' is zero.

**Comment by nirryde** [comment] 2023-11-12 18:49
@dschult I see... I feel like the documentation does not clarify the fact that an operation (like the multiplication I did) can end up with a sparse matrix with zero elements. In other words, I expect that computations which return a sparse array will never have zero elements. Are there any use cases where we would want to explicitly store zero values?

**Comment by dschult** [comment] 2023-11-14 19:56
When you do a multiplication like you did, then any elements that multiply a default value (0) in the other array will result in the value zero.  It can be expensive to update all those zeros if all you want to do with that result is e.g. sum the columns. Rather than copying or reallocating the behind-the-scenes arrays in the sparse matrix, you can just store a value that is zero. It won't affect the sum's result and it will be faster and avoid another allocation of memory to hold intermediate results. 

If you do want to eliminate any zero entries explicitly stored, the `eliminate_zeros()` method is available and you should use it before any operations that would be expensive or confusing if they report locations where the value is zero. The main difficulty as I see it is when people don't know that the values can be zero -- that you should use `nonzero()` if you want to know that. I think documentation is the place where that can be fixed.

I suppose you could eliminate zeros after every operation, but as you might expect, that gets cumbersome in the code -- and would also slow down your computation of most complicated expressions. It really is better this way most of the time.

**Comment by dschult** [comment] 2024-08-30 14:25
If this hasn't been addressed sufficiently, or if there are more comments/questions add them here and we will reopen this issue. If has been quiet for a while so I'm closing.

**Closed by dschult** 2024-08-30 14:25 UTC
Labels: defect, scipy.sparse
