### ISSUE TITLE
LOBPCG convergence failure if guess provided

### ISSUE THREAD

**Issue by mfherbst** [scipy/scipy#10258] opened 2019-06-04 18:34 UTC
When using the lobpcg implementation in `scipy.sparse.linalg` with scipy version `1.3.0` on a preconditioned, normal eigenproblem, the algorithm aborts with the error message shown below if a particular guess is employed. This is surprising, because the guess is derived from an approximate physical model and a single Rayleigh-Ritz step in the subspace spanned by the guess vectors already provides a very good approximation to the desired eigenvalues.

### Reproducing code example:
Can be found in [mfherbst/issue_scipy_lobpcg_guess](https://github.com/mfherbst/issue_scipy_lobpcg_guess). For running the code the datafile is required. On execution the following output is produced on my machine:
```
scipy version:  1.3.0
Problem properties:
N:                  411
m:                  10
λref:               [0.21587252 0.7147382  0.72196884 0.72214299 0.72648404 0.73109012
 0.73639964 0.80308925 0.8303687  0.91917443]
λapprox:            [0.286794   0.75381381 0.75949557 0.76511668 0.76580448 0.77711184
 0.78372357 0.86710816 0.95792697 0.96882807]
A λ dist:           0.011713478159563806
P*A ritz dist:      0.046591195439390276

read_guess=True
ERROR:  9-th leading minor of the array is not positive definite

read_guess=False
```

As can be deduced from the depicted output, the first execution, which employs the guess, fails, whereas the second (employing a random guess) succeeds. `λref` are the eigenvalues on the full matrix from LAPACK, `λapprox` the Ritz values inside the subspace spanned by the guesses, `λ dist` and `ritz dist` are the absolute differences between the last eigenvalue / Ritz value of interest and the next value.

### Error message:
```
Traceback (most recent call last):
  File "./test_lobpcg.py", line 47, in <module>
    test_lobpcg(read_guess=True)
  File "./test_lobpcg.py", line 39, in test_lobpcg
    λ, v = lobpcg(A, X, largest=False, M=P, maxiter=100, tol=tol)
  File "/home/mfh/.julia/python_virtualenv/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py", line 476, in lobpcg
    aux = _b_orthonormalize(B, activeBlockVectorP, retInvR=True)
  File "/home/mfh/.julia/python_virtualenv/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py", line 93, in _b_orthonormalize
    gramVBV = cholesky(gramVBV)
  File "/home/mfh/.julia/python_virtualenv/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "/home/mfh/.julia/python_virtualenv/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.LinAlgError: 9-th leading minor of the array is not positive definite
```

### Scipy/Numpy/Python version information:
```
1.3.0 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by tylerjereddy** [comment] 2019-06-05 01:36
cc @lobpcg

**Comment by lobpcg** [comment] 2019-06-05 03:57
@mfherbst thanks for your nice simple reproducible example! Add verbosityLevel=2 to lobpcg options in the future for your debugging to see more details. 

@rc FYI

With preconditioning and x0, it gives
 ```
iteration 0
current block size: 10
eigenvalue: [0.286794   0.75381721 0.75949588 0.76511675 0.76625736 0.77712279
 0.78387262 0.86711427 0.95792864 0.96884708]
residual norms: [0.21871746 0.18159479 0.17757457 0.18323204 0.20840115 0.21126438
 0.21383723 0.16758579 0.20865024 0.21009511]
iteration 1
current block size: 10
eigenvalue: [0.21737361 0.71846981 0.72258067 0.72601845 0.73037188 0.73170199
 0.73700257 0.8174339  0.8741871  0.92022889]
residual norms: [0.06431672 0.05507051 0.03591181 0.0537821  0.0539346  0.03612681
 0.03617779 0.11242973 0.26292488 0.05608491]
matrix gramA is not sufficiently Hermitian for a=3, b=-1:
condition: 7e-09 < 1.136868e-13
ERROR:  the leading minor of order 24 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.
```
while it works fine without the preconidtioner and/or with the random initial guess. Both the matrix and the preconditioner appear to be reasonably symmetric and even positive definite. And this specific x0 looks OK.

What may be happening here is that x0 contains good approximations to eigenvectors but not in the right order. The first iteration RR puts them in the right order, swapping some columns. E.g., if there are two columns, we get x0 = [b a], but x1 = [a b], so our P which is basically the difference x1-x0 becomes [b-a a-b], i.e., artificially rank-deficient. Of course, the vectors a and b are not exactly the same in x0 and x1, but close. This might happen in the middle of iterations, too, if there are (nearly) multiple eigenvalues, so the corresponding approximate eigenvectors can get easily swapped by RR. 

@mfherbst    - this may also be an explanation for the instability you have found in the Julia code of LOBPCG in https://github.com/JuliaMath/IterativeSolvers.jl/issues/246#issuecomment-498636618

**Comment by antoine-levitt** [comment] 2019-06-05 05:11
This generalizes to a nice observation : subtracting the bases of two subspaces is in general a bad idea, because of orthogonal invariance, even in exact arithmetic. One could perform subspace alignment to get the "right" difference. Remains to be seen if it improves things, how costly that is, and if it can possibly be merged with other operations to avoid extra computation.

**Comment by antoine-levitt** [comment] 2019-06-05 05:57
Hm, I tried the subspace alignment in the hope it might improve the convergence by having better Ps, but it seems not to do nothing (neglecting numerical errors), I'll have to think about that. Code (in julia, no locking, orthogonalizations by QR factorizations to remove all the numerical problems) here: https://gist.github.com/antoine-levitt/f8ac3637c5d5d778a448780172e63e28

**Comment by mfherbst** [comment] 2019-06-05 07:38
> @mfherbst - this may also be an explanation for the instability you have found in the Julia code of LOBPCG in JuliaMath/IterativeSolvers.jl#246 (comment)

I added a julia-Script to the repository. As it turns out, julia's lobpcg also fails, but it fails in fact for both cases (with and without guess).

**Comment by mfherbst** [comment] 2019-06-05 08:00
@antoine-levitt Added some comments about the naive QR-based julia implementaion in  JuliaMath/IterativeSolvers.jl#246.

**Comment by ilayn** [comment] 2019-06-05 08:16
I don't know what is happening in terms of the algorithm logic but if this is an important step common enough then probably it is better to use the proper LAPACK tools such as ?potrf and ?potri to get the necessary data. Especially this part 

```python
def _b_orthonormalize(B, blockVectorV, blockVectorBV=None, retInvR=False):
    if blockVectorBV is None:
        blockVectorBV = blockVectorV if B is None else B(blockVectorV)


    gramVBV = blockVectorV.T.conj() @ blockVectorBV
    # Here cho_factor can be used instead 
    gramVBV = cholesky(gramVBV)
    # See below
    gramVBV = inv(gramVBV, overwrite_a=True)
    
    # This is a cholesky solve step no inverse needed, hence extra numerical noise cost
    blockVectorV = blockVectorV @ gramVBV

    if B is not None:
        # This is also a cholesky solve step no inverse needed
        blockVectorBV = blockVectorBV @  gramVBV
    else:
        blockVectorBV = None

    if retInvR:
        # Inverse can be computed via ?potri, this is numerically less stable
        return blockVectorV, blockVectorBV, gramVBV
    else:
        return blockVectorV, blockVectorBV
```    
in the inverse part I am assuming the inverse of the grammian and not its cholesky factor but anyways the important part is the solving step.

**Comment by antoine-levitt** [comment] 2019-06-05 08:18
That's a good point, the inverse should definitely not be used here. However it will not fully resolve the main issue, which is that cholesky factorization of an overlap matrix might fail when the basis is almost linearly dependent.

**Comment by ilayn** [comment] 2019-06-05 08:28
If they are just basis vectors on the previous step then they need to be projected onto the nullspace of the other. 

If I read the code correctly when `B is None` then it is a problem of the basis `blockvectorV` (almost) not being a full basis which is not fixable at this part of the code.

**Comment by lobpcg** [comment] 2019-06-05 12:53
Late-night theories like mine, https://github.com/scipy/scipy/issues/10258#issuecomment-498929598, are great for thought-provoking discussions, but often do not survive sober morning checks. My possible explanation was really nice, but in this example, the crash is on iteration 1, so P does not even exist yet...

There are multiple possible reasons for my original LOBPCG to crash, most summarized in https://arxiv.org/abs/1704.07458, but their solution is somewhat computationally heavy and the code not available. 

I'll try to spend some time on Saturday debugging.

**Comment by antoine-levitt** [comment] 2019-06-05 13:11
So I did some tests and thinking, here are some thoughts for the brave soul who wants to delve into a stable implementation of LOBPCG

- The root of the instability seems to be the linear dependence between P and X. This is most easily seen in the single-vector case: the Rayleigh-Ritz for the space Y = [x r p] will give as eigenvector Y* A Y a vector `c` that is almost [1;0;0]. The basic algorithm (which, if I understand correctly, is the one implemented in matlab, scipy and julia) is: form p = Y*(c - [1;0;0]), normalize it, orthogonalize it against the new x (equal to Y*c), and deduce A*p from the previous operations and A*Y. Even if the orthogonalization is done stably, that incurs a significant loss of information: eg the A*p deduced from A*Y will deviate from the true one. A much better solution is what Hetmaniuk & Lehoucq do, which is to orthogonalize c against [1;0;0]. Then you deduce A*p from orthogonal transformations, with no loss of accuracy. The implementations in scipy/julia/matlab don't seem to follow that, which is a shame. Of course p itself deviates from the exact-arithmetic one, but only by a relative factor of 10^-16*norm(c-[1;0;0]). It is possible to reduce this using eg perturbation theory, but probably not worth it.

- For stability, the Cholesky-based orthogonalizations should be avoided as far as possible. They will fail for badly conditioned matrices, and you can't really recover from that without discarding valuable information. QR factorizations are good but not sufficient for generalized eigenvalue problems; a good compromise is to orthogonalize with QR wrt the euclidean inner product, and then with Cholesky wrt the B inner product. As @lobpcg says, however, the parallel scalability suffers, although I'm not sure how important that is compared to the Rayleigh-Ritz. https://epubs.siam.org/doi/pdf/10.1137/17M1129830 discusses this.

- If you want to exagerate stability issues, push convergence criteria to the minimum, and disable locking.

- A near-optimal version to compare against is in https://gist.github.com/antoine-levitt/f8ac3637c5d5d778a448780172e63e28 (forgetting about the `align`, which doesn't do anything). This cheats by using too many matvecs for A.

**Comment by mfherbst** [comment] 2019-06-05 13:25
@antoine-levitt I made some amendments to your original gist, reducing the number of applies. It is a little less numerically stable (I lost one order of magnitude maximal precision), but it is more suitable for matrix-free methods. See [mfherbst/issue_scipy_lobpcg_guess](https://github.com/mfherbst/issue_scipy_lobpcg_guess/blob/master/test_LOBPCG_QR.jl).

**Comment by lobpcg** [comment] 2019-06-06 13:55
- The maximal precision is typically of no importance, unless it is really bad. 
- Producing very stable and slow versions is easy, but of little practical interest.
- Multiple implementaions of LOBPCG core ideas are possible, and several publicly available. 
- Our current scipy LOBPCG version follows my original work 
- 1. A. V. Knyazev, I. Lashuk, M. E. Argentati, and E. Ovchinnikov, Block Locally Optimal Preconditioned Eigenvalue Xolvers (BLOPEX) in hypre and PETSc, SIAM Journal on Scientific Computing 25(5): 2224-2239 (2007) 
- 2. A. V. Knyazev, Toward the Optimal Preconditioned Eigensolver: Locally Optimal Block Preconditioned Conjugate Gradient Method, SIAM Journal on Scientific Computing 23(2): 517-541 (2001) 
- Other publicly available revisions (none written in python or MATLAB to easily try) are more stable and slower, to various degrees

My original MATLAB implementation https://www.mathworks.com/matlabcentral/fileexchange/48-lobpcg-m that this scipy code follows does not use try/catch error (unavailable at that time in MATLAB). Since the scipy code typically works most of the time (unless abused), I hope that there may be a simple cheap fix, using try/catch error. I'll look into it.

**Comment by lobpcg** [comment] 2019-06-07 17:36
Let me ping an expert @joseeroman in case he has some advice

**Comment by lobpcg** [comment] 2019-06-08 17:53
@rc @mfherbst  @joseeroman @antoine-levitt @mohamed82008 

I think that I have found the trouble and an easy fix: 

https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py follows https://arxiv.org/abs/0705.2626 implemented in https://github.com/lobpcg/blopex/blob/master/blopex_abstract/krylov/lobpcg.c , which is a somewhat simplified version of my original MATLAB implementation  https://github.com/lobpcg/blopex/blob/master/blopex_tools/matlab/lobpcg/lobpcg.m

Comparing my original MATLAB implementation  https://github.com/lobpcg/blopex/blob/master/blopex_tools/matlab/lobpcg/lobpcg.m with this scipy code, I see 2 steps missing. The most important one is MATLAB lines 601-608
```
    %Making active (preconditioned) residuals orthogonal to blockVectorX
    if isempty(operatorB)
        blockVectorR(:,activeMask) = blockVectorR(:,activeMask) - ...
            blockVectorX*(blockVectorX'*blockVectorR(:,activeMask));
    else
        blockVectorR(:,activeMask) = blockVectorR(:,activeMask) - ...
            blockVectorX*(blockVectorBX'*blockVectorR(:,activeMask));
    end
```

that should have been before line 460 of https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py but not there. I have not tested yet, but this is likely fix the present issue. 

The other omission in the BLOPEX-C and scipy versions is the use ```explicitGramFlag = 1;  %suggested by Garrett Moran``` in MATLAB that forces explicitly computing several blocks in the Gram matrices for the Rayleigh-Ritz method, see starting at line 709 of https://github.com/lobpcg/blopex/blob/master/blopex_tools/matlab/lobpcg/lobpcg.m But this only kicks off at small tolerances so not as crucial as the first omission.

**Comment by lobpcg** [comment] 2019-08-09 01:43
@rc @mfherbst @joseeroman @antoine-levitt @mohamed82008 I think that following my own recommendations https://github.com/scipy/scipy/issues/10258#issuecomment-500145533 I have now fixed this issue in https://github.com/lobpcg/scipy/blob/master/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py 
I'll add more unit tests, make a PR, and reference this issue. 

In the mean time, if you have a chance to test it, have any comments/suggestions, or can help with more unit tests, please feel free to let me know. Performance-wise, it should be no noticeable change, but it should be much more stable now, although the code is still based on the cheap Cholesky.

**Comment by mfherbst** [comment] 2019-08-19 13:01
With the changes suggested in #10621 this issue will be resolved.

**Closed** 2019-08-20 03:50 UTC
Labels: scipy.sparse.linalg

**Comment by lobpcg** [comment] 2019-08-20 15:09
> 
> 
> With the changes suggested in #10621 the issue in the provided example will be resolved.

@mfherbst thanks for providing your perfectly documented and motivating simple example!

**Comment by mfherbst** [comment] 2019-08-20 15:14
@lobpcg You're welcome. I'm happy to have stimulated the discussion.
