### ISSUE TITLE
RuntimeError: dictionary changed size during iteration on loading _continuous_distns.py

### ISSUE THREAD

**Issue by nanodan** [scipy/scipy#11479] opened 2020-02-06 20:58 UTC
When importing from _continuous_distns.py in Apache Beam (tested on Google Cloud Dataflow) the import sometimes throws a `RuntimeError: dictionary changed size during iteration` on the line `pairs = list(globals().items())`

#### Error message:
```
textPayload: "Error message from worker: Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 813, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 448, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 928, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "./CLUSTERS/dbscan_for_intersection_traces_dataflow.py", line 30, in process
  File "/usr/local/lib/python3.5/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "/usr/local/lib/python3.5/site-packages/sklearn/cluster/spectral.py", line 15, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "/usr/local/lib/python3.5/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from .ranking import auc
  File "/usr/local/lib/python3.5/site-packages/sklearn/metrics/ranking.py", line 26, in <module>
    from scipy.stats import rankdata
  File "/usr/local/lib/python3.5/site-packages/scipy/stats/__init__.py", line 379, in <module>
    from .stats import *
  File "/usr/local/lib/python3.5/site-packages/scipy/stats/stats.py", line 182, in <module>
    from . import distributions
  File "/usr/local/lib/python3.5/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/usr/local/lib/python3.5/site-packages/scipy/stats/_continuous_distns.py", line 7337, in <module>
    pairs = list(globals().items())
RuntimeError: dictionary changed size during iteration
```
### Code to Reproduce
`from sklearn.cluster import DBSCAN`

#### Scipy/Numpy/Python version information:
scipy: 1.3.1
scikit-learn: 0.21.3
numpy: 1.17.3

**Comment by pvanmulbregt** [comment] 2020-02-09 05:11
I wasn't able to reproduce the problem
```
from sklearn.cluster import DBSCAN  
sklearn.show_versions()                                                                                                                                                                                    

System:
    python: 3.8.0 (default, Nov  6 2019, 15:49:01)  [Clang 4.0.1 (tags/RELEASE_401/final)]
executable: /Users/Paul/anaconda/envs/py38scipydev2/bin/python
   machine: macOS-10.15.2-x86_64-i386-64bit

Python dependencies:
       pip: 19.3.1
setuptools: 42.0.2.post20191203
   sklearn: 0.22.1
     numpy: 1.17.3
     scipy: 1.5.0.dev0+954b2b2
    Cython: 0.29.14
    pandas: None
matplotlib: 3.1.2
    joblib: 0.14.1

Built with OpenMP: True
```

**Comment by hammad26** [comment] 2020-05-01 08:17
I also faced this exception while loading a model using joblib. Traceback is:

```
  File "/usr/local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 605, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.6/pickle.py", line 1338, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python3.6/pickle.py", line 1388, in find_class
    __import__(module, level=0)
  File "/usr/local/lib/python3.6/site-packages/sklearn/feature_extraction/__init__.py", line 10, in <module>
    from . import text
  File "/usr/local/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 28, in <module>
    from ..preprocessing import normalize
  File "/usr/local/lib/python3.6/site-packages/sklearn/preprocessing/__init__.py", line 8, in <module>
    from .data import Binarizer
  File "/usr/local/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 17, in <module>
    from scipy import stats
  File "/usr/local/lib/python3.6/site-packages/scipy/stats/__init__.py", line 379, in <module>
    from .stats import *
  File "/usr/local/lib/python3.6/site-packages/scipy/stats/stats.py", line 182, in <module>
    from . import distributions
  File "/usr/local/lib/python3.6/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/usr/local/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py", line 7346, in <module>
    pairs = list(globals().items())
RuntimeError: dictionary changed size during iteration
```

**Environment Details**
Python: 3.6.5
scipy: 1.3.2
scikit-learn: 0.21.3
numpy: 1.17.4

**Comment by phongvis** [comment] 2020-07-31 07:43
I'm having the same problem when loading with cloudpickle. It sometimes throws that error. But I can't reproduce it on demand.

**Comment by andyfaff** [comment] 2020-07-31 08:15
- I can't reproduce the original problem with Python 3.8.3, scipy 1.6.0.dev.
- I can't reproduce the original problem with Python 3.6.10, numpy 1.19.1, sklearn=0.23.1, scipy=1.5.2
- I can't reproduce the original problem with Python 3.6.10, numpy 1.19.1, sklearn=0.22.1, scipy=1.5.2

Original post is with Python3.5, which is end-of-life. I'm tempted to close the issue on that basis. The subsequent posts are more recent, not as sure what to do with those. @hammad26, can you try updating scipy/scikit-learn and numpy and see if the problem is still there?

**Comment by phongvis** [comment] 2020-07-31 08:21
Mine is Python 3.8

**Comment by andyfaff** [comment] 2020-07-31 08:27
@phongvis, if we don't have a way to reproduce the error it's very had to fix. Do you have a minimal working example that reproduces the issue? (even if it is a proportion of the time). 

I have no problem with:
```
System:
    python: 3.8.3 (default, Jul  2 2020, 11:26:31)  [Clang 10.0.0 ]
executable: /Users/andrew/miniconda3/envs/dev3/bin/python
   machine: macOS-10.15.6-x86_64-i386-64bit

Python dependencies:
       pip: 20.1.1
setuptools: 49.2.0.post20200714
   sklearn: 0.22
     numpy: 1.19.1
     scipy: 1.6.0.dev0+2a0b800
    Cython: 0.29.21
    pandas: 1.0.5
matplotlib: 3.3.0
    joblib: 0.16.0
```

**Comment by phongvis** [comment] 2020-07-31 08:29
I'm trying different ways to reproduce the error. I'll post when I'm able to. Thanks @andyfaff.

**Comment by andyfaff** [comment] 2020-07-31 08:29
I wonder if `pairs = list(globals().copy().items())` would help.

**Comment by phongvis** [comment] 2020-07-31 08:33
It seems reasonable as it makes a copy first.

**Comment by phongvis** [comment] 2020-07-31 15:07
@andyfaff would it possible for you to make that change?

**Comment by tylerjereddy** [comment] 2020-09-10 01:59
Should be fixed by gh-12833, which has now been merged into `master`.

If someone who observed the issue here wants to confirm they no longer observe it that may be helpful.

**Closed by tylerjereddy** 2020-09-10 01:59 UTC
Labels: defect, scipy.stats

**Comment by WarrenWeckesser** [comment] 2021-08-24 17:44
New report on stackoverflow: https://stackoverflow.com/questions/68911221/python-runtimeerror-dictionary-changed-size-during-iteration-popping-out-rand

**Comment by Dominik1123** [comment] 2021-08-24 21:00
> New report on stackoverflow: https://stackoverflow.com/questions/68911221/python-runtimeerror-dictionary-changed-size-during-iteration-popping-out-rand

That SO post reports the same behavior in `scipy/stats/_discrete_distns.py` while the fix for the current issue only addressed ` scipy/stats/_continuous_distns.py`.

**Comment by andyfaff** [comment] 2021-08-24 23:46
@Dominik1123, @WarrenWeckesser I made a PR for applying the same change to the discrete distributions as well in #14637

**Comment by Dominik1123** [comment] 2021-08-25 16:31
I found this [BPO report](https://bugs.python.org/issue40327) which seems to describe a similar problem (although with the difference that they are iterating over `sys.modules` in a multi-threaded setting with imports happening simultaneously). For that BPO report, it is clear how the iterated dict can change (namely due to imports in other threads). Also according to [this comment](https://bugs.python.org/issue40327#msg366854), adding `.copy()` reduces the probability of this happening, however not to zero. So it seems that the applied "fix" won't prevent this in all cases.

This leaves the question, why are the `globals` changing while being iterated over? Especially since this happens during import of the module, I can't imagine how threading could be an issue here. Did you consider submitting this to BPO?
