### ISSUE TITLE
BUG: warning from `optimize.least_squares` for astropy with OpenBLAS 0.3.26-dev

### ISSUE THREAD

**Issue by neutrinoceros** [scipy/scipy#20531] opened 2024-04-19 13:45 UTC
### Describe your issue.

When running astropy's test suite locally I see one test behaving differently depending on
which version of scipy I have installed.
Namely, I get a warning with scipy 1.13.0, which doesn't appear with 1.12.0.
Specifically, I see this problem with the following wheel `scipy-1.13.0-cp312-cp312-macosx_12_0_arm64.whl`

I've investigated the problem but most of what I tried to gather information failed. In particular
- I wasn't able to reproduce without astropy (or to be more transparent, I haven't had the time to remove astropy from my reproducer yet)
- I wasn't able to reproduce with local builds of scipy (I can build it, but the warning never shows up), so I couldn't bisect it, and I'm suspecting the issue might be in the wheel building process (?)

That said, I'll try to be as thorough as possible in my report with what I *did* find.
For completeness, here's the script I used for building scipy locally

```shell
set -euxo pipefail

export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"

pushd _scipy
git submodule update --init
rm -fr dist
python -m build --wheel
popd

python -m pip install ./_scipy/dist/*.whl
```

where `_scipy` is my local clone of the repo.

I tried checking in the main branch (currently 53a9e10241814b70c0975e099588bdef09006694) as well as the `v1.13.0` tag, both of which behave fine when built locally (no warning is emitted).

Here's my env's info with the local build

<details><summary>Env info (scipy 1.13.0 built locally)</summary>

```
1.13.0 1.26.4 sys.version_info(major=3, minor=12, micro=2, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/homebrew/Cellar/openblas/0.3.27/include
    lib directory: /opt/homebrew/Cellar/openblas/0.3.27/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=56
    pc file directory: /opt/homebrew/opt/openblas/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/homebrew/Cellar/openblas/0.3.27/include
    lib directory: /opt/homebrew/Cellar/openblas/0.3.27/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=56
    pc file directory: /opt/homebrew/opt/openblas/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 13.2.0
  pythran:
    include directory: ../../../../../../../private/var/folders/47/t9k4zdz96vzd4v1rxyv07nvh0000gn/T/build-env-wzebhths/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/47/t9k4zdz96vzd4v1rxyv07nvh0000gn/T/build-env-wzebhths/bin/python
  version: '3.12'
```

</details>

### Reproducing Code Example

```python
from astropy.modeling.models import Gaussian1D
from scipy.optimize import least_squares
import numpy as np


def objective_function(fps, *args):
    "Function to minimize."
    model, x, y = args

    fit_param_indices = list(range(len(model.param_names)))
    parameters = model.parameters

    fit_param_indices = set(fit_param_indices)
    offset = 0
    param_metrics = model._param_metrics
    for name in model.param_names:
        slice_ = param_metrics[name]["slice"]
        values = fps[offset : offset + 1]

        parameters[slice_] = values
        offset += 1

    # Update model parameters before calling ``tied`` constraints.
    model._array_to_parameters()

    return np.ravel(model(x) - y)


def dfunc(params, model, x, y):
    fit_deriv = np.array(model.fit_deriv(x, *params))
    return np.array([np.ravel(_) for _ in np.array(1.0) * fit_deriv]).T


inf = float("inf")
least_squares(
    fun=objective_function,
    x0=np.array([1.0e-03, 3.0e00, 2.0e-01]),
    args=(
        Gaussian1D(amplitude=0.001, mean=3.0, stddev=0.2),
        np.linspace(-500, 500, 2000, endpoint=True),
        np.ones(2000),
    ),
    jac=dfunc,
    bounds=((-inf, -inf, 1.1754943508222875e-38), (inf, inf, inf)),
)
```

### Error message

```shell
/Users/clm/.pyenv/versions/3.12.2/envs/astropy.dev/lib/python3.12/site-packages/scipy/optimize/_lsq/common.py:398: RuntimeWarning: invalid value encountered in cast
  return min_step, np.equal(steps, min_step) * np.sign(s).astype(int)
```

### SciPy/NumPy/Python version and system information

```shell
1.13.0 1.26.4 sys.version_info(major=3, minor=12, micro=2, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.26.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.26.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 13.2.0
  pythran:
    include directory: ../../../../../../private/var/folders/l_/53d72k7j4zl9kj8fzncsd8hw0000gn/T/pip-build-env-mabxfhvc/overlay/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/l_/53d72k7j4zl9kj8fzncsd8hw0000gn/T/cibw-run-ehybylsk/cp312-macosx_arm64/build/venv/bin/python
  version: '3.12'
```

**Comment by neutrinoceros** [comment] 2024-04-19 15:05
comparing system informations from my report I see that the PyPI wheel was compiled with openblas `0.3.26dev` while locally I have `0.3.27`. Any chance this is the meaningful difference ?

**Comment by neutrinoceros** [comment] 2024-04-21 07:05
I tried nightly wheels from https://pypi.anaconda.org/scientific-python-nightly-wheels/simple, both for Python 3.11 and 3.12 and saw the warning with both.
I also tried editing the build process to use homebrew openblas in CI but it doesn't resolve the issue (and it doesn't actual survives wheel testing)

**Comment by neutrinoceros** [comment] 2024-04-22 08:03
Building scipy 1.13.0 from source *from the tarball on pypi* also avoids the warning.

**Comment by neutrinoceros** [comment] 2024-04-22 09:51
I'm also able to reproduce in CI, so I can now exclude the possibility that something is wrong with my personal setup
https://github.com/astropy/astropy/actions/runs/8781878745/job/24094808203?pr=16321

**Comment by lucascolley** [comment] 2024-04-22 10:36
@mattip does this look like It could be an OpenBLAS thing?

**Comment by neutrinoceros** [comment] 2024-04-23 10:01
FYI, today I'm trying to reduce the reproducer down as much as I can. I just reached the point where it no longer depends on astropy but I still have ~1200 lines of vendored code. I'll melt it down some more but at least now it's isolated.

**Comment by neutrinoceros** [comment] 2024-04-23 18:02
Here is a much much simpler version of the reproducer
```python
import numpy as np
from scipy.optimize import least_squares


class Parameter:
    def __init__(self, value):
        self.value = np.float64(value)


class Gaussian1D:
    def __init__(self):
        self.amplitude = Parameter(1)
        self.mean = Parameter(0)
        self.stddev = Parameter(1)


MODEL = Gaussian1D()
X = np.linspace(-500, 500, 2000)
Y = np.ones(2000)


def objective_function(fps):
    a, v, std = MODEL.amplitude.value, MODEL.mean.value, MODEL.stddev.value = fps
    return a * np.exp(-0.5 * (X - v) ** 2 / std**2) - Y


def dfunc(params):
    amplitude, mean, stddev = params

    d_amplitude = np.exp(-0.5 / stddev**2 * (X - mean) ** 2)
    d_mean = amplitude * d_amplitude * (X - mean) / stddev**2
    d_stddev = amplitude * d_amplitude * (X - mean) ** 2 / stddev**3
    return np.array([d_amplitude, d_mean, d_stddev]).T


inf = float("inf")
least_squares(
    fun=objective_function,
    x0=np.array([1.0, 3.0e00, 2.0e-01]),
    jac=dfunc,
    bounds=((-inf, -inf, 0.0), (inf, inf, inf)),
)
```

It could probably be reduced even further if needed, but it's already ~60x smaller than the original version.

**Comment by tylerjereddy** [comment] 2024-04-23 18:20
thanks, let me take a look

**Comment by tylerjereddy** [comment] 2024-04-23 20:53
Well, local reproduction is indeed difficult on MacOS, even with `cibuildwheel` (have to adjust some things to avoid `sudo` and some other things...). While I haven't succeeded at that yet, I did confirm that the `select_step()` `in_bounds()` check is always `True` on `v1.12.0`, but not for `v1.13.0` (referring to the wheels on PyPI): 

https://github.com/scipy/scipy/blob/70fdbf2d33d31cca488a0a64625ac742ed1c63c6/scipy/optimize/_lsq/trf.py#L130-L134

The `return` is always hit in that above block for `v1.12.0` MacOS wheel, but not for `v1.13.0`. @nmayorov may have some insight, but this one is pretty subtle, and I can't reproduce OpenBLAS being the culprit when I try using the same one as the wheel.

**Comment by tylerjereddy** [comment] 2024-04-23 21:05
We may need to print out the iterative values of `x`, `p`, `lb`, and `ub` in the optimization control flow. That may be get a bit messy, I'll circle back to it if an `optimize` regular doesn't chime in soon.

**Comment by andyfaff** [comment] 2024-04-24 05:01
- I don't see this with `('1.14.0.dev0+852.cca3e4c', '1.26.4')`. This is self-built using Accelerate for scipy
- I don't see this with ('1.12.0', '1.26.4').
- I can reproduce with ('1.13.0', '2.0.0rc1'). These are from PyPI using OpenBLAS for scipy, but Accelerate for numpy.
- I can reproduce with ('1.13.0', '1.26.4').

In the reproducing environment I modified `optimize._lsq.common` to include the lines:

```
    with np.errstate(invalid='raise'):
        try:
            v = np.equal(steps, min_step) * np.sign(s).astype(int)
        except FloatingPointError as e:
            print(s, s.dtype)
            raise e
```
 the stacktrace highlights `np.sign(s).astype(int)`:
```
[nan nan nan] float64

---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
Cell In[2], line 37
     33     return np.array([d_amplitude, d_mean, d_stddev]).T
     36 inf = np.inf
---> 37 least_squares(
     38     fun=objective_function,
     39     x0=np.array([1.0, 3.0e00, 2.0e-01]),
     40     jac=dfunc,
     41     bounds=((-inf, -inf, 0.0), (inf, inf, inf)),
     42 )

File ~/miniconda3/envs/dev3/lib/python3.12/site-packages/scipy/optimize/_lsq/least_squares.py:941, in least_squares(fun, x0, jac, bounds, method, ftol, xtol, gtol, x_scale, loss, f_scale, diff_step, tr_solver, tr_options, jac_sparsity, max_nfev, verbose, args, kwargs)
    937     result = call_minpack(fun_wrapped, x0, jac_wrapped, ftol, xtol, gtol,
    938                           max_nfev, x_scale, diff_step)
    940 elif method == 'trf':
--> 941     result = trf(fun_wrapped, jac_wrapped, x0, f0, J0, lb, ub, ftol, xtol,
    942                  gtol, max_nfev, x_scale, loss_function, tr_solver,
    943                  tr_options.copy(), verbose)
    945 elif method == 'dogbox':
    946     if tr_solver == 'lsmr' and 'regularize' in tr_options:

File ~/miniconda3/envs/dev3/lib/python3.12/site-packages/scipy/optimize/_lsq/trf.py:123, in trf(fun, jac, x0, f0, J0, lb, ub, ftol, xtol, gtol, max_nfev, x_scale, loss_function, tr_solver, tr_options, verbose)
    119     return trf_no_bounds(
    120         fun, jac, x0, f0, J0, ftol, xtol, gtol, max_nfev, x_scale,
    121         loss_function, tr_solver, tr_options, verbose)
    122 else:
--> 123     return trf_bounds(
    124         fun, jac, x0, f0, J0, lb, ub, ftol, xtol, gtol, max_nfev, x_scale,
    125         loss_function, tr_solver, tr_options, verbose)

File ~/miniconda3/envs/dev3/lib/python3.12/site-packages/scipy/optimize/_lsq/trf.py:334, in trf_bounds(fun, jac, x0, f0, J0, lb, ub, ftol, xtol, gtol, max_nfev, x_scale, loss_function, tr_solver, tr_options, verbose)
    331     p_h = S.dot(p_S)
    333 p = d * p_h  # Trust-region solution in the original space.
--> 334 step, step_h, predicted_reduction = select_step(
    335     x, J_h, diag_h, g_h, p, p_h, d, Delta, lb, ub, theta)
    337 x_new = make_strictly_feasible(x + step, lb, ub, rstep=0)
    338 f_new = fun(x_new)

File ~/miniconda3/envs/dev3/lib/python3.12/site-packages/scipy/optimize/_lsq/trf.py:134, in select_step(x, J_h, diag_h, g_h, p, p_h, d, Delta, lb, ub, theta)
    131     p_value = evaluate_quadratic(J_h, g_h, p_h, diag=diag_h)
    132     return p, p_h, -p_value
--> 134 p_stride, hits = step_size_to_bound(x, p, lb, ub)
    136 # Compute the reflected direction.
    137 r_h = np.copy(p_h)

File ~/miniconda3/envs/dev3/lib/python3.12/site-packages/scipy/optimize/_lsq/common.py:403, in step_size_to_bound(x, s, lb, ub)
    401     except FloatingPointError as e:
    402         print(s, s.dtype)
--> 403         raise e
    405 return min_step, v

File ~/miniconda3/envs/dev3/lib/python3.12/site-packages/scipy/optimize/_lsq/common.py:400, in step_size_to_bound(x, s, lb, ub)
    398 with np.errstate(invalid='raise'):
    399     try:
--> 400         v = np.equal(steps, min_step) * np.sign(s).astype(int)
    401     except FloatingPointError as e:
    402         print(s, s.dtype)

FloatingPointError: invalid value encountered in cast
```
The `s` array is filled with nan, and it's an invalid cast to make those an int. I'm currently trying to step back up the call chain to find what produces the NaN. Not much as changed in `optimize._lsq`, so I'm inclined to put this down to a BLAS effect.

**Comment by andyfaff** [comment] 2024-04-24 05:46
I think I've pinned it down to the singular value decomposition of an array being different for scipy installed via pip for 1.12 vs 1.13.
To reproduce you have to have this array, [J_augmented.npy.zip](https://github.com/scipy/scipy/files/15088264/J_augmented.npy.zip). It's a numpy array that's been saved and zipped. So you'll need to download and unzip.

To see the issue:
```
from scipy.linalg import svd
import numpy as np
j_augmented = np.load("J_augmented.npy")
svd(j_augmented, full_matrices=False)
```

with scipy==1.12 the output is:
```
(array([[ 3.86075347e-20, -5.14217201e-17,  1.96719877e-17],
       [ 1.56160755e-20,  1.76680709e-33,  7.95697644e-18],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]), array([6.69848203, 0.35240654, 0.35216193]), array([[-9.99303963e-01, -8.28315251e-18, -3.73040025e-02],
       [-0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 3.73040025e-02, -2.21890054e-16, -9.99303963e-01]]))
```

with scipy 1.13 the output is:
```
(array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       ...,
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]]), array([inf, inf, inf]), array([[-1., -0., -0.],
       [ 0.,  1.,  0.],
       [-0., -0., -1.]]))
```

The svd is called as [`U, s, V = svd(J_augmented, full_matrices=False)`](https://github.com/scipy/scipy/blob/8431e12346ac9564e244bfce920dc8a04bcabbd9/scipy/optimize/_lsq/trf.py#L301), affecting the calculation of [`uf = U.T.dot(f_augmented)`](https://github.com/scipy/scipy/blob/8431e12346ac9564e244bfce920dc8a04bcabbd9/scipy/optimize/_lsq/trf.py#L303), then [`p_h, alpha, n_iter = solve_lsq_trust_region(n, m, uf, s, V, Delta, initial_alpha=alpha)`](https://github.com/scipy/scipy/blob/8431e12346ac9564e244bfce920dc8a04bcabbd9/scipy/optimize/_lsq/trf.py#L327C1-L328C64), then [`p = d * p_h`](https://github.com/scipy/scipy/blob/8431e12346ac9564e244bfce920dc8a04bcabbd9/scipy/optimize/_lsq/trf.py#L333), etc.

So if a linalg expert can tell us why the SVD produces different outputs between the two scipy versions, specifically why SVD produces a lot of NaN, then we'll be getting somewhere. So the issue is not to do with optimize, but is to do with linalg.

**Comment by andyfaff** [comment] 2024-04-24 05:49
The offending openblas config for 1.13 is:
```
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.26.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.26.dev
```

For scipy 1.12 the openblas config was:
```
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
```

**Comment by andyfaff** [comment] 2024-04-24 05:53
Note that all values in `J_augmented` are finite, with the maximum value being ~0.9998 and the minimum value being ~ -0.045

**Comment by mattip** [comment] 2024-04-24 05:53
Nice sluething. @martin-frbg does this ring a bell?

**Comment by mattip** [comment] 2024-04-24 05:54
Does this affect x86_64 as well or only arm64?

**Comment by andyfaff** [comment] 2024-04-24 06:01
I'm working on arm64. I think OP is using arm64 as well.

**Comment by martin-frbg** [comment] 2024-04-24 06:22
openblas config as reported can't be correct if you are on arm64 (SANDYBRIDGE default target strongly suggests x86_64). Not many candidates between 0.3.26.dev (whatever snapshot that was) and 0.3.27 - most likely would be the NRM2 kernel for (among others) Apple M getting switched back to the older ARMV8 version due to observed inaccuracies (failing to compute the SVD of a particular matrix, https://github.com/OpenMathLib/OpenBLAS/issues/4583)

**Comment by andyfaff** [comment] 2024-04-24 06:23
Hmm, those instructions are not so easy. I think I've reached the limit of what I'm easily able to do.

**Comment by andyfaff** [comment] 2024-04-24 06:28
> openblas config as reported can't be correct if you are on arm64 (SANDYBRIDGE default target strongly suggests x86_64).

I'm definitely on arm64, it'll be that the openblas.pc file is not correct. I think @mattip does some manipulation of them when building openblas, and the patch will not be perfect.

**Comment by andyfaff** [comment] 2024-04-24 06:52
FWIW I've just tried openblas@0.3.27 from homebrew and the issue isn't present

```
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/homebrew/Cellar/openblas/0.3.27/include
    lib directory: /opt/homebrew/Cellar/openblas/0.3.27/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=56
    pc file directory: /opt/homebrew/opt/openblas/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/homebrew/Cellar/openblas/0.3.27/include
    lib directory: /opt/homebrew/Cellar/openblas/0.3.27/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=1 VORTEX MAX_THREADS=56
    pc file directory: /opt/homebrew/opt/openblas/lib/pkgconfig
    version: 0.3.27
```

A pragmatic approach may be to bump to 0.3.27. However, I can't try with the openblas builds at https://anaconda.org/scientific-python-nightly-wheels/openblas-libs/files because

> scipy/meson.build:271:4: ERROR: File _distributor_init_local.py does not exist.

**Comment by martin-frbg** [comment] 2024-04-24 06:52
No trivial way to fix the "broken" installation, but you should be able to break the "good" one by setting OPENBLAS_CORETYPE=ARMV8 in the environment before calling into OpenBLAS. (Still this would be a bit perplexing as the more generic "ARMV8" NRM2 kernels were used "successfully" in earlier builds)

**Comment by martin-frbg** [comment] 2024-04-24 06:56
I may have misread - is 0.3.26 the version that's assumed to be broken (returning NaNs), or is it 0.3.27 ?

**Comment by andyfaff** [comment] 2024-04-24 07:02
0.3.21.dev (scipy1.12) is ok, 0.3.26.dev (scipy1.13) is broken, 0.3.27 (from homebrew, build scipy locally) is ok.

exporting OPENBLAS_CORETYPE=ARMV8 appeared didn't do anything when I tried running the test with 0.3.21.dev (a la scipy1.12). *However, it did appear to fix the broken version (0.3.26.dev), as installed in scipy1.13*.

**Comment by martin-frbg** [comment] 2024-04-24 07:11
OK, then this is probably a duplicate of "my" closed issue 4583 and you were just unfortunate to hit one of the corner cases where it shows up - though having another reproducer may help with fixing the underlying bug in that particular nrm2 kernel.

**Comment by neutrinoceros** [comment] 2024-04-24 07:13
> Does this affect x86_64 as well or only arm64?

kinda belated, but we've only seen it arm64. x86 appears to be fine.

**Comment by mattip** [comment] 2024-04-24 08:04
> However, I can't try with the openblas builds

Scipy does not build with the wheels yet, it still uses the older tarball-based builds. So theoretically you should be able to use the 32-bit builds from https://anaconda.org/scientific-python-nightly-wheels/openblas-libs/files. But those use a `scipy_` symbol and libname prefix that is not (yet) supported in scipy. So I use the older workflow to still produce a tarball with the older non-prefixed symbols at https://anaconda.org/multibuild-wheels-staging/openblas-libs/files. The latest available there is 0.3.26-382, still a bit shy of 0.3.27. I will start a build of 0.3.27 and get back when it can be tested.

I don't know where the SANDYBRIDGE model is coming from. The download used to build the scipy wheels comes from tools/openblas_support.py, which currently downloads https://anaconda.org/multibuild-wheels-staging/openblas-libs/v0.3.26-382-gb1e8ba50/download/openblas-v0.3.26-382-gb1e8ba50-macosx_11_0_arm64-gf_5272328.tar.gz. The action that [built that tarball](https://github.com/MacPython/openblas-libs/actions/runs/8499664684/job/23307705007#step:10:180) used [this make command](https://github.com/MacPython/openblas-libs/actions/runs/8499664684/job/23307705007#step:7:1106)
```
CFLAGS=' -arch arm64 -fvisibility=protected'
make BUFFERSIZE=20 DYNAMIC_ARCH=1 USE_OPENMP=0 NUM_THREADS=64 \
    BINARY=64 TARGET=VORTEX
```

**Comment by mattip** [comment] 2024-04-24 08:42
I wonder if the `SANDYBRIDGE` comes from not defining `$CORE`. We define `$TARGET`, but perhaps the `$CORE` comes from the host of the cross-compile build.

**Comment by mattip** [comment] 2024-04-24 12:33
See #20569

**Closed** 2024-04-25 10:23 UTC
Labels: defect, scipy.optimize, upstream bug

**Comment by mattip** [comment] 2024-04-26 01:01
> `CORE` is an internal variable and set from `TARGET`

@martin-frbg sorry to bother, but could you point to where this happens? `git grep "\<CORE.*="` is not showing me anything useful as far as I can tell.
