### ISSUE TITLE
Error: anable to solve the linear assignment of a cost_matrix with nan values

### ISSUE THREAD

**Issue by LoSpino87** [scipy/scipy#14545] opened 2021-08-05 10:05 UTC
Hi everybody and thank you for your contributions. 
As reported below, if the following cost_matrix contains nan values, the linear_sum_assignment function crashes.
```
cost_matrix
[[0.70001    0.70001    0.70001    0.70001   ]
 [0.03333333 0.70001    0.70001    0.70001   ]
 [       nan        nan        nan        nan]]
```

```
    indices = linear_sum_assignment(cost_matrix)
  File "/usr/local/lib/python3.7/dist-packages/scipy/optimize/_lsap.py", line 100, in linear_sum_assignment
    return _lsap_module.calculate_assignment(cost_matrix)
ValueError: matrix contains invalid numeric entries
```

scipy version 1.7.0

**Comment by pmla** [comment] 2021-08-05 10:47
Raising a `ValueError` is the intended behaviour. A `nan` value in the input usually means something has gone wrong, so we want to catch this.

**Comment by tupui** [comment] 2021-08-06 10:30
Can we close this then?

**Comment by pmla** [comment] 2021-08-06 10:35
Yes :)

**Closed by pmla** 2021-08-06 10:35 UTC
