### ISSUE TITLE
BUG: scipy 1.10.0 crashes when using a large float in skellam distr on apple silicon

### ISSUE THREAD

**Issue by japoco** [scipy/scipy#17916] opened 2023-02-02 19:48 UTC
### Describe your issue.

Scipy 1.10.0 is crashing my script if I use a large float as a parameter for the skellam distribution on apple silicon.

### Reproducing Code Example

```python
from scipy.stats import skellam

skellam.pmf(0, 1.0, 4820232647677555.0)
# or skellam.cdf(0, 1.0, 4820232647677555.0)
```

### Error message

```shell
libc++abi: terminating with uncaught exception of type boost::wrapexcept<boost::math::rounding_error>: Error in function boost::math::itrunc<double>(double): Value 4820232647677555 can not be represented in the target integer type.
zsh: abort      /usr/bin/python3 /Users/japoco/Programming/model/test.py
```

### SciPy/NumPy/Python version information

`blas_mkl_info:   NOT AVAILABLE blis_info:   NOT AVAILABLE openblas_info:     libraries = ['openblas', 'openblas']     library_dirs = ['/opt/arm64-builds/lib']     language = c     define_macros = [('HAVE_CBLAS', None)]     runtime_library_dirs = ['/opt/arm64-builds/lib'] blas_opt_info:     libraries = ['openblas', 'openblas']     library_dirs = ['/opt/arm64-builds/lib']     language = c     define_macros = [('HAVE_CBLAS', None)]     runtime_library_dirs = ['/opt/arm64-builds/lib'] lapack_mkl_info:   NOT AVAILABLE openblas_lapack_info:     libraries = ['openblas', 'openblas']     library_dirs = ['/opt/arm64-builds/lib']     language = c     define_macros = [('HAVE_CBLAS', None)]     runtime_library_dirs = ['/opt/arm64-builds/lib'] lapack_opt_info:     libraries = ['openblas', 'openblas']     library_dirs = ['/opt/arm64-builds/lib']     language = c     define_macros = [('HAVE_CBLAS', None)]     runtime_library_dirs = ['/opt/arm64-builds/lib']`

**Comment by mdhaber** [comment] 2023-02-02 20:18
@mborland Not sure if it's Boost or our wrapper, but I can reproduce this on Windows. 
```
from scipy.stats import skellam

skellam.pmf(0, 1.0, 4820232647677555.0)


Fatal Python error: Aborted


Main thread:
Current thread 0x000008c0 (most recent call first):
  File "C:\Users\mhaberla\Desktop\scipy\scipy\stats\_discrete_distns.py", line 1432 in _pmf
  File "C:\Users\mhaberla\Desktop\scipy\scipy\stats\_distn_infrastructure.py", line 3379 in pmf
  File "C:\Users\mhaberla\AppData\Local\Temp\ipykernel_13728\3470758036.py", line 3 in <cell line: 3>
```

**Comment by jabamiyumeko** [comment] 2023-02-02 20:25
Yeah I don't think this is specific to an architecture or platform because I just noticed I'm getting this exact same crash on a digital ocean droplet running debian

**Comment by mdhaber** [comment] 2023-02-02 20:29
A quick fix for SciPy would be to change the `np.where(x < 0...` to `np.where(x <= 0...` because `_boost._ncx2_pdf(2*mu2, 2*(1-x), 2*mu1)*2` has no problem.

```
https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/scipy/stats/_discrete_distns.py#L1424-L1432
```

**Comment by mborland** [comment] 2023-02-02 20:43
I'll have to see what integer type we are trying to convert the double to if the error is coming out of `itrunc`.

**Comment by mborland** [comment] 2023-02-02 21:12
Right now nc is limited to 2147483647 because it is represented by an integer. I could make it as large as 9223372036854775807 which would fit the OPs case. Is there sensical upper bound to what nc could be?

**Comment by mborland** [comment] 2023-02-02 21:39
Fair enough. Linked PR should solve it.

**Comment by mdhaber** [comment] 2023-02-02 21:52
Great - will this fix the CDF, too? I didn't look into whether the CDF uses the PDF in this implementation.

**Comment by mborland** [comment] 2023-02-02 22:18
It does now

**Comment by mborland** [comment] 2023-02-03 17:11
Fixes for both PDF and CDF have been merged.

**Comment by jzmaddock** [comment] 2023-02-03 18:07
Thanks for taking care of this Matt, just to clarify, if the non-centrality parameter exceeded a `long long` then it would become impossible to implement because we would be unable to enumerate values of nc even in a double.  By which I mean nc + 1 would still be nc.  I assume this issue only effected platforms with a 32-bit `int`?

**Comment by mborland** [comment] 2023-02-03 18:20
> Thanks for taking care of this Matt, just to clarify, if the non-centrality parameter exceeded a `long long` then it would become impossible to implement because we would be unable to enumerate values of nc even in a double. By which I mean nc + 1 would still be nc. I assume this issue only effected platforms with a 32-bit `int`?

Yes. Are there any systems that define `int` as 64-bits? I only know that metal systems can go the other way and make it 16-bits.

**Comment by jzmaddock** [comment] 2023-02-03 18:50
>Yes. Are there any systems that define int as 64-bits? I only know that metal systems can go the other way and make it 16-bits.

Ah no, my bad, I was thinking about size_t.  Ignore me it's getting later here...

**Comment by agkphysics** [comment] 2023-02-21 04:00
This also seems to occur for the noncentral t-districution:
```python
from scipy.stats import nct

nct.cdf(2, 2, float(2**16))
```
Results in
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::math::rounding_error>'
  what():  Error in function boost::math::itrunc<double>(double): Value 2147483648 can not be represented in the target integer type.
Aborted
```

**Comment by mdhaber** [comment] 2023-02-21 05:18
@mborland @jzmaddock we fixed this for ncx, but is the same true for nct?

**Comment by jzmaddock** [comment] 2023-02-21 09:41
Reproduced.  We can up the integer type to a long long which will push this well into the long grass, beyond that the implementation becomes impossible/unknown.

**Comment by mdhaber** [comment] 2023-02-21 11:29
Thank you!

**Comment by jzmaddock** [comment] 2023-02-21 18:47
As noted in https://github.com/boostorg/math/pull/955 this can only be *somewhat* fixed: the largest term in the series occurs near the **square** of the non-centrality parameter.  So we can still only handle non-centrality up to 2^32.  I spent a little time looking through the literature on this today and don't see an obvious way forward.  I also don't see an obvious use case for really large non-centralities ;)

**Comment by mdhaber** [comment] 2023-02-21 22:07
I do wonder how people come across these cases. @jabamiyumeko @agkphysics how did you encounter this?

**Comment by agkphysics** [comment] 2023-02-21 23:50
I was using Pingouin to do statistical tests, but in one case a pair of samples had almost zero variance, such that the effect size was some huge number. I'll also file an issue with them to maybe check whether the variance is too low when calculating effect size.

**Comment by japoco** [comment] 2023-02-22 09:14
> I do wonder how people come across these cases. @jabamiyumeko @agkphysics how did you encounter this?

I was fitting a model's parameters with scipy.optimize.minimize.

**Comment by jzmaddock** [comment] 2023-02-22 16:23
>I was fitting a model's parameters with scipy.optimize.minimize.

That would explain things, root finders and function minimisers often generate crazy-out-of-bound values while clomping around looking for "the" solution.  I'll have another quick scan of the literature to see if there are other evaluation methods.

**Comment by japoco** [comment] 2023-02-22 16:52
Yeah that is exactly the problem. It happens very rarely, when the gradient estimation is very flat I guess. I “fixed” this on my end by adding bounds to my optimisation.

**Comment by mdhaber** [comment] 2023-02-22 17:00
Thanks @jzmaddock. 
If you don't come across other evaluation methods, could it give an error indicating that the function is not implemented for such large values of the parameter? That would be preferable to the crash of `ncx2` and a bit more helpful than the message we get with `nct`. If we receive a report about it in the future, I would just consider it an enhancement that would be nice but does not need to happen on any timeline.

**Comment by jzmaddock** [comment] 2023-02-22 18:05
Nod.  I was just thinking that, a domain_error I guess?

Aside: it's ironic but in the root finding case, the older C libraries probably "work" because they tend to fail and just return 0 everywhere once the non-central parameter becomes large.  Benton & Krishnamoorthy papers address this, but the assumption is that the integers values adjacent to the largest terms are representable.

**Comment by mdhaber** [comment] 2023-02-22 18:08
Ah. yes, domain_error sounds appropriate to me. Thanks!

**Closed** 2023-03-01 14:50 UTC
Labels: defect, scipy.stats
