### ISSUE TITLE
'scipy.signal.windows' periodicity

### ISSUE THREAD

**Issue by deeuu** [scipy/scipy#4551] opened 2015-02-24 09:53 UTC
Hi,
In testing the `hann` function (and a few others), odd length windows are the same for both symmetrical and periodic types. For example:
```
from scipy.signal import hann
w1 = hann(5,True) #array([ 0. ,  0.5,  1. ,  0.5,  0. ])
w2 = hann(5, False) #array([ 0. ,  0.5,  1. ,  0.5,  0. ])
```
I think the cause is the N-1 denominator which is not adjusted for odd lengths when periodic.

I believe this issue was brought up [here](http://lists.ipython.scipy.org/pipermail/numpy-discussion/2014-September/071270.html)

**Comment by FRidh** [comment] 2015-04-27 13:03
I read the discussion and partly the paper that was mentioned. The paper can be found [online](https://www.utdallas.edu/~cpb021000/EE%204361/Great%20DSP%20Papers/Harris%20on%20Windows.pdf). There's also a discussion about this topic [on wikipedia](http://en.wikipedia.org/wiki/Talk:Window_function#DFT-even_vs._Matlab).

There was also a discussion on the Octave [mailing list](http://octave.1599824.n4.nabble.com/discuss-bug-43305-Hamming-etc-windows-are-wrong-td4667944.html#none) and [bug tracker](http://savannah.gnu.org/bugs/?43305).

## Hamming
In the case of the Hamming window, Scipy 0.15.1 hamming function gives the expected result for an even amount of points (this example was brought up on the mailing list):
```py
>>> hamming(8, False)
array([ 0.08      ,  0.21473088,  0.54      ,  0.86526912,  1.        ,
        0.86526912,  0.54      ,  0.21473088])
```
which is different from the `symmetric` case.
```py
>>> hamming(8, True)
array([ 0.08      ,  0.25319469,  0.64235963,  0.95444568,  0.95444568,
        0.64235963,  0.25319469,  0.08      ])
```

## Hann
When we look at odd length windows, then indeed `symmetric` and `periodic` cases windows are the same
```py
>>> hamming(7, True)
array([ 0.08,  0.31,  0.77,  1.  ,  0.77,  0.31,  0.08])
>>> hamming(7, False)
array([ 0.08,  0.31,  0.77,  1.  ,  0.77,  0.31,  0.08])
```

Let's now have a look at the Hann window
```py
>>> hann(6, True)
array([ 0.       ,  0.3454915,  0.9045085,  0.9045085,  0.3454915,  0.       ])
>>> hann(6, False)
array([ 0.  ,  0.25,  0.75,  1.  ,  0.75,  0.25])
>>> hann(5, True)
array([ 0. ,  0.5,  1. ,  0.5,  0. ])
>>> hann(5, False)
array([ 0. ,  0.5,  1. ,  0.5,  0. ])
```

## Cause
The reason the symmetric and periodic windows are the same for even length is because of the lines
```py
    if not sym and not odd:
        M = M + 1
    ...
    if not sym and not odd:
        w = w[:-1]
```
If the `and not odd` condition would be removed then symmetric and periodic windows would be different.

Octave behaves similarly to Scipy. Matlab behaves differently though, 
```matlab
hann(5, 'symmetric')
         0
    0.5000
    1.0000
    0.5000
         0

hann(5, 'periodic')
      0
    0.3455
    0.9045
    0.9045
    0.3455
```

## What's correct?
The question is now, what is the correct behavior?

**Comment by endolith** [comment] 2015-04-27 15:52
Duplicate of https://github.com/scipy/scipy/issues/2190 ?

**Comment by rgommers** [comment] 2015-04-28 20:48
Indeed, thanks @endolith - closing this as a duplicate. Have linked to this issue from gh-2190, because the links here are useful.

**Closed by rgommers** 2015-04-28 20:48 UTC
Labels: scipy.signal

**Comment by rgommers** [comment] 2015-04-28 20:49
The discussion on the Octave bug tracker proposes to just add all possible options and document them properly. Might be a reasonable way to go here as well.

**Comment by endolith** [comment] 2015-04-28 22:43
I think this demonstrates that the current behavior is incorrect:

```
In [19]: abs(fft(hann(8, sym=False)))
Out[19]: array([ 4.,  2.,  0.,  0.,  0.,  0.,  0.,  2.])

In [20]: abs(fft(hann(7, sym=False)))
Out[20]:
array([ 3.        ,  1.82397424,  0.21573417,  0.0397084 ,  0.0397084 ,
        0.21573417,  1.82397424])
```

If the window is periodic, and raised cosine (=Hann), then its frequency spectrum should only have DC + one frequency component.  `hann(8, sym=False)` looks this way, but `hann(7, sym=False)` does not.

**Comment by endolith** [comment] 2015-04-29 01:24
>  just add all possible options

So that would be "MATLAB symmetric", "MATLAB periodic", and "DFT even", as described in [Wikipedia](http://en.wikipedia.org/wiki/Window_function#Symmetry_and_asymmetry)?

But `hann(8, sym=True)` doesn't match any of those plots.  It looks like the "MATLAB symmetric" plot, except it goes to 0 at the ends.

`hann(8, sym=False)` matches the "DFT even" plot.

**Comment by FRidh** [comment] 2015-04-29 06:01
@endolith I think you're right with the test.

I removed the `and not odd` requirement
```
np.abs(np.fft.fft(hann_fix(7, False)))
array([  3.50000000e+00,   1.75000000e+00,   2.30026015e-16,
         1.70955155e-16,   1.70955155e-16,   2.30026015e-16,
         1.75000000e+00])
```
and all that remains is the DC component and the single frequency with its conjugate. 
This is the same result as you would get in Matlab.

**Comment by endolith** [comment] 2015-04-29 23:15
This was added Nov 2001 in https://github.com/scipy/scipy/commit/c910a765560a2edce76e1be8b2a9eead5b434b0d by @teoliphant .  I don't see any explanation of why it was done that way.  

Octave only added this [2 months ago](http://hg.savannah.gnu.org/hgweb/octave/rev/26fb4bfa4193)?

**Comment by FRidh** [comment] 2015-05-03 09:57
Yes, octave-signal has `periodic` since 1.3.1. However, while they mention in their changelog they have now this Matlab-compatible option, the results do not match with Matlab.
