### ISSUE TITLE
Reliability of p-value in scipy.stats.spearman

### ISSUE THREAD

**Issue by Garrafao** [scipy/scipy#7882] opened 2017-09-18 13:36 UTC
Dear scipy developers,

I am puzzled about the following sentence in the documentation of the function calculating Spearman's rank correlation coefficient in the scipy.stats package:

    "The p-values are not entirely reliable but are probably reasonable for datasets larger than 500 or so."

In the beginning, I interpreted the sentence as saying that the p-values are probably reasonable for data sets larger than 500 or so, but not entirely reliable for smaller data sets.

I am puzzled because the main test statistic used in the function assumes a t-distribution. (I'm not sure whether this is the only statistic used, because for certain cases the function switches to mstats_basic.spearmanr seemingly using another test statistic) This seems to be a valid assumption only if the sample size is small as for example mentioned here:

http://www.janda.org/c10/Lectures/topic06/L24-significanceR.htm

My question is, thus, what the justification for the sentence mentioned above could be or whether the sentence is rather meant in a way that could be paraphrased like this:

    For datasets larger than 500 or so the p-values are not entirely reliable but are probably reasonable.

Thanks for your help in advance! I originally posted the question at

https://stats.stackexchange.com/questions/294586/reliability-of-p-value-in-scipy-stats-spearman

but got no answer, so I write here now.

Best,

Dominik

**Comment by josef-pkt** [comment] 2017-09-18 14:10
Wkipedia has the t formula used in spearman as one of the possible versions
https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient#Determining_significance

I don't know what this vague "not entirely reliable" means. (I don't remember ever looking at a comparison for hypothesis tests for spearman's correlation coefficient, and I don't know how good they are in small samples and in cases when the data is not close to normally distributed.)

However, t versus normal is often just a better small sample approximation. Asymptotically, as the number of observations and degrees of freedom go to infinity, the t distribution approaches the normal distribution. So asymptotically it doesn't make a difference. And in many cases asymptotic normality is all we get.
However, in small samples the t-distribution is often a better approximation than the normal distribution. That often relies on monte carlo studies but can be theoretically shown in some special cases or under special assumptions.

**Comment by Garrafao** [comment] 2017-09-28 14:25
Thanks for your answer. What does 'small' mean here? Rather less than 30 or less than 500?

**Comment by josef-pkt** [comment] 2017-09-28 15:02
For t versus normal, I have seen statements in references that the difference between the two is negligible for df >= 100.
However, when I tried that out, then probabilities far out in the tails still have large relative differences, but that would not matter for most cases of hypothesis tests.

e.g. percent difference in tail probability

```
>>> p = 0.05; stats.norm.sf(stats.t.isf(p, 100)) / p - 1 
-0.031326783149837278
>>> p = 1e-5; stats.norm.sf(stats.t.isf(p, 100)) / p - 1
-0.62402445081675884
>>> p = 1e-5; stats.norm.sf(stats.t.isf(p, 1000)) / p - 1
-0.088101161562240016
```
In small samples using t doesn't overreject as much as using the normal in many/several cases. 

```
>>> p = 0.05; stats.norm.sf(stats.t.isf(p, 10)) / p - 1
-0.30085024179414943
>>> p = 0.05; stats.norm.sf(stats.t.isf(p, 20)) / p - 1
-0.15421738248321093
```

But as I said, I don't know specifically about the spearman correlation case.

**Comment by victor-shepardson** [comment] 2017-10-31 16:59
Notably when correlation = 1, pvalue = 0, regardless of sample size. Which for spearman is inaccurate for very small samples, since there is a small finite number of possible rankings.
```
>>> scipy.stats.spearmanr(np.arange(4), np.arange(4))
SpearmanrResult(correlation=1.0, pvalue=0.0)
>>> scipy.stats.spearmanr(np.arange(32), np.arange(32))
SpearmanrResult(correlation=1.0, pvalue=0.0)
>>> scipy.stats.spearmanr(np.arange(512), np.arange(512))
SpearmanrResult(correlation=1.0, pvalue=0.0)
>>>
>>> n = 10000
>>> sum(
... np.abs(scipy.stats.spearmanr(np.random.rand(4), np.random.rand(4)).correlation)>.999999
... for _ in range(n))/n
0.086099999999999996
```

**Comment by rgommers** [comment] 2018-09-02 02:07
In case someone will dive into this one, here's a possibly useful comment from gh-1797 by @josef-pkt :

    scipy\stats\statlib\spearman.f doesn't return prho
    currently not used, but it might give better small sample probabilities for stats.spearmanr
    statlib.prho currently returns only a status code

**Comment by Wrzlprmft** [comment] 2022-03-09 09:12
I might want to tackle this problem by using an exact permutation test for small sample sizes (which could also cover ties) and possibly the Edgeworth series for higher sample sizes. A small thing that should definitely be done is making _p_ values at least 1/n!. I have already implemented something similar [here](https://github.com/BPSB/combine-p-values-discrete/blob/4b76b207f2275fccb5c4eca3bac7ee1a87d113d8/combine_pvalues_discrete/ctr.py#L96).

However, implementing the permutation comes with the problem that it might considerably increase the computation time for large matrices. If this were just a statistical test, I would consider this worth it, but people might compute correlation matrices without caring about the _p_ value. How should we deal with this?

One obvious thing to do is to provide a parameter that governs the threshold of permutation-based computations. Whoever wants just correlation coefficients can just choose the threshold to be zero. However, I don’t think this should be the default value, which might lead to some people facing things suddenly going much slower.

**Comment by mdhaber** [comment] 2022-03-09 14:13
You might find `permutation_test` useful here.

**Comment by Wrzlprmft** [comment] 2022-03-09 14:36
> You might find [`permutation_test`](https://scipy.github.io/devdocs/reference/generated/scipy.stats.permutation_test.html) useful here. I can post the way to call it in an hour or so.

Hmm, as far as I can tell, this does not account for numbers that only differ due to numerical noise, which can lead to considerably wrong results for small sample sizes. It certainly happened to my implementation. Without ties, we might avoid that by using an integer statistics like the covariance without normalisation, however, I don’t see this working with ties, when ranks become non-integer.

> I think the interface should be a `method='exact'` parameter like several other tests. You can have the default be `'auto'` and choose exact or asymptotic (or randomized) based on some criteria (usually just sample size).

I agree. However, we still have to consider that the reasonable default setting can lead to considerable increases in computation time for people who don’t need the _p_ value at all – for example, if somebody wants to compute all pairwise correlations of thousand datasets of size 6. (Mind that I consider this the lesser evil and don’t see a good way to avoid this, but I think it should be on the table.)

**Comment by mdhaber** [comment] 2022-03-09 15:33
In any case here is code for the exact test, adapted from `test_hypotest.py`.

<details>

```python3
from scipy import stats
from scipy.stats import permutation_test
import numpy as np
from numpy.testing import assert_allclose

def test_against_spearmanr_in_R(alternative, expected_pvalue):
    """
    Results above from R cor.test, e.g.

    options(digits=16)
    x <- c(1.76405235, 0.40015721, 0.97873798,
           2.2408932, 1.86755799, -0.97727788)
    y <- c(2.71414076, 0.2488, 0.87551913,
           2.6514917, 2.01160156, 0.47699563)
    cor.test(x, y, method = "spearm", alternative = "t")
    """
    np.random.seed(0)
    x = stats.norm.rvs(size=6)
    y = x + stats.norm.rvs(size=6)

    expected_statistic = 0.7714285714285715

    def statistic1d(x):
        return stats.spearmanr(x, y).correlation

    res = permutation_test((x,), statistic1d, permutation_type='pairings',
                           n_resamples=np.inf, alternative=alternative)

    assert_allclose(res.statistic, expected_statistic, rtol=1e-12)
    assert_allclose(res.pvalue, expected_pvalue, atol=1e-13)

cases = [('less', 0.9708333333333),
         ('greater', 0.05138888888889),
         ('two-sided', 0.1027777777778)]
for case in cases:
    test_against_spearmanr_in_R(*case)
```

</details>

If it sounds good to you, @Garrafao, I'll add a `noise_threshold` (or some other name, to be discussed in the PR) parameter to `permutation_test`, as the idea applies just as well to any statistic.

**Comment by Wrzlprmft** [comment] 2022-03-09 20:57
> I thought about it originally but wasn't sure how users would pick a threshold. I suppose that is statistic-dependent. Do you have a principled way of choosing it for spearman?

For Spearman’s _ρ_, you can only have integer or half-valued ranks (in case of ties). This imposes a clear discretisation of _ρ_ (for a given sample size and ties), which in turn governs the threshold. However, instead of computing how the discretisation affects _ρ,_ it makes more sense to use a different (equivalent) statistics that operates in clear integer steps, namely, the covariance of ranks with a suitable normalisation factor. This would obviate the need for unifying almost identical values since they cannot happen in integer arithmetics.

I expect that something similar is possible for any ranked statistics, while it shouldn’t matter for unranked statistics, as every permutation yields a different value anyway.

However, all of this is for (internal) uses by people who are aware of this problem and take care when transforming a statistics. The average user of `permutation_test` will likely still benefit from the discussed feature. For this case, I think some relative threshold like 100 times the machine precision (10⁻¹⁴) seems reasonable to me since:

* It captures all numerical noise that can possibly happen for small sample sizes.
* When sample sizes become so large that actual values differ by this amount, you have to use a gargantuan number of samples or be very unlucky to actually see an effect and the effect will likely be tiny.
* Something similar applies when sample sizes become so large that the numerical noise can differ by more than this.

> In any case here is code for the exact test, adapted from `test_hypotest.py`.
> 
> If it sounds good to you, @Wrzlprmft, I'll add an `eps` (or `noise_threshold` or some other name, to be discussed in the PR) parameter to `permutation_test`, as the idea applies just as well to any statistic? Or would you like to? Your algorithm for detecting uniqueness looks good (better than, e.g., rounding to the nearest `eps`).

**Comment by mdhaber** [comment] 2022-03-10 14:39
@Wrzlprmft It's generalized to n-sample statistics. From the documentation:

> Note that if a two-sample statistic, for example, does not inherently depend on the order in which observations are provided - only on the pairings of observations - then only one of the two samples should be provided in data. This dramatically reduces computational cost without affecting the shape of the null distribution (because the frequency/count of each value is affected by the same factor).

Note how the example only passes one of the samples in.

**Comment by Wrzlprmft** [comment] 2022-03-10 14:42
> @Wrzlprmft It's generalized to n-sample statistics. From the documentation:
> 
> […]
> 
> Note how the example only passes one of the samples in.

Ah, I missed that. I should read the documentation before the code …

**Comment by mdhaber** [comment] 2022-03-10 14:46
NP. Is it possible to vectorize this and add an `axis` parameter (without expensive explicit loops)?

**Comment by Wrzlprmft** [comment] 2022-03-10 15:04
> Is it possible to vectorize just the statistic calculation (not p-value) and add an `axis` parameter (without expensive explicit loops)?

I boiled down the statistics to `np.sum(x*y)`, which should be very much vectorisable. Everything else is permutation-invariant can be computed in advance.

(Mind that for my own module, I can’t make use of `permutations` because I need all possible *p* values. This is mainly of interest for SciPy itself.)

**Comment by mdhaber** [comment] 2022-03-10 15:07
I see. Did you plan on making a PR or just doing some legwork to help someone who wants to submit one? (Also, what is your module for? Just curious.)

**Comment by mdhaber** [comment] 2022-09-26 06:00
I studied the difference between the exact and approximate p-values for small samples ($n=6$ through $n=10$).
<details>
```python3
import math
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

Ns = list(range(6, 10))

for N in Ns:
    print(N)
    a = np.arange(N)
    b = a
    
    def statistic(b):
        r = stats.spearmanr(a, b).statistic
        t = r*np.sqrt((N-2)/(1-r**2))
        return t
    
    res = stats.permutation_test((b,), statistic, permutation_type='pairings', 
                                 n_resamples=math.factorial(N))
    
    x = res.null_distribution
    cdf = stats.t(N-2).cdf
    n = len(x)
    x0 = np.sort(np.unique(x))
    y0 = np.array([(x <= xi).sum() for xi in x0]) / n
    y = cdf(x0)
    plt.step(y, y-y0)
    
    # We were not careful to account for possible roundoff error
    # Show that this is OK
    diff = np.diff(y0)
    assert(np.min(diff) > 1e-10)
    
plt.xlabel("Approximate p-value")
plt.ylabel("Error in Approximate p-value")
plt.title(f"Error in KS-test p-value Approximation, N={N}")
plt.legend([f"N={N}" for N in Ns])
```
</details>
![image](https://user-images.githubusercontent.com/6570539/192203843-ae8f9428-5ed5-43e2-8256-75b63fbf4361.png)

It looks like the approximate p-value provided by `spearmanr` is always too small, but (if the trend holds) not by more than 0.005 for (approximate) p-values less than 0.2 for samples with 9 or more observations.

**Comment by ilayn** [comment] 2023-06-12 09:39
I am converting the statslib functions from Fortran to Cython. But I have no idea what they are used for. I found the `gscale` function used in `_ABW` class and `swilk` in `shapiro` but `prho` seems like not used. 

Should I delete it or should I make it such that it returns prho value?

**Comment by rgommers** [comment] 2023-06-12 09:42
`prho` wasn't public and a deprecation warning has been emitted since 1.8.0, so if the test suite passes without it, let's delete it I'd say.

**Comment by mdhaber** [comment] 2024-08-15 17:51
This part of the documentation has been rephrased:

> Although calculation of the p-value does not make strong assumptions about the distributions underlying the samples, it is only accurate for very large samples (>500 observations). For smaller sample sizes, consider a permutation test (see Examples section below).

and the example shows how to perform the permutation test. I'd be happy to add a `method` argument that will do the permutation test automatically if there's a reviewer.

Also, part of the OP's concern was that the sentence might mean:
> For datasets larger than 500 or so the p-values are not entirely reliable but are probably reasonable.

This was probably based on:
![image](https://github.com/user-attachments/assets/8112199c-ac7c-4f3b-8afa-ea21f3a0d952)

from the [linked reference](http://www.janda.org/c10/Lectures/topic06/L24-significanceR.htm). If the normal distribution is valid for large $N$, then the t distribution is also valid for large $N$ because the t distribution approaches the normal distribution as the number of degrees of freedom increases. So I don't think that is what was intended. 

It looks like it was just a standard caution against using p-values based on an asymptotic approximation when the sample size is small. It would benefit from a reference, but I think it's better to leave in this sort of caution than to remove it, so I'll go ahead and close this.

**Closed by mdhaber** 2024-08-15 17:51 UTC
Labels: scipy.stats, enhancement
