### ISSUE TITLE
scipy.ndimage.morphology.binary_opening is waaaaaaay slower than cv2.morphologyEx

### ISSUE THREAD

**Issue by bennlich** [scipy/scipy#5333] opened 2015-10-07 20:36 UTC
Roughly, for a 15000 x 5000 image with a `skimage.morphology.disk` structuring element of radius 17, `scipy.ndimage.morphology.binary_opening` takes ~80s, whereas `cv2.morphologyEx` takes ~6s.

Maybe this is expected? I don't know much about how scipy and opencv differ under the hood. If this is unexpected, I can provide some code to test.

**Comment by pv** [comment] 2015-10-08 07:56
Some differences:

- Opencv morphology operations are AFAIK parallelized, and can use multiple cpus (scipy.ndimage does not).
- I'm not sure if opencv deals with N-d images or only 2D; if the latter, that may explain why ndimage is slower.

But obviously, there is room for optimization in scipy.ndimage.

**Comment by rgommers** [comment] 2015-10-09 18:46
@bennlich the experts live on the scikit-image mailing list, I suggest to ask them. I suspect they'll tell you that 10x difference isn't unexpected given what @pv lists above though.

**Comment by bennlich** [comment] 2015-10-09 20:11
Thanks, @rgommers. Is this the mailing list you're thinking of: https://groups.google.com/forum/#!forum/scikit-image ?

If it does have something to do with cv2 being 2D-only, it might be worth implementing some 2D morphology functions somewhere in scikit-image. 10x speed-up seems like a lot to me just for a bit of parallelization.

**Comment by rgommers** [comment] 2015-10-09 20:21
@bennlich indeed, that's the list. 

Simple parallellization gets you ~4x probably, so a factor ~2.5 from more highly optimized code in OpenCV (which has a heavy focus on performance) would not be very strange....

**Comment by bennlich** [comment] 2015-10-10 05:56
Kk @rgommers. I just made a post over there. I'll report back.

**Comment by JDWarner** [comment] 2015-10-10 07:48
For reference, @bennlich, it would be useful to know how many cores were available on your test system which noted a factor of 13 decrease in execution time.

**Comment by bennlich** [comment] 2015-10-12 17:16
@JDWarner Right! I was running on an amazon ec2 r3.large instance, which has 2 "vCPU"s. Unfortunately, it's a little bit unclear to me if that means two cores or two hyperthreads. I think in this case it means two cores, but I'm not positive.

**Comment by juliantaylor** [comment] 2015-10-13 15:31
opencv beats it by this factor also with one thread, the code is just poorly optimized/generic.
just removing one unnecessary break already gain you up to 25% in runtime. Though to get to the factor 10 more work is required, (specialization for contiguous data, moving border handling out of the loop, ...)

**Comment by rgommers** [comment] 2019-08-10 23:24
there are many functions in `ndimage` and other modules that could be optimized for performance. ever a work in progress, and PRs always welcome. since this is not a bug, I'll close it. thanks all

**Closed by rgommers** 2019-08-10 23:24 UTC
Labels: query, scipy.ndimage
