### ISSUE TITLE
BUG: Regression in `main` creating sparse matrix from float16 raises ValueError: Output dtype not compatible with inputs.

### ISSUE THREAD

**Issue by lesteve** [scipy/scipy#20200] opened 2024-03-06 14:05 UTC
### Describe your issue.

There seems to be a regression in `main` where creating a sparse matrix from a float16 array raises `ValueError: Output dtype not compatible with inputs.`. This was noticed in scikit-learn CI.

The snippet below works fine with scipy 1.12.0.

### Reproducing Code Example

```python
import numpy as np
from scipy.sparse import csc_matrix

csc_matrix(np.array([[1], [2]]), dtype=np.float16)
```

### Error message

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 4
      1 import numpy as np
      2 from scipy.sparse import csc_matrix
----> 4 csc_matrix(np.array([[1], [2]]), dtype=np.float16)

File ~/micromamba/envs/scikit-learn-scipy-dev/lib/python3.12/site-packages/scipy/sparse/_compressed.py:88, in _cs_matrix.__init__(self, arg1, shape, dtype, copy)
     86         raise ValueError(msg) from e
     87     coo = self._coo_container(arg1, dtype=dtype)
---> 88     arrays = coo._coo_to_compressed(self._swap)
     89     self.indptr, self.indices, self.data, self._shape = arrays
     91 # Read matrix dimensions given, if any

File ~/micromamba/envs/scikit-learn-scipy-dev/lib/python3.12/site-packages/scipy/sparse/_coo.py:366, in _coo_base._coo_to_compressed(self, swap)
    363 indices = np.empty_like(minor, dtype=idx_dtype)
    364 data = np.empty_like(self.data, dtype=self.dtype)
--> 366 coo_tocsr(M, N, nnz, major, minor, self.data, indptr, indices, data)
    367 return indptr, indices, data, self.shape

ValueError: Output dtype not compatible with inputs.
```

### SciPy/NumPy/Python version and system information

```shell
1.13.0.dev0+1449.5fd8c5a 2.0.0.dev0+git20240305.8b0bc6d sys.version_info(major=3, minor=12, micro=1, releaselevel='final', serial=0)
/home/lesteve/micromamba/envs/scikit-learn-scipy-dev/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.9",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.15.0",
      "include directory": "../../opt/python/cp312-cp312/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.11.1",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/opt/python/cp312-cp312/bin/python",
    "version": "3.12"
  }
}
```

**Comment by perimosocordiae** [comment] 2024-03-07 01:18
@dschult from the traceback it seems like this may be related to gh-19962. I haven't done a close look into it yet.

**Comment by perimosocordiae** [comment] 2024-03-07 01:25
The root cause of the issue is that our sparsetools native code isn't compiled to support float16 dtypes. See gh-7408 for the detailed discussion of why that is.

This implies that the changes in gh-19962 caused the CSC constructor to invoke a sparsetools routine where previously they would not. Since float16 isn't a supported dtype, I'm inclined to mark this as a "won't fix" issue.

There's probably more we could do to validate dtypes at construction time, but we can address that in a separate issue.

**Closed by perimosocordiae** 2024-03-07 01:25 UTC
Labels: defect, scipy.sparse
