### ISSUE TITLE
BUG: interpolate.griddata: memory leak in linear mode under Python 3.12

### ISSUE THREAD

**Issue by TimoRoth** [scipy/scipy#20917] opened 2024-06-06 21:25 UTC
### Describe your issue.

When running a particular test in our testsuite, specifically under python 3.12, its memory use balloons up to 16GB, while it barely needs 1~2GB under any older Python version.
It's sadly relatively inconclusive, but with all kinds of memory leak testers/profilers, everything points at the griddata interpolation function. Particularly this instance: https://github.com/OGGM/oggm/blob/7489be15c644b54c5f20501c38e654a47c63c53c/oggm/core/gis.py#L797

I was unable to produce any minimal example on how to reproduce this, it only happens in our entire framework of libraries, which makes it really hard to pinpoint down what is leaking where here.

I have already tried running this against the latest 1.14.x branch, since there was a memory leak fixed there recently.
No change in memory balooning behaviour though compared to latest 1.13 version.
I've also tried the binary wheels from pypi vs. our self-compiled version. Both leak in the same way.

I have packaged this all up into a docker image, which is available here, with instructions on how to trigger the issue:
https://hub.docker.com/repository/docker/timoroth/oggm-latest-dev-debug/general
The python version in there is built in debug mode, so pytest-leaks works.
The likely culprit is linked above already.

One interesting and concerning thing I noticed when running this with pytest-leaks in action:
At the end, it exits with the following assertion:
```
test_merge_simulated_thickness: leaked references: [233775], memory blocks: [136886], file descriptors: [7]
...../include/python3.12d/object.h:798: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x7fc6e830f650 is freed>
```

Like stated before, this really _only_ happens when running under python 3.12. The memory behaviour under python 3.11 or older is absolutely tame.
If you want to verify, run the same reproducer from the Docker-Hub image in this docker image: `ghcr.io/oggm/untested_base:py3.11`

### Reproducing Code Example

```python
See above, sadly I've so far been unable to find any minimal reproducer for this.
```

### Error message

```shell
None, if the machine has enough RAM, the test runs to completion successfully.
However, the memory is never released until the python process exits.
When testing for leaks with pytest-leaks, it exits with an assertion about a negative ref count at the very end, after completing the test runs.
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.14.0rc2.dev0+1360.67d743e 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/include/x86_64-linux-gnu/openblas-pthread/
    lib directory: /usr/lib/x86_64-linux-gnu/openblas-pthread/
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS=
      NO_LAPACK= NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 generic MAX_THREADS=64
    pc file directory: /usr/lib/x86_64-linux-gnu/pkgconfig
    version: 0.3.20
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/include/x86_64-linux-gnu/openblas-pthread/
    lib directory: /usr/lib/x86_64-linux-gnu/openblas-pthread/
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS=
      NO_LAPACK= NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 generic MAX_THREADS=64
    pc file directory: /usr/lib/x86_64-linux-gnu/pkgconfig
    version: 0.3.20
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 11.4.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 11.4.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 11.4.0
  pythran:
    include directory: ../../pip-build-env-t7ypm4mq/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /usr/local/pyenv/versions/3.12-dev-debug/bin/python3.12
  version: '3.12'
```

**Comment by nickodell** [comment] 2024-06-07 01:16
It seems like most of the memory growth happens while `reproject_gridded_data_variable_to_grid` is running. That could potentially still implicate SciPy, though, since it uses Salem to reproject, and that reprojection uses a RegularGridInterpolator.

**Comment by TimoRoth** [comment] 2024-06-07 12:25
The reason I report this here is that I ran this through https://pypi.org/project/memory-profiler/ and got this result:

<details>

```
Filename: /root/oggm/oggm/core/gis.py

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
   747    398.0 MiB    398.0 MiB           1   @entity_task(log, writes=['gridded_data'])
   748                                         @profile
   749                                         def process_dem(gdir=None, grid=None, fpath=None, output_filename=None):
   750                                             """Reads the DEM from the tiff, attempts to fill voids and apply smooth.
   751
   752                                             The data is then written to `gridded_data.nc`.
   753
   754                                             Parameters
   755                                             ----------
   756                                             gdir : :py:class:`oggm.GlacierDirectory`
   757                                                 Where to write the data. If set it overrules grid and fpath.
   758                                             grid : :py:class:`salem.gis.Grid`
   759                                                 Grid of the DEM file. Needed if gdir is not provided.
   760                                             fpath : str
   761                                                 The filepath of the DEM file. Needed if gdir is not provided.
   762                                             output_filename : str
   763                                                 The filename of the nc file to add the DEM to. Defaults to gridded_data
   764                                             """
   765    398.0 MiB      0.0 MiB           1       if gdir is not None:
   766                                                 # open srtm tif-file:
   767                                                 dem = read_geotiff_dem(gdir)
   768                                                 # Grid
   769                                                 dem_grid = gdir.grid
   770                                                 grid_name = gdir.rgi_id
   771                                             else:
   772    398.0 MiB      0.0 MiB           1           if grid is None or fpath is None:
   773                                                     raise InvalidParamsError('If you do not provide a gdir you must'
   774                                                                              'define grid and fpath! Given grid='
   775                                                                              f'{grid} and fpath={fpath}.')
   776    398.0 MiB      0.0 MiB           1           dem = read_geotiff_dem(fpath=fpath)
   777    398.0 MiB      0.0 MiB           1           grid_name = 'custom_grid'
   778    398.0 MiB      0.0 MiB           1           dem_grid = grid
   779    398.0 MiB      0.0 MiB           1           diagnostics_dict = dict()
   780                                             # Grid parameters
   781    398.0 MiB      0.0 MiB           1       nx = dem_grid.nx
   782    398.0 MiB      0.0 MiB           1       ny = dem_grid.ny
   783    398.0 MiB      0.0 MiB           1       dx = dem_grid.dx
   784    399.1 MiB      1.0 MiB           1       xx, yy = dem_grid.ij_coordinates
   785
   786                                             # Correct the DEM
   787    399.1 MiB      0.0 MiB           1       valid_mask = np.isfinite(dem)
   788    399.1 MiB      0.0 MiB           1       if np.all(~valid_mask):
   789                                                 raise InvalidDEMError('Not a single valid grid point in DEM')
   790
   791    399.1 MiB      0.0 MiB           1       if np.any(~valid_mask):
   792                                                 # We interpolate
   793    399.1 MiB      0.0 MiB           1           if np.sum(~valid_mask) > (0.25 * nx * ny) and gdir is not None:
   794                                                     log.info('({}) more than 25% NaNs in DEM'.format(gdir.rgi_id))
   795    401.6 MiB      2.5 MiB           1           pnan = np.nonzero(~valid_mask)
   796    407.4 MiB      5.8 MiB           1           pok = np.nonzero(valid_mask)
   797    418.8 MiB     11.4 MiB           1           points = np.array((np.ravel(yy[pok]), np.ravel(xx[pok]))).T
   798    418.8 MiB      0.0 MiB           1           inter = np.array((np.ravel(yy[pnan]), np.ravel(xx[pnan]))).T
   799    418.8 MiB      0.0 MiB           1           try:
   800   1033.4 MiB    614.6 MiB           2               dem[pnan] = griddata(points, np.ravel(dem[pok]), inter,
   801    418.8 MiB      0.0 MiB           1                                    method='linear')
   802                                                 except ValueError:
   803                                                     raise InvalidDEMError('DEM interpolation not possible.')
   804   1033.4 MiB      0.0 MiB           1           if gdir is not None:
   805                                                     log.info(gdir.rgi_id + ': DEM needed interpolation.')
   806                                                     gdir.add_to_diagnostics('dem_needed_interpolation', True)
   807                                                     gdir.add_to_diagnostics('dem_invalid_perc',
   808                                                                             len(pnan[0]) / (nx * ny))
   809                                                 else:
   810   1033.4 MiB      0.0 MiB           1               diagnostics_dict['dem_needed_interpolation'] = True
   811   1033.4 MiB      0.0 MiB           1               diagnostics_dict['dem_invalid_perc'] = len(pnan[0]) / (nx * ny)
   812
   813   1033.4 MiB      0.0 MiB           1       isfinite = np.isfinite(dem)
   814   1033.4 MiB      0.0 MiB           1       if np.any(~isfinite):
   815                                                 # interpolation will still leave NaNs in DEM:
   816                                                 # extrapolate with NN if needed (e.g. coastal areas)
   817   1033.4 MiB      0.0 MiB           1           pnan = np.nonzero(~isfinite)
   818   1033.4 MiB      0.0 MiB           1           pok = np.nonzero(isfinite)
   819   1033.4 MiB      0.0 MiB           1           points = np.array((np.ravel(yy[pok]), np.ravel(xx[pok]))).T
   820   1033.4 MiB      0.0 MiB           1           inter = np.array((np.ravel(yy[pnan]), np.ravel(xx[pnan]))).T
   821   1033.4 MiB      0.0 MiB           1           try:
   822   1033.4 MiB      0.0 MiB           2               dem[pnan] = griddata(points, np.ravel(dem[pok]), inter,
   823   1033.4 MiB      0.0 MiB           1                                    method='nearest')
   824                                                 except ValueError:
   825                                                     raise InvalidDEMError('DEM extrapolation not possible.')
   826   1033.4 MiB      0.0 MiB           1           if gdir is not None:
   827                                                     log.info(gdir.rgi_id + ': DEM needed extrapolation.')
   828                                                     gdir.add_to_diagnostics('dem_needed_extrapolation', True)
   829                                                     gdir.add_to_diagnostics('dem_extrapol_perc',
   830                                                                             len(pnan[0]) / (nx * ny))
   831                                                 else:
   832   1033.4 MiB      0.0 MiB           1               diagnostics_dict['dem_needed_extrapolation'] = True
   833   1033.4 MiB      0.0 MiB           1               diagnostics_dict['dem_extrapol_perc'] = len(pnan[0]) / (nx * ny)
   834
   835   1033.4 MiB      0.0 MiB           1       if np.min(dem) == np.max(dem):
   836                                                 raise InvalidDEMError('({}) min equal max in the DEM.'
   837                                                                       .format(grid_name))
   838
   839                                             # Clip topography to 0 m a.s.l.
   840   1033.4 MiB      0.0 MiB           1       if cfg.PARAMS['clip_dem_to_zero']:
   841   1033.4 MiB      0.0 MiB           1           utils.clip_min(dem, 0, out=dem)
   842
   843                                             # Smooth DEM?
   844   1033.4 MiB      0.0 MiB           1       if cfg.PARAMS['smooth_window'] > 0.:
   845   1033.4 MiB      0.0 MiB           1           gsize = np.rint(cfg.PARAMS['smooth_window'] / dx)
   846   1033.4 MiB      0.0 MiB           1           smoothed_dem = gaussian_blur(dem, int(gsize))
   847                                             else:
   848                                                 smoothed_dem = dem.copy()
   849
   850                                             # Clip topography to 0 m a.s.l.
   851   1033.4 MiB      0.0 MiB           1       if cfg.PARAMS['clip_dem_to_zero']:
   852   1033.4 MiB      0.0 MiB           1           utils.clip_min(smoothed_dem, 0, out=smoothed_dem)
   853
   854   1033.4 MiB      0.0 MiB           1       if gdir is None:
   855   1033.4 MiB      0.0 MiB           2           with open(os.path.join(fpath, 'dem_diagnostics.json'), 'w') as f:
   856   1033.4 MiB      0.0 MiB           1               json.dump(diagnostics_dict, f)
   857
   858                                             # Write to file
   859   1033.4 MiB      0.0 MiB           3       with GriddedNcdfFile(gdir=gdir, grid=dem_grid, fpath=fpath,
   860   1033.4 MiB      0.0 MiB           2                            basename=output_filename, reset=True) as nc:
   861
   862   1033.4 MiB      0.0 MiB           1           v = nc.createVariable('topo', 'f4', ('y', 'x',), zlib=True)
   863   1033.4 MiB      0.0 MiB           1           v.units = 'm'
   864   1033.4 MiB      0.0 MiB           1           v.long_name = 'DEM topography'
   865   1033.4 MiB      0.0 MiB           1           v[:] = dem
   866
   867   1033.4 MiB      0.0 MiB           1           v = nc.createVariable('topo_smoothed', 'f4', ('y', 'x',), zlib=True)
   868   1033.4 MiB      0.0 MiB           1           v.units = 'm'
   869   1033.4 MiB      0.0 MiB           2           v.long_name = ('DEM topography smoothed with radius: '
   870   1033.4 MiB      0.0 MiB           1                          '{:.1} m'.format(cfg.PARAMS['smooth_window']))
   871   1033.4 MiB      0.0 MiB           1           v[:] = smoothed_dem
   872
   873                                                 # If there was some invalid data store this as well
   874   1033.4 MiB      0.0 MiB           1           v = nc.createVariable('topo_valid_mask', 'i1', ('y', 'x',), zlib=True)
   875   1033.4 MiB      0.0 MiB           1           v.units = '-'
   876   1033.4 MiB      0.0 MiB           1           v.long_name = 'DEM validity mask according to geotiff input (1-0)'
   877   1033.4 MiB      0.0 MiB           1           v[:] = valid_mask.astype(int)
   878
   879                                                 # add some meta stats and close
   880   1033.4 MiB      0.0 MiB           1           nc.max_h_dem = np.nanmax(dem)
   881   1033.4 MiB      0.0 MiB           1           nc.min_h_dem = np.nanmin(dem)
```

</details>

One function up, in merge_gridded_data, these extra ~600MB are accumulated multiple times, in total ending up with +6GB.

I've also ran this same profiling on Python 3.11, and it makes a similar allocation, but the difference is that it's near immediately freed again.
While on 3.12, that memory sticks around forever now, and is never freed.

When extending this profiling further, it just points at this line: https://github.com/scipy/scipy/blob/maintenance/1.14.x/scipy/interpolate/_ndgriddata.py#L323
After which, all code is .pyx, which cannot be profiled like this.

My very superficial guess as to what's happening is something, somewhere decreases a ref counter one too many times, either for some reason only on Python 3.12, or for some reason only Py3.12 is bothered by it.
Based on the assertion pytest-leaks throws.

**Comment by ev-br** [comment] 2024-06-07 12:42
OK, so it's not a memory leak in some C function from scipy, it's that python in general does not guarantee when things are deallocated, and python 3.12 does something differently from previous versions. 

Not sure how much scipy can do here.
To double-check:

- can you try replacing the `griddata` call with a direct call to LinearNDInterpolator (see the griddata source: it's a very thin wrapper).
- does the behavior (with LinearNDInterpolator) depend on the scipy version? E.g., if you downgrade to scipy 1.12 or something like that, is there a change?

**Comment by TimoRoth** [comment] 2024-06-07 13:18
I'm not sure what it is, but Python is at least aware of the memory in some shape or form. Not sure if it'd account for a stray malloc in some C-Code.
But the fact that it's this different between 3.11 and 3.12 does strongly hint at it being Python-related for sure.

So far I have tried 1.13.x and 1.14.x. The behaviour is the same there. I have not tried 1.12.x yet, and older versions don't support Py3.12 I think.

I have already tried littering the code with calls to gc.collect(). It changed nothing.

Will try directly calling LinearNDInterpolator and on 1.12.x shortly.

**Comment by ev-br** [comment] 2024-06-07 14:09
Just to make sure, when you say you tried 1.14, the version you tried included https://github.com/scipy/scipy/pull/20404, right? If unsure, retry with the current main or a nightly wheel from https://anaconda.org/scientific-python-nightly-wheels/scipy/files.

> after one test is done, its memory should get GC'd

I don't believe the timing is guaranteed by python VM though.

So from the scipy side I'd suggest working out two possibilities:
- the cython changes from gh-20404 : it should improve memory consumption which went up in  https://github.com/scipy/scipy/pull/18376;
- using LinearNDInterpolator instead of griddata:

```
interp = LinearNDInterpolator(...)
values = interp(....)
```

If this does not help by itself, try adding an explicit `del interp`.

The guess here is that what happens is that the 600mb that `memory_profiler` shows is the `interp` object and something keeps a reference to, thus keeping it for longer than strictly necessary.

Like you said, it's technically possible that there is a genuine stray malloc somewhere; the fact that the problem only shows under python 3.12 and not 3.11 makes other reasons more likely.

**Comment by TimoRoth** [comment] 2024-06-07 17:06
> Just to make sure, when you say you tried 1.14, the version you tried included #20404, right? If unsure, retry with the current main or a nightly wheel from https://anaconda.org/scientific-python-nightly-wheels/scipy/files.

Yes, I explicitly tested 1.14 because of that PR. (See version info in initial report)
I also ran the Benchmark it included (in a loop). It does not leak, but shows a normal GC pattern of ramping up in memory, until the GC kicks in and cleans up.

I also ran that test against 1.13, and unsurprisingly, memory consumption quickly ran out of control.

> > after one test is done, its memory should get GC'd
> 
> I don't believe the timing is guaranteed by python VM though.

Definitely not, but it should be sooner than never/before the OS takes care of it via OOM kill.

> So from the scipy side I'd suggest working out two possibilities:
> 
>     * the cython changes from [BUG: interpolate: fix high memory usage for 2 classes #20404](https://github.com/scipy/scipy/pull/20404) : it should improve memory consumption which went up in  [ENH: CloughTocher2DInterpolator multiple times with different values #18376](https://github.com/scipy/scipy/pull/18376);

I tested this with latest 1.13, and the HEAD of the 1.14.x maintenance branch.
They both show the exact same memory consumption and leaky behaviour, almost down to individual bytes-sizes of allocations.

>     * using LinearNDInterpolator instead of griddata:
> 
> 
> ```
> interp = LinearNDInterpolator(...)
> values = interp(....)
> ```
> 
> If this does not help by itself, try adding an explicit `del interp`.
> 
> The guess here is that what happens is that the 600mb that `memory_profiler` shows is the `interp` object and something keeps a reference to, thus keeping it for longer than strictly necessary.

I'll try those in my next round of tests and report here.

> Like you said, it's technically possible that there is a genuine stray malloc somewhere; the fact that the problem only shows under python 3.12 and not 3.11 makes other reasons more likely.

The wildest guess I have is something, somewhere not managing reference counts correctly.
And Python 3.12 introduces the new concept of "Immortal Objects", which are signaled by a magical refcount.
Though it's unlikely it'd hit that magic number by just decref'ing one too many times.

**Comment by TimoRoth** [comment] 2024-06-07 20:39
One thing to correct myself on:
```
/usr/local/pyenv/versions/3.12-dev-debug/include/python3.12d/object.h:798: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x7f3d68875f80 is freed>
Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: finalizing (tstate=0x00007f3e88b692a8)
```

This also happens without pytest-leaks, just purely by running the test to completion on a debug build of python 3.12.

When directly calling LinearNDInterpolator, not much changes:
```
   800    429.7 MiB      0.0 MiB           1           try:
   801    429.7 MiB      0.0 MiB           1               inputval = np.ravel(dem[pok])
   802   1101.8 MiB    672.1 MiB           1               ip = LinearNDInterpolator(points, inputval, fill_value=np.nan, rescale=False)
   803   1105.8 MiB      4.0 MiB           1               ipr = ip(inter)
   804   1105.8 MiB      0.0 MiB           1               dem[pnan] = ipr
   805                                                 except ValueError:
   806                                                     raise InvalidDEMError('DEM interpolation not possible.')
   807   1105.8 MiB      0.0 MiB           1           if gdir is not None:
   808                                                     log.info(gdir.rgi_id + ': DEM needed interpolation.')
   809                                                     gdir.add_to_diagnostics('dem_needed_interpolation', True)
   810                                                     gdir.add_to_diagnostics('dem_invalid_perc',
   811                                                                             len(pnan[0]) / (nx * ny))
   812                                                 else:
   813   1105.8 MiB      0.0 MiB           1               diagnostics_dict['dem_needed_interpolation'] = True
   814   1105.8 MiB      0.0 MiB           1               diagnostics_dict['dem_invalid_perc'] = len(pnan[0]) / (nx * ny)
   815
   816   1105.8 MiB      0.0 MiB           1       isfinite = np.isfinite(dem)
```

This is the same log with scipy downgraded to the 1.13.1 binary wheel from pypi:
```
   800    517.7 MiB      0.0 MiB           1           try:
   801    517.7 MiB      0.0 MiB           1               inputval = np.ravel(dem[pok])
   802   1187.1 MiB    669.4 MiB           1               ip = LinearNDInterpolator(points, inputval, fill_value=np.nan, rescale=False)
   803   1187.1 MiB      0.0 MiB           1               ipr = ip(inter)
   804   1187.1 MiB      0.0 MiB           1               dem[pnan] = ipr
   805                                                 except ValueError:
   806                                                     raise InvalidDEMError('DEM interpolation not possible.')
   807   1187.1 MiB      0.0 MiB           1           if gdir is not None:
   808                                                     log.info(gdir.rgi_id + ': DEM needed interpolation.')
   809                                                     gdir.add_to_diagnostics('dem_needed_interpolation', True)
   810                                                     gdir.add_to_diagnostics('dem_invalid_perc',
   811                                                                             len(pnan[0]) / (nx * ny))
   812                                                 else:
   813   1187.1 MiB      0.0 MiB           1               diagnostics_dict['dem_needed_interpolation'] = True
   814   1187.1 MiB      0.0 MiB           1               diagnostics_dict['dem_invalid_perc'] = len(pnan[0]) / (nx * ny)
   815
   816   1187.1 MiB      0.0 MiB           1       isfinite = np.isfinite(dem)
```

I also tried downgrading to 1.12.0 this time, and the results are practically identical to the 1.13.1 results.

With a `del` thrown in there, nothing changes either:

```
   800    581.8 MiB      0.0 MiB           1           try:
   801    581.8 MiB      0.0 MiB           1               inputval = np.ravel(dem[pok])
   802   1188.2 MiB    606.4 MiB           1               ip = LinearNDInterpolator(points, inputval, fill_value=np.nan, rescale=False)
   803   1188.2 MiB      0.0 MiB           1               ipr = ip(inter)
   804   1188.2 MiB      0.0 MiB           1               del ip
   805   1188.2 MiB      0.0 MiB           1               dem[pnan] = ipr
   806                                                 except ValueError:
   807                                                     raise InvalidDEMError('DEM interpolation not possible.')
   808   1188.2 MiB      0.0 MiB           1           if gdir is not None:
   809                                                     log.info(gdir.rgi_id + ': DEM needed interpolation.')
   810                                                     gdir.add_to_diagnostics('dem_needed_interpolation', True)
   811                                                     gdir.add_to_diagnostics('dem_invalid_perc',
   812                                                                             len(pnan[0]) / (nx * ny))
   813                                                 else:
   814   1188.2 MiB      0.0 MiB           1               diagnostics_dict['dem_needed_interpolation'] = True
   815   1188.2 MiB      0.0 MiB           1               diagnostics_dict['dem_invalid_perc'] = len(pnan[0]) / (nx * ny)
   816
   817   1188.2 MiB      0.0 MiB           1       isfinite = np.isfinite(dem)
```

The more I look at this, the more it seems like the GC has been completely short-circuited or something.
When I run the same kind of tests under python 3.11, there is the occasional line with a negative memory delta, indicating that the GC ran in the meantime.
But on 3.12, there are only 0 or positive numbers, with the VERY rare small negative number, likely caused by native code doing something.

**Comment by ev-br** [comment] 2024-06-08 07:49
OK, this is starting to look like a refcounting error somewhere indeed. The next step to find where this _somewhere_ is to trim down the reproducer. Does it fail if you take pytest out of the equation and run a standalone script? If you trim it down to just calling LinearNDInterpolator with canned data?

**Comment by fancidev** [comment] 2024-06-08 12:39
Not sure if it might be related to [this comment](https://github.com/python/cpython/issues/109602#issuecomment-1733771118) which mentions a recent (Sep 2023) Cython bug when used with Python 3.12

**Comment by TimoRoth** [comment] 2024-06-08 13:20
That bug should long be fixed though, and I'm relatively certain that I built everything with latest stable cython, which should have the fix.
What I'd like to stress is: _nothing_ seems to be getting GC'd anymore. The graph of memory usage only knows one way over the entire runtime: up, it never goes down once.
So I'm not even sure if this really is scipy, or scipy is just the most visible victim of something else royally messing up the GC.
That would also explain why I've so far been completely unable to create any kind of minimal reproducer for this.
Every time I try to extract parts of this process with canned data, it works as expected.

**Comment by ev-br** [comment] 2024-09-13 07:03
@TimoRoth any luck further chasing down this issue?

**Comment by TimoRoth** [comment] 2024-09-13 11:57
Negative, but I recently verified it's still happening.
And it is not happening when using conda packages, which makes it all the more mysterious.

**Comment by TimoRoth** [comment] 2024-10-10 19:15
I don't know what got updated where, but in a fresh venv with everything fully updated, I am now unable to reproduce this on python 3.12 and 3.13. I don't know what fixed it, let alone what caused it.
Bit unsatisfying, but at least it works now, and we're not indefinitely stuck on 3.11.

**Comment by ev-br** [comment] 2024-10-25 09:33
> in a fresh venv with everything fully updated, I am now unable to reproduce this on python 3.12 and 3.13.

So to double-check: once you use a fresh venv, there is no memory leak?
Meaning the OP was indeed some unfortunate glitch of unknown origin, and all is well unless that specific venv is used.
If so, we can declare that the balance is restored in the force and close this issue as a one-off.
Do feel free to discuss further and please reopen if the problem persists.

**Closed by ev-br** 2024-10-25 09:33 UTC
Labels: defect, scipy.interpolate

**Comment by TimoRoth** [comment] 2024-10-25 11:02
Yeah, some update of something must have fixed this.
I still have an environment with the issue stashes away as docker image, so I could slowly travel through time with it, and see which update fixes it. But so far I didn't have the motivation to do so. I'm just glad we're not stuck on 3.11.
