### ISSUE TITLE
BUG: brew not finding mesonpy

### ISSUE THREAD

**Issue by gregdelozier** [scipy/scipy#16974] opened 2022-09-07 03:52 UTC
### Describe your issue.

Installing SciPy in MacOS Big Sur using brew installation of Python 3.10.6, failing on 

```
"/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'
```

(Complete trace below)

I have read the issues below and perhaps I have missed something. I've also checked some possibilities (e.g. manual installation of Meson, etc.) but despite reasonable experience with Python, this one seems to be eluding me. 

I'd be grateful for any suggestions or direction. 

Thanks!

### Reproducing Code Example

```python
$ pip3 install scipy
```

### Error message

```shell
$ pip3 install scipy
Collecting scipy
  Using cached scipy-1.9.1.tar.gz (42.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 68, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 685, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'
```

### SciPy/NumPy/Python version information

>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info) Traceback (most recent call last):   File "<stdin>", line 1, in <module> ModuleNotFoundError: No module named 'scipy' >>>  >>> import sys, numpy; print(numpy.__version__, sys.version_info) 1.23.2 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0) >>>

**Comment by eli-schwartz** [comment] 2022-09-07 04:47
This is interesting... `pip3 install scipy` is downloading an sdist, which has a pyproject.toml specifying:
```toml
[build-system]
build-backend = 'mesonpy'
requires = [
    "meson-python>=0.8.1",  # we need more fixes in meson-python, so no upper bound now
[....]
```

and then inside `get_requires_for_build_wheel()` (this is all pip internal code) it tries to import that build-backend, but fails because `No module named 'mesonpy'`.

I'm not really sure how something like this would ever happen, because pip should be installing the build-system.requires first... it seems like this should be a pip issue if anything.

What's your version of pip?

**Comment by eli-schwartz** [comment] 2022-09-07 04:48
A quick look through the pip bugtracker pointed me at this, which sounds a lot like your issue: https://github.com/pypa/pip/issues/11275

**Comment by gregdelozier** [comment] 2022-09-07 08:02
> This is interesting... `pip3 install scipy` is downloading an sdist, which has a pyproject.toml specifying:
> 
> ```toml
> [build-system]
> build-backend = 'mesonpy'
> requires = [
>     "meson-python>=0.8.1",  # we need more fixes in meson-python, so no upper bound now
> [....]
> ```
> 
> and then inside `get_requires_for_build_wheel()` (this is all pip internal code) it tries to import that build-backend, but fails because `No module named 'mesonpy'`.
> 
> I'm not really sure how something like this would ever happen, because pip should be installing the build-system.requires first... it seems like this should be a pip issue if anything.
> 
> What's your version of pip?

I think it's pretty current: 

```
$ pip3 --version
pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
$ 

```
Thanks for the comments. I'm still working on it.

**Comment by tupui** [comment] 2022-09-07 08:52
Thanks for reporting. The sdist vs wheel is because we only build wheels for macOS 12 (Monterey). As for why pip does not install build deps I don't know yet.

**Comment by rgommers** [comment] 2022-09-09 10:51
> A quick look through the pip bugtracker pointed me at this, which sounds a lot like your issue: [pypa/pip#11275](https://github.com/pypa/pip/issues/11275)

@gregdelozier did that end up being your issue, or did you not have a `pip.conf` settings file?

**Comment by gregdelozier** [comment] 2022-09-21 00:10
> > A quick look through the pip bugtracker pointed me at this, which sounds a lot like your issue: [pypa/pip#11275](https://github.com/pypa/pip/issues/11275)
> 
> @gregdelozier did that end up being your issue, or did you not have a `pip.conf` settings file?

I do not believe that is the issue. I did take a look at that, and appreciate you bringing it to my attention. 

At the moment I have too many irons in the fire to risk an OS upgrade. It's a pity that scipy seems unavailable to ARM/MacOS 11 -- there must be more than just myself trying to get work done on such a machine. I guess when I have time I'll upgrade. 

Thanks for the help.

**Comment by tupui** [comment] 2022-09-21 00:16
> there must be more than just myself trying to get work done on such a machine.

There are, but there are an exponential combination of platforms and versions to support and as we have limited ressources and maintainers time, we have to make choices.

**Comment by rgommers** [comment] 2022-09-21 05:02
Thanks for checking @gregdelozier. If that wasn't the bug, let's try and see what is actually going on. Could you run `pip3 install scipy -vv` so you get verbose output and we see what is actually happening? It should show things like:
```
$ pip3 install scipy -vv
Using pip 22.1.2 from /Users/rgommers/mambaforge/envs/scipy-dev/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
...
Looking up "https://pypi.org/simple/pip/" in the cache
...
<a ton of "Found link" output that is not interesting>
....
Collecting scipy
  Created temporary directory: /private/var/folders/2m/dk_4hyc90xd2drkbqsbsjfqw0000gn/T/pip-unpack-zlc5tisj
  Looking up "https://files.pythonhosted.org/packages/db/af/16906139f52bc6866c43401869ce247662739ad71afa11c6f18505eb0546/scipy-1.9.1.tar.gz" in the cache
  No cache entry available
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/db/af/16906139f52bc6866c43401869ce247662739ad71afa11c6f18505eb0546/scipy-1.9.1.tar.gz HTTP/1.1" 200 42019478
  Downloading scipy-1.9.1.tar.gz (42.0 MB)
...
  Collecting meson-python>=0.8.1
    Downloading meson_python-0.8.1.tar.gz (30 kB)
    Installing build dependencies: started
    Running command pip subprocess to install build dependencies
    Ignoring typing-extensions: markers 'python_version < "3.8"' don't match your environment
    Collecting meson>=0.62.0
      Downloading meson-0.63.2.tar.gz (2.1 MB)
...
```

**Comment by ericllazarus** [comment] 2022-10-05 22:20
I ran into the same issue on Mac Bigsir 11.7 (20G817)!

```
python3 -m pip install scipy -vv

...see details below in the attached file including my output...

ModuleNotFoundError: No module named 'mesonpy'

Remote version of pip: 22.2.2
Local version of pip:  22.2.2
Was pip installed by pip? True
```
[pip3.txt](https://github.com/scipy/scipy/files/9719319/pip3.txt)

**Comment by rgommers** [comment] 2022-10-05 22:37
Thanks @ericllazarus. I added some more of the relevant traceback from your attachment here:
 
<details>

```
  Found link https://files.pythonhosted.org/packages/db/af/16906139f52bc6866c43401869ce247662739ad71afa11c6f18505eb0546/scipy-1.9.1.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.8,<3.12), version: 1.9.1
Skipping link: not a file: https://pypi.org/simple/scipy/
Given no hashes to check 69 links for project 'scipy': discarding no candidates
Collecting scipy
  Created temporary directory: /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-unpack-rbvzuc99
  Looking up "https://files.pythonhosted.org/packages/db/af/16906139f52bc6866c43401869ce247662739ad71afa11c6f18505eb0546/scipy-1.9.1.tar.gz" in the cache
  Current age based on date: 2044
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 2044
  Using cached scipy-1.9.1.tar.gz (42.0 MB)
  Added scipy from https://files.pythonhosted.org/packages/db/af/16906139f52bc6866c43401869ce247662739ad71afa11c6f18505eb0546/scipy-1.9.1.tar.gz to build tracker '/private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-tracker-2t47ak54'
  Created temporary directory: /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Using pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
  Ignoring numpy: markers 'platform_machine == "loongarch64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64" and platform_machine != "loongarch64" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "loongarch64" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.11" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.12"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_python_implementation == "PyPy"' don't match your environment
  Collecting meson-python>=0.8.1
    Using cached meson_python-0.10.0-py3-none-any.whl (18 kB)
  Collecting meson==0.62.2
    Using cached meson-0.62.2-py3-none-any.whl (864 kB)
  Collecting Cython<3.0,>=0.29.21
    Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
  Collecting pybind11<2.11.0,>=2.4.3
    Using cached pybind11-2.10.0-py3-none-any.whl (213 kB)
  Collecting pythran<0.12.0,>=0.9.12
    Using cached pythran-0.11.0-py3-none-any.whl (4.2 MB)
  Collecting wheel<0.38.0
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting numpy==1.21.6
    Using cached numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
  Collecting tomli>=1.0.0
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting ninja
    Using cached ninja-1.10.2.4-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (231 kB)
  Collecting pyproject-metadata>=0.5.0
    Using cached pyproject_metadata-0.6.1-py3-none-any.whl (7.4 kB)
  Collecting ply>=3.4
    Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
  Collecting beniget~=0.4.0
    Using cached beniget-0.4.1-py3-none-any.whl (9.4 kB)
  Collecting gast~=0.5.0
    Using cached gast-0.5.3-py3-none-any.whl (19 kB)
  Collecting packaging>=19.0
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Installing collected packages: ply, ninja, wheel, tomli, pyparsing, pybind11, numpy, meson, gast, Cython, packaging, beniget, pythran, pyproject-metadata, meson-python
    Creating /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/ninja to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/wheel to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/pybind11-config to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/f2py to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/f2py3 to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/f2py3.10 to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/meson to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/cygdb to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/cython to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/cythonize to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/pythran to 755
    changing mode of /private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-viwdhap6/overlay/bin/pythran-config to 755
  Successfully installed Cython-0.29.32 beniget-0.4.1 gast-0.5.3 meson-0.62.2 meson-python-0.10.0 ninja-1.10.2.4 numpy-1.21.6 packaging-21.3 ply-3.11 pybind11-2.10.0 pyparsing-3.0.9 pyproject-metadata-0.6.1 pythran-0.11.0 tomli-2.0.1 wheel-0.37.1
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Running command Getting requirements to build wheel
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  AssertionError:
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 68, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 685, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

Remote version of pip: 22.2.2
Local version of pip:  22.2.2
Was pip installed by pip? True
Removed scipy from https://files.pythonhosted.org/packages/db/af/16906139f52bc6866c43401869ce247662739ad71afa11c6f18505eb0546/scipy-1.9.1.tar.gz from build tracker '/private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-tracker-2t47ak54'
Removed build tracker: '/private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-tracker-2t47ak54'
```

</details>

So that's two reports of building from source on macOS 11.X with Homebrew failing. A build from source is triggered there because our arm64 wheels are for >= 12.0. Somehow `meson-python` gets installed just fine, but then cannot be imported inside the venv that is created by `pip` for the isolated build. 

I wonder if this can be reproduced on macOS 12 with `pip install scipy --no-binary :scipy:` (I think that's the right command, not tested). That would make this easier to reproduce.

There is one line in the log that I'm not sure about, this looks a little odd: `Error in sitecustomize; set PYTHONVERBOSE for traceback:`. @ericllazarus would you mind doing `export PYTHONVERBOSE` and then re-running the build to see if that says anything more?

**Comment by nealmcb** [comment] 2022-10-05 22:42
Thanks folks!
I'll just note that Eric's output was preceded by (I think) a brew install openblas, and that openblas then suggested that the newer version it installed needed to be enabled via some environmental variables. I don't think Eric tried setting those variables yet, but I was just watching the install remotely....

**Comment by rgommers** [comment] 2022-10-06 06:53
Thanks @nealmcb. I checked what those variables were, and this is what Homebrew does right now:
```
openblas is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides BLAS in Accelerate.framework.

For compilers to find openblas you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"
```

That can't explain `ModuleNotFoundError: No module named 'mesonpy'` though, we never arrive at the place where we need `openblas`.

**Comment by ericllazarus** [comment] 2022-10-11 21:06
Thanks @rgommers 

$ export PYTHONVERBOSE=1
$ export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
$ export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"
$ python3 -m pip install scipy -vv > /tmp/pip3-2.txt 2>&1

"ModuleNotFoundError: No module named 'mesonpy'"

[pip3-2.txt](https://github.com/scipy/scipy/files/9759742/pip3-2.txt)

**Comment by rgommers** [comment] 2022-10-11 21:45
Thanks @ericllazarus. This part makes me think it's a Homebrew bug:
```
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 549, in execsitecustomize
      import sitecustomize
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 883, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/private/var/folders/vs/mn5gszv12h56c8x11y775y9w0000gn/T/pip-build-env-qen_2aat/site/sitecustomize.py", line 22, in <module>
      assert not path in sys.path
  AssertionError
  # destroy sitecustomize
```

There's a ton of issues related to `sitecustomize.py` in Homebrew, and they're doing really messy things to hide their own site-packages from `sys.path`: 
- https://github.com/Homebrew/homebrew-core/search?q=sitecustomize&type=issues.
- https://github.com/Homebrew/brew/pull/8880

Could you please open a HomeBrew bug linking this one?

**Comment by ericllazarus** [comment] 2022-10-11 22:05
Thanks @rgommers. I will open the other ticket. Is there a workaround where I install without homebrew? If so, how?

**Comment by andyfaff** [comment] 2022-10-11 22:27
You have a few options (assuming you're `arm64`):

1. Upgrade to Monterey and pip install scipy
2. Remain on Big-Sur, but use an `x86_64` Python running via Rosetta, there are `macosx_10_9_x86_64` wheels available. I'm not sure how you could setup this kind of Python. I know there are Universal and Intel installers available from [here](https://www.python.org/downloads/macos/). If you install a universal build it may be possible to ask Terminal to run the `x86_64` arch.
3. Try installing scipy via conda.
4. Download the appropriate `macosx_12_0_arm64.whl` from PyPI, change the name to `macosx_11_0_arm64.whl`, and install it. However, it's likely you'll run into bugs as Ralf alluded to. I don't remember the full history of why we don't make wheels for 11_0. This option isn't supported.

**Comment by rgommers** [comment] 2023-04-24 22:43
There have been no more reports of this, and it's not a SciPy bug. So I assume that the Homebrew issue, or whatever else caused this, has been fixed by now. So I'll close this. Thanks all.

**Closed by rgommers** 2023-04-24 22:43 UTC
Labels: defect, Build issues
