### ISSUE TITLE
Rbf hangs indefinitely, even for very small number of points to interpolate

### ISSUE THREAD

**Issue by amerand** [scipy/scipy#5405] opened 2015-10-22 15:58 UTC
Using Scipy 0.16 for Python 2.7.10 on Linux, scipy.interpolate.Rbf hangs, even if it runs in tens of milli seconds for slightly less number of points to interpolate. It is not the case for Scipy 0.15.0 (I downgraded to check) or on a Mac running the same Python, Numpy and Scipy versions.

Details:
```
from scipy.interpolate import Rbf
import numpy as np

def testRbf(N=10,P=100):
        X, Y = np.meshgrid(np.linspace(-5,5,P), np.linspace(-5,5,P))
        x = np.random.randn(N)
        y = np.random.randn(N)
        z = np.random.rand(N)
        return Rbf(x,y,z,function='linear')(X,Y)
```

`testRbf(20,200)` takes 20ms both on Linux and Max (comparable CPUs). While `testRbf(30,200)` runs in 30ms on the Mac, it takes at least several minutes on lInux (I did not have the patience to wait).

Both Linux and Mac computers run Anaconda distribution version 2.3.0 64 bits with: Python 2.7.10, Numpy 1.9.3, Scipy 0.16.0. I downgraded to Scipy 0.15.0 and `testRbf(30,200)` runs in 30ms or so on Linux, as I expect. It could be an Anaconda fluke, if so feel free to close my bug.

**Comment by pv** [comment] 2015-10-22 18:11
Didn't manage to reproduce on linux (on anaconda or without), so it's
not a generic linux issue.
.
The only "costly" computational step there is just inverting a 30x30
matrix, and then multiplying by the result. If that doesn't work, then
probably many other things don't work either --- you can maybe check
`scipy.test()`.

**Comment by amerand** [comment] 2015-10-23 15:37
Dear Pauli,

I ran the test on my mac and it worked in 2minutes. On the linux machine
with scipy 0.16.0, it has been running for almost an hour and has not been
advancing anymore. Using verbose=10 and starting again, I can see it is
hanging at: "test_rbf.test_rbf_interpolation('multiquadric',) ...". No
surprise I guess.

I tried also with scipy 0.15, and the test also hangs forever, but at
"test_random_complex (test_basic.TestDet)".


cheers,

Antoine


PS:
I ran the test on Numpy 1.9.3 (for Scipy 0.15.0) without errors. Numpy
1.10.1 (for Scipy 0.16.0) gives me an error for


ERROR: test_rfft (test_fft.TestFFT1D)

----------------------------------------------------------------------

Traceback (most recent call last):

  File
"/home/amerand/anaconda/lib/python2.7/site-packages/numpy/fft/tests/test_fft.py",
line 72, in test_rfft

    x = np.fft.rfft([0, 1+5j, 0+7j, -3j])

  File
"/home/amerand/anaconda/lib/python2.7/site-packages/numpy/fft/fftpack.py",
line 359, in rfft

    a = array(a, copy=True, dtype=float)

TypeError: can't convert complex to float


======================================================================

FAIL: test_umath.TestComplexFunctions.test_branch_cuts(<ufunc 'arccosh'>,
[-1, 0.5], [1j, 1j], 1, -1, True)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/amerand/anaconda/lib/python2.7/site-packages/nose/case.py",
line 197, in runTest

    self.test(*self.arg)

  File
"/home/amerand/anaconda/lib/python2.7/site-packages/numpy/core/tests/test_umath.py",
line 1748, in _check_branch_cut

    assert_(np.all(np.absolute(y0.imag - yp.imag) < atol), (y0, yp))

  File
"/home/amerand/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py",
line 53, in assert_

    raise AssertionError(smsg)

AssertionError: (array([  0.00000000e+00+3.14159265j,
1.11022302e-16-1.04719755j]), array([  4.71216091e-07+3.14159218j,
1.28119737e-13+1.04719755j]))

**Comment by pv** [comment] 2015-10-24 12:46
Closing --- this seems to be an issue with the BLAS/LAPACK libraries you have installed, and is not fixable by changes on our side.

**Closed by pv** 2015-10-24 12:46 UTC
