### ISSUE TITLE
BUG: `TestThreading.test_median_filter` failure to run quickly on Windows is sensitive to unrelated code changes

### ISSUE THREAD

**Issue by JasonGross** [scipy/scipy#21816] opened 2024-11-06 16:31 UTC
### Describe your issue.

Insofar as I can tell, https://github.com/scipy/scipy/pull/19549, should not be modifying anything that impacts `TestThreading.test_median_filter`.  Yet [fail slow, fast, py3.12/npAny, dev.py](https://github.com/scipy/scipy/actions/runs/11698240835/job/32585233597?pr=19549#logs) fails with
```
___________________ TestThreading.test_median_filter[numpy] ___________________
[gw0] win32 -- Python 3.12.7 C:\hostedtoolcache\windows\Python\3.12.7\x64\python.exe
Test passed but took too long to run: Duration 1.5405415000000175s > 1.0s
```

### Reproducing Code Example

https://github.com/scipy/scipy/pull/19549

### Error message

```
___________________ TestThreading.test_median_filter[numpy] ___________________
[gw0] win32 -- Python 3.12.7 C:\hostedtoolcache\windows\Python\3.12.7\x64\python.exe
Test passed but took too long to run: Duration 1.5405415000000175s > 1.0s
```

### SciPy/NumPy/Python version and system information

See [the logs](https://github.com/scipy/scipy/actions/runs/11698240835/job/32585233597?pr=19549#logs)

**Comment by lucascolley** [comment] 2024-11-06 16:36
duplicate of https://github.com/scipy/scipy/issues/20806#issuecomment-2334335644, but thanks!

**Closed by lucascolley** 2024-11-06 16:36 UTC
Labels: defect

**Comment by JasonGross** [comment] 2024-11-06 18:48
Ah, sorry for not checking, and thanks!  Btw, can you tell if [this failure of the bench](https://app.circleci.com/pipelines/github/scipy/scipy/30997/workflows/1e28d248-8870-42de-b0ff-94dd74883118/jobs/104815) on the same PR related or unrelated?  I can't understand the bench error "Exited with code exit status 2" without any other apparent error.
