### ISSUE TITLE
BUG: Cython3 linalg import order bug

### ISSUE THREAD

**Issue by jeremyleung521** [scipy/scipy#18909] opened 2023-07-18 14:53 UTC
### Describe your issue.

Since Cython 3, I am unable to cythonize if the cimports are in a certain reverse order. Only happens on Linux, not on MacOS. The paths for imports are wrong in the traceback, so this might be a consequence of [this change](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#namespace-packages).

```
# This doesn't work...
cimport scipy.linalg.cython_lapack
cimport scipy.linalg
```
```
# This works...
cimport scipy.linalg
cimport scipy.linalg.cython_lapack
```

### Reproducing Code Example

```python
# This is in an environment with scipy and cython 3 installed
# In test.pyx, have the following lines:
cimport scipy.linalg.cython_lapack
cimport scipy.linalg

# Run the following
cython test.pyx
```

### Error message

```shell
/home/user/anaconda3/envs/scipy-cy/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/user/git15/scipy/test.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
from .linalg cimport cython_blas, cython_lapack
^
------------------------------------------------------------

/home/user/anaconda3/envs/scipy-cy/lib/python3.11/site-packages/scipy/linalg.pxd:1:0: 'scipy/linalg/linalg.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from .linalg cimport cython_blas, cython_lapack
^
------------------------------------------------------------

/home/user/anaconda3/envs/scipy-cy/lib/python3.11/site-packages/scipy/linalg.pxd:1:0: 'scipy/linalg/linalg/cython_blas.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from .linalg cimport cython_blas, cython_lapack
^
------------------------------------------------------------

/home/user/anaconda3/envs/scipy-cy/lib/python3.11/site-packages/scipy/linalg.pxd:1:0: 'scipy/linalg/linalg/cython_lapack.pxd' not found
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys,scipy,numpy,cython; print(scipy.__version__, numpy.__version__, cython.__version__, sys.version_info); scipy.show_config()
1.10.1 1.25.0 3.0.0 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/user/anaconda3/envs/scipy-cy/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/user/anaconda3/envs/scipy-cy/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/user/anaconda3/envs/scipy-cy/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/user/anaconda3/envs/scipy-cy/include']
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/user/anaconda3/envs/scipy-cy/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/user/anaconda3/envs/scipy-cy/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/user/anaconda3/envs/scipy-cy/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/user/anaconda3/envs/scipy-cy/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

**Comment by tupui** [comment] 2023-07-19 14:33
Hi @jeremyleung521, thank you for reporting.

I think this relates to #18242 and alike and is being worked on already.

**Comment by jeremyleung521** [comment] 2023-07-19 14:47
Thanks for the update, @tupui! 

I did a quick search and a lot of those Cython3 PRs are already merged in (including #18242) so I thought this might be one of those edge cases that didn't get caught.

**Comment by rgommers** [comment] 2023-07-22 11:44
I think we're still not testing these APIs with actual Cython code (xref gh-16748), so it may have slipped through. Without checking: I think this is a Cython 3 change that has to be resolved by moving `scipy/linalg.pxd` to `scipy/linalg/__init__.pxd`. And we can't move to `__init__.pxd` files before dropping Cython 0.29.X support.

**Comment by rgommers** [comment] 2023-07-22 11:46
> so this might be a consequence of [this change](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#namespace-packages).

That's about namespace packages, which is something else than SciPy uses. But yeah, it may still be related, it's the same import machinery.

**Comment by mathstuf** [comment] 2024-10-08 00:18
I'm seeing this issue in our builds of scipy (but only on macOS?) non-deterministically. Is there something that can be done in the `meson` code to add some stricter ordering until there's a proper fix?

**Closed** 2024-12-02 16:01 UTC
Labels: defect, Cython

**Comment by mathstuf** [comment] 2025-01-05 14:08
It looks like there's another missing dependency link:

```
      [1315/1465] Generating 'scipy/spatial/_qhull.cpython-312-darwin.so.p/_qhull.c'
      FAILED: scipy/spatial/_qhull.cpython-312-darwin.so.p/_qhull.c
      /opt/glr/paraview/paraview-ci-ext/0/build/install/bin/cython -3 --fast-fail --output-file scipy/spatial/_qhull.cpython-312-darwin.so.p/_qhull.c --include-dir . ../scipy/spatial/_qhull.pyx
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      from libc cimport stdlib
      from libc.math cimport NAN
      from scipy._lib.messagestream cimport MessageStream
      from libc.stdio cimport FILE
      
      from scipy.linalg.cython_lapack cimport dgetrf, dgetrs, dgecon
      ^
      ------------------------------------------------------------
      
      /opt/glr/paraview/paraview-ci-ext/0/build/superbuild/scipy/src/scipy/spatial/_qhull.pyx:30:0: 'scipy/linalg/cython_lapack.pxd' not found
```

**Comment by rgommers** [comment] 2025-01-05 14:38
Thanks @mathstuf, I can reproduce this with:
```
$ meson setup build
$ ninja -C build scipy/spatial/_qhull.cpython-312-x86_64-linux-gnu.so.p/_qhull.c
``` 
It looks like `ninja -C build -t missingdeps` missed this because of a hidden dependency on a generated target. `cython_lapack.pxd` is missing from the dependencies:
```
$ ninja -C build -t inputs scipy/spatial/_qhull.cpython-312-x86_64-linux-gnu.so.p/_qhull.c
../scipy/__init__.py
../scipy/_lib/__init__.py
../scipy/_lib/_ccallback_c.pxd
../scipy/_lib/ccallback.pxd
../scipy/_lib/messagestream.pxd
../scipy/linalg/__init__.pxd
../scipy/optimize/__init__.pxd
../scipy/spatial/_qhull.pxd
../scipy/spatial/_qhull.pyx
../scipy/spatial/setlist.pxd
../scipy/special/__init__.pxd
/home/rgommers/mambaforge/envs/scipy-dev-py312/bin/cython
scipy/__init__.py
scipy/_lib/__init__.py
scipy/_lib/_ccallback_c.pxd
scipy/_lib/ccallback.pxd
scipy/_lib/messagestream.pxd
scipy/linalg/__init__.pxd
scipy/optimize/__init__.pxd
scipy/spatial/_qhull.pxd
scipy/spatial/setlist.pxd
scipy/special/__init__.pxd
```

Building each target separately in a cleanly set up build directory is the robust way to smoke out issues here - that's a little annoying to do, but I think it's time to bite that bullet.

**Comment by mathstuf** [comment] 2025-01-05 14:41
> Building each target separately in a cleanly set up build directory is the robust way to smoke out issues here - that's a little annoying to do, but I think it's time to bite that bullet.

I agree; running that now myself. I'll report back with any others that I find.

**Comment by mathstuf** [comment] 2025-01-06 08:59
Found these other failures:

`scipy/linalg/_cythonized_array_utils.cpython-312-x86_64-linux-gnu.so.p/_cythonized_array_utils.c`:

```
Error compiling Cython file:
------------------------------------------------------------
...
from scipy.linalg._cythonized_array_utils cimport (
    lapack_t,
    np_complex_numeric_t,
    np_numeric_t
    )
from scipy.linalg.cython_lapack cimport sgetrf, dgetrf, cgetrf, zgetrf
^
------------------------------------------------------------

SRCDIR/scipy/linalg/_cythonized_array_utils.pyx:9:0: 'scipy/linalg/cython_lapack.pxd' not found
```

`scipy/linalg/_decomp_interpolative.cpython-312-x86_64-linux-gnu.so.p/_decomp_interpolative.c`:

```
Error compiling Cython file:
------------------------------------------------------------
...

import scipy.linalg as la
from scipy.fft import rfft, fft
from scipy.sparse.linalg import LinearOperator

from scipy.linalg.cython_lapack cimport dlarfgp, dorm2r, zunm2r, zlarfgp
^
------------------------------------------------------------

SRCDIR/scipy/linalg/_decomp_interpolative.pyx:119:0: 'scipy/linalg/cython_lapack.pxd' not found
```

**Comment by rgommers** [comment] 2025-01-07 07:13
Thanks! I opened a PR to fix these. That seems to be all of the ones that depend on `cython_blas`/`cython_lapack`. Did you end up writing a script for this @mathstuf? I'd be interested in seeing it.

I was unable to reproduce the failures for regular build even with a high level of parallelism on a 24-core Linux machine or on a macOS M1 laptop. I'm also curious about your build machine config - you said above it's masOS-only, is that with a large core count Pro/Max CPU?

**Comment by mathstuf** [comment] 2025-01-07 10:57
> Did you end up writing a script for this @mathstuf? I'd be interested in seeing it.

Yep.

Extracting outputs is:

```sh
grep '^build' build.ninja | cut -d: -f1 | cut -d' ' -f2- > rules
```

This needs some post-processing to remove some "outputs" (`PHONY` at the beginning and top-level targets near the end). Then there's a simple loop over these:

```sh
#!/bin/sh

set -e

record () {
    echo "$1" >> fail-log
}

for output in $( cat rules ); do
    echo "$output" >>build.log 2>&1
    rm -rf build
    meson setup build -Dblas=blas -Dlapack=lapack
    ninja -C build "$output" >>build.log 2>&1 || record "$output"
    echo "----------------------------------------" >>broken.log
done
```

>  I'm also curious about your build machine config - you said above it's masOS-only, is that with a large core count Pro/Max CPU?

It's the only place I've even seen it happen in CI. They're Mac Mini machines of various vintages, but seems to happen with the M1 and up machines (we have M1, M2, and M4 Pro hardware) regardless of whether running under `arm64` or completely under Rosetta2 (via `arch -x86_64 bash` as the shell for the entire CI job). Note that we have `sccache` wrapping our compiles, so there could be "uncommon" build orders depending on cache hit rates.

**Comment by rgommers** [comment] 2025-01-07 11:03
Thanks, much appreciated. `sccache` does make sense as the explanation for why I couldn't reproduce it.

I found that `ninja clean` instead of `rm -rf build && meson setup build` works too to reproduce, and is faster, so with that it may be possible to run it in a reasonable amount of time.

**Comment by mathstuf** [comment] 2025-01-07 12:11
Ah, yeah it does. I moved to `rm && meson` when I realized that nothing was doing a repro. Turns out that `scipy` was installed, so the build was picking it up from there instead. Since it was running overnight anyways, I didn't think to go back and use `ninja -t clean` again.
