### ISSUE TITLE
The requested URL /doc/scipy/reference/generated/scipy-integrate-odeint-1.py was not found on this server.

### ISSUE THREAD

**Issue by sebasped** [scipy/scipy#6821] opened 2016-11-28 16:12 UTC
Broken documentation link:

https://docs.scipy.org/doc/scipy/reference/generated/scipy-integrate-odeint-1.py

On doc web page:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html#scipy.integrate.odeint

**Comment by person142** [comment] 2016-11-28 16:25
Duplicate of https://github.com/scipy/scipy/issues/3250, so closing. Thanks for the report @sebasped.

**Closed by person142** 2016-11-28 16:25 UTC
