### ISSUE TITLE
interp1d on ND arrays where some series are nan

### ISSUE THREAD

**Issue by crusaderky** [scipy/scipy#8781] opened 2018-04-28 13:03 UTC
scipy 1.0.1, Anaconda 5, Linux 64 bit

When y is a N-dimensional array, I would expect interp1d to work independently on each series.
When invoked with ``kind='quadratic'`` or ``kind='cubic'``, however, if _any_ series contains NaNs then the interpolated values of _all_ series will be NaN:

```
import numpy
from scipy.interpolate import *

x = numpy.arange(0, 8, 1)
y = numpy.stack([numpy.arange(0, 80, 10), numpy.full((8, ), numpy.nan)], axis=1)
print("x =", x)
print("y =", y)

for kind in ('nearest', 'linear', 'zero', 'slinear', 'quadratic', 'cubic'):
    print(kind + ' =', interp1d(x, y, axis=0, kind=kind)(4.5))
print("Akima =", Akima1DInterpolator(x, y, axis=0)(4.5))
print("PCHIP =", PchipInterpolator(x, y, axis=0)(4.5))
```
Output:
```
x = [0 1 2 3 4 5 6 7]
y = [[ 0. nan]
 [10. nan]
 [20. nan]
 [30. nan]
 [40. nan]
 [50. nan]
 [60. nan]
 [70. nan]]
nearest = [40. nan]
linear = [45. nan]
zero = [40. nan]
slinear = [45. nan]
quadratic = [nan nan]
cubic = [nan nan]
Akima = [45. nan]
PCHIP = [45. nan]
```

**Comment by ev-br** [comment] 2018-04-28 22:12
PCHIP and Akima splines are local, hence they have easier time dealing with nans than cubic or quadratic splines. A more relevant comparison is `CubicSpline`, which raises a ValueError for even a single nan anywhere in an array. So does `make_interp_spline`, actually. 

`interp1d` does fairly weird things to work around and to not raise, see 
https://github.com/scipy/scipy/blob/v1.0.0/scipy/interpolate/interpolate.py#L504

Clearly, this logic can be improved so that `_call_nan_spline` actually does computations for the parts of the input array which are all finite, and fills with nans the rest. PR welcome, I'd say.

**Comment by seanpquinn** [comment] 2021-04-22 03:59
I tried taking a kludgey stab at this. From the comment in this block, it seems LAPACK is sensitive to `nans` and the input arrays need to be sanitized. `nans` are easy enough to mask out, but the difficulty (in my view) seems to be no way to pass position information into the spline function (or getting it when it returns). 

So the `_call_nan_spline` does it in post and masks everything since dummy arrays were sent into the spline.

I didn't really change the post-correction strategy, but instead of sending in dummy arrays, I replace `nans` with a, shall we say, "recognizable" value (full-scale float) that can be filtered after. Obviously, this can be dangerous if users are interpolating data near max floats where outputs could be incorrectly `nan'd`.

https://github.com/seanpquinn/scipy/blob/interp1d_nan_work/scipy/interpolate/interpolate.py#L540

I removed PCHIP and Akima from the above snippet since it gives a value error. This hack also fails `test_interpolate.py` but seems like that test assert is checking that all outputs are `nan` for any `nan` input anyway.

```
python test_interp.py
x = [0 1 2 3 4 5 6 7]
y = [[ 0. nan]
 [10. nan]
 [20. nan]
 [30. nan]
 [40. nan]
 [50. nan]
 [60. nan]
 [70. nan]]
nearest = [40. nan]
linear = [45. nan]
zero = [40. nan]
slinear = [45. nan]
quadratic = [45. nan]
cubic = [45. nan]
```

**Comment by ev-br** [comment] 2021-04-22 05:41
Nice! But not quite.
 It's not obvious what that large values mean for e.g. condition number. That pchip/akima start giving valueerrors might already be a sign. 
Also, having a nan in the x array makes it non salvageable, one cannot just replace it with a value.

**Comment by seanpquinn** [comment] 2021-04-22 16:47
Hmm, I think I get the value error for pchip/akima without my mods though, at least using 1.4.1 on my laptop

Noted about the x nan: so the behavior for x needs to be changed to return all nans if at least one nan in the input

**Comment by ev-br** [comment] 2022-08-09 21:09
OK, as of 

    In [3]: scipy.__version__
    Out[3]: '1.10.0.dev0+1644.903bc39'

PchipInterpolator and Akima1DInterpolator snippets in the OP raise ValueErrors (this is now exactly new in 1.9.x; this change has been made at some point after April 2018), the rest is as it was.

Otherwise, this issue is a duplicate of gh-9315, which has some more details, so let's close this one in favor of that one. Thanks all.

**Closed by ev-br** 2022-08-09 21:09 UTC
Labels: enhancement, scipy.interpolate
