### ISSUE TITLE
Unclear skewnorm documentation

### ISSUE THREAD

**Issue by Guymer** [scipy/scipy#9626] opened 2018-12-26 12:49 UTC
**Short Story**: My issue is about the [`scipy.stats.skewnorm` documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skewnorm.html). I think the equation that is defined on that page is incorrect for non-zero means *or* I am completely misunderstanding it (in which case I apologise for wasting everyone's time).

**Long Story**: I work on two computers, one has SciPy 0.12.1 installed and the other has SciPy 1.1.0 installed. I wanted to use `scipy.stats.skewnorm` on the old computer but it does not exist in that version of SciPy so I implemented the equation in the documentation as a work around. It did not give the expected results when I used a non-zero mean so I implemented [the skewed normal definition given on Wolfram](https://reference.wolfram.com/language/ref/SkewNormalDistribution.html) which worked as expected. I copied the script to the newer computer and checked the output with `scipy.stats.skewnorm`: `scipy.stats.skewnorm` and Wolfram always agree but the equation in the documentation does not (it only agrees when the mean is zero).

### Reproducing code example:
```python
import numpy
import scipy
import scipy.stats
axis = numpy.linspace(-5.0, 15.0, 21)
mean = 10.0
skew = 10.0
sigma = 1.0
a = 2.0 * scipy.stats.norm.pdf(axis, loc = mean, scale = sigma) * scipy.stats.norm.cdf(skew * axis, loc = mean, scale = sigma)
b = scipy.stats.skewnorm.pdf(axis, a = skew, loc = mean, scale = sigma)
```
I have written [a more informative minimum working example on Gist](https://gist.github.com/Guymer/2b197bf0d5df4d1a00068d0c23d8a43c) which has [the output](https://gist.github.com/Guymer/44ddee73fc0008546347cbceef7c7b6f) too. In short `skewnorm.pdf(x, a)` equals `2 * norm.pdf(x) * norm.cdf(a*x)` (as written in the documentation) **only when `loc = 0`** but `skewnorm.pdf(x, a, loc = 10.0)` does not equal `2 * norm.pdf(x, loc = 10.0) * norm.cdf(a*x, loc = 10.0)`. This can be seen in the plot below (created by the linked Gist):
![skewnorm-mwe](https://user-images.githubusercontent.com/4899102/50446072-c7ec8400-090a-11e9-9189-7feed99bbcae.png)
Note how the blue/orange/green datasets are identical (which have `loc = 0.0`) but that the red dataset is different to the purple/brown datasets (which have `loc = 10.0`).

### Scipy/Numpy version information:
old computer: SciPy 0.12.1; NumPy 1.7.1
new computer: SciPy 1.1.0; NumPy 1.15.3

### Summary:
So either my implementation of `skewnorm.pdf(x, a) = 2 * norm.pdf(x) * norm.cdf(a*x)` on line 23 and line 31 of [my Gist](https://gist.github.com/Guymer/2b197bf0d5df4d1a00068d0c23d8a43c) is incorrect or the equation itself is incorrect, in which case the documentation needs updating (perhaps to `scipy.stats.norm.pdf(axis, loc = mean, scale = sigma) * scipy.special.erfc(-skew * (axis - mean) / (numpy.sqrt(2.0) * sigma))`).

*Thank you for your time in reading this.*

**Comment by rgommers** [comment] 2018-12-26 18:46
The implementation of `skewnorm._pdf` matches the documented equation: https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L6083

Your one-liner implementation probably goes wrong because of the handling of loc/scale in the `norm.pdf` and `norm.cdf` methods, which cause `norm.cdf(a*x)` not to translate in `_norm_cdf(a*x)`.

Don't have time to investigate your code in more detail, but as your code doesn't do the required loc/scale handling and the docs match the implementation at https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L6083, I will close this as not a bug.

**Closed by rgommers** 2018-12-26 18:46 UTC
Labels: Documentation, scipy.stats

**Comment by MunishaTripping** [comment] 2019-10-23 12:05
my guess is that in below equation 
 2.0 * scipy.stats.norm.pdf(axis, loc = mean, scale = sigma) * scipy.stats.norm.cdf(skew * axis, loc = mean, scale = sigma) should translate to 
2.0 * scipy.stats.norm.pdf(axis, loc = mean, scale = sigma) * scipy.stats.norm.cdf(skew * axis, loc = skew*mean, scale = sigma)
