### ISSUE TITLE
Intel MKL ERROR in scipy.linalg.eigvalsh for complex matrix larger than 1999

### ISSUE THREAD

**Issue by wangshiphys** [scipy/scipy#8713] opened 2018-04-12 07:38 UTC
`scipy.linalg.eigvalsh()` give a message 

> Intel MKL ERROR: Parameter 12 was incorrect on entry to ZHBRDB.

and return  wrong eigenvalues. When the input matrix is a **real Hermitian**  matrix or a **complex Hermitian with dimension less than 200**0, this function always give the right answer as `np.linalg.eigvalsh` does, but if the matrix is a **complex matrix with dimension larger than 2000**, this function always give the above message and wrong eigenvalues. The returned eigenvalues are all zeros but the last one.

### Reproducing code example:
```python
import scipy.linalg as la
import numpy as np

#row = col = 1999
row = col = 2000
shape = (row, col)

# A real matrix
#M = np.random.random(size=shape)

# A complex matrix
M = np.random.random(size=shape) + np.random.random(size=shape) * 1j

# Construct an Hermitian matrix
M += M.T.conj()

vals_numpy = np.linalg.eigvalsh(M)
vals_scipy = la.eigvalsh(M)
print(vals_scipy)
assert np.allclose(vals_numpy, vals_scipy)

```

### Error message:
```python

Intel MKL ERROR: Parameter 12 was incorrect on entry to ZHBRDB.
[    0.     0.     0. ...     0.     0. 48000.]
Traceback (most recent call last):
  File ".\test.py", line 20, in <module>
    assert np.allclose(vals_numpy, vals_scipy)
AssertionError
```

### Scipy/Numpy/Python version information:
```python

scipy.__version__: '1.0.0'
numpy.__version: '1.14.2'
sys.version_info: sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
Python 3.6.4 :: Anaconda custom (64-bit)
```

**Comment by ilayn** [comment] 2018-04-12 09:05
This is a duplicate of #8205 and as a summary; mainly it is a MKL bug and the necessary `?work` variables are not reported correctly. On the SciPy part we also have some parts to iron out and I've done some work but it won't make it to v1.1. See the MKL board response from the Intel team on #8205

**Closed by ilayn** 2018-04-12 09:05 UTC
