### ISSUE TITLE
Regression in scipy.interpolate in 0.12.0 scipy/interpolate/interpolate.py

### ISSUE THREAD

**Issue by rhewett** [scipy/scipy#2621] opened 2013-07-08 13:31 UTC
When commit https://github.com/scipy/scipy/commit/0d906d0fc54388464603c63119b9e35c9a9c4601 was made, the `interp1d.y` attribute in the interp1d class was replaced with `interp1d._y` for compatibility with the polynomial interpolators.

However, the `interp1d.y` attribute is still set, and has different (transposed) behavior than before.  Moreover, changing `interp1d.y` does not change `interp1d._y` (and vice versa), leading to the issue that caused me to find this. 

I can think of two potential fixes:
1) Completely remove interp1d.y (i.e., removing line 347 of  scipy/interpolate/interpolate.py)
2) Making `interp1d.y` a property that writes to and returns `interp1d._y`

**Comment by ev-br** [comment] 2019-08-05 12:47
OK, a regression in scipy 0.12, no matter how bad, is no longer relevant. There was no further request for `set_y` or `append_points` or anything of this sort since 2013. If there's a use case, a new issue would be helpful.
Closing. Thanks all.

**Closed by ev-br** 2019-08-05 12:47 UTC
Labels: enhancement, prio-normal, scipy.interpolate
