### ISSUE TITLE
BUG: CubicSpline segfaults when passing empty values for `y`with numpy >=1.23

### ISSUE THREAD

**Issue by ocefpaf** [scipy/scipy#17241] opened 2022-10-17 14:00 UTC
### Describe your issue.

While the docs are clear and the values for `y` must be finite, one could pass empty array and, some iterative interpolations we had in our code that relied on that behavior, "worked."

We fixed our code to return a ValueError now instead of relying on that behaviour. However, b/c the old code segfaults, maybe some checks should be in place in SciPy to avoid empty `y` values. Please feel free to close this issue if this doesn't make sense.

### Reproducing Code Example

```python
from scipy.interpolate import CubicSpline
import numpy as np

# Segfaults on my machine when it reaches size>=10 but passes with <10.
x = np.arange(10)

y = np.empty(len(x)) * np.NaN
y_no_nans = y[~np.isnan(y)].reshape(y.shape[0], -1)

# In our code y_no_nans was slowly iterated to reach valid finite value and worked for numpy <1.23.
spline = CubicSpline(x, y_no_nans, bc_type='periodic')
```

### Error message

```shell
Sometimes it segfaults, sometimes it "works" :-/
```

### SciPy/NumPy/Python version information

1.9.1 1.23.3 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment] 2022-10-17 16:51
I can reproduce the segfault with `CubicSpline`.

Raising an exception when `y` has a zero dimension is probably the simplest way to avoid the problem.

On the other hand...

Consider the "normal" behavior, where an 1-d array `x` with shape (n,) and a 2-d array `y` with shape (n, m) are passed to `CubicSpline` to create a callable object `spline`.   `spline` accepts a scalar and returns an array with shape (m,), and more generally, `spline` accepts an array with shape (n1, n2, ..., nk) and returns an array with shape (n1, n2, ..., nk, m).

Nothing in that description requires m > 0.  One can define a consistent API that handles `m = 0` exactly the same as `m > 0`.  If a caller handles arrays with a 0 dimension consistently, then it would be nice for `CubicSpline` to also handle it consistently.

**Comment by ev-br** [comment] 2022-10-17 18:31
What would your API  suggestion, Warren? 

For me, the current scipy main + some older numpy does, in the OP example:

```
In [2]: spline(1)
Out[2]: array([], dtype=float64)

In [3]: spline([1, 2, 3])
Out[3]: array([], shape=(3, 0), dtype=float64)
```

W.r.t., @ocefpaf 's question on where to add the logic: `prepare_input` in cubic.py sounds like a right place. It will be affecting pchip/akima as well, but I think `array([], shape=(10, 0), dtype=float64)` is a useful evaluation result.
Regardless of the decision, the behavior should be tested, and a good place for tests seems to be this file:
https://github.com/scipy/scipy/blob/main/scipy/interpolate/tests/test_polyint.py

**Comment by WarrenWeckesser** [comment] 2022-10-17 21:29
@ev-br, the description that I gave above is the API that I suggest.  And as your example shows, it looks like that is what `CubicSpline` and `pchip` already do, in most cases.  I hadn't tried it with the default boundary conditions of `CubicSpline`  when I made my earlier comment--sorry for not digging deeper.  For example, this works as I would expect:

```
In [13]: spline = CubicSpline(np.arange(10), np.ones((10, 0)))

In [14]: spline(3.4)
Out[14]: array([], dtype=float64)

In [15]: spline([[1, 1.5], [2, 2.5]]).shape
Out[15]: (2, 2, 0)
```

So I think the we just need tests for cases where a dimension of `y` has length 0, and make appropriate fixes for anything that fails.

The problems that I see are:

* `CubicSpline` crashes Python when `bc_type` is `'periodic'` and `y` has a dimension of length 0.  Sometimes it crashes right away, and other times it will appear to work for a while before crashing.  I just ran an ipython session where I repeatedly did `spline = CubicSpline(np.arange(10), np.ones((10, 0)))` without an error, but I got a segfault when I exited ipython.
* `CubicSpline` raises an exception when `y` has a shape such as `(n, 0, 3)`, for any `bc_type`.  For example,

  ```
  In [7]: spline = CubicSpline(np.arange(10), np.ones((10, 0, 3)))
  ---------------------------------------------------------------------------
  ValueError                                Traceback (most recent call last)
  ValueError: unexpected array size: size=30, arr_size=0, rank=2, effrank=2, arr.nd=3, dims=[ 10 3 ], arr.dims=[ 10 0 3 ]
  
  
  The above exception was the direct cause of the following exception:
  
  ValueError                                Traceback (most recent call last)
  <ipython-input-7-a91cf816d08c> in <cell line: 1>()
  ----> 1 spline = CubicSpline(np.arange(10), np.ones((10, 0, 3)))
  
  ~/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/interpolate/_cubic.py in __init__(self, x, y, axis, bc_type, extrapolate)
      784                     b[-1] = 0.5 * bc_end[1] * dx[-1]**2 + 3 * (y[-1] - y[-2])
      785 
  --> 786                 s = solve_banded((1, 1), A, b, overwrite_ab=True,
      787                                  overwrite_b=True, check_finite=False)
      788 
  
  ~/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/_basic.py in solve_banded(l_and_u, ab, b, overwrite_ab, overwrite_b, check_finite)
      455         d = a1[1, :]
      456         dl = a1[2, :-1]
  --> 457         du2, d, du, x, info = gtsv(dl, d, du, b1, overwrite_ab, overwrite_ab,
      458                                    overwrite_ab, overwrite_b)
      459     else:
  
  ValueError: failed in converting 4th argument `b' of _flapack.dgtsv to C/Fortran array

  ```
  But it handles a shape such as `(n, 1, 3)` just fine.

**Comment by ev-br** [comment] 2022-10-18 06:07
Okay, as long as numpy allows zero-sized arrays of various shapes (are there no plans for numpy changing this?), we probably should, too.
Since this used to work for the OP downstream example, and other interpolators either return a zero-sized array or raise, there does not seem to be a backwards compat concern. 

The behavior should be uniform across CubicSpline with varying boundary conditions, make_interp_spline, PchipInterpolator and Akima1DInterpolator.

The test for the desired behavior could then look roughly like

```
x = np.arange(10)
y1 = np.zeros(10, 0, 5)
y2 = np.zeros(10, 5, 0)
xval = np.arange(3)

for y in [y1, y2]:
   for obj = [CubicSpline(x, y), PchipInterpolator(x, y), Akima1DInterpolator(x, y), make_interp_spline(x, y)]:
          # TODO: add b.c. for CubicSpline and make_interp_spline, at least 'bc_type="periodic"'
          assert obj(xval).size == 0
          assert obj(xval).shape == xval.shape + y.shape[1:]
```

Warren, is this what you have in mind?

-----------------------

Implementation-wise, zero-sized inputs should be caught early, before they are fed to either fortran or cython code. Once `y.size == 0` is detected, an interpolator should shortcut to constructing a synthetic `.c` array with the right shape. This should probably be done at each interpolator right after the call to `prepare_input`. Here's what pchip does in the example above:

```
In [31]: pchip(x, y).c
Out[31]: array([], shape=(4, 9, 5, 0), dtype=float64)

In [32]: pchip(x, y2).c
Out[32]: array([], shape=(4, 9, 0, 5), dtype=float64)
```

It is probably easiest to start with the CubicSpline, and I can help with the other ones (BPoly.from_derivatives and make_inter_spline), once the first implementation is there. Would you be interested in updating gh-17245 or sending an alternative PR @ocefpaf ?

**Comment by ev-br** [comment] 2022-10-20 11:19
Here's a possible start: https://github.com/scipy/scipy/compare/main...ev-br:zero-size-arrays?expand=1
ATM it works for make_interp_spline and pchip, need to fix up CubicSpline and Akima1DInterpolator.
@ocefpaf feel free to take over this branch or replicate it, whichever works for you.

**Comment by ocefpaf** [comment] 2022-10-20 12:06
> @ocefpaf feel free to take over this branch or replicate it, whichever works for you.

I'll give it a try this week and, if fail, I'll step away to avoid holding this for much longer and close that PR. Thanks for the guidance!

**Comment by WarrenWeckesser** [comment] 2022-10-27 00:56
@ev-br, getting back to your [comment](https://github.com/scipy/scipy/issues/17241#issuecomment-1281857289): yes, that looks like it would be a reasonable test that the interpolators handle a `y` array that has a dimension with length 0.

It would be good to have also a similar test where `axis` is not the default 0.

**Comment by ev-br** [comment] 2022-10-29 13:24
OK, https://github.com/scipy/scipy/pull/17305 implements the suggested API with an intent to close this issue. Reviews would be appreciated.

**Closed** 2022-11-26 23:08 UTC
Labels: defect, enhancement, scipy.interpolate

**Comment by ev-br** [comment] 2022-11-27 06:41
@ocefpaf heads up:  https://github.com/scipy/scipy/pull/17305 is in, thank you for working on this!
