### ISSUE TITLE
Fitting stats distributions with starting shape parameters

### ISSUE THREAD

**Issue by robertsawko** [scipy/scipy#6977] opened 2017-01-20 14:19 UTC
I am testing the fitting functionality of scipy. I noticed that I can fix certain shape parametrs, fix the `loc` and `scale`, as well as give starting points for `scale` and `loc`. Is it also possible to give starting positions for shape parameters? Simply put I'd like to be able to specify `s` in the following example

```python
from scipy.stats import lognorm

scale = 1.0
loc = 1.0
s = 2.0

data = lognorm(s=s, loc=loc, scale=scale).rvs(100)

params = lognorm.fit(data, loc=loc, scale=scale)
print(params)
```

**Comment by ev-br** [comment] 2017-01-25 16:15
`lognorm.fit(data, s, loc=loc, scale=scale)` should work. 
I'm going to close this as a duplicate of https://github.com/scipy/scipy/issues/6967 and https://github.com/scipy/scipy/issues/5362
If you feel like working on it @robertsawko, it'd be appreciated.

**Closed by ev-br** 2017-01-25 16:15 UTC
