### ISSUE TITLE
Applying interp2d to large (40k-by-90k) arrays?

### ISSUE THREAD

**Issue by xiumingzhang** [scipy/scipy#7663] opened 2017-07-26 20:57 UTC
I have no problems interpolating over small arrays like this.

```
import numpy as np
from scipy.interpolate import interp2d

x = np.arange(900)
y = np.arange(400)
z = np.random.randint(-1000, high=1000, size=(400, 900))
f = interp2d(x, y, z, kind='linear')
# No errors
```

But errors are produced when `x`, `y` and `z` are large, as shown below.

### Reproducing code example:
```
import numpy as np
from scipy.interpolate import interp2d

x = np.arange(90000)
y = np.arange(40000)
z = np.random.randint(-1000, high=1000, size=(40000, 90000))
f = interp2d(x, y, z, kind='linear')
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/software/Anaconda3-4.3.1-Linux-x86_64/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 225, in __init__
    kx=kx, ky=ky, s=0.0)
dfitpack.error: (len(z)==mx*my) failed for 3rd argument z
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.19.1 1.12.1 sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
```

**Comment by pv** [comment] 2017-07-26 21:08
Needs using 64-bit integers in fortran.

**Comment by xiumingzhang** [comment] 2017-07-26 21:10
@pv Thanks a ton for your very prompt reply!

Could you elaborate a bit? Is this some flag that I should specify when I installed my scipy?

**Comment by pv** [comment] 2017-07-26 21:18
I'm afraid this is not supported right now, and is a bit bigger project to fix. In addition to the compiler flags (or perhaps better, adding relevant kind= declarations to the fortran sources), also updating the f2py definitions is necessary.

**Comment by xiumingzhang** [comment] 2017-07-26 21:20
@pv  Good to know -- thanks!  It's fine. I can always slice my array into smaller pieces and do `interp2d` piece by piece, since `interp2d` with `kind=linear` is a local operation.

**Comment by pv** [comment] 2017-07-26 21:21
If you're happy with bilinear, this may be of interest as an alternative: https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interpn.html

**Comment by xiumingzhang** [comment] 2017-07-26 21:24
@pv How is this different from `interp2d` with `kind=linear`? I thought that was just bilinear?

Am I right that to interpolate the value at `(x, y)`, I just simply need to feed `(x, y)`'s four neighbor pixel values into `interp2d` with `kind=linear`?

**Comment by pv** [comment] 2017-07-26 22:18
Whether interp2d is same as bilinear is more complex question, because it's Diercx's more general tensor product spline algorithm with automatic knot selection, running with order=1 splines. I don't know if it picks knots that coincide with grid points.

**Comment by sethtroisi** [comment] 2020-05-15 04:17
Underlying issue is requirement for 64 bit fortran, which is supported in some systems now (?)

Using my largest machine 64GB of ram and wasn't able to run a 40k by 90x but did manage a smaller 40k x 30k interp2d.

**Comment by pv** [comment] 2020-05-15 08:34
Let's reopen --- this would be possible to fix now that the 64-bit f2py support is in, but it's not done yet.

**Comment by sethtroisi** [comment] 2020-05-15 09:59
Can you outline what needs to be done?

I started by changing some of the indexes to integer*8 (not even sure if this is the right type)

https://github.com/scipy/scipy/compare/master...sethtroisi:interpolate_f_64?expand=1

This causes the code to no longer fail with `dfitpack.error: (len(z)==mx*my) failed for 3rd argument z` but my server OOMs before finishing so IDK if it actually works

**Comment by pv** [comment] 2020-05-15 10:03
See the ilp64 pull requests. You'll need to change the build setup. No changes in fortran code or f2py wrappers should be made.

**Comment by tueda** [comment] 2021-04-13 09:41
It would be nice if this can be fixed. I got `dfitpack.error: (len(z)==mx*my) failed for 3rd argument z` for `RectBivariateSpline`.

**Comment by ev-br** [comment] 2022-04-29 17:49
Given that the issue is about linear interpolation on regular grids, I'd start with checking the status of the OP with `RegularGridInterpolator` / `interpn` instead of `interp2d`. Specific things to check:
- whether it actually works on these large problem sizes
- whether the performance is OK, and if not if it can be improved

**Comment by Kai-Striega** [comment] 2022-05-01 06:07
@ev-br I'd be happy to look at this once the issues I'm working on with Matt are done.

**Comment by Kai-Striega** [comment] 2022-06-05 06:46
@ev-br I've got time to look at this now. I may need some more guidance, as I've never worked with the interpolate stuff before.

**Comment by ev-br** [comment] 2022-06-07 07:10
@Kai-Striega great! Here's a quickstart:

```
$ ipython log_interp2d_rgi.py 
39.1 µs ± 221 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
13.8 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
23.4 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
155 µs ± 313 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

where

```
$ cat log_interp2d_rgi.py 
# coding: utf-8
import numpy as np
from scipy.interpolate import interp2d, RegularGridInterpolator as RGI
nx, ny = 10, 20
x = np.arange(nx)
y = np.arange(ny)
rng = np.random.default_rng(12345)
z = rng.uniform(size=(ny, nx))       # note (ny, nx) not (nx, ny)

# interp2d
f = interp2d(x, y, z, kind='linear')

f(x, y)
np.all(f(x, y) == z)

get_ipython().run_line_magic('timeit', "f = interp2d(x, y, z, kind='linear')")
get_ipython().run_line_magic('timeit', 'f(x, y)')


# RGI
rgi = RGI((x, y), z.T, method='linear')   # note the transpose

xg, yg = np.meshgrid(x, y, indexing='ij', sparse=True)
np.all(rgi((xg, yg)) == z.T)

get_ipython().run_line_magic('timeit', 'rgi = RGI((x, y), z.T, method="linear")')
get_ipython().run_line_magic('timeit', 'rgi((xg, yg))')
```

So RGI evaluation is an order of magnitude slower on this toy-sized problem :-). It'd be helpful to check how does this scale: does RGI handle larger problem sizes? how does its performance compare to interp2d?

On my machine the OP the fails to allocate the `z` array, so the OP is a bit extreme :-). I'd start by checking if RGI can handle a problem size at a local limit of interp2d.

**Comment by ev-br** [comment] 2022-06-13 20:54
Ouch. MemoryErrors nonwithstanding, I think it's pretty clear that RGI evaluation could/should be investigated. At the moment it's pure python (https://github.com/scipy/scipy/blob/main/scipy/interpolate/_rgi.py#L346 and https://github.com/scipy/scipy/blob/main/scipy/interpolate/_rgi.py#L418) so I'm guessing there is quite a bit of a room for improvement. I'd go for cython but maybe it's a case for pythran, too.

For cythonization of this, once can probably reuse bits and pieces from https://github.com/scipy/scipy/blob/main/scipy/interpolate/_ppoly.pyx --- e.g. an np.searchsorted analog etc.

**Comment by Kai-Striega** [comment] 2022-06-15 12:57
Thanks, I'm going to give cython a go. I'm pretty busy over the next few days, but I'll get working on this over the weekend.

**Comment by Kai-Striega** [comment] 2022-06-19 07:40
@ev-br I may need some help setting up Cython to work with SciPy. I'm following [Adding Cython to SciPy](https://docs.scipy.org/doc/scipy/dev/contributor/cython.html#adding-cython-to-scipy) from that tutorial: 

> Include your code in a file with a .pyx extension rather than a .py extension. All files with a .pyx extension are automatically converted by Cython to .c files when SciPy is built.

I'm copying all of ``_rgi.py`` into a new file ``_rgi_cython.pyx`` and trying to build it using the ``dev.py`` interface. Do you know if something has changed since the tutorial was written?

**Comment by ev-br** [comment] 2022-06-19 07:49
Yup, turns out this tutorial part is stale ---  with the new meson stuff, you need to add a new cython source to the `interpolate/meson.build` file. I'd start by parroting the '_ppoly.pyx' part. BTW, you are probably exactly the right person to update that tutorial once you get the build running!

Also, I don't think compiling the whole `_rgi.pyx` is the right thing to do. Typically it's better to separate individual functions to cythonize, there's not much point cythonizing things which are not a bottleneck. cf how `_ppoly` works: the PPoly class is in python, and some of its computational routines delegate to `_ppoly.pyx` routines.

**Comment by ev-br** [comment] 2022-06-22 07:55
cross-ref https://github.com/scipy/scipy/pull/16449

**Comment by Kai-Striega** [comment] 2022-06-26 06:16
I've been able to separate the functions  `_evaluate_linear` and `_find_indices` into Cython and have them compile. This hasn't led to any measurable performance increase. On its own, this is expected. But I'm struggling to gain any performance increase even after adding types. This is due to the highly dynamic nature of the code (I think) e.g. we're passing variable length lists of NumPy arrays. I think this is going to involve more refactoring than I first expected and is going to take a bit longer.

**Comment by ev-br** [comment] 2022-06-26 08:22
Do you want to link your code as a draft PR? Then we could move the discussion over there if that's helpful

**Comment by ev-br** [comment] 2022-11-06 09:10
The original `dfitpack.error: (len(z)==mx*my) failed for 3rd argument z for RectBivariateSpline` is blocked on the ILP64 Fortran support in meson builds and is tracked in https://github.com/scipy/scipy/issues/15156.

The recommended alternative, `RegularGridInterpolator(..., method="linear")`, has been sped up considerably in gh-17291, and further improvements are tracked in gh-17356.
Contributing to the latter issue is *very* welcome! Both test-driving the RGI linear code (if you do, please report your findings!) and implementing individual improvements listed in gh-17356.

This issue can I think be closed as a duplicate. Thanks all.

**Closed by ev-br** 2022-11-06 09:10 UTC
Labels: enhancement, task, scipy.interpolate
