### ISSUE TITLE
Add chirp Z-transform, zoom FFT

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#4288] opened 2014-12-18 03:20 UTC
As mentioned in numpy/numpy/issues/1177, Chirp Z-transform and special cases of it have been submitted to SciPy under public domain by Paul Kienzle and Nadav Horesh:  [[SciPy-user] Chirp Z transform](http://mail.scipy.org/pipermail/scipy-user/2009-March/020331.html) 

The special cases of CZT are zoom FFT and "scaled FFT" (not sure what that does).  DFT is also a special case of CZT, so if you call `czt(data)` with the default options, it's an FFT, but faster for prime sizes because of Bluestein's algorithm, useful in `resample` for instance? (#3956):

```
x = rand(42073) # prime length

allclose(czt(x), fft(x))
Out[37]: True

timeit czt(x)
10 loops, best of 3: 53.9 ms per loop

timeit fft(x)
1 loops, best of 3: 2.35 s per loop

2.35 / 53.9e-3 # speedup factor
Out[40]: 43.59925788497217
```

@stefanv said:

> Thank you both for the contribution!  I've reviewed the code and think
> it should be included in SciPy.  Would someone else like to have a
> look before I commit it?
> 
> Where would the best place for this be?  scipy.fftpack?

I think it makes sense to put it in scipy.fftpack, too, though that doesn't have any classes, just functions.  (Unless it should all be put in numpy, but I'm guessing zoom FFT is too specialized for that?)

**Comment by GregoryEAllen** [comment] 2015-02-19 23:42
I would argue that it should be a function. I get that it's an optimization, but it's like a complete API paradigm shift.
Should it have axis=-1 as a param, like the many other transforms?

**Comment by endolith** [comment] 2015-02-22 17:44
So I guess it's creating large signals that it needs to convolute with (like `myczt._Fwk2`), so it probably does make more sense to generate the functions from a class rather than caching long signals.

It is much faster for prime lengths, but also much noisier:

```
timeit fft(sig)
1 loops, best of 3: 14.9 s per loop

timeit czt(sig)
10 loops, best of 3: 123 ms per loop
```

![noise floor n 100003](https://cloud.githubusercontent.com/assets/58611/6319563/18db2170-ba8e-11e4-933c-e957ac06cb03.png)

```
N = 100003

sig = ones(N)
F = fft(sig)
C = czt(sig)

plt.plot(20*log10(abs(F/N)), label='fft')
plt.plot(20*log10(abs(C/N)), label='czt')
plt.margins(0, 0.1)
plt.legend()
plt.title('N = {}'.format(N))
plt.ylabel('dB')
```

When I tried to interpolate to larger size, it has errors, too:

```
n = 1000
m = 100000

sig = randn(n)
F = fft(sig, m)
C = czt(sig, m)

plt.plot(abs(F), alpha=0.3, lw=5, label='fft')
plt.plot(abs(C), '.-', label='czt')
plt.legend()
print(allclose(F, C))
```

![interpolation doesn t match](https://cloud.githubusercontent.com/assets/58611/6319611/565cd7da-ba90-11e4-8da5-8c655e6d6055.png)

**Comment by ewmoore** [comment] 2015-03-06 21:03
At least part of the problem is in lines 91-98 of czt.py.  This not a good way to calculate `wk2`.  For your `N = 10003` example there is overflow in squaring k.  It'll be slower, but a better way to do this would be to move all of this calculation into the exp to start with.

**Comment by endolith** [comment] 2015-03-09 00:51
Any idea what this is for?

```
if w is None:
    w = cmath.exp(-1j*pi/m) 
```

The default of w is not None, it's 1, which makes it:

```
    w = cmath.exp(-2j*pi/m)
```

So this branch would never be reached unless someone specifically said `w=None`, and it would behave differently than if they omitted `w`.

**Comment by endolith** [comment] 2015-03-10 01:12
@ewmoore : Ah, you're right:

![fft-czt vs k 2](https://cloud.githubusercontent.com/assets/58611/6567409/5ed019e0-c69d-11e4-8766-298f6abde9f7.png)

But the exp form of the chirp still has k^2 in it.  For instance, `_Awk2` can be written as `A**-k * exp(k^2/2 * log(w))`, but that still has k^2 in it.  The phase can be wrapped?

**Comment by endolith** [comment] 2015-03-19 03:24
Ok, I improved the accuracy when using frequency scaling factor (which should be renamed from `factor=`?).  I don't think it can be improved when using `w=`, since the error in the output is due to the accumulation of error in `w` itself.

**Comment by rega0051** [comment] 2019-03-19 13:36
Was this ever merged? It seems like it was discussed prior to scipy v1.0 but was never merged, but in looking through the various posts I don't see any showstoppers.

**Comment by endolith** [comment] 2019-03-19 18:51
@rega0051 No, see https://github.com/scipy/scipy/pull/4607    There are some questions about the best function interface too, if you want to give feedback.

**Comment by mreineck** [comment] 2019-08-16 18:30
With the switch to `pocketfft`(which automatically uses Bluestein's algorithm when useful), this is most likely no longer needed for prime-sized FFTs.

For the CZT itself I'll be happy to help with any necessary adjustments to the new FFT infrastructure.

**Comment by rgommers** [comment] 2019-08-17 00:23
Awesome, thanks @mreineck. And thanks @endolith for all your work on this! and everyone else for pitching in!

**Closed by rgommers** 2019-08-17 00:23 UTC
Labels: enhancement, scipy.fftpack

**Comment by mreineck** [comment] 2019-08-17 07:01
Not sure whether this can already be closed ... the CZT part is not in `scipy` yet. Or is it sufficient to just have #4607 open?

**Comment by rgommers** [comment] 2019-08-17 17:37
Yes, gh-4607 is enough. Feature request issues are good for discussion, but no need to keep them open once there's a PR.

Issues our mainly for bugs, our bug count (discovered + undiscovered) is finite, while potential new feature count is infinite:)
