### ISSUE TITLE
TypeError: buffer is too small for requested array when reading file with io.loadmat

### ISSUE THREAD

**Issue by mmagnuski** [scipy/scipy#5516] opened 2015-11-22 00:18 UTC
I was trying to load an eeglab `.set` file - (which is just a `.mat` file) using `io.loadmat`, 
```python
eeg = io.matlab.loadmat(os.path.join(pth, fls[3]))
```
however I get this error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-464c30aa9ce2> in <module>()
----> 1 eeg = io.matlab.loadmat(os.path.join(pth, fls[3]))

c:\Miniconda3\lib\site-packages\scipy\io\matlab\mio.py in loadmat(file_name, mdict, appendmat, **kwargs)
    133     variable_names = kwargs.pop('variable_names', None)
    134     MR = mat_reader_factory(file_name, appendmat, **kwargs)
--> 135     matfile_dict = MR.get_variables(variable_names)
    136     if mdict is not None:
    137         mdict.update(matfile_dict)

c:\Miniconda3\lib\site-packages\scipy\io\matlab\mio5.py in get_variables(self, variable_names)
    290                 continue
    291             try:
--> 292                 res = self.read_var_array(hdr, process)
    293             except MatReadError as err:
    294                 warnings.warn(

c:\Miniconda3\lib\site-packages\scipy\io\matlab\mio5.py in read_var_array(self, header, process)
    250            `process`.
    251         '''
--> 252         return self._matrix_reader.array_from_header(header, process)
    253 
    254     def get_variables(self, variable_names=None):

scipy\io\matlab\mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy\io\matlab\mio5_utils.c:6724)()

scipy\io\matlab\mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy\io\matlab\mio5_utils.c:6200)()

scipy\io\matlab\mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_struct (scipy\io\matlab\mio5_utils.c:9453)()

scipy\io\matlab\mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (scipy\io\matlab\mio5_utils.c:5727)()

scipy\io\matlab\mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy\io\matlab\mio5_utils.c:6098)()

scipy\io\matlab\mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_char (scipy\io\matlab\mio5_utils.c:8245)()

TypeError: buffer is too small for requested array
```

I am using windows 7, python 3 and scipy 16.
My `conda info`:
```
Current conda install:

             platform : win-64
        conda version : 3.18.5
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : C:\Miniconda3  (writable)
  default environment : C:\Miniconda3
     envs directories : C:\Miniconda3\envs
        package cache : C:\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

It is worth noting that the same file can be read using `MAT.jl` package in Julia.

The file can be downloaded from [here](https://www.dropbox.com/sh/ek2dbhskfiurklx/AACEIgA_ywA_SW4MsQt7NgMJa?dl=0)

**Comment by agramfort** [comment] 2016-06-11 08:38
problem only occurs on Python 3.5 for me. It works fine in python 2.7

Files are at:

https://www.dropbox.com/sh/ek2dbhskfiurklx/AACEIgA_ywA_SW4MsQt7NgMJa?dl=0

```
from scipy import io
io.loadmat('faces_e_22.set')
```

to replicate

cc @matthew-brett

**Comment by matthew-brett** [comment] 2016-06-12 01:58
The problem is a struct field `EEG['history']`.   It is a character field that is encoded in uint16 values.  The problem is, that I don't know any good way of guessing the codec for these.  The current scipy way is to use the result of `sys.getdefaultencoding()`.  This is `ascii` on Python 2 and `utf-8` on Python 3, at least on my system.   Trying to decode the `history` byte string with `utf-8` drops a couple of characters, so the declared length of the array is [1, 1096], but the actual length of the unicode string is 1094 after decoding, hence the buffer error.

You can decode the file correctly with:

```
res = sio.loadmat('../Downloads/faces_e_22.set', uint16_codec='ascii')
```

I guess it would be reasonable to switch the uint16 encoding to `latin1` by default, but it might break people's code, or at least cause changes in the output string.

**Comment by matthew-brett** [comment] 2016-06-12 02:13
The [matfile format documentation](http://www.mathworks.com/help/pdf_doc/matlab/matfile_format.pdf) says

```
For character data that is not Unicode encoded, the Data Type 
part of the Tag field should be set to miUINT16.
```

I'm not sure what characters you can have in character data that is not Unicode encoded.

**Comment by agramfort** [comment] 2016-06-12 06:41
io.loadmat('faces_e_22.set', uint16_codec='latin1')

works for me.

thanks @matthew-brett for taking a look.

you can close the issue. We're going to expose the uint16_codec param in MNE function.

**Comment by Eric89GXL** [comment] 2016-06-12 10:41
Thanks for checking @agramfort

**Closed by Eric89GXL** 2016-06-12 10:41 UTC
Labels: scipy.io

**Comment by mmagnuski** [comment] 2016-06-12 14:17
Thanks for help @matthew-brett @agramfort, it works well now!
