### ISSUE TITLE
Incorrect work of scipy.fftpack.fft

### ISSUE THREAD

**Issue by IVN-tone** [scipy/scipy#13185] opened 2020-12-01 18:51 UTC
Hello everyone!

I found some strange (if I'm not mistaken) problem of using scipy.fftpack.fft. I tried to analyze 2 pulses with different widths (4 us and 10 ns) and got the same output result in the frequency domain (see attached). But according to the symmetry property of Fourier transform: the shorter the pulse, the wider it in the frequency domain. Is it correct for scipy.fftpack.fft (sampling is 1e9)?

![Pulses](https://user-images.githubusercontent.com/54066396/100783697-27b90700-341f-11eb-9206-9201ce5153de.jpg)

![Spectra](https://user-images.githubusercontent.com/54066396/100783718-2ee01500-341f-11eb-9f39-e2fc3d89b5b5.jpg)

**Comment by peterbell10** [comment] 2020-12-01 21:13
@IVN-tone please follow the issue template. What code produced those graphs and what version of SciPy are you using?

**Comment by IVN-tone** [comment] 2020-12-02 07:43
@peterbell10 my scipy version is 1.4.1. The code is following:

`from scipy import fftpack

X = fftpack.fft(my_rectangular_pulse_long)
freqs = fftpack.fftfreq(len(my_rectangular_pulse_long)) * (1e9)

Y = fftpack.fft(my_rectangular_pulse_short)
freqs1 = fftpack.fftfreq(len(my_rectangular_pulse_short)) * (1e9)

fig, (ax1,ax2) = plt.subplots(1,2)

ax1.stem(freqs, np.abs(X),use_line_collection=True)
ax2.stem(freqs1, np.abs(X),use_line_collection=True)
ax1.set_xlabel('Frequency in Hertz [Hz]')
ax1.set_ylabel('Frequency Domain (Spectrum) Magnitude')
ax2.set_xlabel('Frequency in Hertz [Hz]')
ax2.set_ylabel('Frequency Domain (Spectrum) Magnitude')

ax1.set_title('4 us')
ax2.set_title('10 ns');`

`my_rectangular_pulse_long` and `my_rectangular_pulse_short` are simple rectangular pulses of 4 us and 10 ns duration.

**Comment by mreineck** [comment] 2020-12-02 10:20
> `my_rectangular_pulse_long` and `my_rectangular_pulse_short` are simple rectangular pulses of 4 us and 10 ns duration.

Sorry, at least for me this is not sufficiently clear to reproduce these objects.
I assume they are numpy arrays. But to run the code we need to know the data type, the length, and the values.

**Comment by IVN-tone** [comment] 2020-12-02 13:11
@mreineck please, see below:

```
from scipy import fftpack

sampling_rate = 1e9
pulse_duration_1 = 20e-6
pulse_duration_2 = 4e-6

def rectangular(t, scaling): 
    return len(t)*[scaling]

def rectangular_pulse(start_time, pulse_duration):
    stop_time = pulse_duration
    wave_length = np.ceil(sampling_rate*pulse_duration)
    t = np.linspace(0,(wave_length-1)/sampling_rate,int(wave_length))
    rp_s = int(max(round(start_time*sampling_rate)+1,1))
    rp_e = int(min(round(stop_time*sampling_rate)+1,wave_length))
    rect_wave = np.asarray(rectangular(t,1))
    rect_wave[0:rp_s] = 0
    rect_wave[rp_e-1:] = 0
    return rect_wave

my_rectangular_pulse_long = rectangular_pulse(0, pulse_duration_1)
my_rectangular_pulse_short = rectangular_pulse(0, pulse_duration_2)

X = fftpack.fft(my_rectangular_pulse_long)
freqs = fftpack.fftfreq(len(my_rectangular_pulse_long))*(1e9)

Y = fftpack.fft(my_rectangular_pulse_short)
freqs1 = fftpack.fftfreq(len(my_rectangular_pulse_short))*(1e9)

fig, (ax1,ax2) = plt.subplots(1,2)

ax1.stem(freqs, np.abs(X),use_line_collection=True)
ax2.stem(freqs1, np.abs(Y),use_line_collection=True)
ax1.set_xlabel('Frequency in Hertz [Hz]')
ax1.set_ylabel('Frequency Domain (Spectrum) Magnitude')
ax2.set_xlabel('Frequency in Hertz [Hz]')
ax2.set_ylabel('Frequency Domain (Spectrum) Magnitude')

# ax1.set_xlim(-1e8,1e8)
# ax2.set_xlim(-1e8,1e8)
# ax1.set_ylim(0,20)
# ax2.set_ylim(0,20)
ax1.set_title('20 us')
ax2.set_title('4 us')

plt.tight_layout();
```

I tried here pulses of 4 us and 20 us:
![Pulses](https://user-images.githubusercontent.com/54066396/100876541-926a5100-34b8-11eb-8175-e31a865a6a0b.png)

![FFT](https://user-images.githubusercontent.com/54066396/100876549-95fdd800-34b8-11eb-837d-5dcc00ab510e.png)

One thing, which is clear here it's that after FFT the amplitudes are proportional to the pulses widths in the time domain, but the spectra look the same.

**Comment by mreineck** [comment] 2020-12-02 13:45
If I understand it correctly, the two arrays have different lengths and have the value of 1, except in the first and last entry, where they are 0.
What the FFT computes for you from these inputs is the spectrum of a (periodic!) signal that is 1 almost everywhere, with a very short dip to 0 in one place. As far as I can tell, this is not what you want.
If you want the spectrum of a single pulse, you will have to use the (non-discrete) Fourier transform; FFT is most likely not going to help you with that.
On the other hand, if you want the spectrum of a periodic pulse, you not only need to provide the "pulse" to the FFT but also the entire rest of the periodic interval (i.e. zeros. How many depends on the length of the interval).

I hope someone else can explain this better ... I'm not very good at this :-/

**Comment by peterbell10** [comment] 2020-12-02 14:01
Another attempt at explaining it: If you introduce periodic replicas of your input signal, it's just a constant with a rectangular pulse of 2 samples going down to zero. That's why the frequency response is so broad, because the pulse is actually very narrow in both cases.

If we include lots of zeros and make the inputs the same length:
```python
my_rectangular_pulse_long = np.zeros(1000)
my_rectangular_pulse_long[400:-400] = 1  # 200 sample pulse

my_rectangular_pulse_short = np.zeros(1000)
my_rectangular_pulse_short[450:-450] = 1  # 100 sample pulse
```

Then you can zoom in on the plots and make out the `sinc` function is broader for the short pulse:
![Figure_1](https://user-images.githubusercontent.com/13238737/100882035-97260980-34a6-11eb-8b65-a7f105911e46.png)

**Comment by peterbell10** [comment] 2020-12-02 14:02
There's no bug here, so I'll close the issue.

**Closed by peterbell10** 2020-12-02 14:02 UTC
Labels: scipy.fftpack

**Comment by IVN-tone** [comment] 2020-12-02 14:30
@peterbell10  thank you for a very good example, so am I right, one of the main things to do for correct usage of fftpack.fft is to have a (relatively) big part of zeros before and after the pulse?

**Comment by peterbell10** [comment] 2020-12-02 15:26
The FFT always treats a signal as periodic. If you pad either side (or both sides) of your signal with zeros then that periodic extension looks more like an isolated series of pulses. So, whether to pad depends on if your signal is really periodic or not.

**Comment by IVN-tone** [comment] 2020-12-03 10:25
@peterbell10 but here the signal is obviously non-periodic (just rectangular pulse) or do you mean in periodicity that we have the same (periodic) discretes by x-axis?

**Comment by mreineck** [comment] 2020-12-03 10:32
> but here the signal is obviously non-periodic

The signal that you pass to the FFT is assumed to be repeat periodically over and over; that's part of the FFT's definition.
This means that you may be only passing an array with a rectangular pulse, but what the FFT actually analyzes is an infinite repetition of these arrays, one after the other.

**Comment by IVN-tone** [comment] 2020-12-03 11:29
@mreineck I see, now it is more clear how it works, it is very similar to the Fourier series, thank you! Does the scipy library have function for single pulse analyzing (without reproducing it periodically as FFT does)?
