### ISSUE TITLE
Scipy.interpolate.griddata Error : Exception ignored in: 'scipy.spatial.qhull._Qhull.__dealloc__'

### ISSUE THREAD

**Issue by HiddenBeginner** [scipy/scipy#8850] opened 2018-05-20 15:26 UTC
I am sorry to my poor English in advance.
I wanted to learn scipy.interpolate.griddata, so I tried to do example code in scipy document.
But I encountered this error.

Following code is an example in scipy.interpolate.griddata document
### Reproducing code example:
```
import numpy as np
import scipy
from scipy.interpolate import griddata

def func(x, y):
    return x*(1-x)*np.cos(4*np.pi*x) * np.sin(4*np.pi*y**2)**2
grid_x, grid_y = np.mgrid[0:1:100j, 0:1:200j]
points = np.random.rand(1000, 2)
values = func(points[:,0], points[:,1])
grid_z2 = griddata(points, values, (grid_x, grid_y), method='cubic')

```

### Error message:
```
AttributeError                            Traceback (most recent call last)
AttributeError: 'NoneType' object has no attribute 'close'

Exception ignored in: 'scipy.spatial.qhull._Qhull.__dealloc__'
AttributeError: 'NoneType' object has no attribute 'close'
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-82f9e2c5b3ea> in <module>()
      7 points = np.random.rand(1000, 2)
      8 values = func(points[:,0], points[:,1])
----> 9 grid_z2 = griddata(points, values, (grid_x, grid_y), method='cubic')

C:\ProgramData\Anaconda3\envs\aerosol\lib\site-packages\scipy\interpolate\ndgriddata.py in griddata(points, values, xi, method, fill_value, rescale)
    224     elif method == 'cubic' and ndim == 2:
    225         ip = CloughTocher2DInterpolator(points, values, fill_value=fill_value,
--> 226                                         rescale=rescale)
    227         return ip(xi)
    228     else:

interpnd.pyx in scipy.interpolate.interpnd.CloughTocher2DInterpolator.__init__()

qhull.pyx in scipy.spatial.qhull.Delaunay.__init__()

qhull.pyx in scipy.spatial.qhull._Qhull.__init__()

messagestream.pyx in scipy._lib.messagestream.MessageStream.__init__()

OSError: Failed to open file b'C:\\Users\\\xec\x9d\xb4\xeb\x8f\x99\xec\xa7\x84\\AppData\\Local\\Temp\\scipy-p3glr7em'
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0) 
```

**Comment by LiangZhengyuCSU** [comment] 2019-04-10 11:17
I have encountered a similar problem when using scipy.spatial.Convexhull. have you find any solution now?

**Comment by Ghostkeeper** [comment] 2020-03-23 12:39
Thanks for the analysis, LiangZhengyuCSU! We've encountered this as well in our library that uses Scipy. However since this is being deployed with our library's users we are not able to change their  %TEMP% environment variables. Is there a way to communicate to Scipy specifically that it must use a different temp directory?

**Comment by rgommers** [comment] 2020-03-23 19:26
It's about this bit of code in `messagestream.pyx`:
```
        # Fall back to temporary files
        fd, filename = tempfile.mkstemp(prefix='scipy-')
        os.close(fd)
        self._filename = filename.encode(sys.getfilesystemencoding())
        self.handle = stdio.fopen(self._filename, "wb+")
        if self.handle == NULL:
            stdio.remove(self._filename)
            raise IOError("Failed to open file {0}".format(self._filename))
        self._removed = 0
```
That does indeed look a little funky.

@Ghostkeeper what does `sys.getfilesystemencoding()` say for you?

**Comment by rgommers** [comment] 2020-03-23 19:28
https://github.com/cython/cython/issues/1803#issuecomment-320029352 may be related

**Comment by rgommers** [comment] 2020-03-23 19:29
> Is there a way to communicate to Scipy specifically that it must use a different temp directory?

no there isn't

**Comment by Ghostkeeper** [comment] 2020-03-24 07:31
> @Ghostkeeper what does sys.getfilesystemencoding() say for you?

Sorry, I haven't been able to reproduce this myself. Our crash reporter finds this issue :(

**Comment by Ghostkeeper** [comment] 2020-03-24 07:38
This is the full error that I have:
![image](https://user-images.githubusercontent.com/2448634/77399905-a054c780-6daa-11ea-95b3-1fe1a7e3717b.png)

**Comment by rgommers** [comment] 2020-03-28 15:13
Looking into this some more:
- `MessageStream` is only used to communicate back error messages from the Qhull library to our Cython code.
- The only other place it's used is `optimize/_trlib`, for the same purpose.
- `open_memstream` is Linux-only; on other platforms that error message communication is done via a tmpfile.
- There's a potential solution to get an in-memory file for Windows instead at https://stackoverflow.com/questions/10305095/can-i-replace-a-call-to-open-memstream-with-a-malloc-and-an-implicit-cast. However not clear that things work on macOS or other platforms then.
- Maybe a better alternative solution is vendoring https://github.com/Snaipe/fmem, which has several in-memory `open_memstream` alternatives.
- Here's yet another lib, for macOS support: https://github.com/NimbusKit/memorymapping

We should do something about this, it's a very obscure error and using interpolation functions shouldn't fail even if it's a user machine issue like the default filesystem encoding being set wrong.

@pv any thoughts on the preferred solution?

**Comment by rgommers** [comment] 2022-07-02 11:20
Thanks for the reports everyone. This should be fixed by gh-16444.

**Closed by rgommers** 2022-07-02 11:20 UTC
Labels: defect, scipy.interpolate
