### ISSUE TITLE
BUG: winsorize nan policy

### ISSUE THREAD

**Issue by ari-stat** [scipy/scipy#15660] opened 2022-02-25 21:01 UTC
### Describe your issue.

nan handling in winsorize for 'omit' option does not work properly.  It seems to count nans as larger than any number, so if there are other large numbers they may not be winsorized.  In the example below, I have 108 numbers, and winsorizing at 1% level (so max and min should be winsorized).  The max (which is the last number in the array) is unchanged.

### Reproducing Code Example

```python
from scipy.stats.mstats import winsorize
import numpy as np

a = np.random.standard_normal(108)
a[0] = np.nan
a[-1] = 80

winsorize(a, limits=(0.01,0.01), nan_policy='omit')
```

### Error message

```shell
No error, but the last element of the output array is still 80, when it is clearly the largest element in the array.  The code seems to be treating nan as the largest element.
```

### SciPy/NumPy/Python version information

1.7.1 1.20.3 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by tupui** [comment] 2022-02-25 22:33
Hi @ari-stat, did you try to change the percentages? You might be on the limit as the function is working on percentiles.

**Comment by mdhaber** [comment] 2022-02-25 23:09
I do think there is a problem here. It will be fixed in the course of gh-14651. (The `nan_policy` of every `stats` function is subject to review because most of them have at least some undesirable/unexpected behaviors.) With that in mind, !@ari-stat, do you mind if I close this and add this (closed) issue to the tracker in gh-14651?

**Comment by tupui** [comment] 2022-02-26 11:09
Thanks @mdhaber but then let's close it and move to the other PR.

**Closed by tupui** 2022-02-26 11:09 UTC
Labels: defect, scipy.stats

**Comment by ari-stat** [comment] 2022-02-27 01:50
I saw the same issue at other percentiles as well, but using n=100+ and limit=0.01 makes the issue easier to see, because only one data point is winsorized.  Thanks.
