### ISSUE TITLE
BUG: Infinite loop in scipy.integrate.solve_ivp()

### ISSUE THREAD

**Issue by leoluecken** [scipy/scipy#17846] opened 2023-01-23 17:14 UTC
### Describe your issue.

`scipy.integrate._ivp.common.select_initial_step()` returns `numpy.nan` if `max(abs(y0)) == numpy.inf` 

This causes programs to lock, when calling `solve_ivp()` with such an initial value.

Probably, `select_initial_step()` (or its callers) should raise an Error in that situation.

### Reproducing Code Example

```python
Call `solve_ivp()` with at least one component of `y0` being infinite (probably a NaN component would cause the same problem).
```

### Error message

```shell
None, program goes into infinite loop, when calling `solve_ivp()`
```

### SciPy/NumPy/Python version information

1.9.3 1.23.5 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by leoluecken** [comment] 2023-01-23 17:27
The infinite loop is also triggered, when the corresponding value of `f0` (argument of `select_initial_step()`) has a NaN component. This should also be checked and fail, I guess.

**Comment by mdhaber** [comment] 2023-01-23 17:35
Thanks @leoluecken. This was reported in gh-11239, so I'll link this one there and close this.

**Comment by mdhaber** [comment] 2023-01-23 17:46
Actually I'll keep this open and close those one, since the discussuon in gh-11239 started with something we can't reproduce.

**Closed** 2023-04-22 07:13 UTC
Labels: defect, scipy.integrate
