### ISSUE TITLE
scipy.linalg test failures on python 3 in Wine

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5578] opened 2015-12-04 11:12 UTC
```
======================================================================
ERROR: test_basic.TestMatrixNorms.test_axis_kwd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\nose-1.1.2-py3.3.egg\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Python33\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "C:\Python33\lib\site-packages\scipy\linalg\tests\test_basic.py", line 1194, in test_axis_kwd
    b = norm(a, ord=np.inf, axis=(1, 0))
  File "C:\Python33\lib\site-packages\scipy\linalg\misc.py", line 165, in norm
    return np.linalg.norm(a, ord=ord, axis=axis)
TypeError: norm() got an unexpected keyword argument 'axis'

======================================================================
ERROR: test_basic.TestVectorNorms.test_axis_kwd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\nose-1.1.2-py3.3.egg\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Python33\lib\site-packages\numpy\testing\decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "C:\Python33\lib\site-packages\scipy\linalg\tests\test_basic.py", line 1157, in test_axis_kwd
    assert_allclose(norm(a, axis=1), [[3.60555128, 4.12310563]] * 2)
  File "C:\Python33\lib\site-packages\scipy\linalg\misc.py", line 165, in norm
    return np.linalg.norm(a, ord=ord, axis=axis)
TypeError: norm() got an unexpected keyword argument 'axis'

======================================================================
FAIL: test_dlamch (test_cython_lapack.test_lamch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\scipy\linalg\tests\test_cython_lapack.py", line 16, in test_dlamch
    lapack.dlamch(c))
  File "C:\Python33\lib\site-packages\numpy\testing\utils.py", line 1179, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Python33\lib\site-packages\numpy\testing\utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(2.506444446667e-312)
 y: array(4.393764671732483e-303)

======================================================================
FAIL: test_slamch (test_cython_lapack.test_lamch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\scipy\linalg\tests\test_cython_lapack.py", line 11, in test_slamch
    lapack.slamch(c))
  File "C:\Python33\lib\site-packages\numpy\testing\utils.py", line 1179, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Python33\lib\site-packages\numpy\testing\utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(0.0)
 y: array(4.974214305753484e+37)

----------------------------------------------------------------------
Ran 1511 tests in 35.893s

FAILED (KNOWNFAIL=4, SKIP=6, errors=2, failures=2)
<nose.result.TextTestResult run=1511 errors=2 failures=2>
```

Superpack installers, SSE3. Numpy 1.7.2
None of these shows up on python 2.7 with numpy 1.6.2.

**Comment by ev-br** [comment] 2015-12-04 16:12
@insertinterestingnamehere looks like something is not zero-initialized somewhere?

**Comment by rgommers** [comment] 2015-12-08 01:01
The ``norm`` failures are fixed now, and the ``lamch`` ones don't look very interesting. Probably OK to mark those as knownfail at least in 0.17.x

**Comment by insertinterestingnamehere** [comment] 2015-12-08 02:46
Somehow I missed this in the churn of my various other emails. Thanks for taking care of the axis keyword issue.
It's not at all clear to me what's going on with the `test_lamch` failures. All those do is compare the output between different wrappers for the same fortran functions. There shouldn't be any difference. The values that each function gives depend on the ieee floating point standard, but in the test failures here it doesn't look like either wrapper is returning the correct value.

**Comment by rgommers** [comment] 2015-12-08 07:08
The ``dlamch`` failre could be just numerical issues I had thought, looking at the very small values.

``slamch`` has been problematic before on OS X, see https://github.com/scipy/scipy/blob/master/scipy/_build_utils/src/wrap_accelerate_f.f#L332. numpy-vendor also uses g77. I thought it was an issue specific to Accelerate, but now I'm not 100%.

**Comment by ev-br** [comment] 2015-12-08 14:29
Ok, as a data point, I tried to see if I can call slamch straight from fortran. And it seems to work:

```
vagrant@vagrant-ubuntu-precise-32:~$ cat slam.f 
      character*10 s
      character*1 c
      integer i
      real x
      double precision y

      s = "esbpnrmulo"

      do i=1, 10
         c = s(i:i)
         write(*, *) c, slamch(c), dlamch(c)
      enddo

      end
vagrant@vagrant-ubuntu-precise-32:~$ .wine/drive_c/MinGW/bin/g77.exe slam.f .wine/drive_c/local/lib/atlas/sse3/libatlas.a .wine/drive_c/local/lib/atlas/sse3/liblapack.a .wine/drive_c/local/lib/atlas/sse3/libf77blas.a
vagrant@vagrant-ubuntu-precise-32:~$ ./a.exe 
 e  5.96046448E-008  1.11022302E-016
 s  1.17549435E-038  0.
 b  2.  2.
 p  1.1920929E-007  2.22044605E-016
 n  24.  53.
 r  1.  1.
 m -125. -1021.
 u  1.17549435E-038  0.
 l  128.  1024.
 o  3.40282347E+038  INF
```

I've no idea if this combination of atlas/blas/lapack is the one that scipy links to (would be good if someone who knows that or knows how to find out, can comment). 

Since this works straight from fortran, it seems to suggest that there is a problem in the wrappers, and this problem is common to f2py and cython wrappers. Something about binary compatibility indeed?

While this particular failures are not very interesting indeed, I cannot help but wonder if this is the same sort issue that causes https://github.com/scipy/scipy/issues/5577.

**Comment by pv** [comment] 2015-12-08 18:45
I think this is just some Python 3 issue, caused by this:
```
# Python 2
>>> bytes(b"foo"[0])
'f'
# Python 3
>>> bytes(b"foo"[0])
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
Indexing or iteration of bytes objects gives *integers*, not 1-character strings:
```
>>> from numpy.compat import asbytes
>>> [scipy.linalg.cython_lapack._test_slamch(c) for c in b"esbpnrmulo"]
[2.802596928649634e-45, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
>>> [scipy.linalg.cython_lapack._test_slamch(asbytes(c)) for c in "esbpnrmulo"]
[5.960464477539063e-08, 1.1754943508222875e-38, 2.0, 1.1920928955078125e-07, 24.0, 1.0, -125.0, 1.1754943508222875e-38, 128.0, 3.4028234663852886e+38]
>>> list(b"esbpnrmulo")
[101, 115, 98, 112, 110, 114, 109, 117, 108, 111]
>>> scipy.linalg.cython_lapack._test_slamch(101)
0.0
```

**Comment by pv** [comment] 2015-12-08 19:02
IOW, slamch/dlamch probably work fine, the test is wrong for python 3.
On linux, it just happens that `lapack.slamch(101)` and `cython_lapack._test_slamch(101)` both return 0.0 --- the cython routine does `bytes(cmach)` which results to passing a null string to the underlying lapack routine. Not sure what f2py does exactly with integer input to CHAR variable on Python 3, but this is probably undefined (and should result to an error, and not pass silently...)

**Comment by insertinterestingnamehere** [comment] 2015-12-08 19:04
Okay, I see the issue with the test now. That's easy enough to fix. I don't have a wine build set up though, so testing would be appreciated.

**Comment by pv** [comment] 2015-12-08 19:06
You can add a check that e.g. `slamch('e') > 0`, so that no need to test on wine.

**Comment by insertinterestingnamehere** [comment] 2015-12-08 19:45
How about https://github.com/scipy/scipy/pull/5595 ?

**Comment by pv** [comment] 2015-12-09 21:16
merged gh-5595

**Closed** 2015-12-09 23:00 UTC
Labels: defect, scipy.linalg
