### ISSUE TITLE
 scipy.optimize.fmin_slsqp imode bug

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [scipy/scipy#6349] opened 2016-07-04 13:28 UTC
There appears to ba a bug in scipy.optimize.fmin_slsqp; given a set of unsatisfyable constraints, the imode return parameter should signal this with a return value of 4, but this does not appear to happen:

```
import scipy.optimize
normals = np.concatenate([np.eye(2), -np.eye(2)])
depth = 1
f_ieqcons = lambda x: normals.dot(x) - depth
x, fx, its, imode, smode = scipy.optimize.fmin_slsqp(
    func=lambda x: (x**2).sum(),
    x0=np.zeros(2),
    f_ieqcons=f_ieqcons,
    full_output=True
)
print(f_ieqcons(x))
assert imode==4  # fail
```

that is, given anaconda scipy 0.17.1 np110py35_1

**Comment by pv** [comment] 2016-07-04 13:58
Seems to be fixed in 0.18.0rc1 and master.

**Comment by pv** [comment] 2016-07-04 14:23
... or perhaps it's fixed, but for wrong reasons. This needs further 
checking.

**Comment by pv** [comment] 2016-07-04 19:40
duplicate of gh-5743

**Closed by pv** 2016-07-04 19:40 UTC
