### ISSUE TITLE
BUG: Bug in scipy.special.struve, returns nan

### ISSUE THREAD

**Issue by ruiefdasilva** [scipy/scipy#19580] opened 2023-11-23 10:54 UTC
### Describe your issue.

When calculating the Struve function for 25.765368073883174 it returns a nan. It should be a zero (or close to that).

### Reproducing Code Example

```python
In [1]: import scipy.special as sp_special

In [2]: sp_special.struve(0, 25.765368073883174)
Out[2]: nan

In [3]: sp_special.struve(0, 25.765368073883174+0.001)
Out[3]: 0.00015522631565283182

In [4]: sp_special.struve(0, 25.765368073883174-0.001)
Out[4]: -0.00015433122211300148
```

### Error message

```shell
In [2]: sp_special.struve(0, 25.765368073883174)
Out[2]: nan
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.24.3 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/LIBRARIES/ANACONDA3_2023/include
    lib directory: /opt/LIBRARIES/ANACONDA3_2023/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /opt/LIBRARIES/ANACONDA3_2023/lib/pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/LIBRARIES/ANACONDA3_2023/include
    lib directory: /opt/LIBRARIES/ANACONDA3_2023/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /opt/LIBRARIES/ANACONDA3_2023/lib/pkgconfig
    version: '2023.1'
  pybind11:
    detection method: pkgconfig
    include directory: /opt/LIBRARIES/ANACONDA3_2023/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: /croot/scipy_1691606680890/_build_env/bin/x86_64-conda-linux-gnu-cc
    linker: ld.bfd
    name: gcc
    version: 11.2.0
  c++:
    commands: /croot/scipy_1691606680890/_build_env/bin/x86_64-conda-linux-gnu-c++
    linker: ld.bfd
    name: gcc
    version: 11.2.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: /croot/scipy_1691606680890/_build_env/bin/x86_64-conda-linux-gnu-gfortran
    linker: ld.bfd
    name: gcc
    version: 11.2.0
  pythran:
    include directory: ../../_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/LIBRARIES/ANACONDA3_2023/bin/python
  version: '3.11'
```

**Comment by GreenMemory16** [comment] 2024-03-08 14:55
Hello, I would like to work on this issue.
Is that possible?

Thanks in advance

**Comment by mdhaber** [comment] 2024-09-08 09:48
Closing as duplicate of gh-5979.

**Closed by mdhaber** 2024-09-08 09:48 UTC
Labels: defect, scipy.special
