### ISSUE TITLE
ENH: Generalized Fischer exact test (Fischer-Freeman-Halton)

### ISSUE THREAD

**Issue by Ge0rges** [scipy/scipy#20981] opened 2024-06-18 06:16 UTC
### Is your feature request related to a problem? Please describe.

I'd like to perform a Fischer exact test on an `R x C` contingency table where expected values for most cells are below 5, and some may be 0. The current implementation is limited to `2x2`.

### Describe the solution you'd like.

I would like the `scipy.stats.fisher_exact ` to accept a `R x C` shaped contingency table.

### Describe alternatives you've considered.

Alternatives were other chi-squared tests, CMH test. These are [limited](https://stats.stackexchange.com/questions/30765/for-chi-square-on-any-2-by-x-contingency-table-should-no-more-than-20-of-the-c) by the expected value of the cells.

### Additional context (e.g. screenshots, GIFs)

A possible implementation [here](https://stackoverflow.com/questions/25368284/fishers-exact-test-for-bigger-than-2-by-2-contingency-table)
Related reading: Freeman, G.H., & Halton, J.H. (1951). "Note on exact treatment of contingency, goodness-of-fit and other problems of significance." Biometrika, 38, 141-149.

**Comment by mdhaber** [comment] 2024-06-18 06:51
@Ge0rges would you agree this is a duplicate of gh-7099?

**Comment by Ge0rges** [comment] 2024-06-18 07:04
Yes apologies for the duplicate.

**Closed** 2024-06-18 07:19 UTC
Labels: enhancement, duplicate
