### ISSUE TITLE
To me, this seems like very odd behavior

### ISSUE THREAD

**Issue by javvy** [scipy/scipy#11774] opened 2020-04-01 13:09 UTC
THIS works as expected:
```python
#Import to good stuff
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

from scipy.special import gamma     # NOTE: Why ius this necessary?

# Print to confirm that the imports were done successfully
print("Skeleton stuff imported OK")

# Start program instructions here
for x in range(5):
    y = sp.special.gamma(x)
    putstr = '   ' + str(x) + ' -> ' + str(y)
    print(putstr)

print('==========================')
print()
while True:
    xs = input('Enter x = ')
    if 'Q' in xs.upper():
        break
    x = eval(xs)

    z = sp.special.entr(x)
    print("entr(%s) = %s" %(x, z))

    w = sp.special.erf(x)
    print("erf(%s) = %s" %(x, w))
        
    y = sp.special.gamma(x)
    print("gamma(%s) = %s" %(x, y))

    print()
```
BUT, if I delete the  line "from scipy.special import gamma", and try to run, 
   I get the following output:
```pytb
Traceback (most recent call last):
  File "D:/PYTHON/MyPrograms/Gamma Test-0000.py", line 14, in <module>
    y = sp.special.gamma(x)
AttributeError: module 'scipy' has no attribute 'special'
```

**Comment by jakevdp** [comment] 2020-04-01 13:57
The ``scipy.special`` module is not available for use unless you import it (or import something from it). It might be clearer to  do this more explicitly:
```python
import scipy.special
```

**Comment by javvy** [comment] 2020-04-01 14:10
Thanks
But---why not?
"You won't find the right answers if you don't ask the right questions!" (Robert Helmbold, 2013) 

    On Wednesday, April 1, 2020, 06:57:56 AM MST, Jake Vanderplas <notifications@github.com> wrote:  
 
 


The scipy.special module is not available for use unless you import it (or import something from it). It might be clearer to do this more explicitly:
import scipy.special

**Comment by matthew-brett** [comment] 2020-04-01 14:14
It's fairly standard in big libraries, like Scipy, not to import everything with a top level import like `import scipy`, because this would make it necessary to import everything from Scipy even if you were only, for example, using the `scipy.special` sub-package.  This in turn would make all Scipy imports slower, as we do (in this case) an unnecessary import  of `scipy.optimize`, `scipy.io` etc.

**Comment by javvy** [comment] 2020-04-01 14:25
Ummmm, better said as:Why doesn't the system recognize that I want special package imported    when I refer to it in the program?
"You won't find the right answers if you don't ask the right questions!" (Robert Helmbold, 2013) 

    On Wednesday, April 1, 2020, 07:14:18 AM MST, Matthew Brett <notifications@github.com> wrote:  
 
 


It's fairly standard in big libraries, like Scipy, not to import everything with a top level import like import scipy, because this would make it necessary to import everything from Scipy even if you were only, for example, using the scipy.special sub-package. This in turn would make all Scipy imports slower, as we do (in this case) an unnecessary import of scipy.optimize, scipy.io etc.

**Comment by jakevdp** [comment] 2020-04-01 14:44
*Explicit is better than implicit.*

— [The Zen Of Python](https://www.python.org/dev/peps/pep-0020/)

**Comment by rkern** [comment] 2020-04-01 14:48
Because that's not how Python's import system was built. ["Explicit is better than implicit."](https://www.python.org/dev/peps/pep-0020/)

In the past, we did have stub objects in the `scipy` namespace for each of the subpackages. So you could just do `import scipy; scipy.special.gamma(...)`. These stub objects would lazily import the actual module when accessed. However, this caused a _ton_ of problems despite the convenience. Python's import system is complicated, and adding magical hacks on top causes some very difficult-to-track-down problems.

In terms of style, I would not do what you are doing:

```python
import scipy as sp
from scipy.special import gamma

sp.special.gamma(...)
```

You are relying on an implicit side effect of the import. Instead, I would follow the Zen of Python here and be explicit.

```python
from scipy import special

special.gamma(...)
```

`import scipy as sp` is unnecessary. There is nothing in that namespace that you need. Just import the subpackages that you need directly and use them explicitly.

**Comment by ilayn** [comment] 2020-04-01 15:16
Thanks @javvy for taking the time for creating the issue.

 Since this is the intended behavior I'll close this but please keep the discussion alive as you wish.

**Comment by rkern** [comment] 2020-04-01 15:17
Just to add an explanation of that implicit side effect:

When we import a subpackage, the Python import system places it in the namespace of the parent package. If you just do `import scipy; print(scipy.special)`, that `scipy.special` access won't work. If you do `import scipy; from scipy import special; print(scipy.special)`, that `scipy.special` access will work because the `from scipy import special` (or `import scipy.special` or `from scipy.special import gamma`) will import the `special` sub-package and place it in the `scipy` namespace as a side effect.

This is mostly for caching purposes. I would consider it an implementation detail. I wouldn't write my code to routinely rely on that implicit side effect. As I stated previously, I would explicitly import the sub-packages that I need and use them explicitly.

**Closed by ilayn** 2020-04-01 15:16 UTC
Labels: query, scipy.special
