### ISSUE TITLE
BUG: stats.zscore with masked arrays containing `nan` values and with `nan_policy='omit'` returns array filled with nan

### ISSUE THREAD

**Issue by VinceBaz** [scipy/scipy#17755] opened 2023-01-09 19:11 UTC
### Describe your issue.

It seems like there is a bug when we try to use `stats.zscore` with a masked array that has a masked `nan` value at index 0, and with `nan_policy='omit'`. In such cases, the function returns an array filled with `nan` values.

It seems to be caused by the following line, which checks whether the array is constant: 

[`isconst = (_first(a, axis) == a).all(axis=axis, keepdims=True)`](https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/scipy/stats/_stats_py.py#L2877)

In this specific case, `isconst` is evaluated to `True` (when in reality it should be evaluated to `False`), and the outputs are set to nan (when in reality they shouldn't)

### Reproducing Code Example

```python
from scipy.stats import zscore
import numpy as np

# With a masked array
A = np.array([np.nan, 1,2,3])
masked_A = np.ma.masked_array(A, np.isnan(A), copy=False, fill_value=np.nan)
z = zscore(masked_A, axis=0, nan_policy='omit').filled()
print(z)  # [nan nan nan nan] : z is filled with nan (this is a bug?)

# Without a masked array
z = zscore(A, axis=0, nan_policy='omit')
print(z)  # [nan -1.22474487 0 -1.22474487] nan values are omitted (as expected)
```

### Error message

```shell
No error message
```

### SciPy/NumPy/Python version information

`1.9.3 1.23.5 sys.version_info(major=3, minor=10, micro=8, releaselevel='final', serial=0)`

**Comment by mdhaber** [comment] 2023-01-09 19:54
This @VinceBaz. This looks like a duplicate of gh-8669, so I'll close this one.
Note that there is a long-term effort to eliminate `nan_policy` bugs in reducing statistics (gh-14651), and I planned to tackle elementwise statistics after that.

**Closed** 2023-01-09 19:54 UTC
Labels: defect, scipy.stats
