### ISSUE TITLE
Random sparse matrix construction allocates large array

### ISSUE THREAD

**Issue by jokasimr** [scipy/scipy#13133] opened 2020-11-25 15:25 UTC
Encountering a MemoryError when creating a large sparse random matrix.
The matrix is created with scipy.sparse.rand, and even if the density is low enough that only a few elements in the whole matrix should be nonzero (or even none at all), it still tries to allocate a large integer array.

I'm not sure if this really is a bug, or I'm just using the function wrong. I know it's possible to create an empty sparse matrix and fill it with random values manually. But I thought it a bit strange that it would try to allocate that much.

#### Reproducing code example:

```
from scipy.sparse import rand
rand(10**5, 10**5, density=0) 
```

#### Error message:

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-68-4d3ba46fe0a7> in <module>
----> 1 rand(10**5, 10**5, density=0)

~/anaconda3/lib/python3.7/site-packages/scipy/sparse/construct.py in rand(m, n, density, format, dtype, random_state)
    840 
    841     """
--> 842     return random(m, n, density, format, dtype, random_state)

~/anaconda3/lib/python3.7/site-packages/scipy/sparse/construct.py in random(m, n, density, format, dtype, random_state, data_rvs)
    786             data_rvs = random_state.rand
    787 
--> 788     ind = random_state.choice(mn, size=k, replace=False)
    789 
    790     j = np.floor(ind * 1. / m).astype(tp, copy=False)

mtrand.pyx in numpy.random.mtrand.RandomState.choice()

mtrand.pyx in numpy.random.mtrand.RandomState.permutation()

MemoryError: Unable to allocate 74.5 GiB for an array with shape (10000000000,) and data type int64

```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by jokasimr** [comment] 2020-11-25 15:44
I expected the result would be something like
```
<100000x100000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in COOrdinate format>
```

**Comment by peterbell10** [comment] 2020-11-25 16:43
Same root cause as gh-9699 I think.

**Comment by jokasimr** [comment] 2020-11-25 17:00
Replacing

```
        return np.random.mtrand._rand
```

with 

```
        return np.random.mtrand._rand
```
in the function [check_random_state](https://github.com/scipy/scipy/blob/19acfed431060aafaa963f7e530c95e70cd4b85c/scipy/_lib/_util.py#L211) resolves the problem.

**Comment by perimosocordiae** [comment] 2021-01-18 20:37
Yes, this is a duplicate of gh-9699, closing.

**Closed by perimosocordiae** 2021-01-18 20:37 UTC
Labels: scipy.sparse

**Comment by jabowery** [comment] 2023-05-22 19:31
I don't see why they are the same root cause.  This is about N^2 memory allocation for what should be _sparse_ matrices whereas https://github.com/scipy/scipy/issues/9699 is about speed of initialization.

**Comment by perimosocordiae** [comment] 2023-05-25 18:39
The speed issue in gh-9699 is directly related to allocating a large temporary inside np.random.choice.
