### ISSUE TITLE
Travis X.4 and X.7 failures in master

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#12613] opened 2020-07-24 21:40 UTC
Master is experiencing the following failures on Travis X.4 and X.7 builds (e.g. gh-12611, 12612):

```
=================================== FAILURES ===================================
__________ TestDifferentialEvolutionSolver.test_args_tuple_is_passed ___________
[gw1] linux -- Python 3.8.0 /home/travis/virtualenv/python3.8.0/bin/python
scipy/optimize/_differentialevolution.py:875: in _calculate_population_energies
    energies[0:nfevs] = calc_energies
E   ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.
        calc_energies = [array([45.34286517]), array([1.03163941]), array([0.9302832]), array([270.39415071]), array([6.52919529]), array([18.59346585]), ...]
        energies   = array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf])
        nfevs      = 15
        num_members = 15
        parameters_pop = array([[-4.19235732],
       [-0.6821278 ],
       [-0.03690092],
       [ 9.14871082],
       [ 1.06458519],
       [...681341],
       [ 7.43671883],
       [ 4.87799655],
       [-3.14677001],
       [-9.6552919 ],
       [-6.53825391]])
        population = array([[0.29038213],
       [0.46589361],
       [0.49815495],
       [0.95743554],
       [0.55322926],
       [0.605...[0.07115933],
       [0.87183594],
       [0.74389983],
       [0.3426615 ],
       [0.01723541],
       [0.1730873 ]])
        self       = <scipy.optimize._differentialevolution.DifferentialEvolutionSolver object at 0x7f9b56613a00>
The above exception was the direct cause of the following exception:
scipy/optimize/tests/test__differential_evolution.py:268: in test_args_tuple_is_passed
    result = differential_evolution(quadratic,
        args       = (1.0, 2.0, 3.0)
        bounds     = [(-10, 10)]
        quadratic  = <function TestDifferentialEvolutionSolver.test_args_tuple_is_passed.<locals>.quadratic at 0x7f9b56609b80>
        self       = <scipy.optimize.tests.test__differential_evolution.TestDifferentialEvolutionSolver object at 0x7f9b5660aa90>
scipy/optimize/_differentialevolution.py:308: in differential_evolution
    ret = solver.solve()
        args       = (1.0, 2.0, 3.0)
        atol       = 0
        bounds     = [(-10, 10)]
        callback   = None
        constraints = ()
        disp       = False
        func       = <function TestDifferentialEvolutionSolver.test_args_tuple_is_passed.<locals>.quadratic at 0x7f9b56609b80>
        init       = 'latinhypercube'
        maxiter    = 1000
        mutation   = (0.5, 1)
        polish     = True
        popsize    = 15
        recombination = 0.7
        seed       = None
        solver     = <scipy.optimize._differentialevolution.DifferentialEvolutionSolver object at 0x7f9b56613a00>
        strategy   = 'best1bin'
        tol        = 0.01
        updating   = 'immediate'
        workers    = 1
scipy/optimize/_differentialevolution.py:750: in solve
    self._calculate_population_energies(
        nit        = 0
        self       = <scipy.optimize._differentialevolution.DifferentialEvolutionSolver object at 0x7f9b56613a00>
        status_message = 'Optimization terminated successfully.'
        warning_flag = False
scipy/optimize/_differentialevolution.py:879: in _calculate_population_energies
    raise RuntimeError(
E   RuntimeError: The map-like callable must be of the form f(func, iterable), returning a sequence of numbers the same length as 'iterable'
        calc_energies = [array([45.34286517]), array([1.03163941]), array([0.9302832]), array([270.39415071]), array([6.52919529]), array([18.59346585]), ...]
        energies   = array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf])
        nfevs      = 15
        num_members = 15
        parameters_pop = array([[-4.19235732],
       [-0.6821278 ],
       [-0.03690092],
       [ 9.14871082],
       [ 1.06458519],
       [...681341],
       [ 7.43671883],
       [ 4.87799655],
       [-3.14677001],
       [-9.6552919 ],
       [-6.53825391]])
        population = array([[0.29038213],
       [0.46589361],
       [0.49815495],
       [0.95743554],
       [0.55322926],
       [0.605...[0.07115933],
       [0.87183594],
       [0.74389983],
       [0.3426615 ],
       [0.01723541],
       [0.1730873 ]])
        self       = <scipy.optimize._differentialevolution.DifferentialEvolutionSolver object at 0x7f9b56613a00>
_________________________ TestSLSQP.test_array_bounds __________________________
[gw0] linux -- Python 3.8.0 /home/travis/virtualenv/python3.8.0/bin/python
scipy/optimize/tests/test_slsqp.py:318: in test_array_bounds
    x = fmin_slsqp(lambda z: np.sum(z**2 - 1), [2.5, 2.5], bounds=bounds, iprint=0)
        bounds     = [(-inf, inf), (array([2]), array([3]))]
        self       = <scipy.optimize.tests.test_slsqp.TestSLSQP object at 0x7f9298d20790>
scipy/optimize/slsqp.py:205: in fmin_slsqp
    res = _minimize_slsqp(func, x0, args, jac=fprime, bounds=bounds,
        acc        = 1e-06
        args       = ()
        bounds     = [(-inf, inf), (array([2]), array([3]))]
        callback   = None
        cons       = ()
        disp       = None
        epsilon    = 1.4901161193847656e-08
        eqcons     = ()
        f_eqcons   = None
        f_ieqcons  = None
        fprime     = None
        fprime_eqcons = None
        fprime_ieqcons = None
        full_output = 0
        func       = <function TestSLSQP.test_array_bounds.<locals>.<lambda> at 0x7f9298d199d0>
        ieqcons    = ()
        iprint     = 0
        iter       = 100
        opts       = {'callback': None, 'disp': False, 'eps': 1.4901161193847656e-08, 'ftol': 1e-06, ...}
        x0         = [2.5, 2.5]
scipy/optimize/slsqp.py:349: in _minimize_slsqp
    bnds = array(bounds, float)
E   ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.
        acc        = 1e-06
        args       = ()
        bounds     = [(-inf, inf), (array([2]), array([3]))]
        callback   = None
        cons       = {'eq': (), 'ineq': ()}
        constraints = ()
        disp       = False
        eps        = 1.4901161193847656e-08
        epsilon    = 1.4901161193847656e-08
        exit_modes = {-1: 'Gradient evaluation required (g & a)', 0: 'Optimization terminated successfully', 1: 'Function evaluation required (f & c)', 2: 'More equality constraints than independent variables', ...}
        finite_diff_rel_step = None
        ftol       = 1e-06
        func       = <function TestSLSQP.test_array_bounds.<locals>.<lambda> at 0x7f9298d199d0>
        iprint     = 0
        iter       = 99
        jac        = None
        jw         = array([0., 0., 0., 0., 0., 0.])
        la         = 1
        len_jw     = 6
        len_w      = 129
        m          = 0
        maxiter    = 100
        meq        = 0
        mieq       = 0
        mineq      = 6
        n          = 2
        n1         = 3
        new_bounds = (array([-inf,   2.]), array([inf,  3.]))
        unknown_options = {}
        w          = array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., ...    0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
        x          = array([2.5, 2.5])
        x0         = [2.5, 2.5]
_______________ test_methods_with_lists[johnsonsb-args49-logpdf] _______________
[gw0] linux -- Python 3.8.0 /home/travis/virtualenv/python3.8.0/bin/python
scipy/stats/tests/test_continuous_basic.py:653: in test_methods_with_lists
    npt.assert_allclose(result,
E   AssertionError: 
E   Not equal to tolerance rtol=1e-15, atol=1e-15
E   
E   Mismatched elements: 1 / 2 (50%)
E   Max absolute difference: 2.66453526e-15
E   Max relative difference: 2.83665371e-15
E    x: array([-0.939323, -1.035262])
E    y: array([-0.939323, -1.035262])
        args       = (4.317267509914106, 3.1837781130785063)
        dist       = <scipy.stats._continuous_distns.johnsonsb_gen object at 0x7f92a96d1ca0>
        distname   = 'johnsonsb'
        f          = <bound method rv_continuous.logpdf of <scipy.stats._continuous_distns.johnsonsb_gen object at 0x7f92a96d1ca0>>
        loc        = [0, 0.1]
        method     = 'logpdf'
        result     = array([-0.93932342, -1.03526171])
        scale      = [1, 1.01]
        shape2     = [[4.317267509914106, 4.317267509914106], [3.1837781130785063, 3.1837781130785063]]
        x          = [0.1, 0.2]
___________________ test_rvs_broadcast[kappa4-shape_args51] ____________________
[gw1] linux -- Python 3.8.0 /home/travis/virtualenv/python3.8.0/bin/python
scipy/stats/tests/test_continuous_basic.py:295: in test_rvs_broadcast
    check_rvs_broadcast(distfunc, dist, allargs, bshape, shape_only, 'd')
        allargs    = [array([[[0.]],
       [[0.]],
       [[0.]],
       [[0.]]]), array([[[[0.]]],
       [[[0.]]],
       [[[0.]]],
       [[[0.]]],
       [[[0.]]]]), array([0., 0.]), array([[1.],
       [1.],
       [1.]])]
        bshape     = [5, 4, 3, 2]
        dist       = 'kappa4'
        distfunc   = <scipy.stats._continuous_distns.kappa4_gen object at 0x7f9b682aeb20>
        k          = 1
        loc        = array([0., 0.])
        nargs      = 2
        scale      = array([[1.],
       [1.],
       [1.]])
        shape_args = (0.0, 0.0)
        shape_only = False
        shp        = (5, 1, 1, 1)
scipy/stats/tests/common_tests.py:320: in check_rvs_broadcast
    assert_allclose(sample, expected, rtol=1e-15)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-15, atol=0
E   
E   Mismatched elements: 4 / 120 (3.33%)
E   Max absolute difference: 8.8817842e-16
E   Max relative difference: 1.29916474e-14
E    x: array([[[[ 1.016852, -0.224164],
E            [-0.394377,  0.518439],
E            [ 1.110963,  0.15067 ]],...
E    y: array([[[[ 1.016852, -0.224164],
E            [-0.394377,  0.518439],
E            [ 1.110963,  0.15067 ]],...
        allargs    = [array([[[0.]],
       [[0.]],
       [[0.]],
       [[0.]]]), array([[[[0.]]],
       [[[0.]]],
       [[[0.]]],
       [[[0.]]],
       [[[0.]]]]), array([0., 0.]), array([[1.],
       [1.],
       [1.]])]
        distfunc   = <scipy.stats._continuous_distns.kappa4_gen object at 0x7f9b682aeb20>
        distname   = 'kappa4'
        expected   = array([[[[ 1.01685242, -0.22416415],
         [-0.39437711,  0.51843892],
         [ 1.1109626 ,  0.15067005]],
     ...3]],
        [[-0.07948249,  0.52165567],
         [ 0.60289017,  0.42927234],
         [-1.77815634,  4.44620019]]]])
        otype      = 'd'
        rvs        = <numpy.vectorize object at 0x7f9b1ed059a0>
        sample     = array([[[[ 1.01685242, -0.22416415],
         [-0.39437711,  0.51843892],
         [ 1.1109626 ,  0.15067005]],
     ...3]],
        [[-0.07948249,  0.52165567],
         [ 0.60289017,  0.42927234],
         [-1.77815634,  4.44620019]]]])
        shape      = [5, 4, 3, 2]
        shape_only = False
___________________ test_rvs_broadcast[kappa4-shape_args53] ____________________
[gw1] linux -- Python 3.8.0 /home/travis/virtualenv/python3.8.0/bin/python
scipy/stats/tests/test_continuous_basic.py:295: in test_rvs_broadcast
    check_rvs_broadcast(distfunc, dist, allargs, bshape, shape_only, 'd')
        allargs    = [array([[[0.]],
       [[0.]],
       [[0.]],
       [[0.]]]), array([[[[0.1]]],
       [[[0.1]]],
       [[[0.1]]],
       [[[0.1]]],
       [[[0.1]]]]), array([0., 0.]), array([[1.],
       [1.],
       [1.]])]
        bshape     = [5, 4, 3, 2]
        dist       = 'kappa4'
        distfunc   = <scipy.stats._continuous_distns.kappa4_gen object at 0x7f9b682aeb20>
        k          = 1
        loc        = array([0., 0.])
        nargs      = 2
        scale      = array([[1.],
       [1.],
       [1.]])
        shape_args = (0.0, 0.1)
        shape_only = False
        shp        = (5, 1, 1, 1)
scipy/stats/tests/common_tests.py:320: in check_rvs_broadcast
    assert_allclose(sample, expected, rtol=1e-15)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-15, atol=0
E   
E   Mismatched elements: 3 / 120 (2.5%)
E   Max absolute difference: 1.11022302e-15
E   Max relative difference: 2.79974471e-15
E    x: array([[[[ 0.966862, -0.226696],
E            [-0.402257,  0.505229],
E            [ 1.051474,  0.149541]],...
E    y: array([[[[ 0.966862, -0.226696],
E            [-0.402257,  0.505229],
E            [ 1.051474,  0.149541]],...
        allargs    = [array([[[0.]],
       [[0.]],
       [[0.]],
       [[0.]]]), array([[[[0.1]]],
       [[[0.1]]],
       [[[0.1]]],
       [[[0.1]]],
       [[[0.1]]]]), array([0., 0.]), array([[1.],
       [1.],
       [1.]])]
        distfunc   = <scipy.stats._continuous_distns.kappa4_gen object at 0x7f9b682aeb20>
        distname   = 'kappa4'
        expected   = array([[[[ 0.96686168, -0.22669551],
         [-0.40225702,  0.50522924],
         [ 1.05147394,  0.14954066]],
     ...3]],
        [[-0.0797992 ,  0.50828298],
         [ 0.58507613,  0.42018904],
         [-1.94605056,  3.58932177]]]])
        otype      = 'd'
        rvs        = <numpy.vectorize object at 0x7f9b1ebf07c0>
        sample     = array([[[[ 0.96686168, -0.22669551],
         [-0.40225702,  0.50522924],
         [ 1.05147394,  0.14954066]],
     ...3]],
        [[-0.0797992 ,  0.50828298],
         [ 0.58507613,  0.42018904],
         [-1.94605056,  3.58932177]]]])
        shape      = [5, 4, 3, 2]
        shape_only = False
___________________ test_methods_with_lists[f-args21-logpdf] ___________________
[gw1] linux -- Python 3.8.0 /home/travis/virtualenv/python3.8.0/bin/python
scipy/stats/tests/test_continuous_basic.py:653: in test_methods_with_lists
    npt.assert_allclose(result,
E   AssertionError: 
E   Not equal to tolerance rtol=1e-15, atol=1e-15
E   
E   Mismatched elements: 1 / 2 (50%)
E   Max absolute difference: 1.42108547e-14
E   Max relative difference: 1.17311837e-15
E    x: array([-12.113743, -12.225716])
E    y: array([-12.113743, -12.225716])
        args       = (29, 18)
        dist       = <scipy.stats._continuous_distns.f_gen object at 0x7f9b6851c2e0>
        distname   = 'f'
        f          = <bound method rv_continuous.logpdf of <scipy.stats._continuous_distns.f_gen object at 0x7f9b6851c2e0>>
        loc        = [0, 0.1]
        method     = 'logpdf'
        result     = array([-12.11374327, -12.22571607])
        scale      = [1, 1.01]
        shape2     = [[29, 29], [18, 18]]
        x          = [0.1, 0.2]
=============================== warnings summary ===============================
/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/_pytest/config/__init__.py:1148
/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/_pytest/config/__init__.py:1148
/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/_pytest/config/__init__.py:1148
  /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/_pytest/config/__init__.py:1148: PytestConfigWarning: Unknown config ini key: env
  
    self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))
-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= slowest 10 durations =============================
51.31s call     build/testenv/lib/python3.8/site-packages/scipy/stats/tests/test_continuous_basic.py::test_cont_basic[kstwo-arg57]
44.14s call     build/testenv/lib/python3.8/site-packages/scipy/stats/tests/test_stats.py::TestMGCStat::test_twosamp
38.55s call     build/testenv/lib/python3.8/site-packages/scipy/stats/tests/test_distributions.py::TestLevyStable::test_pdf_nolan_samples
34.58s call     build/testenv/lib/python3.8/site-packages/scipy/stats/tests/test_continuous_basic.py::test_moments[ksone-arg56-True-True-False]
30.92s call     build/testenv/lib/python3.8/site-packages/scipy/stats/tests/test_continuous_basic.py::test_moments[vonmises-arg98-False-False-False]
29.16s call     build/testenv/lib/python3.8/site-packages/scipy/stats/tests/test_continuous_basic.py::test_moments[kstwo-arg57-True-True-False]
27.98s call     build/testenv/lib/python3.8/site-packages/scipy/optimize/tests/test_minimize_constrained.py::TestTrustRegionConstr::test_list_of_problems
21.29s call     build/testenv/lib/python3.8/site-packages/scipy/stats/tests/test_continuous_basic.py::test_moments[vonmises_line-arg100-True-True-False]
20.79s call     build/testenv/lib/python3.8/site-packages/scipy/spatial/tests/test_distance.py::TestPdist::test_pdist_correlation_iris_nonC
20.39s call     build/testenv/lib/python3.8/site-packages/scipy/special/tests/test_cdflib.py::TestCDFlib::test_chndtrix
=========================== short test summary info ============================
FAILED scipy/optimize/tests/test__differential_evolution.py::TestDifferentialEvolutionSolver::test_args_tuple_is_passed
FAILED scipy/optimize/tests/test_slsqp.py::TestSLSQP::test_array_bounds - Val...
FAILED scipy/stats/tests/test_continuous_basic.py::test_methods_with_lists[johnsonsb-args49-logpdf]
FAILED scipy/stats/tests/test_continuous_basic.py::test_rvs_broadcast[kappa4-shape_args51]
FAILED scipy/stats/tests/test_continuous_basic.py::test_rvs_broadcast[kappa4-shape_args53]
FAILED scipy/stats/tests/test_continuous_basic.py::test_methods_with_lists[f-args21-logpdf]
```

**Comment by andyfaff** [comment] 2020-07-24 22:28
The failing entries are when numpy pre wheels are used. There must be a changed behaviour in an upcoming numpy that we've missed.
@rgommers, can you shed any light?

**Comment by rgommers** [comment] 2020-07-24 22:34
@charris said the wheel builds for NumPy master were failing for a while, and he fixed it yesterday, that's why it's showing up now. See https://github.com/numpy/numpy/issues/16939#issuecomment-663561857 for relevant NumPy conversation.

**Comment by tylerjereddy** [comment] 2020-07-24 23:11
Shows up in `1.5.x` backport CI as well. If SciPy decides to fix the "reverse broadcasting" on our side I may want to backport if it is not too disruptive.

**Comment by andyfaff** [comment] 2020-07-24 23:13
The diffev failure looks like numpy is coercing a list of numpy arrays `[np.array([1.]), np.array([2.], np.array([3.])` to a 2D array, which then can't be used to set the elements of a 1D array.

- has the diffev behaviour always been ropey (and need to be fixed)?
- or is there a fault in numpy?

**Comment by andyfaff** [comment] 2020-07-24 23:15
It's an easy fix for diffev, `np.squeeze(np.array([np.array([1.]), np.array([2.]), np.array([3.])]))`

**Comment by WarrenWeckesser** [comment] 2020-07-26 17:14
The first failure (in `TestSLSQP.test_array_bounds`) should be fixed by @andyfaff's PR:  https://github.com/scipy/scipy/pull/12614.

The test `TestSLSQP.test_array_bounds` that fails is testing exactly the feature that now generates a warning in numpy.  The comment in the test even says "1-element arrays are castable to floats in numpy".   If we want to continue to support this in `fmin_slsqp`, we might have to add some code that explicitly checks for 1-element arrays and converts them to scalars.  In the case of `fmin_slsqp`, we could do this in the function `old_bound_to_new()` in `_constraints.py`.  I'll create a PR for this, in case that is the preferred solution.

The other test failures are test in `stats` where the computed solution doesn't match the expected solution to within the given tolerances.  I haven't investigated what is causing these discrepancies when the master branch of numpy is used.

**Comment by WarrenWeckesser** [comment] 2020-07-26 23:01
FWIW, I haven't been able to reproduce the `stats` failures, using a miniconda3 installation of Python 3.8.3 and the miniconda3 MKL packages,  and numpy version `'1.20.0.dev0+1ce5457'` installed from source, on Mac OS 10.12.6.

**Comment by WarrenWeckesser** [comment] 2020-07-28 13:58
Closed by https://github.com/scipy/scipy/pull/12614, https://github.com/scipy/scipy/pull/12617 and https://github.com/scipy/scipy/pull/12623

**Closed by WarrenWeckesser** 2020-07-28 13:58 UTC
Labels: CI
