### ISSUE TITLE
BUG: csr_array can no longer be initialized with 1D array

### ISSUE THREAD

**Issue by fuglede** [scipy/scipy#20415] opened 2024-04-08 12:39 UTC
### Describe your issue.

As of SciPy 1.13, it is no longer possible to initialize a `scipy.sparse.csr_array` with a 1-dimensional `np.ndarray`; as this was possible before, it seems like a regression.

### Reproducing Code Example

```python
>>> from scipy.sparse import csr_array
>>> import numpy as np
>>> csr_array(np.array([3, 6, 1, 2]))
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/scipy-1-13/lib/python3.12/site-packages/scipy/sparse/_compressed.py", line 88, in __init__
    arrays = coo._coo_to_compressed(self._swap)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/scipy-1-13/lib/python3.12/site-packages/scipy/sparse/_coo.py", line 353, in _coo_to_compressed
    M, N = swap(self.shape)
    ^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

### SciPy/NumPy/Python version and system information

```shell
1.13.0 1.26.4 sys.version_info(major=3, minor=12, micro=2, releaselevel='final', serial=0)
/home/user/miniconda3/envs/scipy-1-13/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.10",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.15.0",
      "include directory": "../../tmp/pip-build-env-giifv1os/overlay/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.26.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.26.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.12.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/opt/python/cp312-cp312/bin/python",
    "version": "3.12"
  }
}
```

**Comment by lucascolley** [comment] 2024-04-08 13:31
cc @dschult

**Comment by dschult** [comment] 2024-04-09 05:34
Thanks for the report!

In previous releases (e.g. 1.11 and 1.12), the phrase `csr_array([1, 2, 3, 4])` created a 2D array with a single row.  Another way to say this is that `csr_array([1, 2, 3, 4])` was the same as `csr_array([[1, 2, 3, 4]])`.  The same was true for coo_array and dok_array.

Notice that it has never before been possible to initialize a 1D sparse array. It might feel like you are doing that in v1.11 or 1.12 but you are actually getting a 2D array with a single row.

With new support for 1D arrays, coo_array and dok_array formats now support 1D arrays. So the result in v1.13 for `coo_array([1, 2, 3, 4])` is a 1D array.  To get the old 2D result you need to provide a 2D input. The example of `csr_array([1, 2, 3, 4])` unfortunately uses `coo_array` during the initialization, but eventually converts to `csr_array`. We did not get the `csr-1d` code (PR #19833 ) reviewed and merged before the release, so this is indeed a bug in v1.13. It will be fixed in v1.14 if/when #19833 is merged. But we should make a fix for v1.13 that provides a better error message.

The solution to this problem is to request a 2D array when you want a 2D array as output. If you have a 1d numpy array (e.g. named `my_1d_array`), and you want a 2d scipy sparse array from it, use `csr_array(my_1d_array[np.newaxis])`. If you are entering a 1d numpy array as a literal, use two square brackets around the input to make it 2D: `csr_array(np.array([[1, 2, 3, 4]]))`

**I will work to provide a PR to provide a more helpful error message.** I claim it is not a regression because the array interface should not be providing a 2D array from 1D input. The change is an inevitable change while moving to support more than 2D shapes. The unfortunate error message hides the underlying problem which is, that input needs to be 2D to get a 2D output. If you want a 1D array you will need to use COO or DOK formats until the support for CSR is merged.

**Comment by fuglede** [comment] 2024-04-09 06:44
Right, the code that broke was relying on creating a 2D array from a 1D array, so when I say it seemed like a regression, it's because it did do exactly that before. :) Anyway, a good error message could also help save some head-scratching.

**Comment by rgommers** [comment] 2024-04-09 06:44
> I claim it is not a regression because the array interface should not be providing a 2D array from 1D input. The change is an inevitable change while moving to support more than 2D shapes.

Sometimes this kind of thing is hard to foresee if there isn't a test covering input like the 1D case here (at least, I assume there was no test). But it clearly is a regression, since it broke working code without any warning. The old behavior of promotion 1D input to 2D should have been emitting a `FutureWarning` instead, giving users a chance to fix their code before it was broken by a new scipy release.

**Closed** 2024-05-09 02:01 UTC
Labels: defect, scipy.sparse
