### ISSUE TITLE
BUG: optimize.minimize: garbage collection in `lbfgs`

### ISSUE THREAD

**Issue by lorentzenchr** [scipy/scipy#20768] opened 2024-05-22 20:06 UTC
### Describe your issue.

Iterated calls to LBFGS increase memory consumption if garbage collection is not explicitly called.

This pipped up in https://github.com/scikit-learn/scikit-learn/issues/28993.

### Reproducing Code Example

```python
import tracemalloc

from scipy.optimize import minimize
import numpy as np


def do_something(*args, **kwargs):
    return np.random.rand()


def do_train():
    minimize(
        do_something,
        np.random.rand(300),
        args=(np.random.rand(2000, 3000)),
        method="L-BFGS-B"
    )


def run(reps):
    tracemalloc.start()
    for _ in range(reps):
        do_train()

    base, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    print(f"| {reps:^6} | {base/ 1024**2:^9.2f} | {peak/ 1024**2:^9.2f} | {(peak-base)/ 1024**2:^9.2f} |")


if __name__ == "__main__":
    print("| # runs | base (MB) | peak (MB) | diff (MB) |")
    print("| ------ | --------- | --------- | --------- |")

    run(1)
    run(2)
    run(3)
    run(4)
    run(5)
    run(6)
    run(7)
    run(8)
    run(9)
    run(14)
    run(16)
    run(8)
```

### Error message

```shell
| # runs | base (MB) | peak (MB) | diff (MB) |
| ------ | --------- | --------- | --------- |
|   1    |   45.79   |   46.59   |   0.80    |
|   2    |   91.57   |   92.37   |   0.80    |
|   3    |  137.36   |  138.16   |   0.80    |
|   4    |  183.15   |  183.94   |   0.80    |
|   5    |  228.93   |  229.73   |   0.80    |
|   6    |  274.72   |  275.52   |   0.80    |
|   7    |   45.79   |  321.21   |  275.42   |
|   8    |  366.29   |  367.08   |   0.80    |
|   9    |  412.07   |  412.87   |   0.80    |
|   14   |  641.00   |  641.80   |   0.80    |
|   16   |  366.29   |  412.07   |   45.78   |
|   8    |  366.29   |  367.08   |   0.80    |
```

### SciPy/NumPy/Python version and system information

```shell
python: 3.10.11
scipy: 1.11.1
```

**Comment by Tialo** [comment] 2024-05-22 20:14
Also tested with scipy==1.13.0

**Comment by nickodell** [comment] 2024-05-22 22:11
I'm able to reproduce this behavior on commit c106aa5b.

Observations:

* This doesn't seem to be solver-specific. SLSQP, BFGS, and L-BFGS-B all leak memory at essentially the same speed.

   This implies that whatever is going wrong is common to all solvers.
* The args array is about 2000 * 3000 * 8 bytes large, which is about [45.7 MiB](https://www.wolframalpha.com/input?i=2000*3000*8bytes+in+mebibytes), which about how much the base memory usage increases by in each row of that table. This suggests that minimize() is keeping the args argument referenced somehow.
* Similarly, increasing the size of args (e.g. `np.random.rand(2000, 30000)`) makes the leak faster.
* Examining referrers to args, it seems it's being kept alive by ScalarFunction. This is strange, since ScalarFunction shouldn't live past the end of the minimization function. In fact, we have many ScalarFunction objects.

Here is a test program I wrote which runs the previous reproducer, and counts the number of ScalarFunction objects on the heap. It goes up each time by the number of times that minimize() has been called, except (I think) when garbage collection is run.

```
import tracemalloc

from scipy.optimize import minimize
import numpy as np
import gc
from scipy.optimize._differentiable_functions import ScalarFunction


def do_something(*args, **kwargs):
    return np.random.rand()



def do_train():
    a = np.random.rand(2000, 3000)
    minimize(
        do_something,
        np.random.rand(300),
        args=(a,),
        method="L-BFGS-B"
    )
    obj = a

    #for i in range(4):
    #    ref_list = gc.get_referrers(obj)
    #    print(ref_list)
    #    if i != 2:
    #        obj = ref_list[0]
    #    else:
    #        obj = ref_list[0][2]
    #    del ref_list


def run(reps):
    tracemalloc.start()
    for _ in range(reps):
        do_train()

    base, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    sf = 0
    for obj in gc.get_objects():
        if isinstance(obj, ScalarFunction):
            sf += 1
    print(f"| {reps:^6} | {base/ 1024**2:^9.2f} | {peak/ 1024**2:^9.2f} | {(peak-base)/ 1024**2:^9.2f} | {sf:^7} |")


if __name__ == "__main__":
    print("| # runs | base (MB) | peak (MB) | diff (MB) | SF objs |")
    print("| ------ | --------- | --------- | --------- | ------- |")

    run(1)
    run(2)
    run(3)
    run(4)
    run(5)
    run(6)
    run(7)
    run(8)
    run(9)
    run(14)
    run(16)
    run(8)
```

Output:

```
| # runs | base (MB) | peak (MB) | diff (MB) | SF objs |
| ------ | --------- | --------- | --------- | ------- |
|   1    |   45.80   |   45.91   |   0.12    |    1    |
|   2    |   91.57   |   91.69   |   0.12    |    3    |
|   3    |  137.36   |  137.48   |   0.12    |    6    |
|   4    |  183.15   |  183.26   |   0.12    |   10    |
|   5    |  228.93   |  229.05   |   0.12    |   15    |
|   6    |  274.72   |  274.84   |   0.12    |   21    |
|   7    |  320.50   |  320.62   |   0.12    |   28    |
|   8    |  320.50   |  320.62   |   0.12    |    7    |
|   9    |  412.07   |  412.19   |   0.12    |   16    |
|   14   |  641.00   |  641.12   |   0.12    |   30    |
|   16   |  274.72   |  503.67   |  228.95   |    7    |
|   8    |  366.29   |  366.40   |   0.12    |   15    |
```

**Comment by nickodell** [comment] 2024-05-22 23:20
I think there's some kind of reference cycle inside `ScalarFunction`. I found it was possible to stop memory usage from growing by setting the function attributes that `ScalarFunction` defines inside `ScalarFunction.__init__()` to None just before the `sf` variable goes out of scope.

Here's the diff:

```
diff --git a/scipy/optimize/_lbfgsb_py.py b/scipy/optimize/_lbfgsb_py.py
index 42ad9038e..e15818db2 100644
--- a/scipy/optimize/_lbfgsb_py.py
+++ b/scipy/optimize/_lbfgsb_py.py
@@ -441,6 +441,10 @@ def _minimize_lbfgsb(fun, x0, args=(), jac=None, bounds=None,
     hess_inv = LbfgsInvHessProduct(s[:n_corrs], y[:n_corrs])
 
     task_str = task_str.decode()
+    sf._update_fun_impl = None
+    sf._update_grad_impl = None
+    sf._update_hess_impl = None
+    sf._update_x_impl = None
     return OptimizeResult(fun=f, jac=g, nfev=sf.nfev,
                           njev=sf.ngev,
                           nit=n_iterations, status=warnflag, message=task_str,
 ```

(This is not a serious suggestion for a fix - this fix would be ugly and need to be applied in every place which uses ScalarFunction. Better to fix it in one place.)

Result:

```
| # runs | base (MB) | peak (MB) | diff (MB) | SF objs |
| ------ | --------- | --------- | --------- | ------- |
|   1    |   0.01    |   45.91   |   45.90   |    0    |
|   2    |   0.00    |   45.90   |   45.90   |    0    |
|   3    |   0.00    |   45.90   |   45.90   |    0    |
|   4    |   0.00    |   45.90   |   45.90   |    0    |
|   5    |   0.00    |   45.90   |   45.90   |    0    |
|   6    |   0.00    |   45.90   |   45.90   |    0    |
|   7    |   0.00    |   45.90   |   45.90   |    0    |
|   8    |   0.00    |   45.90   |   45.90   |    0    |
|   9    |   0.00    |   45.90   |   45.90   |    0    |
|   14   |   0.00    |   45.90   |   45.90   |    0    |
|   16   |   0.00    |   45.90   |   45.90   |    0    |
|   8    |   0.00    |   45.90   |   45.90   |    0    |
```

My best guess is that the functions defined inside `ScalarFunction.__init__()` have a closure that allows them to access local variables, such as `self`. Then those functions get assigned as instance variables of ScalarFunction, which creates the reference cycle.

**Comment by andyfaff** [comment] 2024-05-23 00:01
> thee functions defined inside ScalarFunction.__init__() have a closure that allows them to access local variables, such as self. Then those functions get assigned as instance variables of ScalarFunction

Those statements are correct, and I think that your deduction of the creation of the reference cycle is correct. It should be possible to amend `ScalarFunction` (and VectorFunction and LinearVectorFunction) to avoid this. However, I don't think it'll look as neat as it does now.

**Comment by andyfaff** [comment] 2024-05-23 00:04
It's also worth stating that this has been around for several releases, so it's a wonder that it's not been picked up earlier.

**Comment by nickodell** [comment] 2024-05-23 00:20
> Those statements are correct, and I think that your deduction of the creation of the reference cycle is correct. It should be possible to amend `ScalarFunction` (and VectorFunction and LinearVectorFunction) to avoid this. However, I don't think it'll look as neat as it does now.

Yeah. I've been trying to think about how to solve this without compromising code quality. I have three ideas for how to fix the reference cycle.

1. Move each function from `__init__()`, and add it as an instance method. Rename each function to avoid duplicates. e.g. [this `update_grad`](https://github.com/scipy/scipy/blob/95e27a8573a7e22a9b6b70d8bbc372d778001f89/scipy/optimize/_differentiable_functions.py#L178) call might be renamed to a method called `_update_grad_impl_with_numdiff`. Then `__init__()` would select that implementation by running `self._update_grad_impl = self._update_grad_impl_with_numdiff`.

   Cons: moves the condition controlling if the code is run away from the code that it runs.
2. Move each function from `__init__()`, into module scope, and use something like [WeakMethod here](https://stackoverflow.com/a/55414240/530160) to turn them into instance methods.

   Cons: don't know performance impact of weakref
3. The code above breaks the reference cycle by deleting all of the functions which have a reference to `self`. We could create a method called `ScalarFunction.close()`, which clears those four functions, which would allow the garbage collector to collect ScalarFunction when it goes out of scope.

   Then, we would go to every place where ScalarFunction is used, and add a call to `ScalarFunction.close()`.

   Cons: This would require 30 calls to ScalarFunction.close(). Every future use of this in the codebase would need it too, or it could create a new leak.

I'm not sure what approach would be best. Thoughts?

**Comment by fancidev** [comment] 2024-05-23 00:44
Option 1 seems the most natural to me. The current way (setting object attribute equal to local function with closure capture) looks like an anti-pattern to me.

An “object-oriented” approach may be to subclass this class depending on e.g. whether the Hessian is supplied. That would be more “proper” in my opinion, but it requires larger refactoring that I doubt anyone is keen to do.

**Closed** 2024-05-26 06:25 UTC
Labels: defect, scipy.optimize

**Comment by lorentzenchr** [comment] 2024-05-26 10:00
Wow, thanks for the very fast fix 🥳

**Comment by andyfaff** [comment] 2024-05-26 10:03
Bonus points for the MWE that was provided, and @nickodell for diagnosis of what was going on. Also, the original author of the code did a good job, so it wasn't difficult to modify.
