### ISSUE TITLE
BUG: cKDtree.query no longer accepts DataFrame as input

### ISSUE THREAD

**Issue by martinfleis** [scipy/scipy#18800] opened 2023-06-30 21:16 UTC
### Describe your issue.

Under scipy 1.10.1, `scipy.spatial.cKDTree.query` method accepts a pandas.DataFrame as an input to `x`. Once updated to 1.11.1 or 1.11.0, this no longer works and returns an error.

1.10.1 does not emit any deprecation on that front and I haven't found anything in the release notes so I believe this is actually a regression.

### Reproducing Code Example

```python
import scipy.spatial
import pandas as pd

points = [
    [66.22, 32.54], 
    [22.52, 22.39], 
    [31.01, 81.21],
    ]

tree = scipy.spatial.cKDTree(points, 10)
tree.query(pd.DataFrame(points), 1)
```

### Error message

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 11
      4 points = [
      5     [66.22, 32.54], 
      6     [22.52, 22.39], 
      7     [31.01, 81.21],
      8     ]
     10 tree = scipy.spatial.cKDTree(points, 10)
---> 11 tree.query(pd.DataFrame(points), 1)

File _ckdtree.pyx:794, in scipy.spatial._ckdtree.cKDTree.query()

File ~/mambaforge/envs/pointpats_dev/lib/python3.11/site-packages/pandas/core/generic.py:1466, in NDFrame.__nonzero__(self)
   1464 @final
   1465 def __nonzero__(self) -> NoReturn:
-> 1466     raise ValueError(
   1467         f"The truth value of a {type(self).__name__} is ambiguous. "
   1468         "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
   1469     )

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

### SciPy/NumPy/Python version and system information

```shell
1.11.0 1.24.4 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Users/martin/mambaforge/envs/pointpats_dev/include
    lib directory: /Users/martin/mambaforge/envs/pointpats_dev/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /Users/martin/mambaforge/envs/pointpats_dev/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /Users/martin/mambaforge/envs/pointpats_dev/include
    lib directory: /Users/martin/mambaforge/envs/pointpats_dev/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /Users/martin/mambaforge/envs/pointpats_dev/lib/pkgconfig
    version: 3.9.0
  pybind11:
    detection method: pkgconfig
    include directory: /Users/martin/mambaforge/envs/pointpats_dev/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: arm64-apple-darwin20.0.0-clang
    linker: ld64
    name: clang
    version: 15.0.7
  c++:
    commands: arm64-apple-darwin20.0.0-clang++
    linker: ld64
    name: clang
    version: 15.0.7
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: /Users/runner/miniforge3/conda-bld/scipy-split_1687763513919/_build_env/bin/arm64-apple-darwin20.0.0-gfortran
    linker: ld64
    name: gcc
    version: 12.2.0
  pythran:
    include directory: ../../../_build_env/venv/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
  cross-compiled: true
  host:
    cpu: arm64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /Users/martin/mambaforge/envs/pointpats_dev/bin/python
  version: '3.11'
```

**Comment by martinfleis** [comment] 2023-06-30 21:23
I believe it has been introduced in https://github.com/scipy/scipy/pull/18230 and is coming from this line https://github.com/scipy/scipy/blob/5353f121af03157207c62aa4dd8748888d855a2b/scipy/spatial/_ckdtree.pyx#L560

When passing a DataFrame, this does not return a scalar boolean but a Series. The condition then fails on the error above. I suppose wrapping `data` in `np.asarray(data)` will fix the issue here.

I will open a PR with a fix.

**Comment by ilayn** [comment] 2023-06-30 21:33
I'm not sure if this was supposed to accept a dataframe to start with, and I'm not sure we want to make that commitment now either to be honest. This should have been `df.toarray()` to start with.

**Comment by martinfleis** [comment] 2023-06-30 21:42
That is your call in the end but right now you can create a cKDtree from a DataFrame but you cannot query it using the same DataFrame. I guess that the question here is what is considered `array_like`. I always thought a DataFrame is `array_like` but I'll leave this decision to you. 

I can easily fix the downstream implementation ensuring we pass a numpy.array.

**Comment by ilayn** [comment] 2023-06-30 21:47
It's not just my call fortunately 😅  , so let's see what others also think

**Comment by tylerjereddy** [comment] 2023-06-30 21:54
Let's try checking with @sturlamolden and @peterbell10 to start with perhaps. I tend to agree that I don't think we intentionally supported DataFrames to begin with, but I'm not sure I'd be opposed to a small shim to continue supporting I suppose. Still, if we do that, I suppose we'd want a way to test the behavior, and we may not want to use `pandas` in our testsuite, though mocking up a small `class` or whatever with similar behavior may not be too bad if we really want to support this.

**Comment by mdhaber** [comment] 2023-06-30 22:33
There is some precedent:
https://github.com/scipy/scipy/issues/18254#issuecomment-1502406874

**Comment by tylerjereddy** [comment] 2023-06-30 22:37
Yeah, Ralf seems to call it a bug pretty decisively in that other case because it is an array-like? Interesting, I would have thought one could probably go digging through our code base and find a lot of array-like cases where a pandas thing might not work at the moment, but perhaps not! I guess the point might be that some folks may have been depending on this and that other particular case.

**Comment by mdhaber** [comment] 2023-06-30 22:45
> call it a bug pretty decisively in that other case 

It turned out to be that the pandas series was turning into an object array, and support for object arrays had been explicitly removed. We just ended up improving the error message and adding a test with a mock class as you suggested.

https://github.com/scipy/scipy/pull/18291/files

**Comment by ilayn** [comment] 2023-06-30 22:58
Historically speaking, `array_like` turned out to be a constant performance eater and did not deliver all the convenience promise it held back then. So I am really not in favor of adding pandas support to the word `array_like`. I don't think I agree with Ralf there. We already have a lot of pressure with array api stuff coming in from the gpu folks. And it has a potential to have a complicated story.

We have to hold the line somewhere before we start writing 100 lines of `if this make array, if that then do asarray if not then try this first otherwise cast to X, Y, Z` boilerplate code.

**Comment by sturlamolden** [comment] 2023-06-30 23:09
The bug is on line 794. It should say ```np.isfinite(x_arr).all()```.

**Comment by sturlamolden** [comment] 2023-06-30 23:10
Presumably we have this bug in the other query methods as well.

**Comment by martinfleis** [comment] 2023-07-01 10:41
From a user perspective, whenever I see `array_like` I assume it is what numpy considers array-like. If we take [`numpy.typing.ArrayLike`](https://numpy.org/devdocs/reference/typing.html#numpy.typing.ArrayLike) as a reference, it says

> A [Union](https://docs.python.org/3/library/typing.html#typing.Union) representing objects that can be coerced into an [ndarray](https://numpy.org/devdocs/reference/generated/numpy.ndarray.html#numpy.ndarray).
>
> Among others this includes the likes of:
>
> Scalars.
> (Nested) sequences.
> Objects implementing the `__array__` protocol.

Since DataFrame implements the `__array__` protocol, I automatically consider it array-like. 

Since scipy says in the docstring that an input can be `array_like`, it probably should follow this definition. Having scipy array-like being different from numpy array-like does not sound like a good idea.

Scipy should imho either ensure data are coerced to `numpy.array` whenever it states that an input can be `array_like` or change `array_like` to something more restricted.

This is my perspective as a user depending on both numpy and scipy in downstream. I don't know which implications this would have to the scipy codebase, apart from this one use case I reported above.

**Comment by tupui** [comment] 2023-07-01 11:29
With the work around supporting the Array API standard (which we are probably going to accept), we are moving towards being more explicit. Meaning we would actually not allow anymore things to be array_like and instead request an Array API compatible array. It would be the responsibility of the user to do the proper conversion.

As we can see here, allowing a bit of everything is causing code to pass/fail depending on how internals change. Which is not really desired. I think it's a good thing to ask users to be more explicit.

There is no plan for pandas and alike for SciPy for now. Actually, the Dataframe API standardization is just underway, so we should wait for this work first.

**Comment by sturlamolden** [comment] 2023-07-01 11:33
@martinfleis If you look at the Cython code ```scipy/spatial/_ckdtree.pyx``` you will see that cKDTree invokes ```np.ascontiguousarray``` on any argument defined as array-like. That is, it tries to coerce the argument into a contiguous Numpy array. However in this case, someone has ingnored this and continued to use the uncoerced array-like argument instead of the coerced array.

**Comment by sturlamolden** [comment] 2023-07-01 11:35
This is where the bug was introduced:

https://github.com/scipy/scipy/commit/2fe972659cda0df145ac46c84a7d98050358d506

**Comment by sturlamolden** [comment] 2023-07-01 11:43
@martinfleis
A simple fix is to replace ```np.isfinite(x)``` with ```np.isfinite(x_arr)```. However, I personally dislike forming an redundant array of booleans here. Rather we should loop over the memoryview ```xx``` and call C++11 math function ```std::isfinite``` on each element.

**Comment by tylerjereddy** [comment] 2023-07-01 20:47
Note that this "bug" doesn't exit with `KDTree` as I note over at https://github.com/scipy/scipy/pull/18804#pullrequestreview-1509019940, and indeed, you probably shouldn't be calling `cKDTree` anymore at this point in time per our docs:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html

> [cKDTree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html#scipy.spatial.cKDTree) is functionally identical to [KDTree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html#scipy.spatial.KDTree). Prior to SciPy v1.6.0, [cKDTree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.html#scipy.spatial.cKDTree) had better performance and slightly different functionality but now the two names exist only for backward-compatibility reasons. If compatibility with SciPy < 1.6 is not a concern, prefer [KDTree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html#scipy.spatial.KDTree).

**Comment by tylerjereddy** [comment] 2023-07-01 20:48
I'd almost be tempted to say we shouldn't even fix bugs for `cKDTree` anymore to avoid a maintenance yo-yo!

**Comment by sturlamolden** [comment] 2023-07-02 02:32
It is a regression for old code that use cKDTree directly. There are plenty of that. The PR removes the regression and makes sure KDTree and cKDTree are functionally identical.

**Comment by sturlamolden** [comment] 2023-07-02 03:14
I am not sure what I think of using KDTree as a cludge for cKDTree and having future bug fixes in the kludge code. (If that is what is implied here.) I would rather we keep the cKDTree code as bug-free as we can.  If cKDTree docstring says an argument is array-like then it should work for array-like arguments, presumably through explicit coercion. A related question is when (or if) we should deprecate direct invocation of cKDTree. However, the current situation is that cKDTree is still exported in the scipy.spatial API. A functionality regression in cKDTree therefore warrants a fix, at least for now.

**Comment by tylerjereddy** [comment] 2023-07-02 03:25
I just wanted to bring it up because the discouraged path was being used
and the preferred code path wasn’t even discussed nor checked above, so I
had to analyze two code paths, which has some maintenance cost.

I’m fine with patching both for now but something to think about maybe

**Closed** 2023-07-02 03:48 UTC
Labels: defect, scipy.spatial

**Comment by tylerjereddy** [comment] 2023-07-02 03:51
I merged the fix for `cKDTree`, but I do indeed think we should consider deprecating the discouraged incantation rather than indefinite maintenance of two code paths to do the same thing.

**Comment by ilayn** [comment] 2023-07-02 06:20
I don't know enough about the legacy but if both are doing the same, why not deprecating it? We have subzillions of similar warnings emitted at each version anyways. It won't be the first to disappear from the namespace.

**Comment by tupui** [comment] 2023-07-02 08:46
I am +1 on deprecating a path. We should not have n functions doing the same thing. It's confusing for users and costly for us.

A new deprecation @j-bowhay 😃

**Comment by sturlamolden** [comment] 2023-07-02 10:32
> I don't know enough about the legacy but if both are doing the same, why not deprecating it? We have subzillions of similar warnings emitted at each version anyways. It won't be the first to disappear from the namespace.

KDTree used to be a pure Python implementation that had more methods than cKDTree. It was a pure Cython version that only had the query method. Now, KDTree is a wrapper for cKDTree, which is a Cython wrapper for C++ code. So today we only need to export KDTree in the API. We still have cKDTree in the API for backwards compatibility. We cannot deprecate cKDTree as such, it is needed internally, but we can deprecate it in the exported API.

**Comment by sturlamolden** [comment] 2023-07-02 10:33
I am +1 on deprecation as well.
