### ISSUE TITLE
BUG: Scipy >=1.11.1, GCC 8.5.0 and Cython 3.0.5 combination on RHEL8/Centos Stream 8 results in undefined symbol for wrap_PyUFunc_getfperr when collecting tests

### ISSUE THREAD

**Issue by stratakis** [scipy/scipy#19594] opened 2023-11-25 20:56 UTC
### Describe your issue.

When running the tests after having scipy compiled on a RHEL8/CentOS Stream 8 system with Cython >= 3, I get an undefined symbol error for wrap_PyUFunc_getfperr and more specifically 202 errors which are all of the type:

```
____________________________________________________________________________________________ ERROR collecting cluster/tests/test_disjoint_set.py _____________________________________________________________________________________________
ImportError while importing test module '/usr/local/lib64/python3.11/site-packages/scipy/cluster/tests/test_disjoint_set.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/cluster/__init__.py:27: in <module>
    from . import vq, hierarchy
scipy/cluster/vq.py:72: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:116: in <module>
    from ._geometric_slerp import geometric_slerp
scipy/spatial/_geometric_slerp.py:9: in <module>
    from scipy.spatial.distance import euclidean
scipy/spatial/distance.py:121: in <module>
    from ..special import rel_entr
scipy/special/__init__.py:772: in <module>
    from . import _ufuncs
_ufuncs.pyx:1: in init scipy.special._ufuncs
    ???
E   ImportError: /usr/local/lib64/python3.11/site-packages/scipy/special/_ufuncs_cxx.cpython-311-x86_64-linux-gnu.so: undefined symbol: wrap_PyUFunc_getfperr
```

The GCC version is 8.5.0 and I've tested both Python 3.11 and 3.12. It only happens with Cython >= 3, the previous Cython versions pose no problem.

Also higher GCC versions (e.g.  11.4.1 on RHEL9) don't exhibit this behavior with the same parameters.

I've tested the scipy versions from 1.11.1 to 1.11.4 and it's the same for all.

### Reproducing Code Example

```python
on a Centos Stream 8 container system:

Dependencies:
$ dnf config-manager --set-enabled powertools
$ dnf install dnf-plugins-core
$ dnf builddep python3.11-scipy
$ dnf remove python3.11-Cython # to remove the older version provided by the distro
$ dnf install python3.11-pip git


Clone the scipy repo and checkout the v.1.11.4 tag
$ git submodule update --init
$ python3.11 -m pip install Cython==3.0.5
$ SCIPY_USE_PYTHRAN=0 python3.11 _setup.py build
$ SCIPY_USE_PYTHRAN=0 python3.11 _setup.py install
$ cd /usr/local/lib64/python3.11/site-packages/
$ python3.11 -m pytest scipy/
```

### Error message

```shell
____________________________________________________________________________________________ ERROR collecting cluster/tests/test_disjoint_set.py _____________________________________________________________________________________________
ImportError while importing test module '/usr/local/lib64/python3.11/site-packages/scipy/cluster/tests/test_disjoint_set.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/cluster/__init__.py:27: in <module>
    from . import vq, hierarchy
scipy/cluster/vq.py:72: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:116: in <module>
    from ._geometric_slerp import geometric_slerp
scipy/spatial/_geometric_slerp.py:9: in <module>
    from scipy.spatial.distance import euclidean
scipy/spatial/distance.py:121: in <module>
    from ..special import rel_entr
scipy/special/__init__.py:772: in <module>
    from . import _ufuncs
_ufuncs.pyx:1: in init scipy.special._ufuncs
    ???
E   ImportError: /usr/local/lib64/python3.11/site-packages/scipy/special/_ufuncs_cxx.cpython-311-x86_64-linux-gnu.so: undefined symbol: wrap_PyUFunc_getfperr
______________________________________________________________________________________________ ERROR collecting cluster/tests/test_hierarchy.py ______________________________________________________________________________________________
ImportError while importing test module '/usr/local/lib64/python3.11/site-packages/scipy/cluster/tests/test_hierarchy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/cluster/__init__.py:27: in <module>
    from . import vq, hierarchy
scipy/cluster/vq.py:72: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:116: in <module>
    from ._geometric_slerp import geometric_slerp
scipy/spatial/_geometric_slerp.py:9: in <module>
    from scipy.spatial.distance import euclidean
scipy/spatial/distance.py:121: in <module>
    from ..special import rel_entr
scipy/special/__init__.py:772: in <module>
    from . import _ufuncs
_ufuncs.pyx:1: in init scipy.special._ufuncs
    ???
E   ImportError: /usr/local/lib64/python3.11/site-packages/scipy/special/_ufuncs_cxx.cpython-311-x86_64-linux-gnu.so: undefined symbol: wrap_PyUFunc_getfperr
_________________________________________________________________________________________________ ERROR collecting cluster/tests/test_vq.py __________________________________________________________________________________________________
ImportError while importing test module '/usr/local/lib64/python3.11/site-packages/scipy/cluster/tests/test_vq.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/cluster/__init__.py:27: in <module>
    from . import vq, hierarchy
scipy/cluster/vq.py:72: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:116: in <module>
    from ._geometric_slerp import geometric_slerp
scipy/spatial/_geometric_slerp.py:9: in <module>
    from scipy.spatial.distance import euclidean
scipy/spatial/distance.py:121: in <module>
    from ..special import rel_entr
scipy/special/__init__.py:772: in <module>
    from . import _ufuncs
_ufuncs.pyx:1: in init scipy.special._ufuncs
    ???
E   ImportError: /usr/local/lib64/python3.11/site-packages/scipy/special/_ufuncs_cxx.cpython-311-x86_64-linux-gnu.so: undefined symbol: wrap_PyUFunc_getfperr
```

### SciPy/NumPy/Python version and system information

```shell
1.11.4 1.23.5 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblasp', 'openblasp']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblasp', 'openblasp']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblasp', 'openblasp']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblasp', 'openblasp']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
    not found = AVX512_KNL,AVX512_KNM
```

**Comment by tylerjereddy** [comment] 2023-11-25 22:54
> `python3.11 _setup.py build`

A few questions here:

1) Why are you using the old `setup.py` infrastructure instead of building with `meson`?
2) Why do you need to build from source instead of using a pre-built binary (`pip install scipy`)?
3) Is this just `x86_64` Linux, or something more exotic?

**Comment by stratakis** [comment] 2023-11-26 01:05
> > `python3.11 _setup.py build`
> 
> A few questions here:
> 
>     1. Why are you using the old `setup.py` infrastructure instead of building with `meson`?
> 

While the reproducer I've provided is working through building scipy from the github sources, the actual discovery happened when building scipy as an rpm for the python3.12 stack. I can't use meson since we don't ship it in RHEL. Although just for the sake of investigation, I've tried to work it out a bit and check what happens (by installing meson through pip) but I fell short on the openblas detection mechanism of the meson build system.

>     2. Why do you need to build from source instead of using a pre-built binary (`pip install scipy`)?
> 

Answered above.

>     3. Is this just `x86_64` Linux, or something more exotic?

Tested on x86_64, aarch64, s390x and ppc64le, all with the same result, so it's not arch dependent.

**Comment by andyfaff** [comment] 2023-11-26 01:28
I would be focussing here on getting your build to work with the new meson approach, using `setup.py` is not supported any more. What went wrong with the openblas detection with meson? 

meson uses pkg-config or cmake to figure out where openblas lives. So set PKG_CONFIG_PATH to where the openblas.pc file lives and you should be sweet.

**Comment by stratakis** [comment] 2023-11-26 02:24
> I would be focussing here on getting your build to work with the new meson approach, using `setup.py` is not supported any more. What went wrong with the openblas detection with meson?
> 
> meson uses pkg-config or cmake to figure out where openblas lives. So set PKG_CONFIG_PATH to where the openblas.pc file lives and you should be sweet.

That is not possible at least for the rpm's. meson is not shipped through the distro. In order to make it work I'll either have to utilize a lower Cython version or figure out this issue if possible.

The problem with meson and openblas detection is the missing .pc file from the openblass-devel package, which was not a problem with the setup.py build. I guess I can workaround it by creating my own .pc file and configure the env variable but unfortunately I am restricted to using only the setup.py for the rpm's at this time.

**Comment by andyfaff** [comment] 2023-11-26 02:31
Unfortunately `setup.py` is not something that is going to be supported by the dev team at this point, but we will try to work to get the meson based approach usable for you.

- Can you ask the `openblass-devel` package to ship a .pc file, or a cmake config file? (what are the restrictions for them not adding it)

Further instructions for meson related blas library detection can be found at https://docs.scipy.org/doc/scipy/building/blas_lapack.html.

**Comment by rgommers** [comment] 2023-11-26 08:01
The `1.11.x` minor release does not support Cython 3: https://github.com/scipy/scipy/blob/maintenance/1.11.x/pyproject.toml#L16. We have backported as many changes as possible, but there's a reason there's a `<3` constraint there. Cython 3 broke a lot of things, and was released after 1.11.0. 

The pragmatic thing to do here seems to be to simply use a newer GCC or an older Cython, since you say both fix the problem.

Re Meson/RHEL/OpenBLAS:
- The root cause of this problem is that Fedora (and hence RHEL I assume) has a packager who refuses to ship `openblas.pc`. The bug is https://bugzilla.redhat.com/show_bug.cgi?id=1574517. If you have some leverage to move that along, that'd be great, because the attitude there is ridiculous. They're knowingly leaving out necessary build config files (the `.cmake` ones too IIRC).
- We'll get around to working around the problem, but not before Meson 1.4.0
- I'll also note that if you're building an RPM to be packaged in RHEL (is that the case?), then you should be using FlexiBLAS rather than OpenBLAS I believe. Use `-C-Dblas=flexiblas -C-Dlapack=flexiblas` for that (see http://scipy.github.io/devdocs/building/blas_lapack.html for more details).

**Comment by stratakis** [comment] 2023-11-26 15:18
> Unfortunately `setup.py` is not something that is going to be supported by the dev team at this point, but we will try to work to get the meson based approach usable for you.
> 

Unfortunately as mentioned before it's not possible to utilize meson for this usecase. I understand though that the developers would like to move forward to meson and not support the setup.py infrastructure anymore, so if it's not possible to figure this out I'll utilize the lesser Cython version.

>     * Can you ask the `openblass-devel` package to ship a .pc file, or a cmake config file? (what are the restrictions for them not adding it)
> 

Interestingly enough I found out that RHEL8 actually ships a .pc file as of recently: https://gitlab.com/redhat/centos-stream/rpms/openblas/-/blob/c8s/openblas.spec#L686

But still when I tried out the meson build it didn't detect it.

Nevertheless, as I can't use meson, pondering about this is not going to help me in this case.

> 
> Further instructions for meson related blas library detection can be found at https://docs.scipy.org/doc/scipy/building/blas_lapack.html.

**Comment by stratakis** [comment] 2023-11-26 15:24
> The `1.11.x` minor release does not support Cython 3: https://github.com/scipy/scipy/blob/maintenance/1.11.x/pyproject.toml#L16. We have backported as many changes as possible, but there's a reason there's a `<3` constraint there. Cython 3 broke a lot of things, and was released after 1.11.0.
> 
> The pragmatic thing to do here seems to be to simply use a newer GCC or an older Cython, since you say both fix the problem.
> 

I understand, that might be the way to go. If however there could be some pointers provided in order to debug this further, I'd appreciate that.

> Re Meson/RHEL/OpenBLAS:
> 
>     * The root cause of this problem is that Fedora (and hence RHEL I assume) has a packager who refuses to ship `openblas.pc`. The bug is https://bugzilla.redhat.com/show_bug.cgi?id=1574517. If you have some leverage to move that along, that'd be great, because the attitude there is ridiculous. They're knowingly leaving out necessary build config files (the `.cmake` ones too IIRC).
> 
>     * We'll get around to working around the problem, but not before Meson 1.4.0
> 
>     * I'll also note that if you're building an RPM to be packaged in RHEL (is that the case?), then you should be using FlexiBLAS rather than OpenBLAS I believe. Use `-C-Dblas=flexiblas -C-Dlapack=flexiblas` for that (see http://scipy.github.io/devdocs/building/blas_lapack.html for more details).

RHEL8 doesn't ship FlexiBLAS, just OpenBLAS (in contrast to RHEL9), so that's is not an option unfortunately.

Nevertheless, the issue here is not about the meson build specifically, but if I can figure out the problem with setup.py. If that is not possible I'll utilize Cython < 3 and that should be fine. I get that devels would prefer to iron out the new build system instead of old obsolete infrastructure, so it's ok if we close this issue.

**Comment by rgommers** [comment] 2023-11-27 09:10
> If however there could be some pointers provided in order to debug this further, I'd appreciate that.

I have some recollection about seeing `wrap_PyUFunc_getfperr` before. I can't remember though if it was fixed in Cython or in SciPy - I suspect in Cython.

> If that is not possible I'll utilize Cython < 3 and that should be fine.

That sounds easiest indeed.

>  so it's ok if we close this issue.

Thanks @stratakis, I'll do that.

**Closed by rgommers** 2023-11-27 09:10 UTC
Labels: defect, Build issues, Cython

**Comment by andyfaff** [comment] 2023-11-27 09:14
That symbol is supposed to be defined in `special`, https://github.com/search?q=repo%3Ascipy%2Fscipy%20wrap_PyUFunc_getfperr&type=code

**Comment by stratakis** [comment] 2023-11-28 17:47
I see the same issue popping up here: https://github.com/conda-forge/scipy-feedstock/pull/244#issuecomment-1683142256 and here: https://github.com/termux-user-repository/tur/issues/546

Possibly related to https://github.com/scipy/scipy/issues/19003
