### ISSUE TITLE
minpack2.cpython-38-darwin.so, 2): Symbol not found: _Py_SET_TYPE

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#12489] opened 2020-07-05 08:21 UTC
macOS 10.15.5
Python 3.8.3
numpy 1.19.0
cython 0.29.20

- create a new conda environment with Python 3.8.3
- `pip install numpy cython pytest pybind11`
- git clean -xdf
- git checkout master
- build scipy (4c7b25e4816f6246f30bdfbe5cd7d258f4f107e6) with `python setup.py build`
- install scipy via `pip install .`

I then change out of the scipy directory and try to import scipy:

```
>>> import scipy.optimize as sciopt
sciopt.Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/__init__.py", line 387, in <module>
    from .optimize import *
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 33, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/linesearch.py", line 16, in <module>
    from scipy.optimize import minpack2
ImportError: dlopen(/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/minpack2.cpython-38-darwin.so, 2): Symbol not found: _Py_SET_TYPE
  Referenced from: /Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/minpack2.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/optimize/minpack2.cpython-38-darwin.so
```

pip installing the latest release works.

**Comment by andyfaff** [comment] 2020-07-05 08:32
I tried install cython 0.29.18, the import works then. So something in 0.29.19 onwards causes problems here.

**Comment by pv** [comment] 2020-07-05 09:00
scipy.optimize.minpack2 is f2py'd stuff, so it's unclear why Cython
version affects this.

**Comment by andyfaff** [comment] 2020-07-05 09:20
I don't know why either, but I just checked this behaviour twice.

**Comment by KrisKennaway** [comment] 2020-08-08 21:39
I'm getting the same error, but dropping back to Cython 0.29.18 didn't fix it.

**Comment by peterbell10** [comment] 2020-08-09 01:40
This is very weird since the symbol `_Py_SET_TYPE` only exists in python 3.9 and above. And even then, it's defined as `static inline` in the header so even if the wrong version was included by accident, it should still have the definition anyway.

@andyfaff why do you run both `python setup.py build` and `pip install .`? I think that could potentially cause problems due to building with multiple numpy versions. `python setup.py build` would run `f2py` from numpy 1.19 and generate `Py_SET_TYPE` calls. Then when you do `pip install .` it builds the wheel in an isolated build environment with numpy 1.17.3; still using the `f2py` code generated by numpy 1.19. That could be the root of the issue. Maybe try `git clean -xdf` then build using pip only. 

That still wouldn't explain how `_Py_SET_TYPE` got into the build without python 3.9 though.

**Comment by andyfaff** [comment] 2020-08-09 08:57
> why do you run both `python setup.py build` and `pip install .`?

I was seeing if either way of building was different in the outcome. I'd already tried `git clean -xdf` before trying each type of build.

I'm wondering if it's creeping in via miniconda. I'm building in an environment with pip installed numpy (1.19.1) and I experience little build issues up until now. Why wouldn't either build approach use the numpy installed in the environment?

@KrisKennaway, are you on macOS? Are you using conda?

**Comment by andyfaff** [comment] 2020-08-09 09:03
Here's another example:
```
(dev3) 192-168-1-103:programming andrew$ python
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.stats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/stats/__init__.py", line 387, in <module>
    from .stats import *
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/stats/stats.py", line 174, in <module>
    from scipy.spatial.distance import cdist
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._procrustes import procrustes
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/spatial/_procrustes.py", line 9, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/linalg/__init__.py", line 194, in <module>
    from .misc import *
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/linalg/misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(/Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-darwin.so, 2): Symbol not found: _Py_SET_TYPE
  Referenced from: /Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-darwin.so
```
Then
```
(dev3) 192-168-1-103:programming andrew$ nm -a /Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-darwin.so | grep Py_SET_TYPE
                 U _Py_SET_TYPE
```
The relevant part of the `_fblas.cpython-38-darwin.so` symbol table is:
```
00000000000017d0 - 01 0000   FUN _PyInit__fblas
                 U _PyLong_AsLong
                 U _PyMem_Free
                 U _PyMem_Malloc
                 U _PyModule_Create2
                 U _PyModule_GetDict
                 U _PyNumber_Float
                 U _PyNumber_Long
                 U _PyOS_snprintf
                 U _PyObject_Free
                 U _PyObject_GenericGetAttr
                 U _PyObject_GetAttrString
                 U _PyObject_SetAttrString
                 U _PySequence_Check
                 U _PySequence_GetItem
                 U _PyType_IsSubtype
                 U _PyType_Type
                 U _PyUnicode_Concat
                 U _PyUnicode_FromFormat
                 U _PyUnicode_FromString
                 U _PyUnicode_FromStringAndSize
                 U _Py_BuildValue
                 U _Py_SET_TYPE
                 U __PyObject_New
                 U __Py_Dealloc
                 U __Py_NoneStruct
                 U ___bzero
                 U ___snprintf_chk
                 U ___sprintf_chk
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U ___stderrp
                 U ___strcat_chk
```

**Comment by andyfaff** [comment] 2020-08-09 09:10
The `Py_SET_TYPE` is not in the Python executable in the conda env:
```
nm -a /Users/andrew/miniconda3/envs/dev3/bin/python | grep Py_SET_TYPE
```
doesn't show anything.

**Comment by andyfaff** [comment] 2020-08-09 09:13
Not sure if it's relevant, but if I do this in the site-packages directory:
```
(dev3) 192-168-1-103:site-packages andrew$ grep -r Py_SET_TYPE numpy
numpy/core/include/numpy/npy_3kcompat.h:    #define Py_SET_TYPE(obj, typ) (Py_TYPE(obj) = typ)
numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c:  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
numpy/f2py/rules.py:\tPy_SET_TYPE(&PyFortran_Type, &PyType_Type);
Binary file numpy/f2py/__pycache__/rules.cpython-38.pyc matches
```

**Comment by KrisKennaway** [comment] 2020-08-09 09:13
> I'm wondering if it's creeping in via miniconda. I'm building in an environment with pip installed numpy (1.19.1) and I experience little build issues up until now. Why wouldn't either build approach use the numpy installed in the environment?
> 
> @KrisKennaway, are you on macOS? Are you using conda?

I'm on MacOS 10.15.6, but using pypy3 installed from homebrew.

I can't find a mention of Py_SET_TYPE outside of this package, e.g. 

$ grep -r Py_SET_TYPE /usr/local
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/linalg/_flinalg.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/linalg/_interpolative.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/linalg/_flapack.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/linalg/_fblas.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/optimize/_cobyla.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/optimize/__nnls.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/optimize/_slsqp.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/optimize/_lbfgsb.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/optimize/minpack2.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/integrate/vode.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/integrate/_dop.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/integrate/_test_odeint_banded.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/integrate/lsoda.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/io/_test_fortran.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/special/specfun.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/interpolate/dfitpack.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/sparse/linalg/isolve/_iterative.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/sparse/linalg/eigen/arpack/_arpack.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/stats/mvn.pypy36-pp73-darwin.so matches
Binary file /usr/local/Cellar/pypy3/7.3.1_1/libexec/site-packages/scipy/stats/statlib.pypy36-pp73-darwin.so matches

**Comment by andyfaff** [comment] 2020-08-09 09:21
Perhaps for some reason numpy is including the symbol on Py 3.8, even though it doesn't seem to use the symbol itself.
```
# in /Users/andrew/miniconda3/envs/dev3/lib/python3.8/site-packages/numpy/core
nm -a *.so | grep Py_SET_TYPE
```
gives nothing.

**Comment by andyfaff** [comment] 2020-08-09 09:26
In `numpy/core/include/numpy/npy_3kcompat.h`:
```
#if PY_VERSION_HEX < 0x030900a4
    /* Introduced in https://github.com/python/cpython/commit/d2ec81a8c99796b51fb8c49b77a7fe369863226f */
    #define Py_SET_TYPE(obj, typ) (Py_TYPE(obj) = typ)
    /* Introduced in https://github.com/python/cpython/commit/b10dc3e7a11fcdb97e285882eba6da92594f90f9 */
    #define Py_SET_SIZE(obj, size) (Py_SIZE(obj) = size)
#endif
```
shouldn't this be a greater than?

@rgommers, who would be the best person to ping from the numpy team to see if they have any insight?

**Comment by peterbell10** [comment] 2020-08-09 11:39
>Why wouldn't either build approach use the numpy installed in the environment?

Because of [build-isolation](https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support). The `pyproject.toml` specifies `numpy==1.17.3` is used for python 3.8.
https://github.com/scipy/scipy/blob/96caa9dab5b6921c2c85899d198c9503d3c6c652/pyproject.toml#L8

>In numpy/core/include/numpy/npy_3kcompat.h: [...] shouldn't this be a greater than?

That's the fallback for python version that don't define `Py_SET_SIZE`. So no, it should be less than.

**Comment by rgommers** [comment] 2020-08-09 13:35
> @rgommers, who would be the best person to ping from the numpy team to see if they have any insight?

Probably @mattip. But can you first update your reproducer? As @peterbell10 pointed out, mixing `python setup.py build` and `pip install .` is a bad idea, because you're mixing build artifacts from two builds with different numpy versions.

**Comment by rgommers** [comment] 2020-08-09 14:10
I cannot reproduce this with
```
conda create -n tmp python=3.8
conda activate tmp
pip install numpy cython pytest pybind11
git clean -xdf
python setup.py build_ext -i
```
Note that that installs Python 3.8.5, not 3.8.3 Also, this odd conda/pip mix will not install a BLAS library, so it will still pick up Accelerate (and tests then crash in `linalg/test_basic` for me).

**Comment by mattip** [comment] 2020-08-09 14:36
As mentioned above, according to [PEP 620](https://www.python.org/dev/peps/pep-0620/#disallow-using-py-type-as-l-value), `Py_SET_TYPE` is a new interface meant to replace using `Py_TYPE` as an l-value. In numpy, we have it [as a define](https://github.com/numpy/numpy/blob/a0028bca0117874606bce99261d978df8d3f6610/numpy/core/include/numpy/npy_3kcompat.h#L63) for forward compatibility. I still don't understand how that `#define` is "leaking" out into the shared objects and what the connection to cython could be.

**Comment by mattip** [comment] 2020-08-09 14:51
The only thing I can think of is that somehow your build is getting mixed up, using sources from a recent numpy which [uses `Py_TYPE_SET`](https://github.com/numpy/numpy/blob/18a6e3e505ee416ddfc617f3e9afdff5a031c2c2/numpy/core/src/multiarray/dtypemeta.c#L439) but somehow the headers used in the compilation do not use the version with the `#define`. This could happen if 
-an old version of the numpy headers leaked into one of the `INCLUDE` paths that appear before the ones in the build framework for scipy
- numpy is built with this broken set of headers
- the cythonized files are linked to this newer and broken version of numpy

Does `import numpy` succeed?

**Comment by peterbell10** [comment] 2020-08-09 17:16
>I still don't understand how that #define is "leaking" out into the shared objects and what the connection to cython could be.

Ignoring the `_` for a moment, calling `Py_SET_TYPE(obj, type)` when there is no macro defined might be creating a new implicit function declaration. As for the underscore, for reasons I don't understand, it seems like for some reason every symbol in @andyfaff's `nm` output has an extra underscore. For examble, `_PyObject_GetAttrString` shouldn't have an underscore, `__Py_Dealloc` should only have one underscore and `___snprintf_chk` should have two underscores instead of 3.

**Comment by andyfaff** [comment] 2020-08-10 01:41
This just worked for me without error:

```
(base) $ conda create -n dev38 python=3.8
(dev38) $ conda activate dev38
(dev38) $ python --version
Python 3.8.5

(dev38) $ git clean -xdf
(dev38) $ pip install cython numpy pybind11

Collecting numpy
  Using cached numpy-1.19.1-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
Collecting cython
  Using cached Cython-0.29.21-cp38-cp38-macosx_10_9_x86_64.whl (1.9 MB)
Collecting pybind11
  Using cached pybind11-2.5.0-py2.py3-none-any.whl (296 kB)
Installing collected packages: numpy, cython, pybind11
Successfully installed cython-0.29.21 numpy-1.19.1 pybind11-2.5.0

(dev38) $ pip install .
Processing /Users/andrew/Documents/Andy/programming/scipy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: scipy
  Building wheel for scipy (PEP 517) ... done
  Created wheel for scipy: filename=scipy-1.6.0.dev0+96caa9d-cp38-cp38-macosx_10_9_x86_64.whl size=18749869 sha256=a60d81519364b81b2900dcaf130a96278794b55833ce566654eec67d48fbfedb
  Stored in directory: /private/var/folders/m8/gwtcncws12jf60xw5n6knwnw0000gn/T/pip-ephem-wheel-cache-zmin2im9/wheels/dd/e2/ce/5e25e40098d319817f14448037967682ebcd7efcbb8c9ded4c
Successfully built scipy
Installing collected packages: scipy
Successfully installed scipy-1.6.0.dev0+96caa9d


(dev38) $ cd ..
(dev38) $ python
Python 3.8.5 (default, Aug  5 2020, 03:39:04) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import scipy.stats
>>> exit()
```

```
python setup.py build; python setup.py develop
```
now also work.

*What does not work is*:
```
python setup.py build
pip install .
```

So @peterbell10, your comment is correct. What I didn't know, and I'm not sure that it's in the documentation, is that `pip install .` pins the numpy version for building. I was under the impression that it always used the current installed version (if it was recent enough). What is the recommended build/install route if one wants to use the installed version of numpy to build scipy?

@mattip, `import numpy` always worked.

**Comment by tylerjereddy** [comment] 2020-08-11 02:14
> What is the recommended build/install route if one wants to use the installed version of numpy to build scipy?

You may be looking for the `--no-build-isolation` flag for `pip`. I believe I've used this in CI in a few places, or at least it used to be there.

**Comment by rgommers** [comment] 2021-02-06 20:50
Looks like we're all good here. I can't think of an obvious place to document not to use
```
python setup.py build
pip install .
```
so I think we should close this?

**Closed** 2021-04-14 18:17 UTC
Labels: Build issues, C/C++
