### ISSUE TITLE
Warnings -> errors causing new wheel build failures

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#7538] opened 2017-06-28 13:26 UTC
https://travis-ci.org/MacPython/scipy-wheels/builds/247856101

First - nose generates some warnings on Python 3.5 which now generate failures:

```
======================================================================
ERROR: test suite for <module 'test_streams' from '/venv/lib/python3.5/site-packages/scipy/io/matlab/tests/test_streams.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/venv/lib/python3.5/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/venv/lib/python3.5/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/venv/lib/python3.5/site-packages/nose/util.py", line 453, in try_run
    inspect.getargspec(func)
  File "/usr/lib/python3.5/inspect.py", line 1041, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

E.g. https://travis-ci.org/MacPython/scipy-wheels/jobs/247856114

Also, on OSX:

```
======================================================================

ERROR: test_check_finite (test_basic.TestLstsq)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/build/MacPython/scipy-wheels/venv/lib/python2.7/site-packages/scipy/linalg/tests/test_basic.py", line 1228, in test_check_finite

    overwrite_b=overwrite)

  File "/Users/travis/build/MacPython/scipy-wheels/venv/lib/python2.7/site-packages/scipy/linalg/basic.py", line 1140, in lstsq

    warnings.warn(mesg, RuntimeWarning)

RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
```

E.g. https://travis-ci.org/MacPython/scipy-wheels/jobs/247856124

**Comment by seberg** [comment] 2017-06-28 14:20
Ah crap, the first one would probably be fixed on numpy master, but that does not help for scipy. At least for the second, can you add the suppression yourself? Sounds like it should go into the test itself, since it seems a valid warning?

**Comment by seberg** [comment] 2017-06-28 14:26
Unfortunately, my guess is we will have to add a warning filter into the test function and accordingly runtest.py to fix the first thing :(.

**Comment by seberg** [comment] 2017-06-28 14:27
Wait, no, why is this only in `test_streams`? Or does the whole suit fail? In that case maybe it is a problem during test streams setup?

**Comment by seberg** [comment] 2017-06-28 14:35
So, nvm. the change in numpy won't help here anyway, it would help with errors in nose during setup (plugins not loading). So here, I am not sure what might help, but I think we will probably have to add a suppression before starting the test, which in numpy would be convenient, but in scipy is a bit uglier (since scipy just imports this stuff from numpy).

**Comment by seberg** [comment] 2017-06-28 16:47
Hmmm, another option could even be to just avoid the `setup_module/setup` stuff from nose, which in 2 of the four cases is used for warning catching and in one probably does not need the function at all since no teardown seems needed. The last one however creates a temporary file, so it probably depends on the rest of the module if one could avoid it.

But then it is a pretty annoying way to circumvent a simple warning....

**Comment by seberg** [comment] 2017-06-28 20:00
Hehe, in numpy I actually went this far for that warning:
```
            warnings.filterwarnings("ignore", message=".*getargspec.*",
                                    category=DeprecationWarning,
                                    module=r"nose\.")
```
(because module filters are hard, and I am sure we seriously don't care at all about this warning, ever), and quite frankly, maybe we can just add it before the two `test()` entry points.

@rgommers maybe we really need some better way of making the test filters specific to scipy and not just inherit 50 lines of funny warning filter setup from numpy?

**Comment by rgommers** [comment] 2017-06-29 12:13
> Hehe, in numpy I actually went this far for that warning:

Why isn't that filter being picked up for scipy? We're using the same ``Tester.test`` method as ``scipy.test``.

**Comment by rgommers** [comment] 2017-06-29 12:17
> @rgommers maybe we really need some better way of making the test filters specific to scipy and not just inherit 50 lines of funny warning filter setup from numpy?

Note that some of those funny filters, like ``numpy.dtype size changed`` are for ``scipy`` and other packages, not for ``numpy`` itself. 

We can reimplement ``test``, but we'd likely start by just copying all of those filters. I'm not sure we can leave many out.

**Comment by rgommers** [comment] 2017-06-29 12:19
> another option could even be to just avoid the `setup_module/setup` stuff from nose

+1 those were annoying, and hard to read/understand since you hardly ever need those

**Comment by seberg** [comment] 2017-06-29 13:05
Well, in principle SciPy will pick them up, but for that you need to do a newer numpy versino then Matthew is using, since the old versions don't have those filters in place.

Possibly that comment meant that, but I don't understand it myself without reading the context :)

**Comment by seberg** [comment] 2017-06-29 19:06
So I guess we can just try to avoid the module setup stuff, and hope that it will be enough, at least for now.

**Comment by seberg** [comment] 2017-06-29 20:28
That comment you linked was about a different warning I first thought about that I got on numpy master. It was caused by nose, because you fixed the plugin loading or something, so the fix and the cause went in both in master, so its not an issue....

But in general, we have the problem that if numpy adds some warning filter, scipy will only pick it up if you use the latest numpy version (say that cython warning was not avoidable). I suppose if it gets too bad, we could also limit ourselves to use "develope" mode only as default on new enough numpy. But would prefer to avoid that.

**Comment by rgommers** [comment] 2017-06-30 11:04
> But in general, we have the problem that if numpy adds some warning filter, scipy will only pick it up if you use the latest numpy version

True, that's a good point. So perhaps a good idea to move all the filters over into a ``test()`` function in ``scipy/__init__.py`` if it makes this issue easier to fix.

> I suppose if it gets too bad, we could also limit ourselves to use "develope" mode only as default on new enough numpy. But would prefer to avoid that.

agreed

> So I guess we can just try to avoid the module setup stuff, and hope that it will be enough, at least for now.

sounds fine to me

**Comment by seberg** [comment] 2017-07-01 19:43
Pushed a hopeful fix, removing the module wide setups for now, I had some initial trouble with the test class setup methods, not sure why (but the sparse tests do some pretty complex stuff, might have been the reason), so its now on each test....

**Comment by rgommers** [comment] 2017-07-15 00:55
scipy-wheels builds have been green for the last 4 days, closing

**Closed by rgommers** 2017-07-15 00:55 UTC
Labels: defect
