### ISSUE TITLE
DOC: Add 'import numpy as np' to the 'Examples' section of docstrings.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#16759] opened 2022-08-02 16:17 UTC
It was recently decided that we would add the explicit import of numpy in the 'Examples' section of our docstrings. (See the discussion in https://github.com/scipy/scipy/issues/13049.)  Some progress has been made towards doing this consistently throughout SciPy, but there are still many functions and methods that need to be updated.

I created a script called `find_missing_import_np.py` that finds functions and methods that are missing the import.  Previously stored in a gist, the script is now in my github repo [`analyze-scipy-code`](https://github.com/WarrenWeckesser/analyze-scipy-code).

Here is the output when I run it with the SciPy main development branch (6-November-2022):
```
scipy version 1.10.0.dev0+2152.55452d1


Found 0 objects missing 'import numpy as np'
```
:tada:

**Comment by tupui** [comment] 2022-08-02 16:43
Thanks @WarrenWeckesser. As said in the previous issue and during the last community meetings. I propose to leave this open for onboarding new contributors. This way we have very easy and self contained changes people can make so we can focus on explaining the workflow, build system, commit, GH itself, etc. Still your listing is helpful and we could update this as we go so people can more easily make PRs.

**Comment by WarrenWeckesser** [comment] 2022-08-02 17:02
I added a link to the other issue in the above description.

In that discussion, you [commented](https://github.com/scipy/scipy/issues/13049#issuecomment-1170061966)

> As said earlier, @mdhaber and I proposed to do the work. 

My understanding of that comment is that you will continue to update the examples.  I have intentionally added this task to the 1.10 milestone, because you and others appear to have agreed with [my comment about doing it all at once](https://github.com/scipy/scipy/issues/13049#issuecomment-839886897).

**Comment by WarrenWeckesser** [comment] 2022-08-02 17:10
Note that I don't mean literally "all at once" as in one massive pull request.  I mean making steady progress so that the task is complete for 1.10.

**Comment by tupui** [comment] 2022-08-02 17:14
Yes that was the initial thought, but as we've seen during the sprint it was quite valuable to have something like this and people liked the format to get on board. So IMO we should not set ourselves to finish this specifically for the next release. In the end it's a nice set of issues as it does not impact anything. It's something we want to have, but there is not really any time component.

**Comment by WarrenWeckesser** [comment] 2022-08-02 17:27
> So IMO we should not set ourselves to finish this specifically for the next release.

I think this is not the best decision, and it does not reflect the impression given in the other discussion.  We *should* aim to finish this for the next release. And--apologies in advance for taking your comment so literally--of course it has impact. If it did not impact anything, we wouldn't bother doing it at all.

There are many issues that can be used as "good first issue" or for sprints.  While I agree this issue is also good for such uses, we really don't need to "save" this work for it.

**Comment by WarrenWeckesser** [comment] 2022-08-02 18:37
Anyway, it probably makes sense to have just one github issue for this.  I could either:
* Close gh-13049, and use this issue as the tracker for updating the docstrings (and edit the issue description above to include any specific guidelines, such as https://github.com/scipy/scipy/issues/13049#issuecomment-1199457608), or
* Close this issue, and edit the description of gh-13049 to include a link to the script and its output, so anyone who wants to work on it can see what still needs to be done at the very top of the issue.

Either way, the output can be updated as needed to keep track of the progress of the changes, just like gh-7168 is updated somewhat regularly.

Any preferences?  Or should I just leave them both open?

**Comment by tupui** [comment] 2022-08-02 18:48
As you wish as I personally don't like meta issues. I'd rather use projects in general.

**Comment by ak04p** [comment] 2022-08-11 17:04
Hi, I would like to contribute to this.

**Comment by WarrenWeckesser** [comment] 2022-08-12 06:56
Thanks, @ak04p.  In case you are planning to continue working on this, note that in https://github.com/scipy/scipy/pull/16831 I have updated the docstrings in the file `scipy/special/_add_newdocs.py`, which will take care of 62 functions in `scipy.special`.

**Comment by BassCoder2808** [comment] 2022-09-24 09:57
Hi, @WarrenWeckesser can I contribute to this issue as this issue has been open for a long time

**Comment by WarrenWeckesser** [comment] 2022-09-24 15:06
@BassCoder2808, yes, please do!

**Comment by dna-witch** [comment] 2022-09-28 18:28
Hi @WarrenWeckesser, is this issue still available? How can I get assigned to this task?

**Comment by WarrenWeckesser** [comment] 2022-09-28 18:32
@dna-witch, we don't assign tasks, so you can go ahead and work on it.  The pull request https://github.com/scipy/scipy/pull/17110 will take care of the examples in the `sparse` subpackage.  Other than that, the list above should be up-to-date.

**Comment by WarrenWeckesser** [comment] 2022-09-30 12:25
@dna-witch, in case you have started working on this, take note of https://github.com/scipy/scipy/pull/17115.  That pull request fixes most of the docstrings.

**Comment by tupui** [comment] 2022-10-10 17:15
As discussed during the last community meeting, we don't want anymore PRs for this and moving forward we will only consider a single PR fixing everything at once.

@mdhaber has such script already.

**Comment by WarrenWeckesser** [comment] 2022-10-10 17:30
Just to be clear: https://github.com/scipy/scipy/pull/17115 is almost done, and after that is merged, there won't be a lot of examples left to fix.

**Comment by WarrenWeckesser** [comment] 2022-10-11 22:35
@BassCoder2808's pull request updated 210 docstrings (:rocket:!), leaving just 14 to go--at least according to the script used above.

**Comment by WarrenWeckesser** [comment] 2022-10-17 14:49
FYI: `scipy.special.sinc` is an alias for `numpy.sinc`, so we can ignore that docstring.  It would be nice to deprecated and remove `sinc` from the `scipy.special` namepsace, but that's a separate issue.

**Comment by WarrenWeckesser** [comment] 2022-11-05 16:38
Another small update: the script was not checking `scipy.datasets`, so it missed `electrocardiogram`.  The script and the output shown above have been updated.

**Comment by BassCoder2808** [comment] 2022-11-05 17:00
Hi @WarrenWeckesser, can I update the remaining docstrings as per the script if the issue is still open

**Comment by WarrenWeckesser** [comment] 2022-11-05 17:28
Thanks @BassCoder2808, but in fact I am about to submit a pull request to finish these off.  The main purpose of the pull request will be to fix a bunch of other issues in the docstrings in `scipy.signal`, but as long as I'm fixing docs, I might as well fix the few remaining cases of missing `import numpy as np`.

**Comment by WarrenWeckesser** [comment] 2022-11-05 17:55
Another update: the functions in `scipy.fft` and `scipy.fftpack` that are listed above are actually NumPy functions, so they can be skipped.

**Closed** 2022-11-09 04:15 UTC
Labels: task, Documentation
