### ISSUE TITLE
Different clustering results using same cut height from hierarchy.fcluster and hierarchy.cut_tree

### ISSUE THREAD

**Issue by jolespin** [scipy/scipy#7815] opened 2017-08-31 18:56 UTC
I recently found out about [cut_tree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.cut_tree.html) and was previously using [fcluster](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.cluster.hierarchy.fcluster.html).  I've built code around `fcluster` and was going to update it using `cut_tree` instead but the results are different in the clustering using a simple horizontal cut on the dendrogram. 

I am using the following version:
![image](https://user-images.githubusercontent.com/9061708/29940139-224be844-8e43-11e7-8d5d-870acef287fc.png)

```python
# Import 
from scipy.spatial import distance
from scipy.cluster.hierarchy import dendrogram, fcluster, leaves_list, to_tree, cut_tree, linkage
from sklearn.datasets import load_iris

# Functions
def dism2linkage(DF_dism, method="ward"):
    #Linkage Matrix
    Ar_dist = distance.squareform(DF_dism.as_matrix())
    return linkage(Ar_dist,method=method)

# Load Iris Data
X_iris = pd.DataFrame(load_iris().data,
                           index = ["iris_%d" % i for i in range(load_iris().data.shape[0])],
                           columns = [x.split(" (cm)")[0].replace(" ","_") for x in load_iris().feature_names])


# Dendrogram
Z = dism2linkage(df_dism)
cut_height = 5
with plt.style.context("seaborn-white"):
    fig, ax = plt.subplots(figsize=(17.5,4))
    dendro = dendrogram(Z, labels=df_dism.index, ax=ax, color_threshold=cut_height)
    ax.axhline(cut_height, color="black", linestyle=":")

# Cluster Method 1
Se_c1 = pd.Series(fcluster(Z, t=cut_height, criterion="distance"), index=dendro["ivl"])

# Cluster Method 2:
# Offset by 1 so adding 1 
Se_c2 = pd.Series(cut_tree(Z, height=cut_height).ravel(), index=df_dism.index)[dendro["ivl"]] + 1

print("Differences: ", (Se_c1 != Se_c2).sum(), sep="\t")
pd.DataFrame([ Se_c1, Se_c2])
```
![image](https://user-images.githubusercontent.com/9061708/29940096-fc1305fe-8e42-11e7-8045-387926ba95d1.png)

**Comment by rgommers** [comment] 2017-09-02 04:10
They're different algorithms, so I'd expect the trees to not be identical. Both functions should give valid trees though, and from your results it looks like they do.

Closing because not a bug.

**Closed by rgommers** 2017-09-02 04:10 UTC
Labels: query, scipy.cluster

**Comment by jolespin** [comment] 2017-09-03 16:44
If you're doing a straight horizontal cut of the dendrogram, which one would you use?  Thanks

**Comment by rgommers** [comment] 2017-09-09 02:21
They take the same linkage matrix, so it's very easy to try both and see which clustering you like better. That's what I'd do - hard to say more, may be problem dependent.
