### ISSUE TITLE
memory issue with grey_dilation 

### ISSUE THREAD

**Issue by terot** [scipy/scipy#9803] opened 2019-02-11 07:38 UTC
My issue is about randomly occuring segmentation fault with scipy.ndimage.morphology.grey_dilation. Even if the issue is random, it can be consistently run by setting the [PYTHONMALLOC](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONMALLOC) environment variable. 

### Reproducing code example:

The issue can be reproduced with a minimal example by running the example with `PYTHONMALLOC=debug`

```
import numpy as np
from scipy.ndimage.morphology import grey_dilation

input_3d = np.random.normal(size=(50,50,50))
struct_elem = np.ones((9,9,9))
struct_elem[8,1,1] = 0

grey_dilation(input_3d, footprint=struct_elem)
```

### Error message:

```
Debug memory block at address p=0x3ec4380: API 'r'
    24 bytes originally requested
    The 7 pad bytes at p-7 are FORBIDDENBYTE, as expected.
    The 8 pad bytes at tail=0x3ec4398 are FORBIDDENBYTE, as expected.
    The block was made by call #385557 to debug malloc/realloc.
    Data at p: 00 00 00 00 00 00 00 00 ... 00 00 00 00 00 00 00 00

Fatal Python error: bad ID: Allocated using API 'r', verified using API 'm'

Current thread 0x00007f1e675db740 (most recent call first):
  File "/home/tero/.local/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 271 in _binary_erosion
  File "/home/tero/.local/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 376 in binary_erosion
  File "/home/tero/.local/lib/python3.6/site-packages/scipy/ndimage/morphology.py", line 628 in binary_opening
  File "test03.py", line 8 in <module>
Aborted (core dumped)
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info
```
--> 1.2.0 1.16.1 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)

**Comment by ilayn** [comment] 2019-02-11 07:53
Hi @terot, thanks for taking the time to report this. I can't replicate this on my system after running ~50k times each issue, this and  #9804 . How often do you encounter this and on which architecture?

**Comment by terot** [comment] 2019-02-11 08:09
Hi, this error shows consistently by running the test script with `PYTHONMALLOC=debug`. This is the exact command I use:
```
PYTHONMALLOC=debug python3 test01.py
```

The randomly occuring segfault seems to be effected by this. Removing grey dilation implementation gets rid of the segfault, as far as our tests show.

**Comment by terot** [comment] 2019-02-12 12:27
architecture: x86_64

**Comment by sethtroisi** [comment] 2020-05-21 07:43
I ran `$ i=0; while PYTHONMALLOC=debug python test4.py; do echo "$((i++))";` and I didn't see any errors in the first 5000 loops.

**Comment by rgommers** [comment] 2020-05-22 12:27
I can't reproduce it either. That's 3 failures to reproduce, let's close this. @terot if you have a more specific reproducer please comment and we'll reopen.

**Closed by rgommers** 2020-05-22 12:27 UTC
Labels: defect, scipy.ndimage
