### ISSUE TITLE
Complex matrix square root of positive semi-definite matrix

### ISSUE THREAD

**Issue by jennirinker** [scipy/scipy#12247] opened 2020-05-28 11:33 UTC
I have a positive semi-definite, real matrix, but the output from scipy matrix square root is complex (although the imaginary parts are zero to machine precision). I think it's a bit odd, since the `keep_it_real` logic should force it to real, but something's obviously gone a bit awry.

EDIT: Issue is due to `array_equal` instead of `allclose`, see my second comment.

#### Reproducing code example:

File with 81x81 matrix:
[test.txt](https://github.com/scipy/scipy/files/4695177/test.txt)

```
import numpy as np
from scipy.linalg import sqrtm

mat = np.loadtxt('test.txt')
print('Is it real: ', np.isrealobj(mat))
print('Min eval: ', np.min(np.real(np.linalg.eig(mat)[0])))
print('Is output real: ', np.isrealobj(sqrtm(mat)))
```
This prints
```
Is it real:  True
Min eval:  0.0019360715168965491
Is output real:  False
```

#### Error message:
(none)

#### Scipy/Numpy/Python version information:

```
1.3.0 1.16.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by tirthasheshpatel** [comment] 2020-05-28 11:42
I think that just some numerical instability. Isn't that expected? I am not sure if this is the best solution but you may do ``sqrtm(mat).real`` as a workaround if you are only concerned with real values. 

```python
>>> np.allclose(sqrtm(mat).imag, np.zeros((81, 81)))
True
```

**Comment by jennirinker** [comment] 2020-05-28 11:57
I would say it's not expected, because there is already logic in the function to handle this sort of situation. The issue is that the logic isn't working.

The main problem arises from the use of `np.array_equal` [here](https://github.com/scipy/scipy/blob/v1.4.1/scipy/linalg/_matfuncs_sqrtm.py#L171) instead of `np.allclose`. Consider the two blocks of logic below:

```
import numpy as np
from scipy.linalg import sqrtm
from scipy._lib._util import _asarray_validated
from scipy.linalg.decomp_schur import schur, rsf2csf

A = np.loadtxt('test.txt')

keep_it_real = np.isrealobj(A)
if keep_it_real:
    T, Z = schur(A)
    if not np.array_equal(T, np.triu(T)):
        T, Z = rsf2csf(T, Z)  # this is triggered incorrectly, returns complex
print(np.isrealobj(T))  # returns False

keep_it_real = np.isrealobj(A)
if keep_it_real:
    T, Z = schur(A)
    if not np.allclose(T, np.triu(T)):  # this time, not triggered
        T, Z = rsf2csf(T, Z)
print(np.isrealobj(T))  # returns True
```

**Comment by ilayn** [comment] 2020-05-28 12:00
It is because of that "Is T lower triangular step" things are getting strange because of `np.array_equal`. after real to complex form conversion. This whole `sqrtm` function can use some facelift actually. Anyone care to work on it ?

**Comment by ilayn** [comment] 2020-05-28 12:01
Oops didn't see your second comment. Sorry about that

**Comment by jennirinker** [comment] 2020-05-28 12:03
No worries. If you're cool with just replacing array_equal with allclose, I can make a simple PR. Or if you'd like to wait for the "facelift", that's also fine. :)

**Comment by ilayn** [comment] 2020-05-28 12:06
Let's start with your obvious fix then. It would be great if you can send a simple PR. But feel free to extend it to a facelift.

**Comment by tylerjereddy** [comment] 2023-08-11 21:09
Fixed by gh-17918, though I'll open a separate issue to add a regression test (which I've already drafted..).

**Closed** 2023-08-11 21:14 UTC
Labels: scipy.linalg, maintenance
