### ISSUE TITLE
linalg.lstsq fails under certain circumstances

### ISSUE THREAD

**Issue by kbattocchi** [scipy/scipy#12893] opened 2020-09-28 19:44 UTC
I have found that `lstsq` is sometimes unexpectedly throwing an exception; this is causing major problems because it's used in things like sklearn's `LinearRegression` class.  I've included below a particular very simplified repro, but there appear to be an unpredictable but somewhat widespread set of circumstances that can trigger this bug.

#### Reproducing code example:
```
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import lstsq

n = 9 # doesn't repro for n<=8

# Generate covariates and outcomes
X = np.arange(n).reshape(-1,1)
Y = X

# plot anything with dashed lines (doesn't repro with default line style!)
plt.plot([1,2], [3,4], '--')

lstsq(X,Y)
```

#### Error message
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
 in 
     12 plt.plot([1,2], [3,4], '--')
     13 
---> 14 lstsq(X,Y)

c:\Users\kebatt\source\repos\ProjectAliceCore\automl_venv\lib\site-packages\scipy\linalg\basic.py in lstsq(a, b, cond, overwrite_a, overwrite_b, check_finite, lapack_driver)
   1222         if info < 0:
   1223             raise ValueError('illegal value in %d-th argument of internal %s'
-> 1224                              % (-info, lapack_driver))
   1225         resids = np.asarray([], dtype=x.dtype)
   1226         if m > n:

ValueError: illegal value in 4-th argument of internal None
```
#### Scipy/Numpy/Python version information:
```
1.5.2 1.19.2 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

I am running Windows 10 version 2004, so I assume this is at least somewhat related to https://github.com/numpy/numpy/issues/16744, https://github.com/scipy/scipy/issues/12747, etc., but the manifestation is different.

**Comment by ilayn** [comment] 2020-10-21 10:31
Duplicate of #12747

**Closed by ilayn** 2020-10-21 10:31 UTC
