### ISSUE TITLE
BUG `cdist` with `mahalanobis` fails when used on mem-mapped array

### ISSUE THREAD

**Issue by jjerphan** [scipy/scipy#13861] opened 2021-04-14 07:08 UTC
A segfault is thrown when using `cdist` with `mahalanobis` as a metric on numpy array which have been mem-mapped.

This situation is encountered in scikit-learn (see https://github.com/scikit-learn/scikit-learn/pull/19883)
This happens with `np.float` as `dtype` but not with `int` as `dtype`.

#### Reproducing code example:

```python
import numpy as np
from scipy.spatial.distance import cdist
from sklearn.utils._testing import create_memmap_backed_data

X = np.random.randint(0, 100, size=(20, 4))
VI = np.cov(X)
[Xmm] = create_memmap_backed_data([X])
np.testing.assert_equal(Xmm, X)

# Works fine (eventhough nan in the output)
cdist(Xmm, Xmm, metric='mahalanobis', VI=VI)

#

X = np.random.rand(20, 4)
VI = np.cov(X)
[Xmm] = create_memmap_backed_data([X])
np.testing.assert_equal(Xmm, X)

# A segfault is thrown
cdist(Xmm, Xmm, metric='mahalanobis', VI=VI)
```

#### Error message:

```
[1]    429569 segmentation fault (core dumped)  ipython
```

#### Scipy/Numpy/Python version information:

```python
from sklearn import show_versions
show_versions()
```
```
System:
    python: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
executable: /home/jsquared/.local/share/miniconda/bin/python
   machine: Linux-5.11.11-200.fc33.x86_64-x86_64-with-glibc2.10

Python dependencies:
          pip: 21.0.1
   setuptools: 54.2.0
      sklearn: 1.0.dev0
        numpy: 1.20.2
        scipy: 1.6.2
       Cython: None
       pandas: 1.2.3
   matplotlib: 3.4.1
       joblib: 1.0.1
threadpoolctl: 2.1.0

Built with OpenMP: True
```

**Comment by tupui** [comment] 2021-04-14 07:47
Actually I cannot reproduce from 1.6.1 up to a dev branch. I am on macOS. Could you check on master?

```
from sklearn import show_versions
show_versions()
System:
    python: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]
executable: .../miniconda3/envs/scipydev/bin/python
   machine: macOS-10.16-x86_64-i386-64bit
Python dependencies:
          pip: 20.2.3
   setuptools: 49.6.0.post20200925
      sklearn: 0.24.1
        numpy: 1.20.2  # tested also with 1.19.5
        scipy: 1.7.0.dev0+397d66f  # tested also with 1.6.x
       Cython: 0.29.22
       pandas: 1.2.3
   matplotlib: 3.4.1
       joblib: 1.0.1
threadpoolctl: 2.1.0
Built with OpenMP: True
```

**Comment by jjerphan** [comment] 2021-04-14 09:10
I've tried to install scipy@master in editable mode on a fresh virtual env':
```
Package          Version            Location
---------------- ------------------ ------------------------
backcall         0.2.0
cycler           0.10.0
Cython           0.29.22
decorator        5.0.7
ipython          7.22.0
ipython-genutils 0.2.0
jedi             0.18.0
joblib           1.0.1
kiwisolver       1.3.1
line-profiler    3.1.0
matplotlib       3.4.1
numpy            1.20.2
parso            0.8.2
pexpect          4.8.0
pickleshare      0.7.5
Pillow           8.2.0
pip              21.0.1
prompt-toolkit   3.0.18
ptyprocess       0.7.0
Pygments         2.8.1
pyparsing        2.4.7
python-dateutil  2.8.1
scikit-learn     0.24.1
scipy            1.7.0.dev0+2d8911c /home/jjerphan/dev/scipy
setuptools       47.1.0
six              1.15.0
threadpoolctl    2.1.0
traitlets        5.0.5
wcwidth          0.2.5
```

but I yet get a (I guess unrelated) `ImportError`:

<details>
<summary> Full Trace </summary>
<pre>
In [1]: from sklearn import show_versions
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-66360def7229> in <module>
----> 1 from sklearn import show_versions

~/.virtualenvs/scipy/lib/python3.8/site-packages/sklearn/__init__.py in <module>
     80     from . import _distributor_init  # noqa: F401
     81     from . import __check_build  # noqa: F401
---> 82     from .base import clone
     83     from .utils._show_versions import show_versions
     84 

~/.virtualenvs/scipy/lib/python3.8/site-packages/sklearn/base.py in <module>
     15 from . import __version__
     16 from ._config import get_config
---> 17 from .utils import _IS_32BIT
     18 from .utils._tags import (
     19     _DEFAULT_TAGS,

~/.virtualenvs/scipy/lib/python3.8/site-packages/sklearn/utils/__init__.py in <module>
     21 
     22 from .murmurhash import murmurhash3_32
---> 23 from .class_weight import compute_class_weight, compute_sample_weight
     24 from . import _joblib
     25 from ..exceptions import DataConversionWarning

~/.virtualenvs/scipy/lib/python3.8/site-packages/sklearn/utils/class_weight.py in <module>
      5 import numpy as np
      6 
----> 7 from .validation import _deprecate_positional_args
      8 
      9 

~/.virtualenvs/scipy/lib/python3.8/site-packages/sklearn/utils/validation.py in <module>
     24 from contextlib import suppress
     25 
---> 26 from .fixes import _object_dtype_isnan, parse_version
     27 from .. import get_config as _get_config
     28 from ..exceptions import PositiveSpectrumWarning

~/.virtualenvs/scipy/lib/python3.8/site-packages/sklearn/utils/fixes.py in <module>
     18 import scipy.sparse as sp
     19 import scipy
---> 20 import scipy.stats
     21 from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
     22 from numpy.ma import MaskedArray as _MaskedArray  # TODO: remove in 1.0

~/dev/scipy/scipy/stats/__init__.py in <module>
    434 """
    435 
--> 436 from .stats import *
    437 from .distributions import *
    438 from .morestats import *

~/dev/scipy/scipy/stats/stats.py in <module>
     36 from numpy import array, asarray, ma
     37 
---> 38 from scipy.spatial.distance import cdist
     39 from scipy.ndimage import measurements
     40 from scipy._lib._util import (_lazywhere, check_random_state, MapWrapper,

~/dev/scipy/scipy/spatial/__init__.py in <module>
     99 from ._spherical_voronoi import SphericalVoronoi
    100 from ._plotutils import *
--> 101 from ._procrustes import procrustes
    102 from ._geometric_slerp import geometric_slerp
    103 

~/dev/scipy/scipy/spatial/_procrustes.py in <module>
      7 
      8 import numpy as np
----> 9 from scipy.linalg import orthogonal_procrustes
     10 
     11 

~/dev/scipy/scipy/linalg/__init__.py in <module>
    193 """  # noqa: E501
    194 
--> 195 from .misc import *
    196 from .basic import *
    197 from .decomp import *

~/dev/scipy/scipy/linalg/misc.py in <module>
      1 import numpy as np
      2 from numpy.linalg import LinAlgError
----> 3 from .blas import get_blas_funcs
      4 from .lapack import get_lapack_funcs
      5 

~/dev/scipy/scipy/linalg/blas.py in <module>
    211 import functools
    212 
--> 213 from scipy.linalg import _fblas
    214 try:
    215     from scipy.linalg import _cblas

ImportError: /home/jsquared/dev/scipy/scipy/linalg/_fblas.cpython-38-x86_64-linux-gnu.so: undefined symbol: Npy__PyLong_AsInt

</pre>
</details>

**Comment by tupui** [comment] 2021-04-14 09:15
How did you install? Seeing this
`ImportError: /home/jsquared/dev/scipy/scipy/linalg/_fblas.cpython-38-x86_64-linux-gnu.so: undefined symbol: Npy__PyLong_AsInt` I would say it's a compilation issue. Here is the latest devdoc for installing on ubuntu: https://scipy.github.io/devdocs/dev/contributor/quickstart_ubuntu.html#quickstart-ubuntu

**Comment by jjerphan** [comment] 2021-04-14 12:34
Thanks for the link!

I was using scipy in another way, with bare python virtual environment (without conda).
I still get the `ImportError` via a development environment as explained by the link given above.

As you said, it's related to a compilation issue:

<details>
<summary> <code>python setup.py build_ext --inplace</code> trace (extract)</summary>
<pre>
C compiler: /home/jjerphan/.local/share/miniconda/envs/scipydev/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jjerphan/.local/share/miniconda/envs/scipydev/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jjerphan/.local/share/miniconda/envs/scipydev/include -fPIC

creating /tmp/tmpqegu3fa5/tmp
creating /tmp/tmpqegu3fa5/tmp/tmpqegu3fa5
compile options: '-MMD -MF /tmp/tmpqegu3fa5/file.c.d -c'
x86_64-conda-linux-gnu-cc: /tmp/tmpqegu3fa5/file.c
  libraries mkl_rt not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

openblas_lapack_info:
  libraries openblas not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

openblas_clapack_info:
  libraries openblas,lapack not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

flame_info:
  libraries flame not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /home/jjerphan/.local/share/miniconda/envs/scipydev/lib
  libraries tatlas,tatlas not found in /home/jjerphan/.local/share/miniconda/envs/scipydev/lib
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries lapack_atlas not found in /home/jjerphan/.local/share/miniconda/envs/scipydev/lib
  libraries satlas,satlas not found in /home/jjerphan/.local/share/miniconda/envs/scipydev/lib
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in /home/jjerphan/.local/share/miniconda/envs/scipydev/lib
  libraries ptf77blas,ptcblas,atlas not found in /home/jjerphan/.local/share/miniconda/envs/scipydev/lib
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries lapack_atlas not found in /home/jjerphan/.local/share/miniconda/envs/scipydev/lib
  libraries f77blas,cblas,atlas not found in /home/jjerphan/.local/share/miniconda/envs/scipydev/lib
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

lapack_info:
  FOUND:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
    language = f77

blas_opt_info:
blas_mkl_info:
  libraries mkl_rt not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

blis_info:
  libraries blis not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

openblas_info:
  libraries openblas not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

atlas_3_10_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries tatlas not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

atlas_3_10_blas_info:
  libraries satlas not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

atlas_blas_threads_info:
Setting PTATLAS=ATLAS
  libraries ptf77blas,ptcblas,atlas not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

atlas_blas_info:
  libraries f77blas,cblas,atlas not found in ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
  NOT AVAILABLE

/home/jjerphan/.local/share/miniconda/envs/scipydev/lib/python3.8/site-packages/numpy/distutils/system_info.py:1989: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
blas_info:
C compiler: /home/jjerphan/.local/share/miniconda/envs/scipydev/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/jjerphan/.local/share/miniconda/envs/scipydev/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/jjerphan/.local/share/miniconda/envs/scipydev/include -fPIC

creating /tmp/tmpeb93wugo/tmp
creating /tmp/tmpeb93wugo/tmp/tmpeb93wugo
compile options: '-I/home/jjerphan/.local/share/miniconda/envs/scipydev/include -c'
x86_64-conda-linux-gnu-cc: /tmp/tmpeb93wugo/source.c
/tmp/tmpeb93wugo/source.c:1:10: fatal error: cblas.h: No such file or directory
    1 | #include <cblas.h>
      |          ^~~~~~~~~
compilation terminated.
  FOUND:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
    include_dirs = ['/home/jjerphan/.local/share/miniconda/envs/scipydev/include']

  FOUND:
    define_macros = [('NO_ATLAS_INFO', 1)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
    include_dirs = ['/home/jjerphan/.local/share/miniconda/envs/scipydev/include']

  FOUND:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/jjerphan/.local/share/miniconda/envs/scipydev/lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1)]
    include_dirs = ['/home/jjerphan/.local/share/miniconda/envs/scipydev/include']
<pre>
</details>

CBLAS and OpenBLAS for development are installed on my machine; probably conda is hiding include paths?

**Comment by tupui** [comment] 2021-04-14 13:07
I am not sure about your setup. Normally, if you follow exactly the instructions it should build as we use this in our CI. Your traceback seems to indicate that you still are missing BLAS/LAPACK.

**Comment by peterbell10** [comment] 2021-04-14 14:48
@jjerphan your import failure may be similar to #12489. Try cleaning the scipy directory with `git clean -xdf` and install with `pip install -e .` instead of calling `setup.py` yourself.

**Comment by jjerphan** [comment] 2021-04-14 15:41
Thanks for your suggestions @tupui and @peterbell10.

The modification made by `conda` installation to the `PATH` env' variable somewhat hides some `include` directories.
A workaround to solve the compilation issue is to modify `PATH` temporarily to remove the miniconda installation path from it.

I previously have had this issue before, but haven't managed to find a proper solution.

**Comment by tupui** [comment] 2021-04-14 17:25
Thanks for the info. So, do you still have your original issue?

**Comment by jjerphan** [comment] 2021-04-14 17:42
I do not have the issue, from 1.6.0 to `master` when compiling it myself. 🤔

**Comment by tupui** [comment] 2021-04-14 18:02
Then I propose to close this as it seems that the bug is not coming from SciPy itself. Feel free to add more info here though.

**Comment by tupui** [comment] 2021-04-14 18:13
@peterbell10 looks like we could close both issues no? Our doc is accurate here. We are still talking about some re-write and the install workflow is definitely on the table.

**Comment by peterbell10** [comment] 2021-04-14 18:17
Sure, if nobody can reproduce it any more then closing makes sense. If the segfault comes back, then feel free to reopen the issue and if possible run it under gdb to get a traceback.

**Closed by peterbell10** 2021-04-14 18:17 UTC
Labels: defect, scipy.spatial

**Comment by ogrisel** [comment] 2021-11-23 09:02
Maybe it's not related to being a memmap array but to being a non-memory aligned array which is known to cause problems on some platforms for some compiler versions.
