### ISSUE TITLE
`scipy.linalg.blas.dgemm` appears to have broken `overwrite_c` parameter

### ISSUE THREAD

**Issue by jbloom** [scipy/scipy#6779] opened 2016-11-13 04:46 UTC
The `dgemm` function does *not* write the result into `c` even when using `overwrite_c`. 

I think this is a long-standing bug. I found an earlier mention of it here:
https://mail.scipy.org/pipermail/scipy-user/2008-August/017954.html

**Comment by jbloom** [comment] 2016-11-13 04:49
The bug is in version `0.18.0`.

**Comment by person142** [comment] 2016-11-13 07:44
Duplicate of https://github.com/scipy/scipy/issues/5739? (Haven't looked carefully.)

**Comment by pv** [comment] 2016-11-13 13:46
All the `overwrite_*` options only mean the array may be overwritten, not that it will be overwritten.

**Closed by pv** 2016-11-13 13:46 UTC
