### ISSUE TITLE
ENH: reduce scipy.fft library size

### ISSUE THREAD

**Issue by mreineck** [scipy/scipy#10436] opened 2019-07-10 09:53 UTC
When building current master using `python setup.py install`, pypocketfft appears to be built with debugging info enabled, resulting in a huge (approx. 13MB) shared library. While this is of course fine for developers, debugging info should be switched off (using `-g0` or `-s`) for release builds, since this will shrink the library size to around 800KB, which is much more manageable.
If this is already done for binary releases (sorry, don't know how to check this), please just close this issue!

**Comment by larsoner** [comment] 2019-07-10 11:33
I don't think the debug symbols are meant to be in there. @peterbell10?

**Comment by peterbell10** [comment] 2019-07-10 11:35
Looking at the build logs, it's compiled with `-g` but I'm definitely not adding it.  It looks like setuptools adds it by default.

**Comment by mreineck** [comment] 2019-07-10 11:40
Yes, I think that's the default. If your added flags appear on the command line after the the ones from setuptools, you should be able to override with `-g0`, which is a bit of a hack, but I don't have a better idea at the moment.

**Comment by mreineck** [comment] 2019-07-10 11:42
Again, it's quite possible that all debug symbols are stripped from the library when building the wheels, so maybe it's a non-issue.

**Comment by larsoner** [comment] 2019-07-10 11:44
@peterbell10 can you check to see if other submodules are built by default with debugging symbols? scipy.fft should probably stay consistent with the rest of SciPy.

**Comment by peterbell10** [comment] 2019-07-10 11:50
It looks like every Extension build with distutils will have debug symbols by default. I have also confirmed that `fftpack` is built with debug symbols.

**Comment by mreineck** [comment] 2019-07-10 11:53
Template-heavy C++ modules unfortunately tend to have debug info which is many times larger than the actual object code, in strong contrast to typical C modules. If pypocketfft is the first module of that sort in scipy, it might be necessary to reconsider debug info policy.
(If scipy's installation footprint goes up by 12MB because a new FFT library was introduced, which actually fits in to 800KB, users may be unhappy...)

**Comment by peterbell10** [comment] 2019-07-10 11:59
Looks like `sparsetools` which is also templated C++ has a 39 MB `.so`.

**Comment by mreineck** [comment] 2019-07-10 12:02
Wow. It has roughly 60MB in my local installation, and can be reduced to 2.7MB by stripping.

**Comment by mreineck** [comment] 2019-07-10 12:09
When installiing scipy 1.3 via `pip` I get a stripped-down version of the `sparsetools` library ... so I guess everything is fine and the large .so files only occur when installing from a local git clone.

**Comment by peterbell10** [comment] 2019-07-10 12:09
Can confirm, I did the same and had a look in `site-packages`. The sparsetools `.so` is just 3.4MB.

**Comment by mreineck** [comment] 2019-07-10 12:11
OK, then I think we can close this. Sorry for the noise!

**Comment by larsoner** [comment] 2019-07-10 12:15
Good to know!

**Comment by rgommers** [comment] 2019-07-10 12:49
It may be worth discussing this a bit more. The "policy" (it's not a very deliberate one) made more sense a long time ago, but us receiving useful tracebacks that we wouldn't have otherwise is very rare. And not everyone build from our wheel build setup (e.g. Linux distributions, conda). Why let everyone reinvent this wheel? Removing `-g` by default from C++ code or all compiled code may be a good idea.

**Comment by rgommers** [comment] 2019-07-10 12:50
@pv any thoughts?

**Comment by pv** [comment] 2019-07-14 13:20
Linux distributions have their own policies vs. stripping and probably don't need us to meddle with it, and probably similar applies to Conda. The remaining users probably use prebuilt wheels, which are stripped iirc.

So I'm not sure if this is very important for Scipy users per se. Making the debugging switches more accessible might make sense for numpy distutils, as it's not currently that straightforward to do.

**Comment by rgommers** [comment] 2021-05-14 22:05
> Linux distributions have their own policies vs. stripping and probably don't need us to meddle with it, and probably similar applies to Conda. The remaining users probably use prebuilt wheels, which are stripped iirc.
>
> So I'm not sure if this is very important for Scipy users per se.

Agreed.

> Making the debugging switches more accessible might make sense for numpy distutils, as it's not currently that straightforward to do.

Doesn't make sense to spend effort on this anymore, better focus on migrating away. I'll close this.

**Closed by rgommers** 2021-05-14 22:05 UTC
Labels: needs-decision, scipy.fft
