### ISSUE TITLE
ENH: regression confidence interval

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [scipy/scipy#14769] opened 2021-09-25 18:40 UTC
### Is your feature request related to a problem? Please describe.

When fitting a regression model to data, it is often necessary to generate a confidence band for the regression.  Currently, doing this requires the use of packages other than `scipy`, e.g., `uncertainties`.  It would be great if one could get the entire job done using only `scipy`.

### Describe the solution you'd like.

Ideally, a single function call would give both the regression fit and the confidence band.

**Comment by rkern** [comment] 2021-09-26 02:07
Which regression functionality in `scipy` are you talking about? We have several. Some already provide this (e.g `scipy.odr` just because it happens to be implemented in the underlying FORTRAN library). In general, this is the kind of thing that we do leave to other packages. While "the" least-squares fit is reasonably well defined, a confidence band requires more assumptions/inputs from the user to specify the one you want. Other packages are in better positions to allow you to provide/define those extra pieces of information.

**Comment by tupui** [comment] 2021-09-26 15:49
I think you are looking at [`scipy.stats.bootstrap`](http://scipy.github.io/devdocs/reference/generated/scipy.stats.bootstrap.html). Otherwise for things like asymptotic rules we have to look at the specific methods.

**Comment by Phillip-M-Feldman** [comment] 2021-09-26 17:37
Hm.  One could generate a confidence band by bootstrapping the regression.
I hadn't thought of this.  Thanks!

**Comment by ev-br** [comment] 2021-09-26 17:48
FWIW, I would just generate a bunch of synthetic datasets, do regression for each of them and analyze the distribution of fit results. This probably has a name and is likely implemented somewhere, but as far as I'm concerned, it's easiest to just DIY.

**Comment by rkern** [comment] 2021-09-26 18:17
Using a plain-old bootstrap resampling of the rows of data is often not the preferred method for regression problems (it's great for estimators of univariate data). Consider [resampling the residuals](https://en.wikipedia.org/wiki/Bootstrapping_(statistics)#Resampling_residuals) instead.

And yes, @ev-br that's the core idea of the bootstrap, though generating completely synthetic data is less useful for understanding the uncertainties implied by the particular _dataset_ and is better used as a way to understand the limits of the model and debug your implementation (Andrew Gelman and Aki Vehtari and others call this ["fake data simulation"](https://statmodeling.stat.columbia.edu/2019/03/23/yes-i-really-really-really-like-fake-data-simulation-and-i-cant-stop-talking-about-it/))

**Comment by Phillip-M-Feldman** [comment] 2021-09-27 01:26
Resampling the residuals is intuitively nice.  I like this approach.
Thanks!

**Comment by rkern** [comment] 2021-09-27 03:36
I'm going to close this as you have a path forward.

**Closed by rkern** 2021-09-27 03:36 UTC
Labels: enhancement
