### ISSUE TITLE
BUG: 1.9.0rc1 fails to build on macOS when CXX="g++ -std=gnu++11" 

### ISSUE THREAD

**Issue by mkoeppe** [scipy/scipy#16536] opened 2022-07-03 17:36 UTC
### Describe your issue.

The new build system of scipy 1.9.0rc1 breaks on macOS when the time-tested setting of `CXX="g++ -std=gnu++11"` is in use.

### Reproducing Code Example

```python
~ ➤ /usr/bin/python3 -m pip install --user build                               
Collecting build
  Using cached build-0.8.0-py3-none-any.whl (17 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pep517>=0.9.1
  Using cached pep517-0.12.0-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: packaging>=19.0 in ./Library/Python/3.8/lib/python/site-packages (from build) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in ./Library/Python/3.8/lib/python/site-packages (from packaging>=19.0->build) (2.4.7)
Installing collected packages: tomli, pep517, build
  WARNING: The script pyproject-build is installed in '/Users/mkoeppe/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Successfully installed build-0.8.0 pep517-0.12.0 tomli-2.0.1
WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
~ ➤ cd s/sage/scipy                                                            
scipy ➤ git checkout v1.9.0rc1                                                            git:boostorg_math_729
warning: unable to rmdir 'doc/sphinxext': Directory not empty
M	scipy/_lib/boost
M	scipy/_lib/unuran
Note: switching to 'v1.9.0rc1'.
scipy ➤ CXX="g++ -std=gnu++11" /usr/bin/python3 -m build .                                                                                                       git:72a5f4697*
* Creating venv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29.21,<3.0, meson-python>=0.5.0,<0.7.0, numpy; python_version>='3.11', numpy; python_version>='3.8' and platform_python_implementation=='PyPy', numpy==1.18.5; python_version=='3.8' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64' and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy', numpy==1.19.2; python_version=='3.8' and platform_machine=='aarch64' and platform_python_implementation != 'PyPy', numpy==1.19.3; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy', numpy==1.20.0; python_version=='3.8' and platform_machine=='arm64' and platform_system=='Darwin', numpy==1.20.0; python_version=='3.9' and platform_machine=='arm64' and platform_system=='Darwin', numpy==1.21.6; python_version=='3.10' and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy', numpy==1.22.0; platform_machine=='loongarch64', pybind11>=2.4.3,<2.10.0, pythran>=0.9.12,<0.12.0, wheel<0.38.0)
* Getting dependencies for sdist...
* Building sdist...
+ meson setup --native-file=/Users/mkoeppe/s/sage/scipy/.mesonpy-native-file.ini -Ddebug=false -Dstrip=true -Doptimization=2 --prefix=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8 /Users/mkoeppe/s/sage/scipy /Users/mkoeppe/s/sage/scipy/.mesonpy-029irg41/build
The Meson build system
Version: 0.63.0
Source dir: /Users/mkoeppe/s/sage/scipy
Build dir: /Users/mkoeppe/s/sage/scipy/.mesonpy-029irg41/build
Build type: native build
Project name: SciPy
Project version: 1.9.0rc1
C compiler for the host machine: ccache cc (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.5)")
C linker for the host machine: cc ld64 764

../../meson.build:1:0: ERROR: Unable to get clang pre-processor defines:
error: invalid argument '-std=gnu++11' not allowed with 'C'


A full log can be found at /Users/mkoeppe/s/sage/scipy/.mesonpy-029irg41/build/meson-logs/meson-log.txt
Traceback (most recent call last):
  File "/Users/mkoeppe/Library/Python/3.8/lib/python/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/Users/mkoeppe/Library/Python/3.8/lib/python/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/mkoeppe/Library/Python/3.8/lib/python/site-packages/pep517/in_process/_in_process.py", line 314, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/private/var/folders/38/wnh4gf1552g_crsjnv2vmmww0000gp/T/build-env-xm1fjpkc/lib/python3.8/site-packages/mesonpy/__init__.py", line 811, in build_sdist
    with _project(config_settings) as project:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/private/var/folders/38/wnh4gf1552g_crsjnv2vmmww0000gp/T/build-env-xm1fjpkc/lib/python3.8/site-packages/mesonpy/__init__.py", line 798, in _project
    with Project.with_temp_working_dir(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/private/var/folders/38/wnh4gf1552g_crsjnv2vmmww0000gp/T/build-env-xm1fjpkc/lib/python3.8/site-packages/mesonpy/__init__.py", line 493, in with_temp_working_dir
    yield cls(source_dir, tmpdir, build_dir)
  File "/private/var/folders/38/wnh4gf1552g_crsjnv2vmmww0000gp/T/build-env-xm1fjpkc/lib/python3.8/site-packages/mesonpy/__init__.py", line 418, in __init__
    self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
  File "/private/var/folders/38/wnh4gf1552g_crsjnv2vmmww0000gp/T/build-env-xm1fjpkc/lib/python3.8/site-packages/mesonpy/__init__.py", line 442, in _configure
    self._meson(
  File "/private/var/folders/38/wnh4gf1552g_crsjnv2vmmww0000gp/T/build-env-xm1fjpkc/lib/python3.8/site-packages/mesonpy/__init__.py", line 430, in _meson
    return self._proc('meson', *args)
  File "/private/var/folders/38/wnh4gf1552g_crsjnv2vmmww0000gp/T/build-env-xm1fjpkc/lib/python3.8/site-packages/mesonpy/__init__.py", line 426, in _proc
    subprocess.check_call(list(args))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/Users/mkoeppe/s/sage/scipy/.mesonpy-native-file.ini', '-Ddebug=false', '-Dstrip=true', '-Doptimization=2', '--prefix=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8', '/Users/mkoeppe/s/sage/scipy', '/Users/mkoeppe/s/sage/scipy/.mesonpy-029irg41/build']' returned non-zero exit status 1.

ERROR Backend subprocess exited when trying to invoke build_sdist
```

### Error message

```shell
../../meson.build:1:0: ERROR: Unable to get clang pre-processor defines:
error: invalid argument '-std=gnu++11' not allowed with 'C'
```

### SciPy/NumPy/Python version information

1.9.0rc1

**Comment by rgommers** [comment] 2022-07-04 09:41
> The new build system of scipy 1.9.0rc1 breaks on macOS when the time-tested setting of `CXX="g++ -std=gnu++11"` is in use.

Thanks for the report @mkoeppe. This is surprising, and I agree that it'd be nice if this didn't break. That said, you should not have to pass `-std=gnu++11`, as (a) the SciPy build already does its own selection of C++ standard needed and we may need `c++14` already, and (b) in case you would have to set this option, the correct and more reliable way for doing this with Meson is to pass a command-line option like `-Dcpp_std=c++11` (see https://mesonbuild.com/Builtin-options.html#compiler-options)

I don't understand exactly how a C++ flag ends up in C flags though. I can't find anything in the docs or the issue tracker about this. My guess is this:
- You need a matching set of C and C++ compilers,
- If you _only_ set `CXX` to `g++` and don't set `CC`, then on macOS you could get a mix of `clang` and `g++` - which is bad,
- Meson tries to prevent this and tries to select a matching C compiler,
- And because you added an unwanted flag, this ends up being `gcc -std=gnu++11`

That said, even if I add `CC` I can reproduce this:
```
% CC='clang' CXX='clang++ -std=c++11' python -m build --no-isolation --skip-dependency-check

* Building sdist...
+ meson setup --native-file=/Users/rgommers/code/scipy/.mesonpy-native-file.ini -Ddebug=false -Dstrip=true -Doptimization=2 --prefix=/Users/rgommers/mambaforge/envs/scipy-dev /Users/rgommers/code/scipy /Users/rgommers/code/scipy/.mesonpy-sj7ksjir/build
The Meson build system
Version: 0.63.0.rc2
Source dir: /Users/rgommers/code/scipy
Build dir: /Users/rgommers/code/scipy/.mesonpy-sj7ksjir/build
Build type: native build
Project name: SciPy
Project version: 1.10.0.dev0
C compiler for the host machine: clang (clang 11.1.0 "clang version 11.1.0")
C linker for the host machine: clang ld64 609

../../meson.build:1:0: ERROR: Unable to get clang pre-processor defines:
error: invalid argument '-std=c++11' not allowed with 'C'
```

@eli-schwartz can you perhaps enlighten us about what is going on here?

**Comment by rgommers** [comment] 2022-07-05 16:06
What is happening here can be boiled down to:
```
% clang++ -std=c++11 -E -dM - < /dev/null
error: invalid argument '-std=c++11' not allowed with 'C'
```

So the confusing message about `C` is coming from Clang itself. I threw this in the debugger, and within Meson:
- this is actually coming from `_get_clang_compiler_defines`,
- called on line 533 `defines = _get_clang_compiler_defines(compiler)`,
- called from `detect_cpp_compiler`. 

Everything is in order there, the `compiler` variable contains `['clang++', '-std=c++11']` and we're inside the C++ compiler detection.

The remaining question to me is whether we can improve the error message. @eli-schwartz is `compiler` ever allowed to contain flags, so the variable `compiler` can have length >1? If not, checking that and explicitly erroring out is easy. If it is okay, then whether something works or not completely depends on whether `<FLAG>` happens to work in `clang++ <FLAG> -E -dM - < /dev/null`

**Comment by mkoeppe** [comment] 2022-07-05 17:42
Thanks for tracking this down. I think setting the `CXX` variable like this is quite common, for example autoconf sets it this way in https://github.com/autotools-mirror/autoconf/blob/master/lib/autoconf/c.m4#L2779; but I agree that with a clear error message users could just adjust their variable settings.

**Comment by eli-schwartz** [comment] 2022-07-05 18:49
> The remaining question to me is whether we can improve the error message. @eli-schwartz is `compiler` ever allowed to contain flags, so the variable `compiler` can have length >1? If not, checking that and explicitly erroring out is easy. If it is okay, then whether something works or not completely depends on whether `<FLAG>` happens to work in `clang++ <FLAG> -E -dM - < /dev/null`

The obvious, common one is `CC='ccache clang'`. Of course that's easily detected.

In fact, the question "is it allowed to have length >1" is a really good question, which leads into the question of "so what exactly is a compiler, anyway?" and turns out to have a fantastic answer. "It's complicated." :p 

One less common "compiler" turns out to be `CC='gcc -specs /usr/lib/musl/lib/musl-gcc.specs'`; the -specs option is always accepted and actually modifies how the compiler driver itself works (you can also think of it as "gcc has a default specs file which you can override on the command line before passing any other options").

So... is `CC='clang++ -std=c++11'` something that should be called "a compiler"? Apparently clang itself disagrees, it says that -std=c++11 is a compiler option which is not necessarily valid at any given location. Perhaps -std is a CXXFLAGS then, rather than a CXX? :thinking: 



> I think setting the `CXX` variable like this is quite common, for example autoconf sets it this way

It's not clear to me that:
- autoconf is the best place to be drawing examples from on general principle
- something autoconf does ***deep*** inside its own compiler detection code is a good proof that end users do it too at parts of the compilation process that come *before* compiler detection

**Comment by eli-schwartz** [comment] 2022-07-05 19:02
I did however discover that g++ issues a warning for the same command line (-std and all). 

```
$ g++ -std=c++11 -E -dM - < /dev/null
cc1: warning: command-line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
#define __SSP_STRONG__ 3
#define __DBL_MIN_EXP__ (-1021)
#define __UINT_LEAST16_MAX__ 0xffff
[...]
```

Of course, "-" is not a file detected as any particular language (it's stdin!) so it does make a certain amount of sense that it thinks it is trying to compile a C source instead of a C++ one. It's not supposed to matter.

Passing -xc++ here helps, but _get_clang_compiler_defines doesn't know which language it's looking for. It could be refactored and language-mapped to do so, I suppose...  I still think the proper answer is that this isn't really a compiler, and you might be able to get away with it for -std but I wouldn't want to more generically rely on it.

**Comment by rgommers** [comment] 2022-07-05 19:14
Thanks for that detailed answer @eli-schwartz. So I guess the outcome is "no, not easy to emit a better error message from within the bowels of Meson compiler detection machinery". So let's close this issue and leave it at that.

**Closed by rgommers** 2022-07-05 19:14 UTC
Labels: Build issues, Meson

**Comment by eli-schwartz** [comment] 2022-07-05 19:31
Well, I should say that currently it's basically as clear as mud what the compiler detection machinery does to produce the results it does.

After any failing setup, Meson always says "A full log can be found at `<builddir>/meson-logs/meson-log.txt`" and the expectation is that you want to actually look in there to figure out what happened. Which means in turn that we have a duty to, well, actually log useful stuff there.

We actually have a framework for stuff like `compiler.compiles()`, the sanity check code uses a similar logging approach.

The compiler detection code uses a bunch of Popen with no logging, which means doing forensics *requires* stepping into the Meson source code, and that much should be fixed. This has caused problems for me in the past at least once, I really should fix it and maybe now I actually will. ;)

... also `unable to foo. \n <stderr>` is not quite so explanatory as `unable to foo.\n Stderr: <stderr>`

What I don't think is practical is to analyze those flags and provide a targeted error message saying "oh yeah, these flags should be passed in CXXFLAGS instead of CXX".

**Comment by mkoeppe** [comment] 2022-07-05 19:33
> The compiler detection code uses a bunch of Popen with no logging, which means doing forensics _requires_ stepping into the Meson source code, and that much should be fixed.

+1
