### ISSUE TITLE
domain of argument of scipy.interpolate.RectSphereBivariateSpline(u, v, r, s=0.0, pole_continuity=False, pole_values=None, pole_exact=False, pole_flat=False)

### ISSUE THREAD

**Issue by yaofuzhou** [scipy/scipy#12965] opened 2020-10-18 19:43 UTC
Hi,

Just realized that I am restating the already reported issue
[https://github.com/scipy/scipy/issues/9704](https://github.com/scipy/scipy/issues/9704)

In the documentation of 
domain of argument of scipy.interpolate.RectSphereBivariateSpline(u, v, r, s=0.0, pole_continuity=False, pole_values=None, pole_exact=False, pole_flat=False)
on page
[https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectSphereBivariateSpline.html](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectSphereBivariateSpline.html)
it states that the domain of the 2nd argument v should be [-pi, pi). However, when invoking
RectSphereBivariateSpline.ev(self, theta, phi, dtheta=0, dphi=0)
documented on page
[https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectSphereBivariateSpline.ev.html](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectSphereBivariateSpline.ev.html)
the argument phi, which corresponds to the aforementioned v, requires the input within [0, 2pi) rather than [-pi, pi).

Would you double check the domains of the angular arguments and make sure that the functions and their documentations all have consistent domains for the angles? Thanks!

**Comment by rgommers** [comment] 2020-12-24 18:07
Thanks for the report @yaofuzhou! Let's close this as a duplicate of gh-9704.

**Closed by rgommers** 2020-12-24 18:07 UTC
Labels: Documentation, duplicate, scipy.interpolate
