### ISSUE TITLE
Inexpressive formulation in scipy.stats.linregress documentation

### ISSUE THREAD

**Issue by smoneck** [scipy/scipy#4173] opened 2014-11-20 15:38 UTC
Hi,

since I found NO way to contact anyone in a reasonable amount of time, I see no other way than a bug report:

The description in scipy.stats.linregress

    stderr : float
    Standard error of the estimate

is absolutely inexpressive -- what estimate? I propose changing this to

    Standard error of the estimate of the slope

or something...

Cheers
Stephan

**Comment by gncs** [comment] 2015-02-19 02:27
Thanks for reporting this @smoneck. I think the documentation is very misleading! We should fix this.

**Comment by rgommers** [comment] 2015-10-10 17:17
Closing this as a duplicate of gh-2962, which has a proposed formulation. Thanks all for your input.

**Closed by rgommers** 2015-10-10 17:17 UTC
Labels: Documentation, easy-fix, scipy.stats
