### ISSUE TITLE
Unable to install SciPy from sdist anymore

### ISSUE THREAD

**Issue by rpgdude** [scipy/scipy#10522] opened 2019-07-25 17:24 UTC
My project depends on SciPy and, due to an organizational requirement, all python dependencies must be installed from source distributions. This used to work fine until numpy-1.17rc was released, which drops support for python2.7. When I attempt to install SciPy-1.2.2 (which supports python2.7) from sdist, the setup scripts tried to pull down the latest numpy (1.17.0rc2), which raises the error below.

#### Reproducing code example:

```
(venv27) jmorawski@ptqadeva01:~$ pip install scipy==1.2.2 --no-binary :all:
```

#### Error message:

```
    ERROR: Command errored out with exit status 1:
     command: /home/user/jmorawski/venv27/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sMq2G4/scipy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sMq2G4/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-sMq2G4/scipy/
    Complete output (53 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sMq2G4/scipy/setup.py", line 492, in <module>
        setup_package()
      File "/tmp/pip-install-sMq2G4/scipy/setup.py", line 488, in setup_package
        setup(**metadata)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/home/fds/lang/python/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/fds/lang/python/lib64/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/user/jmorawski/venv27/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-oQ2nGU/numpy-1.17.0rc2/setup.py", line 31, in <module>

    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

#### Scipy/Numpy/Python version information:

```
Python 2.7.10 (default, Feb  3 2017, 15:51:12)
[GCC 4.4.4 20100726 (Red Hat 4.4.4-20)] on linux2
```

**Comment by rgommers** [comment] 2019-07-25 17:29
are you using the most recent version of `pip`? IIRC this is a `pip` bug

**Comment by rpgdude** [comment] 2019-07-25 17:30
> are you using the most recent version of `pip`? IIRC this is a `pip` bug

I am indeed using the latest pip (19.2.1)

**Comment by rgommers** [comment] 2019-07-25 17:33
and latest `setuptools`? this is a duplicate of https://github.com/numpy/numpy/issues/13911#issuecomment-511354070

**Comment by rgommers** [comment] 2019-07-25 17:35
There's a workaround in that NumPy issue, just do `pip install numpy` separately first. This is a `setuptools` or `pip` bug, and it's about the wrong NumPy being picked up so I'll close this as a duplicate of that NumPy issue.

If there's more to add, better to continue there. Thanks @rpgdude

**Closed by rgommers** 2019-07-25 17:35 UTC

**Comment by m4t101** [comment] 2021-10-15 20:42
I have the same problem with installing scipy, if someone could resolve it....

**Comment by rgommers** [comment] 2021-10-15 20:51
You don't have this problem, it has been resolved in recent releases (the `numpy` build dependency is correctly declared in `pyproject.toml`). Please open a new issue with enough details that we can help you @m4t101

**Comment by TigerSteel47** [comment] 2021-10-16 10:52
I'm using Mac with M1 silicon chip and the problem is the same:
![image](https://user-images.githubusercontent.com/92575563/137584502-a358b4f3-256c-4e50-8cf8-ed8f2afb1aaa.png)

**Comment by rgommers** [comment] 2021-10-16 11:30
You're trying to install SciPy 1.3.0 there, which is ancient. This bug is solved, you're making a simple user error there.

For M1, use conda-forge or the `arm64` nightly wheel at https://anaconda.org/scipy-wheels-nightly/. The releases on PyPI do not yet support M1.

Also a tip for future bug reports: rather than take a screenshot, please format the build log or traceback correctly: copy the text, and format it with triple backticks, so it looks like:
```
this
```

**Comment by TigerSteel47** [comment] 2021-10-16 13:52
Thanks for your reply. I will try it.

Tiger Steel
