### ISSUE TITLE
`scipy.fft` is available after `import scipy`

### ISSUE THREAD

**Issue by niboshi** [scipy/scipy#11264] opened 2019-12-23 06:34 UTC
After `import scipy`, most of the subpackages (like `linalg`) are not available unless explicitly imported ,but `scipy.fft` is available.

Background: https://github.com/cupy/cupy/issues/2843
Possibly related: https://github.com/scipy/scipy/pull/10290

#### Reproducing code example:

```
$ python -c 'import scipy; print(scipy.linalg)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'scipy' has no attribute 'linalg'
```

Same error would be expected:
```
$ python -c 'import scipy; print(scipy.fft)'
<module 'scipy.fft' from '/home/niboshi/.pyenv/versions/3.8.0/lib/python3.8/site-packages/scipy/fft/__init__.py'>
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.17.3 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment] 2019-12-23 10:01
We can't change this due to the last lines in `__init__.py` being:
```
    # This makes "from scipy import fft" return scipy.fft, not np.fft
    del fft
    from . import fft
```
You should not rely on it being available though, we'll likely change that once the deprecation is cleaned up.

**Comment by rgommers** [comment] 2019-12-23 10:01
I'll close this, since it's not a bug.

**Closed by rgommers** 2019-12-23 10:01 UTC
